### PR TITLE
Shaders: Clean up

### PR DESCRIPTION
**Pull request by WestLangley**
The shader chunks are now in the same order as in other materials.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
@Mugen87 This is a bit complicated... The primary goal was clear up -- to set a consistent order. I did that.

Afterwards, I had to change the `#if` statement to get the shader to work properly. This is a red flag that there is a design flaw.

The `#define` in the normal chunks are missing `USE_NORMAL`. That macro does not exist yet.

**Comment by WestLangley** [comment]
This can be merged.

**Comment by WestLangley** [comment]
My earlier comment was referring to the fact that the shaders assume normals exist in the geometry. Of course, they don't always.

That is a larger issue, and I do not think it should block this PR.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
