### PR TITLE
Add editorconfig-checker

### PR DESCRIPTION
**Pull request by munrocket**
**Motivation:**
Dat mr.doob style[tm] brings errors with soft spaces

**Solution:**
Add autocheck on each commit with editorconfig-checker

I tried to add checks in all repo, but autofix with `eclint fix '*'` works partially. So checks only for `src` folder for now and probably somebody will try [editorconfig-gradle-plugin](https://github.com/ec4j/editorconfig-gradle-plugin) in future for `editor` and `examples` folders.

Fixes in files committed anonymously (I hope).

### CODE REVIEW

**Comment by mrdoob** [comment]
I don't think all the libs we use in the repo should be forced to use my style.

**Comment by munrocket** [comment]
As I know currently we force all contributors with style guide that use tabs instead of spaces, something changed? We can contribute with prettier? :D

**Comment by looeee** [comment]
@munrocket I guess the point @mrdoob is making is that it's unusual to enforce a code style on third party scripts so this should skip the `editor/js/libs/` and  `examples/jsm/libs` folders. 

As for formatting with prettier, we can only dream haha.

**Comment by Mugen87** [comment]
Closing. However, feel free to improve the code style of non-external code 👍

**Pull request closed without merging**
