### PR TITLE
CurvePath, Path, Shape: Improve API

### PR DESCRIPTION
**Pull request by Mugen87**
This PR enhances the remaining derivations of `Curve` with `.copy()` and `.clone()` methods. That means `CurvePath`, `Path` and `Shape`.

It also harmonizes the constructor of `Shape`.

### CODE REVIEW

**Comment by Mugen87** [comment]
The last commit also removes the redundant method `Shape .extractAllPoints()` and renames `Path .fromPoints()` to `Path .setFromPoints()`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
BTW: Is there a special reason why `PathPrototype` has its own file 🤔 ? It's the only case in the library where constructor and prototype definition are separated.

**Comment by mrdoob** [comment]
> BTW: Is there a special reason why `PathPrototype` has its own file 🤔 ? It's the only case in the library where constructor and prototype definition of an entity (`Path`) are separated.

Not that I know 🤔

**Pull request merged**
