### PR TITLE
IBL Sheen Support

### PR DESCRIPTION
**Pull request by DanielSturk**
Continuation off of https://github.com/mrdoob/three.js/pull/16971

68dbcb30249be1001ef95374718a7c9f

This is based off Google's Filament https://google.github.io/filament/Filament.md.html#figure_materialclothsheen

It relies on a pre-computed lookup table, which is done in the same fashion as the RectAreaLights, see https://github.com/mrdoob/three.js/blob/b43aef8a3c30427c9decab6176ebafcfc06ba353/examples/jsm/lights/SheenIBLUniformsLib.js
(you can partially see it in the background, although the exposure is off in the screenshot)
The DG (dfg) lookup table is from here https://google.github.io/filament/Filament.md.html#figure_dfgclothlut
I extracted only the blue (sheen brdf) channel to save space, which is why it appear different in my demo scene

### CODE REVIEW

**Comment by elalish** [comment]
model-viewer uses only IBL for lighting, so we'll definitely need this to show a sheen effect.

**Comment by mrdoob** [comment]
@elalish I don't think @DanielSturk is working on this anymore. Do you think you can  continue the PR?

**Comment by elalish** [comment]
In my copious spare time... 😂

We should chat with @donmccurdy about supporting the new glTF extensions and make some kind of plan.

**Comment by Mugen87** [comment]
Implemented via #23069.

**Pull request closed without merging**
