### PR TITLE
Added projection logic for the new WebVRCamera

### PR DESCRIPTION
**Pull request by Samsy**
Objects were never projected using layers and webVRCamera.
This PR add the layer logic needed to work with ArrayCameras into the projectobject function.

Added also an example using layers and daydream to test it :  webvr_daydream_videostereo

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind removing the builds and the WebVRCamera code from this PR? Leave the example only.
I'm going to implement in a different way.

**Comment by mrdoob** [comment]
Implemented in a different way.

**Comment by jamieowen** [comment]
Hey,

I've hit the same problem using ArrayCamera and can't use layers also. Has the above fix been reverted now?
I have implemented the same small fix locally, was there any side effects with that method?

Cheers,

Jamie

**Comment by mrdoob** [comment]
I had to revert this change because there were some side effects: #11145

**Comment by mrdoob** [comment]
My current thinking is to implement `layers` into `Material` and do the check there.

**Comment by jamieowen** [comment]
Yeah i see..

Rather than handle the layer on the Material, would an option be to have onBeforeRender and onAfterRender be called twice on the object once with each Left and Right Cameras?  ( Or may be have new onArrayCameraRender functions )

The main projectObject() layer test would be done on ArrayCamera and then the two Left and Right layer test would be called within the ArrayCamera render loop.

The main situation I have is needing to update a custom material ( and actually 2 render targets ) with some parameters generated from left and right camera matrices.  So to be able to get access to those matrices directly from an object would be handy. Otherwise i have to create two of the same object.

**Comment by mrdoob** [comment]
> would an option be to have onBeforeRender and onAfterRender be called twice on the object once with each Left and Right Cameras?

Not sure that it's a good idea...

> The main situation I have is needing to update a custom material ( and actually 2 render targets ) with some parameters generated from left and right camera matrices. So to be able to get access to those matrices directly from an object would be handy. Otherwise i have to create two of the same object.

Do you mind detailing a little bit more your use case? Creating two objects doesn't sound like a bad idea to me.

**Comment by jamieowen** [comment]
Yeah thats cool to use two objects I can always restructure things differently.

Here's the logic / use case and thoughts on the onBeforeRender/etc.

Roughly like this :

```
class NewMesh extends Mesh{
		
	constructor(){
		
		super( null,null );
				
		this.leftEyeRTT = new WebGLRenderTarget();
		this.rightEyeRTT = new WebGLRenderTarget();
		
		// Scene with some objects to render to render targets.
		this.mixScene = new Scene(); 
		
		// Full screen quad
		this.geometry = ...
		
		// A custom material that renders the RTTs with some additional requirements for
		// camera dependant uniforms.
		this.material = new CustomMaterial( {
			uniforms: {
				mixTexture: { value: this.leftEyeRTT.texture },
				camMatrixRelatedProp: { value: new Vector2() }
			}
		} );
		
		
	}
		

	// Called before three.js render() on a custom first scene graph pass.
	preRender( scene, camera, renderer ){
		
		if( !camera.isArrayCamera ){ // No VR.
			
			renderer.render( this.mixScene, camera, this.leftEyeRTT );							
			this.material.uniforms.mixTexture.value = this.leftEyeRTT.texture
			this.material.uniforms.camMatrixRelatedProp.value = // generate for camera, etc...		
			
		}else{ // Yes VR
			
			renderer.render( this.mixScene, camera.cameras[0], this.leftEyeRTT );
			renderer.render( this.mixScene, camera.cameras[1], this.rightEyeRTT );
	
			// The uniforms cannot be set here as we don't know when we are about to draw with left or right cameras.
			
			// I think that it looks like mesh.onBeforeRender() is best place to set
			// uniforms in a one class setup but when they are camera dependent
			// there is no onBeforeRender VR equivalent. ( like onBeforeLeftEye, onBeforeRightEye )
			// ( Which kind of makes sense from an API point of view )
			
			// So you are sent down the two object route...
			
		}	
	}
```

Also, I think the WebVRCamera only updates camera matrices during the camera.onBeforeRender event.  So during any preRender stage that uses them, wouldn't they be a frame behind? ( Without calling camera.onBeforeRender manually )
[https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L1100]()
[https://github.com/mrdoob/three.js/blob/master/examples/js/vr/WebVRCamera.js#L66]()

And, more of a user related thing; if you were tempted to use the onBeforeRender() of a mesh in VR mode to render to a render texture using the renderer you would be breaking the state of the gl context which from what i understand is the main performance benefit of not switching materials/etc during the left/right render process.

May be there should be a separate onPreRender stage on an object3d that isn't so nested in the render process so it can't be abused!?

**Pull request closed without merging**
