### PR TITLE
Check the user agent for Edge browser.

### PR DESCRIPTION
**Pull request by Mathieu-Pasco-Breillot**
If so use a different element from the DOMParser because the children element does not exists.
PHPStorm has fixed indentation, according to JSHint

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like your editor changed the code formatting of the file. Do you mind rendering that?

**Comment by Mathieu-Pasco-Breillot** [comment]
I can't prevent it unfortunately, it's JSLint inside PHPStorm who make my code formatting like this.
Where can I find the right code formatting rules ?

I will edit the file to fit yours anyway :)

**Comment by Mathieu-Pasco-Breillot** [comment]
I tried fixing what I broke but there is still some changes that I can't prevent to change :/
Is that okay this way ?
It seems there is some wrong indentation, right ?
I hope this ok for you to merge it like this !

**Comment by mrdoob** [comment]
How about just using `childNodes` in all browsers?

**Comment by WestLangley** [comment]
>Where can I find the right code formatting rules ?

[Mr.doob's-Code-Style™](https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style™).

**Comment by Mathieu-Pasco-Breillot** [comment]
> How about just using childNodes in all browsers?

Sure we could, should I do it ?

**Comment by mrdoob** [comment]
> Sure we could, should I do it ?

Yes please 😊

**Pull request closed without merging**
