### PR TITLE
Clock pause & resume

### PR DESCRIPTION
**Pull request by NumbuhFour**
Small feature, stops updating `elapsedTime` and returns 0 to `getDelta` then resets the compare time upon resuming.

### CODE REVIEW

**Comment by looeee** [comment]
Just FYI I updated the clocks docs yesterday, you should make changes to the updated files (pull the upstream version before making changes).

**Comment by fordhurley** [comment]
It seems confusing to me that Clock would now have `paused` and `running` properties, and they mean completely different things. In fact, couldn't you just toggle the `running` property to pause/resume the clock?

**Comment by fad4470** [comment]
Setting `running` to false would effectively pause it, but you would have to update `oldTime` when you unpause, otherwise `elapsedTime` will have increased as though it were never paused.

But I kinda agree, having two vars named similarly is a little confusing.

Also rebased onto dev for the docs update.

**Comment by fordhurley** [comment]
I don't think that's true about `elapsedTime` being overestimated after unpausing when using `running` as is. As I understand it, calls to `getDelta()` will return 0 if `!running` and not increment `elapsedTime`. Am I reading the code right?

**Comment by fad4470** [comment]
You're right that it doesn't increment while not running, but once `running` is set back to true, `elapsedTime` will be incremented by the difference between `now` and `oldTime`. Since `oldTime` hasn't been updated, `elapsedTime` will be incremented by all the duration of the pause.

In theory, you could update `oldTime` just before setting `running = true` and have a fully functional pause, but the solution loses elegance.

With that in mind I removed some unused variables I think I forgot to remove, whoopsie.

**Comment by fordhurley** [comment]
Ah, I see the issue now! I still think having these two variables (paused and running) is asking for confusion. 

> In theory, you could update oldTime just before setting running = true and have a fully functional pause, but the solution loses elegance.

This sounds like the way to go to me. The Clock object has `start` and `stop` methods. It only needs a `resume` added to get the needed functionality. The `running` property is already there for the purposes of pausing.

**Comment by Mugen87** [comment]
> I still think having these two variables (paused and running) is asking for confusion.

Agreed.

**Pull request closed without merging**
