### PR TITLE
Finishing Manual::getting started - Arabic documentation

### PR DESCRIPTION
**Pull request by hassanrwx**
included pages:
- FAQ page
- Useful links page

updates:
- list mapping

### CODE REVIEW

**Comment by Mugen87** [comment]
Sidenote: Documentation pages which are not yet translated to arabic produces an ugly 404 page. Wouldn't it make sense to define the entire doc pages in the `ar` section and just point to the English counterparts if no translation is available? I think the project does the same in context of the Chinese translation.

**Comment by mrdoob** [comment]
I think I would make the ugly 404 nicer instead. Not sure if it's possible... 🤔

**Comment by mrdoob** [comment]
Thanks!

**Comment by hassanMuhamad** [comment]
It would be nicer if the 404 page shows a message indicating that the page is not translated to the selected language at the current time, information about the requested resource are available in the English version of the documentation. :leftwards_arrow_with_hook:

**Pull request merged**
