### PR TITLE
WebGPURenderer: Support for multiple render targets

### PR DESCRIPTION
**Pull request by aardgoose**
First attempt at getting multiple render targets working in WebGPU/Nodes using WebGLMultipleRenderTargets, lots of cleanup work required if this looks like the right direction. Probably cleaner to use renderTargets.textures[] though, rather than special cases for multiple targets.

In the nodes material the returned `outputStruct( outputColor1, outputColor2....)` writes to the attached textures. 

Example from webgl2 ported and working (you need to move the mouse around to get the first render. related to another async problem I have a patch for).

### CODE REVIEW

**Comment by sunag** [comment]
Very good, I just think that we can use `NodeMaterial.outputNode` instead of a new material:

```js
const material = new NodeMaterial();
material.outputNode = outputStruct( [ diffuseNode, normalNode ] );
```

So users also use GBuffer to create masks for post processing preserving the mainly material, without having to create other render-pass.

```js
import { materialOutput } = 'three/nodes'

const standardMaterial = new MeshStandardNodeMaterial();
standardMaterial.outputNode = outputStruct( [ materialOutput, maskNode ] );
```

And for Deferred Shading internally approach as:

```js
material.outputNode = outputStruct( [ materialPosition, materialDiffuse, materialNormal, ... ] );
```

--

I will create `materialOutput` I think it can help for this design.

**Comment by aardgoose** [comment]
Using material.outputNode to avoid hacking nodeMaterial internals, ( that was only intended as a workaround).

**Comment by aardgoose** [comment]
@sunag 

Updated to handle antialiasing. Do you want this reworked to handle all RTT cases with the same path, that is a textures array, and avoid all the special casing of Array.isArray()?  This would agree with the approach taken in #26427.

**Comment by sunag** [comment]
Do you want this reworked to handle all RTT cases with the same path, that is a textures array, and avoid all the special casing of Array.isArray()?

Sounds good for me 👍

**Comment by sunag** [comment]
@aardgoose What would be missing here? It would be very good if we could merge this PR in this `r156`.

**Comment by Mugen87** [comment]
>  and we will need to rename WebGLMultipleRenderTargets to MultipleRenderTargets soon too

Maybe we should consider to #26427 before doing this. If @mrdoob approves the general direction of the PR, we don't need a `MultipleRenderTargets` class.

**Pull request merged**
