### PR TITLE
Update Fileloader's judgment to http code.

### PR DESCRIPTION
**Pull request by budblack**
When we use customers http request header such as `Range: 0-` leading http server response resoures without `chunk` mode. Server would response http code not 200 but 206.

### CODE REVIEW

**Comment by mrdoob** [comment]
How about `this.status === 200 || this.status === 206`?

**Comment by budblack** [comment]
That ok, I just took a trick in my project. `this.status === 200 || this.status === 206` is correct  : )

**Comment by mrdoob** [comment]
I'm reading [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206) and I fear this may have side effects on content with correct range in the header though. As in, dispatching on load on a file that has not been fully loaded yet.

**Comment by budblack** [comment]
I'v read it. Yes, your worry is not unnecessary.

Server response http code 206 because client asked a `range of data` with http request header `Range: bytes=[startOffset]-[stopOffset]`.
Also, in http response header there is a header named `Content-Range`, showed is the file been full loaded.

__ we'd better do not merge this request Immediately. It's not rigorous. __

As well, problem is, when browser request a file without Request Header `Range: bytes=0-`, and if the server support `gzip` Content-Encoding way, the Http Response will be transfer with `Transfer-Encoding: chunked` Header, and will not give `Content-Length`(because client would judge the transfer end with a special transfer chunk). So, browser(Fileloader) do not know how large the file is before the transfer done. And there is no way to achieve a progress bar.

I captured the TCP package of my download tool (Free Download Manager). You know, download tools always know how large the file is when a task begin. FDM requested url with Header `Range: bytes=0-`, at first. Then the server respond the Full File(because FDM asked startOffset 0 and no stopOffset).

In the other hand, we can also do not change existing logic in Fileloader to file download process. But send a HEAD Http Request (but not each server support HEAD request) which contain Header `Range` before send GET Http Request, to sniff the file length. You know, Fileloader is not a simple XMLHttpRequest, it is a higher packaged module, like a Download Manager, and it has responsibility to provide informations. 

Or send a GET request with `Range:bytes=0-1` to just sniff it's length.

**Comment by Mugen87** [comment]
Let's stick with `200` return code.

**Pull request closed without merging**
