### PR TITLE
seamless computeTangents() for SphereGeometry

### PR DESCRIPTION
**Pull request by makc**
The issue was reported on discord a day ago, generic computeTangents() called on SphereGeometry creates a seam. An implementation that is aware of SphereGeometry geometry could easily fix it:
Screen Shot 2021-06-09 at 2 13 38
https://jsfiddle.net/1xucLyq8/ (current sphere at the bottom, fixed sphere at the top)

### CODE REVIEW

**Comment by WestLangley** [comment]
This implementation will produce an incorrect result at the north and south poles. You will need special-handling there.

You can use `vertexTangentsHelper` to visualize what you are doing. Use a low-poly sphere for testing.

**Comment by makc** [comment]
@WestLangley there is no correct result at the poles, see https://en.wikipedia.org/wiki/Hairy_ball_theorem

**Comment by makc** [comment]
...actually, I just did what you suggested, and it turns out the south(?) pole still has seams as before:
Screen Shot 2021-06-09 at 13 29 45
Screen Shot 2021-06-09 at 13 29 57
https://jsfiddle.net/vz3r7p1w/

I guess it is not exactly a pole numerically :S there must be some 1e-15 leftovers in the normal

**Comment by WestLangley** [comment]
>there is no correct result at the poles

For the purpose of _rendering_ there is.

**Comment by makc** [comment]
> For the purpose of rendering there is.

yes, if you want to render the seams, I guess

**Comment by makc** [comment]
gonna close this since you find it controversial and this south pole issue would mean going even more into that direction, so unlikely to be accepted. let them eat ~~cake~~seams  ¯\\\_(ツ)\_/¯

**Comment by WestLangley** [comment]
@makc I think your suggestion is a good one. You just have to fix the side seam and leave the poles as-is.

**Comment by makc** [comment]
> Here is your demo with tiny holes at the poles: https://jsfiddle.net/h3wrsm4L/1/

@WestLangley yes, you are right, those thin triangles create a problem any way. The only way to get rid of them is to comment .normalize() out:
Screen Shot 2021-06-12 at 23 05 14

**Comment by WestLangley** [comment]
Computed tangents _at_ the poles should be identical to computed tangents _near_ the poles. (I believe they currently are, but you can verify.)

So only the side seam tangents are incorrect in the current implementation.

An analytical solution similar to your proposal would be nice.

**Pull request closed without merging**
