### PR TITLE
WebGPU: Replace dat.gui to flow ui

### PR DESCRIPTION
**Pull request by sunag**
**Description**

I am working in an integration of `flow` (node graph editor) for `Three.js`,  during this process I am thinking about include the flow GUI in examples. I think that this is more focused on three.js needs and code styles.

I started in `WebGPU` for now.

[webgpu_lights_selective](https://raw.githack.com/sunag/three.js/dev-flow-ui/examples/index.html?q=webgpu#webgpu_lights_selective)

[webgpu_compute](https://raw.githack.com/sunag/three.js/dev-flow-ui/examples/index.html?q=webgpu#webgpu_compute)

### flow ui ###

https://github.com/sunag/flow

This contribution is funded by [Google via Igalia](https://igalia.com).

### CODE REVIEW

**Comment by donmccurdy** [comment]
> Soon I will add support to nodes too

Is there an example or screenshot you can share of what Flow's node-based usage looks like? Sorry if that was included in the WebGPU examples, I don't have a way to view those at the moment.

One thing I'd note is that any GUI we're using throughout the three.js site should support mobile devices and touch events. dat.gui was "just okay" in that regard; Tweakpane has better mobile support. It seems like Flow doesn't yet, is that planned?

**Comment by georgealways** [comment]
@donmccurdy hey! so I did make an effort to make this new library feel good on a phone. Widgets become larger automatically with a (pointer: coarse) media query. You should be able to touch-scroll a long GUI without moving a slider and vice versa. It also uses the native HTML color input just to make life simpler.

The pixi.js filter demo is a pretty good mobile stress test: https://lil-gui-pixi.georgealways.com/tools/demo/

Haven't tested on anything rigorously outside iOS, but would love the help!

**Comment by mrdoob** [comment]
I think I'd go with lil-gui as the replacement of dat.gui and flow ui as the material node editor.

@georgealways would you be up for doing a PR with the hot swap of the examples?

**Comment by georgealways** [comment]
@mrdoob happy to! I should be able to take care of that over the weekend.

**Comment by sunag** [comment]
@donmccurdy Hmm.... It should work on mobile I think

https://raw.githack.com/sunag/flow/master/examples/index.html

Anyway @georgealways did a great work in lil.gui for this reason technically I will be satisfied replacement in examples :)

**Comment by sunag** [comment]
@donmccurdy I make a cleanup of the flow ui to turn it public, for this reason I am reviewing some items before publish.

You can try use here: ( WIP  )
https://raw.githack.com/sunag/flow/master/examples/nodes.html

image

My internal project is a bit different

Flow new UI and `OffscreenCanvas` experiments for arrows
image

Flow editor  with `goldenlayout` and others panels created
image

**Comment by sunag** [comment]
I will close for now and publish other PR for node-graph editor soon.

**Comment by WestLangley** [comment]
@WestLangley said

>@georgealways Nice. Maybe add "title text color" to lil-gui to be backwards-compatible with dat.gui. :-)

@georgealways Oh, actually, I was thinking about the _folder_ text color. Can you add that, too?

**Comment by georgealways** [comment]
@WestLangley I don't really see why not. I added one for the _panel_ called `--title-text-color` for parity with `--title-background-color`. Should we keep track of this over in the lil-gui repo?

**Comment by WestLangley** [comment]
@georgealways Thanks, I saw that change. I am trying to replicate the CSS mods I implemented with dat.gui. I'll post further requests -- if there are any -- on your repo site, but so far it looks good!  :-)

**Pull request closed without merging**
