### PR TITLE
FBXLoader refactor parseAnimation and remove unused entities from return object

### PR DESCRIPTION
**Pull request by looeee**
Previously animations keys were being created by looping over the frames and creating one key for each frame, even if there was no change to the model between the frames. 

With this change, keys are checked against the key from the previous frame and skipped if the position, rotation and scale are all identical. 

Also:
* clarified and expanded  `parseAnimations` comments
* minor refactoring: created `getFrameRate`, renamed  `parseAnimationNode` -> `parseAnimationCurveNode`
* added a utility function `arraysAreEqual` for checking the keys `pos`, `rot` and `scl` arrays against each other.

### CODE REVIEW

**Comment by mrdoob** [comment]
> With this change, keys are checked against the key from the previous frame and skipped if the position, rotation and scale are all identical.

Hmm... Are you keeping the first and last identical ones though? Otherwise I can see this breaking animations. Say..

```js
0, 0.5, 1, 1, 1, 0.5, 0
```

If you removed the repeated `1`s, would it become this?

```js
0, 0.5, 1, 0.75, 0.5, 0.25, 0
```

**Comment by looeee** [comment]
Hmm... yeah, you are correct. Damn 😆 

I tried implementing a check that only removes chains of 3 or more identical keys - so in your example

> 0, 0.5, 1, 1, 1, 0.5, 0

becomes

> 0, 0.5, 1, 1, 0.5, 0

but testing it on a few files it seems like no keyframes are being removed now, so the exporters are probably already performing this optimisation.

**Comment by looeee** [comment]
OK, so this is just another refactoring PR now. 

I've removed the `try...catch` from the `addAnimations` method since I don't think it ever gets called - it looks like it may have been added due to a buggy exporter at some point, but so far I haven't come across any models that trigger it. If it's an issue we can add it back in later though.

**Comment by mrdoob** [comment]
Refactorings are good! 👌

Going back to the keyframe removal thing... Don't you think it's a bit of micro-optimisation? I don't think it saves much CPU-wise but it adds code that could bring potential bugs...?

**Comment by looeee** [comment]
Yeah perhaps - although the difference in some cases was from 100 keyframes to 2 keyframes. 

Actually what I'm trying to do here is make non-baked animations work, and looks like I'm going to have to redo the whole `addAnimations` function for that. 

For a cube translated 100 units on x over 100 frames
Non-baked animation: one keyframe at frame 0 with x = 0, one at frame 99 with x = 100.
Baked animation at one key per frame: 100 keyframes each moving the cube one unit along x.

For the three.js animation system the unbaked version should be fine, but currently the time for each frame is calculated at ` frame / animations.fps`, that is, the frame number divided by the frames per second of the current take. This means that only animations baked at one keyframe per frame work correctly. For the unbaked animation the output is currently:

KF0:  cube at position 0
KF1: cube at position 100
KF2 - KF99: cube at position 0

Since there is no data for KF2 - KF99 the cube is set at it's original position for those.

**Comment by mrdoob** [comment]
I see I see.

**Comment by mrdoob** [comment]
Wops! Conflicts 😇

**Comment by looeee** [comment]
Fixed fixed! 🙂

**Comment by looeee** [comment]
Added some more refactoring here - 

* renamed `stacks` to `takes` - I think the name take is more obvious and familiar to people, even though each take is stored between a stack and a layer in the FBX file (seems like these are not widely supported anyway, only Motion builder seems to export multiple takes, and I can't find anythings that exports multiple layers). 
* simplified the return object of the `parseAnimation` function since there were a lot of unused and repeated entries. Now it looks like:

```js
{
    takes: // animations takes will becomes object.animations[0], object.animations[1] etc
    fps: // global fps for all takes
}
```

**Comment by mrdoob** [comment]
Hmm... Do you mind splitting the PR in two?  One for the refactoring and another one for the duplicate keyframe stripping. I think I need more time to understand the issue. I feel like removing keyframes is not the right solution.

**Comment by looeee** [comment]
Oh, I'm sorry, perhaps I wasn't clear above - I'm not stripping any keyframes here anymore. This is just refactoring, the animations returned after this PR is merged will be identical.

**Comment by mrdoob** [comment]
Oh. Looks good then 😇

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
