### PR TITLE
Examples: Improved webgl_framebuffer_texture.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

Made `webgl_framebuffer_texture` a bit more interesting with a [gosper curve](https://en.wikipedia.org/wiki/Gosper_curve).

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Would probably be nice to move the gosper curve code to a class in the `jsm` folder though?

**Comment by Mugen87** [comment]
Yes. Was not sure about your preference so I embedded the code first 😅 .

**Pull request merged**
