### PR TITLE
change name of _Math to MathUtils

### PR DESCRIPTION
**Pull request by GGAlanSmithee**
As proposed by @bhouston in #9399, this changes the name of `_Math` to `MathUtils`. Not sure if this is something you want @mrdoob but since it was a very quick fix, I figured I might as well send a PR.

This change is only internal, and the class is still exported as `THREE.Math`. ES6 users can do `import {Math as MathUtils} from 'three'` to avoid name collisions.

All examples (that were working before) seem to be working still, which is to be expexted since the build still exports `Math`.

A couple of notes:
- I did not change the name of the file, it is still `Math.js`, should I change it?
- The test in `test/unit/unittests_three-math.html` are not working since the file `build/three-math.js` does not exist. This is true for the dev branch as well though. Is this file generated using the python build pipe or is the test obsolete?

### CODE REVIEW

**Comment by bhouston** [comment]
> The test in test/unit/unittests_three-math.html are not working since the file build/three-math.js does not exist. This is true for the dev branch as well though. Is this file generated using the python build pipe or is the test obsolete?

It should just use three.js now rather than three-math.js because we have this awesome module systme.  No need for custom pre-built subsets of ThreeJS.  ES modules handle that all automatically. :)

**Comment by donmccurdy** [comment]
Wondering if we should consider this again, with more of the codebase and examples using ES modules. Users will otherwise have to alias `Math as _Math` themselves in imports.

See https://github.com/mrdoob/three.js/pull/15592.

**Comment by mrdoob** [comment]
@donmccurdy sounds good 👍

**Comment by donmccurdy** [comment]
Didn't realize there was already an `examples/js/utils/MathUtils` file containing `setQuaternionFromProperEuler` (50 LOC). Do we still want to make the change? We could rename that version QuaternionUtils I suppose..

**Comment by donmccurdy** [comment]
Well if we want it, here it is 😅 https://github.com/mrdoob/three.js/compare/dev...donmccurdy:rename-math-mathutils

**Comment by Mugen87** [comment]
Closing. I think renaming `_Math` to `MathUtils` is a good idea. To simplify things, I would move `setQuaternionFromProperEuler` to `_Math`.

@mrdoob It shouldn't be too much work to make this change. It's more or less a search/replace operation with a few manual changes (e.g. in `utils/modularize.js`, TS files, docs ).

**Comment by mrdoob** [comment]
@Mugen87 Ok, lets do it 👌

**Pull request closed without merging**
