### PR TITLE
Tests: ignore css3d_youtube.

### PR DESCRIPTION
**Pull request by munrocket**
- css3d_youtube in exception list

### CODE REVIEW

**Comment by mrdoob** [comment]
Do we need two folders? `screenshots` and `thumbnails`?

**Comment by mrdoob** [comment]
I think you have included too many changes in a single PR.
The thumbnails change may block all the other changes.

**Comment by munrocket** [comment]
Yes you right, better not to touch it without big reason because it's fragile. I am just fix css3d_youtube and generated some thumbnails.

**Comment by munrocket** [comment]
BeginFrame is simpler, but need proper testing and not so fast as manual RAF control.

**Comment by Mugen87** [comment]
> I am just fix css3d_youtube and generated some thumbnails.

Are you sure this is correct? The PR still contains many changes...

**Review by Mugen87 — APPROVED** [review]

**Comment by munrocket** [comment]
Ok, I am splited to 3 PRs.
Nvm.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
