### PR TITLE
TransformControls normalized gizmo scale between different cameras.

### PR DESCRIPTION
**Pull request by arodic**
Normalized TransformControls gizmo scale with various camera types and parameters.

Added orthographic camera to TransformControls example.

There is still some magic number trickery in there to normalize gizmo scale between perspective and orthographic camera and to maintain the gizmo size when respective camera fov changes.

https://raw.githack.com/io-gui/three.js/transformControls/gizmoScale/examples/misc_controls_transform.html

### CODE REVIEW

**Comment by WestLangley** [comment]
@aroc Good job. You are on the right track for the orthographic case.

For the perspective case, I expect you need to compute the visible height of the frustum at the given distance: See [this SO answer](https://stackoverflow.com/questions/15331358/three-js-get-object-size-with-respect-to-camera-and-object-position-on-screen/15331885#15331885).

I assume the goal is to make the size of the gizmo independent of camera distance, `zoom`, `fov`, and orthographic frustum height.

**Comment by arodic** [comment]
> I assume the goal is to make the size of the gizmo independent of camera distance, zoom, fov, and orthographic frustum height.

Yes @WestLangley exactly. But another goal is to make the gizmo appear the same size when toggling between `OrthographicCamera` and `PerspectiveCamera`.

I used very similar formula to your SO answer except instead of `2 * Math.tan( vFOV / 2 )` I used `1.9 * Math.tan( vFOV / 2 )` and then I maxed that value with the magic number `7`.

The reason I used `1.9` instead of `2` is to make the gizmo in perspective view slightly smaller to compensate  for the fact that its geometry is almost always extending towards the camera and appears visibly larger due to the perspective distortion.  I found that `1.9` makes the gizmo appear more similar in fov above `10`.

As the `fov` goes higher up, the perspective distortion kicks in even further, blowing up the gizmo even more. `1.9` helps with that but eventually as `fov` approaches `180`, the gizmo would blow up into infinity. That is why I maxed it out at `7`, which corresponds roughly to `fov=145`. It makes the gizmo somewhat usable even at extreme `fov` values.

See the new example and use "C" key to toggle between cameras and "V" key to test with random `fov` values for perspective and random `zoom/top/bottom/left/right` values for orthographic.

https://raw.githack.com/io-gui/three.js/transformControls/gizmoScale/examples/misc_controls_transform.html

**Comment by WestLangley** [comment]
>as fov approaches 180

`fov` should never exceed 100, and is typically less than 50 to prevent peripheral distortion.

Given the complexity of the equation, and the fact that what you are computing is not an "eye distance", I would write it like so, using whatever magic numbers you want:
```js
if ( this.camera.isOrthographicCamera ) {
	
	var factor = ( this.camera.top - this.camera.bottom ) / this.camera.zoom;

} else {
	
	var factor = this.worldPosition.distanceTo( this.cameraPosition ) * Math.min( 2 * Math.tan( Math.PI * this.camera.fov / 360 ), 7 );

}

handle.scale.set( 1, 1, 1 ).multiplyScalar( this.size * factor / 7 );
```

You still need to address setting '.zoom' on the perspective camera. Look at the formula for `getEffectiveFOV()`. If you don't want to deal with it, then at least make a mental note of it. :-)

**Comment by arodic** [comment]
Oh I didn't realize `PerspectiveCamera` has `zoom` property. Will add.

**Comment by WestLangley** [comment]
You need to multiply it out.

Using your magic numbers, the answer should look like this:

```js
var factor = this.worldPosition.distanceTo( this.cameraPosition ) * Math.min( 1.9 * Math.tan( Math.PI * this.camera.fov / 360 ) / this.camera.zoom, 7 );
```
Please verify it works.

**Comment by arodic** [comment]
> Please verify it works.

the results appear to be exactly the same as with `getEffectiveFOV()`.

**Comment by WestLangley** [comment]
@Mugen87 I have helped the OP with the math. It looks OK to me.

The new code needs proper formatting. I am not sure if you expect the users to do that, or if the devs handle it.

Also, the near plane is too small.

**Comment by mrdoob** [comment]
> The new code needs proper formatting. I am not sure if you expect the users to do that, or if the devs handle it.

I'll clean it up 👌

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@WestLangley any other changes? https://github.com/mrdoob/three.js/commit/46b53c918bec18d5e1b96aed1923219ba2aa48d0

**Comment by WestLangley** [comment]
@mrdoob 

>Also, the near plane is too small.

And the controls should probably be constrained in both distance and zoom.

@arodic 

You're welcome.

**Pull request merged**
