### PR TITLE
THREE.Triangle: .getPlane() needs a Plane as a target

### PR DESCRIPTION
**Pull request by ikrong**
THREE.Triangle: .getPlane() target should be a Plane

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks!

The /en and /zh docs need to be corrected too, if you would like to do that.
```html
[page:Plane target] — the result will be copied into this Plane.<br /><br />
```

**Comment by ikrong** [comment]
> Thanks!
> 
> The /en and /zh docs need to be corrected too, if you would like to do that.
> 
> ```
> [page:Plane target] — the result will be copied into this Plane.<br /><br />
> ```

I have read this part of the document and do not need to corrected it.

**Comment by WestLangley** [comment]
Change `[page:Vector3 target]` to `[page:Plane target]`.

**Comment by ikrong** [comment]
> Change `[page:Vector3 target]` to `[page:Plane target]`.

My bad, I have corrected those docs.

**Comment by Mugen87** [comment]
While you're at it^^: The TS file also needs this fix:

https://github.com/mrdoob/three.js/blob/a6b2e376644ab156368bfa6cc549d124db048e69/src/math/Triangle.d.ts#L32

**Comment by ikrong** [comment]
> While you're at it^^: The TS file also needs this fix:
> 
> https://github.com/mrdoob/three.js/blob/a6b2e376644ab156368bfa6cc549d124db048e69/src/math/Triangle.d.ts#L32

Thx, I have fixed it.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
