### PR TITLE
Examples: Make event handling more robust in scene comparison demo.

### LINKED ISSUE #19066: doesn't get a proper value on the multi scene sample
##### Description of the problem

In the sample scene named Multiple Scenes Comparison, I encountered the error below.
`Cannot read property '0' of undefined`

I found that `e.touches` becomes `undefined`.

```javascript
function slideMove( e ) {
  if ( ! clicked ) return false;
  sliderMoved = true;

  // e.touches is undefined
  sliderPos = e.pageX || e.touches[ 0 ].pageX;

  if ( sliderPos < 0 ) sliderPos = 0;
  if ( sliderPos > window.innerWidth ) sliderPos = window.innerWidth;
  slider.style.left = sliderPos - ( slider.offsetWidth / 2 ) + "px";
}
```

https://github.com/mrdoob/three.js/blob/master/examples/webgl_multiple_scenes_comparison.html

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by nphsu**
Fixed https://github.com/mrdoob/three.js/issues/19066

Deleted a param that is likely to cause an error in the specific situation.

### CODE REVIEW

**Comment by shunp** [comment]
it might be better to change like the below.

```
if (!e.touches) {
    sliderPos = e.pageX	
} else {
    sliderPos = e.pageX || e.touches[ 0 ].pageX;
}
```

**Comment by Mugen87** [comment]
Why not: 
```js
sliderPos = ( e.pageX === undefined ) ? e.touches[ 0 ].pageX : e.pageX;
```

**Comment by Mugen87** [comment]
For testing:

https://raw.githack.com/shunp/three.js/patch_multiple_scenes_comparison_slidemode/examples/webgl_multiple_scenes_comparison.html

**Comment by shunp** [comment]
@Mugen87 Thank you for your suggestion! 
That would be great!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
