### PR TITLE
Added Function getListObjectsInFrustum To Camera

### PR DESCRIPTION
**Pull request by titansoftime**
This function returns an array of meshes within the camera frustum.

### CODE REVIEW

**Comment by mrdoob** [comment]
I think I would name it `camera.getObjectsInView( scene )` and, as @WestLangley suggested, I would create a frustum inside that method instead (as closure)... Something like this:

```javascript
THREE.Camera.prototype.getListObjectsInFrustum = ( function( scene ){

	var frustum;

	return function () {

		var objects = [];

		if ( scene === undefined ) return objects;

		this.updateMatrix();
		this.updateMatrixWorld();
		this.matrixWorldInverse.getInverse( this.matrixWorld );

		if ( frustum === undefined ) frustum = new THREE.Frustum();

		frustum.setFromMatrix( new THREE.Matrix4().multiplyMatrices( this.projectionMatrix, this.matrixWorldInverse ) );

		scene.traverse( function( object ) {

			if ( object instanceof THREE.Mesh ) {

				if ( frustum.intersectsObject( object ) ) {

					objects.push( object );

				}

			}

		} );

		return objects;

	}

} )();
```

How does this sound?

**Comment by WestLangley** [comment]
What is the purpose of this method?

If you want to avoid animating objects that are not in view, then perform the frustum check before animating. Do not create an array of objects, when an array is not needed.

**Comment by mrdoob** [comment]
It's supposed to be like a helper. Do you mean having some sort of `Camera.isInView( object )`? If so, wouldn't be have to update the matrix/frustum for every call?

**Comment by titansoftime** [comment]
Interesting, I was under the impression that closures used like that are prone to gc issues. This was something that I read a long time ago and probably is no longer the case.

>> It's supposed to be like a helper. Do you mean having some sort of Camera.isInView( object )? If so, wouldn't be have to update the matrix/frustum for every call?

That was the issue I was presented when first attempting it that way.

So far this method has been working great for me. In large zones (scenes) I have gained quite noticeable performance increases.

**Comment by WestLangley** [comment]
I am trying to figure out how to help @titansoftime in an efficient manner...

> It's supposed to be like a helper.

A helper for what?

>  Do you mean having some sort of Camera.isInView( object )?

No. I do not think this this method should exist. It is too inefficient.

> If so, wouldn't be have to update the matrix/frustum for every call?

The matrix/frustum is updated every frame. There should be no need to update it again if we do this right.

> This would be ok with something like AnimationHandler.updateInFrustum()

Yes. That may be the answer. `AnimationHandler.updateInFrustum()`.

> but what if you only wanted to omit certain meshes?

We can cross that bridge when we get to it.

> I will update my code to reflect yours.

You would need to avoid `new Matrix4` by using a closure. But so far, I am not a fan of the method.

**Comment by mrdoob** [comment]
Something along the lines of this?

```javascript
// In THREE.AnimationHandler

updateInView: ( function () {

		var frustum, matrix;

		return function ( camera, deltaTimeMS ) {

			camera.updateMatrix();
			camera.updateMatrixWorld();
			camera.matrixWorldInverse.getInverse( camera.matrixWorld );

			if ( frustum === undefined ) frustum = new THREE.Frustum();
			if ( matrix === undefined ) matrix = new THREE.Matrix4();

			frustum.setFromMatrix( matrix.multiplyMatrices( camera.projectionMatrix, camera.matrixWorldInverse ) );

			for ( var i = 0; i < this.animations.length; i ++ ) {

				var object = ???

				if ( frustum.intersectsObject( object ) ) {

					this.animations[ i ].resetBlendWeights( );
					this.animations[ i ].update( deltaTimeMS );
					
				}

			}

		}

	} )()
```

**Comment by WestLangley** [comment]
@mrdoob 

1. I am not sure the frustum needs to be updated again. It has already been updated in the render loop -- except the first time, of course. Hmmm... what to do?

2. If an animation is not updated when the camera is not looking at it, then the next time the animation is in view and updated, it needs to "catch up" to the current time. If you want to use `deltaTime`, it cannot have the same value for all objects.

**Comment by titansoftime** [comment]
>> If an animation is not updated when the camera is not looking at it, then the next time the animation is in view and updated, it needs to "catch up" to the current time. If you want to use deltaTime, it cannot have the same value for all objects.

Good point. Although for my application (I can't speak for anyone else) this is ok. For example if I'm looking at a spinning windmill, look away and look back at it a moment later, I'm probably not going to notice that the animation started off right where I left it. To me the windmill will simply be spinning. Though I can see how this would be undesirable to some devs, especially if they are using non looped animations.

**Comment by mrdoob** [comment]
> 2. If an animation is not updated when the camera is not looking at it, then the next time the animation is in view and updated, it needs to "catch up" to the current time. If you want to use `deltaTime`, it cannot have the same value for all objects.

Yeah, I was never super happy with the `deltaTime` approach...

**Pull request closed without merging**
