### PR TITLE
InstancedSkinnedMesh

### PR DESCRIPTION
**Pull request by wizgrav**
Similar to InstancedMesh, along with an example, basically repeatedly updating bone matrices and calling setBonesAt(index) to fill a texture with all bone matrices for all instances.

Shader code uses gl_InstanceID and texelFetch so it works on WebGL2 only. It can be made backwards compatible with 1 more attribute(for the lack of gl_InstanceID on WebGL1) and uglier code both on js and glsl side. Should we start standardizing on WebGL2, at least for new features?

@mrdoob the usefulness of this is limited by our capability to fill the bone matrix texture. It would be amazing if we could have an (Instanced)AnimationMixer directly filling the bone texture with matrices with as less copying as possible. Then we can reach thousands of independently animated meshes on screen.

Example live here: [https://wizgrav.github.io/three.js/examples/webgl_instancing_skinning.html](https://wizgrav.github.io/three.js/examples/webgl_instancing_skinning.html)

### CODE REVIEW

**Comment by makc** [comment]
> do we really want to continue the creation of different mesh classes?

kinda relevant input from @mrdoob :

Screen Shot 2021-10-13 at 23 28 31

**Comment by wizgrav** [comment]
@makc unity treats it similarly to three in the sense that they have separate renderers(the equivalent of mesh for us) for static and skinned meshes. Instancing they do differently, you have to do minor additions to your shaders, personally I prefer the three approach which gives you direct access to the instancing attributes/textures. Still even in unity you have to set a flag on the material to enable instancing,

The code paths in the three renderer are pretty clean so as long as an object carries the isInstancedMesh and isSkinnedMesh and the appropriate structure for both (instanceMatrix, instanceColor, count, bindMatrix, skeleton, etc) things will just work. So I guess we could have a method of compositing properties of a generic object. So isPoints + isInstanced along with the structures for both should give us an InstancePoints mesh. And we could have several class with precomposited objects

**Comment by wizgrav** [comment]
@Mugen87 how about a single Drawable class with flags and setters to configure it on the fly? ie Drawable.isSkinned = true would setup the appropriate structures in conjuction with the rest of the configuration. Some flags would be mutually exclusive like isMesh and isPoints etc. IsInstanced would apply to all

**Comment by wizgrav** [comment]
Closing this to bring it back more comprehensive

**Comment by aiden-loroco** [comment]
@wizgrav - do you plan to resurrect this?

**Comment by Skarian** [comment]
@Mugen87 Hi, so awesome that its available in WebGPU but considering WebGPU is not in the mainstream as of yet to my knowledge, I think there would still be a lot of benefit to having a WebGL2 equivalent for the time being. @wizgrav 's solution looks pretty solid from what I can tell.

If there are other solutions I have not found yet please let me know :)

**Comment by CodyJasonBennett** [comment]
There's a way to do this in user-land like https://codesandbox.io/s/2yfgiu although it requires a hack for points rendering -- `object.isMesh = !object.isPoints`.


https://user-images.githubusercontent.com/23324155/216412225-180cd4bf-764e-4d6b-a768-a10d3c141f2b.mp4

**Comment by FarazzShaikh** [comment]
What would it take to have this in ThreeJS core? I'm willing to put time into a comprehensive PR if someone can point me in the right direction.

**Comment by trusktr** [comment]
@FarazzShaikh the API just needs to be clean and make lots of intuitive sense. Can't be a hodge podge like in some other engines. The functionality is already proven out above, but it is the way the classes and code are organized that make a difference.

So if you can come up with something clean, maybe it has higher chance to go in. No one may know exactly what that layout is though.

**Comment by Ctrlmonster** [comment]
Out of curiosity, what are the per instance animation setting capabilties in this PR?
I've been writing a high-level animation system sitting on top of three's that includes things like Blend Trees and Animation State Machines and for those to work with instances I would need to be able to:

- play different (and multiple) animation actions per instance
- set different times per instance
- set different action weights per instance
- set different action timeScales per instance

I might might be missing obvious technical challenges with doing that per instance, but without at least playing different actions per instance, the usability is quite limited.

**Pull request closed without merging**
