### PR TITLE
FBXLoader:  support morphtargets

### PR DESCRIPTION
**Pull request by looeee**
Partial support for morph targets ( blend shapes ) in the FBXLoader. 

Still to do:

* only morph positions is supported for now, no morph normals
* `material.morphtargets = true` needs to be set manually by the user
* animation is not supported (the user can manually set up animation of course, but animations in the loader will be ignored)
* ~~remove code duplication between `genGeo` and `genMorphGeo`~~

fbx_morph

### CODE REVIEW

**Comment by looeee** [comment]
Oops, I broke something when fixing conflicts. Don't merge yet!

**Comment by looeee** [comment]
OK, this should be good to go. I've split the monolithic `genGeo` function into `genGeo`, `getGeoInfo`, `genBuffers`, `genFace`.

Now `genBuffers` and `genFace` are reused when generating the morph target position attribute instead of duplicating the code.

**Comment by mrdoob** [comment]
Fixed a conflict. Should be good to go now?

**Comment by looeee** [comment]
Looks good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
