### PR TITLE
Scene: Introduce .dispose()

### LINKED ISSUE #15485: Scene memory managment is a bit strange for webvr use cases
##### Description of the problem

Most webvr experiences are one experience per site, but when you have a site with multiple webvr experiences you can have the case where you have on ThreeJS renderer (i.e. the WebVR renderer) and you just want to use different scenes with it (a new scene for a new webvr experiences).  This works but it ends up leaking memory because although you can dispose of the objects in the scene graph, the WebGLRenderer saves state for each scene/camera pair.  And it looks like calling dispose on WebGLRenderer makes the renderer invalid afterwards.

You could have one canvas already for WebVR, and then have a new WebGLRenderer for each WebVR experience and just use the same canvas/gl context for each, but there's a memory hit for this as well and you could have bugs where multiple renderers are trying to draw to the same context (i.e. the one who is actually presenting and then one that wasn't shut down correctly).  Using a singleton for the WebVR renderer is nice as it makes it a bit easier to see who is actually renderering.

##### Three.js version

- [x] Dev
- [ ] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixes #15485

### CODE REVIEW

**Comment by aardgoose** [comment]
Do you want to also dispose of the references to objects maintained in WebGLRenderLists, similarly keyed by scene.id and camera.id. 

Or should render lists be added to the WebGLRenderStates to avoid duplication of code etc even?

**Comment by Mugen87** [comment]
Let's just add an `onSceneDispose()` in `WebGLRenderLists`.

**Comment by joshpatt2** [comment]
Thanks for doing this!!!

**Comment by mrdoob** [comment]
Beautiful!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Does this make #12464 redundant?

**Comment by Mugen87** [comment]
Unfortunately no. `Scene.dispose()` is intended to dispose a complete scene object. For instance if an app wants to render a different scene than before, users can call this new method in order to clean up related data cached by `WebGLRenderer`.

#12464 tries to ensures that disposed materials and geometries are actually removed from memory. Calling `Scene.dispose()` would also solve this issue but it fails strange to dispose a scene if you are still going to use it. Because of this, I think we should resolve the conflicts in #12464 and then merge it.

**Pull request merged**
