### PR TITLE
Remove code deprecated for 10 releases

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: -

**Description**

Remove long-deprecated code.

### CODE REVIEW

**Comment by LeviPesin** [comment]
Seems like some examples break? 🤔

**Comment by Mugen87** [comment]
If you open the browser console, the error becomes evident:

> Uncaught SyntaxError: The requested module 'three' does not provide an export named 'SphereBufferGeometry'

`PointsHelper` needs an update: https://github.com/gkjohnson/three-bvh-csg/blob/70f80954e25a089d755afa6a79f9d47b60543eac/src/objects/PointsHelper.js#L14

**Comment by LeviPesin** [comment]
I think this PR should work now?

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/pull/26203#issuecomment-1579054671

**Pull request merged**
