### PR TITLE
.github folder enhancements for ISSUES, HELP and PRs

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
A big part of this PR is the addition of the `.github/ISSUE_TEMPLATE/config.yml` file which displays links to the forum and stackoverflow before a person has created an issue.

I've also removed the `Help` and `Bug` sections from the `contribution.md` file within the `.github` folder as people will have visually seen those links in their respective places, allowing us to separate out those concerns and keep the contribution guide about contributing.

The `.github/ISSUE_TEMPLATES/` folder has two templates. One for Bugs the other for features. I was thinking about adding adding an `Editor`, `examples` and `docs` template but decided to keep things generic for the time being. Your thoughts?

Their is a `.github/pull_request_template.md` file for PRs but I wasn't too sure how to flesh it out. Their is also the possibility to create multiple PR templates within a `.github/PULL_REQUEST_TEMPLATES/` folder should we choose to do so.

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please enable the `Issues` feature on your branch? That should make it easier to review the changes.

**Comment by DefinitelyMaybe** [comment]
What is the issues feature? is that part of git or is that github specific?

**Comment by Mugen87** [comment]
When you go in `Settings`, there should be a section `Features` that allows you to enable the issues tab in your project:

image

**Comment by DefinitelyMaybe** [comment]
done

**Comment by DefinitelyMaybe** [comment]
bump to @Mugen87 or other for review. missed r118, would be nice to get into r119.

**Comment by Mugen87** [comment]
I've tried to test the new templates on your branch but unfortunately I only see the current versions. Do you know how it's possible to preview them in your branch?

**Comment by DefinitelyMaybe** [comment]
Ah right, sorry, they only show up if their on the main branch of the git repo. my bad.

Hmm. I've thrown this PR into the dev branch of my fork. We can work from there.

**Comment by DefinitelyMaybe** [comment]
ok. [here's a link](https://github.com/DefinitelyMaybe/three.js/issues/new/choose) for viewing the create new issue page.
As for the Pull Request template, this:
```markdown
---
name: Pull Request
about: Helping Development of Three.js
title: ''
labels: ''
assignees: ''
---
```
showed up. I had thought it was scrapped off of the PR and the appropriate descriptors updated but unfortunately no. I'm going to simply remove it for the moment and we can add this kind of automation in later when someone feels like looking into it further.

**Comment by DefinitelyMaybe** [comment]
ah, lol, this PR need not be tied to any release of Three.js. @Mugen87 if the above looks all good to you, it's affects will take place as soon as its merged

**Comment by mrdoob** [comment]
Sorry for the delay @DefinitelyMaybe!
Do you mind resolving the conflicts?

**Comment by DefinitelyMaybe** [comment]
ah! will jump onto it this evening.

**Comment by DefinitelyMaybe** [comment]
@mrdoob , please see #20385

**Pull request closed without merging**
