### PR TITLE
remove unicode character from EllipseCurve.js

### PR DESCRIPTION
**Pull request by ngokevin**
My browser errored on this when I built three.js into a Webpack build.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by trusktr** [comment]
Woooo hoooo. This was a pain. The GitHub editor wasn't showing the character in order to remove it when I tried to PR

**Comment by trusktr** [comment]
How'd that even get in there?

**Comment by Mugen87** [comment]
That was my mistake :disappointed:. But i actually don't know how this happened til today.

**Pull request merged**
