### PR TITLE
Add static function `lerpFlat` to `Vector3`.

### PR DESCRIPTION
**Pull request by gonnavis**
Related issue: None.

**Description**

Add static function `lerpFlat` to `Vector3`.

I want to use it to solve some `tempVector3` conflict problems.
And it should improve overall performance by reduce conversions.

And align with `Quaternion.slerpFlat` https://threejs.org/docs/?q=quater#api/en/math/Quaternion.slerpFlat

### CODE REVIEW

**Comment by WestLangley** [comment]
>I want to use it to solve some tempVector3 conflict problems.

Can you please provide details of your use case?

**Comment by gonnavis** [comment]
When using global `tempVector3`s for performance reason ( prevent `new` ), it's very prone to get into `tempVector3` conflict situations.

For example:
```
tempVector3a = new THREE.Vector3();
tempVector3b = new THREE.Vector3();

function fa(arrA, arrB, t) {
  tempVector3a.fromArray(arrA);
  tempVector3b.fromArray(arrB);
  tempVector3a.lerp(tempVector3b, t);
  return tempVector3a.toArray();
}

function fb(arrA, t) { // arrA = [1,1,1]
  tempVector3a.fromArray(arrA);
  const arrB = fa([1,1,1], [3,3,3], 0.5); // result [2,2,2]
  tempVector3b.fromArray(arrB);
  tempVector3a.lerp(tempVector3b, t); // should lerp [1,1,1] [2,2,2] too, but not.
  return tempVector3a.toArray();
}

console.log( fa([1,1,1], [2,2,2], 0.5) );
console.log( fb([1,1,1], 0.5) );
  
// => [1.5, 1.5, 1.5] // correct
// => [2, 2, 2] // wrong
```

But if we have `Vector3.lerpFlat`, we can avoid this problem:
```
function fa(arrA, arrB, t) {
  THREE.Vector3.lerpFlat(arrA,0,arrA,0,arrB,0,t);
  return arrA;
}

function fb(arrA, t) { // arrA = 
  const arrB = fa([1,1,1], [3,3,3], 0.5);
  THREE.Vector3.lerpFlat(arrA,0,arrA,0,arrB,0,t);
  return arrA;
}

console.log( fa([1,1,1], [2,2,2], 0.5) );
console.log( fb([1,1,1], 0.5) );
  
// => [1.5, 1.5, 1.5] // correct
// => [1.5, 1.5, 1.5] // correct
```

**Comment by WestLangley** [comment]
I would consider that to be a bug in your code.

**Comment by gonnavis** [comment]
For this simple example, can fix it by just swap these two lines
```
  tempVector3a.fromArray(arrA);
  const arrB = fa([1,1,1], [3,3,3], 0.5); // result [2,2,2]
```
But it's very hard to find solutions when nested many functions or doing recursion.

Anyway, is it worth adding `lerpFlat` even just to avoid conversion?
`lerp` is frequently used in animation processing, and animation datas often flat arrays.

**Comment by Mugen87** [comment]
`Quaternion.slerpFlat()` was added because it was a useful addition in context of `PropertyMixer`. But just because one math class provides a certain method, it does not mean we have to add it to other classes. At least at the moment I do not think it's appropriate to add `Vector3.lerpFlat()` to the API.

**Pull request closed without merging**
