### PR TITLE
OBJExporter: Avoid duplicate v,vt,vn records in obj file

### PR DESCRIPTION
**Pull request by Silvaire**
Inspired by THREE.Geometry.mergeVertices

### CODE REVIEW

**Comment by WestLangley** [comment]
I see... You are not really "merging" duplicate attributes. You are removing duplicate attributes in the output file.

The success of this approach is highly-dependent on the value of `precision` and the scale of the geometry.

**Comment by donmccurdy** [comment]
It seems risky for the exporter to do this automatically: a mesh that renders correctly in three.js may be exported incorrectly, and by the time you've imported it back through OBJLoader the problem is hard to diagnose. Safer for an exporter to write exactly what it is given.

How about making this a new method:

```js
BufferGeometryUtils.mergeVertices( geometry, precision = 4 )
```

That would allow use with imported models, and with other exporters like GLTFExporter.

**Comment by WestLangley** [comment]
This issue is not about merging vertices. It is only about removing duplicate attributes in the `.obj` file.

I think removal of duplicates is reasonable. I'm just not confident in the approach.

**Comment by donmccurdy** [comment]
I guess my reaction would be to make it about merging vertices, instead. 😅 Assuming the duplicates are already present in the BufferGeometry, and not being introduced in the export process?

**Comment by WestLangley** [comment]
@donmccurdy To me, this PR is only about the duplicate entries in the output file. See [this](http://threejs.org/examples/misc_exporter_obj.html) example and click on "both".

Whether removing the duplicates is worth pursuing is a separate issue.

**Comment by donmccurdy** [comment]
Ok, sounds good. 👍

In that case, perhaps include an `options` argument to OBJExporter, as GLTFExporter does:

```js
exporter.parse( input, callback, {
  mergeDuplicateVertices: true,
  precision: 4
});
```

No strong opinion on what the option(s) should be called.

**Comment by mrdoob** [comment]
I agree with @WestLangley. I think this over complicates the exporter and it can get in the way of adding more features.

I think it would be better to have a javascript function that "post-processes" the output.

**Comment by mrdoob** [comment]
I agree with @WestLangley. I think this would over-complicate the exporter and get in the way of adding new features.

I think it would be better to separate this into a function and/or npm module that optimises obj files instead...

**Comment by mrdoob** [comment]
I would think differently if the obj format had less caveats 😇

**Comment by mrdoob** [comment]
Another approach is what @WestLangley is suggesting. Some sort of `bufferGeometry.optimiseAttributes()`...

**Comment by WestLangley** [comment]
>Another approach is what @WestLangley is suggesting.
>>Some sort of bufferGeometry.optimiseAttributes()...

I don't think I suggested that... This is only about removing repeated attributes in the `.obj` file.

>I think it would be better to separate this into a function and/or npm module that optimises obj files instead.

I think so, too.

**Comment by mrdoob** [comment]
> I don't think I suggested that... This is only about removing repeated attributes in the `.obj` file.

Sorry about that. I referred to the idea of moving the code to a different part.

I can see the complications of parsing a obj file and trying to remove duplicate points and how it can be easier to achieve the same thing before exporting instead.

Something like this:

```js
var clone = THREE.BufferGeometryUtils.optimiseAttributes( buffergeometry.clone() );
var output = exporter.parse( clone );
```

**Comment by WestLangley** [comment]
This issue is about removing duplicate attributes in the `.obj` file.

@mrdoob A `PlaneBufferGeometry` has many normals, and they are all the same. The `.obj` file only needs one entry to represent that normal.

How do you claim to be able to optimize the `.obj` file in that case by optimizing the geometry instead?

**Comment by mrdoob** [comment]
Actually, I've given a little bit more thought to the problem. Yeah, doing a function that "post processes" the resulting string is much easier as it's just a matter of finding duplicated lines and changing indices.

**Comment by donmccurdy** [comment]
Oh, I'd misunderstood the optimization being done here. Thanks thanks. FWIW I use https://github.com/jonnenauha/obj-simplify for this purpose.

**Comment by Silvaire** [comment]
Hi all,

Yes, this is basically just a .obj file size optimisation. I agree that it's highly dependent on the geometry scale as is, and as such, a possibility would be to only remove _exact_ duplicate lines. I'm sure in most cases, the values outputted by the `BufferGeometry` are indeed exactly the same, at least when it's coming from a `BufferGeometry.fromGeometry` call.

In any case, not repeating exact duplicate lines is risk-free, and in the cases I've seen the file size gain (and even probably processing power since 3D softwares will not create a dedicated vertex for each duplicate line) is substantial (for a complex mesh, most vertices are used in multiple triangles). In that sense, I think it makes sense to have it as part of the default behavior.

Having a precision parameter doing some potentially dangerous roundups is indeed a different question, an shouldn't be part of the default as in my PR.

**Comment by WestLangley** [comment]
I think the title of this PR has contributed to a lot of confusion here. Changing it...

**Comment by mrdoob** [comment]
@Silvaire Yeah, we understand your rationale. Sounds like you don't want to understand ours though.

**Comment by Silvaire** [comment]
Yeah, apparently not :)

I really understood the points of not "getting in the way of adding new features" or the fact that the OBJ format has indeed a lot of caveats, not to mention again the fact that as you said, using rounded comparisons might create nasty side-effects.

But again, if we're talking removing exact duplicates records, I don't see how there could be any side effects, and still result in massive file size reduction in many cases.

Or maybe there's just really something I don't understand about OBJs, and then I can just close this PR :D

**Comment by Silvaire** [comment]
Ok, sorry, I just realised I also missed one of your comments @mrdoob. Namely:

> doing a function that "post processes" the resulting string is much easier as it's just a matter of finding duplicated lines and changing indices.

which sounds good.

Should this function be part of Three.js (and in the OBJExporter file) though, or do you consider it to be out-of-scope?

**Comment by mrdoob** [comment]
> Should this function be part of Three.js (and in the OBJExporter file) though, or do you consider it to be out-of-scope?

Yeah, I think it can be part of `OBJExporter`.

**Pull request closed without merging**
