### PR TITLE
LensFlarePlugin: Refactoring and Improvements

### PR DESCRIPTION
**Pull request by Mugen87**
This PR implements the feedback of @mrdoob in #8394

### CODE REVIEW

**Comment by mrdoob** [comment]
Much nicer! Thanks! 😊

**Comment by RemusMar** [comment]
Good work.
But now the console is bloated with this message:

THREE.WebGLRenderer: Uniform "f" is now "1f". three.min.js:613:34

**Comment by Mugen87** [comment]
See this [commit](https://github.com/mrdoob/three.js/commit/9d4b774df1dcd780103a885a09262a9ad55d084c). More refactoring is waiting for us :wink:

**Comment by mrdoob** [comment]
Oh! I'm sorry, I shouldn't have pushed those builds.
Just pushed new/fixed builds.

**Comment by RemusMar** [comment]
> Oh! I'm sorry, I shouldn't have pushed those builds.
> Just pushed new/fixed builds. 

The current one runs perfect on Firefox 45.
well done.
 :+1:

**Pull request merged**
