### PR TITLE
Examples: Refactor hilbert curves.

### PR DESCRIPTION
**Pull request by Mugen87**
Removes the files `hilbert2D` and `hilbert3D` and introduces `THREE.Hilbert` instead. Both functions are now defined in a single file and in the `THREE` namespace (which good for consistency and upcoming module support).

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Instead of the API proposed here,
```js
var vertices = THREE.Hilbert.generate3D( new THREE.Vector3( 0, 0, 0 ), 200.0, 2, 0, 1, 2, 3, 4, 5, 6, 7 );
```
I suggest a simpler API:
```js
var vertices = THREE.Hilbert3D( new THREE.Vector3( 0, 0, 0 ), 200.0, 2, 0, 1, 2, 3, 4, 5, 6, 7 );
```
Similarly, `THREE.Hilbert2D`.

**Comment by mrdoob** [comment]
That sounds good to me. I would even say `new THREE.Hilbert3DLine()`.

**Comment by WestLangley** [comment]
> I would even say new THREE.Hilbert3DLine().

You mean, extending `THREE.Line`?

The common terminology is Hilbert Curve -- of a particular order. I would just go with `Hilbert3D`.

**Comment by Mugen87** [comment]
> I would even say new THREE.Hilbert3DLine().

I did not want to use `THREE.Hilbert3D` since this pattern is only consistent if `Hilbert3D` is a constructor. However, `THREE.Hilbert ` it's more similar to `THREE.Math`.  It provides a namespace with a bunch of functions. Similar to a class with static methods.

**Comment by WestLangley** [comment]
By that argument, I would prefer

```js
THREE.GeometryUtils.hilbert3D( ... )
```

**Comment by Mugen87** [comment]
Fair enough 👍

**Comment by WestLangley** [comment]
Yes, use this pattern:
```js
var vertices = THREE.GeometryUtils.hilbert3D( ... )
```

**Comment by mrdoob** [comment]
Yeah, that sounds good!

**Pull request merged**
