### PR TITLE
ShadowMap: Refactored repetitive code.

### PR DESCRIPTION
**Pull request by tschw**
Includes more robust handling of custom materials (see #7153).

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I think this broke `webgl_animation_skinning_morph`.

**Comment by tschw** [comment]
Fixed this one in #7237.

BTW: That example shows very quirky camera control and eventually reports a negative viewport size (unrelated to these changes).

**Comment by tschw** [comment]
Wow! You are merging faster than I can type... Thanks a lot for catching the bug!

**Comment by mrdoob** [comment]
Uh?

**Pull request merged**
