### PR TITLE
Src: Removed Object.defineProperty() calls.

### LINKED ISSUE #21284: `Object.defineProperty` in `THREE.Vector3` constructor causing a significant performance penalty
**Describe the bug**

I've noticed a significant performance drop in my application when I upgraded the THREE.JS version. Initially from `0.102.0` to `0.125.2`, but I've narrowed it down to a change from `0.119.1` to `0.120.0`. A single model step in my app (simulation) increased from ~10ms to ~50ms. 

I've used JS profiler and noticed that Vector3.clone() is at the top now:
Screenshot 2021-02-15 at 18 34 12

I'm using `THREE.Vector3` in the simulation part of the app, and since many vector operations are implemented in place, `.clone()` calls are very common. When I downgrade version to `0.119.1`, the clone operation isn't there anymore and the model step calculates 4 times faster.

I did a little investigation and replacing `Object.defineProperty( this, 'isVector3', { value: true } );` in `THREE.Vector3` constructor with `this.isVector3 = true;` fixes the issue.

**To Reproduce**, ***Live example***

* r125, slow clone: https://jsfiddle.net/9hrmuLxw/ (open console to see the result)
* r120, slow clone: https://jsfiddle.net/nb0uw1ay/ (open console to see the result)
* r119, fast clone: https://jsfiddle.net/p2bu1qte/ (open console to see the result)

On my machine, the difference is 5ms (r119) vs 45ms (r120, r125). 

I don't think it'd be useful here, but the app I'm working on: 
https://tectonic-explorer.concord.org/?preset=subduction

**Expected behavior**

No .clone performance drop.

**Screenshots**

THREE.JS version 0.119.1 vs 0.120.0:

Screenshot 2021-02-15 at 18 33 25

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome v88
 - Three.js version: r120.0 and newer, r119 is the last one that works fine

### PR DESCRIPTION
**Pull request by mrdoob**
Fixes: #21284

**Description**

@marcofugaro but... [as you said](https://github.com/mrdoob/three.js/issues/19986#issuecomment-775925132), [this test](https://github.com/mrdoob/three.js/blob/fade4fa03bae7da0cd9bc2f459fa96ee45568303/test/unit/src/core/Object3D.tests.js#L300-L304) will now fail?

~~And doing `Vector3.prototype.isVector3 = true` breaks tree shaking.~~

~~🤷‍♂️~~

### CODE REVIEW

**Comment by mrdoob** [comment]
```js
class Foo {
    isFoo = true
    constructor() {
      // ...
    }
}
```

Does that code add `isFoo` to the prototype?

**Comment by marcofugaro** [comment]
@mrdoob do not despair! I am here to help.

Just replace these lines

https://github.com/mrdoob/three.js/blob/1e210ac8f57d43dd2039b962394c181ef5c25bdc/test/unit/src/core/Object3D.tests.js#L300-L304

with this

```js
assert.numEqual( obj.position.x, 1, 'x is equal' );
assert.numEqual( obj.position.y, 1.23, 'y is equal' );
assert.numEqual( obj.position.z, - 4.56, 'z is equal' );
```

And the tests are fixed. I tested this branch locally and there doesn't seem to be any other test that break.

**Comment by mrdoob** [comment]
@marcofugaro thanks!

**Comment by mrdoob** [comment]
It's still annoying that we can't just do `Vector3.prototype.isVector3 = true`.
Before all `Vector3`s would share a single boolean. Now we're creating a boolean per `Vector3` 😕

**Comment by DefinitelyMaybe** [comment]
I agree that's not optimal. I had thought that we'd be able to make use of static properties and methods. progress is slow.

**Comment by DefinitelyMaybe** [comment]
There is also doing: 

```javascript
class Box2 {

	isBox2 = true;

	constructor( min, max ) {

		this.min = ( min !== undefined ) ? min : new Vector2( + Infinity, + Infinity );
		this.max = ( max !== undefined ) ? max : new Vector2( - Infinity, - Infinity );

	}
```

i.e. moving items not dependent on constructor paras outside of the constructor

**Comment by mrdoob** [comment]
@DefinitelyMaybe https://github.com/mrdoob/three.js/issues/19986#issuecomment-775879928

**Comment by Mugen87** [comment]
> Before all Vector3s would share a single boolean. Now we're creating a boolean per Vector3 😕

We should be aware that iterating with a `for in` loop and then checking properties via `hasOwnProperty()` will produce a different (from my point of view unexpected) result now.

`r125`: https://jsfiddle.net/dstwvfg6/1/
`r126dev`: https://jsfiddle.net/gdj89m7t/

I wonder if the performance penalty mentioned in #21284 is not preferable compared to the change in behavior.

**Comment by mrdoob** [comment]
@marcofugaro Are you sure that `Vector3.prototype.isVector3 = true` breaks tree-shaking?

I just did a test and it seems like it works just fine: https://github.com/mrdoob/three.js/commit/f0ad404ceb8edd7b03492dbd97e6c644e786d201

I've also tried `Object.assign( Vector3.prototype, { isVector3: true } );` instead and that definitely breaks tree-shaking.

**Comment by DefinitelyMaybe** [comment]
question mark?

if tree-shaking is mostly surrounding `import`/`export`'s then neither 
`Vector3.prototype.isVector3 = true` or `Object.assign( Vector3.prototype, { isVector3: true } );`
should break tree-shaking, but one reportedly does above.

I'd still prefer not to go back to `Vector3.prototype.isVector3 = true`

I'd submit that keeping data related to an object inside of that object to be more beginner friendly than putting that same data somewhere within the file related to the object.

was the a verdict regarding static properties yet?
```javascript
class Object3D {

	static isObject3D = true
	// ...

}
```

**Comment by mrdoob** [comment]
> was the a verdict regarding static properties yet?

Static properties are not a substitute for `Vector3.prototype.isVector3 = true`.

**Comment by DefinitelyMaybe** [comment]
oops. I'd forgotten that discussion.

**Comment by DefinitelyMaybe** [comment]
quick question, why is `prototype` used?
couldn't you just do `Vector3.isVector3 = true` ?

**Comment by DefinitelyMaybe** [comment]
@mrdoob re: [earlier comment](https://github.com/mrdoob/three.js/pull/21285#issuecomment-779675627)

I changed Vector2.js to:
```javascript
class Vector2 {

	x;
	y;
	isVector2 = true;

	constructor( x = 0, y = 0 ) {
		this.x = x;
		this.y = y;
	}
```
and this was preserved within the three.module.js but not within the three.js

**Comment by marcofugaro** [comment]
> @marcofugaro Are you sure that Vector3.prototype.isVector3 = true breaks tree-shaking?

It breaks it only for **webpack** but not rollup unfortunately 🙈

I added webpack to the script `test-treeshake` in my branch here https://github.com/marcofugaro/three.js/commit/820c6253f3dc144e2297113d212ca5a5d52555bc.

I took `DodecahedronGeometry` as an example since it's not used anywhere else, unlike `Vector2` or `Vector3`.

After adding this line:


You can see it's present in the webpack bundle but not the rollup one:
| index.bundle.js | index-webpack.bundle.js |
|---------|--------|
|  | Screenshot 2021-02-17 at 12 53 18 |

I tested the webpack bundle before and after #21293 and it looks like the bundle size has gotten bigger:
| index-webpack.bundle.js before #21293 | index-webpack.bundle.js after #21293 |
|---------|--------|
| Screenshot 2021-02-17 at 12 54 21 | Screenshot 2021-02-17 at 12 54 31 |

I'd vote for #21293 to be reverted. In my opinion, doing `this.isVector3 = true` is fine since a boolean is just a boolean, it wouldn't take as much memory space as an object would, for example.

**Comment by Mugen87** [comment]
> I'd vote for #21293 to be reverted. In my opinion, doing this.isVector3 = true is fine since a boolean is just a boolean, it wouldn't take as much memory space as an object would, for example.

Sorry, but I don't vote to do that. Like mentioned the property iteration behavior is changed which can be very confusing and a breaking change for apps.

**Comment by mrdoob** [comment]
Agreed. I vote for reporting this as a bug/feature request to Webpack.

**Comment by mrdoob** [comment]
The `.is*` properties are supposed to be internal. Polluting the public API with them is ugly and confusing. Why some classes have them but not others?

**Comment by mrdoob** [comment]
Trivia: Rich Harris himself added them 🤓

**Comment by mrdoob** [comment]
Quick way to test if a module tree-shakes:

```sh
echo "import { Vector3 } from './src/math/Vector3.js';" | npx rollup -f es
```

**Comment by mrdoob** [comment]
> I vote for reporting this as a bug/feature request to Webpack.

Done: https://github.com/webpack/webpack/issues/12716

**Pull request merged**
