### PR TITLE
WebGLPrograms: Add missing ParameterNames

### PR DESCRIPTION
**Pull request by gero3**
This is continuation of #17552. This adds all missing parameters to the parameterNames Array.

### CODE REVIEW

**Comment by Mugen87** [comment]
> This is continuation of #17552.

So it's a replacement for #17552, right?

**Comment by gero3** [comment]
> > This is continuation of #17552.
> 
> So it's a replacement for #17552, correct?

I would prefer #17552 over this, but this indeed fixes the same problem.

> In essence, the entries in `parameterNames` should match the object properties of `parameters`, right (except `shaderID`)?
> 
> https://github.com/mrdoob/three.js/blob/a5c9edd6864bf7b0b0be4644c5388271f39f0d5d/src/renderers/webgl/WebGLPrograms.js#L143-L235

I believe so because parameters are used to create different shaders and different shaders are detected by parameterNames

**Comment by Mugen87** [comment]
Um, why not changing:
```js
for ( var i = 0; i < parameterNames.length; i ++ ) {

   array.push( parameters[ parameterNames[ i ] ] );

}
```
to
```js
Array.prototype.push.apply( array, Object.values( parameters ) );
```
In this way, `parameterNames` is not needed. Would it be a problem if `shaderID` is in the array?

**Comment by gero3** [comment]
It doesn't matter if shaderID is added. ShaderID will just be added twice in that array then. ([Line 245](https://github.com/mrdoob/three.js/blob/a5c9edd6864bf7b0b0be4644c5388271f39f0d5d/src/renderers/webgl/WebGLPrograms.js#L245))

It can be in a critical path, so we should check performance. Also [compability](https://github.com/mrdoob/three.js/blob/a5c9edd6864bf7b0b0be4644c5388271f39f0d5d/src/renderers/webgl/WebGLPrograms.js#L245) could be a problem if we expect internet explorer to still work.

**Comment by Mugen87** [comment]
> It doesn't matter if shaderID is added. ShaderID will just be added twice in that array then.

We could refactor the mentioned lines to the following in order to solve this problem:
```js
if ( parameters.shaderID === undefined )

    array.push( material.fragmentShader );
    array.push( material.vertexShader );

}
```
> It can be in a critical path, so we should check performance. Also compability could be a problem if we expect internet explorer to still work.

True. Unfortunately, IE does not support `Object.values()` 😞

**Comment by Mugen87** [comment]
With ES6 we could even write^^:
```js
array.push(  ...Object.values( parameters ) );
```

**Comment by Mugen87** [comment]
Anyway, I don't care which PR is going to be merged. Both are fine. My suggested refactoring can be done later, too.

**Comment by Mugen87** [comment]
@gero3 Can you please resolve the merge conflicts? I'd like to approve this change.

**Comment by gero3** [comment]
@Mugen87 The conflicts are resolved.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Merging this one in favor of #17552.

**Comment by Mugen87** [comment]
Updated builds: fcb84f52316f29649a86e236127b42e607e3399e

**Pull request merged**
