### PR TITLE
fix MorphBlendMesh setAnimationFps()

### PR DESCRIPTION
**Pull request by dgolovin-dev**
bugfix for: When setAnimationFPS then animation.duration is NaN.

### CODE REVIEW

**Comment by mrdoob** [comment]
What's the fix? As far as I can see you mainly renamed the variables...?
Also, try to target the `dev` branch instead.

**Comment by WestLangley** [comment]
@mrdoob `setAnimationFPS()` and `setAnimationDurstion()` refer to `animation.start`, which did not exist.

**Comment by mrdoob** [comment]
Oh, I see...

**Comment by mrdoob** [comment]
Merged into the `dev` branch.
Thanks!

**Pull request closed without merging**
