### PR TITLE
[MeshStandardMaterial] Documentation on metal/rough details.

### PR DESCRIPTION
**Pull request by donmccurdy**
Correcting information about which channels are used (not red/red), and filling in some details about Metallic-Roughness workflow.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Reference:

- [metallnessmap_fragment.glsl](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/metalnessmap_fragment.glsl#L7)
- [roughnessmap_fragment.glsl](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/roughnessmap_fragment.glsl#L8)

**Comment by WestLangley** [comment]
Thanks! Do you mind adding a similar correction for the `aoMap`, which uses the R-channel?

ref: https://github.com/mrdoob/three.js/issues/10691#issuecomment-276464725

**Comment by takahirox** [comment]
@donmccurdy Perhaps we should try to request to glTF specification team to change metal channel to blue for OcclusionRoughnessMetallic of UE4 compatibility?

**Comment by donmccurdy** [comment]
@WestLangley sure, done.

@takahirox 👍  https://github.com/KhronosGroup/glTF/issues/857

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
