### PR TITLE
Modularize more! :-)

### PR DESCRIPTION
**Pull request by Reggino**
- Modularize whatever is possible: the more, the better
- Properly handle references (imports) to other example files
- Enable multiple exports

More info and context: See #16400

### CODE REVIEW

**Comment by Mugen87** [comment]
Please notice there is also #16477, as an alternative. I've realized that testing the modules individually and adding TS declaration files is the secure way than provide "everything" as a module.

**Comment by Reggino** [comment]
I personally think this script should be part of the build/release steps. "Magic" is IMHO the only way to get and keep the large number of example files in sync.

Optionally the built files could be removed from the repo and generated during a release....

**Comment by donmccurdy** [comment]
Each ES module is going to need to be tested by someone, and that takes much more time than running the script to convert the files. It's that testing that we primarily need community help with, so I'd prefer to keep converting files incrementally until that process is complete.

Improving the conversion script to support features as needed sounds good, of course.

**Comment by Mugen87** [comment]
> It's that testing that we primarily need community help with, so I'd prefer to keep converting files incrementally until that process is complete.

Exactly! Doing the conversion blindly is easy but we have to ensure the modules do actually work.

**Comment by mrdoob** [comment]
Definitely agree with @donmccurdy and @Mugen87. We're not in a hurry, better to do thing step by step and keep things under control.

**Pull request closed without merging**
