### PR TITLE
Examples: Simplify webgl_modifier_subdivision and use modules.

### PR DESCRIPTION
**Pull request by Mugen87**
Removed some complicated elements and hacks (e.g. `createSomething()`) that made it hard to work with the example. The new version is more straightforward and also uses modules now.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev34/examples/webgl_modifier_subdivision.html

**Comment by WestLangley** [comment]
The existing version: https://threejs.org/examples/webgl_modifier_subdivision.html

Showing how it worked on different geometries was interesting, I thought...

If you still prefer to remove the additional example geometries, then perhaps `WaltHead` would be a more interesting one to use.

**Comment by Mugen87** [comment]
> If you still prefer to remove the additional example geometries, then perhaps WaltHead would be a more interesting one to use.

TBH, I'm not quite happy with the resulting workflow which is necessary when you want to illustrate the amount of vertices and faces. For this you have to load `WaltHead` with `BufferGeometryLoader`, convert it to `Geometry` and later convert it back to `BufferGeometry` for rendering (since we don't want to pass `Geometry` to the renderer anymore). Notice that `SubdivisonModifier` still returns `Geometry`.

I've once retrieved the feedback of a user that it's useful to visualize the amount of vertices/faces before and after the modification process.

**Comment by WestLangley** [comment]
But now the example uses Legacy `Geometry` only.

I think it is more helpful to show the workflow for `BufferGeometry`, since that is what loaders return.

Inline comments explaining the steps would also be nice, IMO.

**Comment by Mugen87** [comment]
I'm not feeling strong about this so I've changed to Walt model. Also added a comment that we can change the code if `SubdivisionModifier` eventually returns `BufferGeometry`.

**Comment by WestLangley** [comment]
I do see that it is very slow and unresponsive at level 4 on my machine. Maybe max at 3?

Anyway, thanks!

**Comment by Mugen87** [comment]
Yeah, three seems to be more safe.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
