### PR TITLE
MMD Cubic Bezier interpolation

### PR DESCRIPTION
**Pull request by takahirox**
Original MMD uses Cubic Bezier curves interpolation for bone and camera animation.

https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Cubic_B.C3.A9zier_curves

This PR enables Cubie Bezier curves interpolation for MMD in Three.js

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
We do have some Cubic Bezier code in core by the way...

https://github.com/mrdoob/three.js/blob/dev/src/extras/ShapeUtils.js#L692-L763

But it's likely that it'll get refactored eventually.

**Comment by takahirox** [comment]
Oops, I've missed that.
But let me keep my Cubic Bezier code in `MMDLoader` because
it's optimized for MMD with (x0, y0) = (0, 0), (x3, y3) = (1, 1).

**Comment by mrdoob** [comment]
Sounds good! 👍

**Pull request merged**
