### PR TITLE
WebGLRenderTarget: Add support for swapping textures

### PR DESCRIPTION
**Pull request by Oletus**
This can be used to save GPU memory or to avoid texture copy operations in situations where multiple textures need to be used as render targets but one shared depth/stencil buffer is enough.

The downside is that the WebGL implementation needs to validate the framebuffer again for completeness.

WebGLCubeRenderTarget returns Textures from this function, not CubeTextures.

### CODE REVIEW

**Comment by Oletus** [comment]
Thoughts on this @mrdoob @Mugen87 ? The API is a bit ugly since not just any Texture is suitable for passing in and because WebGLCubeRenderTarget doesn't use CubeTextures, but I'm quite sure that this is useful functionality to have.

**Comment by gkjohnson** [comment]
I recently ran into this again when trying to implement an effect that uses depth peeling. I wound up creating two unused color buffers just because I wanted to write to a depth texture. In my opinion it would be more intuitive to be able to replace the depth buffer of a WebGLRenderTarget especially considering a field already exists for setting the [depthTexture](https://threejs.org/docs/#api/en/renderers/WebGLRenderTarget.depthTexture). I think being able to change `depthTexture` or set it to a shared depth attachment would let you achieve the same effects.

I previously created #19447 about the current inability to update `depthTexture` after the first render and briefly outlined some thoughts an idea for enabling updating the depth / color attachments for devices that don't support depth textures here (https://github.com/mrdoob/three.js/pull/15490#issuecomment-604591891) that I think fit into the existing three.js patterns for updating fields.

It's been on my list to address it at some point but I'm definitely interested in your thoughts!

**Comment by Oletus** [comment]
@gkjohnson I think it's important that both depth textures and depth renderbuffers are supported. WEBGL_depth_texture is not quite universally supported, and depth renderbuffers can be more efficient than depth textures. If both could be swapped in and out of WebGLRenderTargets I think I'd be happy. Still a bit awkward to create extra framebuffer objects, but that's acceptable.

It would have one advantage over this: if a depth buffer could be kept attached to multiple FBOs, the WebGL implementation doesn't have to revalidate framebuffer completeness.

I'd like to hear what other maintainers think!

**Comment by gkjohnson** [comment]
> I think it's important that both depth textures and depth renderbuffers are supported. WEBGL_depth_texture is not quite universally supported, and depth renderbuffers can be more efficient than depth textures.

Yeah I definitely agree. #19447 was created to address the inability to swap depth textures which I think would make adding custom depth buffers easier. I referenced https://github.com/mrdoob/three.js/pull/15490#issuecomment-604591891 to show how adding a frame buffer API for depth might look, which I think is more what you're looking for.

**Comment by Oletus** [comment]
So what are the next steps on this? Do you think it would get traction if I proposed a patch adding a renderbuffer API, or is someone else planning to work on this? Or should this texture swapping API still be considered as well? The two are not mutually exclusive.

**Comment by gkjohnson** [comment]
As far as I'm aware no one is working on this -- I suggested the frame buffer API previously because I expected it fit the existing three.js patterns more closely and would be more agreeable but there wasn't any feedback from maintainers. I think it would be nice to get confirmation that this is something worth doing before putting the work in. Maybe @mrdoob or @Mugen87 have some thoughts?

**Comment by pailhead** [comment]
Since https://github.com/mrdoob/three.js/pull/15490 _is still open_ could you consider pinging the maintainers there?

**Pull request closed without merging**
