### PR TITLE
Fix binary GLTF export in Microsoft Edge

### PR DESCRIPTION
**Pull request by brianpeiris**
Steps to repro:

1. Open https://threejs.org/examples/#misc_exporter_gltf
2. Enable the "Binary" option
3. Click on "Export Scene1"

Previously, the export would fail in Microsoft Edge with an error in the console.

### CODE REVIEW

**Comment by takahirox** [comment]
Can you share the error message for the people who don't have Edge?

**Comment by brianpeiris** [comment]
Sure, the error is:

`Object doesn't support property or method 'toBlob'`

Since edge does not support the standard `canvas.toBlob`, but it has a prefixed, synchronous function called `canvas.msToBlob`.

**Comment by donmccurdy** [comment]
> Microsoft Edge msToBlob only supports PNG

Whoa, surprised by that. 😕 Is there a bug anywhere? Would've expected it to be documented on https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Browser_compatibility at least.

**Comment by brianpeiris** [comment]
Edge inherited `msToBlob` from Internet Explorer. Unlike `toBlob`, `msToBlob` does not let you choose a mime type. https://technet.microsoft.com/en-us/windows/hh771732(v=vs.60)

I can't find any sign that they are planning to implement `toBlob` properly. Their platform status item for it is just marked as "prefixed"
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/htmlcanvaselementtoblobmethod/?q=htmlcanvas

This uservoice ticket from 2016 has very little support and no response from the Edge team
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15107964-support-toblob-on-canvas

**Comment by mrdoob** [comment]
Should this be closed then?

**Comment by brianpeiris** [comment]
Sorry, I'll close for now and reopen when I'm ready.

**Pull request closed without merging**
