### PR TITLE
Introduce ExposureShader

### PR DESCRIPTION
**Pull request by WestLangley**
> This is an exposure-only pass. Useful for rendering HDR output to an archive EXR in working color space, for example.

As suggested in https://github.com/mrdoob/three.js/pull/26130#issuecomment-1562138017.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Hmm, actually... Wouldn't it make sense to do this also in the `OutputPass`?

**Comment by WestLangley** [comment]
@mrdoob Can you please explain what you are referring to?

**Comment by mrdoob** [comment]
Oh, actually... Never mind, I misunderstood.

**Comment by mrdoob** [comment]
No wait...

Wouldn't it be better to hide this for the developer in `OutputPass`?

Ideally the developer wouldn't have to have two different code paths (One for HDR and another for non-HDR).
They would just use `OutputPass`. And `OutputPass` would do toneMapping only in non-HDR displays.

**Comment by WestLangley** [comment]
This is separate from `OutputPass`, which is device-specific.

This is an exposure-only pass. Useful for rendering HDR output to an archive EXR in working color space, for example.

**Comment by mrdoob** [comment]
Ah okay... Makes sense.

I think I didn't understand the exact use case for this PR by reading the conversation #26130.

I'll update your PR description for clarity in case we have to look at this PR again in the future.

**Pull request merged**
