### PR TITLE
Add `setPolarAngle` and `setAzimuthalAngle` to OrbitControls.

### PR DESCRIPTION
**Pull request by msimpson**
Related pull request: #9005

**Description**

> Would `setPolarAngle` / `setAzimuthalAngle` methods be acceptable?
> 
> _Originally posted by @homerjam in https://github.com/mrdoob/three.js/issues/9005#issuecomment-804197073_

> @h0merjam I think these sound good 👍
> 
> _Originally posted by @mrdoob in https://github.com/mrdoob/three.js/issues/9005#issuecomment-804283908_

I suddenly need this, so here's a PR.

### CODE REVIEW

**Comment by msimpson** [comment]
- Added the methods to the `js` version of OrbitControls.
- Provided accompanying documentation.
- Synchronized my side to `mrdoob:dev`.

**Comment by WestLangley** [comment]
Can you please explain your use-case?

Note, these proposed methods will not work with `OrthographicCamera`.

Also, you should not be controlling the camera programmatically behind the back of `OrbitControls`. Do this:

```js
controls.enabled = false;
// ...do what you want with the camera directly
controls.enabled = true;
```

**Comment by msimpson** [comment]
@WestLangley 

Sure. I'm debouncing the `end` event of `OrbitControls` to implement a snapping movement, e.g.:

```
function onControlsStart() {
  
  clearTimeout( snapDampingRef );
  
}

function onControlsEnd() {

  snapDampingRef = setTimeout( () => {
    
    controls.setAzimuthalAngle( Math.round( controls.getAzimuthalAngle() / HALF_PI ) * HALF_PI );
    
  }, SNAP_DAMPING_DELAY );
  
}
```

Without `setAzimuthalAngle` I'd need to avoid `OrbitControls` and build a separate solution for consistent damping.

Genuinely, how do these methods fail under `OrthographicCamera` given internals like `rotateLeft` and `rotateUp`?

Is it the shortest path calculation assuming `Math.PI` and `2 * Math.PI`?

If so, I can externalize that logic.

**Comment by WestLangley** [comment]
Oh, sorry, I edited the misstatement in my post.

**Comment by msimpson** [comment]
@WestLangley 

I assume this is a philosophical issue, where `Controls` examples should provide no programmatic setters.

If that's the case, I'll just implement a purpose-specific solution for my usage and close this request.

Perhaps I should prototype a separate programmatic-only version of `OrbitControls`.

It seems to come up often enough for there to be an `OrbitRig` or something in `examples`.

Would that be a more acceptable solution in the future?

**Comment by WestLangley** [comment]
@msimpson It is true, such requests have come up a lot in the past. That is one reason `OrbitControls` is part of the examples -- so users can modify it to their liking.

>It seems to come up often enough for there to be an OrbitRig or something in examples.
>Would that be a more acceptable solution in the future?

I'm not sure of the answer to your question. I'll defer to @Mugen87 and/or @mrdoob. You may have to propose something more concrete to get a response.

**Comment by msimpson** [comment]
@WestLangley got it.

Closing this in light of the above discussion.

**Comment by homerjam** [comment]
@msimpson I ended up going with https://github.com/yomotsu/camera-controls for my use case which sounds the same as yours - adding inertia/damping

**Comment by msimpson** [comment]
@homerjam 

Thanks. But I'm fine rolling my own, I just wanted to avoid it.

**Pull request closed without merging**
