### PR TITLE
Tests: clean .travis.yml

### PR DESCRIPTION
**Pull request by munrocket**
Tests right now is pretty stable, but exists some issues with taking screenshots on Macbooks.

Want to try in future:
- beginFrame
- github CI, maybe it will be more robust, we unable to [exclude files](https://github.com/travis-ci/travis-ci/issues/6301) from tests stage

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
By the way, can we change the logic so e2e uses the files in `screenshots` to test, instead of the files in `examples`?

That way new PRs won't fail and we can add a screenshot afterward.

**Comment by munrocket** [comment]
@mrdoob yes we can, something similar was suggested by Mugen87. I will add this later if you ok with that.

**Comment by mrdoob** [comment]
Sounds good!

**Pull request merged**
