### PR TITLE
PMREMGenerator: Make background result independent of premultipliedAlpha setting

### LINKED ISSUE #20819: PMREMGenerator: FromScene behavior differs with renderer clear color vs scene.background
**Describe the bug**

The resulting environment map from PMREMGenerator.fromScene differs when calling `renderer.setClearColor( 0xffffff )` beforehand vs calling `scene.background = new Color( 0xffffff );`.

**To Reproduce**

You can see the difference in behavior in this fiddle:

https://jsfiddle.net/0saxwg6n/

Uncomment this line to see the behavior difference:

```
// NOTE: Uncomment this line to make it work
// scene.background = new THREE.Color( 0xffffff );
```

***Code***

Setting clear color:

```js
renderer.setClearColor( 0xffffff );
const generator = new THREE.PMREMGenerator( renderer );
const rt = generator.fromScene( scene );
scene.environment = rt.texture;
```

Setting scene background:

```js
scene.background = new THREE.Color( 0xffffff );
const generator = new THREE.PMREMGenerator( renderer );
const rt = generator.fromScene( scene );
scene.environment = rt.texture;
```

**Expected behavior**

The look of the resulting map is the same regardless of whether or not the background color is set via scene.background or renderer clear color.

**Screenshots**

renderer.setClearColor( 0xffffff );

image

scene.background = new Color( 0xffffff );

image

(an aside but is it expected that the background become so much darker when rendering to the environment map?)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Three.js version: dev

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #20819

Follow on from https://github.com/mrdoob/three.js/pull/20983

**Description**

Fixes the discrepancy in solid background color described in https://github.com/mrdoob/three.js/issues/20819#issuecomment-753002965 when premultipledAlpha is set to `true` and `false`. As far as I can tell when the `premultipliedAlpha` setting is set to true the browser seems to implicitly multiply the renderer clear color by the clear alpha to ensure it's multiplied (can anyone confirm? The documentation on the setting is pretty thin). This is an issue because RGBE encoding stores E in alpha. This PR uses a box to render the background color so renderer clear color is not used and gives consistent results regardless of the setting.

Here's a before and after achieved by adjusting the `webgl_loader_gltf` example with the following settings and tone mapping disabled:

```js
renderer.setClearColor( 0xff0000 );
const envMap = pmremGenerator.fromScene( scene ).texture;
```

|              |    premultipliedAlpha : true    |     premultipliedAlpha : false |
| ---- | ---- | ---- |
| Before | image | image |
| After | image | image |

cc @elalish

### CODE REVIEW

**Comment by gkjohnson** [comment]
Here's the same set of tests from https://github.com/mrdoob/three.js/pull/20983#issuecomment-756374418 with tone mapping disabled and premultiplied alpha set to true:


#### Case 1
```js
// showing scene background overrides background clear color
renderer.setClearColor( 0xff0000 );
scene.background = new THREE.Color( 0xffffff );
const envMap = pmremGenerator.fromScene( scene ).texture;
```

image

#### Case 2
```js
// showing renderer clear color is used when scene.background is null
renderer.setClearColor( 0xff0000 );
scene.background = null;
const envMap = pmremGenerator.fromScene( scene ).texture;
```

image

#### Case 3

```js
// showing renderer clear color yields the same result as scene.background color
renderer.setClearColor( 0xffffff );
scene.background = null;
const envMap = pmremGenerator.fromScene( scene ).texture;
```

image

#### Case 4

```js
// showing the environment map is used if set as the scene.background
renderer.setClearColor( 0xffffff );
scene.background = texture;
const envMap = pmremGenerator.fromScene( scene ).texture;
```

image

**Comment by gkjohnson** [comment]
The `webgl_furnace_test` e2e screenshot test is failing but I'm actually not sure why. It does use PRMREMGenerator.fromScene but here's the difference in the screenshots when I run in locally:

| in dev | newly generated screenshot |
| --- | --- |
| image | webgl_furnace_test |

As far as I can tell from the code the spheres should only be blue when the [user mouses over the page](https://github.com/mrdoob/three.js/blob/master/examples/webgl_furnace_test.html#L39-L47).

**Comment by elalish** [comment]
Seems good to me. We should figure out what's up with the furnace test. I'm hoping it's just a weird artifact of how the screen-shot was done rather than an incorrect render. That test should still be valid.

**Comment by gkjohnson** [comment]
> Seems good to me. We should figure out what's up with the furnace test. I'm hoping it's just a weird artifact of how the screen-shot was done rather than an incorrect render. That test should still be valid.

I merged in latest dev and it looks like the screenshot was fixed (at least on my local machine). I'm not sure how the PREM change could have affected the sphere color but perhaps something else was causing an issue.

**Comment by gkjohnson** [comment]
Okay here are the new results of the screenshot test:

| in dev | newly generated screenshot |
| --- | --- |
| image | webgl_furnace_test |

The background is now lighter which should be expected given that the furnace test uses `fromScene` and default `premultipliedAlpha` setting. Would you like me to update screenshot?

**Comment by elalish** [comment]
Yeah, go ahead and update the screenshot. That looks great, thanks!

**Comment by gkjohnson** [comment]
Looks like `webgl_materials_envmaps_hdr_nodes` has an issue, now? But I've made the screenshot locally and see no differences. Is there a way to see the generated screenshot from CI?

**Comment by gkjohnson** [comment]
@mrdoob I merged master in and it looks like all tests are passing now though I wouldn't have expected that to change anything. I was under the impression that the e2e tests should be deterministic, right? But I see from the GH actions setup that we run the same e2e test 4 times with no changes and it seems it can fail in only one of the runs. Are there still some quirks in the setup that cause it to incorrectly fail sometimes?

**Comment by gkjohnson** [comment]
> I  see from the GH actions setup that we run the same e2e test 4 times with no changes and it seems it can fail in only one of the runs

Nevermind I see now that the four E2E runs check [different screenshots between them so they're evaluated in parallel](https://github.com/mrdoob/three.js/blob/dev/test/e2e/puppeteer.js#L145-L147) so it makes sense that only one of the E2E CI runs would fail. Either way it looks like merging master fixed the failure so this should be good.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
