### PR TITLE
Add BasisTextureLoader

### PR DESCRIPTION
**Pull request by donmccurdy**
[Basis Universal announcement](https://opensource.googleblog.com/2019/05/google-and-binomial-partner-to-open.html). 🎉

Thanks to @shrekshao and @austinEng for their help with the WASM transcoder and WebGL integration, and to Binomial for the Basis universal format and tooling ([GitHub](https://github.com/BinomialLLC/basis_universal)).

The loader in this PR is similar to the one used in the [Basis demos](https://github.com/BinomialLLC/basis_universal/tree/master/webgl), with some enhancements. Transcoding is handled in a Web Worker, and multiple textures can be transcoded in parallel with multiple workers. Several TODOs remain in the code. I plan to fix them, but the loader is functional in the meantime.

Basis will be the foundation for compressed texture support in glTF, per [Khronos blog post](https://www.khronos.org/blog/google-and-binomial-contribute-basis-universal-texture-format-to-khronos-gltf-3d-transmission-open-standard).

### CODE REVIEW

**Comment by takahirox** [comment]
Nice work. Will an example (`examples/webgl_texture_basis.html` or something) be in another PR?

**Comment by donmccurdy** [comment]
Probably another PR, yeah. In the meantime:

```js
const loader = new THREE.BasisTextureLoader();

// Order doesn't matter. Detecting supported formats requires
// a WebGL context. The transcoder path should contain a
// JS wrapper and WASM binary with predetermined names. The
// maxWorkers option is used to avoid conflicts with other
// application services that may need workers.
loader.detectSupport( renderer );
loader.setTranscoderPath( './basis/' );
loader.setMaxWorkers( 4 );

loader.load( './assets/diffuse.basis', ( texture ) => {

	material.map = texture;
	
	render();

} );
```

Just realized I didn't add the `setMaxWorkers` method yet.

**Comment by takahirox** [comment]
OK, looking forward to seeing an example. And thanks for sharing API.

**Comment by titansoftime** [comment]
I'm excited to try this!

**Comment by mrdoob** [comment]
Thanks!

**Comment by donmccurdy** [comment]
Opened https://github.com/mrdoob/three.js/issues/16524 to track next steps on this loader.

**Pull request merged**
