### PR TITLE
Vector2/3/4: add addLength() and subLength()

### PR DESCRIPTION
**Pull request by puxiao**
**Description**

Sometimes it is convenient to use addLength() and subLength() when modifying vectors.

### CODE REVIEW

**Comment by mrdoob** [comment]
Can you share more use cases where these methods would be helpful?

**Comment by puxiao** [comment]
The following conditions are known:

* The coordinates of four vertices of a rectangle: A (xa, ya), B (xb, yb), C (xc, yc), D (xd, yd)

* Point R is located between AB and is 0.2 meters away from AB



No matter how the rectangle changes (scaling, rotation, translation), we need to calculate the position of R.

```
const centerRect = new Vector2((xa+xc)/2, (ya+yc)/2);
const centerAB = new Vector2((xa+xb)/2, (ya+yb)/2);

const positionR = centerAB.sub(centerRect).addLength(0.2).add(centerRect)
```

**Comment by WestLangley** [comment]
You can't really call `.subLength( d )` without checking to see if the length is greater than `d` to begin with. Same for `.addLength( - d )`.

This is a judgement call, but IMO, `.setLength()` and `.multiplyScalar()` are adequate.

**Comment by puxiao** [comment]
I know it's possible to have a vector length of 0, or change that vector to the opposite direction.

I just think this is more convenient for vectors of non-zero length.

**Pull request closed without merging**
