### PR TITLE
Examples: Added helpers to light probe examples

### PR DESCRIPTION
**Pull request by WestLangley**
Added the light probe helpers to the light probe examples.

It is important to verify that:

(1) the irradiance inferred from the environment map is correct,

(2) the computed SH3 coefficients are correct, and

(3) the helper renders correctly.

Also added a notation that the light probes position property, which is important in a light probe volume, is only honored when rendering the helper. The light probe position is currently not used in the lighting calculations.

### CODE REVIEW

**Comment by WestLangley** [comment]
How did the screen shots pass without updating them?

Also, `webgl_lightprobe_cubecamera.html` seems to be redundant given `webgl_lightprobe.html`.

**Comment by Mugen87** [comment]
> Also, webgl_lightprobe_cubecamera.html seems to be redundant given webgl_lightprobe.html.

`webgl_lightprobe_cubecamera` covers a different use case since it generates the light probe from a render target.

**Comment by WestLangley** [comment]
@Mugen87 webgpu screenshots render black for me. Is there a secret?

**Comment by Mugen87** [comment]
Have you lately executed a `npm i`? Maybe the dev dependencies are outdated...

**Comment by WestLangley** [comment]
I'm using homebrew... In the mean time, can you please update the webgpu screen shot?

**Pull request merged**
