### PR TITLE
Fix linter errors in WebGL examples

### PR DESCRIPTION
**Pull request by looeee**
Fix (nearly) all errors in WebGL and WebGL advanced examples. 

There are basically two kinds of linter errors remaining:

1. Global variables such as `Stats`, `WebGL` etc. defined in seperate .js files give a _"'Stats' is not defined. (no-undef)",_ warning. So far only `webgl_geometry_teapot` has a linter instruction to ignore these ( `/*global THREE, WEBGL, dat, window */` ).

```
var stats = new Stats();
```

2. This pattern is used in a lot of examples and gives a _"'controls' is assigned a value but never used. (no-unused-vars)_ warning
```
var controls = new THREE.OrbitControls( camera, renderer.domElement );
```

My preference would be to just ignore these, I'm open to other opinions though.

### CODE REVIEW

**Comment by Mugen87** [comment]
>controls is assigned a value but never used. (no-unused-vars)

lgtm.com also complains about this one. It would be nice to resolve this warning in some way...

**Comment by mrdoob** [comment]
Ops! Seems like #15038 introduced conflicts in this PR.

**Comment by looeee** [comment]
> lgtm.com also complains about this one. It would be nice to resolve this warning in some way...

@Mugen87 actually we can just do 

```js
new THREE.OrbitControls( camera );
```

I had assumed that would cause a linter error so I didn't even try it, but it seems that `mdcs` is OK with it. What do you think?

**Comment by Mugen87** [comment]
Yeah, that would be a possible solution although I would pass in the second parameter:
```js
new THREE.OrbitControls( camera, renderer.domElement );
```
I'm just not sure if the style of this code is okay like that. People might wonder why the new controls object is not assigned to a variable 😅

**Comment by looeee** [comment]
> I'm just not sure if the style of this code is okay like that.

In most linter rule sets this would come up against [no-new](https://eslint.org/docs/rules/no-new) rule. There's always one or two cases where I need `new` for side effects, and avoiding that just for the sake of following this rule results in more verbose code. However, it does seem _untidy_ to me and I try to avoid it. 

In any case, this issue existed before this PR, so we can address it after this is merged. 

@mrdoob it would be great to merge this before any more conflicts are created.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
