### PR TITLE
Fix a typo in multiple places

### PR DESCRIPTION
**Pull request by Dannie226**
Related issue: Was not put into a Github Issue. Issue is on [three.js discourse](https://discourse.threejs.org/t/interleavedbufferattribute-typo/37943/2)

**Description**

There was a typo in every single three.js file, and the three.js source file. The typo was where in a few places, instead of "interleaved" the files said "interlaved." This pull request will fix that.

### CODE REVIEW

**Comment by LeviPesin** [comment]
Please remove build files from this PR.

**Comment by Dannie226** [comment]
The typo was also in the build files. Why remove them?

**Comment by LeviPesin** [comment]
Because they are auto-built from the source files.

**Comment by Dannie226** [comment]
How would I remove the files from the PR? I changed the typos all in one commit, so I don't know how I could remove the files without deleting the pull request and starting over.

**Comment by Dannie226** [comment]
What second commit? I only made one commit, and it changed the typo in all 5 places.

**Comment by LeviPesin** [comment]
Make a new, second commit restoring the build files and just push it to the branch.

**Comment by Dannie226** [comment]
Sorry for the trouble. I am basically github illiterate. I really only use it for storing code, so I don't really know how it works past git command line stuff for pushing and pulling.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
