### PR TITLE
 Examples: Rename Mirror to Reflector

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/pull/12341#issuecomment-334547751

The PR also fixes `MirrorNode` and renames it to `ReflectorNode`.

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing:

http://rawgit.com/mugen87/three.js/dev4/examples/webgl_mirror.html
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_mirror_nodes.html
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_water.html
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_water_flowmap.html
http://rawgit.com/mugen87/three.js/dev4/examples/webvr_sandbox.html

**Comment by Mugen87** [comment]
BTW: I'll put this change into the migration guide.

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Many thanks!

**Comment by mrdoob** [comment]
Hah... #12345 😁

**Pull request merged**
