### PR TITLE
Updated package.json deps

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #XXXX

**Description**

Updated `package.json` and `package-lock.json`

### CODE REVIEW

**Comment by LeviPesin** [comment]
Please also update `test/package.json` and `test/package-lock.json`.

**Comment by linbingquan** [comment]
> Please also update `test/package.json` and `test/package-lock.json`.

Done. Thank you for your reply.

**Comment by Mugen87** [comment]
It seems the E2E test are now failing. Can you please revert the changes to `test/package.json`? These can be updated separtely.

**Comment by linbingquan** [comment]
> It seems the E2E test are now failing. Can you please revert the changes to `test/package.json`? These can be updated separately.

@Mugen87 Done. Thank you for your advice.

**Review by Mugen87 — APPROVED** [review]
Tested locally and it seems everything work as expected 👍 .

**Pull request merged**
