### PR TITLE
USDZExporter: Add support for `WebGPURenderer`.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #29295, https://github.com/mrdoob/three.js/issues/29156#issuecomment-2327068048

**Description**

The PR makes sure `USDZExporter` can be used without a dependency to `WebGLRenderer` by supporting the WebGPU version of `TextureUtils`. For that, the utils must be configurable.

@donmccurdy Do you think we can apply the same approach to `GLTFExporter` as well? And is the approach in general acceptable?

The exporters must call `decompress()` in an async fashion which unfortunately requires quite some refactoring in `GLTFExporter`.

### CODE REVIEW

**Comment by donmccurdy** [comment]
@Mugen87 I think so; opened https://github.com/mrdoob/three.js/pull/29509. Note that the renderer is an argument to TextureUtils.decompress, so we may need to refactor that a bit as well.

**Comment by mrdoob** [comment]
> maybe separate WebGLTextureUtils and WebGPUTextureUtils?

That sounds nicer 👍

**Comment by Mugen87** [comment]
Okay, I have renamed both modules in this PR. 

> Note that the renderer is an argument to TextureUtils.decompress, so we may need to refactor that a bit as well

We could transform the utils real classes and then apply the renderer in the ctor:
```js
const utils = new WebGPUTextureUtils( renderer );
exporter.setTextureUtils( utils );
```
If we decide to do that, I would completely remove the internal renderer creation in the utils. If no renderer is provided to `decompress()`, the methods create renderers for each invocation which isn't ideal, tbh.

**Comment by Mugen87** [comment]
I'll go ahead and merge since refactoring `WebGLTextureUtils`/`WebGPUTextureUtils` like suggested in https://github.com/mrdoob/three.js/pull/29507#issuecomment-2378911590 would require to migrate `GLTFExporter`. So let's complete https://github.com/mrdoob/three.js/pull/29509 first so `GLTFExporter` can handle the `decompress()` call async.

**Pull request merged**
