### PR TITLE
Removed whitelisting of uniform locations.

### PR DESCRIPTION
**Pull request by tschw**
OK, let's give it a try. I compared many examples and couldn't find breakage. The same thing might be possible for the attribute locations cache as well...

### CODE REVIEW

**Comment by mrdoob** [comment]
@benaadams do you have any thoughts about this?

**Comment by benaadams** [comment]
Will have to look at it little more

**Comment by tschw** [comment]
On second thought about this code, I noticed the following:

The availability of a uniform in OpenGL is not known until the dead code elimination pass of the GLSL compiler. Optimization dominates the performance of shader compilation, so a clever driver may provide diagnostics at an earlier point in time and stall when uniform locations are requested.
However, in WebGL (other than in desktop GL) uniform locations are objects. Thus they can implement lazy evaluation until actually used. Also WebGL may run on top of DirectX.
Putting it all together, the approach implemented here is not at all ideal for startup time, based on the possibilities of the specifications.

Since caching something with an incomplete key in a cache that cannot even be purged (as right now) is still very much of a no-no and a potential source of bugs of the weirdest kind, I will update this branch to a safe implementation that makes similar API calls as before, simply extracting the uniform names from the source code. It's not the prettiest thing to do, but it already fixes the problem.

Ultimately, the caching of uniform locations should happen in the renderer upon first use of the program, right before rendering. This way, in case compilation is not finished, all previous commands (e.g. upload of textures) run in parallel. I will implement it, as soon as I can allocate enough time in one piece for it.

**Comment by benaadams** [comment]
> Ultimately, the caching of uniform locations should happen in the renderer upon first use of the program, right before rendering. This way, in case compilation is not finished, all previous commands (e.g. upload of textures) run in parallel.

See #6411 though it needs some rework

**Comment by tschw** [comment]
OK, beforementioned changes are pushed. 

@benaadams 

So your branch will eventually replace the current renderer with a reworked version?
Is it in runnable state on current dev HEAD?

The problem seems still present in the rewritten version, but of course would have to dig deeper into it to know for sure the code I'm looking at isn't dead... For the context of this discussion see:

    https://github.com/mrdoob/three.js/pull/6555

(if you haven't done so already, the submission itself may serve as a test case).

Also, you may want to read up on this one

   https://github.com/mrdoob/three.js/pull/6545

it appears the problematic code has been removed, but again, I could be wrong and doesn't mean the bug is slain for good.

**Comment by benaadams** [comment]
@tschw no there has been an awful lot of code churn recently so its not currently mergable; and needs some careful rework to be brought back into line.

The bug you have highlighted would have still existed in it;  its more around general refactoring; more modularlisation, and splitting compile, link and use into different steps and sorting by shader rather than trying to compile and link immediately before render.

**Comment by benaadams** [comment]
I think whitelisting is for items you don't include in uniforms, for example I use RawShaderMaterial quite a lot and most of my shaders start:
```glsl
    uniform mat4 modelViewMatrix;
    uniform mat4 projectionMatrix;
```
However my uniform blocks do not include these e.g.
```javascript
		var material = new THREE.RawShaderMaterial( {
			uniforms: {
				flag: flagTexture,
				event: eventTexture,

				tick: tickUniform,
				uvAdjust: uvAdjust,
				groundFlags: groundFlags,
				groundFlags1: groundFlags1
			},
			vertexShader: document.getElementById( 'flag-vshader' ).textContent,
			fragmentShader: document.getElementById( 'flag-fshader' ).textContent,
			side: THREE.DoubleSide,
			depthTest: true,
			depthWrite: true,
			attributes: { positions: 1, details: 2 }
		} );
```
So you can include any of ```'viewMatrix','modelViewMatrix','projectionMatrix','normalMatrix','modelMatrix','cameraPosition','morphTargetInfluences','bindMatrix','bindMatrixInverse'``` in your shader without explicitly definining them in your uniforms; and the system will wire them up and set their values for you at render time. Same if you you ```ShaderMaterial``` I think

**Comment by benaadams** [comment]
For example see if this still works: http://threejs.org/examples/webgl_buffergeometry_rawshader

**Comment by tschw** [comment]
OK, replying to both of your messages...

Refactoing, modularisation and anything that improves extensibility and/or maintainability of the renderer sounds good to me! As does grouping by program, especially as all those conditionals can cause quite an explosion with complex scenes...

The example you quoted works. As does *everything* I have tested. Also for the initial version of this PR, which can *theoretically* have worse setup speed with certain combinations of cards, drivers, and WebGL implementations, based on the specifications. I did not see it happen - it just would've been too weird, if the original author had caused that mess for absolutely no reason. Think about it for a moment: A material is supposed to *select* a program and not *define* what further materials selecting the same program will get. That must've been accidental...
The patch causes the list of cached uniform locations to always be complete for the compiled code, so the breaking case is (probably already broken) code that requires existing and written-to uniforms to be irresponsive.

I think that ultimately, all those hardcoded names should evolve away, until we don't need fixed material classes anymore, just a meta model and one "ShaderMaterial" capable enough of carrying the engine. Still a bit of way to go, e.g. to manage multiple programs associated with rendering passes and primitive types, and to have a well-defined API for the GLSL composition... A "PhongMaterial" would end up as a default ruleset entirely defined in data.
Taking this idea beyond shaders, one may ask why to have BoxGeometry, SphereGeometry, ... instead of one "ProceduralGeometry" that wraps some JavaScript source and metadata defining the properties.

**Comment by benaadams** [comment]
If the example works then happy for it to be merged; though use of regex always makes me a little nervous :)

> Taking this idea beyond shaders, one may ask why to have BoxGeometry, SphereGeometry, ... instead of one "ProceduralGeometry" that wraps some JavaScript source and metadata defining the properties.

Well they either subclasses of ```Geometry``` or ```BufferGeometry```; with regular ```Geometry``` being phased out.

Also I'd argue its more clear to do:
 ```new THREE.BoxGeometry(height, width, segsY, segsX)```
or 
```new THREE.SphereGeometry(radius, segsY, segsX, startAngle, endAngle)``` 
rather than 
```new THREE.ProceduralGeometry(typeBox, ...parameters with changing meaning...)```
or
```THREE.ProceduralGeometry.CreateBoxGeometry(height, width, segsY, segsX)```

and to maintain the easy ability include/exclude various geometry types from the minified js, they'd still need to be in separate source files; so either the ```ProceduralGeometry``` type would be defined across multiple files or the factory methods would; making the source again less clear.

**Comment by tschw** [comment]
> If the example works then happy for it to be merged;

Great!

> though use of regex always makes me a little nervous :)

I can understand that.

> Also I'd argue its more clear to do:
> new THREE.BoxGeometry(width, height, depth, widthSegments, heightSegments, depthSegments)
> or
> new THREE.SphereGeometry(radius, widthSegments, heightSegments, phiStart, phiLength, thetaStart, 
> thetaLength) 
> rather than
> new THREE.ProceduralGeometry(typeBox, ...parameters with changing meaning...)

I'd argue that it's easiest to write  <code>scene.getObjectByName("myTestBox")</code>, where the box has been added to the data model in the editor WYSIWYG.

Also, named arguments are certainly easier to read than positional ones:
<code>THREE.BoxGeometry(a,b,c,d,e,f)</code>
vs
<code>THREE.ProceduralGeometry({script: 'box.js',  extent: [a,b,c], segments: [d,e,f]})</code>
Accepting the input in multiple forms becomes much easier too:
<code>THREE.BoxGeometry(v.x, v.y, v.z, n.x, n.y, n.z)</code>
vs
<code>THREE.ProceduralGeometry({script: 'box.js',  extent: v, segments: n})</code>

> ...factory methods...

Of course, there would only be *one* central factory implementing this stuff - not just for <code>ProceduralGeometry</code> but for *any entity* employing the property model...

> and to maintain the easy ability include/exclude various geometry types from the minified js,  

...and when consequently applied, it would save so much code that you might not even bother.

While dreaming: I'd prefer support for the "advanced mode" of the closure compiler to use its automatic dead code elimination simply removing *all* unused code from my final application. Also, given [a suitable "header"](https://github.com/google/closure-library/blob/master/closure/goog/webgl/webgl.js), it could turn all symbolic GL constants into numerals, making the lib both smaller and faster. Not to mention the way better compression at JS level...

**Comment by benaadams** [comment]
> I'd argue that it's easiest to write scene.getObjectByName("myTestBox"), where the box has been added to the data model in the editor WYSIWYG.

Hmmm... we may well be looking at very different use cases.

> THREE.ProceduralGeometry({script: 'box.js', extent: [a,b,c], segments: [d,e,f]})

While I do understand your point, for me that's an allocation for the object, two allocations for the arrays, and an allocation for the parameters object. Only the object itself is permanent, so you've just created an extra bunch of unnecessary garbage for the GC to pick up. As Three.js is generally on the UI thread, as its rendering, and GCs can directly effect frame rate that may be problem. (Though equally I'd try to minimise creating objects on the fly so wouldn't really be effected)

> Of course, there would only be one central factory implementing this stuff - not just for ProceduralGeometry but for any entity employing the property model...

Sounds more like a utils or helper/extensions level on top which could then do something like you suggested?:

```THREE.GeometryUtils.Create({ script: 'box.js', extent: [a,b,c], segments: [d,e,f] })```

**Comment by tschw** [comment]
> While I do understand your point, for me that's an allocation for the object, two allocations for the
> arrays, and an allocation for the parameters object

As you can see from this very changeset, I'm too worried about allocations :grin:. Still, I think the concern is misplaced here: The user sees these allocations and can prevent them. E.g. by using *one* object and reusing it. The library would automatically copy the object when required for asynchronous loading. And creating a new object (or whatever) every frame is a rather weird use case to begin with...

> Sounds more like a utils or helper/extensions level on top which could then do something like you 
> suggested?
> <code>THREE.GeometryUtils.Create({ script: 'box.js', extent: [a,b,c], segments: [d,e,f] })</code>

I think you're missing my point: I'm talking about evolution - as has happened from fixed function GPUs to programmable ones. Here's the stepping stone:

    THREE.ShaderMaterial.prototype.toJSON = function ( meta ) {
        var data = THREE.Material.prototype.toJSON.call( this, meta );

        data.uniforms = this.uniforms; // oops

there can be instances of classes like <code>Texture</code> and <code>VectorN</code> in the data that should *actually* be taken care of... 

Properly addressing this stuff will already yield automatic serialization (and deserialization in the corresponding loader) driven by a (flat) meta model.
My project branch already contains (incomplete and case-specific) editing support for the uniform values declared in the uniforms property of the current ShaderMaterial in a dynamic extra sidebar. With the updating issues solved, it was straightforward to implement.

So loader, exporter and editor that (partially) "write themselves" will just emerge by taking some logically next steps in forward direction. 

A generalization to object properties (not just uniforms) could save many lines of rather boring code that easily contain bugs or become outdated...

**Comment by benaadams** [comment]
Fair enough, isn't really my area of expertise as I only use ```DDSLoader``` and otherwise mostly load straight into ```Float32Array```s for ```BufferGeometry``` from an XHR arraybuffer; and object wise only ```SphereBufferGeometry``` and ```PlaneBufferGeometry```. Material wise I really only use ```RawShaderMaterial``` so my perspective is a little limited :)

**Comment by tschw** [comment]
Interesting. Not sure which shader material I'll end up using. Still exploring... Just ran into stuff that needed fixing and I guess I've fallen in love with that editor - even though it's still a little sketchy, or maybe especially because of it.

Do you pull in uniforms beyond the matrices for lighting and everything? Or do you roll your own outside of three.js? Do you reuse any three.js shader code?

I'm mostly at vertext level, in the moment but will have to deal with the pixels later...

BTW sorry for drifting off-topic so much around here :grinning:.

**Comment by benaadams** [comment]
Continuing the off-topic... :)

> Do you pull in uniforms beyond the matrices for lighting and everything? 

Autogenerated I only use ```viewMatrix```,```modelViewMatrix```,```projectionMatrix```,```normalMatrix```,```cameraPosition```; matrix-wise I add ```projectionMatrixInverse```

> Or do you roll your own outside of three.js? 

Some materials have shared uniforms; whether textures or other things so for example I'll define a global:

 ```var tickUniform = { type: "f", value: 0 };```

Use it in many materials:
````javascript
var materialA = new THREE.RawShaderMaterial( {
	uniforms: {
		grass: grassTexture,
		water: waterTexture,
		biome: biomeTexture,
		noise: noiseTexture,
		...
		mapTile: { type: "t", value: tileAtext },

		tick: tickUniform,

		uvAdjust: uvAdjust,
		groundFlags: groundFlags
	},
	vertexShader: shaders.ground.vertex,
	fragmentShader: shaders.ground.fragment,
	depthTest: true,
	depthWrite: true
} );
````
Update it once in render loop:

```tickUniform.value = ( performance.now() / 1000 - startTick );```

Have never used ```material.needsUpdate``` though do use ```.needsUpdate``` on buffers and textures a lot.

> Do you reuse any three.js shader code?

No; though I do use it very much as reference material, I'm closer to the [deferred rendering shaders](https://github.com/mrdoob/three.js/blob/master/examples/js/ShaderDeferred.js) in general though haven't satisfactory bottomed out the approach to generalise it nicely back into ```WebGLRenderer``` though looking at some options #6464; but my shaders generally are doing a lot of other data processing beyond lighting and shading which is quite specific for what they are for.

With both deferred rendering and continually updating buffers and textures avoiding stalls in the gpu pipeline is one of my main focuses.

Still trying to work [glsl-optimizer](https://www.npmjs.com/package/glsl-optimizer) into my [gulp](http://gulpjs.com/) based build process not quite there though :)

**Comment by tschw** [comment]
<code>var tickUniform = { type: "f", value: 0 };</code>

Haha! I like this pattern ^^. Thanks for all the details.

Very interesting discussion in #6464, will comment on it later. 

> Still trying to work glsl-optimizer into my gulp based build process not quite there though :)

Nice!

There's already a "File" -> "Publish" button in the editor... Would be cool to have a "release mode" implemented in a Node server that externalizes (and maybe even compresses) the data arrays into binary files, compresses the GLSL and throws the rest of the scene data and the library code collectively into the closure compiler (this way, advanced mode will be much easier to support, as the properties in the loader and in the JSON get renamed consistently) and finally serves the result on some HTTP port for immediate testing of the final app :grinning:.

**Pull request closed without merging**
