### PR TITLE
RGBELoader: Simplify texture configuration.

### LINKED ISSUE #24017: [misc] code redundancy of RGBELoader
**Describe the bug**

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/RGBELoader.js#L442

image

it seem there is a useless switch case

***Code***

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

### PR DESCRIPTION
**Pull request by deepkolos**
Fixed #24017

**Description**

clean RGBELoader unused code

0. unused switch case
1. unused format variable

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Without studying the code in depth... Wouldn't this break this if `texture.type ==== UnsignedByteType`?

**Comment by deepkolos** [comment]
@mrdoob RGBELoader support Float or HalfFloat only

image

**Comment by mrdoob** [comment]
I see...

How about this clean up then?

```js
			switch ( texture.type ) {

				case FloatType:
				case HalfFloatType:

					texture.encoding = LinearEncoding;
					texture.minFilter = LinearFilter;
					texture.magFilter = LinearFilter;
					texture.generateMipmaps = false;
					texture.flipY = true;

					break;

			}
```

**Comment by deepkolos** [comment]
@mrdoob  the current clean up will remove switch check too, because of the type check already in the parse function

image

**Comment by mrdoob** [comment]
Right, but my suggestion would only change the properties in the cases we know that need to be changed.
I think it makes the code more readable and more future proof, wouldn't you agree?

**Comment by deepkolos** [comment]
@mrdoob 👌🏻

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
