### PR TITLE
Docs: Clarify InstancedMesh.setMatrixAt() needs update.

### PR DESCRIPTION
**Pull request by gonnavis**
Clarify "You have to set .instanceMatrix.needsUpdate flag to true after called .setMatrixAt()."
I have been troubled by this for a long time, even though I finally found it mentioned in the previous lines.

### CODE REVIEW

**Comment by Mugen87** [comment]
I wonder if we could hide the necessity to set the `needsUpdate` flag at all by introducing a private dirty flag that indicates that buffer attribute requires an update. It would be set to true when using `setMatrixAt()`. The dirty flag could then be checked by the renderer per frame. If set to true, `needsUpdate` is set to true.

I think it's better use a separate dirty flag for this and not directly set `needsUpdate` in `setMatrixAt()`. Otherwise the internal buffer attribute version would be quickly reach high numbers.

**Comment by gonnavis** [comment]
I also think that requires to set property's needsupdate is a bit strange.

**Comment by mrdoob** [comment]
My goal with `InstancedMesh` was to provide a way to render many objects at the same time with minimal CPU (and memory) usage. I thought about adding a flag in `setMatrixAt()` but I worried that it would increase the CPU usage when updating the matrices of thousands of objects per frame.

**Comment by mrdoob** [comment]
Can you change the text to this?

> Make sure you set [page:.instanceMatrix][page:BufferAttribute.needsUpdate .needsUpdate] to true after updating all the matrices.

**Review by Mugen87 — APPROVED** [review]

**Comment by gonnavis** [comment]
@mrdoob Changed.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
