### PR TITLE
VTKLoader: Add support for `AppendedData`.

### PR DESCRIPTION
**Pull request by Mt-Youya**
Related issue: [#28815](https://github.com/mrdoob/three.js/issues/28813)

**Description**
 Add  "AppendedData " format support.

### CODE REVIEW

**Comment by Mugen87** [comment]
Do you mind sharing a VTK asset for testing? The one from your issue points to a 404 page:

https://github.com/Mt-Youya/vanilla-oral/blob/main/public/assets/models/user-appendedData.vtp

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/Mt-Youya/three.js/bd8555046cdc943e8f87cb5b7fcd039a1110eee9/examples/webgl_loader_vtk.html

**Comment by Mt-Youya** [comment]
Oh! Sorry! I forget set public. It works now!

**Review by Mugen87 — APPROVED** [review]
LGTM! The existing assets still work and `user-appendedData.vtk` from your test repo works now.

**Pull request merged**
