### PR TITLE
WebGPURenderer: instance mesh use binding group instead of attribute

### PR DESCRIPTION
**Pull request by z4122**
**Description**

Make instance objects use binding group instead of attribute

For instancing, it is preferable to use binding group buffers rather than attributes. I know in the initial versions of Three.js, uniforms had size limitations, leading to the use of attributes as a workaround.

However, WebGPU recommends using binding groups to pass values to the GPU. This approach eliminates the need for additional computations.

Before 
66283c67560e543b4a306a4e3d047c2

After
1e02c1151aa3f497833e3a1bba3e305

In WebGL2, we can use UBOs (Uniform Buffer Objects) to achieve the same functionality. However, UBOs have a size limit of 64kB in spec. To accommodate this limitation, I restrict the instance count, allowing the application to run under different conditions with varying counts. (In fact, I found that the UBO max size is far more than 64kb in my device.)

Before 
a1635e780460f6ab7f30e5d6f3d939f

After
b70efb398690f12ae77e05a1ca53814

### CODE REVIEW

**Comment by z4122** [comment]
@sunag @RenaudRohlinger Please review this PR

**Comment by sunag** [comment]
Initially we used binding buffer, but the size was very limited, I think having both options is great.

**Comment by sunag** [comment]
Can I merge this PR or you think on doing some other revision?

**Comment by z4122** [comment]
> Can I merge this PR or you think on doing some other revision?

Please review again. 

I found that WebGPU also limits UBO max size https://www.w3.org/TR/webgpu/#dom-supported-limits-maxuniformbufferbindingsize. And the data in the UBO must be aligned to 16 bytes. Since InstanceColor is a vec3 and occupies 12 bytes, I removed the optimization for InstanceColor.

If I change instanceColor to vec4 in InstanceMesh.js, it will affect a lot of code. Therefore, I want to run a benchmark to determine if this change is worthwhile in another PR.

**Comment by z4122** [comment]
@sunag I have solved code confit, please review again. Thanks!

**Pull request merged**
