### PR TITLE
WebGPURenderer: Instance Sprite Example

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
Related comment: https://github.com/mrdoob/three.js/pull/29491#issuecomment-2375456672

**Description**

Third attempt to provide a fallback for THREE.Points with sizeAttenuation support. This PR demonstrates how to combine Sprite Meshes with `instanceBufferAttribute`. /cc @WestLangley

image

*This contribution is funded by [Segments.AI](https://segments.ai) & [Utsubo](https://utsubo.com)*

### CODE REVIEW

**Comment by WestLangley** [comment]
This is a thing of beauty. ❤️ 

I have hacked your example to test some scaling issues...

A Plane and a Sprite of _unit size_ render the same size by design. So should a single instanced Sprite.

Currently the instanced Sprite is too big by a factor of two. This is because the geometry is twice as big. I temporarily fix it by scaling the uniform, but you will have to scale the geometry instead.

Sprites

**Comment by RenaudRohlinger** [comment]
Thanks! 😊 I’ve scaled the geometry accordingly, so it should be now fixed.

**Comment by WestLangley** [comment]
Do you think `InstancedSprites` should have a `.center` property, like `Sprite` does.

Granted, you can add the property and it works.
```js
const sprites = new InstancedSprites( geometry, material );
sprites.center = new THREE.Vector2( 0.5, 0 );
```

**Comment by sunag** [comment]
We can already make instanced sprites, this would be an additional redundancy in the library, more code, documentation and maintenance, `object.count` should be intended to instantiate any object

```js
const material = new THREE.SpriteNodeMaterial( { sizeAttenuation: true, map: sprite, alphaMap: sprite, alphaTest: 0.1, transparent: true } );
material.positionNode = instancedBufferAttribute( new THREE.InstancedBufferAttribute( new Float32Array( positions ), 3 ) );

const particles = new THREE.Sprite( material );
particles.count = 10000;
scene.add( particles );
```

**Comment by sunag** [comment]
Could we use the `object.count` approach instead of creating new objects and materials? This example would be very useful.

**Comment by RenaudRohlinger** [comment]
Ahh, we all forgot about this obvious one. That's why you're the boss 😄.

Updated the PR consequently.

**Comment by sunag** [comment]
The nodes allow so many combinations. It also took me a while to process this possibility, luckily the implementation has evolved this far 🙏.

**Comment by WestLangley** [comment]
The original purpose of this PR was to add `InstanceSprite` -- just as we have `InstanceMesh`. Both are convenience classes.

But `InstanceSprite` was removed from this PR, and the PR was merged.

What is the plan for:

1. computing the correct bounding volumes necessary for frustum culling,

2. handling raycasting,

3. updating the position of one of the instances.

**Comment by RenaudRohlinger** [comment]
My initial idea was just rendering multiples sprites but I understand these elements are importants.

I can still cherry pick my previous commit if we want to add a new Class in the future with all these functions included just like InstancedMesh.

**Comment by WestLangley** [comment]
@RenaudRohlinger I do think your original PR was excellent.

**Comment by sunag** [comment]
@WestLangley These possibilities also came to my mind, but I think we should upgrade these apporachs based on GPU-Compute and abandon approchs using CPU. We could handle some internal rules using `object.count > 1` as well, working with GPU on this should give us more performance and compatibility with procedural stuff, and the unification will reduce maintenance, documentation.

**Pull request merged**
