### PR TITLE
Add multiplication and equality methods to Matrix3

### PR DESCRIPTION
**Pull request by yellcorp**
Adds `multiply(rhs)`, `premultiply(lhs)`, `multiplyMatrices(lhs, rhs)`, `multiplyToArray(lhs, rhs, out)` and `equals(rhs)` to `Matrix3`, bringing its mathematical methods into parity with `Matrix4`. Code style, implementation and method ordering is modeled on `Matrix4` and the style guide.

This is motivated by the use of `Matrix3` instances for calculating 2D affine transforms of the form
```
xx yx tx
xy yy ty
0  0  1
```
which can often go where three.js goes, for composing 2D overlays (UI or otherwise), texture transformation in UV space, or dynamically preparing textures with (say) `CanvasRenderingContext2D`.

Being generic mathematical operations, the 2D motivation remains incidental - it can of course be used for combining normal transforms, non-translated position transforms, etc.

A further enhancement *could* be to add helper methods to initialize 2D translation / scale / rotate matrices, but I've stopped short of that. I'd leave it as an open question of demand, and should maybe be weighed against potential confusion to newcomers at 2D-oriented methods coexisting with the otherwise clearly 3D purpose of Matrix3. 2D transforms are not so hard to create inline where needed.

Unit tests for the `multiplyMatrices` method of both `Matrix3` and `Matrix4` have been added - the latter when I went to look for it as an example, but didn't find.

### CODE REVIEW

**Comment by WestLangley** [comment]
> bringing its mathematical methods into parity with Matrix4

Actually, we made a conscious decision not to do that...

Of course, we can revisit that decision.

The `Matrix3` methods include those methods required for the library to function. You are adding five new methods. There are many others you could add, including other `Matrix4` methods.

What is your use case for these particular methods, and why should we include these methods and not others?

**Comment by mrdoob** [comment]
Actually, `multiplyToArray()` has been removed in `dev`.

**Comment by yellcorp** [comment]
Both the use case for adding those methods and rationale for limiting it to them forms the bulk of my initial comment. I'm not proposing the addition of any methods to `Matrix4` - I'm proposing what subset of its functionality would be both intuitive and useful if present analogously in `Matrix3`. I realize there are as many opinions on what to include in a linear algebra class as there are linear algebra libraries, but I'd argue multiplication is not a controversial one.

My latest, specific use case that motivated this PR is to fit arbitrarily sized, user-submitted images to a prescribed width and height, and then scaling to NPOT for use as a texture. This is implemented as a product of up to three 3x3 affine matrices expressing 2D transforms: `npotScale • coverFit • arbitrary`. `coverFit` is computed and applied after examining `arbitrary`, which scales the image up to fill the rectangle - but only if necessary. NPOT scaling is also done here to obviate three's handling of it at a predictable point in the application code. But even if I left that to three's autoscaling, I'm still multiplying at least two `Matrix3`s. A quick non-rigorous assessment of my options are:
- pushing it down to a GLSL `*` of two `mat3`s, and applying it to the uvs
- importing a separate library and doing all 3x3 matrix operations with that
- writing a standalone function
- monkeypatching `Matrix3`

All of these feel like coding around an API wart - especially for such a fundamental operation, especially as a method present in matrices of one size and not another.

**Comment by yellcorp** [comment]
I included `multiplyToArray` for parity alone, so I won't defend its addition if the 4 equivalent is gone.

**Comment by WestLangley** [comment]
> I'd argue multiplication is not a controversial one.

Neither are addition and subtraction. 

What is the argument for not adding those methods, too?

. . .

This is not a math library. We have omitted many `Matrix3` methods, and we have no `Matrix2` class at all.

Perhaps we could add convenience methods to `examples/js/math`?

Or you could just add the required methods to your project.

**Comment by mrdoob** [comment]
Yup yup! Do you mind removing `multiplyToArray` from the PR?

**Comment by yellcorp** [comment]
Done. Also forgot about documentation - while I was going to see how this discussion played out it was simple to add using Matrix4 as a guide.

**Comment by yellcorp** [comment]
@WestLangley I can only really repeat myself. I've already provided my rationale for the new methods (concrete use case that can be implemented with generic, widely-understood operations), for limiting them to those (nothing not already present on `Matrix4`), and why it's preferable to the alternatives (interface consistency, and the read- and writability of application code that results). I don't think any of the extrapolations you mention are comparable. I'd say that addition and subtraction *are* more controversial due to their lesser relevance to geometric transformations, which supports the assertion it's not math library and these new methods don't detract from its focus.

**Comment by mrdoob** [comment]
I think in this case it's ok. Those methods are pretty common.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
