### PR TITLE
Moved How to update things from wiki to manual

### PR DESCRIPTION
**Pull request by looeee**
Minor clean up, otherwise left as is

### CODE REVIEW

**Comment by WestLangley** [comment]
Any way to redirect this? There are many links on stackoverflow (and elsewhere) to the wiki articles, which will now all be broken.

**Comment by looeee** [comment]
Hmm... Good point. I guess the easiest will be to leave stub pages in the wiki that link to the new manual pages.

**Comment by looeee** [comment]
@mrdoob could you add these pages that I've moved to the main site now rather than waiting until the next release?

**Comment by mrdoob** [comment]
> @mrdoob could you add these pages that I've moved to the main site now rather than waiting until the next release?

Uh oh!

**Comment by mrdoob** [comment]
Oh, actually, yes... I'll update `gh-pages`.

**Comment by mrdoob** [comment]
I'm just going to copy the whole `docs` folder though... some things may get out of sync. 

Otherwise, would you like to do a PR targeting the `gh-pages` branch?

**Comment by looeee** [comment]
> Otherwise, would you like to do a PR targeting the gh-pages branch?

Sure - it looks like the list.js file is causing problems anyway, I kind of expected that to happen.

I'll hopefully have some time to do this later today.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
