### PR TITLE
BufferAttribute: Introduce dispose().

### LINKED ISSUE #15261: add dispose() to BufferAttribute
is it possible to add a dispose() method to BufferAttribute?

i need to dispose buffer attribute directly, not through the buffer geometry.
so i will change BufferAttribute and WebGLAttributes a bit, but i am not sure whether i am right.

i will change like this:
1.Make BufferAttribute as a sub classs of EventDispatcher to dispatch the dispose event
2.Handle dispose event in WebGLAttributes

am i right?  thank you !

##### Three.js version

- [x] Dev
- [ ] r98
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
This PR replaces #15308. Fixed #15261.

A first step to make `BufferAttribute` fixed sized. 

The new policy should be: _If you need to resize buffer data, you have to create a new instance of `BufferAttribute`._

### CODE REVIEW

**Comment by yaoyao-cn** [comment]
@Mugen87 sorry for the delay,  is it necessary to resolve the conflicts caused by #15308 now ? if it is not necessary i will delete the relevant branch.

**Comment by Mugen87** [comment]
Resolved the merge conflicts.

**Comment by FMS-Cat** [comment]
I think I need this right now

**Comment by Mugen87** [comment]
@mrdoob Any chances to merge this PR? If not, do you mind sharing your concerns about this change? Maybe we can find a different solution if this one is not satisfying?

**Comment by Mugen87** [comment]
I'll make a PR on a current code base if this change is wanted. Resolving the merge conflicts seems more risky than starting from scratch^^.

**Comment by OndrejSpanel** [comment]
Note: there is currently no method to properly dispose `instanceMatrix` and `instanceColor` in the `InstancedMesh`.

I think this is really a glaring hole in the resource management. A proper cleanup should always be possible. Someone may have a scene with a lot of dynamic instancing going on (I am now experimenting with exactly such scene) and the missing cleanup causes slowing growing allocation of WebGL resources in such case.

**Comment by Mugen87** [comment]
After a deeper analysis I do not vote to introduce `BufferAttribute.dispose()` anymore since this easily breaks code in `WebGLBindingStates`. Geometry data are managed as a single entity. Calling `dispose()` on attribute level and thus deleting the WebGL buffer would not automatically update the respective VAO.

`InstancedMesh.dispose()` has to be implemented without `BufferAttribute.dispose()`.

**Pull request closed without merging**
