### PR TITLE
Examples: Updated lil-gui v0.17.0

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #XXXX

**Description**

As the title.

### CODE REVIEW

**Comment by georgealways** [comment]
🎉 !

**Comment by Mugen87** [comment]
@georgealways Are there migration task when upgrading from 16 to 17?

**Comment by georgealways** [comment]
It should just be a drop-in, but of course let me know if you run into any trouble.

**Comment by Gregory-Han** [comment]
When I drag and drop from the div that wraps the GUI to the .title, the entire window always closes or opens.
 Is there a way to fix this?

**Pull request merged**
