### PR TITLE
Make sure to use all parameterNames + keep it maintainable.

### PR DESCRIPTION
**Pull request by gero3**
As far as I can tell, there seems to be several parameternames which weren't included in the array:
- isWebGL2
- outputEncoding
- envMapCubeUV
- vertexUvs
- numDirLightShadows
- numPointLightShadows
- numSpotLightShadows

And ShaderID which I left out intentionally.

### CODE REVIEW

**Comment by mrdoob** [comment]
> - numDirLightShadows
> - numPointLightShadows
> - numSpotLightShadows

I think these will force shader recompilation uneeddedly.

**Comment by gero3** [comment]
It requires the shader to be recompiled anyway because the shadercode would change. 
For instance, following code would be changed by [this code](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js#L188) based on numPointLightShadows. 
```
#if defined( USE_SHADOWMAP ) && ( UNROLLED_LOOP_INDEX < NUM_POINT_LIGHT_SHADOWS )
```
Parameter numPointLightShadows = 6
```
#if defined( USE_SHADOWMAP ) && ( UNROLLED_LOOP_INDEX < 6 )
```

Parameter numPointLightShadows = 7
```
#if defined( USE_SHADOWMAP ) && ( UNROLLED_LOOP_INDEX < 7 )
```

This is used in [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/lights_fragment_begin.glsl.js#L42).

**Comment by Oletus** [comment]
num*Shadows should be included in the parameter names. My mistake!

Including "isWebGL2" in parameter names may not be necessary though. I don't think programs can migrate between different renderers.

**Comment by gero3** [comment]
isWebgl2 may not be nessecary but it also can't hurt to have it.

**Pull request closed without merging**
