### PR TITLE
Clipping Intersection Example: Added plane helpers

### PR DESCRIPTION
**Pull request by WestLangley**
A clipping plane defines a half-space. The half-space consists of the points "in front of" the plane -- the side of the plane toward which the normal points.

Clipping removes the complement of the half space -- the points "behind" the plane.

When `clipIntersection` is `true`, clipping retains the _union_ of the half-spaces, and removes (clips) the _intersection_ of the complement of the half-spaces.

When `clipIntersection` is `false`, clipping retains the _intersection_ of the half-spaces, and removes (clips) the _union_ of the complement of the half-spaces.

I added the plane helpers to this example to help users visualize what is going on.

screen shot 2017-06-26 at 8 16 48 pm

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweeet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@mrdoob What do you think of adding info to the webpage like [this](https://rawgit.com/westlangley/three.js/dev-clipping_2/examples/webgl_clipping_intersection.html)? 

Actually, it would not work well on small screens without come responsive CSS, which is not my thing, quite frankly.

**Comment by mrdoob** [comment]
Imo, I think the example is self-explanatory already. Specially after the helpers additions.

**Comment by WestLangley** [comment]
OK. Thanks.

**Comment by pailhead** [comment]
I'm digging through the clipping code and I completely missed what `clipIntersection` does. I just blindly used it as a flag to enable/disable clipping which seems to have worked how i expected with just a single plane. 

I see that `NUM_CLIPPING_PLANES` is a define, which means that removing the single clipping plane from `Material.clippingPlanes` would require an update?

In other words. what is the best approach to add a toggle to turn the clipping on/off [in this example](https://threejs.org/examples/#webgl_clipping_intersection)? I can think of a few ways, flipping between different materials, or using `onBeforeCompile` to add a control uniform, but thought i'd check in here.

**Pull request merged**
