### PR TITLE
Removed dead code

### PR DESCRIPTION
**Pull request by brason**
Not a big deal, but noticed some unused variables. I assume they can be removed?

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks! How did you find them?

**Comment by brason** [comment]
With the wonderful help of Dart's static analysis engine :)

**Comment by mrdoob** [comment]
Magic...!
Feel free to check other files! ;)

**Comment by brason** [comment]
I'm working on it as we speak :P

**Comment by zz85** [comment]
actually uglify-js also warns of many unused variables...

image

**Comment by mrdoob** [comment]
I wonder why closure compiler stopped warning about those... :(

**Pull request merged**
