### PR TITLE
setLength micro optimization

### PR DESCRIPTION
**Pull request by mbredif**
this micro optim saves a few function calls and multiplications...

### CODE REVIEW

**Comment by WestLangley** [comment]
You are inlining an existing method.

The code is written for clarity. So far, we do not inline code or otherwise micro-optimize. I expect a compelling reason would be required to do so, such as a demonstrated performance issue.

**Comment by Mugen87** [comment]
> I expect a compelling reason would be required to do so, such as a demonstrated performance issue.

Even if the performance would be slightly better, I would prefer the current style which is easier to read.

**Comment by WestLangley** [comment]
@mbredif Yes, we have had this discussion before, and have opted for clarity and reusability. But please continue to make suggestions! :-)

**Comment by mbredif** [comment]
Ok, no problem. I am closing it then. I doubt that this would be a bottleneck in any case :)

**Pull request closed without merging**
