### PR TITLE
WebGPURenderStates: Basic implementation

### PR DESCRIPTION
**Pull request by sunag**
**Description**

It's use scene lights automatically in a `LightsNode`.

- [x] [WebGPURenderStates: minimal implementation](https://github.com/mrdoob/three.js/commit/46d895d0c1d2355c694ffa31c766dee3f0440572)
- [x] Generate hash from scene lights
- [x] [add Node.id property](https://github.com/mrdoob/three.js/commit/7a9b3d506e850133bc06fd1115c05af733315dc6)
- [x] [Move static .fromLights() to property and update .getHash()](https://github.com/mrdoob/three.js/commit/c32326742b8d375c201df1295b136730b2eab9d9)
- [ ] Invalidate materials automatically if lights are added or removed

This contribution is funded by [Google via Igalia](https://igalia.com).

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by LeviPesin** [comment]
Would Node.uuid be still needed if Node.id will be added?

**Comment by sunag** [comment]
@LeviPesin Node.uuid is used in .toJSON() mainly.

**Comment by mrdoob** [comment]
@sunag Is this ready to go?

**Comment by sunag** [comment]
@mrdoob yes, yes!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
