### PR TITLE
Fill in TODOs in MeshStandardMaterial doc

### PR DESCRIPTION
**Pull request by erich666**
As it says: fill in the TODOs, and give more description about some other parameters.

### CODE REVIEW

**Comment by erich666** [comment]
Dang it, I have no idea what that "Merge remote-tracking branch 'refs/remotes/mrdoob/dev' into dev" stuff is. I've tried hard to submit these simple changes to a single manual page, one that should be filled in. 

So I have no idea what the examples/webgl_materials_blending_custom.html changes are about, some Git weirdness. Let me know if I should resubmit - it would be a HUGE help to know exactly how to do this process, as I've now tried about three times and am obviously still having problems. We're not all Git and Github experts. I recall there's a Help page somewhere within three.js that says how to do this, but now I can't find it. It used to be linked from the help section of the threejs.org site, but that area's now gone.

Frustratedly yours,

Eric

**Comment by mrdoob** [comment]
Seems like the PR is clean @erich666, no need to worry about it.

@WestLangley looks good?

**Comment by WestLangley** [comment]
This is OK to merge. I will add more detail later.

**Comment by mrdoob** [comment]
Thanks!

**Comment by erich666** [comment]
Whew, good! Glad to do my little bit to help out, I just wish it wasn't so fraught with "hmmm, now what?"

**Pull request merged**
