### PR TITLE
Artifacts: add bundle analyzer.

### PR DESCRIPTION
**Pull request by munrocket**
This is a thing.

### CODE REVIEW

**Comment by mrdoob** [comment]
I was actually trying `rollup-plugin-visualizer` yesterday.

```diff
diff --git a/utils/build/rollup.config.js b/utils/build/rollup.config.js
index 1a8afe448..2eef16048 100644
--- a/utils/build/rollup.config.js
+++ b/utils/build/rollup.config.js
@@ -1,4 +1,5 @@
 import buble from 'rollup-plugin-buble';
+import visualizer from 'rollup-plugin-visualizer';
 
 function glconstants() {
 
@@ -227,7 +228,8 @@ export default [
 		input: 'src/Three.js',
 		plugins: [
 			glconstants(),
-			glsl()
+			glsl(),
+			visualizer()
 		],
 		output: [
 			{
```

Screen Shot 2020-05-07 at 9 09 02 PM

**Comment by munrocket** [comment]
Yep, I am placed it inside CI so we don’t need another dependency on pc.
Also GA have a plan to improve .html download https://github.com/actions/upload-artifact/issues/14

**Comment by mrdoob** [comment]
I see the benefit of creating that visualization a couple of times a year or when we looking for things to optimize. You're proposing to create the visualization for every PR, correct?

**Comment by munrocket** [comment]
Yes, it will be placed here https://github.com/mrdoob/three.js/actions/runs/99954013

**Comment by mrdoob** [comment]
Hmm, I don't think CI is the right place for this. I could see this being part of the build script, but it still feels like noise...

**Comment by munrocket** [comment]
I do not want to polemicize here. I believe that every developer should have this information since we don't have true three-shaking and making it by hand with commenting some of the lines in code.

**Comment by mrdoob** [comment]
So we could generate it once per release then?

**Comment by munrocket** [comment]
Oh f*ck, I am accidentally force pushed.

**Comment by DefinitelyMaybe** [comment]
> So we could generate it once per release then?

Was reading down the page and thinking exactly that

**Comment by munrocket** [comment]
So make it! Enough talking.

**Comment by DefinitelyMaybe** [comment]
...but I like talking 😄 

There's plenty of time for making the things

**Comment by munrocket** [comment]
I have only 2 day to improve your damn DX in three.js

**Comment by mrdoob** [comment]
> I have only 2 day to improve your damn DX in three.js

DX?

**Comment by munrocket** [comment]
My time is limited when I disturb you with this Developer Experience PRs, I need to focus on another project and I will solve all problems that I faced, except typescript migration / tree-shaking, which is pretty complex or politically unwanted. CI is working good without me, you can just maintain it.

**Comment by looeee** [comment]
The rollup plugin seems to do a better job of displaying relative sizes. Here's the output I get from bundle-analyzer.html: 



PropertyBindings takes up the entire center of the screen despite being <16kb.

**Comment by munrocket** [comment]
> The rollup plugin seems to do a better job of displaying relative sizes. Here's the output I get from bundle-analyzer.html:

I get result from `rollup-plugin-visualizer` and renamed it as `bundle-analyzer.html`, because this name is similar to popular package `webpack-bundle-analyzer`. Picture is good [here](https://github.com/mrdoob/three.js/actions/runs/99954013) and should inspire other contributors.

**Pull request closed without merging**
