### PR TITLE
Nrrd loader

### PR DESCRIPTION
**Pull request by stity**
Added : 
- a NRRD parser inspired from XTK NRRD parser : https://github.com/xtk/X
- the zlib library to be able to gunzip gzipped data in the nrrd files
- `THREE.Volume` object to hold the output of the NRRD loader
- `THREE.VolumeSlice` object to hold the slices extracted from the volume
- an example (examples/webgl_loader_nrrd.html)
- a nrrd file and a vtk file for the example

This PR follows this issues :
https://github.com/mrdoob/three.js/issues/8254

### CODE REVIEW

**Comment by stity** [comment]
Demo here : http://stity.github.io/three.js/examples/webgl_loader_nrrd.html

**Comment by WestLangley** [comment]
The  NRRD model takes a long time to load for me (a minute or more), and occasionally with an error.

http://threejsworker.com/api/pullrequests/8344/examples/webgl_loader_nrrd.html

    Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

Can you removing the build from the PR? See the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

Also, include `webgl_loader_nrrd.html` in the files list so it will appear in the examples.

**Comment by stity** [comment]
It is normal to have a long loading time, the NRRD file is 40MB.
I am not able to reproduce the error .
I tested on these browsers : 
 - Google Chrome (Windows and iOS)
 - Firefox (Windows)

Here is what you should see : 
pr screenshot


Regarding the three.js build, it is an end of file and I don't know how to get rid of it, I already merged from the dev branch.

I added the example in the file list.

**Comment by stity** [comment]
@WestLangley I simulated a bad connection with Chrome Developper tools and I got the same error when using your server after 2 min of download : 
http://threejsworker.com/api/pullrequests/8344/examples/webgl_loader_nrrd.html
but I managed to go through the entire download in 3min at this link : 
http://stity.github.io/three.js/examples/webgl_loader_nrrd.html
So it must be a server side issue rather than an issue with my demo.

**Comment by bhouston** [comment]
This is really nice, very very nice but the *.nrrd file is 39MB.  I am not sure we want that in the ThreeJS repo for ever.  Is there is a much smaller *.nrrd, like <= 5MB, you can include as an example?

**Comment by bhouston** [comment]
There is an console.log that is outputing a mesh somewhere in the code.

**Comment by bhouston** [comment]
You should also not include three.js or three.min.js in the PR nor in the history.

**Comment by stity** [comment]
@bhouston I have an abdominal volume (right now it's a knee) which is smaller (about 6MB) but nothing under 5MB.
I will remove the console.log, it was for debug purposes.
During the dev on my branch I first put THREE.Volume and THREE.VolumeSlice in scr/core that is why the build has been changed. But @mrdoob told me to put them in examples/js instead.
I don't know how to get rid of the history of three.js and if you look at the diff, it is the same file, just a different file ending.

**Comment by mrdoob** [comment]
I think 6MB is fine. As per how to clean up the history, you may want to look into git rebasing.

**Comment by stity** [comment]
I did not manage to get a clean history with git rebase so I created a new branch with my code and opened a new pull request  [here](https://github.com/mrdoob/three.js/issues/8364)

**Pull request closed without merging**
