### PR TITLE
Missing combine and envMapIntensity property

### PR DESCRIPTION
**Pull request by atul-mourya**
combine and envMapIntensity properties in MaterialLoader are missing when loading materials

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by takahirox** [comment]
Should we also add `.combine` and `.envMapIntensity` serialization into `Material.toJSON()`?

**Comment by Mugen87** [comment]
If it's actually missing, yes. 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
> Should we also add `.combine` and `.envMapIntensity` serialization into Material.toJSON()?

Let's add in another PR

**Pull request merged**
