### PR TITLE
Attribute dispose

### PR DESCRIPTION
**Pull request by aardgoose**
Add a dispose() method to BufferAttributes to allow render(s) to remove GPU and other resources interdependently of  BufferGeometry objects.  This avoids the GPU memory issues described in #7123 23 and the attached jsFiddle. Not heavily tested.

Note: it appears that the WebGLRenderer already has potential buffer leaks in renderBufferDirect() where attributes are removed from a geometry in the morph code??? I haven't used these so may be misreading it.

Note: InterleavedBuffer not index attributes handled.

### CODE REVIEW

**Comment by mrdoob** [comment]
This PR has conflicts because `build/three.js` is in it 😕

**Comment by aardgoose** [comment]
removed the build noise

**Comment by aardgoose** [comment]
Bug with needsUpdate fixed and merge conflicts removed

**Comment by mrdoob** [comment]
Seems like it needs another pull... 😇

**Comment by aardgoose** [comment]
merged again a conflicts resolved.

**Comment by mrdoob** [comment]
Would you like to give this another go? (Now that `WebGLAttributes` has been cleaned up.

**Comment by aardgoose** [comment]
I'll take a look - Much nicer now attributes not tangled up so much with WebGL(Objects|Geometries)!

**Pull request closed without merging**
