### PR TITLE
Add SSRPass (screen space reflection)

### PR DESCRIPTION
**Pull request by gonnavis**
Continue from https://github.com/mrdoob/three.js/pull/20061 (only support OrthographicCamera).

**Now support PerspectiveCamera.**

[Demo,](http://raw.githack.com/gonnavis/three.js/SSRPass/examples/webgl_postprocessing_ssr.html) [Demo2,](http://raw.githack.com/gonnavis/three.js/SSRPassExamples/examples/physics_ammo_volume_ssr.html) [Demo3,](http://raw.githack.com/gonnavis/three.js/SSRPassExamples/examples/webgl_animation_keyframes_ssr.html) [Demo4,](http://raw.githack.com/gonnavis/three.js/SSRPassExamples/examples/webgl_shading_physical_ssr.html) [SelectiveDemo,](http://raw.githack.com/gonnavis/three.js/SSRPassExamples/examples/webgl_postprocessing_ssr_selective.html) [OrthographicDemo.](http://raw.githack.com/gonnavis/three.js/SSRPassExamples/examples/webgl_postprocessing_ssr_orthographicCamera.html)

**No SSR**
image
**SSR Only**
image
**SSR With Reflector.js As GroundPlane**
(Now just add a reflector to hide the obvious flaw of SSR at ground, need more integration afterwards)
image
image

**Below All SSR Only**
fasdfadf
gergsdgfsdfg
fasdgfawsrefews
fasdgerwgfsadf

### CODE REVIEW

**Comment by gonnavis** [comment]
@Ben-Mack Hello, after add `precision highp float; precision highp sampler2D;` in fragmentShader, It's OK on may iPhone6sp and Honor 10 lite.

**Comment by thedb** [comment]
awesome!

**Comment by Ben-Mack** [comment]
@gonnavis Great! I confirm it's working fine on my Note FE now, performance is a bit better too, the fps increased from 14fps to ~21fps.

**Comment by gonnavis** [comment]
@Ben-Mack Thank you for your testing! I'm keep improving.

**Comment by mrdoob** [comment]
(Testing on a Pixelbook Go)

[Demo](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_postprocessing_ssr.html) runs at 8fps. However, https://cineshader.com/ runs at 60fps.

**Comment by gkjohnson** [comment]
> https://cineshader.com/ runs at 60fps.

@mrdoob are you sure that's using screen space reflections? I don't see any of the artifacts associated with SSR and given that it's only a floor plane reflecting the scene it would probably be a lot simpler and more performant to just render the scene upside down for the reflection.

**Comment by mrdoob** [comment]
I thought it was?

/ping @edankwan

**Comment by edankwan** [comment]
https://cineshader.com only use planar reflection and textured area light. No SSR involved.

**Comment by mrdoob** [comment]
Ah, my bad. I always thought the way the camera moved was "suspicious" 😁

**Comment by Mugen87** [comment]
In any event, I doubt that SSR is an appropriate approach for WebGL. In general,  I don't think it makes sense to adopt any possible rendering technique to WebGL just for having it. If it does not perform well on most device (have somebody tested mobile with SSR?), I do not vote to integrate it into the repository. At the end, we only have to explain disappointed users why the approach does not perform well enough.

**Comment by edankwan** [comment]
THREE uses forward rendering. In the codes, it reflects the beauty pass but not the diffuse. Also, it renders the scene many times. I think if we have multi-render target in place, it might be achievable. Right now it is just too expensive to run.

**Comment by mjurczyk** [comment]
> Demo runs at 8fps.

> has somebody tested SSR with mobile?

> Right now it is just too expensive to run.

Out of curiosity tested Littlest Tokyo demo with SSR (Demo 3 above) on Google Pixel 3a (not exactly a flagship processing power) - it runs at a smooth 25-35fps. The further you move camera, the better results. 100% zoomed in can get down to 9fps.

For comparison:
- Non-SSR Littlest Tokyo demo runs at 35-40fps
- PCSS demo runs at 8-10fps
- Clearcoat PBR demo runs at 15-25fps (also depending on zoom)

So overall it seems to match the performance of other demos / three performance on mobile. Wouldn't use on mobile, but for desktop projects it seems alright.

**Comment by titansoftime** [comment]
On my Samsung Galaxy S7 (released in 2016) I get 25 FPS when zoomed in and 40 FPS when zoomed out. My desktop runs this at a stable 60fps.

I do not understand why a cool feature like this should be rejected for performance reasons when in runs well enough on a 4.5 year old phone.

**Comment by Mugen87** [comment]
> Wouldn't use on mobile, but for desktop projects it seems alright.

On an iMac 5K I get 11 FPS with the SSR demo. The little toky and clear coat demo runs with 60 FPS and PCSS with 46 FPS. 

Sorry but I'm afraid 11 FPS are not usable at all.

**Comment by mjurczyk** [comment]
@Mugen87 out of curiosity, could you check with these settings (they still enable a visible SSR effect):

Screenshot 2020-09-27 at 16 01 25

It's running 30fps (stable) on 2013 MBP. I think distance 900 is a bit of an overshoot in terms of performance - although I wonder what may be causing it to perform so poorly on an iMac if it's playable on a phone.

**Comment by Mugen87** [comment]
With this settings the demo runs faster. However, the performance massively depends on the zoom and I quickly reach a performance way under 30 FPS. And the resulting reflections are looking clipped and thus buggy.

> although I wonder what may be causing it to perform so poorly on an iMac if it's playable on a phone.

I guess it's because apps using this particular SSR code are quickly fragment-shader bound. Hence, the implementation seems to have more issues with handling high resolutions (like the 5K iMac screen) compared to other effects.

**Comment by mjurczyk** [comment]
Right. But you are trying to run SSR on a native 5K resolution? Wouldn't that require a monster GPU to run on any reasonable FPS (regardless whether it's three.js or UE4) ? Or does it perform poorly regardless of the renderer size?

Wouldn't adjusting `resolution` ([L60](https://github.com/mrdoob/three.js/pull/20156/files#diff-fac40a49e80c730ebd9e0e31f5447a8cR60)) solve the issue of outrageous screen sizes 🤔  ?

**Comment by Mugen87** [comment]
IMO, the real crucial point is that other demos work fine with this resolution.

**Comment by gonnavis** [comment]
@mjurczyk Thank you for your testing! I changed the default setting for [Demo3](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_animation_keyframes_ssr.html). And from your conversation, I realized that can use the same skip strategy as viewZ for vZ to improve perfomance.
@Mugen87 Hello Mugen, has the performance under the high-resolution screen improved, after the e12c022 commit?

**Comment by gonnavis** [comment]
In addition, I have been trying to still get the accurate reflectRayLen at xy like https://github.com/mrdoob/three.js/pull/20061, but the previous period was busy because of company work and not much time, so no much progress was made. There have been some breakthroughs in these two days, and I think success is in sight.
If can get accurate reflecRayLen, then can add the distanceAttenuation and doubleSide features, which can skip complex calculations in more cases to greatly improve performance.

**Comment by gonnavis** [comment]
Use `lineLineIntersection` instead of `pointToLineDistance`, thus can get accurate reflectRayLen. 

Add **DistanceAttenuation** feature, and set it on by default, now can run at about 25~33fps on my iPhone6sp.
On a machine with good performance, can manually increase the attenuationDistance, or turn off DistanceAttenuation.

[Demo,](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_postprocessing_ssr.html) [Demo2,](http://gonnavis.com/lib/three.js_github_gonnavis/examples/physics_ammo_volume_ssr.html) [Demo3,](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_animation_keyframes_ssr.html)

bff0bbdd9ec0803ebbc225a5ae658b0

**Comment by gonnavis** [comment]
Finally, I returned to [this tut](https://lettier.github.io/3d-game-shaders-for-beginners/screen-space-reflection.html) to read the text and code, this time can understand the meaning more clearly. In it, found the **perspective-correct interpolation method** and the idea of **just comparing the z diff with surfDist**. Now can greatly simplify the calculation, almost as simple as [OrthographicSSRPass](https://github.com/mrdoob/three.js/pull/20061), thus can run at about 45~58fps on my iPhone6sp with attenuation on.

I'm writing on [this branch](https://github.com/gonnavis/three.js/tree/SSRPassPerspectiveCorrectInterpolation), still has some issues to deal with. Will merge to this SSRPass branch after solving these problems.

**Comment by gonnavis** [comment]
Done. Now the fps on my iPhone6sp with maxDistance=200

a

**Comment by gonnavis** [comment]
I was mainly inspired by [this tut](https://lettier.github.io/3d-game-shaders-for-beginners/screen-space-reflection.html).
For more easily and completely understand the tut, I'm making my own migrating to three.js at [my fork's three.js branch](https://github.com/gonnavis/3d-game-shaders-for-beginners).
Now just partially support diffuse & screen-space-reflection.

[demo](http://gonnavis.com/lib/3d-game-shaders-for-beginners_github_gonnavis/demonstration/three.js/index.html)

a

**Comment by mjurczyk** [comment]
Screenshot 2020-10-23 at 20 13 40

Got a bit buggy on MBP - sometimes when you rotate only reflections rotate, sometimes also they stretch to the sides of the viewport.

**Comment by gonnavis** [comment]
Yes, I also found out, I'll research the cause of this problem.

**Comment by Ben-Mack** [comment]
It's really nice, I've been looking to this effect for a long time. Many thanks for your contribution!

I noticed the reflection is a bit off on inclined surface:
image

**Comment by gonnavis** [comment]
@Ben-Mack Thanks! the tutorials you recommended(https://github.com/vanruesc/postprocessing/issues/190) helped me a lot, I'm still keep learning.

Do you mean the gap between the chimney cover and the body?
image

It's not a problem with inclined surface.
It's because of the limitation of **screen-space**, SSR can only reflect things already renderered. The lower part of the chimney cover has not been rendered, so it cannot be reflected.

The same issuse exists in [Blender EEVEE SSR](https://docs.blender.org/manual/en/latest/render/eevee/render_settings/screen_space_reflections.html)
image

If you do need full reflect, EEVEE suggested using **Reflection Plane** to assist SSR, which in three.js is **Reflector.js**. But I think you can just use it in some place, because **Reflection Plane** just can used at plane and as the number increases, there is a relatively large performance overhead.

**Comment by mjurczyk** [comment]
Possibly a stupid question - but shouldn't that reflection on the incline be parallel to the reflected object?

**Comment by gonnavis** [comment]
@mjurczyk I'm quite confident in my reflection calculation algorithm, but I still do a quick test in Blender to confirm that it should not be parallel.
image

**Comment by mjurczyk** [comment]
Apparently I've never seen a reflection at an angle in my life.. 🙈 

Should have tested with a real-life reflective surface - my bad, your reflections are on-point.

**Comment by marcofugaro** [comment]
> Right now it is just too expensive to run.

I think this can be greatly improved with #16390

**Comment by gonnavis** [comment]
@marcofugaro Thanks! Yes, I'm waiting for this pr https://github.com/mrdoob/three.js/pull/16390 too.
I've already used it in my this repo https://github.com/gonnavis/3d-game-shaders-for-beginners, it works well on my pc, and I'll deep studying how to work with Android if merged.
I guess the only problem of merging https://github.com/mrdoob/three.js/pull/16390 is because IOS not support WebGL2 yet?

**Comment by marcofugaro** [comment]
No idea, WebGL2 has been supported since at least a year

**Comment by gonnavis** [comment]
> No idea, WebGL2 has been supported since at least a year

On IOS, WebGL2 should be turned on in Safari setting manually, not default on.
So still can not used in production environment.

**Comment by marcofugaro** [comment]
Yeah I meant for other browsers, a WebGL2 context is created by default now.

**Comment by mrdoob** [comment]
Is there a way to fix the "jumpiness" of the reflection?

https://user-images.githubusercontent.com/97088/105575423-7752e980-5d63-11eb-96b3-e984155941c5.mov

**Comment by gonnavis** [comment]
@mrdoob Hello Mr.doob. I think it should be related to the judgment of `surfDist`, I will try to solve it first.

**Comment by gonnavis** [comment]
@mrdoob Solved! Turned out that the inconsistent `type` of `depthTexture` and `normalRenderTarget` caused this "jumpiness" problem. Now I changed them both to `FloatType` works well.

**Comment by mrdoob** [comment]
http://raw.githack.com/gonnavis/three.js/SSRPass/examples/webgl_postprocessing_ssr.html

**Comment by mrdoob** [comment]
Comparing it with `Reflector`, it seems like the reflection has a bit of vertical offset:

https://user-images.githubusercontent.com/97088/105699543-70f97480-5eff-11eb-8294-504f517804d8.mov

**Comment by gonnavis** [comment]
> Comparing it with `Reflector`, it seems like the reflection has a bit of vertical offset:

To prevent conflict between ground and reflector at start，I intendly lift the reflector a bit. But now seems can hide ground if reflector is shown. I'll change it.

**Comment by gonnavis** [comment]
Changed, now the GroundPlane and the Reflector at the exact same Y-axis height. 
To prevent conflict, I also set GroundPlane's `depthWrite` to `false` when Reflector is visible, for this scene, the trick has no problem at all. 
And why not always set GroundPlane's `depthWrite` to `false` is because of it need the depth info of GroundPlane to perform SSR when Reflector not visible.

But, turned out that the **main reason** for this problem "the reflection has a bit of vertical offset" **is not the different Y-axis height, main reason is heigh `surfDist` value**. 
Before, I chosed a relative high `surfDist` value `0.0021` to prevent the reflection gap on the ground when camera is very near ground. This value caused the thickness when camera is higher.
image
image

There are many values and expressions relative. Now, I has not found the best of them. So in order to be compatible with different camera positions, only a compromise combination can be found among many parameters.
To decrease the vertical offset between SSR and Reflector for now, I decided to reduce `surfDist` a little and sacrifice the quality when camera is very near ground.
But I'll keep finding the best values and expressions combination, or even the perfect values and expressions combination from mathematical calculation.

**Comment by mrdoob** [comment]
I think we should probably remove the noise setting:

Screen Shot 2021-01-25 at 5 46 06 PM

**Comment by gonnavis** [comment]
> I think we should probably remove the noise setting:

OK, the current noise will produce obvious artifact at some angles. May use something like `ImprovedNoise` instead. And I also impressed by the blur part of [gkjohnson's implemantation](https://github.com/mrdoob/three.js/issues/8248#issuecomment-695155326), but need more time to study. Now remove it first.

BTW, I've just figured out one important thing:
I can understand the gaps above ground is because of the rendered pixels of ground are too less to reflect.
But I can't understand why the gaps on the ground for a long time, because of the pixels of rendered objects are very dense for ground to reflect.
Now I realized, may because of the reflect angle too perpendicular to screen, cause it march far away even just on pixel step, so go behind the surface it should collide. Now know the cause, may can solve it, and should not need `surfDist compensation by angle` done in [this commit](https://github.com/mrdoob/three.js/pull/20156/commits/d042fdf8a4d9901ca016364e843f57a091ffb8ab).
image

**Comment by gonnavis** [comment]
@mrdoob Done! Now use `pointToLineDistance` instead of `viewReflectRayZ` to calculate `away`, thus become stride irrelavent. Now the reflections on ground are very stable.

I used `pointToLineDistance` before, but in order to achieve the DistanceAttenuation effect, I changed it to `lineLineIntersection` and then to `Perspective-Correct Interpolation`.But in the end I found that the implementation of DistanceAttenuation was wrong, and now the correct DistanceAttenuation does not require `viewReflectRayZ`, so `Perspective-Correct Interpolation` is not needed too.
But InfiniteThick effect still using `viewReflectRayZ`, so I not delete it now, may optimizing afterwards.

**Comment by gkjohnson** [comment]
> OK, the current noise will produce obvious artifact at some angles. May use something like ImprovedNoise instead. And I also impressed by the blur part of gkjohnson's implemantation, but need more time to study.

❤️ 

It's looking really good! It's come a long way. If you have any specific questions about details of my demo I'm happy to talk them through a bit. Here are a few thoughts and things to consider implementing that might improve scalability of the effect:

- It looks like the current implementation uses a single pixel "step" when raymarching for reflections which gives the best look but is expensive. I suggest adding a "stride" option that allows the ray to step over multiple pixels. It will introduce artifacts but you can then get by with fewer samples. And by introducing a jitter in the step the artifacts will be less noticeable. The artifacts will be less apparent when not using a perfectly flat mirror like surface, as well.
- In my opinion the best jitter strategy for rough reflections (and for the stride) is blue noise, which requires a premade texture. These textures could be included for SSR or as base64 string but using three.js' `random()` or the regular grid jitter (implementation for stride in [Morgan Mcguire's blogpost](http://casual-effects.blogspot.com/2014/08/screen-space-ray-tracing.html)) can look pretty good, as well.
- Regarding the blur I used in my demo -- the blur samples are weighted based on depth and normal differences in the adjacent pixels so it retains crisp edges at depth and normal disparities. Of course it requires sampling the color, normal, and depth at every pixel to be included for the blur so it's likely to be quite a bit more expensive but it could help remove the halo artifacts like you see where the bunny sits on the ground:

image

**Comment by gonnavis** [comment]
@gkjohnson Great explanation! 
Now I know why Lettier search twice in [his code](https://lettier.github.io/3d-game-shaders-for-beginners/screen-space-reflection.html), this question has bothered me for a long time and haven't figured it out. 
I'll try to implement the  first-big-stride-then-small-stride logic too, and other techniques you mentioned. Thanks a lot!

**Comment by gonnavis** [comment]
Many thanks to [Lonely_Wanderer](https://discourse.threejs.org/t/hows-the-reflection-made-in-this-example/23597) for letting me give priority to performance issues after turning on Reflector.

Now on my iphone6sp, with `SSR` and `Reflector` both on, can run at 40~50 fps.
Better than only `SSR`. Yeah, Realy, both on better than only `SSR` on, Surprising! Because of using `Reflector`'s result first, thus can skip a large amout of `SSR` calculation.

**Comment by mrdoob** [comment]
Thanks!

**Comment by gonnavis** [comment]
Wow, It's my pleasure! Thanks Mr.doob! Thanks every contributor and tutorial writer!

**Comment by webglzhang** [comment]
that's so  cool

**Comment by mjurczyk** [comment]
First of all - I absolutely love it, it is truly magnificent, @gonnavis 😳 🙌 I noticed an interesting issue though (while also spending the entire night trying to debug it :') )

I made [this-small-SSRr-experiment-to-which-GIF-twitter-seems-to-have-hidden-a-direct-URL-so-here-is-an-entire-tweet-URL-pls-remember-to-leave-a-like-and-subscribe](https://twitter.com/thefrontendcat/status/1382853807969873925) - long story short, the sphere is within a SSRr box. And, the entire scene is a single exported Blender GLB (that single glb-root is kinda the important part):

quartz

SSR / SSRr do not seem to see things that are not at the root of the scene, or are not *directly connected* to an object that is in the root  (and I couldn't find a note mentioning that they have to be there 🤔 .)

(1) `SSRrPass.OUTPUT.Default` with all objects in the root of the scene (red cube is not SSRr'd here to make it visible):

Screenshot 2021-04-16 at 13 17 32

(2) `SSRrPass.OUTPUT.NormalSelects` with all objects added manually to the root of the scene:

```js
const sceneChildren = [ /* traversed GLB and put all children here */ ];

sceneChildren.forEach(child => {
  objects.push(child);

  scene.add(child); // NOTE Manually move every child from GLB structure to the root of the scene (it has to be done for at least the objects that SSRr should apply to.)

  if (child.userData.useSSRr) {
    selects.push(child);
  }
});
```

Screenshot 2021-04-16 at 13 18 09

(Note: it also seems to work if you just add the root of the GLB to `selects` - children can then use SSRr properly - but SSRr will be applied to all of them which is not perfect.)

(3) `SSRrPass.OUTPUT.NormalSelects` with unmodified GLB (just load, add to scene, add child to `selects`):

```js
const sceneChildren = [ /* traversed GLB and put all children here */ ];

sceneChildren.forEach(child => {
  objects.push(child);

  // scene.add(child); // NOTE Skip this step

  if (child.userData.useSSRr) {
    selects.push(child);
  }
});
```

Both cube and the box around the sphere should use SSRr, but only the cube is visible (since the crystal box is not in scene root.)

Screenshot 2021-04-16 at 13 18 20

If SSRr requires objects to be in the root, it could be a good idea to add a note about it - since in [the example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing_ssrr.html) all the objects are only in the root, so there's no easy way to realise that limitation 🤔

**Comment by gonnavis** [comment]
@mjurczyk Thanks for you feedback! And sorry for not clarify.
Yes, for simplicity, I only implemented trasparent objects directly belong to the scene in SSRrPass, not support hierarchy now.

I'll try to finish [this pr](https://github.com/mrdoob/three.js/pull/21487) and copy the logic to SSRrPass in this development cycle, which I think will also solve the hierachy problem. 
If can't, a note is really need to be added.

PS: Your demo using SSRrPass ( screen space refraction ) which introduced in [that pr](https://github.com/mrdoob/three.js/pull/21420), not this SSRPass ( screen space reflection ) pr.😊

**Comment by mjurczyk** [comment]
> Your demo using SSRrPass ( screen space refraction ) which introduced in

True, just reckoned it may also apply to SSR and also had this issue in browser bookmarks from earlier. :') 

> If can't, a note is really need to be added.

To be honest this isn't a huge limitation that'd need an urgent fix - just a note should be enough, so nobody gets stuck 👀

**Pull request merged**
