### PR TITLE
Fix Planehelper updateMatrixWorld

### PR DESCRIPTION
**Pull request by webglzhang**
**Description**

 The target need consider the helper's position  in the PlaneHelper updateMatrixWorld function.

This contribution is funded by [Example](https://example.com).

### CODE REVIEW

**Comment by WestLangley** [comment]
A `THREE.Plane` does not have a position property.

The helper is used to visualize the infinite plane defined in Hessian normal form.

**Comment by webglzhang** [comment]
> A `THREE.Plane` does not have a position property.
> 
> The helper is used to visualize the infinite plane defined in Hessian normal form.

In Math,that's right. THREE.Plane is does not have a position property. But THREE.PlaneHelper has a position property. If we set position of PlaneHelper, the render of PlaneHelper is not true.I often use Three.Goup to add THREE.PlaneHelper to solve this problem. I can set the position of planehelper by setting the position of group. Now I wonder if I can solve this problem directly in the updatematrixworld of THREE.PlaneHelper.That's all I think.

**Comment by Mugen87** [comment]
Closing. Sorry, but this is not the intended usage of the helper. You should use it like demonstrated in the [documentation](https://threejs.org/docs/index.html?q=planehe#api/en/helpers/PlaneHelper).

In general, helpers that visualize other 3D objects or math entities are not supposed to be transformed on app level. It's in fact a design issue in the engine that transforming helpers is technically possible by the user. Please do not make use of it.

**Comment by webglzhang** [comment]
> Closing. Sorry, but this is not the intended usage of the helper. You should use it like demonstrated in the [documentation](https://threejs.org/docs/index.html?q=planehe#api/en/helpers/PlaneHelper).
> 
> In general, helpers that visualize other 3D objects or math entities are not supposed to be transformed on app level. It's in fact a design issue in the engine that transforming helpers is technically possible by the user. Please do not make use of it.

You are right.

**Pull request closed without merging**
