### PR TITLE
Remove disney roughness reparameterization

### PR DESCRIPTION
**Pull request by bhouston**
This PR is built upon the cosine cubemap LOD PR: #7414

I have removed the restriction of the Physical materials roughness parameterization to just [0.5 to 1], rather allowing it to vary between [0.04, 1] like the roughness parameterization in UE4.  (The lower limit of 0.04 is required to avoid some divide by zeros.)  This allows one to make perfectly shiny mirrors and other perfectly polished metals.

### CODE REVIEW

**Comment by mrdoob** [comment]
@WestLangley thoughts?

**Comment by WestLangley** [comment]
We need to address this issue after the dev branch is working again.

It seems unlikely to me that Disney would get this wrong, but we will see.

In any event, in the API, roughness ranges from zero to 1. The objective is to make roughness "perceptually linear" over that range. So, the [ 0, 1 ] input is remapped in the shader so we get the perceptually linear result we want.

**Comment by bhouston** [comment]
I do not change the linearity, I just extended the range.  If something isn't compiling I can look into it.

**Comment by WestLangley** [comment]
I think the commit that is the topic of this PR is https://github.com/bhouston/three.js/commit/e7db59ecbaee011cdad721969b4e30caadb6c6f4

That change is fine with me.

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by mrdoob** [comment]
[I've been playing with the new material](http://mrdoob.neocities.org/) and I was starting to notice that the sharper material I was able to achieve was metal. This change bring many more possibilities indeed!

**Comment by mrdoob** [comment]
By the way... Seems like when I use `metalnessMap`, `metalness` has no effect. But when using `rougnessMap`, `roughness` still has effect. Is this the exected behaviour?

**Comment by WestLangley** [comment]
We can change the behavior so `metalnessMap` modulates `metalness`. That would be consistent with how the other maps are handled.

Or we can change how `roughness` is handled.

It is up to you.

**Comment by mrdoob** [comment]
I think I vote for `metalnessMap` modulating `metalness`. Just like `map` modulates `color`.

**Comment by WestLangley** [comment]
OK. I'll take care of it.

**Comment by mrdoob** [comment]
Thanks!

**Pull request closed without merging**
