### PR TITLE
Blender exporter object export with skinned mesh

### PR DESCRIPTION
**Pull request by phfatmonkey**
This exporter change adds support for using Object Loader with skinned meshes while retaining support for JSONLoader. So anyone using using the JSONLoader should not be affected, but this will now support skinned meshes exported with 'Scene' checked and loaded using the ObjectLoader.

Here's a checklist I made to determine functionality.

image

The X's show what was supported in the dev branch prior to this change and this fix.

A few notes:

- For Scene Export, you must have Hierarchy checked. I'm not entirely sure what this is supposed to do, but for now we have a little more functionality than before.

- Exporting with Rest pose doesn't seem to work using Scene export. You must export using Pose and make sure your model is currently in the bind pose.

- The code is a bit cumbersome, but hopefully it can be refactored later. Ideally the best way to do this is to properly transform the bones when using the Scene export. Put that on the To Do list for someone with a little more knowledge on bone matrix transformations. :)

### CODE REVIEW

**Comment by mrdoob** [comment]
@arturitu any chance you could test this?

**Comment by arturitu** [comment]
I have created a branch on this project to test it > [objectLoader branch](https://github.com/arturitu/threejs-animation-workflow/tree/objectLoader) It contains the .blend file too.

It seems to works well with 'phfatmonkey' exporter version:

image

Because with the actual 'dev' exporter, this is the result:

image

But in both cases (I think is another problem with the exporter (or I'm doing something wrong with the textures)) I needed to deselect Texture settings to export the Scene...

image

...because if I try to export with Textures selected (repeat, in both exporters 'dev' and 'phfatmonkey') throw this error >

image

**Comment by phfatmonkey** [comment]
I'll take a look at this today. I know I've exported Textures before, but looking at the error I'm guessing it might be when trying to read properties of the material.

**Comment by phfatmonkey** [comment]
Ok, so I'm not getting this error. @arturitu, can you give me a screenshot of all the export settings? Thanks.

**Comment by arturitu** [comment]
@phfatmonkey 
image
image

**Comment by phfatmonkey** [comment]
Thanks for the screenshots, @arturitu. 

Ok it looks like the exporter was using the data coming from Blender's texture slot ad a key in a dictionary, but the one we got was different than the one it was expecting--the data was 'repeat' bu the exporter was looking for 'RepeatWrapping'. So I added the key to the constants file. I've left the original key there sin case it's being used somewhere else.

I'm not sure why I couldn't get any consistent results however. I may have missed a setting before.

**Comment by arturitu** [comment]
@phfatmonkey Now it was exported perfect! 
image

**Comment by insominx** [comment]
This seems like it's ready to go.  @mrdoob and @arturitu, is there anything else you guys require to merge this?

**Comment by mrdoob** [comment]
> This seems like it's ready to go. @mrdoob and @arturitu, is there anything else you guys require to merge this?

Nope!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> ...because if I try to export with Textures selected (repeat, in both exporters 'dev' and 'phfatmonkey') throw this error >

I think #10591 introduced this issue. I suspect 'mirror' is also broken then.

**Comment by phfatmonkey** [comment]
Great, thanks!

**Pull request merged**
