### PR TITLE
Add Gltransitioner to create crossfade effect much easier and extendable

### PR DESCRIPTION
**Pull request by HypnosNova**
I think the current crossfade effect demo is not so good and when I saw this: https://gl-transitions.com/
The crossfade should be like this. So I write Gltransitioner and provide 2 demos to show how to transition textures and scenes.
And it is much easier for people to use and people can also inject their own shaders into it.
I provide serval shaders from https://gl-transitions.com/ and you can see defferent effect from 2 demos.
I think it could be completely replace crossfade which three.js already has.

### CODE REVIEW

**Comment by HypnosNova** [comment]
Two demos:
[https://rawgit.com/HypnosNova/three.js/BoxSelection/examples/webgl_postprocessing_gltransitions_scenes.html](https://rawgit.com/HypnosNova/three.js/BoxSelection/examples/webgl_postprocessing_gltransitions_scenes.html)

[https://rawgit.com/HypnosNova/three.js/BoxSelection/examples/webgl_postprocessing_gltransitions_textures.html](https://rawgit.com/HypnosNova/three.js/BoxSelection/examples/webgl_postprocessing_gltransitions_textures.html)

**Comment by HypnosNova** [comment]
Two demos:
[https://rawgit.com/HypnosNova/three.js/gltransitioner/examples/webgl_postprocessing_gltransitions_scenes.html](https://rawgit.com/HypnosNova/three.js/gltransitioner/examples/webgl_postprocessing_gltransitions_scenes.html)

[https://rawgit.com/HypnosNova/three.js/gltransitioner/examples/webgl_postprocessing_gltransitions_textures.html](https://rawgit.com/HypnosNova/three.js/gltransitioner/examples/webgl_postprocessing_gltransitions_textures.html)

**Comment by Mugen87** [comment]
This is great stuff but I think it's better to place this in its own repository.

**Comment by Mugen87** [comment]
Closing. The showcase category in the [forum](https://discourse.threejs.org/) is another good place for this.

**Pull request closed without merging**
