### PR TITLE
ES6 (let&const): src/polyfills

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
related #19437

### CODE REVIEW

**Comment by gkjohnson** [comment]
Several of these can be set to `const`, right? `source` and `output` are never modified and I believe `nextKey` can be set to const in the for loop, as well. `let` is definitely the "safer" option here, though.

**Comment by DefinitelyMaybe** [comment]
yup. gosh. I wasn't thinking on this one. one moment, I shall update the commit.

**Comment by marcofugaro** [comment]
@DefinitelyMaybe setting the [prefer-const](https://eslint.org/docs/rules/prefer-const) and [no-const-assign](https://eslint.org/docs/rules/no-const-assign) rule in the `eslintConfig` section in `package.json` might help you in the future.

They automatically detects if the variable is being mutated or not, assuming you're using VSCode 🙂

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
