### PR TITLE
Rebuild Cloth.js and update the example

### PR DESCRIPTION
**Pull request by looeee**
[New Example](https://raw.githack.com/looeee/three.js/bd67e75c805c0b261b8606e74a4d77ed8b336a7c/examples/webgl_animation_cloth.html)

f2

In preperation for converting the file to a module, I attempted to refactor `Cloth.js`. In the end though it was easier to just start over and rebuild the class from scratch, since there was so much logic and global variables shared between the JS file and the HTML file. 

So, welcome to the new `Cloth`, much like the old `Cloth` but with a few improvements and a fancy new example! 

* All data is stored in buffers rather than v3s
* It's now possible to adjust properties of the geometry (previously width/height was hard coded)
* Using a `PlaneBufferGeometry` rather than `ParametricBufferGeometry`. Should be possible to use other geometries, but not tested
 * removed the "ball" algorithm for now, since the logic was spread too much between the files, and very specific to the old design. Perhaps later we can add in more general geometry constraints, for example to prevent the flag going through the flag pole. 
* fixed the "wind" algorithm.  The original algorithm,from [this article](https://viscomp.alexandra.dk/?p=147), applies force per face normal. Perhaps in the conversion to `BufferGeometry` things got messed up and the force was being applied 3 times to each vertex. 

Otherwise, the functionality should be similar. 

One nice improvement for the future would be to use `clock.getDelta()` rather than the current fixed timestep.

### CODE REVIEW

**Comment by Mugen87** [comment]
Nice! When opening the example, the initial movement of the flag looks a bit well... weird. Do you think there is a way to modify the code so the flag has not this init-phase?

**Comment by yomboprime** [comment]
The text reads inversed from the backside 😃

**Comment by looeee** [comment]
> The text reads inversed from the backside 😃

Most flags in the real world are like this, I think. 

> When opening the example, the initial movement of the flag looks a bit well... weird. Do you think there is a way to modify the code so the flag has not this init-phase?

Yeah, I haven't worked out what's causing that yet. I'll investigate some more.

**Comment by looeee** [comment]
@Mugen87 I've tuned the starting conditions and fixed a couple of things. It look better at the start now.

**Comment by Mugen87** [comment]
Much better!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Kind of feel sad about seeing the old example (visual form) go...
It even inspired a installation in an art show in Berlin: https://www.youtube.com/watch?v=JwQV1eJL7e8

**Comment by Mugen87** [comment]
@looeee Would it be much effort so the previous example just uses the new `Cloth` class? 😇

**Comment by arodic** [comment]
> Kind of feel sad about seeing the old example

Yeah, I thought the same. There was something magical and surreal about it. Also, the lighting and colors were kind of uplifting and happy.

This new example is dark and feels grim. The movement of the flag feels unsettling and violent.

I think it makes sense to have some basic art direction in examples. Especially for cloth.js since it is after all the first example presented on the page (alphabetically).

**Comment by looeee** [comment]
> This new example is dark and feels grim. 
> Especially for cloth.js since it is after all the first example presented on the page (alphabetically).

Hmm, that's a valid point, especially since it's the first example. I didn't consider that fully. Of course, it's not a big deal to update this new example to make it brighter and the movement less intense, which would be my preferred option here. But if other people prefer the old example that's fine by me... except that...

> @looeee Would it be much effort so the previous example just uses the new Cloth class? 😇

Unfortunately it seems so. I've just tested it and wasn't able to get the animation to look the same. Probably possible, but it would take more tweaking than I have time for at the moment, since I'm going on vacation in a couple of days and rushing to finish off another project first. Everything was hard coded in the previous example, down to the initial positions of the vertices, and that's hard to replicate exactly. 

In the interest of speeding up conversion of the examples to modules, if someone else wants to take this new `Cloth.js` and have a go at making a new example, tweaking my example, or reverting to the original example, that's fine by me. Otherwise, I'll come back to this in a couple of weeks.

**Comment by Mugen87** [comment]
> Otherwise, I'll come back to this in a couple of weeks.

Okay. For now, I'm going to put the code of the existing `Cloth.js` version to the example HTML file (similar to the crossfade example). In this way, it's more clear that `Cloth.js` can not used as a standalone class.

**Comment by Mugen87** [comment]
Closing for now due to merge conflicts (the example is now module based). It's probably better to start with a fresh PR if you are going to extract `Cloth.js` from the example.

**Comment by makc** [comment]
@yomboprime @looeee 
> The text reads inversed from the backside

```
if (gl_FrontFacing) vUv.x = 1.0 - vUv.x;
```
?

**Pull request closed without merging**
