### PR TITLE
Fix test for property existence in property binding in the case if property is a false boolean or a numeric equal to zero

### PR DESCRIPTION
**Pull request by anthonybriand**
Fix test for property existence in property binding in the case if property is a false boolean or a numeric equal to zero

cf discussion #9057

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
FYI @bhouston @tschw

**Comment by bhouston** [comment]
Argh.  JavaScript should just ban this language construct in "strict" mode, it only leads to problems.

**Comment by mrdoob** [comment]
Right? 😊

**Pull request merged**
