### PR TITLE
Add type check to DepthTexture

### PR DESCRIPTION
**Pull request by takahirox**
Refer to #9725

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... I have the feeling this code could be more readable...

**Comment by takahirox** [comment]
How about this one?

    if ( this.format === DepthFormat ) {

        this.type = type !== undefined ? type : UnsignedShortType;

        if ( this.type !== UnsignedShortType && this.type !== UnsignedIntType ) {

            console.warn( 'THREE.DepthTexture: DepthFormat requires UnsignedShortType or UnsignedIntType.' );

        }

    } else {

        this.type = type !== undefined ? type : UnsignedInt248Type;

        if ( this.type !== UnsignedInt248Type ) {

            console.warn( 'THREE.DepthTexture: DepthStencilFormat requires UnsignedInt248Type.' );

        }

    }

**Comment by mrdoob** [comment]
Some clean up.

```js
    var type;

    if ( this.format === DepthFormat ) {

        if ( type === undefined ) type = UnsignedShortType;

        if ( type !== UnsignedShortType && type !== UnsignedIntType ) {

            console.warn( 'THREE.DepthTexture: DepthFormat requires UnsignedShortType or UnsignedIntType.' );

        }

    } else {

        if ( type === undefined ) type = UnsignedInt248Type;

        if ( type !== UnsignedInt248Type ) {

            console.warn( 'THREE.DepthTexture: DepthStencilFormat requires UnsignedInt248Type.' );

        }

    }

    this.type = type;
```

It still feels complicated though.

**Comment by mrdoob** [comment]
```js
if ( this.format === DepthFormat ) {

	if ( type !== UnsignedShortType && type !== UnsignedIntType ) {

		console.warn( 'THREE.DepthTexture: DepthFormat requires UnsignedShortType or UnsignedIntType.' );
		type = UnsignedShortType;

	}

} else {

	if ( type !== UnsignedInt248Type ) {

		console.warn( 'THREE.DepthTexture: DepthStencilFormat requires UnsignedInt248Type.' );
		type = UnsignedInt248Type;

	}

}

this.type = type;
```

Better...

**Comment by mrdoob** [comment]
Actually, that last approach will force to user to have to pass the type to the constructor, otherwise they'll get warnings... So the previous approach seems the cleanest so far.

```js
if ( format === DepthFormat ) {

	if ( type === undefined ) type = UnsignedShortType;

	if ( type !== UnsignedShortType && type !== UnsignedIntType ) {

		console.warn( 'THREE.DepthTexture: DepthFormat requires UnsignedShortType or UnsignedIntType.' );

	}

} else {

	if ( type === undefined ) type = UnsignedInt248Type;

	if ( type !== UnsignedInt248Type ) {

		console.warn( 'THREE.DepthTexture: DepthStencilFormat requires UnsignedInt248Type.' );

	}

}

this.type = type;
```

**Comment by mrdoob** [comment]
Actually, that approach would force the user to have to pass a type to the constructor or they would have gotten a warning.

Lets just add this logic in this file:

```js
if ( format === undefined ) format = DepthFormat;
if ( type === undefined && format === DepthFormat ) type = UnsignedShortType;
if ( type === undefined && format === DepthStencilFormat ) type = UnsignedInt248Type;

Texture.call( this, null, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy );
```

We can then move the other checks to `WebGLTextures`. That way we can fix things even if the user changes the `format` and/or `type` after initialisation.

See #9566 for reference.

**Comment by takahirox** [comment]
Agreed!

**Comment by takahirox** [comment]
I've updated.

**Comment by takahirox** [comment]
Ah I realized that I should modify some lines. I'll do that later. Please don't merge until I'll have done.

**Comment by takahirox** [comment]
Done

**Comment by mrdoob** [comment]
Cool! Looks good to me.

@mattdesl looks good?

**Comment by takahirox** [comment]
ping @mattdesl

**Comment by takahirox** [comment]
\ping @mattdesl

**Comment by takahirox** [comment]
Let me send ping again @mattdesl

**Comment by mattdesl** [comment]
Sure! 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
