### PR TITLE
Examples: Fix webgl_buffergeometry_instancing_lambert.

### LINKED ISSUE #18801: shader errors in webgl_buffergeometry_instancing_lambert
Rendering works, but the shaders cause errors:
```
THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog
Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: vHighPrecisionZW  
WebGL: INVALID_OPERATION: useProgram: program not valid
WebGL: INVALID_OPERATION: drawElementsInstancedANGLE: no valid shader program in use
[.WebGL-0x1a706ef5f700]GL ERROR :GL_INVALID_OPERATION : glDrawElementsInstancedANGLE: attempt to draw with all attributes having non-zero divisors
WebGL: too many errors, no more errors will be reported to the console for this context.
```
`git bisect` blames fb7edb931589dc63cef94226ba617d7b55293e00 / #18696 which introduced `vHighPrecisionZW`

##### Three.js version
- [x] Dev
- [x] r114

##### Browser
- [x] Chrome
- [x] Firefox

##### OS
- [x] Linux

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #18801.

### CODE REVIEW

**Comment by Mugen87** [comment]
http://raw.githack.com/Mugen87/three.js/dev43/examples/webgl_buffergeometry_instancing_lambert.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hmm...

@WestLangley I think this example is confusing now as there is a simpler way to do this (just use `InstancedMesh`). Do you think it is still needed?

**Comment by WestLangley** [comment]
I promoted it because it shows how to hack an existing shader, and perhaps more importantly, a custom depth shader.

I also promoted it because it avoids using `String.replace()` to inject code snippets. This approach is more-easily readable.

Those were the original reasons, but I do not mind if you remove the example.

**Comment by mrdoob** [comment]
Right. Maybe we should modify it a bit so it doesn't something that can't be done with `InstancedMesh` alone.

**Comment by WestLangley** [comment]
@donmccurdy had good ideas regarding the examples we should include. Perhaps this can be removed, and someone can file a feature request suggesting new examples add.

**Comment by WestLangley** [comment]
I filed a PR to remove it so as not to compete with the newer `InstancedMesh` feature.

**Pull request merged**
