### PR TITLE
Added LottieLoader

### PR DESCRIPTION
**Pull request by mrdoob**
This pull requests adds a loader for [Lottie files](https://lottiefiles.com/).

Unfortunately we can only use [lottie-web](https://github.com/airbnb/lottie-web)'s canvas renderer and many files won't look correctly, but better than nothing...

Screen Shot 2020-10-29 at 8 48 58 PM

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_texture_lottie.html

### CODE REVIEW

**Comment by Mugen87** [comment]
Perfect timing! A user in the forum lately asked about Lottie and three.js:

https://discourse.threejs.org/t/lottie-animations-with-threejs-any-luck/20100

**Comment by mrdoob** [comment]
Yay!

**Comment by Azure-Phoenix** [comment]
> Unfortunately we can only use [lottie-web](https://github.com/airbnb/lottie-web)'s canvas renderer and many files won't look correctly, but better than nothing...

It's great to have lottieLoader.
But could you let me know what is the reason some lottie files are broken?

**Comment by mrdoob** [comment]
> But could you let me know what is the reason some lottie files are broken?

We use https://github.com/airbnb/lottie-web and their canvas renderer doesn't have full support.

Feel free to report the issues you're seeing on their repo.

**Pull request merged**
