### PR TITLE
Material: Remove skinning.

### LINKED ISSUE #19912: `MeshStandardMaterial().skinning = true` doesn't work with `scene.overrideMaterial`.
##### Description of the problem

Assigning `.skinning = true` doesn't work when the material is assigned to `scene.overrideMaterial`:

`scene.overrideMaterial = new THREE.MeshPhysicalMaterial({skinning: true})`

The material and rendered image behave identically to as if `.skinning === false`.

##### Three.js version

- [ x ] r118

##### Browser

- [x] All of them
- [x] Chrome
- [x] Firefox
- [x] Webkit

### LINKED ISSUE #20318: Outline pass exhibits strange behavior when used with both skinned meshes and non skinned meshes
I'm using an outline pass to highlight objects.
Here is the code for the outline pass:
```
    const outlinePass = new THREE.OutlinePass(
      new THREE.Vector2( this.rendererContainer.offsetWidth, this.rendererContainer.offsetHeight ),
      this.viewer.modelScene,
      this.viewer.camera
    );
    outlinePass.visibleEdgeColor.set(color);
    outlinePass.hiddenEdgeColor.set(color);
    outlinePass.overlayMaterial.blending = THREE.NormalBlending;
    outlinePass.depthMaterial.skinning = true;
    outlinePass.prepareMaskMaterial.skinning = true;
```
If I start with a model with skinned meshes and then replace it with a model without skinned meshes I get a whole bunch of dots.

Outline pass on first model
Screenshot from 2020-09-10 20-39-29

Outline pass on second model
Screenshot from 2020-09-10 20-40-51

There is also an issue when applying the outline pass to a model that contains both skinned meshes and non skinned meshes. I combined the two into one model and loaded it into a fresh three js environment.
As you can see the outline pass is no longer accurate for the first model (the one with skinned meshes)
Screenshot from 2020-09-10 20-42-42

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #20318.
Fixed #19912.

**Description**

This PR changes how skinning in `three.js` works. Similar to `InstancedMesh` which enables instanced rendering,  `SkinnedMesh` enables skinning. A separate material property is not necessary anymore. This simplifies the code and also fixes conceptual issues in context of override materials and post processing.

More details in https://github.com/mrdoob/three.js/issues/18533#issuecomment-806810094.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet! So much red! 😀

**Comment by mrdoob** [comment]
Thanks!

**Comment by will-ca** [comment]
Oh, cool.

Will old applications/configuration files that have `skinning:true` now raise errors though, or is it just deprecated?

**Comment by mrdoob** [comment]
It is deprecated.

**Comment by Mugen87** [comment]
> but skinning:false will stop working, right?

Yes. It's not possible to retain this flexibility.

**Comment by will-ca** [comment]
The last comment on https://github.com/mrdoob/three.js/issues/19912#issuecomment-800110233 ties the failure with `scene.overrideMaterial` to another issue with `SSAOPass`. I didn't file a separate issue, but I also noticed that `SSAOPass` didn't work on `SkinnedMesh()`s.

Does this change also fix that?

**Comment by Mugen87** [comment]
Yes, I think so.

**Pull request merged**
