### PR TITLE
Add test-treeshake script

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: https://github.com/mrdoob/three.js/pull/21292#issuecomment-794216456

**Description**

Added a `test-treeshake` script (suggested by @mrdoob) so it's possible to see the tree-shaked size three.js has for people using bundlers (the `Minified Size` entry in the screenshot).

Screenshot 2021-03-10 at 10 41 40

The example code is the most basic working code, taken from the README.

It's importing three.js like if the user was importing it from the node_modules, so it imports `build/three.module.js`. This means that to test some changes you do locally in the `src/` folder, you have to do:
```
npm run build && npm run test-treeshake
```

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Seems the recent class migration further improved the bundle size:

**Comment by marcofugaro** [comment]
Oh yes! If we remove some other deprecated methods we could get it down even more!

**Comment by mrdoob** [comment]
> Oh yes! Now if we remove some other deprecated methods we could get it down even more!

What other deprecated methods are those? 🤔

**Comment by marcofugaro** [comment]
I actually did that test by removing `Three.Legacy.js` altogether 😅

These only are the blocking methods, if removed they shave off `~10kb`

- [x] if removed, `InstancedBufferGeometry.maxInstancedCount` saves `~0.8kb`
- [x] if removed, `Curve.__arcLengthDivisions` saves `~3.1kb`
- [x] if removed, `Raycaster.linePrecision` saves `~1.42kb`
- [x] if removed, `InterleavedBuffer.dynamic` saves `~2.17kb`
- [x] if removed, `MeshPhysicalMaterial.transparency` saves `~3.5kb`


The other `~30kb` are taken up by the deprecated methods of the classes that can't be tree-shaken because they are always needed such as `WebGLRenderer`, `WebGLShadowMap`, `Light`, `Matrix3`, `Matrix4`, `Vector2`, `Vector3`, `Object3d`, `Mesh`, `Material` and so on. They can't bee tree-shaken because they act like class methods I guess, [rollup example here](https://rollupjs.org/repl/?version=2.45.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBNQUlOJTIwRklMRSUyMColMkYlNUNuaW1wb3J0JTIwJTdCJTIwVXNlZENsYXNzJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMuanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglMjBuZXclMjBVc2VkQ2xhc3MoKSUyMCklM0IlMjAlMkYlMkYlMjAxMjUlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBtYXRocy5qcyU1Q24lNUNuZXhwb3J0JTIwY2xhc3MlMjBVc2VkQ2xhc3MlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKHgpJTIwJTdCJTVDbiU1Q3QlNUN0JTIwdGhpcy5yZXN1bHQlMjAlM0QlMjB4JTIwKiUyMHglMjAqJTIweCUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiUyRiUyRiUyMHRoaXMlMjBpcyUyMG5vdCUyMHJlbW92ZWQlMjBldmVuJTIwaWYlMjBub3QlMjBjYWxsZWQlNUNuVXNlZENsYXNzLnByb3RvdHlwZS5kZXByZWNhdGVkTWV0aG9kJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiUyMGNvbnNvbGUubG9nKCdERVBSRUNBVEVEJyklMjAlN0QlNUNuJTVDbmV4cG9ydCUyMGNsYXNzJTIwVW51c2VkQ2xhc3MlMjAlN0IlNUNuJTIwJTIwcHJvcCUyMCUzRCUyMDMlM0IlNUNuJTdEJTVDblVudXNlZENsYXNzLnByb3RvdHlwZS5kZXByZWNhdGVkTWV0aG9kJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiUyMGNvbnNvbGUubG9nKCdERVBSRUNBVEVEJyklMjAlN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

**Pull request merged**
