### PR TITLE
MeshSurfaceSampler: Add `uv` support.

### PR DESCRIPTION
**Pull request by makc**
this is one of two changes I had to do to MeshSurfaceSampler in order to use it for the [grass effect](https://cdn.discordapp.com/attachments/1102540843660886087/1115870644622598184/1181.png) - let's see if it makes sense to you, and then I will maybe come back with the other one

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by gkjohnson** [comment]
At some point this function should really just return a barycoord value and face index so users can interpolate between whatever buffer attributes they want to. Adding a new argument for every possible buffer attribute doesn't seem sustainable 😅

**Comment by Mugen87** [comment]
I'm afraid not all users know how to do the interpolation correctly. Maybe better when `MeshSurfaceSampler` takes care about this.

**Comment by donmccurdy** [comment]
Adding that method (`sampleBarycentric`?) would be ideal I think, though I'm also fine with this PR as a starting point.

**Comment by makc** [comment]
Oh I did not see 24629. Maybe I could borrow the docs thing from there 🤔

**Comment by makc** [comment]
and now there is failed webxr_vr_sandbox screenshot. not my fault, lol

**Comment by Mugen87** [comment]
Don't worry about this example. It frequently fails in other PRs, too. Maybe regenerating the screenshots would help.

**Comment by LeviPesin** [comment]
Maybe we should add that example to the exceptions?

(The number of exceptions starts to be really large... I should look into it and see what can be fixed (e.g. setIntervals), also need to remove BrowserFetcher for Puppeteer 20)

**Pull request merged**
