### PR TITLE
Editor: Implemented Maya focus

### PR DESCRIPTION
**Pull request by rheros**
Now under maya mode  ,  focus can zoom to object by a fit distance ，the size can set in setting board

### CODE REVIEW

**Comment by mrdoob** [comment]
Live link: https://rawgit.com/rheros/three.js/dev/editor/index.html

**Comment by rheros** [comment]
I can't open the Live link , what is it ?
~~ beacuse of the great wall?hahahahaha

**Comment by mrdoob** [comment]
I've merged #13165 instead, which implemented one of the many things in this PR.

I think it would be better to split your PR in different parts. Lets start by doing a PR that allows the user to change the mouse buttons configuration 👌

**Comment by rheros** [comment]
OK

**Comment by rheros** [comment]
a question , that's means my PR contains too many files and changes , I should pull them one by one ? This the first time I use github ,forgive my stupid ~~~

**Comment by mrdoob** [comment]
Basically, instead of doing a lot of changes all at once, it's better to go step by step.

So, instead of adding a dropdown that changes everything to be more like Maya... How about starting by adding a section so the user can change the mouse buttons configuration for now?

**Pull request closed without merging**
