### PR TITLE
WebXRManager: Add getControllers()

### PR DESCRIPTION
**Pull request by vatro**
Allow direct access to the 'controllers' array / WebXRController instances.

### CODE REVIEW

**Comment by Mugen87** [comment]
Do you mind explaining a bit why you need this (and why the existing `getController()` is not enough)?

**Comment by vatro** [comment]
> Do you mind explaining a bit why you need this (and why the existing `getController()` is not enough)?

Sure!

Generally this would allow a more direct access to the `controllers` array / `WebXRController` instances, meaning more freedom concerning WebXRController creation / inspection etc.

Here is a more specific usage example:
https://github.com/vatro/svelthree/blob/3c2f64b2eb6a5cfbe608c421607547cd541ad2b4/src/xr/utils/XRHandUtils.ts#L149-L175

... the comment there says e.g.:
`// we can get handSpace directly from controller in order to prevent using manager.getHand(i), which will create a new handSpace, but we may not want that.`

This is a rather complex subject + I wrote the code around it few months ago and cannot remember (atm?) every aspect that made me do it 🤔, though I believe it had something to do with the ability of switching from grip-controllers to hand tracking on Oculus Quest via the Oculus Quest Menu without leaving the VR space.

**I would be happy with any code change making `controllers` directly accessible**, it must not be the proposed, specific  `getControllers()` method.

**Comment by mrdoob** [comment]
> This is a rather complex subject + I wrote the code around it few months ago and cannot remember (atm?) every aspect that made me do it 🤔, though I believe it had something to do with the ability of switching from grip-controllers to hand tracking on Oculus Quest via the Oculus Quest Menu without leaving the VR space.

Would be great if you could try to remember the reasoning.

**Comment by vatro** [comment]
> Would be great if you could try to remember the reasoning.

Ok, but first I'll short summarize the reasons already mentioned above:
- generally more freedom concerning WebXRController creation / inspection etc.
- ability to iterate over the `controllers` array and and e.g. filter it by some criteria incl.:
   - ability to reference instances of `WebXRController`

**Comment by mrdoob** [comment]
What we like to know is what is your use case.

It may be that the API already allows you to do what you're to do and we can avoid having multiple ways of doing the same thing.

**Comment by vatro** [comment]
> What we like to know is your specific use case. It may be that the API already allows you to do what you're to do and we can avoid having multiple ways of doing the same thing.

I understand. I remember the exact reason was a pretty complex subject and that I've spent a lot of time figuring it out. I'm also not sure my solution is the the best / only possible one. In order to describe why **exactly** I need direct access to the `controllers` array, I'll need to take quite some functionality apart and reconsider / reevaluate the solutions related to it. Normally I leave descriptive comments near the tricky parts (_like in the example above_), so that would be one hint.

I'll try to figure it out exactly as soon as possible.

_Background:_
At he moment I'm migrating the whole project (https://github.com/vatro/svelthree/issues/39) to the newest three.js version + Vite, primarily aiming to drop the need for a custom (slightly modified) three.js version I was using, see [svelthree-three](https://github.com/vatro/svelthree-three). I'm very happy that all tree-shaking issues with imports from `three/examples/jsm` seem to have been solved meanwhile 👏👍, the only problem I stumbled upon (until now 🤞) is this minor change I did to three.js: added `getControllers()` to `WebXRManager` for direct `controllers` array access.

**Comment by vatro** [comment]
> Do you mind explaining a bit why you need this (and why the existing `getController()` is not enough)?

May I ask if there's maybe some strong reason I'm not aware of why the `controllers` array shouldn't be exposed?

**Comment by Mugen87** [comment]
Closing. Exposing the `controllers` array and thus the raw `WebXRController` instances is not something we want to do. `WebXRController` is considered to be an internal entity. The user-relevant features of `WebXRController` are the different spaces a controller represents. Meaning hand, grip and target ray space. These can be accessed via the methods `getController()`, `getControllerGrip()` and `getHand()` of `WebXRManager`.

**Pull request closed without merging**
