### PR TITLE
Added lower-case Mipmap constants

### PR DESCRIPTION
**Pull request by WestLangley**
Inspired by https://github.com/mrdoob/three.js/issues/6457#issuecomment-508727639.

It is `_gl.LINEAR_MIPMAP_LINEAR`, not `_gl.LINEAR_MIP_MAP_LINEAR`.

The boolean `generateMipmaps` uses the correct nomenclature.

This PR is a first-step. We can discuss the best way to proceed.

### CODE REVIEW

**Comment by Mugen87** [comment]
I think I would already use the new constants in the code base. Just introducing them in `constants` is a very small step.

**Comment by WestLangley** [comment]
This is ridiculous. The PR is too small?

Let's merge PRs and make progress.

**Comment by Mugen87** [comment]
PRs should represent meaningful bundles of work. I don't think it makes sense to just add a few constants to the lib. If you want to make progress, you should already introduce them in the rest of the code base.

**Comment by WestLangley** [comment]
This PR adds support for the new nomenclature ("Mipmap"), while maintaining backwards-compatibility with the old ("MipMap").

I'll file another PR to use the new nomenclature in the source code, while leaving the examples as-is.

If that works, I'll update the examples to use the new nomenclature as a final step.

I think we want to maintain backwards-compatibility, so that means supporting both the new and the old nomenclatures.

Maybe someone has a suggestion for how the old nomenclature can be deprecated...

**Comment by Mugen87** [comment]
Again, I'm against this type of PR style. Remembers me at salami tactics....

**Comment by mrdoob** [comment]
TIL about salami tactics 😁

Doing perfect PRs can be a bit taxing, so I'm okay with solving issues in multiple PRs.

**Comment by mrdoob** [comment]
> Maybe someone has a suggestion for how the old nomenclature can be deprecated...

Maybe we should turn them into getters and log a warning when accessed?

**Comment by WestLangley** [comment]
>Maybe we should turn them into getters

Hmm... how is that done? :thinking:

**Pull request merged**
