### PR TITLE
Glsl improvements

### PR DESCRIPTION
**Pull request by benaadams**
Don't know if you want to do one then the other, but this combines #6335 and #6337

### CODE REVIEW

**Comment by benaadams** [comment]
Has a couple bugs, fixing

**Comment by benaadams** [comment]
Ok good to go on this...

**Comment by mrdoob** [comment]
Sweet! Thanks!

**Comment by WestLangley** [comment]
@benaadams Why did you remove `saturate()`?

As @benhouston [said](https://github.com/mrdoob/three.js/pull/6337#issuecomment-89753436), "saturate is really useful and cleans up the code".

**Comment by benaadams** [comment]
It cleaned up the shader source web viewing the generated output; however only briefly as there are more functions there now : )

Will revisit again when the current influx of changes from @mrdoob complete. I'm liking the idea around @bhouston's #6273 as it could mean the best of both worlds.

**Comment by WestLangley** [comment]
@benaadams OK, thanks.

**Comment by mrdoob** [comment]
@benadams feel free to proceed with changes and PRs. The main changes I was doing are there. Everything based on `BufferGeometry ` should still work. Now I just need to get `Geometry` stuff to work again.

**Comment by benaadams** [comment]
@mrdoob but if ```.fromGeometry``` converted full geometries then you could just convert everything to  ```BufferGeometry``` as the prep step and have a single way of rendering geometries? Thought that's where you were going?

**Comment by benaadams** [comment]
Admittedly noting this PR, it doesn't affect the shaders - I think I might have commented on too many things in the last few days, loosing track of the conversations!

**Comment by mrdoob** [comment]
> @mrdoob but if ```.fromGeometry``` converted full geometries then you could just convert everything to  ```BufferGeometry``` as the prep step and have a single way of rendering geometries? Thought that's where you were going?

Yes, that's what I'm doing.

**Pull request merged**
