### PR TITLE
Unify Loaders

### PR DESCRIPTION
**Pull request by zinefer**
This pull request attempts to unify all loader syntax. 

Bonus:
- new `onStart` event in the `LoadingManager`
- plumb the download manager and crossOrigin all the way down to the texture loaders

Remaining Inconsistencies:
- `BinaryLoader` and `JSONLoader` both return 2 parameters to their callback method, whereas all other loaders return 1.
- `ColladaLoader` still returns an object of objects instead of geometry/materials
- I skipped over the `UTF8Loader` because it looks like it is doing weird things with the `onProgress` event. I'll take a closer look at this one.

Other stuff:
- The `PVRLoader` seems like it was already broken ... Am I mistaken?
- The `SceneLoader` example has a broken shader in dev?
- The `ColladaLoader` has some insane scope going on.

### CODE REVIEW

**Comment by m1ga** [comment]
The changed ColladaLoader works very nice even with r71 and is returning geometry. Would be nice to have this included

**Comment by mrdoob** [comment]
Took a while, but finally managed to merge this...
Thanks!

**Comment by dubejf** [comment]
@mrdoob Did you forget to delete branch unify_loaders in the remote?

**Comment by mrdoob** [comment]
Oh wow. How did that happen...?

**Comment by mrdoob** [comment]
Fixed! Thanks!

**Pull request merged**
