### PR TITLE
 split normal_fragment to normal_fragment_begin and normal_fragment_maps 

### PR DESCRIPTION
**Pull request by sunag**
Follow the same logic of this PR https://github.com/mrdoob/three.js/pull/13277

The problem happen when I use the properties `normalMap` and/or `bumpMap` with other code but needing the `normal` core code.

```
normal_fragment.glsl -> normal_fragment_begin.glsl + normal_fragment_maps.glsl
```

### CODE REVIEW

**Comment by Kan0001** [comment]
Please stop sending me this.. Thanks

**Comment by Kan0001** [comment]
How do I stop?

**Comment by WestLangley** [comment]
This looks OK to me.

@mrdoob As before, it is important that this change be listed in the migration notes.

**Comment by sunag** [comment]
Apparently they are the latest split changes. I test with others properties names and work done.
```javascript
material.alphaMap =
material.aoMap = 
material.aoMapIntensity = 
material.bumpMap = 
material.bumpScale = 
material.emissiveMap = 
material.color =
material.displacementMap = 
material.displacementScale =
material.displacementBias = 
material.emissive = 
material.emissiveMap = 
material.emissiveIntensity = 
material.envMap = 
material.envMapIntensity =
material.lightMap = 
material.lightMapIntensity = 
material.map = 
material.metalness =
material.metalnessMap =
material.normalMap = 
material.normalScale =
material.refractionRatio = 
material.roughness =
material.roughnessMap = 
material.gradientMap = map;
```

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@WestLangley Done!

**Pull request merged**
