### PR TITLE
Box3: Remove some warnings

### PR DESCRIPTION
**Pull request by puxiao**
Related issue: #null

**Description**

I don't think it's necessary to report some warning messages since the parameter target in getCenter()/getSize()/getParameter()/clampPoint() is optional.

### CODE REVIEW

**Comment by Mugen87** [comment]
I'm afraid there is a misunderstanding. The `target` parameter is not optional. It's mandatory. The checks `if ( target === undefined ) {` only exist for backwards compatibility reasons. Hence, just removing the warning makes no sense.

BTW: Next time, please target `dev` with your PR (and not `master`).

**Comment by puxiao** [comment]
Sorry, I accidentally click from the document to view the source code.

-------------

<br>



**I think target is really an optional parameter.**

https://github.com/mrdoob/three.js/blob/dev/src/math/Box3.js

```
getSize( target ) {
		if ( target === undefined ) {
			console.warn( 'THREE.Box3: .getSize() target is now required' );
            target = new Vector3();
		}
		return this.isEmpty() ? target.set( 0, 0, 0 ) : target.subVectors( this.max, this.min );
}
```



```
if(target === undeinfed){ target = new Vector3() }
```

Isn't it an optional parameter?



-----



<br>

```
const sizeVector = new Vector3()
box3.getSize(sizeVector)
```

**PK**

```
const sizeVector = box3.getSize()
```

<br>

Although both of the above codes are correct, but i think the second one is more concise.

<br>

**Comment by Mugen87** [comment]
It's not optional. We don't want to promote this pattern:
```js
const sizeVector = box3.getSize();
```
Users tend to use it in animation loops and produce unnecessary object allocation. The idea is to create the `target` object once and reuse it for all calls.

**Comment by WestLangley** [comment]
@mrdoob @Mugen87 It has been 3+ years, I think we can remove these warnings completely. No?

#13494

**Comment by Mugen87** [comment]
Was that three years ago?! How time flies...

Considering that a lot of legacy code was removed during the ES6 conversion, I think it's okay to remove these blocks, too.

**Comment by puxiao** [comment]
emm...  what should we do now?

**Comment by Mugen87** [comment]
Let's see what @mrdoob prefers.

**Comment by puxiao** [comment]
At the same time, it is revised to ES6?

```diff
- if ( target === undefined ) {
-   console.warn( 'THREE.Box3: .getParameter() target is now required' );
-   target = new Vector3();
- }

+ target = target || new Vector3()
```

**Comment by WestLangley** [comment]
@puxiao If @mrdoob agrees to https://github.com/mrdoob/three.js/pull/21923#issuecomment-851473038, it will look like this:
```js
clampPoint( point, target ) {

	return target.copy( point ).clamp( this.min, this.max );

}
```

**Comment by puxiao** [comment]
This pr ([#21923](https://github.com/mrdoob/three.js/pull/21923)) is wrong, because it should not be `mrdoob:master`.

If @mrdoob agrees, i think it's most appropriate for you to submit a new pr (`dev`) .

**Comment by Mugen87** [comment]
There are multiple occasions in different classes that can be updated if the `target` check becomes obsolete. Better to clean this up with a new PR. But please be patient until @mrdoob states his opinion on this topic.

**Comment by mrdoob** [comment]
> @mrdoob @Mugen87 It has been 3+ years, I think we can remove these warnings completely. No?

Sounds good to me! 👍

**Pull request closed without merging**
