### PR TITLE
CurvePath: `.getPoint()` honors `optionalTarget`

### PR DESCRIPTION
**Pull request by ycw**
to match the abstract class https://github.com/mrdoob/three.js/blob/dev/src/extras/core/Curve.js#L49

### CODE REVIEW

**Comment by Mugen87** [comment]
Do you mind removing the following method from the respective doc pages (en/zh)?

https://threejs.org/docs/index.html?q=curve#api/en/extras/core/CurvePath.getPoint
https://threejs.org/docs/index.html#api/zh/extras/core/CurvePath.getPoint

Now that the signature is equal, there is no need to document it separately anymore.

**Review by Mugen87 — APPROVED** [review]

**Comment by ycw** [comment]
@Mugen87 e2e testing (0) timeouted, now what :) ?

**Comment by mrdoob** [comment]
Running tests again...

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
