### PR TITLE
Add PLY Exporter Documentation Page

### PR DESCRIPTION
**Pull request by gkjohnson**
I added documentation for the PLYExporter using the GLTFLoader documentation as reference.

#### Update
I also updated the GLTFExporter page because it incorrectly showed that the constructor could take default options

### CODE REVIEW

**Review by Mugen87 — CHANGES_REQUESTED** [review]
You have add the new doc page at the following place otherwise it won't be accessible via the side menu. https://github.com/mrdoob/three.js/blob/cce7e3170ed6127123c12fb8d05a2eec03a0d78d/docs/list.js#L376

**Comment by Mugen87** [comment]
For testing: https://rawgit.com/gkjohnson/three.js/ply-exporter-docs/docs/

**Review by Mugen87 — APPROVED** [review]

**Comment by gkjohnson** [comment]
@Mugen87 Fixed, thanks!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
