### PR TITLE
FullScreenQuad: Introduce dispose().

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/issues/18148#issuecomment-565413787

### CODE REVIEW

**Comment by mrdoob** [comment]
Does this conflict with #18149?

**Comment by Mugen87** [comment]
No, it's more or less the actual fix. Otherwise you would have to access a private member of `FullScreenQuad` in order to release the internal geometry. With `dispose()`, it's much nicer.

**Comment by mrdoob** [comment]
But, I mean. Should I revert #18149?

**Comment by Mugen87** [comment]
I think just merging this PR is okay. I've merged #18149 so @drcmda could directly work with `dev` without waiting on my PR 😇

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
