### PR TITLE
DirectGeometry: remove boundingBox & boundingSphere properties

### PR DESCRIPTION
**Pull request by WJsjtu**
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/src/core/DirectGeometry.js#L25-L26
 Are these two properties ever used?
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/docs/api/core/DirectGeometry.html#L68-L77
The doc says they can be calculated, but no such functions are found for `DirectGeometry`.
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/docs/api/core/DirectGeometry.html#L99-L107
Here too.
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/docs/api/core/DirectGeometry.html#L97
And this is not true.

### CODE REVIEW

**Comment by Mugen87** [comment]
Instead of removing the code, i think i would clone the bounding volumes from a geometry object in `DirectGeometry.fromGeometry()`. Something like:
```js
if ( geometry.boundingBox !== null ) this.boundingBox = geometry.boundingBox.clone();
if ( geometry. boundingSphere !== null ) this.boundingSphere = geometry.boundingSphere.clone();
```

**Comment by WJsjtu** [comment]
@Mugen87 Yes, maybe you are right.
Up to now, I haven't found any usage of these two properties.
As the doc writes, DirectGeometry is only used internally to convert from `Geometry` to `BufferGeometry` (as my understanding, the main usage is in `updateFromObject`, `fromGeometry` and `fromDirectGeometry` methods of `BufferGeometry`). Currently, the only use of `BufferGeometry.fromDirectGeometry` method is in this repo is  `BufferGeometry.fromGeometry`, and `BufferGeometry.fromGeometry` is only used in `BufferGeometry.updateFromObject` and `BufferGeometry.setFromObject`. 
The `BufferGeometry.setFromObject` which receives an object with geometry instance of `Geometry` as argument will clone the bounding volume for Points and Line, but call `BufferGeometry.fromGeometry` for Mesh. 
`BufferGeometry.fromGeometry` will create a `DirectGeometry` instance as __directGeometry property of the geometry, then `DirectGeometry.fromGeometry` is immediately called,.
However, `DirectGeometry.fromGeometry` doesn't clone the bounding volume, as a result, the bounding volume of Mesh's geometry won't be cloned in `BufferGeometry.setFromObject` as Points's or Line's (if bounding volume is not null). And this is a little inconsistent in logic. 
The `BufferGeometry.updateFromObject` won't copy the bounding volume as well. 
 Maybe the cloning could be added either in `BufferGeometry.fromGeometry` (my opinion) or `DirectGeometry.fromGeometry` as your suggestion.
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/src/core/BufferGeometry.js#L483-L490

**Comment by Mugen87** [comment]
> However both ways will affect BufferGeometry.updateFromObject, it will clone the bounding volumes only for Mesh?

That's okay since the conversion is only supported for meshes.

**Comment by WJsjtu** [comment]
@Mugen87 Could you explain it a little? 

> The conversion from Geometry to BufferGeometry is only supported for meshes.

https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/src/renderers/WebGLRenderer.js#L1333-L1350
`WebGLObjects.update` in line 1350 will trigger `BufferGeometry.updateFromObject` as:
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/src/renderers/webgl/WebGLObjects.js#L9-L25
So example in [doc](https://threejs.org/docs/index.html#api/objects/Line) will call `BufferGeometry.updateFromObject` with argument instance of `Line`.

**Comment by WJsjtu** [comment]
@Mugen87 Thanks for explanation. I'll close this pull request and make a new one as you suggested.
>Instead of removing the code, i think i would clone the bounding volumes from a geometry object in DirectGeometry.fromGeometry() if present.

**Pull request closed without merging**
