### PR TITLE
Examples: Remove ShaderToon.

### PR DESCRIPTION
**Pull request by Mugen87**
`webgl_marchingcubes` now uses `MeshToonMaterial`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev32/examples/webgl_marchingcubes.html

**Comment by WestLangley** [comment]
I think having examples of NPR shaders is a good idea. Why did you do this?

**Comment by mrdoob** [comment]
Yeah, I agree that keeping that code is good in this case. But it's definitely not good that it's currently hidden in the MarchingCubes example.

Maybe we can do another example similar to https://threejs.org/examples/#webgl_materials but with these custom shaders?

**Comment by Mugen87** [comment]
Okay, closing this one then.

**Pull request closed without merging**
