### PR TITLE
JSM: Clean up for MapControls.d.ts

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Comment by gkjohnson** [comment]
Is there a consistent code style for the `d.ts` files? It seems like there are a couple style variants in the repo, now. I feel like it should stay in line with the style used in the main codebase which might mean using single quotes for strings.

Is there any way to get the eslint rules to apply to the `d.ts` files?

**Comment by Mugen87** [comment]
The `d.ts` files use all soft tabs. I would prefer to clean these files up all at once and not individually. I bet certain editors/IDEs might be able to auto-change this with a search and replace function.

**Comment by gkjohnson** [comment]
@Mugen87 It looks like it might be possible to configure eslint to also lint the `d.ts` files so all of the existing lint rules can be applied and tested:

https://www.npmjs.com/package/@typescript-eslint/parser

Maybe it's worth looking into so we can enforce more consistency among the typsecript definitions?

**Comment by Mugen87** [comment]
Sounds good!

**Comment by mrdoob** [comment]
Sounds good to me too!

**Comment by Mugen87** [comment]
Closing. Let's try it with the eslint approach first before start manually converting files.

**Pull request closed without merging**
