### PR TITLE
Examples: Simplify composer setup in GTAO demo.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: https://github.com/mrdoob/three.js/pull/27317

**Description**

@Rabbid76 This PR simplifies the composer setup by not using MSAA and also rendering with the native resolution instead. 

Ideally, user should not setup the render target for the composer manually. Besides, MSAA is not the best AA technique for (HDR) FX workflows. Yes, the demo does not use HDR but I suppose many users will use `GTAOPass` with a HDR workflow. Probably better to promote something different (like TAA or SMAA/FXAA) depending on the use case.

### CODE REVIEW

**Comment by Mugen87** [comment]
PR: https://rawcdn.githack.com/Mugen87/three.js/5cfb57db2103607e47dfa304111c982009436039/examples/webgl_postprocessing_gtao.html
Dev: https://rawcdn.githack.com/mrdoob/three.js/ebe6f10db9c09568fef785a6c30fdacb54449bd5/examples/webgl_postprocessing_gtao.html

**Comment by Mugen87** [comment]
The new demo runs at 60 FPS on my M2 Pro but on a Pixel 4a it runs with 10 FPS^^. The dev version with 35 FPS.

Low frame rates with low/mid end mobile devices are not surprising. I just wonder if we should keep the example as it is so we have more usable results on a greater variety of devices.

**Comment by Mugen87** [comment]
I think rendering such effects in full native resolution is tricky on mobile devices. Projects have to compute the AO (and other effects) with smaller resolutions in order to avoid fragment-shader bound apps. For now, I don't add the device pixel ration for a better compromise of performance and quality.

**Comment by Rabbid76** [comment]
An AO algorithm is simply an approximation to an integral over a hemisphere. There are different algorithms, some are fast and give poor results, others are slower and give better results. GTAO belongs to the second category. None of the algorithms is ideal and all have advantages and disadvantages.

**Comment by Mugen87** [comment]
Indeed. Against this backdrop it might make sense to keep SSAO which is the fastest of the SSAO, SAO and GTAO according to my first tests. However, it also provides the worst results.

We maybe can ditch `SAOPass` since it is seems more expensive than GTAO and there are some quality issues in its example. It seems the effect tends to darken occluded areas too strong so they become almost black. Can't tell yet if this is okay...

**Comment by Rabbid76** [comment]
@Mugen87 I will have a look. The issue seems to be related to the sample distribution of the gtao and/or denoiser. Or the device resolution is simply not set correctly somewhere. Fortunately, there are still a few days until the next release.

**Comment by Mugen87** [comment]
No need to rush. 👍 

The result of the pass is already impressive! Can't forget how good the AO has looked in the 5K rendering^^.

**Comment by Rabbid76** [comment]
Did some tests. Seems to be an issue with the depth buffer. Ao only (no Denoise):
Screenshot_20231205_192901_Chrome

**Comment by Mugen87** [comment]
The default depth precision of `UnsignedIntType` is at least 16 bits. On desktop, the value is usually higher but on mobile it could be indeed 16 bits. I think we can try this in `setGBuffer()`:
```js
depthTexture.format = DepthStencilFormat;
depthTexture.type = UnsignedInt248Type;
```
In this way, we definitely get 24 bits. That should be sufficient. If no, we can switch to `FloatType`.

**Comment by Mugen87** [comment]
Link for testing: https://rawcdn.githack.com/Mugen87/three.js/a1fdeec4c496a306ea5f7bcfc3be009d4f52c14e/examples/webgl_postprocessing_gtao.html

**Comment by Rabbid76** [comment]
Yep, still the same. I will investigate this further...

**Comment by Mugen87** [comment]
Do you still get the issue with this version?

https://rawcdn.githack.com/Mugen87/three.js/6c820a3abba157edc3b98ff5066a915be525ed9e/examples/webgl_postprocessing_gtao.html

**Comment by Mugen87** [comment]
Respective PR #27320. The trick is using `highp` for the depth samplers.

**Comment by Rabbid76** [comment]
Solved! Thank you so much! ❤️

**Comment by Mugen87** [comment]
Awesome! BTW, with the default composer setup (without MSAA), the GTAO runs at 60 FPS on my Pixel 4a now 👍 .

**Pull request merged**
