### PR TITLE
WebGPURenderer: Fix and clean up

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/26581#discussion_r1310747910

**Description**

Clean up

### CODE REVIEW

**Comment by jrjdavidson** [comment]
the cubemap adjustment example is still broken for me in firefox : 
image

**Comment by sunag** [comment]
I noticed you're using githack, have you tried testing locally?

**Comment by jrjdavidson** [comment]
i just tried that and got the same result. Note that I don't run a local version often so I am worried I might be doing something wrong!
image

**Comment by sunag** [comment]
Maybe it can be the Firefox version, you already tried with 117.0?

**Comment by jrjdavidson** [comment]
that was it. looks great!

**Pull request merged**
