### PR TITLE
Fix Code Style and Bugs in Module Examples

### PR DESCRIPTION
**Pull request by gkjohnson**
- Adds missing semicolons and some other code style issues
- Fixes lingering references to `THREE.` in `MapControls`, `OrbitControls`, and `TrackballControls`, making them unusable.

### CODE REVIEW

**Comment by donmccurdy** [comment]
I'm not sure at what point we're ready to call the ES modules the canonical versions (@mrdoob any preference? case by case or all at once?). There are [PRs open against GLTFLoader](https://github.com/mrdoob/three.js/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+GLTFLoader+in%3Atitle), and we'll presumably want to re-run the script if we merge them as-is. IMO, once we start making hand edits to the ES modules, we should begin autogenerating the UMD files and putting the header on them to direct future PRs to the right place.

Any issues that could be fixed in [`modularize.js`](https://github.com/mrdoob/three.js/blob/dev/utils/modularize.js) we should fix there.

**Comment by gkjohnson** [comment]
Updated the script in #15582

**Comment by gkjohnson** [comment]
Would it make sense to move only _some_ of the example modules over be the canonical versions? Those that aren't in active development or don't have open PRs, for example. It may be best to make the conversion when it seems convenient for each script otherwise it'll be hard to find the moment to turn it on for every completed module. `MapControls` and `TransformControls` don't have anything open for them, for example.

I'm thinking something like an ignore list in the convert-examples rollup config?

**Comment by donmccurdy** [comment]
> Would it make sense to move only some of the example modules over be the canonical versions? 

I'm OK with that, but would defer to @mrdoob... having an ignore list and appropriate headers on the files that aren't meant to be edited (whether that's in `js/` or `jsm/`) would also help manage the transition.

If there aren't that many open PRs against examples and we'd rather do this all at once, I'm fine with that too.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> I'm not sure at what point we're ready to call the ES modules the canonical versions (@mrdoob any preference? case by case or all at once?). 

I would go case by case I think. Seems like we can start with controls.

**Comment by gkjohnson** [comment]
> I would go case by case I think. Seems like we can start with controls.

Great -- when I get a chance I'll add an ignore list for the module conversions and add appropriate banners to the non-canonical versions of the example scripts.

**Pull request merged**
