### PR TITLE
WebXR: Added XRButton

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

Adds a new XRButton class which creates a `immersive-ar` or a `immersive-vr` session depending on availability.

This allows making projects that run in passthrough headsets and also on vr headsets.

Side note:
I wonder if it was a mistake to call `immersive-ar` to the session that mobile phones support.
Maybe it should have been called `mobile-ar`?

/cc @toji @cabanier @elalish

### CODE REVIEW

**Review by cabanier — COMMENTED** [review]
LGTM

**Review by cabanier — COMMENTED** [review]
LGTM

**Review by cabanier — COMMENTED** [review]
Most of these experiences are VR only. Maybe there should be a way to prefer VR instead of AR for such sites.

**Comment by mrdoob** [comment]
What makes you think they are VR only?

The problem is that I've not figured out how to make the background transparent yet 😅

WIP

**Comment by cabanier** [comment]
> What makes you think they are VR only?
> 
> The problem is that I've not figured out how to make the background transparent without passing `alpha: true` to the renderer yet 😅

Can you not set a background? WebXR are cleared to transparent black.

**Comment by mrdoob** [comment]
Ok, figured it out...
Turns out there some code around for it already.

**Comment by cabanier** [comment]
So this is a new button that prefers AR mode? If so LGTM

**Review by cabanier — COMMENTED** [review]
LGTM. It doesn't look like I have permission to officially sign off

**Pull request merged**
