### PR TITLE
sea3d more a bit optimization and usability

### PR DESCRIPTION
**Pull request by sunag**

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by sunag** [comment]
Thanks! I went through inattentive the PR was to `dev` branch! I request another PR to the `dev` or has no problems?

**Comment by WestLangley** [comment]
This was to `master`.

**Comment by sunag** [comment]
Sry! it was meant to `dev`.

**Comment by mrdoob** [comment]
That's OK. At the moment `master` and `dev` are in sync.

**Pull request merged**
