### PR TITLE
Bring dat.gui inside vr

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

More work on bringing interactive HTML elements inside VR.

Screenshot 2021-04-22 at 10 53 55

Live link: https://raw.githack.com/mrdoob/three.js/webxr/examples/webxr_vr_sandbox.html

### CODE REVIEW

**Comment by Mugen87** [comment]
Tested this on a Oculus Quest and the interaction works fine. The only thing I have notice is that the labels of the GUI are somewhat hard to read from a steep angle. The text gets more sharp if move my position in front of the GUI.

Would it makes sense to orient the plane always towards the camera's position?

**Comment by mrdoob** [comment]
> Would it makes sense to orient the plane always towards the VR camera's position?

I'm planning on making these panels grabbable.
So we can grab it with one hand and mode the sliders with the other 🤓

**Comment by Mugen87** [comment]
That should definitely help^^.

**Comment by gkjohnson** [comment]
Looks great! I was looking for something like this awhile ago. My only comment is that the name `InteractionManager` feels a little generic. Maybe `XRInteractionManager` to be consistent with the other XR classes? Or something related to the event forwarding it does like `XRInteractionDispatcher`? Either way I'm excited to see this.

**Comment by mrdoob** [comment]
@gkjohnson I was on the middle of a complete API redesign 😅
Would you like to have another look? (I'll add pointer events next)

**Comment by Mugen87** [comment]
Tested the demo on `dev` today again and it works fine 🎉 . Also like how the GUI is positioned now!

**Comment by Gabana** [comment]
Hey Ricardo, the link to the example doesn´t work. Is it still uploaded? if so, can you please update it? Thanks!

**Comment by mrdoob** [comment]
@Gabana https://threejs.org/examples/webxr_vr_sandbox.html

**Pull request merged**
