### PR TITLE
DecalGeometry: Transform normal with normal matrix

### PR DESCRIPTION
**Pull request by WestLangley**
`transformDirection()` should not be applied to normal vectors, unless under certain conditions. The normal map should be applied, instead.

### CODE REVIEW

**Comment by WestLangley** [comment]
Related: Is there a reason decals are added to the scene in `webgl_decals.html`, instead of to the mesh to which they are applied?

Currently, if the mesh is rotated, the decals do not.

**Comment by Mugen87** [comment]
In `webgl_decals`, `transformDirection()` is also used in `checkIntersection()` to transform normals. Does it make sense to update this code as well?

https://github.com/mrdoob/three.js/blob/19e79dcbcd115a6e0452cfa31543806fe9a1dc79/examples/webgl_decals.html#L191

**Comment by Mugen87** [comment]
> Is there a reason decals are added to the scene in webgl_decals.html, instead of to the mesh to which they are applied?

Not that I am aware of. It would seem more natural to add the decals to the logical parent object.

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
@Mugen87 Doing `mesh.attach( decal )` instead of `scene.add( decal )` works well, although `.attach()` only supports a uniformly-scaled parent mesh (the case here). Do you think such a change to the example is worth it?

**Comment by Mugen87** [comment]
Yes, using `attach()` looks like a nicer workflow.

**Pull request merged**
