### PR TITLE
RapierPhysics: Clean up

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: -

**Description**

Just a clean up.

### CODE REVIEW

**Comment by mrdoob** [comment]
After this PR `physics_rapier_instancing` only renders for 1 frame and then everything disappears.
No error in the console.

**Comment by mrdoob** [comment]
Reverting...

**Comment by mrdoob** [comment]
I'll do some of the changes locally and make sure nothing breaks.

**Comment by LeviPesin** [comment]
Yeah... I will test it and file a new PR.

**Pull request merged**
