### PR TITLE
Geometry splitter

### PR DESCRIPTION
**Pull request by Itee**
A little contribution about a tool that, i hope, will be useful !

A geometry splitter that allow to "hide" a part of a mesh to look inside. Helpful when you work with buildings and you need to see inside. It manage, Geometries, BufferGeometries and indexed BufferGeometries.

There are lot of things to improve/support but it is working for many case. But take a look, play a bit, and have fun !

The GeometrySplitter and related are under example directory.

Best regards,
Tristan

### CODE REVIEW

**Comment by mrdoob** [comment]
https://rawgit.com/TristanVALCKE/three.js/GeometrySplitter/examples/webgl_geometry_splitter.html

**Comment by WestLangley** [comment]
One suggestion would be to avoid cloning materials and instantiating meshes with mouse events.
```javascript
console.log( app.renderer.info.memory.geometries ); // 5924
```
Did you consider using [clipping planes](https://threejs.org/examples/webgl_clipping.html), instead?

**Comment by TristanVALCKE** [comment]
The clipping planes is a very good alternative if you need to "hide" a part of a mesh, using... planes !

The idea behind this splitter is more like a boolean modifier (blender like or clipping advanced) that can be use with any mesh as "clipper" and got the splitted part, the union or the difference (this feature is not implemented yet but is based on meshes intersections, so it won't be difficult to implement it, i think)

I will update cloning and fix geometries...

**Comment by mrdoob** [comment]
Would this allow people doing Fruit Ninja? 😀

I think I would call it `SplitModifier` though.

https://github.com/mrdoob/three.js/tree/dev/examples/js/modifiers

**Comment by TristanVALCKE** [comment]
Ah ah ah this allow doing donuts Ninja ! 

In my mind this is just a pre-modifier for a list of boolean modifier. In final this would be able to get a splitting mesh and a mesh to split with a operator type ( union, difference etc...). This will be helpful for modeling.

I will update the name to SplitModifier, and move it to the right folder.

**Comment by WestLangley** [comment]
So would you say this is Constructive Solid Geometry?

The demo is more impressive, IMO, in wireframe using `BoxGeometry`, for example.

**Comment by TristanVALCKE** [comment]
Yes at terme this could become a kind of Constructive Solid Geometry ( but maybe this is already implemented in editor, i didn't check the modifier operators inside, sorry i'm landing... )

**Comment by NicolasRannou** [comment]
Any plan on merging this one soon? I'm looking for an alternative to plane clipping as I want to clip my mesh along a "curved plane geometry" (that can be divided in N planes)

Thanks!

**Comment by Itee** [comment]
I need to work a little on this i few days (maybe this night), because it is not currently able to manage Group or nested children properly !

About you N divider planes be aware that the removed geometry cannot currently be reused (because it just not existing). You will need to use the primary geometry with each SplitModifier on it ( a case that i didn't test ! ). So a feedback will be appreciate ! 

One another good thing to known about this "tool" instead of using clippings plan is about raycasting. Ray will hit hidden geometry using clippings, but not with this one !

I will try to add an input field to allow to load other geometry in view to test what's happen, with "real" Mesh !

**Pull request closed without merging**
