### PR TITLE
Examples: Improved collada skinning example

### PR DESCRIPTION
**Pull request by Mugen87**
This PR will make the Collada skinning example more...entertaining 😊 .

Besides, the new model has a perfect animation loop.

### CODE REVIEW

**Comment by WestLangley** [comment]
Entertaining!

Your scene has only ambient light, and it is set way too high. Try this:
```
var ambientLight = new THREE.AmbientLight( 0xffffff, 0.2 );
scene.add( ambientLight );

var directionalLight = new THREE.DirectionalLight( 0xffffff, 0.8 );
directionalLight.position.set( 1, 1, 0 );
scene.add( directionalLight );
```
The Phong specular reflectance is zero, which does not make sense since the shininess is over 100.

Set the specular reflectance to a value between ( .05, .05, .05 ) and ( 0.1, 0.1, 0.1 ).

**Comment by Mugen87** [comment]
Indeed, that's a better light setup...

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
This is just a matter of personal preference, but I thought I'd share it anyway. I actually prefer the following lighting pattern for viewing a model:
```
var ambientLight = new THREE.AmbientLight( 0xffffff, 0.2 );
scene.add( ambientLight );

var pointLight = new THREE.PointLight( 0xffffff, 0.8 );
camera.add( pointLight );
scene.add( camera );
```
This allows the scene to be uniformly lit regardless of the viewing direction. Otherwise, from half of the view directions, illumination from only ambient light looks (IMHO) terrible.

---

Also, I have a question: Why do so many of the demos have
```
renderer.sortObjects = false;
```
Users copy these examples and do not understand the implications of this. I think we should include this line only when there is a compelling reason to do so.

**Comment by Mugen87** [comment]
> Why do so many of the demos have renderer.sortObjects = false;?

Now that you mention it...Yeah, we should check this if we work on an example.

**Comment by mrdoob** [comment]
> Users copy these examples and do not understand the implications of this. I think we should include this line only when there is a compelling reason to do so.

Agreed!

**Comment by jostschmithals** [comment]
> I actually prefer the following lighting pattern for viewing a model:

Even though an artist would certainly prefer a more elaborate light setup (because only a front light is a little boring ;) ), I fully agree that coupling a point light to the camera is the best basic pattern which should be used in most of the examples.

> Users copy these examples and do not understand the implications of this

When I started with three.js some time ago by studying the examples I noticed that there seem to be many apparently unneeded code lines (for example those you mentioned, but not only those), which might have gotten there by copying&pasting from one example to another. Since it is often hard for a beginner (like me) to realize which lines are really needed and which lines are only "noise" I think this is an important question, and therefore the revision of as many examples as possible from this point of view is already on my todo list (for me a good opportunity to learn more). At the moment I have no time to contribute, but this will change soon.

**Comment by Mugen87** [comment]
Sounds great! From my point of view, the examples have a high educational value and are an important asset of the project. It's good when we take care for them 😊 .

**Comment by WestLangley** [comment]
@Mugen87 Did you convert this example to `dae` format yourself? Did you have to do anything unusual to get it to animate properly with three.js? I see that the 'bind shape matrix' is a reflection matrix.

**Comment by Mugen87** [comment]
When I remember correctly, I've just exported the model from Blender (with the built-in Collada exporter).

**Pull request merged**
