### PR TITLE
Helpers: Ensure light helpers are not frame-late.

### LINKED ISSUE #14801: DirectionalLightHelper is a frame late at best
##### Description of the problem

Manually calling `someHelper.update()` is usually a frame late because the helper users `matrixWorld` which isn't updated until rendering

http://jsfiddle.net/greggman/0oxvetb4/

This has other issues as well. If you make a directional light, set a target, **call update**, then render (never calling update again because you're never changing the light) the helper will never be correct.

http://jsfiddle.net/greggman/en0jco1g/

Should it maybe switch to using a `needsUpdate` style instead of an explicit call to `update`? That would let it sync with the scene. It would also mean nothing needs to be done for a static light

##### Three.js version

- [X] Dev
- [X] r95

##### Browser

- [x] All of them

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #14801.

**Description**

Ensures the world matrices of lights and targets are up-to-date when evaluated in light helpers.

### CODE REVIEW

**Comment by Mugen87** [comment]
Just want to clarify that this issue can't be fixed by overwriting `updateMatrixWorld()`. Doing this does _not_ guarantee that the world matrix of the reference object (the light) is up-to-date.

**Comment by mrdoob** [comment]
> Just want to clarify that this issue can't be fixed by overwriting `updateMatrixWorld()` in the helpers. Doing this does _not_ guarantee that the world matrix of the reference object (the light) is up-to-date.

Hmm, in what case the reference object's wold matrix won't be up to date by the time the helper's `updateMatrixWorld()` runs?

**Comment by acu192** [comment]
This is **EXACTLY** the PR I was planning to send in when I wrote issue #21608. Nice work!

Well, one difference actually: I would do the same change for `PointLightHelper`, address this line:
https://github.com/mrdoob/three.js/blob/5f8443265024b831a9de5a5177bc5aed4f4093ee/src/helpers/PointLightHelper.js#L15

**Comment by acu192** [comment]
PS: This is a big problem being addressed here. It's easy to create a light helper that shows you the wrong thing, in which case it does the **opposite** of helping (it hurts you).

The main fix here is calling `this.light.target.updateWorldMatrix(...)` in the same places that you call `this.light.updateWorldMatrix(...)`. Consistency in updating the light's matrix and target's matrix is kind of important. :) I ran into this bug in my project and it seems (based on the other issued filed) others have as well.

Granted, the long-term solution is to remove targets from lights (and use the light's quaternion instead), but until that solution is in-place, we need to address the *current* bug. This PR fixes the *current* bug and does not add any breaking changes (at least, not that I can imagine).

**Comment by Mugen87** [comment]
I've updated  `PointLightHelper` as requested!

**Comment by acu192** [comment]
@mrdoob Do you think we get this in the r128 release?

**Comment by Mugen87** [comment]
BTW: This is what users do in order to desperately make light helpers work:
````js
const lightHelper = new THREE.DirectionalLightHelper(light, 10);
lightHelper.name = 'lightHelper';
scene.add(lightHelper);
lightHelper.parent.updateMatrixWorld();
lightHelper.update();
````
From: https://discourse.threejs.org/t/directionallight-shadow-camera-helper-pointing-in-the-wrong-direction/27392

With this PR, the user could just add the helper and things work out-of-the-box.

**Comment by acu192** [comment]
@mrdoob Anything we can do to help you feel comfortable with this?

Excited to get it in r136. 😉

**Pull request merged**
