### PR TITLE
moved `flipY = false` to CubeTexture constructor

### PR DESCRIPTION
**Pull request by fordacious**
Fixes https://github.com/mrdoob/three.js/pull/6723#issuecomment-120873527.

### CODE REVIEW

**Comment by WestLangley** [comment]
You have a tabs-spaces problem.
You need to modify the clone() method, also.
You need to check the library and examples for instances where `flipY` was set unnecessarily. One is the ocean example, but there may be others.

**Comment by mrdoob** [comment]
I'm curious of what change in #6723 produced this issue.

**Comment by WestLangley** [comment]
> I'm curious of what change in #6723 produced this issue.

Good question. I am pretty sure the problem existed previously.

**Comment by WestLangley** [comment]
Thank you @fordacious and @mrdoob.

**Pull request merged**
