### PR TITLE
I updated PointerLockControls.js: added setters, getters, configuration and flyMode

### PR DESCRIPTION
**Pull request by Lukas-**
I added to PointerLockControls following options:
- flyMode
- enable/disable flyMode function
- enable/disable jump function
- configuration with setters and getters for: gravity, mass, jump velocity, camera altitude
- section with default values for mass and other factors
- getCameraRotation function
- getCameraPosition function

### CODE REVIEW

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#4076

**Comment by stefan3d** [comment]
I would like to activate the flymode in an example somthing like this:http://chewbonga.com/simple-world-threejs/
How do i manage this?
Is there an example for the use of the flymode?

**Comment by Lukas-** [comment]
Yes, I'm an author of this PullRequest. I can give you link to the project which uses FlyMode but only via private message (I don't want Google to index it). 

So please give me some contact information to you.

**Comment by stefan3d** [comment]
Hi Lukas,
you can conatct me via mail: mail@3dbetrieb.de
Tank you very much!
Best regards Stefan

**Comment by Lukas-** [comment]
Link sent.

**Pull request closed without merging**
