### PR TITLE
simple skeletal animation / skinning example without blending.

### PR DESCRIPTION
**Pull request by antont**
This is the same as the skinning-blending example but just simplified: no blending, no BlendCharacter code etc.

I've often encountered the need to test a model with skeletal animation quickly and it has been annoying to not have a template / code for that ready.

Also in the editor it doesn't seem to work: so far when I've tried to enable skinning there, the model has just disappeared.

So I stripped the BlendCharacter code from the nice example to have this simple thing that just loads a skinned mesh and plays back an animation from it.

If this is wanted in I can clean it up / simplify it further a bit and add to the examples listing if it makes sense.

Oh and I've been running this now actually with the very useful skeleton helper on - should probably resurrect the GUI back in enough so that there'd be a toggle for that at least. Perhaps the anim play/stop too.

### CODE REVIEW

**Comment by mrdoob** [comment]
> Oh and I've been running this now actually with the very useful skeleton helper on - should probably resurrect the GUI back in enough so that there'd be a toggle for that at least. Perhaps the anim play/stop too.

That'd be nice yes!

In fact, if you have another model/animation that'd be extra helpful!

**Comment by antont** [comment]
Oops - was starting to finish this and noticed that a similar simple no-blendcharacter skeletal animation example already exists, is just not included in the examples menu I think:

http://threejs.org/examples/webgl_skinning_simple.html

I think my name, `webgl_animation_skinning.html` for it is better (to match others named `webgl_animation_*`) -- and reusing that fancier marine model & nice walk animation may or may not be a good idea for the simple example -- but otherwise this pullreq is moot as the equivalent code was there already.

Will leave open for comments & to think myself too if there are good ideas what to do about this. If nothing else will close this as unnecessary tomorrow or so.

**Comment by mrdoob** [comment]
Well. I'm mostly interested about new skinned models so we have more to test with.

**Comment by antont** [comment]
Ah, I get you now.

We have quite many of those - at least a set of 4 different humans (originally from makehuman, have motioncap animations put to those in Blender) and ~10 animals (deer, osprey, a couple fish, ducks :)

Those are all creative commons licensed, created with some public funding a few years ago within realxtend.org .. originally for Ogre, now targeting mostly three.js.

Those animal blends (and Ogre exports) are in:
https://github.com/realXtend/chesapeakebay/tree/master/objects

The humans I still need to put to a good place.

Screenshot of the deer which worked correctly with the **old exporter**:
https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/3D-UI_-_WebTundra_-_User_and_Programmers_Guide#Exporting_3D_scenes_from_authoring_applications

Those animals are I think quite interesting as have very different skeletons: four legged deer, wings for the birds etc.

My problem now is that I haven't gotten any of those skels+anims -- nor the marine in three's repo -- to work with the **new exporter** yet. Just reported current status in a comment in #6050 . If find out how to get those working will document that.

Those blends are free to put to the three.js repo too but perhaps better just to point to their own repos to not bloat the three.js one?

**Comment by antont** [comment]
Closing as useless as such a simple example was already in the repo. It could be perhaps renamed & added to the examples menu but that's another story. Also having more models to test with etc. is a different topic, good that info about that is here now for reference anyways.

**Pull request closed without merging**
