### PR TITLE
Cameras: add viewOffset.enabled flag

### PR DESCRIPTION
**Pull request by WestLangley**
... as proposed in https://github.com/mrdoob/three.js/pull/12158#issue-256453616.

Note that `CombinedCamera` is broken in this regard. I do not want to spend any time with this if `CombinedCamera` is going to be removed. Actually, I would be surprised if anyone is using `viewOffset` with combined camera.

### CODE REVIEW

**Comment by Mugen87** [comment]
I think we should remove `CombinedCamera` and the corresponding example. If users complain, we can still add the methods you proposed in https://github.com/mrdoob/three.js/issues/11904#issuecomment-327970550

**Comment by WestLangley** [comment]
>add the methods you proposed

Please have a go at it if you want. :)

However, I am not sure there is an intuitive way to compute the parameters of one camera type from the other. Consequently, I am not sure the methods even make sense. If fact, I am pretty sure they don't.

I think users should manage their cameras themselves.

**Comment by Mugen87** [comment]
I just have this behavior of tools like Blender in mind, where you can switch between both camera types.

> I think users should manage their cameras themselves.

That would be the easiest way for us 😁

**Comment by mrdoob** [comment]
What do you think about removing the `null` logic and always create the `view` object with `enabled: false`?

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/pull/12158#issuecomment-328626680

**Comment by WestLangley** [comment]
I also do not like the view offset parameterization. The parameterization is specific to one particular use-case (multiple screens), but it has other uses for which that parameterization does not make sense.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
