### PR TITLE
Editor: GLSL error feedback & minification

### PR DESCRIPTION
**Pull request by tschw**
Depends on #6801, adds the last three commits.

### CODE REVIEW

**Comment by tschw** [comment]
Re-pushed: Simplification, a fixed typo and some forgotten whitespace.

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by benaadams** [comment]
btw @zz85 has done a interesting and very useful Emscripten pure js port of [glsl-optimizer](http://zz85.github.io/glsl-optimizer/) not what we necessarily want for easy to understand/learning glsl but something to bear in mind

**Comment by tschw** [comment]
Nice - and it's fast! We should integrate it as a stage before the minifier, which will then declutter the output. Ultimately, both would run when "Publish" is clicked, but we'd need a settings panel to make it all optional.

**Pull request merged**
