### PR TITLE
Added TriangleGeometry Class

### PR DESCRIPTION
**Pull request by pxninja**
**Description**

I noticed [Three JS primitives](https://threejs.org/manual/#en/primitives) do not include a triangular plane. This PR adds that primitive with the following parameters: **width**, **height**, **skew**, and **detail**.

While the default parameters create an _equilateral_ triangle, adjusting the width / height / skew will produce any type (isosceles, scalene, right, obtuse). Increasing the detail uniformly subdivides the plane, where "detail" is the number of _edge_ divisions, and the number of facets per division is ( detail + 1 ) ^ 2.

Example of uniform subdivision (aka. what to expect):

image

### CODE REVIEW

**Comment by pxninja** [comment]
After giving it some thought, I can see how normalizing the height could be confusing. Height is now a literal unit and the UV maps to the base and apex of the geometry.

**Comment by Mugen87** [comment]
Do you mind moving `TriangleGeometry` into https://github.com/mrdoob/three.js/tree/dev/examples/jsm/geometries?

This kind of geometry generator has not been requested so far so I do not see it as a core module.

**Comment by pxninja** [comment]
Moved, as requested. For what it's worth, because a triangle is the most fundamental geometry, I (personally) would expect a triangle to be a primitive. Coupled with it being the only geometry that easily creates the Three JS logo, it seems like src/geometry/ is a better fit, but not a big deal either way.

**Comment by linbingquan** [comment]
related: https://github.com/mrdoob/three.js/pull/29690#discussion_r1807127180

**Comment by linbingquan** [comment]
UVsDebug: 
image

**Comment by linbingquan** [comment]
How about do this.

1. Make `detail` default value is `1`
2. Rename `detail` to `segments`

```diff
--- a/examples/jsm/geometries/TriangleGeometry.js
+++ b/examples/jsm/geometries/TriangleGeometry.js
@@ -3,7 +3,7 @@ import { Float32BufferAttribute } from '../core/BufferAttribute.js';

 class TriangleGeometry extends BufferGeometry {

-       constructor( width = 1, height = Math.sqrt( 3 ) / 2, skew = 0, detail = 0 ) {
+       constructor( width = 1, height = Math.sqrt( 3 ) / 2, skew = 0, segments = 1 ) {

                super();

@@ -13,7 +13,7 @@ class TriangleGeometry extends BufferGeometry {
                        width: width,
                        height: height,
                        skew: skew,
-                       detail: detail
+                       segments: segments
                };

                // buffers
@@ -25,18 +25,18 @@ class TriangleGeometry extends BufferGeometry {

                // vertex helper variables

-               const segments = Math.max( Math.floor( detail + 1 ), 1 );
+               const _segments = Math.max( Math.floor( segments ), 1 );
                const offsetX = width / 2;
                const offsetY = height / 3;

                // vertices, normals, and uvs

-               for ( let i = 0; i < segments + 1; i ++ ) {
+               for ( let i = 0; i < _segments + 1; i ++ ) {
```

**Comment by pxninja** [comment]
- `details` is now `segments`
- The UV looks correct to me ... is there something I'm missing?

**Comment by pxninja** [comment]
I'm considering updating the class to minimize UV distortion. Is this closer to what you're expecting @linbingquan ?
```diff
		// vertex helper variables

+		const widthHalf = width / 2;
+		const skewHalf = skew / 2;

-		const offsetX = width / 2;
+		const offsetX = ( width + widthHalf + skewHalf ) / 3;
		const offsetY = height / 3;

+		const length = Math.max( Math.abs( skewHalf ) + widthHalf, width );

+		const maxU = Math.min( length / height, 1);
+		const maxV = Math.min( height / length, 1);

+		const offsetU = skew + width > 0 ? (1 - maxU) / 2 : (length - width) / length;
+		const offsetV = (1 - maxV) / 2;

		// vertices, normals, and uvs

		for ( let i = 0; i < segments + 1; i ++ ) {

			for ( let j = 0; j < i + 1; j ++ ) {

-				const uvX = ( i + j ) / segments / 2;
-				const uvY = ( i - j ) / segments;
+				const normX = ( i + j ) / segments / 2;
+				const normY = ( i - j ) / segments;

-				const x = uvX * width - offsetX + uvY * skew / 2;
-				const y = uvY * height - offsetY;
+				const x = normX * width + normY * skewHalf;
+				const y = normY * height;

+				const u = maxU * x / length;
+				const v = maxV * normY;

-				vertices.push( x, y, 0 );
+				vertices.push( x - offsetX, y - offsetY, 0 );

				normals.push( 0, 0, 1 );

-				uvs.push( uvX );
-				uvs.push( uvY );
+				uvs.push( u  + offsetU, v  + offsetV );

			}

		}
```

**Comment by linbingquan** [comment]
> I'm considering updating the class to minimize UV distortion. Is this closer to what you're expecting @linbingquan ?

In both test cases, there was no problem with the results.

| new TriangleGeometry(1, Math.sqrt( 3 ) / 2, 0, 4) | new TriangleGeometry(1, 1, 0, 4) |
| ----------- | ----------- |
| image| image|

**Comment by pxninja** [comment]
@Mugen87 - Anything else needed on my end? Would love to get this merged.

**Comment by mrdoob** [comment]
Curious to hear about use cases for this geometry...?
I just can't think of one (except generating the library logo 😅).

**Comment by Mugen87** [comment]
We've been a bit more strict when adding new modules to the repository compared to earlier days. With that policy in mind, I tend to place `TriangleGeometry` in a third-party repository or just share it as a Gist. 

IMO, the existing geometry generators in the repository are more than sufficient.

**Comment by pxninja** [comment]
Completely understand (and appreciate) you both safeguarding the quality of Three JS. If this were my project, I would do the same.

@mrdoob - I am currently using this in a project, which is how I noticed its absence. Specifically, I'm generating the base shape and programmatically manipulating the vertices, which allows me to instantiate game assets without having to model each. That aside, any planar example where 1 less vertex allows 25% more stuff (think grass, particle shards, billboards, etc.). This kind of efficiency is notable in procedural applications. Generating the library logo was more of a discovery than the intention.

@Mugen87 - I agree the existing generators capture _many_ applications.

Three JS is awesome. I love it. Triangles are a primitive. The library doesn't have them. And I respect everyone's time enough to not waste it on a feature request I could do, allowing core contributors to focus on more important things. If triangles are something the library would like to consciously omit, please let me know. I'm trying to be helpful (not a nuisance).

**Comment by WestLangley** [comment]
>Triangles are a primitive. The library doesn't have them.

To be fair, currently any regular polygon can be generated, and then optionally transformed.

```js
const geometry = new THREE.CircleGeometry( 1, 3 ); // triangle

geometry.rotateZ( Math.PI / 2 );
geometry.translate( 0, 0.5, 0 );
geometry.scale( 10, 10, 1 );
```

**Comment by pxninja** [comment]
> To be fair, currently any regular polygon can be generated, and then optionally transformed.

Charitably, I take your point. Also, I would have hoped the context clarified I was talking about a generator akin to the one in this PR.

**Comment by Mugen87** [comment]
@pxninja We do appreciate the contribution but it seems the consensus is to maintain such a generator not in this repository. 

I recommend you put `TriangleGeometry` in a separate repo and share the module as a `npm` package so developers can easily use it in their projects. If that is too much maintenance effort, you can still share the module as a simple Gist. In the three.js forum, there is a `Resource` category where developers present or share code that might be useful for others. That would be a good place to promote `TriangleGeometry`.

https://discourse.threejs.org/c/resources/8

**Comment by pxninja** [comment]
Should anything change, the code is available.

**Pull request closed without merging**
