### PR TITLE
determine if normals are flipped by a reflection in the normalMatrix instead of object.matrixWorld

### LINKED ISSUE #14372: Negative scale in camera matrix turns models inside out
Objects are not turned inside out when giving them a negative scale thanks to the fixes in #12787 However when setting a negative scale on the camera, the scene is turned inside out regardless.

Looking at the changes made in #12787 I believe that instead of taking the determinant of `object.matrixWorld` it should be the determinant of `object.modelViewMatrix` which includes the camera view transform.

Local testing confirms that this resolves the issue.

### PR DESCRIPTION
**Pull request by Korijn**
Determine if normals are flipped by a reflection in the normalMatrix instead of object.matrixWorld.

Fixes #14372.

This makes more sense, since the normalMatrix is the end-all transform that determines if the normals will be flipped or not. It's also more efficient, since the determinant of a Matrix3 is much cheaper to compute than that of a Matrix4.

### CODE REVIEW

**Comment by mrdoob** [comment]
What if the object that has the reflection is a parent?

**Comment by Korijn** [comment]
The normalMatrix is taken from the modelViewMatrix which is the product of the camera.matrixWorld and object.matrixWorld, so all parent transforms are included. This behaviour is correct and is not changed by this PR.

**Comment by mrdoob** [comment]
@Korijn Do you mind removing the builds commit?

**Comment by Korijn** [comment]
Yes! @berendkleinhaneveld is working on it

**Comment by Korijn** [comment]
@mrdoob CI failed due to an `npm install` timeout but as you can see the PR passed on the earlier commit that has identical changes. If you want to see CI pass, you'll have to re-run travis, since we don't have permission for that.

**Comment by mrdoob** [comment]
> Even if we disagree about the use case for negative camera scaling, I think we can agree on the fact that it makes more sense to check the determinant of the normalMatrix for this particular code path? :)

Yes, I agree with that.

I'll let @WestLangley decide on this one though.

**Comment by WestLangley** [comment]
@mrdoob This is a good suggestion. Thanks @Korijn.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Note: This has been reverted in #15825. Reflections in the camera matrix (or camera world matrix) are not supported.

**Comment by Korijn** [comment]
Alright, too bad. We'll resort to workarounds then.

**Comment by WestLangley** [comment]
Sorry, @Korijn about reverting your feature. Sometimes we have to make judgment calls, and this was one of them. Glad to hear you have workarounds available.

**Comment by haxiomic** [comment]
Just to add a point of view on this one:

It makes a lot of sense to support reflections in camera matrices, as this is the canonical approach to implement planar reflections (you take a camera's transform, reflect by your mirror plane and done :))

The original normal matrix approach was the best from an overall correctness point of view. I think #15825 would be better fixed by a different approach

I'm on a full-time project right now so I'll just fork and restore the normalMatrix version for now but I'll take a look at fixing #15825 when I get a moment

**Pull request merged**
