### PR TITLE
Examples: Geometry => BufferGeometry

### PR DESCRIPTION
**Pull request by WestLangley**
I modified `webgl_trails.html` slightly, but the other examples should be visually identical.

I am not able to test `webvr_vive_dragging.html`, but the changes are minimal.

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral test link: https://rawgit.com/westlangley/three.js/dev-to_bg_3/examples/webgl_trails.html

Original: http://threejs.org/examples/webgl_trails.html

**Comment by WestLangley** [comment]
Yikes! Both versions of `webgl_trails` are broken on macOS Safari -- at least on my machine. Looks like a strobe light... OK on macOS Chrome.

**Comment by looeee** [comment]
The examples now look very different for me, on windows 10. Tested with Chrome and Firefox. Is this intentional?

OLD:
webgl_trails_old


NEW: 
webgl_trails_new

**Comment by WestLangley** [comment]
Yes, it was intentional to make the dots bigger and decrease the number of lines generated so the trails are more visible.

I will change it there is an objection.

screen shot 2018-02-25 at 12 43 25 am

**Comment by Mugen87** [comment]
> Both versions of webgl_trails are broken on macOS Safari 

Same here. Looks like setting `preserveDrawingBuffer` set to `true` causes the visual error.

**Review by Mugen87 — APPROVED** [review]

**Comment by looeee** [comment]
The old version was beautiful, the new one not so much, although it does arguably demonstrate what's happening more clearly. I'm not going to complain if the change is kept, but I do prefer the old one.

**Comment by mrdoob** [comment]
> The old version was beautiful, the new one not so much

I like both versions. But I'll probably update the example to something more... demonstrative?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@grorg @kenrussell Any ideas why this example blinks in Safari?
https://rawgit.com/mrdoob/three.js/dev/examples/webgl_trails.html

**Comment by grorg** [comment]
Ouch! I don't know what's up.

I filed: https://bugs.webkit.org/show_bug.cgi?id=183151

I guess I broke preserveDrawingBuffer :(

**Pull request merged**
