### PR TITLE
Added constant collection objects to docs

### PR DESCRIPTION
**Pull request by looeee**
There are a couple of objects that collect groups of constants in constants.js
Added info about these to Ccants / materials and constants / textures
- BlendingMode
- TextureFilter
- TextureMapping
- TextureWrapping

### CODE REVIEW

**Comment by mrdoob** [comment]
I think I would use this pattern instead though:

```js
THREE.BlendingMode.NoBlending
```

**Comment by looeee** [comment]
OK, switched over

**Comment by looeee** [comment]
Oops

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
