### PR TITLE
event_controls

### PR DESCRIPTION
**Pull request by alexan0308**
This EventsControls will allow to facilitate development speed for simple manipulations by means of a mouse - point and click, drag and drop.

example - game Tower of Hanoi with minimum code.

Even if you won't accept a branch, I will be all the same glad to remarks and offers. 
More the best name - MouseControls, but it is already occupied...
or MouseEventsControls =)

### CODE REVIEW

**Comment by WestLangley** [comment]
Very interesting! This is similar to [ObjectControls](https://github.com/cabbibo/ObjectControls) by @cabbibo. His approach appears to be more flexible than yours, however. Have a look and see what you think.

Tips for the future: Avoid `new` in methods called in tight loops. Create one object and reuse it.  Also, only use `this.propertyName` for properties you want to expose. Use `var propertyName`, otherwise. Also, `Raycaster.setFromCamera()` is now available.

**Comment by alexan0308** [comment]
> This is similar to ObjectControls by @cabbibo. His approach appears to be more flexible than yours, however. Have a look and see what you think.
Indeed, it appears =). However, I would not want to show raykaster users. That they did not even know about raykastere. My code is more cumbersome, as it works not only for the mesh, but also object3D.
But there was an idea to make my code more understandable:
```javascript
EventsControls.attachEvent( 'mouseOver', function () {
   this.container.style.cursor = 'pointer';
   ...
});

EventsControls.attachEvent( 'mouseOut', function () {
   this.container.style.cursor = 'auto';
   ...
});

EventsControls.attachEvent( 'dragAndDrop', function () {
   ...
});

EventsControls.attachEvent( 'onclick', function () {
   ...
});

EventsControls.attachEvent( 'mouseUp', function () {
...
});
```
>Tips for the future: ... - ok.

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6058

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6058

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6058

**Pull request closed without merging**
