### PR TITLE
log warning when trying to serialize compressed texture

### PR DESCRIPTION
**Pull request by jespertheend**

### CODE REVIEW

**Comment by Mugen87** [comment]
Merging #17745 should also solve #17974

**Comment by jespertheend** [comment]
@Mugen87 oh hmm I thought #17745 would only fix it for DataTextures

**Comment by Mugen87** [comment]
The following branch should also be executed for compressed textures:

https://github.com/mrdoob/three.js/pull/17745/files#diff-955123916e8856f9a39f789ef5bb406dR363-R368

**Comment by jespertheend** [comment]
Ah I see that makes sense now.

**Comment by Mugen87** [comment]
Closing in favor of #17745. It's the more holistic approach.

**Pull request closed without merging**
