### PR TITLE
Blendmesh example newly implemented

### PR DESCRIPTION
**Pull request by jostschmithals**
This new version of the [three.js blendmesh example]( https://threejs.org/examples/#webgl_animation_skinning_blending) does not only fix the bugs I reported [here]( https://github.com/mrdoob/three.js/issues/11126). During the revision I noticed several further issues, so that I decided to write the code completely new from scratch.

It turned out that this was the right decision, since now all seems to work very well in all combinations, all crossfades are optimally synchronized and smoothed, and at least from my point of view the code (with many additional comments) is easier to understand in this way.

I renounced the “normalizing” of the three animations which is done in the original example. This “normalizing” is not only the reason for several bugs in the original code, but I think it makes no real sense - why should idle, walk and run be mixed up all together?

Now on the one hand the weight sliders are correctly live reflecting the automatic crossfades (which didn't work correctly in the original example), and on the other hand you can play with them freely and can test all useful and less useful combinations without any constraints and watch their effect.

The additional event dispatcher/event listener system that was implemented in the original dat gui code is not needed at all (as expected). A normal [dat gui use](https://github.com/jostschmithals/three.js/blob/7df511abee61df0ccce19cebfebdfe3a0c7d97f3/examples/webgl_animation_skinning_blending.html#L159-L215) is sufficient and more straightforward.

I decided to write this basic example without a BlendCharacter class (as distinguished from the original code), since the main purpose of the three.js examples is to learn the three.js features, and this is very hard for a beginner, if these features are not shown directly, but with a wrapper around a wrapper.

I think how to create and use such a BlendCharacter class is more a JavaScript topic than a three.js topic. But if you want to also keep such a pattern in the examples additionally, I would like to create a further version of this example which uses a (improved) BlendCharacter class.

Apart from this my present goal was to recreate all features of the original example and improve their functionality. Perhaps later on it could be useful to split it up into several different examples that show only parts of the functionality? - My vision (in the long view) would be to make a synopsis (placed in the docs) of all three.js examples using the animation system, so that each single example could be made simpler to understand by using only a few special features which aren't used in other examples.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice! Many thanks!

**Comment by mrdoob** [comment]
Is there any way to avoid this alert though?

screen shot 2017-04-12 at 13 00 50

**Comment by mrdoob** [comment]
I don't know if dat.gui allows enabling/disabling buttons...?

**Comment by jostschmithals** [comment]
There is no built-in dat.gui functionality (and the slider is no form element that could be disabled in the usual way), but of course one could simulate disabling by setting `control.domElement.pointerEvents` to `'none'` and `control.domElement.style.opacity` to  a low value.

I will implement this alternative tomorrow.

**Pull request merged**
