### PR TITLE
NodeMaterial PMREM custom size 

### PR DESCRIPTION
**Pull request by sunag**
Custom PMREM texture size per `node`.

**Example**
https://rawgit.com/sunag/three.js/dev-fix-TextureCubeNode/examples/webgl_materials_envmaps_pmrem_nodes.html

**256**
image

**1024**
image

/cc @bhouston @WestLangley

### CODE REVIEW

**Comment by sunag** [comment]
With this approach is possible to create multiples PMREMs for the same material each with different sizes.

**Comment by sunag** [comment]
**Usage**
```javascript
nodeTexture = new THREE.TextureNode( pmremCubeUVPacker.CubeUVRenderTarget.texture );
nodeTextureSize = new THREE.FloatNode( 1024 );

nodeMaterial.environment = new THREE.TextureCubeNode( nodeTexture, nodeTextureSize );
```

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@sunag Thanks for this. Please see `webgl_materials_envmaps_hdr.html` for how to modify this example to properly support modules.

**Comment by sunag** [comment]
@WestLangley Apparently to this is possible is necessary makes this changes https://github.com/mrdoob/three.js/pull/16054

**Comment by WestLangley** [comment]
@sunag I do not think you should be referencing the `THREE` namespace in your example. `import` the classes you need.

@Mugen87 Correct?

**Comment by sunag** [comment]
For this is necessary some changes in `/nodes/` code, remove all `THREE` namespace dependencies that exists there.

**Comment by mrdoob** [comment]
@WestLangley I'm actually changing that. Making the examples import the `THREE` namespace. Makes the development experience nicer (basically how it was before).

**Pull request merged**
