### PR TITLE
Moved page "How to run things locally" from wiki to manual

### PR DESCRIPTION
**Pull request by looeee**
Left as is except for minor cleanup

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting... Just tried github's built-in tool for resolving conflicts. Not too bad...

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
>Interesting... Just tried github's built-in tool for resolving conflicts. Not too bad...

I've been trying to use it myself the last couple of days, but just get an endless spinner.

**Comment by mrdoob** [comment]
Yeah, I was getting that too. I think they fixed it.

**Comment by looeee** [comment]
Ah great, I'll try it again next time I mess things up 😆

**Pull request merged**
