### PR TITLE
Editor: Removed Electron

### PR DESCRIPTION
**Pull request by mrdoob**

### CODE REVIEW

**Comment by Mugen87** [comment]
FYI: I note in the migration guide that `npm run editor` was removed.

https://github.com/mrdoob/three.js/wiki/Migration-Guide

**Comment by devingfx** [comment]
Hello,

May I ask why you did remove electron launch ?

**Comment by Mugen87** [comment]
Because the editor is now a PWA.

**Comment by Mugen87** [comment]
Yep 😊 .

**Comment by devingfx** [comment]
A PWA si to oppose to native mobile app... Not a already web app!
I don't understand why disabling the ability to launch this web app (that was already launchable in a browser) in electon makes it a PWA...

**Comment by Mugen87** [comment]
Things were added, too: https://github.com/mrdoob/three.js/pull/10944#issuecomment-473139223

**Comment by mrdoob** [comment]
@devingfx Electron uses more memory than a PWA. Every Electron app is a new Chromium instance. PWA reuses the browser instance it was installed with.

**Comment by devingfx** [comment]
Thanks for answers guys! :)

**Pull request merged**
