### PR TITLE
Added autoReset to WebGLRenderer.info

### PR DESCRIPTION
**Pull request by Astrak**
See https://github.com/mrdoob/three.js/issues/12420
- added info.autoReset and info.reset
- updated doc

### CODE REVIEW

**Comment by Astrak** [comment]
Any news about this very tiny and cool PR ? :innocent:

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
I suspect this will be refactored eventually. But lets merge it for now 😊

**Comment by mrdoob** [comment]
Thanks!

**Comment by realratchet** [comment]
It should be noted that this causes side-effect in _WebGLObjects_ internal update function, preventing geometry attributes from changing because the frame id remains the same.

**Comment by realratchet** [comment]
Sure, I'll prepare something. This is basically because needsUpdate is never called until next frame. I've ran into such micro-optimization problems with uniforms and geometry not updating before, so I might add those too.

**Comment by mrdoob** [comment]
@realratchet thanks!

**Comment by realratchet** [comment]
Here's a quick test case example https://codepen.io/anon/pen/wyOaod?editors=0010

**Comment by Astrak** [comment]
Hi @realratchet , thanks for the example. The point of setting `renderer.info.autoUpdate = false` is when a developper wants to use a composer or reflectors, and get correct `renderer.info` data. In this case `renderer.info.reset()` can be placed in the render function before starting the internal render calls. If this method is not called at all, as in your example, then `renderer.info.autoUpdate` can just be set to `true` again instead, which solves the problem.

**Comment by realratchet** [comment]
The problem is that if you want to change buffer attributes in-between render passes and retain the count you cannot and would still need to manually track the framerate, otherwise the side effect would happen. IMO WebGLObjects should respect needsUpdate at least when autoReset is disabled.

**Comment by Astrak** [comment]
you mean that `renderer.info.frame` should be separate from an internal `frameId` variable, so one could change the buffers between renders for a same frame ?

**Comment by mrdoob** [comment]
That sounds good to me @Astrak. Do you want to try doing a PR for it?

**Pull request merged**
