### PR TITLE
Matrix4: Clean up

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: -

**Description**

Some cleanup.

### CODE REVIEW

**Comment by mrdoob** [comment]
I don't know where things stand these days but...

When we wrote all those methods years ago we were following performance recommendations by javascript engine authors who said that functions that don't call other functions inside produce faster code.

So the code looks dumb but makes it straightforward for the javascript engine to optimize.

In order to merge this we would need a performance comparison chart of all modern browsers/os combinations.

**Comment by Mugen87** [comment]
I also believe that such "clean up" PRs produce a review effort that is not worth considering the benefits. Actually are there any? The code is not more readable, imo.

**Comment by RemusMar** [comment]
> functions that don't call other functions inside produce faster code.

More than true!
But Levi Pesin is a young fellow and, as I said before, he wants to replace all the "obsolete" things from everywhere.
Most of the young people use to waste processing power for nothing but making the code look "better".

**Comment by LeviPesin** [comment]
In my opinion such code is both more readable and compact. And I find it quite confusing when some methods on the same class use `.set()` while others manipulate the elements array directly (not even reading from it).

**Comment by LeviPesin** [comment]
Somehow it seems like the new version is almost 2x faster:
image
(JSBench doesn't allow to save the benchmark because it's too large, but here is the complete setup:
```
class Matrix4 {

	constructor( n11, n12, n13, n14, n21, n22, n23, n24, n31, n32, n33, n34, n41, n42, n43, n44 ) {

		Matrix4.prototype.isMatrix4 = true;

		this.elements = [

			1, 0, 0, 0,
			0, 1, 0, 0,
			0, 0, 1, 0,
			0, 0, 0, 1

		];

		if ( n11 !== undefined ) {

			this.set( n11, n12, n13, n14, n21, n22, n23, n24, n31, n32, n33, n34, n41, n42, n43, n44 );

		}

	}

	set( n11, n12, n13, n14, n21, n22, n23, n24, n31, n32, n33, n34, n41, n42, n43, n44 ) {

		const te = this.elements;

		te[ 0 ] = n11; te[ 4 ] = n12; te[ 8 ] = n13; te[ 12 ] = n14;
		te[ 1 ] = n21; te[ 5 ] = n22; te[ 9 ] = n23; te[ 13 ] = n24;
		te[ 2 ] = n31; te[ 6 ] = n32; te[ 10 ] = n33; te[ 14 ] = n34;
		te[ 3 ] = n41; te[ 7 ] = n42; te[ 11 ] = n43; te[ 15 ] = n44;

		return this;

	}

	makeRotationFromEulerNew( euler ) {

		const x = euler.x, y = euler.y, z = euler.z;
		const a = Math.cos( x ), b = Math.sin( x );
		const c = Math.cos( y ), d = Math.sin( y );
		const e = Math.cos( z ), f = Math.sin( z );

		if ( euler.order === 'XYZ' ) {

			const ae = a * e, af = a * f, be = b * e, bf = b * f;

			this.set(

				c * e, - c * f, d, 0,
				af + be * d, ae - bf * d, - b * c, 0,
				bf - ae * d, be + af * d, a * c, 0,
				0, 0, 0, 1

			);

		} else if ( euler.order === 'YXZ' ) {

			const ce = c * e, cf = c * f, de = d * e, df = d * f;

			this.set(

				ce + df * b, de * b - cf, a * d, 0,
				a * f, a * e, - b, 0,
				cf * b - de, df + ce * b, a * c, 0,
				0, 0, 0, 1

			);

		} else if ( euler.order === 'ZXY' ) {

			const ce = c * e, cf = c * f, de = d * e, df = d * f;

			this.set(

				ce - df * b, - a * f, de + cf * b, 0,
				cf + de * b, a * e, df - ce * b, 0,
				- a * d, b, a * c, 0,
				0, 0, 0, 1

			);

		} else if ( euler.order === 'ZYX' ) {

			const ae = a * e, af = a * f, be = b * e, bf = b * f;

			this.set(

				c * e, be * d - af, ae * d + bf, 0,
				c * f, bf * d + ae, af * d - be, 0,
				- d, b * c, a * c, 0,
				0, 0, 0, 1

			);

		} else if ( euler.order === 'YZX' ) {

			const ac = a * c, ad = a * d, bc = b * c, bd = b * d;

			this.set(

				c * e, bd - ac * f, bc * f + ad, 0,
				f, a * e, - b * e, 0,
				- d * e, ad * f + bc, ac - bd * f, 0,
				0, 0, 0, 1

			);

		} else if ( euler.order === 'XZY' ) {

			const ac = a * c, ad = a * d, bc = b * c, bd = b * d;

			this.set(

				c * e, - f, d * e, 0,
				ac * f + bd, a * e, ad * f - bc, 0,
				bc * f - ad, b * e, bd * f + ac, 0,
				0, 0, 0, 1

			);

		}

		return this;

	}

	makeRotationFromEulerOld( euler ) {

		const te = this.elements;

		const x = euler.x, y = euler.y, z = euler.z;
		const a = Math.cos( x ), b = Math.sin( x );
		const c = Math.cos( y ), d = Math.sin( y );
		const e = Math.cos( z ), f = Math.sin( z );

		if ( euler.order === 'XYZ' ) {

			const ae = a * e, af = a * f, be = b * e, bf = b * f;

			te[ 0 ] = c * e;
			te[ 4 ] = - c * f;
			te[ 8 ] = d;

			te[ 1 ] = af + be * d;
			te[ 5 ] = ae - bf * d;
			te[ 9 ] = - b * c;

			te[ 2 ] = bf - ae * d;
			te[ 6 ] = be + af * d;
			te[ 10 ] = a * c;

		} else if ( euler.order === 'YXZ' ) {

			const ce = c * e, cf = c * f, de = d * e, df = d * f;

			te[ 0 ] = ce + df * b;
			te[ 4 ] = de * b - cf;
			te[ 8 ] = a * d;

			te[ 1 ] = a * f;
			te[ 5 ] = a * e;
			te[ 9 ] = - b;

			te[ 2 ] = cf * b - de;
			te[ 6 ] = df + ce * b;
			te[ 10 ] = a * c;

		} else if ( euler.order === 'ZXY' ) {

			const ce = c * e, cf = c * f, de = d * e, df = d * f;

			te[ 0 ] = ce - df * b;
			te[ 4 ] = - a * f;
			te[ 8 ] = de + cf * b;

			te[ 1 ] = cf + de * b;
			te[ 5 ] = a * e;
			te[ 9 ] = df - ce * b;

			te[ 2 ] = - a * d;
			te[ 6 ] = b;
			te[ 10 ] = a * c;

		} else if ( euler.order === 'ZYX' ) {

			const ae = a * e, af = a * f, be = b * e, bf = b * f;

			te[ 0 ] = c * e;
			te[ 4 ] = be * d - af;
			te[ 8 ] = ae * d + bf;

			te[ 1 ] = c * f;
			te[ 5 ] = bf * d + ae;
			te[ 9 ] = af * d - be;

			te[ 2 ] = - d;
			te[ 6 ] = b * c;
			te[ 10 ] = a * c;

		} else if ( euler.order === 'YZX' ) {

			const ac = a * c, ad = a * d, bc = b * c, bd = b * d;

			te[ 0 ] = c * e;
			te[ 4 ] = bd - ac * f;
			te[ 8 ] = bc * f + ad;

			te[ 1 ] = f;
			te[ 5 ] = a * e;
			te[ 9 ] = - b * e;

			te[ 2 ] = - d * e;
			te[ 6 ] = ad * f + bc;
			te[ 10 ] = ac - bd * f;

		} else if ( euler.order === 'XZY' ) {

			const ac = a * c, ad = a * d, bc = b * c, bd = b * d;

			te[ 0 ] = c * e;
			te[ 4 ] = - f;
			te[ 8 ] = d * e;

			te[ 1 ] = ac * f + bd;
			te[ 5 ] = a * e;
			te[ 9 ] = ad * f - bc;

			te[ 2 ] = bc * f - ad;
			te[ 6 ] = b * e;
			te[ 10 ] = bd * f + ac;

		}

		// bottom row
		te[ 3 ] = 0;
		te[ 7 ] = 0;
		te[ 11 ] = 0;

		// last column
		te[ 12 ] = 0;
		te[ 13 ] = 0;
		te[ 14 ] = 0;
		te[ 15 ] = 1;

		return this;

	}
	
}

const matrix = new Matrix4();
const euler = { x: Math.PI / 4, y: Math.PI / 4, z: Math.PI / 4 };
```
)

**Comment by LeviPesin** [comment]
It seems they are about the same:
image
And the exact speed-up or slow-down is quite flaky and changes with each benchmark run.
(Unfortunately JSBench doesn't allow to save the benchmark because it is too large, but here is the complete setup (I left only one case in both functions so that the setup would be shorter but it's still too large):
```
class Matrix4 {

	constructor( n11, n12, n13, n14, n21, n22, n23, n24, n31, n32, n33, n34, n41, n42, n43, n44 ) {

		Matrix4.prototype.isMatrix4 = true;

		this.elements = [

			1, 0, 0, 0,
			0, 1, 0, 0,
			0, 0, 1, 0,
			0, 0, 0, 1

		];

		if ( n11 !== undefined ) {

			this.set( n11, n12, n13, n14, n21, n22, n23, n24, n31, n32, n33, n34, n41, n42, n43, n44 );

		}

	}

	set( n11, n12, n13, n14, n21, n22, n23, n24, n31, n32, n33, n34, n41, n42, n43, n44 ) {

		const te = this.elements;

		te[ 0 ] = n11; te[ 4 ] = n12; te[ 8 ] = n13; te[ 12 ] = n14;
		te[ 1 ] = n21; te[ 5 ] = n22; te[ 9 ] = n23; te[ 13 ] = n24;
		te[ 2 ] = n31; te[ 6 ] = n32; te[ 10 ] = n33; te[ 14 ] = n34;
		te[ 3 ] = n41; te[ 7 ] = n42; te[ 11 ] = n43; te[ 15 ] = n44;

		return this;

	}

	makeRotationFromEulerNew( euler ) {

		const x = euler.x, y = euler.y, z = euler.z;
		const a = Math.cos( x ), b = Math.sin( x );
		const c = Math.cos( y ), d = Math.sin( y );
		const e = Math.cos( z ), f = Math.sin( z );

		if ( euler.order === 'XYZ' ) {

			const ae = a * e, af = a * f, be = b * e, bf = b * f;

			this.set(

				c * e, - c * f, d, 0,
				af + be * d, ae - bf * d, - b * c, 0,
				bf - ae * d, be + af * d, a * c, 0,
				0, 0, 0, 1

			);

		}

		return this;

	}

	makeRotationFromEulerOld( euler ) {

		const te = this.elements;

		const x = euler.x, y = euler.y, z = euler.z;
		const a = Math.cos( x ), b = Math.sin( x );
		const c = Math.cos( y ), d = Math.sin( y );
		const e = Math.cos( z ), f = Math.sin( z );

		if ( euler.order === 'XYZ' ) {

			const ae = a * e, af = a * f, be = b * e, bf = b * f;

			te[ 0 ] = c * e;
			te[ 4 ] = - c * f;
			te[ 8 ] = d;

			te[ 1 ] = af + be * d;
			te[ 5 ] = ae - bf * d;
			te[ 9 ] = - b * c;

			te[ 2 ] = bf - ae * d;
			te[ 6 ] = be + af * d;
			te[ 10 ] = a * c;

		}

		// bottom row
		te[ 3 ] = 0;
		te[ 7 ] = 0;
		te[ 11 ] = 0;

		// last column
		te[ 12 ] = 0;
		te[ 13 ] = 0;
		te[ 14 ] = 0;
		te[ 15 ] = 1;

		return this;

	}
	
}

const matrix = new Matrix4();
const euler = { x: Math.PI / 4, y: Math.PI / 4, z: Math.PI / 4, order: 'XYZ' };
```
)

**Comment by RemusMar** [comment]
> In my opinion such code is both more readable and compact. 

That's irrelevant here.
It has to be fastest and with the minimal memory footprint.
Long story short: no need to "clean up" anything here.

**Comment by LeviPesin** [comment]
The new code isn't slower or more memory-consuming than the old one.

**Comment by mrdoob** [comment]
> The new code isn't slower or more memory-consuming than the old one.

We have had many regressions in the past caused by similar cleanups in the past.

You need to be able to guarantee that the code doesn't cause regressions and to do so you need to test the change in all modern browser/os configurations and different devices.

Testing the change only in your computer is not good enough.

**Comment by LeviPesin** [comment]
Does this mean that any cleanup PR targeting src/ directory requires such a wide testing?

**Comment by mrdoob** [comment]
Ideally changes in src/ are bug fixes or performance improvements.

Code clean ups and refractorings can cause regressions and cause extra debate on whether they are needed or not.

I've never heard of anyone complaining about `Matrix4` code being not clean or not readable.

**Comment by LeviPesin** [comment]
I thought that for the src/ directory code size issues were especially important because builds are used by so many people. And even 0.75 KB change feels quite important for me, especially if it makes code more clean (by don't using unneeded references to `this.elements`) and consistent (doing the same thing in most methods, e.g. using `.set()`).

**Comment by RemusMar** [comment]
> I thought that for the src/ directory code size issues were especially important because builds are used by so many people.

The code size is irrelevant here.
Many young people don't understand that if you type less does not always mean that it will run faster.
You also need to understand that "functions that don't call other functions inside produce faster code".

**Comment by Mugen87** [comment]
@LeviPesin Sorry, please accept that this PR is going to be merged. Let's focus on something else.

**Pull request closed without merging**
