### PR TITLE
EXAMPLES: Updated webgl_materials_cars example to use GLTF model

### PR DESCRIPTION
**Pull request by looeee**
Although now it should really be called `webgl_materials_car` since there's only one car model 😅 

[New version](https://goo.gl/hCZqGx )
[Old version](https://threejs.org/examples/#webgl_materials_cars)

### CODE REVIEW

**Comment by WestLangley** [comment]
The model seems to be missing parts.

Maybe do this as a workaround:
```javascript
carModel.traverse( function( node ) { if ( node instanceof THREE.Mesh ) { node.material.side = THREE.DoubleSide } } );
```

Maybe find a better model?

**Comment by looeee** [comment]
I've done quite a bit of work on the model so far, it still has a couple of missing bits \ tiny gaps but I'll fix them in a separate PR since this model is used across a couple of examples. It can mostly be fixed by adding a bottom plate to the car and adding an inside surface to the body.

BTW I did previously submit a different model (Dodge viper) but was told I should use a model already in the repo...

**Comment by takahirox** [comment]
Just curious to know what the main purpose of switching to glTF model is.

**Comment by looeee** [comment]
We're working on deprecating the old BinaryLoader. The examples using these car models are the only remaining places it's used.

**Comment by takahirox** [comment]
Gotcha

**Comment by takahirox** [comment]
BTW do we still need `materials_cars` example?
I'm really not sure what the purpose of `materials_cars` example is.
To show Three.js can switch material real-time?

**Comment by looeee** [comment]
I would be ok with removing it. 

To be honest, there are quite a few examples like this, that either demonstrate something outdated, or don't really demonstrate any feature but just look good, or are duplicates of other examples. 

While it's great to have this huge body of examples, having too many is actually counterproductive since they don't get updated and end up demonstrating out of date techniques (for example, many examples still use Geometry rather than BufferGeometry).

**Comment by takahirox** [comment]
Yeah, I think we can remove `materials_cars` example.

Any thoughts? @mrdoob

**Comment by looeee** [comment]
There are now 3 PRs that use this updated car model: this one and #13084, #13314

Two questions have been raised:

**1.** As @WestLangley pointed out above there are some issues with this model - in particular the interior is missing a couple of pieces. I can either 
 * continue to work on this model to improve it
 * replace it with on of the other models from [webgl_materials_cars](https://threejs.org/examples/#webgl_materials_cars) - probably the Bugatti Veyron since it looks like the other models are also missing pieces
 * find a new model, such as the Dodge Viper that I previously submitted [here](https://rawgit.com/looeee/three.js/d78c734dd2dbe565eed5cde17bd83fe78629a571/examples/webgl_effects_parallaxbarrier.html). I would prefer this one as its less work for me 😅 

**2.** Is this example (materials_cars) worth keeping? Or should we remove it?

@mrdoob can you provide feedback here before I proceed in this?

**Comment by mrdoob** [comment]
Sorry for the delay. This PR is looking good! I'll polish it in the next cycle 👌

**Comment by looeee** [comment]
> Sorry for the delay 

There no rush, just didn't want this to gather _too_ much dust. 🙂

**Comment by looeee** [comment]
Closed in favour of #14843

**Pull request closed without merging**
