### PR TITLE
Examples: Refactor Sky usage.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Alternative implementation for #21575.

**Description**

Uses `elevation` instead of `inclination` in `webgl_shaders_ocean` and `webgl_shaders_sky`.

Both `elevation` and `azimuth` are now expressed in degress.

Range of `elevation` is `[0,90]`. Range of `azimuth` is `[-180,180]`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev54/examples/webgl_shaders_sky.html
https://raw.githack.com/Mugen87/three.js/dev54/examples/webgl_shaders_ocean.html

**Comment by mrdoob** [comment]
@Mugen87 Resolved the conflicts. Looks good?

**Comment by Mugen87** [comment]
Yep! 😊

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
