### PR TITLE
WebGLRenderer: Do not run window.rAF when in XR.

### LINKED ISSUE #18666: Do not call window.requestAnimationFrame when in webxr mode
If I'm not mistaken, running https://threejs.org/examples/webxr_vr_rollercoaster.html in webxr mode will still run the initial webgl loop.

The webxr loop uses session.rAF, and doesn't need window.rAF to be looping.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #18666.

**Description**

I've tested this change with a Oculus Quest (1). When in XR, the animation loop of the `window` context is now stopped. A check for `xr.isPresenting` is not necessary anymore.

### CODE REVIEW

**Comment by marcofugaro** [comment]
What about AR examples that still need to render in the animationLoop to run?

https://github.com/mrdoob/three.js/blob/56ca942a563a5edb4ccfc0536a08499ed6ffc3a1/examples/webxr_ar_hittest.html#L106

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev2/examples/index.html

**Comment by Mugen87** [comment]
Updated the builds for testing.

**Comment by Mugen87** [comment]
AFAICS, there should be difference than before. When you are currently in XR, the following line prevents that the animation loop is executed in context of `window`:

https://github.com/mrdoob/three.js/blob/56ca942a563a5edb4ccfc0536a08499ed6ffc3a1/src/renderers/WebGLRenderer.js#L939

With this PR, the animation loop is stopped and does not run in the background anymore.

**Comment by marcofugaro** [comment]
Okay! I tested the AR examples and they work the same 🙂

**Comment by mrdoob** [comment]
Hmm, I *think* when I did that was because these events were not reliable 🤔
We'll see what happens now 🤞🤓

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
