### PR TITLE
Nodes: Add SepiaNode

### PR DESCRIPTION
**Pull request by cmhhelgeson**
Related issue: 

**Description**

Port of GLSL Sepia Shader to node system.

```typescript
postProcessing = new THREE.PostProcessing( renderer );
const scenePass = pixelationPass( scene, camera, effectController.pixelSize, 
effectController.normalEdgeStrength, effectController.depthEdgeStrength );
// scenePass.getTextureNode() returns pixelation.textureNode, renderOutput returns full effect
const sepiaPass = sepia( { color: scenePass.renderOutput() } );
postProcessing.outputNode = mix( scenePass, sepiaPass, effectController.mixValue );
```

[Live Example](https://raw.githack.com/cmhhelgeson/three.js/webgpu_post_test/examples/webgpu_postprocessing_pixel.html)

### CODE REVIEW

**Comment by sunag** [comment]
I think serpia could be introduced without needing a texture as a parameter, maybe just a `tslFn` could solve the issue.

**Comment by cmhhelgeson** [comment]
> Could `amount` be replaced by a `mix` externally? Maybe we don't need it as a parameter.

I think that makes sense if we're just strictly replicating the sepia effect, but for portability between the old and new shaders I think it makes sense to keep in cases where people are deliberately pushing the value to achieve specific effects.

> I think serpia could be introduced without needing a texture as a parameter, maybe just a tslFn could solve the issue.

Were you think something more like the colorAdjustmentNode where the tslFn is only taking in a color? Or just export a tslFn directly from the file?

**Comment by sunag** [comment]
> I think that makes sense if we're just strictly replicating the sepia effect, but for portability between the old and new shaders I think it makes sense to keep in cases where people are deliberately pushing the value to achieve specific effects.

Developers didn't have support for this level of abstraction before, so we had intensity and amount everywhere, but that's no longer necessary, adding them nowadays would just be adding extra code and operations.

Even if this were preserved and for the sake of practicality, the feeling when looking at the code is that it should be done with `mix`, multiplying all the values ​​of the serpia vector seems more costly for gpu..

> Were you think something more like the colorAdjustmentNode where the tslFn is only taking in a color? Or just export a tslFn directly from the file?

I think no class is needed for this, just export tslFn, like:

```js
export const serpia = /*@__PURE__*/ tslFn( ( [ color ] ) => {

} );
```

**Comment by cmhhelgeson** [comment]
> Developers didn't have support for this level of abstraction before, so we had intensity and amount everywhere, but that's no longer necessary, adding them nowadays would just be adding extra code and operations.
> 

That makes sense, thank you for that explanation, and I'll adjust the code accordingly.

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
