### PR TITLE
Add texture painter example

### PR DESCRIPTION
**Pull request by sciecode**
#9103 - [example](https://rawcdn.githack.com/sciecode/three.js/3c60dbd6bb26896ba3d488ac73d479dfca7540bd/examples/webgl_paint_texture.html)

### CODE REVIEW

**Comment by looeee** [comment]
This is cool! 

But I think the test UV texture is wrong, (0,0) should be in the bottom left. 

uv_test_bw_1024

**Comment by WestLangley** [comment]
Thank you for your contribution, but the code will need significant improvement. You are cloning or instantiating _tens-of-thousands_ of objects per frame when interacting with the mouse. Avoid calling `clone()` and `new` in tight loops. This must be fixed.

You likely do not need an animation loop, since your scene is static.

Also, `Geometry` will soon not be renderable -- only `BufferGeometry` will be. I expect that will require a major rewrite.

But to be honest, the purpose of the examples is to demonstrate three.js features. This demo appears to be more of a three.js-based application -- a bit too complicated to be useful as an example,  IMO.

**Comment by sciecode** [comment]
Appreciate the feedback.

**Comment by sciecode** [comment]
@looeee just a heads up, I agree with UV coordinates being wrong. 
I'm simply using the uv grid texture on dev: [UV_Grid_Sm.jpg](https://github.com/mrdoob/three.js/blob/dev/examples/textures/UV_Grid_Sm.jpg)

**Pull request closed without merging**
