### PR TITLE
Add label and temp functions to ShaderNode

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: - (mentioned in https://github.com/mrdoob/three.js/issues/23534)

**Description**

This PR adds the label and temp functions to the ShaderNode.

### CODE REVIEW

**Comment by sunag** [comment]
@LeviPesin do you think we got another name for it? Maybe `setvar`?

**Comment by LeviPesin** [comment]
> I think that `temp` to define a variable and `label` to define a variable name?

I like this approach!

> I think that this should be optimized by the `NodeBuilder` compiler and the variable should be created automatically if used more than once? At least it was supposed to work that way.

Here is an example:
https://jsfiddle.net/aopLv2cx/
There is a duplicate calculation of `dot(nodeVar2, nodeVar3)`. If you comment line 61 and uncomment 60, it will work properly.

**Comment by sunag** [comment]
@LeviPesin It seems that exist some conflicts in this PR.

**Comment by sunag** [comment]
> There is a duplicate calculation of dot(nodeVar2, nodeVar3). If you comment line 61 and uncomment 60, it will work properly.

This shouldn't happen, I will investigate. 
Thanks for the example.

**Comment by LeviPesin** [comment]
@sunag I think I resolved the conflicts.

**Comment by sunag** [comment]
Thanks! :)

**Comment by LeviPesin** [comment]
@sunag Is there any progress on fixing this example? Should I make a new issue for it?

**Comment by LeviPesin** [comment]
https://github.com/mrdoob/three.js/issues/23728

**Pull request merged**
