### PR TITLE
EXR example: remove custom tone mapping shader

### PR DESCRIPTION
**Pull request by WestLangley**
We have built-in tone mapping now. There is no need for a custom shader.

Also clean up.

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral test links:

old: https://threejs.org/examples/webgl_loader_texture_exr.html

new: https://rawgit.com/westlangley/three.js/dev-exr_example/examples/webgl_loader_texture_exr.html

**Review by Mugen87 — APPROVED** [review]

**Comment by looeee** [comment]
I'm getting a black screen on Android Chrome with the new version. Moto G6.

**Comment by WestLangley** [comment]
@looeee I am not able to test that hardware... Can you please see if you can identify the failure point?

**Comment by looeee** [comment]
@WestLangley here's what I get in the console:

```
[.WebGL-0x998fa300]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: 
webgl_loader_texture_exr.html:1 [.WebGL-0x998fa300]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

The GPU is an Adreno 506.

**Comment by WestLangley** [comment]
This example is not complicated, but it does generate mips, whereas the previous example did not. I implemented it that way because that is what users would typically require.

@looeee Please try this modification to the code with your device:

```javascript
texture.generateMipmaps = false;

texture.minFilter = THREE.LinearFilter;
texture.magFilter = THREE.LinearFilter;
```

Presumably that works. If so, verify that when `texture.generateMipmaps = true`, the default filter setting are correct.

**Comment by mrdoob** [comment]
I'll merge and investigate...

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@WestLangley 

> @looeee Please try this modification to the code with your device:
>
> ```javascript
> texture.generateMipmaps = false;
> 
> texture.minFilter = THREE.LinearFilter;
> texture.magFilter = THREE.LinearFilter;
> ```

Doesn't seem to fix it...

The original code works though:

```js
texture.minFilter = THREE.NearestFilter;
texture.magFilter = THREE.NearestFilter;
```

**Comment by WestLangley** [comment]
@mrdoob @looeee Is this still a problem? I would like to restore the filtering.

**Comment by mrdoob** [comment]
Hmm, yeah, lets restore it so we can bring it to a "sane" state.

**Pull request merged**
