### PR TITLE
Examples: Clean up webgl_geometries2.html

### PR DESCRIPTION
**Pull request by Mugen87**
As suggested in https://github.com/mrdoob/three.js/issues/12388#issuecomment-335867600

### CODE REVIEW

**Comment by Mugen87** [comment]
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_geometries_parametric.html

**Comment by WestLangley** [comment]
This is much better, thanks!

However, it is also a very old example. Here are some suggestions for improvement. Maybe you agree.

- The lighting is terrible. Add a point light to the camera, instead.
- The directional light is being rotated in the render loop. I doubt that is having an effect.
- Multi-material objects are not needed.
- The rotating axes are not needed.

I like the look of https://threejs.org/examples/webgl_geometry_shapes.html. The geometries in that case are more-easily viewable.

**Comment by Mugen87** [comment]
I like all of your suggestions 😊 . Is it okay for you to implement them in a separate PR? I'd like to keep `webgl_geometries_parametric` and `webgl_geometries` identical. Your suggestions should applied to both examples.

**Comment by WestLangley** [comment]
Sure.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
