### PR TITLE
Simplify FogExp2 GLSL, correct documentation and rename internal fogExp param. to fogExp2

### PR DESCRIPTION
**Pull request by EliasHasle**
Background: #17264

This is the first step, intended to be uncontroversial.

The simplification is equivalent and clearer, and saves a potentially branching operation.

The documentation was wrong stating that FogExp2 is exponentially densening fog. It is now called exponential squared fog, following http://in2gpu.com/2014/07/22/create-fog-shader/.

The parameter renaming lays the foundation for a later PR introducing proper exponential fog.

### CODE REVIEW

**Comment by EliasHasle** [comment]
I haven't touched the translated documentation, BTW.

**Comment by EliasHasle** [comment]
Here is an undisputable proof of the simplification: https://www.wolframalpha.com/input/?i=2%5E(x*1%2Fln(2))+%3D+e%5Ex 😉

**Comment by WestLangley** [comment]
```glsl
float fogFactor = 1.0 - exp( - fogDensity * fogDensity * fogDepth * fogDepth ) );
```

That will not compile. Please test your code before you file a PR.

And please target the dev branch, not master.

**Comment by EliasHasle** [comment]
> That will not compile. Please test your code before you file a PR.

You are so right! I actually did the whole PR in a rush in the online editor, and was afraid of breaking uncommitted local modifications by pulling the PR branch to my local copy. I really thought I had avoided silly mistakes like that in such a tiny PR, but anyway, thanks for pointing it out.

> And please target the dev branch, not master.

Oh, I thought it was always master. dev next time, then. Or is there a way for me to switch target branch?

**Comment by mrdoob** [comment]
> And please target the dev branch, not master.

I think I can change that 🤔 Lets see what happens.

**Comment by mrdoob** [comment]
I guess nothing broke.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
