### PR TITLE
WebXR: make it tree-shakable

### PR DESCRIPTION
**Pull request by munrocket**
All is ok with E2E here, if we will fix problem with UUID determinism.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sorry but this changes the API 😕

Also, we are still developing `WebXRManager` so it may be premature to change it if we have not finished the abstraction yet.

I have been considering refactoring it though (with tree shacking in mind):

```js
const controller = new THREE.WebXRController();
controller.addEventListener( 'select', event => {} );

const camera = new THREE.WebXRCamera();
renderer.render( scene, camera );
```

Or maybe...

```js
const webxr = new THREE.WebXRSession();
const controller = webxr.getController( 'left' );
controller.addEventListener( 'select', event => {} );

const camera = webxr.getCamera();
renderer.render( scene, camera );
```

But changing the API requires carefully studying all the use cases first.

**Comment by munrocket** [comment]
I am agree with it. Never faced with breaking change before.

**Comment by Mugen87** [comment]
> Also, we are still developing WebXRManager so it may be premature to change it if we have not finished the abstraction yet.

Closing then until the upcoming API design becomes more clear.

**Comment by munrocket** [comment]
@Mugen87 I think this PR was closed to early, because we doesn't have a solution for WebXR tree-shaking yet. This was the easiest way to fix it.

Also we have another 110 PRs that can be closed simply because they outdated.

**Comment by Mugen87** [comment]
@mrdoob made clear that this particular change will not be merged. A redesign of `WebXRManager` should be discussed in an issue.

**Comment by munrocket** [comment]
Already discussed in #19410

**Comment by mrdoob** [comment]
> Already discussed in #19410

#19410 is about `Math`, not about `WebXRManager`.

**Pull request closed without merging**
