### PR TITLE
fix rollup.unit.config.js

### LINKED ISSUE #19533: rollup: npm run dev-test broken.
##### Description of the problem

1. `npm run dev-test` happened the entry could not resolve.
2. `npm run test-unit` is not problem.
3. Those are script use the same config file `rollup.unit.config.js`

```
[ROLLUPTEST] rollup v2.10.0
[ROLLUPTEST] bundles unit/three.editor.unit.js → unit\build\three.editor.unit.js...
[ROLLUPTEST] [!] Error: Could not resolve entry module (unit/three.editor.unit.js).
[ROLLUPTEST] Error: Could not resolve entry module (unit/three.editor.unit.js).
```

##### Three.js version

- [x] Dev
- [ ] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by munrocket**
Fixes #19533

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by munrocket** [comment]
It's was not ready PR, because it's broken all unit tests.

**Comment by mrdoob** [comment]
Ah... Please, mark the PR as "Draft" when is not ready.

**Comment by munrocket** [comment]
Also did not notice that.

**Comment by DefinitelyMaybe** [comment]
ah. I'll add a note to the contribution guide

**Pull request merged**
