### PR TITLE
Editor add multimaterial support. Fix shading widget.

### PR DESCRIPTION
**Pull request by manthrax**
I've added awareness of the material array to the Editor. hth!

### CODE REVIEW

**Comment by manthrax** [comment]
Found a couple more corner cases I need to fix first...

**Comment by manthrax** [comment]
image

**Comment by manthrax** [comment]
image

**Comment by manthrax** [comment]
image

**Comment by mrdoob** [comment]
How about a dropdown instead?

**Comment by manthrax** [comment]
Ok. :) Thanks for the feedback. UX is not my forte.

**Pull request closed without merging**
