### PR TITLE
package.json: Don't export `src` directory in package files

### PR DESCRIPTION
**Pull request by legobeat**
Related issue: https://github.com/mrdoob/three.js/issues/20019#issuecomment-1546593357

#26048 proposes to remove fonts from the distribution files.
This is the same for the `src` directory.

### CODE REVIEW

**Comment by LeviPesin** [comment]
I'm not sure about how safely we can do that... Some users import from `three/src/Three.js`, because it provides better size after tree-shaking (no idea how, I think @marcofugaro knows more).

**Comment by Mugen87** [comment]
It's unclear how many users import files directly from the `src` directory so I don't think this change is acceptable. 

Also I question the motivation of this change in general. I personally don't think the size of the npm package is a real issue. Definitely not something that justifies such potential major breaking changes.

**Comment by LeviPesin** [comment]
Maybe we can at least deprecate somehow import from `src`?

**Comment by Mugen87** [comment]
Sorry, but I see no need to invest time and budget into this issue. Let's focus on other topics.

**Pull request closed without merging**
