### PR TITLE
EventDispatcher converted to es6

### PR DESCRIPTION
**Pull request by treblereel**
Related issue: #19986

### CODE REVIEW

**Comment by donmccurdy** [comment]
Note that this change could have downstream effects on classes that extend Object3D:

https://github.com/mrdoob/three.js/blob/670b1e9e85356d98efa4c702e93c85dd52f01e1e/src/core/Object3D.js#L115-L119

It may not — I don't see any calls to `super.*` methods — but this would need to be tested and confirmed.

**Comment by mrdoob** [comment]
Yeah, I suspect this change will break everything.

@treblereel Have you tested this?

**Comment by treblereel** [comment]
@mrdoob yeap, i my case all good. i also checked demos and got no issues

**Comment by DefinitelyMaybe** [comment]
Hey, quick question on this one: Could we simply extend [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) and add the hasEventListener function?
```javascript
class EventDispatcher extends EventTarget {
  hasEventListener( type, listener ) {
  // ...  
  }
}
```

**Comment by Mugen87** [comment]
Does not work in `node.js`.

**Comment by DefinitelyMaybe** [comment]
Actually it was [added](https://github.com/nodejs/node/pull/35496) into [node.js v15.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#2020-10-20-version-1500-current-bethgriggs)
Happy to not accept this into the fray now but later it may be nice.

**Comment by treblereel** [comment]
> Actually it was [added](https://github.com/nodejs/node/pull/35496) into [node.js v15.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#2020-10-20-version-1500-current-bethgriggs)
> Happy to not accept this into the fray now but later it may be nice.

ok, good to know, closing this PR

**Comment by Mugen87** [comment]
> Could we simply extend EventTarget and add the hasEventListener function?

Just want to add that a benchmark [here](https://github.com/mrdoob/three.js/pull/18564#issuecomment-584457877) showed that using `EventTarget` is noticeably slower compared to the current implementation.

**Comment by DefinitelyMaybe** [comment]
oh shoot. that's a big difference. Thank you for pointing that one out @Mugen87. Let's stick with what we got

**Pull request closed without merging**
