### PR TITLE
Remove Equirectangular Reflection/Refraction Mapping

### PR DESCRIPTION
**Pull request by WestLangley**
We support equirectangular textures as a scene background by using this pattern:
```js
scene.background = new THREE.WebGLCubeRenderTarget( 512 ).fromEquirectangularTexture( renderer, texture );
```
Similarly, we support equirectangular textures as an environment map:
```js
let envMap = new THREE.WebGLCubeRenderTarget( 512 ).fromEquirectangularTexture( renderer, texture ).texture;
```
And as a PMREM environment map like so:
```js
let envMap = pmremGenerator.fromEquirectangular( texture ).texture;
```
Issues:
1. I think `webgl_materials_envmaps.html` can be removed since there is only the cube case now. It is an old example.

2. I was not sure what to do with `editor/js/Sidebar.Material.js`. @Mugen87 can you help with that?

3. With this PR, `FBXLoader.js` no longer supports environment maps. Something will have to be done. Not sure what... /ping @looeee /ping @takahirox 

4. `LWOLoader` - same thing. /ping @sciecode /ping @looeee 

To do: update Migration docs.

### CODE REVIEW

**Comment by Mugen87** [comment]
May I ask first what's the motivation behind this PR? 

Another option is to enhance the support of equirectangular textures e.g. by solving #9733. 

I want to clarify this since I know from local customers that they are using equirectangular environment maps and relying on this code. They also hopped that the native support for this format gets improved in the future (#9733).

Besides, what about the idea of implementing `THREE.EquirectangularTexture`?

In general, we should only require migration tasks from users if there is a compelling reasons. I don't see this right now.

**Comment by mrdoob** [comment]
The main reason was to simplify the internal shaders. But I guess we would end up using more GPU memory?

**Comment by Mugen87** [comment]
> But I guess we would end up using more GPU memory in these cases?

Not sure about that.

I'm concerned about the development experience. The least that I would expect is that `three.js` internally converts from equirect to cube map. But letting the user doing this seems not appropriate to me (considering how long the engine supports equirect textures).

**Comment by WestLangley** [comment]
>The main reason was to simplify the internal shaders.

Correct.

Equirectangular environment maps are not supported natively by `MeshStandardMaterial` and `MeshPhysicalMaterial` and never will be. They _are_ supported if they are first converted to cube maps, however. This is consistent with the glTF spec.

A future PR can possibly automate the conversion for the user. But this is a first step.

**Comment by Mugen87** [comment]
I'm okay with not supporting them in the shaders. However, I'm afraid this first step will confuse users.

I suggest to file a PR which internally converts from equirect to cubemap so the user does not have to care about this. 

The user should not know that equirect maps are not supported in shaders. Ideally, equirect textures can just loaded and used like cube maps.

**Comment by looeee** [comment]
> I suggest to file a PR which internally converts from equirect to cubemap so the user does not have to care about this.

This would be ideal, but what about the `WebGLCubeRenderTarget` size? Could we create a setting on the renderer or texture for that?

**Comment by WestLangley** [comment]
>I'm okay with not supporting them in the shaders.

Good.

>However, I'm afraid this first step will confuse users.

Users will be just fine. You do not need to be afraid.

See above for the patterns for users to follow. These patterns were introduced in prior releases.

Users know how to follow patterns. That is why the examples have been so effective.

In Unity, a reflection probe is stored as a cube map. And Babylon provides a method like we do for users to convert from equirectangular to cube format.

>I suggest to file a PR which internally converts from equirect to cubemap so the user does not have to care about this.

If that is doable, then you should be able to implement the feature in an hour, and file a follow-up PR as step no. 2.

For now, this PR is a fine first step.

**Comment by Mugen87** [comment]
> Users will be just fine. You do not need to be afraid.

Sorry, I see this different. I've got a lot of complains over the years from `three.js` developers in Germany that the current release management is one of the biggest drawbacks of the project. Simply because there is no distinction between major and minor releases. The releases each month may or may not contain breaking changes and it's every time not foreseeable what kind of release will be published.

This PR in its current form is a breaking change I do not support. A feature is removed without compelling reason (simplifying shaders is no reasons for me to remove a long-supported feature). The only way to make things for again is a migration task. Believe it or not, users hate this tasks and I'd like to reduce them to a minimum.

> If that is doable, then you should be able to implement the feature in an hour,

Please try this solution. Instead of just removing code from the library a better PR is to internally convert to cube maps.

**Comment by mrdoob** [comment]
>> The main reason was to simplify the internal shaders.
>
> Correct.

Actually, there is a more compelling reason and it's that the there are artifacts in the poles:

Screen Shot 2020-07-20 at 10 01 20 PM

Plus a seam in the wrapping area:

Screen Shot 2020-07-20 at 10 01 34 PM

**Comment by mrdoob** [comment]
I agree with @Mugen87 that we should be careful with breaking changes.

I also think this PR is a good first step. So what I'm going to do is to do another PR on top of this one implementing the rest of the change.

This is what I'm thinking:

```js
const loader = new THREE.EquirectangularTextureLoader();
const texture = textureLoader.load( 'textures/foo.jpg' ); // returns THREE.EquirectangularTexture
material.envMap = texture;
```

When `WebGLRenderer` finds a `isEquirectangularTexture` it automatically creates a `CubeMap` internally and it uses half of the texture height as its size.

If someone needs a different cubemap size, then they can use @WestLangley's pattern:

```js
const renderTarget = new THREE.WebGLCubeRenderTarget( 512 ).fromEquirectangularTexture( renderer, texture );
material.envMap = renderTarget.texture;
```

How does this sound?

**Comment by WestLangley** [comment]
I think that is just as "breaking" as what I proposed. The user still has to do something different.

Anyway, I do not think a new loader is required. An equirectangular envMap can be identified by its aspect ratio.

**Comment by WestLangley** [comment]
With this PR, users can still use an equirectangular texture as an environment map. They just have to assign `envMap` differently.

And users will have improved results.

**Comment by mrdoob** [comment]
> I think that is just as "breaking" as what I proposed. The user still has to do something different.

Indeed, the user will still have to change their code, but I think it's important the the concepts won't change that much.

They'll have to go from this:

```js
const loader = new THREE.TextureLoader();
const texture = loader.load( 'textures/foo.jpg' );
texture.mapping = THREE.EquirectangularReflectionMapping;
material.envMap = texture;
```

To this:

```js
const loader = new THREE.EquirectangularTextureLoader();
const texture = textureLoader.load( 'textures/foo.jpg' );
material.envMap = texture;
```

Which is less of a change than this:

```js
const loader = new THREE.TextureLoader();
loader.load( 'textures/foo.jpg', function ( texture ) {

    const renderTarget = new THREE.WebGLCubeRenderTarget( 512 );
    material.envMap = renderTarget.fromEquirectangularTexture( renderer, texture ).texture;

} );
```

Both codes will work, but I don't think users should be have to learn about `WebGLCubeRenderTarget` neither have to decide the resolution of the texture in order to do this.

They're dealing with equirectangular textures which are pretty common, so I think it's worth adding a new texture type and loader type.

**Comment by mrdoob** [comment]
I can merge this now, or I can build on top of it and do another PR that will merge this one tomorrow too.

I prefer doing the later to double check that we're not missing anything.

**Comment by Mugen87** [comment]
I clearly favor `EquirectangularTexture` and `EquirectangularTextureLoader` (which are nice pendants to `CubeTexture` and `CubeTextureLoader`).

I've just hoped the engine could detect when legacy `EquirectangularReflectionMapping` and `EquirectangularRefractionMapping` are set and then perform the conversion for the user (by internally creating an instance of `EquirectangularTexture`). In this way the new pattern can be provided but the previous approach would not break.

**Comment by mrdoob** [comment]
That sounds good to me. Will do 👌

**Comment by Mugen87** [comment]
Perfect!!! 😊

**Comment by WestLangley** [comment]
>I clearly favor EquirectangularTexture and EquirectangularTextureLoader

It seems to me we already have all the loaders we need for equirectangular textures: `TextureLoader`, `EXRLoader`, and `RGBELoader`.

I do not think we need another loader -- or want one.

**Comment by WestLangley** [comment]
This PR was filed after discussing it first with @mrdoob. It was filed because @mrdoob said it was a good first step, and we could follow up with a second step if we saw fit.

If you think a second step is warranted, and want to continue to allow this pattern:
```js
new RGBELoader().load( 'equirectangular.hdr', function ( texture ) {

	texture.mapping = THREE.EquirectangularReflectionMapping;

	material.envMap = texture;

} );
```
...then the renderer needs to do something like this behind the scene:

```js
material.__envMap = new THREE.WebGLCubeRenderTarget( 256 ).fromEquirectangularTexture( renderer, matereial.envMap );
```
I would avoid changing the material properties set by the user.

**Comment by mrdoob** [comment]
> ...then the renderer needs to do something like this behind the scene:
>
> ```js
> material.__envMap = new THREE.WebGLCubeRenderTarget( 256 ).fromEquirectangularTexture( renderer, matereial.envMap );
> ```
> I would avoid changing the material properties set by the user.

Yep! That's what I've implemented in #19909:

https://github.com/mrdoob/three.js/blob/d50a5f0d6b2fc4f5c8d8ea2c49e98c5db0b894c2/src/renderers/webgl/WebGLTextures.js#L1317-L1326

**Comment by mrdoob** [comment]
> It seems to me we already have all the loaders we need for equirectangular textures: `TextureLoader`, `EXRLoader`, and `RGBELoader`.

I can see how that can be confusing. I'll study this.

**Comment by mrdoob** [comment]
We all agree that we want to remove the equirectangular code from ShaderChunks.

Some of us want to make sure user's code do not break and that was the main purpose of #19911.

API design wise, the benefits of having something like `EquirectangularTexture` is that the user is telling the renderer how its supposed to interpret it and the renderer doesn't have to do guesses. I think guessing that a texture is equirectangular based on the dimensions is prone to confusion.

`EquirectangularTexture` has issues though. `EXRLoader` returns a `DataTexture`. How do we turn it into a `EquirectangularTexture`?

Questions like that are easier to see for me now that I've sketched #19911 rather than talking about our hunches.

Hope this clarifies things.

**Comment by mrdoob** [comment]
I'm thinking that intead of `EquirectangularTexture` and `EquirectangularTextureLoader` it'll be simpler to add a new property to `Texture` instead.

Maybe `texture.projection = THREE.EquirectangularProjection`?

**Comment by Mugen87** [comment]
> API design wise, the benefits of having something like EquirectangularTexture is that the user is telling the renderer how its supposed to interpret it and the renderer doesn't have to do guesses.

One thing I like about `EquirectangularTextureLoader `: It makes the API more expressive since it's more clear from the code what type of texture is loaded.

**Comment by Mugen87** [comment]
BTW: In the past, it was decided to go for separate classes instead of encoding type information in properties. That's the reason for having `DataTexture2DArray`, `DataTexture3D` next to `DataTexture`. I feel `EquirectangularTexture` is a good complement in that regard. Especially in context of `Texture` and `CubeTexture`.

**Comment by mrdoob** [comment]
That's a good point. So we would need a `EquirectangularDataTexture` too.

But, rather than doing a `EquirectangularTextureLoader` we can add a `setTextureType` to `TextureLoader`:

```js
var loader = new THREE.RGBELoader();
loader.setDataType( THREE.UnsignedByteType );
loader.setTextureType( THREE.EquirectangularDataTexture );
loader.load( 'venice_sunset_1k.hdr', function ( texture ) {

	scene.background = texture;

} );
```

`RGBELoader` should probably extend `TextureLoader` and be renamed to `RGBETextureLoader` (as it's returning a texture).

Eventually, we could also do the PMREM automatically inside the renderer and the code would just be:

```js
var loader = new THREE.RGBETextureLoader();
loader.setDataType( THREE.UnsignedByteType );
loader.setTextureType( THREE.EquirectangularDataTexture );
loader.load( 'venice_sunset_1k.hdr', function ( texture ) {

	scene.background = texture;
	scene.environment = texture;

} );
```

**Comment by Mugen87** [comment]
BTW: Maybe targeting `r120`? It would be good to have enough time to verify these changes on `dev`. `r119` is already published next week.

**Comment by Mugen87** [comment]
> RGBELoader should probably extend TextureLoader and be renamed to RGBETextureLoader (as it's returning a texture).

Same for `EXRLoader`. It should be `EXRTextureLoader` then.

**Comment by mrdoob** [comment]
> BTW: Maybe targeting `r120`? It would be good to have enough time to verify these changes on `dev`. `r119` is already published next week.

Sounds good 👌

**Comment by mrdoob** [comment]
Another benefit of `EquirectangularTexture` is that we can easily keep the original data when serialising the scene.

With `new THREE.WebGLCubeRenderTarget( 256 ).fromEquirectangularTexture()` we lose the user's data.

**Comment by WestLangley** [comment]
>With new THREE.WebGLCubeRenderTarget().fromEquirectangularTexture() we lose the user's data.

How do you lose it?

https://github.com/mrdoob/three.js/pull/19845#issuecomment-662794181

**Comment by WestLangley** [comment]
>One thing I like about EquirectangularTextureLoader : It makes the API more expressive since it's more clear from the code what type of texture is loaded.
>In the past, it was decided to go for separate classes instead of encoding type information in properties. That's the reason for having DataTexture2DArray, DataTexture3D next to DataTexture. I feel EquirectangularTexture is a good complement in that regard.

No. We have different types and loaders because the data in the file is encoded differently. An EXR environment map and an EXR image of your grandmother are not loaded differently.

We don't have `NormalMapTexture`.

**Comment by WestLangley** [comment]
>I think guessing that a texture is equirectangular based on the dimensions is prone to confusion.

From the Unity docs
https://docs.unity3d.com/Manual/class-Cubemap.html

>By default Unity looks at the aspect ratio of the imported texture to determine the most appropriate layout from the above. When imported, a cubemap is produced which can be used for skyboxes and reflections:

We only support 2 types of flat environment maps: PMREM and equirectangular. The PMREM one has aspect 1.

We currently also have the texture `mapping` property to differentiate them.

**Comment by Mugen87** [comment]
> Eventually, we could also do the PMREM automatically inside the renderer and the code would just be:

I like this idea since most user don't understand PMREM anyway. I should be an internal thing of the renderer.

**Comment by Mugen87** [comment]
>  Eventually, we could also do the PMREM automatically inside the renderer

I like this idea since most users don't understand PMREM anyway.

**Comment by mrdoob** [comment]
>> With new THREE.WebGLCubeRenderTarget().fromEquirectangularTexture() we lose the user's data.
>
> How do you lose it?

If we do `scene.toJSON()` when we reach `material.envMap` we'll find a `WebGLCubeRenderTarget` which we would have to read from GPU memory and convert into a `CubeTexture` and that'll no longer be the equirectangular texture the user loaded.

But, if I understand correctly, you're suggesting not creating `EquirectangularTexture` and continue using `Texture` with `EquirectangularReflectionMapping` and `EquirectangularRefractionMapping` instead.

**Comment by WestLangley** [comment]
Above, I said this:
```js
material.__envMap = new THREE.WebGLCubeRenderTarget( 256 ).fromEquirectangularTexture( renderer, matereial.envMap );
```
and this:

>I would avoid changing the material properties set by the user.

**Comment by mrdoob** [comment]
Yes, I wrote my answer well aware of that.

Another thing about `EquirectangularTexture` is that gets us closer from getting rid of `mapping`.
So `Cube`/`Equirectangular`/`CubeUV` could be soon redundant and next we'll have to see how to get rid of the `Reflection` and `Refraction` parts.

@WestLangley what do you think about this idea (or something similar)?

```js
texture.projection = THREE.EquirectangularProjection;
```

We're blocked because the current situation is not good. This PR can't be merged because it will break users code and we don't like making the user deal with  `WebGLCubeRenderTarget`. We're trying to propose solutions to finish this PR.

**Comment by mrdoob** [comment]
> This PR can't be merged because it will break users code and we don't like making the user deal with  `WebGLCubeRenderTarget`.

API design wise... Keep in mind that next year we'll *probably* be moving to `WebGPURenderer`. It would be great if the user only have to switch renderers without changing code. Using `WebGLCubeRenderTarget` would be confusing when rendering with `WebGPURenderer`. Three is supposed to be renderer agnostic, so the less we leak the better.

**Comment by WestLangley** [comment]
@mrdoob sad

>This PR can't be merged because it will break users code and we don't like making the user deal with WebGLCubeRenderTarget.

I understand that you changed your mind and do not want to merge this as-is. That is fine. Those things happen.

So the "second-step" must be implemented.

What is needed is to inject
```js
material.__envMap = new THREE.WebGLCubeRenderTarget( 256 ).fromEquirectangularTexture( renderer, material.envMap );
```
 into the renderer in the right place.

I thought it would be nice if @Mugen87 would help in doing that. But he has not.

I am not familiar-enough with that part of the code, otherwise I would have done it myself.

**Comment by mrdoob** [comment]
That is true. This PR is step one. And @Mugen87 suggested that before merging we should do step two too (backwards compatible). #19911 is step two but I got carried away and tried to do step three too (new API).

> What is needed is to inject
> ```js
> material.__envMap = new THREE.WebGLCubeRenderTarget( 256 ).fromEquirectangularTexture( renderer, material.envMap );
> ```

That's what [WebGLCubeMaps](https://github.com/mrdoob/three.js/blob/36d2384cd9f9c20fcb368b3937c51d936569fad0/src/renderers/webgl/WebGLCubeMaps.js) does but without polluting the API.

**Comment by WestLangley** [comment]
@mrdoob 

I think this is where we ultimately need to get to, and it appears you are heading in the right direction:

1. For `Basic`, `Lambert`, and `Phong`: an equirectangular `envMap` is converted to a cube map automatically.

2. For `Standard` and `Physical`: an equirectangular `envMap` is converted to PMREM automatically; a cube `envMap`  is also converted to PMREM automatically.

(I am not sure how to handle a user's custom `ShaderMaterial`, though.)

3. Removing the `equirect` shader chunks is now the last step -- not the first step.

This results in no API changes.

**Comment by Mugen87** [comment]
> I thought it would be nice if @Mugen87 would help in doing that. But he has not.

Such accusations are just counterproductive. No good style.

I'm trying to support this PR and #19911 as good as possible. I just want the best solution for `three.js`'s users. And that is no breaking change when the engine stops support for equirectangular textures in GLSL.

**Comment by mrdoob** [comment]
> (I am not sure how to handle a user's custom `ShaderMaterial`, though.)

I guess that's the kind of user that will have to use: 

```js
let envMap = new THREE.WebGLCubeRenderTarget( texture.image.height / 2 ).fromEquirectangularTexture( renderer, texture ).texture;
```

**Comment by mrdoob** [comment]
> I thought it would be nice if @Mugen87 would help in doing that. But he has not.

I learnt long ago to not allow me get sad when contributors don't do something. I focus on appreciating when they do something instead 🙂

**Comment by Mugen87** [comment]
I guess this PR can be closed in favor of #19911?

**Comment by mrdoob** [comment]
> I guess this PR can be closed in favor of #19911?

My PR extends this one. When my PR gets merged this will get merged too.

**Comment by Mugen87** [comment]
Interesting. Did not know this is possible^^.

**Comment by mrdoob** [comment]
Yes, I cloned `WestLangley:dev_equirect_refl_mapping` locally, continued it and made a PR.

**Comment by WestLangley** [comment]
@mrdoob Most of the changes in this PR are reverted in your PR.

Personally, I think it is best for the project if you (1) close this, and (2) _squash_ the commits in your PR so the history is more understandable.

**Comment by mrdoob** [comment]
> Personally, I think it is best for the project if you (1) close this, and (2) squash the commits in your PR so the history is more understandable.

Sorry, I don't know how to squash the commits in my PR.

This issue is really challenging my intellectual abilities in many levels. I'm trying to stay focused on solving the mipmapping and RGBE issue and move on to other issues.

**Comment by donmccurdy** [comment]
> Actually, IMHO there is a more compelling reason and it's that the current code produces artifacts in the poles ... Plus a seam in the wrapping area

Do we know if these artifacts are inherent in equirectangular projections, or just a limitation of our current code?

I'm just curious – sorry I don't have an opinion on the discussion here. In other words, regardless of the API, should we be recommending that users choose cubemaps rather than equirectangular textures when they can?

**Comment by WestLangley** [comment]
>should we be recommending that users choose cube maps rather than equirectangular textures when they can?

I don't think that is necessary. The texture is now converted to a cube map automatically by the renderer.

**Pull request closed without merging**
