### PR TITLE
ParametricGeometry: Remove from core.

### LINKED ISSUE #17381: Serialization of ParametricGeometry, ParametricBufferGeometry contains unserializable function
##### Description of the problem

The parametric function in a ParametricBufferGeometry ultimately gets serialized as `{ func }` on the geometry, and since it is a function, the object representation is no longer serializable, at least in terms of the web's [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). In the context of other serialization issues (https://github.com/mrdoob/three.js/pull/17328, https://github.com/mrdoob/three.js/pull/16816, https://github.com/mrdoob/three.js/pull/16764), maybe this issue would be better framed as, "What is the serialization strategy for three.js objects?"

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #17381.

**Description**

The design of `ParametricGeometry` makes it complex to implement a secure serialization/deserialization. 

Considering the very special character of the generator in general,  I vote to move the class to the example directory.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, the E2E tests seem to be failing. False alarm?

**Comment by Mugen87** [comment]
Two examples still used `ParametricBufferGeometry` instead of `ParametricGeometry`. Hence, I've overlooked them while searching for `ParametricGeometry`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Should we add something like this to `Three.Legacy.js`?

```js
export function ParametricGeometry() {

	console.error( 'THREE.ParametricGeometry has been moved to /examples/jsm/geometries/ParametricGeometry.js' );
	return new BufferGeometry();

}
```

**Comment by Mugen87** [comment]
Sounds good! Are you going to add this code or should I make another PR?

**Comment by Mugen87** [comment]
Never mind^^! c5bb5434555a3c3ddd784944a0a124f996fc721b

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
