### PR TITLE
Makes sure fog is enabled when fog type is changed

### PR DESCRIPTION
**Pull request by GGAlanSmithee**
Fixes point 3 of #9227

Just adding a dispatch handler seems to do the trick

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, shouldn't this go in `viewport.js` instead?

**Comment by GGAlanSmithee** [comment]
`viewport.js` is already listening for fog changes and updating accordingly, but if I understand it correctly it is non-trivial to just update the scene when changing fog type (According to [this](https://github.com/mrdoob/three.js/wiki/Updates)). Might be a missunderstanding on my part though.

The reason that I added the event listener to the `Sidebar.Project.js` is that it has the internal function `createRenderer` which re-creates the renderer, making the fog appear.

If it is possible to enable fog without recreating the scene that would be much better though, so I will see what I can do.

**Comment by GGAlanSmithee** [comment]
Looking at `viewport.js` it looks like the scene is properly updated when fog type or params are changed, but the changes still aren't applied to the scene though.

**Comment by GGAlanSmithee** [comment]
Rebased on dev since the modules PR was accepted.

**Comment by mrdoob** [comment]
Hmmm, that's a bug in `WebGLRenderer` then. Shaders should recompile if fog changes...

**Comment by GGAlanSmithee** [comment]
> Hmmm, that's a bug in WebGLRenderer then. Shaders should recompile if fog changes...

Okay, I will close this PR for now since it's obviously wrong. I will attempt to create an isolated reproduction and if successful, I will open a new issue on it.

**Comment by GGAlanSmithee** [comment]
#9384

**Pull request closed without merging**
