### PR TITLE
Zoom over position.

### PR DESCRIPTION
**Pull request by Dubiy**
Zooming over point of interest (under cursor), not over center of canvas.

Available to switch on that option, by setting this.zoomOverPosition = true;
Disabled by default.

### CODE REVIEW

**Comment by Mugen87** [comment]
Does your PR aim for the same goal as #17145?

**Comment by Dubiy** [comment]
> Does your PR aim for the same goal as #17145?

Looks similar, but my solution for OrthographicCamera

**Comment by Mugen87** [comment]
The PR of @WestLangley actually supports both orthographic and perspective cameras.

**Comment by Mugen87** [comment]
Closing in favor of #17145. Thanks for your effort though!

**Pull request closed without merging**
