### PR TITLE
Temporal Anti-Aliasing at a cost of 1 render per frame

### PR DESCRIPTION
**Pull request by bhouston**
This PR introduces the TAARenderPass, which is derived from the MSAARenderPass.  The TAA render passes operates like the MSAARenderPass unless you set the "accumulate" flag.  Once that flag is set, the TAA render pass will accumulate across frames the camera jittered renders.  If the scene is static it will, after 16 frames, produce a perfectly 16x MSAA anti-aliased result, but without any frame-rate sacrifice.

This TAARenderPass can be further improved once we implement a true deferred pipeline via the use of a motion vector pass, then it could do the accumulation even when the scene is dynamic by using the motion vectors to find out what the previous pixel values were.

I am sure there are more ways we can improve the TAA approach but this at least gives us a basic approach to start with.

Details on the general theory: http://iryoku.com/aacourse/

### CODE REVIEW

**Comment by bhouston** [comment]
Example of a sene that refines to MSAA 16x when static at a cost of 1 render per frame:

http://ci.threejs.org/api/pullrequests/8178/examples/webgl_postprocessing_taa.html

**Comment by bhouston** [comment]
More details on what was implemented (but without motion vector pass, it only supports static scene AA): http://bartwronski.com/2014/03/15/temporal-supersampling-and-antialiasing/

**Comment by MasterJames** [comment]
Nice work as always. Thanks for this improvement and taking the temporal approach.

**Comment by makc** [comment]
> by using the motion vectors to find out what the previous pixel values were

but there is lighting difference, and also things like video textures...

**Comment by bhouston** [comment]
The motion vector approach has thresholds they use to exclude long vectors
and I believe major changes or something like that.  All major AAA games
use taa now including star wars battlefront and fall out 4.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by bhouston** [comment]
I've just updated this further so that as it is accumulating the temporal anti-alias samples it is showing the incremental refinement.  Thus the refinement happens faster and it fades in so it is less jarring.

Also fixed a bug in both the msaa and taa routines as I wasn't accumulating alpha correctly.

**Comment by mrdoob** [comment]
Great stuff Ben!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
