### PR TITLE
MeshMatcapMaterial: Add support for vertex tangents

### LINKED ISSUE #22245: Matcap with Normal map not working on sketchfab gltf but works with gltf exported from blender
**Describe the bug**

All gltfs from sketchfab which i tested are not able to turn on matcap + normalmap . 
If i open the same model  in blender & re export as gltf then matcap + normalMap works

**To Reproduce**

1. Get these models:
-  from sketchfab: [ZIP](https://github.com/mrdoob/three.js/files/6917844/modular_sci-fi_wall_test_2.zip) taken from [here](https://sketchfab.com/3d-models/modular-sci-fi-wall-test-2-060031f51d7246379186bbc626be13b9)

- blender version : [blenderExport.zip](https://github.com/mrdoob/three.js/files/6917876/blenderExport.zip)

2. turn on matcap 
3. set model's normalmap as matcapMaterial.normalMap

**Screenshots**

gltf from sketchfab
error

same gltf from blender
after

**Platform:**

 - Device: [Desktop,]
 - OS: [Windows,]
 - Browser: [Chrome]
 - Three.js version: [r131]
 
 _if anyone can let me know how to add an external model(in this case gltf+bin+textures)  into jsfiddle ...i'll setup a fiddle also_

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #22245.

### CODE REVIEW

**Comment by WestLangley** [comment]
Why am I getting all these extra commits? :/

**Comment by Mugen87** [comment]
The squash and merge option creates new commits which are different compared to the original ones. Hence, I create new branches for a feature or force-push to the latest commit on `dev` in order to avoid them.

**Comment by WestLangley** [comment]
I assume this is mergeable...

Hopefully I fixed it for future PRs with `git reset --hard upstream/dev`...

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
