### PR TITLE
Remove reference to THREE in IcosahedronGeometry.js

### PR DESCRIPTION
**Pull request by kexhest**
Remove old reference to the THREE namespace.

### CODE REVIEW

**Comment by magnus-bergman** [comment]
I see now that there are more geometries that still use have references to the THREE namespace. This makes the code unable to build when including three from src in projects. I only fixed this error since this was causing me issues. Do you want me to fix the others and squash the fixes into this PR?

**Comment by Mugen87** [comment]
> Do you want me to fix the others and squash the fixes into this PR?

That would be great!

**Comment by mrdoob** [comment]
> Do you want me to fix the others and squash the fixes into this PR?

Yes please!

**Comment by magnus-bergman** [comment]
Done!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
