### PR TITLE
Revert VideoTexture: Added frameRate property

### PR DESCRIPTION
**Pull request by mrdoob**
For some reason sometimes, on Chrome the uploaded texture is from a previous video frame 🤔

See #12763

### CODE REVIEW

**Comment by netpro2k** [comment]
Hmm I was going to try something very similar (though probably using a `THREE.Clock` to use `performance.now()` when available). Since there is no synchronization between the video frames and the frame limiting, its not unexpected that you might end missing a frame sometimes. You would probably need to set the frame limit to slightly higher than the video framerate (or accept that you may sometimes be a frame behind). This is obviously not ideal, but neither is submitting the texture at 90FPS for a 30FPS video so it might still be a useful feature (maybe off by default?) until we come up with something better.

Also, how were you able to debug the texture being a frame behind?

**Comment by mrdoob** [comment]
> Also, how were you able to debug the texture being a frame behind?

Oh, the issue was not it was one frame behind. The issue was that the frames that I would see presented were something like this:

```
0, 1, 2, 4, 3, 5, 6, 7, 9, 8, ...
```

It's probably a Chrome bug that I'll have to report. 

I'll investigate this a bit more this week.

**Comment by mrdoob** [comment]
Opened an issue for it: #13379

**Comment by netpro2k** [comment]
Hmm does this frame ordering bug only happen when doing FPS limiting?

**Comment by mrdoob** [comment]
Yes

**Pull request merged**
