### PR TITLE
Make the material easier to extend for WebGLRender

### PR DESCRIPTION
**Pull request by brianxu**
update of #5812

### CODE REVIEW

**Comment by mrdoob** [comment]
I think I would prefer to keep materials away from uniforms and attributes... Think of materials as definitions that other renderers (which don't use uniforms) can also render.

**Comment by brianxu** [comment]
@mrdoob it's fine if you want to keep the abstract meaning for materials, but for webGL, essentially a material is a shader, and you cannot get away with uniforms, right? You can still use these materials if you just want to use the properties it will still work.The current way that embed all the uniforms logic inside the renderer makes it hard to extend the existing material and update the uniforms. I think this change is natural to me, but I am open to suggestion if you think there is a better solution.

**Comment by brianxu** [comment]
@mrdoob how about rename the refreshUniforms into something like updateMaterial? and we can maybe pass in the renderer and do some updates based on the renderer type? that seems to be more abstract.

**Comment by mrdoob** [comment]
That sounds better. Could you write a example usage here?

**Comment by brianxu** [comment]
ok, let's use the LineBasicMaterial as an example:
THREE.LineBasicMaterial.prototype.update = function ( uniforms ) {
	this.refreshUniformsLine( uniforms );
};

THREE.LineBasicMaterial.prototype.update = function ( renderer ) {
	if (renderer instanceof WebGLRenderer)
		this.refreshUniformsLine( uniforms );// I think it makes sense to have this inside the Material.js
        if (renderer instanceof CanvasRenderer)
		//update something, if there is update logic inside CanvasRenderer?
};

THREE.LineBasicMaterial.prototype.getID = function () {
	return 'basic';
};

**Comment by coballast** [comment]
I think it would be better if you had renderer specific logic in the renderer itself, rather than switching based on what kind of renderer it is. So for example, every renderer could implement it's own update() method, and LineBasicMaterial would call that, passing itself in as an option. Let the subclasses handle the details.

**Comment by dmtaub** [comment]
I think the problem this is trying to solve is that it's impossible to use
materials that don't conform to the existing material assumptions without
modifying the renderer. If each material takes care of its own rendering,
it becomes much easier to add-on new kinds of materials that handle their
uniforms in a different way.

It reminds me of a similar problem I've had where the loader has a huge
conditional branching for every type of Object3D. This makes it incredibly
difficult to add new subclasses for Object3D.

Would another solution be for the renderer to provide an API to register
material types and then use some internal object that maps type->update
function ?

**Comment by dmtaub** [comment]
any movement on this? It's very hard to make custom materials without forking three.js while a switch statement in the renderer is the only way to add new functionality...

**Comment by mrdoob** [comment]
Could this extend `RawShaderMaterial`?

**Comment by brianxu** [comment]
Yes we can. But it might be very ugly, because we still want to reuse the builtin uniforms and we will basically have lots of duplicate code inside RawShaderMaterial.
These PR try to solve two problems:
1. reuse the update of uniforms
2. add a handler for update uniforms in each material so that it's customizable

**Comment by brianxu** [comment]
@mrdoob can you suggest a way to solve the 2nd problem?

**Comment by chen-pang** [comment]
Can we add custom uniform support for just ShaderMaterial or create a new material type that inherits from ShaderMaterial? Custom uniforms are only needed when we are writing our own shaders I think.

We then only need additional handling for this material type in the main render method then. Nothing else is impacted.

**Comment by brianxu** [comment]
yeah, I agree it could work in that way as long as we are not trying to extend the built in threejs material class, which is certainly a pity. But the change will be much smaller and more likely to be accepted then.

**Comment by tschw** [comment]
The plan is to make the ShaderMaterial case the main code path in the WebGL renderer (see posts by @WestLangley and me in #6885). Then we can remove all `instanceof` operators and use proper subclassing. Right now, a factory method returning a `ShaderMaterial` instance is the way to go for client code (if you set `.lights = true` and define the uniforms, you get the lighting info passed in). 

Shaders (= their specifications) need an own representation in the data model, because multiple materials (= ShaderMaterials) may use the same shader under different parameterization. Also note that shader specifications are in fact templates that are instantiated, IOW one shader specification can compile to a multitude of actual programs. In the GLSL case, instantiation happens via the GLSL preprocessor (see #6963).
The concept of a Shader is an abstract one and not at all bound to a specific renderer: A software renderer may compile RenderMan to JavaScript, and a raytracing renderer may compile OSL to compute shaders for WebGL2, just to come up with some fun futuristic examples. We may want to use GLSL as the default shading language for now, though :-).

Extending the existing shading code is currently quite difficult. There is a lot of "low level hacking" going on, because the higher level components are difficult to customize and still too incomplete to embrace that use case. For the same reason, there are many code submissions that do not consider the library as a whole.

I'm working on a proper solution to these problems, but it's taking some time as there are several tools to be written. I haven't published any of the code yet, and it's not that urgent (unless anyone want to help me), as the in-core changes to Three.js will be minimal. Maybe I should let the cat out of the bag soon?

However, the material data model will have to be improved, as mentioned in the second paragraph of this message and detailed in #6963. That ticket contains a mrdoob-approved recipe for the next step for improving the current situation. Feel free to pick it up if you want to help, @brianxu .

**Comment by tschw** [comment]
@chen-pang 
> Can we add custom uniform support for just ShaderMaterial

I beg your pardon? `ShaderMaterial` certainly *does* support custom uniforms. :-) Also note that subclassing is overrated :-). Here is how you get a similar amount of syntactic sugar:

```javascript
function createMySpecialMaterial( /* ... */ ) {

    var uniforms = {

        // reference entries to control globally,
        // copy entries to control on a per-material basis

    };

    var instance = new THREE.ShaderMaterial( { uniforms: uniforms /* ... */ } );

    /* ... */

    instance.mySpecialMethod = function( /* ... */ ) {

        /* ... */

    };

    return instance;

}
```

You could also just put application-specific methods directly on `ShaderMaterial.prototype`...

**Comment by chen-pang** [comment]
@tschw Sorry I wasn't clear in my comment. I was talking in the context of this thread, and I should say 'better' custom uniform support. 

What the PR is trying to achieve, is to provide a better way to update values of custom uniforms. Currently the values of default uniforms in ShaderMaterial get updated in each render pass, and the values of custom uniforms can only be updated with separate logic. This causes much inconvenience because we do use uniforms whose value should be updated all the time.

**Comment by tschw** [comment]
> I was talking in the context of this thread

Me too, sorry in case I wasn't clear :-).

> Currently the values of default uniforms in ShaderMaterial get updated in each render pass, and the values of custom uniforms can only be updated with separate logic. This causes much inconvenience because we do use uniforms whose value should be updated all the time.

@chen-pang 
Unless you are talking about a bug present in `r71`, fixed in `r72`, and in effect when uniforms are setup in an unfortunate way, both custom and standard uniforms are updated (that is, uploaded to the GPU program) on every render for `ShaderMaterial`. 

Using custom uniforms you'll logically always have to set their values *somewhere*. You can establish central control of values that are the same for all materials by referencing the same entry.

```javascript
// Initialization:
var timeUniform = { type: 'f', value: 0 };
material1.uniforms[ 'time' ] = timeUniform;
material2.uniforms[ 'time' ] = timeUniform;
// ...
var startTime = Date.now();
// ...

// Every frame:
timeUniform.value = Date.now() - startTime;
// Note: If you change the identity of material.uniforms or its properties
// you have to set material.needsUpdate = true and it may not work with r71.
// The values are always updated, unless you hit the bug in r71.
renderer.render( scene, camera );
```

In case you need to dispatch based on the (logical) type of the material (not the type of the JavaScript object, that one must always be `ShaderMaterial`), you can use the pattern from my previous post, and attach an `.updateCustomUniforms` (or however you want to call it) method to your objects and call it on each material before calling `render`. Alternatively, you can enumerate your custom material "types" and `switch`.  

I fail to see how not having a JavaScript type (that is, a constructor, a prototype, and the opportunity to use `instanceof` to get yourself into the kind of trouble we are in :-)), for your individual materials can possibly be anything but a *minor* inconvenience in a loosely-typed scripting language, but I agree that the limitation is not pretty. As I explained in this thread, just moving forward as planned will solve this issue - and the major ones too.

**Comment by chen-pang** [comment]
@tschw You're right, I was just saying this is causing `inconvenience`, and can get improved.

The inconvenience may not be _minor_ in some situations. Imagine your just need one extra matrix in your shader that's not standard, which you'd expect it's just a minor issue. But now you need to modify the main render routine and need to traverse all scene objects and update their material. This might not be so easy as it seems in some project, as this part usually sit in some central location and any change may require much more discussion among developers working on the same project than needed when simply changing a material.

**Comment by tschw** [comment]
> The inconvenience may not be minor in some situations. Imagine you just need one extra matrix in your shader that's not standard, which you'd expect it's just a really trivial problem.

It is?!

> If THREE.js default renderer checks for the existence of .updateCustomUniforms() and call it when it is updating all the standard uniforms, it can save a lot of trouble. 

I don't think a callback mechanism of that kind really belongs onto the material or any scene graph object.

What if the material gets used multiple times by different objects?

Since you are not asking to be passed the object, I guess your matrix is the same for all shaders. In this case you can just set up your materials to reference the same data, and update only one matrix from the outside.

> But right now to support that, you need to modify the main render routine, traverse all scene objects and update their material. 
> This might not be so easy as it seems in some project, as this part of code usually sit in a central location and any change there may require much more discussion among developers working on the same project than needed when simply changing a material.

Okay, in that case, you should fight for some kind of `.beforeRender` callback. The discussion with your fellow developers seems well-invested and overdue ;-).

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6318

**Pull request closed without merging**
