### PR TITLE
Hopf Torus application

### PR DESCRIPTION
**Pull request by stla**
Related issue: #14140

**Description**

The Hopf torus application. I use `dat.gui.min.js`, I don't know how to use `lil-gui`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/stla/three.js/hopfapplication/examples/webgl_geometry_hopf.html

**Comment by Mugen87** [comment]
> I use dat.gui.min.js, I don't know how to use lil-gui.

You can study the existing examples in order to understand how `lil-gui` is used. There is not much of a difference.

**Comment by stla** [comment]
You're right, that's almost the same. I've just done an update. Does it work now? I don't know how to run the app locally with `<script type="module">`.

**Comment by stla** [comment]
I ran `npm install make-screenshot` but now the screenshot is entirely black.

**Comment by Mugen87** [comment]
The example code is broken:

> Uncaught ReferenceError: pt is not defined
    at renderSphericalCurve (webgl_geometry_hopf.html:547)
    at init1 (webgl_geometry_hopf.html:554)
    at webgl_geometry_hopf.html:68

Please do not share untested code. You can verify the new example by running a local web server. Read the following guide for more information:

https://threejs.org/docs/index.html#manual/en/introduction/How-to-run-things-locally

**Comment by stla** [comment]
Ok, sorry.

**Comment by stla** [comment]
Ok, I use a R package to run a server and this works.

This error didn't occur with my pure JS version (no module). It was `for(pt in array)` instead of `for(let pt in array)`.

I have  a strange error message: `THREE.ParametricGeometry has been moved to /examples/jsm/geometries/ParametricGeometry.js`. However this is the path I provide:

`import { ParametricGeometry } from './jsm/geometries/ParametricGeometry.js';`.

**Comment by Mugen87** [comment]
When you import `ParametricGeometry` via ES6 modules, you don't need to use the `THREE` namespace.

Instead of adding new example, how about adding the new geometry to [webgl_geometries_parametric](https://threejs.org/examples/webgl_geometries_parametric) instead? The parametric equation could be added [here](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/geometries/ParametricGeometries.js).

**Comment by stla** [comment]
> When you import `ParametricGeometry` via ES6 modules, you don't need to use the `THREE` namespace.
> 
> Instead of adding new example, how about adding the new geometry to [webgl_geometries_parametric](https://threejs.org/examples/webgl_geometries_parametric) instead? The parametric equation could be added [here](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/geometries/ParametricGeometries.js).

Hmm not sure it is doable, because my parametric geometry depends on a Catmull curve preliminarily calculated. But if you want I can add the ["tennis ball" Hopf torus](https://laustep.github.io/stlahblog/posts/HopfTorus2.html) geometry, which is self-contained.

**Comment by stla** [comment]
By the way, [here](https://laustep.github.io/stlahblog/posts/myJSartworks.html) are my threejs artworks, if you want to take a look.

**Comment by Mugen87** [comment]
@stla This is not the right place to promote your work.

**Comment by Mugen87** [comment]
> But if you want I can add the "tennis ball" Hopf torus geometry, which is self-contained.

Sounds good!

**Comment by mrdoob** [comment]
> But if you want I can add the "tennis ball" Hopf torus geometry, which is self-contained.

Yep, that sounds better 👍

**Comment by mrdoob** [comment]
#23068

**Pull request closed without merging**
