### PR TITLE
Updates and Fixes for View Source #9462

### PR DESCRIPTION
**Pull request by espnicholas**
Adds functionality of appending raw source from examples to simple modal. This addresses issues from #9462 and expands on #9463 

Let me know your input, I can always expand on this in the future when I have more time.

screencapture-localhost-8888-three-js-examples-1470343386168
screencapture-localhost-8888-three-js-examples-1470343407974

### CODE REVIEW

**Comment by espnicholas** [comment]
@mrdoob I've looked more into syntax highlighting, are we allowed to include small(2kb) JavaScript vendor/lib files to the project? And if so would it be referenced from the examples/js/lib folder?

**Comment by espnicholas** [comment]
@mrdoob Here is a preview of what it would look like with highlighting. Also is line numbers desired?

syntax-hightlighting

**Comment by espnicholas** [comment]
Heres the example with line numbers.

view-source--line numbers

**Comment by mrdoob** [comment]
That looks good! Is the PR ready to go then?

**Comment by espnicholas** [comment]
I need to commit some of the updates and we'll be good! @mrdoob

**Comment by espnicholas** [comment]
@mrdoob Okay! We should be good

**Comment by espnicholas** [comment]
@verteAzur I didn't think of linking the links to the js libraries. That's an idea, but maybe for another PR. 👍

**Comment by mrdoob** [comment]
Sorry, I ended up opting for keeping it simple and just linking to github instead.

**Comment by mrdoob** [comment]
Thanks though!

**Comment by verteAzur** [comment]
With r81 and no connection, I get the old view source function, which is perfect... Thanks for all considerations!

**Comment by mrdoob** [comment]
Uhm?

**Pull request closed without merging**
