### PR TITLE
Editor: Improved ShaderMaterial panel

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

Before:

Screen Shot 2021-03-06 at 9 21 26 AM

After:

Screen Shot 2021-03-06 at 9 21 47 AM

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
Is there any possibility we can better align these elements to their parent grid?

(left versus right)

Frame 1

**Comment by mrdoob** [comment]
That'd be nice indeed!
Not sure if it'll work everywhere though.

**Comment by CodyJasonBennett** [comment]
I'll have to look, but I wouldn't think it would be too hard to use flexbox here.

**Comment by mrdoob** [comment]
Famous last words...

**Pull request merged**
