### PR TITLE
ImageLoader: Inherit from Loader.

### PR DESCRIPTION
**Pull request by Mugen87**
Next `ImageLoader`.

### CODE REVIEW

**Comment by Mugen87** [comment]
I wonder do we really need the following line in `ImageLoader.load()`?

https://github.com/mrdoob/three.js/pull/17327/files#diff-5a20f4f2a40cdef2c71315768c612ce9L21

The loaders do usually not perform such parameter verification.

**Comment by mrdoob** [comment]
> I wonder do we really need the following line in `ImageLoader.load()`?

We can remove it I think.

**Comment by Mugen87** [comment]
Done!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
