### PR TITLE
README: Fixed GB punctuation

### PR DESCRIPTION
**Pull request by MrPaschenko**
**Description**
Insert a space between the numerical value and the unit symbol: “2 GB”

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
How is this a typo?

**Comment by MrPaschenko** [comment]
Well, it's not a typo, but just punctual rules:)

https://english.stackexchange.com/questions/2794/punctuation-with-units

**Comment by mrdoob** [comment]
I see...

**Comment by mrdoob** [comment]
Thanks

**Pull request merged**
