### PR TITLE
WebGLRenderer: Remove RGBEEncoding and RGBEFormat.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This PR removes `RGBEEncoding` and `RGBEFormat`.

That means `RGBELoader` and `HDRCubeTextureLoader` do not support `UnsignedByteType` anymore.

### CODE REVIEW

**Comment by chubei-oppen** [comment]
Is it possible to revert this? There're still devices out there not supporting floating point texture extensions.

**Comment by Mugen87** [comment]
No sorry. We definitely remove all inline GLSL decodes. You have to enhance the build-in shaders by yourself if you still need    RGBA8 HDR textures.

**Comment by chubei-oppen** [comment]
I see. May I ask what's the motivation behind it? It certainly makes keeping our fork up-to-date with main repo more difficult, so I'm curious about what we are paying for.

**Comment by Mugen87** [comment]
The general approach of inline decode and encodes is problematic. It produces wrong texture filtering and can break blending. Since WebGL 2 is now mature enough, we've decided to make Float16 mandatory for HDR workflows.

**Comment by chubei-oppen** [comment]
TBH I don't know anyone complaining `RGBEEncoding` because it's only used in IBL. The filtering was handled in built-in shader code and no blending will be taking place. But thanks for you answer still.

**Comment by mrdoob** [comment]
@chubei-oppen 

> There're still devices out there not supporting floating point texture extensions.

What devices are those?

> It certainly makes keeping our fork up-to-date with main repo more difficult,

Out of curiosity, what other modifications did you need to do that required a fork?

**Comment by chubei-oppen** [comment]
@mrdoob Sorry, not devices. Platforms actually. 

[WeChat Mini Program](https://developers.weixin.qq.com/miniprogram/en/dev/component/canvas.html) only supports WebGL and a very limited set of extensions(not the same set depending on OS/device). And they won't add WebGL2 support in the near future(we know because we're working closely with Mini Program group). But WeChat has over 1 billion users so I expect a lot of people sticking to below r136 just to keep their app running on WeChat. These people will be Chinese developers so the feedback won't be as strong as the actual impact because of the language barrier.

Other mini programs, namely Taobao from Alibaba and TicTok, have similar levels of WebGL support the last time I checked it(several months ago).

As of our fork, there are two big things that are important to us but I don't see hope merging into upstream:

- Vendor glTF extension support, such as https://github.com/oppenfuture/glTF/blob/hpnormal/extensions/2.0/Vendor/OFT_texture_highPrecisionNormal. We have more.
- An ugly Adreno bug workaround https://github.com/oppenfuture/three.js/pull/36.

**Comment by mrdoob** [comment]
> [WeChat Mini Program](https://developers.weixin.qq.com/miniprogram/en/dev/component/canvas.html) only supports WebGL and a very limited set of extensions(not the same set depending on OS/device). And they won't add WebGL2 support in the near future(we know because we're working closely with Mini Program group).

That's unfortunate...

Right now there are 3 code paths: WebGL1, WebGL2 and WebGPU...

We do not have the resources to maintain all of them and we have to align with the stacks modern browsers are focusing on (WebGL2 and WebGPU).

Hopefully WeChat and co will update to WebGL2 and WebGPU soon.

> - An ugly Adreno bug workaround https://github.com/oppenfuture/three.js/pull/36.

This shouldn't require a fork. We implemented this workaround too last year.

**Comment by chubei-oppen** [comment]
> We do not have the resources to maintain all of them and we have to align with the stacks modern browsers are focusing on (WebGL2 and WebGPU).

Totally understand. Your work on three.js has been incredible, and we owe huge thanks to all three.js contributors. I was not complaining about removing this feature, just trying to give information that you might not have and see if it changes the decision. We'll pay what we have to for supporting outdated platforms.

> This shouldn't require a fork. We implemented this workaround too last year.

If you're referring to https://github.com/mrdoob/three.js/pull/21202, that's a different bug. The bug we were trying to fix can be reproduced with [this page](http://beiyu.me.uk/adreno_6xx_webgl_bug.html). You should see a black quad in a gray background, but with Adreno 6xx GPU the quad would be blue.

**Comment by mrdoob** [comment]
>> This shouldn't require a fork. We implemented this workaround too last year.
>
> If you're referring to https://github.com/mrdoob/three.js/pull/21202, that's a different bug. The bug we were trying to fix can be reproduced with [this page](http://beiyu.me.uk/adreno_6xx_webgl_bug.html). You should see a black quad in a gray background, but with Adreno 6xx GPU the quad would be blue.

Hmm, is that because Adreno ignores the precision of numbers when using structs?
https://twitter.com/garrettkjohnson/status/1453446051738767361

**Comment by chubei-oppen** [comment]
> Hmm, is that because Adreno ignores the precision of numbers when using structs? https://twitter.com/garrettkjohnson/status/1453446051738767361

Yes, I believe so.

**Comment by mrdoob** [comment]
Grrrr

**Comment by gkjohnson** [comment]
> Hmm, is that because Adreno ignores the precision of numbers when using structs? https://twitter.com/garrettkjohnson/status/1453446051738767361

I've made an issue in the Khronos WebGL repo for this but so far not a whole lot more info, yet:

https://github.com/KhronosGroup/WebGL/issues/3351

**Comment by mrdoob** [comment]
@chubei-oppen

> [WeChat Mini Program](https://developers.weixin.qq.com/miniprogram/en/dev/component/canvas.html) only supports WebGL and a very limited set of extensions(not the same set depending on OS/device). And they won't add WebGL2 support in the near future(we know because we're working closely with Mini Program group).

Would it be possible for you to ask them what are the reasons they won't add WebGL2?

**Comment by chubei-oppen** [comment]
They have other priorities. There's no strong enough motivation for them to put resources into WebGL2.

**Pull request merged**
