### PR TITLE
Examples: Added panoramic 6DOF example 🌐

### PR DESCRIPTION
**Pull request by juniorxsound**
**What?**
Add an example that shows how to use 360 panoramas with depth maps to apply vertex displacement and create 6 degrees of freedom 360 panoramic environment.

Desktop example 
6DoF

VR example
quest

### CODE REVIEW

**Comment by mrdoob** [comment]
Very nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
Looking nice! BTW some code indentation seems broken. Do you fix in your side @mrdoob ?

**Comment by mrdoob** [comment]
I'll have time to clean it up next week, unless someone does before me.

I'm also curious to test if the `ShaderMaterial` is needed, or if the effect can be also achieved with a `MeshBasicMaterial` and the `displacementMap` property.

**Comment by juniorxsound** [comment]
@mrdoob @takahirox Thanks 🎉 I can spend some time cleaning up the example and investigating whether it could be done without the `ShaderMaterial`

**Comment by mrdoob** [comment]
That'd be great!

**Comment by juniorxsound** [comment]
After a quick test I realized this could totally be done with a `MeshStandardMaterial` and a negative displacement scale - will commit the simplified version! Thanks for the suggestion @mrdoob 🙏🏽

meshstandardmaterial

**Comment by kanybekasanbekov** [comment]
Can anyone explain me how can view 360 panorama like this?

**Comment by Mugen87** [comment]
@kanybekasanbekov Please use the forum for [help requests](https://discourse.threejs.org/).

**Comment by mrdoob** [comment]
Actually, this probably should be done with `MeshBasicMaterial` too. But it doesn't support `displacementMap` 🤔

**Comment by juniorxsound** [comment]
@mrdoob I can definitely take a look at adding `displacementMap`, `displacementScale` and `displacementBias` to `MeshBasicMaterial`, do you think it makes sense to add it?

**Comment by mrdoob** [comment]
I was trying to think why it was only in `MeshStandardMaterial`, but I don't see why it couldn't be in `MeshBasicMaterial`, `MeshLambertMaterial` and `MeshPhongMaterial` too yeah.

**Pull request merged**
