### PR TITLE
WebGLRenderer: Revert to drawingbuffer sized transmissionRenderTarget

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #26131 #25494

**Description**

This PR reverts #26131 because performance was really bad on mobile.

It also reverts #25494 as I am still not convinced the blinking artefacts we see with `royal_esplanade_1k.hdr` are good enough reason to sacrifice the quality in materials with low `roughness`.

/cc @elalish

### CODE REVIEW

**Comment by mrdoob** [comment]
After merging this I wanted to try the WebGL 1 path (`floorPowerOfTwo`):

```js
_this.getDrawingBufferSize( _vector2 );
_transmissionRenderTarget.setSize( floorPowerOfTwo( _vector2.x ), floorPowerOfTwo( _vector2.y ) );
```

| getDrawingBuffer | floorPowerOfTwo |
| --- | --- |
| Screenshot 2023-05-26 at 20 27 33 | Screenshot 2023-05-26 at 20 27 37 |

Interestingly, the black parts of the lightbulb filament look pretty much the same but the bright part of the filament becomes much more blurred/pixelated.

Does anybody understand why this happens?

/cc @elalish @WestLangley @N8python

**Comment by mrdoob** [comment]
Here's a video that may help:

https://github.com/mrdoob/three.js/assets/97088/09db68fd-ad20-483f-909b-0310e72007dd

I did it while we were working on #25483.

**Comment by elalish** [comment]
Agreed with @WestLangley - that's super strange. Maybe a bad blur that isn't hitting all the pixels? 

@mrdoob, the reason the filament looks more blocky is that it has values >>1, next to values <1 - they're getting interpolated linearly, and then tone-mapped after. This results in looking almost like nearest interpolation. All the pixel interpolation and antialiasing (stuff for perceptual niceness) really needs to happen after tonemapping to work properly. 

Also @mrdoob, your second video appears to be an image. Do you have any idea what's causing what you see? Is the blur based on depth or something?

**Comment by mrdoob** [comment]
> Also @mrdoob, your second video appears to be an image. Do you have any idea what's causing what you see? Is the blur based on depth or something?

Damn! So hard to share that video... I've updated the post.

**Comment by mrdoob** [comment]
I think I understand the issue.

As you say, it's linear interpolating and it doesn't have enough pixels to interpolate to such high values and ends up being blocky/pixelated.

I feel like reverting to 1024x1024 texture just happened to produce better results with that environment, but the issue is still there.

**Comment by WestLangley** [comment]
It doesn't happen when the background is flat. Comment out `EquirectangularReflectionMapping`.

**Comment by Mugen87** [comment]
Where you can see the flickering pretty well is in [webgl_loader_gltf_lights](https://rawcdn.githack.com/mrdoob/three.js/dev/examples/webgl_loader_gltf_lights.html).

If we can't find a final solution for this issue, I vote to revert to the `r152` state so there is no change in behavior. The blinking feels like a bug whereas the the lower (1024x1024) resolution is just a quality issue.

**Comment by mrdoob** [comment]
> It doesn't happen when the background is flat. Comment out `EquirectangularReflectionMapping`.

Made a screen recording to try to understand... What is it that doesn't happen? 

https://github.com/mrdoob/three.js/assets/97088/df3b50b2-ab02-4969-ad90-0cff43cca7ed

**Comment by mrdoob** [comment]
Any chance you could do a screen recording...?

**Comment by mrdoob** [comment]
@Mugen87 

> If we can't find a final solution for this issue, I vote to revert to the `r152` state so there is no change in behavior. The intense blinking in `webgl_loader_gltf_lights` feels buggy whereas the the lower (1024x1024) resolution more like a quality issue.

As far as I remember, we originally reverted to 1024x1024 because @WestLangley mentioned the color changes in `webgl_materials_physical_transmission` and now there's the blinking issue in `webgl_loader_gltf_lights`.

At the same time, @elalish's feedback is that `model-viewer`'s transmission looks bad.

I fear our examples are not representative of most projects that use transmission out there...

Before reverting I would like to hear more from the community.

**Comment by WestLangley** [comment]
>Any chance you could do a screen recording...?

To test a "flat" background, I modified the example like so:

```js
//texture.mapping = THREE.EquirectangularReflectionMapping;
texture.offset.set( 0.67, 0.55 );
texture.repeat.set( 0.125, 0.125 );
```
Sorry about the ugly banding. It is not evident in practice... 

Flat Background

**Pull request merged**
