### PR TITLE
Fix cinematic camera example

### PR DESCRIPTION
**Pull request by takahirox**
This PR fixes broken cinemaric camera example #13729

@Mugen87 

Why DEPTH_PACKING comparison in fragment shader of `BokehShader2` is not

	#if DEPTH_PACKING == 3201

but

	#if DEPTH_PACKING == 1

?

3201 is `THREE.RGBADepthPacking`.

### CODE REVIEW

**Comment by Mugen87** [comment]
It is just a `true`/`false` flag :blush: 

I've reused this pattern from other shaders e.g.
https://github.com/mrdoob/three.js/blob/22dffb009a63c3687821ccdab5b2f81badca8ed8/examples/js/shaders/SAOShader.js#L79-L85

**Comment by Mugen87** [comment]
The depth material of `CinematicCamera` also needs `RGBADepthPacking`.

https://github.com/takahirox/three.js/blob/f069efb0d79b7b9adadc30005d7c832543a68db5/examples/js/cameras/CinematicCamera.js#L20

```js
this.material_depth = new THREE.MeshDepthMaterial();
this.material_depth.depthPacking = THREE.RGBADepthPacking;
```

**Comment by Mugen87** [comment]
Test link: https://rawgit.com/takahirox/three.js/FixCinematicCamera/examples/webgl_camera_cinematic.html

**Comment by takahirox** [comment]
Thanks, I've updated.

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
