### PR TITLE
Documentation: Add 'import maps' section to Installation docs

### PR DESCRIPTION
**Pull request by donmccurdy**
Following up on #19622.

Link: https://raw.githack.com/mrdoob/three.js/donmccurdy-docs-import-maps/docs/index.html#manual/en/introduction/Installation

### CODE REVIEW

**Comment by donmccurdy** [comment]
^Looks like links to Glitch break because of some character in the URL? I'll need to patch `page.js` for that I think.

**Comment by gkjohnson** [comment]
Just curious is there any reason you didn't use the [trailing slash for a package root](https://github.com/WICG/import-maps#packages-via-trailing-slashes) in the [glitch example](https://glitch.com/edit/#!/three-import-map?path=index.html%3A1%3A0)? 

```js
{
  "imports": {
    "three": "https://unpkg.com/three@0.118.1/build/three.module.js",
    "three/": "https://unpkg.com/three@0.118.1/"
  }
}
```

**Comment by donmccurdy** [comment]
No important reason, although the `jsm` folder is the only one containing ES modules.

**Comment by Mugen87** [comment]
> Looks like links to Glitch break because of some character in the URL? I'll need to patch page.js for that I think.

Or you just use a `<a>` tag for now.

**Comment by donmccurdy** [comment]
Fixed ✅

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
