### PR TITLE
ObjLoader2: Minimification fix

### PR DESCRIPTION
**Pull request by Itee**
From this original [Issues](https://github.com/Itee/three-full/issues/4).

Some part of the Worker code are hard coded. In such case the minification will break due to classname replacement.

I replace the hard coded part by their constructor name that will point to the minimified version of the classname.

### CODE REVIEW

**Comment by mrdoob** [comment]
@kaisalmen https://github.com/mrdoob/three.js/pull/14874/commits/c348557a1c90fc3942c37e8898ecc37a2e731828

**Comment by mrdoob** [comment]
Thanks!

**Comment by Itee** [comment]
Thanks to you !

**Comment by mrdoob** [comment]
Done

**Comment by kaisalmen** [comment]
Thanks!

**Pull request merged**
