### PR TITLE
Firing events on shader compile or link errors

### PR DESCRIPTION
**Pull request by MiiBond**
Here's a quick change where a `THREE.Material` will dispatch a 'shaderCompileError' or a 'programLinkError' event when it fails to compile or link respectively.

This is useful if, for example, a shader fails to compile on the target hardware due to limited capabilities (e.g. varying or uniforms counts) and you want to automatically scale back the shader at run time.

This is also potentially useful if the user is editing shaders in your application and you want to handle errors cleanly. Though, I'm not currently passing any detailed information through the event.

Any suggestions or feedback on this?

I included a very contrived example where a compile error is captured, the shaders are substituted, a link error is then captured and a MeshBasicMaterial is substituted. Also, a material with many uniforms repeatedly fails to compile and the code keeps scaling the number down until it runs on your machine.

### CODE REVIEW

**Comment by dubejf** [comment]
Related #2433

**Comment by tschw** [comment]
You can iterate the array property `.info.programs` of a `WebGLRenderer` instance. This array contains all `WebGLProgram` instances produced by the renderer in random order.

When any diagnostics (warnings or errors) were issued during shader compilation a `WebGLProgram` instance contains a  `.diagnostics` structure and `.diagnostics.runnable` is `false` in case the shader actually failed to compile and there were not just warnings. This mechanism may already suffice for the use case you describe. 

If we really need an event to be fired, the renderer should just test for `diagnostics in shader && ! shader.diagnostics.runnable` after compilation. 

Your current changeset throws an exception from within `WebGLProgram` and thus breaks error feedback. Also, conditionals are added to the renderer (I'll elaborate on why this is bad below).

The mechanism described above was implemented by these two commits:

* 3ea6feb84ce278acdc0eed3cdbb7dbb8aa41c78f WebGLProgram: Compilation errors go to .diagnostics.
* 1fe7121f9cf8414460e3728ba51901cdfc6c44a9 WebGLRenderer: Exposed _programs in .info.programs.

The changes carefully avoid complicating the renderer. You may want to understand the following two commits in the same PR (#6818)

* 4aa4eeb5c7baeeafe35d7c43a6a264a941c1cfce Prevented renderer from caching outdated programs.
* d4191cf082878344ae7010152db30ebaf070387c Fixes wrong program reference counting.

just to get an idea how subtle the workings of the renderer are (these are just examples, I made some more fixes of that kind in other PRs and spent quite some time debugging that code - other developers probably made the same experience) and why we should try to improve the situation, or, most importantly, not make it worse. In other words, make sure you understand the invariants and assumptions the surrounding code relies upon and still expect the unexpected when adding stuff, ideally keeping things as simple as possible.

**Comment by MiiBond** [comment]
Thanks for the great feedback, @tschw. That's exactly what I was looking for. You're right that I didn't have a good enough understanding of the renderer's handling of programs before making this change. Having the diagnostic structure is great. The last time I paid any attention to this, compile errors weren't being handled well at all and the code would just cause a whole bunch of Javascript errors with programs not existing, etc. I guess I just assumed that the state of this was still really bad...

Anyway, using the diagnostic structure, we could fire an event in ```setProgram``` when the program isn't runnable. This would allow the fallback logic that I'm looking for. Checking the ```runnable``` flag yourself isn't ideal as you'd have to check manually after the render call is made. An event would be much cleaner.

What does everyone think? And what would be good event names? 'shaderCompileError', 'shaderLinkError', etc.?

**Comment by tschw** [comment]
> I didn't have a good enough understanding of the renderer's handling of programs

Can't blame you (or anyone else). The code isn't exactly straightforward and easy to oversee, although it keeps getting better as long as we all keep pulling in the same direction.

> the code would just cause a whole bunch of Javascript errors with programs not existing, etc

Errors from the GL may still occur - I'm not sure - if so, maybe should be prevented - certainly should, if they make the renderer choke on other parts of the scene.

> Anyway, using the diagnostic structure, we could fire an event in setProgram when the program isn't runnable. This would allow the fallback logic that I'm looking for. Checking the runnable flag yourself isn't ideal as you'd have to check manually after the render call is made. An event would be much cleaner.
>
> What does everyone think?

I don't generally object, but I'm also not convinced about its "cleanness":

Listeners usually don't return results, so there would still have to be some way to interact with the renderer to request recompilation. How would that interface look like? Event, really? Or callback?

We'd also have to make sure that all referencing materials can actually get the updated shader, without updating it over and over again for each material that uses it. In fact, we're missing a `Shader` or `GpuProgram` as a first class citizen in the data model of the scene graph, so materials can officially share shaders. Currently, it's literally all "shady business" in more or less implementation details of the renderer (and when you call `toJSON` on a scene that uses the same shader with 100 different uniform sets you get 100 copies of its code, not to mention uniform serialization). For any solution that deserves the adjective "clean" these important issues would need to be resolved in a sensible way.

Shader complations are costly operations and so it might be a good idea to let the browser take a breath after a bunch of them at startup. We might want to encourage the client to leave the event handler of the current animation frame before retrying to avoid long periods of synchronous processing.
OTOH WebGL implementations usually can reject a faulty shader quickly because they parse it before passing it on to the driver, but I'm not sure they *always* can, IOW check all limits. Resource aquisition can overlap and get queued, so maybe altering the shader right away is not such a bad idea. /ping @benaadams may have some insights to share...

**Comment by MiiBond** [comment]
It would be nice to be able to compile shaders and link programs outside of the render loop. Part of the reason that things are so awkward now is that you have to have a material on an object in the scene before compilation happens. That means waiting for one frame at least before knowing whether the program is successfully created. It would be nice if we could control this so that we can check for successful compilation before trying to render. Also, for example, we could precompile shaders during loading scenes or something rather than being forced to lockup the scene whenever an object with an uncompiled shader is rendered.

**Comment by mrdoob** [comment]
I wonder if we could do something along these lines:

```javascript
var vs = new THREE.WebGLShader( string );
var fs = new THREE.WebGLShader( string );
var program = new THREE.WebGLProgram( vs, fs );
material.program = renderer.programs.compile( program );
```

**Comment by tschw** [comment]
> It would be nice to be able to compile shaders and link programs outside of the render loop [...]

Indeed!

> I wonder if we could do something along these lines [...]

We should do *something* along these lines :-). I do think there should be clear distinction between "specifications" and "instances" created from these specifications, however, and we should use distinct classes as we're talking apples and pairs with a 1:n relationship in between. We can of course redefine the meaning of existing names, but I'll temporarily rename the "WebGLShader" from your suggestion, for the sake of clarity of this discussion.

It would also be great if we'd get control over the GLSL "instantiation"; so we can allow an app to ship the output from glsl-optimizer and find the correct, specialized (IOW already-prefixed and preprocessed) GLSL code for the parameters provided by the renderer. In fact, I have a local branch of the editor that can optimize and subsequently minify the GLSL on "Publish" including the UI for build options, but put it on hold until the data model is ripe for it.

GLSL preprocessor definitions, are either numbers or booleans. Given an ordered set of defines that matter to a shader, their values (as currently found in the temporary `parameters` object in the renderer) can be compressed into a short, persistable string key to identify the *instance* of a shader (keys for both shaders together with the UUIDs identifying the input source code can then replace that `code` thingy in the renderer for identifying programs - we really wouldn't want to use that enchilada as a key in JSON data - it's longer than what we'd want to look up).  All this stuff should actually implemented separately, but I am considering the use case in the design.

Back to business:

```javascript
// ShaderSpecification could become an entity of the data model, 
// IOW have a UUID and get flattened-out in JSON.
//
// A sorted array of the preprocessor defines that are affecting
// the shader could also be held by objects of this class.
//
// We can't implement the .needsUpdate convention here:
//
// One specification may produce multiple instances; we couldn't
// know when to flip .needsUpdate back to 'false'.
// However, referencing materials should update automatically if
// one or both ShaderSpecifications change state (without having
// to set material.needsUpdate).
var vs = new THREE.ShaderSpecification( inputSourceCode );
var fs = new THREE.ShaderSpecification( inputSourceCode );

// ShaderSpecifications could simply be added on the material
// (string assignment could be deprecated via property setter)
material.vertexShader = vs;
material.fragmentShader = fs;
// When changing these properties to refer to different objects,
// material.needsUpdate is assumed to be set.
// There is an existing code path that takes care of this case.

// We can render as usual and shaders will be compiled.

// We can export our scene at any point.

// Let's take a shot at the new stuff:

var program = renderer.getProgram( material );

// The result will contain the info for GLSL composition, or to
// alternatively avoid it, taking its result from a map instead:

if ( ReleaseMode === true ) {

    var shaders = program.shaders; 
    // instances, *not* specs, we might as well use an array

    for ( var k in shaders ) {

        var shader = shaders[ k ];

        var optimized = optimizedGlsl[ shader.key ];

        if ( optimized !== undefined ) {

            shader.overrideGlsl( optimized );
            // // Internally (see 'compile' algorithm below):
            // previouslyComposedInput := spec.inputSourceCode
            // finalGlsl := optimized

        }

    }

}

var success  = program.compile();
// we may actually get a cached result, here:
//
// The program instance can be reused across materials and hold
// an up-to-date, already-compiled WebGL program.
//
// The algorithm for tracking updates inside 'compile' could be:
//
// for both shaders:
//
//     if spec.inputSourceCode != previouslyComposedInput:
//
//         finalGlsl := composeGlsl( spec, params )
//         previouslyComposedInput := spec.inputSourceCode
//
//     if finalGlsl != previouslyCompiledGlsl:
//
//         webglShaderHandle := gl.compileShader( finalGlsl )
//         previouslyCompiledGlsl := finalGlsl
//
// if a shader was compiled:
//
//     webglProgramHandle := gl.linkProgram( shaders )
//
// return whether last link was successful (whenever it took
// place)
```
I think this infrastructure could be implemented with very little changes to the control flow of the renderer. It would simply create `WebGLProgram` where it does now. The surrounding code would get exposed as the `getProgram` method (or however we may want to name it). Then, whenever the renderer switches the program it would call `program.compile()` in order to look for changes - and get a quick, cached response in case nothing has.

With this stuff in place, firing a callback when compilation fails seems quite reasonable to me. It should happen before diagnostics are issued. In fact we could give it a default on `WebGLRenderer.prototype` that takes care of the muttering, so the client can decide whether to suppress diagnostics, present it hirself, or use the default by calling the overridden method on the prototype. 

By the way: GLSL editing from within the editor can be very useful for verification and debugging, and we shouldn't forget to add a new "Shader" panel to its sidebar :-).

**Comment by benaadams** [comment]
@tschw I did split out the shader compile and reduce the recals of some of the things  #6411 might have some useful code

**Comment by tschw** [comment]
@benaadams Not so sure - `dev` has diverged quite a bit since that code was written. #6411 should be pulled up or reimplemented eventually, though.

For this one, I'm actually not so much concerned about the renderer side, guessing it will implement itself rather quickly. I'd really try to keep the changes down to a minimum - just move stuff around and wrap it up, keeping the API separate from rewrites and further refactoring. Having shader specifications as first class citizens in the data model will be the biggest part, I guess.

Any takers? Or will it have to wait until I can find more time for Three.js development (wish it was now) and get the other task finished? Either way, an "OK, sounds good, let's go" from @mrdoob would be encouraging too, I guess.

**Comment by mrdoob** [comment]
OK, sounds good, let's go! 😉

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6963

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6963

**Pull request closed without merging**
