### PR TITLE
GLTFLoader: Ignore redundant 'KHR_texture_transform' extensions and 'textures' entries.

### LINKED ISSUE #21559: GLTFimporter prevent duplicates of same image when used in multiple materials
NOTE :Old title was  'GLTFexporter prevent exporting duplicates of same image when used in multiple materials'

**Is your feature request related to a problem? Please describe.**

same images used in multiple materials exports as duplicates leading to increase in file size

**Describe the solution you'd like**

If same textureLoader object is used then have the exporter save the image once & have the materials refer to this single image 

**Additional context**

Also applicable for other exporters like USDZ

### LINKED ISSUE #21819: poor performance with some gltf files
so this file here has some 120K tris and 3 x 2K textures, however when I drop it into 3js editor fps goes out the window. I get much better performance in https://sandbox.babylonjs.com/ with the same model.

@donmccurdy  could it be related to the fact that, for some reason, 3js loader duplicates the textures for each map in every material across the model? here, we have 4 identical materials with 5 maps, 3 of them being same texture, but 3js creates 20 textures for this:
Screen Shot 2021-05-12 at 16 06 17
Screen Shot 2021-05-12 at 16 06 36

glb file in zip below:
[three_js_problem_model.glb.zip](https://github.com/mrdoob/three.js/files/6466747/three_js_problem_model.glb.zip)

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #21819. Fixes #21559.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Also mentioning these issues on https://github.com/KhronosGroup/glTF-Validator/issues/163, hoping exporters can try to fix them as well.

**Comment by mrdoob** [comment]
Uh oh...

```
ERROR! Diff wrong in 0.117 of pixels in file: webgl_loader_gltf_compressed
```

**Comment by donmccurdy** [comment]
Ah thanks! Nice catch by the test, it is a regression:

Screen Shot 2021-05-12 at 10 48 21 AM

Will look into that more...

**Comment by donmccurdy** [comment]
Fixed 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
