### PR TITLE
Const Enum: CullFace

### PR DESCRIPTION
**Pull request by Itee**
The first PR about #12579.

This is a working example, that show how it should be implemented.
As you can see we need to use a try catch to be sure that in any case the end user will 'see' warning about the deprecation.

@haroldiedema, 

@mrdoob Want you one PR per constants, or a single PR for all ?

### CODE REVIEW

**Review by haroldiedema — APPROVED** [review]
As for the one big PR or separate smaller ones. My personal preference would go to the smaller ones since they're easier to review. Less chance to overlook things.

PR looks good to me 👍 . Let's see what the rest thinks.

**Comment by mrdoob** [comment]
While we're at it, we could make them uppercase (`THREE.CULLFACE.NONE`), as the constants they are. But, I don't like that this would considerably increase the build size and parsing time... 😟

**Comment by Itee** [comment]
No prob to make them uppercase. 

And about:

> this would considerably increase the build size and parsing time...

I'm not sure that you're talking about the uppercase, but this should have no impact. And at least, duplicate constants in legacy file with their respective getter will increase build and parsing time but just for release until we could throw this legacy stuff away. Maybe under r91 ?

**Comment by haroldiedema** [comment]
> I'm not sure that you're talking about the uppercase, but this should have no impact.
There's a common convention where constants (defines) are declared in upper case.

> But, I don't like that this would considerably increase the build size and parsing time...
Maybe a good idea to do some performance testing. I think (at least) v8 is smart enough to do some form of caching when variable lookups are happening since all they are, are pointers in memory.

**Comment by Itee** [comment]
>  > I'm not sure that you're talking about the uppercase, but this should have no impact.

> There's a common convention where constants (defines) are declared in upper case.

Yes i know, i just tell that make constant uppercase should not impact performances.

About testing i will take a look. But in the worth case performances will be impacted only during the transition. I don't know how many releases are required before throw this type of deprecation, but it should not be so big.

**Comment by donmccurdy** [comment]
Not a strong preference but I think it’s more common to use uppercase only for the values, like: `THREE.CullFace.NONE`

**Comment by mrdoob** [comment]
> I'm not sure that you're talking about the uppercase, but this should have no impact. 

Yeah sorry, my comment ended up confusing. I mean changing all the constants at this point would impact file size and parse time. Unfortunately we can't throw the legacy file. The only way I can see to remove that file would be by doing a three.js 2.0 type of thing...

I understand this is frustrating.

**Comment by haroldiedema** [comment]
>  by doing a three.js 2.0 type of thing...

If we're ever going down this road, perhaps introducing [semantic versioning](https://semver.org/) would be a _very_ good idea to indicate new features or BC breaks in the (public) API, like this PR without the legacy part.

**Comment by mrdoob** [comment]
Another approach would be by, somehow, converting all constants to functions.

In this case it would become this:

```js
renderer.setFaceCullingNone();
renderer.setFaceCullingBack();
renderer.setFaceCullingFront();
renderer.setFaceCullingFrontBack();
```

I don't know what's better/worse...

**Comment by haroldiedema** [comment]
> converting all constants to functions.
That would be a nightmare to configure dynamically (say based on JSON or whatever) 😝

**Comment by mrdoob** [comment]
In fact, in this case it could be just:

```js
renderer.setFaceCullingFront( boolean );
renderer.setFaceCullingBack( boolean );
```

**Comment by mrdoob** [comment]
> That would be a nightmare to configure dynamically (say based on JSON or whatever) 😝 

True...

**Comment by haroldiedema** [comment]
That particular scenario is doable, but how would you go about material definitions then?

```javascript
let material = new THREE.MeshPhongMaterial({
    // some config...
    side: THREE.xyz // ... ?
});
```

You would then have to execute extra functions afterwards while you would ideally want this information ready when the constructor is called of said `Material`.

**Comment by mrdoob** [comment]
I've never been a big fan of that API style (passing an object to the constructor). It's error prone and a hard to maintain.

I would have gone with something like this:

```js
let material = new THREE.MeshPhongMaterial().setBackSide();
```

**Comment by haroldiedema** [comment]
I agree. But I'd rather solve this in an API using "data objects", to maintain backward compatibility and allow custom frameworks to configure THREE 'classes' in an easy manner.

Something like this:
```javascript
class PhongMaterialDefinition extends Object
{
    setColor (color)
    {
        this.color = color; // Could do additional type-checking here.
        return this;
    }

    setFrontSide ()
    {
        this.side = THREE.FrontSide;
        return this;
    }

    setBackSide ()
    {
        this.side = THREE.BackSide;
        return this;
    }
}

let my_definition = new PhongMaterialDefinition()
    .setColor(0xff00ff)
    .setFrontSide();

let my_material = new THREE.MeshPhongMaterial(my_definition);
```

**Comment by Itee** [comment]
I miss somethings about the deprecation here. 

@mrdoob you're saying that all stuff in legacy will never be removed ? What is the goal to mark some function deprecated in a certain build if it is not to remove them in the next ???

People that already use constant stuff use a certain build version like r88 for example. If they want to upgrade their code base they will upgrade the three version to r89 and so got the deprecation warnings. They will upgrade what is marked as deprecated. 
And finally the deprecated stuff could be remove under r90, considering that their code base is already upgraded. So no breaking can happen ?!

@donmccurdy 

> THREE.CullFace.NONE

Yes i think it is more readable, i will change to this.

About:

> renderer.setFrontFaceCulling( boolean );
renderer.setBackFaceCulling( boolean );

Using a bool is not necessary, but using function instead of simple integral constants, will increase the code base, the code complexity (IMO), and won't be easily shareable between classes. Imagine a class with 3-4 constants of 3 or 4 member each... So 9 to 16 methods to add, documents etc... ??? Uuuhhh....

However, chainable call could be a great thing in three, i remember a try for Three.App with @looeee using such things.

**Comment by mrdoob** [comment]
> What is the goal to mark some function deprecated in a certain build if it is not to remove them in the next ???

Allowing people to upgrade their projects to the latest version and having handy warning messages in the console while keeping their project still fully functional.

**Comment by Itee** [comment]
I'm not sure that a user of three r59 (for example) and upgrade to r89 won't see his application break... 
In which case:

> Allowing people to upgrade their projects to the latest version and having handy warning messages in the console while keeping their project still fully functional.

will be false. 

@mrdoob Any way, should i continue in this direction ? A three v1.0.0 should be feasible/in store ?

**Comment by haroldiedema** [comment]
> I'm not sure that a user of three r59 (for example) and upgrade to r89 won't see his application break...

Framework upgrades should be done incrementally anyways. It's good practice 😄

**Comment by mrdoob** [comment]
I agree it's good practice, but I don't think that's what people do 😕

**Comment by Itee** [comment]
Yes, they should upgrades incrementally, and in this way we could 'safely' remove legacy stuff after some releases.

Keep backward compatibility for older browser ( that are still supported by their producer, but don't make backward compatibility for ie7 for example ) is good/required.

But keep legacy stuff along the complete live of a library is, IMO, a non sens. 

The problem here about the update is that people are not award about when could happen breaking change when they upgrade. No Major version upgrade. That normally signal to end user that some things will break.

The good idea could be to keep legacy stuff between 2 major version. 

For example:

r89 -> 1.0.0: current legacy stuff still here.
1.0.0 -> 1.1.12: current legacy stuff still here + new legacy stuff about 1.0.0+
1.1.23 -> 2.0.0: legacy stuff from r89 removed, new legacy about 1.0.0+ still here
etc...

This allow people to don't see application break between major release, if they upgrade incrementally major version. That is, in fact, like does almost all packages, so people should be aware about this type of practices during their development life (even if they are new comer).

**Pull request closed without merging**
