### PR TITLE
Remove logs from GCodeLoader

### PR DESCRIPTION
**Pull request by tentone**
Hi

 - Removed logs from gcodeloader.
 - Kept the arc command check with comment in case somebody wants to implement it later.

Cheers

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks for this.

Maybe just comment the logs out, and they can be un-commented for debugging. What do you think?

**Comment by mrdoob** [comment]
> Maybe just comment the logs out, and they can be un-commented for debugging. What do you think?

That sounds better to me yeah.

**Comment by mrdoob** [comment]
615c99f779bd01b6caecfc758f61f987bcd48759

**Comment by WestLangley** [comment]
Thanks!

**Pull request closed without merging**
