### PR TITLE
Design update

### PR DESCRIPTION
**Pull request by mrdoob**
Implementing @yuinchien redesign.

Before:

Screen Shot 2019-04-28 at 12 52 10 AM

After:

Screen Shot 2019-04-28 at 12 56 32 AM

Before:

Screen Shot 2019-04-28 at 12 53 33 AM

After:

Screen Shot 2019-04-28 at 12 53 46 AM

https://raw.githack.com/mrdoob/three.js/dev/docs/
https://raw.githack.com/mrdoob/three.js/dev/examples/

### CODE REVIEW

**Comment by fernandojsg** [comment]
I like the overall change, but I feel the color of the links on the left side are not consistent with the link colors on the right side

**Comment by mrdoob** [comment]
Yeah. Work in progress 😊

**Comment by fernandojsg** [comment]
👍

**Comment by linbingquan** [comment]
I think use default font `Microsoft YaHei` is better in Chinese.

screenshot in `font-family: "Microsoft YaHei"`(cancle body `font-family` css in `main.css`)
image

screenshot in `font-family: 'RobotoMono', monospace;`
image

**Comment by mrdoob** [comment]
@yuinchien does that look good to you?

I guess I can implement it this way: https://stackoverflow.com/a/49490341

**Comment by yuinchien** [comment]
@mrdoob didn't know how Chinese font look like in Window... Yes, Microsoft YaHei looks fine!

**Comment by yuinchien** [comment]
@mrdoob the md icons in the design are scaled down to 20x20 instead of the standard 24x24 because the standard vertical height for UI elements are slightly reduced, to better accommodate the large amount of content on the site. 

Screen Shot 2019-04-28 at 9 47 28 AM
See the search icon in the design (left) is smaller.

**Comment by mrdoob** [comment]
@yuinchien Yes, there are a lot of things to improve. We can go through them tomorrow 😊

**Comment by mrdoob** [comment]
I managed to unify all the css though. I'm no longer ashamed of it! Haha

**Pull request merged**
