### PR TITLE
Examples: move ifc library into libs folder

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: -

**Description**

The [lint-fix command](https://github.com/mrdoob/three.js/blob/f994a92b3436e23156dc23f84d74236c0efd317f/package.json#L54) ignores the `libs/` folder when linting. The `web-ifc-api.js` library was being linted because it's not in the libs folder, this fixes it.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Hmm, but then... until import maps are better supported, it makes it difficult to move these files around...

Now you can just copy the `IFCLoader.js` together with the `ifc` folder and it just works.

**Comment by marcofugaro** [comment]
Well it's already like that for other loaders that use libs such as fflate.

I think it's better than having this logging polluting the lint commands 😅

image

**Comment by mrdoob** [comment]
Can we solve this one by doing this for now? 😇

```
    "lint-examples": "eslint examples/js examples/jsm --ext js --ignore-pattern libs --ignore-pattern ifc/",
```

**Comment by marcofugaro** [comment]
Sure!

**Pull request closed without merging**
