### PR TITLE
Remove d.ts files

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #15597

**Description**

This PR removes all .d.ts files from the repo.

TypeScript definitions were originally maintained in https://github.com/DefinitelyTyped/DefinitelyTyped but 2 years ago we decided to include them in the repo hoping that it would ensue they would be in sync.

The side effect of that decision was a considerable increase on maintenance burden and made things harder for new contributors too. For the sake of continuity of the project I think it's best to move them back to DefinitelyTyped (or any other repo interested in maintaining them).

During the 2 years that these files were in the repo I think we did a good job at bringing them in sync but it's time to delegate the maintenance.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by squidfunk** [comment]
Hmm, I guess this will break a lot of projects. I agree with removing the generics, but shouldn't we at least wait, until there's an alternative before removing _all_ types? This renders Three.js pretty much unusable in my TS-only codebase.

**Comment by mrdoob** [comment]
This would only remove them from `dev`. We have until February 24 publishing `0.126.0` on npm.

**Comment by DavidPeicho** [comment]
It's really too bad because it brings a lot of value for TS users. I understand it's a lot of effort so maybe we could choose someone that can help maintain the typings?

**Comment by squidfunk** [comment]
Okay, cool. I understand that you don't want to maintain them, but I'm strongly in favor of a solid migration plan. DefinitelyTyped sounds like a good alternative if you don't want to have them in the repositories. If it's as easy as dropping in `@types/three.js`, that would be ideal. Note that there might be some problems with the `examples` folder though.

**Comment by mrdoob** [comment]
@squidfunk Would you like to take on this task?

**Comment by squidfunk** [comment]
@mrdoob Thanks for asking. I'm afraid, I can't do that as I already have too many open source projects to maintain. I'm sorry.

**Comment by mrdoob** [comment]
@squidfunk By "task" I didn't mean maintaining them, I meant dropping them to `@types/three`.

**Comment by xawill** [comment]
Sorry to all TS users that my PR triggered this...

**Comment by joshuaellis** [comment]
Wouldn't this be a good opportunity to do an RFC from the community?

**Comment by mrdoob** [comment]
Already did: https://twitter.com/threejs_org/status/1355153151310098433

**Comment by DavidPeicho** [comment]
What do you think about keeping them in this repo and someone is assigned as the main person to handle types? Not sure how that could go.

**Comment by joshuaellis** [comment]
@mrdoob I don't mind putting them on DefinitelyTyped if that's the decision we want to do.

**Comment by mrdoob** [comment]
@DavidPeicho TS related conversations have been too noisy and distracting. I would prefer if all that activity happened somewhere else.

**Comment by mrdoob** [comment]
@joshuaellis That'd be great. Let me know when it's done 🙏

**Comment by CodyJasonBennett** [comment]
Is there any way we can make this work with JSDoc or does that have the same pitfalls?

**Comment by Methuselah96** [comment]
I would be willing to help maintain the types on DefinitelyTyped.

**Comment by DavidPeicho** [comment]
Okay I guess then we can move them, and start from there. The library is published every month we basically need to have the types ready at each release :)

**Comment by Methuselah96** [comment]
(P.S. The types were significantly better after they moved to this repo since it was very easy for the types to get out-of-date on DefinitelyTyped. It was also a huge advantage to have the code and types in-sync to help with breaking changes. However I agree with @mrdoob's reasoning and I don't think it's a fair expectation for any project to have to maintain types if it's causing unnecessary noise. Thank you for trying it out and the period in which the types were always in-sync.)

**Comment by Methuselah96** [comment]
@DavidPeicho Yeah, it won't be easy and we should expect some lag between the package publishing and updated types publishing.

**Comment by Methuselah96** [comment]
@mrdoob Note that I am also willing to take ownership of the type definitions on this repo (in response to [this comment](https://github.com/mrdoob/three.js/pull/19702#issuecomment-767646194)) which would mean that we can continue to have high-quality types that are always up-to-date. You could just mention on any TypeScript related issues and PRs and I could handle it/give my recommendation.

**Comment by joshuaellis** [comment]
> @mrdoob Note that I am also willing to take ownership of the type definitions on this repo (in response to [this comment](https://github.com/mrdoob/three.js/pull/19702#issuecomment-767646194) and [this comment](https://github.com/mrdoob/three.js/issues/21172#issuecomment-769770366)) which would mean that we can continue to have high-quality types that are always up-to-date with each release. You could just mention me on any TypeScript related issues and PRs and I could handle it/give my recommendation.
> 
> I think this would be the better situation for the developer's overall-all experience and it would be make significantly less work for people maintaining the types (so they don't have to cross-reference all the changes and try to get releases out ASAP), but I do understand that it does still impact you. However I think that I could take a lot of the work that you had to do in #19702 and #21172 and handle it as much as I can before letting you make an executive decision (if necessary/desired).

I second this, I am also happy to help on the TS front in the same way as @Methuselah96.

**Comment by CodyJasonBennett** [comment]
I'm concerned about the stability of types and related documentation for modules in the examples folder, as this is often their only form of documentation.

If the issue is with the burden of maintaining these modules in addition to the three core, perhaps this should be a larger conversation?

I worry that this is only a symptom of a larger problem.

**Comment by mrdoob** [comment]
@Methuselah96 Many thanks for stepping up! 🙏

I think I'd prefer if the types are on DefinitelyTyped for now though. By the way, one benefit of having it outside is that you can update the types any time instead of just once a month.

As per the next steps... We just need to copy the current types to the DefinitelyTyped repo and change [this line](https://github.com/mrdoob/three.js/blob/8a2665a9ddce556863619509f9486abebcb1fd70/package.json#L7) to `@types/three`, right?

**Comment by Methuselah96** [comment]
@mrdoob Yeah, we just need to copy the types and users will have to install `@types/three` separately from `three`. The line you referenced would be removed altogether (which is already done as part of this PR).

Sounds like @joshuaellis volunteered to do the work to put the types on DefinitelyTyped, so I'll wait until that's done unless he would prefer I do it.

**Comment by joshuaellis** [comment]
@Methuselah96, @mrdoob I am indeed already on it. @Methuselah96 i'll add you as an owner to the code while i'm at it.

**Comment by gkjohnson** [comment]
I'm not an expert in TS but is it possible to maintain type definitions in a different repo owned by the three.js community? So users would have a more dedicated location to direct issues, questions, discussions, and PRs and the types will be easier to browse? It could go in the the [threejs Github org](https://github.com/threejs/) where people within the community could maintain it but would direct noise away from the core project.

**Comment by donmccurdy** [comment]
> I'm not an expert in TS but is it possible to maintain type definitions in a different repo owned by the three.js community?

p5.js did this (https://github.com/p5-types/p5.ts), it's definitely an option. I don't have a preference and would be happy to defer to any TypeScript users here, especially those able to help maintain the type definitions. **Pros:** Might be easier to include tooling that tests the type definitions. **Cons:** Can't use the standard `@types/*` namespace if it's not in DefinitelyTyped, I expect.

**Comment by joshuaellis** [comment]
> I'm not an expert in TS but is it possible to maintain type definitions in a different repo owned by the three.js community?

IMO DefinitelyTyped is the defacto for this kind of thing, I think keeping it with other TS declarations is stronger in the long run. There's a bunch of repo bot help in DT too... I'm not sure the benefit of having it in it's own repo?

**Comment by donmccurdy** [comment]
> I'm not sure the benefit of having it in it's own repo?

There are some scripts in this repo now that check the `d.ts` files against official examples. I'm not sure how helpful those tests are, but having them around is the main benefit I can think of. Maintenance of the types has been better since they moved into this repo, but I don't know whether that was caused by (a) consuming maintainers' time, (b) higher visibility to the three.js community, or (c) something else.

**Comment by gkjohnson** [comment]
> p5.js did this (https://github.com/p5-types/p5.ts), it's definitely an option.

Interesting. It looks like they basically generate the types in that repo and still ultimately upload them to DefinitelyTyped.

> I'm not sure the benefit of having it in it's own repo?

As a user to doesn't use typescript but benefits from the typings in the form of intellisense I'd find it easier / less intimidating to more casually contribute or raise fixes and updates to a project where I know my contributions will be vetted by people who know more than I do in the context of three.js. As evidenced by the many issues in this repo involving generics or different ways of representing typed information for three.js it's not always straight forward what the "right" answer should be.

It seems the types would ultimately have to wind up in DefinitelyTyped which could be automated with some kind of CI action but in my opinion the benefit would lowering the barrier of entry and intimidation of contributing and providing testing or linting infrastructure like @donmccurdy suggested.

It just occurred to me that moving everything to DefinitelyTyped entirely would probably lower the visibility of the types and therefore the smaller contributions to them, as well.

**Comment by fazouane-marouane** [comment]
Would a (possibly gradual) migration of three.js to typescript be a possibility ? I can spend some time on this if you're open to the idea.

**Comment by mrdoob** [comment]
@fazouane-marouane No, sorry. Better to use @bhouston's https://threeify.org/ or https://www.babylonjs.com/.

**Comment by mrdoob** [comment]
Okay, merging this for now.

**Comment by joshuaellis** [comment]
I've started the move over, but it's not just a drag and drop situtation but it'll be done before r126. You can track the progress, and contribute here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50930

**Comment by Methuselah96** [comment]
> 
> 
> > I'm not sure the benefit of having it in it's own repo?
> 
> There are some scripts in this repo now that check the `d.ts` files against official examples. I'm not sure how helpful those tests are, but having them around is the only benefit I can think of. I suppose the tests could be moved somewhere else and just run against DefinitelyTyped, too. Maintenance of the types has been better since they moved into this repo, but I don't know whether that was caused by (a) consuming maintainers' time, (b) higher visibility to the three.js community, or (c) something else.

@donmccurdy We're planning on bringing the example deceleration files over as well. Is that what you are referring to, or are there other examples?

**Comment by donmccurdy** [comment]
Those declaration files are important, and I agree they should be kept. But what I meant was that repository contained a macro...

https://github.com/mrdoob/three.js/blob/350f0a021943d6fa1d039a7c14c303653daa463f/package.json#L68

...which I believe did some general regression tests of the type definitions. It might be worth keeping something like that in DefinitelyTyped or elsewhere.

**Comment by Methuselah96** [comment]
Got it. From what I can tell that command is just linting and then compiling the declaration files to make sure there are no issues. DefinitelyTyped already does that as part of its process so I don't think we'll see any regression in that regard.

**Comment by Mugen87** [comment]
@mrdoob Since the d.ts files are now available at `Definitely Typed` and the respective `npm` package is available how about announcing this PR in the forum? So we have something to refer when users are asking about this change.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/three
https://www.npmjs.com/package/@types/three

When I understand it correctly, TS user now have to install the above `npm` package to get their typings back, right?

**Comment by CodyJasonBennett** [comment]
Yes, and it'll prompt them to look for types from `@types/three`.

**Comment by mrdoob** [comment]
@Mugen87 Sounds good to me 👍

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/with-r126-typescript-type-declaration-files-are-located-at-definitelytyped/23157

**Comment by marquizzo** [comment]
My only question is are types versioned in DefinitelyTyped? For example, if the latest Three.js version is `r140` but I'm installing an old project that runs on revision `r126`, will I be able to install `@types/three@0.126`? Or does it always use the latest definition files? I'm [looking at this discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7719) and it sounds like the `.d.ts` files aren't versioned.

**Comment by Methuselah96** [comment]
Types [are indeed versioned](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) on DefinitelyTyped and you will be able to install `@types/three@0.126` to get the correct types for `r126`.

**Comment by Methuselah96** [comment]
@gkjohnson @donmccurdy We decided to go ahead and host the types in https://github.com/three-types/three-ts-types and then sync them to DefinitelyTyped, so I believe that should relieve most people's fears with using DefinitelyTyped.

**Comment by beginor** [comment]
I think its too bad to remove the `*.d.ts` from this repo, those files should be generated from source file, not be maintained manually.

Typescript does not only work with ts files, but alwo can works with js files, please refer to this post : [TypeScript without TypeScript -- JSDoc superpowers](https://fettblog.eu/typescript-jsdoc-superpowers/)

If we add JSDoc to the source cold, we can generate excellent d.ts files with `tsc`.

**Comment by beginor** [comment]
There is a great [video](https://www.youtube.com/watch?v=YHvqbeh_n9U) on that. But there’s a lot, lot more to it than a couple of basic types in comments. Turns out working with JSDoc type gets you very far.

https://www.youtube.com/watch?v=YHvqbeh_n9U

**Pull request merged**
