### PR TITLE
add EXRLoader example

### PR DESCRIPTION
**Pull request by richardmonette**
Adds a basic EXRLoader. Can read the header and uncompressed data.

I've added an example based of https://github.com/mrdoob/three.js/blob/dev/examples/webgl_materials_texture_hdr.html

I'd like to follow this up with better support of EXR feature, in particular PIZ compression.

related: https://github.com/mrdoob/three.js/issues/10652

cc @mrdoob

### CODE REVIEW

**Comment by WestLangley** [comment]
https://rawgit.com/richardmonette/three.js/dev/examples/webgl_materials_texture_exr.html

**Comment by WestLangley** [comment]
On MacOS, Chrome is claiming the texture is NPOT ( 1023 x 511 to be exact ).

Also, the tone mapping is rendering way too dark. May be related.

Errors are thrown with Safari and the image is not rendered.

**Comment by richardmonette** [comment]
@WestLangley thank you for your feedback, I believe my latest commit addresses the NPOT issues.

**Comment by WestLangley** [comment]
Yes, the issues I mentioned above appear to be resolved. Thanks.

**Comment by Mugen87** [comment]
@richardmonette Can you please add the new example to [examples/files.js](https://github.com/mrdoob/three.js/blob/dev/examples/files.js)? Otherwise it won't appear in the navigation panel.

**Comment by mrdoob** [comment]
> @richardmonette Can you please add the new example to [examples/files.js](https://github.com/mrdoob/three.js/blob/dev/examples/files.js)? 

I'll do that.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> @mrdoob @Mugen87 FYI, I deleted the live link I added above; the link will break anyway when the OP deletes the topic branch. I think deleting the link is the best practice.

I don't have strong feelings about this yet. If there were people complaining about broken links...

**Comment by WestLangley** [comment]
I think the addition of a live link, which used to be available via `threejsworker`, is a nice convenience for the reader. That is why I added it. It is of no value, however, once it is broken.

**Comment by mrdoob** [comment]
Maybe it's a wording issue? "Ephemeral test link" 😁

**Comment by WestLangley** [comment]
>"Ephemeral test link"

:-)

Yes. I have been adding an "ephemeral test link" in a separate comment so it can be removed when it becomes obsolete. @Mugen87 has been helpful in this regard, too.

**Comment by jxarco** [comment]
@richardmonette how about following the EXRLoader with the parsing of ZIP compression exr files? 

And Is the parsing of PIZ compression exr files working?

Many thanks!

**Comment by richardmonette** [comment]
Parsing compressed EXR files is _significantly_ more complex than uncompressed.

I have, however, been working on upgrading the implementation to parse PIZ compressed files, as these seem to be the most common, and hope to have something for review in the near future.

**Comment by richardmonette** [comment]
@jxarco I've put together an initial implementation of the PIZ wavelet decompression https://github.com/mrdoob/three.js/pull/13346

**Pull request merged**
