### PR TITLE
MapControls

### PR DESCRIPTION
**Pull request by moroine**
This PR replace #14065 

Live: [https://cdn.rawgit.com/moroine/three.js/MapControls/examples/misc_controls_map.html](https://cdn.rawgit.com/moroine/three.js/MapControls/examples/misc_controls_map.html)

This MapControls is identical to OrbitControls excepting: 

- Change default `mouseButtons` (orbit is now right click and pan is left).
- Change touch behavior:
    - 1 finger: pan
    - 2 fingers:
        - spread or squish: zoom
        - rotate: orbit left
        - drag vertically: orbit up

The limitations of the implementation are:

- Starting orbit up will disable orbit left & zoom if order to prevent flickering
- The way to detect vertical drag might not be optimal and there is probably some constant fine tunning (I don't like that kind of stuff stuck_out_tongue ).
- Almost all code is copy / paste from OrbitControls this is not optimal for maintenance.

As specified by @WestLangley in [comment](https://github.com/mrdoob/three.js/pull/14065#issuecomment-393729551) it would be interesting to extends OrbitControls.

In my opinion it's not possible given the current structure of examples. IMO the three options to refactor this properly are :

- Base Controls class shipping common code and both Orbit & Map extending Base
    - Will require to expose a lot of methods which should remain internal
    - The user will need to include both OrbitControls/Mapcontrols & BaseControls file...
- MapControls extending OrbitControls
    - Will require to expose a lot of methods which should remain internal
    - The user will need to include both OrbitControls & MapControls file...
- Creating a Helper with common code and use it in Orbit & Map
    - The user will need to include both Helper and MapControls/OrbitControls

IMO creating a Helper would be nice, but only if example move one day to import syntax but that's another debate :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by moroine** [comment]
To help reviewing [here](http://www.mergely.com/eXFqRIZX/) is the diff between [OrbitControls](https://github.com/moroine/three.js/blob/MapControls/examples/js/controls/OrbitControls.js) and [MapControls](https://github.com/moroine/three.js/blob/MapControls/examples/js/controls/MapControls.js)

**Comment by mrdoob** [comment]
Looking good!
How do you orbit up on desktop?

**Comment by WestLangley** [comment]
>How do you orbit up on desktop?

right-mouse. This is another place where I think also supporting ctrl-mouse makes sense.

What happens with a track-pad?

**Comment by moroine** [comment]
> I think also supporting ctrl-mouse makes sense.

Me too, but I think I'll add it in another PR later on maybe in the same time than #13972 to have the same implementation.

> What happens with a track-pad?
Good point ! Tested on mine under Windows and it doesn't seems to react to touch events. I'm not sure we have trackpad touch events.

**Comment by moroine** [comment]
@WestLangley do you think it's ready to be merged ?

**Comment by WestLangley** [comment]
I think this is good to go. Improvements can be added in later.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
