### PR TITLE
WebGPURenderer: Support WebGLCubeRenderTarget

### PR DESCRIPTION
**Pull request by aardgoose**
Added support to render to WebGLCubeRenderTarget and fixes cubeTexture lookups for WebGL

Also adds mipmap creation for renderTarget textures and minor depthTexture handling.

### CODE REVIEW

**Comment by RenaudRohlinger** [comment]
This one will conflict with #27463

**Comment by aardgoose** [comment]
/@sunag @RenaudRohlinger  Rebased on recent msaa changes - does anyone use/expect msaa on cube textures?

**Comment by RenaudRohlinger** [comment]
> Rebased on recent msaa changes - does anyone use/expect msaa on cube textures?

Considering that MSAA has never been supported on cube textures in Three.js, and we haven't received any complaints or requests for this feature ever, I suggest we refrain from implementing it at this stage. /@aardgoose

**Comment by RenaudRohlinger** [comment]
Requires https://github.com/mrdoob/three.js/pull/27490 to be merged in order to fix an issue and then be able regenerates a correct version of the screenshot of `webgpu_loader_gltf`. /cc @sunag

**Pull request merged**
