### PR TITLE
New example: webgl masking

### PR DESCRIPTION
**Pull request by Mugen87**
This example illustrates a basic masking effect via the stencil buffer (see #8006). 

Although users have to work with `THREE.WebGLState`, it shows the consistent handling of color, depth and stencil buffer over material properties. Besides, users can see that it's not necessary to write much code to achieve a masking effect.

### CODE REVIEW

**Comment by WestLangley** [comment]
I was thinking of something more like this: http://jsfiddle.net/LeerxmnL/, which is a modification of this PR.

We don't want the mask to apply color.

I appreciate all the thought you have put into this, but to me, requiring a mask to be a material is a bit bizarre -- just my opinion -- so I am not really sure I'm liking this new approach. But I do not have an alternative, either, other than to restore things to the way they used to be.

**Comment by Mugen87** [comment]
I applied your suggestions to the example. And of course it's good, that we discuss the solution in this way. I am just the opinion, that the new properties can be very handy in some situations. 

Let's say you want to apply the stencil test to particular objects in your application (not to the entire scene). Without material properties, the only way to achieve this is to manage to separate scenes. The first scene is rendered with stencil test, the second scene without. I think it's bad, that you need to divide your scene graph just for this task.

With the new material properties ('stencilWrite' and 'stencilTest') instead, you can still have one single scene and apply the stencil test to the respective objects. That's the easier approach IMO...

**Comment by WestLangley** [comment]
Sorry, I am not buying it. Whether you are rendering into the stencil buffer (or not) should have nothing to do with the materials in the scene.

In your approach, you are coupling materials and stencilWrite/Test. I do not think that is a good idea at all.

Any scene can be a mask -- regardless of the materials in the scene. Your approach is too restrictive, IMHO -- and as far as I know, non-standard.

**Comment by Mugen87** [comment]
I understand your objections. If you think the previous approach is better, i have no problems to revert the new code. If we close this PR, the only PR to revert is (#8006).

**Comment by WestLangley** [comment]
>i have no problems to revert the new code.

Would you be willing to revert, and then continue to explore alternate approaches? Your contributions are valuable, IMO.

**Comment by Mugen87** [comment]
Thanks :wink:! The PR is reverted. Of course i will think about other possible solutions.

**Pull request closed without merging**
