### PR TITLE
Added src directory to gh-pages.

### PR DESCRIPTION
**Pull request by arodic**
Now that Three.js source is completely modular it is useful to have src/ directory in the release. 🎉

### CODE REVIEW

**Comment by donmccurdy** [comment]
PR https://github.com/mrdoob/three.js/pull/15700 fixed this for the NPM release – did you mean to open this PR against the `gh-pages` branch for another reason?

**Comment by arodic** [comment]
No actually, this is to include `src/` in `gh-pages` and have them served on threejs.org and other gh-pages.

**Comment by mrdoob** [comment]
I'm not sure how I feel about this...

Importing from `src` is kind of "advanced" mode. Things can easily break from version to version.

Importing from `http://threejs.org/build/*` is kind of discouraged but thanks to [Three.Legacy.js](https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js) projects doing so shouldn't break. 

We can't do that for `src`.

**Comment by donmccurdy** [comment]
^Inclined to agree – there are a few CDNs that can be used instead, with the benefit of versioning:

- https://cdn.jsdelivr.net/npm/three@0.101.1/build/three.min.js
- https://cdn.jsdelivr.net/npm/three@0.101.1/examples/js/controls/OrbitControls.js

**Pull request closed without merging**
