### PR TITLE
OrbitControls: Removed update condition code

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

This PR removes the distance-based condition code and simply dispatches a change event every time `update()` is called.

Before:

https://github.com/mrdoob/three.js/assets/97088/904f11a1-0832-45f7-96e3-13e01f64d86c

After:

https://github.com/mrdoob/three.js/assets/97088/11baf4f3-e90f-4bee-bcd9-ceb96cd56be5

### CODE REVIEW

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/0a97813fd293f77b7c2b5a5432a9224acd06926c

**Comment by makc** [comment]
@mrdoob Ive got curious and tracked it down - apparently, this condition was solving some issue around the poles #4769

**Comment by makc** [comment]
then again, it only happened because of EPS check at https://github.com/mrdoob/three.js/commit/4320eec34f11c9227d569357729557082b2cd0fc#diff-1586dbbe957416428df5ba776d207f3abdf8271cc07527c95090d4be8c8ac6f4L287

**Comment by makc** [comment]
...so it actually was #4499 )

**Comment by mrdoob** [comment]
Hmm, I'll try doing this:

```js
lastTargetPosition.manhattanDistanceTo( scope.target ) > 0
```

**Comment by mrdoob** [comment]
Hmm... That works too.

**Comment by mrdoob** [comment]
#26063

**Pull request merged**
