### PR TITLE
Examples: Remove broken iCCP chunks in some PNG files.

### PR DESCRIPTION
**Pull request by chirsz-ever**
The modified PNG files had broken iCCP chunks (CRC32 check failed).

All iCCP chunks in the image files are removed.

They are data encoded in textures, so the normal sRGB iCCP chunks are
also be removed.

### CODE REVIEW

**Comment by WestLangley** [comment]
>They have normal iCCP chunks with sRGB colorspace.

The profiles are not honored in three.js, but FWIW, the normal and roughness texture files are assumed to be encoded with a linear transfer function -- not sRGB.

**Comment by mrdoob** [comment]
What other colorspaces does iCCP support?

**Comment by chirsz-ever** [comment]
> FWIW, the normal and roughness texture files are assumed to be encoded with a linear transfer function -- not sRGB.

Yes, I think the loader read the image as is, and this PR or the sRGB profile would not affect it.

https://github.com/mrdoob/three.js/blob/ec0f9f8acc0b846998c4b9dc1a2afb6e7a66f8a1/examples/webgpu_clearcoat.html#L91

> What other colorspaces does iCCP support?

Any. On the Internet, most of pictures use sRGB colorspace, and sRGB is the default colorspace for images not annotated with colorspace information[^1]. Recently, Display-P3 photos account for a certain proportion. I see Three.js has a wide-gamut example to test Display-P3 colorspace[^2].

[^1]: For JPEG this is specified in the standard. For PNG this is the de facto standard: see [this issue](https://github.com/godotengine/godot/issues/37220#issuecomment-656306521), the first image looks darker than other images, because it uses linear colorspace without any colorspace annotation, but your browser interprets it as sRGB.

[^2]: https://github.com/mrdoob/three.js/blob/ec0f9f8acc0b846998c4b9dc1a2afb6e7a66f8a1/examples/webgl_test_wide_gamut.html

**Comment by Mugen87** [comment]
>> FWIW, the normal and roughness texture files are assumed to be encoded with a linear transfer function -- not sRGB.

> Yes, I think the loader read the image as is, and this PR or the sRGB profile would not affect it.

In this case, can't we just remove the iCCP chunks from the RGB file. I don't understand the value of adding meta data when they are essentially ignored.

**Comment by chirsz-ever** [comment]
@mrdoob What you said is very reasonable. Now all iCCP chunks are removed. You can use pnginfo.py in [this repo](https://github.com/chirsz-ever/imageinfo) to verify it.

For example, for `examples/textures/pbr/Scratched_gold/Scratched_gold_01_1K_Normal.png`:

Before:

```
b'IHDR', offset=8
  Width: 1024
  Height: 1024
  Bit Depth: 8
  Color Type: Truecolor
b'zTXt', offset=33
    Keywords: Raw profile type exif
    Content: (628 bytes)
crc_saved=1202812110, crc_calc=528595506
b'iCCP', offset=277, CRC32 check failed
b'iTXt', offset=8181
b'iCCP', offset=12029
  Profile Name: sRGB
  Compressed Profile: 8440 bytes
  Profile: 8940 bytes
  desc: sRGB
b'IEND', offset=1159550
```

Now:

```
b'IHDR', offset=8
  Width: 1024
  Height: 1024
  Bit Depth: 8
  Color Type: Truecolor
b'zTXt', offset=33
    Keywords: Raw profile type exif
    Content: (628 bytes)
b'iTXt', offset=277
b'IEND', offset=1143188
```

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
