### PR TITLE
Add Maya mouse button operation and can be configed 

### PR DESCRIPTION
**Pull request by rheros**
在新版focus功能的基础上做的
添加了maya的鼠标操作方式，可在setting面板配置

### CODE REVIEW

**Comment by rheros** [comment]
Remove focus function from my last PR
The new  focus function created by #13165 is very cool，I like it， learned！！

**Comment by mrdoob** [comment]
The problem of your approach is that it doesn't scale well. If we start this we will end up like this 😁

screen shot 2018-03-01 at 4 07 17 pm

**Comment by mrdoob** [comment]
It would be better something like:

```
MOUSE SETTINGS
-----------------
LEFT     ˅ ROTATE
MIDDLE   ˅ ZOOM
RIGHT    ˅ PAN
```

**Comment by rheros** [comment]
It's make me very happy to get your reply , you know, it's the first time to Communicate with a real foreigner。非常高兴啊 哈哈哈哈！！
I get it.  You mean we can let the user to define which button can do what. Like Focus can be bind "f" or "s" . Yeah ,  it's more freedom for users .
By the way ,I'm a TA , as I known, in most cases the artist just want to  get a operation they have used, to config every item will boring them .
May I offer a way to selection the  reference operations like what I've done  , moreover , offer a board to change every item as a custom reference.
Like this.

What do you think about this~~

**Comment by mrdoob** [comment]
> By the way ,I'm a TA , as I known, in most cases the artist just want to get a operation they have used, to config every item will boring them .

Yeah, I understand. We can solve that in the future. But for now, I would just implement it like this:

> ```
> MOUSE SETTINGS
> -----------------
> LEFT     ˅ ROTATE
> MIDDLE   ˅ ZOOM
> RIGHT    ˅ PAN
> ```

**Comment by rheros** [comment]
Get it

**Comment by mrdoob** [comment]
Preview link:
https://rawgit.com/rheros/three.js/dev/editor/

**Comment by mrdoob** [comment]
Preview link:
https://rawgit.com/rheros/three.js/dev/editor/

**Comment by mrdoob** [comment]
I think you may need to rebase your branch 🤔

**Comment by Mugen87** [comment]
Closing since the PR has serious merge conflicts and also modifies files like `CONTRIBUTING.md` which should not be necessary.

@rheros Sorry for the late response. The idea of the PR and @mrdoob related suggestion (https://github.com/mrdoob/three.js/pull/13456#issuecomment-370114768) are great. It would be cool if you can give it another go.

**Pull request closed without merging**
