### PR TITLE
Examples: Testing out Tweakpane as replacement for dat.gui

### PR DESCRIPTION
**Pull request by donmccurdy**
A small test, replacing dat.gui with [Tweakpane](https://cocopon.github.io/tweakpane/) in an example. dat.gui is mostly in maintenance mode at this point, where Tweakpane appears to be actively developed. All things considered, it may be better to steer our users to an actively maintained UI library.

Thoughts so far:

- Tweakpane's mobile and touchscreen support seems much more polished.
- Tweakpane does not use horizontal space quite as well, labels had to be shortened a bit in this example. Perhaps this could be [themed](https://cocopon.github.io/tweakpane/theming.html).
- Tweakpane is a larger library (26kb minzipped vs 14kb minzipped)
- I slightly prefer the appearance of Tweakpane, but not a driving concern here
- Both APIs are generally very similar.

| dat.gui | tweakpane |
|---|---|
| dat.gui screenshot | tweakpane screenshot |

https://raw.githack.com/donmccurdy/three.js/feat-tweakpane-example/examples/webgl_instancing_scatter.html

### CODE REVIEW

**Comment by donmccurdy** [comment]
Tweakpane currently does not offer an ES module build. The maintainer has indicated in a GitHub comment that he would consider a PR for it, but since the build tool is Webpack (which doesn't support multiple outputs...) it's not a totally trivial addition.

**Comment by Mugen87** [comment]
The E2E test is failing since it's required to remove the UI from the website. You can easily fix this by hiding the root element of the Tweakpane container.

https://github.com/mrdoob/three.js/blob/dev/test/e2e/clean-page.js

In general, I'm not a fan of having multiple libraries for the same purpose in a repository. If we decide to use Tweakpane, I suggest to completely remove `dat.gui`.

**Comment by Mugen87** [comment]
> All things considered, it may be better to steer our users to an actively maintained UI library.

According to this, we could also consider to replace `tween.js` with `GSAP`.

**Comment by donmccurdy** [comment]
> In general, I'm not a fan of having multiple libraries for the same purpose in a repository.

Agreed, if we do begin to use Tweakpane we should be doing so with the intention of replacing dat.gui. If we'd rather not, or don't feel that Tweakpane is the right replacement, that's certainly OK and I can close this PR.

**Comment by mrdoob** [comment]
>> All things considered, it may be better to steer our users to an actively maintained UI library.
>
> According to this, we could also consider to replace `tween.js` with `GSAP`. But this can be discussed in a separate issue.

GSAP is... [complicated](https://greensock.com/why-license/)...

**Comment by mrdoob** [comment]
> In general, I'm not a fan of having multiple libraries for the same purpose in a repository. If we decide to use Tweakpane, I suggest to completely remove `dat.gui`.

Yeah, the idea of this PR was to see if replacing `dat.gui` with `Tweakpane` could be done.

**Comment by mrdoob** [comment]
Something that I just noticed is that we lose the ability to collapse/hide the panel.

**Comment by donmccurdy** [comment]
Collapsing is available, but we do have to call `addFolder()` for each example: https://cocopon.github.io/tweakpane/ui-components.html#folder. I don't think it has a hotkey to hide the entire GUI like dat.gui does, though.

**Comment by arpu** [comment]
Why not use something like https://github.com/lo-th/uil ? and its 3d compatible ( not sure if this is possible for all examples)

**Comment by donmccurdy** [comment]
Tweakpane seemed to be the most mature option to me, but I'm certainly open to other suggestions. uil.js does not seem to offer much accessibility, and the mobile/touch support is not as good as either dat.gui or Tweakpane. That is likely a result of its use of Canvas instead of HTML to support 3D rendering; it's hard to build a UI with Canvas 2D (or WebGL) that is also accessible.

**Comment by cocopon** [comment]
Thank you for considering Tweakpane.

> Something that I just noticed is that we lose the ability to collapse/hide the panel.

Tweakpane provides the pane title to collapse/hide the whole pane:

```js
const pane = new Tweakpane({
  title: 'Parameters',
});
```

https://cocopon.github.io/tweakpane/quick-tour.html#folders

**Comment by donmccurdy** [comment]
I've been using tweakpane in https://gltf.report and some other projects, and haven't found any notable issues so far. Having a plugin API for [new UI controllers](https://github.com/topics/tweakpane) is a really nice addition.

Any thoughts on whether this is a direction we want to go in?

**Pull request closed without merging**
