### PR TITLE
NodeMaterial: fixes

### PR DESCRIPTION
**Pull request by sunag**
- Add anti-aliasing of @elalish
- Fix `NormalNode` context
- Update default `StandardNodeMaterial` values

Issue:  https://github.com/mrdoob/three.js/issues/18360

### CODE REVIEW

**Comment by sunag** [comment]
@njarraud It fix your issue https://github.com/mrdoob/three.js/issues/18360?

**Comment by sunag** [comment]
Exist a brightness difference of light in `MeshStandardNodeMaterial` to default material that I not fixed https://threejs.org/examples/webgl_materials_nodes.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by njarraud** [comment]
> @njarraud It fix your issue #18360?

It looks like it does on the example from issue #18360 
Thanks!

**Pull request merged**
