### PR TITLE
Update REVISION

### PR DESCRIPTION
**Pull request by paulmasson**
Please merge when appropriate

### CODE REVIEW

**Comment by mrdoob** [comment]
We'll probably release a .1 next week with a few fixes so let's wait until then before merging this.

**Comment by paulmasson** [comment]
> We'll probably release a .1 next week with a few fixes so let's wait until then before merging this.

@mrdoob is this still going to happen?

**Comment by paulmasson** [comment]
And?

**Comment by Mugen87** [comment]
I think we can merge the PR since we can perform builds on `master` as well.

**Comment by mrdoob** [comment]
Yeah. Let's merge this.

**Pull request merged**
