### PR TITLE
WebGLRenderer: Create WebGL context with alpha: true.

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #22418

### CODE REVIEW

**Comment by mrdoob** [comment]
So there are two ways of doing it...

1) Let the browser do the compositing by doing `canvas.style.background = '#000` (first commit) which results in a bunch of E2E errors because SwiftShader seem to render lines/wireframes differently at that resolution:

| Current | New |
| --- | --- |
| image | image |

2) Or do it in `WebGLBackground` (second commit) which breaks `webgl_materials_blending_custom`:

Screen Shot 2022-01-13 at 9 40 58 PM

**Comment by mrdoob** [comment]
On the bright side... many of the examples that used to run at 40-50fps on my laptop, now run at 60fps 🥲

**Comment by Mugen87** [comment]
The PR has the following line:
```js
state.buffers.color.setClear( color.r, color.g, color.b, useAlpha ? alpha : 1.0, premultipliedAlpha );
```
I'm afraid this could introduce side effects when doing post processing. When `alpha` is set to `false` it is not possible to clear the alpha value in render targets anymore which might be necessary for certain use cases. Do you think we can figure out a solution that does affect the number of cleared channels?

How about using something like this: https://github.com/Mugen87/three.js/commit/db825d28761b745b5c5c6d4116d3eaace5ecc3e6

The idea is to always set `alpha` to `true` like in this PR. However, the `alpha` parameter is not passed to `WebGLBackground`. Instead, the default `clearAlpha` in `WebGLBackground` is changed from `0` to `1`.

So if users want to blend the canvas with the HTML background, they need this line:
```js
renderer.setClearAlpha( 0 );
```

**Comment by Mugen87** [comment]
What I don't understand is why subtractive blending with `alpha: true` does not honor the checkerboard background.

**Comment by Mugen87** [comment]
Some fiddles for testing:

(1) `alpha: false`: https://jsfiddle.net/eagy9rsq/
(2) `alpha: true`: https://jsfiddle.net/eagy9rsq/1/
(3) `alpha: true` and opacity `0.5`: https://jsfiddle.net/eagy9rsq/2/
(4) `alpha: false` and opacity `0.5`: https://jsfiddle.net/eagy9rsq/3/

I think I understand what happens in (2) and (3) but can somebody explain why test case 1 and 4 look identical?

**Comment by mrdoob** [comment]
Hmm...

We could also set `alpha: true` and `scene.background = new Color( 0, 0, 0 )` by default.

I think that should solve post processing and, migration wise, people would just have to set `scene.background` to `null` if they want transparent background.

**Comment by Mugen87** [comment]
> We could also set alpha: true and scene.background = new Color( 0, 0, 0 ) by default.

Sounds good! I like this solution more working with `Scene.background` seems more intuitive than setting a different clear alpha value with `setClearAlpha()`.

**Comment by mrdoob** [comment]
Seems like it also breaks code that used `renderer.setClearColor()`. Which, I'm okay with 😇

**Comment by Mugen87** [comment]
When `alpha` is always `true`, I think the renderer should use a clear alpha value of `1` by default. `WebGPURenderer` works like that and it turned out to be a good setup so far.

Does this sound okay for you?

What are your plans for `setClearAlpha()` and `setClearColor()`? Just want to know if these methods could be part of a potential solution.

The engine has to provide a way to define the clear alpha. If it is not `setClearAlpha()`, we have to think about a new API.

**Comment by mrdoob** [comment]
@Mugen87 Yeah, I think I'm going to give https://github.com/Mugen87/three.js/commit/db825d28761b745b5c5c6d4116d3eaace5ecc3e6 a try. Seems easier indeed 🤞

**Comment by mrdoob** [comment]
One more try... 😅

**Comment by mrdoob** [comment]
One "solution" would be to remove `THREE.CustomBlending`, `material.blendSrc`, `material.blendDest` and `material.blendEquation` and see how many people complain... 🙈

Does WebGPU have these things too?

**Comment by Mugen87** [comment]
Yes^^. `WebGPURenderer` already support the same set of blending setups like `WebGLRenderer`.

https://github.com/mrdoob/three.js/blob/fed9e42ea990f191568e4c904d083f47f882f501/examples/jsm/renderers/webgpu/WebGPURenderPipeline.js#L60-L70

The blending is part of the render pipeline and part of the respective descriptor (see https://gpuweb.github.io/gpuweb/#blend-state for details).

**Comment by Mugen87** [comment]
I'm not sure it's necessary to remove any blending setups. I'm sure we can update `webgl_materials_blending` and `webgl_materials_blending_custom` such that both examples makes sense with `alpha: true`.

**Comment by Mugen87** [comment]
In the long term, I would recommend to remove the `alpha` parameter completely. 

Maybe we can introduce at some point a solution over `Scene.background` (e.g. by assigning a four component color value). In this way, users could perform all background configurations via `Scene.background` and don't need `setClearAlpha()` and `setClearColor()` anymore. However, this requires users always pass a scene to `WebGLRenderer.render()` and not just a mesh.

**Comment by mrdoob** [comment]
Alright. I'll merge this for now then.

I don't think I'll be able to investigate `THREE. CustomBlending` during this cycle though.

**Pull request merged**
