### PR TITLE
Optimize EventDispatcher performance with Map and Set

### PR DESCRIPTION
**Pull request by ghost**
Hey, not sure if these changes are what you're looking for, but here's what I did:

I swapped out plain objects and arrays for `Map` and `Set` in the `EventDispatcher` class to store event listeners. The goal is to boost performance, especially when there are a lot of listeners, since `Map` and `Set` offer O(1) time complexity for adding, removing, and checking items.

### Key Changes:
- **Performance improvement**: Should give a nice performance improvement in `Edge`, and we should see similar improvements in `Chrome` and `Firefox` too.
- **API compatibility**: The update doesn't break the existing `EventDispatcher` API, so no need to change anything on the user side I think.
- **Efficiency improvements**: This should help reduce overhead and make event dispatching faster, which is especially useful in performance-heavy scenarios like 3D games.
- **Cross-browser compatibility**: It's all compatible with the MDN baseline and works across modern browsers.
- **Benchmarks**: I ran some benchmarks with `performance.now()` in the browser and saw good improvements in `Edge`. `Chrome` should have similar results.

Let me know what you think!

### CODE REVIEW

**Comment by mrdoob** [comment]
> * **Benchmarks**: I ran some benchmarks with `performance.now()` in the browser and saw good improvements in `Edge`. `Chrome` should have similar results.

Please, share links to these benchmarks 🙏

**Comment by linbingquan** [comment]
```ts
import { EventDispatcher as OldEventDispatcher } from "./old.js";
import { EventDispatcher as NewEventDispatcher } from "./new.js";

Deno.bench({
  name: "new",
  fn() {
    const dispatcher = new NewEventDispatcher();
    dispatcher.addEventListener("event", () => {});
    dispatcher.dispatchEvent("event");
  },
});

Deno.bench({
  name: "old",
  fn() {
    const dispatcher = new OldEventDispatcher();
    dispatcher.addEventListener("event", () => {});
    dispatcher.dispatchEvent("event");
  },
});
```

```
benchmark   time/iter (avg)        iter/s      (min … max)           p75      p99     p995
----------- ----------------------------- --------------------- --------------------------
old                 47.3 ns    21,140,000 ( 39.5 ns … 247.7 ns)  48.9 ns  92.1 ns  97.4 ns
new                115.2 ns     8,677,000 ( 99.8 ns … 629.5 ns) 108.6 ns 552.0 ns 607.8 ns

summary
  old
     2.44x faster than new
```

**Comment by linbingquan** [comment]
```ts
import { EventDispatcher as OldEventDispatcher } from "./old.js";
import { EventDispatcher as NewEventDispatcher } from "./new.js";

Deno.bench({
  name: "old",
  baseline: true,
  fn() {
    const dispatcher = new OldEventDispatcher();
    dispatcher.addEventListener("event", () => {});
    dispatcher.dispatchEvent("event");
  },
});

Deno.bench({
  name: "new",
  fn() {
    const dispatcher = new NewEventDispatcher();
    dispatcher.addEventListener("event", () => {});
    dispatcher.dispatchEvent("event");
  },
});
```

```
benchmark   time/iter (avg)        iter/s      (min … max)           p75      p99     p995
----------- ----------------------------- --------------------- --------------------------
old                 48.1 ns    20,790,000 ( 39.1 ns … 201.3 ns)  49.4 ns  95.1 ns 109.9 ns
new                116.6 ns     8,574,000 (102.7 ns … 297.5 ns) 119.9 ns 191.1 ns 218.7 ns

summary
  old
     2.42x faster than new
```

**Comment by sunag** [comment]
> old 2.42x faster than new

It makes sense to me. Usually primitive values ​​are faster, this should also apply to `for` instead of `forEach`.

**Comment by gkjohnson** [comment]
> ```js
> dispatcher.dispatchEvent("event");
> ```

Just to make sure - this benchmark isn't using `dispatchEvent` properly. The function takes an object like so:

> ```js
> dispatcher.dispatchEvent( { type: 'event' } );
> ```

It may still be faster but this "dispatch" call isn't actually doing or testing anything right now. I would also benchmark `dispatchEvent` and `addEventListener` separately since `dispatchEvent` will get called significantly more frequently than `addEventListener`.

**Comment by eXponenta** [comment]
Any iterators that use `Symbol.iterator` is slower about 2 times relative indexed for loop. 

Map and Set stored as linked hash tree and can't be indexed and because of this uses `Symbol.iterator` for it.

Iteration more important than add/remove listeners, because events can be fired every frame, but listeners assigned only in app start or when something updated by user input.

Also classic events tree about 10-20 listeners, slice over 10-20 is highly optimised operation.

Also Map and Set by designed for frequent update by unknown key set.

Events map is KNOWN keyset. Because we not set random key as event type every update and listeners map will be high optimised type-shape with strictly known properties.

Classic event name in core: "update".
This mean that we will be created a lot of  small objects with references to single shape map inside JS runtime with property name "update".
[How this works] (https://mathiasbynens.be/notes/shapes-ics )


Conclusion: Map and Set not good idea for usage for EventDispatcher due to performance degradations in basic usage.

**Comment by Mugen87** [comment]
Based on the feedback so far it seems better to close the PR.

**Comment by linbingquan** [comment]
I borrowed from the existing library and I wrote `Emitter.ts` and found these:

With the following changes, dispatchEvent should be faster than it is now.

Test cases can be less rigorous and contain errors.

1.  `dispatchEvent( event )` change to `dispatchEvent(type, ...args)`
2.  remove code `event.target = this` and `event.target = null` 
3.  use `apply` replace `call`

```sh
benchmark            time/iter (avg)        iter/s      (min … max)           p75      p99     p995
-------------------- ----------------------------- --------------------- --------------------------
Emitter                      18.7 ns    53,360,000 ( 15.3 ns … 138.2 ns)  18.9 ns  36.4 ns  55.3 ns
NewEventDispatcher           18.8 ns    53,110,000 ( 14.6 ns … 157.2 ns)  18.4 ns  73.1 ns  82.2 ns
EventDispatcher              30.8 ns    32,450,000 ( 24.0 ns … 244.5 ns)  33.5 ns  58.2 ns 118.6 ns
mitt                         38.4 ns    26,030,000 ( 32.2 ns … 142.8 ns)  41.3 ns  69.3 ns 100.2 ns
onfire.js                    41.3 ns    24,230,000 ( 30.5 ns … 249.9 ns)  44.2 ns  81.0 ns 120.2 ns

summary
  Emitter
     1.00x faster than NewEventDispatcher
     1.64x faster than EventDispatcher
     2.05x faster than mitt
     2.20x faster than onfire.js
```

If these changes are implemented, they should involve quite a few code changes...
We may must to explicitly pass the target like: `dispatchEvent(type, {type, target: this})`

**Pull request closed without merging**
