### PR TITLE
WebGPURenderer: Texture2D Array

### PR DESCRIPTION
**Pull request by sunag**
**Description**

I made revisions and added support for `Texture2D Array`.

**Example**

https://raw.githack.com/mrdoob/three.js/dev/examples/webgpu_textures_2d-array.html

TSL Syntax:

```js
const map = new THREE.DataArrayTexture( ... );
const mapLayer = 3;

...

material.colorNode = texture( map ).depth( mapLayer );
```

### CODE REVIEW

**Comment by WestLangley** [comment]
@sunag Something is wrong with `webgpu_cubemap_adjustments`. The dark triangle that appears on the bottom of the sphere should not be so visible. In the following screenshot, the material is modified with metalness 0 and roughness 0.

Screenshot 2023-11-16 at 8 14 20 PM


Compare with `webgl_materials_envmaps_hdr.html`.

I can file a separate bug report if you feel it is warranted.

**Comment by sunag** [comment]
@WestLangley The `hue()` function is causing this, I will update the code, thanks!

**Comment by WestLangley** [comment]
@sunag I tested your PR and it still does not look correct for some reason. Compare with `webgl_materials_envmaps_hdr.html` and replace the geometry with a sphere.

**Comment by sunag** [comment]
If it's due to the difference below it's because of PMREM, unfortunately I haven't managed to implement the node-based solution yet.

| WebGL | WebGPU |
| ------------- | ------------- |
| image  | image |

**Comment by WestLangley** [comment]
Yes, that is what I am seeing.

**Comment by mrdoob** [comment]
Does this enable enable `webgpu_morphtargets_face`? ([webgl_morphtargets_face](https://threejs.org/examples/webgl_morphtargets_face.html))

**Comment by sunag** [comment]
> Does this enable webgpu_morphtargets_face?

I will implement it in a separate PR, I would like to use `compute()` but this would not work in `WebGLBackend` at this time.

**Pull request merged**
