### PR TITLE
NodeEditor: minor improvement

### PR DESCRIPTION
**Pull request by fyoudine**
Adding some minor improvement and fix

### CODE REVIEW

**Comment by sunag** [comment]
About `JoinNode` you are adding support for multi-vector inputs, right? e.g: `[ vec2, float ]` -> `vec3`?

**Comment by fyoudine** [comment]
> About `JoinNode` you are adding support for multi-vector inputs, right? e.g: `[ vec2, float ]` -> `vec3`?

Hello @sunag exactly

**Review by sunag — APPROVED** [review]
Nice!! I think we need to rename `JoinEditor` names later to be more compliant. ( Maybe rename it in runtime from node input )

image

**Comment by sunag** [comment]
Thanks!

**Pull request merged**
