### PR TITLE
Editor: Added Listbox element

### PR DESCRIPTION
**Pull request by sdinesh86**
Referring to #17489, adding a simple Generic Listbox implementation.

### CODE REVIEW

**Comment by mrdoob** [comment]
Ops, do you mind fixing the conflicts?

**Comment by sdinesh86** [comment]
> Ops, do you mind fixing the conflicts?

I am not so sure how to do that can you guide me ?

**Comment by mrdoob** [comment]
You have to pull from `mrdoob:dev` to your local `sdinesh86:editor-listbox` branch.
Do you use command line or a gui?

**Comment by sdinesh86** [comment]
> You have to pull from `mrdoob:dev` to your local `sdinesh86:editor-listbox` branch.
> Do you use command line or a gui?

I use GUI from VS Code should i accept both changes, Incoming changes or Current changes ?

**Comment by mrdoob** [comment]
> Should i include the TabbedPanel related changes in this PR as well ?

Yes, the issue is that the TabbedPanel PR got merged, and that created conflicts with this PR, so in order to fix it you need to merge these changes here. The easiest is to merge `dev` in this branch.

**Comment by sdinesh86** [comment]
I had a stash of these changes that i will apply on the dev branch and then merge in this branch

**Comment by mrdoob** [comment]
That works 👍

**Comment by sdinesh86** [comment]
Thanks, done 👍

**Comment by mrdoob** [comment]
Just to confirm, do these changes look good to you?
https://github.com/mrdoob/three.js/pull/17490/files

**Comment by sdinesh86** [comment]
yes they look good

Also regarding some of the changes in my PR, i will tend to include some patchs just to not break existing things, sort of like transitional changes

I will be cleaning them up at the end of the task #17489

The idea is that, i will be new things and refactoring things like a patch till we get a good implementation of Material Browser.
Once we find the right implementation and are sure of it will take some time to clean up all the previous patchs and freeze it.

What are your thoughts ?

**Comment by mrdoob** [comment]
Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
