### PR TITLE
Multiple Elements Example: Add camera controller to each element

### PR DESCRIPTION
**Pull request by WestLangley**
I thought it would be useful to show how to make each element interactive.

This demo could be improved further by removing the animation loop and rendering only in response to user events.

http://ci.threejs.org/api/pullrequests/7703/examples/index.html#webgl_multiple_elements

### CODE REVIEW

**Comment by mrdoob** [comment]
I like it! It loses a bit of the wow factor though...
I think seeing them all moving was the main point of the example.

**Comment by WestLangley** [comment]
>I think seeing them all moving was the main point of the example.

The main point of the example was to show how to have multiple divs and one renderer.

This example shows how to have one renderer and multiple controllers, each controlling its own camera.

One could modify this PR to have the objects spin, or add 90 additional divs, I suppose.

**Comment by mrdoob** [comment]
> The main point of the example was to show how to have multiple divs and one renderer.

Yes, but it also handles what viewports are visible and avoids rendering the ones that are not, that's why there were 100 viewports.

> One could modify this PR to have the objects spin, or add 90 additional divs, I suppose.

Yeah, maybe having them rotating on the Y axis may do the trick.

**Comment by WestLangley** [comment]
@mrdoob I added some animation for visual interest. I'l leave it up to you if you want to merge this, further change it, or close this PR. Whatever you want is fine with me.

**Comment by mrdoob** [comment]
Maybe we should disable zoom in the controls? The page can't scroll now...

**Comment by WestLangley** [comment]
>The page can't scroll now...

The behavior I see is the page will scroll as long as the cursor/touch is outside a canvas element.

I tried TrackballControls, and the behavior is worse -- it zooms and scrolls at the same time. :/

>Maybe we should disable zoom in the controls?

I can do that if you like.

However, on my iPhone, the examples page with the iframe does not render correctly with this example. The CSS and canvas elements are not aligned. It works fine as a stand-alone page.

**Comment by WestLangley** [comment]
@gero3 Is it true that http://ci.threejs.org/api/pullrequests/7703/examples/webgl_multiple_elements.html does not update when additional commits are pushed to the PR? That is what appears to be happening.

**Comment by mrdoob** [comment]
> However, on my iPhone, the examples page with the iframe does not render correctly with this example. The CSS and canvas elements are not aligned. It works fine as a stand-alone page.

I bet is related to this iOS gripe:

https://github.com/mrdoob/three.js/blob/dev/examples/index.html#L202-L213

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
