### PR TITLE
Line3: Add equalsLoose()

### PR DESCRIPTION
**Pull request by trololek**
Hello,
I propose a new method for Line3 to check if two lines are loosely the same, as in one line has the start point of the other line as an end point and vice versa. Currently there is (at least to my knowledge) no way to check wether two lines are loosely the same in a convenient manner (i.e. without for example instantiating a new line with swapped start and end points).

### CODE REVIEW

**Comment by Mugen87** [comment]
I wonder if this shouldn't be the implementation of `equals()`. It seems other projects implement their equals method that way e.g. https://github.com/juj/MathGeoLib/blob/2940b99b99cfe575dd45103ef20f4019dee15b54/src/Geometry/LineSegment.cpp#L151-L154

**Comment by WestLangley** [comment]
This PR is testing for coincidence.

```js
line1.isCoincident( line2 );
```
I had not previously heard of line segments being "equal".

I guess a short line segment can be coincident with a longer line segment, however....

Maybe

```js
line1.isEquivalent( line2 );
```

**Comment by Mugen87** [comment]
I've changed my mind. Since `Line3` distinguishes between `start` and `end` point, it's not valid to treat the mentioned case as equality. Otherwise methods like `at()` would produce different result although they would be considered as equal.

**Comment by mrdoob** [comment]
`matches()`?

**Comment by trololek** [comment]
I think `matches()` matches quiet nicely :) I also think `equals()` should return only true for strict equality, for the same reasons @Mugen87 mentioned.

**Comment by WestLangley** [comment]
I would consider this method app-specific.

If you insist on including it, then I'd name it `isCoincident()`, or `coincident()`.

If you add it, others may want `isParallel()`, `isPerpendicular()`, `isColinear()`, `intersects()`, etc...

**Comment by Mugen87** [comment]
> I would consider this method app-specific.

Me too. As long as not more users requests such a method, I would leave it out. 

Especially since all suggested names are not really self-explaining (so a look in the documentation or the source code is required to know what the method actually does).

**Comment by mrdoob** [comment]
Agreed.

Lets close this one for now and reopen it if more people needs it in the future.

**Pull request closed without merging**
