### PR TITLE
EXRLoader: support single channel luminance - RedFormat

### PR DESCRIPTION
**Pull request by sciecode**
Addresses https://github.com/mrdoob/three.js/issues/20195#issuecomment-986023382

I noticed a difference between our implementation and OpenEXR's in trying to decompress a block only if input-data is actually smaller than the expected data-size. This PR standardizes this issue and makes equivalent to OpenEXR implementation.

It also initially includes support for luminance - single channel files `HalfFloatType / FloatType`. 
Luminance images are treated as `RedFormat` - WebGL2 only context.

Updated  `textureData` header info to include specification flags, to help identify if problematic files contain lack of supported features like  Deep-Image, Multi-Part or Tiled image files.

image

I largely tested these changes, but would appreciate further testing - @Mugen87, @WestLangley 

-- 

Currently we fail to support `.setDataType( THREE.UnsignedByteType )` on Luminance maps. 

`setDataType` is properly followed even in cases where there is an underlying mismatch between input-type and output-types.  
( e.g like a float32b input file transformed into a half16b texture ). When we set the output-type to `UnsignedByteType` on a RGB/RGBA files we also encode the output-texture as `RGBEEncoding` and transform the data appropriately.

However transforming a luminance map of 32/16 type to an uint8 type is not yet specified, should I explicitly allow that transformation? If so, should I then change the texture format to `LuminanceFormat` in order to support WebGL1 contexts?

### CODE REVIEW

**Comment by Mugen87** [comment]
> However transforming a luminance map of 32/16 type to an uint8 type is not yet specified, should I explicitly allow that transformation?

I think at some point the encoding to RGBE should be removed from `EXRLoader` and half float used instead. With WebGL 2 we can rely on half float, see #22998.

Yes, half float textures allocate more memory however it's possible to use `THREE.LinearFilter` and it simplifies the code in the loader and shader.

**Comment by Mugen87** [comment]
The luminance texture on my computer loads now as expected 👍 .

**Comment by Mugen87** [comment]
https://raw.githack.com/sciecode/three.js/exrloader-channels/examples/index.html

**Comment by sciecode** [comment]
> > However transforming a luminance map of 32/16 type to an uint8 type is not yet specified, should I explicitly allow that transformation?
> 
> I think at some point the encoding to RGBE should be removed from `EXRLoader` and half float used instead. With WebGL 2 we can rely on half float, see #22998.

By default the loader already specifies `HalfFloatType` as the default output type. 

> Yes, half float textures allocate more memory however it's possible to use `THREE.LinearFilter` and it simplifies the code in the loader and shader. 

Yeah I can definitely see that being an issue. In that case, this PR should be ready to merge, in case we don't find any testing problems.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
