### PR TITLE
Texture JSON

### PR DESCRIPTION
**Pull request by tschw**
Lets Texture.toJSON write texture info in numeric form.
Lets ObjectLoader read this format and also the symbolic one for some backward compatibility.
Also fixes a potential loader quirk.

### CODE REVIEW

**Comment by mrdoob** [comment]
> Lets ObjectLoader read this format and also the symbolic one for some backward compatibility.

Hmmm, I think I would ignore the backwards compatibility here as I suspect not much code relies on this yet.

**Comment by tschw** [comment]
It breaks scene import from Blender, maybe also from other converters/exporters until they get updated...

**Comment by mrdoob** [comment]
@repsac what do you think? Should we go with numeric or symbolic form?

**Comment by repsac** [comment]
I think I would be in favor of numeric form. But maybe (for the sake of sanity) for r72 it prints a warning to console that symbolic form gets deprecated on the next release.

**Comment by mrdoob** [comment]
Sounds good!

**Pull request merged**
