### PR TITLE
Core: Convert Object3D and EventDispatcher to ES6 classes.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

Converts the remaining two class in the `src/core` folder.

### CODE REVIEW

**Comment by Mugen87** [comment]
`WebXRManager` needs to be updated before `EventDispatcher` can be an ES6 class.

**Comment by mrdoob** [comment]
Thanks!

**Comment by drcmda** [comment]
@Mugen87 do you still remember what prompted this change https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L66-L94

Screenshot 2021-11-01 at 14 32 45

the request we go was that people want to wire up their own vectors/matrixes which they can then control outside of the class. but it seems these props can't get overwritten any longer.

**Comment by mrdoob** [comment]
It was a bad practice.

People did this a lot:

```js
mesh.position = new THREE Vector(1,1,1)
```

Instead of

```js
mesh.position.set(1,1,1)
```

That pattern also broke `mesh.rotation` which we need to track to create `mesh.quaternion`.

**Comment by drcmda** [comment]
for reference https://github.com/pmndrs/react-three-fiber/discussions/1419 they want to drive matrix externally, which is similar, `mesh.matrix = externalMatrix`. if this is the intended direction, i would communicate that overwriting props in threejs is no longer accepted.

**Comment by mrdoob** [comment]
It definitely is discouraged.

**Comment by drcmda** [comment]
understood. im glad i opted for .copy for `<mesh position={external}` some years ago ☺️

**Pull request merged**
