### PR TITLE
PMREM: Un-flip CubeUV tiles

### PR DESCRIPTION
**Pull request by WestLangley**
Currently, all the tiles are rendered to the `Cube_UV` texture flipped left-right.

Reducing the flipping should be helpful in debugging other issues.

To keep things simple, face indexing in PMREM is not changed with this PR. Also, this PR should have no impact on the final rendering.

In other words, this PR only flips the the tiles so they look like the original faces of the cube map. No tiles are moved or swapped.

### CODE REVIEW

**Comment by elalish** [comment]
Okay, given the discussion [there](https://github.com/mrdoob/three.js/pull/19237#issuecomment-620143773), this seems like a good approach.

**Comment by sciecode** [comment]
> Okay, given the discussion [there](https://github.com/mrdoob/three.js/pull/19237#issuecomment-620143773), this seems like a good approach.

Sorry, I deleted the previous post because I got confused again.

This is indeed mind bending @elalish, you were definitely right.

I'll review everything I said again and make sure I'm not talking non-sense.

**Comment by sciecode** [comment]
Ok, I'll explain what confused me.

This PR is not yet inline with CubeMaps handedness, +/X are swapped. So this is yet in RH.

cubemap ( left ) - PR ( right )
      

However we can modify it to make it exactly the same and it will still work fine if we modify `fromScene` to make the camera exactly the same as the cubemap explanation in https://github.com/mrdoob/three.js/pull/19237#issuecomment-620102814

I tested it and it works fine. However, I don't like it. Specifically because when call the function `getUV` in the shaders, we are given a direction in RH ( default three.js ) and we need to output UV from a texture in LH ( cube map ) which is simply a nightmare to debug. It took me a solid hour and a half just to try and figure out how to do it and truth be told is was mostly try and error. But I wouldn't go against it if that's how we want to proceed.

The current state of the PR however is a mid-way between one and the other and I don't see a reason for making it this way.

I say we have two options, fix this to be completely the same as CubeMap textures and later file a PR to fix `fromScene` camera, or we go with my approach in #19237. 

Right now, I'm favoring my approach, simply because it is easier to reason about when debugging.

**Comment by WestLangley** [comment]
This PR is simple. It only does one thing: flips the images. Other PRs can follow.

PMREM from this PR -- matches the 6 cubemap images
WestLangley


PMREM from r.116 -- images are reversed
r 116

**Comment by sciecode** [comment]
> This PR is simple. It only does one thing: flips the images. Other PRs can follow.

I'm afraid this is not true, this PR is incomplete.

Compare the differences between the generated background in DEV and your PR. You're gonna notice that all textures are inverted, specifically look for the blue light.

This is actually expected, since you reversed all textures in the cube_uv texture, but didn't change the way `pmremGenerator.fromScene` produces these textures. If you are able to fix this, without using `scene.scale` or `scene.rotation`. I'll close my PR and we can move on with yours.

No problem.

**Comment by sciecode** [comment]
Here's an simple comparison I made, to showcase this.

[ DEV `fromScene`](https://jsfiddle.net/5pyn98va/)
[ PR `fromScene`](https://jsfiddle.net/zeqtfgkc/)

**Comment by mrdoob** [comment]
Thanks!

**Comment by sciecode** [comment]
This closes #19159 btw.

**Comment by WestLangley** [comment]
I have merged a patch from @sciecode that should fix #19159.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Emmett Lalish <notifications@github.com>
发送时间：2020-04-28 02:17
主题：Re: [mrdoob/three.js] PMREM: Un-flip CubeUV tiles (#19235)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Okay, given the discussion there, this seems like a good approach.

**Pull request merged**
