### PR TITLE
Add "set" functions to allow changes to viewport and scissoring

### PR DESCRIPTION
**Pull request by jcsavvi**
Adding the ability to set scissoring (and viewport) to `WebGLRenderTarget`, as currently the `setRenderTarget` method of `WebGLRenderer` uses the original values for `scissor` and `scissorTest` and `WebGLRenderTarget` provides no methods to change them (although the properties are not private).

This change allows the use of `myWebGLRenderTarget.setScissor(x, y, width, height);` instead of having to call `myWebGLRenderTarget.scissor.set(x, y, width, height);` before any `myWebGLRenderer.render(scene, camera, myWebGLRenderTarget);` (otherwise the scissor for the originally created render target overwrites the context scisssor every render).

Using scissoring in my off-screen render target gains significant FPS when I render a scene for pixel-picking and I only care about one pixel or a few pixels e.g. under the mouse pointer. I simply update a vector of mouse X & Y coordinates `onmousemove` and pass these as `x` & `y` to `myWebGLRenderTarget.scissorSet(x, y, 1, 1);` before `myWebGLRenderer.render(myPickSceneWithObjectIDsEncodedInFragColor, camera, myWebGLRenderTarget)`, with the obvious `myWebGLRenderer.readRenderTargetPixels(myWebGLRenderTarget, x, y, 1, 1, pickPixel);` using the same `x` & `y`. Whilst this example changes the scissor every render pass, it seems better to use the same scissoring methods against the render target as I do against the renderer.

### CODE REVIEW

**Comment by mrdoob** [comment]
> This change allows the use of `myWebGLRenderTarget.setScissor(x, y, width, height);` instead of having to call `myWebGLRenderTarget.scissor.set(x, y, width, height);` 

What's wrong with calling `myWebGLRenderTarget.scissor.set(x, y, width, height);`?

**Comment by jcsavvi** [comment]
Ola Doobs. Long time listener, first time caller.

This change allows the use of myWebGLRenderTarget.setScissor(x, y, width,
height); instead of having to call myWebGLRenderTarget.scissor.set(x, y,
width, height);

What's wrong with calling myWebGLRenderTarget.scissor.set(x, y, width,
height);?

Yeah, nothing wrong with that. Just that I spent ages digging through
`WebGLRenderer` (which is my active object when I call rendering actions
against my `WebGLRenderTarget`) trying to figure out why my scissor calls
to `myWebGLRenderer.setScissor()` only apply to the null render target
despite using `myWebGLRenderer.render()` to actually do the work for my
`WebGLRenderTarget`.

It's just that there's a weird overlap and disconnect between
`WebGLRenderer` and `WebGLRenderTarget`, and I'm sure that a lot of
off-screen render target use is for pixel picking, it makes sense to make
it really obvious to users of `WebGLRenderTarget` that the scissor settings
of the renderer are not used by the non-null targets (and that the default
"on create time" scissor is used despite the renderer's scissor settings).
This was not obvious to me without hacking, and it cost me FPS when my
scissoring was not happening on the render target, which took a while to
track down (cause I can't see it).

I'm happy to add docs & even an example of pixel-picking using scissoring
with off-screen targets. It's well worth it to not run the frag shader for
pixels that you don't want to pick, and i don't think that's commonly done.

Happy for you to reject the pull and do something different, just let me
know if you want me to do the work.

J

**Comment by WestLangley** [comment]
>I'm happy to add ... an example of pixel-picking using scissoring
with off-screen targets. It's well worth it to not run the frag shader for
pixels that you don't want to pick, and i don't think that's commonly done.

I think that would be illustrative -- or maybe you could modify an existing example...

I have no opinion one way or the other regarding the proposed API change.

**Comment by jcsavvi** [comment]
On my little mobile chipset, this example runs at 40fps after zooming out to see all cubes. After my change, I get 50fps.

The demonstration of the use of the new methods (which are commented out) are there to show how the scissor would be set on the render target vs set on the renderer.

I believe a few folks out there would expect that the `setScissor()` method of the renderer (i.e. the `WebGLRenderer`) would apply to the off-screen render-target as it does to the on-screen default target (which it doesn't - the renderer uses the scissor paramaters within the `WebGLRenderTarget` if called with a `renderTarget` parameter). Adding the methods on the `WebGLRenderTarget` goes some way to help users see that they must set the scissor on the render target.

**Comment by Mugen87** [comment]
> What's wrong with calling myWebGLRenderTarget.scissor.set(x, y, width, height);?

I think doing this is fine. Additional wrapper methods only unnecessarily bloat the API.

**Pull request closed without merging**
