### PR TITLE
Add missing uv properties

### PR DESCRIPTION
**Pull request by MagnuzBinder**

### CODE REVIEW

**Comment by WestLangley** [comment]
Should this section be moved elsewhere -- for example, to the `fromBufferGeometry()` method? Or maybe moved to the example section? Lines don't have UVs.

Also, on a semi-related note, any idea what the following paragraph is referring to?

>In addition to the the built-in attributes, you can set your own custom attributes using the addAttribute method. With Geometry, these attributes are set and stored on the Material. In BufferGeometry, the attributes are stored with the geometry itself. Note that you still need to set the attributes information on the material as well, but the value of each attribute is stored in the BufferGeometry.

---

I should add that this part of the documentation is not intended to be a tutorial; its purpose is to document the API.

As a tutorial, it is inadequate. We can refer readers to third-party books and tutorials if we want. Keeping the focus limited will make the documentation easier to write.

Also, saying

>This also makes BufferGeometry harder to work with than Geometry

is an opinion, and is not appropriate here.

This is not meant to be critical. In fact, the contributors to the docs deserve many, many thanks for their efforts.

**Comment by caseygrun** [comment]
It's been a while, but I think I wrote that section because I initially found it very confusing why there were two different classes that could represent geometry. While I agree that the docs are not intended as a tutorial, the distinction between Geometry and BufferGeometry was invented by the authors of three.js, and it's important for users to understand which to use to suit their needs. The core difference is that BufferGeometry is a lower-level construct which allows finer control of the attribute data whereas Geometry has a higher-level but less performant API. You're right that "This also makes BufferGeometry harder to work with than Geometry" isn't the most elegant way to convey that difference, but that was my best attempt at the time.

As for the longer paragraph, at the time it was written (not sure if this is still the case), for `Geometry`s, the names and data for the underlying WebGL attributes were stored in a property of the `Geometry`'s attached `Material`. On the other hand, data for attributes of a `BufferGeometry` were set and stored on the `BufferGeometry` object itself, and only the names of the attributes were set on the `Material`. At least, that's what I remember...

**Comment by Mugen87** [comment]
> This also makes BufferGeometry harder to work with than Geometry

This sentence was removed a while ago. The general description of `BufferGeometry` sounds now less opinion-based.

Apart from that, I agree with @WestLangley that the `Accessing Attributes` section is inappropriate for this doc page. I suggest to close the PR and make another one to clean up the page.

**Pull request closed without merging**
