### PR TITLE
LoaderUtils: Added .extractExtension()

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces a common and robust way in order to extract the file extension from a given url via `LoaderUtils.extractExtension()`.

### CODE REVIEW

**Comment by makc** [comment]
@Mugen87 you kind of lost the functionality here. you do index + 1, while original does (index -1 >>> 0) + 2. the difference is that index == -1 maps to 0 (whole file name) in your version and 4294967296 (empty string) in theirs, for example

**Comment by Mugen87** [comment]
Have you seen the test cases. The approach seems to work ( also see http://www.jstips.co/en/javascript/get-file-extension/ )

**Comment by makc** [comment]
It should work when there is actual extension, yes

**Comment by Mugen87** [comment]
Um, I'm not sure I have understood your first comment correctly. If you know a better/faster approach with the same outcome, then please share the complete function in this thread.

**Comment by makc** [comment]
sorry, nvm. I think I misread the diff

**Comment by mrdoob** [comment]
In the editor I use this code:

```js
url.split( '.' ).pop().toLowerCase();
```

**Comment by takahirox** [comment]
`url` strings passed to `Loader`s can be invalid. So it should be more robust for `Loader`s. For example

    'abc'.split( '.' ).pop().toLowerCase()

returns 'abc' but extension should be `null`, `undefined`, empty strings, or something like that.

**Pull request closed without merging**
