### PR TITLE
BatchedMesh: Fix `renderer.info.render` when using multidraw.

### PR DESCRIPTION
**Pull request by agargaro**
Related issue: #29531 

**Description**

`info.update()` increases the draw calls by 1 for each call, and here it is called more than once. 
In addition, the number of triangles is not calculated correctly.

Edit: moved to draft to do more checking

### CODE REVIEW

**Comment by Mugen87** [comment]
It looks good to me. This should also be checked by @gkjohnson 🙌 .

**Comment by gkjohnson** [comment]
The `WebGLBufferRenderer` implementation should be updated to match `WebGLIndexedBufferRenderer` (the current PR modifies the WebGPURenderer WebGL fallback version only):

https://github.com/mrdoob/three.js/blob/1841e388302219ae05aa23852211d052bca58b52/src/renderers/webgl/WebGLBufferRenderer.js#L72-L76

And I'm less familiar with the WebGPURenderer but it looks like the primitives aren't correctly counted in that case, either:

https://github.com/mrdoob/three.js/blob/1841e388302219ae05aa23852211d052bca58b52/src/renderers/webgpu/WebGPUBackend.js#L952-L959

**Comment by agargaro** [comment]
> The `WebGLBufferRenderer` implementation should be updated to match `WebGLIndexedBufferRenderer` (the current PR modifies the WebGPURenderer WebGL fallback version only):
> 
> https://github.com/mrdoob/three.js/blob/1841e388302219ae05aa23852211d052bca58b52/src/renderers/webgl/WebGLBufferRenderer.js#L72-L76

fixed, thanks

> 
> And I'm less familiar with the WebGPURenderer but it looks like the primitives aren't correctly counted in that case, either:
> 
> https://github.com/mrdoob/three.js/blob/1841e388302219ae05aa23852211d052bca58b52/src/renderers/webgpu/WebGPUBackend.js#L952-L959

is this relative to #29488?

**Comment by gkjohnson** [comment]
> is this relative to https://github.com/mrdoob/three.js/issues/29488? info.update() is not called at all

Seems likely - but again support for BatchedMesh in the WebGPU backend seems incomplete at the moment. If you can test it then it seems worth adding either way.

**Comment by RenaudRohlinger** [comment]
Support for BatchedMesh in the WebGPU backend will be finalized with the completion of the indirect draw API (WIP: [#29372](https://github.com/mrdoob/three.js/pull/29372)). We'll also need to determine how to handle the statistics for indirect draw calls in renderer.info. Once we identify an appropriate way to represent these stats, we can make decisions on how to calculate the infos of the BatchedMesh in WebGPU I guess.

**Review by gkjohnson — APPROVED** [review]

**Pull request merged**
