### PR TITLE
Object3d: Add optional target to `getObjectsByProperty()`.

### LINKED ISSUE #27223: Object3D: getObjectsByProperty improvement
### Description

The **getObjectsByProperty** method can be greatly improved by sharing the same array, instead of creating new ones and concatenating them.

I have created an example where performance can be checked.

If you want I can do PR.

### Reproduction steps

I created a scene with 5000 children and called the getObjectsByProperty method to select them all.

### Code

Current function:

```js
getObjectsByProperty( name, value ) {

		let result = [];

		if ( this[ name ] === value ) result.push( this );

		for ( let i = 0, l = this.children.length; i < l; i ++ ) {

			const childResult = this.children[ i ].getObjectsByProperty( name, value );

			if ( childResult.length > 0 ) {

				result = result.concat( childResult );

			}

		}

		return result;

	}
```

Function with shared array reference:

```js
function getObjectsByProperty2(name, value, result = []) {
  if (this[name] === value) result.push(this);

  for (let i = 0, l = this.children.length; i < l; i++) {
    this.children[i].getObjectsByProperty2(name, value, result);
  }

  return result;
};
```

### Live example

https://jsfiddle.net/agargaro/qyh6zxkg/4/

### Screenshots

_No response_

### Version

r158

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by agargaro**
Fix #27223

**Description**

getObjectsByProperty performance improvement

### CODE REVIEW

**Comment by Mugen87** [comment]
The documentation of `Object3D.getObjectsByProperty()` should be updated to reflect the new parameter:

https://threejs.org/docs/index.html#api/en/core/Object3D.getObjectsByProperty

**Comment by agargaro** [comment]
I copied the description from here:

https://threejs.org/docs/#api/en/core/Raycaster.intersectObjects

Now is:

image

Is it OK or should I edit it?

I also updated the code, adding the children variable.

**Comment by Mugen87** [comment]
> Is it ok or should I edit it?

Description sounds good that way, imo.

> Is it ok if I only edit the english one?

It would be ideal to copy over the changes to the other pages. The English text can be translated at a later point.

**Comment by agargaro** [comment]
I've updated the other pages with the english texts and translated the Italian one.

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
