### PR TITLE
Loader: Remove .initMaterials() and .createMaterial().

### PR DESCRIPTION
**Pull request by Mugen87**
After removing `CTMLoader`, `LegacyJSONLoader` is the only loader that still relies on `.initMaterials()` and `.createMaterial()`.

The PR removes both methods from `Loader` and transfers the logic as new functions to `LegacyJSONLoader`.

Tested with `models/json/legacy/monster/monster.js`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Awesome!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I think we can also remove the `onLoadStart`, `onLoadProgress` and `onLoadComplete` methods?

With all this cleaned up, we can then add `load`, `parse`, `setCrossOrigin`, `setPath`, `setResourcePath`, etc so then we can use the class as a base for all the loaders and remove all the duplicate methods.

What do you think?

**Comment by Mugen87** [comment]
Sounds good! 👍

**Pull request merged**
