### PR TITLE
Add unit tests for play, stop and reset in animationAction

### PR DESCRIPTION
**Pull request by gero3**
This PR adds unit tests for animationAction.

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind converting the file to hard tabs?

**Comment by gero3** [comment]
This is now fixed.

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
`npm run test` fails with this change here on my Windows10.
Seems like Destructuring Assignment, for example `var {mixer,animationAction} = createAnimation();`, can't be handled.

```
$ npm install
$ npm run test

> three@0.89.0 test C:\Users\takahiro\Documents\three.js.test
> npm run build-test && qunit test/unit/three.source.unit.js


> three@0.89.0 build-test C:\Users\takahiro\Documents\three.js.test
> rollup -c test/rollup.unit.config.js

(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
options.entry is now options.input
options.targets is now options.output
output.dest is now output.file

test/three.editor.unit.js → test/unit/three.editor.unit.js...
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
moduleName is now name
(!) Import of non-existent exports
test\unit\editor\Command.tests.js
4: /* global QUnit */
5:
6: import { NothingsIsExportedYet } from '../../../editor/js/Command';
            ^
7:
8: export default QUnit.module( 'Editor', () => {
test\unit\editor\Config.tests.js
4: /* global QUnit */
5:
6: import { NothingsIsExportedYet } from '../../../editor/js/Config';
            ^
7:
8: export default QUnit.module( 'Editor', () => {
test\unit\editor\Editor.tests.js
4: /* global QUnit */
5:
6: import { NothingsIsExportedYet } from '../../../editor/js/Editor';
            ^
7:
8: export default QUnit.module( 'Editor', () => {

...and 61 other files
created test/unit/three.editor.unit.js in 1.1s
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
options.entry is now options.input
options.targets is now options.output
output.dest is now output.file

test/three.example.unit.js → test/unit/three.example.unit.js...
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
moduleName is now name
created test/unit/three.example.unit.js in 3ms
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
options.entry is now options.input
options.targets is now options.output
output.dest is now output.file

test/three.source.unit.js → test/unit/three.source.unit.js...
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
moduleName is now name
created test/unit/three.source.unit.js in 5.6s
TAP version 13
not ok 1 test/unit/three.source.unit.js > Failed to load the test file with error:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at run (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\bin\run.js:71:4)
    at Object.<anonymous> (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\bin\qunit:48:2)
    at Module._compile (module.js:409:26)
  ---
  message: "should be able to load file"
  severity: failed
  actual: false
  expected: true
  stack:     at Object.<anonymous> (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\bin\run.js:78:13)
    at runTest (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\qunit\qunit.js:1478:30)
    at Object.run (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\qunit\qunit.js:1464:6)
    at C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\qunit\qunit.js:1670:12
    at Object.advance (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\qunit\qunit.js:1116:26)
    at begin (C:\Users\takahiro\Documents\three.js.test\node_modules\qunit\qunit\qunit.js:3059:20)
  ...
1..1
# pass 0
# skip 0
# todo 0
# fail 1

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v4.6.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! three@0.89.0 test: `npm run build-test && qunit test/unit/three.source.unit.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the three@0.89.0 test script 'npm run build-test && qunit test/unit/three.source.unit.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the three package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-test && qunit test/unit/three.source.unit.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs three
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls three
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\takahiro\Documents\three.js.test\npm-debug.log
```

Am I missing something?

**Comment by gero3** [comment]
I was using a newer version of node.js which has support for Destructuring Assignment. I was thinking that  rollup would remove those.  I'll make a PR to remove all Destructuring Assignments .

**Pull request merged**
