### PR TITLE
Docs: add ES6/Webpack boilerplate to Getting Started docs

### PR DESCRIPTION
**Pull request by edwinwebb**
I've been working on a three starter project / boilerplate project using Webpack and Three.js for the past few years. I've been using it for my own projects but think it will be useful for anyone wanting to get started with three.js.

https://github.com/edwinwebb/three-seed/

In this PR I've added links to the project and a section in the Getting Started guide.

I hope the project will get some help new developers get started with three.js using modern tools. I have some free time to rework the getting started guides to use this project as a base.

### CODE REVIEW

**Comment by Mugen87** [comment]
I vote for an additional link in the [Useful links](https://threejs.org/docs/index.html#manual/introduction/Useful-links) page. It's the typical place where we refer to external resources and projects. Maybe you can extend the `Tools` section with an entry and link directly to your github repo?

**Comment by looeee** [comment]
Agreed, I think the useful links page is the best place for this.

**Comment by edwinwebb** [comment]
No worries. Understood.

I strongly believe that new three.js developers should be guided towards modern development environments over the current recommendations. I've the time to re-write the getting started guide to use webpack / ES6. Do you think the three.js team and new developers would find this beneficial? 

I will make a new PR with just the link once this PR is closed.

**Comment by donmccurdy** [comment]
The *Import via modules* documentation is intended to describe how to use three.js in modern development environments, such as Webpack, targeted to users who are already comfortable in those environments. I don't think that the *Getting started* guide should advise a particular configuration (e.g. Webpack vs. Browserify), or steer people toward Node.js-based builds if they aren't yet familiar with them.

Your starter pack looks solid, +1 for including with useful links. One bit of feedback would be to include advice on referencing `examples/js/*`, which is a common need. This is currently [a bit tricky with ES6 imports](https://github.com/mrdoob/three.js/issues/9562)...

---

Related — I particularly like the [VueJS guide](https://vuejs.org/v2/guide/), which gives a JSFiddle and CDN link as starting points, and advises against beginning with `vue-cli` unless users are already familiar with Node.js-based tools. Links to our existing JSFiddle boilerplate, or to the CDN files, would be welcome additions IMHO.

**Comment by edwinwebb** [comment]
Thanks for the feedback. I'm sure I can help out with some docs if the three.js team has any needs. In the meantime I will open a new PR with the links and close this.

**Pull request closed without merging**
