### PR TITLE
Fix "Sprite rendering problem in VR mode" 

### PR DESCRIPTION
**Pull request by mamun4122**

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please describe a little bit what changes do you like to introduce?

**Comment by mamun4122** [comment]
This is bug fix for #11726. In VR mode sprite was not showing in correct position. For this In `WebGLSpriteRenderer()`i tried to handle sprite differently for VR mode & normal mode.

**Comment by TarVK** [comment]
I am not sure if this is the proper way of leaving useless feedback, but thanks a lot man, this fix of yours saved my project!

**Comment by florence8627** [comment]
Thanks ! After re-building three.js using the fix. Sprites work perfectly in VR now !

**Pull request closed without merging**
