### PR TITLE
CubeCamera: `NoToneMapping` as default

### PR DESCRIPTION
**Pull request by sunag**
Fix possible use of `ToneMapping` before the final rendering.

### CODE REVIEW

**Comment by donmccurdy** [comment]
I'm not sure we can hard-code THREE.CubeCamera to NoToneMapping ... it can also be used to render a fully-formed image into a .jpg or .png cubemap, for example.

**Comment by sunag** [comment]
>  There's already an exception in THREE.WebGLRenderer to exclude tone mapping when drawing to a render target, perhaps THREE.WebGPURenderer needs that same workaround?

Hmm.. Exclude tone mapping when drawing to a render target is interesting, I liked, we could even add a property like `CubeCamera.toneMapping` as alternative. I was curious to know how I would render with tone mapping once the render target is excluded the tone mapping in render?

**Comment by donmccurdy** [comment]
We can still write a tone-mapped image to a render target by using THREE.OutputPass. Or if you're using the `postprocessing` npm module, it would require ToneMappingEffect. But currently there is no override I'm aware of to cause THREE.WebGLRenderer to write a tone-mapped image to a render target by itself.

**Comment by sunag** [comment]
This PR would not affect this use, since tone-mapping is performed in another render pass, and even if the renderer defined a `toneMapping` it would be ignored, this also explains the fact that it also passed the tests since WebGLRenderer already is ignoring `toneMapping` by default in `CubeCamera`. But I think it's better to actually have a workaround in `WebGPURenderer`, since it would be a general solution. Thanks for the feedback :)

**Pull request closed without merging**
