### PR TITLE
Prevent redefinition of vViewPosition

### LINKED ISSUE #17192: MeshNormalMaterial: Can't use clippingPlanes with flatShading
##### Description of the problem

```
THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog No compiled fragment shader when at least one graphics shader is attached.
THREE.WebGLShader: gl.getShaderInfoLog() vertex
ERROR: 0:109: 'vViewPosition' : redefinition
```

Please also include a live example if possible. You can start from these templates:
https://jsfiddle.net/89q1zs23/

##### Three.js version

- [ ] Dev
- [x] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #17192.

I am not sure if this is the best solution...

Feedback appreciated.

/ping @sunag 
/ping @mrdoob 
/ping @Mugen87

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by sunag** [comment]
@WestLangley `vViewPosition`  not could be every declared like in other materials? https://github.com/mrdoob/three.js/blob/f89180d3df9021121bc1d670f1223ff2166eddc2/src/renderers/shaders/ShaderLib/meshphysical_vert.glsl.js#L4

**Comment by mrdoob** [comment]
Hmm, I want to do some clean up first before going down this path...

**Comment by WestLangley** [comment]
>I want to do some clean up first

@mrdoob OK. Do you want me to close this now?

**Comment by mrdoob** [comment]
We can keep it open for now. This is the kind of clean up I'm trying to do: https://github.com/mrdoob/three.js/commit/8da85fa372bdd7a12cb73c8e56850e24376b1921

**Comment by sunag** [comment]
@mrdoob @WestLangley @bhouston I will publish the PR in some days. Its is a parser of GLSL with optimizer of flow, this is my first bench of the code. The result is quite expressive running the performance nodes example.

`StandardNodeMaterial` starts 3x faster than native material.

image

**Pull request closed without merging**
