### PR TITLE
Crossfade: Moved to BufferGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
Thanks to `BufferGeometryUtils.mergeBufferGeometries` another migration to `BufferGeometry` 😊 .

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawgit.com/Mugen87/three.js/dev4/examples/webgl_postprocessing_crossfade.html

**Comment by WestLangley** [comment]
Unrelated, but setting `color` components to values greater than 1 will have bizarre side effects. Plus, doing so is not valid, as `color` represents the _diffuse reflectance of the material_. This would be OK:
```javascript
color.setRGB( 0, 0, 0.1 + 0.9 * Math.random() );
```

**Comment by Mugen87** [comment]
Added!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
