### PR TITLE
Editor: Added User Data input in GEOMETRY tab

### LINKED ISSUE #28488: Editor: Missing `User Data` input in Geometry tab
### Description

Unlike Object/Material tabs, there's no input for `User Data`, not sure that this is intended or not.

### Reproduction steps

1. Opens https://threejs.org/editor/
2. Adds a Box
3. Select GEOMETRY property tab
4. You should not see User Data input in there

### Code

n/a

### Live example

n/a

### Screenshots

image

### Version

r164

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by ycw**
fix: #28488

Preview: https://raw.githack.com/ycw/three.js/editor-add-userdata-in-geometry-tab/editor/index.html

image

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
I have noticed one unrelated thing while testing: With English language settings a scroll horizontal bar occurs by default now:

image

Shouldn't be the default styles ensure the sidebar is wide enough so no scroll bar occurs when using the English setting?

**Comment by ycw** [comment]
The h scrollbar presents here due to 22px margin-right added to last tab, that margin is used to ensure that the last tab can be fully shown even if sidebar's v scrollbar is triggered:

https://github.com/mrdoob/three.js/assets/1063018/21d2ae5d-a3ba-465b-bb54-4342f398b8e7

**Comment by Mugen87** [comment]
Even then it would be good to hide it by default.

**Comment by ycw** [comment]
done. #28491

**Comment by Mugen87** [comment]
Thanks!

**Pull request merged**
