### PR TITLE
Example shadow / contact fix

### LINKED ISSUE #20848: Example - webgl_shadow_contact artifacts
**Describe the bug**

[The contact shadow example](https://threejs.org/examples/?q=contact#webgl_shadow_contact) from @marcofugaro, when viewed from further away or with increased plane size, starts to flimmer and get distorted shadows.

**To Reproduce**

Basicly just dolly out far enough in the example. 
I made a live example which shows it better.

https://jsfiddle.net/h0jmwvpd/2/

**Expected behavior**

The shadows should stay static. No artifacts, no flimmering.

**Platform:**

 - Device: Desktop
 - OS: Windows, MacOS
 - Browser: Chrome
 - Three.js version: r123

### PR DESCRIPTION
**Pull request by Fluqz**
Related issue: Fixed https://github.com/mrdoob/three.js/issues/20848

**Description**

The current example has a small z-fighting bug, because of multiple planes laying over each other.
`polygonOffset` will fix the issue

### CODE REVIEW

**Comment by gkjohnson** [comment]
Thanks! With `polygonOffset` the vertical offset should no longer be needed:

https://github.com/mrdoob/three.js/pull/20849/files#diff-f6e6eaefcc3ba526fa08c969dcb2456960450a4e12162ce3464e5f7f3007104fR140

**Comment by mrdoob** [comment]
Thanks!

**Comment by marcofugaro** [comment]
Guys I just noticed now the meshes go through the shadow plane, making the `fillPlane` useless. Not even the color input in the gui works.

Any idea how to fix this with `polygonOffset`?

| Current | Original |
|--------|-------------|
| Screenshot 2021-01-11 at 13 45 20 | Screenshot 2021-01-11 at 13 45 47 |

**Comment by gkjohnson** [comment]
> Guys I just noticed now the meshes go through the shadow plane, making the fillPlane useless.

Oh good catch. Just tried it out and what's happening is the shadow plane renders first and renders to depth meaning the fill plane fails the depth test everywhere. If the fill plane weren't transparent this would have worked. I just tried a couple fixes and here's what works:

- Keep the polygon offset and set `renderOrder = 1` on the shadow plane or
- Set `depthWrite = false` on both materials and set `renderOrder = 1` on the shadow plane

**Comment by Mugen87** [comment]
> Set depthWrite = false on both materials and set renderOrder = 1 on the shadow plane

I vote for this solution.

**Pull request merged**
