### PR TITLE
Examples: Fix god rays demo

### PR DESCRIPTION
**Pull request by Mugen87**
This PR ensures that `webgl_postprocessing_godrays` works again. #13480 broke it since the render results of `MeshDepthMaterial` changed.

@WestLangley I'm not sure my fix is the best one. It would be great if you can have a look 👍 

https://threejs.org/examples/webgl_postprocessing_godrays.html
Fixed: https://rawgit.com/Mugen87/three.js/dev3/examples/webgl_postprocessing_godrays.html

### CODE REVIEW

**Comment by Mugen87** [comment]
I've just restored the original depth mask that is later blurred in the shader in order the create the god rays.

**Comment by WestLangley** [comment]
I am not sure... This is an example by @huwb from the early days of three.js.

/ping @huwb

**Review by huwb — APPROVED** [review]
Looks great - nice work

**Comment by huwb** [comment]
Hi sorry for the delay. Thanks for the fixup, It looks great to me.

I'm a bit of a git noob, if there's something i need to do here besides approving the changes to move this forward let me know.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
