### PR TITLE
GLTFExporter: fix znear and zfar range for cameras

### PR DESCRIPTION
**Pull request by fernandojsg**
To pass validation
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#orthographiczfar-white_check_mark

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#orthographicznear-white_check_mark

#13380

### CODE REVIEW

**Comment by takahirox** [comment]
In Three.js, near and far should be

Perspective Camera: Infinity > far > near > 0
OrthographicCamera Camera: Infinity > far > near >= 0

https://threejs.org/docs/#api/cameras/OrthographicCamera.near
https://threejs.org/docs/#api/cameras/OrthographicCamera.far
https://threejs.org/docs/#api/cameras/PerspectiveCamera.near
https://threejs.org/docs/#api/cameras/PerspectiveCamera.far

So ideally we don't need to check in exporter. I think this check should be done in loader, rather than exporter.

@fernandojsg How did you make/load the model which didn't pass the validation?

**Comment by fernandojsg** [comment]
@takahirox even if the valid ranges are as you stated, three.js doesn't have any type of validation when you set these values so it's perfectly fine to add a <0 near plane and things will works as expected. In fact if you look at the examples where the ortho camera is being used, you could find many examples where it has a negative value.
So I'd just keep it to ensure we export valid things even if the original code could be potencially wrong.

**Comment by takahirox** [comment]
I discussed with @mrdoob on Twitter.

https://twitter.com/superhoge/status/966966096141193216

We concluded it's worth to make sure the valid parameters in `GLTFExporter` although we don't do neither parameter validation nor type check in general. Because

- exporter isn't hot code (code that runs every frame), so no performance impact
- hard to fix the invalid gltf files that get spread around
- for Facebook 3D Posts (This has updated our mind!)

from these reasons, feeling like I should more aggressively make sure the valid parameters in the exporter.

**Comment by takahirox** [comment]
BTW

> In fact if you look at the examples where the ortho camera is being used, you could find many examples where it has a negative value.

I think we should fix the examples.

**Pull request merged**
