### PR TITLE
WebXRManager: Decompose cameraVR.matrixWorld

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: https://github.com/google/model-viewer/pull/2464/files#r647866462

### CODE REVIEW

**Comment by elalish** [comment]
Thanks!

**Comment by zalo** [comment]
Looks like this PR causes a bug whenever you move the Camera's parent (because the `cameraVR`'s World Matrix is being decomposed/copied into `camera`'s Local Position/Quaternion/Scale). I encountered this when testing out a VR Locomotion method that relies on moving the rendering camera's parent.

@elalish [I don't fully understand the comment that lead to this](https://github.com/google/model-viewer/pull/2464/files#r647866462); What was wrong with the old method?

**Comment by elalish** [comment]
The WebXR manager was updating most, but not all of the vr camera state; specifically it was missing the decompose, which forced apps to do it themselves separately (and debugging to figure out what was happening was pretty tricky). I haven't thought about the re-parenting aspect; there may well be a better way, but we should not revert to the  old way.

**Comment by zalo** [comment]
That is, it wasn’t setting the xrCamera’s position, rotation, and scale?  (Was there anything wrong with the normal camera’s transform data?)

If the issue was the normal camera, then rather than copying the worldMatrix between the two, would it be acceptable to continue copying only the local matrix (with local pos/rot/scale), but then force the camera to recalculate its world matrix from that and it’s hierarchy?

**Comment by elalish** [comment]
> That is, it wasn’t setting the xrCamera’s position, rotation, and scale? 

Yes, that was the problem.

> If the issue was the normal camera, then rather than copying the worldMatrix between the two, would it be acceptable to continue copying only the local matrix (with local pos/rot/scale), but then force the camera to recalculate its world matrix from that and it’s hierarchy?

Maybe? As long as the two cameras' states are in sync, I think I'll be happy.

**Comment by a-dpq** [comment]
I noticed recently that when I exit immersive mode, the location of the camera changes, and when I enter immersive mode again it goes back to where it should be. Could that be related to this issue?

**Pull request merged**
