### PR TITLE
Fixed for non-HTML documents

### LINKED ISSUE #9026: Doesn't work in non-HTML documents
three.js assumes an HTML document context. I want to run three.js inside an SVG document, where `document.createElement` inherits the SVG namespace.

### PR DESCRIPTION
**Pull request by eligrey**
Fixes #9026.

I fixed your `document.createElement` calls to explicitly specify the HTML namespace. These changes will not affect execution in normal HTML documents for any browsers.

### CODE REVIEW

**Comment by eligrey** [comment]
Actually don't merge this yet. I missed a couple other `createElement` calls in the dev branch. I'll be adding them in a few minutes.

**Comment by mrdoob** [comment]
>  I can replace the `new Image()` call with `document.createElementNS( 'http://www.w3.org/1999/xhtml', 'img' )`.

Yeah, I think we should do that. Just to be consistent.

**Comment by eligrey** [comment]
@mrdoob Done

**Comment by mrdoob** [comment]
Oh sorry, a recent for to ImageLoader is probably causing conflicts. Do you mind pulling from `dev`?

**Comment by eligrey** [comment]
@mrdoob Updated again.

**Comment by mrdoob** [comment]
Sorry!! One last time? I was on the middle of refactoring the WebGLRenderer 😇

**Comment by eligrey** [comment]
Um, I think I messed up while rebasing. Just a few minutes...

**Comment by eligrey** [comment]
@mrdoob Ok done again. Btw, please don't forget to use `document.createElementNS( 'http://www.w3.org/1999/xhtml', '...' );` from here on out, in whatever code you write.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
