### PR TITLE
WebGPU: Fix computation of projection matrices.

### LINKED ISSUE #20276: WebGPURenderer: Unable to render with orthographic camera.
The [WebGPU sandbox](https://raw.githack.com/mrdoob/three.js/dev/examples/webgpu_sandbox.html) uses the following perspective camera setup:
```js
camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 0.1, 10 );
```
The rendered result seems as expected. However if I switch to an orthographic camera like so...
```js
const frustumSize = 10;
const aspect = window.innerWidth / window.innerHeight;

camera = new THREE.OrthographicCamera( 0.5 * frustumSize * aspect / - 2, 0.5 * frustumSize * aspect / 2, frustumSize / 2, frustumSize / - 2, 0, 10 );
```
...nothing is rendered anymore.

As far as I understand, this is caused by the fact that WebGPU has different [coordinate system definitions](https://gpuweb.github.io/gpuweb/#coordinate-systems) than WebGL. So in WebGPU, the `z` coordinate in `NDC` space lies in the range `[0,1]` whereas in WebGL it is `[-1,1]`.

That means the current projection matrices for both perspective and orthographic cameras are not computed correctly in [Matrix4](https://github.com/mrdoob/three.js/blob/56d0b32e01acf2e83b5d9e8d5b69ab67a09bbd0c/src/math/Matrix4.js#L764-L808) in context of `WebGPU`. It seems these formulas are correct: https://metashapes.com/blog/opengl-metal-projection-matrix-problem/

@mrdoob I have no idea so far how to hide this complexity from the user. When creating a camera, the projection matrix is computed right away from the parameters. In order to provide a "correct" matrix, the camera would have to know in which context (WebGL, WebGPU) it is going to be used.

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #20276.

### CODE REVIEW

**Comment by mrdoob** [comment]
Could `WebGPURenderer` have a internal matrix used to premultiply these at render time?

**Comment by Mugen87** [comment]
I thought about this but I'm afraid this approach is too error prone. When projection matrices are recomputed in user-code, they always get incorrect results as long as `WebGPURenderer.render()` has been called. This is a misleading/unexpected behavior I would like to avoid.

TBH, the safest approach would be to modify `Matrix4.makePerspective()` and `Matrix4.makeOrthographic()` since both implementations are wrong in context of WebGPU.

**Comment by mrdoob** [comment]
Doing `Matrix4.prototype.makeOrthographic = function () { console.log( 'bar' ) }` seems to work on a class.

However, if we create the camera before the renderer that wouldn't work...

Forgot to ask.. if we just changed `makeOrthographic` to go from [0,1] I guess a ton of shaders would break, right?

**Comment by Mugen87** [comment]
Yes, the projection matrices are specific for both WebGL and WebGPU. We need different ones depending on what renderer is going to be used.

I've updated the PR and now changed `Matrix4`. Should have not this right from the beginning.

**Comment by Mugen87** [comment]
Okay. Updated the PR.

**Comment by Mugen87** [comment]
Merging for further testing on `dev`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
