### PR TITLE
RGBMLoader: Fix alerts in UPNG.js.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This PR fixes the lgtm.com alerts in `RGBMLoader`. Since these issues came from the `UPNG.js` code, I've reported them at the original repository. The maintainer quickly fixed them (one of them was actually a minor bug). We can now apply the code changes to `RGBMLoader`.

https://github.com/photopea/UPNG.js/issues/71

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Although we should start considering removing it though. I think Safari 15 no longer needs it?

**Comment by Mugen87** [comment]
It seems RGBM is purposely used by developers in favor of other HDR formats (independently on iOS). I'm not sure we should remove it and force users to a migration task. It seems supporting RGBM in the library is not really a huge deal.

**Comment by mrdoob** [comment]
I meant removing UPNG.js

**Comment by Mugen87** [comment]
Oh, okay. Interesting point! I did not have the chance to test it but does iOS 15 still premulitplying alpha on PNG loading?

**Comment by mrdoob** [comment]
Hmm, I remember testing this a few months ago with Safari Technology Preview and seemed like they finally solved it. I have not tried in the release yet.

**Pull request merged**
