### PR TITLE
Examples: remove gpu particle system example

### PR DESCRIPTION
**Pull request by WestLangley**
As suggested by @mrdoob in https://github.com/mrdoob/three.js/pull/16133#issuecomment-488216356.

### CODE REVIEW

**Comment by Mugen87** [comment]
I think the does not mean the entire example, just the code section from the PR.

**Comment by sciecode** [comment]
If that was the case, wouldn't he just have merged the PR?

**Comment by Mugen87** [comment]
I think he just waited on a response of the original developer.

**Review by Mugen87 — CHANGES_REQUESTED** [review]
The example should not be deleted.

**Comment by mrdoob** [comment]
I actually did mean removing it yeah. I do not feel the code is a good starting point for people to hack on. Too much code to assimilate.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@Mugen87 sorry for the time lost porting it to ES6 😕

**Comment by sciecode** [comment]
@mrdoob do you feel like we should get a simpler example to replace this? Or is it not something you plan on keeping as an example?

I could try working on something smaller if that's something you deem necessary.

**Comment by mrdoob** [comment]
I think so yes 🙏

**Comment by Mugen87** [comment]
> sorry for the time lost porting it to ES6

No worries. It were so many of them 😉

**Pull request merged**
