### PR TITLE
Depth texture example: changed to white-nearest

### PR DESCRIPTION
**Pull request by WestLangley**
... plus minor cleanup

Fixes https://github.com/mrdoob/three.js/pull/13480#issuecomment-370159486.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by MichaelJendryke** [comment]
Sorry, but how would I invert 
```
var material =  new THREE.MeshDepthMaterial({
     });
```
so that it shows black-nearest?

**Comment by mrdoob** [comment]
@MichaelJendryke Please, use the [forum](https://discourse.threejs.org/) for help.

**Comment by Iaaan** [comment]
Sorry to dig up this old PR, but looks like this change didn't make it into the r90 -> r91 migration guide. I think it'd be helpful!

**Comment by Mugen87** [comment]
@Iaaan Done: https://github.com/mrdoob/three.js/wiki/Migration-Guide#r90--r91

**Pull request merged**
