### PR TITLE
Tests: webgl_materials_envmaps_exr screenshot.

### PR DESCRIPTION
**Pull request by munrocket**
Don't know what is happening here, this is an update or bug in #19070.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Screen Shot 2020-04-08 at 8 22 59 PM

Hah! I had not seen this for a while... Nice work! 👏👏👏

**Comment by munrocket** [comment]
[shy]

I have done literally nothing.

**Comment by munrocket** [comment]
I needed to create a hotfix instead of new screenshot. Review was not deep enough  (>'o')>

**Comment by sciecode** [comment]
#19070 was indeed a bug, filed a fix for it on #19083. We can revert this.

**Comment by munrocket** [comment]
<('o'<)

**Pull request merged**
