### PR TITLE
Added support for SVG styles attribute in SVGLoader

### PR DESCRIPTION
**Pull request by paulbrzeski**
As discussed in https://github.com/mrdoob/three.js/issues/13478

### CODE REVIEW

**Comment by mrdoob** [comment]
Could you attach in this section a svg that uses this?

**Comment by paulbrzeski** [comment]
@mrdoob Can't attach an SVG but here's a .txt copy of it :)
[shapes.txt](https://github.com/mrdoob/three.js/files/1888392/shapes.txt)

**Comment by mrdoob** [comment]
Thanks!

Hmm, I think the current code in the `dev` branch already displays this file correctly?

I've dragging the file to https://rawgit.com/mrdoob/three.js/dev/editor/

And I'm getting this:

screen shot 2018-04-12 at 12 05 04 pm

**Comment by ndebeiss** [comment]
Actually lots of the SVG tags can have that style attributes with comma separated properties, maybe it would be better inside `function parseNode( node, style )`
And it should manage inheritance (stacking the style properties ?). A color defined on a g tag is propagated to children nodes (like in the example https://rawgit.com/mrdoob/three.js/dev/examples/models/svg/tiger.svg).

I would add that the DOMParser() already parses the style content. I just looked at Chrome but it gives following property `node.style.length ` and you can then browse the properties with node.style[0...].

It requires a bit more work :sweat_smile: . If you want and if I can find time I will try to address that.

**Comment by mrdoob** [comment]
I'm sorry, I do not understand what you're trying to say. Do you have a file that doesn't load correctly?

**Comment by ndebeiss** [comment]
No it is not an issue, just that I can suggest another pull request. The comments I do here are :
- style properties can be retrieved under Chrome, without needing that manual parsing, I will check on other browsers what is available.
- style properties can be defined on almost all SVG tags, so we could add that reading in another method
- style properties inherit from the ancestor tags, it might be even better to let those properties inside the DOM and implement their reading from the stack of ancestors.

**Comment by mrdoob** [comment]
@ndebeiss I see I see. To avoid over-engineering I prefer to go case by case with sample files.

**Comment by mrdoob** [comment]
Closing this PR as it seems it is no longer needed.

**Comment by paulbrzeski** [comment]
@mrdoob Sorry I haven't had time to explain what this was for :P 

In my specific use case, I'm using [Fabric.JS](http://fabricjs.com/) to manage the SVG assets on an interactive canvas. I'm not sure why but the colours from Fabric.JS SVG output didn't render correctly using the dev branch SVGLoader but that's what my changes were for. 
error

**Comment by mrdoob** [comment]
> I'm not sure why but the colours from Fabric.JS SVG output didn't render correctly using the dev branch SVGLoader so that's what my changes were for.

Do the colours render correctly now?

**Comment by paulbrzeski** [comment]
@mrdoob Nah, the screenshot above is using latest SVGLoader. I revised the check at [line 484](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/SVGLoader.js#L484) to "if ( node.style && node.style.fill !== '' )" and that passed the error from my screenshot.

The fill colour according to SVGLoader is always going to be black though.. according to this - https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/SVGLoader.js#L517

**Comment by mrdoob** [comment]
I remain confused... Do you have a svg file that doesn't display correctly with the current `SVGLoader`? If so, can you share it?

**Comment by paulbrzeski** [comment]
@mrdoob The SVG file I already posted is an example however it doesn't occur in the Editor example, possibly due to loading the file first via SVGLoader.load(). 

I'm using SVGLoader as a parser not a loader. The SVG "documents" are created on the fly in code. When I push the file I posted here as a string, I get exceptions as per my screenshots and the colours don't appear. If that string is saved, it works fine via SVGLoader.load but that's not how I'm using it.

I actually wasn't sure how to respond because I thought I might need to post multiple screenshots of the debug demonstating the issue I had :P

**Comment by ndebeiss** [comment]
I tried your example :
https://rawgit.com/ndebeiss/three.js/dev/examples/svg_load_and_render.html
and the colours are well rendered whereas I also read the SVG as a string with code:

```javascript
var loader = new THREE.SVGLoader();
var paths = loader.parse( document.getElementById('example').innerHTML);
```

the error you have is that node.style has not been parsed by DOMParser because it does not know it is SVG, and that is why you need to add that manual parsing of style attribute. I think that is because you read the string differently ?
Are you using the following code ?

```javascript
var xml = new DOMParser().parseFromString( text, 'image/svg+xml' );
```

**Comment by paulbrzeski** [comment]
@ndebeiss 
Ahhh! Cheers for that :) Looks like I was missing the wrapping elements :P I just had the SVG elements and was trying to parse them. 

I'll refactor to use DOMParser and hopefully that should mean I'm sorted without changing SVGLoader :)

Sorry for the run around guys!

**Pull request closed without merging**
