### PR TITLE
OutlinePass: Added support for orthographic cameras

### PR DESCRIPTION
**Pull request by Mugen87**
Solves #13274

The PR also fixed the warning `WARNING: Output of vertex shader 'vUv' not read by fragment shader`

### CODE REVIEW

**Comment by Mugen87** [comment]
Demo1 (perspective camera): http://rawgit.com/Mugen87/three.js/dev8/examples/webgl_postprocessing_outline.html

Demo2 (orthographic camera): https://jsfiddle.net/9a3c8o5a/8/

**Comment by WestLangley** [comment]
Hmm. I expected you to inject code like so:
```javascript
function foo( camera ) {

	var str = ( camera.isPerspectiveCamera ) ? 'perspective' : 'orthographic';

	return 	'				float viewZ = - ' + str + 'DepthToViewZ( depth, cameraNearFar.x, cameraNearFar.y );'

}
```
This is how it is done elsewhere in `WebGLProgram`. There is no need to use a define.

**Comment by Mugen87** [comment]
I've updated the code and the examples. How do you like this approach?

https://jsfiddle.net/9a3c8o5a/9/

**Comment by WestLangley** [comment]
I think that is an improvement. :)

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
