### PR TITLE
CameraHelper: Fix copy()/clone()

### LINKED ISSUE #13565: CameraHelper: .clone() is broken
##### Description of the problem

`CameraHelper::constructor` expects a `Camera` argument, but since `CameraHelper::clone` is not overwritten it will forward to `LineSegments::constructor` which expects a geometry and a material.

As a result `cameraHelper.camera` won't be set and `cameraHelper.clone()` throws via `.update()` (see https://jsfiddle.net/bbnk59af/).

Overwriting `CameraHelper::clone` to account for its own constructor solves the issue (see https://jsfiddle.net/bbnk59af/1/):

```
THREE.CameraHelper.prototype.clone = function () {
	var clone = new this.constructor(this.camera).copy(this);
	return clone;
}

```

I am not sure what the intended behaviour is in the case that `cameraHelper.clone()` gets called as a child of `scene.clone()`. The cameras and their helpers would be cloned individually, but the cloned helpers would point to the original cameras instead of the cloned ones.

##### Three.js version

- [X] Dev
- [X] r90

##### Browser

- [x] All of them

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #13565

The idea is to allow `CameraHelper` to be created without parameters (like `GridHelper`). In this way, it's possible to implement `clone()` in this fashion:

```js
return new this.constructor().copy( this );
```
which is the ideal implementation of a clone method.

BTW: `pointMap` is actually unique for all helpers so a copy of this property is not necessary.

### CODE REVIEW

**Comment by WestLangley** [comment]
>The idea is to allow CameraHelper to be created without parameters (like GridHelper).

Instantiating a `CameraHelper` without a camera does not seem to me to be a good idea because it can't be rendered without a camera.

Also, why does a user need to clone a camera helper?

Similarly for the other renderable helpers that depend on another object.

Related: #16078.

**Comment by Mugen87** [comment]
> Instantiating a CameraHelper without a camera does not seem to me to be a good idea because it can't be rendered without a camera.

That's true. I've only added this possibility in order to implement the `clone()` as posted above.

**Comment by WestLangley** [comment]
>Instantiating a CameraHelper without a camera does not seem to me to be a good idea because it can't be rendered without a camera.
>>That's true. I've only added this possibility in order to implement the clone() as posted above.

I understand. It is the cloning that is the problem with our design. I am trying to see if we can maybe fix our design.

**Comment by Mugen87** [comment]
> Also, why does a user need to clone a camera helper?

Yes, the reasonableness of this is questionable. TBH, I'm doing this PR for technical reasons. So the methods are present and produce an understandable result.

But yeah,  there are scenarios where the clone does not work as expected. For example if you clone an entire scene, a clone of `CameraHelper` would still refer to the "old" camera of the source scene. Not to the new one.

**Comment by Mugen87** [comment]
> I am trying to see if we can maybe fix our design.

Closing for now then.

**Pull request closed without merging**
