### PR TITLE
Vector2|3|4: Use `Math.trunc()` in `roundToZero()`.

### PR DESCRIPTION
**Pull request by ycw**
`Math.trunc`  is much [faster than current impl](https://jsperf.app/fiwuti/1/preview)

### CODE REVIEW

**Comment by WestLangley** [comment]
>Math.trunc is much [faster than current impl](https://jsperf.app/fiwuti/1/preview)

FWIW, in my testing on Safari/FF MacOS -- it's marginally _slower_.

**Comment by ycw** [comment]
@WestLangley chrome116 on win11

**Comment by WestLangley** [comment]
Always test on a variety of OS/Browsers before making performance claims.

Just as in this case, results can be surprising. :-)

**Comment by Mugen87** [comment]
Tested on a macMini with M2 Pro:

image

image

image

Overall, `Math.trunc()` seems the better solution than what is implemented now. And it is more readable than the bitwise operation.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Let's give this a try!

**Comment by manthrax** [comment]
Wow.. blows my mind that Math.***( x ) is faster than an x | 0...

**Pull request merged**
