### PR TITLE
Persp/Orhto Camera: Added .set() methods.

### PR DESCRIPTION
**Pull request by Mugen87**
see #15043

@mrdoob I've honored all properties in `set()` for consistency reasons (because the math classes also do so). Do you think certain parameters are unnecessary?

### CODE REVIEW

**Comment by WestLangley** [comment]
I think `updateProjectionMatrix()` should either be the responsibility of the user or of the library -- but not sometimes one and sometimes the other. Pick one API and be consistent.

**Comment by WestLangley** [comment]
Also, are you saying that in the [examples](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_camera.html#L184-L188):
```js
cameraOrtho.left = - 0.5 * frustumSize * aspect / 2;
cameraOrtho.right = 0.5 * frustumSize * aspect / 2;
cameraOrtho.top = frustumSize / 2;
cameraOrtho.bottom = - frustumSize / 2;
cameraOrtho.updateProjectionMatrix();
```
would be replaced by:
```js
cameraOrtho.set( left, right, top, bottom,
    cameraOrtho.near, cameraOrtho.far, cameraOrtho.zoom, cameraOrtho.view );
```
I think that would be awkward.

**Comment by Mugen87** [comment]
>I think updateProjectionMatrix() should either be the responsibility of the user or of the library -- but not sometimes one and sometimes the other. 

Then you have to remove the method call from the constructor and methods like `setFocalLength()`, `setViewOffset()` etc. I don't think this is a good idea. Besides, methods like `Object3D.updateMatrix()` or `Object3D.updateMatrixWorld()` are also used by library and user code. So what?

I don't want to adjust the examples. As @mrdoob pointed out here https://github.com/mrdoob/three.js/pull/15043#issuecomment-539535702, he likes the methods. The question for me is just how should signature look like.

**Comment by mrdoob** [comment]
> I think that would be awkward.

Indeed...

Is this less awkward?

```js
	set: function ( left, right, top, bottom, near, far, zoom, view ) {

		if ( left !== undefined ) this.left = left;
		if ( right !== undefined ) this.right = right;
		if ( top !== undefined ) this.top = top;
		if ( bottom !== undefined ) this.bottom = bottom;

		if ( near !== undefined ) this.near = near;
		if ( far !== undefined ) this.far = far;

		if ( zoom !== undefined ) this.zoom = zoom;
		if ( view !== undefined ) this.view = view;

		this.updateProjectionMatrix();

		return this;

	},
```

**Comment by WestLangley** [comment]
>I think that would be awkward.
>>Indeed...
>>>Is this less awkward?

I think that is confusing: if unspecified, `zoom` will retain whatever value it was previously.

I really don't think this method is necessary, anyway.

**Comment by Mugen87** [comment]
> if unspecified, zoom will retain whatever value it was previously.

Isn't this the expected behavior? IMHO, I don't think this is confusing...

**Comment by EliasHasle** [comment]
I tend to always forget, and have to check, the order of constructor parameters for the cameras, and whenever I have to modify a camera after creation, I find the property assignment approach more readable and writable. `Object.assign` is a good friend.

I hope that the `set` methods will not be the first choice for most applications. I do understand the desire for API consistency between classes, though.

**Comment by Mugen87** [comment]
Let's close this. We normally expect that `set()` is called with all parameters. It would be indeed inconsistent if `.set()` methods of camera classes behave differently than the math ones.

**Comment by EliasHasle** [comment]
Hm, isn't that what `set()` does in this PR. Or do you mean that all parameters are required? In that case, `THREE.Euler` is a counterexample, where `order` is optional:

https://github.com/mrdoob/three.js/blob/22ed6755399fa180ede84bf18ff6cea0ad66f6c0/src/math/Euler.js#L104

**Comment by Mugen87** [comment]
> Or do you mean that all parameters are required?

That one.

> THREE.Euler is a counterexample, where order is optional

This class seems to be an exception.

**Pull request closed without merging**
