### PR TITLE
RoughnessMipmapper: clean up formatting

### PR DESCRIPTION
**Pull request by WestLangley**
`RoughnessMipmapper` may not be working correctly, but it is not a result of this PR, which is clean up only.

### CODE REVIEW

**Comment by mrdoob** [comment]
Yeah, @elalish is looking into it.

**Comment by mrdoob** [comment]
Thanks!

**Comment by XmmmmmmY** [comment]
import { RoughnessMipmapper } from 'three/examples/jsm/utils/RoughnessMipmapper.js';
Does the file exist?

**Comment by WestLangley** [comment]
@XmmmmmmY `RoughnessMipmapper` has been [removed](https://github.com/mrdoob/three.js/pull/23143).

**Pull request merged**
