### PR TITLE
Kkruups dev1

### PR DESCRIPTION
**Pull request by kkruups**
As per @mrdoob, attempted to make change directly.
However, direct edit resulted in having to create new PR, since no direct edit rights.

BR/KK

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like it's already fixed in https://github.com/creationix/msgpack-js-browser/blob/master/msgpack.js. I'll pull after merging this.

**Comment by mrdoob** [comment]
Thanks!

**Comment by kkruups** [comment]
Yes, I had submitted PR fix to @creationix  as well.


BR/Kk

**Comment by kkruups** [comment]
Thanks! :)

**Comment by mrdoob** [comment]
I see I see! Double thanks!

**Pull request merged**
