### PR TITLE
CameraControls

### PR DESCRIPTION
**Pull request by WilliamLiu-1997**
Related issue: #CameraControls

**Description**
This set of controls performs turning, moving(zooming on OrthographicCamera), and panning.
Pan up/down/left/right - middle mouse / touch: one finger move
Move forward/backward - mousewheel / touch: two finger spread or squish
Turn - right mouse, or arrow keys / touch: three finger swipe

The CameraControls is updated from OrbitControls.
Updates compared to OrbitControls:
1. The dollying of PerspectiveCamera is replaced with panning forward and backward. The controlling will be more free as there will no limit by mindistance.
2. The turning will be conducted using the position of PerspectiveCamera as the center.

This contribution is funded by [William](https://github.com/WilliamLiu-1997/CameraControls).

### CODE REVIEW

**Comment by WestLangley** [comment]
Thank you for your PR.

I think it is correct to say that the Controls in this PR is modeling a movie camera at a fixed elevation.

It can dolly forward/backward and pan left/right.

Rotation is centered on the camera itself.

**Comment by WilliamLiu-1997** [comment]
> Thank you for your PR.
> 
> I think it is correct to say that the Controls in this PR is modeling a movie camera at a fixed elevation.
> 
> It can dolly forward/backward and pan left/right.
> 
> Rotation is centered on the camera itself.

Thanks so much for your comment! I have updated its description. By the way, it can also pan up/down.
By clicking right buttom and moving your mouse you can pan left/right/up/down.
By scrolling the mouse wheel you can dolly forward/backward.
By clicking the middle buttom and moving your mouse you can rotate the camera.

**Comment by WestLangley** [comment]
>By clicking the middle buttom

**Comment by WestLangley** [comment]
OK, I corrected my comment to prevent confusion. Can it look up/down -- or only horizontally?

Also, FYI, macs do not have a middle mouse button.

**Comment by WilliamLiu-1997** [comment]
> OK, I corrected my comment to prevent confusion. Can it look up/down -- or only horizontally?
> 
> Also, FYI, macs do not have a middle mouse button.

Yeah, it can look up/down/left/right

Thanks. I will assign the rotation to the left mouse button by default.
You can also reassign them like orbitcontrols

**Comment by WilliamLiu-1997** [comment]
Here is an example of the CameraControls
[https://rawcdn.githack.com/WilliamLiu-1997/three.js/8879424c1bca23c6f60651a6f6c1713f041a3327/examples/misc_controls_cameracontrols.html](url)

**Comment by WilliamLiu-1997** [comment]
Here is an example of CameraControls
https://rawcdn.githack.com/WilliamLiu-1997/three.js/8879424c1bca23c6f60651a6f6c1713f041a3327/examples/misc_controls_cameracontrols.html

**Comment by WestLangley** [comment]
When a movie camera moves forward, it does not sink into the ground just because it is looking down.

Also, I think your left-right/up-down rotation motion is backwards. Usually, the touch point should remain generally under the mouse.

Finally, I do not decide what features are merged. I am only trying to help clarify for others what this PR has to offer.

**Comment by WilliamLiu-1997** [comment]
> When a movie camera moves forward, it does not sink into the ground just because it is looking down.
> 
> Also, I think your left-right/up-down rotation motion is backwards. Usually, the touch point should remain generally under the mouse.
> 
> Finally, I do not decide what features are merged. I am only trying to help clarify for others what this PR has to offer.

Thanks for your explain. I have no idea about movie camera before. So this shouldn't be a movie camera. In the orbitcontrols, we can rotate, dolly in/out, pan left/right/(up/down **or** horizontal forward/backward according to attribute screenSpacePanning). When I am doing a project using three.js, I found it is inconvenient that I can only move the camera to 4 directions out of 6. That is why I made this.

That is my personal habit. Anyway, I have converted it, and added a new attribute "invertRotate" to control the direction of rotation.

No worries, and thanks so much for your advice.

Example: https://rawcdn.githack.com/WilliamLiu-1997/three.js/bf39b22c640ad4d28584e8aa6ed6c0bcb7a2bf67/examples/misc_controls_cameracontrols.html

**Comment by WestLangley** [comment]
@WilliamLiu-1997 I am not sure what your plan is, but others have [shared](https://github.com/yomotsu/camera-controls) their Controls on GitHub. Maybe you would like to do the same.

**Comment by mrdoob** [comment]
Kind of looks like CCTV camera 😁

By the way, it's "sensitivity" and not "sensibility".

**Pull request closed without merging**
