### PR TITLE
Docs: format the matrices

### LINKED ISSUE #26812: Update documentation to use MathML
### Description

The current implementation of the documentation is somewhat inconsistent with math notation. A few examples:

1. Matrices currently vary between having and not having commas to separate elements:
a. (without commas) https://threejs.org/docs/#api/en/math/Matrix4.makeRotationFromQuaternion
image
b. (with commas) https://threejs.org/docs/#api/en/math/Matrix4.makeBasis
image

2. Some pages are inconsistent even within the same example:
a. https://threejs.org/docs/#api/ar/math/Matrix4.makeBasis utilizes both [Arabic commas](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode) and regular commas.
image

3. Alignment inconsistencies:
a. (center aligned) https://threejs.org/docs/#api/en/math/Matrix4.makeBasis
image
b. (left-ish aligned): https://threejs.org/docs/#api/en/math/Matrix4.makeRotationZ
image

4. Some sections do not have the correct formatting:
a. https://threejs.org/docs/#api/en/math/Matrix4.makeRotationY
image

### Solution

I propose that we replace the math markup throughout the documentation with MathML, which is accepted by all major browsers (according to [mdn](https://developer.mozilla.org/en-US/docs/Web/MathML#browser_compatibility) and [caniuse](https://caniuse.com/mathml)).

### Alternatives

The alternative would be to format the `<code>` sections in the documentation more carefully, but I'm not so sure that this is a superior alternative.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ycw**
fix: #26812

This PR attempts to format the matrices in docs by using simple html/css

preview: http://raw.githack.com/ycw/three.js/mat-html/docs/index.html#api/en/math/Matrix4.extractBasis

mat_preview

<details>
<summary>usage</summary> 

```html
<!-- matrix 4x4 -->
<span class="matrix mat4">
  <i>1</i><i>0</i><i>0</i><i>0</i>
  <i>0</i><i>1</i><i>0</i><i>0</i>
  <i>0</i><i>0</i><i>1</i><i>0</i>
  <i>0</i><i>0</i><i>0</i><i>1</i>
</span>

<!-- matrix 3x3 -->
<span class="matrix mat3">
  <i>1</i><i>0</i><i>0</i>
  <i>0</i><i>1</i><i>0</i>
  <i>0</i><i>0</i><i>1</i>
</span>

<!-- matrix 3x1 -->
<span class="matrix mat3x1">
  <i>x</i>
  <i>y</i>
  <i>z</i>
</span>
```

</details>

<details>
  <summary>example</summary>

```html
<!-- children can be any inline elements like i, b, u, s, span, mark etc... -->
<span class="matrix mat4">
  <i>a</i><i>b</i><i>c</i><b>v.x</b>
  <i>e</i><i>f</i><i>g</i><b>v.y</b>
  <i>i</i><i>j</i><i>k</i><b>v.z</b>
  <i>m</i><i>n</i><i>o</i><i>p</i>
</span>
```

mat_bold

</details>

### CODE REVIEW

**Comment by Mugen87** [comment]
The new formatting looks great but this isn't MathML, right? 

If so, it would be nice to see the same doc page updated with MathML so we can easier compare both approaches.

**Comment by Mugen87** [comment]
This how a 4x4 matrix definition with MathML would look like. Just markup, no CSS:

https://jsfiddle.net/71w6yovn/

I personally would prefer MathML over a custom styled solution via CSS. Simply because MathML is intended for exact this purpose and I see no reason to build something custom next to it.

**Comment by ycw** [comment]
agree.. as long as the `<math>` has wider USER adoption, not browser compat. :D

**Comment by Mugen87** [comment]
How does this version of the fiddle look on your Android device? 

https://jsfiddle.net/6bvydfnL/5/

It seems what we see on Android is a font issue. A solution for this is to include `MathJax`. It would be an additional dependency but at least we could use MathML to write math syntax. `MathJax` could be removed when the font issue has been resolved over the time.

**Comment by Mugen87** [comment]
Looking at the HTML source code though, `MathJax` creates custom HTML and CSS so it wouldn't be so optimal for search engines anymore. So one of the major benefits of using MathML would be lost.

**Comment by Mugen87** [comment]
It seems the font stretching issues have been reported to the Chromium bug tracker. So there is hope this gets eventually fixed.

https://bugs.chromium.org/p/chromium/issues/list?q=mathml&can=2

**Comment by ycw** [comment]
https://jsfiddle.net/71w6yovn/



https://jsfiddle.net/6bvydfnL/5/show

**Comment by Mugen87** [comment]
After some more testing of MathML it seems the formatting is not as consistent as originally expected. Even Firefox on macOS does not render the brackets in the correct size. If we agree on using MathML, we have to be aware that style issues are inevitable.

BTW: I've realized now that most of the discussion in this PR should have happened in https://github.com/mrdoob/three.js/issues/26812.

**Comment by Mugen87** [comment]
> Even Firefox on macOS does not render the brackets in the correct size.

After upgrading to macOS 14.0 and Firefox 118, this isn't true anymore. Brackets have now the correct size.

**Pull request closed without merging**
