### PR TITLE
New example: EarthControls

### PR DESCRIPTION
**Pull request by clement-igonet**
I've just coded an example similar to examples/misc_controls_orbit.html
The goal is to show a convenient way to navigate around a planet (earth), as I did in my own OpenEarthView project.
[EarthControls.zip](https://github.com/mrdoob/three.js/files/1444509/EarthControls.zip)

### CODE REVIEW

**Comment by looeee** [comment]
You have added a lot of unrelated files here - if you do a `git pull upstream dev` it should fix most of them. It's best not to track all files - i.e. don't do `git add .` to avoid this in future. Just track the files you need - `git add ./examples/js/controls/EarthControls.js`

Going over the files in your zip, your earth controls are basically a copy of OrbitControls with the static Y-UP from #12564 implemented and a couple of other things related to earth size added. I would prefer to just add the option to preserver Y-UP to the current controls as suggested in that PR. 

On the other hand though, the question of how to create a basic scene with a planet and a camera that rotates around it is a very common one and is used in many tutorials. I think it would be a good idea to change the  [misc_controls_orbit](https://threejs.org/examples/?q=orbit#misc_controls_orbit) to show a planet rather than the current (ugly) cloud of triangles.

**Comment by clement-igonet** [comment]
Hi Lewy,

   Thank you for your reply.
   I do not understand what you say about "git add ." That is not the way I use git.

   I agree with the idea of adapting OrbitControls for planet navigation. However, what I did to have nice rotation around the sphere is a little tricky: I make rotate the sphere around its center rather than moving the camera around the planet. I do not know if it is acceptable, but it simplify a lot all process when going further with all other features (tiles, building position, ground elevation, etc...).

   So, I can suggest you an OrbitControls modification, but I think it will complexify existing code.

   Mrdood, an advice?

Clement.

On 6 November 2017 02:50:50 CET, Lewy Blue <notifications@github.com> wrote:
>You have added a lot of unrelated files here - if you do a `git pull
>upstream dev` it should fix most of them. It's best not to track all
>files - i.e. don't do `git add .` to avoid this in future. Just track
>the files you need - `git add ./examples/js/controls/EarthControls.js`
>
>Going over the files in your zip, your earth controls are basically a
>copy of OrbitControls with the static Y-UP from #12564 implemented and
>a couple of other things related to earth size added. I would prefer to
>just add the option to preserver Y-UP to the current controls as
>suggested in that PR. 
>
>On the other hand though, the question of how to create a basic scene
>with a planet and a camera that rotates around it is a very common one
>and is used in many tutorials. I think it would be a good idea to
>change the 
>[misc_controls_orbit](https://threejs.org/examples/?q=orbit#misc_controls_orbit)
>to show a planet rather than the current (ugly) cloud of triangles. 
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrdoob/three.js/pull/12586#issuecomment-342025978

-- 
Sent from my mobile. It explains my brevity.

**Comment by Mugen87** [comment]
Closing since the PR is not setup correctly.

@clement-igonet Please have a look at this wiki article in order to create a proper PR: [How to contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js)

**Comment by mrdoob** [comment]
Weird controls...

Left-click and drag rotates the earth and right-click and drag rotates the camera.

Right?

**Comment by clement-igonet** [comment]
Right!

On 9 November 2017 01:04:27 CET, "Mr.doob" <notifications@github.com> wrote:
>Weird controls...
>
>Left-click and drag rotates the earth and right-click and drag rotates
>the camera.
>
>Right?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrdoob/three.js/pull/12586#issuecomment-343003119

-- 
Sent from my mobile. It explains my brevity.

**Pull request closed without merging**
