### PR TITLE
GLTFLoader: Remove spec/gloss examples generated by COLLADA2GLTF.

### PR DESCRIPTION
**Pull request by donmccurdy**
COLLADA2GLTF is not generating spec/gloss materials correctly, the output is too glossy. This PR removes the spec/gloss examples, excluding two:

1. Boombox (created with glTF Tools for Unity)
2. Duck (created with COLLADA2GLTF, but doesn't display the issue)

Details: https://github.com/KhronosGroup/glTF-Sample-Models/issues/151

### CODE REVIEW

**Comment by takahirox** [comment]
Oh, I didn't know it's an issue. I thought "more glossiness" were from the minor difference of the spec between metalic/roughness and spec/gloss without deep thinking.

**Review by takahirox — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
Off topic: Do you think we still need RiggedSimple model? I think it's ok to remove it because we already have some other skinning models (monster and cesium man) in examples. If you agree, I'll make PR.

**Comment by donmccurdy** [comment]
I'd be OK with removing that, yes. 👍

**Pull request merged**
