### PR TITLE
Optimized version of LTC Area lights

### PR DESCRIPTION
**Pull request by spidersharma03**
I have made some optimizations in LTC Area lights, which are taken from::
http://advances.realtimerendering.com/s2016/s2016_ltc_rnd.pdf
Thanks to Stephen Hill, with whom I exchanged some emails.

I did some performance bench marks. Some results are here::
https://docs.google.com/document/d/1369HGo5uDbwtHe8fahTPMKPe7Pe_MjIOg1exEkyj8UY/edit?usp=sharing

@bhouston , @abelnation

### CODE REVIEW

**Comment by bhouston** [comment]
Live demos with the optimization: 

https://rawgit.com/spidersharma03/three.js/AreaLight_Optimized/examples/webgl_lights_rectarealight.html
https://rawgit.com/spidersharma03/three.js/AreaLight_Optimized/examples/webgl_lights_arealight.html

Versus the current implementation:

https://rawgit.com/mrdoob/three.js/dev/examples/webgl_lights_rectarealight.html
https://rawgit.com/mrdoob/three.js/dev/examples/webgl_lights_arealight.html

**Comment by abelnation** [comment]
This is incredible!  Amazing work!

**Comment by WestLangley** [comment]
I agree, we should use this approximation -- and remove the slower polygon-clipping code, which is no longer used. However, to say that this is an "optimization" is misleading.

If you solve a problem more efficiently, that is an optimization. If you solve a different problem more efficiently, that is an approximation.

You are approximating the form factor of a horizon-clipped polygon with (an approximation of) the form factor of a horizon-clipped sphere.

**Comment by bhouston** [comment]
> You are approximating the form factor of a horizon-clipped polygon with (an approximation of) the form factor of a horizon-clipped sphere.

That is very true.  When I switch between the two demos before and after this PR, I can not see any differences, so it is a pretty good approximation. :)

**Comment by mrdoob** [comment]
Nice nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> and remove the slower polygon-clipping code

@spidersharma03 would you like to do another PR removing the unused code?

**Comment by spidersharma03** [comment]
> I agree, we should use this approximation -- and remove the slower polygon-clipping code, which is no longer used. However, to say that this is an "optimization" is misleading.

I Agree :-)

> @spidersharma03 would you like to do another PR removing the unused code?

Yes, I will do that.

Meanwhile, I also plan to use a LUT  to better approximate the sphere form factor, instead of the current approximation as noted in the paper( But that, in a separate PR). Stephen Hill said that he is still evaluating the options and wanted to keep them open for specific needs in terms of speed/accuracy.

I have one more question here regarding other area light shapes. So, I have implemented some other shapes like Sphere, Disk and Tube( mainly Frostbite implementation), and have a single AreaLight class( I am using RectAreaLight only, but we could change its name to AreaLight) but with a shapeType option to select a particular shape. Based upon the shapeType, inside the shader I am switching between the specific shape functions. thoughts?

here is a screenshot of other shapes::
image

**Pull request merged**
