### PR TITLE
Added Oculus Go controller model

### PR DESCRIPTION
**Pull request by kosso**
Added OBJ and MTL files for an Oculus Go controller which I created on tinkercad.

Duplicated the GearVR example and edited for the Oculus Go.

### CODE REVIEW

**Comment by mrdoob** [comment]
Look good! Do you mind removing the last commit though?

**Comment by kosso** [comment]
Should I do the request again? 
(I was trying to work out why the build failed the tests).

**Comment by kosso** [comment]
Closing this one and will resubmit PR.

**Comment by mrdoob** [comment]
> (I was trying to work out why the build failed the tests).

Sorry about that. Seems like @lgtmhq is having some issues after we removed all python code.

**Pull request closed without merging**
