### PR TITLE
Examples: Update or remove some InstancedBufferGeometry examples

### PR DESCRIPTION
**Pull request by donmccurdy**
~~The good news: It's 60 LOC shorter.
The bad news: I'm not sure this really demonstrates anything that `instancing / suzanne` doesn't already show. See https://github.com/mrdoob/three.js/issues/17056#issuecomment-559913402.~~

Updated with suggestions from https://github.com/mrdoob/three.js/issues/17056#issuecomment-559913402. This PR now:

- removes `instancing2`
- removes `buffergeometry / instancing / dynamic`
- updates `buffergeometry / instancing / interleaved / dynamic` to use InstancedMesh and interleaved InstancedBufferGeometry.

Demo: https://raw.githack.com/mrdoob/three.js/9ae6a5a92fe0107dab5f560d552c8b90b5b3bdc4/examples/?q=instanc#webgl_buffergeometry_instancing_interleaved

### CODE REVIEW

**Comment by Mugen87** [comment]
http://raw.githack.com/donmccurdy/three.js/examples-buffergeometry-instancedmesh/examples/webgl_buffergeometry_instancing_dynamic.html

**Comment by mrdoob** [comment]
I think I vote for removing it.

**Comment by donmccurdy** [comment]
Updated PR based on https://github.com/mrdoob/three.js/issues/17056#issuecomment-559913402 ✅

**Comment by Mugen87** [comment]
It seems you're using now an instance of `InstancedBufferGeometry` to create an instance of `InstancedMesh`. I don't think we want to promote this kind of usage.

**Comment by donmccurdy** [comment]
It's an oversight here, and I'm happy to change it, but — why wouldn't we want to promote that usage? I do think it's important that InstancedMesh be compatible with instanced attributes, and unless we plan to create a different API for that, InstancedMesh and InstancedBufferGeometry will need to be kept compatible with one another.

For example, users of ShaderMaterial or NodeMaterial will want to be able to use custom per-instance attributes with InstancedMesh.

**Comment by Mugen87** [comment]
Um, maybe I'm looking too strict on this topic. I'm curious what @mrdoob thinks about this^^

**Comment by donmccurdy** [comment]
Here's a more practical example where InstancedMesh and InstancedBufferGeometry complement one another: https://github.com/mrdoob/three.js/pull/18039.

**Comment by mrdoob** [comment]
> Um, maybe I'm looking too strict on this topic. I'm curious what @mrdoob thinks about this^^

I'm open minded about it for now 🧐

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
