### PR TITLE
Examples: Remove obsolete code in webxr_vr_video.

### PR DESCRIPTION
**Pull request by Mugen87**
Is there a special reason for using `NearestFilter` for the video texture?

### CODE REVIEW

**Comment by mrdoob** [comment]
Maybe at the time it was performance. But I think we can remove that now.

**Comment by Mugen87** [comment]
Okay, done!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
BTW: I don't 100% understand the usage of two sphere meshes in this example (at least I was not able to properly explain it in a [forum topic](https://discourse.threejs.org/t/intersectobjects-doesnt-work-in-vr-mode/20129/9)^^).

Couldn't the example just use a single sphere and avoid any layer configurations?

**Comment by mrdoob** [comment]
The video has two views side by side, one for each eye: https://threejs.org/examples/textures/MaryOculus.webm

What the example does is to create two spheres and modify that uvs so each sphere renders a different part of the video. Then sets each sphere in a different layer so the cameras inside the WebXRManager see a different object.

**Comment by Mugen87** [comment]
Many thanks, that cleared things up! 👍 I was not aware that the video has two views.

**Pull request merged**
