### PR TITLE
Examples: Improve FXAA demo

### LINKED ISSUE #15553: The FXAA example should show how to use the effect for post processing
FXAA is often recommended for use instead of default MSAA to increase performance. 

However, the [current example](https://threejs.org/examples/#webgl_postprocessing_fxaa) only shows how to apply it to a png image. 

It's useful to have an example that shows how to apply a shader to an image, but I think it would be better to do this with one of the other effects instead.

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #15553

The example looks now similar to the new demo that demonstrates multisampled renderbuffers. It's now easier to compare a scene with FXAA and without it. The example also uses `EffectComposer`.

### CODE REVIEW

**Comment by looeee** [comment]
Looks much better 👍

**Comment by WestLangley** [comment]
This example does not set pixel ratio?

**Comment by mrdoob** [comment]
@WestLangley good catch 👍

**Comment by Mugen87** [comment]
Done. 65bb7e70122fc3057519d1f9c240ec6fffd3a1e0

BTW: I've not set the pixel ratio in the first place for two reasons:

- It's easier to see the aliasing on retina displays
- Because `EffectComposer` still has problems with pixel ratio #14340

**Comment by mrdoob** [comment]
> It's easier to see the aliasing on retina displays

Makes sense. On some retina displays it seems to get blurry though, so it was confusing.

**Comment by WestLangley** [comment]
I would expect the fxaa shader uniforms to take the pixel ratio into consideration, and they don't...

**Pull request merged**
