### PR TITLE
Implemented CinematicCamera feature using BokehShader2

### PR DESCRIPTION
**Pull request by ghost**
The idea was to create a simple and re-usable camera with bokeh effect, extending from Perspective Camera and using BokehShader.

CinematicCamera behaves as PerspectiveCamera if the CinematicCamera renderer is not called in the base renderer of any example.
[Check out line 230](https://github.com/kaypiKun/three.js/blob/CinematicCamera/examples/webgl_camera_cinematic.html)

CinematicCamera is implemented [here](https://github.com/kaypiKun/three.js/blob/CinematicCamera/src/cameras/CinematicCamera.js)

I hope I am not deviating from the project too much.

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting! I think it should sit in `examples/js/cameras` instead though.

**Comment by WestLangley** [comment]
You also do not need to include the builds in the PR.

Please see the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

**Comment by kaypiKun** [comment]
@WestLangley @mrdoob Sorry, I checked the rules but got lost on the last line. Should I recreate another pull request from a new branch with the changes you mentioned?

**Comment by WestLangley** [comment]
Yes, please.

**Comment by kaypiKun** [comment]
[here](https://github.com/mrdoob/three.js/pull/7664) is the new request.
Thanks.

**Pull request closed without merging**
