### PR TITLE
Lathe geometry in the editor

### PR DESCRIPTION
**Pull request by rfm1201**
Added a minimal support of lathe geometry in the editor.

### CODE REVIEW

**Comment by mrdoob** [comment]
Super nice! Thanks!

**Comment by mrdoob** [comment]
Do you think `LatheGeometry` should revolve on the Y axis instead of on the Z axis?

**Comment by rfm1201** [comment]
The first time I use the function, I thought it will revolve on the Y axis.
Why?
Because the points you pass to the function must have the Y at 0.

If the function is refactored, maybe the points should be Vector2 and a parameter should be added to choose the axe. By axe, I mean X, Y or Z.
The problem is that’s a breaking change.

In my own version of the editor, I rotate the mesh because I think it’s more natural.

**Comment by mrdoob** [comment]
It is a breaking change but it's easy to warn the user though (checking for `Vector2`).

**Pull request merged**
