### PR TITLE
Examples: Modularize usage of cannon.js.

### PR DESCRIPTION
**Pull request by Mugen87**
More ES6 module usage.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev49/examples/physics_cannon_instancing.html

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Did you ported it to modules yourself?

**Comment by Mugen87** [comment]
Yep. The last commit of the official repository is more than four years old. Not sure it's still maintained...

**Comment by mrdoob** [comment]
Would it be easy to do a PR with the update to the cannon.js repo?

**Comment by arpu** [comment]
there is this Typescript rewrite from cannon and maintained https://github.com/react-spring/cannon-es

**Comment by mrdoob** [comment]
They should rename it to `cannon.ts`.

**Comment by donmccurdy** [comment]
I didn't realize they ported it to TS! Nicely it works as a drop-in replacement for cannon.js even in plain-JS projects, thanks @arpu for the patch in A-Frame Physics System (https://github.com/donmccurdy/aframe-physics-system/pull/147).

**Comment by Mugen87** [comment]
@mrdoob Do you want to use this file?

https://github.com/react-spring/cannon-es/blob/master/dist/cannon-es.js

I've checked it locally and it seems to work.

**Comment by mrdoob** [comment]
Hmm, no... I was hoping we could help @schteppe making the library transition to ES modules.

**Comment by Mugen87** [comment]
It seems the build of `cannon.js` uses Browserify. Is it actually possible with this tool to output an ES6 `*.module.js` file?

**Comment by mrdoob** [comment]
Seems like [cannon-es](https://github.com/react-spring/cannon-es) is getting some traction. Should we use that instead? (Sorry for the wasted hours 😔)

**Comment by Mugen87** [comment]
No problem. New PR: #19709

**Pull request merged**
