### PR TITLE
OBJLoader now optionally reports unknown lines

### PR DESCRIPTION
**Pull request by vidstige**
Now the OBJLoader reports unknown lines via the `onParseFail` function. This
allows apps to either display the error for building robust apps, or
just ignore it if you don't care for some reason. Default is to use the `onError` function to report parsing error as well to keep things simple.

### CODE REVIEW

**Comment by leitzler** [comment]
In my opinion you should skip the default behaviour, it could break other users code. The behaviour for the loader is that the load either works (and trigger `onLoad`) or don't work (triggers `onError`).

If you don't supply a handler for `onParseFail` you could end up with callbacks from both `onError` and `onLoad`. There are probably users that performs cleanup in `onError` today, and if they update three.js without knowing about this, they will end up with pretty strange behaviours.

**Comment by vidstige** [comment]
@leitzler alright, thanks for the feedback. It makes lots of sense to have balanced callbacks, e.g. either are always called but never both. I updated the code to do nothing as default.

**Comment by mrdoob** [comment]
I think I would throw an Error instead, which then you could catch from your code. No `onWarning` stuff needed.

**Comment by vidstige** [comment]
But this is called  from inside the `XHRLoader.load` so how would I actually catch it? Also does it really make sense to have a callback for errors, but throw an error for warnings?

**Comment by vidstige** [comment]
Also relating to the comment of @leitzler - That would potentially break peoples codes.

**Comment by mrdoob** [comment]
> But this is called  from inside the `XHRLoader.load` so how would I actually catch it? Also does it really make sense to have a callback for errors, but throw an error for warnings?

I think this should work...?

```javascript
try {
    loader.load( 'file.obj', function ( object ) {
        //
    } );
} catch ( e ) {
   console.error( e );
}

**Comment by vidstige** [comment]
Alright, I can try that. Still don't know if that's a good idea.

**Comment by vidstige** [comment]
One thing to consider before going error throwing is that as it is now, you can ignore parse warnings in the middle of the file and still get the mesh out, as with throwing an error, it's not possible to ignore it in that way any more.

**Comment by leitzler** [comment]
If it's just a warning, wouldn't it be a better option to preprocess the file?

**Comment by vidstige** [comment]
My opinion? Yes, then an error callback would be called for all errors and to parse weird files preprocessing would be needed. 

This would mean using the onError callback for all errors, but stop parsing as soon as it it emitted. Is this what you want?

**Comment by vidstige** [comment]
try {
        loader.load( 'file.obj', function ( object ) {
            //
        } );
    } catch ( e ) {
       console.error( e );
    }

@mrdoob that won't work as the exception will be thrown _after_ the load function returns and execution has passed outside the try-catch block.

**Comment by vidstige** [comment]
All things considering I think the current solution has it's advantages... Let me break it down.
* Does not break existing code.
* People parsing crazy files can still do so.
* People who want to trigger an error on invalid files (such as parsing a png file) can do so.
* When calling load, either `onError` or `onLoad` will be called but never both. This is important to make simple cleanup routines etc.

**Comment by vidstige** [comment]
Just to give you guys some context on why this is important. We had an issue where we accidentally tried to load a file that was not an obj-file. Actually it was a [git lfs](https://git-lfs.github.com/) placeholder file. It took a while to track down. A helpful message in the console would have saved lots of time, and will probably do so again in the future if that feature is in. In general let's try to fail early. :)

**Comment by mrdoob** [comment]
> @mrdoob that won't work as the exception will be thrown after the load function returns and execution has passed outside the try-catch block.

I see... How about this then?

```js
var loader = new THREE.OBJLoader();
new XHRLoader().load( 'file.obj', function ( text ) {
    try {
        var object = loader.parse( text );
    } catch ( e ) {
        console.error( e );
    }
}
``

The reason I'm hesitant about this change is because all the loaders now have the same interface. If we change this we should change all. So if there is a way to achieve the same functionality without modifying the API, I would favour it.

**Comment by leitzler** [comment]
In the context where you load another filetype without noticing, the parser should throw an error. I.e. the file is not a valid file.

But a valid file could still contain unknown lines, right?

How about the parser throwing error if the parsed file doesn't contain any data at all?

**Comment by vidstige** [comment]
@leitzler no I think lines need to start with a small set of characters for the file to be valid. otherwise _all_ files are valid obj files and that's not very helpful when detecting e.g. you're trying to parse something that's not a obj file. Checking for zero vertices etc is another alternative, but puts some needless constraints on. It would be nice if the loader still is flexible enough to handle this.

**Comment by vidstige** [comment]
@mrdoob I see, I did not know they all had the same interface. Alright, how about this then. Alterinative A: What if there is a function on the `OBJLoader` object like so

    loader.setRaiseForParseErrors(true); // better name?

when this is set to true, the _normal_ error event (`onError`) will be raised, and parsing halted. 

Alternative B: Likewise there is a function on the `OBJLoader` like so

    loader.setWarning(myWarningCallback);

Both solutions give the following benefits
* Code out there still works as per usual
* Interface for constructor & load function is same across loaders.
* Detecting parse errors is possible, but opt-in.

What's your thought on this?

**Comment by vidstige** [comment]
ping @mrdoob or let's leave until after holidays?

**Comment by mrdoob** [comment]
I think I would go with the throwing error approach by now 😅

**Comment by vidstige** [comment]
Haha, alright lets do that. I'm just worried other people going to be bothered by it.

**Pull request closed without merging**
