### PR TITLE
Puppeteer E2E test: Fix text-rendering differences

### PR DESCRIPTION
**Pull request by LeviPesin**
Related:
- https://github.com/mrdoob/three.js/pull/25403#discussion_r1094215965
- https://github.com/puppeteer/puppeteer/issues/661
- https://github.com/puppeteer/puppeteer/issues/2410

**Description**

Fix differences in text rendering in Puppeteer between different platforms and also regenerate some screenshots (using Chromium 109.0.5414.120 (revision 1070054, https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1070054/chrome-win.zip), stable channel on win64).

### CODE REVIEW

**Comment by epreston** [comment]
@LeviPesin gday, e2e was failing on the mac so I took a peek.  Code is pushing an `--enable-features=Vulkan` flag.  That doesn't look right.  What's it required for ?

Also added a `--enable-logging=stderr --v=1` to the build flags to get more detailed messages during runs so I can pass along detailed reasons for failures.

Where do we tune the memory allocated for the chromium browser session ?

**Comment by epreston** [comment]
Your constant for `mac_arm` is missing an R in the value.

**Comment by epreston** [comment]
To get the native mac browser and avoid slow rosetta emulation looks like you need to opt into it:

```js
const browserFetcher = new BrowserFetcher( { path: 'test/e2e/chromium', useMacOSARMBinary: true } );
```

After fixing the typo in the `PLATFORMS` constant :

```js
console.log( browserFetcher.platform() );
```

This will return `mac_arm` instead of `mac` when it's on ARM.  In turn, that downloaded the chromium for `mac_arm` and started running tests.

**Comment by epreston** [comment]
It's finally able to complete a full run.  The messages at the end are below, might not be what you want to do.

Screenshot 2023-02-07 at 11 11 09 am

`webgl_multiple_elements_text` error was:

Screenshot 2023-02-07 at 11 13 13 am

`webgl_postprocessing_procedural` error was:

Screenshot 2023-02-07 at 11 12 53 am

I am doing another pull and running.

**Comment by LeviPesin** [comment]
> Your constant for mac_arm , in PLATFORMS is missing an R in the value.

> To get the native mac browser and avoid slow rosetta emulation (buggy because its never tested on arm because they have arm builds) looks like you need to opt into it:
const browserFetcher = new BrowserFetcher( { path: 'test/e2e/chromium', useMacOSARMBinary: true } );

Thank you! Will fix those errors.

The problem why some examples fail in this PR (which I tried to fix but to no avail) is text rendering -- I tried using some flags and/or setting a custom font so that it overwrites the default system font but that doesn't seem to work. I will investigate more.

**Comment by epreston** [comment]
Ran again with all the lasted updates. R

2 Mods applied, one ommitted.

- [x] `PLATFORMS`
- [x] `useMacOSARMBinary: true`
- [ ] remove `--enable-features=Vulkan`

Next test is all 3.  Vulkan won't have much supports on the Macs.

Updating this comment with the results.

**Comment by epreston** [comment]
Also a new issue popped up.

- When retrying the test, it doesn't say if it ran the test again or its status

Screenshot 2023-02-07 at 1 16 18 pm

**Comment by LeviPesin** [comment]
> When it is retrying the test, it doesn't say if it ran the test again or its status

This is strange, it should... It can be significantly below that line -- because when making a new attempt it's added to the end of the queue.

**Comment by epreston** [comment]
3 Mods applied:

- [x] `PLATFORMS`
- [x] `useMacOSARMBinary: true`
- [x] remove `--enable-features=Vulkan`



Screenshot 2023-
02-07 at 1 51 53 pm

Screenshot 2023-02-07 at 2 11 12 pm

**Comment by epreston** [comment]
Looks like the `vulkan` is harmless.

**Comment by epreston** [comment]
> > When it is retrying the test, it doesn't say if it ran the test again or its status
> 
> This is strange, it should... It can be significantly below that line -- because when making a new attempt it's added to the end of the queue.

Ok.  Checking logs again to confirm.

**Comment by LeviPesin** [comment]
Vulkan-related flags were added in https://github.com/mrdoob/three.js/pull/25304 by @mrdoob. I'm not really sure about what they do but at least they fix the "no adapters error" for WebGPU on Linux.

**Comment by epreston** [comment]
Forcing `swiftshader` is forcing software emulation.  For automated tests running in the cloud with no GPU, might be a good thing.

I have the same tests failing all runs.  Hows this match up with the image updates and tolerances ?

**Comment by epreston** [comment]
I'm going to run the suite full native, raw, no swiftshader and post the results below so you have that data point.

**Comment by LeviPesin** [comment]
> I have the same tests failing all runs. Hows this match up with the image updates and tolerances ?

The examples that are failing are exactly the examples that use many text -- and the difference is exactly in text rendering. I will think more about how to solve this...

**Comment by epreston** [comment]
Updated the raw test data.  Is it a font thing ?

**Comment by epreston** [comment]
The test rig is filtering web requests for the three library so it can return a version where random replaced with a fixed value to get consistent results.

These examples might import from other places.  Is it possible some of these could need filtering now or in the future ?

```js
	{
		"imports": {
			"three": "../build/three.module.js",
			"three/addons/": "./jsm/"
		}
	}
```

**Comment by epreston** [comment]
Another one:

Looks like the filtering is only doing `http:` requests.  What if someone where to swap that to `https` in an example ?  Might be required for certain types of code now or in the future.

**Comment by epreston** [comment]
The same examples fail each time.  I'm going to run each example directly on the Mac and post the results.  

Maybe there will be a font not loaded or not compatible, some sort of message.

**Comment by LeviPesin** [comment]
There was a discussion about Math.random() filtering in https://github.com/mrdoob/three.js/pull/24109. I'm not very convinced it is needed (it was said there that otherwise many screenshots could break when another Math.random() is inserted before a one)...

By the way, we can theoretically just set the JS random value when starting the browser (there is such a flag) and then remove the filtering and `Math._random()` code from deterministic-injection.js.

**Comment by epreston** [comment]
Half way through the Mac tests.  My back was hurting so had to break from using the laptop.  I'll send through the infos shortly.

**Comment by Mugen87** [comment]
Since the CI only runs on a single OS now, I'm not sure this is still needed. Because of the many merge conflicts, it's best to give this a fresh start _if_ the change is still required.

**Pull request closed without merging**
