### PR TITLE
Make `applyMatrix4` work on a `BufferGeometry` with `InterleavedBufferAttribute` normals.

### LINKED ISSUE #21433: BufferGeometry.applyMatrix4 throws for normals from InterleavedBufferAttributes
**Describe the bug**

Calling `applyMatrix4` on a `BufferGeometry` may throw a `TypeError` if the attributes are from an `InterleavedBufferAttribute` object, as `InterleavedBufferAttribute` doesn't have `applyNormalMatrix` or `transformDirection`.

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [dev, r121]

### PR DESCRIPTION
**Pull request by devnev**
Closes #21433

**Description**

Allow `applyMatrix4` to be called on a `BufferGeometry` with normal or tangent attributes from an `InterleavedBufferAttribute` by adding the `applyNormalMatrix` and `transformDirection` methods. Method implementations are copied from `BufferAttribute`.

### CODE REVIEW

**Comment by WestLangley** [comment]
Sweet. Do you mind also updating the doc file?

**Review by Mugen87 — APPROVED** [review]

**Comment by devnev** [comment]
@Mugen87 @WestLangley is there anything else I should do for this to be merged?

**Comment by Mugen87** [comment]
Nope^^. @mrdoob just needs to review the PR.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
