### PR TITLE
Added general purpose particle system example: campfire.

### PR DESCRIPTION
**Pull request by mkkellogg**
General Purpose Particle System - There are a number of other particle system examples on the Three.js site, but the aim of this one is to be more general purpose, extendable, and to support texture animations. This campfire example includes three systems: fire, smoke, and embers. Example page is at examples/particles/general.

### CODE REVIEW

**Comment by WestLangley** [comment]
Sweet! http://ci.threejs.org/api/pullrequests/7841/examples/webgl_particles_general.html

**Comment by mrdoob** [comment]
Looks great!

Is https://github.com/mkkellogg/ParticleSystemJS the main page for it? If so we should probably link to it somewhere (either source or example).

**Comment by mkkellogg** [comment]
Yes, https://github.com/mkkellogg/ParticleSystemJS is the main page, I can make a quick update to the example page with a link. The code for the particle systems is currently contained in 5 different files, should I package them up into a single file and minify them for the example or leave them as they are in the source repo?

**Comment by mrdoob** [comment]
It depends of how you want the code to be managed. If you want to make sure there are no multiple versions of the code, then it's better to add here a minified file as a library and point to `mkkellogg/ParticleSystemJS` as the source.

**Comment by mkkellogg** [comment]
Ok, I have updated the PR with the particle system source packaged into a single minified library file called GeneralParticleSystem.min.js.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Now that this had become its own library, how about giving it a name? Say... flecks?

```
github.com/mkkellogg/flecks // github.com/mkkellogg/ParticleSystemJS
js/libs/flecks.min.js // js/GeneralParticleSystem.min.js

FLECKS.Atlas // THREE.Atlas
FLECKS.SingularVector // THREE.Particles.SingularVector
FLECKS.ParticleSystem // THREE.Particles.ParticleSystem
FLECKS.RandomModifier // THREE.Particles.RandomModifier
...
```

That way it's easier to use (less code to write), it has its own namespace so it can be simplified and  it's also less THREE namespace pollution (and possible collision).

What do you think?

**Comment by mkkellogg** [comment]
Ah, that's a good idea. "Flecks" is a good name, but I was also thinking about possibly naming it "Photons". I will give the name a little more thought and then I will make the update.

**Comment by mrdoob** [comment]
Yay!

**Comment by mkkellogg** [comment]
Ok, I have renamed the name-space to "PHOTONS" and I have included the minified version under examples/js/libs. The new PR is ready to go.

**Pull request merged**
