### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by WestLangley**
The arguments were swapped.

`darkness` is in [0, 1].

### CODE REVIEW

**Comment by Mugen87** [comment]
I wasn't able to push to your branch but here is the updated screenshot.

webgl_postprocessing_advanced

**Comment by WestLangley** [comment]
Thanks, @Mugen87, but e2e is failing... Trying to figure out what is going on. :/

**Comment by WestLangley** [comment]
@Mugen87 You screenshot may be compressed. It is not passing e2e. And my screenshots are black.

>I wasn't able to push to your branch

Not sure why that is, either. It says "Maintainers are allowed to edit this pull request."

**Comment by Mugen87** [comment]
Now it works! I guess I was on the wrong branch, not `dev-clean_up`.

**Pull request merged**
