### PR TITLE
CI: Travis -> Github Actions

### PR DESCRIPTION
**Pull request by munrocket**
Cons:
* Anchors [not supported](https://github.community/t5/GitHub-Actions/Support-for-YAML-anchors/m-p/30336) and configs become huge
* Allow-failure [not supported](https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033) and new examples will need a screenshot.

Pros:
* Hope that CI will be more rubust (we need to press rebuild button in Travis 2-5 times in 1 week)
* We can ignore changes in `/docs/`

### CODE REVIEW

**Comment by munrocket** [comment]
Seems that force-push works and it's much faster than Travis, at least for now.

**Comment by munrocket** [comment]
Fixed build issue, appeared in #19118

**Comment by Mugen87** [comment]
I think we should give this a try and see how it goes 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
This has been running for 3 hours now... 🤔
https://github.com/mrdoob/three.js/runs/587667358?check_suite_focus=true

**Comment by Mugen87** [comment]
Unfortunately, the [same error pops](https://github.com/mrdoob/three.js/pull/18928#issuecomment-608381506) up again:

>  ! [remote rejected]     dev43 -> dev43 (refusing to allow an OAuth App to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/Mugen87/three.js.git'

I'm unable to push.

**Comment by munrocket** [comment]
@mrdoob after rebuild - 4m 15s, it's possible some bug with script?
The steps in Travis are failing before they even load and not related to us.

@Mugen87 here a [solution](https://github.community/t5/GitHub-Actions/Refusing-to-allow-an-integration-to-create-or-update/td-p/32472). Not handy but seems work.

We also can try CircleCI. They need a registration on site and integration like Travis.
I can't decide what is better here @mrdoob.

**Comment by Mugen87** [comment]
> @Mugen87 here a solution. Not handy but seems work.

Okay, it works now. For all macOS users: If you hit similar problems, just delete the github entry from your Keychain Access app and login again.

**Comment by munrocket** [comment]
Also fails sometime. Possibility to freeze build for 6h probably even worse than Travis workflow.



Impossible to rerun one step, but only all of them. Rerun button available for all contributors?

**Comment by munrocket** [comment]
Stupid tests. All CI is a crap. It's not automatic testing, it's semi-automatic.
LGTM also slow and check PR in docs, recently I tried to optimize it, but without success #19133.

**Comment by munrocket** [comment]
[First fail](https://github.com/mrdoob/three.js/runs/613235373?check_suite_focus=true) after 80 successful builds.



It's pretty good actually.

**Comment by Mugen87** [comment]
Yep, after a some minor credentials issues at the beginning I have to say it works quite well!

**Pull request merged**
