### PR TITLE
JSM: Update modules.

### PR DESCRIPTION
**Pull request by Mugen87**
Updates the JSM module and TS file for `HDRCubeTextureLoader`, see #16718

@WestLangley We should always update at least the TS declaration file when things change otherwise everything gets out of sync.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 OK. Thanks!

**Comment by mrdoob** [comment]
@WestLangley @Mugen87 I wouldn't stress too much about it though. I don't want to make the process of contributing feel like a chore.

**Comment by Mugen87** [comment]
Understood. I personally tend to take such things to exactly 😅

**Pull request merged**
