### PR TITLE
Added clone functionality for objects

### PR DESCRIPTION
**Pull request by hena-3**
#6716 PR

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks!

**Comment by WestLangley** [comment]
@TatumCreative What is the best practice to ensure that the docs are updated when functionality is added?

**Comment by TatumCreative** [comment]
@WestLangley Well... in an ideal world I think that docs updates would come with the code changes. Barring that, a ping to me I can at least note that doc updates are needed, and try and get to it. A longer term solution is probably to add some scripting verification to test the docs for completeness. We already have some decent regex tagging with stuff like `[method:null post]()` in the docs. It seems like we could put something together to verify them. That solution would also expose parts of the API that are wrong and are missing in the docs.

I probably won't have as much time in the next 2 months to dedicate to some of this as I'm doing a WebGL fellowship with Mozilla's developer network, so I'll be concentrating on some other docs for awhile :) I plan on hopping back over here after all of that though.

**Comment by WestLangley** [comment]
@TatumCreative OK, thanks. Maybe you can come up with a creative solution. : - )

@hena-3 Do you mind updating the relevant docs, too?

**Comment by hena-3** [comment]
Ok, will send PR for updated docs too.

**Comment by WestLangley** [comment]
@hena-3  Many thanks. : - )

**Comment by TatumCreative** [comment]
@hena-3 You rock, thanks!

**Pull request merged**
