### PR TITLE
Added VertexTangentsHelper

### PR DESCRIPTION
**Pull request by WestLangley**
I'll have to add docs at a later time...

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you plan on using it in the helpers example?

**Comment by WestLangley** [comment]
>Do you plan on using it in the helpers example?

My main purpose was to make it available because we have bugs in our tangent code that need to be investigated...

**Comment by WestLangley** [comment]
I'll be glad to add an example of its use in a subsequent PR.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
