### PR TITLE
 Updated shadowMap.cullFace -> .flipSidedFaces.

### PR DESCRIPTION
**Pull request by tschw**
See #8779

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
How about `flipFaceSides`?

**Comment by tschw** [comment]
@mrdoob 
> How about flipFaceSides?

I think that would be less clear, since it's not the faces that are being flipped but the faces on the flip side that are being used. 

```
flipSidedFaces -> invertFaceCulling
! allowDoubleSided -> forceFaceCulling
```
more low-level naming again, but would still be clear about what's going on.

Or something like
```
flipSidedFaces -> useOppositeFaces
```
?

**Comment by tschw** [comment]
@WestLangley did not yet elaborate on the question on the sought defaults (see https://github.com/mrdoob/three.js/pull/8779#issuecomment-216080281).

If it's supposed to be self-shadowing and panning to prevent it for double-sided materials, then `allowDoubleSided` can be dropped altogether.

Otherwise, 
```javascript
renderDoubleSidedAs = THREE.BackSide
```

might do.

**Pull request merged**
