### PR TITLE
ColladaLoader: Added support for polylists with more than four vertices.

### LINKED ISSUE #13727: ColladaLoader: add support for polylist with more than 4 vertices
Please expand the ColladaLoader to support polylist of more than 4 vertices.

Here is a section of the DAE that the loader can't parse correctly.

`<polylist count="18" material="Material2">
                    <input offset="0" semantic="VERTEX" source="#ID23"/>
                    <input offset="1" semantic="TEXCOORD" source="#ID24"/>
                    <vcount>5 5 8 8 4 4 4 4 5 5 5 5 5 5 4 4 4 4</vcount>
                    <p>0 0 1 1 2 2 3 3 4 4 5 4 6 3 7 2 8 1 9 0 10 5 11 6 12 7 13 8 14 9 15 10 16 11 17 12 18 12 19 11 20 10 21 9 22 8 23 7 24 6 25 5 26 13 27 14 28 15 29 16 30 16 31 15 32 14 33 13 34 17 35 18 36 19 37 20 38 20 39 19 40 18 41 17 42 21 43 22 44 23 45 24 46 25 47 25 48 24 49 23 50 22 51 21 52 26 53 27 54 28 55 29 56 30 57 30 58 29 59 28 60 27 61 26 62 31 63 32 64 33 65 34 66 35 67 35 68 34 69 33 70 32 71 31 72 36 73 37 74 38 75 39 76 39 77 38 78 37 79 36 80 40 81 41 82 42 83 43 84 43 85 42 86 41 87 40</p>
                </polylist>`
##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

### PR DESCRIPTION
**Pull request by Mugen87**
Fixes #13727 :tada: 

@l-xiong Can you please make a test with this change and your model? 

BTW: When you've shared the model, you've missed to add the corresponding texture `CabinetFront.jpg`. I've used a fallback texture on my system to test the model. Everything looked good so far.

### CODE REVIEW

**Comment by l-xiong** [comment]
Thanks for the prompt response on this, much is appreciated.

I tested the modified class against a few of my models, including the one I uploaded with the ticket.  Overall, your changes are good; it fixed the polylist issue.  However, on one of my models, it showed white edges.  I uploaded the model with a couple pics - one loaded with the old loader and one with this loader so you can see what I'm talking about.  Other than this, everything else seemed good.

Loaded with this loader:
scr36-new-loader

Loaded with old loader:
scr36-old-loader
DAE model with texture:
[SCR36.txt](https://github.com/mrdoob/three.js/files/1872045/SCR36.txt)
cabinetfront

**Comment by Mugen87** [comment]
Many thanks for your feedback! 

You see these white edges because the new loader correctly parses lines. Sketchfab produces the same result:

image

**Comment by l-xiong** [comment]
Interesting.  I'll have someone retouch the models to remove the white edges/lines.

I guess that is it; everything is good.  Thanks again for your help.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
