### PR TITLE
Altered VRControls and VREffect

### PR DESCRIPTION
**Pull request by pindiespace**
1. VRControls filterInvalidDevices changed to prevent error on missing .deviceName.
2. VREffect changes with setter setFOV allowing dynamic change to FOV (e.g. on orientation change).

### CODE REVIEW

**Comment by borismus** [comment]
Pete, could you provide rationale for `setFOV`? The FOV can be changed on the camera directly.

**Comment by pindiespace** [comment]
Just made it easy within webvr-boilerplate - abstraction.

On Tue, Jan 12, 2016 at 1:26 PM, Boris Smus <notifications@github.com>
wrote:

> Pete, could you provide rationale for setFOV? The FOV can be changed on
> the camera directly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/pull/7934#issuecomment-171061010>.
>



-- 
============================================================
=================
*Dr. Pete Markiewicz*
*Email:* pindiespace@gmail.com
*Sustainable virtual design blog:*
http://sustainablevirtualdesign.wordpress.com
*Sustainability template:* http://greenboilerplate.com
*Teaching site: *http://plyojump.com <http://www.plyojump.com/>
*Buy my book! *- Millennials and the Popular Culture
*Lifecourse:* http://www.lifecourse.com/store/catalog/lca/mpc.html
* AmazonAuthor Page:*
http://www.amazon.com/Pete-Markiewicz/e/B0069VZ7BG/ref=ntt_athr_dp_pel_pop_2
*On that page, see my DARPA Grand Challenge 2005 entry video, "Team
Robomonster":*
*Team Robomonster *(DARPA 2005 Grand Challenge):
http://robotsthatjump.wordpress.com/category/team-robomonster/
*Indiespace *(1st to sell downloaded music, March 1994):
http://www.indiespace.com. Also see http://archive.org under
"Kspace.com" 1996 for our original site.
============================================================
=================

**Comment by borismus** [comment]
I don't understand.

**Comment by pindiespace** [comment]
It seems to me that FOV changes are unlikely to be made due to changes in
the virtual world model, which is where you typically manipulate the
camera. An FOV would be chosen at the start of a VR scene, and kept there,
unlikely to change due to changes in the virtual environment.

The place where an FOV change could happen is at the device level, i.e.
changing orientation between portrait and landscape, while retaining stereo
view. Current boilerplate only uses landscape, but that could change.
Adjusting FOV might make sense in that case.

Another case would be changes in the device, requesting changes in the FOV,
possibly in only one eye.

Changing FOV in these cases seems to belong at a "higher" level above the
camera. You would write a function watching for camera movements
corresponding to orientation changes, but you already have the manager
watching for device changes.

So, adding a small setter for the manager to use during orientation changes
seems reasonable. It's abstract  or indirect because the camera is being
changed without the manager knowing about camera details,

On Tue, Jan 12, 2016 at 5:24 PM, Boris Smus <notifications@github.com>
wrote:

> I don't understand.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/pull/7934#issuecomment-171122150>.
>



-- 
============================================================
=================
*Dr. Pete Markiewicz*
*Email:* pindiespace@gmail.com
*Sustainable virtual design blog:*
http://sustainablevirtualdesign.wordpress.com
*Sustainability template:* http://greenboilerplate.com
*Teaching site: *http://plyojump.com <http://www.plyojump.com/>
*Buy my book! *- Millennials and the Popular Culture
*Lifecourse:* http://www.lifecourse.com/store/catalog/lca/mpc.html
* AmazonAuthor Page:*
http://www.amazon.com/Pete-Markiewicz/e/B0069VZ7BG/ref=ntt_athr_dp_pel_pop_2
*On that page, see my DARPA Grand Challenge 2005 entry video, "Team
Robomonster":*
*Team Robomonster *(DARPA 2005 Grand Challenge):
http://robotsthatjump.wordpress.com/category/team-robomonster/
*Indiespace *(1st to sell downloaded music, March 1994):
http://www.indiespace.com. Also see http://archive.org under
"Kspace.com" 1996 for our original site.
============================================================
=================

**Comment by Mugen87** [comment]
`VRControls` and `VREffect` are now deprecated, see https://github.com/mrdoob/three.js/issues/11301#issuecomment-308641241

**Pull request closed without merging**
