### PR TITLE
Support FBX Binary format

### PR DESCRIPTION
**Pull request by takahirox**
This PR lets `FBXLoader2` support FBX Binary format. #9860

Binary model data can include compressed data.
You need to import `examples/libs/zlib_and_gzip.min.js` for such models.

BTW does anyone have good FBX Binary model data which can be used as an example?

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thankss!

**Comment by mrdoob** [comment]
Hmm, any chance this could depend on http://stuk.github.io/jszip/ instead? That's what https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/KMZLoader.js and https://threejs.org/editor/ depends on already.

**Comment by takahirox** [comment]
OK, I'll try.

(BTW who uses `examples/libs/zlib_and_gzip.min.js`?)

**Comment by mrdoob** [comment]
webgl_loader_nrrd.html is seems...

**Comment by takahirox** [comment]
Hm, it seems JSZip's APIs aren't fitting to FBXLoader.
FBXLoader just needs inflate(uncompress) function but
JSZip APIs expect zip (archived) file/data.

**Comment by mrdoob** [comment]
So then it mainly needs https://github.com/imaya/zlib.js/blob/master/bin/rawinflate.min.js, right?

What do you think about adding that code directly inside `FBXLoader` so it doesn't require dependencies?

**Comment by takahirox** [comment]
I can try, but personally I think I want to separate them for maintenance.
(Maybe dev's ease of maintenance vs user's ease of use)

**Comment by mrdoob** [comment]
Oks! Sounds good 👌

**Comment by mrdoob** [comment]
Some clean up... `NRRDLoader` only needed gunzip, so I replaced `zlib_and_gzip.min.js` with `gunzip.min.js`. We already had `inflate.min.js` in the libs so we can use that one `FBXLoader`.

**Comment by vinaysshenoy** [comment]
The loader doesn't seem to handling certain FBX files properly. I've attached an FBX file which I'm using to test it, and the model imports correctly in Unity3D, but the geometry doesn't load properly in the FbxLoader. Attaching screenshots for reference.

screen shot 2017-05-15 at 2 09 12 pm
screen shot 2017-05-15 at 2 08 41 pm
screen shot 2017-05-15 at 2 08 30 pm
screen shot 2017-05-15 at 2 14 37 pm



[Here's the FBX file](https://github.com/mrdoob/three.js/files/1000523/test.FBX.zip)

@takahirox Would you be able to take a look at this?

**Comment by takahirox** [comment]
Would you please check if text version of that model can be displayed correctly with `FBXLoader`?
I'd like to clarify if this issue is of binary parser.

**Comment by vinaysshenoy** [comment]
@takahirox I just checked. ASCII version is also not displaying correctly.

I suppose this is actually related to the Fbx -> THREE.Group conversion not handling certain cases.

**Comment by takahirox** [comment]
I see.
Would you please make another issue?
This thread already has been merged/closed.

**Comment by vinaysshenoy** [comment]
Sure, will do.

**Pull request merged**
