### PR TITLE
Test Puppeteer WebGPU

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #XXXX

**Description**

Puppeteer running on github ci (macos only) may support WebGPU already...

### CODE REVIEW

**Comment by mrdoob** [comment]
> Error: Diff wrong in 39.7% of pixels in file: webgpu_compute_particles

Grrrr!

**Comment by sunag** [comment]
I think that `WebGPURenderer` will need to two tests one for each both backends soon?

**Comment by mrdoob** [comment]
Yeah, but I didn't manage to make it work.

This is the repo with the options: https://github.com/actions/runner-images

We're still using SwiftShader/WebGL in the CI and no sign of runner-images with GPUs coming soon...

**Comment by Mugen87** [comment]
> We're still using SwiftShader/WebGL in the CI and no sign of runner-images with GPUs coming soon...

In this case, let's close the PR until the support in`runner-images` improves.

**Pull request closed without merging**
