### PR TITLE
MeshPhysicalMaterial: Renamed attenuationColor to attenuation

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #22156

**Description**

We do not have any `*Color` property. Seems like `attenuation` is more appropriate.

@WestLangley Should it be `attenuationTint` instead?

### CODE REVIEW

**Comment by mrdoob** [comment]
Merging this for now...

**Comment by WestLangley** [comment]
@mrdoob 

`specularTint` is a tinting of the monochromatic specular reflectance.

//

"attenuation Color"  the hue shift of white light as it passes through a medium.

I assume, the attenuation would be applied to the light source of any color.

In that case, I think `attenuationTint` is best, because it is tinting the light color.

**Comment by WestLangley** [comment]
`transmissionTint` ?

**Comment by mrdoob** [comment]
There's also `attenuationDistance`.... so `attenuationTint` sounds good to me 👍

**Pull request merged**
