### PR TITLE
Tests: Modernise Benchmarks

### PR DESCRIPTION
**Pull request by epreston**
Related issue: none.

**Description**

This update modernises the `test/benchmark`.

Convert static vendor files to package dependencies.
Explicit block scope for variables used in tests. (es6)
Clean-up variable names for readability
Addresses underscore security vulnerability.

### CODE REVIEW

**Comment by Mugen87** [comment]
Sidenote: It was actually suggested to completely delete the benchmarks. They would already be gone if #25341 would have been merged. When we delete the builds `three.js` and `three.min.js`, they will definitely be gone. It would be more interesting to migrate the benchmarks to jsbench like suggested here: https://github.com/mrdoob/three.js/issues/25124#issuecomment-1356205827

**Comment by epreston** [comment]
Yeah, the benchmarks don't do anything except take up space with 7 year old dependencies.

I thought, clean it up so at least it isn't setting off the tools and taking up space.  It can be a placeholder / requirements for what comes next.  Jsbench is good.  If it goes vite/vitest it covers off webserver/bundler/tests/benchmark/etc in one shot.

**Comment by Mugen87** [comment]
See #25435.

**Comment by Mugen87** [comment]
> It can be a placeholder / requirements for what comes next.

We have git if it's necessary to restore old code.

**Comment by epreston** [comment]
Sounds good.  Can you delete the `benchmarks` folder so it removes all the warnings and the security vulnerability ?

**Comment by LeviPesin** [comment]
I think @Mugen87 already did that in https://github.com/mrdoob/three.js/pull/25435.

**Comment by diarmidmackenzie** [comment]
> It would be more interesting to migrate the benchmarks to jsbench like suggested here: https://github.com/mrdoob/three.js/issues/25124#issuecomment-1356205827

As far as I can tell, JS Bench is unsuitable for three.js benchmarking requirements, [as explained here](https://github.com/mrdoob/three.js/issues/25124#issuecomment-1359477618).

There are a bunch of issues that would have to be solved to have a usable solution based on jsbench.

**Comment by epreston** [comment]
I agree.  Performance results change if the window is focused or not on interactive / browser based tests.

**Comment by Mugen87** [comment]
> TL;DR: jsbench.me is great for use cases where someone wants to compare the performance of a couple of different ways of doing things within THREE.js.

I think this is actually sufficient for us. In almost all cases in the past we wanted to compare approaches e.g. to verify changes of a PR. This was often not done with the previous benchmark suite but with other tools like jsbench, the browser's dev tools or custom performance measurements via JS. 

The thing is I don't like the idea of having another complex component in the repository. Sure, it would provide some benefit we always have to consider the related complexity/maintenance effort and noise (discussions, issues, PRs etc.). This is already a problem with the E2E tests. And I don't see a compelling reason for having the same with a new benchmark suite.

If someone would be interested to implement a suite in a separate repository, that would be of course fine. But it's already too much going on in this repo.

**Comment by epreston** [comment]
That's fair.  What was there wasn't adding value directly, it was more a template that may have been important whipping up something here or there.

You'll change your mind about the unit and e2e tests now that they are more than placeholders.  Cuts out a lot of noise and adds stability.

**Comment by Mugen87** [comment]
> Cuts out a lot of noise and adds stability.

What I mean with noise is the general need for discussions and reviews when somebody is working on a component. We can't just blindly merge PRs, changes have to be reviewed and discussed. Also things have to be maintained, security alerts and bugs have to be fixed. The more components you have in a repository, there more maintenance work the collaborators have to do. And they have less time for the "actual" features of the project.

**Comment by Mugen87** [comment]
I mean it's great that new contributors can work at the manual, tests or the E2E system but it's important to highlight that we collaborators have to spend parts of our work time for the related reviews and discussion. Time that we can't invest elsewhere. Hence, I'm glad the benchmarks are finally out of our way^^.

**Comment by epreston** [comment]
I don't know how to put this other than: your time is being stolen from actual features and confidence to implement them because of the lack of tests, execution of those tests, etc.

It really is a form of design feedback before the PR gets to review.   It will enforce more thought into things before it takes other peoples time.   It raises the conversation out of "does this work?" to "how do we want this to work?".

**Comment by epreston** [comment]
I think you and I care a lot about this library.  I have a couple of weeks off and this is what I want to do with my time.  I really respect what you guys have achieved.

**Comment by mrdoob** [comment]
A lot of the JavaScript code in the library has been untouched for years now. Lately we tend to move GLSL code around for which the E2E tests are all that we need.

The library is also "kind of" simple. It's very rare that we can't think of what can break when we change something.

Most of the work I personally do is API design (like #25254) for which unit tests and benchmarks do not help.

Because of all these factors, I never run unit tests or benchmarks but maybe others do.

**Comment by epreston** [comment]
Not everyone's the audience.  They run on every PR.  A filter for silliness and typos is always handy.

I'm going to challenge your idea: I think if you have a proper set of unit tests you'll be able to model out different API changes and have this spit out a definitive list of the impacts.  You'd be able to compare them quickly and with confidence.  Once you go down this path, you don't want to build or design without it.  It really is good design feedback.

Remember, I'm a commercial consumer of this library and many others.  One thing we lose time to on projects is small changes in dependencies that have unforeseen consequences.  

Last little bits are: Unit tests point out the inconsistencies, there's a mix and match of things with and without 'isXXX' and 'type' in this library as a simple example.  They provide a definitive reference and example for exercising each part of the API.

Lastly, I've been playing around with your treeshake.  I can see how we can get simple builds down by 55% in size.  I wouldn't be confident in putting it forward without a healthy set of unit tests to prove it.  I wouldn't expect anyone else to be confident without proof.  Worst case, might require you to decouple extras like `PMREMGenerator` from core classes or something similar.  That just doubles your risk unless you have something that proves clearly that it works and what the impacts are.

**Comment by epreston** [comment]
All that said, and sorry for the long read, I'd prefer to work on things that meet your projects needs and not my own during this time.

Point me at the dirty chores that people haven't gotten around to and I'll clean them up.

**Comment by epreston** [comment]
One last thing, sorry sorry..

About moving around that GLSL code.  Yeah, that's taken most of the focus.  Not sure where I picked it up but the best way to guarantee upgrades for your product when using three.js is to copy and overwrite ShaderChunk on load.

This is what we do to ensure our library of shaders doesn't break since 136.

```js
  // install shader chunks
  function installShaderChunks() {
    for (const chunkDefinition in shaderChunkDefinitions) {
      const name = chunkDefinition.split('/').pop().slice(0, -'.glsl'.length);
      // ShaderChunk[name] = shaderChunkDefinitions[chunkDefinition].default;
      ShaderChunk[name] = shaderChunkDefinitions[chunkDefinition];
    }
  }

  // install shader chunks immidiately
  installShaderChunks();
```

If you could incorporate that best practice (not sure how) followed by a few of the recent projects your promote on the web page, you would be able to drop a good amount of weight from builds.  

Heres the spirit of the idea:

Shader defaults are available if you opt in, copy them before writing a ton of shaders for stability,  then opt out to get them tree-shaken.  Three.js can be up to 20% smaller for simple builds doing that alone.

Decoupling `PMREMGenerator` from `WebGLCubeUVMaps` and opting into that behaviour only saves 3%.

**Pull request closed without merging**
