### PR TITLE
FBXLoader: reorganise code and create FBXTreeParser

### PR DESCRIPTION
**Pull request by looeee**
* Reorganised the code a little to bring it more in line with GLTFLoader and other loaders. Should be a little less cut and paste involved to convert the file into a module now since there is just one case of `THREE.FBXLoader` that needs to be replace with `export default FBXLoader` (or your preferred export style).
 
* Removed unnecessary use of `Object.Assign` from prototypes 

* Created `FBXTreeParser`. The amount of parameters being passed between `FBXTree` parsing functions was starting to get hard to reason with, moving them into  `FBXTreeParser` and using `this` for a couple of the more common parameters (`FBXTree` and `connections`) has made things a lot cleaner. Can likely be cleaned up further in future PRs. 

* Gave a couple of functions clearer names:
    * `getNormals` -> `parseNormals`
    * `getUVs` -> `parseUVs`
    * `getColors` -> `parseVertexColors`
    * `getMaterials` -> `parseMaterialIndices`

### CODE REVIEW

**Comment by mrdoob** [comment]
Opps! This PR has conflicts now...

**Comment by looeee** [comment]
Yeah, that was inevitable. I'll fix it tomorrow

**Comment by looeee** [comment]
@mrdoob conflicts resolved! 😁

**Comment by mrdoob** [comment]
Sweet! Thanks!

**Pull request merged**
