### PR TITLE
3DMLoader: Read object names from .3dm file

### PR DESCRIPTION
**Pull request by perkma**
In Rhino object can have a name. This name is currently accessible using Object.userData[ 'attributes' ].name. For better coherence it would be nice to have the name directly on the Three.js object.

### CODE REVIEW

**Comment by Mugen87** [comment]
@fraguada Looking good?

**Comment by fraguada** [comment]
Looks legit. Thanks @perkma!

Thanks @Mugen87 for the ping!

**Comment by Mugen87** [comment]
@perkma Do you mind rebasing the PR? The current diff looks odd.

**Comment by perkma** [comment]
Rebased.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
