### PR TITLE
OrbitControls: allow for inverse Azimuthal range 

### PR DESCRIPTION
**Pull request by munrocket**
Continues #19266

### CODE REVIEW

**Comment by sciecode** [comment]
I failed to understand both the intention and what this attempts to solve, care to explain?

**Comment by sciecode** [comment]
I failed to understand what this attempts to solve @munrocket, would you, please, explain?

**Comment by munrocket** [comment]
Just try <_<

**Comment by sciecode** [comment]
This tries to extend azimuthal angle range, by clamping the inputted values into range [ -PI, PI ], however it does so on every update call, which doesn't sound like the best option to me.

It also changes the user inputted-value, which is not something we usually do.

If we really want to go the route of extending the azimuthal angle range, I rather we instead modify the API to use something like:

```
controls.setMinAzimuthAngle();
controls.setMaxAzimuthAngle();
```

That way, we only need to clamp the values when the user changes the limits. However, if we are going for an API change, I still prefer going for `AzimuthCenter` and `AzimuthRange`.

Eitherway, not my call. Let's see what @Mugen87 and @WestLangley have to say.

**Comment by munrocket** [comment]
Sorry, not check the context, so we can place range remapping in initialization. I just find this hack fun, because it reuse you code :)

**Comment by sciecode** [comment]
> Sorry, not check the context, so we can place range remapping in initialization. I just find this hack fun, because it reuse you code :)

If we do that during initialization, the user won't have the option to alter it afterwards, which breaks the current API.

**Comment by munrocket** [comment]
Too many flops in runtime, closing in favor of #19298

**Pull request closed without merging**
