### PR TITLE
Add support for SVG Groups

### PR DESCRIPTION
**Pull request by pgodwin**
For discussion more than anything else. 
Adds support for passing through the groups parsed out of the SVG file. This makes it easier to do things like highlighting on groups from the SVG, or rendering different SVG groups with different parameters.

### CODE REVIEW

**Comment by yomboprime** [comment]
Now that the SVGLoader exports the root node, the user application can do the groups management.

See [This example](https://yomboprime.github.io/three_example_svg_groups/webgl_loader_svg_groups.html) on how to do it.

In the example, each path is assigned a random color depending on which group the path belongs to.

**Comment by WestLangley** [comment]
@yomboprime Thanks for your example.

Tip: if you use the un-minified `three.js`, it is easier for users to debug.

**Comment by WestLangley** [comment]
Closing. This issue appears to be resolved.

**Comment by pgodwin** [comment]
Thanks for the example, that does the trick. So this is certainly resolved.

**Pull request closed without merging**
