### PR TITLE
Allow user to define state in trackball constructor

### PR DESCRIPTION
**Pull request by NicolasRannou**
Allow use to specify the trackball behavior in the constructor.

### CODE REVIEW

**Comment by mrdoob** [comment]
What's the use case, and why does it have to be in the constructor, why now just `setState()`?

**Comment by NicolasRannou** [comment]
@mrdoob the use case to to allow user to tweak the behavior: in medical imaging, people are used to zoom with right click (button 3) and pan with wheel button (button 2).
Right now, zoom and button buttons are inverted and there is no straight forward way to update it.

A `setState()` method sounds good, I can submit a new pull request if you are still interested in this feature.

**Comment by WestLangley** [comment]
I am not sure exposing, or allowing the user to set, the internal state is the right solution here.

`OrbitControls` allows this:
```javascript
controls.mouseButtons = { ORBIT: THREE.MOUSE.LEFT, ZOOM: THREE.MOUSE.MIDDLE, PAN: THREE.MOUSE.RIGHT };
```
Thing is, I think it only will work correctly if the left and right buttons are switched -- not the middle and right.

**Comment by NicolasRannou** [comment]
yes such a solution would be good -

The fact that only left and right could be switched in the OrbitControls sounds more like a bug rather than a limitation of this approach, right?

**Comment by WestLangley** [comment]
>The fact that only left and right could be switched in the OrbitControls sounds more like a bug rather than a limitation of this approach, right?

No. I think it is because the left and right buttons involve dragging the mouse, and the middle does not.

**Comment by NicolasRannou** [comment]
Closing because irrelevant now and too old

**Pull request closed without merging**
