### PR TITLE
Return geometry after calling applyMatrix()

### PR DESCRIPTION
**Pull request by Wilt**
Return geometry (`this`) after calling `applyMatrix():`

### CODE REVIEW

**Comment by WestLangley** [comment]
Do you mind targeting the dev branch and updating the docs?

I think the same change should be implemented in `BufferGeometry`, if @mrdoob agrees with this PR.

**Comment by Wilt** [comment]
@WestLangley Sorry for that, I thought my PR was targeted at the dev branch...

**Comment by Wilt** [comment]
Changed to PR in dev branch: https://github.com/mrdoob/three.js/pull/8181

**Comment by Wilt** [comment]
@WestLangley  Where in the docs do I need to make an update?

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/blob/dev/docs/api/core/Geometry.html.

Actually, the method return values do not seem to be specified in that document. Compare with the `applyMatrix()` method in the `Vector3` class:

https://github.com/mrdoob/three.js/blob/master/docs/api/math/Vector3.html

/ping @TatumCreative Do you mind having a look?

**Comment by TatumCreative** [comment]
Sure, but it will be a week or so.

**Pull request closed without merging**
