### PR TITLE
[TransformControls] Minor refactor and clean up.

### PR DESCRIPTION
**Pull request by sdinesh86**
This PR fix's issues such as,
Broken Drag and Drop functionality in the editor outliner panel.

### CODE REVIEW

**Comment by arodic** [comment]
What is the easiest way to live test this PR now that the rawgit is down?

This should be OK, but I wanted to make sure there are no issues with touch.

**Comment by mrdoob** [comment]
@arodic https://raw.githack.com/sdinesh86/three.js/transformcontrols_v2_patch/examples/#misc_controls_transform

**Comment by mrdoob** [comment]
> This PR fix's issues such as,
Broken Drag and Drop functionality in the editor outliner panel.

Actually, I noticed that. I was going to investigate.

**Comment by mrdoob** [comment]
Yeah, this PR fixes the outliner not longer being able to move nodes around:

https://raw.githack.com/sdinesh86/three.js/transformcontrols_v2_patch/editor/

**Comment by arodic** [comment]
lgtm

**Comment by mrdoob** [comment]
Thanks!

**Comment by sdinesh86** [comment]
And this marks as my first ever PR in a project

Thanks a lot ^^ :)

**Pull request merged**
