### PR TITLE
GLTFExporter: Ensure normalized normal attribute

### PR DESCRIPTION
**Pull request by takahirox**
This PR lets `GLTFExporter` ensure normalized normal attribute. See  https://github.com/mrdoob/three.js/issues/11951#issuecomment-375981553

I still need to evaluate to know if this change (quite) slows the performance because this's our first computation with each vertex but let me first share the PR with you. You can test by yourselves, too, if you want.

@fernandojsg Can you share the model file on which this change can affect the performance if you have? I tested some standard models but I didn't see performance degradation (from same to just a few percents worse).

### CODE REVIEW

**Comment by WestLangley** [comment]
Normals in three.js are assumed to have unit length. The library does not validate inputs, however.

We already have `BufferGeometry.normalizeNormals()`. In that method, zero-vectors are left unchanged. Zero-vectors are considered a user error.

**Comment by takahirox** [comment]
We already concluded in another thread that `GLTFExporter` ensures valid glTF even if model has unexpected values, like zero-vectors or non-unit length normal.

**Comment by fernandojsg** [comment]
Looking good so far, just two requests:
- I'd add a `checkNormalizedNormals` (or so) parameter :)
- What about checking just the normals that we're going to actually export? We already use `drawRange` to detect the number of attributes to export: https://github.com/mrdoob/three.js/blob/dev/examples/js/exporters/GLTFExporter.js#L467-L479 so we could save some time computing unused normals on very big buffers (like the vr paint examples).

**Comment by takahirox** [comment]
> I'd add a checkNormalizedNormals (or so) parameter :)

I wanna think that option if we see the actual use case/model where checking (quite) slows the performance. I still a bit doubt if it does... So evaluating first.

> What about checking just the normals that we're going to actually export?

If we do that, perhaps it might be better to check/ensure in `processBuffer(View)` as you first suggested. Let me think about it...

**Comment by fernandojsg** [comment]
> I wanna think that option if we see the actual use case/model where checking (quite) slows the performance. I still a bit doubt checking does... So evaluating first.

You are right, I just did a quick test with a significantly big buffer and it was quick to normalize:
```javascript
var geometry = new THREE.BufferGeometry();
var numElements = 10000000;
var positions = new THREE.BufferAttribute( new Float32Array( numElements * 3 ), 3 );
positions.dynamic = true;
geometry.addAttribute( 'position', positions );

var normals = new THREE.BufferAttribute( new Float32Array( numElements * 3 ), 3 );
normals.dynamic = true;
geometry.addAttribute( 'normal', normals );
geometry.normalizeNormals();
```

**Review by fernandojsg — APPROVED** [review]

**Comment by takahirox** [comment]
Cool.

Let's think those two options if/when we see this checking actually affects the performance.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
