### PR TITLE
Triangle: fix import d.ts

### PR DESCRIPTION
**Pull request by sciecode**
https://github.com/mrdoob/three.js/pull/16596#commitcomment-33736798

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Hint: VSCode for example shows when such imports are missing.

**Comment by Mugen87** [comment]
@mrdoob I think it's best to update `master` and the `npm` package with this fix.

**Comment by mrdoob** [comment]
> @mrdoob I think it's best to update master and the npm package with this fix.

Is it really worth a 0.105.1? Does Typescript break because of this?

**Comment by mrdoob** [comment]
Oh, I just saw #https://github.com/mrdoob/three.js/issues/16617. I guess it does break indeed.

**Comment by spassvogel** [comment]
Thanks guys.

**Comment by mrdoob** [comment]
> @mrdoob I think it's best to update master and the npm package with this fix.

Done!

**Comment by sciecode** [comment]
@mrdoob sorry about the extra work.

@Mugen87 
I was running tests as I made the changes, I'm not entirely sure how I let that one slip. 
Remember fixing this problem locally, I probably retrieved wrong stash.

**Comment by mrdoob** [comment]
No worries!

**Pull request merged**
