### PR TITLE
Docs: Toon Material Browser

### PR DESCRIPTION
**Pull request by mghini**
Added material-browser for MeshToonMaterial documentation page

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/mghini/three.js/ToonMaterialBrowser/docs/index.html#api/en/materials/MeshToonMaterial

**Comment by Mugen87** [comment]
Maybe we should add a note that you often want to use `MeshToonMaterial` with `OutlineEffect` in order to produce the typical visual appearance of a toon shader. AFAIK, `MeshToonMaterial` is always used with `OutlineEffect` in the examples.

**Comment by WestLangley** [comment]
That is not what that material is supposed to look like. One also doesn't use a grass map for a gradient.

Either the example here has issues, or there is a problem with the material.

**Comment by takahirox** [comment]
Gradient map should be like "Gradient Mask_B" in http://technical-eden.blogspot.com/2012/01/gradient-mapping-awesome-way-to-get.html

**Comment by WestLangley** [comment]
>The grass map is also used for other map types in context of other materials which is not ideal:

I think it would be a worthwhile effort to further improve the docs.

IMHO, In the material examples, you don't need all the menu choices from the base classes to be repeated every time.

@takahirox I have never seen a toon shader that supports hotspots, environment maps, or even maps for that matter... Or multiple lights. (Maybe I am missing something?)

A toon shader can be written in a few lines of code, and IMHO, should not have extended `Phong`, which is way too flexible. I would have implemented it like `MeshMatcapMaterial`.

**Comment by Mugen87** [comment]
> A toon shader can be written in a few lines of code, and IMHO, should not have extended Phong, which is way too flexible. I would have implemented it like MeshMatcapMaterial.

I agree. I think we should consider to refactor `MeshToonMaterial` at some point and also `OutlineEffect` so it only supports the toon material.

**Comment by WestLangley** [comment]
>@takahirox I have never seen a toon shader that supports hotspots, environment maps, or even maps for that matter... Or multiple lights. (Maybe I am missing something?)

>A toon shader can be written in a few lines of code, and IMHO, should not have extended Phong, which is way too flexible. I would have implemented it like MeshMatcapMaterial.

/ping @takahirox

**Comment by takahirox** [comment]
OK, let me revisit `MeshToonMaterial`. Not sure if `OutlineEffect` should be specific to toon material tho.

**Comment by WestLangley** [comment]
/bump

I think a refactoring of `MeshToonMaterial` along the lines of ` MeshMatcapMaterial` is worthwhile.

**Comment by Mugen87** [comment]
@WestLangley Let's create a separate issue for this. The PR can be closed now because of #16255

**Pull request closed without merging**
