### PR TITLE
AlphaToCoverage Example: Make wireframe thickness consistent

### PR DESCRIPTION
**Pull request by gkjohnson**
Related issue: #21383

**Description**

Adjust the ATC shader so it the  wireframe lines are a consistent thickness. Thanks for adding in the alpha to coverage option!

image

cc @Mugen87 @WestLangley

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Thanks for doing this!

**Comment by mrdoob** [comment]
Thanks!

**Comment by gkjohnson** [comment]
> The crisp lines of the AtC wireframe are fantastic!

It looks so good!

**Comment by WestLangley** [comment]
The uniform is not initialized correctly in the new material.
```js
uniforms: { 'thickness': { value: API.thickness } },
```

**Comment by WestLangley** [comment]
Should be
```js
uniforms: { 'thickness': { value: API.thickness } },
```

**Pull request merged**
