### PR TITLE
ColladaLoader: Make sure vertex normals are cloned

### PR DESCRIPTION
**Pull request by WestLangley**

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmmm... How did you hit this? Someone on StackOverflow?

**Comment by WestLangley** [comment]
A stackoverflow question got me started on a method to mirror a hierarchical object (with child meshes). I was testing with a Collada model that had quads. I did not test this PR on a model with pentagon faces, however.

I may be over-cloning. Usually we only clone the normals that are repeated.

**Comment by mrdoob** [comment]
I see I see. Thanks!

**Comment by WestLangley** [comment]
Whew!

**Pull request merged**
