### PR TITLE
Modified output of Line.raycast and Points.raycast. Updated docs for RayCaster.

### PR DESCRIPTION
**Pull request by vakorol**
Made the return value of `Line.raycast()` and `Points.raycast()` include `indices` array with a single vertex index, instead of scalar `index`. Included `distanceToRay` in the same return value for `Line.raycast()`. Updated docs for `RayCaster.intersectObject()` to reflect the changes.

### CODE REVIEW

**Comment by WestLangley** [comment]
>include indices array with a single vertex index, instead of scalar index

Can you explain why you made that change?

>Included distanceToRay

Your calculation of `distanceToRay` is in local space, not world space. I think that will lead to confusion.

**Comment by mrdoob** [comment]
>> include indices array with a single vertex index, instead of scalar index

> Can you explain why you made that change?

It's basically so Raycaster output is consistant between `Mesh`, `Line` and `Points`.

See #9634

We can probably still keep `index` for backwards compatibility though.

**Comment by WestLangley** [comment]
>include indices array with a single vertex index, instead of scalar index
>>It's basically so Raycaster output is consistant between Mesh, Line and Points. 

Sorry, I do not understand. This PR is returning an array with a single element. With what is that consistent?

>Your calculation of distanceToRay is in local space, not world space.

That is a problem with this PR.

**Comment by mrdoob** [comment]
Hmm, I was under the impression that `Mesh.raycast()` returned a `indices` array. But I guess the real problem is that the documentation is wrong?

**Comment by vakorol** [comment]
Sorry for late answer.
I realize the problem with @distanceToRay@ now, it's just that it's included in the output when intersecting @Line@, so i thought it would be nice to have it for @Points@, to.

@Mesh.raycast()@ returns @indices@ in the output object, but @Points.raycast()@ and @Line.raycast()@ return @index@. This makes sense, of course, but is a bit confusing that different objects return different sets of attributes.

**Comment by BrianSipple** [comment]
I just wanted to chime in to mention that I have a current project where my team ran in to this same confusion (trying to access `indices` for intersected `Points`, when we should have been looking for `index`). So this change would make things a lot more clear.

@WestLangley I think by "consistency", we're referring to the contract of the return object for any given `raycast` implementation. To me, at least, that's a much more intuitive starting point, and it gives developers the opportunity to separate concerns between a part of their code that does raycasting, a part that defines the specifics of the objects being checked for intersections, and a part that worries about what to make of an `x.raycast()` result.

**Comment by Mugen87** [comment]
As mentioned here https://github.com/mrdoob/three.js/pull/9654#issuecomment-246554278, the documentation was wrong since `Mesh.raycast()` did never produce `indices` in its output object. Hence, the PR does not make sense by modifying the output of `Points.raycast` and `Lines.raycast`.

**Pull request closed without merging**
