### PR TITLE
Raycaster: Set recursive default value to true

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in #21278.

### CODE REVIEW

**Comment by Mugen87** [comment]
This change will also require to update the examples.

**Comment by WestLangley** [comment]
@mrdoob What do you think?

**Comment by mrdoob** [comment]
Sounds good to me! 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Updated the migration guide: https://github.com/mrdoob/three.js/wiki/Migration-Guide#132--133

@WestLangley Are you going to update the examples?

**Comment by WestLangley** [comment]
@Mugen87 OK

**Pull request merged**
