### PR TITLE
FirstPersonControls: Implement Pointer Events.

### PR DESCRIPTION
**Pull request by Mugen87**
see [#20161 (comment)](https://github.com/mrdoob/three.js/pull/20161#issuecomment-678796016).

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev50/examples/webgl_geometry_minecraft.html

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/20191#issuecomment-680936598.

**Comment by Mugen87** [comment]
@mrdoob Should I reopen this PR and #20168?

**Comment by mrdoob** [comment]
We'll have to move them to use pointer events eventually.

The reason I didn't merge this PR and #20168 was because I noticed public variables got renamed and would require investigating the consequences.

**Comment by Mugen87** [comment]
Okay. Feel free to reopen the PRs when you feel the time is ready :+1:

**Pull request closed without merging**
