### PR TITLE
PR for #7335

### LINKED ISSUE #7335: editor failure on extremely big json
Not really big deal, I guess. However, importing 30-something MB STL / exporting geometry fails with
screen shot 2015-10-13 at 12 31 57
If I comment out
```javascript
output = output.replace( /[\n\t]+([\d\.e\-\[\]]+)/g, '$1' );
```
it works, I mean I get 200-something MB JSON ) Maybe it could be good idea to try-catch this line, and proceed with un-replaced string, if it fails?

### PR DESCRIPTION
**Pull request by makc**
fixes #7335

### CODE REVIEW

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7349

**Comment by mrdoob** [comment]
Thanks!

**Comment by leitzler** [comment]
Wouldn't a warning be nice if it fails? Couldn't this silent "retry" upon any exception hide other errors otherwise?

**Comment by makc** [comment]
the warning saying "your json is not pretty"?

**Comment by makc** [comment]
"...because it's fat" :fire:

**Pull request merged**
