### PR TITLE
Examples: Improved lighting in LDrawLoader example

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #22181

**Description**

Enabled `ACESFilmicToneMapping` and increased IBL brightness.

| before | after |
|---|---|
| Screenshot 2021-07-26 at 15 03 18 | Screenshot 2021-07-26 at 15 03 31 |
| Screenshot 2021-07-26 at 15 02 50 | Screenshot 2021-07-26 at 15 03 02 |

/cc @gkjohnson

### CODE REVIEW

**Comment by WestLangley** [comment]
It looks over-bright, and there is no way to control the exposure of "room environment".

Also, `AcesFilmicTonemapping` hue-shifts. The rendered colors should look like the CSS Lego colors. If it looks washed out, then you need to find another solution.

https://www.ldraw.org/article/547

**Comment by WestLangley** [comment]
With this PR.



Screen Shot 2021-07-26 at 12 19 31 PM

LDrawLoader hacked to use MeshBasicMaterial. No tone mapping. Linear output Encoding.

Screen Shot 2021-07-26 at 12 18 49 PM

**Comment by gkjohnson** [comment]
If we continue to use `outputEncoding = sRGBEncoding` I think we need to convert the LDraw colors to Linear color space.

To @mrdoob's comment (https://github.com/mrdoob/three.js/pull/22181#issuecomment-886573255):

> Shouldn't the loader produce linear colors? What if someone wanted to mix Lego models with GLTF models? 🤔

I wouldn't be against it but I think a number of model loaders I think load material and vertex colors in sRGB because that's how they're stored (PLYLoader, ColladaLoader, etc). But having a consistent color space that models are loaded in to would simplify things. If we change the loaders so colors are consistently loaded in Linear color space then I think the default value for `WebGLRenderer.outputEncoding` would need to changed to `sRGBEncoding`.

**Comment by WestLangley** [comment]
And the loader is setting `envMapIntensity` to 0.3 for some materials; 1.0 for others. Why?

**Comment by gkjohnson** [comment]
> And the loader is setting envMapIntensity to 0.3 for some materials; 1.0 for others. Why?

Oh yes sorry -- I don't believe there's a good reason. It should be removed so it defaults to 1.0. I think it was a misunderstood / misguided addition on my part.

**Comment by mrdoob** [comment]
> I think the default value for `WebGLRenderer.outputEncoding` would need to changed to `sRGBEncoding`.

Yes! I want to change that soon. We can try next month?

**Comment by gkjohnson** [comment]
@mrdoob @WestLangley 

> Yes! I want to change that soon. We can try next month?

Would that entail converting all the model loaders to produce linear colors rather than sRGB? And I'm not sure if this has been discussed before but have you considered ferrying around the color space in the `Color` class so the renderer is aware of what the correct conversion should be?

```js
const color = new THREE.Color();
color.set( 0xff0000, sRGBEncoding );
console.log( color.encoding ); // sRGBEncoding
```

**Comment by Mugen87** [comment]
Related #19169.

**Pull request merged**
