### PR TITLE
Proposed example that illustrates a way to convert geometry to buffer geometry

### PR DESCRIPTION
**Pull request by callumprentice**
Found myself wanting to create some THREE.BufferGeometry objects and I did so by creating them first as THREE.Geometry, then converting to THREE.BufferGeometry.

Thought it might be useful for someone else so I made a simple interactive demo.

I think I have the formatted switched to MrDoob style :)

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by callumprentice** [comment]
Yay! :) Thank *you*

**Comment by WestLangley** [comment]
@callumprentice Two suggestions for improvement -- if you are so inclined...

1. I like the sphere with the hearts. That is sufficient. You do not need 11 examples of the same thing. I'd remove the GUI and simplify the code to a single, fixed, example. It is easier for a user to follow. (Also, type `renderer.info` into the console. Geometries are not being disposed of properly. Simplifying to a single example will solve that problem. )

2. We already have `BufferGeometry.fromGeometry()` -- a simple-to-use method. You are not converting a geometry to bufferGeometry. You are constructing a bufferGeometry from pieces of regular geometry. I am concerned that this is going to be confusing to users. Perhaps a better title would be appropriate.

The demo does nicely show how `Geometry` properties relate to `BufferGeometry` attributes.

**Comment by mrdoob** [comment]
Agreed with @WestLangley points.

**Comment by callumprentice** [comment]
Created a pull request with changes as per your suggestions.

https://github.com/mrdoob/three.js/pull/6653

Cheers!

**Pull request merged**
