### PR TITLE
OrbitControls: Added public methods to pan, rotate and dolly camera. …

### PR DESCRIPTION
**Pull request by carlosanunes**
…(#8906)

Continued from: https://github.com/mrdoob/three.js/pull/8919

### CODE REVIEW

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/pull/8919#issuecomment-220376760

**Comment by mrdoob** [comment]
Do we need the `Camera` bit in these new methods?

**Comment by WestLangley** [comment]
>Do we need the Camera bit in these new methods?

I do not think we do.

**Comment by mrdoob** [comment]
@carlosanunes do you mind removing the `Camera` bit from the method names?

**Comment by carlosanunes** [comment]
@mrdoob Done.

**Comment by Mugen87** [comment]
@WestLangley What do you think about this PR? Should `OrbitControls`  expose these functions? Or should we leave this up to the user?

**Comment by looeee** [comment]
I frequently find myself needing to expose these methods so I vote in favour of this change. 

One thing though - is there any need to call `update()` after every change? This means it may end up getting called multiple times per frame.

**Comment by WestLangley** [comment]
`OrbitControls` has had too many cooks in the kitchen and it needs to be rewritten IMO.

I think users can expose these methods themselves, but I don't feel strongly one way or the other.

**Comment by Mugen87** [comment]
I tend to be a little bit restrictive with such changes. So i vote for closing the PR.

**Comment by carlosanunes** [comment]
Defending this PR, this is a very minor change, it is really close to just exposing the methods, no functioning of orbit controls is actually changed. And there seems to be more developers other than me with interest in it.
It is true that 'users' can change this themselves but that, with more or less difficulty, is true of any feature request.

@Mugen87 
Why do you feel uncomfortable with such a change ?

**Comment by Mugen87** [comment]
From my point of view, the entities in the `examples` directory should provide a fundamental framework of program logic. Nothing more. Besides, these entities are intended to be adjusted/enhanced by users for their particular requirements. That's the reason why i'm generally prefer to keep things small, lean and consistent. When merging this, users could expect that other controls have similar APIs.

**Comment by carlosanunes** [comment]
> should provide a fundamental framework of program logic

Hmm... I see what you mean... For consistency then, what has been the general rule of enforcement ?

**Comment by Mugen87** [comment]
I admit that's a hard question :sweat_smile:. The only thing i can say is that my opinion is based on two influencing factors: How other PRs were reviewed/discussed in the past and my personal preference.

**Comment by carlosanunes** [comment]
Well... going against my own interests on this, i'll close this PR, strictly following the guideline you described. I can't say there is a strong reason to make an exception here.

Having said that, the problem may then be that this is in examples/ when it should be in an utils/ folder. In practice devs rely on Orbit Controls for more than just an example (although not being such an important module to have as the loaders).

**Comment by ferrolho** [comment]
I was just making a comment regarding this issue here: https://github.com/mrdoob/three.js/commit/9389bbe78d6ed22521892e8fba0c4ec3aedd68de#commitcomment-26853957

As I say in the comment linked above, I am trying to interface a three.js Scene with my Xbox controller and it would be rather useful to have these methods public.
Is this a good enough argument to make you change your mind, @Mugen87 ? :stuck_out_tongue:

**Comment by EliasHasle** [comment]
@Mugen87 @carlosanunes How about making "secret" (undocumented/unsupported) underscore-prefixed references, following a convention used elsewhere in the library for "private" properties/methods?

**Comment by drcmda** [comment]
> From my point of view, the entities in the examples directory should provide a fundamental framework of program logic. Nothing more. That's the reason why I generally prefer to keep things small, lean and consistent. When merging this, users could expect that other controls have similar APIs too.

@Mugen87 @mrdoob  i know it's too late, but just to give you another perspective. there are those of us that have no idea how the math works, and these examples are everything we have. im trying to move a camera while controls are present for half a day now without any luck so far - and im asking myself - why is something so simple so hard. yes i could fork and expose some functions. but then it's gonna age, three is going to have breaking changes, tracing what broke what will be next to impossible, it will eventually all fall apart. don't get this in the wrong way, the work you all have done is incredible - just perhaps it could be time to move away from that hack-it-yourself mentality, putting more consideration into ease of use. that's usually a good next step if something's technically stable.

**Comment by WestLangley** [comment]
@drcmda 
>I'm trying to move a camera while controls are present

Avoid manipulating the camera when controls are enabled.

```js
controls.enabled = false;
// ...do what you want
controls.enabled = true;
```

**Comment by drcmda** [comment]
thanks west, appreciate it! that bit i have. i thought i could hijack the lerping functions for programmatic dolly/pan and rotate. these are the ones that would can break me.

**Comment by WestLangley** [comment]
Well, if exposing the methods was sufficient to solve your problem, you would not have been stuck for a half-day. So, I guess I do not understand what your issue is.

**Comment by drcmda** [comment]
i have forked primitives before, as i said, they outdate. so i tried lerping the camera myself, but everything i needed is sealed in that class, hence the pull request.

**Comment by h0merjam** [comment]
Would `setPolarAngle` / `setAzimuthalAngle` methods be acceptable?

**Comment by mrdoob** [comment]
@h0merjam I think these sound good 👍

**Comment by forerunrun** [comment]
@homerjam @mrdoob do you think there may be the possibility of using 
```
controls.target.matrix.makeRotationY( USER INPUT );
camera.position.applyMatrix4( controls.target.matrix );
```
or would this interfere with pre existing methods in `OrbitControls`?

**Comment by drcmda** [comment]
we made an implementation for three-stdlib picking the shortest delta angle https://github.com/pmndrs/three-stdlib/pull/65

**Comment by forerunrun** [comment]
@drcmda that's really useful thanks for sharing!

**Pull request closed without merging**
