### PR TITLE
BufferAttribute: Allow 2D `position` data.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #27401, #6288, #8798, #12221, #15009, #19735, #25748

**Description**

Over the past years, different developers wanted to use the library with a 2D `position` attribute. We did not support this so far since we were unsure about the implications of this change.

It turns out that logic that relies on the setter/getter API of `BufferAttribute` (which is true for `BufferGeometry`) can support a 2D `position` attribute with just a few changes. The idea is to apply the same policy as the WebGL and WebGPU implementations. Meaning the `z` component is considered as `0` if not explicitly set.

That means `getZ()` now returns `0` for `vec2` data. And `setZ()` and `setXYZ()` ignore the given z values. This is done for `BufferAttribute` as well as `InterleavedBufferAttribute`. Things like bounding volume, normal or tangent computation via `BufferGeometry` should work with this change as expected.

Edit: `BufferGeometry.applyMatrix4()` and the related transformation methods are an exception since the matrix-vector multiplication requires 3D vectors.

I think it's okay to give this PR a try under the label of an "experimental feature". If we encounter serious issues with 2D `position` data in production, we can reconsider and revert if necessary.

### CODE REVIEW

**Comment by WestLangley** [comment]
If you really think this is advisable, I'd suggest you try what I tried and modify `PlaneGeometry` to use a  2D `position` attribute and see what breaks.

For example, `BufferAttribute.applyMatrix4()` will need to be fixed -- likely by modifying lower-level methods.

**Comment by Mugen87** [comment]
`applyMatrix4()` can only work with `vec3` and not `vec2` (or `vec4`) by definition. I mean how would you multiply a 4x4 matrix with a 2D vector?

We could check the item size of the  `position` attribute and only apply the matrix in the `vec3` case. We could also consider to report a warning and document the limitation to make things more transparent.

That said, after so many requests for this feature I do believe `three.js` should support a `vec2` position attribute even if the support is limited.

**Comment by WestLangley** [comment]
To me, this is a slippery slope. I would advise against saying you support it, while not fully supporting it.

**Comment by Mugen87** [comment]
TBH, I believe this thinking is too restrictive since it prevents us from implementing features which are useful. There is no need a feature must be compatible with *everything* in the engine (which *full support* implies). A warning in `applyMatrix4()` seems sufficient to me.

@Oletus What are your thoughts here?

**Comment by WestLangley** [comment]
>A warning in applyMatrix4() seems sufficient to me.

There are other methods that break. `geometry.rotateX()` is the first one I noticed. I did not attempt to determine the complete list.

**Comment by Mugen87** [comment]
The transformation methods all rely on `applyMatrix4()` so devs should see the warning.

**Comment by Mugen87** [comment]
> We could automatically update the item size from 2 to 3 in applyMatrix4() by resizing the attribute if necessary. If devs want that, it can be added at any time.

I've added a separate commit that implements that. So 2D data are now gracefully handled when devs want to transform their geometry.

**Comment by Mugen87** [comment]
I've used the last two weeks to take one step back and reconsider this change. 

It's true that you can save memory by enabling a `vec2` position attribute but on the other hand the potential savings are minor and the additional complexity in the geometry classes larger than originally expected. The buffer attribute resize to `vec3` when devs attempt to transform geometry data is also unfortunate.

At this point I have the feeling we can't implement 2D vertex data in a satisfying way. The current approach feels too "hacky", imo. At least for now I'm not further pursue this topic and close the PR.

**Pull request closed without merging**
