### PR TITLE
Clarify .clone() action

### PR DESCRIPTION
**Pull request by paulmasson**

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
What other properties should be copying though?

**Comment by paulmasson** [comment]
Vertex colors, for one. Unclear to me why you don’t just copy all the properties that have been defined.

**Comment by Zob1** [comment]
I ran into this issue just today. In my project I define a custom property in meshes that I call "material_index". It selects which material I use from an array of materials. This is for in-game assets that use multiple meshes and materials. 

I do this because cloning an object doesn't create a clone of the material it uses. So I have to do it manually during the asset-cloning process if I want to have multiple copies of an asset that can have its material manipulated without affecting the other copies of that same asset.

**Comment by Zob1** [comment]
Sorry, forgot to specify that each time I clone an object, I have to manually copy the custom property to the new object because clone() won't do it. It would be nice if clone() had some extra parameters for this kind of process. Maybe a Boolean or two or three for material cloning, geometry cloning, and property cloning. :)

**Comment by mrdoob** [comment]
Ohm, we can't copy custom properties. The code would become a nightmare if we tried to support all the custom properties people can come up with.

**Pull request merged**
