### PR TITLE
FBXLoader: Set sRGBEncoding for various texture types.

### PR DESCRIPTION
**Pull request by looeee**
As discussed in #14419, it would be best if loaders set texture encoding to `THREE.sRGBEncoding` by default, however only `GLTFLoader` currently does this.  Unfortunately, changing this now for other loaders would be a breaking change.

Instead I've added a flag to the `FBXLoader`. Defaults to false (previous behaviour), while setting `fbxLoader.sRGBTextureEncoding = true` will now set ` THREE.sRGBEncoding` on the diffuse map, emmissive map, and specular map if they are present. 

Enabling this flag will also require setting `renderer.gammaOutput = true;` for correct results. 

Unlike glTF, FBX format does not specify the texture encoding that should be used, so it's probably best that this is set by a flag rather than be default behaviour anyway. 

@donmccurdy I've followed the behaviour of `GLTFLoader` and only set the encoding for `diffuseMap`, `emissiveMap` and `specularMap`. Is this correct?

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks for looking into this! `envMap` should be included as well; glTF does not include environment maps at this point. Note that the Mixamo example will change noticeably with gammaOutput enabled, because it doesn't use textures at all.

I do like the idea of exposing an option for correct colorspace and lighting. But I wouldn't use the word "encoding" here, per https://github.com/mrdoob/three.js/issues/11337, we hope to rename that property on textures soon. Perhaps:

- loader.sRGBTextureColorSpace = true
- loader.textureColorSpace = THREE.sRGBEncoding
- loader.physicallyCorrectLighting = true

A couple references on the (lack of) colorspace clarity in FBX:

- [Vertex colors: sRGB, linear, ???](https://forums.autodesk.com/t5/fbx-forum/vertex-colors-srgb-linear/td-p/7985264) (unanswered)
- [Color management in 3DS Max marked for "future consideration"](https://forums.autodesk.com/t5/3ds-max-ideas/implement-color-management-in-3ds-max-support-for-icc-luts-etc/idi-p/6790724)

**Comment by looeee** [comment]
I like the name `physicallyCorrectLighting`. However it's likely to cause confusion with the [WebGLRenderer.physicallyCorrectLights](https://threejs.org/docs/#api/renderers/WebGLRenderer.physicallyCorrectLights), which as far as I can make out is related to making lights have a physically correct fallof in a real-world sized scene, rather than anything to do with color space. 

Let's go with `loader.textureColorSpace = THREE.sRGBEncoding`, it seems like the most flexible.

**Comment by looeee** [comment]
Before (right ) and after (left) comparison. 

srgb_comparison

**Review by donmccurdy — APPROVED** [review]

**Comment by looeee** [comment]
@mrdoob are there any issues with this or can it be merged?

**Comment by looeee** [comment]
/ping @mrdoob  

Is there some issue with adding color management to the loader? If so let me know and I'll close this.

**Comment by mrdoob** [comment]
I think I would avoid having the additional flag. I think it's okay for this to be a breaking change.

**Comment by looeee** [comment]
> I think I would avoid having the additional flag.

Yeah, I prefer that too. I've removed the flag and this is now done automatically:

``` js
material.map.encoding = THREE.sRGBEncoding;
material.emissiveMap.encoding = THREE.sRGBEncoding;
material.envMap.encoding = THREE.sRGBEncoding;
material.specularMap.encoding = THREE.sRGBEncoding;
```

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Updated the migration guide with this change:

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r106--r107

**Pull request merged**
