### PR TITLE
Controls: Move into core.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: https://github.com/mrdoob/three.js/pull/29079#issuecomment-2288145594

**Description**

As suggested in https://github.com/mrdoob/three.js/pull/29079#issuecomment-2288145594, the PR moves `Controls` into core.

### CODE REVIEW

**Comment by arodic** [comment]
Wow!!! I’ve programmed my hibernation chamber to wake me up when this PR finally merges. I did not expect to wake up as soon as 2024!!!

Please forgive my snark but I do wonder what has changed?

I’ve made multiple efforts over the years to refactor controls that had a lot of duplicated logic and same bugs reappearing across multiple controls. The argument against it was that controls are just “examples” and don’t belong to threejs core. Has this stance finally changed???

**Comment by mrdoob** [comment]
Only `Controls.js` has been added to core. The actual controls files remain in "examples" 😇

**Comment by arodic** [comment]
Same thing I’ve proposed years ago. Anyway, super stoked this is finally happening!

**Comment by mrdoob** [comment]
Slowly but surely!™ 😁

**Comment by pailhead** [comment]
I hope @arodic doesn’t mind me sharing this, I’ll delete it if so.

We know each other from the late early 2000s from a 3d art forum. We both made a ton of 3d models at the time. 15 years later, we’re both in SF working on similar things. Granted he’s was in Pixar and Google, I was kinda just learning how to program, squatting and dumpster diving. But we both did webGL! . A bit later, a 23andMe test shows that we are related :)


So I think that this may be genetics  🤣 

The world may have benefited if we listened to @arodic half a decade ago, but it’s never too late!

**Pull request merged**
