### PR TITLE
refined large screen layout & type scale

### PR DESCRIPTION
**Pull request by yuinchien**
Thanks for all the feedback on the design update. I understand people have different preferences and habit of using the docs, this is the latest update to address the responses from users. Changes:

– Refined type scale (switched back to px from rem to make sure numbers are always integers for diff screen sizes)
– Refined large screen layout to improve readability

Change takes time, I hope people can give the new design some time to get used to. PR is welcome down the line to continue improvements!

### CODE REVIEW

**Comment by gkjohnson** [comment]
https://raw.githack.com/mrdoob/three.js/refine-design/docs/#api/en/core/Object3D

**Comment by looeee** [comment]
Getting there! 

I think that this is perfect when viewed on my phone. Unfortunately, I never use the three.js docs on my phone, and it's still not quite right, to me at least, on bigger screens. Mainly there's not enough differentiation between heading sizes/fonts and the spacing is still a bit off, making it hard to scan quickly. 

**Left**: this PR. 

**Right**: Browser defaults for `margin-top`, `margin-bottom`, `font-size`, `line-height`, `font-weight`, with a bit of extra `<p.margin-bottom>` . 

comp

The main differences that make the defaults easier to scan, are the reduced spacing in the menu, the bold fonts in the `<h1>`, and the more consistent decrease in size and spacing between heading levels. 

Things I'd change from browser defaults: Heading could be increased in size a bit, perhaps a bit less space between `<h3>` and content, and slightly increase `<p.line-height>`.

**Comment by looeee** [comment]
By the way, I just opened the current [Object3D doc page](https://threejs.org/docs/#api/en/core/Object3D) fullscreen, and found myself instinctively stepping back from my screen so that I could see it properly. 

After this PR I no longer feel the need to do that, so this is already a big improvement.

**Comment by yuinchien** [comment]
There's an issue on iOS for setting height for iframe, which results in the header doesn't lock at the top. https://stackoverflow.com/questions/34320046/iframe-height-issues-on-ios-mobile-safari

An *iframe-wrapper* was added to fix the height issue. You can test the latest link on iOS. 
https://raw.githack.com/mrdoob/three.js/refine-design/docs/#manual/en/introduction/Creating-a-scene

Scrolling the panel is now smooth on iOS too. The new main.css includes smooth scrolling for the landing page as well.

**Comment by mrdoob** [comment]
In my system...

Before:

Screen Shot 2019-06-20 at 11 20 00 AM

After:

Screen Shot 2019-06-20 at 11 20 20 AM

Notice the double scrollbar.

After many years on MacOS and continuously being bitten by the issue of MacOS blindfolding me of scrollbars being there with its auto-hide feature I decided to force-enable scrollbars always.

Screen Shot 2019-06-20 at 11 24 01 AM

**Comment by yuinchien** [comment]
@mrdoob Does the double scrollbar occur because of this change https://github.com/mrdoob/three.js/pull/16637/commits/d1474e8794eacbf6e2ad6194b55dabd3d5d56629? Because on iOS setting height for iFrame is buggy, i added a wrapper in order to fix the header at the top. The double scrollbar is not good, we can revert this commit.

**Comment by WestLangley** [comment]
For a separate PR, in the examples tab, flipping from portrait to landscape on an iPhone after the page has loaded results in all sorts of problems.

**Comment by mrdoob** [comment]
@yuinchien that seems to be the case:

https://raw.githack.com/mrdoob/three.js/40783c3447203b876b317519bf675355ca44f884/docs/index.html#api/en/core/Object3D

Screen Shot 2019-06-20 at 1 06 34 PM

**Comment by mrdoob** [comment]
@WestLangley Uh oh!

**Comment by WestLangley** [comment]
>@WestLangley Uh oh!

I forgot to mention... it is looking much better. :-)

**Comment by mrdoob** [comment]
Double scrollbar is now gone! 🙌

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
