### PR TITLE
SGILoader - Parses Silicon Graphics Image files into THREE.DataTexture

### PR DESCRIPTION
**Pull request by a-drew**
Parses the Silicon Graphics Image standard( .rgba .rgb .bw .sgi .int .inta) into a usable three js texture regardless of RLE strorage or verbatim.

### CODE REVIEW

**Comment by WestLangley** [comment]
Your example tests one of three new .rgb files. Should all three be tested?

**Comment by mrdoob** [comment]
> Your example tests one of three new .rgb files. Should all three be tested?

You mean included in the example?

**Comment by WestLangley** [comment]
Yes.

**Comment by crimsonFuckr** [comment]
I was planning to add a button that would cycle through them.

**Comment by mrdoob** [comment]
Maybe something similar to the TGA example with some objects using the textures?
http://threejs.org/examples/webgl_materials_texture_tga.html

**Pull request closed without merging**
