### PR TITLE
remove comments and unnecessary newlines from glsl files

### PR DESCRIPTION
**Pull request by Rich-Harris**
Via https://github.com/mrdoob/three.js/pull/9381#issuecomment-234681602. This is something that could conceivably be moved into a Rollup plugin (rollup-plugin-glsl), though I thought it would be easier to start with an inline transformer – perhaps ultimately a plugin could handle other forms of minification and optimisation (via https://github.com/aras-p/glsl-optimizer perhaps?) though I'm not familiar with enough with the various options to have an opinion.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet! I wouldn't worry about glsl-optimizer just yet.

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
Can we figure out a way to make the shaders included in rollup?  I bet if we did things properly we could move all of the examples/js files into the main source tree and have them conditionally included if they are used.

That would be so amazing.

**Comment by bhouston** [comment]
In fact C++ libraries are generally like that.  You have tons of headers, but you only include the headers you need for the specific features you want to use.

But we need to then make it easy for others to use their own build tools that use either rolllup or webpack (v2 I understand also had tree shaking.)

**Comment by mrdoob** [comment]
I wonder how many people use build systems vs how many people just include `three.min.js`...

**Comment by GGAlanSmithee** [comment]
@mrdoob Users who have just included `three.min.js` will still be able to do so. That bundle will be complete (as in that it will contain all code). The modularization related functionality discussed here and other PR's will just enable some major size optimizations for the tradeoff of  bundling `three.js` yourself.

**Comment by bhouston** [comment]
@mrdoob:
> I wonder how many people use build systems vs how many people just include three.min.js... Wouldn't want to force the build system approach to the later group...

Modules are a huge improvement for allowing conditional compilations.  It's pretty neat stuff.  I think that the modules will be used by professionals.  Hobbiest and students will still use the pre-build three.min.js file because it is easier to grasp. :)

**Comment by mrdoob** [comment]
Yes, I know. I'm referring to the examples.

**Pull request merged**
