### PR TITLE
Docs: and tests for textures/FramebufferTexture

### PR DESCRIPTION
**Pull request by epreston**
Related issue: none.

**Description**

Add example code, link to full example, add property that differs from base class.
Add missing properties and describe how they differ from the base class, Texture.
Add unit test file for textures/FramebufferTexture.

### CODE REVIEW

**Comment by epreston** [comment]
To ensure clean pull requests, I should wait for this to be reviewed before submitting the cleanup for all of Textures.

**Comment by mrdoob** [comment]
Seems like the PR has conflicts.

**Comment by epreston** [comment]
Sorted. I was worried about this one.  Nailed down the process to steam ahead.

**Comment by mrdoob** [comment]
Now it says `Files changes: 0` 🤔

**Comment by epreston** [comment]
Yeah, the change set for "test texture cleanup" built on these changes, must have contained them.

I'm going to close this one so we have nice clean commits.

**Pull request closed without merging**
