### PR TITLE
Add setOverrideMimeType() to XHRLoader

### PR DESCRIPTION
**Pull request by takahirox**
This PR adds `setOverrideMimeType()` to `XHRLoader`.
Users can specify charcode of downloaded file with it.

I need this ability because
VPD file which includes `MMD` pose data is generally shift_jis.
To load the file correctly
I need to set `request.overrideMimeType( 'text/plain; charset=shift_jis' );`

### CODE REVIEW

**Comment by mrdoob** [comment]
How about calling it `setMimeType()` instead?

**Comment by takahirox** [comment]
Agreed! I'll update soon

**Comment by mrdoob** [comment]
Ops, you'll have to pull from `dev` first. I've just renamed XHRLoader to FileLoader... 😇

**Comment by takahirox** [comment]
I've done!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
