### PR TITLE
Examples: Remove revision log from all renderers.

### PR DESCRIPTION
**Pull request by zarov**
Kind of follow #17342 

I'm a little confused where to edit this, but if I understood correctly, those `jsm` should be good.

### CODE REVIEW

**Comment by Mugen87** [comment]
> I'm a little confused where to edit this, but if I understood correctly, those jsm should be good.

You actually have to edit the files in the `js` directory and then run `node utils/modularize.js` in order to generate the `jsm` version. 

Um, I think I would completely remove the console.logs instead.

**Comment by zarov** [comment]
> You actually have to edit the files in the js directory and then run node utils/modularize.js in order to generate the jsm version.

Ok, thanks for the info.

> Um, I think I would completely remove the console.logs instead.

Ok for me, I'll wait a bit if someone wants to keep them.

**Comment by zarov** [comment]
Updated, I pushed only the `js` files, not sure if I need to add the generated `jsm` or if it is an automated task ?

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Normally, you do this by yourself. By executing `node utils/modularize.js`. However, we can also do this for you.

**Comment by zarov** [comment]
No problem, it's done !

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
