### PR TITLE
KTX2Loader: Support ZSTD-compressed DataTexture and DataTexture3D

### PR DESCRIPTION
**Pull request by donmccurdy**
Allows KTX2Loader to support ZSTD-compressed DataTexture and DataTexture3D with raw formats (u8, f16, f32).

I have also removed the UMD build, `examples/js/KTX2Loader.js`. At this point it would depend on three globals — WorkerPool, KTX, and ZSTDDecoder — which is starting to feel excessive. Originally it was added to help get support in A-Frame (https://github.com/aframevr/aframe/issues/4919) but this hasn't happened, and I think it may be easier just to make a custom KTX2Loader build for A-Frame if necessary.

This type of compression is quite useful for things like LUTs — the table below shows example sizes for a typical 65x65x65 3D LUT texture.

| format | size |
|--------|------|
| .cube  | 7.1 MB | 
| .ktx2 + f32  | 1.0 MB |
| .ktx2 + f32 + zstd | 90 KB |

/cc @drcmda

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> This type of compression is quite useful for things like LUTs — the table below shows example sizes for a typical 65x65x65 3D LUT texture.

/fyi @elalish

**Comment by elalish** [comment]
This is cool! Is there a tool for compressing a LUT into KTX2?

**Comment by donmccurdy** [comment]
I don't have the ZSTD encoder working yet (use ktxsc to add compression in the meantime) but yeah, WIP:

https://lut-to-texture.glitch.me/

**Pull request merged**
