### PR TITLE
UUID: fix range

### PR DESCRIPTION
**Pull request by munrocket**
Math.random() gives a values in range [0, 1), that's why previous version never return 0xFF in 4 places. Example: ( 0.9999999999999999 * 0xffffffff ) & 0xff -> 254

### CODE REVIEW

**Comment by munrocket** [comment]
@mrdoob this is improvement.

**Comment by makc** [comment]
@mrdoob btw, was there an explanation anywhere why do uuid-s have to follow rfc 4122?

**Comment by munrocket** [comment]
I checked various uuid's implementations with benchmarks and can confirm that current algorithm pretty fast. For example it's faster than algo based on `date.now() / performance.now() / crypto.getRandomValues(..) / DataView.getUint16(..)`. Right now uuid's used in node shaders and gltf loader seems too. The only thing that I am not checked is the ability to replace the string with `new ArrayBuffer(16)`.

But yeah uuid based on time or uuid based on RFC 4122 v1 looks more robust than RFC 4122 v4.

**Comment by Mugen87** [comment]
Better to strictly stick to an [established implementation](https://github.com/tflanagan/node-rfc4122/blob/f9fc54a3f7c9552b8e4f69cae1ceb141c7033fa7/rfc4122.js#L98-L109) than applying custom changes to it. Closing.

**Pull request closed without merging**
