### PR TITLE
Ensure alphaTest is formatted as a float

### LINKED ISSUE #13976: Shader compilation error with alphaTest=1.0
When alphaTest is 1.0, fragment shader compilation fails. Filing based on comments in https://github.com/mrdoob/three.js/issues/7125#issuecomment-384721639.

```js
var material = new THREE.MeshStandardMaterial( {
      color: 0x00ffff, 
      alphaTest: 1.0
} );
```

```
THREE.WebGLShader: gl.getShaderInfoLog() fragment ERROR: 0:986: '<' : wrong operand types - no operation '<' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const int' (or there is no acceptable conversion) ...
```

Demo: https://jsfiddle.net/donmccurdy/6L8g7eh6/1/
three.js r92

See glTF file in this ZIP: [screw.zip](https://github.com/mrdoob/three.js/files/1968102/screw.zip)

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #13976. As discussed in #13977.

### CODE REVIEW

**Review by takahirox — APPROVED** [review]

**Comment by WestLangley** [comment]
I considered that, but it is too limiting. Suppose the value is 0.9375...

**Comment by WestLangley** [comment]
With a float `DataTexture`, the alpha channel can take values greater than 1, as can `alphaTest`.

**Comment by mrdoob** [comment]
I see... I just find the current code a little bit hard to decipher.

Is this more clear?

```js
parameters.alphaTest ? '#define ALPHATEST ' + parameters.alphaTest + ( parameters.alphaTest.toString().length === 1 ? '.0' : '' ) : '',
```

**Comment by WestLangley** [comment]
Thing is, `alphaTest` can be any integer value, and hence have any number of digits. How about:
```javascript
Number.isInteger( parameters.alphaTest );
```

**Comment by mrdoob** [comment]
Yep! That one sounds good to me 👌

**Comment by WestLangley** [comment]
I've messed up... Maybe you can cherry-pick?

**Comment by takahirox** [comment]
Two cents. IE on desktop doesn't seem to support `Number.isInteger`. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

Should we add polyfill?

**Comment by mrdoob** [comment]
> Two cents. IE on desktop doesn't seem to support `Number.isInteger`. 

I guess `Math.floor( parameters.alphaTest ) === parameters.alphaTest` does the same?

**Comment by WestLangley** [comment]
I vote for what I had originally:
```javascript
parameters.alphaTest ? '#define ALPHATEST ' + parameters.alphaTest + ( parameters.alphaTest % 1 ? '' : '.0' ) : '',
```

**Comment by WestLangley** [comment]
Closing in favor of #14028.

**Pull request closed without merging**
