### PR TITLE
Simple, Fast Float32Array-based Math classes: Vector2/3/4 + Color

### PR DESCRIPTION
**Pull request by bhouston**
I've done a third Float32Array-based math refactor to allow for easy usage of the math classes directly on Float32Arrays.  This time I used what I learned was fast (this.array + this.offset so that one does no view or buffer allocations per object) and I've combined that with @gero3's simple extension method to minimize the changes to the classes themselves.

The end result is this PR that is as fast as ThreeJS used to be, but it allows for the ThreeJS math types to live within Float32Arrays with Vector3 just being a helper class you can "attach" (see function with this name) to Float32Arrays when needed.

The best part of this PR is that it makes ThreeJS smaller. :)

### CODE REVIEW

**Comment by bhouston** [comment]
This PR introduces the idea of "attach" in math primitives, it means that you can have a primitive directly represent the elements in a larger array.  I used it to simplify Box.fromArray from this:

```
	setFromArray: function ( array ) {

		this.makeEmpty();

		var minX = + Infinity;
		var minY = + Infinity;
		var minZ = + Infinity;

		var maxX = - Infinity;
		var maxY = - Infinity;
		var maxZ = - Infinity;

		for ( var i = 0, il = array.length; i < il; i += 3 ) {

			var x = array[ i ];
			var y = array[ i + 1 ];
			var z = array[ i + 2 ];

			if ( x < minX ) minX = x;
			if ( y < minY ) minY = y;
			if ( z < minZ ) minZ = z;

			if ( x > maxX ) maxX = x;
			if ( y > maxY ) maxY = y;
			if ( z > maxZ ) maxZ = z;

		}

		this.min.set( minX, minY, minZ );
		this.max.set( maxX, maxY, maxZ );

	},
```

To this:
```
	setFromArray: function ( array ) {

		this.makeEmpty();

		var p = new THREE.Vector3( array, 0 );

		for ( var i = 0, il = array.length; i < il; i += 3 ) {

			this.expandByPoint( p.attach( array, i ) );

		}

	}
```

**Comment by gero3** [comment]
Is the allocator still nessecary now that we can attach the vectors to arrays?? 
I'm starting to think that since we already advice not to create many vector objects, it should have a minimal impact on most code while making sure that memory management is simple. I think we should provide a way to create vector pools but in the library itself, we should keep things simple enough. The fact that people would be able to keep a 1000 times more memory then they use scares me a bit.

**Comment by gero3** [comment]
Actually for the pool we could mostly reuse the allocator logic in here, only allowing fixed length when created with a specific length and one with exponential growth to decrease the amount of allocations.
I was thinking of starting with 32, 64,128 en so on.

**Comment by bhouston** [comment]
@gero3, I do not believe the number of allocations of Float32Array matter a huge amount.  I think that mostly the reason for the allocator was to amortize the cost of the Float32Array creation across more than one Vector3.  I found that a new Float32Array() costs a fair bit.  But if one uses an allocator, one quickly reduces that cost.

Assume F is the cost of allocating Float32Array.  If one uses blocksize of 1024, then one can create 330 Vector3s, now the cost of using a Float32Array is F / 330 (e.g. F / 1024 / 3 ), which is nothing.  In fact we could use blocksizes of even 256 floats, because than the cost of using Float32ARray is F / 85 (e.g. F / 256 / 3 ), which is already nearly nothing.  There is a cost of using an allocator intermediary that is non-trival, thus using large block sizes to ultra-reduce the cost of Float32Array allocations across Vector3s is likely not useful.

The exponential blocksize growth is usually used for data structures that require copies upon each growth.  They use that doubling to amortize the copy cost as the array grows.

In our case I think small Float32Array are most likely to end up unused than large arrays and thus most likely to be GC'ed.  So I favor small arrays just sufficient to amortize the cost of creating new Float32Arrays to be insignificant to the fixed cost of the allocator intermediary.

**Comment by bhouston** [comment]
The best example to see that this PR is still slightly slower for Vector3 creation as opposed to what is in ThreeJS right now is this one, but only if you run it locally to discount the influence of internet speed:

http://ci.threejs.org/api/pullrequests/8672/examples/webgl_geometry_large_mesh.html

Before this PR I am seeing load times of ~100ms, and after I am seeing ~150ms load times.  This is because this examples uses BinaryLoader which creates tons Vector3s.  The new allocator approach does incur some overhead because it is an extra function call per new Vector3().

BinaryLoader could be made many times faster if we use the new Vector3.attach functionality appropriate with large Float32Arrays.

**Comment by mrdoob** [comment]
> This PR introduces the idea of "attach" in math primitives, it means that you can have a primitive directly represent the elements in a larger array.  I used it to simplify Box.fromArray from this:

We seem to be going back and forth with that code...

https://github.com/mrdoob/three.js/commit/55ad1f48a168c988d576f214099ac1100fd037da#diff-f0786190348a02468cbe264506044e6c

**Comment by mrdoob** [comment]
Instead of magically trying to implement it underneath everything, it may be more manageable to start doing `Vector2Array`, `Vector3Array`, ... and slowly replace where needed.

Something along the lines of what @gero3 previously suggested...

```js
THREE.Vector3Array = function ( buffer, offset ) {
    this.array = new Float32Array( buffer, offset, 3 );
};

THREE.Vector3Array.prototype = new THREE.Vector3();

Object.defineProperties( THREE.Vector3Array.prototype, {
	x: {
		get: function () {
			return this.array[ 0 ];
		},
		set: function ( value ) {
			this.array[ 0 ] = value;
		}
	},
	y: {
		get: function () {
			return this.array[ 1 ];
		},
		set: function ( value ) {
			this.array[ 1 ] = value;
		}
	},
	z: {
		get: function () {
			return this.array[ 2 ];
		},
		set: function ( value ) {
			this.array[ 2 ] = value;
		}
	}
} );
```

**Comment by mrdoob** [comment]
> The best example to see that this PR is still slightly slower for Vector3 creation as opposed to what is in ThreeJS right now is this one, but only if you run it locally to discount the influence of internet speed:

> http://ci.threejs.org/api/pullrequests/8672/examples/webgl_geometry_large_mesh.html

> Before this PR I am seeing load times of ~100ms, and after I am seeing ~150ms load times.  This is because this examples uses BinaryLoader which creates tons Vector3s.  The new allocator approach does incur some overhead because it is an extra function call per new Vector3().

On top of performance, it'll be interesting to compare memory usage before/after too.

**Comment by gero3** [comment]
```javascript

THREE.Vector3Array = function ( array, offset ) {

    this.array = array, 
    this.offset = offset;

};

Object.defineProperties( THREE.Vector3Array.prototype, {
    x: {
        get: function () {
            return this.array[ this.offset ];
        },
        set: function ( value ) {
            this.array[ this.offset ] = value;
        }
    },
    y: {
        get: function () {
            return this.array[ this.offset + 1 ];
        },
        set: function ( value ) {
            this.array[ this.offset + 1 ] = value;
        }
    },
    z: {
        get: function () {
            return this.array[ this.offset + 2 ];
        },
        set: function ( value ) {
            this.array[ this.offset + 2 ] = value;
        }
    }
} );

THREE.Vector3Array.prototype.set = function() { ... };
THREE.Vector3Array.prototype.setScalar= function() { ... };
THREE.Vector3Array.prototype.setComponent = function() { ... };
....

THREE.Vector3 = function() {
    this.array = new Float32Array(3);
    this.offset = 0;
}

THREE.Vector3.prototype = new THREE.Vector3Array();
```

@mrdoob @bhouston Wouldn't this be an easy solution?? Making the Vector3Array the baseclass makes it easy to create Vector3s and also doesn't switch from doubles to singles now.

**Comment by mrdoob** [comment]
Yep! That's definitely a nice solution. I just wonder how much the getter/setter impact would have.
Also, as previously stated, `new Float32Array()` is slow.

**Comment by gero3** [comment]
I'll try to add a version which updates this.
And check it for performance

**Comment by bhouston** [comment]
I am dissappointed with this whole approach, it is not faster in any place.  :/  I want to be able to argue in favor of it, but it isn't faster.

And even the Vector3.attach() idea, while I like it conceptually it is slower than going Vector3.fromArray().  I think that Vector3 with member x, y, z floats is well optimized by the Chrome to use registers or something like that.

So I am feeling that my efforts on Monday/Tuesday were actually not generally useful in any way except for ruling out ideas as not real improvements. :/

I really do want to argue that there is something redeemable about this approach, but I fear there isn't.  It is just slower, not much slower, but slower.

We should still never to keep around a lot of Vector3s, they are inefficient in terms of memory.  But the current Vector3 structure is the fastest for calculation even when using it from a large Float32Array (fromArray/toArray is faster than "attach".)

I think that one improvement may be to allow for one to quickly turn a set of Vector3s into a large Float32Array so that one can adopt Float32Arrays everywhere for storage even in cases were one doesn't know the final size of the Vector3 array.  I'll make a PR with this, I call it a block array and is somewhat similar to the Allocator pattern of @mrdoob and @tschw .

**Comment by tschw** [comment]
As one last thought / question: Did you consider alignment in your tests? Tightly packing `Vector3`s makes them cross cache lines. Leaving one 32-bit value of padding would avoid that problem - and maybe is something that took a toll on the approach.

**Comment by bhouston** [comment]
@tschw I just tried having Vector3/Vector2/VEctror3 all requests arrays of 4 floats each (16 byte alignment) and it made no difference.

**Comment by bhouston** [comment]
The main issue is that all mathematics operations seem slowing when working on Float32Array buffers than with immediate x,y,z floats.  I think it may have to do with how the compiler is optimizing things.  Probably reading/writing to main memory more or something like that with using Float32Arrays.  I guess I need an /FA switch for Chrome: https://msdn.microsoft.com/en-us/library/367y26c6.aspx

**Comment by tschw** [comment]
> The main issue is that all mathematics operations seem slower when working on Float32Array buffers than with immediate x,y,z floats. I think it may have to do with how the compiler is optimizing things.

I think I once read something about there being some call overhead into native code - C functions always need to be `CALL`ed, I guess. Not sure that's how typed arrays are currently implemented, though.

Independent of that, there can be views, so there can be side effects. Those are hard to track and knock out optimizations. Example:
```javascript
x[0] = 1;
func(); // may change x[0] through a view
x[1024] = x[0] * 0.5; // if can't happen would optimally be x[1024] = 0.5;
```

> I guess I need an /FA switch for Chrome

V8  has several switches to trace JIT activity.

https://gist.github.com/kevincennis/0cd2138c78a07412ef21

OTOH a slight performance loss with Chrome would probably be acceptable when it yields a boost with other browsers. They usually need the extra speed more badly.

> I think that local variables, and then next object member variables, beat large Float32Arrays arrays because more optimizations are available to the compiler -- something like that feels like what I am fighting. 

Yes, this makes a lot of sense.

Actually the engines create a packed memory layout for the objects. It's what the whole "hidden type business" is all about. Also, JS `Array`s are being typed based on their contents. I once read into that code, it's quite impressive. Typed arrays appeared to be handled as second-class citizens of sorts.

> Probably smart register usage is beating reading/writing to main memory all the time.

X86s not have sooo many registers :), although in case it's about `CALL`s would still be a close enough way to look at it - even with a pure stack machine, since in that case a specific layout of the data is enforced - on the stack - other than with custom code generation, where the data can be used wherever it wants to be (based on the surrounding code).

**Pull request closed without merging**
