### PR TITLE
WebGLState: Use getParameter() to detect current scissor/viewport.

### LINKED ISSUE #21824: Three.JS WebGLRenderer fails to create when canvas is not initialized.
**Describe the bug**
I'm using Expo React-Native with Three.JS, and just recently noticed a new bug that happens when I'm initializing the Three.JS renderer. ````TypeError: null is not an object (evaluating 'gl.canvas.width')````.

Same as mentioned in [this thread](https://github.com/expo/expo-three/issues/202).

I've pinpointed the source of the issue to be due to this change https://github.com/mrdoob/three.js/commit/f5c6b1c944a2dba2c7abb9fb780719a8fbe46ab0, specifically

The changing of the following lines in its initialization from
````
	const currentScissor = new Vector4();
 	const currentViewport = new Vector4();
````
to
````
 	const currentScissor = new Vector4( 0, 0, gl.canvas.width, gl.canvas.height );
 	const currentViewport = new Vector4( 0, 0, gl.canvas.width, gl.canvas.height );
````

I've tested by replacing these lines with the original ones (the Vector4 without parameters) and this issue is gone.

I'm filing this issue to ask if it will be ok if I create a pull request to change these lines to be
````
 	const currentScissor = gl.canvas ? new Vector4( 0, 0, gl.canvas.width, gl.canvas.height ) : new Vector4();
 	const currentViewport = gl.canvas ? new Vector4( 0, 0, gl.canvas.width, gl.canvas.height ) : new Vector4();
````
This change causes everything to work again.

**To Reproduce**

1. Go to https://snack.expo.io/@switt/threejs-renderer-initialization-bug-example
2. Use a mobile device running Expo Go client to scan the QR code to run it.
3. See Alert "Renderer failed", with error message of "null is not an object (evaluating 'e.canvas.width')"
4. Change package.json version of "three" to something like "~0.122"
5. See a spinning cube.

***Code***

```tsx
import { ExpoWebGLRenderingContext, GLView } from 'expo-gl';
...
      <GLView
        style={{ flex: 1 }}
        onContextCreate={async (gl: ExpoWebGLRenderingContext) => {
          const {
            drawingBufferWidth: width,
            drawingBufferHeight: height,
          } = gl;

          const renderer = new Renderer({ gl }) // This will fail
          renderer.setSize(width, height)
          renderer.setClearColor(sceneColor)
      }}
/>
```

***Live example***

* [expo snack](https://snack.expo.io/@switt/threejs-renderer-initialization-bug-example)

**Expected behavior**

- Renderer created successfully

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Mobile Expo React-Native, SDK 39-41
 - OS: iOS and Android
 - Browser: Expo GLView React-Native
 - Three.js version: "^0.128.0" (not sure what last working version was, but 0.122 did work)

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #21824.

**Description**

As suggested in https://github.com/mrdoob/three.js/issues/21824#issuecomment-840763153.

### CODE REVIEW

**Comment by gkjohnson** [comment]
Looks good! `gl.canvas` is also used in the reset function [here](https://github.com/mrdoob/three.js/blob/e8f2565c6df9ad41d8c202793eabc712ecaf7a00/src/renderers/webgl/WebGLState.js#L984-L985) and [here](https://github.com/mrdoob/three.js/blob/e8f2565c6df9ad41d8c202793eabc712ecaf7a00/src/renderers/webgl/WebGLState.js#L1017-L1018). Should those be changed to use `gl.drawingBuffer*` considering they seem to more accurately reflect the initial viewport and scissor settings anyway?

**Comment by Mugen87** [comment]
Using `gl.canvas` should not cause issues in `reset()`.

**Comment by WestLangley** [comment]
IMHO, it's confusing for these reasons.
```js
currentScissor.set( 0, 0, gl.canvas.width, gl.canvas.height );
currentViewport.set( 0, 0, gl.canvas.width, gl.canvas.height );
```
Variables sized in device pixels should be assigned values in device pixel units -- not in CSS pixel units.

```js
gl.scissor( 0, 0, gl.canvas.width, gl.canvas.height );
gl.viewport( 0, 0, gl.canvas.width, gl.canvas.height );
```
Likewise, functions expecting device pixel units should not be passed values in CSS pixel units.

...unless you are assuming the device pixel ratio is 1, in which case an inline comment would be nice.

//

Maybe rename `currentScissor` to `deviceScissor`?

**Comment by gkjohnson** [comment]
@WestLangley 
> Variables sized in device pixels should be assigned values in device pixel units -- not in CSS pixel units.

`canvas.width` and `canvas.height` should reflect the current size of the render buffer (unless the device cannot support the requested size), right? CSS dimensions would be retrieved with `clientWidth` and `clientHeight`.

@Mugen87 
> Using gl.canvas should not cause issues in reset().

If expo is setting `gl.canvas` to null as the MDN docs say its allowed to then calling `reset` will cause an error. And it seemed to me that the `drawingBuffer*` values were the more correct ones to use given my test in https://github.com/mrdoob/three.js/issues/21824#issuecomment-840763153. Maybe calling `reset` doesn't get called often enough for this to be a noticeable issue, though.

**Comment by Mugen87** [comment]
The usage of `getParameter()` makes sense in the initialization part of `WebGLState` and is an improvement.

However, IMO using the `drawingBuffer` properties is not the right thing to do. You have mentioned an issue in https://github.com/mrdoob/three.js/issues/21824#issuecomment-840763153 which was already discussed in #5194 and which is browser specific. I think we should not start to implement workarounds for this nor make the engine "smart". Coupling the viewport and scissor to the dimensions of the canvas seems the most natural thing to do. Edge cases like too large canvas sizes needs to be solved elsewhere (best in the browser implementation).

**Pull request merged**
