### PR TITLE
TS: Add missing method saveState type in OrbitControl.d.ts

### PR DESCRIPTION
**Pull request by jnuricumbo**
Fix missing method saveState type in OrbitControl.d.ts

### CODE REVIEW

**Comment by Mugen87** [comment]
Strange, the method is already defined on `dev`:

https://github.com/mrdoob/three.js/blob/0b078bc4aea4699a4d32b83e19836f485473baf1/examples/jsm/controls/OrbitControls.d.ts#L147

**Comment by gkjohnson** [comment]
@Mugen87 it looks like it's defined on MapControls, not OrbitControls. Looking at the source it looks like MapControls inherits from OrbitControls so it may be worth cleaning up the types so we're not duplicating all the members across both class definitions.

**Comment by jnuricumbo** [comment]
@Mugen87 Sorry, already merge with #17510, and I agree with @gkjohnson, in that way we avoid such type missings

**Comment by Mugen87** [comment]
Oh dear, I see the problem. Okay, but let's merge this PR for now and do the clean up with a different one.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
