### PR TITLE
Global: Fix broken imports.

### PR DESCRIPTION
**Pull request by Mugen87**
#23255

**Description**

#23255 broke the doc browsers and the editor.

### CODE REVIEW

**Comment by Mugen87** [comment]
I'm not sure how to solve the broken `test-unit-examples` command.

@marcofugaro Do you have an advice for fixing the unit tests?

**Comment by marcofugaro** [comment]
Thanks! Totally missed those files.

I'll take a look at the unit tests

**Comment by mrdoob** [comment]
Ops! Thanks!

**Comment by takahirox** [comment]
Ouch, I have opened #23304 because I didn't notice https://github.com/mrdoob/three.js/pull/23293#issuecomment-1018580295

Anyways, #23304 may be worth to track the problem (or as reminder) since this PR is merged (closed).

**Pull request merged**
