### PR TITLE
Run build-examples

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: #21584

**Description**

Run the build-examples script introduced in #21584.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
FYI: The additional lgtm errors are produced since `RGBMLoader` (and the embedded `UPNG.js`) is now available in `examples/js`, too.

**Comment by mrdoob** [comment]
Thanks!

**Comment by fraguada** [comment]
@marcofugaro @Mugen87 @mrdoob this [PR added a /js version of the 3dmLoader](https://github.com/mrdoob/three.js/commits/dev/examples/js/loaders/3DMLoader.js). Was this the intention? 3dmLoader was developed as a jsm-first/only loader 😎.

**Comment by mrdoob** [comment]
@fraguada `jsm/` files are now the canonical ones and we are able to generate `js/` from them 👍

**Comment by fraguada** [comment]
That's rad. I was refactoring the jsm version and was wondering about the js version. I'll leave it as it then and let the build tools work their magic.

**Pull request merged**
