### PR TITLE
DragControls: Added `.getRaycaster()`.

### PR DESCRIPTION
**Pull request by draibolit**
Related issue: #22844

**Description**

to expose raycaster in drag control to change it its layer when objects are not in the default layer ( layer 0 ).

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Wait, how does this work? Isn't that method private?

**Comment by Mugen87** [comment]
It seems the OP missed to add the following line:
```js
this. getRaycaster = getRaycaster;
```

**Comment by Mugen87** [comment]
c547a74f901d1e608d546deaa3c0be20b6f7d868

**Pull request merged**
