### PR TITLE
Editor: Add Stats.js

### PR DESCRIPTION
**Pull request by Temdog007**
Addresses #16007

### CODE REVIEW

**Comment by Temdog007** [comment]
For testing: https://raw.githack.com/Temdog007/three.js/feature/FPS/editor/index.html

**Comment by looeee** [comment]
That was quick 😁

**Comment by looeee** [comment]
This has the same issue as #15998 regarding the dropdown menus. The menus will always need to have the highest z-index of anything in the scene.

**Comment by Temdog007** [comment]
I'm going to a separate PR for that issue.

**Comment by Temdog007** [comment]
#16010

**Review by looeee — APPROVED** [review]

**Comment by Temdog007** [comment]
I forgot about one detail about the editor. It only renders the scene when it needs to (camera moved, object added, object moved, etc). So, the FPS isn't going to be useful unless there is a continuous render option. I'll work on adding that to this PR.

**Comment by Temdog007** [comment]
Turns out that stats.js causes some click events not to work in the editor. I think it would be better to use `ViewportInfo` to display the FPS (same way the the object number and triangle count is displayed). Because of this, I'm going to close this PR and open a new one with that solution in mind.

**Comment by mrdoob** [comment]
I would just add `ms` to `ViewportInfo` and add simple code to calculate how long rendering the frame took.

**Pull request closed without merging**
