### PR TITLE
Improved Docs / Constants / DrawModes

### PR DESCRIPTION
**Pull request by looeee**
Added minimal explanations of what these constants mean, and usage instructions. 

One thing I'm not 100% sure of is how these relate to faces - do the faces need to be set up to correspond to the drawmode? (I'm guessing they do, at the very least for UV mapping to work) 
If someone can clue me in to that I'll update the docs accordingly.

### CODE REVIEW

**Comment by WestLangley** [comment]
@looeee Thanks for updating the docs!

>One thing I'm not 100% sure of is how these relate to faces - do the faces need to be set up to correspond to the drawmode?

Well, I think we have a design flaw. It seems to me that `drawMode` only makes sense with `BufferGeometry`. Consequently, `drawMode` should not be a property of `Mesh`, but of `BufferGeometry`.

And, as we use it, the name is more appropriately `trianglesDrawMode`. (This is confounded with the long-standing issue that we don't know if a `BufferGeometry` represents a line, points, or a mesh.)

In fact, is there a use-case for setting `drawMode` with indexed `BufferGeometry`? It may be appropriate for non-indexed only.

/ping @benaadams

**Comment by aardgoose** [comment]
I wonder if it is worth noting somewhere that DirectX10 onwards doesn't support triange fan mode. ANGLE converts fan draw mode to a supported mode and rewrites the buffers, so this is obviously not an optimal path on platforms using ANGLE.  Maybe too renderer specific??

**Comment by mrdoob** [comment]
> I wonder if it is worth noting somewhere that DirectX10 onwards doesn't support triange fan mode. ANGLE converts fan draw mode to a supported mode and rewrites the buffers, so this is obviously not an optimal path on platforms using ANGLE

Yeah, I think we should add a note. @looeee do you mind adding that?

**Comment by looeee** [comment]
How does that look?

**Comment by WestLangley** [comment]
/ping @mrdoob Can you please comment on https://github.com/mrdoob/three.js/pull/9980#issuecomment-257479746?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> /ping @mrdoob Can you please comment on https://github.com/mrdoob/three.js/pull/9980#issuecomment-257479746?

Yep, this is definitely a design flaw, and yeah, I also think that it should sit in the geometry instead.

This actually may bring an opportunity, we could consider doing `MeshGeometry` (or `TrianglesGeometry`?), `LineGeometry` and `PointsGeometry`. All of them extending `BufferGeometry`. This should allow us to move away from `Geometry` even more, and also be able to have functions to convert from `LineGeometry` to `MeshGeometry`.

**Pull request merged**
