### PR TITLE
CSM: Add support for Orthographic Camera

### PR DESCRIPTION
**Pull request by gkjohnson**
This PR adds support for an orthographic camera to the CSM example and simplifies the CSM api, as well. While shadow cascades are less relevant for an orthographic camera at least the shadows will continue to behave as expected when using one.

Temporary live link:
https://raw.githack.com/gkjohnson/three.js/orthographic-csm/examples/webgl_shadowmap_csm.html

**Changes**
- Removed `near`, `far`, `fov`, and `aspect` fields from the CSM class and pull them directly from the camera to avoid redundancy, make it easier to update the shadows based on the active camera, and avoid duplicating OrthographicCamera fields on the class, too.
- Add `maxFar` field to `CSM` to set a maximum shadow draw cutoff. When calculating cascades the minimum value of `camera.far` and `maxFar` is used.
- Use the cameras projection matrix to compute the frustum rather than the fov, near, far, and aspect values in order to support the orthographic camera.

**Upcoming**
- Reuse cache variables for frustums and points to avoid object allocation.
- Update CSM helper to show where cascade cutoffs are in a first person view
- Update CSM helper to show shadow render bounds
- Update CSM helper to have similar API to BoxHelper with function to update it.
- ~Fix case where objects can cast truncated shadows presumably because the shadow bounds only consider tightly containing the frustum.~

Let me know if there are any objections to the upcoming changes!

/ping @vHawk

### CODE REVIEW

**Comment by mrdoob** [comment]
@vHawk looks good?

**Comment by vHawk** [comment]
I guess it's fine.

@gkjohnson Can you please explain what «case where objects can cast truncated shadows» means or even provide a screenshot?

**Comment by gkjohnson** [comment]
> I guess it's fine.

If there are any api or code changes you're hesitant about please let me know and we can figure it out! I'm just excited to get this to a point where I can use it and debug it in my own applications.

> Can you please explain what «case where objects can cast truncated shadows» means or even provide a screenshot?

I actually think I misunderstood what I was seeing while I was editing the example so I actually don't think this is an issue. I'll strike that line! 😳

**Comment by mrdoob** [comment]
> _Edit: Specifically I see now that it was a misunderstanding of what `lightMargin` did._

Should I wait before merging?

**Comment by gkjohnson** [comment]
> > Edit: Specifically I see now that it was a misunderstanding of what lightMargin did.
>
> Should I wait before merging?

I didn't make any changes related to `lightMargin` in this PR -- if it looks good to everyone, then it should be good to merge! I was just taking note of it to remind myself later.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
