### PR TITLE
WebVR Vive Controller Ray

### PR DESCRIPTION
**Pull request by Alexander-Krause-Glau**
Added raycasting example as mentioned in #9494 for controller1.

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind reverting to tabs for indentation?

**Comment by Alexander-Krause** [comment]
Should be tab indentation now. However I am on my Mac and don't know how this thing called "Brackets" works. Don't judge me...

**Comment by mrdoob** [comment]
If you check https://github.com/mrdoob/three.js/pull/9544/files you'll see that the whole file indentations have changed. That page should only show the additions you've done.

**Comment by Alexander-Krause** [comment]
Have a look at [this new branch](https://github.com/Alexander-Krause/three.js/commit/2bb40cf95acb6c8455badb96ea9a3d7410bbac17). This lacks all the commits about indentation.

**Comment by mrdoob** [comment]
Looks good now! I'll test this next week (I don't have a Vive atm).

**Comment by mrdoob** [comment]
I ended up doing a dragging example which has the raycasting part on it too.
https://github.com/mrdoob/three.js/blob/dev/examples/webvr_vive_dragging.html

Thanks though!

**Pull request closed without merging**
