### PR TITLE
BufferGeometry Morphtargets

### PR DESCRIPTION
**Pull request by satori99**
This is the PR to go with #5750

This includes BufferGeometry MorphTarget support and the example. 
I also added some extras and fixes I made to get the example working

The changes do not affect existing code.

### CODE REVIEW

**Comment by mhelvens** [comment]
Thanks for your work on this! It would be very useful if you could also adapt `BufferGeometry.prototype.fromGeometry`. It does not yet fetch the `morphTargets` from the original `Geometry` instance.

I'm trying to use your code to load a '.json' model as an animated `BufferGeometry`. (An alternative solution would be a `BufferGeometry` version of `JSONLoader`. But implementing `fromGeometry` seems like a sensible step in any case).

**Comment by satori99** [comment]
There *is* a BufferGeometry compatible version of `JSONLoader` already, it is called `ObjectLoader` and it is part of the main lib. It already supports Indexed and non-indexed BUfferGeometry. The `dev` version of ObjectLoader now supports material textures properly so a lot of the code this example is now defunct.

However ObjectLoader doesn't support morphtargets for BufferGeometry so that still needs to be done manually and the renderer needs to be patched until mrdoob and others decide on how to best implement BufferGeometry morphtargets for real.

I put the morphtarget data under the data block, but that is not part of the spec for the Three.js Object Format 4.3 JSON yet, so I may have jumped the gun on what is planned for this feature.

**Comment by mhelvens** [comment]
Hm. If you have time, could you possibly have a look at [this StackOverflow question](http://stackoverflow.com/questions/28946566/three-js-how-to-load-an-animated-json-model-from-a-web-worker)? Until a proper solution is written, I'd settle for a hack, but it appears I am unable to do it on my own (I've been trying for two weeks). I'll buy you a (digital) beer!

**Comment by benaadams** [comment]
Fixed by https://github.com/mrdoob/three.js/commit/18839c8a2b7be7223df028572aaf9711fab0a3b1 in dev?

**Comment by mrdoob** [comment]
No no. That was just for skinning. Working on (re-designing) morphtargets as we speak :)

**Comment by mrdoob** [comment]
@satori99 I'm using this code as reference btw, so thanks!

**Comment by satori99** [comment]
If you would like to include the animated flag as a bufferfeometry+morph example., I would be happy to turn it into a proper example page. The json file with animation is only 350KB.

**Pull request closed without merging**
