### PR TITLE
InstancingMesh: Added per instance color support

### PR DESCRIPTION
**Pull request by mrdoob**
This allows doing this:

```js
const color = new THREE.Color( 0xff0000 );
const mesh = new THREE.InstancedMesh( geometry, material, 10 );
mesh.setColorAt( 0, color );
```

### CODE REVIEW

**Comment by donmccurdy** [comment]
@mrdoob note that this already works, without GLSL or renderer changes, as shown in this example:

https://github.com/mrdoob/three.js/blob/b5c272cf408cb33153190fa715d81581bd95ee47/examples/webgl_instancing_scatter.html#L101-L105

Maybe `.setColorAt(...)` could rely on the same method?

**Comment by mrdoob** [comment]
I looked at that example but I'm not able to follow the code.

And then we have this other one:
https://threejs.org/examples/?q=inst#webgl_instancing_modified

I think we need a simpler example.

**Comment by mrdoob** [comment]
Does the approach in `webgl_instancing_scatter` support instanceColor + vertexColors?

**Comment by donmccurdy** [comment]
> Does the approach in webgl_instancing_scatter support instanceColor + vertexColors?

No, it is relying on the fact that existing shader code for the `color` attribute can be given an instance attribute instead of a vertex attribute. So you can only use one or the other.

> I think we need a simpler example.

I think most of the complexity has to do with turning a Mesh into InstancedMesh+InstancedBufferGeometry. calling `.setAttribute( 'color', new THREE.InstancedBufferAttribute( color, 3 ) ); ` is not complicated. In my opinion https://threejs.org/examples/?q=inst#webgl_instancing_modified should be changed to do something that _can't_ be done without editing the shader, like different UV offsets for each instance to give the effect of different textures on each.

**Comment by mrdoob** [comment]
> No, it is relying on the fact that existing shader code for the `color` attribute can be given an instance attribute instead of a vertex attribute. So you can only use one or the other.

What does GLTF *think* about this?

**Comment by donmccurdy** [comment]
To support `EXT_mesh_gpu_instancing` we need the ability to put custom InstanceBufferAttributes on InstancedMesh, as the "instancing / scatter" example does. But glTF doesn't specify any particular meaning of those attributes, except the instance transform. So, support for per-instance colors is not required for glTF: having `color`+`instanceColor`, or just `color`, would both be fine.

**Comment by mrdoob** [comment]
As far as I can see, this PR doesn't conflict with that usage, correct?

The intent of this PR is to make a nicer API for per-instance colors.

**Comment by Mugen87** [comment]
Just for my understanding: This PR allows to use vertex colors and a color value per instance right?

In any event, I like the idea of defining the instance color via `setColorAt()` without working with buffer attributes.

**Comment by mrdoob** [comment]
> This PR allows to use vertex colors and a color value per instance right?

This PR allows setting a color per-instance that multiplies the geometry vertex colors (if enabled) which multiplies the material color, etc

**Comment by donmccurdy** [comment]
> As far as I can see, this PR doesn't conflict with that usage, correct?

I don't see any confilct, no. :) Worst case, we could always change the internal implementation of `setColorAt` later.

**Comment by mrdoob** [comment]
Thanks doob!

**Comment by LasseD** [comment]
I am happy to see color being added to instancing.

Is there a reason for not including alpha, or at least the possibility of including the alpha channel?

**Comment by Mugen87** [comment]
@LasseD Instancing and transparency are tricky, see #20431.

**Comment by LasseD** [comment]
Thanks @Mugen87 . This is what I feared. Thanks for the link, it provides good insight.

**Pull request merged**
