### PR TITLE
Lazy uuid generation and avoid uuid use in main renderer

### PR DESCRIPTION
**Pull request by aardgoose**
An alternative approach to solve #13069.

Use a WeakMap in WebGLAttributes and WebGLProperties keyed by objects instead of the objects uuids.
(removes need for uuid's in core rendering code). 

Add lazy generation as suggested previously by @takahirox  and others, using a source object in _Math to avoid duplicated code (most of base three.js converted).

Lightly tested with examples, editor and own application, no significant performance changes other than reduced memory usage, uuid's generated only when required.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice and clean approach!

`WeakMap` is IE11, but it's mainly used in the `WebGLRenderer` so that should be safe?

It would be very nice if you could get some numbers. For instance, how long it takes to generate 1 million `Object3D`s with and without, memory with and without, etc.

**Comment by takahirox** [comment]
Yeah, I want the performance and memory number, too.

>WeakMap is IE11+, but it's mainly used in the WebGLRenderer so that should be safe?

What does this mean?

**Comment by aardgoose** [comment]
OK some initial stats ( creation without uuids only)

I timed the init() function of the webgl_lights_pointlights2.html example, creating 100,000 objects (geometry and material shared so that's 100,000 uuid creations difference ). Chrome 63 on WIn10.

90dev : 

average: 2589ms
std dev: 44ms

90dev + this PR:

average: 1651ms
std dev: 37ms

( 10 runs each )


I'll look at property lookups in WebGL(Attributes|Properties) next with Object property vs WeakMap lookup. 

Worthwhile noting this: https://v8project.blogspot.co.uk/  , the figures only look at creating and adding to WeakMaps, so maybe WeakMap.get() is already optimized.

**Comment by takahirox** [comment]
Can you also evaluate `scene.toJSON()` performance?
I'm worried if `.toJSON()` would have an bad impact from lazy uuid generation if we merge this PR.
`.toJSON()` would be the typical usecase where it generates uuid at a time.

**Comment by aardgoose** [comment]
Testing a render loop using http://localhost:8080/examples/#webgldeferred_animation
(its not changing the scene but I expect when  most property and attribute access will be lookup.

Running for roughly 40seconds with no interaction @ 60 fps.

90dev   

scripting:  17.234% of wall time

90dev + lazy uuid:

scripting: 17.150% of wall time

It looks like any difference is in the noise (I tested with Chrome 65 (canary) and got similar numbers with a slight improvement with lazy uuid.

@takahirox I'll take a look at toJSON, Of course the overhead of generateUUID() will move from object creation time to serialization time, which will show up, but you have to take it in one place or another,

Any extra overhead will be getting the uuid via a setter method and a test for null in the setter.

**Comment by aardgoose** [comment]
Another go at the results above - I think my browser was struggling with memory pressure.

With a clean browser (closed and opened before each set of 10 runs) I get ( for 100000 objects ). Looking at the standard deviations I suspect that the base line has more disturbance from GC activity?  The last case (lazy + ) has the String().toLowerCase() hack added and the resultant heap size is around 40 - 45MB lower (from 445Mb to 40MB).  No rendering pass was made, json serialization was carried out with scene.traverse().

90dev | create | json | total
----|----|---|---
ave | 999 | 1006| 2005
stdev | 265|407|564

lazy uuid|create|json|total
----------|-------|----|---
ave | 827 | 931 | 1758
stdev | 153 | 187 | 313

lazy + | create | json | total
-------|--------|-------|-----
ave| 809|889|1698
stdev|129|173|267

**Comment by takahirox** [comment]
>Testing a render loop using http://localhost:8080/examples/#webgldeferred_animation

I don't recommend you to use webgldeferred_animation for the test because it uses special WebGLRenderer `WebGLDeferredRenderer`.

**Comment by zz85** [comment]
image

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

🤔  Weakmap browsers compatibility is better than what I recalled, I hope they are well optimised across them too.

**Comment by aardgoose** [comment]
Some micro benchmarks of WeakMap vs the existing WebGLProperties mechanism. (Code below).
This attempts to reproduce a fairly typical pattern of properties.get() access with a mixture of object types (Using a single object type may allow the VM to optimise the uuid property lookup, which doesn't happen in the WebgLRenderer. n=10000 is roughly equivalent to 2000 unique scene graph objects.

Tests on Windows 10 with Chrome 63 and Firefox 57 browsers restarted for each test run. I'm surprised the FF is an order of magnitude slower for all these tests, but this difference was repeated with more test runs.

Flattened strings in Chrome are faster, presumably because there is more work traversing the string fragments of the UUID in the un-flattened case. WeakMap.get() is significantly faster on both broswers here.

Note: I added an export of WebGLProperties for these tests.


## Chrome 63

### test: 90dev

runtime (addition): 14.68999999999994
runtime (lookup): 88012.05


### test: uuid-flatten

runtime (addition): 10.134999999999991
runtime (lookup): 37377.66000000001


### test: WeakMap

runtime (addition): 5.569999999999993
runtime (lookup): 29048.085000000003


## FireFox 57.0.4


### test: 90dev

runtime (addition): 29
runtime (lookup): 269494.98000000004


### test: uuid-flatten

runtime (addition): 18.079999999999984
runtime (lookup): 252126.


### test: WeakMap

runtime (addition): 19.139999999999986
runtime (lookup): 100928.78




	var objects = [];
	var n = 10000;
	var i,j,o, t0, t1;

	console.log( 'test: WeakMap');

	for ( i = 0; i < n / 5; i++ ) {

		objects.push( new THREE.Object3D() );
		objects.push( new THREE.BufferGeometry() );
		objects.push( new THREE.MeshBasicMaterial() );
		objects.push( new THREE.Texture() );
		objects.push( new THREE.Texture() );

	}

	var properties = new THREE.WebGLProperties();

	t0 = performance.now();

	for ( i = 0; i < objects.length; i++ ) {

		properties.get( objects[ i ] );

	}

	t1 = performance.now();

	console.log( 'runtime (addition):', t1 - t0 );

	t0 = performance.now();

	for ( i = 0; i < 100000; i++ ) {

		for ( j = 0; j < objects.length; j++ ) {

			properties.get( objects[ j ] );

		}

	}

	t1 = performance.now();

	console.log( 'runtime (lookup):', t1 - t0 );

```

**Comment by mrdoob** [comment]
Interesting. I'm all for adopting `WeakMap`. Would you like to do a new PR only for that change? We can merge it at the beginning of the next cycle (next week) and try it for a month.

**Comment by aardgoose** [comment]
Done: #13102 

Actually for the lazy uuid setter/getter copying to work in IE11 a polyfill for getOwnPropertyDescriptors() is needed.

**Pull request closed without merging**
