### PR TITLE
Refactor pointslights example

### PR DESCRIPTION
**Pull request by looeee**
Replaced the walt head model with the OBJ version, removed use of `BinaryLoader`.

Moved the models from the `examples/obj` folder to `examples/models/obj`.

[Live version](https://rawgit.com/looeee/three.js/cec21680efc8ad7b6aca31afa16063de8c01abbd/examples/webgl_lights_pointlights.html)

### CODE REVIEW

**Comment by Mugen87** [comment]
Any changes we can switch to `glTF` instead?

see https://github.com/mrdoob/three.js/issues/5045#issuecomment-356799307

Besides, it makes sense to add the model only once and not in other PRs, too. I suggest to make a single PR for this one and #13086.

**Comment by looeee** [comment]
> Any changes we can switch to glTF instead?

Sure, do you have any preference for a model?

**Comment by Mugen87** [comment]
I guess we could convert the `OBJ` file to `glTF`. 

With this project: https://github.com/AnalyticalGraphicsInc/obj2gltf

Or just import the `OBJ` in Blender and export it to `glTF`.

**Comment by Mugen87** [comment]
> My opinion on GLTF is that's it's not quite mature enough to promote exclusively over other formats yet though - for example there's no clean workflow for exporting to GLTF from most modelling programs.

IMO if we use this opportunity and immediately switch to `glTF`, we have future-proof examples. Otherwise we can do a bunch of new PRs in the near future. Let's save that work and perform the change now.

**Comment by looeee** [comment]
OK, that sounds reasonable 😄

**Comment by looeee** [comment]
...and done! 

Updated [live version](https://rawgit.com/looeee/three.js/64071b4b562e129e347b1f4ba71d0e3d3971b993/examples/webgl_lights_pointlights.html). 

The `obj2gltf` converter seems to work really well, as long as I don't try to export in `glb` format - is that GLTF version one only?

**Comment by Mugen87** [comment]
Cool! 👍 

I think we can remove the `OBJ` and `MTL` file from the PR.

> The obj2gltf converter seems to work really well, as long as I don't try to export in glb format - is that GLTF version one only?

We should prefer `glb` files since it's the actual binary representation. What happens when you export to `glb`? I thought the converter supports this option 🤔

**Comment by looeee** [comment]
> What happens when you export to glb?

I get an error saying I need to switch to `LegacyGLTFLoader`.

**Comment by donmccurdy** [comment]
> The obj2gltf converter seems to work really well, as long as I don't try to export in glb format - is that GLTF version one only?

Hmm that's odd... 🤔 you're using the CLI version? Note that the online converter (https://cesiumjs.org/convertmodel.html) is out of date.

I tried with obj2gltf and THREE.GLTFExporter, and both work ok in https://gltf-viewer.donmccurdy.com/, which only uses THREE.GLTFLoader and confirms glTF 2.0. Here's a ZIP with both:

[WaltHead-glb.zip](https://github.com/mrdoob/three.js/files/1623151/WaltHead-glb.zip)

**Comment by looeee** [comment]
Oh, I figured it out. I was using the command line but writing the binary data using 

```
var data = Buffer.from(JSON.stringify(gltf));
fs.writeFileSync('model.gltf', data);
```

Oops! 😓

**Comment by mrdoob** [comment]
Actually... For this specific model, I think it's better to keep it as obj (as that's the source) 😅

**Comment by mrdoob** [comment]
Merged the two first commits.

**Comment by mrdoob** [comment]
Thanks!

**Pull request closed without merging**
