### PR TITLE
Added Line and LineSegments support for the Three.js glTF loader. Inc…

### PR DESCRIPTION
**Pull request by bdysvik**
Added Line and LineSegments support for the Three.js glTF loader. Includes two examples: _snowFlake_ and _SnowFlakes_ where _snowFlake_ is a THREE.Line object and _snowFlakes_ a THREE.LineSegments object. Both examples are based on the geometry in the bufferedgeometry/lines/indexed demo.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Review by twittmann — COMMENTED** [review]
:1289 you use  THREE.Line which is GL_LINE_STRIP but primitive mode is WEBGL_CONSTANTS.LINES which is a GL_LINE .. so I think you should allways use THREE.LineSegments. ( without caring if it has indices or not )
- in my test case this solved my problem - but I do not know if you had something other in mind ..

**Comment by donmccurdy** [comment]
@twittmann Yes, I think you're right. Do you have an example model you could share, including how you generated it, so we can confirm this?

**Comment by twittmann** [comment]
[far_center.zip](https://github.com/mrdoob/three.js/files/1119267/far_center.zip)

The generator is self written -  I use the same structure as my OpenGL impleplementation does, to create the glTF Format.  But this is part of a bigger project so I'm sorry that I can't give you enough information about it. 
But of course it also could be my fault - by missunderstanding the spec .

**Comment by donmccurdy** [comment]
Thanks @twittmann, see #11677. If you are hoping to also use other primitive modes, and run into the minor detail that we haven't implemented them in THREE.GLTF2Loader, example models for those would be very helpful. 🙂

**Pull request merged**
