### PR TITLE
Object3D: Honor `recursive` parameter of `copy()` in subclasses.

### PR DESCRIPTION
**Pull request by frading**
**Description**

I've had a situation where I would need to clone a Spotlight or PointLight which had children, but without wanting those children. It did not seem possible as the `copy` method did not pass the `recursive` argument to the inherited `Object3D.copy` method.

So I've added the `recursive` argument to the `copy` method of a few classes.

Unless there is a reason of not allowing to pass the recursive argument is intentional, which I may have missed?

### CODE REVIEW

**Review by Mugen87 — DISMISSED** [review]
I think it's good to make this change in order for consistency reasons. Please honor all remaining classes like `InstancedMesh`, `Points` or `Sprite`.

**Comment by frading** [comment]
Ah yes, I missed those. Done now.
And I realise now there are also `MorphAnimMesh` and `LightningStorm` which could then do with this in that case, so I've also updated them.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by VeinSyct** [comment]
The changes in the Object3D is causing error when loading animated gltf "THREE.Object3D.add: object not an instance of THREE.Object3D. undefined"

**Comment by Mugen87** [comment]
Can you please explain in more detail how this change produce the mentioned error?

The examples load animated glTF assets without issues e.g. https://threejs.org/examples/webgl_animation_skinning_blending

**Comment by Mugen87** [comment]
The above project relies on `r127dev` so there is probably a migration task required if it wants to support latest `three.js` versions.

**Comment by VeinSyct** [comment]
There was nothing wrong with the car engine sound https://github.com/Antonio-R1/engine-sound-generator works perfectly with threejs release 141, the was occuring from my code bug when I load the gltf `gltf.scene` i fixed it with `gltf.scene.children[0]`. so sorry guys my bad.

**Pull request merged**
