### PR TITLE
WebGLRenderer: Add temporary sRGB encoding fix for WebXR.

### LINKED ISSUE #23278: darker textures in WebxrSession in latest dev git
darker textures in WebxrSession in latest dev git 

**To Reproduce**

https://raw.githack.com/mrdoob/three.js/dev/examples/?q=webxr#webxr_vr_ballshooter

**Screenshots**

Bildschirmfoto von 2022-01-19 18-35-50

**Platform:**

 - Device: [Desktop]
 - OS: [Linux, Android]
 - Browser: [Chrome]
 - Three.js version: [dev, 3280febab086be367ee80d8fbf15361872c64a8e]

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #23278.

**Description**

see https://github.com/mrdoob/three.js/issues/23278#issuecomment-1017243497.

@arpu Do you mind verifying if this works for you?

### CODE REVIEW

**Comment by cabanier** [comment]
This looks good! I hope it fixes the problem.

**Comment by Mugen87** [comment]
Merging for further testing.

New build files: 63ffa26705da2026c2070056b42fc7f766e06c76

**Comment by arpu** [comment]
tested this,  same result darker Textures but using 
```
_currentRenderTarget.texture.encoding
```
fixed it

**Comment by Mugen87** [comment]
Of course! I make a new PR.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
New builds 63650755e03cfe983a42bca3a489f71930fff3b7.

**Pull request merged**
