### PR TITLE
Editor: Avoid runtime error when fog is removed.

### PR DESCRIPTION
**Pull request by linbingquan**
I Change Fog's value to `NONE`, `scene.fog` is `null` after Fog's value is `Linear` or `Exponential`.
```
Uncaught TypeError: Cannot read property 'isFog' of null
    at Viewport.js:481
    at g.execute (signals.min.js:8)
    at e.Signal.dispatch (signals.min.js:12)
    at onFogChanged (Sidebar.Scene.js:132)
    at UI.Select.<anonymous> (Sidebar.Scene.js:152)
```

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
https://raw.githack.com/linbingquan/three.js/bugfix/editor/index.html

**Comment by mrdoob** [comment]
I know it's unconventional, but I think I prefer this:

```js
		if ( scene.fog === null ) {

		} else if ( scene.fog.isFog ) {

			scene.fog.color.setHex( fogColor );
			scene.fog.near = fogNear;
			scene.fog.far = fogFar;

		} else if ( scene.fog.isFogExp2 ) {

			scene.fog.color.setHex( fogColor );
			scene.fog.density = fogDensity;

		}
```

**Comment by linbingquan** [comment]
> I know it's unconventional, but I think I prefer this:

@mrdoob I was a little confused. At first time, I coded such as what you prefer, I tried to found how to judge empty object in `THREE` and `Editor`, but I was not sure which type is better. 

I found judge empty object for `scene.fog` code in
https://github.com/mrdoob/three.js/blob/dev/editor/js/Sidebar.Scene.js#L230-L251
```js
	if ( scene.fog ) {

			fogColor.setHexValue( scene.fog.color.getHex() );

			if ( scene.fog.isFog ) {

				fogType.setValue( "Fog" );
				fogNear.setValue( scene.fog.near );
				fogFar.setValue( scene.fog.far );

			} else if ( scene.fog.isFogExp2 ) {

				fogType.setValue( "FogExp2" );
				fogDensity.setValue( scene.fog.density );

			}

		} else {

			fogType.setValue( "None" );

	}
```

**Comment by mrdoob** [comment]
Oh, I guess that pattern is more flexible indeed. Looks good then!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
