### PR TITLE
AxisHelper: changed axes colors to pure red, green, and blue

### PR DESCRIPTION
**Pull request by WestLangley**
Personal preference. Let's see if this is merged...   :)

BTW, it really should have been named `AxesHelper`.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
But... if these axes were pure red, green and blue, I wouldn't be able to suspect that SpaceX is using three.js in their Mars entry simulations 😜

https://twitter.com/mrdoob/status/913947510577565696

**Comment by Mugen87** [comment]
:flushed:

**Comment by WestLangley** [comment]
Yeah, the tweet motivated me to post this. :)

**Comment by mrdoob** [comment]
I don't understand the logic 🤔

**Comment by WestLangley** [comment]
It's no big deal. I was never a fan of the current colors. I saw the tweet, and decided to file a PR.

**Comment by mrdoob** [comment]
Sorry, but these colors are one of the few resources we have to spot three.js in the wild. `SkeletonHelper` colors is another one.

Wouldn't like to lose that...

**Comment by WestLangley** [comment]
That's OK.

**Comment by WestLangley** [comment]
Since an axis is something to rotate around, and axes refers to coordinate axes, how do you feel about renaming the helper to `AxesHelper` -- or do you feel is it OK as-is?

**Comment by mrdoob** [comment]
`AxesHelper` sounds good to me 😊

**Pull request closed without merging**
