### PR TITLE
CylinderBufferGeometry with groups

### PR DESCRIPTION
**Pull request by rfm1201**
CylinderBufferGeometry with 3 different textures when used with Multimaterial

### CODE REVIEW

**Comment by mrdoob** [comment]
Are you splitting it top/side/bottom?

**Comment by WestLangley** [comment]
It is side, top, bottom = material index 0, 1, 2. That seems right to me.

**Comment by Mugen87** [comment]
> It is side, top, bottom = material index 0, 1, 2.

Yup, that's correct!

**Comment by WestLangley** [comment]
@Mugen87 I meant, can you review the code changes? :  - )

**Comment by Mugen87** [comment]
Code looks good :grin:.

**Comment by WestLangley** [comment]
Thanks!

**Comment by mrdoob** [comment]
Ah, I see... `groupCount` confused me. Maybe `groupLength` would be more clear.
Anyway... Looks good. Thanks!

**Comment by mrdoob** [comment]
Thanks!

**Comment by rfm1201** [comment]
I know it's a little bit late to answer now but I used the names found in BoxBufferGeometry.js

**Pull request merged**
