### PR TITLE
OrbitControls example: modify scene

### PR DESCRIPTION
**Pull request by WestLangley**
Make the scene a bit more `OrbitControls`-compatible.

### CODE REVIEW

**Comment by WestLangley** [comment]
Example: https://rawgit.com/westlangley/three.js/dev-orbit/examples/misc_controls_orbit.html

**Comment by clement-igonet** [comment]
From my point of view, a convenient "panning" would be to have a move parallel to your pyramid ground. It's like if the ground were sliding, in a parallel move relative to itself.
So, orbital move should not change height of your sphere center
I would add axes representation to help the understanding.
In that way, you should not be able to move the camera under the pyramid ground.

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
>a convenient "panning" would be to have a move parallel to your pyramid ground

Agreed. That is how `OrbitControls` panning should have been implemented. Currently, `OrbitControls` pans in screen-space, just like `TrackballControls`.

The suggested panning method is set as the default in an upcoming re-write of the class.

**Comment by clement-igonet** [comment]
Good to hear you understand me 😀 Do you want me to suggest an implementation ?
-- 
Sent from my mobile. It explains my brevity.

**Comment by WestLangley** [comment]
That will not be necessary.

**Comment by clement-igonet** [comment]
From my point if view, panning is out of scope. It extends orbit control, but it is not orbit control.
And also, its implementation is finally too dependent on object (a plan) into the scene. 
Imagine the case of a planet navigation: we would like to rotate a sphere rather than to slide a plan. 

I would suggest to let to the user the ability to implement his/her own extended control relative to his/her context.
So, pan() function could be externally defined if needed. It's what I tried to do in a "monkey" style. 😀

**Comment by WestLangley** [comment]
`OrbitControls` is not part of the library -- it is part of the examples. Users are free to modify the class as they see fit.

**Comment by clement-igonet** [comment]
OK.
It is an improvement of the example. And what not imagine that a good example could later become part of the lib...

**Comment by clement-igonet** [comment]
I've suggest a fix for panUp move here: [#12727](https://github.com/mrdoob/three.js/pull/12727).
What do you think ?

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
