### PR TITLE
Texture additional offset (rotation center) 

### PR DESCRIPTION
**Pull request by tentone**
Hi

@WestLangley 

This PR "fixes kinda of" some additional offset when working with texture parameters after texture rotation update.

Changed rotation center point from (0.5, 0.5) to (0.0, 0.0) in for maps, it does seem to affect the new webgl_material_rotation example, but affects rotation on normal cases, probably would be a better option to add center property to texture with default value to (0.0, 0.0) to keep compatibility with already existing code or maybe change transformation order to apply rotation after offset?

b

After applying this code change

a

Cumps
Hi

### CODE REVIEW

**Comment by WestLangley** [comment]
Sorry, I do not understand what your issue is. A live demo may help.

Is this not acceptable?
```javascript
texture.matrixAutoUpdate = false;
texture.matrix.setUvTransform( offsetX, offsetY, repeatX, repeatY, rotation, centerX, centerY );
```

**Comment by tentone** [comment]
I can write a demo.

The problem it that since this adds some additional offset this breaks compatibility with already existing code for a lot of people that are using offset and scale for spritesheet animation or for atlas etc.

Im suggesting to add center attribute to texture with default (0.0, 0.0).

**Comment by tentone** [comment]
@WestLangley Changed it to have center stored in the texture directly (0,0) as default, this should make it easier for people to work with it and keeps compatibility with already existing code.

**Comment by WestLangley** [comment]
>this breaks compatibility with already existing code for a lot of people

What code -- and what people -- are your referring to?

I do not object to making changes, but I do not understand what your issue is.

>I can write a demo.

That would be helpful.

Also, what you are now proposing is similar to what I originally proposed in #11863. Please have a look at that thread to understand the changes @mrdoob requested.

**Comment by tentone** [comment]
I google for spritesheet animation implementation w/ threejs (already tested with mine above) and found this one from @stemkoski

https://stemkoski.github.io/Three.js/Texture-Animation.html

Forked it and updated only threejs to current build

https://tentone.github.io/stemkoskipage/Three.js/Texture-Animation.html

This is why i think would be better to set rotation center by default to 0 and let people change it directly from THREE.Texture

Cumps

**Comment by WestLangley** [comment]
OK. I see what you mean, now.... We need to do something.

What is happening is (by default) the rotation -- _and scaling_ -- is occurring from the center (0.5, 0.5), instead of the lower-left corner.

In other words, the _fixed-point_ when rotating and scaling is (0.5, 0.5), and it used to be the lower-left (0, 0).

So, one solution is to do what you originally suggested in your first commit, and simply use (0, 0) for the center when `texture.matrixAutoUpdate` is `true`. This does not require adding `center` as an additional property of `Texture`.

@mrdoob preferred the API implemented in  #11863 -- and that was after several iterations. So let's see what he thinks about adding `center` as a property. I do not think adding `center` is required to address the issue you raised here.

**Comment by tentone** [comment]
Yes, this could also be fixed by sorting transformations order probably.  If we apply translation first and rotation and scaling after that would fix this but would require additional calculations to recalculate rotation center and scaling directions.

Totally agree, center is just a "comfort option".

Thanks a lot.

**Comment by mrdoob** [comment]
> @mrdoob preferred the API implemented in  #11863 -- and that was after several iterations. So let's see what he thinks about adding `center` as a property. I do not think adding `center` is required to address the issue you raised here.

So the problem is that `THREE.Sprite` already had `rotation` and the center was on `0,0`?

**Comment by WestLangley** [comment]
I would say that the issue is not with rotation. Rotation was not previously supported for textures.

The problem is that `center` is not a property of the texture, and is hardwired to [0.5, 0.5] when `texture.matrixAutoUpdate` is `true`.

Obviously, texture rotation is relative to the center-point -- _but texture rescaling is too_.

Simply by making the default center [ 0, 0 ], the `offset/repeat` values in existing code will work as they did previously.

**Comment by tentone** [comment]
@mrdoob the problem is that rotation center also affects the "offset" of the texture by having it hardcoded to (0.5, 0.5), we break compatibility for libraries that were using texture offset (because we will add an extra offset by default).

The easy fix is to simply change the center of rotation to (0, 0), wich its totally fine if somebody wants to change it to something else (most people probably want this value to be (0.5, 0.5))  they can simply set matrixAutoUpdate false and set the transformation matrix for the texture by hand.

Another solution (more convenient for most beginners in my opinion) would be to add center attribute to THREE.Texture (with default value (0,0) to avoid breaking already existing code).

**Comment by tentone** [comment]
@mrdoob 

Please take a look at this before next stable release.

Thanks a lot.

**Comment by WestLangley** [comment]
@mrdoob If, for some reason, you want to implement the minimum change, the first commit of this PR is sufficient to solve the issue.

In any event, @tentone will have to update the docs -- also, the `copy()` and `toJSON()` methods, if `.center` is added.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
>In any event, @tentone will have to update the docs -- also, the copy() and toJSON() methods, if .center is added.

@tentone  Please don't forget. Thanks.

**Pull request merged**
