### PR TITLE
Examples: Fix toggle icon CSS issue.

### PR DESCRIPTION
**Pull request by Mugen87**
Another approach for fixing https://github.com/mrdoob/three.js/pull/19881#issuecomment-663835540.

The code can't rely on `h2:first-child` since headinga are dynamically hidden/shown. Hence, the code defines now the first visible heading.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev43/examples/index.html

**Comment by mrdoob** [comment]
I'm going to have to study this one... Feels hacky 🤔

**Comment by Mugen87** [comment]
I couldn't think of a CSS based solution :worried:.

**Comment by mrdoob** [comment]
No worries! CSS is annoying like that 😁

**Comment by Mugen87** [comment]
A user personally made me aware that this problem still exists in prod. I vote to merge this PR as a temporary solution. It can be improved/replaced with something else in the future.

**Comment by Mugen87** [comment]
Closing. Let me try a different approach 😇 .

**Pull request closed without merging**
