### PR TITLE
AudioListener: use AudioParam attributes if supported.

### PR DESCRIPTION
**Pull request by andreasjeppsson**
Fixes audio glitches in Chrome.

https://webaudio.github.io/web-audio-api/#AudioListener

### CODE REVIEW

**Comment by mrdoob** [comment]
What audio glitches are those by the way?
Or is this a workaround for something they are planning to fix soon?
Seems strange that `setPosition()` and `setOrientation()` wouldn't already set the values at the current time...?

**Comment by andreasplan8** [comment]
Listen to this simple example in Chrome 53. I'm playing two loops and rotating the listener. (example is not using three).

using setPosition()
http://labs.plan8.se/panner_test/?audioparam=0

using audioParam attributes
http://labs.plan8.se/panner_test/?audioparam=1

using audioParam attributes and scheduling the values 0.01 seconds:
http://labs.plan8.se/panner_test/?audioparam=1&time=0.01

My guess is that this is a new implementation in Chrome and not a bug. 
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/zH8QYCU0Y2I/-ZvcW-4TBwAJ

**Comment by mrdoob** [comment]
Just pinged some guys at Chrome to double check this is not a regression.

**Comment by hoch** [comment]
First, we removed the 'dezippering' from the implementation per spec.
https://webaudio.github.io/web-audio-api/#audioparam-transitions

`setPosition()` had the internal smoothing (i.e. dezippering) to make the transition glitchless but it's removed. This explains the glitch in the first test case in the https://github.com/mrdoob/three.js/pull/9845#issuecomment-253455386.

Also the fix in PR might not be what you want here. As suggested in the spec above, you have to use AudioParam's `setTargetAtTime()` or `linearRampToValueAtTime()` to achieve the smooth position change.

Lastly, I think Chrome is the only browser implemented this so far, so the web app still needs to take care of other browsers.

**Comment by mrdoob** [comment]
Also, as per [the spec](https://webaudio.github.io/web-audio-api/#widl-AudioListener-setOrientation-void-float-x-float-y-float-z-float-xUp-float-yUp-float-zUp), seems like `setPosition` and `setOrientation` are being deprecated.

**Comment by andreasplan8** [comment]
Ok, thanks for the info!
Should I make a new PR using setTargetAtTime() or linearRampToValueAtTime() ?

**Comment by hoch** [comment]
My assumption is that `updateMatrixWorld()` gets called for every frame. (~16.7ms) Then using `linearRampToValueAtTime(value, currentTime + 0.017)` might be slightly better. This ensures your audio listener to transition from the state A to B over 17ms without any glitch.

Please do the experiment with various durations. I think it mainly depends on the scene or the application you're rendering.

Can `updateMatrixWorld(optional transitionDuration)` be an option here? Allowing developers to choose the responsiveness of transition would be nice as well.

**Comment by mrdoob** [comment]
> My assumption is that `updateMatrixWorld()` gets called for every frame. (~16.7ms) Then using `linearRampToValueAtTime(value, currentTime + 0.017)` might be slightly better. 

I don't think hard-coding ms values is a good idea. Specially now that we're starting to deal with VR systems that run at 90fps (0.011ms). I guess we should use the delta from the previous frame instead?

**Comment by hoch** [comment]
SGTM.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
