### PR TITLE
MTL Loader support for map_Ks

### PR DESCRIPTION
**Pull request by daveo1001**
Added map_Ks to MTL loader so you can now load a specular map from your MTL file.
Now without any console logs!

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
Just FYI, if you had updated the branch for the old pull request, the pull request would have been updated too.

**Comment by daveo1001** [comment]
Noticed that @GGAlanSmithee. Thanks for the heads-up.

I think my OrbitControls PR went more smoothly.

**Comment by mrdoob** [comment]
Thanks!

**Comment by daveo1001** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEEEEE! Thank you!

**Comment by mrdumb** [comment]
> Added map_Ks to MTL loader so you can now load a spectral map from your MTL file. 

"spectral" map does not exist.
SPECULAR map is another story ...
In any case, this OBJMTL loader is full featured (including NORMAL maps) for over an year:
:http://necromanthus.com/Test/html5/JS/objmtl.js 
And here is a (r78) sample file:
http://necromanthus.com/Test/html5/Claire.html

**Comment by daveo1001** [comment]
cool?

**Pull request merged**
