### PR TITLE
Docs: Add plugins and libraries page

### LINKED ISSUE #19353: Suggestion: Add list of external three.js plugins to documentation
For the most part three.js extensions are stored and maintained in the `examples` directory of this project and it wouldn't surprise me if a lot of users think this is how new packages can or should be built to extend three.js. There are some benefits but more broadly it seems unsustainable because it more or less passes the burden of maintaining the packages onto the maintainers of this repo. There may be other reasons people can't or don't want to include their library in this project, too. I think it would be great to create a page documentation page that links to externally maintained libraries that plug into three.js (or even just can be used with three.js).

I think this would encourage people to make more packages and make other packages people do maintain more discoverable. [This thread on SDF text rendering](https://discourse.threejs.org/t/troika-3d-text-library-for-sdf-text-rendering/15111) specifically is what prompted the idea. I was looking for a three.js-compatible SDF implementation awhile ago but I wasn't able to find this. Even when you know what you want packages aren't always so findable.

I think the page would ultimately just be a list of github repos to start with and an optional short description. If the list becomes long enough we could organize a bit more. I know I have some projects I'd add to the list.

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #19353

**Description**

Here's a first pass at a page documenting some external libraries and plugins that work with three.js or are otherwise solutions to common questions in three.js (physics engines, etc). Here's the live link:

https://raw.githack.com/gkjohnson/three.js/plugins-and-libraries/docs/#manual/en/introduction/Libraries-and-Plugins

I tried to add packages that seemed reasonably maintained but it might be worth documenting out of date ones in case someone wants to submit PRs / update them. I haven't added them in this PR but here are some other out of date packages that I still see come up every once and awhile:

- [partykals](https://github.com/RonenNess/partykals)
- [ShaderParticleEngine](https://github.com/squarefeet/ShaderParticleEngine)
- [TrailRendererJS](https://github.com/mkkellogg/TrailRendererJS)
- [Wagner Postprocessing](https://github.com/spite/Wagner)
- [THREE.MeshLine](https://github.com/spite/THREE.MeshLine)
- [dat.guiVR](https://github.com/xinaesthete/dat.guiVR) (which does have a maintained fork for WebXR [here](https://github.com/xinaesthete/dat.guiVR))
- [three_js_outline](https://www.npmjs.com/package/three_js_outline)
- [THREE.DrawCallInspector](https://discourse.threejs.org/t/three-drawcallinspector-visualize-draw-call-cost-experimental/)
- THREE.BLAS
- GSAP
- tween.js

The list here is what I had at the forefront of my mind -- others should feel free to add / suggest more!

### CODE REVIEW

**Comment by donmccurdy** [comment]
Under "Wrappers and Frameworks", it might be nice to include [ECSY](https://github.com/ecsyjs/ecsy).

For categories where three.js itself offers an alternative, it might be good to call that out somehow. For example:

***

### File Formats

In addition to the [official three.js loaders](https://github.com/mrdoob/three.js/tree/dev/examples/jsm/loaders), support for some additional formats is available through external libraries.

- urdf-loader
- ...

**Comment by gkjohnson** [comment]
@donmccurdy Done! Added both.

**Comment by mrdoob** [comment]
@gkjohnson Do you mind adding `OBJLoader2` to the list too? See https://github.com/mrdoob/three.js/pull/21014

**Comment by gkjohnson** [comment]
> @gkjohnson Do you mind adding OBJLoader2 to the list too? See #21014

Added!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
