### PR TITLE
FBXLoader fix transform inheritance, convert back to local

### PR DESCRIPTION
**Pull request by DVLP**
Related issue: #14520

Fix for node transformation inheritance in FBX loader

This contribution is funded by [Bad.City](https://bad.city).

### CODE REVIEW

**Comment by looeee** [comment]
Thanks for the PR @DVLP. I'll review it after Christmas.

**Comment by looeee** [comment]
@DVLP thank you for your patience. I've tested this with a bunch of models and this fixes a few outstanding problems (two open issues here, plus a couple of other problematic models I have kept for testing). Great work 😄 

Fixes: #15287, #14204 (@makc can you confirm that one?)
Does not fix #14903.

**Review by looeee — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
> makc can you confirm that one

I have no sources from back then, but I guess you could just drop the file into 3js editor? maybe thats what mrdoob did

**Comment by mrdoob** [comment]
> maybe thats what mrdoob did

Yep

**Comment by DVLP** [comment]
Nice

**Comment by mrdoob** [comment]
@DVLP Any ideas of what's left in #14204?

**Comment by DVLP** [comment]
I thought about it and the first place to look at would be why lPostRotationM requires inverting with lPostRotationM.invert(). This is the part that is different compared to the source code from Autodesk. I'd start from investigating why is this required and searching earlier in the chain if it's unnecessarily inverted or the opposite, if it should be inverted earlier.

What I also noticed the other two rotations(lPreRotationM, lRotationM) were empty and inverting them didn't do anything so I left them without .invert. In other models they may not be empty so this could make a difference. Maybe lPreRotationM.invert() and lRotationM.invert() are also required?

That's where I'd start but currently I'm to busy to start debugging these.

**Comment by looeee** [comment]
>  # This is a nightmare. 

No arguments from me there 😅

**Pull request merged**
