### PR TITLE
New version of index_thumbs.html that displays a list of examples and thumbnails

### PR DESCRIPTION
**Pull request by callumprentice**
Re-added the code and made a new pull request after something bad happened to original repository. 

This change re-adds the index_thumbs.html and associated CSS file -this page displays the list of examples dynamically and now references the official screenshots folder for thumbnails.

Also re-added the node.js script I wrote to capture thumbnails for all examples.

### CODE REVIEW

**Comment by looeee** [comment]
@callumprentice did you see that there's now a bunch of example screenshots generated by #18574? 
They might not be suitable for display as thumbnails, but we should keep all screenshots in the same place. Maybe `/examples/screenshots/`?

**Comment by callumprentice** [comment]
Yes - the new version of index_thumbs.html references that dir instead of the thumbs one I added to my repo.

**Comment by munrocket** [comment]
As suggested by Mugen, we probably need to turn off such errors for new pages and make a new fake stage in travis for warnings. By the way, why index_thumbs.html and not index.html?

**Comment by Mugen87** [comment]
Can #17957 be closed now? Should we focus on this PR, instead?

**Comment by munrocket** [comment]
Looks like my screenshots [not too bad](https://rawcdn.githack.com/callumprentice/three.js/877624e65ea4cee51a272440cd6f43b0f2dc593e/examples/index_thumbs.html) as I thought and I was too strict to myself, they just render only first frame. But I solved problem with LWO loaders and MMD loader, witch is blank in your  [previous thumbnails](https://raw.githack.com/mrdoob/three.js/9fa5ecbc596a5fce8d98a5b53c2e1a28f432fe33/examples/index_thumbs.html).

But it's intresting that you able to render `dof2` and `bvh` properly. I wonder if I can improve my tests, inspired by your result. I will try to improve my tests later, just tired with this screenshot-hell, they was always different.

**Comment by callumprentice** [comment]
> Can #17957 be closed now? Should we focus on this PR, instead?

Yes - that sounds like a plan.

**Comment by callumprentice** [comment]
> But it's intresting that you able to render `dof2` and `bvh` properly. I wonder if I can improve my tests, inspired by your result. I will try to improve my tests later, just tired with this screenshot-hell, they was always different.

It's tricky isn't it and without support for rendering a screenshot implicit in each demo, I am not sure how to avoid it - the various "tweaks" I allow in my script seem to work mostly okay though and I can extend them to cover ones that are not so good.

**Comment by callumprentice** [comment]
> And probably index_thumbs.html page can be index.html

When I originally submitted this idea, I implemented it as a single column of thumbnails in a left side frame - just like the existing one but with images along with a checkbox to show/hide them.  

AFAIR, @mrdoob thought the design should be different (https://github.com/mrdoob/three.js/issues/17692#issuecomment-542127360) so I changed it to what it is now.

Would be odd to have 2 different versions though - I imagined mine would be a link off the original for people who preferred a more visual approach.

**Comment by looeee** [comment]
> AFAIR, @mrdoob thought the design should be different (#17692 (comment)) so I changed it to what it is now.

@mrdoob's comment from #17692:

> As per the design, I think I would just add the thumbnails as a grid in the main page. Similar to https://threejs.org.

What about starting with a full page of thumbnails until you select one, then have the thumbnails shrink down to a sidebar?

**Comment by mrdoob** [comment]
I recall doing a mockup design for one of @callumprentice's PRs? I can't find it now...

**Comment by mrdoob** [comment]
> Also re-added the node.js script I wrote to capture thumbnails for all examples.

Won't be confusing to have 2 different ways of generating thumbnails?

**Comment by callumprentice** [comment]
> I recall doing a mockup design for one of @callumprentice's PRs? I can't find it now...

Maybe this from the original suggestion I added to the issues list? https://github.com/mrdoob/three.js/issues/17692#issuecomment-544135817

**Comment by callumprentice** [comment]
> > Also re-added the node.js script I wrote to capture thumbnails for all examples.
> 
> Won't be confusing to have 2 different ways of generating thumbnails?

I think so - I didn't know there was another way until yesterday. Not worried at all if you don't use mine - I just thought it did quite a good job and the ability to add tweaks to get the more tricky examples to render a useful frame seemed useful happy to remove if that helps.

**Comment by looeee** [comment]
> I recall doing a mockup design for one of @callumprentice's PRs? I can't find it now...

> Maybe this from the original suggestion I added to the issues list? #17692 (comment)

That looks great to me 👍 

It would be nice if there's some way to get back to the grid of images after opening an example.

**Comment by munrocket** [comment]
A new script that generating thumbnails and screenshots for testing here #18732

**Comment by mrdoob** [comment]
> It would be nice if there's some way to get back to the grid of images after opening an example.

Yes, the current examples page has taken years of tweaking. It won't be easy to replace.

**Comment by munrocket** [comment]
Finally I just added thumbnail generator to old script, because a new version based on BeginFrame API was not robust and slower. Thumbnail stored in `screenshot` folder and have `.jpg` extension.

**Comment by callumprentice** [comment]
I think we’re trying to get to a point where we can (a) see lots of thumbnails and (b) see the example without opening a new tab/window. 

What about a page where the top 2/3s (for example) displayed the example and the bottom 1/3 (for example) displayed the thumbnail grid? Clicking on a thumbnail in the bottom part would open the example in the top part. There would be a toggle to open or close the “drawer” of thumbnails in case you wanted to view the example at full size. 

I have a skeleton with dummy assets working - worth taking it a bit further and making it use real examples?

**Comment by looeee** [comment]
> What about a page where the top 2/3s (for example) displayed the example and the bottom 1/3 (for example) displayed the thumbnail grid?

Hmm, why does that remind me of something? 

Oh, wait: [mrdoob.com](https://mrdoob.com) 😁 

That looks pretty good to me, although we'd need the row of thumbs to be big enough to display the example name.

**Comment by munrocket** [comment]
Reminds about youtube sidebar on steroids :)

Can this problem somehow related to that fact that right now searching algorithm not the best? For example if I want to find `subsurface scattering`, I need to remember that this example named as `translucency` in three.js. Another case when we are newbie or don’t remember names at all, but can find it only by thumbnail. 

Actually we can solve both problems separately. First with searching algo based on full text (or on keywords), second with thumbnails.

**Comment by callumprentice** [comment]
I maybe didn’t explain it well then. I didn’t imagine it like the MrDoob site although that is very slick. Just a way to have both lots of thumbnails (not a single row) and the example itself in the same page. 

It would be helpful to have a deeper search but maybe that’s a feature to add later. I also proposed a feature a while back that let you see new and updated examples with a checkbox. I would find that very useful.

**Comment by mrdoob** [comment]
> What about a page where the top 2/3s (for example) displayed the example and the bottom 1/3 (for example) displayed the thumbnail grid? Clicking on a thumbnail in the bottom part would open the example in the top part. There would be a toggle to open or close the “drawer” of thumbnails in case you wanted to view the example at full size.

> I maybe didn’t explain it well then. I didn’t imagine it like the MrDoob site although that is very slick. Just a way to have both lots of thumbnails (not a single row) and the example itself in the same page.

When talking about ui/ux design, a design mockup is worth 1000 words.

**Comment by callumprentice** [comment]
I made a mock-up: https://3ve.surge.sh/examples/mock.html#

Terribly hacky but maybe illustrates what I had in mind?

**Comment by mrdoob** [comment]
Nice! How would that look like on mobile?

**Comment by mrdoob** [comment]
Just tried:

Screen Shot 2020-02-26 at 2 46 01 PM

**Comment by callumprentice** [comment]
Didn't work when I took a quick look on my phone (7+, iOS 13) and not sure why. I expect it can be made to work since there is nothing very clever going on .

**Comment by callumprentice** [comment]
> Just tried:

Hmmm. not brilliant but not insurmountable I hope.

**Comment by mrdoob** [comment]
This is how the current one looks like:

Screen Shot 2020-02-26 at 2 47 41 PM

**Comment by callumprentice** [comment]
> This is how the current one looks like:

Yeah - that works really well on my phone at least.

**Comment by looeee** [comment]
> I made a mock-up: https://3ve.surge.sh/examples/mock.html#

Nice! This is great. 

Feedback:

* I'd personally make the grid section a bit smaller, maybe around 75/25 split. 
* Not a big fan of the big shadow fade between the example and grid. That's wasted space, a smaller and crisper transition would be better, IMO.
* The X button works great, but needs a white background to be visible against black examples. 
* Handling resizing needs a bit of work. Sometimes the example vanishes when switching landscape -> portrait, and I have to hit the X twice to get it back. 
* Maybe switch the X to ▲ and ▼ ?

**Comment by callumprentice** [comment]
> Nice! How would that look like on mobile?

New version that is a bit neater and seems to work ok on mobile: https://3ve.surge.sh/examples/mock2.html

@mrdoob What do you think?

@looeee - thanks for the feedback - make sense. I didn't get chance to act on anything before I pushed out the second mockup but I will.
> * I'd personally make the grid section a bit smaller, maybe around 75/25 split.
Noted - I'll make it a variable

> * Not a big fan of the big shadow fade between the example and grid. That's wasted space, a smaller and crisper transition would be better, IMO. 
I like skeuomorphic design but noted :)

> * The X button works great, but needs a white background to be visible against black examples.
Yep - agreed.

> * Handling resizing needs a bit of work. Sometimes the example vanishes when switching landscape -> portrait, and I have to hit the X twice to get it back.
The new version is brand new code so shouldn't be a problem anymore.  However, sometimes the examples aren't written to take account of changing screen size so maybe that's why?

> * Maybe switch the X to ▲ and ▼ ?
I think I like that - it's hard aligning svg inside a little div - I'll give it a go.

Let me know if I should keep working on this or if you'd like to try something different.

**Comment by mrdoob** [comment]
> Let me know if I should keep working on this or if you'd like to try something different.

I don't think this approach (throwing away the old code, completely changing the design, ...) is likely to be successful.

A more conservative approach would be trying to add a checkbox to the current code that displays screenshots or not. So the current UX would stay the same but a new option would allow users to enable screenshots if they want.

**Comment by callumprentice** [comment]
> A more conservative approach would be trying to add a checkbox to the current code that displays screenshots or not. So the current UX would stay the same but a new option would allow users to enable screenshots if they want.

Um.  Wait. That was exactly the approach I took for the first iteration I made months ago. Literally. It was the same as now but there was a checkbox next to the search filter that displayed a  thumbnail for each when it was checked. 

You didn’t like that and suggested I make something more like the examples page so I did, several times. 

Your comments earlier today led me to think I was on the right track with something you might accept so I made the second mock.

I’m not sure what to do now.

**Comment by mrdoob** [comment]
>> A more conservative approach would be trying to add a checkbox to the current code that displays screenshots or not. So the current UX would stay the same but a new option would allow users to enable screenshots if they want.
>
> Um. Wait. That was exactly the approach I took for the first iteration I made months ago. Literally. It was the same as now but there was a checkbox next to the search filter that displayed a thumbnail for each when it was checked.

Are you referring to https://github.com/mrdoob/three.js/pull/17957?

**Comment by callumprentice** [comment]
No. #17692 was my original suggestion and your comments.

I have the newest version of the Puppeteer node.js script I wrote to generate he thumbnails although that seems to have been superseded by something @looeee is working as far as I can tell. 

I don’t think I have the original examples code I mention in that thread anymore sadly.

**Comment by mrdoob** [comment]
Ah, sorry. Seems like the conversation in that PR focused more on what technology to use for generating screenshots rather than the examples page improvements.

**Comment by munrocket** [comment]
##### Feedback: 

* Better to place github logo at beginning of the line.



* Horizontal navigation with vertical scrollbar looks ugly on wide screens
* UI design is differ than in threejs.org ( no shadows, sharp edges, grey / blue color pallete )
* Idea is good but no one attempt is finished for deploy

**Comment by munrocket** [comment]
I make a little research and find that guy who make current design seems from google (but not 100% sure). So I suggest to take youtube as a reference, it's better than in babylon.



Wide screenshots without edges, round icons from github, gray/blue Roboto font. Note that you can change index.html directly, no need to index_thumbnails.html.

Also as an idea for future: we can add tags in the bottom.

**Comment by munrocket** [comment]
Closing in favor of #19375

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：munrocket <notifications@github.com>
发送时间：2020-05-18 14:21
主题：Re: [mrdoob/three.js] New version of index_thumbs.html that displays a list of examples and thumbnails (#18714)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closing in favor of #19375

**Pull request closed without merging**
