### PR TITLE
PMREM and EquiangularToCubeGenerator: added dispose() methods

### PR DESCRIPTION
**Pull request by WestLangley**
...as proposed in https://github.com/mrdoob/three.js/pull/13752#issuecomment-378298529, plus some clean up.

Calling the dispose() methods _significantly_ frees up gpu memory.

### CODE REVIEW

**Comment by WestLangley** [comment]
Unrelated to this PR...

I am thinking that this pattern is a bit too much:
```javascript
var pmremGenerator = new THREE.PMREMGenerator( hdrCubeMap );
pmremGenerator.update( renderer );

var pmremCubeUVPacker = new THREE.PMREMCubeUVPacker( pmremGenerator.cubeLods );
pmremCubeUVPacker.update( renderer );

hdrCubeRenderTarget = pmremCubeUVPacker.CubeUVRenderTarget;

hdrCubeMap.dispose();
pmremGenerator.dispose();
pmremCubeUVPacker.dispose();
```

Pehaps we can hide all of that, and free up memory when we are done, via a simpler API:

```javascript
var pmrem = new THREE.PMREM(); // Extends WebGLRenderTarget

pmrem.setFromCubeMap( cubeTexture, renderer ); 

pmrem.setFromEquirectangularMap( texture, renderer ); // alternate

material.envMap = pmrem.texture;
```

/ping @bhouston

**Comment by bhouston** [comment]
I like the below:

```
var pmrem = new THREE.PMREM(); // Extends WebGLRenderTarget

pmrem.setFromCubeMap( cubeTexture, renderer ); 

pmrem.setFromEquirectangularMap( texture, renderer ); // alternate

material.envMap = pmrem.texture;
```

I can view it as a few separate operations:

- Convert EquirectangularMap to CubeMap.  This is useful outside of the PMREM convolution method.  So probably should eventually be separated.
- Convolve CubeMap into a CubeMap mipmap chain.
- Convert CubeMap mipmap chain into a CubeUV2 texture.  (The UV Packer)

I would actually suggest killing the idea of the PMREM class and replacing it with CubeTextureFactory/CubeTextureUtility class that has these functions on it.  I am sure there are others we could add.  I think that having them each as separable atomic operations would make it clearer and easier to use.

**Comment by bhouston** [comment]
How about:

```
// converters
CubeMapConverter.equirectangularMapToCubeTextureMap()
CubeMapConverter.cubeTextureMapToEquirectangularMap()
CubeMapConverter.cubeTextureMapToCubeUV2Map()
CubeMapConverter.cubeTextureMapToSphericalHarmonics3()
CubeMapConverter.sphericalHarmonicsToCubeTextureMap()

// convolver?
CubeMapConvolver.convolveCubeMap()
```

Basically I view the above as more precise and atomic.

**Comment by bhouston** [comment]
Or another alternative design would be to follow the Math class examples, where we avoid utility/factory classes and just have a class for each different interpretation of data:

```
EquirectangularMap em = new THREE.EquirectangularMap();

CubeTexture.convertFromEquirectangularMap( em );
CubeTexture.convolve();
CubeTexture.convertFromSphericalHarmonics( sh );

CubeUV2Map.convertFromCubeMap( cubeMap );

SphericalHarmonics3.convertFromCubeMap( cubeMap );
```

**Comment by WestLangley** [comment]
@bhouston Thank you for the suggestions.

For now, this PR allows us to continue to use the existing utilities, and in the HDR example, optionally dispose of ~ 500 temporary geometries and textures.

Is this OK to merge?

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
