### PR TITLE
Y axis dosent's change

### PR DESCRIPTION
**Pull request by liubgithub**
How about maintains the Y axis dosent's change? If the Y axis change when rotating or moving the scene, I think it's very difficult to control the whole scene.
there is a map like this https://maptalks.org/gallery/extrude-buildings/index.html

### CODE REVIEW

**Comment by WestLangley** [comment]
To summarize, there are two suggestions in this PR.

1. Have `OrbitControls` pan parallel to the XZ plane. I think this is the way it should have been implemented in the first place. Currently, `OrbitControls` pans parallel to screen space -- like `TrackballControls`. At this point, however, I expect all we can do is add the proposed panning method as an option.

2. Prevent `OrbitControls` from changing the camera's elevation (`position.y`) when the camera is being rotated. This suggested change would be quite limiting, IMO, and is probably not advisable.

**Comment by mrdoob** [comment]
> Prevent `OrbitControls` from changing the camera's elevation (`position.y`) when the camera is being rotated. 

Meaning that it would be a look-around type of camera?

**Comment by WestLangley** [comment]
@mrdoob As in the PR, just comment out the line below, and you can easily see the resulting behavior.
```javascript
// rotateUp( 2 * Math.PI * rotateDelta.y / element.clientHeight * scope.rotateSpeed );
```

**Comment by liubgithub** [comment]
Yes, maybe we can set some optional parameter to switch this **control** into a  **look-around** state

**Comment by mrdoob** [comment]
Implemented in #13242

**Pull request closed without merging**
