### PR TITLE
Texture: Add WorldMapping to use world coordinates for texturing (#18992)

### PR DESCRIPTION
**Pull request by finnbear**
This PR adds `THREE.WorldMapping`, an alternative to `THREE.UVMapping`. `WorldMapping` works by using two (user defined) axes of the vertex's world coordinates as the UV coordinates for texture mapping. It is configurable via the API:
```javascript
mesh.worldMappingAxes = 'xz'; // the default
mesh.material.map.mapping = THREE.WorldMapping;
```
This is crucial for applying "seamless" textures to grids of non-square objects without manually setting the UVs of each one. As a result, `InstancedMesh` is supported.

The changes don't break any of the examples I tried running.

A working example is available: `webgl_materials_texture_worldmapping`
image

Please see #18992 for more details.

**Warning:** This is my first PR on this repository and the biggest PR I have ever written for any repository. It may break things. Please merge with caution. Suggestions for changes/fixes welcome.

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral live link:
https://raw.githack.com/finnbear/three.js/dev/examples/webgl_materials_texture_worldmapping.html

**Comment by finnbear** [comment]
Thanks for adding a live link. I'm in the process of adding my build from this PR to my application to see if it actually solves my problem :wink:. There seems like there might be an issue so hold off on merging for now. Comments are welcome though.

**Comment by finnbear** [comment]
Okay, after some fixes, there are no remaining issues with my app. This is mergable AFAIK :smile:

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/18992#issuecomment-607127577

**Comment by finnbear** [comment]
see https://github.com/mrdoob/three.js/issues/18992#issuecomment-607285048, in response to previous comment

**Comment by gkjohnson** [comment]
I agree that this is application specific and doesn't belong in core -- I think node materials or ShaderMaterials serve this use case well.

**Comment by finnbear** [comment]
Okay, let's close this and finalize discussion in the issue.

**Comment by WestLangley** [comment]
Removed temporary live link.

**Pull request closed without merging**
