### PR TITLE
Fix OrbitControls in firefox

### PR DESCRIPTION
**Pull request by fkammer**
Zooming in & out of objects in firefox does also scroll the hole page. There are multiple StackOverflow discussions about this issue. See [here](http://stackoverflow.com/questions/25293927/threejs-rendering-scene-in-div-prevent-scrolling-of-browser-window-do-zoom-i) and [here](http://stackoverflow.com/questions/31685502/prevent-page-scrolling-while-mouse-is-over-scene-in-firefox).

The answer in the first linked question also provides a link where you can experience the bug: http://www.matheretter.de/formeln/geometrie/zylinder/

I fixed that behavior by changing the event listener from `DOMMouseScroll` to `MozMousePixelScroll`.

Used Firefox Version: 41.0.1 on OS X El Capitan (10.11)

### CODE REVIEW

**Comment by mrdoob** [comment]
Sounds good. Do you mind doing a new PR targeting the `dev` branch instead?

**Comment by fkammer** [comment]
No problem. I rebased it and created a new PR: #7331

**Comment by bsergean** [comment]
Hi there, I was looking at this change and it seems that MozMousePixelScroll is only working for firefox: what about other browser like Chrome or IE ?

If they don't support this event, will Zoom be broken on those browsers ?

**Comment by bsergean** [comment]
Nevermind it looks like the previous event was already firefox specific; please ignore my comment.

**Comment by fkammer** [comment]
@bsergean `DOMMouseScroll` already was a firefox-only eventListener. For other browsers the `mousewheel` listener should work.

**Comment by bsergean** [comment]
Got it @fkammer / I figured this out while looking more in depth at your fix. Thanks for the fix btw, this was quite annoying.

**Comment by fkammer** [comment]
It really is! :D It surprises me that nobody fixed it before

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7310

**Pull request closed without merging**
