### PR TITLE
Revert "Revert closure optimisations"

### PR DESCRIPTION
**Pull request by mrdoob**
Reverts mrdoob/three.js#11246

### CODE REVIEW

**Comment by pailhead** [comment]
@mrdoob 

We're importing the files directly from source and running into the circular dep problem with `Matrix4` and `Vector3`. With webpack this just automagically works, because the `Vector3` and `Matrix4` functions are hoisted inside of `three.module.js` and their prototypes are evaluated after.

But when importing these files individually, the circular dep issue persists.

It looks like the lazy eval would fix this, but this nuked it.

**Comment by mrdoob** [comment]
I guess we'll have to revert the revert... 😅

**Comment by pailhead** [comment]
Yeah..... but i also did this if it is a good enough a benchmark


https://jsperf.com/check666

The flipside of this pattern is a potential big performance hit :(

**Comment by mrdoob** [comment]
Hmm...

**Comment by chazcb** [comment]
Looks like the cost to do an identity check (instead of the || boolean casting) is pretty small (about 1% in the one test I ran on Chrome 😃 ) https://jsperf.com/test-identity-check-cost/1

Just verified that with this revert revert revert applied to latest dev branch I can directly import Vector3 / Matrix4 / other three.js primitives using Jest's module loader.

So +1 to revert revert revert

**Comment by pailhead** [comment]
@mrdoob  ^ :)

**Comment by chazcb** [comment]
PR added here https://github.com/mrdoob/three.js/pull/12348

**Pull request merged**
