### PR TITLE
Added recursive check.

### PR DESCRIPTION
**Pull request by Wilt**
Added a recursive check which was missing (oops).
In the previous code the method was always recursive.

### CODE REVIEW

**Comment by mrdoob** [comment]
`recursive` was actually removed during this `dev` cycle...

**Comment by Wilt** [comment]
On purpose? Why was it removed?
I added it again because someone made [a comment].(https://github.com/mrdoob/three.js/commit/66598e6896689d4566b652c16c29ffb8c7bb2d40#commitcomment-9749521).

**Comment by mrdoob** [comment]
It was removed because I thought it was over engineering.

**Comment by Wilt** [comment]
But I guess that soon the whole recursive flag will be dropped as a parameter right? Otherwise it is confusing that a param `recursive` can be passed but it doesn't do anything...

**Comment by mrdoob** [comment]
As far as I'm aware it has been dropped already.

**Pull request closed without merging**
