### PR TITLE
remove redundant brackets

### PR DESCRIPTION
**Pull request by 1993heqiang**
**Description**

remove redundant brackets

### CODE REVIEW

**Comment by Mugen87** [comment]
At most of these place, the additional brackets improved readability. TBH, I do not vote to remove them.

**Comment by 1993heqiang** [comment]
> At most of these place, the additional brackets improve readability. TBH, I do not vote to remove them.


I don't think these brackets can improve readability. At least this is not:
image

**Comment by Mugen87** [comment]
Yeah, this one and the changes in `Raycaster` are an exception.

**Comment by 1993heqiang** [comment]
> Yeah, this one and the changes in `Raycaster` are an exception.

I agree with your opinion. I have resubmitted a new PR and only modify Object3D
.js and Raycaster.js.#20916

**Pull request closed without merging**
