### PR TITLE
Geometry browser

### PR DESCRIPTION
**Pull request by gregtatum**
Some more live examples for the docs.

One issue I did notice is that the winding order appears to be off for a lot of the geometry, so the wireframe does not generate correctly for `gl.drawArrays( gl.LINES, ... )`. I could open up a separate issue for that and look into fixing it.

### CODE REVIEW

**Comment by WestLangley** [comment]
Try this pattern:

    var wireframe = new THREE.WireframeGeometry( geometry );
    var line = new THREE.LineSegments( wireframe );

**Comment by mrdoob** [comment]
Also, how about...

```javascript
if ( guis[ selectedGeometry ] !== undefined ) {

	guis[ selectedGeometry ]( mesh );

}

if ( selectedGeometry === 'TextGeometry' ) {

	return { fixed : true };

}

return {};
```

**Comment by TatumCreative** [comment]
@mrdoob Haha, yeah that probably would be better. I copied it over from the materials browser and it doesn't make sense as a switch anymore. I'll get that tweaked.

**Comment by TatumCreative** [comment]
Ok, I've updated both of those.

**Comment by TatumCreative** [comment]
@WestLangley Nope, I removed it.

**Comment by mrdoob** [comment]
Sweet! Thanks!

**Pull request merged**
