### PR TITLE
Docs: Clarify alpha parameter.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #23230

**Description**

We probably should clarify what the `alpha` parameter does now.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hehe. That explanation shows that we should probably deprecate the property 😅

**Comment by Mugen87** [comment]
Yeah. It is probably the most pragmatic approach to remove the parameter and use setClearAlpha() instead.

**Comment by mrdoob** [comment]
Hmm, this is my attempt at explaining the change:

https://github.com/mrdoob/three.js/wiki/Migration-Guide/_compare/9157d904d632544d10b1a7efc3e871ee37b70523...1ba90fc86bf14ccec06c2d7cb54cc783a64543f1#diff-4ad5863459ec532fa596d3b5b3fd70a3e5c2750cdef85fbaa7e5706443bcb7d4

What do you think?

**Comment by Mugen87** [comment]
Sounds good! 😊

**Comment by Mugen87** [comment]
Closing then. Maybe it's best to keep the current documentation until `alpha` is completely removed. The note in the migration guide should be sufficient.

**Pull request closed without merging**
