### PR TITLE
Add feature to blender exporter to embed textures in .json file

### PR DESCRIPTION
**Pull request by mhirsch**
This PR adds a feature to the blender exporter to embed textures in the .json file as base64 strings, much like three.js editor. I find this pretty useful when using the three.js editor from disk or from the web, since the texture paths from the .json file will usually not be correct relative to the three.js editor root.

The patch uses the native base64 library in python to do the encoding, and disables the copy_textures option when selected, to avoid the confusing situation of copying texture image files without using them.

### CODE REVIEW

**Comment by mrdoob** [comment]
Maybe "Copy Textures" could be renamed to "Export Textures". "Embed Textures" would then rely on the previous checkbox to be checked.

How does that sound?

**Comment by mhirsch** [comment]
Just so I'm clear -- there would be two options: export textures and embed textures? Clicking export textures would copy the textures to the model export directory and embed textures would base64 encode them in the json file? When embed textures is checked, copy textures must also be checked?

If you think the above is more intuitive for users I'm happy to re-submit the patch with that behavior.

**Comment by mrdoob** [comment]
Is there a way to make the "Embed" checkbox clickable only if "Export Textures" is clicked?

**Comment by mhirsch** [comment]
I see -- sure, I'll submit a new PR.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mhirsch** [comment]
@mrdoob I thought I'd ping you again, in case you didn't see this. Can we merge this PR?

**Comment by mrdoob** [comment]
Thanks for pinging! I would have missed this otherwise. Looks good now!

**Comment by mhirsch** [comment]
Thanks!

**Pull request merged**
