### PR TITLE
WebGLAttributes: Add uploadCallback when attribute gets updated

### PR DESCRIPTION
**Pull request by Yxwww**
Ensure `.onUploadCallback` gets called when attribute gets updated. 
Context: https://discourse.threejs.org/t/how-to-dispose-bufferattribute-array-on-updates/11044/2

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@Yxwww Sorry, but the PR did not get enough support in the last months. Closing for now.

**Comment by Yxwww** [comment]
Thanks for the update 👍 

Does it mean this approach is not ideal ? Is there any alternative approach I should take ?

**Comment by Mugen87** [comment]
> Is there any alternative approach I should take ?

You can remove the array data in the next frame manually since the renderer will perform the update until then.

BTW: It's actually no good approach to create a new `BufferAttribute` like mentioned in the forum. This will only create a memory leak since it's not possible to free single buffer attributes (meaning you can call `dispose()` only on the geometry object, not on attributes).

**Comment by Yxwww** [comment]
Ah after reading some dispose code. It makes more sense to me. Thanks for explaining !

**Pull request closed without merging**
