### PR TITLE
fix: grammatical mistakes in README.md

### PR DESCRIPTION
**Pull request by YashSalunke12**
### Description
fixed some grammatical mistakes to increase readability

### CODE REVIEW

**Comment by WestLangley** [comment]
This PR needs to be reverted.

https://www.thewriter.com/tools/style-guide/punctuation/hyphens

**Comment by WestLangley** [comment]
Sorry. Something is messed up somehow... This is what it should be:
```js
an easy-to-use, lightweight, cross-browser, general-purpose 3D library.
```

**Comment by mrdoob** [comment]
@WestLangley Isn't that what it is already?

**Comment by WestLangley** [comment]
Yes. This PR is correct.

**Pull request merged**
