### PR TITLE
ParametricGeometry: Revert class change.

### PR DESCRIPTION
**Pull request by Mugen87**
`ParametricGeometry` can't be a class right now. Fixed the broken example code in `ParametricGeometries`.

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
could you please provide further details as to why. we're only just getting into the month and if we're lucky we'll be able to look into this (and likely other things that come up along the way).

**Comment by donmccurdy** [comment]
It's extended by `examples/js/geometries/ParametricGeometries.js`, which would need to be converted first. My understanding is that files in `examples/*` should not be converted until after December.

**Comment by Mugen87** [comment]
@DefinitelyMaybe What @donmccurdy mentioned was discussed many times in the past. I'm honestly a bit surprised that this aspect of the ES6 migration isn't clear yet.

**Comment by DefinitelyMaybe** [comment]
I guess I will continue to surprise you then. I don't know everything about three.js, I don't remember all conversations & there relation to other topics and I'm still learning.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
