### PR TITLE
JSM: Added TS files for OBJLoader2 and fix style issues.

### PR DESCRIPTION
**Pull request by Mugen87**
The TS type declaration files for `OBJLoader2` were lately requested in the forum (see [here](https://discourse.threejs.org/t/typescript-extras-type-definition/8324)).

The PR also fixes all code styles issues in the `OBJLoader2` code base.

/cc @kaisalmen

### CODE REVIEW

**Comment by kaisalmen** [comment]
@Mugen87 Thank you, I will review the ts files over the weekend. Did you create them (semi-)automatically and if so how or manually? Regarding formatting, I guess I need to do my homework. 😅 Are there any configuration files available for jslint ode IDE configuration (WebStorm/VSCode)? Any hints are welcome. Thanks

**Comment by kaisalmen** [comment]
Btw, ping me in the forum when I could be of help  and don't notice it myself.

**Comment by Mugen87** [comment]
> Btw, ping me in the forum when I could be of help and don't notice it myself.

Okay! And yeah, I've written the TS declaration files manually^^.

**Comment by Mugen87** [comment]
Merging for now. Feel free to create a new PR with fixes/improvements.

**Comment by mrdoob** [comment]
Thanks!

**Comment by kaisalmen** [comment]
@Mugen87 thanks again for you work. I overlook that some public functions are not properly documented in the js files. I started polishing this and will perform minor changes to the ts files where required. PR will come later...

**Pull request merged**
