### PR TITLE
E2E: remove installation checking

### PR DESCRIPTION
**Pull request by munrocket**
This was added to simplify e2e adoption and checking useless right now.

P.S.
I am just revisited current e2e implementation after reading this tweet https://twitter.com/RReverser/status/1417800541133058050
Basically we doing almost the same, but we also controlling time. Each frame is rendered in 16ms in our virtual time to make pictures exactly the same, we rendering 2 frames and making screenshot after that.

Ways to improve current e2e implementation (without recreating all screenshots):
* to use some fancy test framework
* remove progressive attempts to simplify script but testing pipeline will be little bit slower
* try to take benefits from parallel pages https://github.com/checkly/puppeteer-examples/blob/master/5.%20parallel-pages/screenshots_parallel.js
* change puppeteer to playwright they have almost the same API but playwright supports Safari and Firefox.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I wouldn't worry about Firefox and Safari.
At this point I think it'd be more beneficial to figure out how to make WebGPU work.

**Comment by munrocket** [comment]
> how to make WebGPU work.

When it will be stable at Chrome and in Puppeteer it will work here after remaking screenshots.

**Comment by mrdoob** [comment]
Yes, but until then we'll have to make the screenshots manually for the webgpu examples.

**Comment by munrocket** [comment]
One can add changes locally to `puppeteer.js` file
```js
const browser = await puppeteer.launch({
      headless: ! process.env.VISIBLE,
      args: [
        '--use-gl=swiftshader',
        '--no-sandbox',
        '--enable-surface-synchronization',

//// addition
        '--enable-unsafe-webgpu',
        '--enable-dawn-features=use_tint_generator'
      ],
      executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
      userDataDir: '/Users/$USER/Library/Application\\ Support/Google/ChromeCanaryTestUnsecure/',
  });
```
and then execute 'nom run make-screenshot <webgpu_samples>'.

This can be temporary experimental branch for webgpu screenshots.

**Comment by munrocket** [comment]
Also in situation like this, when you not sure about proper flags image-output is usefull. https://github.com/mrdoob/three.js/commit/98cfa79bbbb389fb93362bf74fd1ffb53796ff55#diff-cc4fa397e997f0bb32b468a53b6e33bf4e6d59c4a869faab0625e15d048128af

**Comment by mrdoob** [comment]
```js
		'--enable-unsafe-webgpu',
		'--enable-dawn-features=use_tint_generator'
```

Seems like these flags produce black renders with the current version of puppeteer.
The API is still changing so it's probably too early.

**Comment by munrocket** [comment]
@mrdoob swiftshader not work.

WebGPU need additional instance of puppeteer with --use-gl=egl or something like that (depends on OS in CI an in your PC)

**Comment by mrdoob** [comment]
@munrocket I think WebGPU is still not available in puppeteer.

**Pull request merged**
