### PR TITLE
Matrix4: added premultiply() method

### LINKED ISSUE #8496: Matrix* should have a preMultiply function
##### Description of the problem

In my application it makes much more sense to deal with an Object3D's matrix directly, rather than using the position and rotation properties. When rotating an object about its parent's origin, I have to write this code:

    object.matrix.multiplyMatrices(rotation, object.matrix);

Which is somewhat verbose. My suggested alternative is to write this:

    object.matrix.preMultiply(rotation);

This would require the addition of a very simple function. Of course, I could add this to my own code, but I think that this would be nice for everyone to have.

I would be glad to add this and submit a pull request, but only if it's OK with the project maintainers.

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #8496.

### CODE REVIEW

**Comment by bhouston** [comment]
I've wanted this for ever.  Although I would also deprecate Matrix4.multiply and replace it with postMultiply.  I'd do the same for Matrix3. :)

**Comment by bhouston** [comment]
Well, I'm fine with this PR as it. :)

**Comment by mrdoob** [comment]
Hmmm, how about making it lower-case?

```javascript
vector.add();
vector.subtract();
matrix.multiply();
matrix.premultiply();
matrix.transpose();
...
```

More consistant API...

**Comment by WestLangley** [comment]
>Hmmm, how about making it lower-case?

Oh yes. Much better.

**Comment by mrdoob** [comment]
Yay!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
