### PR TITLE
WebGPURenderer: Backdrop Node - Part 1/3

### PR DESCRIPTION
**Pull request by sunag**
**Description**

This was more progress from tree-oriented rendering, at least that's how I'm interpreting it. With `WebGPURenderer.copyFramebufferToRenderTarget()` and `Node.updateBefore()` it is possible to obtain a textured copy of the current rendering, this has always been one of my biggest difficulties in creating advanced shaders without having to make a new RTT for everything. Unlike the current transmission that just considers opaque objects, `backdropNode` will be able to do with any object more easily, because it applies filters on each render call if necessary, which is extremely useful for 2d games and visual fx too.

**Live**

https://raw.githack.com/sunag/three.js/dev-backdrop-1/examples/webgpu_backdrop.html

**API**

```js
const material = new MeshStandardNodeMaterial();
material.transparent = true;

// everything behind the object will be monochromatic.
material.backdropNode = viewportSharedTexture().rgb.saturation( 0 );
```

Example of the above material applied to a sphere. 

image

**Board**

image

### CODE REVIEW

**Comment by sunag** [comment]
@LeviPesin E2E testing has failed. Maybe should we add these examples [ `physics_ammo_instancing`, `physics_rapier_instancing` ] in `exceptionList`?
```
List of failed screenshots: physics_ammo_instancing physics_rapier_instancing
If you are sure that everything is correct, try to run "npm run make-screenshot physics_ammo_instancing physics_rapier_instancing". If this does not help, try increasing idleTime and parseTime variables in /test/e2e/puppeteer.js file. If this also does not help, add remaining screenshots to the exception list.
```

**Comment by LeviPesin** [comment]
I suggested just to temporary revert the failing commit: https://github.com/mrdoob/three.js/commit/285dd1cb78a4a64a0e78e2eac05ae97658b47253

**Comment by Mugen87** [comment]
> Maybe should we add these examples [ physics_ammo_instancing, physics_rapier_instancing ] in exceptionList?

Let's do that. I'm not in favor to revert work just because E2E is buggy.

**Comment by mrdoob** [comment]
If you pull from `dev` the errors will go away 👌

**Pull request merged**
