### PR TITLE
support Geometry in GLTFExporter

### PR DESCRIPTION
**Pull request by makc**
ok, I know you guys hate old Geometry but, while it's still around, and it takes a single line to support it - why not?

### CODE REVIEW

**Comment by donmccurdy** [comment]
Geometry should have been covered by this block:

https://github.com/makc/three.js.fork/blob/fc31f5e634714c9811a8a13046419b369b8ee522/examples/js/exporters/GLTFExporter.js#L1030-L1033

Have you found an example that isn’t working?

**Comment by makc** [comment]
well yes I was getting geometry.getAttribute not defined. unfortunately the scene is dynamic, so I don't have easy to reproduce test case

**Comment by makc** [comment]
looking at the code above it could have been lines

**Comment by makc** [comment]
in which case this is not a proper fix - closing

**Pull request closed without merging**
