### PR TITLE
Add InterleavedBufferAttribute.prototype.toJSON

### PR DESCRIPTION
**Pull request by jsantell**
Serializing an object that has InterleavedBufferAttributes will throw -- not terribly familiar with interleaved buffers, not sure if any other values should be returned.

### CODE REVIEW

**Comment by Mugen87** [comment]
There was a similar PR some time ago, see #16838

Fact is that interleaved attributes share a common interleaved buffer. That makes serialization and deserialization tricky since you can't serialize interleaved attributes in an isolated way. If you restored the attributes, they don't share a common buffer anymore. There are also no copy and clone methods for interleaved attributes because of their special architecture.

**Comment by jsantell** [comment]
My main interest is making it possible to serialize a scene with InterleavedBufferAttributes -- much like WebGLRenderTargets (https://github.com/mrdoob/three.js/pull/16816), the existence of either of these currently makes the serialization *of the rest of the scene* impossible. I'd be happy with `toJSON()` existing and returning an empty object, but I think there is some extra information that can be provided (size, type, etc.).

As it is now, unserializable objects are not only un-deserializable via ObjectLoader (issue of serialization), they break `toJSON()` for the entire scene (issue of breaking serializing everything else in the scene)

**Comment by jsantell** [comment]
Checking for `.toJSON` existence from BufferGeometry's toJSON (or any other object that may serialize an interleaved buffer attribute) would also solve the use case of serializing the rest of a scene if `toJSON()` should be reserved for completely serializable objects (e.g. can be hydrated via ObjectLoader) as another option

**Comment by Mugen87** [comment]
> As it is now, unserializable objects are not only un-deserializable via ObjectLoader (issue of serialization), they break toJSON() for the entire scene

That's indeed a problem. I think I would prefer to ignore objects which are not serializable. Do you think this approach would also work in context of `WebGLRenderTarget`'s?

**Comment by looeee** [comment]
>  I think I would prefer to ignore objects which are not serializable. 

Could we log a warning?

**Pull request closed without merging**
