### PR TITLE
Reuse 'setDrawingBufferSize' from 'setSize' in WebGLRenderer

### PR DESCRIPTION
**Pull request by delmohf**
**Description**

The major piece of `WebGLRenderer.setSize` implementation is pretty similar to `WebGLRenderer.setDrawingBufferSize` so I'm wondering whether the latter could be reused from the former to honor the DRY principle. 

Is there any reason to keep these both methods unrelated even when their implementations are similar?

### CODE REVIEW

**Comment by Mugen87** [comment]
`setDrawingBufferSize()` also set the pixel ratio. Hence, it feels a bit odd that `setSize()` redefines the pixel ratio via `setDrawingBufferSize()`...

**Comment by delmohf** [comment]
I get it but `setSize` is not actually "redefining" the pixel ratio, it's just "passing" to `setDrawingBufferSize` the same pixel ratio that already exists, the same `_pixelRatio` it already used. It's just a matter of code reutilization. 

If this is not a clear solution for you, I think it should be fixed anyway to avoid the repetition of the same logic in two different places: 
- update _width, _height 
- update _canvas dimension using _pixelRatio too

May be an internal function that can be called from `setSize` and `setDrawingBufferSize`?

**Comment by Mugen87** [comment]
DRY is not the holy grail of software development. Sometimes code is actually easier to read if (especially trivial) statements are inlined instead of encapsulated away. I vote to keep the current implementation to emphasize simplicity.

**Comment by delmohf** [comment]
IMHO it feels a bit odd doing the same thing from two different places. There would be a **single source of truth**, so there would be a unique place where `_width`, `_height` and `_canvas` dimensions are updated to.

**Comment by WestLangley** [comment]
How about removing `setDrawingBufferSize()`? We do not advocate using it, it is not documented, and the other methods are sufficent.

**Comment by Mugen87** [comment]
I'm fine with that 👍 .

**Comment by WestLangley** [comment]
@Mugen87 Do you want to remove it?

**Comment by Mugen87** [comment]
Yes. I've checked the code base again and `setDrawingBufferSize()` isn't used anywhere.

Do you want to make the PR?

Sidenote: `WebGPURenderer.setDrawingBufferSize()` can also be removed. And I suggest to keep `getDrawingBufferSize()` as a convenience method. This method is also used in the code base.

**Comment by WestLangley** [comment]
Actually, if you don't mind, I prefer you file the PR. Hopefully, the removal won't negatively impact users.

**Pull request closed without merging**
