### PR TITLE
LWOLoader: clean up

### PR DESCRIPTION
**Pull request by sciecode**
`LINE`, `ENAB`, `NNDS`, `REFL` duplicates case clean up.

@looeee please confirm the correct cases were kept.

### CODE REVIEW

**Comment by sciecode** [comment]
Incorrect rendering of `webgl_loader_lwo`. Implementing commit to fix changes.

**Comment by sciecode** [comment]
Incorrect rendering not related with commit. 
Introduced #16107, proposed re-fix #16113 (works).

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
This is not correct, there's loads of `LWOLoader: form already exists on parent`. 

@mrdoob please give me time to review PRs for the loader before merging.

**Comment by looeee** [comment]
@sciecode when making changes to the Block and Chunk parsing section of the loader, you will need to check the changes against quite a few files. The simple test file in the example is not enough. 

I have a big directory of LWO test files, but I'm not sure which ones I can share. I'll find that out and make a dropbox folder of test models.

**Comment by sciecode** [comment]
@looeee I would greatly appreciate the test models. 
I believe I've fixed the incorrect parsing types and removed correct duplicated cases on newly forked branch commit sciecode/three.js@623fab399b5869f27ebbbd5f03fc60b7582311d9.
If you could check the changes on modified  `LWOLoader.js` and confirm it's ok, I would make a new PR to fix it.

**Pull request merged**
