### PR TITLE
Initial untested spherical harmonics implementation.

### PR DESCRIPTION
**Pull request by bhouston**
I've made this PR at @WestLangley's request.

This is an initial implementation of SphericalHarmonics, both the JS class and a shader.  I haven't tested it, but I think that this implementation form is pretty close to what we want as it is based on the general standards.

Thus this PR is for others to build upon.

### CODE REVIEW

**Comment by bhouston** [comment]
Adding this for future reference: How to calculate SH from a cube texture - http://www.sunandblackcat.com/tipFullView.php?l=eng&topicid=32

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6405

**Comment by mattdesl** [comment]
I just stumbled on this repository which may also be useful for reference.
https://github.com/google/spherical-harmonics

**Comment by bhouston** [comment]
@mattdesl very nice.  I wonder what Google is using it for?

**Pull request closed without merging**
