### PR TITLE
Color: Added setSRGB() method

### PR DESCRIPTION
**Pull request by WestLangley**
This is convenient, for example, if the color is a CSS color.

A use case is a color set by `dat.gui`
```js
folder.addColor( API, 'lightColor' )
	.onChange( function( value ) { light.color.setSRGB( value ) } );
```
I'll add docs if there is interest in this method.

### CODE REVIEW

**Comment by Mugen87** [comment]
How about making a new class `THREE.CSSColor`  instead. As mentioned in #20279, most users don't know that sRGB is. If they use `THREE.CSSColor`, the engine can handle the color space conversion internally.

**Comment by WestLangley** [comment]
I am open to any proposals.

**Comment by WestLangley** [comment]
`material.color` (or `material.specular` for highly-specular materials) should be specified in linear space. Without handling this correctly, the rendered color will be incorrect.

Scene light colors should be specified in linear space, too.

**Comment by donmccurdy** [comment]
Green field, I'd prefer that `setHex()`/`getHex()` and CSS string equivalents would assume sRGB input/output. Methods operating on r/g/b components could remain linear. Currently I'm [recommending](https://www.donmccurdy.com/2020/06/17/color-management-in-threejs/) the pattern below — while it's verbose, it is also very clear:

```js
material.color.setHex( 0x4285f4 ).convertSRGBToLinear();
```

I think I'd like to have a goal for the eventual API before we begin adding sRGB versions of the various setters/getters.

Related: https://twitter.com/mrdoob/status/1273742169103187968

**Comment by WestLangley** [comment]
>whenever 3MF uses colors that are expressed as #RRGGBB hexadecimal quantities with 8 bits per color channel, they are assumed to be in sRGB color space. [link](https://github.com/3MFConsortium/spec_materials/blob/master/3MF%20Materials%20Extension.md#12-srgb-and-linear-color-values)

So it has been done that way....

>I'd prefer that setHex()/getHex() and CSS string equivalents would assume sRGB input/output

Personally, I think that is too confusing. The different color formats should be equivalent, IMO. As they are now.

//

So far, I prefer `color.setSRGB( value )`. The sRGB color could be specified in _any_ format for all we know.

We could do `color.setCSS( value )`, instead , but I think that obfuscates something the developer should be aware of.

**Comment by donmccurdy** [comment]
> Personally, I think that is too confusing. The different color formats should be equivalent, IMO. As they are now.

Blender's UI does this too: RGBA and HSL values are linear, hex colors are gamma-corrected. This also provides more consistency with the r/g/b components in vertex colors, which should remain linear. We'll also want ColorKeyframeTrack to interpolate in linear space, and this may save us added conversions in the render loop there.

I would really like to have a setting for this, rather than new getters/setters.

**Comment by WestLangley** [comment]
What you are proposing is more restrictive than what we are doing now. Personally, I think that will lead to developer complaints. I prefer flexibility.

Also, developers are expected to know about the importance of setting texture `sRGBEncoding`. How can knowledge of sRGB color space be off-limits?

**Comment by donmccurdy** [comment]
> How can knowledge of sRGB color space be off-limits?

Not off limits, but let's be realistic that even experienced users find color space extraordinarily confusing. The `convertsSRGBToLinear` method is there for the few who know what they're doing, but with so few of those users we don't need a more concise version of the same thing through `setSRGB`. If we were designing from scratch today, we should choose an API that gives correct results even if you _don't_ understand sRGB yet, as many programs are able to do. I don't think it's too late to reach that outcome.

I don't believe there's any loss of flexibility here, but it depends on the final API and implementation details.

Let me try a PR similar to https://github.com/mrdoob/three.js/pull/20279#issuecomment-688479307. Merging https://github.com/mrdoob/three.js/pull/20279 would be OK, but I'd like to wait on this PR.

**Comment by WestLangley** [comment]
OK, closing.

**Pull request closed without merging**
