### PR TITLE
WebGLMultipleRenderers: Use Geometry

### PR DESCRIPTION
**Pull request by dubejf**
- WebGLMultipleRenderers: Use Geometry instead of BufferGeometry
- index.html: Add "webgl_multiple_renderers" again
- Misc. fixes to please closure compiler (unused var).
- Misc. fixes (semicolon).

### CODE REVIEW

**Comment by WestLangley** [comment]
FYI. The html title and the info title are not correct -- cut and paste error. Nice demo, BTW.  : - )

**Comment by dubejf** [comment]
Thanks, but the clever demo is all @fordacious' work!

**Comment by WestLangley** [comment]
Oops. Nice demo, @fordacious!

**Comment by mrdoob** [comment]
Thanks!

**Comment by fordacious** [comment]
@WestLangley thanks c:

**Pull request merged**
