### PR TITLE
Examples: Improved webgl_loader_gltf_anisotropy.

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #25580 #26051

**Description**

Changed the environment image with a more detailed one to make the anisotropy shine more.

I've also changed the default camera position and restored `zoom` and `panning` so we can appreciate the new material from any direction and any distance.

| Before | After |
| --- | --- |
| Screenshot 2023-05-16 at 12 45 13 PM | Screenshot 2023-05-16 at 12 45 06 PM | 

/cc @elalish @sunag @WestLangley

### CODE REVIEW

**Comment by elalish** [comment]
There's an improved version of the model on the way too, which I can hopefully merge soon.

**Comment by donmccurdy** [comment]
For the next version – let's run it through texture compression as well. This cuts about 50% of file size, losslessly, for the current GLB:

```
gltf-transform png AnisotropyBarnLamp.glb AnisotropyBarnLampOptimized.glb
```

**Comment by elalish** [comment]
@donmccurdy I dunno about losslessly: it strips out the anisotropy extension it doesn't understand, along with the associated texture. I think that's most of the reason for the size savings. Would be awesome if gltf-transform could pass unknown extensions through without loss, though that might be tricky, especially with references.

**Comment by elalish** [comment]
oh, maybe I'm just on an old version. Thanks, that's great to know!

**Pull request merged**
