### PR TITLE
fix copy material

### PR DESCRIPTION
**Pull request by sunag**
Hi. I made a fix in copy material of MeshPhongMaterial.js transferring the values of clone to copy. This would help to extend the MeshPhongMaterial.

Thks

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Is this the pattern you want to apply to all materials, not just Phong -- well, all objects, for that matter?

/ping @dubejf If this is the pattern we want, then I do not think that `Mesh.copy()`, for example, is correct.

	THREE.Mesh.prototype.clone = function () {

		var mesh = new THREE.Mesh( this.geometry, this.material );
		return mesh.copy( this );

	};

	THREE.Mesh.prototype.copy = function ( source ) {

		THREE.Object3D.prototype.copy.call( this, source );
		return this;

	};

**Comment by mrdoob** [comment]
> Is this the pattern you want to apply to all materials, not just Phong -- well, all objects, for that matter?

I think is a good feature, yep.

**Comment by dubejf** [comment]
Should `copy` be added to all classes upfront or on demand?

@WestLangley What's wrong with `Mesh.copy()`? Is it about `geometry` and `material`?

**Comment by mrdoob** [comment]
> /ping @dubejf If this is the pattern we want, then I do not think that `Mesh.copy()`, for example, is correct.

Do you mean that that is not really cloning geometry and material? It's kind of intentional.

**Comment by WestLangley** [comment]
@dubejf @mrdoob Oops. Sorry. `Mesh.copy()` is fine.

**Pull request merged**
