### PR TITLE
Shaders: Initialize `geometryClearcoatNormal` to suppress OpenGL warning.

### LINKED ISSUE #26994: Getting warning in custom WebGL implementation running ThreeJS
### Description

This code works:
```js
const geometry = new THREE.SphereGeometry(5,32,32);
const material = new THREE.MeshNormalMaterial();
```
but as soon as I am switching to physical material like MeshStandardMaterial:
```js
const material = new THREE.MeshStandardMaterial( { color: 0xFFFFFF } );
```
I am getting this warning:
```
THREE.WebGLProgram: Program Info Log: Fragment info
-------------
0(1578) : warning C7050: "geometryClearcoatNormal" might be used before being initialized
```
in the fragment shader produced by ThreeJS.

Here is the code of the fragment shader around that location:
```
....
vec3 geometryPosition = - vViewPosition;
vec3 geometryNormal = normal;
vec3 geometryViewDir = ( isOrthographic ) ? vec3( 0, 0, 1 ) : normalize( vViewPosition );
vec3 geometryClearcoatNormal;  // <<<<<<<<<< line 1578
#ifdef USE_CLEARCOAT
  geometryClearcoatNormal = clearcoatNormal;
#endif
#ifdef USE_IRIDESCENCE
...
```
(USE_CLEARCOAT is false in that particular instantiation - tested on the Web and locally)

I suspect that problem is in my WebGL implementation. But it is quite thin layer that is simply tunneling JS calls to real OpenGL (not ANGLE) like this for example:
```c++
value WebGL::linkProgram(WebGLProgram* program) {
	glLinkProgram(program->id);
	return check_gl_error();
}
``` 
That machine has OpenGL  4.6 and NVIDIA drivers.

In general non-THREE WebGL samples and tests works OK as far as I can tell, only that one above.

I'll really appreciate any idea of why such warning appears. 

### Reproduction steps

N/A - no public release yet. 

### Code

```js
import * as THREE from "three.module.js";

function main(canvas) {

    let {width,height} = canvas.box("inner");

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera( 75, width/height, 0.1, 1000 );
          camera.position.z = 15;

    const light = new THREE.AmbientLight(0xFFFFFF, 1);
    scene.add(light);      

    const geometry = new THREE.SphereGeometry(5,32,32);
    const texture = new THREE.TextureLoader().load( "images/earth.jpg" );
    const material = new THREE.MeshStandardMaterial( { map : texture , color: 0xFFFFFF } );

    const mesh = new THREE.Mesh( geometry, material );
    scene.add( mesh );

    const renderer = new THREE.WebGLRenderer( { antialias: true, canvas } );
    renderer.setSize( width, height );
    renderer.setAnimationLoop( animation );

    // animation

    function animation( time ) {

        mesh.rotation.x += 0.01;
        mesh.rotation.y += 0.01;

        renderer.render( scene, camera );
    }

}

document.on("ready", function() {
  main( document.$("canvas") );
});
```

### Live example

N/A

### Screenshots

N/A

### Version

157

### Device

Desktop

### Browser

_No response_

### OS

Windows

### PR DESCRIPTION
**Pull request by c-smile**
Fix of 0(1578) : 'warning C7050: "geometryClearcoatNormal" might be used before being initialized' 

Fixed #26994

**Description**

This warning appears while running ThreeJS on top of WebGL implementation that uses system OpenGL directly. 
In particular in [Sciter Engine](https://sciter.com) on Windows with OpenGL 4.6 / NVIDIA drivers.

This warning manifests on any attempt to use "physical" materials like: 
```
const material = new THREE.MeshStandardMaterial( { color: 0xFFFFFF } );
```
Note, no such warning in non-physical materials like MeshNormalMaterial

### CODE REVIEW

**Comment by WestLangley** [comment]
Initializing a normal to zero raises a red flag: normals are of unit length.

Looking into this, `vec3 geometryClearcoatNormal` should be declared and initialized inside `#ifdef USE_CLEARCOAT`.

But you can't do that because of the refactoring in done in #26805.

https://github.com/mrdoob/three.js/blob/7bf83b8b1716666958f5dd24dc49ad73111c5839/src/renderers/shaders/ShaderChunk/lights_fragment_begin.glsl.js#L74


//

Also, `CSMShader` appears to have the same issue.

**Comment by Mugen87** [comment]
This initialization is purely technical. As long as the code doesn't use the normal, I see no issue, tbh.

**Comment by mrdoob** [comment]
@WestLangley Would it be better to initialize it as `vec3( 0.0, 0.0, 1.0 )`?

**Comment by WestLangley** [comment]
@mrdoob The real problem is it shouldn't be instantiated at all if it is not going to be used.

**Comment by mrdoob** [comment]
Ah, so we could do this instead?

```glsl
#ifdef USE_CLEARCOAT
	vec3 geometryClearcoatNormal = clearcoatNormal;
#endif
```

**Comment by Mugen87** [comment]
This does not work which is explained here: https://github.com/mrdoob/three.js/pull/27002#issuecomment-1768850633

**Comment by Mugen87** [comment]
I have the feeling we overthink this issue a bit. As long as `geometryClearcoatNormal` isn't used, it's value really does not matter.

**Pull request merged**
