### PR TITLE
BufferedGeometry Instancing

### PR DESCRIPTION
**Pull request by benaadams**
Hardware instancing using ANGLE_instanced_arrays for BufferedGeometry related to Issue #5171

### CODE REVIEW

**Comment by benaadams** [comment]
Test cases 

Arrays: http://prealpha.ageofascent.com/examples/webgl_buffergeometry_instancing.html
Elements: http://prealpha.ageofascent.com/examples/webgl_buffergeometry_instancing_dynamic.html

Looks good to go.

**Comment by WestLangley** [comment]
Wow. `renderer.info` is very impressive. : - )

**Comment by benaadams** [comment]
Also now resolves #3435 example usage: http://prealpha.ageofascent.com/examples/webgl_buffergeometry_instancing_interleaved_dynamic.html not very exciting; though what its doing behind the scenes is very interesting especially allowing for for partial dynamic updates of buffers 

e.g. only update one buffer and group all changing params together in a chunk as x,y,z,u,v,nx,ny,nz are all close together, or instanced variables

**Comment by WestLangley** [comment]
These examples are very illustrative. Thanks.

In three.js, a rotation is nominally a Euler vector. I think for clarity, it would be a good idea to rename `rotation(s)` to `quaternion(s)` or `quat(s)` in this PR.

**Comment by benaadams** [comment]
You are challenging my git squish abilities ;-)

Good suggestion though, will make the change

**Comment by benaadams** [comment]
Renamed to orientation, that work?

**Comment by WestLangley** [comment]
> Renamed to orientation, that work?

I see. You don't want to name them quaternions, because they are not `Quaternions` -- they're typed-arrays that represent quaternions.

Fair enough. : - )

**Comment by benaadams** [comment]
Don't want to give the impression there is some automatic handling where there is with other Quaternions, e.g. its not baked into the matrix and shaders don't automate it with #defines. If/how/when is probably a different issue/discussion?

**Comment by benaadams** [comment]
FYI maxInstancedCount on InstancedBufferGeometry allows dynamic control over number of instances with -1 meaning draw all.

So you can allocate more instances for the buffers; but dynamically change how many are drawn by changing maxInstancedCount to less than the allocated count.

**Comment by WestLangley** [comment]
> with -1 meaning draw all.

Do you think `undefined` would be better?

**Comment by benaadams** [comment]
@WestLangley changed to undefined and added a skip draw when counts are 0

**Comment by benaadams** [comment]
Also added a dat.gui to http://prealpha.ageofascent.com/examples/webgl_buffergeometry_instancing.html to demonstrate this dynamic changing of the instance count.

**Comment by WestLangley** [comment]
Sweet. The more dat.gui's the better.  : - )

**Comment by benaadams** [comment]
Added some changes with explanations to https://github.com/cabbibo/InstanceMesh/pull/1/files to show how @cabbibo could change http://cabbi.bo/InstanceMesh/ to use hardware instancing with this PR rather than pseudo-instancing (data repeating); which may help as its a before and after comparision?

**Comment by mrdoob** [comment]
Super lovely work @benaadams! 😊

**Comment by Bigmacbook** [comment]
@benaadams omg that exapmle is only taking 3 renderer.calls

Now is it easy to remove and add new cubes with like one or two lines of code,

we really need this in the next version of three js

**Comment by robhawkes** [comment]
I'm trying to get my head around this fancy instanced BufferGeometry stuff – I understand how it works if you set everything up in one go (and how you can dynamically update the attributes), but I'm unsure about how it works in different dynamic situations.

Specifically, is it possible to dynamically add and remove instances or is this a one-time event, like when merging geometry?

**Comment by mrdoob** [comment]
Please, use SO for help...

**Comment by robhawkes** [comment]
No problem, I didn't do it initially as I thought the feature was still being developed so thought it best to keep implementation questions connected to the issues.

I've [posted it on SO](http://stackoverflow.com/questions/32646531/how-can-you-dynamically-add-and-remove-objects-using-three-instancedbuffergeomet) if anyone knows the answers or is interested in the answer!

**Comment by benaadams** [comment]
Answered

**Pull request merged**
