### PR TITLE
WebGLRenderer: Sort on bounding sphere center, not origin

### LINKED ISSUE #25820: GLTFLoader: Order of nodes in hierarchy is non-deterministic in some cases when compression is used
### Description

When authoring models that use transparency for real-time use, often the order of nodes in the hierarchy is the only option for artists to control transparency sorting. However, it looks like when compression (draco) is used, the hierarchy resulting from a file is non-deterministic - sometimes node A comes before node B and sometimes after, potentially altering the resulting appearance.

The attached file exhibits this behaviour in three-based viewers, e.g.
- https://gltf-viewer.donmccurdy.com/
- https://three.needle.tools/examples/?q=multiple#webgl_loader_multiple

[TransparencyOrder.zip](https://github.com/mrdoob/three.js/files/11215443/TransparencyOrder.zip)

Video of the issue: dropping the same file results in different results on different attempts. For some reason, after a few attempts the result "stabilizes" until the page is reloaded.
https://user-images.githubusercontent.com/2693840/231571409-6cb75554-bd70-4419-ae6a-ea30b7b71646.mp4

Looking at the resulting scene hierarchy, in some cases "Interior" comes after "Exterior" but sometimes the order is reverted. This seems to only happen when compression is used.

Curiously, I can't get this to reproduce in https://modelviewer.dev/editor/; @elalish are you using custom transparency sorting?

### Reproduction steps

1. Open https://gltf-viewer.donmccurdy.com/ or other viewers that use default three.js GLTFLoader + rendering
2. Drop the file attached above
3. Drop the file _again_ - in some cases you'll see an appearance change
4. Drop the file _again_ - appearance will likely change back
5. Refresh the page and repeat 2-4; in some cases one version will already be present at the start, in others subsequent loading will show it

### Code

-

### Live example

-

### Screenshots

_No response_

### Version

latest

### Device

Desktop, Mobile

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by donmccurdy**
It's common practice for modelers to "apply" or "freeze" transforms, setting object origins to zero, which creates a problem for our default sort.

By sorting on the center of an object's bounding sphere, rather than its origin, we may improve the odds of drawing triangles in the intended order. This change fixes #25820, and could reduce overdraw more broadly. I did some light performance comparisons on larger scenes – after the bounding sphere is initially computed, I didn't see a significant difference in sorting one way or another. 

I didn't find any authoritative sources on other engines, but random internet comments claim Unity and Unreal Engine sort by the bounding box center. I use the bounding sphere instead, simply because it's easier and more efficient to access its center than to compute the center of a THREE.Box3 instance.

- Fixes #25820
- Related https://github.com/google/model-viewer/issues/3155#issuecomment-1028566855

### CODE REVIEW

**Comment by donmccurdy** [comment]
One other effect to note – with this change, it's more likely that sort order will change as the camera moves. That's really the point, we've always sorted by z-depth from the camera! But it's something to be aware of, if a previously-stable sort is now view dependent.

**Comment by donmccurdy** [comment]
I searched various discussion threads and found (non-authoritative) claims that Unreal, Unity, and Babylon.js all sort by center of bounds. I couldn't find claims they sort by pivot point. I don't have hard proof here, and it would be great to have that — if you have more information about Unity and Unreal here, could you share it?

**Comment by donmccurdy** [comment]
[Comment](https://forum.babylonjs.com/t/rendering-order-of-meshes-within-the-same-rendering-group/19584/5?u=donmccurdy) by a babylon.js developer, 2021 — _"the default front to back sorting is using the bounding box center as the sorting key"_.

[Comment](https://forum.unity.com/threads/sorting-fudge.450248/#post-2915044) by a Unity developer, 2015 — _"The same way all transparent objects are distance-sorted in unity, which is simply using the center of the AABB (I just checked the code for this, and it surprised me a bit actually.. I would have expected some consideration of box size and closest point to the camera, but it is purely the centre of the box)"_.

**Comment by mrdoob** [comment]
Would be nice to have a debug GLB file that shows how the engine sorts objects.

**Comment by hybridherbst** [comment]
@donmccurdy I'll double check!
@mrdoob I have some (all for bug repros), will see what I can share / how to make it obvious what happens

**Comment by bergden-resonai** [comment]
> simply because it's easier and more efficient to access its center than to compute the center of a THREE.Box3 instance
This doesn't sound like a good reason to do something _similar-ish_ to other engines
Moreover - computing the boundingSphere contains within it the same process for computing the boundingBox
https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L381
(which is very curious by itself - why not codeshare? Maybe even make the boundingBox a bonus artifact of the computeBoundingSphere)

If it's possible to make this change coherent with all the references you mentioned with [8 arithmetic operations](https://threejs.org/docs/#api/en/math/Box3.getCenter) I think it's worthwhile

**Comment by donmccurdy** [comment]
Much of what three.js (or any renderer) does is finding acceptable approximations for exact but costly calculations. In this case, both are approximations. Consider that the additional function calls and arithmetic operations have overhead per object in the scene, and that there may be many, many objects.

There would be a fair case for using the AABB center instead of the sphere center if we had either of: (a) real-world examples where this choice matters, or (b) performance benchmarks showing they are similarly fast for large (1000+ object) scenes.

**Comment by donmccurdy** [comment]
Ah sorry for miscommunication here, but the cost of computing the bounds is not the issue. To my understanding we compute both shapes anyway for frustum culling. This is a one-time initialization cost, unrelated to this PR. 

What I'm concerned about is the _per frame_ cost of extracting the center from our pre-computed bounds. If we're doing that at 60 FPS for 1,000 objects, a few milliseconds of difference would matter.

**Pull request merged**
