### PR TITLE
Example stereo pano

### PR DESCRIPTION
**Pull request by rnixik**
This is a stereo panorama example.
I have captured free demo scene Sun Temple from Unreal Engine 4 using SceneCaptureComponent2D (with rotations and supersampling), got two equirectangular projections for left and right eye. Then I converted them into cube-format. There is stereo issue with floor and ceil, I know how to fix it but I need more time with capturing in UE4. There are 4 additional tiles in atlas for proper dimension of file (power of two). But I did not manage to [get rid of seams](http://stackoverflow.com/questions/35113569/seams-on-cube-edges-when-using-texture-atlas-with-three-js). Then I used canvas and `drawImage` to split textures. So, extra black tiles are not necessary now. Resolution is poor because original png file is too heavy for repository (~20 MB). 

I have added webvr-polyfill because demo works on desktops (Chrome and Firefox). Also it should work with Oculus Rift (but did not tested this example).
I have tested it on Samsung Note 4 (Android 4.4.4) with GearVR (cardboard mode) on Chrome 48.

Screenshot (desktop) demo

### CODE REVIEW

**Comment by mrdoob** [comment]
How about using this stereo panorama instead?

http://code.blender.org/wp-content/uploads/2015/03/gooseberry_benchmark_panorama.jpg

https://code.blender.org/2015/03/1451/

**Comment by rnixik** [comment]
Spherical panorama has artefacts on top and bottom of the sphere.
example

My example should works with panoramas from OTOY Octan Render
https://render.otoy.com/vr_gallery.php?page=4&ipp=10  
Like this one
https://vr1.otoycdn.net/vr/pano/16976_E8CF73F1-0AE3-47B1-AF13-BD5F875D9D37_pano.png

**Comment by mrdoob** [comment]
I see I see!

Ok, the only other thing is that I'm not sure whether we should be including the webvr polyfill. It'll be yet another thing to track.

**Comment by rnixik** [comment]
And I am not sure about the lib. But without it example is static and looks like broken on devices without HMD. It is more universal with webvr polyfill.

**Comment by mrdoob** [comment]
> But without it example is static and looks like broken on devices without HMD.

Yes, I think that's fine. As I said, I just would rather not have to keep track of yet another lib and make sure it's up to date.

**Comment by rnixik** [comment]
I have removed `webvr-polyfill`, implemented fallback for browsers without HMD. Now VR mode works only in Firefox with enabled flags and maybe in Chrome. More info [here](https://developer.mozilla.org/ru/docs/Web/API/Navigator/getVRDevices).  I do not have any HMD for desktop to test it.

On mobile VR mode works only in Firefox Nightly now. Webvr-polyfill did a great job.

**Comment by mrdoob** [comment]
> I have removed `webvr-polyfill`, implemented fallback for browsers without HMD. 

Thanks!

> Webvr-polyfill did a great job.

I can see that you don't agree...

In case you want to understand my logic, the WebGL examples do not automatically use a fallback when WebGL is not available.

**Comment by mrdoob** [comment]
Thanks!

**Comment by rnixik** [comment]
Thank you!

**Comment by mrdoob** [comment]
@rnixik Would it be possible to also create a `sun_temple_stripe.jpg`? That way we can use it as an (non webvr) example of panorama without distortion.

**Comment by rnixik** [comment]
@mrdoob Do you mean like this one https://github.com/rnixik/three.js/blob/ebe818381e2dfd2b8cdf33cb4894859d3747e324/examples/textures/cube/sun_temple_stripe_stereo.jpg but captured for non-stereo?

**Comment by mrdoob** [comment]
Yes. I could cut it but it's a JPEG already...

**Comment by rnixik** [comment]
I have one in png http://s.getid.org/jsfiddle/atlas.png but I guess it has been captured for stereo (has some distortions). And this one http://s.getid.org/pan11/images/sun_temple_stripe_left.png don't know what it is.
If you need pure mono png, I can recapture but after 5th of June only.

**Comment by rnixik** [comment]
In addition, in case you need full stereo png http://s.getid.org/pan11/images/out.png

**Comment by rnixik** [comment]
@mrdoob Did it help?

**Comment by mrdoob** [comment]
I think that should be good enough. Thanks!

**Pull request merged**
