### PR TITLE
Example: Clean up

### PR DESCRIPTION
**Pull request by WestLangley**
Mostly minor clean up...

...but I also changed the default metalness to 0, because the HDR effect -- the point of the example -- is not perceptually different from the LDR case when the metalness is 1.

### CODE REVIEW

**Comment by WestLangley** [comment]
Unrelated: The tonemapping exposure is set like so:
```javascript
renderer.toneMappingExposure = Math.pow( params.exposure, 4.0 );
```
This produces unreasonably overexposed results for the specified [ 0, 2 ] exposure range. I know this was copied from elsewhere, but is there a reason for the power relationship here? Don't we want perceptually-linear behavior? Why not simply:
```javascript
renderer.toneMappingExposure = params.exposure;
```

/ping @bhouston for your thoughts...

**Comment by WestLangley** [comment]
Test link: https://rawgit.com/westlangley/three.js/dev-exr/examples/webgl_materials_envmaps_exr.html

**Comment by bhouston** [comment]
The equation is my fault.

There are two different exposures.  I believe that internally to Three.JS we should keep exposure linear ( https://en.wikipedia.org/wiki/Exposure_(photography) ) but sometimes people like to have perceptual like controls and that is generally an exponeitial ( https://en.wikipedia.org/wiki/Exposure_value ).

Although the question for the exponential is more like ( Math.pow( 2, exposureValue ) * D + C ) = exposure, but I haven't yet researched was D and C are.

**Comment by WestLangley** [comment]
Thanks @bhouston. We can deal with it in a separate PR.

This can be merged, then.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
