### PR TITLE
WebGPURenderer: `transmission` and `clearcoat` shouldn't be ignored in `getMaterialCacheKey`

### PR DESCRIPTION
**Pull request by susiwen8**
Related issue: #27995

|             | before | after |
|-------------|--------|-------|
| transmission |<video src="https://github.com/mrdoob/three.js/assets/20318608/7fec67d1-c11b-4154-9e08-8fa470810a2f"></video>|<video src="https://github.com/mrdoob/three.js/assets/20318608/29d886b1-6d8e-4b95-ba49-7f0ce4111100"></video>|
| clearcoat     |<video src="https://github.com/mrdoob/three.js/assets/20318608/12e27b1b-3136-4f67-b39a-ea650536da40"></video>|<video src="https://github.com/mrdoob/three.js/assets/20318608/d7490ae4-7e6c-4e2b-86c0-051f00249d63"></video>|

### CODE REVIEW

**Comment by susiwen8** [comment]
Also comment in `getMaterialCacheKey` tells
> Convert to on/off, important for clearcoat, transmission, etc

So I think it shouldn't be ignore

**Comment by sunag** [comment]
@susiwen8 Could we use an approach to list the `get` properties too? It can avoid other future problems like `anisotropy`, `dispersion`, `iridescence` and any other customized property that needs this process of optimization.

**Comment by susiwen8** [comment]
`getter` is not enumerable, so I propose replacing those`getter` by `Object.defineProperty`, and set `enumerable` to `true`  @sunag

**Comment by susiwen8** [comment]
Something like
```js
		Object.defineProperty( this, 'clearcoat', {
			enumerable: true,
			get: function () {

				return this._clearcoat;

			},
			set: function ( value ) {

				if ( this._clearcoat > 0 !== value > 0 ) {

					this.version ++;

				}

				this._clearcoat = value;

			}
		} );
```

**Comment by sunag** [comment]
Hmm... I imaged an approach using `Object.getOwnPropertyDescriptors()` to we get all `getters` of a class using a function like `getKeys( material )`.

**Comment by sunag** [comment]
> I'm little confused with the purpose, shouldn't we find which property need to be ignored? @sunag

Yes, using get `getKeys( material )` should show all properties of material, without change the core. We could change for something like `for ( const property of getKeys( material ) ) {..`

**Comment by susiwen8** [comment]
> Using get `getKeys( material )` should show all properties of material, without change the core. We could change for something like `for ( const property of getKeys( material ) ) {..`

I understand the purpose of `getKeys`, but the main purpose of this issue is that we need to find out those properties should be ignored.

`for ( const property of getKeys( material ) ) {..` give us material 
propeties including `getter`, if we do nothing in regular expression, there would be no difference with just remove `_` in regular expression

**Comment by sunag** [comment]
The `_` is used to ignore private variables like `_listeners` for example that is added normaly after this first renderer. Using `getKeys` we should keep the old regexp.

**Comment by susiwen8** [comment]
> The `_` is used to ignore private variables like `_listeners` for example that is added normaly after this first renderer. Using `getKeys` we should keep the old regexp.

I see, you are right @sunag

**Pull request merged**
