### PR TITLE
Docs: Fix Object3D.getObjectByProperty

### PR DESCRIPTION
**Pull request by makc**
the ridiculous :Float misake has been pointed out like half a year ago, and yet nobody is fixing it, so...

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
For consistency... Would it be okay if I change `any` to `Any`?

**Comment by Mugen87** [comment]
Make sense! All other type definitions start with a captial.

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
@mrdoob I kind of went wit typscript `any` subconsciously.  could have just used a `*` or removed a type entirely

**Pull request merged**
