### PR TITLE
Fix Blend Shapes and add Convert to Z Up option in Blender exporter

### PR DESCRIPTION
**Pull request by dougppaz**
- Fix Blend Shapes in Blender Exporter
- Add Convert to Z Up option in Blender exporter
- Extra: Fix no action in animation curves (api/animation.py Blender Exporter)

### CODE REVIEW

**Comment by mrdoob** [comment]
When would Flip Axes need to be used, and when wouldn't?

**Comment by douglasppaz** [comment]
I'm working on a project that receives animation information remotely. I found it to be more practical to use blender axes. I use in the same project, bones and blend shapes too.

**Comment by WestLangley** [comment]
Actually, axes are not "flipped" -- it is a coordinate system rotation of 90 degrees.

**Comment by douglasppaz** [comment]
You right @WestLangley 
What's the best nomenclature to this?

I think I'll create another pull request to correct the blend shape's error. And we come back to discuss this question here.

What do you think? @mrdoob @WestLangley

**Comment by WestLangley** [comment]
Sometimes the term `z-up` is used. /ping @Mugen87 ?

But someone other than myself will have to participate in this particular issue.

**Comment by Mugen87** [comment]
I'm not familiar with Python and the Blender API.

@douglasppaz  This is not the first time the project is faced with this issue. You might find some information in this threads: #11404 and #11540

**Comment by douglasppaz** [comment]
I'll change to "Convert to Z Up" option. Okay?

@WestLangley @Mugen87 Thanks for supporting.

**Comment by douglasppaz** [comment]
Done!

**Comment by mrdoob** [comment]
Lets try to solve #13130 first.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117).

**Pull request closed without merging**
