### PR TITLE
DragControls: Fix drag object in local coordinate

### PR DESCRIPTION
**Pull request by lafflan**
when drag an object who's local position and rotation not equal world position and rotation will cause a wrong effect

### CODE REVIEW

**Comment by sweerwen** [comment]
https://jsfiddle.net/sweerwen/3foLr7sn/195/  see this demo

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/sweerwen/three.js/patch-1/examples/webgl_interactive_draggablecubes.html

**Review by Mugen87 — CHANGES_REQUESTED** [review]

**Comment by WestLangley** [comment]
>when drag an object who's local position and rotation not equal world position and rotation will cause a wrong effect

I expect the problem is simply caused by the rotated parent object. Can you confirm?

---

Also, I suggest you avoid `getWorldPosition()` as it is not efficient. World matrices should have been updated already by the renderer in this case.

**Comment by sweerwen** [comment]
> > when drag an object who's local position and rotation not equal world position and rotation will cause a wrong effect
> 
> I expect the problem is simply caused by the rotated parent object. Can you confirm?
> 
> Also, I suggest you avoid `getWorldPosition()` as it is not efficient. World matrices should have been updated already by the renderer in this case.

**Comment by WestLangley** [comment]
>but It seems that there is no other way to get the world position.

Check the source code for `.getWorldPosition()`.
```javascript
vector.setFromMatrixPosition( object.matrixWorld );
```

**Comment by arodic** [comment]
> I expect the problem is simply caused by the rotated parent object. Can you confirm?

Exactly. Thanks, parent's transform should be taken into account when performing world space transformations.

I would expect similar issue to arise with scaled parent (a common case when importing objects from different world units)

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
In your use case,
```javascript
_selected.parent.worldToLocal()
```
inverts the parent's world matrix repeatedly. This method should not be called in tight loops.

Can you compute the necessary inverse and reuse it?

**Comment by WestLangley** [comment]
> Are you suggesting changes to this PR?

I am suggesting the OP avoid calling `worldToLocal()` in tight loops. I doubt the parent's inverse will be changing while dragging.

**Comment by sweerwen** [comment]
@WestLangley thanks， could you please help to check

**Comment by WestLangley** [comment]
@sweerwen  Yes, that is what I had in mind. I have not tested your code, however.

These convenience methods are just that: convenient. However, they are not necessarily efficient.

Thanks for making the change.

**Comment by Mugen87** [comment]
Looks good 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
