### PR TITLE
WebXRManager: Avoid invalid projection matrices when using depth sensing

### PR DESCRIPTION
**Pull request by mrxz**
Related issue: #29098

**Description**

The `depthFar` and `depthNear` values coming from the depth-sensing module could result in invalid projection matrices (`NaN` values). These errors would propagate (left, right, XR and user camera) resulting in a broken state after exiting the XR session.

This PR includes three changes:

- Only recompute a union projection matrix when far plane is finite. In case of an infinite far plane, reuse the projection matrix of the left view. Offsetting the camera is sufficient to fully include both view volumes, assuming the projections are symmetric (see https://computergraphics.stackexchange.com/a/1737)
- Don't update the `far` and `near` properties of the user camera, instead always treat these as input to _set_ the `far`/`near` of the renderState. When depth-sensing is active, the relevant `depthNear`/`depthFar` values are used for rendering, but not written back to the user-camera.
- Remove calls to `updateProjectionMatrix` added in [6e3137](https://github.com/mrdoob/three.js/commit/6e3137aca34c292dccd137d4c775ae15e2a79ed7). These calls aren't needed, as the projection matrices for the left and right view come directly from the WebXR API and are computed in `setProjectionFromUnion` for `cameraXR`. In fact, as the comment above it indicates, the new far/near values only take effect next frame, so immediately computing them is incorrect for that frame.

*This contribution is funded by [Fern Solutions](https://fern.solutions)*

### CODE REVIEW

**Comment by Mugen87** [comment]
@cabanier Looking good?

**Comment by cabanier** [comment]
> @cabanier Looking good?

Does this update the cameras for the left and right eye? It seems like only the main camera is updated and I seem to remember that one is only used to do culling.

**Comment by mrxz** [comment]
> Does this update the cameras for the left and right eye?

Yes, their `near/far` are updated [here](https://github.com/mrdoob/three.js/pull/29120/files#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7eR558-R559) (like before) and their projection matrices are taken from the `XRView` each frame. There should be no reason to manually (re)construct the projection matrices.

**Comment by cabanier** [comment]
> > Does this update the cameras for the left and right eye?
> 
> Yes, their `near/far` are updated [here](https://github.com/mrdoob/three.js/pull/29120/files#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7eR558-R559) (like before) and their projection matrices are taken from the `XRView` each frame. There should be no reason to manually (re)construct the projection matrices.

Great! lgtm!

**Pull request merged**
