### PR TITLE
TransformControls: Fix gizmo scale hover

### PR DESCRIPTION
**Pull request by enomado**
The bug was:

- https://threejs.org/examples/misc_controls_transform.html
- scale <kbd>R</kbd>
- hover mouse on white gizmo's cubes(any of it). All of them will change color only if hovered only left. Other is not.

Bug was caused by sharing a single color object and mutation of it by the last element.

### CODE REVIEW

**Comment by Mugen87** [comment]
/ping @arodic Is this change okay like that?

**Comment by mrdoob** [comment]
Looks good to me.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
FYI @arodic

**Pull request merged**
