### PR TITLE
add THREE.Mesh.prototype.containsPoint

### PR DESCRIPTION
**Pull request by gonnavis**
example
`mesh.containsPoint(new THREE.Vector3(0,0,0))`

### CODE REVIEW

**Comment by gonnavis** [comment]
Hi mrdoob, I often need to change a mesh to point cloud, so I wrote the [demo](https://github.com/gonnavis/whether_point_in_3d_model) before.
The method is inspired by [this answer](https://blender.stackexchange.com/questions/31693/how-to-find-if-a-point-is-inside-a-mesh), and I summerized to **"Just raycast once from the point to any direction, then check the intersects num, if is odd, the point is in the geometry"**.
And found other people have [the same demand](https://stackoverflow.com/questions/16361327/check-if-point-is-inside-a-custom-mesh-geometry/46993407#46993407), so I think if this method can embed into three.js will be very userful.
But I konw the performance is very bad, may be use gpgpu to speed up? I'll try.

**Comment by WestLangley** [comment]
If the mesh is not watertight -- e.g., a planar mesh, or a cylinder without end-caps, or `TeapotBufferGeometry` -- your approach will either not work, or will not be guaranteed to work. Correct?

**Comment by gonnavis** [comment]
Yes, may use some method to check if the mesh is watertight first?

**Comment by gonnavis** [comment]
Or use a option parameter, let the user to specify the direction, no-matter if the mesh is watertight, just use the direction to check.

**Comment by Mugen87** [comment]
I've never seen that an engine supports such a method in their `Mesh` class. AFAIK, at least Unity does not provide such a functionality. Probably because it's complicated to implement a generic `containsPoint()` method that reliably supports all types of meshes (like @WestLangley mentioned). I prefer to keep such code on app level.

**Comment by WestLangley** [comment]
Right. This is an application-specific method, and it only works in certain cases.

See `examples/js/utils/GeometryUtils.js` for methods that will generate random points on the geometry surface.

**Comment by mrdoob** [comment]
Yeah, I can see this getting people confused when their model is not watertight. I'd prefer to add only robust methods to code. Better to leave this as application-specific.

Thanks though!

**Pull request closed without merging**
