### PR TITLE
NodeMaterial - Intro to boolean, mask and dissolve example

### PR DESCRIPTION
**Pull request by sunag**
### Issue
https://github.com/mrdoob/three.js/issues/15654

### New examples

**dissolve** 
https://rawgit.com/sunag/three.js/dev-mask/examples/webgl_materials_nodes.html?e=dissolve

**dissolve - fire**
https://rawgit.com/sunag/three.js/dev-mask/examples/webgl_materials_nodes.html?e=dissolve-fire

### Description
- `material.mask` show `fragment` if `mask` is `true`
- Automatic `float` and `vectors` convertion to `boolean` and vice versa
- `CondNode` returns boolean values if `ifNode` and `elseNode` is `undefined`
- new `BoolNode`

### Usages
```javascript
// CondNode returns a boolean value
// show fragment only if CondNode returns true
material.mask = new THREE.CondNode(
	maskNode, // mask node
	new THREE.FloatNode( .1 ), // threshold
	THREE.CondNode.GREATER // condition
);
```

```javascript
// show fragment if mask is true
material.mask = new THREE.BoolNode( true );
```

image

### CODE REVIEW

**Comment by sunag** [comment]
image

**Comment by donmccurdy** [comment]
This looks great, and solves the use case I needed – thank you! 👏

Do you want to keep the `.alphaTest` property on StandardNodeMaterial? It seems like the MeshStandardNodeMaterial wrapper could just create a `.mask` socket when it sees `.alphaTest`, and then `.alphaTest` wouldn't need to exist on the new API. Assuming I understand the difference in the two materials correctly. Up to you, though, I'm happy with this PR as-is.

**Comment by mrdoob** [comment]
Very nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by donmccurdy** [comment]
This is working well, thanks!

**Pull request merged**
