### PR TITLE
Texture+WebGLRenderTarget: Replace .encoding with .colorSpace

### PR DESCRIPTION
**Pull request by donmccurdy**
Changes in this PR:

- Texture: Replace .encoding with .colorSpace
- WebGLRenderTarget: Replace .encoding with .colorSpace

The .encoding property will continue to work, with a deprecation warning, for the next ~10 releases. The default value of texture.colorSpace is `THREE.NoColorSpace | ''`, and not `THREE.LinearSRGBColorSpace | 'srgb-linear'`, because relatively few textures are Linear-sRGB in typical usage, and NoColorSpace is a more appropriate choice for non-color data like normal and roughness maps. Color textures should be manually assigned `THREE.SRGBColorSpace | 'srgb'`.

Whether WebGLRenderTarget should default to THREE.NoColorSpace or THREE.LinearSRGBColorSpace is a good question for thought, but in practice it makes no difference — neither is handled any differently by the renderer at this time.

Remaining changes for r152, in next PRs:

- [x] WebGLRenderer: Change default output to sRGB
    - https://github.com/mrdoob/three.js/pull/25783
- [ ] Update documentation

Related issue:

- https://github.com/mrdoob/three.js/issues/23614

### CODE REVIEW

**Comment by donmccurdy** [comment]
@Mugen87 I've made backwards-compatible updates to property names here, but haven't updated any usage of the properties in examples. I'm happy to do that in this PR, or another, as you prefer. I though it might be helpful to see that the E2E tests continue to pass before examples are updated.

@WestLangley How do you feel about the choice of defaults here?

**Comment by WestLangley** [comment]
>@WestLangley How do you feel about the choice of defaults here?

I think it is the correct choice.

**Comment by Mugen87** [comment]
> I thought it might be helpful to see that the E2E tests continue to pass before examples are updated.

Good idea! Since the tests pass, I think we can use this PR to update the rest of the codebase accordingly. In this way, the task is logically bundled in one PR.

**Comment by donmccurdy** [comment]
@Mugen87 ok – tests are green! ✅

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
