### PR TITLE
Modified EffectComposer such that offscreen rendertarget size takes properly into account display pixel ratio

### PR DESCRIPTION
**Pull request by robertoranon**
This PR is meant to solve issue [#12188](https://github.com/mrdoob/three.js/issues/12188). In short, the EffectComposer, when creating render targets for offscreen rendering, calls `renderer.getSize`, which does not keep into account Display Pixel Ratio (DPR). As a result, when using DPR > 1 and the Effect Composer, final rendering is downsampled, as with DPR = 1.
With the modification, the Effect Composer now calls `renderer.getDrawingBufferSize()` instead of `getSize()`, and thus follows the DPR set in the renderer.

### CODE REVIEW

**Comment by mrdoob** [comment]
We could also add `setPixelRatio()` to `EffectComposer` and use it case by case.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@mrdoob Did you notice that commit 3 has nothing to do with this issue?

**Comment by Mugen87** [comment]
I just want to draw some attention to https://github.com/mrdoob/three.js/pull/12206/commits/b3cf1c73c279d7d9788d4a9735d17dcb7893b50c. 

@robertoranon Can you explain why this commit was in your PR? I think we should revert it because this changes were not discussed in any form...

**Comment by robertoranon** [comment]
Hi, honestly, I don't know. I did the PR with just the changes for the Effect Composer issue. Then, in a separate thread here on Github (which was specifically about the Outline effect) I was commenting about a change I did to use other colors also for highlighting, and somehow this got into the PR?

Anyway, you can revert it, the changes have nothing to do with the original issue the PR was meant to solve.

**Comment by WestLangley** [comment]
> I think we should revert it because these changes were not discussed in any form...

Commit 3 also appears to break the outline effect by rendering outlines that should be hidden.

**Comment by Mugen87** [comment]
#12281

**Comment by mrdoob** [comment]
> @mrdoob Did you notice that commit 3 has nothing to do with this issue?

I did. But yeah, I agree that we should probably discuss that change first.

**Pull request merged**
