### PR TITLE
Equirect shader: Support decoding, tonemapping, and output encoding

### PR DESCRIPTION
**Pull request by WestLangley**
... just as we did for the cube shader.

### CODE REVIEW

**Comment by WestLangley** [comment]
Please, let's not block this PR, but I think we should find a better way to support code injection for non-built-in materials -- assuming there is a better way. This is how it is done in this PR, and elsewhere in the library:
```javascript
// enable code injection for non-built-in material
Object.defineProperty( equirectMaterial, 'map', {

	get: function () {

		return this.uniforms.tEquirect.value;

	}

} );
```
Code injection only works for materials having recognized property names, i.e., the built-in materials.

/ping @bhouston @mrdoob @donmccurdy

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
This PR requires a new build.

**Comment by mrdoob** [comment]
Done 👍

**Pull request merged**
