### PR TITLE
EXRLoader, HDRCubeTextureLoader, RGBELoader: setType() -> setDataType()

### PR DESCRIPTION
**Pull request by WestLangley**
As suggested in https://github.com/mrdoob/three.js/pull/16768#issuecomment-501529345.

I updated the TS flies. I'm assuming the JSM javascript files can be auto-generated.

I can update the examples if this is merged.

### CODE REVIEW

**Comment by Mugen87** [comment]
> I can update the examples if this is merged.

I don't think it's good to separate this task into two PRs. Please do this all at once.

**Comment by WestLangley** [comment]
>I don't think it's good to separate this task into another PR. Please do it all at once.

The jsm files need to be updated first, otherwise the examples will break.

I'll update the examples after the jsm files are updated.

**Comment by Mugen87** [comment]
Why don't you update them yourself?
```
node utils/modularize.js
```

**Comment by WestLangley** [comment]
@Mugen87 oh. well, that was easy. :-)

**Comment by WestLangley** [comment]
Done!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks! 😇

**Pull request merged**
