### PR TITLE
Removed outro from Rollup config

### PR DESCRIPTION
**Pull request by cecilemuller**
Because it's appended as-is to the bundle, which makes an error at runtime given `exports` is undefined in the ES bundle. However this implies one should use `THREE.getAudioContext()` instead of `THREE.AudioContext`.

### CODE REVIEW

**Comment by mrdoob** [comment]
You're changing the API...
Is there any way we can keep `THREE.AudioContext`?

**Comment by cecilemuller** [comment]
I'd rather not change the API either, but the trouble is ES modules don't seem allowed to export a getter.

However if the result is constant (or can the audio context change like canvas context ?), then /src/Three.js could export the result as AudioContext without using `outro`.

**Comment by fazeaction** [comment]
Better than remove outro inside rollup.config.js, I've tried this:

```var outro = `export var AudioContext = getAudioContext();````

and that seems works properly. Now you can acces THREE.AudioContext like this:

```
import * as THREE from 'three'
console.log(THREE.AudioContext)
```

Someone can confirm it?

**Comment by cecilemuller** [comment]
Exactly, the only way to preserve the API as-is would be to create an instance of AudioContext at startup because there doesn't seem to be a way to export a getter as far as I can tell (which makes sense given it would defeat the purpose of static dependencies).

**Comment by mrdoob** [comment]
Seems like we've finally hit a limit of es6 modules 😁

**Comment by Rich-Harris** [comment]
Yep, in an ES6 world, having a named binding that is a getter is sort of incoherent – it'd be like having a variable that didn't initialise until you used it. The point of the workaround was to preserve the behaviour for existing (UMD) users while still allowing the codebase to be modularised. The ES bundle (which wasn't part of that original work) can't have an `AudioContext` export – I think it'll have to have a separate config altogether.

My advice from the sidelines would be to export `getAudioContext` and deprecate `THREE.AudioContext` for everyone – still have it in the UMD build to avoid breakage, but start steering people towards `getAudioContext`. That way, when browsers natively support modules (which I believe isn't that far away), Three will be ready.

**Comment by AlbertoElias** [comment]
Is there a temporary recommended workaround for the time being?

**Comment by cecilemuller** [comment]
I'll close this PR and send a new one with the outro only in the umd build.

**Pull request closed without merging**
