### PR TITLE
Audio: Add missing sign in pause().

### PR DESCRIPTION
**Pull request by Mugen87**
see #18664. Sorry, I've missed to add the `+` sign 😇 .

### CODE REVIEW

**Comment by Mugen87** [comment]
Updated test fiddle with latest `dev` build:

https://jsfiddle.net/4m0c67x8/

**Comment by mrdoob** [comment]
That... doesn't look right to me... 🤔

**Comment by Mugen87** [comment]
I've tested the fiddle quite a while and it seems the correct approach to compute the `offset` parameter for `AudioBufferSourceNode.start()`. The value is relative to the `when` parameter which is something I've realized when testing the fiddle from @SUDOCS.

**Comment by SUDOCS** [comment]
@mrdoob @Mugen87 
I think `this.context.currentTime - this._startedAt` means the duration between two pauses. It could be a negative number when user clicks pause in the time less than `delay`(also with other condictions). So I agree with the implementation like so:
```
this._pausedAt += Math.max( this.context.currentTime - this._startedAt, 0 ) * this.playbackRate;
```

However, `pause()` also goes wrong when audio looping. I tried to improve it in `play()` like so:
```
source.start(this._startedAt, (this._pausedAt + this.offset) % this.duration, this.duration);
```
but `this.duration` always be `undefined`.

My mother language isn't English and my understanding of `AudioBufferSourceNode.start ()` is not very thorough, so sorry for my possible mistakes in advance.

**Comment by shootTheLuck** [comment]
Hello  All!

I noticed this same issue with pausing/restarting _looped_ audio and was working on it in a similar way.  Hopefully, mentioning this here is ok as opposed to opening another issue.  I was able to make it work properly by changing the line @SUDOCS mentions in the `play()` method to:

`source.start( this._startedAt, ( this._pausedAt + this.offset ) % this.buffer.duration, this.duration );`

If `loop.Start`/`loop.End` are set I guess it might get more complicated...

r115

**Comment by Mugen87** [comment]
> but this.duration always be undefined.

The property is `undefined` unless you assign a value to it. It is optional and can be used to overwrite the default duration of the audio buffer.

@shootTheLuck It seems your code does not work if `Audio.duration` is set by the user since you always use the duration of the buffer. Maybe like so:
```js
var offset = ( this._pausedAt + this.offset ) % ( this.duration || this.buffer.duration );
source.start( this._startedAt, offset, this.duration );
```

**Comment by shootTheLuck** [comment]
@Mugen Awesome!  I didn't know about using duration either but I see it now in the docs.  

I spent yesterday playing with this sound: https://opengameart.org/sites/default/files/audio_preview/54321GO.ogg.mp3 :flushed:  and have a suggestion for pausing with `loopStart / loopEnd` that seems to work pretty well.

I'd be thrilled to be able to share it in operation and I signed up with jsfiddle but I'm not able to get your fiddle https://jsfiddle.net/4m0c67x8/ to work anymore...nor the one I'm trying to set up here: https://jsfiddle.net/shootTheLuck/cnf14gv9/latest/ .  

If you'd like, my suggestions for `.pause` and `.play` (and `stop`) are in the fiddle and marked with ///***.   I'd be interested to know what you think!

**Comment by Mugen87** [comment]
Can you try it with the following fiddle? https://jsfiddle.net/smhrdac4/

I've only updated the audio file. It's now one of the repository.

**Comment by shootTheLuck** [comment]
Hi and Thanks!

https://jsfiddle.net/shootTheLuck/6jsnLuq2/32/

Hopefully that works to demonstrate

**Comment by Mugen87** [comment]
> However, pause() also goes wrong when audio looping. I tried to improve it in play() like so:

@SUDOCS I've tested your code and I don't think it works. Why do you think that the computed offset should be modulo the audio buffer's duration? Even if an audio is looped, the duration does not change.

**Comment by shootTheLuck** [comment]
@Mugen87  Hello, my apologies if I'm mistaken, but did you mean me?  Looking back on this, I seem to have been the one to bring up the buffer duration... and you rightly corrected me with:

>  Maybe like so?

>var offset = ( this._pausedAt + this.offset ) % ( this.duration || this.buffer.duration );
source.start( this._startedAt, offset, this.duration );

**Comment by Mugen87** [comment]
I'm actually referring to this post^^: https://github.com/mrdoob/three.js/pull/18676#issuecomment-588580517

**Comment by Mugen87** [comment]
@shootTheLuck Sorry, I was confused by my own suggestion because I've tested with a badly audio file. This one made it much more easier to debug the issue:

https://audiojungle.net/item/male-voice-counting-1-to-10/21677488

**Pull request merged**
