### PR TITLE
New DecalGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
This PR re-implements `DecalGeometry` and moves it from the examples directory to the core. Features:

- `DecalGeometry` now produces `BufferGeometry`
- The implementation supports meshes based on `BufferGeometry`(new) or `Geometry`
- The generation process is more memory efficient (although there is still some room for improvements)
- More comments and a new doc page
- I've also updated the example
- The constructor parameter slightly changed. The optional `check` parameter was removed and `orientation` must be an `Euler` now.

Naming conventions are aligned to this great article (it is also linked in the source code): http://blog.wolfire.com/2009/06/how-to-project-decals/

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
For consistency, we may want to add the usal proxy thing though...

https://github.com/mrdoob/three.js/blob/dev/src/geometries/BoxGeometry.js#L6-L29

**Comment by Mugen87** [comment]
`DecalGeometry` is like `WireframeGeometry` or `EdgesGeometry`. There is no need for a `Geometry` proxy.

**Comment by mrdoob** [comment]
Good point.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Yay :tada:

**Pull request merged**
