### PR TITLE
Added refractor example

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces a new object `THREE.Refractor` which can be used to create planar refractive (see-through) surfaces like water or windows.

Objects of type `THREE.Refractor` are treated like transparent objects, so they are rendered in back to front order. The implementation supports multiple refractive objects in a scene graph with linear time complexity.

The implementation is similar to `THREE.Mirror`. But things like the virtual camera or the refraction plane are calculated differently. I'm planning to slightly refactor `THREE.Mirror` so it can be used in combination with `THREE.Refractor` in order to create more advanced water effects.

### CODE REVIEW

**Comment by Mugen87** [comment]
BTW: The PR does not change the core of the library. Just example code :blush:

**Comment by mrdoob** [comment]
YESSS!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I'm really enjoying these self-contained, self-rendering objects... `Mirror`, `Water`, `Refractor`, ... I'm also planning on moving `THREE.Lensflare` to this approach too.

We may want to look for a name for these... Components, Plugins, Smart Objects, ...? 😅

/cc @WestLangley

**Comment by WestLangley** [comment]
>We may want to look for a name for these... 

I would just call them Classes.

**Pull request merged**
