### PR TITLE
MeshLambertMaterial: Added support for lightMap, aoMap, emissiveMap

### LINKED ISSUE #7812: lightMap not usable in MeshLambertMaterial anymore
Hello!

Why are lightMaps not supported for MeshLambertMaterials any longer? Is there another way to achieve the same use with another property?

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #7812.

This is a first step. Additional cleanup will follow in a later PR.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
We could just kill MeshLambertMaterial and have a flag or something for where the lighting calculation happens -- like .useVertexLighting = true/false.  I think it may not be the hardest change now.

**Comment by WestLangley** [comment]
@bhouston Thing is, `MeshPhongMaterial`, having specular highlights, will not render properly if lighting is computed per-vertex on low-poly meshes.

**Comment by bhouston** [comment]
@WestLangley But non-specular highlights also render poorly with MeshLambertMaterial -- imagine a single quad floor -- any lights that are near it but are not anywhere close to its extend will basically render their lambert contributions wrong as well.

I think that calling it vertexLighting is more accurate than Lambert and unifying it will remove a lot of code and make ThreeJS easier to use.

But then again if I had unlimited time, I'd also get rid of Basic as well, it is just a Standard material with emissive and that ignores lights.

Maybe one can unify the idea of no lighting, vertex lighting, pixel lighting, face lighting as a single parameter:

```
material.lighting = [ THREE.PixelLighting | THREE.VertexLighting | THREE.FaceLighting | THREE.NoLighting ]
```

**Comment by bhouston** [comment]
I guess I do not have any issues unifying the materials because the way the shaders are creating in ThreeJS is that there if you are no using various options, the glsl code generated for the material gets smaller.

**Comment by mrdoob** [comment]
I agree with @bhouston. If there is a way to add `material.lighting = [ THREE.PixelLighting | THREE.VertexLighting | THREE.FaceLighting | THREE.NoLighting ]` that would simplify things a lot. Stating with just `[ THREE.PixelLighting | THREE.VertexLighting ]` will already clean up quite a bit.

**Comment by WestLangley** [comment]
As a first step, I have to clean up `MeshLambertMaterial` a bit to share more code with `MeshPhongMaterial`.

**Comment by bhouston** [comment]
BTW I think FaceLighting can not really be done in the glsl shader by itself -- it is most about data preparation of the normals prior to GPU upload.  So I think that only the Pixel, Vertex, NoLighting are really feasible.

**Pull request merged**
