### PR TITLE
Examples: More module examples.

### PR DESCRIPTION
**Pull request by Mugen87**
Moving on with material examples...

### CODE REVIEW

**Comment by Mugen87** [comment]
Half of the job is done 😉

**Comment by mrdoob** [comment]
Amazing! Thanks!

**Comment by WestLangley** [comment]
So... these informative commands no longer work in the console.

    > renderer.info

    > scene.children

**Comment by Mugen87** [comment]
Well, using modules means moving away from polluting the global namespace and all related problems. If these commands does not work anymore, we are doing everything right.

**Comment by WestLangley** [comment]
That reply is not helpful. I suppose that means you do not have a solution to the issue I raised?

**Comment by mrdoob** [comment]
@WestLangley the Chrome DevTool is almost ready ^^

**Pull request merged**
