### PR TITLE
src/objects: move to es6 classes

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
Related issue: #19986

**Description**

This PR moves most of the `src/objects` folder to es6 classes. The reverted commits were on the scripts which would've failed the e-2-e tests.

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
daaaamm. ok. single file per commit and then later:
`git revert [commit]`
When files conflicts become a thing.

**Comment by DefinitelyMaybe** [comment]
@Mugen87 @mrdoob this one might be ready for review 🙏

**Comment by Mugen87** [comment]
Since `Squash and Merge` is not enable for this project, I suggest you reset to the commit you have started this PR (the one before 917c08a2d770a016fdbeab3df20f990a9492c1e3), then commit your changes and force push the single commit.

Right now, the commit history is of this PR quite ugly.

**Comment by DefinitelyMaybe** [comment]
#21266

**Pull request closed without merging**
