### PR TITLE
Docs: Improve Clock page.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #23693

**Description**

Clarifies the documentation page of `Clock` to avoid further confusion that becomes apparent in #23693.

### CODE REVIEW

**Comment by 1337816495** [comment]
Hi, clock also starts automatically when `getElapsedTime` is called for the first time.
By the way, can I contribute the corresponding Chinese documentation (based on your PR)?

**Comment by 1337816495** [comment]
> 

Because `getElapsedTime` internally calls `getDelta`.

**Comment by Mugen87** [comment]
> By the way, can I contribute the corresponding Chinese documentation (based on your PR)?

Feel free to do so!

**Comment by 1337816495** [comment]
> 

okkkk！

**Pull request merged**
