### PR TITLE
Examples: Removed deprecated THREE.ClosedSplineCurve3

### PR DESCRIPTION
**Pull request by Mugen87**
Nothing special. This PR just replaces `THREE.ClosedSplineCurve3` with
`THREE.CatmullRomCurve3` to avoid undesirable warnings.

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks. There is also a lingering reference to `ClosedSplineCurve3` in `Curve.js`.

**Comment by Mugen87** [comment]
@WestLangley Nice catch :+1:

**Comment by Mugen87** [comment]
Besides, can we move `THREE.ClosedSplineCurve3` to `THREE.Legacy.js`?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> Besides, can we move `THREE.ClosedSplineCurve3` to `THREE.Legacy.js`?

Yep!

**Comment by Mugen87** [comment]
Ok. I'll do this with a new PR...

**Comment by WestLangley** [comment]
>Nice catch

I thought you were going to replace the comment, not remove it. : - )

**Comment by Mugen87** [comment]
> I thought you were going to replace the comment, not remove it. : - )

Oops! I'll correct this with the next PR...

**Comment by Mugen87** [comment]
Um, moving `THREE.ClosedSplineCurve3` to `THREE.Legacy.js` procudes the following warning when you build the library:

_/var/folders/gq/fc_dn3d14jdgnlmt0hfs6t340000gn/T/tmpoULwwM:32951: WARNING - THREE.CatmullRomCurve3.prototype defined before its owner. THREE.CatmullRomCurve3 is defined at /var/folders/gq/fc_dn3d14jdgnlmt0hfs6t340000gn/T/tmpoULwwM:35629
THREE.ClosedSplineCurve3.prototype = Object.create( THREE.CatmullRomCurve3.prototype );_

This line seems problematic if it's in `THREE.Legacy.js`.

```javascript
THREE.ClosedSplineCurve3.prototype = Object.create( THREE.CatmullRomCurve3.prototype );
```

**Comment by Mugen87** [comment]
I think the problem is that `extras.json` is included after `common.json` in the build. So with the current setup we are not able to move code from `/extra` to `THREE.Legacy.js`. One solution could be a separate legacy file for `/extra` that is include in `extras.json`.

**Pull request merged**
