### PR TITLE
Quick FBXLoader Fixes

### PR DESCRIPTION
**Pull request by Kyle-Larson**
A couple of things I missed from refactoring FBXLoader.

- Loader now works for models that are not rigged to skeleton.
- Now uses XHRLoader instead of deprecated FileLoader.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm? `XHRLoader` is the one that is deprecated 🤔

**Comment by Kyle-Larson** [comment]
... Apparently that is so.  Did this get deprecated between r82 and current dev?  If so, I'll change that back, and I guess I have to keep a separate version running for my project that is using r82.  I guess I assumed that the examples page would be older than the most current release 😖.  I'll remove the XHR changes then.

**Comment by mrdoob** [comment]
You can also do this in your project...

```js
if ( 'FileLoader' in THREE.=== false ) THREE.FileLoader = THREE.XHRLoader;
```

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
