### PR TITLE
Add dispose function to VREffect to prevent memory leak

### PR DESCRIPTION
**Pull request by cnspaha**
Add dispose function to VREffect. Otherwise it causes a memory leak if it is instantiated several times -> always add eventlistener on window

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Why are you instantiating it several times though?

**Comment by PaHae** [comment]
Thanks for the merge ;)
I have an application which uses a lot of different views. And sometimes when a view isn't needed anymore it will be destroyed. Also our 3d view will be destroyed if we don't need it anymore. And when we need it again we make a new instance of it and of course we also have to instantiate the VREffect again which is a member of our own renderer "class".

either way adding listeners to a object, especially the window, without having a way to remove it isn't good^^

**Comment by PaHae** [comment]
do you think u can commit this fix to the r81 tag?

**Pull request merged**
