### PR TITLE
Refactor GridHelper to support different size and divisions

### PR DESCRIPTION
**Pull request by Makio64**
**Description**

GridHelper can now receive a width/height and different division. The previous signature still work ( synthax inspired by animejs ) 

`new GridHelper( size , divisions, color1 , color2 )`
`new GridHelper( 10 , 10, 0xff0000 , 0x00ff00 )` create a grid of 10x10 divide 10 times.
`new GridHelper( [5,10] , [5,2], 0xff0000 , 0x00ff00 )` create a grid of 5x10 divide 5 time on x axis and 2 times on z axis 

Can also mix the int / array for size/divisions

### CODE REVIEW

**Comment by Mugen87** [comment]
I'm not sure about this, tbh. It seems having grids like that is a quite specific thing. In order to keep the helper straightforward, I currently tend to leave this bit out.

**Comment by Makio64** [comment]
@Mugen87 I often found myself needing it while doing editor or prototyping so I though it might be profitable to others. 

Here some use cases not squared : 
- "Infinite runner" level editor : long tiles of 3 x 100 to put obstacles on it
- Rooms editor prototype : placing items on a grid based on a wall / floor in a not cubic room
- Dungeon game prototype : the fight in each rooms are on a grid based but the battlefield is not always squared

But I think the code added is too big for the usage, I will try to make it more small and elegant

**Comment by Makio64** [comment]
@Mugen87 i reduced the code, its 67lines in total but if you think its too much, maybe in addons or in a Gist

**Comment by Mugen87** [comment]
The new approach is indeed cleaner! Let's see what @mrdoob thinks about this feature.

**Comment by Mugen87** [comment]
Even if the approach is cleaner I still prefer the existing, more simple solution. Putting a more advanced grid helper in a Gist or even in a external repository sounds more appropriate.

**Pull request closed without merging**
