### PR TITLE
TS: Update LineSegments

### PR DESCRIPTION
**Pull request by ycw**
remove 3rd param, `mode` is redundant.
prop `type` is always "LineSegments", so use literal type is sufficient.

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like this PR is creating a bunch of linting issues?
https://github.com/mrdoob/three.js/pull/20295/files

**Comment by ycw** [comment]
`LineSegments` is the base type of bunch of helpers which **do** change the prop `type`, so the old one is fine.

LineSegments.d.ts
```ts
type : 'LineSegments' | string
```

**Comment by Mugen87** [comment]
@ycw Please always target the `master` branch when making PRs.

**Review by Mugen87 — APPROVED** [review]

**Comment by ycw** [comment]
my bad.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
