### PR TITLE
CompressedTexture: Add more ASTC formats.

### LINKED ISSUE #18764: sRGB ASTC formats not supported
##### Description of the problem:

Three.js supports [a number of ASTC formats](https://github.com/mrdoob/three.js/blob/dev/src/constants.js#L118), but not [the complete set](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_texture_compression_astc_hdr.txt) (ctrl+f "0x93D7"). The omission of the \*\_SRGB8\_ALPHA8\_\* formats means that Three.js won't load properly-encoded sRGB ASTCs. This is because ASTC can encode RGB data as either linear or sRGB, but it can only encode the alpha channel as linear. When using sRGB encoding, the RGB and the Alpha channels are distinct and a different format, and thus enum, is used.

I've put together a somewhat crude [example](https://jsfiddle.net/hrpj50Le/).

If line 50 calls getBase64ImgL(), it loads the KTX file containing the linearly-encoded ASTC. If your device doesn't support ASTC, you'll get the following, expected warnings: 

I also print out the texture object, and we can see that the texture's internal format is 37815, the enum for an RGBA 8x8 ASTC. (If your device does support the format, it should show up as the texture on the plane, but my phone doesn't seem to like jsFiddle)

If line 50 instead calls getBase64ImgS() to load the sRGB texture, the error is different:

The texture's format is 37847, which is the enum for an SRGB8_ALPHA8 8x8 ASTC but isn't defined as such by Three. Because Three.js doesn't even realize it's looking at an ASTC texture, there is also no warning about device compatibility (and it will still fail even if your device supports ASTC)

If #12939 is good indication, implementing these formats may be as easy as adding the appropriate enums to constants.js and WebGLUtils.js, but I don't have easy means to tinker with it myself.

I'm including the ASTC (actually, KTX) files I'm using, generated with PVRtexTool as a GUI for ASTCEnc.exe: [ASTCTestSet.zip](https://github.com/mrdoob/three.js/files/4264299/ASTCTestSet.zip)

##### Three.js version

- [x ] Dev
- [x ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android (especially)
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
ASTCs ought to work on Oculus Quest and most Android phones, but JSFiddle doesn't so if you want to see for yourself, it'll take some work.

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #18764.

@YorickCobb `37847` should now be recognized as `SRGB8_ALPHA8_ASTC_8x8_Format`. Does the PR look good to you?

### CODE REVIEW

**Comment by YorickCobb** [comment]
Works perfect 👍

**Comment by donmccurdy** [comment]
How do the sRGB formats work in conjunction with `texture.encoding`? Would you also set `texture.encoding = THREE.sRGBEncoding` on a texture using `SRGB8_ALPHA8_ASTC_8x8_Format`, or is the sRGB->linear step done by WebGL?

**Comment by YorickCobb** [comment]
You still have to set `texture.encoding` for it to render correctly, but I humbly suggest that this is the correct behavior. AFAIK sRGB-encoded PNGs for example still default to linear encoding, so it would be inconsistent if ASTCs/any other specific format didn't also respect the default. The advantage in sRGB-encoded textures is that the bit depth is spread out more usefully, so this doesn't make the distinction useless or anything.

**Comment by Mugen87** [comment]
>  or is the sRGB->linear step done by WebGL?

[EXT_sRGB](https://developer.mozilla.org/en-US/docs/Web/API/EXT_sRGB) is for this use case. In WebGL 2 you can use the respective formats without the extension. 

So when defining the internal format of a texture as `gl.SRGB8`, the texture will be automatically converted to linear space when being fetched in the shader.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
