### PR TITLE
Add SSRrPass (screen space refraction)

### PR DESCRIPTION
**Pull request by gonnavis**
Add **SSRrPass** (**s**creen **s**pace **r**ef**r**action), based on https://github.com/mrdoob/three.js/pull/20156 .

[Demo](https://raw.githack.com/gonnavis/three.js/SSRrPassPr/examples/webgl_postprocessing_ssrr.html)

image

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good!

Are you planning on ignoring the fragments that are occluded by other objects?

**Comment by gonnavis** [comment]
OK, yes, I'm doing on this.

**Comment by gonnavis** [comment]
> Are you planning on ignoring the fragments that are occluded by other objects?

Done. But using the same on/off material strategy like SSRPass which need re-render whole scene once more.
I'm curious about if can directly copy `beautyRendertarget`'s existing `depthBuffer` to `normalRendertarget`? Not found in RenderTarget's doc.

**Comment by gonnavis** [comment]
Still many features can be added, such as: light focusing, semitransparent shadow, double sided, stacked transparent objects,  etc.
But I feel need more long time to do these, the current state may be suitable as a first step.

**Comment by mrdoob** [comment]
Looking great!

I think we don't need the metalness slider:

Screen Shot 2021-03-13 at 9 30 27 AM

And I think the output should be `Refractive` instead of `Metalness`?

**Comment by gonnavis** [comment]
Thanks！

The metalness and roughness sliders are used for specular effect, it's different from the metalness output, and yes, the metalness output naming is wrong, I'll change it.

**Comment by gonnavis** [comment]
Hello Mr.doob, I renamed `Metalness` to `Refractive`, and let `specular` togglable, but keep `metalness` and `roughness` sliders unchanged. Is it ok?

**Comment by mrdoob** [comment]
Any ideas of why light reflection jumps/pops?

https://user-images.githubusercontent.com/97088/111066510-66973800-84b7-11eb-8df5-68956df4c143.mp4

**Comment by gonnavis** [comment]
Hello Mr.doob, I tried on my P40, iPhone6sp and Win10PC, the light reflection of them all very smooth.
 
I searched and found that Pixel 4a use Adreno GPU, which I noticed in three.js's src that has many workarounds for it, may the problem is because of the special Adreno GPU? 
I added a `Specular` output, could you please try in this output mode? ( which should no SSRr logic involved )
If still jumps, I think it should be the problem of special Adreno GPU.

**Comment by marcofugaro** [comment]
Looks awesome! I noticed some artifacts appearing as well, though you might want to know.

They appear when the scene background color is behind. They don't happen with the ground plane.

image

**Comment by gonnavis** [comment]
Thanks! I think it's may caused by large depth difference,  I'll try to improve it.

**Comment by gonnavis** [comment]
Oops! When debugging this issue, I added a `DepthSelects` OUTPUT and found it was pure white.

It turns out that the previous `tDepthSelects` information is completely wrong. This explains a lot of my previous questions, such as can not having too high IOR, why the refraction of the box is oblique, etc.

However, a new visual error has been introduced and is still being processed.

Left before, right after.
image

**Comment by gonnavis** [comment]
Hello @marcofugaro , I found the gaps in `img1` is caused by too high `maxDistance`, may related to pricesion problem or something else, still researching. Now I let the `maxDistance` configurable, for this demo scene, I found the value `15` is most suitable, `img2`.

But for the whole artifacts before the background, `img2`, it's cause by the refraction ray not hit any rendered pixel, so fallbacked to initial rendered pixels at this palce, this fallback is very useful at areas like `img7`.
I think it's a limitation of screen-space, I have tried to use the end pixel of the refraction ray if not hit, [demo](https://raw.githack.com/gonnavis/three.js/SSRrPassArtifactsShared/examples/webgl_postprocessing_ssrr.html), it can solve this specific area's artifacts `img3`, but caused more artifacts at elsewhere, `img5` `img6`. 
May have some good way to over-render the scene to compensate it, but for simple pure screen-space-refraction, may no good solution.

For gaps at `img4`, it's another issue that related to `surfDist`, this is a predictable problem, same as SSRPass, but I don't know why the effects thus high, and can't find a very suitable `surfDist` value for all the scene, still researching.


image

**Comment by gonnavis** [comment]
> For gaps at img4, it's another issue that related to surfDist, this is a predictable problem, same as SSRPass, but I don't know why the effect thus high, and can't find a very suitable surfDist value for all the scene, still researching.
EDIT: Found that surfDist=0.5 is the most compromised value for this demo scene, changed.

Completely solved. Turned out that caused by the same reason as https://github.com/mrdoob/three.js/pull/20156#issuecomment-767009995 that refract ray too perpendicular to screen, cause it march far away even just one pixel step, so go behind the surface it should collide.
Solved [this](https://github.com/gonnavis/three.js/blob/3aac348a0af8a38a322a2d777e0a8968e5c0fe83/examples/jsm/shaders/SSRrShader.js#L201) simultaneously ( same reason ).

But now too accurate, if the rendered pixles not face camera ( like the ground below ) thus has large gap, will not pass the `away<=sD` check, thus will not be refracted, caused the holes on bunny's back 🤔. Still thinking about how to make up for this shortcoming.


image

**Comment by gonnavis** [comment]
Tried to implement `accurate` or `rough` option per object, but the result seems too complex, and facing the same difficult choices at [there](https://github.com/mrdoob/three.js/pull/21487).

So just add a overall `infiniteThick` option like SSRPass, but turn it on by defualt, to ensure bunny's display effect ( especially the back ), but sacrificing some detailed parts ( especially thre refrections on the cube ). Let user choose use which overall setting or implementing `accurate` or `rough` option per object by themsevlves.

**Comment by gonnavis** [comment]
> They appear when the scene background color is behind. They don't happen with the ground plane.

@marcofugaro Solved! After the commits above, now just increase the `maxDistance` can solve this problem! Surprisingly the specular improved too!

Still not sure how it works, because I'm not sure what's the `viewPosition` of background is, but for this demo scene, `maxDistance=50` is enough. Keep researching.

image

**Comment by gonnavis** [comment]
Add setting: fillHole.

`fillHole` vs pure `infiniteThick`
image

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I think this code is going to be very useful for implementing [KHR_materials_ior](https://github.com/KhronosGroup/glTF/pull/1718), [KHR_materials_translucency](https://github.com/KhronosGroup/glTF/pull/1825) and [KHR_materials_volume](https://github.com/KhronosGroup/glTF/pull/1726) 👍

**Comment by vinkovsky** [comment]
Amazing work! Does it works with screen space reflection shader?

**Comment by vinkovsky** [comment]
It would be great to be able to change the refractive index for every object in the scene

**Comment by gonnavis** [comment]
@vinkovsky Thanks!

> It would be great to be able to change the refractive index for every object in the scene

Not yet in the release, but I'm working on this https://github.com/mrdoob/three.js/pull/21487 . Can copy the codes to your project first if necessary.


> Does it works with screen space reflection shader?

Threejs's compoer system can be connected in series, so simple answer is can. But I think It'll has problem and hard to choose use wich first.

I want to combine SSRPass and SSRrPass into something like SSRaytracePass, to make them work together and reuse the diffuse/depth/normal infos to improve performce. But the two existing Passes has much to be improved like the above one, so may need more time.

**Comment by vinkovsky** [comment]
Thanks for the quick response @gonnavis ! i appreciate your work!

**Pull request merged**
