### PR TITLE
Automatic matrixworld calculation

### PR DESCRIPTION
**Pull request by gero3**
Continuation of #6851

This is the solution of updating matrixworld without the need to call updatematrixWorld().

What has changed:
- Properties:
  - `Matrix` and `matrixWorld` are always up to date (They get calculated when called). 
  - `Matrix` can be set to a specific matrix. `matrixAutoUpdate` should be set to false.
- Methods:
  - `updateMatrix`: checks if position, rotation and scale haven't changed and recalculates only when changed Before this were always recalculated. This should only be called when matrixAutoUpdate is false and the matrix is in need of an update.
  - `_updateMatrixWorld`: This is an internal method. This calculates the matrixworld based on the previous calculated parent matrixworld and matrix. This is also the method that needs to be overridden when the matrixworld needs to be calculated differently. [example](https://github.com/gero3/three.js/blob/MatrixworldUpdate/examples/js/Gyroscope.js#L14-L63)
  - `updateMatrixWorld`: This calculates the matrixworld by calculating the parents matrixWorld and its onw matrix. Internally it calls `_updateMatrixWorld`.
  - `_updateChildrenMatrixWorld`: This is an internal method. This calculates the matrixworld based on the previous calculated parent matrixworld and matrix and off all its children.  Internally it calls `_updateMatrixWorld`.
  - `updateChildrenMatrixWorld`:This calculates the matrixworld by calculating the parents matrixWorld and its own matrix and that of its descendants. Internally it calls `_updateChildrenMatrixWorld`.

@WestLangley, @mrdoob

### CODE REVIEW

**Comment by WestLangley** [comment]
So users should never have to call `updateMatrix()` or `updateMatrixWorld()` or `updateChildrenMatrixWorld()`. Correct?

Also, the bug that `updateMatrixWorld()` did not update parents is corrected by this PR.

In the renderers, you call `scene.updateChildrenMatrixWorld()` each render loop. Why, exactly, is this beneficial? In other words, why is it faster this way?

And of course, many thanks. : - )

**Comment by gero3** [comment]
> So users should never have to call updateMatrix() or updateMatrixWorld() or updateChildrenMatrixWorld(). Correct?

correct

> Also, the bug that updateMatrixWorld() did not update parents is corrected by this PR.

indeed
 
> In the renderers, you call scene.updateChildrenMatrixWorld() each render loop. Why, exactly, is this beneficial? In other words, why is it faster this way?

This is needed because of deep hierarchies and the renderers should make use of cached matrices.

> And of course, many thanks. : - )

**Comment by gero3** [comment]
This has the same performance as current dev.

**Comment by gero3** [comment]
updated the description.

**Comment by gero3** [comment]
It seems ready to be added to the repository

**Comment by gero3** [comment]
Is there still a problem with this PR??

**Comment by mrdoob** [comment]
Sorry for the delay. Having a look now.

**Comment by gero3** [comment]
Is this PR for R72 or are we waiting till r73? I would prefer to get it in as soon as possible tough.

**Comment by mrdoob** [comment]
Merging this at the moment 😉

**Comment by mrdoob** [comment]
Unfortunately the performance regression is a bit too much 😕

Chrome:
```
webgl_performance.html: 56fps to 53fps
webgl_performance_static.html: 60fps to 53fps
webgl_performance_deep.html: 56fps to 51fps
```

Firefox:
```
webgl_performance.html: 48fps to 40fps
webgl_performance_static.html: 48fps to 45fps
webgl_performance_deep.html: 55fps to 35fps
```

**Comment by gero3** [comment]
The above commits should fix the performance problems.

**Comment by mrdoob** [comment]
I'm really hesitant to merge this one... I think I would be less scared if it was split into different parts.

1. Split `updateMatrixWorld()` to `updateMatrixWorld()`, `updateAncestorsMatrixWorld()`  and `updateChildrenMatrixWorld()`.
2. Replace `this.updateMatrixWorld( true )` and `this.matrixWorld` instances with `this.updateAncestorsMatrixWorld()` or `this.getUpdatedMatrixWorld()` (instead of "magical" getters/setters)

I think the idea of making it just work is great, but I think it would make things extra difficult to spot bugs or performance issues in people's code.

**Comment by WestLangley** [comment]
In an effort to find a compromise so we can move on, perhaps we can omit the lazy updating of matrices, and just create the necessary methods to do what we need.

1. `updateMatrixWorld()` must produce the correct answer. That means it must bubble up the tree. It doesn't; it traverses down the tree. @gero3 has a solution for that. I propose that `updateMatrixWorld()` be modified to do what its name says it does. It should not update the matrices of children.

2. Since the renderer needs to traverse the scene graph, create another method called `updateMatrixWorldOfChildren()`, or just add a recursive flag: `updateMatrixWorld( recursive )`.

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7019

**Comment by brianpeiris** [comment]
For those following along @gero3's quest, the latest PR is #9410

**Pull request closed without merging**
