### PR TITLE
Object3D: Update world matrix prior to use

### LINKED ISSUE #20220: localToWorld uses matrix from the previous frame
##### Description of the problem

It seems that `Object3D.prototype.localToWorld` (and all other matrix-related stuff) works with the matrix that is not up to dated.
This can be easily checked by the following code:

```typescript
const object = new three.Mesh(
    new three.BoxGeometry(1, 1, 1),
    new three.MeshBasicMaterial,
);

// expected : 0, 0, 0
// actual   : 0, 0, 0
console.log(object.localToWorld(new three.Vector3(0 ,0, 0)));

object.position.set(1, 2, 3);

// expected : 1, 2, 3
// actual   : 0, 0, 0
console.log(object.localToWorld(new three.Vector3(0 ,0, 0)));

object.updateWorldMatrix(true, false);

// expected : 1, 2, 3
// actual   : 1, 2, 3
console.log(object.localToWorld(new three.Vector3(0 ,0, 0)));
```

The only way to fix this is to use `updateWorldMatrix` (or render the scene) to force matrix update.
In my case this causes a camera to lag behind the object which it is tracking. That was definitely not what I was expect to see, so I think this should be fixed.

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #20220.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by donmccurdy** [comment]
I'm still a bit unsure about this... see discussion in https://github.com/mrdoob/three.js/issues/20220. I like the direction of https://github.com/mrdoob/three.js/issues/13704#issuecomment-684066122 though, @WestLangley, do you think that changes the plan for this PR?

**Comment by WestLangley** [comment]
@donmccurdy The short-answer is 'no'. I think this PR should be merged. I know you have strong feelings about this topic, and we can always make further changes if you feel it is warranted.

**Comment by donmccurdy** [comment]
There are well-documented performance bottlenecks coming from `updateMatrixWorld`:

- https://github.com/mrdoob/three.js/issues/14135
- https://github.com/mrdoob/three.js/issues/14360
- https://discourse.threejs.org/t/updatematrixworld-performance/3217
- https://github.com/mozilla/hubs/pull/753

Admittedly, there are also plenty of questions and confusion stemming from users not knowing when to update matrices manually. In the past, I've advised people to use `localToWorld` when `getWorldPosition()` was causing performance issues. As a result, this change will be a bug fix for some users, and a performance regression for other users.

I would like to offer some way to easily opt out of the cost of these updates, if we're going to enable them by default. Perhaps a method of Matrix4 that operates directly on a Quaternion, or a method of a Quaternion that directly applies a Matrix4? Maybe traverse the `object.parent` chain and bail out on the update if `scene.autoUpdate` is false?

**Comment by WestLangley** [comment]
>There are well-documented performance bottlenecks coming from updateMatrixWorld:

Those four links are old, and do not pertain to the current implementations in the library.

Let's ensure the calculations produce the correct answer first, and worry about performance second.

**Comment by donmccurdy** [comment]
> Let's ensure the calculations produce the correct answer first, and worry about performance second.

There is a (difficult) decision underlying these API questions, but it's not about correct vs. incorrect — it's about how much simplicity in an API is worth, and at what point performance considerations take precedence. 

Of the two obvious paths — faster and harder to use vs. slower and easier to use — my own preference is that these methods (localToWorld, worldToLocal, getWorldPosition, getWorldRotation) should not perform world matrix updates. I do not think our getters should have side effects, or make defensive updates. But I'd be OK with a holistic decision on these methods that is consistent, even if it's not the one I prefer. And in that sense, this PR does make all of the methods behave the same way, so that's good.

It's not my intention to block this PR, so if @mrdoob or @Mugen87 feel that it's a good change, please do go ahead and merge it. I would recommend including something in the release notes: for any application that already calls these methods correctly, the update will add overhead without changing the result.

**Comment by WestLangley** [comment]
@donmccurdy Maybe we can add an arg to the API that can be used to prevent tree traversals. How does that sound to you?

**Comment by mrdoob** [comment]
Sorry, I need more time to review this one. Moving it to the next release.

**Comment by WestLangley** [comment]
This PR is a follow-up to #19969.

**Comment by WestLangley** [comment]
This is not getting traction, so closing.

I still support the change, however.

**Pull request closed without merging**
