### PR TITLE
Add types property to indicate the main declaration file

### PR DESCRIPTION
**Pull request by hujiulong**
Add `types` property to indicate the main declaration file.
[docs](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

### CODE REVIEW

**Comment by hujiulong** [comment]
How about we just ignore .js files in the src folder to reduce the size of npm package?

**Comment by donmccurdy** [comment]
@mrdoob we wanted to allow people to import from the src/ dir anyway right? May as well start including it I think.

**Comment by Mugen87** [comment]
Just for my understanding: `package.json` already refers to `three.module.js`. Wouldn't it a bit redundant if users can import classes from this module and the source files.

**Comment by donmccurdy** [comment]
Completely redundant, yes. But at least the source files themselves are small, especially compared to `examples/models`. Part of the idea behind converting the `.glsl` files to `.js` was to change the `package.json` pointer:

- main -> build/three.min.js
- module -> src/Three.js

... In theory, this means build systems using ES modules are more likely to tree-shake the library effectively. But at the moment we have more hypotheses about how tree-shaking works than actual evidence... including them in the module _without_ replacing the `module` entry might be safe way to let users test this in their build systems and get some early results.

All that to say, I'm fine with including the `src/` tree in the npm package.

**Comment by hujiulong** [comment]
@mrdoob Hi, So can you merge this PR?

**Comment by Methuselah96** [comment]
@donmccurdy Yeah, I just tested this locally and it works. There are some things that need to be fixed about the typings (they don't export all of their interfaces (e.g. `ExtrudeGeometryOptions`, `TextGeometryParamters`, etc.), just the ones that match three.js classes (`ExtrudeGeometry`, `TextGeometry`, etc)), but I can fix that in a separate PR.

**Comment by mrdoob** [comment]
> Just for my understanding: `package.json` already refers to `three.module.js`. Wouldn't it a bit redundant if users can import classes from this module and the source files.

`three.module.js` includes [Three.Legacy.js](https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js) and seems like build tools have a hard time to tree-shake all that. When importing directly from `src/`, build tools seem to produce smaller outputs.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
