### PR TITLE
support costume painter sort functions

### PR DESCRIPTION
**Pull request by ranbuch**
As discussed [here](https://github.com/mrdoob/three.js/issues/13889#issuecomment-385225320) I've created a PR that enables support for dynamic sort functions.

### CODE REVIEW

**Comment by Mugen87** [comment]
Please remove all build files from the PR.

**Comment by Mugen87** [comment]
Now you have removed the build files from the repo^^

**Comment by ranbuch** [comment]
@Mugen87 I've reverted to my first commit but couldn't see `three.js` and `three.module.js`.
I've un-commited only `three.min.js`.
Let me know if there's still an issue, maybe it's best to delete this PR and I'll create a new one.

**Comment by Mugen87** [comment]
The change list looks still not correct. Maybe it's better to start from scratch...

**Comment by donmccurdy** [comment]
One way to reset the build files would be:

```
git checkout dev -- build/
```

But now I don't see the non-build files so maybe something has gone wrong. 😅

**Pull request closed without merging**
