### PR TITLE
Removed ImageUtils

### PR DESCRIPTION
**Pull request by Mugen87**
Removed the deprecated `ImageUtils`. The code of this file was not used in the entire repo anymore.

### CODE REVIEW

**Comment by tentone** [comment]
Hi i would prefer to move this to a examples/js/utils folder.

I think that the ImageUtils class migth be of help sometimes.

**Comment by donmccurdy** [comment]
@tentone It's in examples already — was there a particular part that looks helpful? 

I think `generateDataTexture` seems fairly trivial, and could just be an example in the docs for [THREE.DataTexture](https://threejs.org/docs/#api/textures/DataTexture).

Computing a normal map from a height map is more complex, but there's no threejs-specific code in that at all, and you can find essentially the same source code on www.paulbrunt.co.uk/lab/heightnormal/ or https://github.com/mrdoob/three.js/issues/427.

So for me, +1 on removing ImageUtils, and we can add links to any appropriate resources instead.

**Comment by Mugen87** [comment]
> I think generateDataTexture seems fairly trivial, and could just be an example in the docs for THREE.DataTexture.

Good idea! I'll add the code to the documentation page.

**Comment by tentone** [comment]
Totally agree.

I only see value in the normal map generator as well, the datatexture generator is really simple.

But i also don't have any specific reason to remove it from the repo, i find it to be useful and it is not part of the core anyway.

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
> But i also don't have any specific reason to remove it from the repo, i find it to be useful and it is not part of the core anyway.

It's just more to maintain is the issue; ideally the `examples/js/*` folder should contain examples of three.js-specific things. A generic WebGL example like this would be better in a blog post or GitHub gist somewhere.

**Comment by mrdoob** [comment]
> I only see value in the normal map generator as well.

I think that code will be more useful in `texgen.js` 😊 #todolist

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
