### PR TITLE
OBJLoader: When a new o/g starts, inherit the currently parsed material.

### LINKED ISSUE #8792: OBJLoader: resets declared usemtl on new object
In the current implementation when new `o/g` is encountered the parser forgets what the current `usemtl` declaration was and sets an empty material name to the parser state. If I understand the spec correctly, it should use the declared material for any objects until it is changed.

This will produce objects that are missing the material name if the obj file does not explicitly say `usemtl` after each `o/g` line. Most exporters seem to do this always but I've encountered files that do not.

Fairly trivial fix. Making an issue so I remember to fix this, if someone does not beat me to it.

```
usemtl material_name

Polygonal and free-form geometry statement.

Specifies the material name for the element following it. Once a
material is assigned, it cannot be turned off; it can only be
changed.

material_name is the name of the material. If a material name is
not specified, a white material is used.
```
http://www.martinreddy.net/gfx/3d/OBJ.spec

### PR DESCRIPTION
**Pull request by jonnenauha**
Inherited material is overwritten if 'usemtl' declaration is encountered after the object starts but prior to next object start. Exception to this is when faces have been declared to the inherited material, to keep MultiMaterial in sync (that skeleton asset had this bug, rare but happens).

Fixes #8792 and #8871 (@mrdoob those can be closed).

P.S. I'm sad I missed the r77 by a day :( Anyone needing the fixes, just copy the OBJLoader from dev after this has been merged.

### CODE REVIEW

**Comment by jonnenauha** [comment]
My current obj test set, yey for obj loader :)

image

**Comment by WestLangley** [comment]
@jonnenauha If the material file lists 5 materials, do all the objects share single instances of those 5 materials -- or does each object get its own cloned copy?

**Comment by jonnenauha** [comment]
I haven't done any changes to that aspecct while working on the loader. If you load and set a .mtl file for the loader prior to parsing, my understanding is that per unique material name, you are sharing it across all submeshes that use it. 

https://github.com/jonnenauha/three.js/blob/d2e8afc0b4cb9b821248907b7cfcca785cf5296a/examples/js/loaders/OBJLoader.js#L648-L683

Its simply calling the create on MTL creator that afaik returns the same material after initial create.

If you don't set a loader, you'll get back unique phong materials for each submesh even if same material name is referenced multiple times.

This would be a easy fix to `.clone()` here https://github.com/jonnenauha/three.js/blob/d2e8afc0b4cb9b821248907b7cfcca785cf5296a/examples/js/loaders/OBJLoader.js#L659 but IMO this would be the wrong way to go, if the obj declared that two or more should use the same material, user would also expect if he modified one of them all of them get updated. If you wish to do per submesh material mods, you could clone it then.

Also some obj files I work with get huge, like 4000 draw calls huge, while many thousands might reference the same solid color material. It would probably not be good to clone each to be unique automatically.

I have done an app side optimization that can merge all mesh geometries that use the same material after the OBJLoader is done. This is a huge win in certain models, dropping draw calls from 4k to ~10-20.

**Comment by WestLangley** [comment]
@jonnenauha Thank you for your reply.

> If the obj declared that two or more meshes should use the same material, user would also expect if he modified one of them all of them get updated.

Yes. This is what I think the behavior should be.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> P.S. I'm sad I missed the r77 by a day :( Anyone needing the fixes, just copy the OBJLoader from dev after this has been merged.

Promoted to r77! 😊

**Comment by jonnenauha** [comment]
@mrdoob cool, thanks :) If you have time you could reference the other PR in the release changelog as well

> Added multi-material and geometry group support in OBJLoader. #8689 (@jonnenauha)

Adding https://github.com/mrdoob/three.js/pull/8691 also to that line. Might be good for people to track stuff if they are interested, the bulk of the multi material / group stuff is in that PR.

**Comment by mrdoob** [comment]
Done!

**Pull request merged**
