### PR TITLE
GLTFLoader: Support sparse accessors.

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes https://github.com/donmccurdy/three-gltf-viewer/issues/53.

References:
- https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#sparse-accessors
- https://github.com/KhronosGroup/glTF-Sample-Models/issues/99

/cc @takahirox

### CODE REVIEW

**Comment by takahirox** [comment]
Any reasons that this PR doesn't care `sparse.count`, `sparse.indices.byteOffset`, and `sparse.values.byteOffset`?

**Comment by donmccurdy** [comment]
You're right, those should be checked... pushed a change that I think fixes it, but I don't have the test model on this computer so let me verify it later today.

**Comment by donmccurdy** [comment]
Ok, I think it's all set.

**Comment by takahirox** [comment]
Looks ok to me now.

**Comment by mrdoob** [comment]
Thanks!

**Comment by cx20** [comment]
I updated the status of gltf-test. Three.js is all green again.
https://github.com/cx20/gltf-test#gltf-20-sample-models

https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=SimpleSparseAccessor&scale=1&type=glTF

**Pull request merged**
