### PR TITLE
LWOLoader: dev branch factorization

### PR DESCRIPTION
**Pull request by sciecode**
This PR intends to return LWO main development branch to three.js and extend a factorization scheme per discussed on threejs/lwoloader#24

It does not include update to typescript definition per module import, which I think might be necessary. If it is, I would like to request help from someone more familiar with it, as my version would likely be useless.

**discussion**
I would like to just briefly discuss my opinion on the failed approach of trying to maintain a separated dev repository from Three.js. Having an autonomous control of development is beneficial, but having to keep both Three.js version and Dev branch files synchronized proved to be a bigger burden.

If we were to try a similar approach for other loaders in the future, I would strongly recommend using `git submodule` approach where the entire development is also moved to a different repository.

### CODE REVIEW

**Comment by sciecode** [comment]
https://rawcdn.githack.com/sciecode/three.js/fad42e6be39949b2ebc2b27878fcc8eabe21f4eb/examples/webgl_loader_lwo.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> If we were to try a similar approach for other loaders in the future, I would strongly recommend using `git submodule` approach where the entire development is also moved to a different repository.

One downside of submodules is that when you download the repo as a zip file submodules are not included. Or at least that used to be the case years ago.

**Comment by looeee** [comment]
`git clone --recurse-submodules` will clone with submodules. But I don't think there's any way to download them in the zip. 

Here are the previous discussion related to the LWOLoader being in a separate repo:
#16679 #16678

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Guilherme Avila <notifications@github.com>
发送时间：2020-05-17 07:19
主题：Re: [mrdoob/three.js] LWOLoader: dev branch factorization (#19378)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

https://rawcdn.githack.com/sciecode/three.js/fad42e6be39949b2ebc2b27878fcc8eabe21f4eb/examples/webgl_loader_lwo.html

**Pull request merged**
