### PR TITLE
Attempt to work around compiler errors regarding IncidentLight return variable

### PR DESCRIPTION
**Pull request by bhouston**
Tryinng to adddress this bug: https://github.com/mrdoob/three.js/issues/8161

But I can not reproduce the bug so this workaround is guided by @kozec first suggestion here: https://github.com/mrdoob/three.js/issues/8161#issuecomment-200730919 and my similar suspicions mentioned here: https://github.com/mrdoob/three.js/issues/8161#issuecomment-200347933

Please test this fix @doexclusive, @Frankling, and anyone else who has seen it.

### CODE REVIEW

**Comment by bhouston** [comment]
Test link: http://ci.threejs.org/api/pullrequests/8461/examples/webgl_materials_envmaps_hdr.html

**Comment by kozec** [comment]
I can confirm that test link works on NVidia Quadro 600 in same configuration as where original problem was present.

**Comment by Frankling** [comment]
@bhouston hi this example can compile by default ,as you can see below, just some warnings
qq 20160325083833

the test link one screen shot below:
qq 20160325083933

the problem is the example link:
http://threejs.org/examples/webgl_loader_collada_keyframe

qq 20160325084408

when I changed the pointLight to DirectLight ,it worked,BTW, when I changed the pointLight to SpotLight it produce the same problem as the pointLight

**Comment by Frankling** [comment]
below is the console.log produced when i change the shader which you did 

[Uploading localhost-1458868507361.log.txt…]()

**Comment by bhouston** [comment]
You can test the other examples with the change in this or via this link:

http://ci.threejs.org/viewpullrequest.html#8461

**Comment by Frankling** [comment]
@bhouston  thanks, it worked now, I will test more examples to make sure it has no bugs

**Comment by mrdoob** [comment]
@kozec @Frankling can you guys confirm that this shadertoy reproduces this issue? https://www.shadertoy.com/view/lddXD8

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@kozec @Frankling can you guys confirm that this shadertoy reproduces this issue? https://www.shadertoy.com/view/lddXD8

**Comment by kozec** [comment]
Sorry, but I will not have access to problematic machine until monday.

**Comment by Frankling** [comment]
@mrdoob it doesn't reproduce issue

**Comment by mrdoob** [comment]
Oh... I may not understand what the issue is then...

**Comment by WestLangley** [comment]
@mrdoob Did you merge this into master and not rebuild?

**Comment by mrdoob** [comment]
Oh... I thought this was targeting `dev`.

**Comment by mrdoob** [comment]
I'll undo the merge and merge into `dev` instead...

**Comment by mrdoob** [comment]
Done. Thanks @WestLangley!

**Pull request merged**
