### PR TITLE
WebGLTextures: Avoid memory leaks when logging warnings

### LINKED ISSUE #11378: Maybe a memory leak when using canvas to show images.
##### Description of the problem 

[JSFiddle here](https://jsfiddle.net/liyuanqiu/wkdgt8h7/5/)

I record the performance in Chrome when running this JSFiddle, it shows:
1024x1024
The memory peak value getting higher and higher, but the valley value always keeps a low value.

Then uncomment the two lines in line number 30 and 31:
```
width = 1000;
height = 1100;
```
The canvas size is not power of two, and the memory usage increases rapidly

the performance record shows:
1000x1100
The memory peak value and valley value both getting higher and higher.

I call the dispose method of material and texture explicitly, and remove the mesh from scene in every loop.

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes #11378

This PR removes passing `image` to `console.warn` to avoid memory leaks.

Yes, it's better to avoid NPOTs.
But I don't think passing `image` to `console.warn` is very helpful.
From the other side, it can create huge memory leaks, when using big NPOT canvases.

Eventually, we can pass `image.src` (if available) instead of `image`.

### CODE REVIEW

**Comment by Mugen87** [comment]
It's interesting that passing the image object to `console.warn` causes a memory leak. I'm fine with your suggested change, I just wonder if you have some sort of source that documents/proofs this behavior.

**Comment by cherniavskii** [comment]
@Mugen87 sure, I can setup an example. I just need some time for that ;)

**Comment by cherniavskii** [comment]
Actually, there already is a good example from https://github.com/mrdoob/three.js/issues/11378#issue-230583893:

Steps to reproduce:
1. Open https://jsfiddle.net/liyuanqiu/wkdgt8h7/5/
2. Change `width` to `1000` (line 27)
3. Rerun fiddle
4. Open Chrome Task Manager (Shift + Esc)
5. See how Memory Footprint increases drastically

To make sure that this issue is caused by reference in console:
1. Add `window.console.warn = () => {}` in line 25
2. Rerun fiddle
3. See how Memory Footprint doesn't increase that much

**Comment by Mugen87** [comment]
Yeah, I can reproduce. It really makes a difference if a normal warning is logged with just some text like in this [example](https://jsfiddle.net/wkdgt8h7/26/) or if the image object is passed in...

**Comment by Mugen87** [comment]
> Eventually, we can pass image.src (if available) instead of image.

I think the PR is okay like that. User can still set breakpoint at the warning at then investigate the `image` object.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
BTW: Can you also remove the `image` object from the warning in `clampToMaxSize()`?

https://github.com/mrdoob/three.js/pull/14483/files#diff-973542b02af23aede566f8cb84c7212eR39

Same problem...

**Comment by cherniavskii** [comment]
@Mugen87 done!

**Comment by cherniavskii** [comment]
@Mugen87 

What do you think about those lines? `texture` is passed to `console.warn` too.

https://github.com/mrdoob/three.js/blob/0949e59f3a4978efc39d7c1366d26274b7d9af82/src/renderers/webgl/WebGLTextures.js#L404

https://github.com/mrdoob/three.js/blob/0949e59f3a4978efc39d7c1366d26274b7d9af82/src/renderers/webgl/WebGLTextures.js#L413


I don't have those warnings in my app, but maybe it's worth to remove them too?

**Comment by Mugen87** [comment]
I think it's consistent if we don't log these objects, too. You can clean up the warnings in `setTextureParameters()` and `setTexture2D()`.

**Comment by WestLangley** [comment]
Please remember to target the dev branch when submitting a PR.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
