### PR TITLE
Fix CircleBufferGeometry

### PR DESCRIPTION
**Pull request by brason**
Off by one :)

### CODE REVIEW

**Comment by benaadams** [comment]
Is it? (Might be)

What about when ```thetaLength``` is not ```Math.PI * 2```? e.g. its not a full circle, but an arc

**Comment by brason** [comment]
Oops... But I'm positive it's off by one. Should it be `s < vertices - 1` then?

**Comment by brason** [comment]
I tried it with other values of `thetaLength` and it seemed to work.

**Comment by benaadams** [comment]
Yeah that's an off by one error :)

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
