### PR TITLE
Remove webgl_materials_texture_3d.html

### PR DESCRIPTION
**Pull request by takahirox**
I've missed removing `webgl_materials_texture_3d.html` in #14951

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
While you're at it... Can you also rename these examples to `webgl2_materials_texture3d.html` and `webgl2_materials_texture3d_volume.html`, uncomment this section of the `files.js` and move the examples there?

https://github.com/mrdoob/three.js/blob/dev/examples/files.js#L315-L319

**Comment by mrdoob** [comment]
Actually, I'll do it myself.

**Comment by mrdoob** [comment]
Done. #14965

**Comment by takahirox** [comment]
Sorry I was having dinner

**Comment by mrdoob** [comment]
No worries!

**Comment by mrdoob** [comment]
Looking tidier:
https://rawgit.com/mrdoob/three.js/dev/examples/?q=webgl2

**Pull request merged**
