### PR TITLE
Speedup Matrix inverse

### PR DESCRIPTION
**Pull request by Corey-Maler**
Remove function call gives up to 30% of speedup. See comparison https://jsfiddle.net/xqs0st3c/

### CODE REVIEW

**Comment by bhouston** [comment]
Nice.

**Comment by mrdoob** [comment]
Should we do the same with `Matrix4.getInverse()`?

**Comment by Corey-Maler** [comment]
Ow, I didn't expect a much speed up in Matrix4, but tests (https://jsfiddle.net/xqs0st3c/1/) shows that in Matrix4 it is even faster (on my computer 1500ms vs 1000ms thats ~35%).

P.S. In google chrome on Mac OS.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Usnul** [comment]
for those that are curious why this happens. There are 2 read passes over elements array in the original implementation (one in main body of getInverse and one in multiplyScalar), also if you do an "instanceof" check instead of "elements.length === 9" you get numbers more like these:
```js
Matrix3 test
 T…E.Matrix3 {elements: Float32Array[9]}
old: 438.133ms
new: 347.131ms
```  

which is more like a 20% saving and not 30, still super useful though :)

**Pull request merged**
