### PR TITLE
MMD assets license

### PR DESCRIPTION
**Pull request by takahirox**
Do you mind if I move MMD assets from Three.js repository to another repository

https://github.com/takahirox/mmd-assets

and let `webgl_loader_mmd*.html` examples load them via rawgit?

I reviewed their licenses and realized that they shouldn't be under MIT license repository
because (they're ok to be used for Three.js examples but) most of them don't allow commercial use.

LMK if there's any better  ways.

### CODE REVIEW

**Comment by takahirox** [comment]
Ops, I close PR so far because I need to solve this error.

MMDLoader.js:2451 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.(…)

**Comment by mrdoob** [comment]
Hmm... There idea of the repo always was to be able to download it and everything works. There are no dependencies...

So, unless we find assets that can be included here, we'll have to remove the examples too 😕

**Comment by takahirox** [comment]
Hmm...... probably there's no MMD assets which can be under MIT license repository.... Hmmm.......

**Comment by yomotsu** [comment]
We can use Mobuko-san(モブ子さん), which is provided as a public domain MMD model with PMCA.
see http://matosus304.blog106.fc2.com/blog-entry-215.html

> PMCAに付属しているパーツは全てパブリックドメイン相当とし、その利用に制限を求めません。また、作者はパーツを利用した事によって生じた損害に対し一切の責任を負いません。

-> Models built with PMCA are under the PublicDomain, and no limitation to use. also, the author will  will not take full responsibility for that.

still need to think about music and VMD files tho

**Comment by takahirox** [comment]
@yomotsu 

Thanks. But as you mentioned we need to solve the license issues of all MMD assets...

Anyways let me open this PR again because we need clear this issue.

**Comment by mrdoob** [comment]
Hmm, I don't think I agree with "poluting" the examples folder with a new folder. Why not just keep it in `examples/models/mmd`?

**Comment by takahirox** [comment]
I see, I've reverted.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
