### PR TITLE
WebGLRenderer: Remove gammaOutput, introduce outputEncoding.

### PR DESCRIPTION
**Pull request by Mugen87**
As proposed in #11337.

This PR removes `gammaOutput` and introduces `outputEncoding` as a replacement. `gammaOutput` can still be used, however a warning will be generated. The renderer ensures to update materials if `outputEncoding` is changed during runtime.

There is in subtle change that needs some highlight: `getTextureEncodingFromMap()` does only depend from the given map now. That means the previous behavior of automatically setting the `encoding` of a render target's textures to `GammaEncoding` if `gammaOutput` is `true` does not exist anymore. This is also the correct behavior from my point of view. Meaning, when using post-processing via `EffectComposer`, `WebGLRenderer.outputEncoding` should not be changed and gamma correction should be done via `ShaderPass` and `GammaCorrectionShader`. Check out how `webgl_materials_normalmap` is written now to see this idea in action.

### CODE REVIEW

**Comment by WestLangley** [comment]
It is not appropriate to use both of these patterns in the same example:
```js
renderer.outputEncoding = THREE.GammaEncoding;

texture.encoding = THREE.sRGBEncoding;
```

Doing so will cause color distortion.

In the examples, use `THREE.sRGBEncoding` for both texture encoding and renderer output encoding.

Some users prefer the flexibility of `GammaEncoding` in combination with `renderer.gammaFactor`. I think it would be appropriate to have one example use that case.

**Comment by Mugen87** [comment]
> Doing so will cause color distortion.

I've just tried to retain the current visuals as good as possible. If things can be improved, I'm glad to do this with this PR.

**Comment by Mugen87** [comment]
> I think it would be appropriate to have one example use that case.

Do you have an example already in mind?

**Comment by WestLangley** [comment]
It would have to be one without textures, I guess...

**Comment by Mugen87** [comment]
How about `webgl_buffergeometry`?

**Comment by WestLangley** [comment]
>How about webgl_buffergeometry?

Or none. I don't have a strong opinion on that.

**Comment by Mugen87** [comment]
Then I would leave it out for now since the API is proper documented. If necessary, we can still update one of the examples in the future.

**Comment by mrdoob** [comment]
Many thanks!

**Comment by Mugen87** [comment]
Yay! It's great to get rid of `gammeInput` and `gammaOutput` in a single release^^

**Comment by mrdoob** [comment]
So many things are being solved in this release 😍

**Comment by Mugen87** [comment]
I would say it's the best release 2019 😁

**Comment by mrdoob** [comment]
Getting it ready for the next decade 😀

**Pull request merged**
