### PR TITLE
WebVR Examples: Update 'Enter VR' button copy based on supported API

### PR DESCRIPTION
**Pull request by mvilledieu**

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/mvilledieu/three.js/WebVR-Examples--Update-Enter-VR-Button-Copy-to-XR/examples/index.html?q=webvr

**Comment by mrdoob** [comment]
Hmm, this is how it used to be before. https://github.com/mrdoob/three.js/commit/266b13932cb61c210e64a932d03e406a80a25eea#diff-4488c2b5394be3dc8ef1cdeeaf06d72c
But I thought `XR` would be confusing for users so I unified both cases to just `VR`.

However, I guess this change is coming from Magic Leap and in that case there is not really `VR`...? 🧐

**Comment by mvilledieu** [comment]
Ouuups, I see! Yes coming from Magic Leap, I just found it somehow confusing for users to have the `Enter VR` button "only" since in my mind it directly referred to the `WebVR API`, so I thought that having them differentiated not by types of devices but by types of APIs being called would sort of make sense for now?

I guess in the near future once the `WebXR API` first official release happens we could just rename everything to `XR` as it used to be called since `XR` will technically englobe everything? 

I felt the same about `renderer.vr` but felt like it was still early to rename all that? Let me know your thoughts.

**Comment by mrdoob** [comment]
I was thinking it would be simpler to create 2 different code paths. AR examples are probably going to be different than VR examples. So for AR examples we can create a WebAR.js that also uses the WebXR API to display a `[START AR]` button or something.

What do you think?

**Comment by mvilledieu** [comment]
Yes, this makes sense to me. Specifically for the examples since as you mentioned they will, for sure, be different in the future. 

Let me close that one!

**Pull request closed without merging**
