### PR TITLE
Nodes: Rename invert() -> oneMinus()

### PR DESCRIPTION
**Pull request by sunag**
**Description**

It seems to be the most common term.

### CODE REVIEW

**Comment by LeviPesin** [comment]
I think it's better to remain it `invert`... It may be little bit confusing with `reciprocal`, but it is cleaner when used in code.

**Comment by sunag** [comment]
> I think it's better to remain it invert... It may be a little bit confusing with reciprocal, but it is cleaner when used in code.

Hmm... I also like the term invert(). My concern is that the others popular NodesGraph use this term:
- Unity https://docs.unity3d.com/Packages/com.unity.shadergraph@6.9/manual/One-Minus-Node.html
- Unreal https://www.youtube.com/watch?v=bS6WWlAVj9o

**Comment by sunag** [comment]
Maybe @mrdoob has a suggestion?

**Comment by mrdoob** [comment]
I think it's better to follow the terms used in other node editors. So OneMinus 👍

**Comment by LeviPesin** [comment]
Maybe we can have alias `invert` for `oneMinus`?

**Comment by LeviPesin** [comment]
@sunag Why we cannot have `invert` as an alias of `oneMinus`? I still think `invert` is cleaner when used in code.

**Comment by sunag** [comment]
> @sunag Why we cannot have invert as an alias of oneMinus? I still think invert is cleaner when used in code.

I think `alias` should be used in case of backward compatibility. I think avoid `alias` can should make it easier for new users and simplify the documentation. Maybe if `invert( mag = 1 )` had a value for magnitude it would already have a difference? then it wouldn't be the same, like:

```js
const number = float( 90 )
const result = number.invert( 100 ); // result is 10 ( 100 - 90 )

// -> invert( value = 1 ) // default is 1

const number = float( .9 )
const result = number.invert(); // result is 0.1 ( 1.0 - 0.9 )
```

**Comment by LeviPesin** [comment]
It wouldn't be invert then... Maybe then it is better to remain as it is.

**Pull request merged**
