### PR TITLE
PMREMGenerator flips cube textures from WebGLRenderTargetCube

### LINKED ISSUE #15301: PMREMGenerator flips the X axis when receiving a non CubeTexture
##### Description of the problem

When using a texture from WebGLRenderTargetCube (e.g. EquirectangularToCubeGenerator) with PMREMGenerator, the generated environment map does not match the environment, and is flipped on the X axis, unlike when using a CubeTexture.

This can be recreated [in the EXR example](https://threejs.org/examples/?q=exr#webgl_materials_envmaps_exr) and:

```
scene.background = cubemapGenerator.renderTarget;
//cubemapGenerator.dispose();
```

screenshot from 2018-11-21 15-45-11
screenshot from 2018-11-21 15-42-23

##### Three.js version

- [x] Dev
- [ ] r98
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by jsantell**
Fixes #15301.

This is a straight forward solution but when checking different roughness values, it appears that the flipping is reversed in some mipmaps, but not sure where that's occurring in the code.

(the red circle should be on the left, yellow on the right, it's correct at roughness: 0 and several other times it appears)

flipped

As a quick test, flipping the X in the PMREMCubeUVPacker's frag color worked across all roughness values, but this seems that the fix is better off in the PMREMGenerator.

Thoughts?

### CODE REVIEW

**Comment by jsantell** [comment]
@bhouston my understanding is CubeTextures require a flip and WebGLRenderTargetCubes do not -- the PMREMGenerator assumes CubeTextures, so the flip is built in somewhere, and the places I've tried result in inconsistent flipping through the convolution layers (gif in OP) or only handled in the UV packer (which will work most of the time, but it should also have correct flip in the generator)

**Comment by jsantell** [comment]
Found the issue! The flip should only occur on the first LOD pass (which is currently handled, but only for CubeTexture). Changed `queryScale` to `tFlip` to be in line with other instances in three where a tFlip occurs, and now appropriately handle when receiving a texture from a WebGLRenderTargetCube. Updated code

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
