### PR TITLE
RGB Halftone (post-processing)

### PR DESCRIPTION
**Pull request by meatbags**
A colour-halftone post-processing pass for effect composer. Lots of options.

* rotate dot grids independently
* point styles = dot, line, ellipse, square
* blend with input (a few different modes)
* grey-scale option
* randomise dot position (scatter)

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawgit.com/meatbags/three.js/dev/examples/webgl_postprocessing_rgb_halftone.html

**Comment by mrdoob** [comment]
Beautiful!

**Comment by mrdoob** [comment]
Thanks!

**Comment by meatbags** [comment]
Neat, thanks!

**Pull request merged**
