### PR TITLE
WebGPURenderer: Add backend information to `data-engine` field.

### PR DESCRIPTION
**Pull request by jclaessens97**
**Description**

Currently there is no easy way to debug if you're running on webgpu or webgl fallback. There is an `data-engine` attribute, but it's always set to `webgpu`. This should make it easier to debug that.

*This contribution is funded by [Segments.ai](https://segments.ai/)*

### CODE REVIEW

**Comment by Mugen87** [comment]
> There is an data-engine attribute, but it's always set to webgpu.

How about we about the data-engine attribute so it provides more information? In this way, we don't have update `Info`. The following should do the trick:

```
getDomElement() {

    let domElement = this.domElement;

    if ( domElement === null ) {

        domElement = ( this.parameters.canvas !== undefined ) ? this.parameters.canvas : createCanvasElement();

        const backend = ( this.coordinateSystem === WebGPUCoordinateSystem ) ? 'WebGPU backend' : 'WebGL backend';

        // OffscreenCanvas does not have setAttribute, see #22811
        if ( 'setAttribute' in domElement ) domElement.setAttribute( 'data-engine', `three.js r${REVISION} WebGPURenderer, ${backend}` );

        this.domElement = domElement;

    }

    return domElement;

}
```

**Review by Mugen87 — APPROVED** [review]

**Comment by linbingquan** [comment]
图片

I think this display is incorrect.

`Renderer.domElement = backend.getDomElement();` code was runing before `await Renderer.init()`.

Test browser: Firefox 131

**Comment by Mugen87** [comment]
Good catch! I'll revert the PR for now. Let's think about a new solution.

**Comment by Mugen87** [comment]
@jclaessens97 If you are interested in the current used backend, can't you just evaluate `renderer.backend.coordinateSystem`?

**Comment by jclaessens97** [comment]
Probably yes. Thought it would be useful to have directly in three, but now that I know what to look for, I succesfully implemented it that way without a need of having it in threejs!

**Pull request merged**
