### PR TITLE
Restored factor of PI to BRDFs

### PR DESCRIPTION
**Pull request by WestLangley**
1. Previously, we left the factor of PI out of our BRDFs because the factor was cancelled out in the rendering equation. I have restored those factors -- at least for the time being -- until we can be assured the code is correct.
2. We also need to keep careful track of our units, as we are including a wide variety of light types. In particular, we need to properly differentiate between radiance and irradiance in our calculations. Consequently, I renamed a few variables so the units were clear. I tried to make the changes as minimal as possible.
3. `MeshLambertMaterial` had a number of bugs. They are fixed for now. We can further refactor `Lambert` later.
4. I believe we had lightmap implementation wrong. Light maps are in units of irradiance and are additive to total irradiance. To keep the rendered output the same as before, I had to multiply lightmap by PI. With this PR, lightmaps render as they did before, but this is likely not correct. Lightmaps still need to be fixed.

/ping @bhouston
/ping @tschw

### CODE REVIEW

**Comment by bhouston** [comment]
I like this change.

One issue is that in this PR we are removing two sets of descriptive names (indirect/direct diffuse/specular) and replacing it with a unit of measurement (irradiance/radiance.)  I guess you could argue that irradiance/radiance are equivalent to diffuse/specular (in many cases but not always), but they are not a replacement for the indirect/direct distinction.  Thus I would like to see Indirect and Direct re-introduced to the light probe accessor names, thus:

getLightProbeIndirectRadiance?
getLightProbeIndirectIrradiance?

Could we also rename direct light accessors to be more precise as well?  I believe they return radiance.  Thus getDirectLightDirectRadiance,getSpotLightDirectRadiance, getPointLightDirectRadiance?

**Comment by bhouston** [comment]
I haven't checked the math yet.  One issue is likely that we do not compensate for the punctual light optimization when setting the uniforms in WebGLRenderer, thus you have to compensate for the punctual light scaling while setting Light.intensity, which is a little weird.

**Comment by WestLangley** [comment]
Yes, we can change the function names if you like this better:

    getLightProbeIrradiance -> getLightProbeIndirectIrradiance
    getLightProbeRadiance -> getLightProbeIndirectRadiance

> Could we also rename direct light accessors to be more precise as well? I believe they return radiance. Thus getDirectLightDirectRadiance,getSpotLightDirectRadiance, getPointLightDirectRadiance?

Yes, but I'm not sure which methods you would like changed.

> I haven't checked the math yet. One issue is likely that we do not compensate for the punctual light optimization when setting the uniforms in WebGLRenderer, thus you have to compensate for the punctual light scaling while setting Light.intensity, which is a little weird.

I am not sure what you are referring to by the "punctual light optimization". Can you point to specific code that concerns you?

If you are referring to the extra factor of PI, another way of thinking about it is we say, by definition, the irradiance emitted by a punctual light source orthogonal to the surface is PI times its color times its intensity.

**Comment by bhouston** [comment]
I was just thinking we could be consistent and change these function signatures as well:

https://github.com/WestLangley/three.js/blob/dev-pi/src/renderers/shaders/ShaderChunk/lights_pars.glsl#L19

https://github.com/WestLangley/three.js/blob/dev-pi/src/renderers/shaders/ShaderChunk/lights_pars.glsl#L43

https://github.com/WestLangley/three.js/blob/dev-pi/src/renderers/shaders/ShaderChunk/lights_pars.glsl#L73

To include a mention of "radiance" as well for clarity instead of their current use of the imprecise term "Light" -- then these match the same pattern as the others.

This is a great change. :)

**Comment by bhouston** [comment]
Funny thing, given that glsl supports polymorphism via parameter types, we could simplify these:

```
IncidentLight getDirectionalDirectLight( const in DirectionalLight directionalLight, const in GeometricContext geometry );
IncidentLight getPointDirectLight( const in PointLight pointLight, const in GeometricContext geometry );
IncidentLight getSpotDirectLight( const in SpotLight spotLight, const in GeometricContext geometry );
```

To this -- I think it is less verbose and clearer:
```
IncidentLight getDirectRadiance( const in DirectionalLight directionalLight, const in GeometricContext geometry );
IncidentLight getDirectRadiance( const in PointLight pointLight, const in GeometricContext geometry );
IncidentLight getDirectRadiance( const in SpotLight spotLight, const in GeometricContext geometry );
```

Once we get a LightProbe struct type, we can use the same signature type on those functions: "getIndirectRadiance", "getIndirectIrradiance". :)

**Comment by bhouston** [comment]
The above mirrors Apple's Model I/O Light interface of "irradianceAtPoint":

https://developer.apple.com/library/prerelease/tvos/documentation/ModelIO/Reference/MDLLight_Class/index.html#//apple_ref/occ/cl/MDLLight

Off topic, Apple's Model I/O library has a LightProbe struct that supports both irradiance textures as well as spherical harmonics in the same class.  Sort of neat:

https://developer.apple.com/library/prerelease/tvos/documentation/ModelIO/Reference/MDLLightProbe_Class/index.html#//apple_ref/occ/cl/MDLLightProbe

**Comment by WestLangley** [comment]
>I was just thinking we could be consistent and change these function signatures as well:

Thing is, those methods return a struct of an "attenuated color" and direction. I think of color as being unitless. Maybe we need some more refactoring... Can we hold off on that one until I think about it some more?

Maybe this?

    IncidentLight getDirectLight( const in DirectionalLight directionalLight, const in GeometricContext geometry );
    IncidentLight getDirectLight( const in PointLight pointLight, const in GeometricContext geometry );
    IncidentLight getDirectLight( const in SpotLight spotLight, const in GeometricContext geometry

**Comment by bhouston** [comment]
> I think of color as being unitless.

Usually a light source has a "power", measured in Watts,, like a 60W light bulb. :)
Irradiance has a unit of W/m^2, e.g power / area.
Radiance has a unit of W/(m^2*sr), e.g. power / area * steradians

Thus if we have a function returning irradiance or radiance, we should likely assume it in the above units.  Now of course our lights.intensity parameter is not yet considered to be in Watts, and our attenuation function is not energy preserving so right now we lose our units getting to irradiance/radiance, but we do not have to be doing this.

**Comment by WestLangley** [comment]
We are typing at the same time with the same thoughts. : - )

BTW, `reflectedLight` also has units of radiance -- at least in theory. It could be called `reflectedRadiance".

The formula to remember is

    radiance = BRDF * irradiance

We need to keep track of this when we switch to radiometric units for our lights.

**Comment by bhouston** [comment]
Yes. :)

And color is actually just spectral radiance or spectral irradiance in these cases -- radiance/irradiance further separated by wavelength bands.

**Comment by bhouston** [comment]
> Thing is, those methods return a struct of an "attenuated color" and direction. 

The color returned by these queries is still irradiance though I think.

**Comment by WestLangley** [comment]
Do you have a referece for how we can specify our lights in lumens -- or whatever -- and convert the units to an appropriate scale for rendering?

**Comment by bhouston** [comment]
Can I, @WestLangley, write the physically correct lights?

I have tried twice in the past:

https://github.com/mrdoob/three.js/pull/6255
https://github.com/mrdoob/three.js/pull/5787

In the above PRs you can see that I was trying to measure the light in lumens, and to have consistent integrals across the spheres of the light intensity at varying distances.  This is what we are aiming to do now:

https://github.com/mrdoob/three.js/pull/5787#issuecomment-67718617

You argued strongly against this change, you should read the comments of yours, and in the end I could get nothing accepted that was physically-based -- it was just arbitrary functions.

**Comment by WestLangley** [comment]
>You argued strongly against this change, you should read the comments of yours, and in the end I could get nothing accepted that was physically-based -- it was just arbitrary functions.

Sorry, @bhouston. Please let's not rehash old differences. Let's move forward. I support what you want now, and we are making good progress.

**Comment by mrdoob** [comment]
@bhouston Sorry for those PR not getting accepted. I was in the middle of refactoring the WebGLRenderer and I was not able to give them enough attention. Now that things are more stable (and we're doing A TON of progress) we can give it another go 😊

**Comment by mrdoob** [comment]
Merging this one!

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
