### PR TITLE
Blender exporter: Added MultiMaterial support

### PR DESCRIPTION
**Pull request by s9k**
Fixed PR: #8077

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, do you mind pasting here the output of a cube with multi material?

**Comment by s9k** [comment]
Of course, no problem

```json
{
    "metadata":{
        "sourceFile":"only_cube.blend",
        "generator":"io_three",
        "type":"Object",
        "version":4.4
    },
    "animations":[{
        "tracks":[],
        "fps":24,
        "name":"default"
    }],
    "materials":[{
        "materials":[{
            "name":"Red",
            "uuid":"D835F384-C44A-3532-99AA-E639AC03D4DB",
            "type":"MeshPhongMaterial",
            "color":13369344,
            "emissive":0,
            "vertexColors":0,
            "blending":"NormalBlending",
            "depthTest":true,
            "depthWrite":true,
            "specular":8355711,
            "shininess":50
        },{
            "name":"Blue",
            "uuid":"D78C0BE8-A39B-39FF-A056-62B254C2AA15",
            "type":"MeshPhongMaterial",
            "color":204,
            "emissive":0,
            "vertexColors":0,
            "blending":"NormalBlending",
            "depthTest":true,
            "depthWrite":true,
            "specular":8355711,
            "shininess":50
        },{
            "name":"Green",
            "uuid":"66E50ADB-BD20-33C1-AF6D-0E7569ED9B31",
            "type":"MeshPhongMaterial",
            "color":52224,
            "emissive":0,
            "vertexColors":0,
            "blending":"NormalBlending",
            "depthTest":true,
            "depthWrite":true,
            "specular":8355711,
            "shininess":50
        }],
        "type":"MultiMaterial",
        "name":"Red,Blue,Green",
        "uuid":"B3F27320-5607-4342-B1C2-B99A1589E3C0"
    }],
    "textures":[],
    "images":[],
    "object":{
        "children":[{
            "name":"Cube",
            "uuid":"F29D1AC4-D789-3D8E-BAB5-59DC1B758FE2",
            "matrix":[-1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1],
            "visible":true,
            "type":"Mesh",
            "material":"B3F27320-5607-4342-B1C2-B99A1589E3C0",
            "castShadow":true,
            "receiveShadow":true,
            "geometry":"FE46F7EB-A263-3807-8987-EB40ABE18EAA"
        }],
        "matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
        "type":"Scene",
        "uuid":"020FBCE6-FD1C-4588-9BD8-6029F1860325"
    },
    "geometries":[{
        "metadata":{
            "position":20,
            "normal":20,
            "uv":20,
            "uv2":20,
            "generator":"io_three",
            "version":3
        },
        "data":{
            "index":{
                "itemSize":1,
                "type":"Uint16Array",
                "array":[0,1,2,3,4,5,6,0,2,7,3,5,8,9,10,11,12,13,14,8,10,15,11,13,16,1,5,0,17,18,19,16,5,7,0,18]
            },
            "groups":[{
                "start":0,
                "materialIndex":0,
                "count":12
            },{
                "start":12,
                "materialIndex":1,
                "count":12
            },{
                "start":24,
                "materialIndex":2,
                "count":12
            }],
            "attributes":{
                "position":{
                    "itemSize":3,
                    "type":"Float32Array",
                    "array":[1,1,1,1,1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,1,1,-1,1,-1,1,1,-1,1,-1,-1,-1,-1,1,-1,1,1,-1,-1,1,1,-1,-1,-1,1,1,1,1,-1,1,-1,-1,1,1,-1,-1,1,-1,-1,-1]
                },
                "normal":{
                    "itemSize":3,
                    "type":"Float32Array",
                    "array":[0.577349,0.577349,0.577349,0.577349,0.577349,-0.577349,-0.577349,0.577349,-0.577349,-0.577349,-0.577349,0.577349,-0.577349,-0.577349,-0.577349,0.577349,-0.577349,-0.577349,-0.577349,0.577349,0.577349,0.577349,-0.577349,0.577349,-0.577349,0.577349,0.577349,-0.577349,0.577349,-0.577349,-0.577349,-0.577349,-0.577349,0.577349,-0.577349,0.577349,0.577349,-0.577349,-0.577349,0.577349,0.577349,-0.577349,-0.577349,-0.577349,0.577349,0.577349,0.577349,0.577349,-0.577349,0.577349,-0.577349,-0.577349,0.577349,0.577349,-0.577349,-0.577349,0.577349,-0.577349,-0.577349,-0.577349]
                },
                "uv2":{
                    "itemSize":2,
                    "type":"Float32Array",
                    "array":[0.8,0.2,0.8,0.8,0.2,0.8,0.8,0.2,0.8,0.8,0.2,0.8,0.2,0.2,0.2,0.2,0.8,0.2,0.8,0.8,0.2,0.8,0.8,0.2,0.8,0.8,0.2,0.8,0.2,0.2,0.2,0.2,0.8,0.2,0.8,0.8,0.2,0.8,0.2,0.2]
                },
                "uv":{
                    "itemSize":2,
                    "type":"Float32Array",
                    "array":[1,0,1,1,0,1,1,0,1,1,0,1,0,0,0,0,1,0,1,1,0,1,1,0,1,1,0,1,0,0,0,0,1,0,1,1,0,1,0,0]
                }
            }
        },
        "type":"BufferGeometry",
        "name":"CubeGeometry",
        "uuid":"FE46F7EB-A263-3807-8987-EB40ABE18EAA"
    }]
}
```

**Comment by mlknz** [comment]
I tested this with few different models and got expected result.
Could it be merged, please?

**Comment by mrdoob** [comment]
Seems like this PR got lost and is unmergeable again. Sorry about that 😞

**Comment by mrdoob** [comment]
@s9k Any chance you can re-implement?

**Comment by poofik** [comment]
Yes please commit this to the main branch. The fix seems to work.

**Comment by SonicSerpentine** [comment]
+1 
VERY interested in this, so I tried merging myself.
There was just one conflict in geometry.py, so I kept both changes.
It filled out the multi material fine, but didn't fill out the corresponding geometry index range groups.

**Comment by haywirez** [comment]
Any update on this?

**Comment by kervel** [comment]
the s9k version still works perfectly (pull request won't merge, but i just checked out the s9k:exporter-multimat-fix2 branch directly and installed the exporter from there)

**Comment by haywirez** [comment]
How can we move this forward?

**Comment by chenye0712** [comment]
Hi everyone. Thanks for fixing the exporter!! I am using the sk9 version, and the exported json file is including multiple materials for one object perfectly. But my question is, in the code what do I need to modify to get the mesh colored correctly by these multiple materials it owns.

My current code looks like:
	var loader = new THREE.ObjectLoader();
	loader.load('./Beach.json', function(loadedObj, materials) {
	    var beach = loadedObj.getObjectByName("Beach");
	    var sea = loadedObj.getObjectByName("Sea");
            ...
        }

Thank you in advance!!

**Comment by SonicSerpentine** [comment]
Hi chenye0712. That's the problem right now. The multi-material is written just fine, but the exporter fails to write the geometry indices that dictate which faces get what sub material.

**Comment by chenye-totoro** [comment]
@SonicSerpentine  Hi. I copied the json from sk9 in this thread, and it can render a multi-material cube fine, so I thought if I use his fixed version, it should work in threejs? I probably misunderstood it ...l'll try ColladaLoader. Thanks!

**Comment by chenye-totoro** [comment]
Hi everyone and @SonicSerpentine ! I am using sk9 io_three, and it's write the geometry with sub material indices well! The problem is all sub material has color of pale gray, as showed in the following "color:: 10724259. Is it because I am using cycle render? Or is there any setting in Blender I need to check? 
    {
            "name":"grass",
            "uuid":"A64C33A0-FC05-3493-AF3E-90A8AD3CE5A6",
            "type":"MeshPhongMaterial",
            "color":10724259,
            "emissive":0,
            "vertexColors":0,
            "blending":"NormalBlending",
            "depthTest":true,
            "depthWrite":true,
            "specular":8355711,
            "shininess":50
    }

sorry to bother you again, I just feel like I am so close...

**Comment by mrdoob** [comment]
I've finally been able to refactor multi-materials so the json format is now easier ✨

This is how it looks like: https://github.com/mrdoob/three.js/issues/10931#issuecomment-290734264

Anyone up for implementing it in the Blender exporter?

**Comment by Mugen87** [comment]
This was implemented in #11836

**Pull request closed without merging**
