### PR TITLE
Shaders: restore support for standard cube maps in physical shader

### PR DESCRIPTION
**Pull request by WestLangley**
Reverts #22234.

Work-around for #22236.

This PR requires `maxMIPLevel` to be restored, too, I think. See #13501.

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral test link using `MeshStandardMaterial`:

https://raw.githack.com/westlangley/three.js/dev_physical_env_cube/examples/webgl_materials_cubemap_dynamic.html

**Comment by WestLangley** [comment]
@Mugen87 I am not sure if this is needed. Just sharing in case it is helpful...

**Comment by ligaofeng0901** [comment]
I agree that we should restore cube env map in physical shader, as least before we find a better soultion.  It doesn't confilct with cube uv map. As a user, I can get a better effect with cubeuvmap from `PMREMGenerator `, or a better performance with relatime cube map from `WebGLCubeRenderTarget`.

**Comment by WestLangley** [comment]
@ligaofeng0901 This PR would only be merged as a last resort. I am hopeful that will not be necessary.

**Comment by WestLangley** [comment]
It appears this was not required. Closing...

**Pull request closed without merging**
