### PR TITLE
JSM: Use "module" instead of "min" prefix for libs.

### PR DESCRIPTION
**Pull request by Mugen87**
To better indicate that these libs are actually modules.

### CODE REVIEW

**Comment by mrdoob** [comment]
I guess they can also be `name.module.min.js`?

**Comment by Mugen87** [comment]
I think so 😅

**Comment by Mugen87** [comment]
How about this:
```
chevrotain.module.min.js
dat.gui.module.js
gunzip.module.min.js
inflate.module.min.js
mmdparser.module.js
stats.module.js
```

**Comment by mrdoob** [comment]
That works 👌

**Pull request merged**
