### PR TITLE
removed the extra double for loop

### PR DESCRIPTION
**Pull request by virajdoshi11**
**Description :**
There is a nested for loop in TorusBufferGeometry.js which is I think unnecessary, so, I removed that nested for loop and added that code in the previous nested for loop

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like your editor reformatted the file.

**Comment by virajdoshi11** [comment]
There are probably more files that need this change should I do all of those?

**Comment by Mugen87** [comment]
TBH, I think it's better for readability if indices are generated separately. Especially since not loops for generating index and vertex data are not always equal.

**Comment by virajdoshi11** [comment]
Agree with you but if the scene has too much of vertices or objects or user has imported a big file than it might take some time to load up the torus or any other object

**Comment by Mugen87** [comment]
Can you share a benchmark that shows the performance difference between both approaches?

**Comment by virajdoshi11** [comment]
if we go with same approach as previous it is obvious that it would take more time to generate a torus (or any object) but adding that code in 1 nested loop would save some time and work for the computer don't you think so?

**Comment by Mugen87** [comment]
Yes, but if the difference is negligible I would prefer to keep the current code.

**Comment by Mugen87** [comment]
BTW: Why have you created a new PR? #20610

**Comment by virajdoshi11** [comment]
"Yes, but if the difference is negligible I would prefer to keep the current code."
Though it won't make much difference but I think a little optimization is good
Sorry for making a new PR actually I am new to github

**Comment by virajdoshi11** [comment]
And i don't know why there is a linting error, what more formatting needs to be done?

**Comment by Mugen87** [comment]
You are using soft instead of hard tabs.

**Comment by Mugen87** [comment]
The linting errors are actually visible in the `Files changed` tab: https://github.com/mrdoob/three.js/pull/20609/files

**Comment by mrdoob** [comment]
I agree with @Mugen87. This seems like a micro optimization that makes the code less readable.

Closing. Sorry about that.

**Pull request closed without merging**
