### PR TITLE
Remove optionalTarget - part 6

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in #12231.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 @mrdoob @zz85 

Ugh... I have run into a road-block with all the curve classes (and parametric geometries, apparently).

The curve classes are 2D/3D-agnostic. So one is unable to modify the codebase to pre-allocate the `Vector2/3` targets, because there is no way to know in what dimension the user operating.

So, as it stands, part of the library/examples still support `optionalTarget`, and it is due to the `getPoint()` method -- and related methods.

**Comment by Mugen87** [comment]
When i remember correctly, the only problematic part is `Curve.getTangent()`.

https://github.com/mrdoob/three.js/blob/e5012e237dd1f05182dc1879347e7cb05bbebf48/src/extras/core/Curve.js#L240-L257

I guess one solution is to overwrite `Curve.getTangent()` in all derived classes and remove the default implementation in `Curve` (analogous to `.getPoint()`). The classes in `extras/curves` are assigned either to 2D or 3D space. So no ambiguity in this code.

@WestLangley What other spots have you detected?

**Comment by Mugen87** [comment]
Yeah, I remember this when I've added serialization/deserialization.

One approach that might solve the problem is to delegate the creation of `Vector2/3`  to the curve classes. `Curve.getPoints()` could look like this:
```js
getPoints: function ( divisions ) {

	if ( divisions === undefined ) divisions = 5;

	var points = [];

	for ( var d = 0; d <= divisions; d ++ ) {

                var point = this.createVector();

                this.getPoint( d / divisions, point )

		points.push( point );

	}

	return points;

}
```
But i'm not sure how nice this is.

**Comment by WestLangley** [comment]
Maybe we should have 2D- and 3D-specific classes, instead.

**Comment by Mugen87** [comment]
Do you mean something like `Curve2D` and `Curve3D`?

**Comment by WestLangley** [comment]
Yes. Just a thought...

    Curve -> LineCurve
    Curve3 -> LineCurve3

**Comment by WestLangley** [comment]
Oh, wait... I meant

    Curve and CurvePath (2D-only)

    Curve3 and CurvePath3 (3D-only)

**Pull request merged**
