### PR TITLE
Add RGBFormat to Three.Legacy.js.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

Testing the approach suggested in https://github.com/mrdoob/three.js/pull/23228#issuecomment-1023402590.

### CODE REVIEW

**Comment by Mugen87** [comment]
Unfortunately, this automatically logs the warning when the library file is loaded.

**Comment by mrdoob** [comment]
Yeah, I didn't say so in #23228 because I was hoping @Makio64 would figure it out on his own 😛

**Comment by mrdoob** [comment]
[Spoiler] The solution is to use a getter... somehow.

**Comment by Mugen87** [comment]
Um, I'm not aware how this should be possible with a getter. Can't we just export a simple function?
```js
export function RGBAFormat() {

	console.warn( 'THREE.RGBFormat has been removed. Please ues THREE.RGBAFormat instead. https://github.com/mrdoob/three.js/pull/23228' );
	return 1022;

}
```

**Comment by Mugen87** [comment]
Um, I'm not aware how this is possible with a getter. Related: https://stackoverflow.com/questions/44757177/how-to-export-getter-in-es6-module-system

**Comment by mrdoob** [comment]
Yeah...

Hmm... We could keep the constant and turn `texture.format` into a getter/setter, and warn the user when it tries to use RGBFormat (and replace it with RGBAFormat).

**Comment by Mugen87** [comment]
Would you be play with this approach? https://github.com/Mugen87/three.js/commit/eb92dbe0045c9d3dd4d0b7ff134029c3bc885cd0

**Comment by mrdoob** [comment]
That's even better 👍

**Pull request closed without merging**
