### PR TITLE
-- size, ++ speed

### PR DESCRIPTION
**Pull request by tschw**
This PR adds a custom build step that replaces THREE & WebGL symbolic constants with numerals. It also contains some minor cleanup based on diagnostics from the JS build.

The build step is implemented both in Python and in JavaScript for both build variants. It has a debug mode that logs the replacements.

### CODE REVIEW

**Comment by tschw** [comment]
Related: #8822

**Comment by gero3** [comment]
The package.json in build should be deprecated and replaced with the one in the root. It is no longer useful to have it in there.

**Comment by tschw** [comment]
@gero3 
> The package.json in build should be deprecated and replaced with the one in the root. It is no longer useful to have it in there.

Ah! What is a smooth way to deprecate it?

BTW is `build.min` a good name for the minifying build? Is there some established standard we can follow, maybe?

**Comment by tschw** [comment]
@gero3 
Does the root `package.json` run on Windows? Seeing `cd ./utils/build && node ...` I guess it might assume a UNIX-style shell (I'm not sure what Windows can handle these days, though)?

If so, can we just invoke the build from the root directory, maybe?

**Comment by gero3** [comment]
I like the idea of the constifier but not the implementation right now. Mostly because it requires us to keep track of constants in 2 places now.

> @gero3
> 
> The package.json in build should be deprecated and replaced with the one in the root. It is no longer useful to have it in there.
> Ah! What is a smooth way to deprecate it?

Just delete the file. It is just a relic now. Nobody should be using it anyway. It isn't kept up to date anyways.

> 
> Is build.min a good name for the minifying build? Is there some established standard we can follow, maybe?

I actually would add the following actually. That way it is similar to the python version.

```
script: {
  build: "npm run build.debug && npm run build.release",
  build.debug: "cd ./utils/build && node build.js --include common --include extras --output ../../build/three.js",
  build.release: "cd ./utils/build && node build.js --include common --include extras --minify --output ../../build/three.min.js"
}
```

**Comment by gero3** [comment]
> @gero3 
> Does the root package.json run on Windows? Seeing cd ./utils/build && node ... I guess it might assume a UNIX-style shell (although I'm not sure what Windows can handle these days).
> 
> If so, can we just invoke the build from the root directory, maybe?

Yes, it also runs on WIndows. The build script is made to run specifically from the directory, similar to then python script.

**Comment by gero3** [comment]
@tschw
I don't get why you changed MaterialIdCount to materialIdCount.

**Comment by tschw** [comment]
> I don't get why you changed MaterialIdCount to materialIdCount.

> I like the idea of the constifier but not the implementation right now. Mostly because it requires us to keep track of constants in 2 places now.

Because you haven't.

See `utils/build/constifier/dumper.html` extracts all uppercase names on `THREE` and a GL context that have the type `number`. It then outputs the JSON file. To update simply copy&paste.

**Comment by tschw** [comment]
@gero3 
> I don't get why you changed MaterialIdCount to materialIdCount.

Also, these names are global variables, not constants. So they should follow the conventions for variables not constants.

We could put some deprecation code into `Three.Legacy.js` or, alternatively, if we really want them to be inconsistently uppercased, initialize them to `null` or blacklist them.

@tschw wrote:
> See `utils/build/constifier/dumper.html` ...

I guess it might be possible to automate it even further, using this tool only only for hard-wiring the WebGL constants and extract the `THREE` constants in via node.js. Is it possible to load `THREE` in this context? I guess you may have some experience?

**Comment by gero3** [comment]
> @tschw wrote:
> 
> See utils/build/constifier/dumper.html ...
> I guess it might be possible to automate it even further, using this tool only only for hard-wiring the WebGL constants, extracting the THREE constants via node.js. Is it possible to load THREE in this context? I guess you may have some experience?

Using Eval the concatenated source code could get you the the THREE object which can be used in the findConstants object.

**Comment by tschw** [comment]
@gero3 
> Using Eval the concatenated source code could get you the the THREE object which can be used in the findConstants object.

Would it be a (better) option to just `require` the temp file? Does Three.js set `module.exports` when `module` is provided, that is?

**Comment by gero3** [comment]
It does. But you can't require a string without writing it to the disk somewhere.

**Comment by tschw** [comment]
@gero3 
> It does. 

Ah cool!

> But you can't require a string without writing it to the disk somewhere.

Right - it's only in memory with the JS build... Isn't `eval` deprecated? Also, extracting the constants every time would slow down the build quite a bit, which might be acceptable since we're talking release builds only. I don't think writing a temp file would dominate.

Maybe constant extraction should just be a separate invocation that performs a debug build as a prerequisite?

@mrdoob 
What are your thoughts on the `*IdCount` considerations [above](https://github.com/mrdoob/three.js/pull/8824#issuecomment-217428544)?

Yet another option (that would allow them to remain uppercased) would be to move them onto the classes, e.g. `Material.InstanceId`. As a matter of personal taste, I'd like it better if this kind of naming would indicate something that does not change, however, I think it should be your call.

**Comment by gero3** [comment]
uglify is very slow compared to the extraction process normally. It shouldn't take a second to get all of the constants.

**Comment by bhouston** [comment]
Why don't we just adopt JavaScript symbols which are designed for this?

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol

Constantly like this do not really impact ThreeJS's size at all because they get reduced by gzip.  This seems like a special case hard to maintain gzip step that isn't necessary.  I would like to see the differences in resulting gzip size before and after this PR.  Is it significantly?

I do not understand the point of this PR.

Also this PR changes the static variable naming convention from first uppercase letter to lowercase for a number of constants.  I am okay with changing convention but as its own PR.

**Comment by bhouston** [comment]
@gero3 wrote:
> The package.json in build should be deprecated and replaced with the one in the root. It is no longer useful to have it in there.

I completely agree. :)

**Comment by bhouston** [comment]
> Ah! What is a smooth way to deprecate it?

Just kill it, it doesn't work well and I doubt many are using it.

**Comment by tschw** [comment]
@bhouston 
> Symbols...

...won't make the properties constant. Only the data. Also, they are unsupported by most browsers.

> Constantly like this do not really impact ThreeJS's size at all because they get reduced by gzip. This seems like a special case hard to maintain gzip step that isn't necessary. 

There is no gzip step.

> I would like to see the differences in resulting gzip size before and after this PR. Is it significantly better?

Just see above. It's 2KB gzipped and that equates to a lot of code...
I also see a ~ 10% JS speedup with Firefox.

**Comment by bhouston** [comment]
> There is no gzip step.

Most webservers serve *.js files (and other text files) as gzipped (or soon brotli) automatically, at least in professional contexts.  https://en.wikipedia.org/wiki/HTTP_compression  Many webservers, like nginx, and do this transparently and cache the gzipped intermediates automatically: http://nginx.org/en/docs/http/ngx_http_gzip_module.html

**Comment by tschw** [comment]
@bhouston 
I know. And I measured 2KB difference piping the resulting `three.min.js` file through gzip.

**Comment by tschw** [comment]
@bhouston 
> I've done my own experiments before with changing THREE to T and Vector3 to V3 and it made almost no difference in the resulting gzip file because well compression.

Those occur much more frequently, therefore compress to almost nothing anyway.

**Comment by bhouston** [comment]
2K, that is sort of what I saw as well, that is 2% saving, which isn't much.  This to me isn't a major issue.

I am not sure that is sufficient to obfuscate the source files like this and duplicate the constants in two places which increases the maintenance complexity of Three.js.  I really do not like violating DRY just to save 2K: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself for just a 2K saving.

There are higher priority issues with ThreeJs in my opinion.

**Comment by bhouston** [comment]
I slightly oppose this for now because of the DRY violation.  But if that was addressed, I wouldn't have much of an opinion on this PR either way, the savings are minimal, but the build step can easily be turned off is needed, so it sort of nets out to even.

**Comment by tschw** [comment]
> I slightly oppose this for now because of the DRY violation.

Please read the full thread before opposing because there is none. Constant extraction was automated right from the start and I'm currently automating it further. It will be completely transparent.

**Comment by tschw** [comment]
@bhouston 
Also using symbolic constants like we do inhibits optimizations, causes `switch`..`case` to deoptimize on Chrome, and makes the renderer slower (this is particularly true for the standardized WebGL constants which are eliminated). It also complicates the architecture because you have to pass `gl` around, just to access constants on it - so we may even want to generate a debug mode file with those constants to decouple access to them from the live context.

**Comment by tschw** [comment]
@bhouston 
> 2K, that is sort of what I saw as well, that is 2% saving, which isn't much. 

2K gzipped actually equates to *a lot* of code!

**Comment by abelnation** [comment]
RE the `cd utils/build` step before running the build script, I agree that it would be more ideal if the build script could be run from any path.  The script can detect it's own path via `__dirname` and then resolve all other paths relative to that.  

see: https://github.com/abelnation/three.js/blob/improve-npm-build/utils/build/build.js#L8

**Comment by bhouston** [comment]
If other tools use the constified version and try to use THREE.XXXXXX what happens?  Do they have to run this script on all of their code too?  Do the examples work with this new version without changes?

**Comment by tschw** [comment]
@bhouston 
> If other tools use the constified version and try to use THREE.XXXXXX what happens? Do they have to run this script on all of their code too? Do the examples work with this new version without changes?

`THREE.XXXX` all exist. So external code will of course keep working. You *can* use it, if you like to.

It's also safe to use code like
```javascript
THREE.XXXX = 111;
```
and the token will **not** be replaced in this case.

**Comment by tschw** [comment]
> Do the examples work with this new version without changes?

I wouldn't even dare to make this a PR if they didn't :)

**Comment by bhouston** [comment]
Okay, this alleviates most of my concerns.  I'd have the automatic extraction run on each build -- so that the mapping file isn't checked into git, it is just a temprorary -- that was what set of my DRY concerns.

**Comment by tschw** [comment]
@bhouston 
> Okay, this alleviates most of my concerns. 

:)

> I'd have the automatic extraction run on each build

Yes, in this version, the generator is still an `.html` file that extracts both `THREE` and `gl` constants.

I'm currently separating these cases: The previous approach is used for WebGL (so we don't need a GL context within node.js for building the lib - which would be problematic, e.g. when builds are performed on a headless server). Those are standardized and don't change.

The `THREE` constants OTOH are determined during the build process, so you can happily edit without worries.

> so that the mapping file isn't checked into git, it is just a temprorary

I'd still have to have a version of that file checked in, unless we want to agree to depend on node.js for the python-based build: It may be invoked without node being installed. In this case I'd issue a warning message.

**Comment by bhouston** [comment]
I'd diverge, python doesn't support the advanced features that the node.js build supports. This being one of them.  Python build should  be deprecated, it is just a historical artifact because ThreeJS existed before the right of node.

**Comment by tschw** [comment]
@bhouston 
> I'd diverge, python doesn't support the advanced features that the node.js build supports. This being one of them. Python build should be deprecated, it is just a historical artifact because ThreeJS existed before the rise of node.

Therefore we'd have to get closure compiler up and running with node, first. Then we can smoothly deprecate the python build and just have it call node when it's available. For now it warns when node is not there because it has to use a pre-built file it can't update.

**Comment by bhouston** [comment]
> Therefore we'd have to get closure compiler up and running with node, first

Already done in my PR. :)

**Comment by tschw** [comment]
@abelnation 
> RE the cd utils/build step before running the build script, I agree that it would be more ideal if the build script could be run from any path. The script can detect it's own path via __dirname and then resolve all other paths relative to that. 

Given that the script takes paths as main arguments, I'd find that rather weird. Wouldn't it be better to interpret and specify these paths relative to where the script is actually invoked? 

It can still resolve specific options, such as `--includes` and `--externs`, as relative to the corresponding directories next to the script. This way, it's both easy to use and flexible, since an absolute path can be used to break out of the default directories.

**Comment by tschw** [comment]
@gero3 
> uglify is very slow compared to the extraction process normally. It shouldn't take a second to get all of the constants.

Yes, you were right. It's rather insignificant. I just wrote the concatenated file to disk and `require`'d it. It's currently reused by the Python build.

> I like the idea of the constifier but not the implementation right now.

Like it better now?

**Comment by abelnation** [comment]
@tschw yes, totally agree.  any paths you pass in as arguments would be relative to your current working directory.  `build.js`, however, refers internally to various paths, which can easily be resolved relative to the script directory (not current working directory), regardless of where the script was executed from.  

see: #8831

**Comment by bhouston** [comment]
You know, one thing that may be more scalable and long term that this solution is to start to use the advanced compilation features of the Google Closure compiler -- you can mark things as const or enum in it, you can do amazing optimizations:

https://developers.google.com/closure/compiler/docs/js-for-compiler#overview

I think that if we adopted these advanced features, we could crazily reduce the size of the ThreeJS package.  And if we made it easy to include other bits of code in the optimizatino process, we could help others optimize their code in tandem with ThreeJS.

https://developers.google.com/closure/compiler/docs/api-tutorial3

My concerns are we are special casing one optimization when we could really be doing full global optimization with dead code elimination in a robust fashion -- Google is putting a lot of money into the Closure Compiler, soemthing we can not hope to match, we might as well leverage it.  Basically if it is a boat, I want to get on it, rather than trying to build a little raft.

**Comment by tschw** [comment]
@bhouston 
> I think that if we adopted these advanced features, we could crazily reduce the size of the ThreeJS package.

True.

I use closure compiler exclusively in that mode and brought up the issue often enough around here to know that there is no interest in it, however.

It requires extra work, such as annotations here and there, and @mrdoob doesn't like them. I can understand that, because it would be a very different development style. Closure compiler in advanced mode essentially turns JavaScript into a strictly typed language. 

We'd also have to use google's modularization system (`goog.require` / `provide`) in order to get proper dead code elimination. Without strict dependency scanning, we will still see everything with static initialization (and we use that a lot in Three.js) showing up in the build.

Replacing constants is the probably most important optimization in terms of speed. Also, there are lots of factorizations that can be done like I proposed in #8793. 

It would be a lot of work to support closure advanced mode and I won't invest several days, unless I can be certain that it's even wanted.

**Comment by bhouston** [comment]
Okay, if full closure is ruled out then this is the next best solution. :)  I enjoy the discussions @tschw as I learn a lot from you.

**Comment by tschw** [comment]
@bhouston 
> I enjoy the discussions @tschw as I learn a lot from you.

Me too, me too! You never hold back when it comes to sharing information, experience, thoughts, code and ideas either. And your contribution to this project is tremendously valuable.

**Comment by mrdoob** [comment]
Would it be possible to split this PR in two? I would like to tackle the `Object.assign()` changes first and the constants later on.

**Comment by tschw** [comment]
> Would it be possible to split this PR in two? I would like to tackle the Object.assign() changes first and the constants later on.

Sure.

Thought at first this one broke, but then I looked at the build and everything was looking fine. Turns out I was in fact just testing `canvas / cube` believing it was `webgl / cube` :).

**Comment by mrdoob** [comment]
> Thought at first this one broke, but then I looked at the build and everything was looking fine. Turns out I was in fact just testing `canvas / cube` believing it was `webgl / cube` :).

Haha!

**Comment by tschw** [comment]
@mrdoob 
The threads grow long real quickly and I guess you can't always read it all. However, I figure (from upvoting above question) that you may not like that `*IdCount` renamer in this PR. If so, please help me pick one of the many alternatives there are. These two posts list the ones I could think of:

https://github.com/mrdoob/three.js/pull/8824#issuecomment-217428544
https://github.com/mrdoob/three.js/pull/8824#issuecomment-217443617

**Comment by mrdoob** [comment]
> The threads grow long real quickly and I guess you can't always read it all. However, I figure (from upvoting above question) that you may not like that *IdCount renamer in this PR. 

Actually, I was thinking we could make these counters internal. Like...

```javascript
THREE.Texture = ( function () {
    var id = 0;
    return function () {
        Object.defineProperty( this, 'id', { value: id ++ } );
    };
} )();
```

This should work fine with `Object3D`, `Material` and `Texture`. However, `BufferGeometry` currently uses the same counter `Geometry` uses and that'll create issues inside `WebGLRenderer`...

Also, I wonder if people relies on `THREE.*IdCount` for something...

**Comment by tschw** [comment]
@mrdoob 
> However, BufferGeometry currently uses the same counter Geometry uses

How about `Geometry.id` (static), in that case? Or applying this pattern consistently?

> Also, I wonder if people relies on THREE.*IdCount for something...

The latter would keep it exposed and allow deprecation of the old name via Three.Legacy, but maybe it's exotic enough to just solve it by documenting it for the next release on the Migration page?

**Comment by tschw** [comment]
/ping @mrdoob 
What about this one?

**Comment by mrdoob** [comment]
I like the idea, but the `*IdCount` issue has become a bit of a blocker 😕

Rather than having to notify the user that these variables have changed name, I think I would like to remove them (using the approach in https://github.com/mrdoob/three.js/pull/8824#issuecomment-218314649) and solve the `BufferGeometry`/`Geometry`/`DirectGeometry` collision.

Then the PR/Feature should be ready to go.

**Comment by danrossi** [comment]
Hi I believe this is the best threat to be commenting on. How is this coming along to reduce the filesize ? Is there a way to remove all the shaders not in use at all ?

**Comment by donmccurdy** [comment]
@danrossi More recently three.js has moved to ES6 modules and Rollup for its build (#9310). This means that for the particular case of pruning parts of three.js that aren't needed for your particular project, you can use tree-shaking in build systems like Rollup or Webpack. Here is an example of how to set that up: https://stackoverflow.com/questions/41538767/how-do-i-tree-shake-three-js-using-webpack-or-rollup

As far as efforts to reduce the "default" size of threejs, I don't current status of this PR.

**Comment by danrossi** [comment]
Ok not a problem I might have to make another ticket. for my purpose the bundle has to stay global and so not packaged in. Yes I use such imports but it's global. 

I have a special build of three which only exports the required files. I can reduce it down to 350kb or there abouts. 

However  there is alot of things that are still included unnecessarily like all the shaders and their respective uniforms configs. 

The shaders need to be modular somehow. I don't need any of them apart for MeshBasicMaterial and create my own with a RawShaderMaterial.

Not sure where to ask about that.

**Comment by danrossi** [comment]
I figured out a hack here to prevent including all the shader code. In the rollup build its trying to transform them I just provide an empty string. 

```

function glsl() {

	return {

		transform( code, id ) {

			if ( /\.glsl$/.test( id ) === false ) return;

			if (!/meshbasic/.test(id)) {
				return {
					code: 'export default " "',
					map: { mappings: '' }
				};
			}

			var transformedCode = 'export default ' + JSON.stringify(
					code
						.replace( /[ \t]*\/\/.*\n/g, '' )
						.replace( /[ \t]*\/\*[\s\S]*?\*\//g, '' )
						.replace( /\n{2,}/g, '\n' )
				) + ';';

			return {
				code: transformedCode,
				map: { mappings: '' }
			};

		}

	};

}```

**Comment by danrossi** [comment]
This code has proven to be a problem for an external project I am working on. I think this importing causes more problems than good. It is expecting three installed via npm. I might have to convert them all back to global prefixes. I can't just tell that code to treat three as global. Even though I am bundling that three code beforehand. 



I am trying to include the module of that project into a custom three bundle and its trying to include duplicated files and increase the filesize. I think it has even included minified sources from somewhere. 

Without that project included and with the shaders now removed I have managed to trim it down to 260kb ! 

```
import {
    //MeshBasicMaterial,
    RawShaderMaterial,
    BoxBufferGeometry,
    Mesh,
    Group,
    LinearMipMapLinearFilter,
    LinearFilter,
    DoubleSide
} from 'three';
```

**Comment by danrossi** [comment]
I am using import constants for a custom shader with morph target requires. So I have to include these back into the bundle. All other shaders can go for my needs. It still setups up a heap of helper properties in the ShaderLib. So extra code not needed. 

```
if (!/morphtarget|begin_vertex|project_vertex/.test(id)) {
				return {
					code: 'export default " "',
					map: { mappings: '' }
				};
			}
```

**Comment by danrossi** [comment]
Please refer to this discourse in regards to one way tree shaking problems. 

The import system is only designed to bundle three.js into an app. You can use the elegant import setup  in a 3rd party module build and set three as global in the rollup config. 

But when trying to bundle that module back into a custom three bundle you can't. The import code is tree shaking duplicated three module code for no reason and increases the size about 3 times. I think it even includes minified code. 

For bundled my custom modules I have to hard code locations of the sources. I am using three github sources not npm. And don't even want it to look for npm three. 

Sorry I don't know where else to report this. 


https://discourse.threejs.org/t/tree-shaking-three-js/1349/17?u=danrossi

**Comment by mrdoob** [comment]
> 2K, that is sort of what I saw as well, that is 2% saving, which isn't much. This to me isn't a major issue.

👍

**Pull request closed without merging**
