### PR TITLE
Clock

### LINKED ISSUE #8112: Clock (start, getDelta) broken in Node.js r74, 'performance.now' not defined
The functionality of `THREE.Clock` broke in release r74 when attempting to run in Node.js (installed via npm package 'three'). Functions like `.start()` & `.getDelta()` complain about `ReferenceError: performance is not defined` (as in `performance.now()`).

I might be missing something, but it would seem the changes in 71ddb80818c504028a0cd1dd4c61de0edaa237a8 removed the polyfill for `performance.now` necessary to run THREE (Clock) in Node; as far as I can tell, Node.js doesn't have a global `performance` implemented.
I am not sure if/how much issues #7787, or #7800 are involved. 

Running w/ r74 (current broken state):
```
$ node
> var THREE = require('three');
undefined
> var myclock = new THREE.Clock();
undefined
> myclock.start()
ReferenceError: performance is not defined
    at THREE.Clock.start (/data/users/rlinsalata/workspaces/js_ws/node_playground/node_modules/three/three.js:7911:20)
    at repl:1:10
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)

> myclock.getDelta()
ReferenceError: performance is not defined
    at THREE.Clock.start (/data/users/rlinsalata/workspaces/js_ws/node_playground/node_modules/three/three.js:7911:20)
    at THREE.Clock.getDelta (/data/users/rlinsalata/workspaces/js_ws/node_playground/node_modules/three/three.js:7938:9)
    at repl:1:10
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
> THREE.REVISION
'74'
```

Running w/ r73 (old working state):
```
$ node
> var THREE = require('three');
> THREE.REVISION
'73'
> var myclock = new THREE.Clock();
> myclock.start()
> myclock.getDelta()
20.876
> myclock.getDelta()
1.437
> myclock.getDelta()
4.405
```

Version Info:
Three version r74
npm package 'three' three@0.74
Node v5.2.0
Ubuntu 14.04

### PR DESCRIPTION
**Pull request by tschw**
Fixes #8112 and keeps using `performance`, even though the precision decreases over a longer period of time.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> even though the precision decreases over a longer period of time.

What do you mean?

**Comment by tschw** [comment]
> > even though the precision decreases over a longer period of time.

@mrdoob 
> What do you mean?

Three things
- `* 0.001` -> `/ 1000` no longer induces a precalculated error, so it is a lot more accurate, but that doesn't make it necessarily exact,
- a bit of aliasing and the error from this calculation is accumulated in `.elapsedTime`, and
- this floatingpoint value increases in magnitude and therefore loses precision after the dot at some point .

So there's no reliable absolute precision and I'm not quite sure about the relative case (error in respect to the magnitude, that is), here.

**Comment by mrdoob** [comment]
Ah, I understand. Thanks for the explanation! 😊

**Comment by tschw** [comment]
@mrdoob 
> Ah, I understand. Thanks for the explanation!

I think it's good you ask, because we graphics folks do good having these effects on the radar. 

In this case we have a 64-bits, so there's quite some headroom. In GLSL, the minimum precisions are only 24/16 bits for vertex/fragment shader. Carrying around large offsets effectively turn `float`s into `int`s or something even less precise on an absolute scale.

**Pull request merged**
