### PR TITLE
GLTFLoader: Add renderer.gammaOutput=true to examples.

### LINKED ISSUE #12554: GLTFLoader display model is darker
##### Description of the problem 

My modal is .obj, and it displays well when I use objLoader and mtlLoader . I use obj2gltf to convert my obj modal to gltf. And then it displays more darker with GLTFLoader. what's the problem?

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #12554. See #11110.

### CODE REVIEW

**Comment by takahirox** [comment]
I don't perfectly understand gamma color topics yet, but `renderer.gammaOutput` should always be true when `GLTFLoader` is used? I'm wondering if we should write this note to document or somewhere.

**Comment by donmccurdy** [comment]
I'm still figuring this out too, but from #11110 it sounds like `gammaOutput=true` should be preferred most of the time, regardless of model formats, unless you are doing post-processing.

**Comment by donmccurdy** [comment]
Related: https://maddieman.wordpress.com/2009/06/23/gamma-correction-and-linear-colour-space-simplified/

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
