### PR TITLE
Src: Ensure tone mapped value is in-range

### PR DESCRIPTION
**Pull request by WestLangley**
As mentioned in https://github.com/mrdoob/three.js/pull/26129#issuecomment-1561645663.

### CODE REVIEW

**Comment by WestLangley** [comment]
>suppose we were using three.js to bake environment maps or lightmaps in the common unitless or "relative" lighting workflow, for export to .EXR. I believe we would want linear tone mapping

I would use `NoToneMapping` for that. Granted, that is an important workflow, but it does not involve a tone mapping step.

>Using max( toneMappingExposure * color, 0.0 ) would be safe, though, and likely forward-compatible with HDR color spaces?

I think you mean for HDR _devices_. ... HDR devices will require separate tone mapping functions. I don't think we need to address that now.

>I think it would be reasonable to properly expose the image before applying effects like bloom, which in turn should happen before clamping.

My understanding is color correction and color grading effects are applied prior to exposure and tone mapping. In fact, exposure immediately precedes tone mapping.

**Comment by donmccurdy** [comment]
> I would use NoToneMapping for that

🔲 We cannot adjust exposure with NoToneMapping – that is the purpose of LinearToneMapping I think? This would be necessary for a unitless env map.

> I think you mean for HDR devices.

✅ Yes, thanks. Agreed that we don't need to address it now, and these devices will require new tone mapping functions in any case.

> My understanding is color correction and color grading effects are applied prior to exposure and tone mapping...

✅ Spent some time reading on this, and yes – usually prior to exposure and tone mapping, or sometimes after both, but I couldn't find examples of effects that must go between the two. I'll withdraw that concern.

**Review by donmccurdy — APPROVED** [review]
> Furthermore, one must pass valid data into the OETF. Failing to clamp is incorrect.

I'm not aware that [0,1] input data is a requirement of the sRGB OETF. The same clamp could also be applied immediately prior to the OETF, rather than in the tone mapping function. But if we wish this to be a requirement of our color pipeline, that is OK with me.

**Comment by WestLangley** [comment]
I implemented an `ExposureShader`, and it works great for @donmccurdy's use case. In particular, it is device-independent, unlike our (future) `OutputPass`.

If there is interest, I'll file a PR.

**Comment by mrdoob** [comment]
@WestLangley That is interesting indeed!

**Pull request merged**
