### PR TITLE
WebGLRenderer: deprecated renderTarget and forceClear from render()

### LINKED ISSUE #15420: WebGLRenderer.render() should respect previously set render target
A little while ago `clearRenderTarget()` was (rightly) deprecated because it internally changed the render target. Now you have to do it explicitely:

```javascript
renderer.setRenderTarget(target);
renderer.clear();
```

This makes the internally used concept of a state machine more clear.
But by that logic a call to `render()` should use the current render target as well:

```javascript
renderer.setRenderTarget(target);
renderer.render(scene, camera);      // should render to target
```

But that doesn't work because of this line:
https://github.com/mrdoob/three.js/blob/3013895bf68ad0c27fb0f9d3ca0beea2c0e7a87a/src/renderers/WebGLRenderer.js#L1106

Right now it only works like this:
```javascript
renderer.setRenderTarget(target);
renderer.render(scene, camera, target);
```

Please let me know what you think. I'd be happy to submit a PR for this.

### PR DESCRIPTION
**Pull request by maccesch**
resolves #15420

### CODE REVIEW

**Comment by Mugen87** [comment]
I only vote to merge such a PR if the codebase (examples/docs) is also changed. Otherwise there are a lot of warnings all over the repository.

**Comment by maccesch** [comment]
Makes sense. I'm on it.

**Comment by maccesch** [comment]
Ok everything should be updated. The docs in englisch I changed as well but unfortunately I don't know Chinese...

**Comment by maccesch** [comment]
Is there anything that I need to change for this to be merged?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Ops! Seems like this PR broke many examples. 

https://raw.githack.com/mrdoob/three.js/dev/examples/#webgl_animation_cloth
https://raw.githack.com/mrdoob/three.js/dev/examples/#webgl_animation_skinning_blending
https://raw.githack.com/mrdoob/three.js/dev/examples/#webgl_camera_array
...

Do you mind taking a look?

**Comment by maccesch** [comment]
Sure!

**Comment by maccesch** [comment]
Turns out I somehow forgot to restore the render target after the shadow map was rendered. Sorry about that!

**Comment by Mugen87** [comment]
Update the migration guide^^

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r101--r102

**Comment by mrdoob** [comment]
> Turns out I somehow forgot to restore the render target after the shadow map was rendered. Sorry about that!

No worries!

**Comment by Mugen87** [comment]
I have tested all examples in `dev` and it seems this PR broke the following demos:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_effects_anaglyph.html

black screen and the following warning: 

[.WebGL-0x7f9b460c1c00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_cubemap_dynamic.html

black screen and the following warning:

[.WebGL-0x7ffabc003800]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl2_multisampled_renderbuffers.html

black screen on the left and no warning

All three examples work with the previous commit in `dev`: 28b6dc802cdeffcddeb509486309389108fb043b

@maccesch Can you please have a look at these?

**Comment by maccesch** [comment]
Sure, on it.

**Comment by Mugen87** [comment]
Updated the list...

**Comment by maccesch** [comment]
The box selection works for me without any errors. Just to make sure: Did you rebuild first?

**Comment by Mugen87** [comment]
The build files on `dev` should be up to date.

**Comment by Mugen87** [comment]
I think you have to ensure that render targets are at certain points unset. For example here:

https://github.com/mrdoob/three.js/blob/efe122c338c5cf2bc31b41825f6c3d1851223a3f/examples/js/effects/AnaglyphEffect.js#L145-L148

The second call of `WebGLRenderer.render` should not use a render target, so you have to set it to null. This would be the fix:

```js
renderer.setRenderTarget( _renderTargetR );
renderer.clear();
renderer.render( scene, _stereo.cameraR );

renderer.setRenderTarget( null ); // FIX
renderer.render( _scene, _camera );
```
I guess the other demos needs similar fixes.

**Comment by Mugen87** [comment]
@mrdoob @WestLangley I'm not sure we were aware of this side effect. Problems like mentioned in my previous post will break app code.

**Comment by WestLangley** [comment]
I was aware of it. See https://github.com/mrdoob/three.js/issues/15420#issuecomment-447531871.

**Comment by WestLangley** [comment]
Who is responsible for updating the typescript files when the API is changed?

**Comment by Mugen87** [comment]
> Who is responsible for updating the typescript files when the API is changed?

I would say the one who is doing the change.

In any event, let me update the migration guide to make things more clear.

**Comment by Mugen87** [comment]
This one is also broken: https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_furnace_test.html

The spheres should not be visible.

**Comment by WestLangley** [comment]
@mrdoob What is the pattern you want users to use? In other words, what is the convention we are adopting?
```js
renderer.setRenderTarget( null ); // always set prior to each render call
renderer.render( scene, camera );
```
or
```js
renderer.getRenderTarget( previousRenderTarget );
renderer.setRenderTarget( newRenderTarget );
renderer.render( scene, camera );
renderer.setRenderTarget( previousRenderTarget ); // always restore to previous render target
```

**Comment by maccesch** [comment]
The anaglyph example was indeed easy to fix. I forgot to set the render target to `null` like I did in all the other examples. 

The multisample render target actually required a little change in the renderer. 

The other examples I haven’t figured out yet. They seem to be related to something in the effect composer. But I’ll figure that out. 

I can do the TypeScript definition update as well

**Comment by mrdoob** [comment]
> @mrdoob What is the pattern you want users to use? In other words, what is the convention we are adopting?

For the time being this one looks best.

```js
renderer.setRenderTarget( null ); // always set prior to each render call
renderer.render( scene, camera );
```

Only when needed though.

We could add new methods to `WebGLRenderTexture`:

```js
var target = new THREE.WebGLRenderTexture( 256, 256 );
target.setRenderer( renderer );
target.render( scene, camera );

var material = new THREE.MeshBasicMaterial( { map: target.texture } );
```

So `WebGLRenderTexture`'s `.render()` would be the code we keep repeating now:

```js
var currentRenderTarget = renderer.getRenderTarget();
renderer.setRenderTarget( this );
renderer.render( scene, camera );
renderer.setRenderTarget( currentRenderTarget );
```

Or we could create a new helper class:

```js
var rtRenderer = new THREE.RenderTargetRenderer( renderer );
rtRenderer.setRenderTarget( target );
rtRenderer.render( scene, camera );

var material = new THREE.MeshBasicMaterial( { map: target.texture } );
```

**Comment by WestLangley** [comment]
>Only when needed though.

But like I said in https://github.com/mrdoob/three.js/issues/15420#issuecomment-447531871,

>there is no guarantee the render target had not been changed by some other method.

Therefore it is always needed.

On the other hand, note how in shadow mapping we restore the render target to the previous render target. So it is not clear when to do what, or who is responsible.

**Comment by maccesch** [comment]
> > there is no guarantee the render target had not been changed by some other method.
> 
> Therefore it is always needed.

Actually we now made / are making sure that no method changes the render target. If a method needs to do it, it is restored at the end. So unless the user explicitely changes the render target himself he doesn't need to call `setRenderTarget( null );`

**Comment by WestLangley** [comment]
Then you are implementing  the second approach in https://github.com/mrdoob/three.js/pull/15571#issuecomment-463736748 -- not the approach @mrdoob seemed to prefer.

Personally, I do not care which policy is adopted; I just want it made clear.

**Comment by mrdoob** [comment]
>> Only when needed though.

> But like I said in https://github.com/mrdoob/three.js/issues/15420#issuecomment-447531871,

Yeah. I meant that we should not add that to all the examples, but only to the code that needs it.

**Comment by WestLangley** [comment]
So the policy is: "if the render target is changed, it must be restored".

**Comment by mrdoob** [comment]
Ah, I get what you mean now. Yes.

**Comment by Mugen87** [comment]
After some debugging I have found another problem. `THREE.CubeCamera` is currently broken since `WebGLRenderer.setRenderTarget()` has to be called before each call of `WebGLRenderer.render()`. Otherwise the wrong framebuffer is used and not the one for the active cube face.

https://github.com/mrdoob/three.js/blob/e284e9bf28c422131a02f9af44b9813aed9828b9/src/renderers/WebGLRenderer.js#L2537-L2542

So just doing this is not enough:

```js
renderTarget.activeCubeFace = 2;
renderer.render( scene, cameraPY );
```
This only works for the first cube side but not for the five others since the framebuffer never changes.
---

TBH, I vote to revert the PR for now for several reasons:

- It was badly tested
- The change should done with a consistent policy in how render targets are restored
- We need to clarify how to handle changes of `activeCubeFace`. This might need an API change.

**Comment by mrdoob** [comment]
> So just doing this is not enough:
>
> ```js
> renderTarget.activeCubeFace = 2;
> renderer.render( scene, cameraPY );
> ```

Not sure I follow. How would the change need to be to fix `CubeCamera`?

**Comment by mrdoob** [comment]
Related: #15525

**Comment by Mugen87** [comment]
Before this PR was merged, `CubeCamera` looked like this:

```js
this.update = function ( renderer, scene ) {

    if ( this.parent === null ) this.updateMatrixWorld();

    var currentRenderTarget = renderer.getRenderTarget();

    var renderTarget = this.renderTarget;
    var generateMipmaps = renderTarget.texture.generateMipmaps;

    renderTarget.texture.generateMipmaps = false;

    renderTarget.activeCubeFace = 0;
    renderer.render( scene, cameraPX, renderTarget );

    renderTarget.activeCubeFace = 1;
    renderer.render( scene, cameraNX, renderTarget );

    renderTarget.activeCubeFace = 2;
    renderer.render( scene, cameraPY, renderTarget );

    renderTarget.activeCubeFace = 3;
    renderer.render( scene, cameraNY, renderTarget );

    renderTarget.activeCubeFace = 4;
    renderer.render( scene, cameraPZ, renderTarget );

    renderTarget.texture.generateMipmaps = generateMipmaps;

    renderTarget.activeCubeFace = 5;
    renderer.render( scene, cameraNZ, renderTarget );

    renderer.setRenderTarget( currentRenderTarget );

};
```
Notice how a render target was supplied and internally set by the renderer. After the change, the file looks like this:
```js
this.update = function ( renderer, scene ) {

    if ( this.parent === null ) this.updateMatrixWorld();

    var currentRenderTarget = renderer.getRenderTarget();

    var renderTarget = this.renderTarget;
    var generateMipmaps = renderTarget.texture.generateMipmaps;

    renderTarget.texture.generateMipmaps = false;

    renderTarget.activeCubeFace = 0;
    renderer.setRenderTarget( renderTarget );

    renderer.render( scene, cameraPX );

    renderTarget.activeCubeFace = 1;
    renderer.render( scene, cameraNX );

    renderTarget.activeCubeFace = 2;
    renderer.render( scene, cameraPY );

    renderTarget.activeCubeFace = 3;
    renderer.render( scene, cameraNY );

    renderTarget.activeCubeFace = 4;
    renderer.render( scene, cameraPZ );

    renderTarget.texture.generateMipmaps = generateMipmaps;

    renderTarget.activeCubeFace = 5;
    renderer.render( scene, cameraNZ );

    renderer.setRenderTarget( currentRenderTarget );

};
```

`setRenderTarget()` is only used once in order to set the instance of `WebGLRenderTargetCube`. This does not work thought since `setRenderTarget()` also sets the correct framebuffer which depends in this case on the active cube face. A fix would look like this:

```js
this.update = function ( renderer, scene ) {

    if ( this.parent === null ) this.updateMatrixWorld();

    var currentRenderTarget = renderer.getRenderTarget();

    var renderTarget = this.renderTarget;
    var generateMipmaps = renderTarget.texture.generateMipmaps;

    renderTarget.texture.generateMipmaps = false;

    renderTarget.activeCubeFace = 0;
    renderer.setRenderTarget( renderTarget );
    renderer.render( scene, cameraPX );

    renderTarget.activeCubeFace = 1;
    renderer.setRenderTarget( renderTarget );
    renderer.render( scene, cameraNX );

    renderTarget.activeCubeFace = 2;
    renderer.setRenderTarget( renderTarget );
    renderer.render( scene, cameraPY );

    renderTarget.activeCubeFace = 3;
    renderer.setRenderTarget( renderTarget );
    renderer.render( scene, cameraNY );

    renderTarget.activeCubeFace = 4;
    renderer.setRenderTarget( renderTarget );
    renderer.render( scene, cameraPZ );

    renderTarget.texture.generateMipmaps = generateMipmaps;

    renderTarget.activeCubeFace = 5;
    renderer.setRenderTarget( renderTarget );
    renderer.render( scene, cameraNZ );

    renderer.setRenderTarget( currentRenderTarget );

};
```
Now, `webgl_materials_cubemap_dynamic` works again. But as you can see, it's contradictory to use `setRenderTarget()` like that since the render target does not actually change.

**Comment by maccesch** [comment]
@Mugen87 I get it, you're right. Maybe we should move some of the code from `setRenderTarget()` to `render()`?

**Comment by maccesch** [comment]
The just submitted PR makes the dynamic cube map example work again.

**Comment by Mugen87** [comment]
Sorry, but introducing `WebGLRenderTarget.beforeRender()` is no good design from my point of view. There is already `Object3D.onBeforeRender()` which is part of the public API. What if `WebGLRenderTargetCube.beforeRender()` is overwritten by users? Besides, new methods should be documented and also the typescript files adjusted. I don't see these changes in your PR.

Before you make more PRs, I suggest to revert the previous work and start from scratch with a new branch where everything is carefully discussed, tested and verified. I can't say that I'm happy in how these changes are implemented in `dev`....

**Comment by maccesch** [comment]
Sure. I'll support what you decide. But I feel we're close to finishing this. Only two examples left to fix. And I'm happy to include docs and TypeScript files if you want.

> There is already `Object3D.onBeforeRender()` which is part of the public API

Should I rename `beforeRender` to `onBeforeRender`? The render targets don't inherit from `Object3D`

> What if `WebGLRenderTargetCube.beforeRender()` is overwritten by users?

I'm sorry but I don't follow here.

**Comment by Mugen87** [comment]
> > What if `WebGLRenderTargetCube.beforeRender()` is overwritten by users?

>I'm sorry but I don't follow here.

Sry, I've already mixed `beforeRender` with `onBeforeRender()`^^. I guess I would put the code directly into  `WebGLRenderer` instead of introducing a new method.

**Comment by maccesch** [comment]
> I guess I would put the code directly into `WebGLRenderer.render()` instead of introducing a new method.

Updated PR.

> The code base follows no common policy in how render targets are restored so far.

I feel it does. The library code always takes care to restore the current render target if it has been changed in a method. Only user code in examples uses the `setRenderTarget( null );` like a user would have to do.

**Comment by Mugen87** [comment]
> Only user code in examples uses the `setRenderTarget( null );` like a user would have to do. 

The problem when users copy code from the examples (and that happens a lot), `setRenderTarget( null );` is not robust. This approach does not restore a render target that was  previously set by the user.

**Comment by maccesch** [comment]
Settings the render target to `null` robustly renders to screen like before `renderer.render()` without a provided render target argument did. So when users copy code from examples, I don't see any difference to before the API change.

And when they call any library method they can rely on the fact that a previously set render target still is the current render target. The same goes for the example code like `EffectComposer` and all that.

Only at places in the example code where a user would have deliberately wanted to change a render target that he himself set previously, a call to `setRenderTarget` is done. This includes changes to `null`.

This is in line with what @mrdoob said [here](https://github.com/mrdoob/three.js/pull/15571#issuecomment-463760123)

**Comment by maccesch** [comment]
You might be right though about moving this to separate branch for now. I've been at the deferred renderer for a while now and I still don't exactly know what's going wrong. I suspect it has something to do with the stencil buffer. I don't have too much time so it might take a while until I figure this out.

**Comment by Mugen87** [comment]
`BokehPass.render()` is one example I'm referring to. With this new approach, it's necessary to restore the render target like the clear color and clear alpha.

**Comment by maccesch** [comment]
> `BokehPass.render()` is one example I'm referring to.

Correct me if I'm wrong but render passes only ever are used in combination with `EffectComposer`. All the passes' `render()` methods are called in `EffectComposer.render()`. So to optimize things I only restored the render target at the end of `EffectComposer.render()`.

https://github.com/mrdoob/three.js/blob/e284e9bf28c422131a02f9af44b9813aed9828b9/examples/js/postprocessing/EffectComposer.js#L138

If you think that render passes might be used outside of the effect composer of course I can easily change that.

---

> This terminology is not correct. There is no "user code" in the library.

Sorry for using the wrong terminology. Maybe my thinking is wrong but currently I'm assuming this: The code in the example .html files is meant as what I called "user code". In the sense that when a user uses the library he would write code like that. Also when someone copies an example this is the code he would change. Is that not correct?

**Comment by Mugen87** [comment]
That's correct, yes. About the other point: It's more about implementing a policy like previously mentioned in this thread: https://github.com/mrdoob/three.js/pull/15571#issuecomment-463892756

**Comment by jee7** [comment]
Sorry to bug in, but this seems like a weird change. Having the `renderTarget` in the `render` signature was very convenient. From the user's perspective I would not want to write 4 lines of code
```
renderer.setRenderTarget(renderTarget);
renderer.render(scene, camera);
renderer.setRenderTarget(null);
renderer.render(scene, camera);
```
instead of just writing 2 lines:
```
renderer.render(scene, camera, renderTarget);
renderer.render(scene, camera);
```
Especially if I do not want to think about the state-machine with the `_currentRenderTarget` inside the library code. I understand that there are cases where it might make more sense to think about the state-machine, like if you need to do several ops (render, clear etc) with a single render target in a sequence.
But for me this change just seems to generate a lot of overhead in coding. Would it be possible to keep the `render(scene, camera, renderTarget, forceClear)` signature together with this change to support both use cases?
Or even just `render(scene, camera, renderTarget)`? It makes sense to read that we _render a scene (what) with a camera (with what) to the render target (to where)_. This single line seems to indicate to the reader the main things they need to know about this render. With the other approach they always have to check if the state-machine has changed (is there some `setRenderTarget` maybe some 30 lines above the actual `render` call etc).

I see the issue this entire thing started from. That this way it was confusing to clear the render target without calling `render()`. However, that could easily be solved by implementing the `clearRenderTarget(renderTarget)` in a way that it changes the inner `_currentRenderTarget` back to whatever it was before the method was called. Just as it seems to be done now inside the `CubeCamera.clear()`.

**Comment by mrdoob** [comment]
Sorry for the delay and thanks for the patience and discourse guys!

In my eyes, the actual issue here is `renderTarget.activeCubeFace`. I think I would, instead, pass the activeCubeFace as a second parameter in `setRenderTarget()`.

The `CubeCamera` code would look like this:

```js
this.update = function ( renderer, scene ) {

    if ( this.parent === null ) this.updateMatrixWorld();

    var currentRenderTarget = renderer.getRenderTarget();

    var renderTarget = this.renderTarget;
    var generateMipmaps = renderTarget.texture.generateMipmaps;

    renderTarget.texture.generateMipmaps = false;

    renderer.setRenderTarget( renderTarget, 0 );
    renderer.render( scene, cameraPX );

    renderer.setRenderTarget( renderTarget, 1 );
    renderer.render( scene, cameraNX );

    renderer.setRenderTarget( renderTarget, 2 );
    renderer.render( scene, cameraPY );

    renderer.setRenderTarget( renderTarget, 3 );
    renderer.render( scene, cameraNY );

    renderer.setRenderTarget( renderTarget, 4 );
    renderer.render( scene, cameraPZ );

    renderTarget.texture.generateMipmaps = generateMipmaps;

    renderer.setRenderTarget( renderTarget, 5 );
    renderer.render( scene, cameraNZ );

    renderer.setRenderTarget( currentRenderTarget );

};
```

**Comment by mrdoob** [comment]
@Mugen87 

> When users copy code from the examples (and that happens a lot), `setRenderTarget( null );` is not robust.

That's a fair point. Should we introduce `renderer.unsetRenderTarget()`?

**Comment by mrdoob** [comment]
@jee7 

> Sorry to bug in, but this seems like a weird change. Having the `renderTarget` in the `render` signature was very convenient. From the user's perspective I would not want to write 4 lines of code

It was indeed convenient, but it also introduced bugs. As per brevity of code, I'm hoping we'll eventually create something like what I proposed [here](https://github.com/mrdoob/three.js/pull/15571#issuecomment-463760123).

So your 2 lines of code will be even shorter:

```js
renderTarget.render( scene, camera );
renderer.render( scene, camera );
```

**Comment by jee7** [comment]
> As per brevity of code, I'm hoping we'll eventually create something like what I proposed [here](https://github.com/mrdoob/three.js/pull/15571#issuecomment-463760123).
> 
> So your 2 lines of code will be even shorter:
> 
> ```js
> renderTarget.render( scene, camera );
> renderer.render( scene, camera );
> ```
But that is even more confusing. In that case both the `WebGLRenderTarget` and `WebGLRenderer` would have the functionality to render. So far it has been very clear that the renderers render. If other objects with different semantics also have the ability to start the GPU pipeline, then this does not seem right. Unless you plan to fully get rid of the idea that a renderer renders. In that case there should also be some screen class like:
```js
var screen = new THREE.WebGLScreen(...);
screen.render(scene, camera);

var target = new THREE.WebGLRenderTarget(...);
target.render(scene, camera);

```
Even in that case it seems weird. Does a _target_ or a _screen_ really should have functionality to render? They both seem rather like containers for the end result, rather than the objects that actually know how to call the pipeline and render.

The final example in your post does keep the idea that renderers render, but it still mixes apples and oranges. Like then there should also be a `ScreenRenderer`. Unless that is the `RenderTargetRenderer` with a default `renderTarget = null` in it.

In both cases I don't currently see how does the current `WebGLRenderer` fit into all that new structure. Likely it would not even be a renderer, but some context object for the new target-specific renderers. Which is an interesting concept, because then you could also have something like `WebGLContext`, `CanvasContext` etc and those all can be used to render into a render target or screen easily. But this seems like a really big change.

I hope it all works out somehow, but currently it seems difficult to see the logic behind this.

**Comment by timothyallan** [comment]
I also find it a bit off semantically if my renderTarget would have to render itself. It's a target for a renderer, not a renderer itself.

I would assume that the renderer would do the rendering, and I would tell it -what- to render, explicitly. Relying on some other function that had been called previously, maybe even by a different component/class, could be a source of confusion.

Has there been any thoughts into using a parameter object instead of hardcoded parameters like there is with Mesh's etc? No set parameter order, allows for future expansion, is explicit, and doesn't rely on multiple function calls in specific order.

Render thyself
```
renderer.render( scene, camera );
```

Render something else using optional property object
```
renderer.render( scene, camera, { target : renderTarget, clear : false });
```

or if you want to get fancy and replace 
```
renderTarget.render( scene, camera );
renderer.render( scene, camera );
```
into a one liner, it could take a target array and render them in order ;)
```
renderer.render( scene, camera, { target : [renderTarget, renderer]});
```

**Comment by mrdoob** [comment]
Okay, we'll cross that bridge when we come to it. For now we need to move out the `renderTarget`.

**Comment by Mugen87** [comment]
After debugging for a while now I think I know why `webgldeferred_animation` is broken. To make it short: Calling `renderer.clear()` is not always the same than passing `forceClear` to `WebGLRenderer.render()`. Why? Because executing `renderer.clear()` without parameters clears everything (color, depth, stencil). However, this might be unwanted!

In a scenario like this, things are going to break:

```js
renderer.autoClearDepth = false;
renderer.autoClearStencil = false;

renderer.clear(); // clears everything

renderer.render( scene, camera, renderTarget, forceClear ); // only clears color
```
In context of `webgldeferred_animation`, the problem is that `RenderPass` always calls `renderer.clear()` although `WebGLDeferredRenderer` changes `autoClearDepth` and `autoClearStencil` at various places. Changing the code in `RenderPass` to the following fixes the issue:
```js
if ( this.clear ) renderer.clear( renderer.autoClearColor, renderer.autoClearDepth, renderer.autoClearStencil );
```
But this solutions seems a hack from my point of view. Maybe `WebGLRenderer.clear()` can respect the auto properties directly? Something like:

```js
this.clear = function ( color, depth, stencil ) {

   var bits = 0;

   if ( this.autoClearColor || color ) bits |= _gl.COLOR_BUFFER_BIT;
   if ( this.autoClearDepth || depth ) bits |= _gl.DEPTH_BUFFER_BIT;
   if ( this.autoClearStencil || stencil ) bits |= _gl.STENCIL_BUFFER_BIT;

   _gl.clear( bits );

};
```

**Comment by Mugen87** [comment]
To sum it up: `WebGLRenderer.clear()` is no 100% surrogate for the `forceClear` parameter.

**Comment by Mugen87** [comment]
> Should we introduce `renderer.unsetRenderTarget()`?

I actually wanted to vote for the following style. It's just a more safe approach when users copy code.

```js
var previousRenderTarget = renderer.getRenderTarget();
renderer.setRenderTarget( newRenderTarget );
renderer.render( scene, camera );
renderer.setRenderTarget( previousRenderTarget );
```

**Comment by mrdoob** [comment]
Thanks for investigating this @Mugen87. It's great to be aware of that breakage, but it gets to show how fragile the current design was. I think the new approach will make the code more clear.

**Comment by Mugen87** [comment]
In this case we should remove `WebGLDeferredRenderer` since it is based on are workflow which is not supported anymore. It seems not possible to fix `WebGLDeferredRenderer` without changing other entities like `RenderPass`. The class only works if the post-processing respects `autoClearDepth` and `autoClearStencil` . And that's not true anymore since passes clear all buffers.

An other option might be to change the way of how `WebGLRenderer.clear()` works. It would be actually nice if it's possible to define a "clear state" that is respected by all calls of `WebGLRenderer.clear()`. Right now, you always have to pass parameters to the method call. Instead we could do this:

```js
renderer.setClearState( true, false, false ); // only clear color but not the depth and stencil buffer
renderer.clear();
```

This would be closer to "state machine" concept. The former parameters of `WebGLRenderer.clear()` should deprecated with such an approach.

**Comment by maccesch** [comment]
@Mugen87 Thanks for that insight on `WebGLDeferredRenderer`! I didn't quite get that before.

Do you think that instead of having just a broad `.clear` flag on `RenderPass` adding more fine grained flags `.clearStencil`, `clearDepth`, `clearColor` would be a bad idea?

**Comment by Mugen87** [comment]
I think a quick fix like this would be okay:

```
if ( this.clear ) renderer.clear( renderer.autoClearColor, renderer.autoClearDepth, renderer.autoClearStencil );
```
This approach is also used at other places like:
https://github.com/mrdoob/three.js/blob/b863277f1fc695a4d0b974b369589aab59a74c96/src/renderers/webgl/WebGLBackground.js#L47

The code could be added in `RenderPass` and `ShaderPass` but it would not solve the actual issue.

**Comment by gfodor** [comment]
It looks like this PR introduced references to `arguments` inside of `render`, which causes memory to be allocated every frame.

**Comment by Mugen87** [comment]
Can you please elaborate in more detail what you mean?

**Comment by gfodor** [comment]
sure. the use of `arguments` in a JS function allocates memory (if you use the firefox allocations profiler, you can see this.) by introducing the use of `arguments` in `render` in this PR, a call to render() will now allocate memory whereas before it did not. I don't know in general three.js's philosophy on managing memory allocations but it seems a good idea to avoid it in anything happening every frame since it increases GC. there are other places where three.js allocates memory in the main render loop, but this is a recent regression and surfaces in the top allocators in profiling our app, so I wanted to mention it.

**Comment by maccesch** [comment]
@Mugen87 Should we then maybe add the arguments back but as `renderTargetDeprecated` and `clearDeprecated` or so? This way we could avoid using `arguments`.

**Comment by Mugen87** [comment]
@gfodor I'm afraid we have to process the deprecated parameters in some way, otherwise a lot of code will break. User should still be able to pass `renderTarget` and `clear` to the method but they are going to be warned that this approach is deprecated.

Um, this issue an unfortunate side effect nobody was aware of.

> Should we then maybe add the arguments back but as renderTargetDeprecated and clearDeprecated or so?

This is the only solution I can think of right now, too. It will clutter the method signature but at least the memory allocation is gone. And don't have to document these parameters.

@mrdoob What do you think?

**Comment by takahirox** [comment]
Does anyone here know if the modern JIT compilers still allocate memory every frame for `arguments[2,3]` access? I tried to take memory allocation profile but I couldn't do it well because of the devtool change...

If they still allocate, I would like to suggest to avoid it. For example we might simply remove the checking `arguments[2, 3]` lines because two years has past since this PR was merged. Or `*Deprecated` arguments solution still looks good to me.

**Comment by mrdoob** [comment]
@takahirox removing these sounds good to me 👍

**Pull request merged**
