### PR TITLE
initital version materials

### PR DESCRIPTION
**Pull request by gero3**
This is a try to get materials as a array of materials. This is what is suggested in #8924.
I don't really like the approach decsribed here, tough. Mainly because it still needs to check if there is only 1  element in the array.

### CODE REVIEW

**Comment by mrdoob** [comment]
I already tried some days ago and also found showstoppers:
https://github.com/mrdoob/three.js/issues/8924#issuecomment-285847549

**Comment by TheCodeCrafter** [comment]
If you want to avoid isArray, just check indexes.
`if(array[1]) {
   isArray = true;
} else {
  isArray = false;
}`

That is all you would have to do right? Because if it wasn't an array, then it would be undefined, and ultimately, false (but we may have to alter it to fit with undefined). But you get the main idea, right? I'm pretty new to hardcore engine programming, and even checking for arrays, so I'm probably wrong, and you awesome people have probably thought of this already, but I'm just throwing this out there....

**Comment by mrdoob** [comment]
@TheCodeCrafter Please, read the whole discussion carefully. The issue is not about calling `Array.isArray()`.

**Comment by mrdoob** [comment]
> I'm pretty new to hardcore engine programming, and even checking for arrays, so I'm probably wrong, and you awesome people have probably thought of this already, but I'm just throwing this out there....

Please, refrain of doing that here. Comments that don't provide valuable information can become a burden for people that want to help. They can easily get overwhelmed because there is too much noise/too much to read.

**Comment by gero3** [comment]
Actually I'm working on another idea.

**Pull request closed without merging**
