### PR TITLE
Shaders: Move bicubic texture filtering to transmission chunk.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #25483, https://discourse.threejs.org/t/potential-regression-v149-v150/48397

**Description**

`r150` introduces a regression since the bicubic texture filtering was added to `common.glsl`. This chunk is used in all materials as well as vertex and fragment shaders. However: 

- `common.glsl` should not hold logic which is vertex or fragment shader specific.
- `common.glsl` should not hold GLSL 3 specific code which breaks WebGL 1 (like `textureSize` or `textureLod`).  

To be clear: The current code in `common.glsl` breaks all WebGL 1 apps. This change needs to be cherry-picked to `master`.

### CODE REVIEW

**Comment by epreston** [comment]
This reminds me, can we change the approach and workflow for shaders ?  

- Builds would be 20% smaller
- developers would be free to drastically enhance the shaders with fewer restrictions 
- things like this would not break people upgrading (our game side stepped this using the alternative approach).  

Where is the best place to document this ?

**Comment by LeviPesin** [comment]
Please create a new issue. I personally think the best approach is to integrate Nodes system into core (https://github.com/mrdoob/three.js/issues/16440) and then use node materials instead of current shaders.

**Comment by epreston** [comment]
> (Also, builds could be made much smaller, I think, just by excluding XR from them -- I think the percent of projects that are using it is far from 100%...)

XR is a sensible 5% gain if it can be decoupled.

> (And the best way is possibly to remove the builds entirely -- with current bundlers being able to create a custom build with all unneeded parts tree-shaked.)

I'm talking a savings of 20% off the minimum bundled tree shaken size.

**Comment by epreston** [comment]
@Mugen87 I'm not going off topic.  Every release has one of these issues, your game / renderer breaks, and you have to go digging.  We can structure this to de-risk it.

I'll document it out in an issue.

**Comment by Mugen87** [comment]
Sorry, but your posts are off-topic since they are unrelated to this particular change. And that makes it harder for the team to follow the discussion and eventually review the PR. 

Like you have already mentioned, it's best to file a new issue.

**Comment by mrdoob** [comment]
> To be clear: The current code in `common.glsl` breaks all WebGL 1 apps. This change needs to be cherry-picked to `master`.

Done! And published `0.150.1` on npm.

**Comment by paulmasson** [comment]
@mrdoob are you planning to update this release on JSDelivr, as you have done in the past (notably r137). And I'd love to know how you are able to update static branches there, as you are clearly able to do. Thanks!

**Comment by rahulp-open** [comment]
I have a vite project where I am using threejs library. configured the project with vite latest.

After bulding prod build, Project size is 503KBs. 

Same project built with v0.148.1 of threejs is 103KBs.

this is huge change in bundle size, what caused this issue!!!??

**Comment by epreston** [comment]
@rahulp-open few things:
-  writing out your issue here ensures not many people will see it
- 148.1 does not exist
- there's only a 2 KB difference in 148 and 150

**Comment by rahulp-open** [comment]
It's making a lot of changes in build size. Build size went from 100kb to 500kb.

**Comment by epreston** [comment]
You've disabled minification in vite. It's impossible for the library to be larger than 380 KB otherwise. Please raise a separate issue.

**Comment by rahulp-open** [comment]
This is V 1.150.0

image

This is V 0.148.0

image

**Comment by rahulp-open** [comment]
@epreston 
> You've disabled minification in vite. It's impossible for the library to be larger than 380 KB otherwise. Please raise a separate issue.

image

minify is set to esBuild

**Comment by epreston** [comment]
Raise a separate issue please.

**Comment by epreston** [comment]
You're last screenshot shows why you are having an issue building a library of a library using this tooling.  Please tag me in the issue so I can point it out.

**Pull request merged**
