### PR TITLE
SoftwareRenderer draw lines

### PR DESCRIPTION
**Pull request by daoshengmu**
Support to draw lines in SoftwareRenderer.
It can adjust lineWidth by LineBasicMaterial.linewidth. Besides, I also give some examples, lines_colors, lines_cubes, lines_sphere, lines_splines to prove this function that works.
To solve #5073 Three.Line requirement.

### CODE REVIEW

**Comment by daoshengmu** [comment]
@mrdoob . How is this pull request? it can be merged?

**Comment by mrdoob** [comment]
There are some issues with spaces vs tabs indentation... https://github.com/mrdoob/three.js/pull/5892/files

But, the main reason I'm hesitant is that I'm seeing that the fixed point stuff makes the whole thing a bit hard to maintain (as you're probably well aware of). I wonder whether we should remove all that, end up with a less performant software renderer, but easier to maintain and improve...

**Comment by daoshengmu** [comment]
@mrdoob I have fixed the indentation. The fixed-point part is really hard to understand. I also can't be sure why it do this way. Probably, I must do some modifications to help me to understand it, or someone can explain it.

**Comment by mrdoob** [comment]
The fixed point code is by @rygorous. It produces a very fast rasterer. But it's a bit too hard to maintain (not everyone is @rygorous)

**Comment by daoshengmu** [comment]
@mrdoob . I think we should merge this PR first. At least, we already have some impressive demos. In the future, if we want to add any new functions, we must refactor this part.

**Comment by mrdoob** [comment]
Sounds good! Thanks for fixing the indentations!

**Comment by daoshengmu** [comment]
@mrdoob . Thanks for reply. Please wait me to fix the branch conflicts, and I will notice you to help merge it.

**Comment by mrdoob** [comment]
Oh, that'd be great. Many thanks!

**Comment by daoshengmu** [comment]
@mrdoob, I think it is good. Merge please.

**Comment by mrdoob** [comment]
Looks good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
