### PR TITLE
Examples: Convert loaders to ES6 Part III.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

More loader conversions.

I did not convert all loader to code to `let/const` since some code depends on the specific scoping of `var`. Since I'm not 100% familiar with the format of the following loaders, I would like to ask other devs for help and remove the remaining usage of `var` in `3DMLoader`, `EXRLoader`, `GCodeLoader`, `VTKLoader` and `LDrawLoader`.

/ping @tentone, @yomboprime, @fraguada, @sciecode

### CODE REVIEW

**Comment by yomboprime** [comment]
I've tested the LDrawLoader exhaustively (all models and options) and seems to be working right.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
What I have meant is that there is still code in the above loaders using `var` that needs to be converted.

**Comment by tentone** [comment]
Looks okay, On the GCodeLoader we can replace all var with let without problem.

**Comment by Mugen87** [comment]
@tentone Unfortunately that did not work in `GCodeLoader`. At the following place the linter says `line` is not defined when using `let/const`. 

https://github.com/mrdoob/three.js/blob/8f6cc7df1b0974753a62291ed9bd583a266f2b6f/examples/jsm/loaders/GCodeLoader.js#L94

The entire function `addSegment()` should be refactored so it does not rely on variables outside its scope. There are few places in the code base where such changes are necessary.

**Comment by Mugen87** [comment]
This is another confusing place:

https://github.com/mrdoob/three.js/blob/8f6cc7df1b0974753a62291ed9bd583a266f2b6f/examples/jsm/loaders/GCodeLoader.js#L202-L211

Where does `i` come from?

**Comment by tentone** [comment]
The methods should be moved into the loop. i variable comes from there, I will create a branch and open a PR too clean these up.

Thanks a lot!

**Comment by mrdoob** [comment]
@Mugen87 @marcofugaro do you guys get this when running `npm run build-examples`?

Screenshot 2021-04-13 at 21 39 55

**Comment by Mugen87** [comment]
I had the same error lately because of an outdated rollup version. Run `npm i` and try it again.

**Comment by mrdoob** [comment]
That was it. Thanks!

**Comment by fraguada** [comment]
@Mugen87 starting to look at this now. Happy to say bye to `var`!

**Comment by fraguada** [comment]
@Mugen87 starting to look at this now to fix the remaining `var`. Thanks!

**Pull request merged**
