### PR TITLE
Fix logarithmic depth buffer result when rendering with OrthographicCamera

### LINKED ISSUE #9108: Logarithmic Depth Buffer + Orthographic Camera
##### Description of the problem

Originally submitted to StackOverflow here: http://stackoverflow.com/questions/37733259/logarithmic-depth-buffer-orthographic-camera

The issue occurs when combining the logarithmic depth buffer option with an orthographic camera.

When using the standard linear depth buffer, both perspective and orthographic cameras work as expected.

When using a logarithmic depth buffer, only the perspective camera works as expected. Using an orthographic camera results in geometry bleeding through.

A jsfiddle highlighting the problem (also linked in the StackOverflow post) can be found here: http://jsfiddle.net/TheJim01/05up96m0/
##### Three.js version
- [x] r85
- [x] r84
- [x] r83
- [x] r82
- [x] r81
- [x] r80
- [x] r79
- [x] r78
- [x] r77
- [x] Tested back as far as r71
##### Browser
- [x] Chrome
- [ ] Chrome (Android) **<-- WORKS**
- [x] Firefox
- [ ] IE11 (IE does not support the EXT_frag_depth extension)
##### OS
- [x] Windows 7 (only one tested)
##### Hardware Requirements (graphics card, VR Device, ...)

I've seen the issue on two desktops with NVidia Quadro K600 (4GB), and a laptop with Quadro NVS 160M (2GB),

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #9108

Moves the orthographic camera detection shader code into a shared function and uses the default fragment depth when using an orthographic camera. I've tested this with the logarithmic depth buffer enabled and an orthographic camera in my application and it no longer causes the draw-through effect.

Some things to note:
- This disables the logarithmic depth buffer when using an orthographic projection matrix so there are no benefits to using a logarithmic depth buffer with an ortho camera. It just changes the shader code to produce sensible results.
- `gl_FragDepth` is _still_ written to when using an orthographic camera meaning the performance penalties are still incurred, which is not ideal but the other option of using defines would require recompiling all materials in the scene. I don't believe there's anything else in the library that automatically triggers a recompilation of shaders as far as I'm aware?
- If the `gl_FragDepth = gl_FragCoord.z` code path is enabled for perspective camera (which should be the same as disabling logdepth) we can see a bit of a different artifact in the large depth values demo but this could be due to how and when the gpu is able to discard fragments due to depth:

image

And lastly [here](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FragDepth.xhtml) is the relevant documentation that states that this is the right way to get the default depth value

> If depth buffering is enabled and no shader writes to gl_FragDepth, then the fixed function value for depth will be used (this value is contained in the z component of gl_FragCoord)

### CODE REVIEW

**Comment by WestLangley** [comment]
What do you think about this nomenclature?

```glsl
varying float isPerspective;

isPerspective = isPerspectiveMatrix( projectionMatrix ) ? 1.0 : 0.0;

...

gl_FragDepthEXT = ( isPerspective == 1.0 ) ? log2( vFragDepth ) * logDepthBufFC * 0.5 : gl_FragCoord.z;
```

Just a suggestion.

**Comment by gkjohnson** [comment]
> ```js
> varying float isPerspective;
> 
> isPerspective = isPerspectiveMatrix( projectionMatrix ) ? 1.0 : 0.0;
> ```

This is what I had originally named the variable but `points_vertex.glsl` and `sprites_vertex.glsl` also declare variables named `isPerspective` so I picked a name that seemed less likely to inadvertently conflict with other shader code.

> ```js
> gl_FragDepthEXT = ( isPerspective == 1.0 ) ? log2( vFragDepth ) * logDepthBufFC * 0.5 : gl_FragCoord.z;
> ```

I can move the conditional to a single line, as well. Just for my own education is this a stylistic preference or are there supposed to be implications like performance benefits to this style of condition?

**Comment by WestLangley** [comment]
Well, we _typically_ name varyings starting with a 'v', so even better would be something like:

```glsl
varying vPerspectiveCamera;
```

> conditional to a single line... is this a stylistic preference

Yes. Write it any way you want. It is really up to @mrdoob.

**Comment by WestLangley** [comment]
Thanks for this. I don't know what to tell you about the artifacts you are seeing. Perhpas @Mugen87 can have a look at this PR.

@mrdoob What this PR is doing is simply ignoring the request for a logarithmic depth buffer if the camera not a perspective one.

**Comment by gkjohnson** [comment]
Updated the variables names to `vIsPerspective`.

> I don't know what to tell you about the artifacts you are seeing.

My best guess is that it would have something to do with being able to discard fragments due to the depth test after the vertex shader in the first case but must wait to do the check until after the fragment shader in the second case.

**Comment by mrdoob** [comment]
Looks good to me!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@gkjohnson @WestLangley 

FYI I've reverted cfb584d98788b8ead2a43ece73e29c4c8fac66fe. That change broke #17476. 

Screen Shot 2019-09-27 at 2 49 11 PM

Screen Shot 2019-09-27 at 2 49 56 PM

I *think* it's because multiview does `#define projectionMatrix projectionMatrices[VIEW_ID]`.

Reverting that change fixes it, but I bet it means that points and sprites won't work with multiview. Something to study at some point.

**Comment by mrdoob** [comment]
Neeverrr miiiindd 😅https://github.com/mrdoob/three.js/commit/cded5c085fc6a0d5e082a70026b34fb2cfa70ec3

**Pull request merged**
