### PR TITLE
Add Subpixel Morphological Antialiasing (SMAA)

### PR DESCRIPTION
**Pull request by mpk**
This is the WebGL implementation of Subpixel Morphological Antialiasing (SMAA). It is a post-processing antialiasing technique, which should be as fast as FXAA while providing better quality (e.g. does not blur texture details).

The code is based on the reference implementation at https://github.com/iryoku/smaa (version 2.8; master is broken), which is MIT licensed. Fortunately, OpenGL 3 version is available, so I have directly used that one and modified parts that OpenGL ES does not like (variable length loops) and flipped some Y coordinates. All changes are noted in the source.

For three.js, I have implemented SMAA as a separate pass for EffectComposer (`SMAAPass.js` which uses shaders defined in `SMAAShader.js`). This should make it easy for developers to use SMAA, because it hides the actual complexity of multiple passes and binding of precomputed textures required for SMAA.

The required precomputed textures are:
- "search" - this one is very small and I have embedded it in JS.
- "area" - this one is unfortunately quite large (160 x 560 px) and must be provided from external file (`smaa-area.png`). Although the reference implementation provides a script that generates the texture, it is a very slow process (minutes), so it is infeasible to do it on-the-fly in a web browser.

Reference implementation provides the following options:
- Mode: 1x, S2x, T2x, 4x - In WebGL 1, only the 1x mode is feasible (other modes require 2x MSAA buffers).
- Preset: Low, Medium, High, Ultra - I have implemented only the Medium, which should provide 80% quality, per docs.
- Edge detection: Depth, Luma, Color - I have implemented only the Color, which should be the best one (catches most edges).

This PR is accompanied with an example (`webgl_postprocessing_smaa.html`), which should illustrate SMAA advantage - preserving texture details.

The results of this WebGL implementation are pixel-perfect identical to the reference implementation.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice! How about embedding both textures using base64 encoding instead?

**Comment by mpk** [comment]
That's a good idea; I have added it to the PR.

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
Sweet!  This is amazing.

**Comment by robertoranon** [comment]
Hi, I found two problems with the SMAA implementation and example (three.js 88dev):

- first, the example includes the following lines in the onWindowResize() method:

`var pixelRatio = renderer.getPixelRatio();
var newWidth  = Math.floor( width / pixelRatio ) || 1;
var newHeight = Math.floor( height / pixelRatio ) || 1;
composer.setSize( newWidth, newHeight );`

in retina displays, if I'm not mistaken, renderer.getPixelRatio() returns 2, so this will half the size of the composer each time the window is resized, making the rendered image very pixellated.

Substituting those lines with 

`composer.setSize( width, height);`

solves the problem.

- the second issue is more general - smaa does not seem to work very well, at least on my machine (MacBook Pro late 2016, radeon pro 460, chrome/safari). In the following screenshot, the wireframe cube does not seem very antialiased, and I wonder whether this is happens with other GPUs as well..

screen shot 2017-09-12 at 12 30 37

**Comment by bhouston** [comment]
Does SMAA work as designed?  That would be the first quesiton I would ask.  Sometimes these AA algorithms have limitations and the white lines on a black background is very challenging and also non-typical.

**Comment by robertoranon** [comment]
Good question, let it be added to the other two :)

More info: I have also tried to apply the SMAA pass to a more complex object, but I don't see any relevant difference ... but perhaps I did something wrong (although it does not seems so). The same object with a FXAA pass, instead of SMAA, is correctly antialiased and the result is clearly different than with no antialiasing. 

So I really don't know if it works as designed.

**Comment by bhouston** [comment]
I do not have time to analyse the code but I remember SMAA working when it was originally contributed.  It is more computationally intensive that FXAA and thus it is expected to generally produces better results than FXAA.  I remember that it did at one time.  Try cheking out the version of threeJS when SMAA was contributed and comparing it to now.  I suspect somehow it broke / bit rotted: https://en.wikipedia.org/wiki/Software_rot

**Comment by robertoranon** [comment]
Thanks for the hint.

I just did that and slightly modified the SMAA example of that commit such that:
- the wireframe box is added (there was just the textured one at that time)
- added a switch so that one can toggle between SMAA, and no antialiasing
I don't see any difference with the latest 88dev.  I attach the modified example, so anyone can check on their machine.

In my machine, what I do notice is that SMAA is quite ok when the cubes are rotating, much less so if they are still - I've added a toggle also to check that.


[webgl_postprocessing_smaa.html.zip](https://github.com/mrdoob/three.js/files/1296134/webgl_postprocessing_smaa.html.zip)

**Comment by bhouston** [comment]
When I run SMAA on my laptop (GTX 1050) I get these results:

image

When emulating Nexus 6P (DPR of 3.5) I get this:

image

Looks like it works for me on both the lines (except the vertical ones) as well as on the cube.  So I am going to say that it generally is working.

**Comment by robertoranon** [comment]
From your images, I'd say it works well for the GTX 1050, much less for the Nexus emulation, although the second screenshot has a near-vertical line that the first does not present.
What I see is more similar to the Nexus emulation, so it could be that the shader does not play with my AMD card as well as with your NVIDIA. 
Do you experience the same problem I described above if you resize the window?

**Comment by bhouston** [comment]
The card is the same for both.  The only different is the DPR.  I suspect the issue is DPR issues in the sizing of some of the buffers.

**Comment by robertoranon** [comment]
Yes, that is the cause. I suspect that the author of the example really intended to write

`var newWidth = Math.floor( width * pixelRatio ) || 1; `
`var newHeight = Math.floor( height * pixelRatio ) || 1; `
`composer.setSize( newWidth, newHeight );`

so that the offscreen buffers are the same exact resolution as the browser window.

**Comment by bhouston** [comment]
@robertoranon can you make a PR with that fix?

**Comment by robertoranon** [comment]
Yes, sure.

**Comment by robertoranon** [comment]
Done: #12187

**Pull request merged**
