### PR TITLE
Example for using ESLint to help enforce your style rules

### PR DESCRIPTION
**Pull request by greggman**
I just got done setting this up for one of my projects and I thought I'd show you how to set it up for yours if you're interested. I'm not expecting you to pull this request (you can if you want) but rather if you don't like it as is you can reference it.

So, if you get this branch, cd to the root folder and type

```
npm install
sudo npm install grunt-cli -g   // assuming you don't have grunt installed already
```

then you can now do

```
grunt eslint
```

and it checks many or most of your style rules. See `utils/build/eslint/eslint.json` that most of the rules are off right now because the code is breaking them all over the place :P Ideally if you add this to the official three.js repo we could turn on one rule, fix all the warnings, then make a pull request and repeat until its all one style. 

It's currently only checking the `src` folder. Ideally we'd turn it on for the `examples` and `test` folders as well. One thing I need to look into is how easy it would be it lint inline html scripts for the examples folder but hey, one step at a time.

So ... first that makes it easy to manually check if the code mostly matches your style guide but...
## travis-ci

if you setup a free account on travis-ci.org and turn it on
for the three.js repo it will lint any pull request automatically 
and have the results directly in the pull request on github.

I turned it on on my copy of three.js repo. 
[You can see it ran here](https://travis-ci.org/greggman/three.js)
## git integration

You can also setup a git pre-commit script to run "grunt eslint" before
committing. That's a local only thing meaning it won't propagate to other
users but it might be useful for yourself if you want to make sure you don't
commit something that breaks your own rules
## custom rules

[ESLint](http://eslint.org) allows custom rules. The easiest way to make a custom rule is to copy one of the built in rules. So for example

```
cp node_modules/eslint/lib/rules/brace-style.js utils/build/eslint/rules/three-brace-style.js
```

Now there's a rule called `three-brace-style`. You could modify it so it enforced a blank line after `{` and before `}`
## overriding rules

Sometimes you need to override a rule for special code. You can do that with a comment in the code. For example if you wanted to allow an unused var you could do this

```
/*eslint no-unused-vars: 0*/
```
## where to put these files

I thought I should put all of these files in `utils/eslint` or `utils/build/eslint`. The advantage to the latter is that you already have a `package.json` file there that I'm guessing you use. The reason I put a few files in the root though is because that way they work with travis-ci without much work. If you move them somewhere else I suspect there's a bunch of work to do to get travis-ci to handle that case. Of course it's up to you.

### CODE REVIEW

**Comment by greggman** [comment]
If you're curious I made [a breaking pull request to my own repo here](https://github.com/greggman/three.js/pull/6) and you can see down the page it shows it failed the lint step.

**Comment by mrdoob** [comment]
I like the idea of having this on utils but I'm not sure about travis. I don't really want to be too imposing about the code style when people submit PR. Better for them to focus on the feature or bugfix. I can always fix the code style after. If I have a tool that does that then even better :D!

**Comment by greggman** [comment]
Yea, a tool to reformat would be good too. I see putting it on travis as a way to gently tell them there's a style guide. That way I don't have tell them. They'll see it when they provide the pull request so it's not me imposing it :P

**Comment by mrdoob** [comment]
No no. I didn't mean you were imposing it. I meant "the system" would be imposing it.

**Comment by greggman** [comment]
Yea I get that. I just find having the system imposing it removes most issues. I mean why even have a style guide if you really don't care? Once all the code fits the guide an automated system is just a gentle reminder to keep the code in the style you want. Someone uploads a patch, they automatically get told a few minor issues, they fix them, problem solved.  Or, if you don't actually care, then just remove the style guide

**Comment by greggman** [comment]
I should add, even if you don't want to enforce the style turning on travis-ci eslinting will still catch real errors. Just turn off all the style rules but keep the rules that check for common errors and issues.

**Comment by zz85** [comment]
@greggman i'm sure you've seen the node-jscs approach to code formatting for mrdoob style #4802 and http://zz85.github.io/mrdoobapproves/

integrating Travis-ci was also something I was thinking about. how do you find eslint for code formatting / code style checking over jscs? My impression of eslint would be enforcing good coding patterns more than code style...

**Comment by greggman** [comment]
eslint is plugin based, that lets me easily add my own rules for my style.

**Comment by mrdoob** [comment]
> But you might care about

>    if ( a == b ) 

>vs

>    if ( a === b )

Indeed! Travis would be great for this. Can it also check for ```if ( !value )```? ;)

**Comment by greggman** [comment]
I'm confused. Isn't `if ( !value )` valid JavaScript or did you just mean you want the space in there as in `if ( ! value )`  Or rather what would you rather have than `if ( ! value )`?  Writing the rule to check it is easy.

**Comment by mrdoob** [comment]
I meant suggesting replacing

```javascript
if ( !value )
```

with

```javascript
if ( value === undefined )
```

or 

```javascript
if ( value === null )
```

or

```javascript
if ( value === false )
```

or whatever the code is supposed to be actually checking.

**Comment by greggman** [comment]
so I wrote a check. Here's what it found

**ignore the error message** just look at the line numbers and see if that's what you wanted it to find.

```
src/core/Geometry.js
  311:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  321:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  325:9  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  348:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/FontUtils.js
  125:7  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/core/Curve.js
   65:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
   83:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  110:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/core/CurvePath.js
   41:5  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  250:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  272:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/core/Path.js
  184:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  359:9  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  397:9  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  625:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  658:7  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/core/Shape.js
  207:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  212:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  317:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  332:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  408:11  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/geometries/ExtrudeGeometry.js
  114:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  177:7  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  376:7  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  406:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  458:9  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/extras/objects/MorphBlendMesh.js
   81:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
   88:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  248:7  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/loaders/BinaryTextureLoader.js
  31:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/math/Spline.js
  87:7  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/objects/MorphAnimMesh.js
  59:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  75:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  82:8  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  94:6  error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/renderers/WebGLRenderer.js
  1547:7   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  2045:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  3528:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  3573:10  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  3793:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  3801:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  3822:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  4361:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  4801:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5129:10  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5171:11  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5262:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5272:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5293:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5315:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5347:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5838:9   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  5881:10  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  6141:10  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  6380:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast

src/renderers/webgl/plugins/ShadowMapPlugin.js
  102:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  110:10  error  Redundant negation in an if statement condition  no-bang-boolean-cast
  155:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast
  174:8   error  Redundant negation in an if statement condition  no-bang-boolean-cast

```

**Comment by mrdoob** [comment]
Yep! This is great!
Wouldn't mind adopting travis just so these things stop coming O:)

**Comment by greggman** [comment]
So I pushed a version with that check checked in.

**Comment by greggman** [comment]
I'm not sure if you want this or not. Since JavaScript is typeless it basically can't know if you have a boolean or not. So for example this will fail

     if ( !isClockwise() ) 

That will have to be

     if ( isClockwise() === false )

If that's what you want then ok. This seems like it will work. It just seem common to negate a boolean value.

Basically you edit `eslint.json` and turn on/off the rules you want enforced. 0 = ignore, 1 = warn, 2 = error so for example

    "no-mixed-spaces-and-tabs": 2,

means mixed spaces and tabs are an error.  Some rules have options in which case the format is
    
    "no-mixed-spaces-and-tabs":  [2, option1, option2, ...],

I can turn them all off except `no-bang-boolean-cast`. 

Otherwise just sign up for travis-ci and in your profile turn on checking for three.js and it should start checking. You'd probably want to fix (or have me fix) all those errors for `if ( !variable )` first

**Pull request closed without merging**
