### PR TITLE
Textures support for ObjectLoader. issue #4967

### PR DESCRIPTION
**Pull request by denzp**
Hi! @mrdoob could you review pr?

### CODE REVIEW

**Comment by denzp** [comment]
Hi @mrdoob! Any news on this? :)

**Comment by mese79** [comment]
Hi
This is a useful loader for new exporter.
I've made some changes to make default texturePath:
```
load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

		if (scope.texturePath == '') {
			scope.texturePath = url.substring(0, url.lastIndexOf('/') + 1);
		}

		var loader = new THREE.XHRLoader( scope.manager );
		loader.setCrossOrigin( this.crossOrigin );
		loader.load( url, function ( text ) {

			scope.parse( JSON.parse( text ), onLoad );

		}
```
So there is no need to put your texture in the root or use setTexturePath function.

**Comment by mrdoob** [comment]
Lets do this! :+1:

**Comment by mrdoob** [comment]
Thanks! ^^

**Pull request merged**
