### PR TITLE
Compute lightprobe from a CubeRenderTarget

### PR DESCRIPTION
**Pull request by nipmarsh**
Replaces #17514.

### CODE REVIEW

**Comment by WestLangley** [comment]
@nipmarsh Did you test this PR before submitting it?

**Comment by nipmarsh** [comment]
> @nipmarsh Did you test this PR before submitting it?

Not really as i took the files from my previous PR... the example was broken and is now fixed

**Comment by Mugen87** [comment]
Live link for testing:

http://raw.githack.com/nipmarsh/three.js/lightprobe_cubecamera/examples/webgl_lightprobe_cubecamera.html

It seems the example produces a lot of warnings of type:

> WARNING: LightProbeGenerator convertColorToLinear() encountered an unsupported encoding.

With opened dev console, it takes many seconds until example is displayed because of those massive logging.

**Comment by nipmarsh** [comment]
> Live link for testing:
> 
> http://raw.githack.com/nipmarsh/three.js/lightprobe_cubecamera/examples/webgl_lightprobe_cubecamera.html
> 
> It seems the example produces a lot of warnings of type:
> 
> > WARNING: LightProbeGenerator convertColorToLinear() encountered an unsupported encoding.
> 
> With opened dev console, it takes many seconds until example is displayed because of those massive logging.

Should be better now

**Comment by WestLangley** [comment]
>@nipmarsh Did you test this PR before submitting it?
>>Not really...

Please don't do that again. You waste my time and the time of other maintainers.

**Comment by WestLangley** [comment]
Please use the `pisa` environment map in your example.

---


I tried, and this is the result:

Screen Shot 2019-10-23 at 11 55 09 AM

I expected something more like the the result from https://threejs.org/examples/webgl_lightprobe.html:

Screen Shot 2019-10-23 at 11 54 46 AM

**Comment by WestLangley** [comment]
That looks more like it! :-)

@mrdoob I think this can be merged if you are happy with the new example.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
