### PR TITLE
Examples: Clean up.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #21825

**Description**

Minor linter fixes.

### CODE REVIEW

**Comment by Mugen87** [comment]
@zalo The example logs in the browser console this warning:

> [.WebGL-0x7f9887061a00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

Do you mind having a look?

**Review by zalo — CHANGES_REQUESTED** [review]
Apologies for the delay; it looks like this is caused by the portal rendering itself to its own render texture.

The fix is simple at [line 198:](https://github.com/mrdoob/three.js/blob/7e7c29560294a8dd5840305bc920329afd400643/examples/webgl_portal.html#L198)
```javascript
renderer.render( scene, portalCamera );
```
should be something similar to:
```javascript
thisPortalMesh.visible = false; // hide this portal from its own rendering
renderer.render( scene, portalCamera );
thisPortalMesh.visible = true; // re-enable this portal's visibility for general rendering
```

**Comment by Mugen87** [comment]
Yep, that fixed the issue! Thx.

**Review by zalo — APPROVED** [review]
😁 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
