### PR TITLE
fixed a bug

### PR DESCRIPTION
**Pull request by hujiulong**
if TouchEvent is not defined in the browser,an exception will be thrown,cause else branch statements not to be executed.

### CODE REVIEW

**Comment by mrdoob** [comment]
How about just checking if `window[ 'TouchEvent' ] !== undefined`?

**Comment by hujiulong** [comment]
yes, you're right.

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
