### PR TITLE
node material r5 + mirror nodes example

### PR DESCRIPTION
**Pull request by sunag**
- Precision fix PB'Shader and GL_EXT_shader_texture_lod
- THREE.Matrix4Node
- Better node optimization at THREE.TempNode 
- THREE.MirrorNode + webgl_mirror_nodes.html example
- Fix PB'Shaders to Three.JS r76 and r77

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice! Thanks!

**Comment by mrdoob** [comment]
Seems like the all the shader that `StandardNodeMaterial` produces has some uninitialised vars?

screen shot 2016-08-22 at 10 21 29

screen shot 2016-08-22 at 10 22 08

**Comment by sunag** [comment]
> Seems like the all the shader that StandardNodeMaterial produces has some uninitialised vars?

Hmm, this is in `dev` branch? I tested in `r80` work done but with some warns.

teapot

**Comment by mrdoob** [comment]
Yep, `dev` and `r80`. Those issues tend to appear on my graphics card when glsl variables haven't been initialised.

**Pull request merged**
