### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by WestLangley**
Simple, uniform lighting.

### CODE REVIEW

**Comment by mrdoob** [comment]
Light that comes from the camera reminds me to scary movies like "The Blair Witch Project" where the only thing the viewer sees us what the spotlight is pointing at... 🤔

Static directional light gives more of a studio shot feel I think.

**Comment by WestLangley** [comment]
Do you approve of adding a directional light to the camera -- the current implementation? I certainly don't.

>Static directional light gives more of a studio shot feel I think.

That is fine for a static camera, but it produces an unattractive dark side when using controls.

And adding an ambient light is not acceptable because it is too flat.

Static directional plus a hemisphere light?

**Comment by mrdoob** [comment]
> Static directional plus a hemisphere light?

Yes, that's what I tend to do.

**Comment by WestLangley** [comment]
Changed to static directional light plus hemisphere light.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
