### PR TITLE
Fixed branding in docs

### PR DESCRIPTION
**Pull request by looeee**
Changed occurrences of 'Three' and 'Three.js' to 'three.js' throughout the docs per @WestLangley's request here #10395

I left it as 'Three.js' at the start of sentences though, as the dot makes it confusing not too:

> In addition to the geometry, we need a material to color it. three.js comes with several materials, but we'll stick to the <strong>MeshBasicMaterial</strong> for now.

Better:
>> In addition to the geometry, we need a material to color it. Three.js comes with several materials, but we'll stick to the <strong>MeshBasicMaterial</strong> for now.

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like there are conflicts. Do you mind pulling from `dev`?

**Comment by WestLangley** [comment]
>I left it as 'Three.js' at the start of sentences though, as the dot makes it confusing not too:

If that bothers you, then avoid putting three.js as the first word. (e.g., "The three.js library...") It should be lower case.

**Comment by mrdoob** [comment]
Actually, I personally don't mind that it behaves like a normal word. So "Three.js" and "three.js" sound good. What sometimes bothers me is when people get creative (THREEjs, threeJS, etc) 😁

**Comment by looeee** [comment]
Haha damn! Sorry, trying out a new mergetool and it totally made a mess of this.  I'll just close this and create a new PR.

**Comment by looeee** [comment]
@WestLangley no, doesn't bother me at all 😄 Just trying to make the docs as clear as possible. Thanks for bringing up the issue of branding, it's a point I had meant to raise a while back but it slipped my mind. 

@mrdoob I'll let you guys make a decision before going any further with this.

**Pull request closed without merging**
