### PR TITLE
Fixed incorrect shader processing in glTF loader (#9890)

### PR DESCRIPTION
**Pull request by proteamer**

### CODE REVIEW

**Comment by mrdoob** [comment]
@richtr looks good?

**Comment by richtr** [comment]
I think the proposed regex in this PR would also match things like e.g. `a_normal+` or `a_normal1` or `a_normal ` too. Similarly things like `+a_normal` and `+a_normal+` match too.

I think we should use https://github.com/mrdoob/three.js/pull/9897. I didn't see this PR before creating that PR. Didn't mean to step on any toes around here! :)

**Comment by proteamer** [comment]
Hi @richtr! Thanks for the fix it looks good.

I'v done a few [tests](https://jsbin.com/lewoqo/edit?js,console) for these regex and made sure that both regex works pretty similar.

+1 for #9897 your regex looks more elegant.

**Comment by richtr** [comment]
Good point @proteamer. It seems I didn't replace `\\w` with `\w` when I tested your regex fixes manually so the results came out incorrectly :/

**Pull request closed without merging**
