### PR TITLE
convert to `this.STATE` for overriding

### PR DESCRIPTION
**Pull request by kellyselden**
We would like to use this file from the npm package, but we are currently maintaining a copy because we need to change `STATE` to remap key bindings. This change would allow us to delete our copy and override `STATE`.

### CODE REVIEW

**Comment by Mugen87** [comment]
>...because we need to change STATE to remap key bindings.

Couldn't you just edit `this.keys`?

https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/examples/js/controls/TrackballControls.js#L36

**Comment by karimbeyrouti** [comment]
@Mugen87 hello :-) We are changing the default mouse behaviour to pan in some circumstances / rotate in others. Key bindings are not going to useful for that. 

our code does the following:

```
  this.setupForPan = function() {
    _this.STATE = { NONE: - 1, ROTATE: 2, ZOOM: 1, PAN: 0, TOUCH_ROTATE: 3, TOUCH_ZOOM_PAN: 4 };
  };

  this.setupForRotation = function() {
    _this.STATE = { NONE: - 1, ROTATE: 0, ZOOM: 1, PAN: 2, TOUCH_ROTATE: 3, TOUCH_ZOOM_PAN: 4 };
  };
```

Which sets the default click and drag to 'pan' - or 'rotate'.

**Comment by mrdoob** [comment]
I would rather add a `setStateConstants()` method. But still seems hacky.

**Comment by WestLangley** [comment]
I do not think the internal `STATE` should be exposed.

`TrackballControls` is part of the examples. You are free to modify your copy to suit your needs.

**Pull request closed without merging**
