### PR TITLE
SpotLight: rectangular spot light shape

### PR DESCRIPTION
**Pull request by nipmarsh**
This PR add the possibility to change the spot light shape from Circle to Rectangular

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, I don't think it's a good idea to support different shapes in a hard coded way. #13057 seems to be more promising.

**Comment by nipmarsh** [comment]
> Um, I don't think it's a good idea to support different shapes in a hard coded way. #13057 seems to be more promising.

I saw it but it is completly inactive for a while now... Maybe i can create a new type of light call RectangularSpotLight?

**Comment by Mugen87** [comment]
What if then someone wants a TriangularSpotLight^^? It seems this approach does not scale very well...

**Comment by nipmarsh** [comment]
> What if then someone wants a TriangularSpotLight^^? It seems this approach does not scale very well...

I've just implemented what was suggested by @mrdoob in this comment https://github.com/mrdoob/three.js/pull/13057#issuecomment-359005867

Regarding this comment, this PR seems to be a good idea

**Comment by Mugen87** [comment]
I think your approach is too limited. Using a texture in the sense of [Cookies](https://docs.unity3d.com/Manual/Cookies.html) is much more flexibel, IMO. Anyway, this needs to be discussed in #13057.

**Comment by WestLangley** [comment]
I think that cookies are the best way to model the "barn doors" on studio lights. I would prefer to go the cookie route.

**Comment by Mugen87** [comment]
@nipmarsh Thanks for your work on this but it's better to focus on #14621 instead.

**Pull request closed without merging**
