### PR TITLE
Optimization of matrixWorldNeedsUpdate (selective scene traversal)

### PR DESCRIPTION
**Pull request by OndrejSpanel**
In this PR I will experiment with optimizations described in #21387 - it will be marked as draft until I think it is ready to be considered for merging.

Current commit is just a starting point, encapsulating `matrixWorldNeedsUpdate` in a property.

I would prefer defining the property at the prototype level, I tried that in ae930e8bbc0cc483e1584f8a06afa630daab75b5, but units tests were failing then (JSON read / write tests were reporting missing and unexpected `matrixWorldNeedsUpdate` - see https://github.com/OndrejSpanel/three.js/runs/2021349228?check_suite_focus=true

### CODE REVIEW

**Comment by OndrejSpanel** [comment]
I think I have implemented the selective children traversal in the commit above.

The sample needs to be changed a bit to benefit from the optimization, because there is one thing happening I did not think of:  the camera is updating in each frame, therefore the root scene node is marked for update as well. This means there needs to be an intermediate object (`Group`) introduced, because any objects placed directly in the scene root will be always traversed.

I think the intermediate group is acceptable and in my opinion this better represents real life scenes.

When checking the timing using the performance view, I can see the `updateMatrixWorld` is no longer measurable. I am unable would like to demonstrate overall CPU time improvements as well, but when I try to use the numbers shown by the sample itself running in the browser, I get varying values even for the same configuration, which makes any comparison not meaningful.

Do you have any accepted workflow to measure impact of optimizations like this one?

**Comment by OndrejSpanel** [comment]
I am afraid I need some advice, because I am hitting a strange obstacle . While I have achieved the goal of eliminating `updateMatrixWorld` from the profile in the example, repeated measurements on both Chrome and Firefox show the overall time needed for rendering has increased significantly (like from 50 to 80ms). I see the increase straight after introduction of the property, with no other changes. Now the strange thing is that when profiling the increase can be mostly seen in function `projectObject` and object rendering, which do not seem to access `matrixWorldNeedsUpdate` at all. It seems the fact I have introduced the property has causes something wrong with the `Object3D` representation.

I have read something about fast and slow properties in JS (https://v8.dev/blog/fast-properties), but I am not sure if and how this could be applied to the situation I see.

@mrdoob @WestLangley @Mugen87 Did you ever see anything like this, or do you have some advice how to do this better to or learn more what exactly is going on?

**Comment by LeviPesin** [comment]
Why did you close this PR?

**Comment by OndrejSpanel** [comment]
I think it auto-closed when I deleted the branch in my fork, when doing a cleanup in it (this PR was based on my dev branch). I have currently no intension to pursue this further.

**Pull request closed without merging**
