### PR TITLE
Shaderchunk: Add missing defaults

### PR DESCRIPTION
**Pull request by Itee**
This PR normalize the ShaderChunk usage in ShaderMaterial, and add missing default_vertex and default_fragment to it.

In case this "lib" should be splitted in the future (like utils liks), this could be fine to normalize it before any other fundamental changes.

### CODE REVIEW

**Comment by mrdoob** [comment]
Duplicate of #15724

**Comment by mrdoob** [comment]
Still thinking we shouldn't do this. https://github.com/mrdoob/three.js/pull/15724#issuecomment-461217595

**Comment by Itee** [comment]
I wasn't aware of #15724. (i miss the typescript, damn ! ^^)

And yes i clearly understand the "why" you did this, and why you won't. But to make easier parsing for batch/convert script this will be useful.

@mrdoob Did you plan to split/remove this file ? Or re-export all import statement like in Materials intermediary exporter file (I think this is the target, no ?) ? 

In case you go this way i could easily find/replace all ShaderChunk import by their real shader import and keep backward compatibility. Tell me and i will open an other PR for this purpose.

**Comment by mrdoob** [comment]
> In case you go this way i could easily find/replace all ShaderChunk import by their real shader import and keep backward compatibility. 

That'll be good to see yes. Won't be easy to remove `ShaderChunk` because of how `WebGLRenderer` uses it, but the less we use it across the library the better.

**Comment by Itee** [comment]
Ok i will give it a try and close this one.

**Pull request closed without merging**
