### PR TITLE
Make OrbitControls compatible with CombinedCamera.

### PR DESCRIPTION
**Pull request by achetwood**
Changes to allow OrbitControls to work correctly in conjunction with CombinedCamera.

### CODE REVIEW

**Comment by WestLangley** [comment]
I'm not sure about using `OrbitControls` with `CombinedCamera`... I believe there will be undesirable side effects that you will have to handle.

For example, zooming out with the mouse when using orthographic mode changes the `zoom` factor, which leads to arbitrarily large and invalid `fov` when switching to perspective mode. There may be additional issues. This would require an example and extensive testing.

Perhaps it would be easier to avoid `CombinedCamera` altogether, and have two cameras, each with its own `OrbitControls`. I have not tried it, however.

**Comment by achetwood** [comment]
That is true and in my specific use case, I already was handling that issue. I have created an example with the necessary camera.zoom changes when switching from orthographic to perspective. 

There maybe other issues, although there haven't been any that I have noticed in our full scenario where we have used this for about two months now. Obviously we have always been specifically setting zoom levels for perspective/orthographic modes.

We have tried using separate Otho/Pers cameras, but this proved awkward and the CombinedCamera is, in our use case, the better solution. 
A link to the simple example as well as our actual application is below, note the actual application is changing quite regularly and may not work

http://achetwood.github.io/ThreeJSExamples/CombinedCameraTest.html
http://www.stairbox.com/stairs/stairbuilderoffice3DDev.html

**Comment by achetwood** [comment]
Might be a better solution to save the previous zoom factor when a change from perspective to orthographic is made so when it changes back we can restore the previous zoom level and do this from within CombinedCamera itself rather than setting it implicitly on the application side.

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6734

**Pull request closed without merging**
