### PR TITLE
Use Object.assign for constant definitions.

### PR DESCRIPTION
**Pull request by tschw**
See #8824

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
As far as I understand, this pattern:

```js
THREE.RingGeometry.prototype=Object.create(THREE.Geometry.prototype);
THREE.RingGeometry.prototype.constructor=THREE.RingGeometry;
```

Can now be just this...

```js
Object.assign( THREE.RingGeometry.prototype, THREE.Geometry.prototype );
```

Right?

**Comment by tschw** [comment]
@mrdoob 
> `Object.assign( THREE.RingGeometry.prototype, THREE.Geometry.prototype );`

I guess that might be oversimplified: Once we ask `aRingGeometry instanceof THREE.Geometry` we'll get `false` since 
```javascript
THREE.RingGeometry.prototype.constructor === THREE.RingGeometry &&
THREE.RingGeometry.prototype.prototype.constructor  === Object
```

and not

```javascript
THREE.RingGeometry.prototype.constructor === THREE.RingGeometry &&
THREE.RingGeometry.prototype.prototype.constructor === THREE.Geometry &&
THREE.RingGeometry.prototype.prototype.prototype.constructor  === Object
```

.

So it's

```javascript
THREE.RingGeometry.prototype =
        Object.assign( Object.create( THREE.Geometry.prototype ), {

    constructor: THREE.RingGeometry, // else it's THREE.Geometry

    /* ... */

} );
```

. Unfortunately

```javascript
Object.assign( THREE.RingGeometry.prototype, {

    prototype: THREE.Geometry.prototype,  // !!! WON'T WORK !!! 

    // ...

} );
```

, can't work because prototype is not an enumerable property and the prototype chain can't be changed this way. So this won't work either:
```javascript
Object.assign( THREE.RingGeometry.prototype, {

    // ...

} ).prototype = THREE.Geometry.prototype;
// resetting .prototype won't establish a prototype chain, it requires construction
```
.

To *can* get around `Object.create` like done [here](https://github.com/google/closure-library/blob/master/closure/goog/base.js#L2233-L2239), however, I have no clue *why* they actually do it.

**Comment by mrdoob** [comment]
I see I see. As usual, thanks a ton for the explanations!

**Comment by tschw** [comment]
I had to correct above post; `obj.prototype` isn't meaningful. It's either `ctor.prototype` or `obj.__proto__`.

**Pull request merged**
