### PR TITLE
InstancedBufferGeometry.maxInstancedCount => .instanceCount

### LINKED ISSUE #18990: InstancedBufferGeometry: maxInstancedCount property
The `maxInstancedCount` property is poorly-named, IMO.

I suggest that the property be renamed to `.instanceDrawCount`, which specifies the number of instances to render. That is how the property is being used.

Also, the renderer should silently ensure the draw count does not exceed the maximum possible, based on the buffer size -- as we currently do with `BufferGeometry.drawRange`.

- [ x ] Dev
- [  x ] r115

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #18990.

I'll update the migration docs if this is merged.

### CODE REVIEW

**Comment by Mugen87** [comment]
Don't you think it's better to name the property just `count` so it's aligned to `InstancedMesh`?

**Comment by WestLangley** [comment]
@Mugen87 OK, if you want.

But now that I think about it, I am wondering if this PR is even a good idea...

Having a `count` property would lead users to think they have to set it -- and they don't. It works similar to `drawRange.count`, which also defaults to `Infinity`. The renderer will not try to render more instances than the buffer will allow. The users do not have to set `count` at all.

Maybe leave the API the same?

**Comment by Mugen87** [comment]
I think the problem is that you want to align the API towards `drawRange` whereas I want to align it to `InstancedMesh` :)

When creating an instance of `InstancedMesh`, `count` is a mandatory parameter. If not assigned, the respective property will be `undefined`. I think it would be great if the instancing API behaves similar. However, I also understand the idea to make it consistent to how `drawRange` works.

@mrdoob What is your preference here? 😊

**Comment by WestLangley** [comment]
With `InstancedMesh`, `count` is required because the constructor allocates the `instanceMatrix` buffer.

With `InstancedBufferGeometry`, the user allocates the buffers, because there can be any number of them. `maxInstancedCount`, which is optional,  serves the same purpose as `drawRange` in that case.

**Comment by Mugen87** [comment]
Yes, that's important to highlight.

**Comment by WestLangley** [comment]
I think this PR is good-to-go.

**Comment by WestLangley** [comment]
@mrdoob tl;dr

Currently, `.maxInstancedCount` is used to specify the number of instances to render, and there is no check preventing the renderer from trying to render more instances than the buffer will allow.

This PR renames the property to `.instanceCount`, and also adds a check preventing the mentioned rendering error -- just as we do with `.drawRange`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
