### PR TITLE
Additional RingGeometry Fix

### PR DESCRIPTION
**Pull request by ChainsawXIV**
This change removes the extra triangles connecting the ends of a partial RingGeometry, and sets the minimum number of concentric bands to one, like merpnderp's #4878 does. However, it also:
- Eliminates the redundant vertices created when the ring is complete, and welds the seem
- Prevents values of thetaLength greater than 2 \* PI which would create overlapping geo
- Removes some redundant calculation form the process of RingGeometry face generation

### CODE REVIEW

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#4899

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#4899

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#4899

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#4899

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#4899

**Comment by mrdoob** [comment]
@ChainsawXIV Do you mind targeting the `dev` branch instead?

**Pull request closed without merging**
