### PR TITLE
Package.json: add `serve` and `serve-ssl` script

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #XXXX

**Description**

Background: We can easily and quickly view examples of documents, etc. Do not go far to package and compile logic.

### CODE REVIEW

**Comment by Mugen87** [comment]
TBH, the scripts section is already large and I don't see the reasons for adding the suggested ones.

Why is it an issue to use `dev` scripts instead? Does the additional logic slow down your system?

**Comment by linbingquan** [comment]
> TBH, the scripts section is already large and I don't see enough arguments for adding the suggested ones.
> 
> Why is it an issue to use `dev` scripts instead? Does the additional logic slow down your system?

TBH, I found the CMD `npx servez` I needed yesterday. Now that this PR is closed, it's OK for me.

Should be my laptop performance is average, feel slow...

```shell
> npm run dev

> three@0.169.0 dev
[ROLLUP] created build/three.module.js in 2.1s
[ROLLUP] created build/three.webgpu.js in 2.5s
[ROLLUP] created build/three.webgpu.nodes.js in 2.1s
[ROLLUP] created build/three.module.min.js in 4.9s
[ROLLUP] created build/three.webgpu.min.js in 9s
[ROLLUP] created build/three.webgpu.nodes.min.js in 8s
[ROLLUP] created build/three.cjs in 1.6s
```

**Comment by Mugen87** [comment]
AFAICS, the build times should cause issues if you just want to view examples or the documentation. They do not "block" the local web server process.

**Comment by linbingquan** [comment]
> AFAICS, the build times should not cause issues if you just want to view examples or the documentation. They do not "block" the local web server process.

I mostly look at documents and examples. Do not want to run the package build logic during this time. Users can run the corresponding script according to their own needs.

**Comment by Mugen87** [comment]
Sorry, but if you just want to host than install a web server globally and start it in your three.js directory. I'm not in favor of special requests in general and I think avoiding them whenever possible helps to get things more straighforward.

**Pull request closed without merging**
