### PR TITLE
Add documentation of computeMorphedBufferGeometry

### PR DESCRIPTION
**Pull request by SntsDev**
Missing documentation for #21064

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by SntsDev** [comment]
I renamed `computeMorphedBufferGeometry` to `computeMorphedAttributes`, as suggested by @WestLangley and @Mugen87. 

@Mugen87: As the input is an Object3D (because we need the material) it's important to check whether it uses a BufferGeometry. To simplify things, I added `else`s  to the checks of the user input.

**Comment by Mugen87** [comment]
I still think it's better to remove the checks. Also consider to change type to `Mesh | Line | Points` instead of using `Object3D`.

**Comment by SntsDev** [comment]
> I still think it's better to remove at least the first check. Also consider to change the parameter type to `Mesh | Line | Points` instead of using `Object3D`. These classes have a geometry.

Done!

**Comment by Mugen87** [comment]
The check `if ( ! object.geometry ) {` can also be removed. `Mesh`, `Line` and `Points` _always_ have a geometry. Even if you provide no argument in the constructor, they have a default geometry.

**Comment by SntsDev** [comment]
> The check `if ( ! object.geometry ) {` can also be removed. `Mesh`, `Line` and `Points` _always_ have a geometry. Even if you provide no argument in the constructor, they have a default geometry.

Done!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
