### PR TITLE
Added support for instancing with Points

### PR DESCRIPTION
**Pull request by WestLangley**
/ping @benaadams

### CODE REVIEW

**Comment by benaadams** [comment]
Looks like it will work; though if you used position+offset for instancing that would be heavier than just using position non-instanced as the gpu is processing double the number of attributes.

There is a three choice trade off between: 
```lots of objects``` vs ```merged multi object``` vs ```instancing``` 
which is 
```drawcalls``` vs ```memory speed``` vs ```vertex processing```

For small poly objects (points definitely being this) then repetition is a low percentage of the overall data (for example square quads/billboards); so updating 4 positions for each corner is better than updating 1 offset with the gpu then processing 2 attributes per vertex rather than one.

When you get to about 100 vertexes per object ; that becomes a lot of overhead of data to be pumping around on the memory bus if you are updating all the positions for each object; so the trade off goes the other way, in that its now better for the gpu to process 2 vertexes per object and only update one offset per object, then it is to update 100+ positions per object.

The ideal situation, if it actually worked, would be to have lots of drawcalls; since the matrix cost is probably still in the instancing for the camera, except they are terribly slow; which is what DirectX12 and Vulkan are all about, so maybe in WebGL3 :P

**Comment by WestLangley** [comment]
> Looks like it will work; though if you used position+offset for instancing that would be heavier than just using position non-instanced as the gpu is processing double the number of attributes.

Yes, it does work. I am computing the offsets in the GPU, and the position is just a single point at the origin.

Consequently, there is no load on the CPU, and `needsUpdate` is never called. So there is that benefit. All the computation is on the GPU.

**Comment by benaadams** [comment]
Sounds like you don't need position though or to do any calcs with it since its always zero?

**Comment by WestLangley** [comment]
I get the following error if I leave position out.

    glDrawArraysIntancedANGLE: attempt to draw with all attributes having non-zero divisors

**Comment by benaadams** [comment]
I mean you don't need to use instancing at all; if you are for example just using a point index you could set position in the shader (rawshader) to be: ```attribute float position;```

**Comment by benaadams** [comment]
Though the PR is technically correct; so good to merge :+1: 

Just pointing out might be better way to do it.

**Comment by WestLangley** [comment]
Here is what I am doing.

```glsl
uniform mat4 modelViewMatrix;
uniform mat4 projectionMatrix;

attribute vec3 position;
attribute float idx;
attribute vec3 color;

varying vec3 vColor;

uniform float time;

void main() {

	vColor = color;

	vec3 offset = vec3 (
		sin( idx * 3.0 ) * 10.0,
		cos( idx * 5.0 ) * 10.0 + sin( time + idx ) * 1.0,
		sin( idx * 2.0 ) * 10.0
	);

	vec4 mvPosition = modelViewMatrix * vec4( position + offset, 1.0 ); // position must be used or error thrown...

	gl_PointSize = 2.0 * ( 300.0 / length( mvPosition.xyz ) );

	gl_Position = projectionMatrix * mvPosition;

}
```

So I understand what you are suggesting, avoid instancing alltogether in this case?

**Comment by WestLangley** [comment]
> Though the PR is technically correct; so good to merge

Yay! I was thinking we could do the same for `THREE.Line` and `THREE.LineSegments`, but based on your comments, I am now wondering if it makes sense to add support for that...

**Comment by benaadams** [comment]
Could go non-instanced and just drop position; though not sure what three.js would think, so rename ```idx``` to ```position```
```glsl
uniform mat4 modelViewMatrix;
uniform mat4 projectionMatrix;

attribute float position;
attribute vec3 color;

varying vec3 vColor;

uniform float time;

void main() {

    vColor = color;

    vec3 offset = vec3 (
        sin( idx * 3.0 ) * 10.0,
        cos( idx * 5.0 ) * 10.0 + sin( time + idx ) * 1.0,
        sin( idx * 2.0 ) * 10.0
    );

    vec4 mvPosition = modelViewMatrix * vec4( position + offset, 1.0 ); 

    gl_PointSize = 2.0 * ( 300.0 / length( mvPosition.xyz ) );

    gl_Position = projectionMatrix * mvPosition;

}
```

**Comment by benaadams** [comment]
Might want to take out ``` * 1.0``` too ;-)

**Comment by WestLangley** [comment]
> Might want to take out * 1.0 too ;-)

hehe. I was in the middle of fiddling with it...

What do you think about `THREE.Line` support?

**Comment by benaadams** [comment]
Lines could be more interesting; if for example you wanted lots of parallel lines that were quite long would make sense to have a set of offsets to change per line (or even rotations) rather than updating several hundred points per line; or even use the index like your original example; to do a lookup up over texture or video. Api-wise it is simpler to do the instancing.

**Comment by mrdoob** [comment]
I think it would be great to have an example of non-instancing-based gpu particles btw.

And, yes, it's a good point, probably better to come up with a use case before implementing blindly.

**Comment by WestLangley** [comment]
The use case for `THREE.Points` originated from #7304.

Rather than updating the vertices of the point cloud in the CPU, and the pushing the coordinates to the GPU every frame, the identical calculations are performed on the GPU, instead.

That seems to be a pretty compelling use case to me.

**Comment by mrdoob** [comment]
> The use case for `THREE.Points` originated from #7304.

Added a instancing-less solution in that same thread.

**Comment by WestLangley** [comment]
> Added a instancing-less solution in that same thread.

We have parallel threads going on here... : - )   See my reply in #7304.

**Comment by mrdoob** [comment]
Solved #7304 😊
I'm just trying to avoid adding another code path when isn't really needed.

**Comment by WestLangley** [comment]
@mrdoob That's OK. Thank you for your alternative approach. : - )

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7316

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7316

**Pull request closed without merging**
