### PR TITLE
Refactor: Move CSS3D classes into the source

### PR DESCRIPTION
**Pull request by trusktr**
I'd like to `npm install three` and use the CSS3D stuff. I'm making "mixed mode" like in [this example](http://jsfiddle.net/trusktr/jc6j1wmf/).

### CODE REVIEW

**Comment by mrdoob** [comment]
Have you had a read at #9562?

**Comment by yomotsu** [comment]
Also my slide would be helpful.
https://speakerdeck.com/yomotsu/webgl-libs-for-webapp-frameworks
Here is a example code with webpack import-loader and export-loader.
https://www.dropbox.com/home/works/talk/2017-09-27_html5-conf/demos/demo1-webpack/src?preview=main.js

**Comment by donmccurdy** [comment]
Would prefer #9562; I don't think CSS3D is a general enough use case, and there are many things in examples I'd like do be able to install with npm :)

BTW A-Frame already does some [special requires](https://github.com/aframevr/aframe/blob/master/src/lib/three.js#L22-L25) to get files from examples in.

**Comment by trusktr** [comment]
Using things like imports-loader makes your code webpack-specific, then it won't work elsewhere.

It's better to stick to standards so that things work in all build systems, not just Webpack. (This is a good solution for Webpack users, but not for everyone).

**Comment by trusktr** [comment]
Babel can compile individual files to global namespaces (quicker than Webpack): https://babeljs.io/docs/plugins/transform-es2015-modules-umd/

It could be possible to add a build-globals step that can convert all module files into globals. Users could include specific script tags for anything they need.

**Comment by donmccurdy** [comment]
I don't think this is a choice between webpack-specific solutions and adding everything into `src/*`.

Will reply in more detail on #9562.

**Pull request closed without merging**
