### PR TITLE
Texture patch (texSubImage2D)

### PR DESCRIPTION
**Pull request by arcanis**
Happy new year ! :tada:
## Summary

This PR should make it possible for the users to dynamically "patch" their texture, more efficiently than if they had to create another one from scratch (thanks to `texSubImage2D`). The main use case is on texture maps, since it's now possible to easily "merge" textures together. A basic implementation is providen by the new `GridTexture` class.
## Related issues:
- https://github.com/mrdoob/three.js/issues/303
- https://github.com/mrdoob/three.js/issues/4155
- https://github.com/mrdoob/three.js/pull/4661
## New classes
- **TexturePatch**
  
  A TexturePatch is a subtexture that should be applied by a renderer on top of the original texture. It shouldn't be manually created by userland codes, since a texture will create its own TexturePatch instances via its `patchTexture` member function.
- **GridTexture**
  
  A GridTexture is an empty DataTexture splitted into similarly-sized pieces, and exposing a simple API to efficiently apply subtextures inside each of these pieces. Basically, it's a kind of texture atlas which only works on perfect grids.
- **GridTextureLocator**
  
  A GridTextureLocator is a pointer to a cell inside a GridTexture. It shouldn't be created by userland codes, since a GridTexture will create its own locators instances via its `getLocator` member function.
## Changed classes
- Each `Texture` now have an additionnal `patchVersion` field. It is used for the renderer to know which patch it should apply on top of its current internal representation of a texture. This version is increased at each new patch, but not when a patch is removed (because there is no way to efficiently remove a patch).
- Geometries (both Geometry's and BufferGeometry's instances) now have a `uvSystem` field (which defaults to `null`, so that it doesn't add too much memory overhead on current codebases), and a `switchUvSystem` utility. Such a feature wasn't useful until now, but since this PR adds the ability to implement texture maps, I feel like it's quite important to give the user a way to easily translate UVs from a point to another. This way, changing an atlas' selected texture doesn't require any boilerplate code, that would be quite common otherwise.
### Low-level API
- The user will first create a `Texture` object, and use it as before
- At any point, the user can call `texture.patchTexture(subTexture)` as parameter, with `subTexture` being another `Texture` instance. The call will return a TexturePatch instance, that will be used to locate the patch inside the original texture. It is safe to discard this return value altogether (it will eventually get garbage collected, at the same time as the texture).
- Should the user want to patch the original texture again, two cases may apply: either the new patch is covers an existing one (in which case it is best practice to call `patch.destroy()` on the previous patch), or it is not. Even if the user doesn't follow the good practice and doesn't destroy the previous patches as they are covered up, the code will still work as expected (but memory and possibly performances will grow).
- **Note:** Calling `patch.destroy()` will **not** remove the patch from the internal texture. It is best to only call this method if the patch will be made fully obsolete by another one that would cover it entirely.
### High-level API
- The user will create a `GridTexture` object
- When the user wants to add a texture into the grid, it will first use `getLocator(id)`, with `id` being a unique string accross the texture grid. This function will return a locator, which is a pointer to an unspecified reserved location on the texture grid. If a locator with this ID already exists, its reference counter will be increased, and it will be returned. Otherwise, a new locator will be returned. The return format is the following: `[locator, isCreated]`.
- If the `isCreated` flag is true, the user will then load the texture by any means necessary, then call `locator.draw(subTexture)`, passing it the texture as `subTexture`. Otherwise, there is nothing to do, since the texture is already being loaded from somewhere else, and will eventually be available.
- Once the texture is loaded, in order to update the geometry UV to match the texture location on the texture grid, the user will then call `geometry.switchUvSystem(locator.uvSystem)`.
- Should the user not need the texture picked from the atlas anymore, they have to call `locator.dispose()`. By doing this, they release their side of the locator. Once the locator has been disposed by everyone who required it, it becomes candidate to be garbage collected. However, as long as it is not effectively garbage collected (which happens when a user asks for a locator with a new id), it will be reused should someone ask for this locator id.
## Pros
- It works accross multiple renderers (because we store the patchs we need in the textures)
- Assuming that Three.js would implement a "restore after context loss" feature, it would work without adding anything else (again, because we store the patchs we need in the textures)
- The high-level API should cover most use cases
- The low-level API is still there, should someone want to implement a more complex use case (such as a loader for TexturePacker-generated atlas maps)
## Cons

There isn't any real cons to this API: no risk of backward compatibility issues, no significant additional overhead, ... The only thing that could be improved is the feature set (see below).
## PR Issues
- I mainly worked on the API, and as such this PR doesn't implement compressed textures support. I've never used them, so I don't feel like doing it. That being said, if you feel like supporting them is blocking, I can try to spend some time on it.
- On a related level, this PR doesn't implement any kind of mipmap support, because I don't really know how it works. I would be quite happy if someone else could tackle this (I guess implementing it would only require to add a few code paths inside `uploadTexturePatch`) but again, I can do it if you feel like it's blocking.
- I haven't really put huge thought in an example yet, and so the current one is kinda lame. I think I could do something better by using the Imgur API (something like a photo gallery, maybe?).

### CODE REVIEW

**Comment by makc** [comment]
@arcanis Just passing by, but thanks for texSubImage2D hint :)

@mrdoob Some kind of texture.patch (x, y, image) would be great, regardless of this PR fate (I mean, I do not see any way to do it in this PR either, it binds you to rectangular grid system).

**Comment by arcanis** [comment]
@makc Actually, both API are implemented : a high-level API (via `GridTexture`), that only work on perfect grid atlases and should cover most use cases, but also a low-level API (via `texture.patchTexture`), that can apply a subtexture of any size, at any offset (GridTexture is kind of an helper on top of this, since it be tedious to manage such patchs).

**Comment by arcanis** [comment]
Ping someone (@mrdoob) ? At least an aknowledgement ? :sweat_smile:

Note that this PR is still a WIP : I'm using it myself and I've spotted a bug, and a few names that should probably be reworded.

**Comment by titansoftime** [comment]
This is incredible, I have been wanting something like this since day one =]

**Comment by arcanis** [comment]
Rebased against dev.

**Comment by FreakTheMighty** [comment]
@arcanis I'm attempting to use patch to first load a low resolution spherical panorama onto a sphere, then patch it with higher resolutions tiles. I'm finding that this doesn't work. If I understand my issue correctly, the patch bases the x,y units on the first texture I apply which is smaller than total of the patches I will apply. As such, I end up patching out of bounds. That makes sense, but do you have any thoughts on a different way to approach this?

Here's my code

```javascript
loader.load(lowResUrl, function(texture) {
  
  var material = new MeshBasicMaterial( { map : texture, transparent: true } );
  
  self.roomSphere.material = material;
  
    for (var c = 0; c < 16; c++) {

      for (var r = 0; r < 16; r++) {

        var unit = [self.pad(r+1, 2), self.pad(c+1, 2)].join('_');

        var tile = url.replace('.JPG', '_' + unit + '.png');

        var patchTex = function ( tile, r, c) {
          return function(unitTexture) {
            self.roomSphere.material.map.patchTexture(unitTexture, c*256, 2048-r*128);
          }
        };

        loader.load( tile, patchTex(tile, r, c) );
      }
    }
});

```

**Comment by arcanis** [comment]
Assuming I correctly understand what you mean, I believe that the original texture still needs to be big enough to contain every future patch (it's not possible to dynamically change a texture size, for example*). So in your case, you will want to create your `texture` object with something like this:

```js
var cols = 16, rows = 16;
var width = cols * 256, height = rows * 128;
var texture = new THREE.DataTexture(new Uint8Array(width * height * 4), width, height);
```

This way, you will have enough room to fit your whole texture atlas.

Of course, you could also implement a custom texture that would extend the underlying texture whenever needed, but I have the feeling that it would hurt your performances a lot, since you would need to transfer all the patch every time you would do this.

**Comment by FreakTheMighty** [comment]
Thanks @arcanis, you did understand my questions correctly. Thank you for taking the time to parse it :). I ended up loading the low resolution texture onto a slightly larger sphere, then was able to use the new patch texture api easily. I think the solution you outlined wouldn't fit my needs, as the main issue I'm working around is a UI freeze that happens when loading a 4096x2048 texture into video memory. I suspect that freeze would still happen if I push an empty texture into memory.

**Comment by arcanis** [comment]
I do not "champion" this issue anymore - my thoughts on how this feature could be implemented API-wise are still there if you need them, and the current implementation will remain available for some time, but I'm afraid I now have to move on other things.

**Comment by makc** [comment]
@arcanis if PR is not accepted right away, it rots - merge conflicts appear, and it gets useless - like my #6911 did, for example.

**Comment by arcanis** [comment]
Sure, that's part of why I don't want to support it anymore - I don't have enough time to maintain a branch that may never be merged.

I fully know that this PR isn't yet ready to be merged, and that it needs quite a bit of extra brainstorming. Given that it still hasn't got any feedback from any core contributor yet, I'm concerned about the overhead time that I would need to spend rebasing and maintaining an out-of-tree branch rather than actually working on the feature.

That being said, the code is still there, and I would be really happy to see it eventually merged into Three.js - I just don't have enough time to maintain the PR (plus, I really hate when PRs are stalling), especially when I'm not using Three.js anymore.

So if anyone needs it, feel free to `git fetch` my branch, improve it and open a new PR.

--- 

As a side note, please don't see this message as a rant against core contributors - I fully know that they have so much work to do, and so little time to spend on it ;)

**Pull request closed without merging**
