### PR TITLE
Package.json: Removed npm start, dev and dev-test.

### PR DESCRIPTION
**Pull request by mrdoob**
I don't know who uses these.
I usually have `http-server -p 8080` running in one tab and then do `npm run build` when needed in another.

### CODE REVIEW

**Comment by fernandojsg** [comment]
😢

**Comment by Mugen87** [comment]
Oh man, these were important to me, too. 😢 Can we please restore them?

**Comment by mrdoob** [comment]
All of them? We should also replace `http-server` with `servez`.

**Comment by Mugen87** [comment]
I would say `dev-test` can be removed. 

@fernandojsg Are you fine with this?

> We should replace http-server with servez (the security vulnerability they've had the whole year sparked this).

What is the difference between servez and just serve?

**Comment by mrdoob** [comment]
I believe `servez` is simpler.
@greggman does `servez` have something to disable cache? (like `-c-1` in `http-server`)

**Comment by greggman** [comment]
serves disables the cache by default.

**Comment by fernandojsg** [comment]
> I would say `dev-test` can be removed.
> 
> @fernandojsg Are you fine with this?

Yep, I've never used `dev-test` just `dev`

**Comment by Mugen87** [comment]
I've created a PR since I've already miss my npm commands.

**Pull request merged**
