### PR TITLE
Fix docs for Matrix3#getInverse()

### PR DESCRIPTION
**Pull request by MajorBreakfast**
It looked awkward to me that `Matrix3#getInverse()` would take a `Matrix4` as input. After looking at the code, I think that this is just a typo.

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
Okay, I was wrong. It accesses element 9 and 10 as well. So it definitely needs a `Matrix4`. But how can a `Matrix3f` represent the inverse of a `Matrix4`? This needs to be explained more in the docs.

**Comment by MajorBreakfast** [comment]
Ah well, so it just inverts the rotation part.

What about:
- Renaming it to `Matrix3#getInverseRotation()`
- Adding `Matrix3#getInverse()` that supports both
- And deprecating `Matrix4` as input

**Comment by MajorBreakfast** [comment]
Another tiny thing: `throwOnInvertible ` -> `throwOnNonInvertible`

**Comment by WestLangley** [comment]
`Matrix3.getInverse( matrix4 )` is used by the library to compute the normal matrix from the object transform.

The `Matrix3()` class is not a full-fledged matrix3 library. At the time, the decision was to keep the library lean. We included only the methods required by the library. It is up to @mrdoob if he wants to change that policy.

**Comment by mrdoob** [comment]
It's becoming a bit up to demand and use cases. But without going too crazy...

**Pull request closed without merging**
