### PR TITLE
Docs(Korean): Created Docs for Korean

### PR DESCRIPTION
**Pull request by wonderlandpark**
Start translating docs for Korean

### CODE REVIEW

**Comment by mrdoob** [comment]
Instead of copying the whole `en` folder, I think it's better to just add the files that have been translated.
Like how it's being done for [arabic](https://github.com/mrdoob/three.js/tree/dev/docs/api/ar).

**Comment by wonderlandpark** [comment]
> Instead of copying the whole `en` folder, I think it's better to just add the files that have been translated.
> Like how it's being done for [arabic](https://github.com/mrdoob/three.js/tree/dev/docs/api/ar).

I have removed other files!

**Comment by mrdoob** [comment]
Thank you. Much easier to review.

Seem like the first page is not yet fully translated?

**Comment by wonderlandpark** [comment]
Yes I will convert it to Draft

**Comment by wonderlandpark** [comment]
Translated first Page 🥰

**Comment by mrdoob** [comment]
Great!

What other pages are you planning on translating?

**Comment by wonderlandpark** [comment]
I would like to keep translate it. I love this project and it would be great to contribute. I'll try little by little when I have time.

**Comment by mrdoob** [comment]
I'm not sure what's the right thing to do here...
Adding a new language to the docs only with one page doesn't seem right.

**Comment by Mugen87** [comment]
How about filing a new PR when @wonderlandpark has a few more pages together. E.g. the `Manual` section.

**Comment by mrdoob** [comment]
Yes, he can also continue working on this PR. I'll wait until then.

**Comment by wonderlandpark** [comment]
OK, Thanks for replying!

**Comment by Mugen87** [comment]
Closing in favor of #20865.

**Pull request closed without merging**
