### PR TITLE
Docs: Add note about non-uniform scaling to FAQ.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: see #22781

**Description**

Trying to formulate a note about non-uniform scaling and its potential ramifications.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 requested a review from me. Why was this merged?

**Comment by mrdoob** [comment]
@WestLangley Sorry, I assumed that you were okay with it since you changed the title of the issue a few hours ago.

I prefer to rely in the "Approved" feature but I recall you not being as fan of it so I usually look out for other types of signals from your side. I misread this one 😅

**Comment by WestLangley** [comment]
>To avoid situations like that in the first place try to avoid non-uniform scaling whenever possible.

I do not think we should advise users not to use a three.js feature.

@Mugen87 I understand that this was intended as a starting point for a discussion, and I invested several hours restudying the issue today so I could help you. I had hoped to have the opportunity to reply...

TBH, I really do not agree with the wording of any part of this PR. It does not provide useful information to the user. (I know this PR was just a straw man.)

I would revert this PR and we can consider adding useful information elsewhere.

**Comment by Mugen87** [comment]
Yes, the PR was considered as starting point. 

It's not clear to me yet how we make the users aware about the consequences of non-uniform scaling. The statement of this PR was just a first draft I wanted the feedback of others how we could improve it.

**Comment by Mugen87** [comment]
I've reverted the change via #22818.

**Comment by Mugen87** [comment]
> and we can consider adding useful information elsewhere.

What would you suggest? If you think it's the method `attach()` it's necessary to identify *all* method that potentially fail when non-uniform scaling is used and adding respective notes.

**Comment by mrdoob** [comment]
Would it help to log a warning in the `attach()` method if the scale is non uniform?

**Comment by WestLangley** [comment]
It is not actually the scale that is the issue. It is the shear introduced into the child's world matrix that is the problem. So we would have to test for shear prior to calling the decompose method...

**Comment by mrdoob** [comment]
Ah right, yes. Seems like something we could do in this case?

**Comment by WestLangley** [comment]
Maybe, but [this](https://github.com/mrdoob/three.js/issues/22769#issuecomment-965646914) makes attaching to a non-uniformly-scaled parent a non-issue.

Also, if the child is not rotated, then there will be no shearing, and `attach()` works correctly....

The issue is a bit complex, unfortunately.

**Comment by WestLangley** [comment]
FWIW, if we were to add a test to ensure the matrix was, in fact, decomposable (to a scale and pure rotation), it may be sufficient to test that the columns of the rotation component of the matrix are mutually-orthogonal. That is easy, except you have to allow for roundoff error in the test.

We can add that, but it is a judgement call as to whether it is needed.

**Pull request merged**
