### PR TITLE
Correct detection of Uint32BufferAttribute for length of verticies

### PR DESCRIPTION
**Pull request by Neesnu**
Detection should be length of vertices not length of the index array

### CODE REVIEW

**Comment by Neesnu** [comment]
Might even want to do vertices.length / 3 since reference into the position array is three times bigger then actual vertices

**Comment by WestLangley** [comment]
Perhaps this:
```javascript
this.setIndex( new ( Math.max.apply( Math, indices ) > 65535 ? Uint32BufferAttribute : Uint16BufferAttribute )( indices, 1 ) );
```

**Comment by Mugen87** [comment]
@Neesnu I've always thought we need to check the `length` of the `indices` array, because this value is crucial for the kind of the underlying typed array. Can you explain why we should use the length of the `vertices`?

BTW: I'm happy to clarify this. Was never 100% sure about this...

@WestLangley I'm afraid i don't understand your code snippet. Do you mean:

```javascript
Math.max.apply( vertices, indices ) > 65535
```

**Comment by Neesnu** [comment]
@Mugen87 we need to use the length of the vertices because the indices are a pointer into that array, if the vertices get above 65535, the integer in the index array needs to be able to point to that number

@WestLangley's code pulls the highest value in the indices array, your replacement would fail

My suggestion is going with @WestLangley 's solution.

**Comment by Mugen87** [comment]
That makes sense! Then let's submit @WestLangley solution! 👍

**Comment by Mugen87** [comment]
@Neesnu Thanks for your explanation!

**Comment by mrdoob** [comment]
> My suggestion is going with @WestLangley 's solution.

Took me a while to understand the code but after I understood I agree. @Neesnu do you mind updating the PR with @WestLangley approach?

**Comment by Neesnu** [comment]
@mrdoob On it.

**Comment by Neesnu** [comment]
Missed a couple, let me fix those

**Comment by Neesnu** [comment]
That should be everywhere the detection happens.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@mrdoob How about changing to this?
```javascript
setIndex: function ( indices ) {

	this.index = new ( Math.max.apply( Math, indices ) > 65535 ? Uint32BufferAttribute : Uint16BufferAttribute )( indices, 1 );

},
```

**Comment by mrdoob** [comment]
Tempting...

**Comment by mrdoob** [comment]
Bad news... `webgl_geometry_terrain` doesn't like this...

screen shot 2017-01-18 at 23 24 33

**Comment by Neesnu** [comment]
Just got done with a couple tests, I believe that a new solution is required since javascript has a maximum number of parameters. Maybe we make a helper function in the vain of http://stackoverflow.com/a/13440842

**Comment by mrdoob** [comment]
I guess we'll have to add `THREE.Math.max()`? and I guess `THREE.Math.min()`?

**Comment by mrdoob** [comment]
Or maybe `THREE.Math.arrayMax()` and `THREE.Math.arrayMin()` for clarity?

**Comment by mrdoob** [comment]
Working on it...

**Comment by mrdoob** [comment]
Done!

Also implemented @WestLangley suggestion but I'm not sure about naming...

Maybe `setIndices( array )`? Or, maybe we can add a `Array.isArray()` check in `setIndex()`?

**Comment by WestLangley** [comment]
>Or, maybe we can just add a Array.isArray() check in setIndex()?

Yeah, that one. :)

**Comment by mrdoob** [comment]
Done! I've also done a `utils` module for `arrayMin` and `arrayMax`.

**Pull request merged**
