### PR TITLE
update texture.image

### PR DESCRIPTION
**Pull request by xlsfs**
When changing textures with "texture.image = newImage" the scene does not update

Tried setting the needsUpdate of texture and material to no avail

### CODE REVIEW

**Comment by Mugen87** [comment]
This is actually not the intended usage of `Texture`. Instead of assigning a new image to `Texture.image`, create a new texture instance instead.

**Comment by xlsfs** [comment]
ok thanks for your explanation

**Comment by mrdoob** [comment]
@Mugen87 should we use `Object.defineProperty()` for defining the `image` property so people stop doing this?

**Comment by Mugen87** [comment]
Yes that sounds good to me!

**Comment by Mugen87** [comment]
Um, not sure we can do that without breaking code. Assigning an image object before the texture has used for rendering is actually fine.

**Comment by LeviPesin** [comment]
I don't think it is a good idea to significantly decrease performance (AFAIR `Object.defineProperty()` is very slow) in order to "teach" users...

**Comment by mrdoob** [comment]
Is not about "teaching" users, it's about reducing the number of incoming issues and pull requests 😅

**Pull request closed without merging**
