### PR TITLE
Docs: Add id attribute to old manual's header tags

### PR DESCRIPTION
**Pull request by jamestiotio**
Related issue: #23225

**Description**

This pull request adds the requested `id` attributes to the header tags (`<h2>` and `<h3>`) in the old manual.

Additional note: I figured that this should be done incrementally to avoid a huge list of changes that is harder to review. I will work on adding the corresponding `id` attributes to the [API reference docs](https://github.com/mrdoob/three.js/tree/dev/docs/api/en) and [examples](https://github.com/mrdoob/three.js/tree/dev/docs/examples/en) in separate PRs.

### CODE REVIEW

**Comment by Mugen87** [comment]
It seems that the feature request of the issue is not implemented with this PR. The ids are now added but it's not possible link to a specific section.

E.g. the site link https://raw.githack.com/jamestiotio/three.js/dev/docs/index.html#manual/en/introduction/Creating-a-scene works but not https://raw.githack.com/jamestiotio/three.js/dev/docs/index.html#manual/en/introduction/Creating-a-scene#rendering-the-scene

**Comment by jamestiotio** [comment]
@Mugen87 Could you kindly check again? I have implemented some fixes. It should be possible to link to a specific ID now.

**Comment by Mugen87** [comment]
It seems to work now. 

However, I'm not sure about the value of this feature if header links have to be created manually. Compared to sites like wikipedia, the docs do not have a table of contents section so the links are currently not clickable. I wonder if a clickable hashtag next to each header would solve this issue.

**Comment by jamestiotio** [comment]
Hi @Mugen87, I have added clickable hashtags in commit adebeb9dc84e01f73160c9852519d4239199af8e. The hashtags are located beside each header in a style somewhat similar to the ones used in the articles on [GitHub Blog](https://github.blog/). Could you kindly check if this is much better?

Cheers!

**Comment by Mugen87** [comment]
The current documentation (and its manual part) lacks certain features which are common in other projects like advanced search or more fine-grained navigation in the manual. However, we have the special situation that we are not generating our documentation but developing it ourself. That said, the focus of this project shouldn't lie on developing a documentation template but a 3D engine. So we have to make compromises in context of the documentation by limiting the features and focusing on the most important things.

This change ended up more complicated than originally thought. Next to the additional JS logic we would have to add a significant amount of markup to introduce linkable headers. This is unfortunately out of scope. If we adapt a different style for maintaining the manual (see #27832), we hopefully get this feature for free.

**Pull request closed without merging**
