### PR TITLE
MMDToonMaterial: Removed unnecessary `envMap` shader chunks.

### PR DESCRIPTION
**Pull request by WestLangley**
... as proposed in https://github.com/mrdoob/three.js/pull/25117#issuecomment-1345775852.

/ping @takahirox

### CODE REVIEW

**Comment by WestLangley** [comment]
@takahirox I gave it a shot. :-) This is compatible with the three.js examples, but based on https://github.com/mrdoob/three.js/pull/25117#issuecomment-1345758000,  I understand `MMDLoader` needs to be corrected...

**Comment by WestLangley** [comment]
@Mugen87 At this point, I think merging this is a reasonable, low-risk option.

**Comment by Mugen87** [comment]
When reading https://github.com/mrdoob/three.js/pull/25117#issuecomment-1345758000, it seems this PR requires further changes.

TBH, since this isn't an urgent topic, I would prefer to let @takahirox review the PR.

**Comment by WestLangley** [comment]
>it seems this PR requires further changes.

Actually, `MMDLoader` requires changes, which I am not going to try to fix.

This PR just removes shader chunks from `MMDToonShader` that should not be used.

**Comment by takahirox** [comment]
Sorry, I have been a bit too busy. I will make anothre PR to fix the problem and then review this PR. (But the change looks good already.)

**Comment by takahirox** [comment]
Made a PR #25226

**Comment by Mugen87** [comment]
Since https://github.com/mrdoob/three.js/pull/25226 is in, this one can be merged, too 🎉 .

**Pull request merged**
