### PR TITLE
Rollup: replace Bublè with Babel

### PR DESCRIPTION
**Pull request by marcofugaro**
Remake of #20129 

[Bublè is in maintenance mode](https://github.com/bublejs/buble), and it doesn't support class fields, which are needed for better tree-shaking.

Let's replace it with [Babel](https://github.com/babel/babel), I have provided a config and updated the post-cleanup code so that the bundle is more or less the same, there will be some small changes though.

Preview of the bundle is here, in another branch:
https://raw.githubusercontent.com/marcofugaro/three.js/babel-build/build/three.js

Switching to node 12 (current LTS) is needed for tests to support class properties.

Related to  #19986

### CODE REVIEW

**Comment by mrdoob** [comment]
Okay! Lets give this a try! 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Do we still [polyfills.js](https://github.com/mrdoob/three.js/blob/dev/src/polyfills.js) now that we're using Babel?

**Comment by mrdoob** [comment]
It sure doesn't make sense in `three.module.js`...

**Comment by marcofugaro** [comment]
@mrdoob great idea! Babel has a [feature] (not enabled by default) which automatically detects the globals you're using and polyfills them regarding the supported browsers you provided as targets.

I did a quick test locally, and these are the included pollyfills: ([core-js] is the library containing all the polyfills)

Screenshot 2020-09-22 at 20 38 21

^ It correctly includes the polyfills we need

Screenshot 2020-09-22 at 21 25 32

^ Also includes a lot of other stuff needed for IE11

Screenshot 2020-09-22 at 21 10 55

^ But also a lot of typed array methods needed for IE11, my guess is it included those just because we use typed arrays.

All in all this adds ~`50kb` to the `three.min.js` bundle.

The alternative is to specify just the polyfills we need by hand, and only for the browser bundles.

**Comment by mrdoob** [comment]
> The alternative is to specify just the polyfills we need by hand, and only for the browser bundles.

I think that would be best yeah 👍

**Pull request merged**
