### PR TITLE
Line: fix copy and clone methods

### LINKED ISSUE #8452: GridHelper clone is broken
it has constructor = THREE.GridHelper but inherited clone method expects constructor property to be LineSegments

### PR DESCRIPTION
**Pull request by WestLangley**
This PR also fixes #8452.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Having second thoughts about this one...

Neither `Mesh` nor `Points` copy the `geometry` or `material`. Copy and clone usually reference the original geometries and materials. I guess we didn't follow that pattern here.

Was this to fix `GridHelper.clone()` issue?

Unless I'm missing something... I think I agree with @Mugen87, we should consider reverting this one and fixing `GridHelper.clone()` directly.

**Comment by WestLangley** [comment]
I filed #15064 to replace this PR and it went nowhere.

**Comment by mrdoob** [comment]
I understand, but I'm trying to understand why this was done for `Line` but not for `Mesh` nor `Points`.

**Comment by mrdoob** [comment]
For now I'm going to revert this, because this change is the reason #15974 is happening.

**Pull request merged**
