### PR TITLE
Examples: Updated multiple scenes demo.

### PR DESCRIPTION
**Pull request by linbingquan**
I am not sure it is better, but it is simple.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/linbingquan/three.js/dev-examples-multiple-scenes/examples/webgl_multiple_scenes_comparison.html

TBH, I think the new inverted type of style is confusing.

**Comment by linbingquan** [comment]
> TBH, I think the new inverted type of style is confusing.

I feel the red background is a bit harsh

**Comment by linbingquan** [comment]
> TBH, I think the new inverted type of style is confusing.

I feel the red background is a bit harsh.

**Comment by mrdoob** [comment]
I agree. The new one is confusing. Looks like post processing.

**Comment by linbingquan** [comment]
How about this https://github.com/mrdoob/three.js/pull/19703.

**Pull request closed without merging**
