### PR TITLE
add renderer prop in onBeforeCompile

### PR DESCRIPTION
**Pull request by sunag**
My need:

To the next `NodeMaterial` release is need `renderer` argument to build material. Not to complicate too much the idea is use an auto build since the `onBeforeCompile` is called.

```javascript
THREE.NodeMaterial.prototype.onBeforeCompile = function( shader ) {

_this.build( shader.renderer );

};
```

Renderer argument is the first moment to texture `encoding`. Now is individual by texture and not by slot as previously, for example:

**Old**
```javascript
	if ( builder.isSlot( 'color' ) ) {

		code = 'mapTexelToLinear(' + code + ')';

	} else if ( builder.isSlot( 'emissive' ) ) {

		code = 'emissiveMapTexelToLinear(' + code + ')';

	} else if ( builder.isSlot( 'environment' ) ) {

		code = 'envMapTexelToLinear(' + code + ')';

	}
```

**New**
```javascript
code = builder.material.getTexelDecodingFunction( code, this.value.encoding, builder.renderer );
```

And fix the fact that the old mode only work with linear texture encoding in `NodeMaterial`.

### CODE REVIEW

**Comment by sunag** [comment]
Or could be this:

```javascript
material.onBeforeCompile( materialProperties.shader, _shader );
```

https://github.com/sunag/three.js/blob/a4b8c30be485b4ff661c60151f84ecb57e441227/src/renderers/WebGLRenderer.js#L1541

**Comment by mrdoob** [comment]
> Or could be this:
>
> ```javascript
> material.onBeforeCompile( materialProperties.shader, _this );
> ```

I think I vote for that instead.

**Comment by sunag** [comment]
Done!

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
I think there should be an update to the documentation when a method's signature is changed.

**Comment by Mugen87** [comment]
Current doc: https://rawgit.com/mrdoob/three.js/dev/docs/index.html#api/materials/Material.onBeforeCompile

**Comment by sunag** [comment]
Is to change it
```javascript
[method:null onBeforeCompile]()
```
to?
```javascript
[method:null onBeforeCompile]( [param:Object shader], [param:WebGLRenderer renderer] )
```

**Comment by mrdoob** [comment]
@sunag yep!

**Comment by sunag** [comment]
Done

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
