### PR TITLE
FBXLoader: Added map support

### PR DESCRIPTION
**Pull request by looeee**
Added support for the following map types to FBXLoader: 

* displacementMap 
* emissiveMap 
* specularMap 
* alphaMap 

Improved warnings for unsupported map types. 

Switch texture.name from the `name` property (which is always just 'Texture') to `attrName` which holds the actual texture name. 

~~Environment maps are not directly supported in FBX format, however it looks like it may be possible to support them via the `ReflectionColor` map.~~

Added env map support, see comment below. 

~~There are two remaining maps in three.js that I haven't worked out how to support yet:~~
There is no support for the following two map types
* aoMap
* lightMap

### CODE REVIEW

**Comment by looeee** [comment]
A question regarding `specularMap` - there are two related maps that could be used here:

* SpecularColor
* SpecularFactor (AKA SpecularLevel)

I've gone with the color map, however perhaps the SpecularLevel would be more appropriate. Does specularMap effect specular color in three.js, or just the intensity?

**Comment by WestLangley** [comment]
I'd hold off on specular until the changes in #9339 are addressed.

**Comment by looeee** [comment]
While I agree that it will be nice once or if the changes #9339 over a year ago are addressed, in the the meantime there should be some support for a specular map.

In total there are three maps that modulate specular in the FBX format:

* SpecularColor
* SpecularFactor 
* ShininessExponent (glossiness) 

Which do you think is the most appropriate at the moment for the `specularMap` slot?

**Comment by looeee** [comment]
Added env map support. Only `THREE.EquirectangularReflectionMapping` is supported - there's no way to specify any other kind and this matches the way the model looks in 3DS max when I'm testing. 

There's also no way support for cube maps unfortunately.

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
Hmm... just realised that this causes a warning since I'm defining `.envMapIntensity` for all materials and Phong / Lambert don't have that parameter. 

I'll have to redo that bit...

**Comment by WestLangley** [comment]
>In total there are three maps that modulate specular in the FBX format: SpecularColor, SpecularFactor, ShininessExponent (glossiness)
>Which do you think is the most appropriate at the moment for the specularMap slot?

They don't sound like maps to me.

**Comment by looeee** [comment]
@WestLangley agreed, but I didn't choose the nomenclature for the FBX format 😆 

These correspond in 3DS max to the following map slots:

SpecularColor -> Specular color map 
SpecularFactor -> Specular level map 
ShininessExponent -> glossiness map

These are also all properties on the material:

SpecularColor -> float x representing color RGB(x, x, x)
SpecularFactor -> float (in practice this seems to be always 0) 
ShininessExponent -> float

There are two additional properties in the format:

Specular -> RGB color
Shininess -> Float

**Pull request merged**
