### PR TITLE
SimplifyModifier - Basic Edge-Collapse Geometry Modifier

### PR DESCRIPTION
**Pull request by zz85**
- api: simplify.modify( geometry, reductions ) gives new geometry
- #5806
- slightly different from http://blurspline.com/labs/3d/bunny/ but makes this a simpler example
- no rabbit yet..

image

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet! Thanks!

**Comment by WestLangley** [comment]
@zz85  Do you plan on adding normals?

**Comment by zz85** [comment]
@WestLangley do you mean `geometry.computeFaceNormals()`?

**Comment by WestLangley** [comment]
No. It appears your simplified geometries have no vertex normals -- or in the case of buffer geometry, zero-length ones.

**Comment by scdd** [comment]
路过

**Comment by sam-hertig** [comment]
I am wondering whether it is intentional that the number of vertices of the original geometry sometimes changes when fed into the modifier: Writing out the length of the array of vertices for the unsimplified geometries indicates a reduction in length from 256 to 212 for the box, and from 81 to 64 for the plane in the example html-file. Strangely, torus and sphere remain unchanged... Thanks for your help!

**Comment by sam-hertig** [comment]
It seems to be caused due to calling the mergeVertices() method on geometry. This could be dangerous, since it could reduce to number of vertices of the original geometry such that calling the modifier with a count of (geometry.vertices.length * 0.5) eventually eliminate too many, resulting in 'no next vertex'. Correct me if I am missing something. Thanks!

**Comment by zz85** [comment]
Tt does seem like this has a side effect on the original geometry. I guess some cloning needs to be done (either inside or outside SimplifyGeometry).

**Pull request merged**
