### PR TITLE
Update Material.toJSON

### PR DESCRIPTION
**Pull request by bGute**
Add missing support for: polygonOffset, polygonOffsetFactor and polygonOffsetUnits .

See #14070

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
PRs need to target the `dev` branch, not `master`.

**Comment by Mugen87** [comment]
@mrdoob I think this can be merged. The PR targets `dev` now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
