### PR TITLE
Editor ui refactor

### PR DESCRIPTION
**Pull request by sdinesh86**
Created a new EditorView Ui component and moved all the Viewport, Sidebar, Toolbar etc.. into it.
Modularize the UI Components as well

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, what are the benefits of this?

**Comment by sdinesh86** [comment]
In general the idea behind this PR is not start moving the Editor code to be a more managable code and make arrangments for the implementations needed in editor from UI / UX perspective.

Example : The EditorView class was done so as later we can use a Layouting component in order to create it, with this we would be able to have more managable UI / UX.

I am working on a Layout and SplitPanes component that we could use for this,
LayoutPanel to stack the MenuBar and Viewport, Sidebar.
And SplitPanes to have collapsible Panels for Sidebar.

I will be using [Split.js](https://split.js.org/) for the SplitPanes comonent and as for the LayoutPanel i will be using css3 flex layout.

**Comment by Mugen87** [comment]
> Example : The EditorView class was done so as later we can use a Layouting component in order to create it, with this we would be able to have more managable UI / UX.

Um, I don't understand why you need a single "container" element for this. A layout component should also works with multiple children. If so, this entire refactoring is not necessary.

**Comment by mrdoob** [comment]
> I will be using Split.js for the SplitPanes comonent and as for the LayoutPanel i will be using css3 flex layout.

I fear all this is over engineering. We just need the viewport and the sidebar to be able to resize. We don't need to make all the elements resizable.

**Comment by sdinesh86** [comment]
I agree it might be over engineering but i feel the editor should have these so as to make it intuitive and easy to use,

In our team we use the editor heavly, and a lot of these changes are mostly feedback from the pears working on it. We have a lot of large scenes, and people working on it always point out how difficult, tedious and time consuming it is to work on these large scenes.

So these changes might be very opinionated and too much. and if you feel its too much and doesnt fit the vision of this editor we can surely close this one.

**Comment by mrdoob** [comment]
> We have a lot of large scenes, and people working on it always point out how difficult, tedious and time consuming it is to work on these large scenes.

Do you mind ellaborating how are you planning to address these issues? And/or how does this PR address these issues? Some transparency there will help us understand what you're trying to do.

**Comment by sdinesh86** [comment]
Sure

First of all just a small breif on the work we do.
We use threejs to display models ( Jwellery, clothing etc ) on websites, the models that we get made are in peices which need to be composed into scene file. we try to use the editor for this as much as possible.

Difficulties we face :

1. Since we need to compose the scenes out of large number of files and the outliner in the editor is small it becomes difficult to navigate and track objects in the outliner.
2. In order edit materials one has to select the object and then navigate to the bottom section of the sidebar which again has to be scrolled in order to reach to certain props.
3. In order to assign the material one has to select the object first then navigate to the material browser and then assign the material, ( In our case this process has to be sometimes repeated nearly 60 - 70 times :( )
4. There is no ability to group objects, move multiple objects once etc.

How does this PR address this.
This PR doesnt really address these issues right now, but my goal is to reach there while making the code more easy to work with, at the same time make this into a more full fledged editor.

Honestly I might be over thinking and over engineering on this one, but felt this could help. If you guys have any other ideas or vision, I would be happy to work towards that.

Also initially i was about to write an editor for our work, but then thought of instead of reinventing the wheel i could take this forward.

Your thoughts and suggestions will be much appreciated.

**Comment by mrdoob** [comment]
Thanks for the explanation.

In the past I've seen people forking the editor and adjusting it for their use case. I think that that approach maybe suitable here too.

**Comment by sdinesh86** [comment]
Yup I am already doing that, in fact we started off with this approach and now have shifted to a complete rework on it and doing it different way

we can close this PR

**Pull request closed without merging**
