### PR TITLE
KTX texture loader

### PR DESCRIPTION
**Pull request by amakaseev**
This texture can store all types of the compressed textures including ASTC

https://www.khronos.org/opengles/sdk/tools/KTX/

I can add an example of use to webgl_materials_texture_compressed.html?
or to create new?

### CODE REVIEW

**Comment by mrdoob** [comment]
I would rename `webgl_materials_texture_ktx` to `webgl_loaders_texture_ktx`.

**Comment by WestLangley** [comment]
>I can add an example of use to webgl_materials_texture_compressed.html?

That example only loads .dds textures. Perhaps the example should be renamed, too.

**Comment by mrdoob** [comment]
Good point. I'll merge and clean up.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Seems like this code/example also tries to load the `WEBGL_compressed_texture_pvrtc` extension.

screen shot 2017-12-22 at 12 36 28 pm

Is that expected?

**Comment by amakaseev** [comment]
> Seems like this code/example also tries to load the WEBGL_compressed_texture_pvrtc extension.

No, sorry, but so far only the ASTC format, in further I planned to create KTX files with other formats

**Pull request merged**
