### PR TITLE
USDZExporter: Add anchoring support.

### LINKED ISSUE #21995: USDZ exporter with target wall placement
**Is your feature request related to a problem? Please describe.**

When exporting to USDZ currently there is the possibility missing to define the tracking target for AR view (AR Quick-look)

**Describe the solution you'd like**

I'm thinking of a way to make the exporter configurable so that it accepts the different tracking targets supported by Apple AR Quick-look

**Additional context**
Reading through the schema definition here: https://developer.apple.com/documentation/arkit/usdz_schemas_for_ar 
It is possible to encode into the USDZ which tracking target should be used. Hence, I've extended the USDZExporter to support configuration for targets. For now, wall target is integrated but more can be added in the future.

Please see this branch for more context.

Also, I'd like to add that this is my first approach to contribute to this amazing project. And I'm sure I need to do many rounds before this is even close to acceptable but I'd like to give it a go.

My WIP branch: https://github.com/ThorstenBux/three.js/tree/feat/wall-placement-usdz

### PR DESCRIPTION
**Pull request by aleneum**
This is basically the same as #21997 by @ThorstenBux but with fixed white spaces.
The problem wasn't too few tabs but too many in strings.

Original description:

Fixed #21995

Description

Until these changes, it wasn't possible to tell AR Quicklook that a USDZ file should be attached to a wall target as opposed to a horizontal surface.

Reference: https://developer.apple.com/documentation/arkit/usdz_schemas_for_ar/preliminary_anchoringapi

This contribution is funded by Tripod Digital.

### CODE REVIEW

**Comment by aleneum** [comment]
I just realized that the added strings also contained tabs. I fixed that (I hope the indent is correct). I decided to squash this into one commit (and force push) to not inflate the commit history any further.

**Comment by elalish** [comment]
@donmccurdy yes, I think so. We actually have our own API to specify wall-placement, so that will be our normal route. We would definitely use this feature in combination with our USDZ auto-generation.

**Comment by aleneum** [comment]
Hello again, since there hasn't been activity for 6 month and I am doing some 'repo cleaning' right now: Is this still a PR you are considering merging? Let me know if I could do something to make hitting that merge button easier for you. If this PR is not valid anymore I'd close this and delete my fork of three.js.

Cheers

**Comment by milesgreen** [comment]
+1 for this feature. Ability to specify floor or wall anchor when exporting USDZ would be great.

**Comment by elalish** [comment]
@mrdoob Any reason we can't merge this?

**Comment by Mugen87** [comment]
The API has slightly changed according to other exporters: #24865

**Pull request merged**
