### PR TITLE
Editor: Sorting objects for Menubar.Add.js

### PR DESCRIPTION
**Pull request by linbingquan**
Sorting objects follow this rule, simple to complex, like 2D < 3D or `Tetrahedron` < `Octahedron` < `Icosahedron`

### CODE REVIEW

**Comment by mrdoob** [comment]
I think I would, instead, change the order so it's sorted alphabetically.

**Comment by linbingquan** [comment]
> I think I would, instead, change the order so it's sorted alphabetically.

@mrdoob You mean this? 

- `Box` < `Circle` < `Cylinder` < `Iconsahedron` < `Lathe`
- `AmbientLight` < `DirectionalLight` < `HemisphereLight`

image

**Comment by looeee** [comment]
That looks better to me. My brain scans lists in alphabetical order very fast, other orders tend to slow me down.

**Comment by mrdoob** [comment]
@linbingquan yes 👌

**Comment by linbingquan** [comment]
http://raw.githack.com/linbingquan/three.js/dev1/editor/index.html

**Comment by mrdoob** [comment]
Hmm, I wouldn't introduce a new API for this, I would just move the code around 😇

**Comment by linbingquan** [comment]
http://raw.githack.com/linbingquan/three.js/dev1/editor/index.html
image

**Comment by linbingquan** [comment]
@mrdoob http://raw.githack.com/linbingquan/three.js/dev1/editor/index.html

image

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
