### PR TITLE
Fix the array checking logic

### PR DESCRIPTION
**Pull request by xyan190**
An argument could be an array when argument.length > 0.

### CODE REVIEW

**Comment by mrdoob** [comment]
I don't think I like the idea of passing arrays...

**Comment by tschw** [comment]
Although I can't read mrdoob's mind, there are actually some reasons for rejecting your code:

If it actually worked, it would be very questionable design to base function overloading on the presence of some `.length` property: Suppose an object had some length - a geometric one, for instance...

You can always pass an array as arguments to any function using `Function.prototype.apply`:

    myNode.add.apply(myNode, arrayOfObjects)

or just code a loop. A single, sufficiently simple way to achieve a desired effect is enough.

Did you test your code? ;-) Also, it's a good idea to include a documentation update when proposing interface changes...

If we haven't completely demotivated you and you'd still like to contribute: Some examples on the dev branch are currently not working because of recent interface changes (see warnings on the console) - updates should be most welcome.

I guess the implementation of `add(...)` would read cleaner without that recursion - it probably just evolved that way.

**Comment by xyan190** [comment]
Thanks for the comments.

So if we need to support the array argument, then we should fix this bug. Maybe Array.isArray() is a better choice to check whether the argument is an array or not.

If we don't want to support the array argument, then we should fix the code by removing some code.

I may fire a bug on the Issues to let experienced guys to address this problem. Thank you!

**Comment by tschw** [comment]
Could you please elaborate on where there is a bug?!

As documented, the `.add` method expects an arbitrary number of arguments - no arrays.

As shown in my previous post, you can just `.apply` the `.add` method to get your array's elements added efficiently.

**Comment by tschw** [comment]
The `.add` and `.remove` methods are the proper way to manipulate the scene graph. The `.children` property is exposed mainly for the purpose of efficient traversal, I guess. Manipulation may (or may not) work during initialization, that is before the parent object sees the renderer. The documentation could be clearer on that...

Also, as said before, the recursion is a little weird. Ricardo may (or may not) accept a pull request tidying it up - frankly put, there are more important issues than fixing things that aren't broken. If you really care about it, digging into it and providing a documentation update would be a more useful contribution, IMHO.

**Comment by xyan190** [comment]
OK. I see. The array is not expected by the `.add`. I misunderstood the document. Thanks!

**Pull request closed without merging**
