### PR TITLE
 Clear opaque and transparent array in WebGLRenderer.dispose (#8987)

### PR DESCRIPTION
**Pull request by olivierchatry**

### CODE REVIEW

**Comment by mrdoob** [comment]
@tschw 

Do you think doing something like this would be a good idea?

```js
var Pool = function () {
    this.array = [];
    this.index = -1;
};
Object.assign( Pool.prototype, {
    add: function ( item ) {
        this.array[ ++ index ] = item;
    },
    clear: function () {
        this.array = [];
        this.index = -1;
    }
} );

//

opaqueObjects = new Pool();
transparentObjects = new Pool();

```

Suggestions for better names?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@tschw 

Do you think doing something like this would be a good idea?

```js
var Pool = function () {
    this.array = [];
    this.index = -1;
};

Object.assign( Pool.prototype, {
    add: function ( item ) {
        this.array[ ++ index ] = item;
    },
    clear: function () {
        this.array = [];
        this.index = -1;
    }
} );

//

opaqueObjects = new Pool();
transparentObjects = new Pool();

```

Suggestions for better names?

**Comment by olivierchatry** [comment]
No worry :) but about the "Pool" thing, what is the overhead of calling a function on a critical path like this ?

**Comment by mrdoob** [comment]
Yeah, I wonder if it would be noticeable...
It'd sure clean up the code a bit and make it more robust though.

**Comment by olivierchatry** [comment]
Not sure it would, maybe the interpreter / dynrec is inlining small
function like this. But yeah it would make things a bit cleaner.

**Comment by tschw** [comment]
@mrdoob 
> Do you think doing something like this would be a good idea?

Very sketchy. And a little over-engineered, but I guess we shouldn't argue over taste :).

When doing
```javascript
this.array = [];
```
in `.clear()`, might as well just use an array and `push`, since it actually removes all caching. We are also recycling the objects itself, so the encapsulation would have to be refined to have the same effect like the code I once added.

**Comment by mrdoob** [comment]
> When doing
```javascript
this.array = [];
```
in `.clear()`, might as well just use an array and `push`, since it actually removes all caching. We are also recycling the objects itself, so the encapsulation would have to be refined to have the same effect like the code I once added.

Hmm, how would that look like?

**Comment by tschw** [comment]
> Hmm, how would that look like?

Well, actually there's a `.clear()` and a `.purgeCache()` case. The former is between frames (where we want to keep as much memory allocated as possible) and the other is when we want to clear the cache, e.g. switching levels in a game or when the renderer is shut down. Then, in order to not only recycle the array but also the objects, we'd have to make `.add` take property values, and not objects, I guess.

**Pull request merged**
