### PR TITLE
MTLLoader: fixes issue when textures are not updated on image load.

### LINKED ISSUE #12105: MTLLoader : Loader does not wait for textures to be loaded or updates the material when textures are loaded
##### Description of the problem 

When loading obj+mtl models using the MTLLoader, if the loading is fast enough the model is loaded and inserted into the scene without textures.

Simplifying a bit my usage, I use the OBJLoader2 + MTLLoader loaders to insert models into my scene. I set their onload function to a function that adds the model and redraws the scene. That is,
 the renderer is only called when an object is loaded and added (there is no animation loop).
If the loading process is fast enough, the model is added without textures.

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by carlosanunes**
As I am not sure about three.js internal updates, not sure if this is a real fix to the issue, but it is working in my tests.

Fixes #12105

### CODE REVIEW

**Comment by mrdoob** [comment]
Any chance you could share a jsfiddle that shows the issue?

**Comment by Mugen87** [comment]
I don't think this is the right fix. From my point of view, the loading process behaves correctly. If you want to wait until all assets of your OBJ file are loaded, use `LoadingManager` like suggested in this [comment](https://github.com/mrdoob/three.js/issues/12105#issuecomment-326630328).

**Comment by Mugen87** [comment]
@carlosanunes You are targeting `master` branch right now. `dev` branch is the correct one.

More information: https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

**Comment by carlosanunes** [comment]
@mrdoob , will try to do so. (can't share the models)

@Mugen87 , will change to dev.

**Comment by morigazuo** [comment]
very cool

**Pull request closed without merging**
