### PR TITLE
Implement normals loading

### PR DESCRIPTION
**Pull request by elijahsgh**
Yay, normals.

Tested by toggling Flat/Smooth shading on models with normals present.

### CODE REVIEW

**Comment by mrdoob** [comment]
Looks good!

**Comment by mrdoob** [comment]
Why are you doing `vertices.clone()` and `normals.clone()` though?

**Comment by tamarintech** [comment]
That's a leftover from when I first implemented the AMFLoader in my project.  I wanted objects that could be scaled (via applying a matrix), altered by geometry removal (split, faces removed, etc), deleted, etc without affecting other geometry.

Since then, I've been wondering if the clone was even necessary.  That section will be reworked for the AMF Constellations feature soon.  Constellations are a mechanism for creating redundant arrangements of objects by reference to a loaded object (example: if you had a chess board you would want constellations of pawns, etc).

Any tips?  I've learned a lot since the original implementation and I'm pretty sure those clones are unnecessary.

**Comment by mrdoob** [comment]
Sounds like you could just reuse the geometry in different meshes for doing the constellations thing?

**Comment by tamarintech** [comment]
Absolutely what I've been thinking. :)

It'll all be refactored to reuse the geometry attributes for the constellations feature.

**Pull request merged**
