### PR TITLE
GLTFLoader: Fix ‘this’ error.

### PR DESCRIPTION
**Pull request by nqdy666**

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please also update the version of `GLTFLoader` in the `examples/js` directory?

**Comment by mrdoob** [comment]
I'll merge and clean up.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
FYI @donmccurdy @cdata

**Comment by cdata** [comment]
Thanks for the heads up on this 👍

**Pull request merged**
