### PR TITLE
NormalMap Shader: prevent branching

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in https://github.com/mrdoob/three.js/pull/17586#issuecomment-536050826.

/ping @JordyvanDortmont 
/ping @sunag

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by sunag** [comment]
@WestLangley Is possible find a way to turn `frontFacing` a global constant in shader?
```javascript
#ifdef FRONT_SIDE
bool frontFacing = 1.0;
#elif BACK_SIDED
bool frontFacing = -1.0;
#elif DOUBLE_SIDED
bool frontFacing = dot( cross( S, T ), N ) > 0.0 ? 1.0 : -1.0;
#endif
```

Thus it can be used in other functions like `bump map`:
https://github.com/mrdoob/three.js/blob/e6920cdf8d4a76c582f7ac91b93a1056eec740ae/src/renderers/shaders/ShaderChunk/bumpmap_pars_fragment.glsl.js#L38

**Comment by sunag** [comment]
> @WestLangley Is possible find a way to turn frontFacing a global constant in shader?

Seems that is was implemented in
https://makc3d.wordpress.com/2015/09/17/alternative-to-gl_frontfacing/
http://jsfiddle.net/8sgdaknm/7/

I think that a face direction (`target *= faceDir`(-1 or 1), is better that `target *= float( boolean ) * 2.0 - 1.0`  approach.

**Comment by mrdoob** [comment]
> I think that a face direction (`target *= faceDir`(-1 or 1), is better that `target *= float( boolean ) * 2.0 - 1.0`  approach.

Why?

**Comment by WestLangley** [comment]
>Is possible find a way to turn frontFacing a global constant in shader?
>#elif DOUBLE_SIDED
>bool frontFacing = dot( cross( S, T ), N ) > 0.0 ? 1.0 : -1.0;


We already have access to `gl_FrontFacing`.

Also, `dot( cross( S, T ), N )` is a temporary work-around and a hack.

**Comment by sunag** [comment]
I am creating a PR for show better the idea.
https://github.com/mrdoob/three.js/commit/29f6248df0b1b7531718be8e08a3820425261f42

**Comment by sunag** [comment]
@mrdoob is about to use this approach:
https://github.com/sunag/three.js/commit/3b73f1c1ad4be30686382c193a9512abf70177cc

**Comment by mrdoob** [comment]
@sunag yeah, would be nice to have a PR with your suggestion so we can discuss it there.

**Pull request merged**
