### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #21018

**Description**

Use `BoxBufferGeometry` instead of `BoxGeometry`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
It's ugly indeed 😕

**Comment by mrdoob** [comment]
How about we rename all the geometry generators to `BoxGeometry`, `CircleGeometry`, etc

But we leave `BufferGeometry` and co as it is?

And then we add `export { BoxGeometry as BoxBufferGeometry }`, etc in `Three.Legacy.js`?

**Comment by Mugen87** [comment]
I think it's better to keep the class names like `BoxGeometry` intact if you have the intention to rename `BufferGeometry` to `Geometry` at some point.

**Comment by Mugen87** [comment]
I've made a PR with an alternative approach 👍 . Seeing code makes it easier to compare with what we have in `dev` now.

**Comment by mrdoob** [comment]
> I think it's better to keep the class names like `BoxGeometry` intact (and not deprecate them) if you have the intention to rename `BufferGeometry` to `Geometry` at some point.

👍👍👍

**Pull request merged**
