### PR TITLE
Arealight for MeshPhongMaterial & WebGLRenderer

### PR DESCRIPTION
**Pull request by bhouston**
There was always an AreaLight class but it was only used in the deferred renderer examples.  This is an implementation that works with MeshPhongMaterial and WebGLRenderer.

It isn't perfect and it is based on http://stackoverflow.com/questions/17021264/improved-area-lighting-in-webgl-threejs

AreaLight should be properly added to the Three.JS Editor, although I do not know how to do that.

Includes my merge parts of these two other PRs: https://github.com/mrdoob/three.js/pull/5785 https://github.com/mrdoob/three.js/pull/5788

### CODE REVIEW

**Comment by mrdoob** [comment]
Any thoughts on this PR @WestLangley?

**Comment by WestLangley** [comment]
I would like to revisit this at some point. I am hopeful we can continue to make progress on @bhouston's other PRs first.

**Comment by mrdoob** [comment]
Which of @bhouston's PR should I tackle next?

**Comment by WestLangley** [comment]
> Which of @bhouston's PR should I tackle next?

First #5791. That should be easy, I think.

Then if @bhouston will remove the conflicts in #5805, I will carefully review it. I hope that will be straight-forward. It would be helpful if the many commits were collapsed into one.

After those changes, I believe @bhouston had some further shader-related PRs he wanted to propose.

**Comment by mrdoob** [comment]
@bhouston any idea of when you will be able to address @WestLangley points?

**Comment by mrdoob** [comment]
I guess this PR needs some updating?

**Comment by bhouston** [comment]
obsolete.  I guess we'll try again in the future.

**Comment by EskelCz** [comment]
@bhouston why is this obsolete?
WestLangley shared this at stackoverflow, working (with some minor quirks) in custom shaders:
http://stackoverflow.com/a/17160137
I'm waiting for integrated area lights like for a miracle. :( Thanks for any clarification.

**Comment by mrdoob** [comment]
> obsolete. I guess we'll try again in the future.

Yes please! 😊

**Pull request closed without merging**
