### PR TITLE
MathUtils: Use crypto.randomUUID() when available.

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #13069

**Description**

Browser are adding [a function for generating random UUIDs](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID).
It's already available in Chrome, Edge and it's coming in [Safari](https://webkit.org/blog/11971/release-notes-for-safari-technology-preview-132/) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1723674).

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Meh, I don't know how to make this pretty...

**Comment by Mugen87** [comment]
You probably have to put the test 'randomUUID' in crypto` inside `generateUUID()`.

**Comment by mrdoob** [comment]
I was trying to avoid not having to check every time. I guess I'll have to declare it outside...

**Comment by Mugen87** [comment]
Maybe having two functions `generateUUIDCrypto()` and `generateUUIDLegacy()`. And then do this:
```js
const generateUUID = ( 'randomUUID' in crypto ) ? generateUUIDCrypto : generateUUIDLegacy;
````

**Comment by mrdoob** [comment]
I'm also trying to avoid having to declare `_lut` 😅

**Comment by Mugen87** [comment]
It seems the `crypto` variable does not exists in `node.js`. Adding `typeof crypto=== 'undefined'` should solve this.

**Comment by mrdoob** [comment]
Alright, lets see how this goes 🤞

**Comment by mrdoob** [comment]
Hmm, rollup is adding a getter:

Screen Shot 2021-09-20 at 7 18 35 PM

@Mugen87 I'll try your approach 👍

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/e245401ff32d54b1295b8b97a5a3f01ef057199e

**Comment by Mugen87** [comment]
Looking good!

**Pull request merged**
