### PR TITLE
FBXLoader: interpolate large Euler rotation values to allow converting to Quaternions

### PR DESCRIPTION
**Pull request by looeee**
Alternative to #13757. See also #13756

Rotation in FBX files are specified in Euler angles, which can have arbitrarily large values. This causes problems when converting to Quaternions which don't support values greater than 2 * PI. In fact, values greater than PI seem to cause problems as the Quaternion then loses directional information and can rotate in the wrong direction.

This PR add a function to interpolate rotation keys frames when the values are greater than PI. 

After this PR a rotation keyframe on the x axis with 

```js
times = [0, 4]
values = [0, 720]
```

Will be interpolated to 

```js
times = [0, 1, 2, 3, 4]
values = [0, 180, 360, 540, 720]
```

### CODE REVIEW

**Comment by WestLangley** [comment]
>Euler angles, which can have arbitrarily large values.

Euler angles specify an orientation; they do not specify an animation path. `( PI, 0, 0 )` and `( - PI, 0, 0 )` are the same orientation, as are `( 2 PI, 0, 0 )` and `( 0, 0, 0 )`. Euler angles have a limited range of valid values.

**Comment by looeee** [comment]
OK, but in FBX files the rotation values in animation keyframes, which are specified in Euler angles, can have a arbitrarily large step in a single keyframe. 

For example the model provided by @nick-nikoliuk in #13756 rotates -990 degrees around z over one keyframe.  When loaded in other frameworks the cube performs 2.75 full rotations. It seems like it should do the same in three.js.

**Comment by WestLangley** [comment]
You are conflating concepts. Euler angles do not specify 990 degree rotations.

If other frameworks support that example, I agree it makes sense for three.js to do so, too.

Just make sure your code works in a variety of cases. You may have to break the keyframe into, say, 120 degree increments (instead of 180) to avoid ambiguity.

**Comment by looeee** [comment]
Ok, let's say that FBX rotation tracks can comtain arbitrarily large angles even though it's technically incorrect for them to do so since FBX files specify rotations in Euler angles.

In any case, I tested this with the same set of models that I've tested previous PRs against and there appear to be no issues. 

I'd rather not divide up the tracks any more than is necessary. If we come across models where this causes a problem we can use a smaller division, but I world expect 120 is still unnecessary, 179 should suffice in that case.

**Comment by WestLangley** [comment]
I have not tested this, but I would at least avoid 180 and - 180.

**Comment by looeee** [comment]
Ok, seems reasonable. I'll test that in the morning

**Comment by looeee** [comment]
Switched to interpolating at 179 instead of 180 degrees. @WestLangley looks okay to you?

**Comment by mrdoob** [comment]
How about...

```js
if ( valuesSpan >= 180 ) {
```

**Comment by looeee** [comment]
Yeah, that's better.

**Comment by WestLangley** [comment]
>if ( valuesSpan >= 180 ) {

Can `valuesSpan` be negative; for example: - 200?

**Comment by looeee** [comment]
Yes, it absolutely should. The `maths.abs` got lost somewhere in the refactoring.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
