### PR TITLE
Vector convinience functions isFinite and quaternionTo

### PR DESCRIPTION
**Pull request by ShynRou**
These functions should make working with vectors a bit easier.

### CODE REVIEW

**Comment by WestLangley** [comment]
We already have `Quaternion.setFromUnitVectors( v1, v2 )`.

Also, we avoid calling `new` and `clone()` in these methods. That is why the closures are used.

What is your use-case for `Vector*.isFinite()`?

**Comment by ShynRou** [comment]
Sorry I must have overlooked Quaternion.setFromUnitVectors( v1, v2 )
When ever you need to check if the result is valid. Not NaN or Infinite.
For example after normalize()

**Comment by WestLangley** [comment]
>For example after normalize()

Can you provide a specific example where the result is invalid for valid inputs?

**Comment by ShynRou** [comment]
Normalizing a vector with length of 0?

**Pull request closed without merging**
