### PR TITLE
Fixed CRLF issues with global find and dos2unix

### LINKED ISSUE #13224: Should we fix all CRLF issues?
##### Description of the problem

Hi all,

the introduction of `.gitattributes` made sense, but it comes with a cost. If not all your files obey to the imposed rule you may get into trouble when switching branches even if that is not obvious (line endings are correct). Sometimes the only workaround is to hard reset to a fairly old commit and reset to hard to dev again; sounds weird, yes, but it works knowing from past personal experience.
It doesn't matter on a Linux box, but on Windows it can be annoying. Can't speak for Macs as I don't have one (`LF` is standard here, CR is long gone, correct?).

The following command performed with Cygwin on my Windows 10 box dev branch commit 4e0f6a7043bedafbf9d1e685e1cdda76dbab67fd :
```bash
find . -not \( -path "./.git/*" -o -path "./.idea/*" -o -path "./node_modules/*" \) -type f -exec dos2unix {} \;
```
revealed the list you find below.

I haven't issues a merge request (see: https://github.com/kaisalmen/three.js/tree/dos2unix) as I want to know you opinion about this first.

Do you think there is need for action? I guess there are issues on other OS platforms (dev->dev merge and several commit messages suggest that). IMHO, I would correct this once all files are `LF` any new commit from Windows will be automatically converted due to `.gitattributes` instructions.

```bash
.github/CONTRIBUTING.md
docs/api/cameras/Camera.html
docs/api/constants/Materials.html
docs/api/core/BufferGeometry.html
docs/api/core/EventDispatcher.html
docs/api/core/Face3.html
docs/api/extras/core/Curve.html
docs/api/extras/core/Shape.html
docs/api/extras/curves/ArcCurve.html
docs/api/extras/curves/CubicBezierCurve.html
docs/api/extras/curves/CubicBezierCurve3.html
docs/api/extras/curves/EllipseCurve.html
docs/api/extras/curves/LineCurve.html
docs/api/extras/curves/LineCurve3.html
docs/api/extras/curves/QuadraticBezierCurve.html
docs/api/extras/curves/QuadraticBezierCurve3.html
docs/api/extras/curves/SplineCurve.html
docs/api/extras/objects/ImmediateRenderObject.html
docs/api/geometries/DodecahedronBufferGeometry.html
docs/api/geometries/DodecahedronGeometry.html
docs/api/geometries/IcosahedronBufferGeometry.html
docs/api/geometries/IcosahedronGeometry.html
docs/api/geometries/OctahedronBufferGeometry.html
docs/api/geometries/OctahedronGeometry.html
docs/api/geometries/ParametricBufferGeometry.html
docs/api/geometries/ParametricGeometry.html
docs/api/geometries/PlaneGeometry.html
docs/api/geometries/PolyhedronBufferGeometry.html
docs/api/geometries/PolyhedronGeometry.html
docs/api/geometries/ShapeBufferGeometry.html
docs/api/geometries/ShapeGeometry.html
docs/api/geometries/TetrahedronBufferGeometry.html
docs/api/geometries/TetrahedronGeometry.html
docs/api/geometries/TextBufferGeometry.html
docs/api/geometries/TubeBufferGeometry.html
docs/api/geometries/TubeGeometry.html
docs/api/helpers/ArrowHelper.html
docs/api/helpers/CameraHelper.html
docs/api/helpers/FaceNormalsHelper.html
docs/api/helpers/GridHelper.html
docs/api/helpers/SpotLightHelper.html
docs/api/helpers/VertexNormalsHelper.html
docs/api/lights/AmbientLight.html
docs/api/lights/HemisphereLight.html
docs/api/lights/Light.html
docs/api/lights/PointLight.html
docs/api/lights/SpotLight.html
docs/api/loaders/JSONLoader.html
docs/api/loaders/Loader.html
docs/api/loaders/LoaderUtils.html
docs/api/loaders/ObjectLoader.html
docs/api/materials/LineBasicMaterial.html
docs/api/materials/RawShaderMaterial.html
docs/api/materials/SpriteMaterial.html
docs/api/objects/Skeleton.html
docs/api/renderers/shaders/ShaderChunk.html
docs/api/renderers/shaders/ShaderLib.html
docs/api/renderers/shaders/UniformsLib.html
docs/api/renderers/shaders/UniformsUtils.html
docs/api/renderers/webgl/WebGLProgram.html
docs/api/renderers/webgl/WebGLShader.html
docs/api/renderers/webgl/WebGLState.html
docs/api/renderers/WebGLRenderTargetCube.html
docs/api/scenes/Fog.html
docs/api/textures/DataTexture.html
docs/api/textures/Texture.html
docs/examples/geometries/ConvexBufferGeometry.html
docs/examples/geometries/ConvexGeometry.html
docs/examples/geometries/DecalGeometry.html
docs/examples/loaders/LoaderSupport.html
examples/models/babylon/skull.babylon
examples/models/fbx/nurbs.fbx
examples/models/json/pressure.json
examples/models/md2/ogro/Ogro.txt
examples/models/mmd/vmds/readme_wavefile_camera.txt
examples/models/obj/ninja/displacement.txt
examples/models/stl/ascii/slotted_disk.stl
examples/models/vtk/bunny.vtk
examples/obj/camaro/.htaccess
examples/obj/cubes/cubes.mtl
examples/obj/cubes/cubes.obj
examples/obj/f50/.htaccess
examples/obj/gallardo/.htaccess
examples/obj/leeperrysmith/.htaccess
examples/obj/leeperrysmith/LeePerrySmith_License.txt
examples/obj/veyron/.htaccess
examples/textures/cube/Bridge2/readme.txt
examples/textures/cube/Park2/readme.txt
examples/textures/cube/Park3Med/readme.txt
examples/textures/cube/SwedishRoyalCastle/readme.txt
examples/webgl_buffergeometry_instancing.html
examples/webgl_buffergeometry_instancing_billboards.html
examples/webgl_buffergeometry_instancing_dynamic.html
examples/webgl_buffergeometry_instancing_interleaved_dynamic.html
examples/webgl_buffergeometry_instancing2.html
examples/webgl_camera.html
examples/webgl_hdr.html
examples/webgl_loader_obj2_meshspray.html
examples/webgl_loader_obj2_options.html
examples/webgl_loader_texture_exr.html
examples/webgl_loader_texture_hdr.html
examples/webgl_loader_x.html
examples/webgl_materials_texture_manualmipmap.html
examples/webgl_modifier_subdivision.html
examples/webgl_modifier_tessellation.html
examples/webgl_morphnormals.html
examples/webgl_performance_doublesided.html
examples/webgl_postprocessing_smaa.html
examples/webgl_raycast_texture.html
examples/webgl_shaders_sky.html
examples/webgl_shaders_tonemapping.html
examples/webgl_test_memory.html
examples/webgl_test_memory2.html
examples/webvr_vive.html
examples/webvr_vive_dragging.html
examples/webvr_vive_paint.html
examples/webvr_vive_sculpt.html
test/unit/UnitTests.html
test/unit/unittests_editor_toRemoveAfterEditorES6Refactoring.html
```

##### Three.js version

- [x] Dev

##### OS

- [x] Windows

### PR DESCRIPTION
**Pull request by kaisalmen**
This resolves #13224

### CODE REVIEW

**Comment by kaisalmen** [comment]
Why do the checks always fail on me, la la lalala 😉 any idea?

**Comment by mrdoob** [comment]
Do you mind doing it again? Seems like a PR I just merged it's already conflicting 😇

**Comment by kaisalmen** [comment]
Try again... 👍

**Comment by mrdoob** [comment]
Applied the global dox2unix locally. 3bcb9c2d0db2799a54835aa4c3b18f4bb7052533

**Comment by mrdoob** [comment]
Thanks!

**Comment by shi-yan** [comment]
Does Texture's constructor support Canvas element as its input?

https://gist.github.com/MAKIO135/eab7b74e85ed2be48eeb

https://stackoverflow.com/questions/12380072/threejs-render-text-in-canvas-as-texture-and-then-apply-to-a-plane

the document doesn't mention it at all.

**Pull request closed without merging**
