### PR TITLE
BufferGeometryUtils: Add MikkTSpace version of .computeTangents()

### PR DESCRIPTION
**Pull request by donmccurdy**
**Summary:** Adds a `computeTangents( geometry )` function to BufferGeometryUtils, implementing the [MikkTSpace](http://www.mikktspace.com/) standard for vertex tangents used with tangent space normal maps.

**Background:** Vertex tangents are used when baking normal maps, but often those original tangents are not included in the model itself. While a different method of computing tangents will usually look "close" to the right result, in some cases (particularly with mirrored UVs) you may see seams or other visual problems. The only way to completely avoid those problems is to use exactly the same vertex tangents as the normal map baker. For that purpose, MikkTSpace is the de facto standard — it is open source, widely used, and is designed to return the same tangents even when certain changes (like reordering vertices) have been made to the underlying geometry.

Currently this PR does _not_ remove the existing `geometry.computeTangents()` method. The new function is added to BufferGeometryUtils instead, because the size of the MikkTSpace WASM module (from [`mikktspace-wasm`](https://github.com/donmccurdy/mikktspace-wasm)) is about 21 KB gzipped. 

Note that calculating vertex tangents is somewhat costly — on my machine it takes 75ms for the DamagedHelmet.glb sample. Any existing geometry index must be removed, although the index can be recomputed after generating tangents. For those reasons, most users probably should not blindly compute vertex tangents in the hope it will make their normal maps look better — where possible, compute tangents offline with tools like [`gltf-transform tangents`](https://gltf-transform.donmccurdy.com/cli.html) or Blender, and omit tangents when there's no benefit.

This PR also borrows a `denormalize()` function from #22874.

**Usage:**

```javascript
import { computeTangents } from 'three/examples/jsm/utils/BufferGeometryUtils.js';

geometry = computeTangents( geometry );
```

**Related:**

- https://github.com/mrdoob/three.js/pull/22816
- https://github.com/mrdoob/three.js/issues/18565
- https://github.com/mrdoob/three.js/issues/20997
- https://github.com/mrdoob/three.js/issues/17804
- https://github.com/mrdoob/three.js/issues/15850
- https://github.com/mrdoob/three.js/issues/15428
- https://github.com/mrdoob/three.js/issues/11438

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by donmccurdy** [comment]
One other note – the build script will skip `mikktspace.module.js`, leaving `examples/js/utils/BufferGeometryUtils.js` depending on an undefined global `generateTangents` function when used from the `examples/js/*` directory. So users not importing ES Modules would need to define that with a modified build of the `mikktspace` npm package. The package only publishes CJS (for Node.js) and ES Module builds currently.

**Comment by gkjohnson** [comment]
This would be nice to get merged. I'd like to use it for my [path tracing work](https://github.com/gkjohnson/three-gpu-pathtracer) for meshes with normal maps that don't already have tangents generated. I'm looking at other ways to generate them as-needed in the shader but this would be a good start.

Would like to see it in the next release 😁 🙏

**Comment by mrdoob** [comment]
Thanks!

**Comment by gkjohnson** [comment]
Looks like this doesn't work with bundlers that don't support top level await at the moment... which Parcel doesn't, at least (argh!)

https://github.com/parcel-bundler/parcel/issues/4028

**Comment by gkjohnson** [comment]
Oh... which actually means that `BufferGeometryUtils` can't be imported into a project at all without breaking it in one of these bundlers.

**Comment by donmccurdy** [comment]
> Oh... which actually means that BufferGeometryUtils can't be imported into a project at all without breaking it in one of these bundlers...

Hm, BufferGeometryUtils is all individual exports now — is methods other than `computeTangents` broken in Parcel as well?

```js
import { mergeBufferGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
```

> Looks like this doesn't work with bundlers that don't support top level await at the moment... 

Ugh, I thought top-level await was just part of the ES Modules spec. 🤦‍♂️ I don't suppose dynamic imports or .wasm imports are better supported? Would rather not do the Base64 decode and WASM instantiation synchronously on the main thread... I guess our other option would be to make the MikkTSpace dependency explicit:

```js
import { MikkTSpace } from '../libs/mikktspace.module.js';
import { computeTangents } from 'three/examples/jsm/utils/BufferGeometryUtils.js';

async function someUserCode() {

  await MikkTSpace.ready;
 
  // ...

  geometry = computeTangents( geometry, MikkTSpace );

}
```

Also note — there's currently a bug with non-indexed geometry, https://github.com/mrdoob/three.js/issues/23795.

**Comment by LeviPesin** [comment]
> Ugh, I thought top-level await was just part of the ES Modules spec. 🤦‍♂️ I don't suppose dynamic imports or .wasm imports are better supported?

I think that dynamic imports (if you are talking about `import()`) they are supported in pretty much everywhere.

**Comment by donmccurdy** [comment]
In browsers, yes — but like top-level await it will also depend on your bundler to rewrite URLs correctly. I guess in this case it doesn't matter, we probably want `computeTangents` itself to be synchronous, so we couldn't put in a dynamic import. Unless/until importing .wasm files directly is widely supported, let's do the userland `await MikkTSpace.ready;` option?

**Comment by gkjohnson** [comment]
I'm okay with `MikkTSpace.ready`.

**Pull request merged**
