### PR TITLE
TS: fix CompressedTextureLoader.d.ts

### PR DESCRIPTION
**Pull request by linbingquan**
related: #20370

### CODE REVIEW

**Comment by linbingquan** [comment]
I am confused, I see the function is return `CompressedTexture`.

https://github.com/mrdoob/three.js/blob/538533d0688e95ffbe3c6a943032be55dc74b4f8/examples/jsm/loaders/KTX2Loader.js#L124-L156

**Comment by Mugen87** [comment]
Why is this confusing for you^^?

**Comment by linbingquan** [comment]
> Why is this confusing for you^^?

Excuse me, This PR changed is right  now?

and you want me to commit this change like it.

```diff
diff --git a/examples/jsm/loaders/KTX2Loader.d.ts b/examples/jsm/loaders/KTX2Loader.d.ts
index 1f1d25867..4a0c84ba7 100644
--- a/examples/jsm/loaders/KTX2Loader.d.ts
+++ b/examples/jsm/loaders/KTX2Loader.d.ts
@@ -17,7 +17,7 @@ export class KTX2Loader extends CompressedTextureLoader {
 		onLoad: ( texture: CompressedTexture ) => void,
 		onProgress?: ( event: ProgressEvent ) => void,
 		onError?: ( event: ErrorEvent ) => void
-	): CompressedTexture;
+	): void;
 
 	parse(
 		buffer: ArrayBuffer,
```

**Comment by Mugen87** [comment]
No, you can delete the entire method definition. Because it's identical to its upper class.

**Comment by linbingquan** [comment]
> No, you can delete the entire method definition. Because it's identical to its upper class.

Thanks for your reply.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
