### PR TITLE
Manual: Improve compatibility with import maps.

### LINKED ISSUE #23363: examples/jsm files import change broke https://threejs.org hot-linking and code samples in the manual
**Describe the bug**

This has broken a lot of stuff but in my local repo, and some in the official examples.

Getting:

```
Uncaught typeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./". or "../"
```

I'm running chrome on windows.

Spent a lot of time wondering about this until I saw another user with the same problem...  Now I'm seeing that the addition of the new polyfill by looking at the examples and perusing the threads:

```html
<!-- Import maps polyfill -->
<!-- Remove this when import maps will be widely supported -->
<script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>

<script type="importmap">
	{
		"imports": {
			"three": "../build/three.module.js"
		}
	}
</script>
```

Is this documented anywhere? 

Also, can this shim at least pulled into the threejs repo until it's stable/widespread? It seems problematic to have the library now *require* a quiet import from some random external CDN.

Looking here, seems to indicate it breaks every browser except chrome/opera ??

https://caniuse.com/import-maps

Can someone explain to me what value this change brings to the ecosystem to justify its adoption before its supported in all browsers?

From what I can tell, it basically takes a shotgun to the ecosystem of codepen/glitch/jsfiddle examples that already exist that rely on the existing behavior.

Is there a way to automatically pull in the shim on import of three.module.js for browsers without support, without requiring everyone to manually add the shim to their html?

I burned an evening trying to work around this, thinking that it was some new/updated chrome restriction.

Now I'm seeing other people having this issue.

```js
import * as SkeletonUtils from 'https://threejs.org/examples/jsm/examples/SkeletonUtils.js';
```

***Live example***

The codepen examples on this manual page are broken: (https://threejs.org/manual/#en/load-obj)

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #23363.

**Description**

This PR fixes the examples of the manual. They should work standalone and in the editor view again.

The script export to sites like jsfiddle is not yet fixed. I've hidden the export button until this feature works again.

@greggman Your pointers were really helpful! I've tried to make the changes to `editor.js` and `editor-settings.js` as simple as possible. There are surely more smart solutions but at least the examples should work again.

### CODE REVIEW

**Comment by greggman** [comment]
If that works that's great!

I tried to make a more generic change here (ie, not hardcoding 'three'): 

https://github.com/greggman/three.js/tree/fix-live-editor-for-r137

**Comment by greggman** [comment]
It will be more work to make it export. (I guess skydev no longer works with r137? ... not sure)

**Comment by mrdoob** [comment]
Cherry-picked in `master`.

**Comment by mrdoob** [comment]
Looks like @ycw is looking into it too:
https://github.com/ycw/three.js/commits/manual-fix

**Pull request closed without merging**
