### PR TITLE
GridHelper: Simplify .clone()

### PR DESCRIPTION
**Pull request by Mugen87**
Much nicer and more correct 😇

### CODE REVIEW

**Comment by mrdoob** [comment]
What do we need `parameters` for then? 😛

**Comment by Mugen87** [comment]
I thought it might be useful to retain the information how the helper was generated. Besides, if you want to serialize the helper, it's not necessary to save the entire geometry but just the parameters (similar to the geometry generators).

**Comment by Mugen87** [comment]
If you like, we can remove `parameters` and make `size`, `divisions` etc. real properties. I mean assign them directly to `this` in the ctor. I think both approaches are okay.

**Comment by mrdoob** [comment]
> I thought it might be useful to retain the information how the helper was generated. Besides, if you want to serialize the helper, it's not necessary to save the entire geometry but just the parameters (similar to the geometry generators) 😇

That's a different problem though. And if we did that we would have to do it for all the helpers... we should leave that for a later time. Better to focus on fixing `copy()`/`clone()` for now.

**Comment by mrdoob** [comment]
Fixed caa62466fbb5c75bc59ad96bdd83bf92902db5fb.

**Comment by mrdoob** [comment]
I just was worry that we're opening a whole new can of worms while we're closing one 😅

**Comment by Mugen87** [comment]
Fair enough 😊

**Pull request merged**
