### PR TITLE
Fix an issue where buffers don't get deleted

### PR DESCRIPTION
**Pull request by gero3**
partial fix for #6729

Make sure buffers get deleted

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, this seems a bit entangled. I'll think about the issue.

**Comment by gero3** [comment]
I can update the system to make sure that attribaute sare only accessed from webglGeometries which is where they belong.

**Comment by dubejf** [comment]
I just noticed that this tackles the same problem as #6875, but is more aggressive about deleting buffers.

**Comment by mrdoob** [comment]
Ended up merging this one too. Thanks @gero3!

**Comment by mrdoob** [comment]
Hmm... I think attributes could benefit of some clean up. The code for them is now spread around `WebGLObjects` and `WebGLGeometries`. Maybe it could be nice to have a `WebGLAttributes` class?

**Comment by dubejf** [comment]
Geat! I was concerned that deleting the attribute buffers in `onGeometryDispose` would wreck havoc when a `BufferGeometry` is used by multiple meshes, but the buffers are recreated automatically. This is good.

**Pull request merged**
