### PR TITLE
FBXLoader: Removed unused Binary Reader methods

### PR DESCRIPTION
**Pull request by looeee**
The binary reader implemented all the DataView.getXXX methods even though many of them are not needed - removed the unused methods here. 

EDIT: Oops, BinaryReader, not BinaryParser

### CODE REVIEW

**Comment by looeee** [comment]
@donmccurdy this would be a good time to rename the methods as well - do you have any suggestions?

**Comment by donmccurdy** [comment]
I think`get____List()` or `getArrayOf____()` would minimize the chance of misreading. Or since `getUint64Array()` is gone now, just having each method return typed arrays would be consistent.

**Comment by looeee** [comment]
`getArrayOf____()` sounds good to me. 

They need to return normal arrays since these are expected throughout the rest of the file.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
