### PR TITLE
New FBXLoader w/ Unindexed Buffer Geometry

### PR DESCRIPTION
**Pull request by Kyle-Larson**
Did a complete overhaul of the FBXLoader and made the following changes
- FBXLoader now returns `BufferGeometry` instead of `Geometry`.
- `BufferGeometry` is unindexed, to allow multiple normals and UVs per vertex, for correct UV seams and normals ( see #10546 ).
- Scene graph is now properly generated based on FBX exported scene graph.
- Animations are now applied on a per-FBX-scene basis, which is how they are treated when they are exported from Maya / Blender / other programs.
- Animations are not only applied to skeleton-based deformers anymore, `Object3D`'s may now be animated.

There are some side effects of the loader that are present in the end `THREE.Group` that is delivered from the loader.
- `THREE.Group` has `.animations` with the Animation Clips loaded from the FBX.
- Each object has an FBX_ID attached with the internal ID from the exported file representing the object.
- `THREE.Group` has `{ skeleton: { bones: [ THREE.Object3D ] } }` attached for animations to work (Animation parsing required this object path in order to animate a non-skeleton scene graph).

One last change I made was that the NURBSCurve is not exported into the `.userData` of the `THREE.Group`.  I thought this was a very specific use case of the userData, and it didn't make much sense to keep userData for getting the curves instead of just traversing the scene graph to find the curves.  NURBSCurve is still exported and displays in the scene graph, but the `userData` object is removed.

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks!

**Comment by takahirox** [comment]
Just curious to know why the name is `FBXLoader2`?
How/When will existing `FBXLoader` and new `FBXLoader2` be merged?
(Or replace `FBXLoader` with `FBXLoader2`)

I've been working on Binary format FBX.
Should I work with new `FBXLoader2`, not existing `FBXLoader`?

**Comment by mrdoob** [comment]
It usually gets replaced when the second version supports all the features the first version supports.

**Comment by Kyle-Larson** [comment]
I decided to make `FBXLoader2` instead of changing the existing file for the following reasons:
- The entire parser had to be re-written.  The entire structure was based around indexed buffers when I had to make unindexed buffers, so almost all of the parsing functions had to be rewritten.  As far as workspace stuff goes, I wanted to work in a clean file with reference to the old file rather than editing in-file.
- There's upsides and downsides to either implementation.  This new implementation fixes issues with polygonVertices differing in UV / Normal data, but the old implementation takes advantage of index buffers.  I didn't feel comfortable completely replacing one file with the other, so we have it as 2 files for now.
- The new FBXLoader is still slightly experimental.  It hasn't been tested as extensively as the old one has, so it would be nice to have the new one around a bit longer before replacing the old one.
- The new FBXLoader returns an object with a different system for animations, so legacy code will probably still want the old loader around for use.  In a major versioning update, we can consider removing the old loader in favor of the new one.

**Comment by Kyle-Larson** [comment]
@takahirox If your binary loading system can generate the same FBXNode that the original FBXLoader uses, then it will also work with the new FBXLoader.  Ideally we separate the file parsing logic from the interpretation logic, so the structure of the FBXNode hasn't changed, only the interpretation of it.

**Comment by takahirox** [comment]
I see I see, thanks guys!

**Comment by dougajmcdonald** [comment]
Hi @Kyle-Larson have I gone mad? I'm looking here and not seeing the loader anymore: https://github.com/mrdoob/three.js/tree/master/src/loaders

**Comment by Mugen87** [comment]
Look at: https://github.com/mrdoob/three.js/tree/master/examples/js/loaders

**Comment by dougajmcdonald** [comment]
@Mugen87 Interesting, I'm trying to get my head round what's where. Does this imply that I need to grab the loader separately? I'd have expected it to be in the src. The 85 release on NPM gives me `Uncaught TypeError: THREE.FBXLoader is not a constructor` but other bits of three are loading OK.

**Comment by Mugen87** [comment]
> Does this imply that I need to grab the loader separately?

Yes. Also see see https://github.com/mrdoob/three.js/issues/11201#issuecomment-295747067

**Comment by dougajmcdonald** [comment]
@Mugen87 Thanks very much, that makes sense I'll grab the files separately.

**Pull request merged**
