### PR TITLE
Restore LightShadow export for now.

### PR DESCRIPTION
**Pull request by Mugen87**
@WestLangley You're right. Let's be safe here for now.

see https://github.com/mrdoob/three.js/issues/20109#issuecomment-677978968

### CODE REVIEW

**Comment by Mugen87** [comment]
>  I don't see a reason these classes should be recreated.

Let me clarify one point I have originally overlooked when removing `LightShadow` from the public API: It was highlighted in #20109 that after the removal the fov of the shadow camera is now coupled to the spot light's angle. Since doing this
```js
spotLight.shadow.camera.fov = 45;
```
never had an effect, the "workaround" was to create a custom instance of `LightShadow`.

If you want to keep the angle/fov coupling, I suggest we highlight this in the documentation. Or we are looking for an API that let the user disable the auto fov. 

One idea that comes in my mind is to add something like `SpotLightShadow.autoFOV` with default to `true`. If disabled, user can set `spotLight.shadow.camera.fov` which is evaluated like so in `SpotLightShadow.updateMatrices()`:
```js
const fov = ( this.autoFOV ) ? MathUtils.RAD2DEG * 2 * light.angle : camera.fov;
```

**Comment by mrdoob** [comment]
Hmm, seems like I can't reopen this PR.

**Comment by Mugen87** [comment]
Sorry, I've force-pused the branch^^. Should I make a new PR with restoring `LightShadow`?

**Comment by mrdoob** [comment]
Yes please 🙏

**Comment by Mugen87** [comment]
Done! 😊

**Comment by GerfriedC** [comment]
Not funny, I had compiled an animation of the shadow over the day using such code and now it is broken. Any other example how to simulate wandering shadows?

**Comment by mrdoob** [comment]
@GerfriedC Could you elaborate your use case? Ideally in the [forum](https://discourse.threejs.org/)?

**Pull request closed without merging**
