### PR TITLE
Let ObjectLoader load extended PerspectiveCamera.

### PR DESCRIPTION
**Pull request by tschw**

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting approach...

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by tschw** [comment]
> Interesting approach...

Pretty much
```javascript
function CTor( settings ) {

    Object.assign( this, {
            propA: 10,
            propB: 'anotherDefault';
        }, settings );

}
```
but from the outside.

**Comment by mrdoob** [comment]
Continued... #8556 8556

**Pull request merged**
