### PR TITLE
FBXLoader: simplify FBXTree

### PR DESCRIPTION
**Pull request by looeee**
Brings the FBXTree returned by the Binary and Text parser closer to the actual FBX file structure and removes lots of unused entries (in particular blank `ID`s, `attrNames` and `attrTypes`). 

Removes `.properties` and `.subNodes` which were created by the parsers but not found in the original FBX structure.

Also cleaned up and simplified the parsers a bit.

### CODE REVIEW

**Comment by mrdoob** [comment]
Uops! Conflicts 😅

**Comment by looeee** [comment]
Seems like the addition of LoaderUtils is causing problems here - have the builds been updated to include  it?

**Comment by mrdoob** [comment]
Yep!

**Comment by looeee** [comment]
The issue I ran into previously was related to #12924. I'll sort out the conflicts now.

**Comment by looeee** [comment]
@mrdoob conflicts are resolved 👍

**Comment by mrdoob** [comment]
Seems like the `Filename` PR created conflicts again...

**Comment by looeee** [comment]
😅 

Resolved again

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
