### PR TITLE
Make loop unrolling completely whitespace-insensitive

### PR DESCRIPTION
**Pull request by yushijinhun**
This is just another #19726. Since #20012 is accepted, I think it's okay to make loop unrolling completely whitespace-insensitive.

### CODE REVIEW

**Comment by Mugen87** [comment]
TBH, I'm not a fan of salami tactics. My opinion still stands:

https://github.com/mrdoob/three.js/pull/19726#issuecomment-649476952

**Comment by mrdoob** [comment]
I'm undecided...
@yushijinhun how does your code look like?

**Comment by yushijinhun** [comment]
> I'm undecided...
> @yushijinhun how does your code look like?

I'm removing all unnecessary whitespaces from GLSL code to reduce bundle size.
So I hope the following style can be accepted:
```c
#pragma unroll_loop_start
for(int i=0;i<5;i++){k+=m[i];}
#pragma unroll_loop_end
```

**Comment by mrdoob** [comment]
Seems like there is no need to add `\s+` to `#pragma`s?

**Comment by yushijinhun** [comment]
> Seems like there is no need to add `\s+` to `#pragma`s?

Not quite necessary. I have removed them.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
