### PR TITLE
Added LogLuvLoader.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #22757

**Description**

This PR introduces `LogLuvLoader` which allows to load HDR images in the LogLuv TIFF format.

The code uses parts of `UTIF` for parsing TIFF images and a custom `toRGBA()` method to extract HDR texels in linear RGB color space. The default texture type is half float. Using single precision float is supported.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev59/examples/webgl_loader_texture_logluv.html

For comparison:

https://raw.githack.com/Mugen87/three.js/dev59/examples/webgl_loader_texture_rgbm.html
https://raw.githack.com/Mugen87/three.js/dev59/examples/webgl_loader_texture_hdr.html
https://raw.githack.com/Mugen87/three.js/dev59/examples/webgl_loader_texture_exr.html

**Comment by mrdoob** [comment]
Nice! Seems like the best way to compare them is to put the slider at 0.02. Logluv seems are nice looking as hdr but a bit more orangy.

**Comment by Mugen87** [comment]
BTW: The hue might shift depending on the feedback in https://github.com/mrdoob/three.js/issues/22757#issuecomment-971990536.

**Comment by Mugen87** [comment]
Using the matrix from the respective paper for now: http://www.anyhere.com/gward/papers/jgtpap1.pdf

**Comment by Mugen87** [comment]
Old (sRGB matrix): https://raw.githack.com/Mugen87/three.js/cb6ad7eaa231309bd6594c6ae594eea31ddc13e1/examples/webgl_loader_texture_logluv.html
New (CIE RGB matrix): https://raw.githack.com/Mugen87/three.js/8648a2d548bbd31507169782d39ac69eb07580f1/examples/webgl_loader_texture_logluv.html

**Comment by mrdoob** [comment]
Now it looks kind of pale... Is that normal?

**Comment by Mugen87** [comment]
TBH, I'm not yet 100% sure which color conversion matrix is the correct one. But according to the paper and `UTIF.js`s implementation it is the CIE RGB matrix. Let's wait with a merge until this detail is clear...

**Comment by Mugen87** [comment]
Wait, the numbers in the matrix was not correct. Now it looks better:

https://raw.githack.com/Mugen87/three.js/251f8e1748ebbeabdca1ae17e35a286b6a5cc7f2/examples/webgl_loader_texture_logluv.html

**Comment by WestLangley** [comment]
three.js does not currently handle color space accurately.

But. for the purpose of doing something reasonably-consistent, we can assume we want to convert to  linear-sRGB color space -- i.e., the sRGB primaries and the D65 white point, without the gamma correction.

So, I would assume the correct matrix to use is the sRGB matrix.

**Comment by Mugen87** [comment]
I don't think this would be correct. Sticking to the specification of the paper produces the result I have originally expected. Using the sRGB matrix produces a wrong hue shift.

**Comment by mrdoob** [comment]
Sounds like this is good enough for now 😊

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
