### PR TITLE
add geometry normalization

### PR DESCRIPTION
**Pull request by xizhonghua**
add THREE.Geometry.normalize().
make the geometry centered at (0,0,0) and has a unit radius bounding sphere.

documentation updated as well.

### CODE REVIEW

**Comment by WestLangley** [comment]
Yes, `Geometry.center()` is missing from the docs.

I am not sure about the method `Geometry.normalize()`, however. Centering a geometry is a common use case. I do not believe scaling a geometry to fit inside a unit sphere is common, however.

What is your use case?

**Comment by xizhonghua** [comment]
center and scale the geometry to have unit radius is a common preprocessing step in many geometric algorithms such as shape decomposition and shape retrieval in which we will measure soma properties (concavity, geodesic distance, etc) of the mesh, and set a threshold to have different behaviors based on the measure.  After scaling, we can use the same threshold for all the meshes to evaluate the performance of the algorithms no matter what's original size of the mesh, since the meshes could be from different sources and might not be scaled to the same size.

Also it helps to setup the lights and camera position, which don't need to be changed when load and render different models in single model applications.

**Comment by xizhonghua** [comment]
Currently I'm doing mesh inflation, a typical single model application as mentioned above.
http://masc.cs.gmu.edu/origami/inflation.html
You can drop any OBJ file onto the canvas and press space to inflate.

**Comment by mrdoob** [comment]
Do you mind doing a new PR but targeting the `dev` branch instead?

**Comment by mrdoob** [comment]
#6565

**Pull request closed without merging**
