### PR TITLE
Enable accessing accessors[0] in GLTF2Loader for indices, textures, and skin

### PR DESCRIPTION
**Pull request by takahirox**
This PR fixes zero value `mesh.primitive.indices` issue in `GLTF(2)Loader`.
This change enables `GLTF2Loader` to load gltf 2.0 simple box model.

https://github.com/cx20/gltf-test/tree/2.0

In glTF 2.0, `accessors` became an array so accessing id will be equal to or greater than 0 integer.

    if ( primitive.indices )

will be false if `indices` is 0.
We should explicitly compare with `undefined`.

I think the same change is necessary in glTF 1.0 loader to access named "0" accessor.

Update:
I realized that this's glTF 2.0 specific issue because
glTF 1.0 `mesh.primitive.indices` is `strings` whose length is > 0.
`if ("0")` will be true, so only 2.0 loader needs to take care of it.

Update2:
I applied the same change to `texture.sampler/source` in `GLTF2Loader`.
This change enables it to load glTF 2.0 textured box in the like above.
`texture.sampler/source` props are required even in 1.0,
so we could remove `if (texture.sampler/source)` line.

### CODE REVIEW

**Comment by mrdoob** [comment]
@donmccurdy looks good?

**Comment by takahirox** [comment]
Let me apply the same change to `node.skin`

**Comment by donmccurdy** [comment]
Looks good to me!

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
