### PR TITLE
Added basic functionality to SVGLoader.

### PR DESCRIPTION
**Pull request by mrdoob**
Progress... #13478

screen shot 2018-03-17 at 03 07 09

### CODE REVIEW

**Comment by Mugen87** [comment]
When I zoom near the tiger, i can see a lot of z-fighting between the single faces. Setting `depthWrite` to `false` in the shape material solves the problem.

**Comment by mrdoob** [comment]
Yeah... Or disable `depthTest`? There is a few challenges with this one.

**Comment by Mugen87** [comment]
Um...if you just disable `depthWrite`, objects closer to the camera are still drawn correctly (they are overdrawn by the shapes). That's not the case with a disabled `depthTest`.

**Comment by mrdoob** [comment]
Worth a try!

**Comment by WestLangley** [comment]
@mrdoob I think you are going to have to ensure that the intended render order is maintained.

**Comment by mrdoob** [comment]
I think the nodes order in svg is already the intended render order. Unless someone is using z-index, but that's more of a html thing.

**Comment by WestLangley** [comment]
>I think the nodes order in svg is already the intended render order.

Right. But the renderer sorts objects by default. Perhaps it defaults to sorting by `id` in this case...

**Comment by mrdoob** [comment]
Yep!

**Pull request merged**
