### PR TITLE
Added getObjectsByname to Object3D

### PR DESCRIPTION
**Pull request by kishore25kumar**
https://github.com/mrdoob/three.js/issues/7350

### CODE REVIEW

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7351

**Comment by mrdoob** [comment]
Sorry, my intention was to provide you with the code that did what you wanted. I don't think it needs to be part of the library.

**Comment by kishore25kumar** [comment]
@mrdoob can i know the reason for this function not to be in the library

**Comment by mrdoob** [comment]
1. We have a 100kb budget
2. This seems very use case specific
3. The user has to write very few code.

If more people asks for it, number 2 can then be removed and we can reconsider.

**Pull request closed without merging**
