### PR TITLE
Light: Make scale immutable

### PR DESCRIPTION
**Pull request by mrdoob**
@WestLangley What do you think about making lights scale immutable?

### CODE REVIEW

**Comment by WestLangley** [comment]
Maybe, but I think most of the scaling problems will come from a light which is a child of a scaled object -- for example, headlights on a scaled car.

I am not aware of users scaling lights themselves.

**Comment by donmccurdy** [comment]
glTF does let the node scale affect lights, though not properties like range:

https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual#adding-light-instances-to-nodes

**Comment by WestLangley** [comment]
Yes, the glTF spec says

>The light's transform is affected by the node's world scale, but all properties of the light (such as range and intensity) are unaffected.

Similarly, in three.js, the _size_ of the rect area light is not affected.

**Comment by mrdoob** [comment]
Hmm, yeah... This doesn't solve much.
Thanks for the feedback!

**Pull request closed without merging**
