### PR TITLE
Adds blender exporter option to toggle compact separators output

### PR DESCRIPTION
**Pull request by jorgenfb**
This change will enable smaller file size for exported models from blender, which of course matters on the web.

It adds the option to use compact separators in the exported JSON output. When enabled it will set JSON key separator to `': '` and JSON value separator to `','`. When disabled the default separators (`': '` and `', '`) is used. Example output:

Old / default output:

```
{"matrix": [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]}
```

New output (when enabled):

```
{"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}
```

The compact option reduces the generated file size considerably. I tested three models:

4888757 bytes => 4090855 bytes, a 16 % reduction, 3 % when zipped
3883955 bytes => 4644569 bytes, a 16 % reduction, 3 % when zipped
3295633 bytes => 3940764 bytes, a 16 % reduction, 3 % when zipped

I also tried lowering the precision of the output, and was able to get around 20 % reduction. Still around 3 % when compressed.

The default value is to disable this feature. Includes both a graphical interface and api option to toggle this feature.

### CODE REVIEW

**Comment by antont** [comment]
Why do you want an option for this? Instead of just doing compact output always. Seems that for vert arrays compact is always good .. perhaps you are worried about readability of other sections?

(also, always when seeing these works on worries with filesize & ascii data I wonder how many have tried or even considered the binary format options like glTF which has seemed pretty good to me .. but that's another story)

**Comment by jorgenfb** [comment]
Personally I would be happy to always output the compact format. The reason I made it optional and defaulting to "off" was because of the indent option defaulting to "on" which I assumed was to improve readability. I seems strange to have intent defaulting to "on" and compact separators to "off". I have no problem setting the setting manually (default settings can be saved in the interface).

I chose this format for different reasons. File size was not the primary reason, but it is still nice to have. I have actually tested multiple formats and glTF was one of them. Using the online converter to convert my collada file actually increased the file size compared to using the JSON format.

**Comment by mrdoob** [comment]
I agree. I would just set this on by default. What does the indent option do?

**Comment by jorgenfb** [comment]
Indent option turns on indention for the exported JSON:
```
// with indent = True (the default)
{
    "geometries": [1, 2, 3, 4, 5, ...]
}

// with indent = False 
{"geometries": [1, 2, 3, 4, 5, ...]}

// with indent = False AND compact = True
{"geometries":[1,2,3,4,5...]}
```

I have updated the PR to remove the option to toggle it, since we all agree. Now the exporter always output the compact format.

I did not touch the indent option, but I would be happy to do it in another PR if it is of any interest.

**Comment by mrdoob** [comment]
Looks good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
