### PR TITLE
WebGLProgram: support cube uv refraction mapping

### LINKED ISSUE #19611: PMREM Refraction support
##### Description of the problem

PMREM seems to miss support for refraction mapping even though the mapping option `CubeUVRefractionMapping` exists.

Comparison between enabled refraction of Equirectangular vs PMREM:

firefox_2020-06-10_12-26-46
Equirectangular with `EquirectangularRefractionMapping`

firefox_2020-06-10_12-27-00
PMREM with `CubeUVRefractionMapping`

I extended the envmaps example to show the problem:
* [demo](https://deml.io/three/examples/webgl_materials_envmaps.html) (dev branch)
* [file](https://github.com/JohannesDeml/three.js/blob/test/pmrem-refraction/examples/webgl_materials_envmaps.html)

##### Three.js version

- [ x ] Dev
- [ x ] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by sciecode**
Fixes #19611

[cube_uv_envmaps_example](https://rawcdn.githack.com/sciecode/three.js/688b9d58334c4f6030bbbc8519c8ea9a725b9fdf/examples/webgl_materials_envmaps.html)

### CODE REVIEW

**Review by JohannesDeml — APPROVED** [review]
Awesome, I love easy fixes!

**Comment by Mugen87** [comment]
It should be clarify (if possible) why this change wasn't done in the first place. Also relevant: https://github.com/mrdoob/three.js/issues/19611#issuecomment-642318824

**Comment by WestLangley** [comment]
>It should be clarified (if possible) why this change wasn't done in the first place.

Possibly because our refraction model is inadequate. See the live link above. It is not even reasonably realistic.

**Comment by sciecode** [comment]
> It should be clarified (if possible) why this change wasn't done in the first place. 

I guess it is relevant to ping @elalish in that case.

> My guess is that this type of refraction does not play well with PBR models.

> Possibly because our refraction model is inadequate. See the live link above. It is not even reasonably realistic.

Refraction in the rasterizing pipeline is not a solved problem, there's no simple way of rendering refractive materials, especially in a single pass workflow was we are currently using.

The model we use is more about what can be done, instead of an approach for realistic refraction. We're only considering the front face surface of the object and simulating refraction only in that surface, but even that is still not completely correct, as we are not assuming a complex index of refraction and the effect of dielectrics ( and all that fun stuff ).
 
It is possible to make it slightly better if we try a multiple depth & normal passes pipeline ( cubemap ) for having a better prediction of how the light being refracted will behave after passing to the interior of the volume. It will look better, but it will still not be photo realistic, simply because we it can't be. The interactions of refractive surfaces are way too recursive in nature to be correctly rendered in the rasterizing pipeline.

> Related: Does GLTF support refraction?
@mrdoob It does not. They are still considering if it that is something they want to venture in for GLTF 2.0 spec, but it is sitting as "possible" thing. In reality, I don't think it will ever be.

With all of that being said, I still think that if a user is requesting support for something that is entirely possible in our current pipeline, even if it is not realistic, and it involves such a simple fix, we have no reason not to support it.

**Comment by JohannesDeml** [comment]
To get a better understanding of the parameters I exposed roughness and refractionRatio: [demo](https://rawcdn.githack.com/johannesdeml/three.js/4db265b353f2719492b08a6c4069f5b8b951bd19/examples/webgl_materials_envmaps.html)

For me it was just very strange to have that constant, but not the result I was expecting. Sadly the  resolution of the PMREM texture is not that high, which is very apparent for refractions.

**Comment by sciecode** [comment]
> Sadly the resolution of the PMREM texture is not that high.

This is something I'm looking to tackle soon, I just need to find the time for it. We had discussed previously that allowing the user control of the texture resolution is something that we should probably do.

**Comment by elalish** [comment]
The only reason I didn't do this in the first place was that I had no refractive models to test with and I didn't want to cause any regressions. I think this is a good idea; it may not be accurate, but it's better than nothing. Kind of like soft shadows; their absence is noticeable, but their accuracy is generally not. 

As for glTF and refraction, this is actually under very active discussion in the working group. Hopefully before long we will have extensions for a configurable IOR and even a "thickness texture", which kind of like AO, will allow real-time rasterizers to do a halfway decent job of refraction and absorption calculations that would otherwise require raytracing.

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
Sorry, I have not seen any transparent metals. That is what your example is using.

Can you demonstrate that this works when metalness = 0? You may need to test both `MeshStandardMaterial` and `MeshPhysicalMaterial` given that `Physical` has the additional `transparency` property.

**Comment by sciecode** [comment]
> Sorry, I have not seen any transparent metals. That is what your example is using.
> Can you demonstrate that this works when metalness = 0?

I'm sorry, I copied the example given in the issue, but I did not notice he was applying the refractive envmap to a `MeshStandardMaterial`. I should have checked that.

It appears the refractive mappings in general are only correctly considered when using `MeshLambertMaterial` or `MeshPhongMaterial` or with metalness 1 in for the PBR materials ( standard / physical ).

But this is an issue outside of the scope of this PR, to be honest. This PR just ensures that WebGLProgram correctly understands `CubeUVRefractionMapping` as a refractive map and correctly sets the appropriated define for the shaders.

**Comment by WestLangley** [comment]
Let's see a live demo before considering merging this.

**Comment by JohannesDeml** [comment]
> Sorry, I have not seen any transparent metals. That is what your example is using.

That is my fault. When I tried to get it working, I used metals, since reflections are way more visible there. Here is the updated example: [Demo](https://rawcdn.githack.com/johannesdeml/three.js/d781d11c0fccacee67f5c39ad43a89a639512b00/examples/webgl_materials_envmaps.html)

**Comment by lm199406** [comment]
你是从哪里看到的信息发送给我的？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Johannes Deml"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午3:16
收件人： &nbsp;“ mrdoob / three.js” <three.js@noreply.github.com&gt;;
抄送： &nbsp;“ Subscribed” <subscribed@noreply.github.com&gt;;
主题： &nbsp;回复：[mrdoob / three.js] WebGLProgram：支持多维数据集uv反射映射（＃19623）





  
抱歉，我没有看到任何透明金属。这就是您的示例所使用的。
  
那是我的错 当我尝试使其工作时，我使用了金属，因为反射在该处更明显。这是更新的示例：演示
  
— 
您收到此消息是因为您已订阅此线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by sciecode** [comment]
> Let's see a live demo before considering merging this.

[standard_physical_refraction](https://rawcdn.githack.com/sciecode/three.js/c43254c387e0f1734dade974c8440edf0f6e534a/examples/webgl_materials_envmaps.html) left is standard, right is physical

Just to be absolutely clear, this behavior is not exclusive to case `CubeUVRefractionMapping`.
It already happens in dev with `CubeRefractionMapping` and `EquirectangularRefractionMapping`

**Comment by sciecode** [comment]
> > Sadly the resolution of the PMREM texture is not that high.
> 
> This is something I'm looking to tackle soon, I just need to find the time for it. We had discussed previously that allowing the user control of the texture resolution is something that we should probably do.

@elalish I wanted to run some things by you regarding this functionality. Would it be possible to contact you somewhere else? ( twitter maybe? @sciecode ) Just to make sure that we are on the same page regarding how to introduce support for variable texture sizes.

**Comment by JohannesDeml** [comment]
After taking a closer look at the results again, there is one inconsistency for me with refraction in the standard and physical material when metalness is set to 0. The fresnel, which makes a lot of sense for reflection does not make any sense (at least I think so) for refraction. I think the result would need to look like metalness 1.0 for refraction, for which you see the pure refraction without any fresnel effect. Of course, going one step further it would be nice to have a fresnel reflection and a pure refraction on the material.

Here is the current effect with metalness 0:
image

and this is a changed version with fresnel reflection + refraction with metalness 0:
image

Here is the live example with reflections + refractions: https://rawcdn.githack.com/johannesdeml/three.js/6e57f55b3f3af594dcd23f6fb89ccbfb2dbda5f0/examples/webgl_materials_envmaps.html

Not sure if this is a path you want to go, or if you want to wait for gltf to define ior and then implement a general solution.

**Comment by Mugen87** [comment]
Regarding https://github.com/mrdoob/three.js/pull/19623#issuecomment-644195529, is it still desirable to merge this PR?

**Comment by sciecode** [comment]
> Regarding [#19623 (comment)](https://github.com/mrdoob/three.js/pull/19623#issuecomment-644195529), is it still desirable to merge this PR?
> 
> If not, it might be better to remove `CubeUVRefractionMapping` for now since it has no effect anyway.

Not sure to be honest, as I mentioned, the refraction map will really only work reliably with metalness = 1.0.
But, as correctly pointed out by @JohannesDeml, we lose the ability to represent the fresnel correctly.

Ideally we would want both things to happen for PBR materials, but it is tricky.

`CubeUVRefractionMapping` would still work, more or less, as expected for other materials, but it does have a lot of problems in its current form, much like the `CubeRefractionMapping`. I'm not attached to this PR in the slightest, I leave this decision to you guys.

**Comment by mrdoob** [comment]
I think incorrect is better than nothing 🤔

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
