### PR TITLE
Node: Add `SobelOperatorNode`.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This PR adds Sobel edge detection for `WebGPURenderer`.

### CODE REVIEW

**Comment by RenaudRohlinger** [comment]
Splendid. 👏

**Comment by Mugen87** [comment]
@RenaudRohlinger @sunag I want to make a `DepthOfFieldNode` via porting a bokeh shader. For that I need to sample the scene's depth in the pass which will also be required for a series of other effects like AO.

I've tried doing this:
```js
const scenePass = pass( scene, camera );

const scenePassColor = scenePass.getTextureNode();
const scenePassViewZ = scenePass.getViewZNode();

postProcessing.outputNode = scenePassColor.dof( scenePassViewZ, camera, focus, apeture, maxBlur );
```
In the DOF node, I access the viewZ in the TSL code but unfortunately get a `Maximum call stack size exceeded` error. 

Do I perform the setup incorrectly? How does a minimal FX pass look like which samples viewZ from a scene pass?

**Comment by Mugen87** [comment]
For reference here is the full code: https://github.com/Mugen87/three.js/commit/f117497aa28a1326d8fb7fe306a04936718f94c0

If I replace `const factor = this.focus.add( this.viewZNode );` with `const factor = this.focus.add( 1.0 );` in `DepthOfFieldNode`, the runtime error disappears.

**Comment by RenaudRohlinger** [comment]
For this you should use `getTextureDepthNode()` I think. I made an AO Node a while ago using it.

And then if necessary:
```js
perspectiveDepthToViewZ(
    yourDepth,
    cameraNear,
    cameraFar
 )
 ```
 Also I might not be up to date with https://github.com/mrdoob/three.js/pull/28720, the logic might have changed.

**Comment by Mugen87** [comment]
It seems `getViewZNode()` from `PassNode` should do the exact same thing. The great thing about this method is that I would not need a reference to the camera in the DOF node. 

> Also I'm not sure anymore, with https://github.com/mrdoob/three.js/pull/28720 this logic might have changed.

Right, let's see what @sunag says about `getViewZNode()`.

**Comment by sunag** [comment]
@Mugen87 Maybe it's something else, `getViewZNode()` seems right. I will clone you code here for check.

**Comment by sunag** [comment]
https://github.com/Mugen87/three.js/commit/f117497aa28a1326d8fb7fe306a04936718f94c0#r143473219 This fix the error but even so don't show the dof effect...

**Comment by sunag** [comment]
@Mugen87 It's cache related try replace sampleTexture to:

```js
const sampleTexture = ( uv ) => this.textureNode.uv( uv );
```

image

**Comment by Mugen87** [comment]
Now it works! Thanks for the support^^.

Latest commit: https://github.com/Mugen87/three.js/commit/0669cf47e3487ee492830f2d85919541c388e773

Live example: https://rawcdn.githack.com/Mugen87/three.js/0669cf47e3487ee492830f2d85919541c388e773/examples/webgpu_postprocessing_dof.html

I'll file a PR tomorrow!

**Pull request merged**
