### PR TITLE
VRMLLoader: Basic support for Extrusion.

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adds basic support for the `Extrusion` node. Not yet supported are texture coordinates and extrusion paths different from `(0, 1, 0)`. But the already supported features are definitely interesting 🤓.

Room             |  Pyramide | Twisted Shape
:-------------------------:|:-------------------------:|:-------------------------:
image | image | image

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Where can we see this in action?

**Comment by mrdoob** [comment]
I guess we could update `webgl_loader_vrml` with a dropdown to load the different vrmls we have now?

**Comment by Mugen87** [comment]
Yeah, good idea! 

BTW: The above assets are already part of the repo.

**Pull request merged**
