### PR TITLE
Matcap Shader

### PR DESCRIPTION
**Pull request by Halocom**
A shader file for creating matcap effect

### CODE REVIEW

**Comment by haroldiedema** [comment]
Can we see a live example of this?

**Comment by Halocom** [comment]
the code has been been taken from here : https://github.com/msfeldstein/three-matcap-material
a demo has been made here : https://www.clicktorelease.com/code/spherical-environment-mapping/
and source of matcap images could been downloaded here for testing : https://sespider.deviantart.com/art/163-FREE-MatCaps-258893793

**Comment by Mugen87** [comment]
TBH, I don't see a benefit of adding this code to the repo...

**Comment by Halocom** [comment]
@Mugen87 if you have a solution for displaying an object with a matcap image in three.js as three.js is actually, so yes : no benefit ! but actually in three.js i don't find any simple way for doing this...

**Comment by Halocom** [comment]
it's just about sharing and use the shader quickly inside three.js

**Comment by WestLangley** [comment]
Yes, three.js should support matcaps or lit-spheres natively.

Try
```javascript
var envMap = loader.load( 'matcap.jpg' );

envMap.mapping = THREE.SphericalReflectionMapping;

var material = new THREE.MeshBasicMaterial( { envMap : envMap } );
```

Note: I believe there is a problem with the current implementation, but that is a debate for another thread.

**Comment by Halocom** [comment]
@WestLangley  thank you !!! so cool, i didn't know this technique for creating matcap effects ! 
This pull can be close ;-)

**Pull request closed without merging**
