### PR TITLE
Add option to prevent vr from auto submitting frame on render

### PR DESCRIPTION
**Pull request by joshpatt2**
Right now the Renderer auto submit frames.  This breaks usage of the stencil buffer which requires multiple renders.  I'm adding a flag to turn of auto submit frame.

This is a fix for
#13967

### CODE REVIEW

**Comment by joshpatt2** [comment]
Sorry, looks like when i updated this i messed up the formatting.  I'm a way on holidays for 8 days but will fix it when i get back :)

**Comment by mrdoob** [comment]
Hmm, any way you could do a jsfiddle showing what your use case is?

**Comment by joshpatt2** [comment]
@mrdoob sure thing, working on it now :)

**Comment by joshpatt2** [comment]
@mrdoob  - https://jsfiddle.net/wm0ah2zd/1/

**Comment by joshpatt2** [comment]
@mrdoob  anything else needed to land this pull request?

**Comment by joshpatt2** [comment]
@mrdoob looks like this keeps getting moved, any reason it can't go into the next revision? I keep having to upgrade my copy when ever i update (I'm using this for Facebook's WebVR support for 3D photos)

**Comment by Mugen87** [comment]
Closing since `WebVRManager` has been removed and `WebXRManager` does not have a `submitFrame()` method. So #13967 needs a different fix.

**Pull request closed without merging**
