### PR TITLE
Catch more d.ts error with the Typescript Compiler

### PR DESCRIPTION
**Pull request by gkjohnson**
Add more linting and error checking to the `d.ts` files by using the `tsc` typescript compiler.

At the moment `tsc` does not support file globs so it's difficult to globally check all files (such as examples), but the `src/Three.d.ts` file seems to cover all of the core definitions for now. Maybe someone has some ideas on how to cleanly add globs to npm the script?

Related to https://github.com/mrdoob/three.js/issues/16926#issuecomment-506363792

### CODE REVIEW

**Comment by Mugen87** [comment]
Will this change allow to detect errors like #16918?

**Comment by gkjohnson** [comment]
Yeah it will catch those errors and more. You can test this by deleting the `BufferGeometry` and `Geometry` imports at the top of that file and running the linter. Using the typescript compiler for these cases is what was suggested by the typescript-eslint team: https://github.com/typescript-eslint/typescript-eslint/issues/662

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Let's give this a try 😊

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
