### PR TITLE
Examples: Inline small utility methods for examples/js

### PR DESCRIPTION
**Pull request by donmccurdy**
Currently there appear to be two choices for files in `examples/{js,jsm}` that depend on utilities like BufferGeometryUtils or WorkerPool:

- (A) Copy/paste the necessary methods
  - Duplicates the code; harder to maintain.
- (B) `import * as BufferGeometryUtils`
  - Results in larger bundles for ESM users, and requires CJS/UMD users to manually import the utils file.

I think we could improve things a bit by allowing Rollup to inline methods from certain utility files when it compiles the `examples/js` versions. This means ESM users get strictly smaller bundles, and CJS/UMD users will have a better developer experience and *usually* get smaller bundles, although some duplication is still possible there if loading multiple files that depend on the same utilities. Particularly for the ESM  benefits I think that's a good tradeoff.

The main side-effect here is related to enabling `treeshake: 'recommended'`. Rollup tree-shakes a fair bit of dead code from existing examples, but I can't think of any downside to that.

### CODE REVIEW

**Comment by marcofugaro** [comment]
> import * as BufferGeometryUtils
> Results in larger bundles for ESM users,

What do you mean?

```js
import * as BufferGeometryUtils from 'three/examples/jsm/utils/BufferGeometryUtils.js'

console.log(BufferGeometryUtils.mergeVertices)
```

is transformed into

```js
function mergeVertices() {
  // ...
}

console.log(mergeVertices);
```

By any bundler, such as rollup with default build settings.

**Comment by donmccurdy** [comment]
Hm, `BufferGeometryUtils` is not being tree-shaken with `import * as BufferGeometryUtils`, but apparently not for the reason I thought. This check prevents it:

https://github.com/mrdoob/three.js/blob/604a9118e27df51d6b609e58e2161a4dfc609ba5/examples/jsm/modifiers/SimplifyModifier.js#L22-L26

**Comment by marcofugaro** [comment]
oh yeah, that check does not make sense in the modules world.

I think we can remove it, just like for `WorkerPool` in `KTX2Loader`, the error is enough to warn the user.

**Comment by donmccurdy** [comment]
We could, but can you say more about why? Does having these functions inlined in `examples/js` seem like a problem?

**Comment by marcofugaro** [comment]
> We could, but can you say more about why?

I was talking about `examples/jsm` these functions are unnecessary because a module will always be defined. Sorry I did not see you already removed them in this PR.

Regarding `example/js`, tested your PR, encountered no problem at all!
Just wanted to clarify that using `import * as BufferGeometryUtils` does not impact tree-shaking at all.

**Comment by donmccurdy** [comment]
Based on #23175, it sounds like this PR is micro-optimization in an area where larger changes would be better. Closing!

**Pull request closed without merging**
