### PR TITLE
Example: New Water Shader

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces a new shader that utilizes `THREE.Mirror` and `THREE.Refractor` in order to create a fully reflective and refractive water effect in real-time. The implementation is based on the following presentation of Valve: [Water Flow in Portal 2](http://www.valvesoftware.com/publications/2010/siggraph2010_vlachos_waterflow.pdf).

Not everything mentioned in the presentation is implemented. Supported features are:

- The flow of the water can be configured with a single `flowDirection` vector or a `flowMap`. This texture contains 2D flow vectors and allows fine control of the actual water flow. It is a color map and the following [image](https://cloud.githubusercontent.com/assets/12612165/20037569/76753df0-a422-11e6-9efb-e6f7c4e69cc2.png) of Valve illustrates the possible colors and their effect.
- The shader uses two normals maps instead of one and an offset approach to avoid the most visible parts of the "repetition problem" (same normals flow through the same part of the mesh).
- The shader uses a fresnel term to blend reflection and refraction maps in a natural way.

There are two new examples. The first one shows the general usage of the effect, the second one is focused on flow maps.

### CODE REVIEW

**Comment by Mugen87** [comment]
Of course you could add even more features to the shader but i think this is a good foundation for many applications. The current implementation is manageable and can easy be enhanced, depending on users requirements.

**Comment by mrdoob** [comment]
Very nice!

**Comment by mrdoob** [comment]
It's now tempting to rename `THREE.Mirror` to `THREE.Reflector`...

**Comment by Mugen87** [comment]
Yes, i think this name would be more consistent in view to `THREE.Refractor`.

**Comment by Mugen87** [comment]
But if we rename `THREE.Mirror` to `THREE.Reflector`, we should do this in a separate PR. This change is also backwards compatible.

**Comment by mrdoob** [comment]
Agreed!

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
The flow example is very cool 😄 

If you replaced the flow map with a circular gradient could you get a whirlpool type effect?

**Comment by Mugen87** [comment]
I'm actually not sure how this would look like 😅 . But basically a flow map allows many types of different water effects. 

BTW: A flow map can easily created by hand with Photoshop or Gimp. If you use soft brushes or blur filters, you can create nice transitions between colors and thus different flow directions. Hard changes between colors create an unnatural seam instead.

**Comment by tentone** [comment]
@looeee

Yeah a flow map basically encodes in the RG channels of the image the X, Y of the normalized vector that indicates direction of the water flow, (R=0.5 its X=0).
It should be fairly easy to create a whirlpool effect easily using these.

@Mugen87 

Thanks a lot this is awesome, i might even try to get this working in nunuStudio 👍

**Pull request merged**
