### PR TITLE
WebGPURenderer: `MeshPhysicalNodeMaterial` - Fix `clearcoatRoughness`

### PR DESCRIPTION
**Pull request by sunag**
**Description**

Value limits and geometry-based roughness adjustments were not applied to `clearcoatRoughness`. 

More perceptive in the red sphere.

### CODE REVIEW

**Comment by mrdoob** [comment]
The material seem to be matching `WebGLRenderer` now 👌

| WebGPU | WebGL |
| --- | --- |
|  |  |

But seems like the background is blurrier compared to master 🤔

| WebGPU | WebGPU (master ) |
| --- | --- |
|  |  |

**Comment by sunag** [comment]
> But seems like the background is blurrier compared to master 🤔

I think this is not related to this PR, I believe it is due to some PMREM update that the screenshot was not updated.

**Comment by mrdoob** [comment]
Yes, it's definitely unrelated to this PR. I just wanted to make sure we're aware.

It's easier to see comparing these examples:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_gltf.html
https://raw.githack.com/mrdoob/three.js/dev/examples/webgpu_loader_gltf.html

**Comment by sunag** [comment]
`WebGLRenderer` only uses PMREM if `backgroundBlurriness` is greater than zero, I added `scene.backgroundBlurriness = 0.001;` in `webgl_loader_gltf` and had the same result as in WebGPU. I will improve this in an update.

**Pull request merged**
