### PR TITLE
add params for cubemap params (to support mobile)

### PR DESCRIPTION
**Pull request by richardmonette**
img_0186 copy

- Fixes a weird thing where the `EquiangularToCubeGenerator` had the format hard coded (it's now read from the source by default).

- Adds overrides for the type and format, specifically this makes it possible to tweak the `webgl_materials_envmaps_exr` example to work on mobile webGL (where only half precision texture is supported) Before the textures showed up as blank/black, see screenshot above for it now working nicely.

@WestLangley

### CODE REVIEW

**Comment by richardmonette** [comment]
> What should the output mips, encoding, and min/mag filters be for THREE.EXRLoader()?

Good question. Perhaps we can take that into another discussion, and still 🚢this spot fix. I've updated to the options object, as suggested 👍

**Comment by WestLangley** [comment]
@richardmonette Thanks! The API change should be noted in the migration docs, especially if there is no console warning.

@mrdoob This looks good.

**Comment by richardmonette** [comment]
> The API change should be noted in the migration docs

Happy to update this, can you please point me towards those docs? (Haven't ever had to update those yet! 😄)

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/wiki/Migration-Guide

**Comment by telime** [comment]
oh disagreement... I am looking forward to it.
"Renamed EquiangularToCubeGenerator to EquirectangularToCubeGenerator"

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
>The API change should be noted in the migration docs, especially if there is no console warning.

Done.

**Pull request merged**
