### PR TITLE
Box with filleted edges

### PR DESCRIPTION
**Pull request by pailhead**
A box with rounded edges. Could be cleaned up but it works. A bit confused as to what makes it a buffer geometry, i extended from that, but do create a bunch of Vector3s.

### CODE REVIEW

**Comment by Mugen87** [comment]
Generally, we want to keep the selection of geometry entities as basic and generic as possible. This kind of box is too use case specific.

Nevertheless, interesting work! Maybe you could create a separate github project for this geometry (or a gist) and post it in the [forum](https://discourse.threejs.org/)(categroy `Showcase`).

**Comment by pailhead** [comment]
I would advocate a bit more for this if the code were cleaner, smaller and if it could do segments along the face :) But, I'm curious, what makes a torus knot more basic geometry than this? I'm not sure but I think 3ds max may also consider that more basic than a filleted box.

Either way since this is just a drop in, it's been available on npm for a while now.

**Comment by Mugen87** [comment]
Well, for new classes we are a little bit more strict than in the earlier days. I also think the selection of geometry generators in the library is more than adequate.

BTW: Here the link to the mentioned npm package: https://www.npmjs.com/package/three-rounded-box

**Comment by pailhead** [comment]
@Mugen87 

Yeah i definitely wouldn't want this to be included with my build, since atm i have zero use for it. But i've also got zero use for the rest of the geometry, with the exception being the plane (conceptually, it's geometry, but can also be a **screen filler thingie**.

With that being said, i'm not sure if i agree with this:

> I also think the selection of geometry generators in the library is more than adequate.

I think the selection is a bit arbitrary and a bit legacy.

---

- As a user, i'd like to have a library of geometries that i can use with three. Ideally, anything that has been described parametrically ever, should eventually be available in the webgl world, through three.js.
- As a user, i'd like to be able to select which geometries i use with three.js. I dont want to have to include code in my app that is never ever going to be used. 

Consider the plane - screen drawing, terrain, billboards all in addition to being used as one would use a torus knot - to reflect some light and be transformed somewhere in the world. 

I haven't seen many real world apps that use a torus knot, it seems like its used mostly for testing other features (i've seen clipping, lighting, texturing etc). But why is this any more meaningful or important than say the utah teapot?

This is what i've been staring at for almost 20 years, 3ds max treats some of this geometry a different way: 

maxgeometries01

maxgeometries02


Again, this should not be accepted and be in the core, nor as is, nor improved. But, it should be "available" and improved. Advertising on forums won't do it much good (i think i posted on reddit). People downloaded it but no one commented on the code or tried to contribute. If it were in `/customGeometries` or `/extendedGeometries` more people would see it. /Examples could probably do atm.

**Comment by mrdoob** [comment]
How about adding it to `examples/js/geometries/`?

**Comment by pailhead** [comment]
😊  didnt know about `/geometries`

yes that makes sense

**Comment by mrdoob** [comment]
Yay! Do you want to amend this PR?

**Pull request closed without merging**
