### PR TITLE
Support Sector of CylinderGeometry

### LINKED ISSUE #5837: Adding the ability to draw only a portion of a CylinderGeometry
The RingGeometry constructor can take thetaStart and thetaLength parameters to draw only a portion of the ring (arc? curve?).

I needed to do something similar with a cylinder, so I added two extra parameters to the CylinderGeometry constructor (angleStart and angleEnd), and changed 3 lines:
```javascript
	var x, y, vertices = [], uvs = [];
	var radiansInAngle = angleEnd - angleStart;		// NEW

	for ( y = 0; y <= heightSegments; y ++ ) {
		var verticesRow = [];
		var uvsRow = [];

		var v = y / heightSegments;
		var radius = v * ( radiusBottom - radiusTop ) + radiusTop;

		for ( x = 0; x <= radialSegments; x ++ ) {
			var u = x / radialSegments;
			var vertex = new THREE.Vector3();
			vertex.x = radius * Math.sin( u * radiansInAngle + angleStart );	// EDITED
			vertex.y = - v * height + heightHalf;
			vertex.z = radius * Math.cos( u * radiansInAngle + angleStart );	// EDITED
			this.vertices.push( vertex );
			verticesRow.push( this.vertices.length - 1 );
			uvsRow.push( new THREE.Vector2( u, 1 - v ) );
		}

		vertices.push( verticesRow );
		uvs.push( uvsRow );
	}
```

Is this something that might be added to CylinderGeometry at some point?

### PR DESCRIPTION
**Pull request by WestLangley**
Adds `thetaStart` and `thetaLength` -- similar to the API for `RingGeometry` and `CircleGeometry`.

Fixes #5837

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Then `openEnded` parameter bothers me though...

**Comment by WestLangley** [comment]
> Then openEnded parameter bothers me though...

How would you like the API changed?

**Comment by mrdoob** [comment]
Not sure... I wonder if something like a `CappedCylinderGeometry` that would internally use `CylinderGeometry` would make sense.

**Comment by alexan0308** [comment]
There are no segments thetaSegments in CylinderGeometry and CircleGeometry =)

**Comment by WestLangley** [comment]
In this case, the term `radialSegments` is used, instead.

**Comment by alexan0308** [comment]
No. Look you and ideal =)
image

**Comment by alexan0308** [comment]
and maybe even add the inner radius? ))) 
or create ring3dgeometry. Strangely enough, it is difficult to [create a ring](http://stackoverflow.com/questions/28460758/smooth-ring-3d-in-three-js)

**Pull request merged**
