### PR TITLE
Geometry: Support non-indexed with groups in fromBufferGeometry()

### LINKED ISSUE #11140: Non-indexed BufferGeometry with MultiMaterial
##### Description of the problem 

The problem is in geometry.fromBufferGeometry method. If BufferGeometry is non-indexed it is impossible to use MultiMaterial. Because material index of group is taken into account only if BufferGeometry has index. 
https://github.com/mrdoob/three.js/blob/master/src/core/Geometry.js#L326
But it is not always the case. For example, BufferGeometry loaded from .OBJ file is non-indexed but has groups.

##### Three.js version

- [ ] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
`.fromBufferGeometry()` now regards non-indexed `BufferGeometry` that has groups.

Fixes: #7917 #11140

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by FishOrBear** [comment]
@Mugen87  @mrdoob  
line 327:
```js
for ( var i = 0; i < positions.length / 3; i += 3 ) {
	addFace( i, i + 1, i + 2 );
}
```
This will not be better.
```js
for ( var i = 0; i + 2 < positions.length / 3; i += 3 ) {
		addFace( i, i + 1, i + 2 );
}
```

**Comment by mrdoob** [comment]
How's it that better?
Is that in case the last face is incomplete? Wouldn't that break anyway?

**Comment by Mugen87** [comment]
I don't understand that code :confused:

**Comment by FishOrBear** [comment]
```js
let lineGeo = new THREE.BufferGeometry();
var vertices = new Float32Array([
    0, 0, 0,
    0, 0, 2]);
lineGeo.addAttribute('position', new THREE.BufferAttribute(vertices, 3));

let geo =new THREE.Geometry().fromBufferGeometry(lineGeo)
```

This code will cause an error

@Mugen87 @mrdoob

**Comment by WestLangley** [comment]
Related: https://github.com/mrdoob/three.js/pull/13144#issuecomment-359180187

I think `Geometry.fromBufferGeometry()` assumes the buffer geometry represents a mesh with `TrianglesDrawMode`.

**Comment by mrdoob** [comment]
@FishOrBear Curious about to hear your use case, why do you need to convert `BufferGeometry` to `Geometry`?

**Comment by FishOrBear** [comment]
@mrdoob 
In fact, I am lazy.

When I implement the screen to select the entities, I want to get the edges and faces of the geometry, and then do the intersection detection.

Because using this method can be achieved with less code.

**Pull request merged**
