### PR TITLE
WebGLPrograms: Simpler vertexUvs check.

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #25721

**Description**

Bumped into this while working on #25721.

Is it still worth checking all the possible maps before including the UV chunks? 🤔

### CODE REVIEW

**Comment by Mugen87** [comment]
> Is it still worth checking all the possible maps before including the UV chunks? 🤔

TBH, I would say yes. Otherwise you end up with unused attribute data in the shader. The code also performs a uv transformation per vertex which is not required. 

I could also imagine you are getting an unused varying warning in the fragment shader.

**Comment by mrdoob** [comment]
After #25721 the check will have to be a bit more complicated now though.
Now it'll have to see if any of the maps is using `uvSet === 0`, and then again with `uvSet === 1` before enabling `USE_UV2`...

**Comment by Mugen87** [comment]
If I implement the code and remove the map in [webgl_geometry_cube](https://threejs.org/examples/#webgl_geometry_cube) from the cube, I see this in the browser console (Firefox):

> THREE.WebGLProgram: Program Info Log: WARNING: Output of vertex shader 'webgl_37cc066937ccaa46' not read by fragment shader

I think we should avoid such reports whenever possible. That's why `UVS_VERTEX_ONLY` was added  e.g. when just using a displacement map.

**Comment by mrdoob** [comment]
This PR is no longer relevant after all the refactoring in #25721 😅

**Pull request closed without merging**
