### PR TITLE
Removed Geometry generators

### PR DESCRIPTION
**Pull request by mrdoob**
Trying to remove `THREE.Geometry`.

### CODE REVIEW

**Comment by Mugen87** [comment]
Assuming `Geometry` is later moved to the examples and renamed to `LegacyGeometry`. And `BufferGeometry` is renamed to `Geometry`. Can we then rename the generators back to e.g. `BoxGeometry`? 

By adding an alias for each geometry generator, names like `BoxBufferGeometry` should still work.

**Comment by mrdoob** [comment]
I'll give that a try tomorrow 👍

**Comment by Mugen87** [comment]
BTW: `webgl_buffergeometry_constructed_from_geometry` is failing in the E2E since it's the last example that uses `ExtrudeGeometry`.

TBH, it makes no sense to convert it to `BufferGeometry` since its purpose is to show the construction of a `BufferGeometry` from `Geometry`. I think we can delete it 👍 .

**Comment by Mugen87** [comment]
Since #21021 is now in `dev`, I hope rebasing should fix unit and E2E tests.

**Comment by mrdoob** [comment]
> Assuming `Geometry` is later moved to the examples and renamed to `LegacyGeometry`. And `BufferGeometry` is renamed to `Geometry`. Can we then rename the generators back to e.g. `BoxGeometry`? 

Thinking more about this... I'm not sure we can do that.

If we rename `BufferGeometry` to `Geometry` then we'll also have to change all the `.isBufferGeometry` checks everywhere.

**Comment by Mugen87** [comment]
Couldn't we just add the  `isBufferGeometry` property to `Geometry` (for backwards compatibility)?

**Comment by mrdoob** [comment]
I think that complicates things more...

I would rather keep `BufferGeometry` as the base and introduce something like `MeshGeometry`, `LineGeometry`, `PointsGeometry` and make them extend `BufferGeometry`.

That way we'll end up with `BoxMeshGeometry`, `CircleMeshGeometry`, etc

I'd also allow us to check `geometry.isMeshGeometry` in `Line` and warn the user that things are not likely to look right.

**Comment by Mugen87** [comment]
Okay, that's fine with me. I remember we discussed the introduced of specific geometry classes earlier.

**Comment by mrdoob** [comment]
Yeah... I'm still unsure about the approach, but feels way less scary than renaming `BufferGeometry` to `Geometry` 😅

**Comment by Mugen87** [comment]
I'm just sad that the name `Geometry` is now somewhat reserved and not usable for the actual primal geometry class (which is `BufferGeometry`).

**Comment by mrdoob** [comment]
Yeah, I understand... 🤗

**Comment by Mugen87** [comment]
Maybe we can reconsider a rename later. When `LegacyGeometry` was part of the example for a year or so.

**Comment by Mugen87** [comment]
Possible next steps:

- Move the class `DirectGeometry` into `Geometry.js`.
- Remove the following methods in `BufferGeometry`: `fromGeometry()`, `fromDirectGeometry()`, `setFromObject()` and `updateFromObject()`. Enhance `THREE.Legacy.js` and log console errors for the above methods.
- Introduce `Geometry.toBufferGeometry()`.
- Stop rendering `Geometry`. This requires a small change in `WebGLGeometries` and `WebGLObjects`.

- (Optional): Move `Geometry.js` to `examples/jsm/geometries`.
- (Optional): Remove all `isGeometry` checks in the code base. Instead, check for `geometry.isBufferGeometry !== true`.

**Comment by mrdoob** [comment]
I'll merge this for now and open another PR with these steps.

**Comment by mrdoob** [comment]
#21031

**Pull request merged**
