### PR TITLE
Examples: Improve SSAARenderPass example

### PR DESCRIPTION
**Pull request by gkjohnson**
Related issue: https://github.com/mrdoob/three.js/issues/20681#issuecomment-733454391

**Description**

Use a lit sphere to better demonstrate artifacts introduced by `SSAARenderPass` and expose `unbiased` as GUI param which can be used to mitigate the artifacts. 

https://raw.githack.com/gkjohnson/three.js/ssaa-pass-improvement/examples/webgl_postprocessing_ssaa.html

To see / toggle the artifacts use 32 samples and toggle the "unbiased" checkbox.

### CODE REVIEW

**Comment by mrdoob** [comment]
Is there a reason it shouldn't always be unbiased?

**Comment by Mugen87** [comment]
Agreed that it makes sense to demonstrate the `unbiased` parameter.

However, there is a second example that already does this: 

https://threejs.org/examples/webgl_postprocessing_ssaa_unbiased

How about removing `webgl_postprocessing_ssaa` and rename `webgl_postprocessing_ssaa_unbiased` to `webgl_postprocessing_ssaa`?

**Comment by gkjohnson** [comment]
@mrdoob 
> Is there a reason it shouldn't always be unbiased?

As far as I can tell, no.

@Mugen87 
> How about removing `webgl_postprocessing_ssaa` and rename `webgl_postprocessing_ssaa_unbiased` to `webgl_postprocessing_ssaa`?

I didn't even see there was already an unbiased example. I'm not sure if there's a reason to have two, though.

Made another PR that renames the existing example here depending on which one you want to merge: #20764

**Comment by Mugen87** [comment]
I have approved #20764 👍 .

**Pull request closed without merging**
