### PR TITLE
fix error referencing undefined.

### PR DESCRIPTION
**Pull request by ckddbs**

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind explaining a bit what this PR is fixing?

**Comment by WestLangley** [comment]
Apparently it is this line in `parse()`

    self.manager.itemError( url );

For consistency with the rest of the library, think we should find a solution that does not change the `parse()` signature.

**Comment by ckddbs** [comment]
When failed to load a file, it throws null referencing exception.

**Comment by Mugen87** [comment]
This PR refers to #11695

**Pull request closed without merging**
