### PR TITLE
Unittests with mocha and chai

### PR DESCRIPTION
**Pull request by simonThiele**
Hi,

as implied here #7665 I implemented the first test file for Camera with mocha testing framework (mochajs.org) and chai assertion lib (chaijs.com). You can now run this two test with `npm test` (don't forget to install missing libs before via npm). If you are fine with it I would rewrite all current tests to support mocha and chai so we can get serious ;).

Suggestions are welcome!

P.S.: Mocha starts a node server so I need to include that `self = global` hack inside the test file until a new build file was released.

### CODE REVIEW

**Comment by MasterJames** [comment]
Interesting. Thanks. Chai Looks better at first glance.

**Comment by simonThiele** [comment]
@GGAlanSmithee maybe this is interesting for you too

**Comment by GGAlanSmithee** [comment]
@simonThiele 

Nice!

I see you use `assert` for some equal checks and another time you use `expect`, is there any specific reason you use one or the other? (I'm asking more out of interest then anything else).

Personally, I almost only use `expect` since i like its fluent API as well as its ability to do dee object comparison. (Not saying you can't do that with assert - I haven't used it a lot.)

**Comment by mrdoob** [comment]
> You can now run this two test with `npm test` (don't forget to install missing libs before via npm).

I don't use npm. Would it be possible to include the libraries in the repo instead?

**Comment by mrdoob** [comment]
Also, the old test was 25 lines and the new one is 45 lines. Usually one adds libraries so the code is shorter/easier to read 😉

**Comment by simonThiele** [comment]
@GGAlanSmithee It depends on the test case. I use expect if I expect a value, but the result can be any value. Assert is used if you expect that something happens or not, so binary expectation. You can express the same test with expect, should or assert and it depends mostly on your flavor :) (see the three example boxes on top of chais landing page).

**Comment by simonThiele** [comment]
@mrdoob
> Would it be possible to include the libraries in the repo instead?
You mean by coping the hole src?

> Also, the old test was 25 lines and the new one is 45 lines. Usually one adds libraries so the code is shorter/easier to read
Yes, because I done something wrong (see last commit) now it's 42 against 25 :) If you clear the whitespace it's 25 against 19 and if you remove the `self = global` hack when the build file contains it (see #7747) it's 22 against 19. BUT you have a very powerfull testing environment with all you need and if you translate all the other tests (which I would like to do) than you can even delete some files and don't need to add your tests to html files since they are searched automatically. Furthermore you don't need to log out your results if a tests breaks since the wrong value will be printed out with all infos. I belive that this is a big value.

**Comment by mrdoob** [comment]
>> Would it be possible to include the libraries in the repo instead?

> You mean by copying the whole src?

Yep! I always try to make the whole thing dependency-less.

**Comment by GGAlanSmithee** [comment]
> Yep! I always try to make the whole thing dependency-less

That would not make it dependency-less though, it would only hide the dependency.

**Comment by mrdoob** [comment]
Right. Just like we're already "hiding" these dependencies: https://github.com/mrdoob/three.js/tree/master/examples/js/libs

**Comment by GGAlanSmithee** [comment]
I'm not sure if you are being sarcastic because of the qoutation marks, but to answer you question, yes.

It's not as much as hiding the files as hiding the dependency. I guessMaybe hiding isn't the right word. My answer was a reaction to you saying

**Comment by mrdoob** [comment]
What I meant is that I try to make it so you can just download https://github.com/mrdoob/three.js/archive/master.zip and be good to go.

**Comment by GGAlanSmithee** [comment]
Ah! I guess you want no external dependencies then! Should have understood that.

**Comment by simonThiele** [comment]
I'm not totally with you because I think it's okay to use external dependencies first of all for the test server but if you say you don't want them it's okay for me. Let me check if we can get around of them.

**Comment by simonThiele** [comment]
Okay, so the only solution I see is copying the src to the three repo. If @mrdoob is fine with that I will do so, so please tell me :)

**Comment by simonThiele** [comment]
Okay, I don't see any way to keep both, mocha and chai, because it's too much code. We can keep the HTML testing file and use chai as an assertion lib only but that would imply to change its behaviour to show testing results in the HTML "output". So, it is as it is :/

**Comment by MasterJames** [comment]
Yes agreed. And it's totally extensible.
http://chaijs.com/plugins

**Comment by mrdoob** [comment]
Sorry about that... I just have the feeling we would be over engineering the unit tests and... more code = more bugs.

**Comment by simonThiele** [comment]
Kk fine by me, let's close this

**Pull request closed without merging**
