### PR TITLE
webgl_terrain_dynamic: bugfixing and simplification

### PR DESCRIPTION
**Pull request by Mugen87**
This PR fixes two runtime errors in `examples/js/ShaderTerrain.js` and simplifies the example `examples/webgl_terrain_dynamic.html`(see #8405).

Unfortunately i had no time so far to refactor the lighting shader code in `examples/js/ShaderTerrain.js`. I've planned to use the shader chunk `lights_template.glsl` to replace some of the old code. Is it okay to implement this in a separate PR?

### CODE REVIEW

**Comment by mrdoob** [comment]
> Is it okay to implement this in a separate PR?

Definitely!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mateidragos** [comment]
Hello,

Whenever you have some time, it would help me - and the children we work for - if you could take a look at this question: 

https://stackoverflow.com/questions/48025766/three-js-animesh-rewrite-or-fix-it-wont-play-in-the-new-version-even-if-morpha

It is not urgent but it would help me, especially if I just forgot something and it is an easy answer (I hope it is).

:) Thank you and happy holidays. :)

**Comment by Mugen87** [comment]
@mateidragos Please don't post such messages at github.

**Comment by mateidragos** [comment]
Sorry for bothering you. :(

I thought that if you found a sollution you could share it.

When I don't know something I ask.

Usually people help, especially when we work for children in foster homes and in hospitals.

Thank you for your answer and again appologies if my message offended you.

**Comment by mrdoob** [comment]
@mateidragos Asking questions is good, but this board is not for that.

Unfortunately this is a issue with Github itself. I wish there was a way to make people read [this guide](https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md) before posting here.

We need these kind of rules and people to "follow" the rules so we can continue the project. Otherwise we'll get burnt out. I'm sure you understand.

Anyway, we have already communicated over Twitter DM and I'm already working on bringing these animals back.

Please, use the [forum](https://discourse.threejs.org/) next time.

**Comment by mateidragos** [comment]
Thank you and sorry for using the time for creation rather than reading
guides.

Sometimes it happends like this in my mind ...

I hoped it is just a small thing I did not know how to do, some line of
code I may have missed ...

It seems it might be more than that ...

Thank you again for the help. :) :)

**Pull request merged**
