### PR TITLE
pass all blending parameters to setBlending in SpritePlugin

### PR DESCRIPTION
**Pull request by stuikomma**
The SpritePlugin did not call `state.setBlending` with all the required parameters, which is why premultiplied alpha would not work.

This PR adds the missing parameters and adds an example showing the difference between premultiplied and non-premultiplied textures for sprites.

Left is a sprite without premultiplied alpha (and what it looked like before this fix), right is with premultiplied alpha.
image

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks for the code fix. I am not sure we need the example, but we do need to have the [WebGLState  docs](http://threejs.org/docs/#api/renderers/webgl/WebGLState) corrected.

**Comment by stuikomma** [comment]
Hi @WestLangley,
thanks for your fast reply :)

Regarding the example: It took me quite a while to figure out the right parameters (`premultiplyAlpha` and `premultipliedAlpha`). In order to have that documented and to see a demo of the issue I think an example would be of help to other devs. Maybe it should be extended to cover premultiplied alpha in general (for other textures as well as sprites).
But I'm not super attached to the example. If you don't like it, we can throw it out.

Do you create an issue for updating the docs or should I include it here?

**Comment by WestLangley** [comment]
You can add the docs here if you like.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
