### PR TITLE
GLTFLoader: Fix handling of normalized animation outputs

### LINKED ISSUE #16658: GLTFLoader: Animation samplers don't handle normalized accessors correctly
GLTF spec says that for rotation and weights animations, values may contain BYTE/SHORT normalized values. However, they aren't supported correctly by three.js.

What happens right now is that we create (for example) QuaternionKeyframeTrack, which ends up calling AnimationUtils.convertArray which simply creates a new Float32Array without normalizing the values.

I would like to fix it but I'm not sure where the best place to fix this is. Should GLTFLoader convert the output accessor to Float32Array manually, or is it better to add normalized input array support to various keyframe tracks?

### PR DESCRIPTION
**Pull request by zeux**
Per GLTF spec, rotation and weight animation outputs can use normalized
BYTE/SHORT/etc. accessors. However, the animation tracks don't support
normalized values, which results in erroneous playback.

This change manually renormalizes the array elements before handing them
to the animation system to fix this.

Fixes #16658.

### CODE REVIEW

**Review by donmccurdy — APPROVED** [review]
We'll want to support unsigned arrays too, I think, but I'm OK with merging this in the meantime.

**Comment by zeux** [comment]
Oh sorry this has completely escaped my notice - I was thinking about quaternions where unsigned data is non-sensical (I raised a spec issue for that), but for weights it makes perfect sense. I will fix this.

**Comment by zeux** [comment]
@donmccurdy Please re-review; didn't find a clean way to check if the accessor is signed so opted for just enumerating types, at least that way it's explicit that we only support 4 of them? :)

**Review by donmccurdy — APPROVED** [review]
Looks good – yes I think we have to enumerate the array types here. 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
