### PR TITLE
Examples: Resizable grid view

### PR DESCRIPTION
**Pull request by marcofugaro**
Followup of #19375

I implemented a resizable examples view as suggested in https://github.com/mrdoob/three.js/pull/19375#issuecomment-629955667.

It is under a breakpoint, so it is enabled on landscape iPad and up.

I've set the minimum card width to `200px`, but it can be adjusted.

Note: on Chrome, in certain situations, the resizing may be a little bit laggy. This is because it triggers re-paint, and painting is handled on the CPU in Chrome.

[demo](https://raw.githack.com/marcofugaro/three.js/example-mode-resizable-grid/examples/index.html)

### [Live demo](https://raw.githack.com/marcofugaro/three.js/example-mode-resizable-grid/examples/index.html)

### CODE REVIEW

**Comment by munrocket** [comment]
Looks like it's hard to catch scrollbar with this UX (._.) Actually it's what I am afraid of and this is the reason why simple button #18841 looks better for me. Also grid _unreachable_ on mobile phones.

Anyway thanks for you effort, we are going to the best three.js webpage. Don't want to stop this, but we need more feedback IMHO. I never seen draggable scrollbar before.

**Comment by marcofugaro** [comment]
You're right.
I moved the interaction area towards the outside so now the scrollbar is still usable.

It is not supposed to work on mobile, it is disabled there.

The problem with the button, is that it overlaps with the `x` of the search. This might confuse the user. It is generally avoided to change the layout without the user specifically requesting so. It could work if we find another place for the button.

**Comment by munrocket** [comment]
Wow, looks better now!
[Githack](https://rawcdn.githack.com/marcofugaro/three.js/5ff8babeb02b606dc88c512a9484fad6c1d31674/examples/index.html)

**Comment by NicolasRannou** [comment]
I'm a bit late to the party and maybe that's for another PR, but I think it may still be useful to have the previous list of examples without thumbnails? If so, we could add 2 toggle buttons at the right of the search bar to switch from "preview" to "no-preview" list?

threes_examples

**Comment by marcofugaro** [comment]
@NicolasRannou could you elaborate on why you would want to use the list without images instead of the one with the images?

**Comment by NicolasRannou** [comment]
So I think that this new view is great to explore examples but it does take a lot of scrolling to reach the end of the list - granted that the search bar is there to quickly access one example.

I'm not strongly feeling about it but I just wanted to mention it!

Great work!

**Comment by marcofugaro** [comment]
> scrolling to reach the end of the list 

I totally agree! Does the grid view I proposed in this PR help with that? Take in mind that we could still make the cards smaller so there are more in a single view.

**Comment by mrdoob** [comment]
@NicolasRannou https://github.com/mrdoob/three.js/pull/19881

**Comment by marcofugaro** [comment]
I rebased this PR and integrated it with the minimal layout toggle.

https://raw.githack.com/marcofugaro/three.js/example-mode-resizable-grid/examples/index.html

**Comment by mrdoob** [comment]
I think it would be nice to have some more days to test this. Moving it to next release.

**Comment by mrdoob** [comment]
Implemented a resizer in the editor using `event.movementX` (Safari doesn't support it though)... https://github.com/mrdoob/three.js/commit/42a1d5e1db57aa16e38eaeac2ea4ee2573887d4d

**Comment by marcofugaro** [comment]
@mrdoob Nice! Should I refactor using `event.movementX` as well?

**Comment by marcofugaro** [comment]
Alright, rebased and converted to let/const!

**Comment by mrdoob** [comment]
I'm still unsure about this one.
It's weird that examples is expandable but docs is not...

**Comment by marcofugaro** [comment]
@mrdoob well the docs don't need to be expandable. The titles length and the whole entries list are both short. Also users don't snoop around and discover the docs like you would do for the examples.

**Comment by mrdoob** [comment]
Yeah. Just feels a bit inconsistent...
Anyway, would be great if you could refactor using `event.movementX` yes 🙏

**Comment by marcofugaro** [comment]
@mrdoob I had a go with this, but it looks like `movementX` is in integers, making the current implementation with `pageX` a bit more precise.
Kinda like the pointer events vs the mouse events.



I think the current implementation is fine and simple enough, but let me know if I should change anything else.

**Comment by OndrejSpanel** [comment]
> could you elaborate on why you would want to use the list without images instead of the one with the images?

I would often prefer it because I can see much more examples on one screen. Currently when looking for something I see four examples on one page. With text only (as can be seen in [2016 version of the page](https://web.archive.org/web/20161026061818/https://threejs.org/web/20161026061818/https://threejs.org/examples/) I saw about 40 of them and the whole list would fit on 10 pages, which was quite possible to read through just to get an impression what examples are available. The complete list is 100 pages long with images.

**Comment by marcofugaro** [comment]
@OndrejSpanel a toggle between text/image version has been added since then.

**Comment by Mugen87** [comment]
Although the feature is nice, it adds quite a loot of code `examples/index.html. In the interests of maintainability and simplicity, it's better to not merge the PR until a more compact solution is found.

**Comment by marcofugaro** [comment]
@Mugen87 I am afraid there is not a more compact solution, the resizer in the editor is structured more or less the same: https://github.com/mrdoob/three.js/blob/dev/editor/js/Resizer.js

But it looks like people are not interested in this grid feature anymore.

**Pull request closed without merging**
