### PR TITLE
Implemented Scene.environment

### PR DESCRIPTION
**Pull request by mrdoob**
Follows Unity, Unreal and Substance Painter nomenclature.

Replaces #18157.

### CODE REVIEW

**Comment by Mugen87** [comment]
I like the distinction between `Scene.background` and `Scene. environment`.Definitely more flexible than the previous `CubeTextureBackground`.

**Comment by elalish** [comment]
Agreed, this looks great!

**Comment by mrdoob** [comment]
Sweet! Lets give a try 🤞

**Comment by Mugen87** [comment]
When writing the docs and playing around with the code, I've found a minor issue: When you apply a texture to `Scene.environment` _after_ the compilation of physical materials, you won't see an effect. You manually have to set `Material.needsUpdate` to `true`.

The following live example demonstrate this issue. A box is added to the scene before the HDR texture is loaded. Hence, it stays unlit although `Scene.environment` is properly configured.

Demo: https://jsfiddle.net/5027efko/1/

**Comment by mrdoob** [comment]
Yes. I noticed that issue in the previous implementation and yes something like the way we handle `outputEncoding` should work 👌

I'll give it a go tomorrow!

**Comment by mrdoob** [comment]
@Mugen87 Done! https://github.com/mrdoob/three.js/commit/087546d2f6cfeda800c951c543ef980cf6af3a2e

**Pull request merged**
