### PR TITLE
Fixed clipped quad pass when using clippingPlanes on WebGLRenderer

### LINKED ISSUE #10401: WebGLRenderer Clipping Plane with EffectComposer
##### Description of the problem 
When using global clipping planes of WebGLRenderer, the different passes of EffectComposer are not renderered correctly when they involve rendering a WebGLRenderTarget. Indeed, the renderer is also applying the clipping on textures, resulting in a brutal clipping.  You can see the effect in the following example :  http://jsfiddle.net/Ludobaka/tvvou3m2/

I'm available to fix the problem but I'm still thinking of how to design it. I prefered to create the issue first. I was thinking of :
- Modifying each ThreeJS Pass to deactivate clippingPlane when rendering a framebuffer
- Make some changes on WebGLRendererTarget to deactivate clippingPlanes when using a framebuffer

Update :
The problem seems to come at WebGLRenderer.render when calling projectObject. ThreeJS is checking CPU side if the object is viewable or not.

##### Three.js version

- [x] Dev
- [x] r83
- [x] r82
- [x] Previous rev with clipping planes

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)
None

### PR DESCRIPTION
**Pull request by Ludobaka**
Fixed #10401 

I don't know if it's the best solution, but I decided to use frustumCulled feature of THREE.Mesh to avoid quad passes to be clipped by the WebGLRenderer clipping planes. All ThreeJS postprocessing example using a quad were modified.

Proof of error : http://jsfiddle.net/Ludobaka/tvvou3m2/
Proof of solving : http://jsfiddle.net/Ludobaka/n4qe5r7g/

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, I don't see any difference between those jsfiddles...?

**Comment by Ludobaka** [comment]
I updated the error to make it more obvious to see. Tell me if it's ok for you now.

**Comment by mrdoob** [comment]
Ah, I see the error now 👍

Do you mind adding a message though? Something like...

```js
this.quad.frustumCulled = false; // Avoid getting clipped
```

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
