### PR TITLE
Web*RManager: Dispatch sessionstart/sessionend events

### PR DESCRIPTION
**Pull request by takahirox**
From #16277

This PR lets `WebVR/XRManager` dispatch start/endSession event on entering / existing from immersive mode.

API

```javascript
renderer.vr.addEventListener( 'startSession', function ( event ) {

    console.log( 'In immersive mode.' );

} );

renderer.vr.addEventListener( 'endSession', function ( event ) {

    console.log( 'Out of immersive mode.' );

} );
```

Benefit

- Common Event API no matter whether WebVR or WebXR API
- In WebXR API users needed to watch session to detect entering/existing from immersive mode but currently we don't expose session. With this proposal we don't need to expose session.

### CODE REVIEW

**Comment by mrdoob** [comment]
This is looking good.

Just to make sure I'm following... What is a use case for listening to these events?

**Comment by takahirox** [comment]
My use case is #15840. For PostProcessing I need renderer size but when the size is changed when entering or leaving from immersive mode. I watch renderer size every frame in #15840 for now but it'd be more efficient if I can watch session start/end event.

I guess some users also may want to do similar stuffs efficiently.

**Comment by takahirox** [comment]
Resolved the conflicts.

**Comment by mrdoob** [comment]
Looking good!

One change though. Could you rename the events to `sessionstart` and `sessionend`?

**Comment by takahirox** [comment]
Updated

**Comment by mrdoob** [comment]
I intentionally shifted the terms: `sessionstart` and `sessionend`. Just like `touchstart`, `touchend`, etc

**Comment by takahirox** [comment]
Yeah, I though so. And this PR looking good now?

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
