### PR TITLE
VRMLLoader: Allow minus in Identifier

### PR DESCRIPTION
**Pull request by tuarrep**
Reopening of #18298

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@tuarrep Did that fix it? I tried loading one of your wrl files and I'm getting this:

Screen Shot 2020-09-11 at 10 50 14 AM

**Comment by Mugen87** [comment]
The `jsm` module probably needs an update first.

**Comment by mrdoob** [comment]
I updated it. And now `webgl_loader_vrml` is failing.

@tuarrep are you able to investigate this?

**Comment by Mugen87** [comment]
@tuarrep Contributions should always be tested with existing examples. It's not acceptable to introduce a breakage. 

If you can't manage to fix this issue, the PR has to be reverted.

**Comment by tuarrep** [comment]
@Mugen87 

It's not my responsibility to merge. If it breaks, revert it, no problem.

@mrdoob I can investigate, I need some time to do so. As the patch was written in January, I need to recall all the details.
I've a working patched code on a project, I'll test on it.

**Comment by mrdoob** [comment]
It's all good! I'll revert in the meantime.

**Pull request merged**
