### PR TITLE
MMDLoader: set material type to 'MMDToonMaterial'

### PR DESCRIPTION
**Pull request by WestLangley**
...as we do elsewhere to provide a unique name to the ShaderMaterial.

### CODE REVIEW

**Comment by WestLangley** [comment]
@takahirox Is it intended that `MMDToonMaterial` supports environment maps?

I am trying to determine if the env map shader chunks are necessary...

**Review by takahirox — APPROVED** [review]

**Comment by takahirox** [comment]
Hm, not really.

**Comment by WestLangley** [comment]
I thought matcaps were used for the environment and `material.envMap` is never set...

**Comment by takahirox** [comment]
Ah I had forgotten matcap. MMD envmap might be able to be rewritten with matcap.

**Comment by WestLangley** [comment]
I think you and I discussed this when you were implementing it 100 years ago.  :-)

**Pull request merged**
