### PR TITLE
`LineMaterial`: Add support for sectional textures

### PR DESCRIPTION
**Pull request by sguimmara**
Related issue: #28129 

**Description**

The `LineMaterial` is updated with the `map` property. When this map is defined, it is used to colorize the line along the sectional axis (the U of the UV coordinate).

The texture color is multiplied with the line color to get the final color.

This texture can be any texture, but only the first row of pixels will be read (i.e the V texture coordinate is always 0).

We are reusing the existing UV coordinates (after transforming them back into the [0, 1] range).

The usage of this texture in the fragment shader is guarded by a define, that is automatically set when setting the `.map` property of the material. Conversely, the define is deleted when the `.map` property is assigned to a nullish value.

The `webgl_lines_fat` example is updated to use an optional texture when the checkbox is toggled on in the GUI panel.

image

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: https://rawcdn.githack.com/sguimmara/three.js/28129-linematerial-sectional-textures/examples/webgl_lines_fat.html

**Comment by Mugen87** [comment]
The quality of the texture along curves is a bit problematic. Similar issues can be seen with dashed lines. Besides, the texture looks quite jaggy especially when configuring a very wide line.

image

I suspect the current behavior will be quickly reported as a bug.

**Comment by WestLangley** [comment]
Actually, the points in the example are way too close for practical purposes. With fewer points, this is the result.

Screenshot 2024-04-13 at 12 01 25 PM

There are still artifacts, and the artifacts "rotate" as the camera moves.

As I have said many times: https://github.com/mrdoob/three.js/issues/16964#issuecomment-507822935. `MeshLine` may be a better implementation in certain cases.

**Comment by Mugen87** [comment]
@sguimmara Thanks for sharing your solution here but as pointed out in the above comments the implementation does not produce satisfying results across different configuration setups. It's great if it works for your specific use case but it seems the fundamental assumptions of our wide line implementation make it hard to develop any kind of texture mapping.

> MeshLine may be a better implementation in certain cases.

The problem is that the original `MeshLine` repository isn't supported anymore, afaik. It seems the fork https://github.com/lume/three-meshline is a bit more up-to-date but you still end up with a non-instanced version which is a performance issue for certain apps.

**Pull request closed without merging**
