### PR TITLE
OBJLoader2 V3.0.0-Beta as jsm

### PR DESCRIPTION
**Pull request by kaisalmen**
**2019-05-03** Description has been fully revised.

I have ported `OBJLoader2` to jsm, but it is **not just a port** of the existing version! This version follows a new approach. `LoaderSupport` is dropped and worker usage will be different (ongoing work in other repo and not yet included in this PR).

After I came back to work on the OBJLoader2/WorkerSupport (#13664) after half a year, I realized that I need to change the approach. Provide loaders the capability to run inside a Worker is just one use case. What I really started to create was a configurable asset loader that should be able chain asset loading tasks, should be able to execute loading tasks inside workers and in should be able to run in parallel on demand (Director).
Why do I tell you this? Because I use ES2017 features (async/await) for the `AssetPipelineLoader` and then it was the logical conclusion to port `OBJLoader2` along. in addition, through the definition of modules it becomes easier to identify and mark (dependency chains) re-usable code blocks.  ES5 support should be possible via Babel, but I have not tested it yet.
My idea was that the introduction to jsm part allows evolution of the new code in parallel with the legacy implementation.

What has changed?
- `MaterialHandler`and `MeshReceiver` have been extracted from `OBJLoader2`. The are re-usable in the asset loader/ worker support context. I really don't like to copy code that is approx. 90% identical.
- All MTL handling code has been removed from `OBJLoader2`. This was the wrong approach (see `MtlObjBridge`). **Hint:** a future asset chain is `MtlLoader` -> `MtlObjBridge` -> `ObjLoader2` ([ongoing work](https://github.com/kaisalmen/WWOBJLoader/blob/dev/test/assetPipelineLoader/main.src.html#L104-L129))
- `OBJLoader2` will not get any further dependencies. Worker execution will use `OBJLoader2` and other loaders.
- [OBJ Verify has been updated](https://raw.githack.com/kaisalmen/three.js/OBJLoader2_V300_beta_es6/examples/models/obj/verify/verify.html) to use modules for both `OBJLoader` and `OBJLoader2`, so there is something to try it out immediately 😉 Consider #13663 `OBJLoader2Parser` has less errors and more features even without worker support!

This code has preview status and may contain bugs (usual bug OBJ verification models load fine though, Parser code changed the least) and may need documentation update. Typescript bindings are also not there, yet.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by kaisalmen** [comment]
Thank you, I expected some comments, though. Now I need to get the rest done for the next release. Unfortunately, jsm support inside Workers is still experimental. I need find solution that works now (remove exports/imports) when building the worker code and a second path (future browsers) that uses the modules directly.

**Comment by mrdoob** [comment]
> I expected some comments, though. Now I need to get the rest done for the next release. 

😅

**Comment by jkfhto** [comment]
The loadMtl method of objLoader2 has been removed. How can I handle the mtl file?

**Comment by kaisalmen** [comment]
Like this;
https://github.com/mrdoob/three.js/blob/dev/examples/models/obj/verify/verify.html#L169-L181

I have introduced `MtlObjBridge` with this version of `OBJLoader2` (see comment above).

**Comment by Mugen87** [comment]
@kaisalmen Can you please put all `OBJLoader2` related files into a single directory `obj` in `jsm/loaders`? It's confusing that directories like `bridge`, `shared` and `worker` are placed in the root directory of `loaders`.

**Comment by kaisalmen** [comment]
Yes, I will do and create another PR before R106 is due. We can discuss later if non-obj related code should be put elsewhere when the worker and asset loader code becomes available. I fall behind my plans as re-using modules in worker will be super easy in the future, but right now one need to support the old of code loading (including transformation if you don't want to write things twice). Module support in worker is only available in Chrome and behind an experimental web extensions flag.

**Pull request merged**
