### PR TITLE
Editor: Use WebXR's offerSession when available

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #27359

https://raw.githack.com/mrdoob/three.js/dev/editor/index.html

/fyi @cabanier

### CODE REVIEW

**Comment by cabanier** [comment]
awesome! thanks

**Comment by mrdoob** [comment]
@cabanier The editor no longer loads on the Quest Pro after this PR.

a7a523ab85b786d8f0802aa2d808c4c4

**Comment by cabanier** [comment]
o woah! The crash corgi!
Can you hit the oculus button 5 times and file a bugreport?
Also if you have adb can you do `adb logcat > out.txt`, reproduce the crash and send me the log file?

**Comment by mrdoob** [comment]
I don't have adb unfortunately...

Are you able to reproduce on your Quest Pro?

**Comment by cabanier** [comment]
I'm on PTO this week. I'll forward to my team

**Comment by mrdoob** [comment]
I've filled a bug report. It crashes on Quest 3 too.

**Comment by cabanier** [comment]
how do you reproduce? Just open the URL above and go immersive?

We got your report.

**Comment by mrdoob** [comment]
Just trying to open the URL is enough. The browser will try a few times and then corgi appears.

**Comment by sylwesterdigital** [comment]
> o woah! The crash corgi! Can you hit the oculus button 5 times and file a bugreport? Also if you have adb can you do `adb logcat > out.txt`, reproduce the crash and send me the log file?

I have attached an adb log if this still is valid from the corgi circular loop.
[threejs-editor-corgi-adb-log.txt](https://github.com/mrdoob/three.js/files/14380748/threejs-editor-corgi-adb-log.txt)

**Comment by cabanier** [comment]
I found the issue on our side. You're calling `offerSession` very soon after page load at which point we didn't initialize WebXR yet.
I will fix this for the next browser version.

**Comment by mrdoob** [comment]
Excellent. What browser version will that be?

**Pull request merged**
