### PR TITLE
OrbitControls: Improve mouse customizable options

### PR DESCRIPTION
**Pull request by sciecode**
This is a logical follow up over the previous improvement of allowing users a better control over the mouse actions. These changes allow for complete customization of `mouseButtons`.

Currently, we only allow for swapping LEFT and RIGHT buttons between ROTATE and PAN. 
With this PR users are able to bind ROTATE, PAN and DOLLY to any of the mouse buttons.

@WestLangley mind reviewing these changes?

### CODE REVIEW

**Comment by Mugen87** [comment]
It makes the code definitely more readable 👍 .

**Comment by Mugen87** [comment]
http://raw.githack.com/sciecode/three.js/dev-orbit-buttons/examples/misc_controls_orbit.html

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 Ugh.  I just deleted the live link since it no longer is valid. Sorry. In the future I'll let you do that.

**Comment by sciecode** [comment]
I've been using production githack links, those don't go bad after user deletes branch.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
