### PR TITLE
Editor: Refactored SidebarMaterial

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

Better late than never...

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/mrdoob/three.js/editor/editor/index.html

**Comment by Mugen87** [comment]
Much cleaner!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
I've broken multi-material support though...

I'll see if I can fix it during the next dev cycle. Although I do not remember what loaders produce multi materials.

**Comment by Mugen87** [comment]
> Although I do not remember what loaders produce multi materials.

`OBJLoader` does.

https://github.com/mrdoob/three.js/blob/5820a00a2d0f10c619bf7281f48018fba44e9d65/examples/jsm/loaders/OBJLoader.js#L837

**Comment by mrdoob** [comment]
I'm definitely not a fan of all the multi-material / groups design... But I'll try to get it working again next month 😬

**Pull request merged**
