### PR TITLE
Texture: Use default value for image setter.

### PR DESCRIPTION
**Pull request by xlsfs**
If "data" is "undefined ", "serializeImage(data)" will report an error

### CODE REVIEW

**Comment by Mugen87** [comment]
If `Source.data` becomes `undefined`, it's an app level error. 

Do you mind describing how `Source.data` gets this value?

**Comment by xlsfs** [comment]
I used the browser plugin "oslabs-beta/BACE", which used ".image = undefined"
Line 54 of this file: https://github.com/oslabs-beta/BACE/blob/dev/src/content/toJSON.js#L54

**Comment by Mugen87** [comment]
Do you mind changing this line instead:
https://github.com/mrdoob/three.js/blob/acb58df60448e75561c363f142f0df878705443d/src/textures/Texture.js#L86
to 
```js
set image( value = null ) { 
```
That should also do the trick.

**Comment by xlsfs** [comment]
ok thanks, I have amended the commit

**Pull request merged**
