### PR TITLE
Remove unused `is*` properties

### PR DESCRIPTION
**Pull request by Rich-Harris**
This is the PR mentioned in https://github.com/mrdoob/three.js/pull/9310#issuecomment-234533375 – whereas the module conversion script was forced to be conservative in order to retain all functionality, we're now in a position to sand down the rough edges. In particular, the proliferation of `this.isWhatever = true` statements was a bit unsightly.
1. `isWhatever` properties are moved to the prototype where they belong (this was difficult to automate hence me doing it now) – will reduce noise when inspecting objects in devtools
2. In cases where the `isWhatever` property is never actually used, it's removed altogether

This shaves just over 5kb off the minified bundle (~800 bytes gzipped).

### CODE REVIEW

**Comment by Rich-Harris** [comment]
FYI am working on those merge conflicts...

**Comment by WestLangley** [comment]
Friendly tip: Please do not include the build files in the PR.

**Comment by Rich-Harris** [comment]
@WestLangley sorry about that, have removed the build files

**Comment by WestLangley** [comment]
@Rich-Harris No need to apologize.

**Comment by mrdoob** [comment]
Thanks!!

**Comment by mrdoob** [comment]
Something the previous build system did was removing the comments from the .glsl files at build time...

https://github.com/mrdoob/three.js/blob/dev/utils/build/build.py#L62-L69

Is there a way the new build system could do the same?

**Comment by Rich-Harris** [comment]
Certainly! Opened https://github.com/mrdoob/three.js/pull/9389

**Pull request merged**
