### PR TITLE
ocean shader example with gerstner waves

### PR DESCRIPTION
**Pull request by Sean-Bradley**
This is the classic ocean shader example, but modifying the vertices in the vertex shader using a gerstner/trochoidal wave function.

Admittedly its not perfect, and I suspect there is something wrong with how I calculate the normals that are used to mimic the buoyancy angle. But I think it looks pretty good anyway.

Maybe its a good example to add to the official examples. No problem otherwise. I will probably host a mit example of it somewhere anyway.

Local dev url ; http://127.0.0.1:8080/examples/webgl_shaders_ocean_gerstner.html

gerstner-waves

### CODE REVIEW

**Comment by mrdoob** [comment]
Live link: https://raw.githack.com/Sean-Bradley/three.js/gerstner-waves/examples/webgl_shaders_ocean_gerstner.html

**Comment by mrdoob** [comment]
I think there is something wrong with the lighting 🤔

**Comment by Mugen87** [comment]
TBH, I vote for sharing this code as resource in the forum and not add it to the examples. Custom shaders enhanced with shaders chunks are hard to maintain I think this examples is just too specific. Especially since there are already multiple water implementations.

**Comment by Sean-Bradley** [comment]
No problem, 
I'll close it. It is a bit specific. But it does look good.
I'll post the link on discourse as a resource.

**Pull request closed without merging**
