### PR TITLE
Update TubeGeometry.js

### PR DESCRIPTION
**Pull request by NiklasKnaack**
Instead of one radius, you can define a start and an end radius. Very useful for conical tubes.

### CODE REVIEW

**Comment by liuhongyi0101** [comment]
good

**Comment by WestLangley** [comment]
This API change will break everyone's code.

Also, we [previously](https://github.com/mrdoob/three.js/pull/5679/files) had a `taper` property and it was [removed](https://github.com/mrdoob/three.js/pull/9841).

Will `LatheBufferGeometry` work for your use case?

**Comment by NiklasKnaack** [comment]
That's true. 
But, do LatheBufferGeometry and CatmullRomCurve3 work together?
I'll try it with LatheBufferGeometry. Hopefully i can do with it also stuff like that:
http://blog.niklasknaack.de/2017/02/tentacle-creature.html

**Comment by WestLangley** [comment]
>But, do LatheBufferGeometry and CatmullRomCurve3 work together?

No.

By the way, if you taper your `TubeGeometry`, you need to adjust the normals accordingly. You are not doing that.

**Pull request closed without merging**
