### PR TITLE
Examples: Move jsm/nodes to ES6.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

Since devs still work at this part of the repository, it's actually better to move it to ES6, too.

### CODE REVIEW

**Comment by mrdoob** [comment]
Which should be merged first? This one or https://github.com/mrdoob/three.js/pull/21800?

**Comment by donmccurdy** [comment]
Let's merge this PR first, I can clean up the other one afterward. Will be glad to have ES6 Class syntax here! 👍

**Comment by Mugen87** [comment]
@sunag I have not converted the following line to ES6: 

https://github.com/mrdoob/three.js/blob/b13eccc8bf1b6aeecf6e5652ba18d2425f6ec22f/examples/jsm/nodes/core/TempNode.js#L68-L70

I'm not sure why `generate()` is called twice in different ways? 🤔

**Comment by sunag** [comment]
A long time ago I made this block of code, it is in need of some revisions... 
The use `prototype` is to prevent call the abstract function without call the `generateTempVar`.

I don`t test it but we could do something different now, like this for example:

```js
..

name = this.generateTempVar( builder, output, uuid, data.output, ns );

const code = this.generate( builder, type, uuid );

..

generateTempVar( builder, output, uuid, type, ns ) {

	if ( ! this.getShared( builder, output ) ) console.error( 'THREE.TempNode is not shared!' );

	uuid = uuid || this.uuid;

	return builder.getTempVar( uuid, type || this.getType( builder ), ns, this.getLabel() ).name;

}

generate( builder, output, uuid, type, ns ) {

	return this.generateTempVar( builder, output, uuid, type, ns );

}

```

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
