### PR TITLE
Fixed Bug in Double Byte Code in utf8Read

### PR DESCRIPTION
**Pull request by kkruups**
Code before fix was extracting 4-bits from 1st utf8 Byte instead of 5 bits, resulting in 10-bit binary number instead of 11-bit as specified for Double Byte.

### CODE REVIEW

**Comment by kkruups** [comment]
Hi,
I just wanted to add fix for msgpack-js.js, but had to resolve merge issue with FileLoader.js.

**Comment by kkruups** [comment]
Add'l info comments in code snippet provides details on fix :

 string += String.fromCharCode(
        ((byte & 0x0f) << 6) |   //note:  this is a bug here, should be 0x1f not 0x0f
        (view.getUint8(++i) & 0x3f)      //Get 2nd Byte, then
                                         //Extract right-most 6-bits from 2nd Byte, 10xxxxxx, and bitwiseAnd with 0x3f (111111),
                                         //10xxxxxx & 111111 == xxxxxx then bitwiseOR   nnnnn000000 | xxxxxx == nnnnnxxxxxx to build charcode
      );

**Comment by mrdoob** [comment]
> I just wanted to add fix for msgpack-js.js, but had to resolve merge issue with FileLoader.js.

I think it's better if you fork my `dev` into a new branch.

For this specific case, you can actually do the change directly here:
https://github.com/mrdoob/three.js/edit/dev/examples/js/libs/msgpack-js.js

However, shouldn't this fix go to here instead? https://github.com/creationix/msgpack-js

**Comment by kkruups** [comment]
@mrdoob ,
Yes, my fix pull request was submitted and committed @creationix/msgpack-js.
However, I did not see fix reflected in code in this repository,three.js, so  I decided to add here as well. 
I will do as u recommend, make change directly.  

BR/KK

**Comment by mrdoob** [comment]
#12146

**Pull request closed without merging**
