### PR TITLE
Editor: Add parent and index parameters to AddObjectCommand.

### PR DESCRIPTION
**Pull request by 1993heqiang**
**Description**
Add parent and index parameters to AddObjectCommand.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, what does this solve?

**Comment by 1993heqiang** [comment]
> Hmm, what does this solve?

When I need to add a child to an object, I can use it directly. Instead, first use `AddObjectCommand `to create a new object, and then use `MoveObjectCommand` to move the object.

**Comment by 1993heqiang** [comment]
In the process of using the editor, I select an object in the scene tree, and then add an object. I prefer to add a sub-object to the selected object instead of adding an object directly to the scene. 😄

**Comment by Mugen87** [comment]
Can you please describe step by step how to reproduce the issue? I'm afraid it's not yet clear what this PR is going to fix.

If you are working with modified editor source code for your project, it's unlikely that this PR is going to be merged (since it's purely application specific).

**Comment by 1993heqiang** [comment]
> Can you please describe step by step how to reproduce the issue? I'm afraid it's not yet clear what this PR is going to fix.
> 
> If you are working with modified editor source code for your project, it's unlikely that this PR is going to be merged (since it's purely application specific).

This PR is not to fix a problem, increasing the Parent and Index parameters make this command more flexible, similar to the Add method in Editor.js.

**Comment by Mugen87** [comment]
Sorry, but I'm afraid this change is confusing. The internals of the editor are not meant to be a public API. 

If features are not used in the code base, there is no need to add them.

**Comment by 1993heqiang** [comment]
OK. I will close it.

**Pull request closed without merging**
