### PR TITLE
[EXAMPLES] Added BufferGeometry morph example

### PR DESCRIPTION
**Pull request by looeee**
Added basic buffergeometry morph target example. Replacement for #13847

[Live link](https://raw.githack.com/looeee/three.js/examples_buffergeometry_morph/examples/webgl_buffergeometry_morphtargets.html)

### CODE REVIEW

**Comment by looeee** [comment]
I've added this to the `WebGL / Advanced` section in the examples since that's where all the other buffer geometry examples are, however I'm not sure that's the right place for it since it's supposed to be an introductory example. 

Also, perhaps we should rename [webgl_morphtargets](https://threejs.org/examples/webgl_morphtargets) to `webgl_geometry_morphtargets`?

**Comment by mrdoob** [comment]
For this example, how about creating a `BoxBufferGeometry` then clone it and spherify the clone (basically normalize every vertex position). And maybe for the 2nd clone apply a twist to the vertices?

**Comment by looeee** [comment]
@mrdoob OK, done 😄

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
