### PR TITLE
Added eye-dome lighting example

### PR DESCRIPTION
**Pull request by brucedjones**
Reference for eyedome lighting: https://www.researchgate.net/publication/320616607_Eye-Dome_Lighting_a_non-photorealistic_shading_technique

Based on the approach used by Potree:https://github.com/potree/potree/

### CODE REVIEW

**Comment by WestLangley** [comment]
Live: https://rawgit.com/brucedjones/three.js/dev/examples/webgl_postprocessing_eye_dome_lighting.html

There is no reason all the meshes have to have the same color.

**Comment by WestLangley** [comment]
If there is interest, I expect this should be implemented as `EDLPass.js`, instead -- to be used with `EffectComposer`. See, for example, https://threejs.org/examples/webgl_postprocessing_ssao.html.

@bhouston Are you familiar with this technique? I was not.

**Comment by brucedjones** [comment]
I've updated the example to give each mesh a random color.

I agree that this could be implemented more generally. I just wrote this as a learning exercise and thought it would be worth contributing back.

**Comment by bhouston** [comment]
It seems like it is a MatCap under a different name?

**Comment by bhouston** [comment]
This description sounds like it is another form SAO / SSAO - I guess we can have more in examples/js:

```
The basic principle of the EDL algorithm is to consider a half-sphere (the dome) centered at each pixel p. This dome is bounded by “a horizontal plane,” which is perpendicular to the observer direction at point p. The shading is a function of the amount of this dome visible at p, or conversely, it is inversely determined by the amount of this dome hidden by the neighbors of p (those being taken on a ring around p in image space). In other words, a neighbor pixel will reduce the lighting at p if its depth is lower (i.e. closer to the viewer) than the one of p. This procedure defines a shading amount that depends solely on the depth values of the close neighbors. To achieve a better shading that takes into account farther neighbor pixels, a multi-scale approach is implemented, with the same shading function being applied at lower resolutions (typically half and quarter image size). Those shaded images are then filtered in order to limit aliasing induced by lower resolution, using a cross bilateral filter [3] (Gaussian blur modulated by depth differences), and then merged together with the full resolution shaded image. This approach is graphically represented in Figure 2. 
```

https://blog.kitware.com/eye-dome-lighting-a-non-photorealistic-shading-technique/

**Comment by WestLangley** [comment]
>I agree that this could be implemented more generally. I just wrote this as a learning exercise and thought it would be worth contributing back.

Would you be interested in creating `EDLPass.js`, instead?

**Comment by brucedjones** [comment]
I am interested for sure, but I don't think i'll be able to get around to it any time soon.

**Comment by m-schuetz** [comment]
The EDL sample at https://rawgit.com/brucedjones/three.js/dev/examples/webgl_postprocessing_eye_dome_lighting.html  is currently sensitive to the near clip plane. I guess that readDepth doesn't actually return the log2(linearDepth) because ```texture2D( depthSampler, coord ).x``` doesn't return the linear depth but [0,1] (?)

**Comment by m-schuetz** [comment]
Probably due to the same reason but what I was referring to is that when you change the near clip plane  (```camera.near = 1.0; camera.updateProjectionMatrix();```) the shading changes as well.

**Comment by Mugen87** [comment]
@brucedjones Thanks for the PR however there are a few things that prevents it from being merged.

As mentioned by @WestLangley it would be better to put the code into a `EDLPass` class in order to enable a post-processing setup like this:
```js
const composer = new EffectComposer( renderer );

const renderPass = new RenderPass( scene, camera );
composer.addPass( renderPass );

const edlPass = new EDLPass( options );
composer.addPass( edlPass );
```
Besides, the example code needs be implemented based on modules. And it's necessary to resolve the mentioned shading artifacts.

I'd be happy to review/support a new PR since the presented technique is definitely interesting.

**Pull request closed without merging**
