### PR TITLE
Shadowing / Culling

### PR DESCRIPTION
**Pull request by tschw**

### CODE REVIEW

**Comment by tschw** [comment]
Will temporarily include builds for testing.

**Comment by tschw** [comment]
Seems to fix #8760.

**Comment by killroy42** [comment]
Will run this for testing... Thanks!

**Comment by mrdoob** [comment]
Thanks for doing the extra clean up! 😊

**Comment by tschw** [comment]
> Thanks for doing the extra clean up!

NP, just picking up stuff on the go.

Please note that I don't mind taking the builds out before the merge. Squash-merged builds cause a bit of a mess in case we want to revert after their next update. Not that I expect that we will, but having the option could be worth a little delay.

**Comment by killroy42** [comment]
I'm currently working on a prototyping framework that should also easily plug into codepen. I'll try to clean it all up and create a repo for it all, including the multi-revision "harness". Might make it easier to fill out more of those checkmarks in the issue reports.

**Comment by tschw** [comment]
I guess I'll just use a second non-PR branch for testing, next time. Or there might be threejsworker-way, once it's back online...

@killroy42 
> I'm currently working on a prototyping framework that should also easily plug into codepen. I'll try to clean it all up and create a repo for it all, including the multi-revision "harness". Might make it easier to fill out more of those checkmarks in the issue reports.

:+1: Please promote the use of non-minified / debuggable builds.

**Pull request merged**
