### PR TITLE
Ported canvas particles waves example to webgl

### PR DESCRIPTION
**Pull request by WestLangley**
As suggested in https://github.com/mrdoob/three.js/issues/14581#issuecomment-432483311.

This is a direct port. I'd suggest it be upgraded later to use `Points` instead of `Sprite`. Hence, the slight name change.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Review by looeee — APPROVED** [review]

**Comment by mrdoob** [comment]
> This is a direct port. I'd suggest it be upgraded later to use Points instead of Sprite. Hence, the slight name change.

Agreed. But then it'll need a custom shader, right?

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
>Agreed. But then it'll need a custom shader, right?

Currently, there are 2500 draw calls. You can use `Points` and `PointsMaterial` with a `map`, or you can use `Points` with `ShaderMaterial` and a custom fragment shader that discards fragments to create circular points.

Note, there is a max size that gl_points will render. I'm not sure if that limit would be reached in this demo.

You could also use instancing, and update all positions on the GPU.

It depends on what three.js features you want to demonstrate.

**Comment by WestLangley** [comment]
@Mugen87 I deleted your temporary live link. I try to clean those up. Sorry, I didn't realize an unexplained reference to your comment would linger...

**Comment by Mugen87** [comment]
No problem 😊

**Comment by WestLangley** [comment]
Maybe it it better just to edit the post like so if it is not one's own, or if it contains additional content:

    Temporary live link removed.

**Pull request merged**
