### PR TITLE
Fix collada loader to load faces with multiple materials properly, setting materialIndex

### PR DESCRIPTION
**Pull request by jterrace**

### CODE REVIEW

**Comment by schubboy** [comment]
I can confirm that this issue has re-appeared in r75.

**Comment by schubboy** [comment]
and this seems to be the fix, (but don't quote me on it):

In the "ColladaLoader.js" file:
Take the for loop on line 4656 from version r73 and paste it under line 1173 in version r75

Multi-Materials appear to work (at cursory glance) with that line in there.

**Comment by mrdoob** [comment]
Do you mind sharing here the loop you're referring to?

**Comment by schubboy** [comment]
for (j = 0; j < geom.faces.length; j++) {

						var face = geom.faces[j];
						face.materialIndex = used_materials[face.daeMaterial]

					}

**Comment by mrdoob** [comment]
#8598

**Pull request closed without merging**
