### PR TITLE
Add a link to readme

### PR DESCRIPTION
**Pull request by sasha240100**
@mrdoob I made a hard work making the [framework for Three.js](https://github.com/WhitestormJS/whitestorm.js). My first idea was to just join Three.js and 3D physics, by then I realized that it will be much better to have a simple, flexible structure that will make any integrations for Three.js simple.

**TL;DR:** I understand that adding a link to Three.js can be a bit aggressive, but **I will appreciate if you will decide to merge this.**

This framework is a hard work of last 3 years. **My goal is to open as many integrations for Three.js as i can. And that's what possible with [Whitestorm.js](https://github.com/WhitestormJS/whitestorm.js) right now:**

 - Component-oriented structure
 - [Modules](https://hackernoon.com/migrating-to-whitestormjs-v2-beta-module-system-2eeaeda08a80#.63ub1x1g6) (plugins)
 - [Physics integration in a few steps](https://github.com/WhitestormJS/whitestorm.js#why)
 - You can switch from one physics module to another just by replacing module. (API is similar)
 - [React-whs](https://github.com/WhitestormJS/react-whs) - integration with ReactJS.
 - Integration with React Native (will be soon, i already have a working example)
 - Modules for [stats.js](https://github.com/WhitestormJS/whs-module-statsjs) and [dat.gui](https://github.com/WhitestormJS/whs-module-dat.gui)

**Whitestorm.js is used in pair with Three.js. From my perspective, it's like some kind of React for DOM, but for Three.js (i hope so).**

_*whs -whitestorm.js_

I'm not sure, but it would be awesome if it fits near "editor" link on Three.js website.

**Thanks to all Three.js community for this awesome library!** ☺️

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting... Yeah, I think we should list somewhere all the frameworks built on top of three.js.

Here's the ones I know:

* A-Frame
* ReactVR
* SceneVR
* Whitestorm.js

**Comment by sasha240100** [comment]
@mrdoob Yep, adding them to main pages of three.js will help people to save a time and be able to compare them to their needs.

Do I need to make a commit to add links of them?

**Comment by mrdoob** [comment]
I don't think the README is the right place for this. Not sure what's the right place for it really.

**Comment by sasha240100** [comment]
@mrdoob okay. How about website?

**Comment by sasha240100** [comment]
@mrdoob How about just a friendly link on a website?))

**Pull request closed without merging**
