### PR TITLE
WebGLRenderTargetCube: removed references to THREE namespace

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes https://github.com/mrdoob/three.js/pull/16671#discussion_r294359348.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
This PR generates a circular dependency. Not sure how to fix that...
```js
src/renderers/WebGLRenderTargetCube.js -> src/cameras/CubeCamera.js -> src/renderers/WebGLRenderTargetCube.js
```

**Comment by WestLangley** [comment]
Any ideas?...

**Comment by mrdoob** [comment]
No rush I think, we'll get a reminder every time we recompile anyway hehe

**Comment by Mugen87** [comment]
Just for my understanding: Why not putting `fromEquirectangularTexture()` to `CubeTexture` instead like suggested here: #9746. This would resolve the circular dependency.

**Pull request merged**
