### PR TITLE
WebGLRenderer: Added SortingGroup

### LINKED ISSUE #14415: Two mesh with Muti-Materials set same renderOrder value, the z-order is not correct?
##### Description of the problem

I create two mesh with same renderOrder. 

```js
var circleGeometry = new THREE.CircleBufferGeometry(radius, segements);                                                                                                                                                                 
var ringGeometry = new THREE.RingBufferGeometry(radius, radius + ringWidth, segements);                                                                                                                                                                 
var cellGeometry = null;
  
//...

var circleMaterial = new THREE.MeshBasicMaterial({                                                                                                                                                                                                                                                                        
  map: texture,                                                                                                                                                                                                                                                                                                         
  // wireframe: true                                                                                                                                                                                                                                                                                                    
});                                                                                                                                                                                                                                                                                                                       
var ringMaterial = new THREE.MeshBasicMaterial({                                                                                                                                                                                                                                                                          
  color: 0x000000,                                                                                                                                                                                                                                                                                                      
  vertexColors: THREE.VertexColors,                                                                                                                                                                                                                                                                                     
  // wireframe: true                                                                                                                                                                                                                                                                                                    
});
                                                                                                                                                                                                                                                                                               
cellGeometry = THREE.BufferGeometryUtils.mergeBufferGeometries([circleGeometry, ringGeometry], true);                                                                                                                                                                                                                     
var mesh1 = new THREE.Mesh(cellGeometry, [circleMaterial, ringMaterial]);                                                                                                                                                                                                                                                 
scene.add(mesh1);                                                                                                                                                                                                                                                                                                         
mesh1.renderOrder = radius;                                                                                                                                                                                                                                                                                               
var mesh2 = new THREE.Mesh(cellGeometry, [circleMaterial, ringMaterial]);                                                                                                                                                                                                                                                 
mesh2.position.x += 2;                                                                                                                                                                                                                                                                                                    
mesh2.renderOrder = radius;    
                                                                                                                                                                                                                                                                             
scene.add(mesh2);  
```

The result was not correct, see screenshot!
![1530709073076](https://user-images.githubusercontent.com/1814495/42278306-f63daf40-7fcc-11e8-9063-b8cecd26014d.jpg)
￼

##### Three.js version


- [ ] r94


##### Browser

- [x] Chrome


##### OS


- [ ] macOS

##### Hardware Requirements (graphics card, VR Device, ...)

### PR DESCRIPTION
**Pull request by Mugen87**
Fixes #14415

The PR introduces a new class `SortingGroup` which can be used to group objects within the render list. So it's somewhat similar to Unity's [SortingGroup](https://docs.unity3d.com/ScriptReference/Rendering.SortingGroup.html) API.

### CODE REVIEW

**Comment by Mugen87** [comment]
Nested groups are not supported so far. The PR is just a first approach to see such a system in action.

**Comment by WestLangley** [comment]
So, within a sorting group, `object.renderOrder` only applies relative to the objects within the sorting group.  Is that your intention?

If so, I expect `SortingGroup` will have to have its `renderOrder` property honored so the sorting groups can be sorted.

**Comment by WestLangley** [comment]
And a sorting group should not contain both opaque and transparent renderable objects. I think that is OK, though.

**Comment by WestLangley** [comment]
@mrdoob I wonder if `SVGLoader` could make use of this feature to ensure the shapes are rendered in the proper order -- especially if there are multiple SVG objects, or other objects in the scene.

**Comment by Mugen87** [comment]
> So, within a sorting group, object.renderOrder only applies relative to the objects within the sorting group. Is that your intention?

Yes. And if `SortingGroup` groups are not used at all, `renderOrder` has still the highest priority.

> If so, I expect SortingGroup will have to have its renderOrder property honored so the sorting groups can be sorted.

Um, I'm not sure how to solve this. Objects of type `SortingGroup` are not added to the render list so it's not possible to sort them right now. I guess we need some additional logic for this use case...

**Comment by WestLangley** [comment]
Yes. You have to be able to sort the sorting groups themselves.

**Comment by navigator117** [comment]
Mesh without SortingGroup parent should be able to compare renderOrder with SortingGroup, as unity does this.

**Comment by Mugen87** [comment]
This should work now, too. The code is also slightly refactored so changes to `projectObject()` are not necessary anymore.

https://jsfiddle.net/f2Lommf5/8969/

**Comment by Mugen87** [comment]
Nevertheless the holistic architecture of this approach feels hacky. Besides, the current way `WebGLSortingGroups` and `WebGLRenderList` are working together is no good. I'm closing the PR for now and try to think of a different approach.

**Comment by mrdoob** [comment]
Patch:

```diff
diff --git a/src/renderers/WebGLRenderer.js b/src/renderers/WebGLRenderer.js
index 4f61704e7..f684902b8 100644
--- a/src/renderers/WebGLRenderer.js
+++ b/src/renderers/WebGLRenderer.js
@@ -1073,7 +1073,7 @@ function WebGLRenderer( parameters ) {
 		currentRenderList = renderLists.get( scene, camera );
 		currentRenderList.init();
 
-		projectObject( scene, camera, _this.sortObjects );
+		projectObject( scene, camera, 0, _this.sortObjects );
 
 		if ( _this.sortObjects === true ) {
 
@@ -1164,7 +1164,7 @@ function WebGLRenderer( parameters ) {
 
 	};
 
-	function projectObject( object, camera, sortObjects ) {
+	function projectObject( object, camera, groupOrder, sortObjects ) {
 
 		if ( object.visible === false ) return;
 
@@ -1172,7 +1172,11 @@ function WebGLRenderer( parameters ) {
 
 		if ( visible ) {
 
-			if ( object.isLight ) {
+			if ( object.isGroup ) {
+
+				groupOrder = object.renderOrder;
+
+			} else if ( object.isLight ) {
 
 				currentRenderState.pushLight( object );
 
@@ -1196,7 +1200,7 @@ function WebGLRenderer( parameters ) {
 					var geometry = objects.update( object );
 					var material = object.material;
 
-					currentRenderList.push( object, geometry, material, _vector3.z, null );
+					currentRenderList.push( object, geometry, material, groupOrder, _vector3.z, null );
 
 				}
 
@@ -1209,7 +1213,7 @@ function WebGLRenderer( parameters ) {
 
 				}
 
-				currentRenderList.push( object, null, object.material, _vector3.z, null );
+				currentRenderList.push( object, null, object.material, groupOrder, _vector3.z, null );
 
 			} else if ( object.isMesh || object.isLine || object.isPoints ) {
 
@@ -1242,7 +1246,7 @@ function WebGLRenderer( parameters ) {
 
 							if ( groupMaterial && groupMaterial.visible ) {
 
-								currentRenderList.push( object, geometry, groupMaterial, _vector3.z, group );
+								currentRenderList.push( object, geometry, groupMaterial, groupOrder, _vector3.z, group );
 
 							}
 
@@ -1250,7 +1254,7 @@ function WebGLRenderer( parameters ) {
 
 					} else if ( material.visible ) {
 
-						currentRenderList.push( object, geometry, material, _vector3.z, null );
+						currentRenderList.push( object, geometry, material, groupOrder, _vector3.z, null );
 
 					}
 
@@ -1264,7 +1268,7 @@ function WebGLRenderer( parameters ) {
 
 		for ( var i = 0, l = children.length; i < l; i ++ ) {
 
-			projectObject( children[ i ], camera, sortObjects );
+			projectObject( children[ i ], camera, groupOrder, sortObjects );
 
 		}
 
diff --git a/src/renderers/webgl/WebGLRenderLists.js b/src/renderers/webgl/WebGLRenderLists.js
index 234de8d5f..0150d2518 100644
--- a/src/renderers/webgl/WebGLRenderLists.js
+++ b/src/renderers/webgl/WebGLRenderLists.js
@@ -4,7 +4,11 @@
 
 function painterSortStable( a, b ) {
 
-	if ( a.renderOrder !== b.renderOrder ) {
+	if ( a.groupOrder !== b.groupOrder ) {
+
+		return a.groupOrder - b.groupOrder;
+
+	} else if ( a.renderOrder !== b.renderOrder ) {
 
 		return a.renderOrder - b.renderOrder;
 
@@ -30,7 +34,11 @@ function painterSortStable( a, b ) {
 
 function reversePainterSortStable( a, b ) {
 
-	if ( a.renderOrder !== b.renderOrder ) {
+	if ( a.groupOrder !== b.groupOrder ) {
+
+		return a.groupOrder - b.groupOrder;
+
+	} else if ( a.renderOrder !== b.renderOrder ) {
 
 		return a.renderOrder - b.renderOrder;
 
@@ -64,7 +72,7 @@ function WebGLRenderList() {
 
 	}
 
-	function getNextRenderItem( object, geometry, material, z, group ) {
+	function getNextRenderItem( object, geometry, material, groupOrder, z, group ) {
 
 		var renderItem = renderItems[ renderItemsIndex ];
 
@@ -76,6 +84,7 @@ function WebGLRenderList() {
 				geometry: geometry,
 				material: material,
 				program: material.program,
+				groupOrder: groupOrder,
 				renderOrder: object.renderOrder,
 				z: z,
 				group: group
@@ -90,6 +99,7 @@ function WebGLRenderList() {
 			renderItem.geometry = geometry;
 			renderItem.material = material;
 			renderItem.program = material.program;
+			renderItem.groupOrder = object.groupOrder;
 			renderItem.renderOrder = object.renderOrder;
 			renderItem.z = z;
 			renderItem.group = group;
```

**Pull request closed without merging**
