### PR TITLE
Color: add .setColorName() and Color.NAMES

### PR DESCRIPTION
**Pull request by pauldps**
**Summary**

* expose `_colorKeywords` (as `Color.NAMES`) to be used by external code
* add `.setColorName` to set color directly from X11 name

**Motivation**

While developing a game using ThreeJS, I noticed the Color class internally declares a list of X11 colors that I could use in my project as well. That object is kind of big so I thought it would be helpful to expose it, keeping me from creating another color list.

I also created a new instance method called `setColorName` which receives the color name and skips unnecessary checks in `setStyle` for better performance.

**Notes**

* The deleted "todo" test block on `setRGB` was apparently duplicated, so I deleted it. The proper test already exists at line ~~298~~ 88.
* ~~While I was at it I added a test on `isColor`.~~ (A test to `isColor` was added by the last rebase so I removed my change.)

This is my first PR, so let me know if I missed anything or did anything wrong. The new code has tests and is properly linted. Any advice and feedback would be appreciated.

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting... Could you also update the docs?

**Comment by pauloddr** [comment]
Will do! 

Meanwhile, I found out my PR doesn't actually _expose_ `ColorKeywords` on the minified version, it just exposes them to whomever is `import`ing them in Node -- not as useful. I probably need to make it available directly on the `Color` object as a static property. Would that be okay?

If so... `Color.ColorKeywords`? Since it's a constant, I was thinking something like `Color.KEYWORDS` or `Color.NAMES`. What do you think?

Whichever option is chosen, I'll update it in the docs as well.

**Comment by pauloddr** [comment]
Implemented as `Color.NAMES`, and added Docs. Let me know if the grammar/wording needs changes. I'm not a native English speaker. :sweat_smile:

**Comment by Mugen87** [comment]
@pauloddr Sorry, this PR gets lost. Do you mind rebasing the PR? 😇

**Comment by pauloddr** [comment]
Rebased! Also made some changes to the PR description based on the resolved conflicts.

**Comment by Mugen87** [comment]
Do you mind updating the [TypeScript declaration](https://github.com/mrdoob/three.js/blob/dev/src/math/Color.d.ts) file for `Color`?  I guess we need these two entries:
```ts
/**
 * Sets this color from a color name. Faster than {@link Color#setStyle .setStyle()} method if you don't need the other CSS-style formats.
 * @param style Color name in X11 format.
 */
setStyleName( style: string ): Color;

/**
 * List of X11 color names.
 */
static NAMES: Record<string, number>;
```

**Comment by mrdoob** [comment]
Also, I think `setColorName()` may be more clear?

**Comment by pauloddr** [comment]
Done and done! I also added a new test to `setStyle` with a color name, which I noticed was missing.

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
