### PR TITLE
add read float buffer example

### PR DESCRIPTION
**Pull request by nraynaud**
the example reads the background texture point under the mouse and
displays the value on the window.

### CODE REVIEW

**Comment by nraynaud** [comment]
Unless I fucked up, the conflict is just because I re-compiled the minified library, it was stale and I couldn't run my new example.

**Comment by WestLangley** [comment]
>Unless I messed up, the conflict is just because I re-compiled the minified library

There is no need to include builds with the PR. Might as well check your formatting, too.

See the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

**Comment by nraynaud** [comment]
It looks like XCode tricked me, it was looking fine there.

**Comment by WestLangley** [comment]
Thank you for your contributions. Like I said, there is no need to include builds with the PR. : - ) That should solve your mistery.

Also see the Wiki article [Mr.doob's-Code-Style™](https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style™).

> It looks like XCode tricked me, it was looking fine there.

Yeah. Your previous PRs have similar issues with leading spaces and formatting, too.

**Comment by nraynaud** [comment]
I tried to format it with the online tool, I don't think I want to create a profile in my IDE for that strange codestyle, I hope you're pleased.

There is still this problem that if I don't send the build the example doesn't work at all out of the box. You seem to be passively aggressively insisting, but I'm not sure. Do you want me to remove the build or is it just 'not needed'?

**Comment by mrdoob** [comment]
> Do you want me to remove the build or is it just 'not needed'?

Yes please, remove the build. I'll update it myself 😊

**Comment by mrdoob** [comment]
Thanks to @gero3 (#7258) you can check your example here too:
http://threejsworker.com/api/pullrequests/7289/examples/webgl_read_float_buffer.html

Which, by the way, as far as I can see, the pixel picked is from the texture in the background so the spheres are probably not needed?

**Comment by nraynaud** [comment]
wait! you had a tool to automatically format the code from the PR and you made me do the roundtrips?

**Comment by mrdoob** [comment]
> wait! you had a tool to automatically format the code from the PR and you made me do the roundtrips?

You mean http://zz85.github.io/mrdoobapproves/? It is linked in the article @WestLangley referenced. Maybe we can improve the wording so it's more obvious.

**Comment by nraynaud** [comment]
No, I saw and used that one. Forget it I misread something on the issue you
referenced.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
