### PR TITLE
FileLoader: Added workaround for Alipay browser's bug.

### PR DESCRIPTION
**Pull request by neciszhang**
Related issue: #23015

**Description**
In Alipay browser, response.body is undefined, when i change it,I load .Glb file successfully in Alipay browser.

### CODE REVIEW

**Comment by Mugen87** [comment]
> In Alipay browser, response.body is undefined

Just for clarification: Is it spec-compliant that `response.body` can be `undefined`? Or is this a browser bug?

**Comment by neciszhang** [comment]
> > In Alipay browser, response.body is undefined
> 
> Just for clarification: Is it spec-compliant that `response.body` can be `undefined`? Or is this a browser bug?
Here is the full response.
image
And "typeof ReadableStream=function" in Alipay Browser .

**Comment by neciszhang** [comment]
> > In Alipay browser, response.body is undefined
> 
> Just for clarification: Is it spec-compliant that `response.body` can be `undefined`? Or is this a browser bug?

The response.body document,[here](https://developer.mozilla.org/en-US/docs/Web/API/Response/body).

**Comment by Mugen87** [comment]
Um, in this case it looks like a browser issue, no? Have you considered to report it to Alipay?

**Comment by mrdoob** [comment]
Hmm, I guess the workaround is not too bad in this case...

**Pull request merged**
