### PR TITLE
FBXLoader: Fix Filename to RelativeFilename in parseImage()

### PR DESCRIPTION
**Pull request by acidsound**
The path of "Filename" property is useless. It depends on local directory (ex. C:\somewhere\blahblah\somefile.fbx). RelativeFilename is better for URI.
I made a tiny example in codesandbox ( https://codesandbox.io/s/y2kv8yyw5j ).
enjoy it! 💃

### CODE REVIEW

**Comment by looeee** [comment]
You'll need to update the line below as well to prevent breaking embedded images:

```
blobs[ videoNode.Filename ] = image;
```
To
```
blobs[ videoNode.RelativeFilename || videoNode.Filename ] = image;
```

**Review by looeee — APPROVED** [review]
Looks good now!

**Comment by mrdoob** [comment]
Thanks!

**Comment by acidsound** [comment]
Awesome! 👍

**Pull request merged**
