### PR TITLE
Show LGTM.com JavaScript code quality badge

### PR DESCRIPTION
**Pull request by sj**
I think this score is something to be proud of!

### CODE REVIEW

**Comment by Mugen87** [comment]
I just wondering why `lgtm.com` still shows a label for Python.

image

After the removal of the Blender exporter, the repo is free of Python code. There are also many warnings which refer to deleted Python files.

**Comment by sjvs** [comment]
@Mugen87: good spot. Python analysis has been disabled manually after the last Python file was deleted, but LGTM defaults to showing the data from the last successful analysis (i.e., when there was still Python code). That's why you still see the badge and the alerts. We're working on resolving that ASAP!

**Comment by Mugen87** [comment]
Okay, I see. Thanks for the information 👍

**Comment by mrdoob** [comment]
I think the page it links to is confusing:
https://lgtm.com/projects/g/mrdoob/three.js/context:javascript

I think it would be better if it just linked to the root:
https://lgtm.com/projects/g/mrdoob/three.js/

**Comment by mrdoob** [comment]
Also, I think the badge should just say "code quality" (without the js/ts) as github already states there is only javascript in the repo so it's redundant.

**Comment by sjvs** [comment]
I've updated the link, but unfortunately it's not possible to change the text on the badge. That's stored hard-coded by our friends at shields.io. Hope that's OK!

**Comment by sjvs** [comment]
Apologies — one of my colleagues pointed out that it is actually possible to override the label on a badge. I've changed it now.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I changed the badge to be a bit more subtle... The more subtle the badge is the more it's going to spread I think ✌️

**Comment by Mugen87** [comment]
> Python analysis has been disabled manually after the last Python file was deleted, but LGTM defaults to showing the data from the last successful analysis (i.e., when there was still Python code). That's why you still see the badge and the alerts. We're working on resolving that ASAP!

@sj It still seems `lgtm.com` shows a rating for Python code, see 

image

Besides, `lgtm.com` shows 62 phyton alerts although the files are deleted for quite a while now. I would expect `lgtm.com` recognizes the deletion and then removes the respective alerts.

**Comment by makc** [comment]
@Mugen87 it is easy then, no?
* add perfect python one liner file,
* enable and run lgtm,
* remove python file,
* disable lgtm again

**Comment by Mugen87** [comment]
I can only repeat myself. I files are deleted, the respective `lgtm` errors should also be gone. This is obviously not the case.

**Comment by makc** [comment]
weird thing, lgtm has direct link to files which I thought would point to a branch where python files were not removed, but no. the link, for example, is https://github.com/mrdoob/three.js/tree/3cfe5ed63f964614fd41cf4aec52e4bbb5ca4d12/utils/exporters/blender/addons/io_three/constants.py and 3cfe5ed is the latest commit from yesterday

**Comment by mrdoob** [comment]
> @Mugen87 it is easy then, no?
> * add perfect python one liner file,
> * enable and run lgtm,
> * remove python file,
> * disable lgtm again

That may work?

**Comment by makc** [comment]
@mrdoob it might not work if what he says was true before python parsing was disabled.

**Comment by Mugen87** [comment]
>  it might not work if what he says was true before python parsing was disabled.

What  do you mean by disabled? AFAIK, it's not possible to disable languages at `lgtm.com` yet, see https://discuss.lgtm.com/t/disable-javascript-analysis/2150/2.

**Comment by makc** [comment]
@Mugen87 I was referring to this part:
> Python analysis has been disabled manually after the last Python file was deleted

how could it have been "disabled manually" if you say "it's not possible to disable languages at lgtm.com yet"

**Comment by makc** [comment]
regardless, if it was disabled AFTER the files were deleted, none of this matters, I guess... I was thinking that disabling was what froze the results, and then enabling it back would make it notice that python files are gone.

**Comment by Mugen87** [comment]
I see. In any event, I would expect that if you delete a file the respective alerts also disappear. How do you feel abou this?

**Comment by mrdoob** [comment]
Should we add a python file somewhere to see what happens?

**Comment by Mugen87** [comment]
Yes, I'm curious now 🤓 .

**Comment by mrdoob** [comment]
Done! 🧐

**Comment by makc** [comment]
@mrdoob maybe you need to press some buttons [here](https://lgtm.com/projects/g/mrdoob/three.js/ci/) in on demand tab or Idk

**Comment by mrdoob** [comment]
It usually takes some hours. We'll check again tomorrow.

**Comment by mrdoob** [comment]
Screen Shot 2020-03-23 at 11 20 32 AM

**Pull request merged**
