### PR TITLE
BufferGeometry: Add ability to read interleaved data in computeVertexNormals().

### PR DESCRIPTION
**Pull request by Mugen87**
From #18433. This modification helps to read interleaved data for normal computations. A new attribute is not interleaved however the method computes now data which are at least usable.

### CODE REVIEW

**Comment by WestLangley** [comment]
Should the title be `BufferGeometry: support interleaved positions in computeVertexNormals()`?

In other words, is that an accurate description of what this is doing?

**Comment by Mugen87** [comment]
First, I've hesitated a bit since I wanted to avoid confusion. The PR adds no real interleaved buffer support. Just the ability to read interleaved data by using the generic getter and setters from the `BufferAttribute` API. But your title is indeed more descriptive. Changing...

**Comment by Mugen87** [comment]
I've slightly changed the title compared to yours since reading index data is now different, too.

**Comment by WestLangley** [comment]
>The PR adds no real interleaved buffer support. Just the ability to read interleaved data 

It seems to me you are supporting reading and _setting_ (existing) interleaved data.

Should the title be `BufferGeometry: support interleaved data in computeVertexNormals()`?

**Comment by Mugen87** [comment]
The problem is when the buffer attribute for normals needs to be created, data are not interleaved.
```js
normalAttribute = new BufferAttribute( new Float32Array( positionAttribute.count * 3 ), 3 );
```
 It would only work for existing normals hence it's not a real support :(.

**Comment by mrdoob** [comment]
Hmm, if this is not fixing it... wouldn't it be better to check if it's interleaved and log a warning that is not supported?

**Comment by WestLangley** [comment]
@mrdoob He is fixing it. It is just that if normals do not exist, then non-interleaved normals are added. That is reasonable.

**Comment by mrdoob** [comment]
Ah, I see! 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
