### PR TITLE
MeshPhysicalMaterial JSON and editor support

### PR DESCRIPTION
**Pull request by aardgoose**
First look at Editor code, but it seems to work.
(now it is documented someone may come looking for it)

### CODE REVIEW

**Comment by aardgoose** [comment]
Reflectivity parameter not added yet, this clashes with reflectivity in MeshPhongMaterial which is linked to envMap... so the interface gets messy.

**Comment by aardgoose** [comment]
@WestLangley is the reflectivity name clash something you are working on?  I've noticed you have added envMapIntensity to MeshStandardMaterial but it doesn't look like it is wired up yet?

**Comment by WestLangley** [comment]
>is the reflectivity name clash something you are working on?

No. Why is this a problem?

>I've noticed you have added envMapIntensity to MeshStandardMaterial but it doesn't look like it is wired up yet?

It works for me outside the editor. What do you mean by "not wired up"?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> Reflectivity parameter not added yet, this clashes with reflectivity in MeshPhongMaterial which is linked to envMap... so the interface gets messy. 

Yeah, I haven't had a chance to look into this, I remember it being messy indeed.

**Comment by aardgoose** [comment]
@WestLangley  

2) wired up, my mistake - I was expecting it to be used in envmap_frag but I see now it is used in light_pars.glsl. - I also noticed the line

 `uniform float envMapIntensity; // temporary`

 in meshphysical_frag.glsl.

1)  reflectivity, this clash is a problem because the existing editor code assumes that a parameter name is used in the same way for every shader. But is is used instead of envMapIntensity in MeshPhongMaterial, and currently only enabled for editing when envMap is set.

So if I follow the current coding pattern in editor/js/Sidebar.Material.jst the MeshPhongMaterial editor tab will show reflectivity twice etc without special casing by Material name, which so far has been avoided, and I assume the author(s) would like to keep it that way. Also the envMap editor settings are broken currently for MeshPhysicalMaterial

This could be obviously coded around, but I am not sure if that would be acceptable. Ideally reflectivity would be renamed to envMapIntensity in Phong but would obviously cause lots of compatibility problems with models etc

Your thoughts and @mrdoob 's?

**Comment by WestLangley** [comment]
> Ideally reflectivity would be renamed to envMapIntensity in Phong

Actually, `reflectivity` is a property of the material; `envMapIntensity` is a property of the environment map.

**Pull request merged**
