### PR TITLE
HDR/EXR texture loader examples: replaced images; added attribution

### PR DESCRIPTION
**Pull request by WestLangley**

### CODE REVIEW

**Comment by WestLangley** [comment]
Temporary live links:

Before:

https://threejs.org/examples/webgl_loader_texture_hdr.html

https://threejs.org/examples/webgl_loader_texture_exr.html

After:

https://raw.githack.com/westlangley/three.js/dev-examples_loader_exr_hdr/examples/webgl_loader_texture_hdr.html

https://raw.githack.com/westlangley/three.js/dev-examples_loader_exr_hdr/examples/webgl_loader_texture_exr.html

**Comment by looeee** [comment]
It would be good to have a smaller step size on the exposure, or even a logarithmic slider. You can really see the variation in brightness in the 0.001 to 0.1 range but you can't select that with the slider currently.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@mrdoob I now recommend removing the `webgl_hdr.html` example. We do not require custom shaders to decode HDR files. How do you feel about that?

**Comment by WestLangley** [comment]
Actually, we could add `webgl_loader_texture_rgbm.html` if you want...
```js
new THREE.TextureLoader().load( 'textures/cube/pisaRGBM16/nz.png', function ( texture ) {

texture.encoding = THREE.RGBM16Encoding;
```

**Comment by mrdoob** [comment]
Yes and yes! 😁

**Pull request merged**
