### PR TITLE
Documentation: Fix broken link

### PR DESCRIPTION
**Pull request by MagnuzBinder**

### CODE REVIEW

**Comment by Mugen87** [comment]
The same problem is also in `TextBufferGeometry.html`

**Comment by Mugen87** [comment]
Looks like there are some problem with this PR, see:

http://rawgit.com/MagnuzBinder/three.js/patch-30/docs/index.html#api/geometries/TextGeometry

Using a dash after `page:` does not seem to work.

**Comment by Mugen87** [comment]
I guess we need to update this function in order to parse `[page:Creating-text Creating text]` to:
```HTML
<a onclick="window.parent.setUrlFragment('Creating Text')" title="Creating Text">Creating text</a>
```
https://github.com/mrdoob/three.js/blob/d381e6cca05878a784fa509c5846f3aebc003e95/docs/page.js#L29-L70

**Comment by MagnuzBinder** [comment]
Whoops! Sorry, I wasn't aware of that limitation, and I admit I didn't check it before committing, since it seemed a trivial typo. Perhaps it would be easier to change the page URL to have it conform to the limitation?

**Comment by Mugen87** [comment]
I tend to change `onDocumentLoad()` so something like `Creating-text` is transformed to `Creating Text`. A simple `name = name.replace( '-', ' ' );` is maybe sufficient.

\ping @looeee for second opinion.

**Comment by Mugen87** [comment]
Closing. Like mentioned in https://github.com/mrdoob/three.js/pull/12848#issuecomment-350543352 we need to refactor the link generation logic or use a different URLs to solve this problem.

**Pull request closed without merging**
