### PR TITLE
Add empty map to glsl plugin

### PR DESCRIPTION
**Pull request by jarkonik**
That is how it should look like according to rollup plugin conventions: https://github.com/rollup/rollup/wiki/Plugins

### CODE REVIEW

**Comment by mrdoob** [comment]
@Rich-Harris looks good?

**Comment by Rich-Harris** [comment]
Yep, LGTM!

**Comment by mrdoob** [comment]
Thanks!

**Comment by donmccurdy** [comment]
Has this convention changed? According to [latest plugin development docs](https://rollupjs.org/guide/en/#plugin-development), "you can preserve existing sourcemaps by setting map to null." Our Rollup plugins are currently not propagating sourcemaps ... they did work in https://github.com/mrdoob/three.js/pull/10954 (which was after this PR) so I'm confused about what would have broken them.

/cc @Mugen87

**Pull request merged**
