### PR TITLE
Editor: Time render operation

### LINKED ISSUE #16007: Editor: add FPS counter
It would be useful for the editor to have an FPS counter - probably the best place for this would be in the lower left of the viewport along above the object, vertices, triangles count. 

Alternatively, stats.js could be added, perhaps in the viewport top left. That would have the advantage of showing memory data as well. In that case it should probably be disabled by default since it's a bit more visually distracting. 

@Temdog007 what do you think?

### PR DESCRIPTION
**Pull request by Temdog007**
Fixes #16007.

Based on @mrdoob's [comment](https://github.com/mrdoob/three.js/issues/16007#issuecomment-473988100).

### CODE REVIEW

**Comment by Temdog007** [comment]
For testing: https://raw.githack.com/Temdog007/three.js/feature/renderTime/editor/index.html

**Comment by looeee** [comment]
`render time 1.7,249,999,982,886,948ms`

I think it would be OK to round this down a bit 😁 
I doubt anyone needs more than 4 or 5 decimal places on milliseconds, so `1.7249ms`. 

Also, "last frame time" might be more a descriptive label.

**Comment by Temdog007** [comment]
Turns out that Firefox always rounds to the nearest ms with `performance.now`. I had to use Chrome to see any decimals.

**Review by Mugen87 — APPROVED** [review]

**Comment by Temdog007** [comment]
I'm not sure how useful this really is. Unless there is a continuous render mode (where the Editor will render on every `requestAnimationFrame` rather than on an event), this may not provide useful information. In practice, one would want to know how rendering the scene affects the FPS. Closing for now.

**Pull request closed without merging**
