### PR TITLE
Fixed examples for YouTube Data API v3

### PR DESCRIPTION
**Pull request by kakakakakku**
Hi, I found that `css3d_youtube.html` is not working well.
Some errors occured like this.
It is due to updating of YouTube Data API v3.
- https://support.google.com/youtube/answer/6098135?hl=en
- http://stackoverflow.com/questions/30685625/alternative-for-https-gdata-youtube-com-feeds-api-videos-video-idv-2

```
Failed to load resource: the server responded with a status of 410 (OK)
css3d_youtube.html:1 Uncaught SyntaxError: Unexpected token <
```
# Important Point : API KEY

YouTube Data API v3 require personal API KEY.
So if you try this, you have to get API KEY and set `key={YOUR_API_KEY}`.
- https://console.developers.google.com
# Search API
- https://developers.google.com/youtube/v3/docs/search
# Parameter

I used `snippet` value with `part` parameter.
Other value are below.
- https://developers.google.com/youtube/v3/getting-started
# Image
## Before

before
## After

after

### CODE REVIEW

**Comment by mrdoob** [comment]
Merged into the `dev` branch.
Thanks!

**Comment by Kakakakakku** [comment]
Oh, sorry.
I will push again to `dev` now.

**Comment by mrdoob** [comment]
No need. Already merged it 😊

**Comment by Kakakakakku** [comment]
Thanks :+1: 
Next time, I will PR to `dev`.

**Pull request closed without merging**
