### PR TITLE
MeshStandardMaterial: metalnessMap now modulates metalness

### PR DESCRIPTION
**Pull request by WestLangley**
See discussion in https://github.com/mrdoob/three.js/pull/7420

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Now that `metalnessMap` modulates `metalness`... Should `metalness` be `0.5` by default? Or maybe `1`?

I can see this generating confusion in the future (`roughnessMap` not fully effective because `roughness` hasn't been set to `1` and/or `metalnessMap` not fully effective because `metalness` hasn't been set to `0`).

**Comment by WestLangley** [comment]
Yes, I know. That was why I originally decoupled `metalness` from `metalnessMap`. Actually, I think I prefer having `roughness` decoupled, too, for the reason you state, but I know that would not be consistent with the behavior in the rest of the library. It is your call.

I have no problem defaulting metalness to 0.5. I do not think 1 would be appropriate.

**Comment by WestLangley** [comment]
Currently, for the maps to be 100% effective, `roughness` and `metalness` should be 1.

**Comment by WestLangley** [comment]
Also, uses should know that if `metalness` is greater than zero, an environment map is required for the material to look correct. Metallic materials need something to reflect.

**Comment by mrdoob** [comment]
Sounds good. I'll change the default to 0.5 by now.

**Pull request merged**
