### PR TITLE
TransformControls: Added scaleSnap.

### LINKED ISSUE #14902: Scaling snap for the Transform Controls
Hello guys,

I wonder, if it's possible to consider some 'scaling snap' value while using "scale" mode for the "Transform Controls"? The expectation here is to snap "endpoint" while scaling.

Thanks.

### PR DESCRIPTION
**Pull request by arodic**
Added scaleSnap to TransformControls. Fixes #14902

### CODE REVIEW

**Comment by arodic** [comment]
Live demo: https://raw.githack.com/arodic/three.js/feature/TransformControlls-scaleSnap/examples/misc_controls_transform.html

Press "R" for scale, then hold "ctrl" for snapping.

**Comment by Mugen87** [comment]
Cool 👍

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
On MacOS Ctrl+Click shows the context menu. Would Shift+Click work?

**Comment by Mugen87** [comment]
> On MacOS Ctrl+Click shows the context menu. Would Shift+Click work?

I'll make a PR with the fix.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
