### PR TITLE
add local fog effect to phong material (independent of camera)

### PR DESCRIPTION
**Pull request by nn4e**
fog_demo

### CODE REVIEW

**Comment by mrdoob** [comment]
This reminds me that at some point I thought it would be handy if `AmbientLight` had near/far radius. I guess the difference is that `AmbientLight` would be additive?

**Comment by WestLangley** [comment]
@nn4e Thank you for your contribution. There are some issues, however.

Pan the camera behind one of the cubes -- so the camera is within the fog -- and turn around. You will see that close objects are foggy and far objects are clear. That is not physically possible.

Also, your cube is located at x = 500 and your fog is located far away at x = 5200, with fog radius 5000. 

You are required to do that because it is the only way your fog model will work. I am not sure your model is appropriate.

@mrdoob Yes, `THREE.AmbientLight` is additive. It is a very simple implementation of indirect lighting (global illumination), and it is not location-based. It applies to the entire scene.

If you want location-based indirect lighting, the best way to implement that would be via light probes, I expect.

**Comment by nn4e** [comment]
@WestLangley It's intended to hide the borders of the scene, and yes it looks wrong if camera beyond the border and looks back, but in my case it does not matter, 
photo_2015-07-19_22-39-15
because the camera can not get there

**Comment by nn4e** [comment]
I really need this feature and do not want to maintain my own fork. It can be accepted in any form?

**Comment by WestLangley** [comment]
So what is important to you is to hide the borders of the scene and have the fog camera-position-independent?

What if `THREE.Fog()` could be fixed at a user-specified location, like the origin, and not move with the camera?

    THREE.Fog = function ( color, near, far ) {

	    this.name = '';

	    this.color = new THREE.Color( color );

	    this.near = ( near !== undefined ) ? near : 1;
	    this.far = ( far !== undefined ) ? far : 1000;

	    this.center = new THREE.Vector3(); // used when static is true
	    this.static = false;

    };

    THREE.Fog.prototype.clone = function () {

	    var fog = new THREE.Fog( this.color.getHex(), this.near, this.far );

	    fog.center.copy( this.center );
	    fog.static = this.static;

	    return fog;

    };

**Comment by nn4e** [comment]
THREE.Fog need  to hide the end of camera distance
and the only single radius does not allow to flexibility set  borders, need multiple sources.

**Comment by WestLangley** [comment]
I am trying to help you work within the framework of three.js.

As I said, `THREE.Fog` could be modified so it can be fixed at a user-specified location, like the origin, and not move with the camera.

>  THREE.Fog need to hide the end of camera distance

What do you mean by that? I thought you wanted the fog to be camera-position-independent?

Also, `THREE.Fog` uniforms can be reset every frame. That gives you flexibility.

**Comment by nn4e** [comment]
@WestLangley I mean I need Fog relative to the camera, and at the same time I need some static fog. However, the current implementation  does not provide multiple fog

**Comment by nn4e** [comment]
I think the best solution would be  api, which allows to inject code, variables and constants in the materials shaders, observe the objects in render context and update custom Uniform.
I could try to implement it, but not sure I get it well

**Comment by mrdoob** [comment]
This case is very specific. I think a better approach for this would be to (finally) implement hooks into the material, so you could add your custom code to `MeshPhongMaterial`.

Something like:

```javascript
var material = new THREE.MeshPhongMaterial();
material.custom.fragmentShader.postOutput = 'gl_FragColor.w = mix(0.0,1.0,worldPosition.z)'
```

So we can have a bunch of "hooks":

```javascript
material.custom.vertexShader.preOutput = '';
material.custom.vertexShader.postOutput = '';
material.custom.fragmentShader.preOutput = '';
material.custom.fragmentShader.postOutput = '';
```

Thoughts?

**Comment by mrdoob** [comment]
> I think the best solution would be api, which allows to inject code, variables and constants in the materials shaders, observe the objects in render context and update custom Uniform.

Oh, I missed that comment. Yes, we're in the same page.

**Comment by gero3** [comment]
Why not use postprocessing for this case??
First render the scene completely and then add the fog on top of it.

**Comment by nn4e** [comment]
@mrdoob I see it like THREE.Extentions.add(THREE.PluginName), where PluginName contains shaderchunks, uniforms, and functions that can be called from the render and WebGLProgram.
This model is easier to use and reuse, and we can create a collection of plug-ins, containing strange features like this fog.

@gero3 What about depth? In any case, I think one render pass will be faster than two.

**Comment by mrdoob** [comment]
> @mrdoob I see it like THREE.Extentions.add(THREE.PluginName), where PluginName contains shaderchunks, uniforms, and functions that can be called from the render and WebGLProgram.
This model is easier to use and reuse, and we can create a collection of plug-ins, containing strange features like this fog.

I don't know... Such approach doesn't look very explicit. Also it's probably a pain to help people with.

**Comment by mrdoob** [comment]
How about something like...

```javascript
material.onProgram = function ( program ) {
    var code = program.fragmentShader.code;
    code.replace( 'gl_Fragment = blah', 'gl_Fragment = vec4(1.0,0.0,0.0,1.0);' );
};
```

**Comment by nn4e** [comment]
I think  direct code replacement  is not the best solution, but it will be ok, if you add pointers in shader code, for example //[Pars] //[MainBegin] //[MainEnd]
and may be //[DirectLightBegin] //[DirectLightEnd] etc..

Also it would be nice to simplify definition checking , for example
#if MAX_SPOT_LIGHTS > 0 || defined( USE_BUMPMAP ) || defined( USE_ENVMAP )
	varying vec3 vWorldPosition;

#endif
replace to: #ifdef USE_WORLD_POS

And also need something like material.customUniforms

**Comment by mrdoob** [comment]
All that sounds good!

**Pull request closed without merging**
