### PR TITLE
SVG Loader: Accept multiple transforms in a single node

### PR DESCRIPTION
**Pull request by yomboprime**
Parses multiple transforms in the `transform` node attribute and combines them into one.

Related #14418 #13478 

Ping @napter

### CODE REVIEW

**Comment by mrdoob** [comment]
Minor... Instead of `newTransform` I think I would name that var `currentTransform`.

**Comment by WestLangley** [comment]
>Minor... Instead of newTransform I think I would name that var currentTransform.

... or just `transform`.

Perhaps you can reuse matrices, too. There is a lot of this:

```javascript
newTransform = new THREE.Matrix3();
```

**Comment by yomboprime** [comment]
I did those. The code is neater now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
