### PR TITLE
Docs: Removed outdated information

### PR DESCRIPTION
**Pull request by atul-mourya**
Dynamic addition of light in run-time does seems to be possible in three.js

### CODE REVIEW

**Comment by looeee** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by WestLangley** [comment]
@looeee Why did you label this a help request and close it?

This PR appears to me to be a proposed update to an outdated document.

**Comment by atul-mourya** [comment]
@WestLangley Yes, that was my intent. Was looking to update which seems to me outdated.
Correct me if I'm wrong with the proposal content.

**Comment by WestLangley** [comment]
@atul-mourya The document is old and needs to be updated with more precise language. There is nothing wrong with what you intended to do.

**Comment by mrdoob** [comment]
What @WestLangley said.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
