### PR TITLE
Allow a custom loader manager to be used with OBJLoader2

### PR DESCRIPTION
**Pull request by unphased**
@kaisalmen please review, thank you

### CODE REVIEW

**Comment by unphased** [comment]
@kaisalmen I am also happy to provide a PR in your https://github.com/kaisalmen/WWOBJLoader repo as well. I guess i will do that

**Comment by mrdoob** [comment]
@kaisalmen for context... #12983

**Comment by kaisalmen** [comment]
I merged it in my repo a minute ago. Thanks again for spotting this.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
