### PR TITLE
Addons: Remove `GPUStatsPanel`.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #29295

**Description**

This PR removes the addon `GPUStatsPanel`. For more detailed performance monitoring, it's best to use https://github.com/RenaudRohlinger/stats-gl since it works for both WebGL and WebGPU.

As mentioned earlier, ideally `stats-gl` replaces the original `stats.js` in the examples at some point. Since there seems to be some issues in context of Safari and M processors (see #28978), it's probably best to wait a bit until these problems have been resolved.

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you switch instead to `stats-gl` on your side? If you put the following into an example's import map, you can import via `import Stats from 'stats-gl';` and use it as a replacement of stats.js.
```js
"stats-gl": "https://cdn.jsdelivr.net/npm/stats-gl@2.2.8/dist/main.js"
```

I have the feeling this is better than retaining `GPUStatsPanel` which is simply rendundant.

**Comment by gkjohnson** [comment]
I'm just suggesting to not remove stats.js related components until stats.js is removed from the project. But I see that stats-gl is basically the same thing.

**Comment by mrdoob** [comment]
How about replacing `GPUStatsPanel` with `stats-gl` in those examples instead?

**Comment by RenaudRohlinger** [comment]
Regarding stats-gl, I’m considering disabling the GPU metrics by default.
Since this is the only metric currently causing issues and is quite advanced, its default state might be better set to off, especially given that it’s not entirely accurate. The CPU metric, on the other hand, is both stable and highly useful, which could be sufficient to drive adoption and facilitate the transition from stats to stats-gl. /cc @Mugen87

**Comment by RenaudRohlinger** [comment]
Released `stats-gl@2.3.1 `which doesn't have the GPU metrics by default.

**Pull request merged**
