### PR TITLE
ShadowNode: Ensure background does not influence shadow map.

### LINKED ISSUE #30111: backgroundNode color renders in the shadow map
### Description

When using : 

`scene.backgroundNode = new THREE.Color(0xff0000)`

The background color renders in the shadow map 

but also : 

`scene.background = new THREE.Color(0xff0000)` does same effects

EDIT :  

For some reasons, the backgroundNode allows THREE.Color as input, realised it is not a problem using color( 0xff000 ) from TSL color 

Screenshot 2024-12-12 at 15 19 45

### Live example

This fiddle display the shadow map texture in the center plane 

[Live fiddle](https://jsfiddle.net/7v0skobf/5/)

### Version

r171

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #30111.

**Description**

The PR makes sure the scene background does not affect the shadow map anymore.

@sunag We might want to rename `PostProcessingUtils` to `RendererUtils` maybe^^?

### CODE REVIEW

**Comment by sunag** [comment]
> @sunag We might want to rename PostProcessingUtils to RendererUtils maybe^^?

I'm happy we're so aligned, as I was considering this as well :)

**Comment by Mugen87** [comment]
The PR breaks the motion blur demo. Investigating...

**Comment by Mugen87** [comment]
There was actually a bug in `resetRendererAndSceneState()`. I have refactored the module slightly so this oversight does not happen anymore.

**Comment by Mugen87** [comment]
@sunag With this PR, the shadows in `webgpu_shadowmap_opacity` look a bit darker. That happens because the scene's background does not influence the shadow map anymore (verified this by toggle the scene reset). I _think_ the shadow color is now more correct.

**Pull request merged**
