### PR TITLE
Examples: Added user-interaction button in webgl_video_panorama_equirectangular

### PR DESCRIPTION
**Pull request by WestLangley**
Following the pattern used elsewhere. :-)

/ping @Mugen87

### CODE REVIEW

**Comment by WestLangley** [comment]
temporary live link:

https://raw.githack.com/westlangley/three.js/dev_user_interaction/examples/webgl_video_panorama_equirectangular.html

**Comment by Mugen87** [comment]
The overlay is actually not required for muted videos. The video should also start without it.

**Comment by WestLangley** [comment]
Without the overlay, I get this error on macOS Safari.

    Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**Comment by Mugen87** [comment]
Um, do you also get this error with the latest version?

https://threejs.org/examples/webgl_video_panorama_equirectangular

**Comment by WestLangley** [comment]
That URL works for me on Chrome and FF on macOS, but not Safari 13.1.

**Comment by Mugen87** [comment]
Strange. I'm also using Safari 13.1 and everything runs fine. Interestingly, your [githack URL](https://raw.githack.com/westlangley/three.js/dev_user_interaction/examples/webgl_video_panorama_equirectangular.html) does not work in Safari. I get:

> THREE.WebGLState: SecurityError: The operation is insecure.

Besides, in Chrome the new version produces this warning until the video starts:

> WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty

**Comment by WestLangley** [comment]
I have no idea what is going on... :/

**Comment by WestLangley** [comment]
>The overlay is actually not required for muted videos. 

This PR is not needed, then. Closing.

**Pull request closed without merging**
