### PR TITLE
Docs: Added .js extension to path of GLTFLoader.

### PR DESCRIPTION
**Pull request by parke**
I got a 404 error when I ran the line as written, but the 404 error went away when I added .js.  So, should the path end in .js?  I am a new user of three.js.

### CODE REVIEW

**Comment by parke** [comment]
Also, I needed this:
`var  loader = new GLTFLoader();`
Not this:
`var loader = new THREE.GLTFLoader();`

**Comment by WestLangley** [comment]
Yep. Yep.

Would you like to make all the corrections?

Also, it is helpful if you make the same changes to the `docs/manual/zh` file, too.

**Review by parke — COMMENTED** [review]
Removed buggy THREE. from example code.

**Comment by parke** [comment]
Anything else?

**Comment by WestLangley** [comment]
Looks good. Thanks!

**Review by donmccurdy — APPROVED** [review]
For some users it will work either way, but I agree this would be more general. Thanks!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
