### PR TITLE
These changes update the exporter to work with 3ds Max 2016

### PR DESCRIPTION
**Pull request by amirebrahimi**

### CODE REVIEW

**Comment by mrdoob** [comment]
@RemusMar could you double check?

**Comment by RemusMar** [comment]
> @RemusMar could you double check?

His changes are MaxScript related.
I don't have 3DS Max 2016, so I cannot test them.
But they look ok ...

**Comment by mrdoob** [comment]
@tormozok do you have 3DS Max 2016?

**Comment by tormozok** [comment]
2015

**Comment by amirebrahimi** [comment]
FYI: It's possible to test this using a trial version of 3dsMax 2016.

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6776

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6776

**Pull request merged**
