### PR TITLE
WebXRController: Hide controller while system UI is up.

### PR DESCRIPTION
**Pull request by cabanier**
Related issue: #20729

**Description**

In the update callback for controller and hands, skip all the logic that deals with positioning of input source while the session is blurred.
When the logic is skipped, the controller ends up being set to invisible

This contribution is funded by [Oculus](https://oculus.com).

### CODE REVIEW

**Comment by cabanier** [comment]
closes #20729

**Comment by FMS-Cat** [comment]
I've tried on my Oculus Quest 2, I think it's working fine.

**Review by Mugen87 — APPROVED** [review]

**Comment by cabanier** [comment]
@Mugen87 How does it get merged?

**Comment by Mugen87** [comment]
@cabanier PRs are getting merged by @mrdoob.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
