### PR TITLE
added delete button support in editor

### PR DESCRIPTION
**Pull request by MrRar**
See https://css-tricks.com/snippets/javascript/javascript-keycodes/ for key codes.

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
Nice! Was thinking about doing this too.. backspace for deleting is not intuitive unless you're erasing text. For backwards compatability you might want to let the backspace `case` flow to deletion as well though, since it isn't doing anything else atm.

```javascript
case 8: // backspace
case 46: // delete
    event.preventDefault(); // prevent browser back
    
    var object = editor.selected;
    if ( confirm( 'Delete ' + object.name + '?' ) === false ) return;
...
```

Also, you should probably target the `dev` branch.. Don't know if it matters for editor changes though.

**Comment by mrdoob** [comment]
Oh, hah. I haven't had a keyboard with that button in a while...

**Comment by mrdoob** [comment]
This looks good, but could you target the `dev` branch instead?

**Comment by MrRar** [comment]
Ok @mrdoob, I did it.

**Pull request closed without merging**
