### PR TITLE
Allow bevel to be subtracted (instead of being added)

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a new option `bevelSubtract` to `Extrude*Geometry` and `Text*Geometry`, which subtracts the bevel from the shapes instead of adding it. We found this very useful for some fonts, where adding bevel resulted in accents and umlauts bleeding into the main letter. With bevel subtracted instead of added, the letters look great (and the accent/umlaut is properly separated).

### CODE REVIEW

**Comment by ffdybuster** [comment]
Before (bevel added):
bevel-add

After (bevel subtracted):
bevel-subtract

**Comment by ffdybuster** [comment]
Some more examples. Note that for bevel added, the letters are more voluminous, while for bevel subtracted, they are as slim as the non-bevel ones (but look better). It helps to open the images in tabs and switch between them.

With bevel added (classic):
bevel-add

Without bevel:
no-bevel

With bevel subtracted:
bevel-subtract

**Comment by ffdybuster** [comment]
@mrdoob any opinions on this one?

**Comment by WestLangley** [comment]
What happens in your use case if you just set `bevelSize` to be negative - in lieu of this PR?

**Comment by WestLangley** [comment]
As I said, please try negative `bevelSize` without using this PR.

**Comment by ffdybuster** [comment]
That's exactly what the screenshot is showing. If `bevelSubtract` is `false`, the PR does exactly nothing else than the original code. The screenshot shows `bevelSubtract === false` and `bevelSize < 0`.

**Comment by WestLangley** [comment]
Can you rewrite your PR without  the `bevelSubtract` property and instead implement your logic by testing if `bevelSize` is less than zero?

**Comment by ffdybuster** [comment]
Sure. I mainly did it this way to avoid breaking backwards compatibility. (I'm not sure if anyone actually wants the current "negative bevel" version...)

**Comment by ffdybuster** [comment]
@WestLangley I added the rewrite as a new commit; if it should stay this way I can squash the commits.

**Comment by ffdybuster** [comment]
@WestLangley did you had any time to look at the update?

**Comment by WestLangley** [comment]
I did, but you did not implement what I suggested in https://github.com/mrdoob/three.js/pull/14233#issuecomment-424745327.

**Comment by ffdybuster** [comment]
I'm sorry if I misunderstood you. I understood your comment that you want `bevelSubtract` gone from the *interface*, not from the *implementation*. Do you mean that I should replace `bevelSize` by `Math.abs( bevelSize )` everywhere and `bevelSubtract` by `bevelSize < 0`?

**Comment by WestLangley** [comment]
Yes. Please try that and see if your changes are more clear.

**Comment by WestLangley** [comment]
Did you test these changes?

**Comment by andreasplesch** [comment]
What happens if bevelSize is more negative than the extrude amount/depth ? Threejs does not do a lot of sanity checking as a matter of course.

**Comment by ffdybuster** [comment]
@WestLangley now I did. After fixing a sign error, they work.

@andreasplesch it looks a bit funny then :) Example:
negative-bevel-extreme
Preventing this requires to understand the shape globally (and not just locally). I don't think it's worth to implement that in three.js itself.

**Comment by WestLangley** [comment]
>Did you test these changes?
>@WestLangley now I did. After fixing a sign error, they work.

Please test your code before you file a PR or merge commits.

**Comment by WestLangley** [comment]
I think your code
```
bs = Math.abs( bevelSize ) * Math.sin( t * Math.PI / 2 );

if ( bevelSize < 0 ) {

	bs += bevelSize;

}
```
be made more clear by
```javascript
var s = Math.sin( t * Math.PI / 2 );

bs = ( bevelSize > 0 ) ? bevelSize * s : bevelSize * ( 1 - s );
```
(I am still trying to understand what your changes are actually doing...)

**Comment by ffdybuster** [comment]
> (I am still trying to understand what your changes are actually doing...)

The original bevel code goes in the direction of the 2D shape's "2D normal" (`contourMovements[i]`), where the distance is 0 at the edges and `bevelSize` in the middle.

The new code changes this behavior in case `bevelSize < 0`, namely it does forward `bevelSize` at the edges and 0 in the middle.

**Comment by WestLangley** [comment]
`bevelSize` positive, zero, and negative.

screen shot 2018-11-05 at 1 35 24 pm

It appears to be a nice feature. A negative value can be problematic, however, as vertices can collide. But so can a positive value for that matter.

**Comment by WestLangley** [comment]
I have done the best I can to help clarify this PR. It is up to others to decide if it is a feature we want merge.

**Review by haroldiedema — APPROVED** [review]
LGTM :+1:

This improves the look on some of the game icon fonts I'm using as well.

**Comment by ffdybuster** [comment]
@mrdoob is there a chance to get this merged eventually?

**Comment by Mugen87** [comment]
It's okay to merge as long as the changes to `docs/scenes/js/geometry.js` are removed. I think these are not necessary...

**Comment by ffdybuster** [comment]
@Mugen87 the changes to `docs/scenes/js/geometry.js` allow to use negative `bevelSize` in the examples in the documentation. If you really want I can remove them.

I'll update the documentation tomorrow.

**Comment by Mugen87** [comment]
> @Mugen87 the changes to docs/scenes/js/geometry.js allow to use negative bevelSize in the examples in the documentation.

In this case, everything is fine. I've overlooked that it is used to adjust the value range

**Comment by ffdybuster** [comment]
@Mugen87 I've updated the docs, including the ones for `TextGeometry` and `TextBufferedGeometry`.

Is there a changelog I need to add something to?

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
When merged, I'll add a note to the migration guide:

https://github.com/mrdoob/three.js/wiki/Migration-Guide

**Comment by Mugen87** [comment]
> Is there a changelog I need to add something to?

No. We will consider the PR for the release notes because of the assigned milestone.

**Comment by mrdoob** [comment]
I don't think changing the behaviour of `bevelSize` is good. Instead, I would add a new parameter `bevelBaseSize` that does what you're looking for.

**Comment by ffdybuster** [comment]
@mrdoob How should `bevelBaseSize` work? Should that essentially be subtracted from `bs` (in the calculations), so that `bevelBaseSize = -bevelSize` will give the same effect as a negative value for `bevelSize`?

**Comment by mrdoob** [comment]
Yes, for your use case you would only have to change `bevelBaseSize`.
Maybe `bevelStartSize` is more clear?

**Comment by ffdybuster** [comment]
Hmm, both names are fine for me. Whatever you prefer :)

**Comment by mrdoob** [comment]
I think I like `bevelBaseSize`. @WestLangley @Mugen87 any preferences/suggestions?

**Comment by ffdybuster** [comment]
Just to make sure that I understand this correctly: bevel starts at `bevelBaseSize`, and goes up to `bevelBaseSize + bevelSize`? Or does it go from `bevelBaseSize` to `bevelSize`? (The "base" name indicates the first for me, while the "start" name makes me think more of the second.)

**Comment by mrdoob** [comment]
> Just to make sure that I understand this correctly: bevel starts at `bevelBaseSize`, and goes up to `bevelBaseSize + bevelSize`?

👍

**Comment by Mugen87** [comment]
> I think I like bevelBaseSize.

Sounds good!

**Comment by ffdybuster** [comment]
I've updated the PR, tested the changes, and LGTM finally finished as well ;)

**Comment by WestLangley** [comment]
>I don't think changing the behaviour of bevelSize is good.

The previous version of this PR did not change the behavior of bevelSize, it just allowed a negative value.

>I think I like bevelBaseSize. @WestLangley ... any preferences/suggestions?

I think `bevelBaseSize` and the new version of this PR is unnecessarily confusing, and the documentation is not clear. (To be fair, the docs were confusing to begin with.)

I would revert `bevelBaseSize` and retain the previous API.

But if you insist, then I'd rename it to `bevelOffset`.

**Comment by ffdybuster** [comment]
> > I don't think changing the behaviour of bevelSize is good.
> 
> The previous version of this PR did not change the behavior of bevelSize, it just allowed a negative value.

The behavior got changed for negative values; it was possible to use them before, even though this wasn't documented.

The nice thing about the new implementation is that you can also (ab-)use bevel to shrink / extend a shape by setting `bevelSize` to zero and playing with `bevelBaseSize` (or however it will be called in the end).

**Comment by WestLangley** [comment]
@ffdybuster Whatever @mrdoob wants is fine. I was just responding to his request for my opinion.

**Comment by mrdoob** [comment]
> The previous version of this PR did not change the behavior of bevelSize, it just allowed a negative value.

I think it did. If someone previous used a negative value it would look differently after this PR?

> But if you insist, then I'd rename it to `bevelOffset`.

Indeed! `bevelOffset` sounds better 👌

**Comment by ffdybuster** [comment]
I've renamed the option to `bevelOffset` and tested it, it still works.

**Comment by mrdoob** [comment]
Thanks!

**Comment by ffdybuster** [comment]
@WestLangley @andreasplesch @haroldiedema @Mugen87 @mrdoob thanks a lot for reviewing and merging this!

**Comment by mrdoob** [comment]
Thank you for persevering! 😅

**Pull request merged**
