### PR TITLE
ParametricGeometry Example: Clean up

### PR DESCRIPTION
**Pull request by WestLangley**
minor cleanup

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@nowherenearithaca Sorry. Overlooked updating the docs in this case. Would you like to contribute a patch to the docs?

Did you at least get a console warning?

**Comment by nowherenearithaca** [comment]
No console warning - and adding one might be hard on performance because it's generally running a tight loop on that... which probably motivated the previous change there to begin with.  I think you would have heard a lot of noise if this broke things for many people...

**Comment by paulmasson** [comment]
Since no one has updated the documentation yet, here it is #13846.

Do this change really improve performance enough to warrant breaking things? Certainly just cost me some time figuring out what was going on.

**Pull request merged**
