### PR TITLE
THREE.MathUtils: added seededRandom() method

### PR DESCRIPTION
**Pull request by WestLangley**
This is useful in generating repeatable results in an existing example.

```js
THREE.Math.prng( 123 );

Math.random = THREE.Math.prng;
```

### CODE REVIEW

**Comment by Mugen87** [comment]
This code was removed from the examples here: #16576

And now you want to add it to the core?

**Comment by WestLangley** [comment]
@Mugen87 If you don't want users of the library to have access to this method, I'll close this.

**Comment by Mugen87** [comment]
No offense, I'm just irritated by the PR. I think we made a decision in #16576 to not add such code to the lib...

**Comment by WestLangley** [comment]
>No offense, I'm just irritated by the PR

Please don't be. I was not intending to annoy you. I thought I was doing what you suggested when you said:

>Okay, if @mrdoob wants to keep PRNG, I suggest to move it into the THREE namespace and the file to the math directory.

But I guess you were suggesting to move it to `math/js/examples`...

We can do that, merge this, or close this. I don't care.

**Comment by Mugen87** [comment]
Yeah, in this sentence I was referring to `examples/js/math`^^. Anyway, since `PRNG.js` is now gone, I would only add it back if there is an actual user request.

**Comment by mrdoob** [comment]
Seems like this was a misunderstanding. @Mugen87 suggested adding PRNG in the `THREE` namespace so we can generate the [JSM](https://github.com/mrdoob/three.js/tree/dev/examples/jsm) version automatically.

**Comment by Mugen87** [comment]
I actually wanted to remove `PRNG.js` in the first place since it was not used in the repo^^. So I think the status quo is oka ynow.

**Comment by WestLangley** [comment]
Trying again...

**Comment by mrdoob** [comment]
We just need a good use case.

**Comment by munrocket** [comment]
```
var x = crypto.getRandomValues( new Uint32Array(1) )[0] / 0xFFFFFFFF;
```
Should work almost in any browser. Performance only twice worse, because it’s cryptography safe PRNG and supports an arrays.

**Comment by WestLangley** [comment]
Closing again...

**Comment by mrdoob** [comment]
@WestLangley can we call this `MahtUtils.deterministicRandom()`?

**Comment by mrdoob** [comment]
Oh, can't reopen the PR because the branch is gone.

**Comment by WestLangley** [comment]
>can we call this MathUtils.deterministicRandom()?

@mrdoob Maybe `MathUtils.seededRandom()` or `.seedRandom()`?

Similar nomenclature is used here: https://github.com/davidbau/seedrandom

**Comment by mrdoob** [comment]
Hmm, `seedRandom()` is shorter... I have no preference, as long as is not an acronym.

**Comment by mrdoob** [comment]
Actually, I think `seededRandom()` sounds better.

**Comment by mrdoob** [comment]
Thanks!

**Comment by wrightwriter** [comment]
This function expects big numbers, otherwise it results in a very biased distribution.
I think this warrants a comment, explaining this, no?
image
image

**Pull request merged**
