### PR TITLE
Ready Player Me thumbnail updated.

### PR DESCRIPTION
**Pull request by srcnalt**
Updated the Ready Player Me project log in files.

### CODE REVIEW

**Comment by mrdoob** [comment]
As you know, we're trying to avoid turning that page into ads.
Adding "Ready Player Me" to the image fits the tone, but the tag line seems a bit too advertisingy.

**Comment by srcnalt** [comment]
Hi @mrdoob, thank you for the feedback. I'll ask the team the provide me a fitting image without text but logo only.

**Comment by mrdoob** [comment]
Much better!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
