### PR TITLE
GPUParticleSystem: Refactoring

### PR DESCRIPTION
**Pull request by Mugen87**
This PR solves the problems mentioned in  #11149

- Added missing `dispose` method
- Introduced a single shader attribute per particle property instead of encoding/decoding float to vector4 and vice versa.
- Clean up and code style

As a compromise you need to maintain more shader attributes than before. However, the code should now much easier to read and understand. Besides the numerical robustness is better than before.

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks!

**Comment by Mugen87** [comment]
@neeh Are you still planning to implement the mentioned change? It would be nice to patch this before `r85` is released.

**Comment by neeh** [comment]
Hi Michael,

Yes, can't agree more.
Still have this in my mind but I'm kind of busy now :S

Can you handle this?

**Comment by Mugen87** [comment]
Yep, no problem!

**Pull request merged**
