### PR TITLE
MeshPhysicalMaterial: improve clearcoat energy conservation

### PR DESCRIPTION
**Pull request by WestLangley**
This PR follows the approach outlined in the glTF spec.

### CODE REVIEW

**Comment by WestLangley** [comment]
@sunag FYI. I am doing my best to improve the physical material shaders and avoid a ripple-effect through `NodeMaterial`. Doing so is quite challenging. Examples that use code-injection to modify shader chunks are also a problem.

**Comment by sunag** [comment]
@WestLangley I'm loving your updates. You are doing an amazing job around here.

**Comment by mrdoob** [comment]
> @WestLangley I'm loving your updates. You are doing an amazing job around here.

Yes yes!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
