### PR TITLE
Added support for lookAt() with transformed parents

### PR DESCRIPTION
**Pull request by yomboprime**
I've implemented a solution to the restriction of `Object3D.lookAt( vector )` and `Camera.lookAt( vector )`. It seemed to me that it could be useful to get rid of that restriction (the one of not allowing the object to have transformed parents)

The solution consists of transforming the input vector target position to the object's parent space. Since the object position and the up vector are already in the parent's space, they can be used 'as is'.
As the target vector is now in the parent space as well as the other vectors, the previous call to `Matrix4.lookAt()` works as expected.

I've put an `if` statement that checks if the object has a parent and is not the Scene node, and if so it makes the transform. If not, it defaults to the previous behavior.

I've added a new example `misc/lookAt2` which is copied from the previous one, and creates a hierarchy of 0 to 4 parents to each arrow object, and only the leaf is made to 'lookAt'.

The camera in this example is also a child of an object, to test the method in `Camera`.

I've also tested other examples with shadows for example, as there is a call to Camera.lookAt() to set the shadow camera in the core.

### CODE REVIEW

**Comment by WestLangley** [comment]
In your example, the arrows point all over the place. Shouldn't they all point toward the same point?

Maybe the following pattern would be clearer:

```javascript
if ( this.parent === undefined || this.parent instanceof THREE.Scene ) {

	m1.lookAt( vector, this.position, this.up );

} else {

	// your code

}
```

One way for you to demonstrate your approach works is to add the camera as a child of a rotated `Object3D`, which in turn is a child of the scene. Rotate the object in the render loop and call `camera.lookAt( scene.position )` and see what happens.

The camera should stay upright.

**Comment by yomboprime** [comment]
> In your example, the arrows point all over the place. Shouldn't they all point toward the same point?

The child arrows do the `lookAt`, but the parents are static. I've changed the parents color so they are more distinguishable from the leaves.

I've changed the `if` statement as you indicated.

And also I've made rotate slowly the camera Object3D parent, also as per your suggestion.

**Comment by WestLangley** [comment]
> I've changed the parents color so they are more distinguishable from the leaves.

I see. It is clearer to me when `parent.opactiy = 0.1;`

The problem with your approach is you do not maintain "up-ness" in your child object. The parent's transform destroys it.

**Comment by yomboprime** [comment]
> I see. It is clearer to me when parent.opactiy = 0.1;

All right I'll change that.

> The problem with your approach is you do not maintain "up-ness" in your child object. The parent's transform destroys it.

I assumed that the `this.up` vector is always in the parent space, just like `this.position`. Isn't that right?

**Comment by yomboprime** [comment]
Sorry, I clicked on Close by mistake.

**Comment by WestLangley** [comment]
> I assumed that the this.up vector is always in the parent space, just like this.position.

`this.position` is in parent space?

Part of the problem is it can be debated what `lookAt()` should do if the object is a child of a transformed parent. I do not believe `lookAt()` in that case should ever result in the object being upside down. You may disagree. And your argument could be valid, too.

**Comment by yomboprime** [comment]
> this.position is in parent space?

Well I mean that the `this.position` is relative to the parent position (when there is a parent). I think of it being in the parent space, yes.

What do you think about an extra parameter which tells if the up vector is to be considered also in world space?

**Comment by yomboprime** [comment]
Ahhrgh.. I did it again xP

**Comment by WestLangley** [comment]
> What do you think about an extra parameter which tells if the up vector is to be considered also in world space?

I don't think so. The `up` vector is an absolute vector and is not affected by matrix transforms.

This is a confusing issue, which is the primary reason I did not implement this feature years ago. If we can get it to work, that is great. But we have to agree on what the functionality should be.

I should add that there has been little demand for this capability. It could be because it is difficult to understand what the behavior should be if there is a transformed parent.

**Comment by yomboprime** [comment]
> I don't think so. The up vector is an absolute vector and is not affected by matrix transforms.

All right. then the up vector can be treated as the input vector, and transform it from world to parent space as well. Please let me know if this makes sense.

**Comment by WestLangley** [comment]
> Please let me know if this makes sense.

Sorry, I have no idea. If I knew the answer, I certainly would tell you. This problem becomes more complicated when the parent is scaled.

Perhaps it would make sense for you to explain what use case you are solving, so we can figure out what properties the solution should have.

**Comment by yomboprime** [comment]
For example, the turret of a military tank. In this case it makes sense that the up vector of the turret is considered in local parent space.

**Comment by WestLangley** [comment]
> For example, the turret of a military tank.

Agreed. We would not want the turret to twist.

What do you think about the use case of a camera as a child of a vehicle? Would we want the camera to remain level as it calls `lookAt()`?

> local parent space

I do not like that terminology. It may mean something clear to you, but it is not common. Can we avoid using it to avoid confusion?

I view the `up` vector as different from the local y-axis, for example. To me, the `up` vector does not get transformed. It is just a world-space direction.

**Comment by yomboprime** [comment]
All right. Then if the up vector is always a world-space direction, it can be transformed in `lookAt()` just as the `vector` parameter. Do you think this would be acceptable general behavior?

My previous example of the turret was a simplification. In a real case, the turret has two pieces at least which turn each in at most one axis (the cannon itself rotates only in the X axis). So a proper tank simulation would have to add extra math to calculate the turn for each piece, it is not sufficient a simple `lookAt` call.

**Comment by yomboprime** [comment]
Ah sorry I forgot the scaling issue with the up vector. It could be normalized after transform.

**Comment by yomboprime** [comment]
Well ok, I agree with you, this PR is not useful. Closing it.

**Comment by WestLangley** [comment]
Thank you for your attempt. : - )

I can implement "my way", but I am not convinced that is the correct behavior, and "your way" may be preferred in some cases. So the solution, for now, is not to support it.

**Comment by yomboprime** [comment]
You're welcome : - )
Yeah, it is preferable to let the users implement an ad-hoc solution for their problem, having `Matrix4.lookAt()`.

**Pull request closed without merging**
