### PR TITLE
misinformation in docs about modules

### PR DESCRIPTION
**Pull request by munrocket**

### CODE REVIEW

**Comment by Mugen87** [comment]
You also have to adjust this line, otherwise user will get a runtime error when copy/paste the code:

https://github.com/mrdoob/three.js/pull/17076/files#diff-b272ae25a77c61d4e305bea9106871afR107

**Review by Mugen87 — DISMISSED** [review]

**Comment by Mugen87** [comment]
I think it's better to only advocate the ES6 approach and remove the others. Besides, the following line needs a change otherwise user will get a runtime error.

https://github.com/mrdoob/three.js/pull/17076/files#diff-b272ae25a77c61d4e305bea9106871afR107

`var loader = new THREE.GLTFLoader();` has to be `var loader = new GLTFLoader();`

**Comment by munrocket** [comment]
>and remove the others
After that we will need to change all documentation. I will add two additional words before example of code to be fully correct.

**Comment by munrocket** [comment]
If you want that we can edit all examples in documentation one by one and add LoadingManager to them also.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Okay, it's fine like that.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
