### PR TITLE
My APIs remapped proposal

### PR DESCRIPTION
**Pull request by Seagat2011**
APIs are mapped according to folderization. This example includes both src/ and example/js/ libraries :) I dont have node installed so I went by standard file conventions. My classBuilder is written in python, which i am willing to share.

### CODE REVIEW

**Comment by looeee** [comment]
Can you give some explanation as to why you want to do this?

As a side note, files in the build directory are the entire compiled three.js library, created automatically by the "npm run build" command. 

Your file would go in the src/ directory as an alternative to src/Three.js

**Comment by Seagat2011** [comment]
Yes, what I discussed with mrdoob is the idea of self-documenting API for someon whom has never seen ThreeJS or WebGL: I feel THREE.geometries.IcosahedronGeometry() is more descriptive than THREE.IcosahedronGeometry() because THREE.geometries.* documents all the geometries that are available (hence self-documenting) ; I also like the way repository is folderized so I wish to stick to that convention with library calls. Also in the classBuilder I wrote libraries can be added or removed easily

**Comment by looeee** [comment]
Can you link to any other discussions about this here? 

What about the examples, and people's existing code, won't this break everything? Or are you suggesting maintaining two separate APIs?

**Comment by Seagat2011** [comment]
OK. See these discussions in these threads #10559 , #10520

@looeee : I would like to propose this as a major revision . Yes .

**Comment by Seagat2011** [comment]
I think this will break everything. But so what. If you guys are coding by hand i can develop  AI and some other CASE tools. Microsoft used AI to file file 20,000 patents in year 2016. Dont you have AI and CASE tools. the I believe the newer version of the code will remain scalable and maintainable

**Comment by Mugen87** [comment]
I don't think that this is a step in the right direction. We should try to keep things as simple as possible. That was always the philosophy of `three.js`. And the reason for its popularity, at least from my point of view. 

So CASE tools and all this stuff is fine as long as it does not lead to over-engineering, which makes everything unnecessarily complicated. I think there are enough more important open tasks to focus on than restructuring the entire project.

> I think this will break everything. But so what.

That's not the idea of library development...

**Comment by looeee** [comment]
>I think this will break everything. But so what.

Well, breaking everything is a big deal. It's not something you just do because one person suggests it without any kind of strong argument to back it up. 

If you are interested in CASE tools I'd suggest looking in the test/ folder (Does unit testing count as CASE?) I'm sure there are some improvements that could be made there.

**Comment by mrdoob** [comment]
What @Mugen87 and @looeee said 👍

**Comment by Seagat2011** [comment]
Ok then its settled, thanks so much guys. All comments will be taken as good advice. This weekend at GGJ17 i'll tackle the editor.js suggestions and the loaders. Best wishes to all ;)

**Pull request closed without merging**
