### PR TITLE
added access to webglrenderer background ( mesh and camera ) for uv managment

### PR DESCRIPTION
**Pull request by nxgraphics**
this lets you change the uv on the fly, needed for mobile dev, depending on device orientation we switch the uv's on fly

### CODE REVIEW

**Comment by WestLangley** [comment]
Why are you changing uv's? Do `offset` and `repeat` not work for you?

And why do you need access to the plane camera?

**Comment by nxgraphics** [comment]
we are rotating the uv's depending on a camera feed, since the browser rotates depending on the device orientation on a mobile device, we need to access the plane ( mesh ) uv's and set them manually, so offset and repeat will not work, the plane and background accessor is enough, 
the camera getter was added for convenience.

**Comment by WestLangley** [comment]
Would #11863 work for you?

**Comment by selimbek** [comment]
For AR purpose, we also want to change WebGLBackground.planeMesh.material with a custom one, to support  GL_OES_EGL_image_external extension.

Yes we can follow the paths designed in [chromium-webar](https://github.com/googlevr/chromium-webar/tree/master/examples/threejs/video) and rendering 2 separates scenes one over the other. 

But for our part, we think it will be more usefull to extend background potential by allowing custom material, and thus giving direct access to WebGLBackground.planeMesh and WebGLRenderer.background . 
This is a little change compared to the flexibility gained

**Comment by PerspectivesLab** [comment]
#11863 can't work since we have our own material with specified shaders, accesing WebGLBackground.planeMesh is needed for 
1/ setting material and not a map,

webgl/WebGLBackground.js line 100 :
`planeMesh.material.map = background;`

2/ changing uv's
webgl/WebGLBackground.js line 21 :
`var planeCamera, planeMesh;`
planeMesh isnt accessible, so no custom material, or even uv access

**Comment by mrdoob** [comment]
I think these use cases are a little bit too advanced for the current `scene.background`. Also, I've yet to make it work properly in WebVR...

**Comment by selimbek** [comment]
Ok I understand, i'll keep an eye on WebVR :)

**Pull request closed without merging**
