### PR TITLE
Examples: Convert cameras and geometries to ES6.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

More usage of ES6 syntax.

### CODE REVIEW

**Comment by Mugen87** [comment]
@marcofugaro When executing the conversion script on my branch, this pops up:
```
/Users/Michael/Documents/workspace/three.js/examples/js/exporters/USDZExporter.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/3MFLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/AMFLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/EXRLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/FBXLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/KMZLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/NRRDLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/TiltLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level

/Users/Michael/Documents/workspace/three.js/examples/js/loaders/VTKLoader.js
  2:1  error  Parsing error: 'import' and 'export' may only appear at the top level
```
It seems the script misses to remove the following import statement. At least on my computer:
```js
import * as fflate from '../libs/fflate.module.min.js';
```

**Comment by marcofugaro** [comment]
@Mugen87 you're on windows right? 

It is probably the `\n` not matching in these replaces, could you test that ti fixes itself by removing the `\n`? 

https://github.com/mrdoob/three.js/blob/d9a5084d261e58807c0ceaed107b37dd36cae877/utils/build/rollup.examples.config.js#L116-L121

**Comment by marcofugaro** [comment]
They can be safely removed, there is a `trimStart()` call after. I'll make a PR if you confirm the source of the problem.

**Comment by Mugen87** [comment]
I'm on macOS.

**Comment by marcofugaro** [comment]
@Mugen87 tested your branch and the issue doesn't happen on my machine.

Could you help me debug this particular line on your machine? Why this replace doesn't work?

https://github.com/mrdoob/three.js/blob/d9a5084d261e58807c0ceaed107b37dd36cae877/utils/build/rollup.examples.config.js#L116

**Comment by Mugen87** [comment]
The strange thing is `import * as fflate from '../libs/fflate.module.min.js';` gets replaced with:
```js
import { unzipSync } from '../libs/fflate.module.min.js';
```
And then the linter complains. Not sure why this happens yet.

**Comment by Mugen87** [comment]
I've removed my `node_modules` folder now and made a fresh `npm i`. Now it seems to work!

**Comment by marcofugaro** [comment]
@Mugen87 it's probably rollup, could you run a `npm install` to make sure you have the correct version?

I have this version:

image

**Comment by Mugen87** [comment]
Yep, using this version solved the issue.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
