### PR TITLE
Fairly sure this should be add not subtract :)

### PR DESCRIPTION
**Pull request by stevesan**
log(a*b) = log(a) + log(b)

### CODE REVIEW

**Comment by WestLangley** [comment]
/ping @bhouston https://github.com/mrdoob/three.js/pull/7414/files

**Comment by bhouston** [comment]
Correct!  Sorry about that.

**Comment by stevesan** [comment]
Thanks guys!
I did have another question concerning this. With the PMREMGen, it
generates a MIP chain with one radiance map per roughness level, and the
roughness levels appear to be linearly increasing (
https://github.com/mrdoob/three.js/blob/dev/examples/js/pmrem/PMREMGenerator.js#L101).
However, getSpecularMIPLevel is specific for the McGuire approximation that
assumes a plain-old box-filtered MIP chain. So is it selecting the best MIP
level if you're using the PMREM MIP chain? Should a different function be
used here, ie. just mipLevel = roughness?

Cheers!
--Steve

**Comment by stevesan** [comment]
Ooof nevermind, right *after* I sent this I saw this;
https://github.com/stevesan/three.js/blob/43fc24478784de820621bc494b3cc9cb8d8ea1c4/src/renderers/shaders/ShaderChunk/lights_pars.glsl#L263

:P

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
@stevesan Thanks for verifying the validity of these equations.  Here are some known issues:

The PMREM is very approximate and had never been truly validated because we use the previous mipmap for the next and it is a bit of work to ensure the repeating convolution corresponds to a particular roughness.  If you wanted to go through it, it may be valuable.

Also there is the issue that the sampling pattern isn't great, and you want to have as few samples as possible to ensure the PMREM is generated fast.

Lastly, to really bring the quality of ThreeJS up someone should code up generating PMREM from within the environment and then using that as local reflection probes -- that would be crazy amazing.  Given that then PMREM takes a cubemap as input, most of the pieces required for this are in place.

BTW I knew Doug James from a long time ago -- probably haven't spoke to him in a decade -- as I also have a simulation background: https://scholar.google.ca/citations?user=--UmWDUAAAAJ&hl=en

**Comment by stevesan** [comment]
Hi @bhouston,
My particular interest is in static env maps, so I think near term I will
end up using a pre-comp tool (probably Lys) for the mip-chain. Dynamic
PMREM would be awesome, just not what I need right now. (Btw have you seen
the Shadow Warrior 2 slides on this? They did it all under 1ms on consoles,
using tricks like having a super-low-quality version of the scene for
rendering the env map: https://www.youtube.com/watch?v=p6eKd5czAvs)

However, I am curious about the CubeUV mapping. What was the reason to do
this over a normal cube map? Is it because textureCubeLodEXT is not 100%
supported? If that is the case, I may want to leverage CubeUV even with a
pre-computed mip chain!

Related, I was also wondering about this line:
https://github.com/stevesan/three.js/blob/43fc24478784de820621bc494b3cc9cb8d8ea1c4/src/renderers/shaders/ShaderChunk/lights_pars.glsl#L254
Isn't the third argument just a bias added to whatever LOD will be
selected? Is it accurate to pass specularMIPLevel for that?

And hey, awesome you use to do sim stuff! Yeah Doug was my PhD advisor, and
we did a bunch of crazy sound sim:
http://dl.acm.org/results.cfm?query=steven+an&Go.x=0&Go.y=0

**Comment by bhouston** [comment]
I was in the audience for some of Theodore Kim's work regarding sound at SIGGRAPH.  It was awesome stuff.  Not sure if it was one of your papers or not as it was some time ago.

> I think near term I will end up using a pre-comp tool (probably Lys) for the mip-chain. 

Understandable.  We use PMREM as it does work well.  I figure it could just be improved a bit in terms of math and it will match Lys.

> I am curious about the CubeUV mapping. What was the reason to do
this over a normal cube map? Is it because textureCubeLodEXT is not 100%
supported

Yes.  We need good results everywhere.  But CubeUV is slow compared to a Cubemap accessed via the extension.  CubeUV does allow for roughness and mipmapping of the roughness at the same time, as it is a dual chain.

Even hen the extension is available, it isn't guarrented that the extension will produce seamless results.  The situation may have changed but at one time it was very problematic -- see this discussion from 2.5 years ago: https://bugs.chromium.org/p/chromium/issues/detail?id=479753

> Btw have you seen
the Shadow Warrior 2 slides on this? They did it all under 1ms on consoles,
using tricks like having a super-low-quality version of the scene for
rendering the env map: https://www.youtube.com/watch?v=p6eKd5czAvs)

We should implement something like that -- this is one of the first places where Three.JS is not competitive with UE4 and Unity. :)

> Isn't the third argument just a bias added to whatever LOD will be
selected? Is it accurate to pass specularMIPLevel for that?

It is wrong and I guess it can be removed.  Removing it is also wrong because the map doesn't blur.  So both solutions are wrong.

I suggest using CubeUV if the extension isn't available so this case is never hit.

**Comment by stevesan** [comment]
Got it, well if it's easier I'll give the PMREM generator a shot! Maybe
I'll dig in and see what I can do to improve it if anything (wouldn't call
myself an expert on convolving though).

Yeah Ted was a post doc at Cornell, and we worked on my first paper
together. He does awesome stuff! If the talk was about reduced deformable
models, it's definitely related to what we did together :)

**Pull request merged**
