### PR TITLE
GLTFExporter: create separate accessors per group for non-indexed geometry

### LINKED ISSUE #21538: GLTFExporter does not honor groups with non-indexed geometry.
**Describe the bug**

A model that uses multiple materials on a single mesh does not always export to glTF in a way that preserves the multiple materials.

Specifically, I noticed the problem with non-indexed geometry. It looks like it does work for indexed geometry.

**To Reproduce**

1. Go to https://codesandbox.io/s/pensive-microservice-iq2vp
2. See that the cube has different colors on each side, due to multiple materials each assigned to a group on the geometry.
3. Click the "Download .gltf" button. (Unfortunately couldn't get the fancy download button to work. But it logs the glTF JSON to the console in the code sandbox. And [here's a gist](https://gist.github.com/wnayes/da34358701951667cf8407d10a10bba4) with what the JSON result is.
3. Import the cube gltf into something like Blender and observe that all sides are one color.

***Code***

The full example is in the sandbox:
https://codesandbox.io/s/pensive-microservice-iq2vp

But the important parts are as follows:
```js
  const geometry = new THREE.BoxBufferGeometry( 10, 10, 10 );
  geometry.clearGroups();
  geometry.addGroup( 0, 6, 0 );
  geometry.addGroup( 6, 6, 1 );
  geometry.addGroup( 12, 6, 2 );
  geometry.addGroup( 18, 6, 3 );
  geometry.addGroup( 24, 6, 4 );
  geometry.addGroup( 30, 6, 5 );
  geometry = geometry.toNonIndexed(); // Important for repro

  const materials = [
    new THREE.MeshBasicMaterial( { color: 0xFFFFFF, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0xFF0000, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0x00FF00, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0x0000FF, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0xFFFF00, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0x00FFFF, visible: true } )
  ];

  const mesh = new THREE.Mesh(geometry, materials );
  scene.add( mesh );
```
```js
  const exporter = new GLTFExporter();
  exporter.parse(scene, function (gltfJson) {
    console.log(gltfJson);
  }, { binary: false });
```

**Screenshots**
Cube in code sandbox rendered by three.js:
three-cube-codesandbox

Cube in Blender after glTF export with GLTFExporter:
three-cube-blender

**Platform:**

 - Browser: [Chrome]
 - Three.js version: [0.126.1]

**Observations**
In the glTF file that is created, the primitives of the mesh all use different `material`s as expected, but they all share the same `attributes` which appears to be the cause of the render issue.

In GLTFExporter `processMesh`, I think we'd need to create separate accessors for each group. This is done when `geometry.index !== null` in the groups loop towards the bottom of `processMesh`, but for non-indexed there is no equivalent handling.

### PR DESCRIPTION
**Pull request by jtbandes**
Fixes https://github.com/mrdoob/three.js/issues/21538

**Description**

GLTFExporter handled `groups` for indexed geometry by adjusting the `indices` accessor. However, it was missing logic to handle `groups` in non-indexed geometry. This change adds support for non-indexed geometry by creating separate accessors for each group.

Also adds a new multi-colored cube example (both indexed and non-indexed) taken from https://github.com/mrdoob/three.js/issues/21538 to misc_exporter_gltf.html, ~and to the unit tests~. Looks like the unit tests have been deleted 😓 

image

One downside of this implementation (and the current exporter architecture) is that the attribute data gets duplicated when groups overlap. Fixing this seems like it might require a more difficult refactor and I would appreciate input from anyone familiar with the existing code.

### CODE REVIEW

**Comment by jtbandes** [comment]
cc @takahirox @donmccurdy It looks like you both have worked on GLTFExporter; would you be able to review this change?

**Comment by donmccurdy** [comment]
> One downside of this implementation (and the current exporter architecture) is that the attribute data gets duplicated when groups overlap. Fixing this seems like it might require a more difficult refactor...

I don't think it's necessary to fix this – likely a rare case, and could be avoided by using indices. Performance-sensitive applications should probably be using indices anyway? Plenty of tools are available for optimizing the glTF after export as well.

This looks good to me if @takahirox has no concerns — thanks @jtbandes!

**Comment by jtbandes** [comment]
Any update on this?

**Comment by takahirox** [comment]
Sorry, wanted to review but lack of time. Please ignore me for now because I don't want to block. I may review later as follow up.

**Comment by mrdoob** [comment]
The thing is that I'm not really a fan of our geometry groups / multi material API anymore...

How does GLTF deal with the concept of geometry groups / multi material?

**Comment by takahirox** [comment]
> How does GLTF deal with the concept of geometry groups / multi material?

In glTF a `mesh` can have multiple `primitives`.

https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#geometry

A `primitive` consists of a `geometry` (`attributes` and `indices` in glTF) and a reference to a `material`. A `mesh` having multiple `premitives` in glTF may correspond to a `Mesh` having geometry groups and multi materials in Three.js.

Three.js `GLTFLoader` used to create a `Mesh` having geometry groups and multi materials from `mesh` having multiple `primitives` in glTF. But we realized geometry groups and multi materials can make `GLTFLoader` complex. So we decided to create ` Group` having multiple `Mesh`es from it. So now `GLTFLoader` doesn't generate geometry groups and multi materials.

**Comment by donmccurdy** [comment]
Each glTF mesh could contain many primitives, where some primitives are triangle meshes and others are points or lines, they do not have to be consistent. So, mapping a mesh to `THREE.Group` containing `{Mesh | Points | Lines | ...}[]` in three.js works well enough, but the relationship might be too loose to be useful for inspiring a new three.js object API.

**Comment by kolodi** [comment]
Splitting a single mesh with multi materials (geometry groups) into separate meshes during export/import feels not quite right. It breaks many workflows dependant on nodes structure of the scene. In my case, I really need single mesh for the decals to work properly. Once you have exported a single mesh into multiple glTF primitives there must be a way to restore the same exact single mesh during the import process. 
To work around this issue I have introduced the automerge step after the import based on some userData information in my specific application, but this adds a certain overhead to the loading process. I think restoring original scene shape directly during export/import is a more correct approach.

**Comment by donmccurdy** [comment]
I've given up on trying to have GLTFLoader create multi-material meshes during the loading process — there's no possible glTF input for which GLTFLoader will currently construct a multi-material mesh. Trying to do so within the loader added a lot of complexity and overhead in the past.

I have no strong preference on what _GLTFExporter_ should do, though.

**Pull request closed without merging**
