### PR TITLE
WebXRManager: Controllers dispatch 'inputsourceschange' event

### PR DESCRIPTION
**Pull request by soadzoor**
Among other potentially useful things, this is needed to determine whether we should add a helper line to the controller or not. Before firing this event, there's no information available about the controller's type (handheld, head, etc.)

### CODE REVIEW

**Comment by mrdoob** [comment]
We should implement this event in WebVRManager too otherwise ballshooter won't show the lines when using the WebVR API.

**Comment by soadzoor** [comment]
I think WebVR doesn't support handheld controllers, so there's no way and no point to dispatch this event there. But maybe I'm wrong, I'm not really familiar with the WebVR specification.

**Comment by mrdoob** [comment]
If `WebVRManager` doesn't emulate this event somehow the example will look different depending on the platform.

**Comment by soadzoor** [comment]
They work different now, as they are. I cannot get the shooting event working with WebVR. The `selectstart` and `selectend` events are not firing when I use WebVR instead WebXR.

My suggestion would be to deprecate the whole WebVR thing in favor of WebXR. No one should develop using the WebVR API anymore.

**Comment by soadzoor** [comment]
> Really? The ballshooter example works on Oculus Go and that is using the WebVR API.
Well, it doesn't work in a simple google cardboard viewer for me, but maybe I'm missing something. You can try if you remove the origin trial meta tags and set the necessary flags in your android device's `chrome://flags`.

> The WebXR API is still not finished. Oculus browser and Firefox support WebVR and not WebXR.
Yea, maybe it would be too soon to deprecate it. It's a screwy situtation, because WebVR is still experimental (browsers generally don't support it by default. You can set some flags, or request an origin trial token), but WebXR already makes it out of date.

Is there an event in WebVR manager, that fires when the controllers are assigned? Is there a way to determine whether the user is using a handcontroller, or headcontroller?

**Comment by jsantell** [comment]
@soadzoor WebVR uses the Gamepad API; [THREE.VRController](https://github.com/stewdio/THREE.VRController) is a good reference implementation

**Comment by soadzoor** [comment]
@jsantell Seems to me that it checks for a change in a loop, which doesn't seem to be a nice solution. Is there any other way?

**Comment by jsantell** [comment]
@soadzoor that's just how you check the gamepad API, by checking values on every frame, leaving it up to the consumer to implement things like double press or hold. Very tedious. Also it's being replaced with XRInputSource for WebXR

**Comment by soadzoor** [comment]
It seems I cannot get the ballshooter example working with the webvr API with a cardboard viewer. I can look around, but I cannot make any interactions (shoot balls). Kind of a good news is that there's no controller-helper visible either.

So we're kind of stuck here.

The example uses the `selectStart` and `selectEnd` methods to decide whether the user is currently interacting with the scene (with either a handcontroller, or a "head"controller --> by tapping the scene basically). But it seems these methods are only available for a WebVR-handcontroller combo, or for WebXR-anycontroller combo.

> If WebVRManager doesn't emulate this event somehow the example will look different depending on the platform.

-- > So merging these changes wouldn't make the examples less consistent across the different WebVR APIs

**Comment by Mugen87** [comment]
> We should implement this event in WebVRManager too otherwise ballshooter won't show the lines when using the WebVR API.

It seems this change is good to go now?

**Pull request closed without merging**
