### PR TITLE
Replace deprecated String.prototype.substr()

### PR DESCRIPTION
**Pull request by CommanderRoot**
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

### CODE REVIEW

**Comment by mrdoob** [comment]
Why `slice()` instead of `substring()`?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

**Comment by CommanderRoot** [comment]
Both have their use cases. Both return the same in most cases but can [differ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#differences_between_substring_and_slice) if the second parameter is smaller than the first or negative.
I personally like that `slice()` has less "magic" and is more likely to act the way you want to (or think it does). For example in cases where you expect the second parameter to be possibly negative and you want to replicate `substr()` you would use `substring()` other than that I like to use `slice()`

**Comment by CommanderRoot** [comment]
That's correct. In both cases the first parameter is >= 0. If the second one would be negative `substring()` will return an empty string (like `substr()`), `slice()` however would return everything from the start until the last x chars

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
