### PR TITLE
[WIP] VR + Post Processing

### PR DESCRIPTION
**Pull request by takahirox**
Let me share my WIP PR trying to enable VR + post-processing.
Feedback is welcome because I'm feeling like there'd be better designs.

Video: https://twitter.com/superhoge/status/866687749385891841

Policy:
- keep using `EffectComposer` + `Pass` approach
- reusable existing shader pass
- enable different post-processing for each left/right view

Basic idea:
1. Render normally with `WebVRCamera`
2. Extract the left/right half of the result of 1 to half size renderTarget. 
3. Apply pass to each half
4. Combine the left/right results

Disadvantage:
- Not good Performance. Rendering# increases in five. (two for 2., two for 3., one for 4.)

How to use:

    // Glitch example
    camera = new THREE.WebVRCamera( vrdisplay, renderer );
    composer = new THREE.EffectComposer( renderer );
    composer.setSize( window.innerWidth, window.innerHeight );
    composer.addPass( new THREE.RenderPass( scene, camera ) );
    composer.addPass( new THREE.ShaderVRPass( vrdisplay, new THREE.GlitchPass() ) );
    composer.passes[ composer.passes.length - 1 ].renderToScreen = true;

Change:
- Add `ShaderVRPass` which acts as the basic idea I wrote above.
- Update `WebGLState` properties instead of `WebGLRenderer` properties for rendering with `ArrayCamera`(see #11051)
- Add a way to prevent `vrDisplay.submitFrame()` invoking from `WebVRCamera` because I wanna invoke it after post-processing.
- Extract update logic (ex: glitch calculation) from `pass.render()` to `pass.update()` method because I wanna call `pass.render()` two times but run the update logic once in an animation frame.

### CODE REVIEW

**Comment by wizgrav** [comment]
I think that the performance issue in your approach could be solve by having a .renderTarget property to camera. This property would override the framebuffer per camera similar to the .viewport property of WebGLRendertarget. This way things would get drawn directly in the appropriate target. I'm not sure what the cost of switching framebuffers per object is but I imagine it would amount to much less than an extra full screen pass

**Comment by takahirox** [comment]
Thanks for the comment.

I need to update this PR because Three.js VR API has been updated.

**Comment by takahirox** [comment]
@mrdoob 

Currently `vr.submitFrame();` is called in the end of `WebGLRenderer.render()` if `vr` is enabled.

https://github.com/mrdoob/three.js/blob/146b9370daa183c3c8f88879b12069b7dffe2c3b/src/renderers/WebGLRenderer.js#L1238-L1242

But we wanna call `.submitFrame()` after post-processing if post-processing is applied.

There're some options in my mind,

1. add an option to `WebGLRenderer` or `WebVRManager` which enables VR but doesn't call `.submitFrame()`
2. `WebGLRenderer` has post-processing support (imports `EffectComposer`?) and calls `.submitFrame()` after applying post-processing.

Which one do you prefer? Or any better ideas?

**Comment by wizgrav** [comment]
regarding submitFrame, #11582 addresses that the same way VREffect did, by setting an autoSubmitFrame flag

**Comment by takahirox** [comment]
Thanks!

@mrdoob Will you merge #11582 soon?

**Comment by takahirox** [comment]
Updated. I've changed the strategy a bit.

`EffectComposer` manages post-processing for VR. So no longer we need `ShaderVRPass`.

Users can reuse `*Pass` for VR without any changes now.

Video: https://twitter.com/superhoge/status/927923513767337984

		composer = new THREE.EffectComposer( renderer );
		composer.setSize( window.innerWidth, window.innerHeight );

		composer.addPass( new THREE.RenderPass( scene, camera ) );
		composer.addPass( new THREE.UnrealBloomPass( new THREE.Vector2( window.innerWidth, window.innerHeight ), 1.0, 0.7, 0.1 ) );
		composer.addPass( new THREE.ShaderPass( THREE.FilmShader ) );
		composer.addPass( new THREE.GlitchPass() );
		composer.addPass( new THREE.ShaderPass( THREE.FXAAShader ) );

		composer.passes[ composer.passes.length - 1 ].renderToScreen = true;

**Comment by mrdoob** [comment]
Are you planning on updating this PR after the `scene.onAfterRender()` addition?

**Comment by takahirox** [comment]
Yes, I'm working now 😄

**Comment by takahirox** [comment]
Feeling like first updating `EffectComposer` APIs with `scene.onAfterRender()` even for non-VR. VR support is next.

IMO current `EffectComposer` isn't fitting to `scene.onAfterRender()`

**Comment by sjlynch** [comment]
Any updates on this? This is something I think a lot of us need for our WebVR projects.

I looked into aframe-effects for VR post-processing but it does not seem to be very well maintained. https://github.com/wizgrav/aframe-effects

If three.js could support VR with effectscomposer, it would be killer and IMO is one of the few remaining key features needed to convince people to use Threejs over something like Unity.

**Comment by takahirox** [comment]
I'm revisiting VR + PostProcessing... Came to think Aframe style looks more performant and am gonna try.

**Comment by takahirox** [comment]
Closing in favor of #15840

**Pull request closed without merging**
