### PR TITLE
Only compute direction once in sky shader and disable depthWrite

### PR DESCRIPTION
**Pull request by Oletus**
depthTest is kept enabled since it may be desirable to render the sky after other geometry is already rendered.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/higharc/three.js/sky-shader-cleanup2/examples/webgl_shaders_sky.html

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
@Mugen87 @Oletus starting at luminance = 1.1897 and above you get this at https://raw.githack.com/higharc/three.js/sky-shader-cleanup2/examples/webgl_shaders_sky.html:



Is it supposed to do that?

**Comment by Mugen87** [comment]
@makc I see the same behavior on prod so I guess it's the intended behavior.

**Comment by Oletus** [comment]
@mrdoob Thanks for merging!

@makc That's a pre-existing issue not related to this patch specifically. Probably numerical precision runs out somewhere, so I doubt it's exactly intended. But not sure how much need there is to go in and try to analyze it.

**Pull request merged**
