### PR TITLE
Add WebGL1Renderer.

### PR DESCRIPTION
**Pull request by Mugen87**
See https://github.com/mrdoob/three.js/pull/19620#issuecomment-643307729.

### CODE REVIEW

**Comment by gero3** [comment]
Why not add a read-only property `ContextNames` which can be overridden by WEBGL1Renderer to store which contexts need to be checked?? The getContext code will look cleaner and the WebglRenderer doesn't need to know about WEBGL1renderer.

**Comment by Mugen87** [comment]
Sounds a bit like over-engineering to me. This is a simple and easy change. And I don't think it's a problem that `WebGLRenderer` test for `isWebGL1Renderer`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Made the code a little bit more robust: https://github.com/mrdoob/three.js/commit/c5dc00682d87aaad49ee6b096176c0cc43708acf

**Comment by Mugen87** [comment]
Looks nice! ❤️

**Pull request merged**
