### PR TITLE
Added GLTFLoader support for EXT_mesh_gpu_instancing

### PR DESCRIPTION
**Pull request by shantzis1962**
Related issue: #21937 

This PR implements the glTF EXT_mesh_gpu_instancing extension in GLTFLoader. It includes support for any combination of translate/rotate/scale and also correctly handles the case where the node already has a transform assigned to it.

It also provides an example in /examples/?q=gltf#webgl_loader_gltf_instancing (copying the "Battle Damaged Sci-Fi Helmet").

Note: This is my first PR in threejs so forgive me if I got some of the conventions wrong. In particular, I wasn't sure whether it was correct to copy/rework the 'jsm' version into the 'js' version. I did so just in case.

### CODE REVIEW

**Comment by takahirox** [comment]
Hi @shantzis1962, thanks for being interested in and working on it. I have read through the code. I think the implementation can be simpler. For example Three.js glTF loader and pluting generally don't need to validate data. It's ok to expect input data is valid. We ask users or apps to validate data with external glTF validators beforehand.

As in https://github.com/mrdoob/three.js/issues/21937 there already be [an external `EXT_mesh_gpu_instancing` plugin](https://github.com/takahirox/three-gltf-extensions/blob/main/loaders/EXT_mesh_gpu_instancing/EXT_mesh_gpu_instancing.js) made by me. I think it's simpler and can be good start.

If you don't mind, I will make a PR based on mine now and I would like you to ask for creating a follow up PR (if yours have some improvements). What do you think?

**Comment by shantzis62** [comment]
@takahirox Thanks for taking a look at this. Yes, that's great. Again, please accept my apologies if I "stepped on your toes" with this PR. Please do make a PR and once it's pulled in, I'll see if it's even necessary for me to make additions.

Again, thank you...

**Comment by takahirox** [comment]
@shantzis62 

Thanks for the response. I made a PR #24528 let me close this PR for now.

> Again, please accept my apologies if I "stepped on your toes" with this PR.

No problem, at all! Please don't apology. I know I should have made a PR much earlier.

**Comment by WestLangley** [comment]
> I wasn't sure whether it was correct to copy/rework the 'jsm' version into the 'js' version.

That is not necessary. The `js/` versions are auto-generated later via `npm run build-examples`.

**Pull request closed without merging**
