### PR TITLE
replaced javascript keywords with non-conflicting alternatives

### PR DESCRIPTION
**Pull request by dr0ps**
I use the YUI Compressor to generate a compressed version of three.js and the additional files used in my project. YUI Compressor requires a very strictly valid javascript syntax and fails because javascript keywords are used as parameter or variable names in several places of three.js. After my changes the YUI Compressor does no longer complain.
I think I applied all suggested changes from the last try but I also rebased the commit on a current dev branch.

### CODE REVIEW

**Comment by looeee** [comment]
`boolean` is not a JavaScript keyword. `Boolean` is, but the capitalization is important. 

It's YUI compressor that is incorrect here, not three.js. 

It's also a [dead project](https://github.com/yui/yuicompressor/issues/276) as far as I can see - barely any updates in the last couple of years. You should probably switch to a different minifier.

**Comment by looeee** [comment]
Also, this is exactly the same as your previous PR here: #13065 
You were asked to use `bool` as an replacement for `boolean` the last time. 

If you make that change this will probably be accepted, since `bool` tends to be the standard parameter name anyway.

**Comment by dr0ps** [comment]
So I changed it all to "bool".

**Comment by mrdoob** [comment]
> `boolean` is not a JavaScript keyword. `Boolean` is.

👍

**Comment by dr0ps** [comment]
This is ridiculous. Lowercase boolean is a keyword in all Javascript/Ecmascript standards except ES5/6. Uppercase Boolean is not a keyword at all but the class name for the wrapper object. It is probably very much ok to have your own Boolean. It is not ok to use boolean except for ES5/6.

**Comment by mrdoob** [comment]
@dr0ps do you have any links that support your claim?

**Comment by looeee** [comment]
Actually @dr0ps is partially correct, `boolean` was a "Future reserved keyword" in ES1-3. 

That is, it was never actually a keyword but was reserved as a potential keyword. 

See "Future reserved keywords in older standards" on [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) mdn page. 

We could merge this as it's a relatively minor change, but I think that the onus is on users like @dr0ps to ensure that they are using libraries that are compliant to the _current_ spec. Or at least a fairly recent spec. ES3 has been outdated since ES5 was released in 2009.

**Comment by dr0ps** [comment]
Sure. The ECMAscript 6 Lexial Grammar says "The following are reserved as future keywords by older ECMAScript specifications (ECMAScript 1 till 3)" and it lists both "boolean" and "char". 
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Lexical_grammar
And the W3C explicitly states "Do not use these words as variables. ECMAScript 5/6 does not have full support in all browsers".
https://www.w3schools.com/js/js_reserved.asp

**Comment by looeee** [comment]
@dr0ps w3schools is a good place for learning JS but should not be taken as a definitive source for spec info. You should refer to mdn instead.

Unless you can find a source that says otherwise, I think we can assume that all modern browsers are fully ES5 compliant (or at least very close to), and we don't need to follow older spec versions anymore. 

Again, I would suggest that you change to a different library for minification, since the one you are using is outdated.

**Pull request closed without merging**
