### PR TITLE
Remove JSONLoader from THREE namespace

### PR DESCRIPTION
**Pull request by Mugen87**
This PR removes `JSONLoader` from the examples, editor and docs. It's not possible to create the loader via `new THREE.JSONLoader()` anymore. Instead, an error message is logged.

`ObjectLoader` is still able to use `JSONLoader`. So technically, `JSONLoader` is still part of the build but not accessible over the `THREE` namespace. Examples like [webgl_loader_json_claraio](http://localhost:8080/examples/webgl_loader_json_claraio.html) still work.

At some point, we might want to completely remove the `Geometry` support from `ObjectLoader`.

### CODE REVIEW

**Comment by Mugen87** [comment]
Okay, I've added `JSONLoader` to `examples/js/loaders/deprecated`. If the file is added to an app, the default `JSONLoader` definition of the core library (which produces an error log now) will be overwritten and the loader can be used as before.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Don't you think this should be mentioned in the migration docs?

**Comment by Mugen87** [comment]
> Don't you think this should be mentioned in the migration docs?

Um, of course. I was going to do it. But you know I'm from Germany. When this PR was merged, it was Saturday in the middle of the night and quite frankly I was pretty busy with my date (adorable girl with blond hair and green eyes).

Sorry for the delay. Let me update the migration guide now 🙌 .

**Comment by mrdoob** [comment]
Wait. We have not removed the code, we have just made it inaccessible.

It's a bit confusing... 🤔

**Comment by Mugen87** [comment]
`OBJLoader` still needs the code in order to parse geometries of type `Geometry`.

https://github.com/mrdoob/three.js/blob/0c51e577afd011aea8d635db2eeb9185b3999889/src/loaders/ObjectLoader.js#L194-L195

**Pull request merged**
