### PR TITLE
Added another exporter for 3D Max that handles Morph Targets 

### PR DESCRIPTION
**Pull request by mesealexan**
New exporter for 3D Max
It outputs all the vertices position into morpTargets.
It uses the active time frame
It checks for position, rotation, scale, and modifiers and exports all
vertices positions locally.

I'm also working on a generic exporter for 3D Max that will export the entire scene (cameras, lights, geometries, lines, animated objects using keyframes, animated objects using morph targets). Do you think it would be useful?

### CODE REVIEW

**Comment by pixeldamage** [comment]
A decent exporter for max would be handy for me. I've currently been using openCollada to get my meshes into the engine and exporting dummy objects for camera / light animation. I've learnt a bit of code/ three.js enough to create and assign pbr materials and linking up matrices. I've been having problems with ThreeJSExporter.ms getting Morph Targets out. I think it's partly because I'm not sure how the script expects the scene setup in max.I've tried using the Morpher modifier as well as a skinned animation. Is there any documentation for how it's supposed to be used? I'm using the horse example TJS scene to debug the lack of morph target but the exporter has so far given me still/static meshes. Ideally what I'm trying to acheive is to bake down a very complex rig to point cache / vertex animation and this seems like the best way currently of doing it. Or is it?

**Comment by looeee** [comment]
Have you tried exporting as FBX and using the FBXLoader?

**Comment by pixeldamage** [comment]
@looeee Hi thanks for the reply. Do you mean in general or with morph targets? A few weeks ago I did some size tests and found ascii fbx to be larger than dae (at least in this instance and size is a concern for these projects). 

I've just done some more tests with the FBXLoader / Exporter and found I'm not getting morph targets or standard materials out (they default to unlit/basic) with the error "FBXLoader.js:206 No implementation given for material type [object Object] in FBXLoader.js." I've tried std blinn / std phong / dx shader.  

I also tried with exporting out to both Z and Y up and both are coming out the same (the usual 90 degree offset issue between Z/Y coord systems). Resetting the transforms doesn't seem to help. Point Cache modifiers get disabled at export (apparently it will disable all WSM modifiers). At least from my experiments so far I've found OpenCollada doesn't suffer these rotation issues and I hacked it's loader to read std phong mats as TJS PBR to make the process a little easier. Still it's far from ideal as it doesn't read lights, cams or (for me so far) morph targets and point cache data

**Comment by pixeldamage** [comment]
I've just done some more investigating and it looks like there are two FBXLoaders (FBXLoader.js & FBXLoader2.js) available. By looking inside those files it seems neither support morph targets, point cache, lights or cameras. @mesealexan I know this thread is a couple of years old but is your enhanced max exporter available anywhere? I've tried your .js exporter (ThreeJSExporter.ms) and I couldn't get morph targets to appear at all until I opened up the exported .js file and found all the MT keys are labelled FRAME000. By manually editing/incrementing these I got it to work. I'm guessing perhaps something's changed in newer versions of max.

**Pull request merged**
