### PR TITLE
Add support for loading SkinnedMeshes from SceneLoader + bug fix.

### PR DESCRIPTION
**Pull request by bhouston**
ObjectLoader would only load Meshes, not SkinnedMeshes.  We found it nicer if ObjectLoader would load meshes that have bones as SkinnedMeshes.  This change does that.

Additionally, there was a bug with nodeName not being set in the AnimationClip.parseAnimation() function.  This removes nodeName as it wasn't necessary anyhow.

### CODE REVIEW

**Comment by mrdoob** [comment]
The `ObjectLoader` change looks good. But I fear the `AnimationClip` change may conflict with @tschw refactoring PR?

**Comment by tschw** [comment]
Sure would. However, I didn't *really* change that code and just moved it around, so I guess we should certainly pull the bugfix on top of it.

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by tschw** [comment]
OK, in this case I guess I'll take care of it :-).

**Pull request merged**
