### PR TITLE
GridHelper: Size parameter is now correctly handled

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adresses #10409.

A grid with `size` of 10 is now equal to a `PlaneGeometry` with `widht`/`height` of 10.

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks. Update examples, too?

**Comment by Mugen87** [comment]
Of course! I forgot about it.

**Comment by Mugen87** [comment]
Done!

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
@Mugen87 regarding the docs for this, if I do:

    var gridHelper = new THREE.GridHelper( 10 );

this will create a 20x20 square grid centred at (0, 0, 0). Correct?

**Comment by Mugen87** [comment]
See http://jsfiddle.net/2zvfzuL7/1/

```javascript
var gridHelper = new THREE.GridHelper( 10 );
```
will produce a 10x10 grid.

**Comment by looeee** [comment]
Ah great! I think that should count as "expected behaviour" 😁 
I'll leave the docs as they are.

**Pull request merged**
