### PR TITLE
CSS2D/3DRenderer: Make the code more reasonable.

### PR DESCRIPTION
**Pull request by lafflan**
IMO, i don't think it's necessary to traverse the entire scene every frame, only traverse and hide when `object.visible === false` is more reasonable.

### CODE REVIEW

**Comment by yomotsu** [comment]
As I mentioned before:
https://github.com/mrdoob/three.js/pull/28293#issuecomment-2097841080
I think ALL objects need to be hidden before rendering.

Therefore, this change might break the expected behavior.
You may test with nested CSS2D/3DObjects.

**Comment by lafflan** [comment]
> like
hidden object > visible object Should hide both objects. but the child may be rendered with this change.
I have tested in `examples/css2d_label.html` of both nested `mesh > css2d` and `css2d > css2d` situation, all results appear to meet expectations.

**Comment by lafflan** [comment]
> > like
> > `hidden object > visible object` Should hide both objects. but the child may be rendered with this change.
> 
> I have tested in `examples/css2d_label.html` of both nested `mesh > css2d` and `css2d > css2d` situation, all results appear to meet expectations.

**Comment by mrdoob** [comment]
@lafflan Any chance you can share the code you used for testing that?

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
