### PR TITLE
Fixed Xbot.glb normals

### PR DESCRIPTION
**Pull request by c-morten**
- Reported in https://github.com/mrdoob/three.js/pull/18822#issuecomment-612733862

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Would it be possible to also include the `blend` file in the repo so people can see how it was created?

**Comment by c-morten** [comment]
Sure, where would you want that file to live? Add a 'blend' folder to examples/models?

**Comment by mrdoob** [comment]
Yep! `examples/models/gltf/Xbot.blend`

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：c-morten <notifications@github.com>
发送时间：2020-05-14 03:02
主题：Re: [mrdoob/three.js] Fixed Xbot.glb normals (#19354)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Sure, where would you want that file to live? Add a 'blend' folder to examples/models?

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：c-morten <notifications@github.com>
发送时间：2020-05-14 02:51
主题：[mrdoob/three.js] Fixed Xbot.glb normals (#19354)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Reported in #18822 (comment) 



You can view, comment on, or merge this pull request online at:
  https://github.com/mrdoob/three.js/pull/19354
Commit Summary
Fixed Xbot.glb normals 
File Changes
M examples/models/gltf/Xbot.glb (0) 
Patch Links:
https://github.com/mrdoob/three.js/pull/19354.patch 
https://github.com/mrdoob/three.js/pull/19354.diff

**Pull request merged**
