### PR TITLE
[Tentative] Texture layering

### PR DESCRIPTION
**Pull request by emileswain**
I need to re-write this for a proper pull request, but before i did i wanted to gather some feedback and guidance on if it would be A) useful, and B) the correct approach.

**What does it do**
You can layer multiple textures and apply masking between them.

**How does it do that**
WIth the custom uniforms a user can specify a target texture (Atlas) and mask to override the diffuseColor.

Enabling layerTextureMaps inserts all the require Shader chunks.

**There are two examples**
There are two examples, one with material loader, and the other with hand written.

webgl_materials_layered_textures.html
webgl_materials_layered_textures2.html

**Issues**
- I've implemented this on the base material class, short of where else whilst to implemented it whilst i  was finding my way around Three.js. 
- I've only partially implemented all of the attributes. So this commit only supports one masked texture over the existing map.
- Naming is confusing.
- I've limited knowledge of shader performance so believe the methods aren't great. How to test if a material is loaded. 
- It is a straight port from my project so has some limitations. I.e. Atlas lookup is limited.
- I've committed (a sin) the build folder, and some psd files that are unnecessary. Hence a re-write. Afraid i'm not that familiar with git/hub.

**Summary**
I hope this proves useful to someone, even if it's an example of not how to implement this. I'd be willing to look at re-implementing this in a better way if that would be useful.

### CODE REVIEW

**Comment by WestLangley** [comment]
http://ci.threejs.org/api/pullrequests/8315/examples/webgl_materials_layered_textures.html
http://ci.threejs.org/api/pullrequests/8315/examples/webgl_materials_layered_textures2.html

**Comment by mrdoob** [comment]
Have you considered using `NodeMaterial`? http://threejs.org/examples/#webgl_materials_nodes

**Comment by emileswain** [comment]
Wow, how did i miss that! It certainly looks like it has the ability to achieve a whole host of effects. 

Though i have to say i would not have immediately guessed that THREE.Math3Node() would be the answer to layering textures. 

I'll go and look through all the examples and docs etc, but is this optimised for mobile use?

**Comment by Mugen87** [comment]
Closing. I guess it makes more sense to build something like this with `NodeMaterial` instead of modifying the current implementation of `WebGLRenderer`.

**Pull request closed without merging**
