### PR TITLE
Refactor cubemap example

### PR DESCRIPTION
**Pull request by looeee**
Replace the walt head model with the OBJ version, remove use of `BinaryLoader` and deleted the old binary format models since they are no longer used. 

[live version](https://rawgit.com/looeee/three.js/431a936c9a035d372e64336063b90ba215d4f845/examples/webgl_materials_cubemap.html).

EDIT: switched to use of `OrbitControls` as well, instead of custom control

### CODE REVIEW

**Comment by looeee** [comment]
@Mugen87 are you OK with using the OBJ version of the model here? I can switch to the GLTF version if you prefer.

**Comment by Mugen87** [comment]
I would also use the glTF Version😇

**Comment by looeee** [comment]
OK, done 😄

**Comment by mrdoob** [comment]
As in #13085, I think it's better to use the OBJ for this specific model.

**Comment by mrdoob** [comment]
Sorry for the back and forth! 😇

**Comment by looeee** [comment]
:sweat-smile:

It's no problem, I learned how to use obj2gltf which will surely come in handy.

I'm traveling a lot the next two of days but I'll try and find a coffee shop to do this in.

**Comment by mrdoob** [comment]
Ops! Another merge created some conflicts. 😇

**Comment by mrdoob** [comment]
Wait, I should be able to merge the first two commits.

**Comment by mrdoob** [comment]
Done. Thanks!

**Comment by looeee** [comment]
Sweet!

**Pull request closed without merging**
