### PR TITLE
SMAAPass: Texture marked for update but image is incomplete

### PR DESCRIPTION
**Pull request by ghost**
See #15162 
Mark textures for update asynchronously

### CODE REVIEW

**Comment by Mugen87** [comment]
Any chances to rebase the PR on the latest `dev` branch?

**Comment by cnsdato** [comment]
> Any chances to rebase the PR on the latest `dev` branch?

I will try

**Comment by cnsdato** [comment]
Is there any chance to edit this pull request to an other branch? Or should I create a new one?

**Comment by Mugen87** [comment]
Maybe it's easier to create a new branch based on latest `dev`

**Comment by cnsdato** [comment]
Yes I have done this. But should I create a new PR and let this one closed?

**Comment by Mugen87** [comment]
Please create a new PR.

**Pull request closed without merging**
