### PR TITLE
Added shared skeleton example

### PR DESCRIPTION
**Pull request by funwithtriangles**
Multiple instances of SkinnedMesh all controlled by a single Skeleton. Use the controls to compare performance with a multi skeleton approach.

Related issue: https://github.com/mrdoob/three.js/issues/9606

### CODE REVIEW

**Comment by WestLangley** [comment]
Temporary live link:

https://raw.githack.com/funwithtriangles/three.js/dev/examples/webgl_animation_sharedskeleton.html

**Comment by titansoftime** [comment]
Very impressive. Now since each mesh has its own mixer, is it possible for the animations to be out of sync or even play different animations simultaneously?

Even if not, your approach would be a huge help in a variety of scenarios. Nice.

**Comment by funwithtriangles** [comment]
Where you see each mesh having its own mixer is just for the multi skeleton example to show the performance difference. With the shared skeleton it is just one mixer. The only way I can see to have a bit of variation is to increase the number of shared skeletons and assign them randomly throughout the meshes.

**Comment by funwithtriangles** [comment]
Wondering if the example should be slightly simpler in terms of the GPU side of things. It runs nice and smooth on my machine but I fear it's going to be quite hellish for slower machines. Perhaps start with less dancers and maybe simpler materials?

**Comment by looeee** [comment]
This is cool, but the example should start with less rows (probaly just one). Attempting to run it on my Moto G6, Firefox just crashes and Chrome only displays a black screen.

**Comment by funwithtriangles** [comment]
Yep, I think I'm a little spoilt running on my high end gaming laptop. 😅 Will get around to doing some tweaks to this.

**Comment by titansoftime** [comment]
> Where you see each mesh having its own mixer is just for the multi skeleton example to show the performance difference.

Ah. Gotcha.

> The only way I can see to have a bit of variation is to increase the number of shared skeletons and assign them randomly throughout the meshes.

Makes sense.

**Comment by funwithtriangles** [comment]
@looeee I've massively simplified the demo. Only using one part of the model to reduce geometries and have swapped out the material for `MeshNormalMaterial`. I think this makes sense anyway as the performance gain is really only a CPU one so it's good to keep the GPU part simple. Also the default setting is now just one row of dancers.

It now works on mobile but interestingly I can't see any performance gains at all between having the skeleton shared or duplicated. I'm guessing the bottleneck for most mobile devices is still on the GPU so we don't see any gains. I guess finding a model with the same number of bones but a simpler mesh would be a good way to test this theory.

**Comment by FlorentMasson** [comment]
Thanks, this example was really useful and should be merged 😉

**Comment by jpweeks** [comment]
I've found the use of `detached` mode to be pretty confusing and needing an example like this.

**Comment by Mugen87** [comment]
Closing in favor of #26995.

**Pull request closed without merging**
