### PR TITLE
Update unit command to search in unit/build folder

### PR DESCRIPTION
**Pull request by gero3**
Running the unit tests on my machine takes upwards of 3 minutes while on the Ci build it takes only 15 seconds.

### To Reproduce:
- Start from fresh install of three.js
- run 'npm install'
- run 'npm install --prefix test'
- run 'npm run test-unit'

### Issue
- Running the command 'npm install --prefix test' creates a node_modules folder which contains a symbolic folder link to the three.js workspace. When qunit starts looking for files to unit test, It also starts running in the node_modules which contains the three.js workspace because it doesn't understand recursive symbolic links. 

### Solution 
- ~~Run the qunit command as close to the file it needs to test.~~ (This doesn't work because of differences in windows and Unix. [Example](https://github.com/mrdoob/three.js/runs/740448941#step:6:52)) 
- Remove the symbolic link to the three.js workspace.

### CODE REVIEW

**Comment by mrdoob** [comment]
@munrocket looks good to you?

**Review by munrocket — COMMENTED** [review]
Never thought about this, looks good but we need to add rimraf into /test/package.json devDependencies in this PR.

**Comment by gero3** [comment]
I've added rimraf to the package.json.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
