### PR TITLE
get rid of syntax errors in console

### PR DESCRIPTION
**Pull request by makc**
see http://stackoverflow.com/a/7375676/2207790

### CODE REVIEW

**Comment by makc** [comment]
the other post somewhere said that's because firefox tries to create responseXML and fails, which is normal for non-xml files that 3js loads. but having these bogus errors in console is annoying, hope this commit puts an end to it.

**Comment by mrdoob** [comment]
What errors were you getting?

**Comment by makc** [comment]
same as in the stackoverflow post above, in the 1st line of loaded model:
screen shot 2015-11-07 at 22 41 08
or
screen shot 2015-11-07 at 22 42 03

**Comment by mrdoob** [comment]
Oh, I see.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
