### PR TITLE
Distanced based fog

### PR DESCRIPTION
**Pull request by greggman**
#14601

I should warn you, at least in my tests while it does seem to work it's different and lots of projects using fog will probably need to tweak their fog settings.

### CODE REVIEW

**Comment by mrdoob** [comment]
I bet. Curious to try with the examples.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Well, my curiosity has been satisfied. The first example is broken already 😁
https://rawgit.com/mrdoob/three.js/dev/examples/#webgl_animation_cloth

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/issues/14601#issuecomment-409791978

**Pull request merged**
