### PR TITLE
Examples: Add `viewportSafeUV` in `webgpu_backdrop`

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/29025

**Description**

Improve the example and add good practices.

### CODE REVIEW

**Comment by wcandillon** [comment]
@sunag when using this new node, I am getting the following validation error:
```
Validation: Source [Texture (unlabeled 393x754 px, TextureFormat::Depth24Plus)] sample count (4) and destination [Texture (unlabeled 393x754 px, TextureFormat::Depth24Plus)] sample count (1) does not match.
```
Any chance you could help find the underlying API call and maybe root cause of the issue? I would love to debug this further.

**Comment by wcandillon** [comment]
The issue might be on our side but I am wondering if you could set me in the right direction

**Comment by sunag** [comment]
WebGPU needs specific methods to deal with sampled textures and this has not been implemented yet, `{ antialias: false }` will help solve these issues until we improve this support.

**Comment by wcandillon** [comment]
thank you for providing this context, appreciate it :)

**Pull request merged**
