### PR TITLE
Make WebGLRenderer.setViewport(), setScissor() relative to lower-left corner

### LINKED ISSUE #12210: WebGLRenderer .setViewport() and .setScissor() inverted coordinates
##### Description of the problem 

I've a rather complex application which looks not properly working after the commit 43ae8e4ef86bb11ce3c46dbe1e3e17f2a26f82bd. I see different issues because of such commit but the simplest to describe is that the geometry looks shifted few pixels up in the y direction. I've recently updated my three release from 83 to 87 and after a quite painful bisection I've found that my application gets broken after the reported commit (message: "WebGLRenderer: Added y swap to setViewport() and setScissor()." made on 8 Jun 2017) . It's possible (I'd say it's almost sure) that the commit is correct and I simply need to update something on my side, but I don't fully understand what such commit does and why such change has been pushed. Could someone explain me the reasons behind it?

thanks in advance

Dav

##### Three.js version

- [ x] r86

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #12210.

When specifying the viewport and the scissor box, (x, y) is the coordinate of the lower left corner of the rectangular region.

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/viewport

### CODE REVIEW

**Comment by WestLangley** [comment]
Now, `.setViewport()` follows the webGL convention, so the viewport transform, which converts from NDC space to window space, is correct when applied to NDC coordinates.

Also, .setViewport() now follows the same convention as `WebGLTarget.viewport.set().

---

Aside: `.getCurrentViewport()` should correctly return the viewport previously set by `.setViewport()`. If it doesn't, that is a separate issue, unrelated to this PR.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Yeah, I also think it's better to stick to the WebGL conventions.

**Comment by Mugen87** [comment]
I'm fine with this change 😇

**Comment by mrdoob** [comment]
Thanks! 😅

**Pull request merged**
