### PR TITLE
Make screenshot on Windows

### PR DESCRIPTION
**Pull request by ycw**
Related issue: #28296

### CODE REVIEW

**Comment by Mugen87** [comment]
As expected the tests fail, sometimes with very large diffs. Since the examples have not been changed visually, the diff must be related to `setAnimationLoop()`. I suspect the usage of `setAnimationLoop()` is maybe not 100% deterministic. The fix for that does maybe not work anymore, see https://github.com/mrdoob/three.js/blob/dev/test/e2e/deterministic-injection.js.

**Comment by sunag** [comment]
The message I received seems more familiar as if there isn't a device with a GPU attached on the hardware side? 
`Error creating WebGL context., another attempt`

At another time, the `webgpu` examples also crashed with the same errors, which wouldn't justify `setAnimationLoop()` since these examples were not changed until this problem occurred?

**Comment by Mugen87** [comment]
@ycw Thanks for filing the PR and confirming the failure!

**Comment by ycw** [comment]
my pleasure

**Pull request closed without merging**
