### PR TITLE
Module worker support in OBJLoader2Parallel and webgl_loader_obj2_options example

### PR DESCRIPTION
**Pull request by kaisalmen**
Fixed module worker support in `OBJLoader2Parallel` and `WorkerExecutionSupport`.  Bumped internal versions to 3.2.0.

This was already available for quite some time, but not visible in an example and I broke it in between without noticing it first. Now `webgl_loader_obj2_options.html` allows to select "module workers" to be used before loading starts.

Module Workers are supported on Chromium (80+). Firefox does not support module workers, yet.

### CODE REVIEW

**Comment by kaisalmen** [comment]
Btw, the above example check must fail, because the models are now only loaded after pressing run in DAT menu which renders this check somewhat useless.

**Comment by mrdoob** [comment]
> Btw, the travis example check must fail, because the models are now only loaded after pressing run in DAT menu which renders this check somewhat useless.
Is there a way to make the image tests call a function?

/ping @munrocket

**Comment by munrocket** [comment]
Looks posible. You can make an exception and new screenshot for it.

**Comment by munrocket** [comment]
@kaisalmen I checked your commit by hand. And I was surprised that I need to press some button in order to see .obj modles. It's look little bit wierd for me. But! You can add `id='startbutton'` in dat.gui and Travis will press that button and wait for loading automatically.

**Comment by kaisalmen** [comment]
Thanks @munrocket, id added the id to the `run` button. Yes, pressing a button is unusual, but I want users to give the choice to be able to test both worker implementations (module & legacy) in one examples.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
