### PR TITLE
Math: Less mormalization error in Quaternion.slerp.

### PR DESCRIPTION
**Pull request by tschw**
Currently `.slerp` produces a high normalization error (at least on glibc/Linux) that stems from the `acos` function. Changing it to use `atan2` (a more frequently used function) yields an error within the range of one epsilon. It also appears to be faster, but I didn't measure it thoroughly enough to guarantee that.

Based on the `Animation` branch, since it introduces the unit test that revealed the problem.

### CODE REVIEW

**Comment by WestLangley** [comment]
Interesting... I wonder if our other uses of `acos` are problematic?

Also, what does the "Flat" in "slerpFlat" refer to?

**Comment by tschw** [comment]
> I wonder if our other uses of acos are problematic?

Where else do we use it?

Generally speaking, `atan2` is a good idea when having the corresponding sine around. Another noteworthy thing about trigonometric functions is that some implementations return a surprisingly high amount of error when the parameter needs to be wrapped around to N*Pi or unit range, so it's best not to rely on that behavior and instead keep the number of rotations down.

> Also, what does the "Flat" in "slerpFlat" refer to?

The data - flattened into arrays. The name was suggested by @bhouston in his review and appeared immediately obvious to me. There were no objections, so I happily picked it up.

See also
https://github.com/tschw/three.js/blob/49f50fb7384488acae8c425d3153577ad119780e/src/math/Quaternion.js#L527-L530

**Comment by WestLangley** [comment]
> I wonder if our other uses of acos are problematic?
>>Where else do we use it?

Outside of the examples, it is the Vector*, Quaternion, and a few other classes.

If there is a problem with the `acos` function under certain conditions, I would be interested in understanding the conditions you are referring to. Can you elaborate?

The only issue we have had so far is if the arg to `acos` is outside the domain of the function.

> Also, what does the "Flat" in "slerpFlat" refer to?
>> The data - flattened into arrays. 

I see. We have previously used the `fromArray` and `toArray` nomenclature when the args are arrays. Hmmm... in this case it is both...

**Comment by tschw** [comment]
> The only issue we have had so far is if the arg to acos is outside the domain of the function.

I was referring to this one in my previous post, and apparently you have met.

> If there is a problem with the acos function under certain conditions, I would be interested in understanding the conditions you are referring to. Can you elaborate?

I had to use a tolerance of 64 Eps to pass a test checking whether a quaternion stays at unit length after a (true, non-degenerate) slerp. The only difference compared to the flat implementation (passing the test with 1 Eps) along the control path in question was the use of `acos` instead of `atan2`.

So apparently `acos` produces less precise of a result. It's probably allowed to do so by some specification (I guess the precise numbers can be found in the IA32 spec) and  in itself not a problem. We just have to be careful when the error has a chance to stack up somewhere.

OT - other math stuff - but you seem to be the right address for it: I noticed that double Observer pattern in `Quaternion` and `Euler` calling back and forth for updating each other. I've been wondering whether it would be easier / cleaner to just have an `EulerView` that compares the quaternion against a copy to know whether it's in sync. I guess it would also be quite a bit faster - four values and comparisons vs. two closures and a function call + sync on absolutely any update of either of the two. Making sense?

**Comment by WestLangley** [comment]
> I was referring to this one in my previous post, and apparently you have met.

Sorry, I do not understand what you are saying in this sentence.

> in itself [acos is] not a problem.

OK, based on your discussion above, I will not pursue this further.

Aside: You likely have discovered this, but I'll state it for the record. By convention, three.js does not, in general, check arguments. So, for example, direction vectors are assumed to be of unit length, as are rotational axes. Quaternions are also assumed to be of unit length. So for `slerp()` to work correctly, the inputs must be of unit length. I am not sure if we check for unit quaternions when loading models. Maybe we should. Also, in the case of `slerp()`, I see it does not normalize its output, since in theory at least, normalization is not required -- and of course, doing so is extra computation.

---

> I've been wondering whether it would be easier / cleaner to just have an EulerView that compares the quaternion against a copy to know whether it's in sync.

Hehe. You are hijacking your own post. I gues you are allowed to do that. : - )

Yes, yes. It would be great if the `Euler/Quaternion` synchronization could be revisited. I am not sure how much of a computational load it induces, but there is clearly a lot of synchronization going on.

To express the issue another way, I like to say: "three.js is quaternion-based; Euler rotations are provided for user-convenience." So, in light of that view, yes, perhaps `object.rotation` could be lazily updated -- updated only when accessed. That is, allowed to get out-of-sync.

Comparing with a known value sounds like an efficient approach, in any event. And by that, I assume you mean that `rotation` keeps a copy of the last value of the `quaternion` it is synchronized to.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
