### PR TITLE
return XMLHttpRequest from load() methods that do not return anything else

### PR DESCRIPTION
**Pull request by makc**
Follow-up PR to #8091 I skipped some loaders where it was not obvious to me where to stick that return statement, and also things like XxxTextureLoader that already return textures from load() call.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, that's not very readable... Do you mind changing it to this pattern?

```javascript
loader.load( url, function( text ) {

	onLoad( scope.parse( text ) );
  
}, onProgress, onError );

return loader;
```

**Comment by makc** [comment]
`return loader` will not give you access to request

**Comment by mrdoob** [comment]
Oh, true... How about...

```javascript
var request = loader.load( url, function( text ) {

    onLoad( scope.parse( text ) );

}, onProgress, onError );

return request;
```

**Comment by makc** [comment]
Right, now I need to figure out how to mass-replace that.

**Comment by 0merta** [comment]
You may find this PR interesting. #9600 
It allows you to abort all active requests using the LoadingManager.
To abort a single request we may store the current request inside every Loader.

**Comment by makc** [comment]
> This branch has conflicts

too late, closing.

**Pull request closed without merging**
