### PR TITLE
Easier getting started 

### PR DESCRIPTION
**Pull request by svenefftinge**
This PR adds a small config for gitpod, a free for open-source service. We've developed it to provide dev environments with a single click. 

I have made the configuration so that
 - `npm install` and
 - `npm start`

are executed and when the dev server serves on port 8080, the root is opened in the preview.

I think it is useful for both three.js users and contributors to play around with the examples, create PRs or provide reproducibles. Note, that you can start workspace from any GitHub context (issues, files, branches and PRs) by prefixing the github URL with `gitpod.io/#` or install the browser extension. It will open a fresh dev environment with the right git state checked out. The three.js repo is quite large which makes the starting time a bit longer than usual.

Screenshot 2019-06-02 at 14 47 01

Let me know if you think this could be useful for your community and if I should change anything (e.g. I wasn't sure where to put the Open in Gitpod button). ❤️

### CODE REVIEW

**Comment by svenefftinge** [comment]
Btw. you can review this PR in gitpod as well, just prefix the URL:

https://gitpod.io/#https://github.com/mrdoob/three.js/pull/16653

**Comment by mrdoob** [comment]
Adding this to the readme looks like a advertising move to me.

It may be interesting to add a page in the docs with all the options though (glitch, jstiddle, codesandbox, etc)

Also, we gave enough dot files pollution in the root already.

**Comment by svenefftinge** [comment]
> Adding this to the readme looks like a advertising move to me.

Yes, of course I'm trying to make people aware of Gitpod (we are a young bootstrapped startup). But if it's not considered useful it should not be added.

> Also, we gave enough dot files pollution in the root already.

Fair enough, I have added the config [here](https://github.com/gitpod-io/definitely-gp/blob/master/three.js/.gitpod.yml), so it will be picked up by anyone using gitpod on your repo.

Feel free to reach out in future in case you reconsider and need help.

**Comment by looeee** [comment]
Adding some links to starter projects in Codepen, jsFiddle, gitpod, glitch.io, codesandbox.io, stackblitz, and any others that people know of, either in the **Getting Started** doc or even a new **Quick Start** page would be useful though.

**Pull request closed without merging**
