### PR TITLE
WebGLCapabilities: Use mediump by default

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

This PR is just to see what would break if we used mediump by default and also to test if there are any performance improvements.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/mrdoob/three.js/mediump/examples/index.html

**Comment by marcofugaro** [comment]
Hmm, wonder what's the discussion that led to this test

**Comment by Mugen87** [comment]
Some context: #14570

**Comment by mrdoob** [comment]
On Pixel 4a...

https://threejs.org/examples/webgl_materials_variations_physical.html (8fps)
https://raw.githack.com/mrdoob/three.js/mediump/examples/webgl_materials_variations_physical.html (14fps)

https://threejs.org/examples/webgl_materials_physical_clearcoat.html (25fps)
https://raw.githack.com/mrdoob/three.js/mediump/examples/webgl_materials_physical_clearcoat.html (42fps)

**Comment by Mugen87** [comment]
There seems to be artifacts with certain demos. E.g. 

https://raw.githack.com/mrdoob/three.js/mediump/examples/webgl_lights_rectarealight.html
https://threejs.org/examples/webgl_lights_rectarealight

Probably because of https://github.com/mrdoob/three.js/issues/14570#issuecomment-408577795.

**Comment by Mugen87** [comment]
There are missing hot spots with the marching cubes example.

https://raw.githack.com/mrdoob/three.js/mediump/examples/webgl_marchingcubes.html

image

https://threejs.org/examples/webgl_marchingcubes

image

**Pull request closed without merging**
