### PR TITLE
CurveModifier: Switch to half float.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: https://github.com/mrdoob/three.js/pull/28375#issuecomment-2109759121

**Description**

Switching to a half float texture in `CurveModifier` for better compatibility.

### CODE REVIEW

**Comment by Mugen87** [comment]
@manthrax Does half float work in your app as well?

**Comment by Mugen87** [comment]
Testing: 

https://rawcdn.githack.com/Mugen87/three.js/dev78/examples/webgl_modifier_curve.html
https://rawcdn.githack.com/Mugen87/three.js/dev78/examples/webgl_modifier_curve_instanced.html

**Comment by manthrax** [comment]
It looks fine to me on that text example..

I also checked it in my more complex example and didn't see any visual difference, so, LGTM? :D

**Comment by Mugen87** [comment]
Thanks for testing! 

The change to half float is also a performance improvement since it save memory and bandwidth (which is especially important for mobile).

**Pull request merged**
