### PR TITLE
Editor: Added CubeMap support for Scene.background.

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces `UICubeTexture` which can be used to configure the scene's background with a cube texture.

Similar to a textured background, it's not yet possible to save/reload this setting.

Related: #13880

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev19/editor/index.html

**Comment by Mugen87** [comment]
@mrdoob Well, implementing `UICubeTexture` was not that easy^^. The current code tries to save as much UI space as possible by using a `select` element in order to select the single sides of the cube texture for configuration.

**Comment by mrdoob** [comment]
> @mrdoob Well, implementing `UICubeTexture` was not that easy^^. The current code tries to save as much UI space as possible by using a `select` element in order to select the single sides of the cube texture for configuration. I'm open for better, more user-friendly approaches 😇 

It's a tricky one! How about this UI?

```
PX: [   ]
PY: [   ]
PZ: [   ]
NX: [   ]
NY: [   ]
NZ: [   ]
```

**Comment by Mugen87** [comment]
```
PX: [   ]
PY: [   ]
PZ: [   ]
NX: [   ]
NY: [   ]
NZ: [   ]
```
I've tried this one first but noticed that a lot of space gets lost since the background configuration is always visible when the `SCENE` tab is active.
```js
P: [   ] [   ] [   ]
N: [   ] [   ] [   ]
```
I've not though of that option so far^^. I like it because we can save space and get rid of the select element. Let me give this a try.

**Comment by Mugen87** [comment]
BTW: My actual goal is to fully support background/ environment maps so we can reproduce examples like the basic glTF (hemlet)  demo in the editor. Against this backdrop, a new `ENVIRONMENT MAPS` section in the `PROJECT` tab similar to `MATERIALS` could be useful. It would allow the users to globally define environment maps and then apply them to the background and to `Material.envMap`. What do you think.

In any case we need `UICubeTexture`. But a little road map could help to clarify the development targets^^.

**Comment by Mugen87** [comment]
Looks much better now:

image

**Comment by mrdoob** [comment]
> BTW: My actual goal is to fully support background/ environment maps so we can reproduce examples like the basic glTF (hemlet)  demo in the editor. Against this backdrop, a new `ENVIRONMENT MAPS` section in the `PROJECT` tab similar to `MATERIALS` could be useful. It would allow the users to globally define environment maps and then apply them to the background and to `Material.envMap`. What do you think? 

Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
