### PR TITLE
Moved doc's menu related CSS and JS into seperate files

### PR DESCRIPTION
**Pull request by looeee**
Created files menu.css and menu.js that contain the CSS and js that was inline in the index.html file.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, I'm not sure about this one...

**Comment by looeee** [comment]
@mrdoob no problem if you don't like it. Is there a reason for it all to be inline though? It's a bit of a mess in there...

**Comment by looeee** [comment]
@mrdoob slightly off topic but when is the next release due? There are couple of things I'd like to finish in the docs beforehand if possible...

**Comment by mrdoob** [comment]
I usually aim for the 15th 😅

**Comment by looeee** [comment]
o_0 I'd better get to work! Actually it's mainly just going over the docs for lights, everything else can wait.

**Comment by mrdoob** [comment]
Ah! If it's docs stuff I can easily cherry-pick stuff post-release.

**Pull request closed without merging**
