### PR TITLE
Add typings for `stats.module.js`.

### PR DESCRIPTION
**Pull request by lgarron**

### CODE REVIEW

**Comment by Mugen87** [comment]
Please have a look at #17530. We decided there to not add TS declaration files for libs.

**Comment by lgarron** [comment]
Ah, I didn't realize the lib came from an external project. Thanks for the info!

**Comment by mrdoob** [comment]
Well, considering it's the second try...

**Comment by mrdoob** [comment]
Thanks!

**Comment by yehuozhili** [comment]
this typings might has some error . because it can't  been  new . lacks a construct signature

**Comment by lgarron** [comment]
> this typings might has some error . because it can't been new . lacks a construct signature

That's because `Stats` doesn't have a class constructor in the implementation:

https://github.com/lgarron/three.js/blob/c94098295f634599ed510e27792c5e2b618c6b7b/examples/jsm/libs/stats.module.js#L5

The direct way to construct it is to call `Stats(...)` directly (no `new`).

**Comment by yehuozhili** [comment]
thanks ; its my fault ;  i saw some learning materials use it with new ;

**Pull request merged**
