### PR TITLE
Update issue template with correct arguments to OrbitControls

### PR DESCRIPTION
**Pull request by EliasHasle**
...in jsfiddles, that is.

https://discourse.threejs.org/t/jsfiddle-templates-should-supply-renderer-domelement-to-orbitcontrols/9267/11

#17612

### CODE REVIEW

**Comment by looeee** [comment]
We should probably update them to use buffer geometry as well.

**Comment by EliasHasle** [comment]
Ah, I didn't know the issue template fiddles were different. I will have to adapt the current ones instead, then.

**Comment by EliasHasle** [comment]
I was going to update the new fiddles from the old, but now the old fails with syntax error on `*` (presumably `import *`). 😕

**Comment by EliasHasle** [comment]
Anyway, it may be inconvenient/uncomfortable that I own the official fiddles. An alternative surely is that the owner of the official fiddles updates them to pass `renderer.domElement` after `camera`.

**Comment by looeee** [comment]
> Ah, I didn't know the issue template fiddles were different. 

This isn't intentional. The issue templates were updated sometime in the last month and the forum templates got left behind.

**Comment by Mugen87** [comment]
Solved via https://github.com/mrdoob/three.js/commit/35eaaa18bd5fae9033bdac30a857a281122c9536

**Pull request closed without merging**
