### PR TITLE
EffectComposer2

### PR DESCRIPTION
**Pull request by Oletus**
EffectComposer2 is a successor to the post-processing stack EffectComposer. Its advantages are:

1. A simpler but more flexible Pass API. Passes specify a list of input and output buffers that they need instead of having "readBuffer" and "writeBuffer" passed in. It's intended that in the future buffers handled by EffectComposer2 can contain depth, normal etc. information in addition to color information. There's no more "renderToScreen" flag for each pass - instead the final color render target for EffectComposer2 gets passed to the render() function.

2. Common functionality is shared between render passes.

The API for the passes has changed so that passes written against EffectComposer are not compatible with EffectComposer2, so this is added alongside the old EffectComposer instead of replacing it. However, the outward-facing API is mostly the same with the exception of removal of the "renderToScreen" flag.

### CODE REVIEW

**Comment by donutcoffee** [comment]
I like how you've removed the confusing "readBuffer" and "writeBuffer" from EffectComposer.

I also like that you've sort of added the ability to pass a camera to fillQuad (renderWithClear) e.g. in ShaderPass. There still is a problem with that that it breaks use of Layers just like the original postprocessing.

Would you consider passing a camera to ShaderPass, just like any other pass?
`THREE.ShaderPass2 = function ( shader, textureID, camera ) {`
then at line 63:
`THREE.Pass2.renderWithClear( renderer, this.fillQuad.scene, this.camera || this.fillQuad.camera, writeBuffer, this.colorWriteBufferConfig.clear );`

fillQuad.camera could be renamed to fillQuad.defaultCamera for clarity.

I can't quite comment on the rest at this time - it's been a while too since you submitted this. Are you still working on this?

**Comment by Oletus** [comment]
I'm not actively working on this right now. Some of the smaller enhancements were merged to the existing EffectComposer in PRs #15976 and #16033 . It would still be nice to create an upgraded version of EffectComposer that would get rid of the confusing usage of "readBuffer", but this is a tricky change to make since all the postprocessing passes need to be upgraded, and this change didn't seem to create much interest back when I started on it. Maybe we could make further small changes while keeping things backward compatible like renaming the parameters so that the names would be more intuitive.

**Comment by Oletus** [comment]
I'm not quite sure what you refer to when you talk about problems with layers. Applying regular camera layers doesn't make sense when a postprocessing pass is filling the screen with a single quad, and as far as I know when some passes perform scene rendering with an override material regular camera layers are being applied like they should.

**Comment by donutcoffee** [comment]
> 
> 
> I'm not quite sure what you refer to when you talk about problems with layers. Applying regular camera layers doesn't make sense when a postprocessing pass is filling the screen with a single quad, and as far as I know when some passes perform scene rendering with an override material regular camera layers are being applied like they should.

I have a project where I need to turn groups of objects and some postprocessing elements off at times. Using Layers is a good way to do that, by design. I guess Pass.enable could be used, but in my experience that leads to unexpected results due to buffers not being swapped when they need to etc.

The Layers of the fillQuad is easily set as it's a public property already. Camera used to be hidden.

I agree it's an uncommon case, and it could be seen as a workaround the real problem which is that Pass.enable is tricky to use. :)

**Comment by DavidPeicho** [comment]
With MRT now in the core, I think this should be revisted again. We also need some pooling for render targets

**Comment by DavidPeicho** [comment]
I don't use the EffectComposer a lot (I in general use a custom one). I wrote a course though and I wanted the students to be able to use post-processing easily. I actually discovered that a lot of post-process weren't following the same API.

Some post-process don't handle the resizing correctly, example with the [Bokeh Pass](https://github.com/mrdoob/three.js/blob/master/examples/jsm/postprocessing/BokehPass.js).

Should we give a try to an improvement to the effect composer? Or should we track down the effect that aren't following conventions?

**Comment by Mugen87** [comment]
> Or should we track down the effect that aren't following conventions?

I would start with that since we easier have results. Discussing a new API for post processing is a bigger thing.

**Comment by DavidPeicho** [comment]
I can give a show to fixing some of the post-process. Not the same issue, but I still think we need to add an API to re-use / share the render targets

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/12115#issuecomment-2429240760.

**Pull request closed without merging**
