### PR TITLE
set material.skinning in ObjectLoader for skinned meshes

### PR DESCRIPTION
**Pull request by aardgoose**
set material.skinning to silence SkinnedMesh warning

### CODE REVIEW

**Comment by mrdoob** [comment]
This feels patchy. Where is the json coming from?

**Comment by aardgoose** [comment]
From examples/models/skinned/marine/marine_anims_core.json as seen in animation / skinning / blending

**Comment by aardgoose** [comment]
ok, fixed model (and deleted some trailing whitespace)

How should arrays of materials passed to SkinnedMesh behave, now MultiMaterial is deprecated?
The warning message checks for .skinning = true? Should all materials in an array be checked for skinning = true, or the warning not emitted for arrays of materials. Adding skinning = true to an array seems 'patchy' as you would say.

**Comment by mrdoob** [comment]
> The warning message checks for .skinning = true? 

I removed the check https://github.com/mrdoob/three.js/commit/ec3a86668019835bbb4b729381f0dc5509417ea5

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
