### PR TITLE
ObjectLoader: Import geometries directly.

### PR DESCRIPTION
**Pull request by mrdoob**
This should allow geometries to be tree-shacked?

See https://github.com/mrdoob/three.js/issues/19986#issuecomment-684940548.

### CODE REVIEW

**Comment by donmccurdy** [comment]
No objection to this change, but I don't think it affects #19986 – the geometries will still be in the bundle until ObjectLoader can itself be tree-shaken. Presumably that requires converting ObjectLoader to as ES6 Class, which brings us back to https://github.com/mrdoob/three.js/issues/19986#issuecomment-683326381.

**Comment by mrdoob** [comment]
Ah, because `Loader` needs to be converted to a class in order to convert `ObjectLoader` to a class. Right?

**Comment by marcofugaro** [comment]
Yeah, sorry my bad @mrdoob, I corrected my comment after. `ObjectLoader` Just needs to be converted to a class, as @donmccurdy said.

**Comment by donmccurdy** [comment]
Hm... I think we'd confirmed that prototype "classes" can't _be extended by_ ES6 classes. But the other way around actually seems to work fine here, @Mugen87 do you know if there's anything wrong with having an ES6 class extend a prototype class? In that case maybe we could convert ObjectLoader to an ES6 Class now.

**Comment by mrdoob** [comment]
Second try. #20240

**Comment by Mugen87** [comment]
> do you know if there's anything wrong with having an ES6 class extend a prototype class?

Not that I'm aware of^^.

**Pull request closed without merging**
