### PR TITLE
Added object-space normal map example

### PR DESCRIPTION
**Pull request by WestLangley**
As discussed in #14139.

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral live link: https://rawgit.com/westlangley/three.js/dev-nefertiti/examples/webgl_materials_normalmap_object_space.html

**Comment by mrdoob** [comment]
Any chance the model could be converted to .glb?

**Comment by WestLangley** [comment]
>Any chance the model could be converted to .glb?

I'll defer to @donmccurdy on that one.

Note that gtTF does not support object-space normal maps at this time, so this model has been modified. A comment to that effect is included in the example.

**Comment by donmccurdy** [comment]
Here is a GLB version, created with http://glb-packer.glitch.me/. There are some validation warnings, but they're also present in the original.

[Nefertiti.glb.zip](https://github.com/mrdoob/three.js/files/2243743/Nefertiti.glb.zip)

@mlimper are you using this feature somewhere already? If you want to suggest a (strawman) extension name like `FRAUNHOFER_object_space_normal_map` we can add that to the model and prevent it from being loaded incorrectly elsewhere by accident.

**Comment by mlimper** [comment]
> @mlimper are you using this feature somewhere already? If you want to suggest a (strawman) extension name like FRAUNHOFER_object_space_normal_map we can add that to the model and prevent it from being loaded incorrectly elsewhere by accident.

Right now we are only using this in our HTML5 export, which is a BabylonJS viewer and a glTF file.
What we do there is add a flag to "extras" and interpret it in the JS code of the viewer to tell Babylon how to interpret the normal map:

```
(...)
"materials": [
  {
      "normalTexture": {
        "extras": {
          "objectSpaceNormals": true
        },
        "index": 0
      },
     (...)
  }
]
(...)
```

This is kind of hack is supposed to only be used within our HTML export, so we didn't add an extension yet. If some engine would just load this file as-is, not knowing about the "extras", it would display the normals in a wrong way (interpreting them as the standard tangent-space normal map). I guess a cleaner way would probably be to move the "normalTexture" into an "extensions" object of the material instead?

Unfortunately I don't have the bandwidth right now to propose a proper extension, that would have to be after SIGGRAPH, but if someone wants to start already we wouldn't mind (there doesn't necessarily have to be a FRAUNHOFER_... extension, maybe we could check with other glTF folks and directly propose an EXT_... one?)

**Comment by donmccurdy** [comment]
> If some engine would just load this file as-is, not knowing about the "extras", it would display the normals in a wrong way (interpreting them as the standard tangent-space normal map). I guess a cleaner way would probably be to move the "normalTexture" into an "extensions" object of the material instead?

I'm really looking for a way to ensure this model will not pass validation checks. 😅 Putting a draft extension name, or even `TMP_not_a_real_extension`, in `extensionsRequired` would do so and prevent its being uploaded somewhere accidentally, and cause GLTFLoader to log a warning. I didn't mean to suggest writing a full specification for the extension unless you already wanted to, and I don't know one way or another whether there's interest yet for an EXT_ version. Generally I think we'd prefer to see extensions start as a vendor extension and gain community interest + feedback, rather than jumping straight to `EXT_` or `KHR_`. So as soon as there was even an issue opened suggesting a name for an object-space extension, I'd want to attach that extension name to this model just to have some hint for validation.

In any case this PR can move ahead — I would use the `.GLB` version attached above.

**Comment by donmccurdy** [comment]
@WestLangley the textures can be removed as well — they're embedded in a `.glb`.

**Comment by WestLangley** [comment]
@donmccurdy Got it! Thanks!

**Comment by mlimper** [comment]
> I'm really looking for a way to ensure this model will not pass validation checks. 😅 Putting a draft extension name, or even TMP_not_a_real_extension, in extensionsRequired would do so and prevent its being uploaded somewhere accidentally

That makes sense, I didn't think about this ;-)

**Review by donmccurdy — APPROVED** [review]

**Comment by WestLangley** [comment]
@mrdoob I think this can be merged.

**Comment by WestLangley** [comment]
I do not believe there are any more issue with this PR.

**Comment by mrdoob** [comment]
I think the example is great, but I'm unsure about the model. I'm not it does justice to the feature?

Maybe [this one](http://www.cultlab3d.de/index.php/helmet/) looks better? [This one](http://ten24.info/sample-scan/) is good, but I can't find the license...

Or maybe just a checkbox to enable/disable the normal map to see the difference?

**Comment by mrdoob** [comment]
Okay, lets merge it for now. We can improve it over time ✌️

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
