### PR TITLE
Blender exporter: Changed .offsets to .drawcalls.

### PR DESCRIPTION
**Pull request by tschw**
Seems to be missing in #6803.

### CODE REVIEW

**Comment by mrdoob** [comment]
We should also update `BufferGeometryLoader`.

https://github.com/mrdoob/three.js/blob/master/src/loaders/BufferGeometryLoader.js#L50-L56

**Comment by tschw** [comment]
An update to `BufferGeometryLoader` is contained in #6803.

**Comment by mrdoob** [comment]
Yes... But what I'm saying is that if we change `offsets` to `drawcalls` in the exporter(s) we also need to update the loader(s), while still supporting the old name `offsets`.

Also here:
https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L1074-L1078

**Comment by tschw** [comment]
Oh, I see: it has not been changed!  Been jumping to conclusions...

**Comment by dubejf** [comment]
Yeah, I decide to wait before changing the serialization format, but it's better to do it now!

@tschw In the loader, to support existing files, you'll need to do

```
	var offsets = json.data.drawcalls || json.data.offsets;
```

You'll also need to update the key in `toJSON` for `BufferGeometry.js`
```
data.data.offsets -> data.data.drawcalls
```

`CTMLoader` also as an `offsets` field but I don't thinks it's related.

I didn't check the `.py` generators for references to `offsets`.

@mrdoob Maybe the format version should be bumped to `4.5` ?

**Comment by dubejf** [comment]
Or maybe we want to wait for the introduction of `THREE.Drawcall` to change the json?

**Comment by tschw** [comment]
While we're at it. Oh wait, looks I should have created another branch.

**Comment by tschw** [comment]
OK, backward compatibility is in.

In fact we already changed the JSON format and symbolic constants already cause warnings.

Where can I read what you are up to in regard to `THREE.Drawcall`?

Quite obviously, multiple objects could share a single `BufferGeometry` if they could have distinct draw calls.

Some renderers have a concept of a "primtive set" as part of an object; an index buffer range associated with a material. In this case the model space (and the "object uniforms" - but there are no uniform buffers in WebGL) are also shared. It could be interesting to run less JS code when moving complex objects around.

Ultimately, there is the idea of a "Renderable"; that has n:1 relationships to everything it needs to be rendered: Geometry buffers, technique (material type in three.js), scene properties, object properties and material properties. Is "Drawcall" going be something like that?

**Comment by dubejf** [comment]
The idea for `THREE.Drawcall` was discussed in #6803, but it's not my fight!

Also, `InstancedBufferGeometry` stores instances per `drawcall`. It probably doesn't work with json import/export currently.

**Comment by benaadams** [comment]
> Also, InstancedBufferGeometry stores instances per drawcall. It probably doesn't work with json import/export currently.

You will currently have to create your own shaders and add extra attributes for Instancing, so I wouldn't worry :)

e.g. you want regular mesh data position of vertex etc for the model; however when you instance it you might want to repeat that mesh at 1000 different places, so you need an addition instanced position which acts as the adjustment to the vertex positions

Also is currently only available in dev so feel free to improve.

**Comment by tschw** [comment]
Thanks - thought it was rooted somewhere else. So it's supposed to be the "primitive set" kind-of thing.

Something like
```javascript
/**
 * @typedef {{
 *     elementCount: !number
 *     bufferOffset: ?number
 *     sceneGraphNode: !THREE.Object3D
 *     geometry: !THREE.IGeometry
 *     material: !THREE.Material
 * }}
 */
```
could directly go into the renderer, get counted, multiplied with a cost metric and sorted by the optimal criterion for each pass. Maybe IDs would be better instead of real object references...

**Comment by tschw** [comment]
I see the other `.offsets` -> `.drawcalls` branch has been merged. What about this one?

/ping @mrdoob

Want to keep it `.offsets` in the JSON? No problem. I separated the texture constants stuff into another branch (removed here, via force push).

I also found some leftover code that I removed:
```javascript
var offsetsArray = JSON.parse( JSON.stringify( offsets ) );
// [ ... then deep-copy it ]
```
Since it's awkward, you may want to consider tidying it, even when we close this one.

`BufferGeometryLoader` appears to have DOS line endings or something inconsistent...

**Comment by mrdoob** [comment]
Sorry for the delay.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
