### PR TITLE
Support multiple uv maps, lightMap, normalMap, and specularMap in ColladaLoader2

### PR DESCRIPTION
**Pull request by jbaicoianu**

### CODE REVIEW

**Comment by DavidPeicho** [comment]
It looks like you are only adding 1 extra UV maps, isn't it possible to support up to 4 UV maps?

**Comment by jbaicoianu** [comment]
@DavidPeicho yes you're right, and some assumptions are made - for example it's assuming that diffuse, normal, and specular all share the same uv map, and ambient uses the second map.  It could definitely be improved.  

Do you have any example Collada files with multiple UV maps used like this?  Most of the files we deal with follow the convention explained above, but I would love to make this work for more obscure uses as well.

**Comment by mrdoob** [comment]
@Mugen87 Was this implemented already?

**Comment by Mugen87** [comment]
No, not yet.

**Comment by Mugen87** [comment]
A `.dae` file that uses these maps would be useful.

@jbaicoianu Are you still interesting in implementing this? You would have to start with a fresh PR and targeting the file `examples/js/loaders/ColladaLoader.js` instead. (see #12212)

**Comment by jbaicoianu** [comment]
Definitely still interested yes, we've been using ColladaLoader2 with these mods in production for a few months now but it was right before a numbet of major changes, so I haven't done the work yet to remerge.  I'll take a crack at it next week.

 As far as example models, http://assets.metacade.com/metacade/flynns-v5/flynns-exterior.dae is an example of a model which uses all of these maps (diffuse + normal + specular on uv layer 1, aoMap on uv layer 2).  This same material setup is used by a lot of our users, any time they want to include baked lighting.

Live version with working materials is at https://www.metacade.com/

**Pull request closed without merging**
