### PR TITLE
KTX loader

### PR DESCRIPTION
**Pull request by amakaseev**
This is how compressed textures are supposed to be used:

best for **desktop**:
- BC1(DXT1) - opaque textures
- BC3(DXT5) - transparent textures with full alpha range

best for **iOS**:
- PVR2, PVR4 - opaque textures or alpha

best for **Android**:
- ETC1 - opaque textures
- ASTC_4x4, ASTC8x8 - transparent textures with full alpha range

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice clean up!

**Comment by mrdoob** [comment]
Thanks!

**Comment by TimvanScherpenzeel** [comment]
Hi @amakaseev,

I've been working on a project called [texture-compressor](https://github.com/TimvanScherpenzeel/texture-compressor) which is a CLI tool for texture compression using ASTC, ETC, PVRTC and S3TC in a KTX container.

KTXLoader.js is working fine with non-mipmapped files but I am running into issues with mipmapped KTX images. I first thought that it must be the encoders that are messing things up but they all appear to give valid output (astcenc, PVRTexToolCLI and crunch).

A working demo can be found here: https://timvanscherpenzeel.github.io/texture-compressor/. If necessary I can supply a JSFiddle with the specific issue. I've also created a ticket in my repo here with some of the error output: https://github.com/TimvanScherpenzeel/texture-compressor/issues/12.

Did you notice any issues regarding mipmapping? The files appear valid and the number of mipmap levels reported in the header are correct. Am I missing something?

Many thanks in advance,

Tim van Scherpenzeel

**Comment by amakaseev** [comment]
Hi @TimvanScherpenzeel,

Your ktx file has one mipmap level.
screen shot 2018-06-27 at 11 42 12

**Comment by TimvanScherpenzeel** [comment]
Thank you for your quick response!

Two questions:
- Is this from the folder `flippedY-mipmaps`? (https://github.com/TimvanScherpenzeel/texture-compressor/blob/master/docs/example/flippedY-mipmaps/example-dxt1.ktx)
- What tool are you using to visualise the KTX file?

I've updated https://timvanscherpenzeel.github.io/texture-compressor/ to use the flippedY-mipmaps version (showing the error). This reports the number of mipmap levels to be 9.

**Comment by amakaseev** [comment]
I've used [PVRTexTool](https://community.imgtec.com/developers/powervr/tools/pvrtextool/) for converting and seeing the result.

**Comment by TimvanScherpenzeel** [comment]
I am unfortunately unable to open BC / DXT on my Mac with PVRTexTool.
screen shot 2018-06-27 at 11 55 28

I was however able to open the ETC and PVRTC files and they both show 9 valid and correct mipmaps.
screen shot 2018-06-27 at 11 55 48
screen shot 2018-06-27 at 11 55 42

But when loading ETC1 using Browserstack on a `SAMSUNG GALAXY S9 PLUS` nothing is rendered and the following errors are thrown:
screen shot 2018-06-27 at 11 57 13

**Comment by amakaseev** [comment]
> I am unfortunately unable to open BC / DXT on my Mac with PVRTexTool.
BC / DXT work only on windows :(
I have use ktx file with astc compression and this work fine on android.
On ios i have use .pvr files

**Comment by TimvanScherpenzeel** [comment]
The regular versions work fine across all devices I tested (Windows, Mac, various Android devices and various iOS devices). I am just experiencing issues with the mipmapped versions.

To show you a bit better I've made two different pages:

Non-mipmapped version:
https://timvanscherpenzeel.github.io/texture-compressor/

Mipmapped version:
https://timvanscherpenzeel.github.io/texture-compressor/mipmap.html

**Comment by TimvanScherpenzeel** [comment]
Hi @amakaseev,

After a lot of confusion I found out that the mipmap-chain has to be mipmap complete (meaning down to 1x1 pixel). I had mine set to generate until 2x2 pixels.

You can try it out here: https://timvanscherpenzeel.github.io/texture-compressor/mipmap.html

My apologies for the confusion and many thanks for your help!

Tim

**Pull request merged**
