### PR TITLE
Math: Clean up for copy().

### PR DESCRIPTION
**Pull request by linbingquan**
**Description**

Make `Math.copy` simple.

### CODE REVIEW

**Comment by linbingquan** [comment]
This PR doesn't pass `npm  run test-unit`, I closed it.

**Comment by Mugen87** [comment]
Yeah, you have not assigned the parameter in the right order. Anyway, I think the code is okay as it is.

**Comment by linbingquan** [comment]
@Mugen87 Excuse me, Can you tell me why this PR can't pass the `test-unit`.

**Comment by linbingquan** [comment]
> you have not assigned the parameters in the right order.

I checked it a few times, but also I don't found the mistake. Please tell me how to correct it.

**Comment by Mugen87** [comment]
Let's keep the code as it is.

**Pull request closed without merging**
