### PR TITLE
Fix typings and documentation of LoadingManager

### PR DESCRIPTION
**Pull request by chemicstry**
Fixed incorrect type for `onProgress` callback.
Fixed incorrect documentation for `onLoad` and `onError`.
Added documentation for `onStart`.
Added parameter descriptions for other callbacks.

### CODE REVIEW

**Comment by Mugen87** [comment]
> Added parameter descriptions for other callbacks.

@mrdoob Just for clarification. Do we really want to introduce more JSDoc-like documentation in TS type declaration files? Users could expect at some point we do this in all files. I believe this would make doc maintenance even more complicated.

**Comment by mrdoob** [comment]
I don't know... What do you think @chemicstry?

**Comment by chemicstry** [comment]
I am really not sure. I was just developing in TS, noticed incorrect documentation in IDE and decided to fix it. Incorrect documentation is worse than none. If you want I can just remove all documentation from this file and leave only the type fix.

**Comment by mrdoob** [comment]
Well. We'll see what happens 😁

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
