### PR TITLE
Material: Fixed .normalScale serialization.

### LINKED ISSUE #7454: Serialization / Editor / App Player: What's wrong with normal mapping?
After importing a model with a normal map (`MeshPhongMaterial`), hitting Play yields a black screen.

What's [this strange comment](https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L159) all about? Just changes in the data model?

`.normalScale` apparently is a 2D vector: https://github.com/mrdoob/three.js/blob/dev/src/loaders/MaterialLoader.js#L100

### PR DESCRIPTION
**Pull request by tschw**
Serialize a scalar instead of nothing / NaN.

/fixes #7454

### CODE REVIEW

**Comment by WestLangley** [comment]
`Material.normalScale` is a `Vector2`. Reasonable values are [ 1, 1 ] or [ 1. - 1 ]. Usually, both components have the same absolute value.

I do no think length is what you want.

**Comment by tschw** [comment]
> Material.normalScale is a Vector2

It's a scalar in the JSON:

https://github.com/mrdoob/three.js/blob/dev/src/loaders/MaterialLoader.js#L100

(also exported as such).

I'm happy with length because it's not NaN ;-). But yes, I can extend this PR to write an array in `.toJSON` and check whether the type is array or scalar the loader.

**Comment by mrdoob** [comment]
Shouldn't just be `.toArray()`?

**Comment by WestLangley** [comment]
Yes. When importing, you have to be able to set the sign of the x- and y-components. I do not understand how a scalar in the JSON could possibly work.

**Comment by tschw** [comment]
Better?

**Comment by tschw** [comment]
Note that we can't just change the importer as it would break all the models out there that contain a scalar.

In Blender, there seems to be no way to have separate weights or inverted axes (thus I let the exporter write the uniform weight two times). Apparently X and Y axes can be flipped, but we'd need a 2x2 matrix to support that:

ui

**Comment by mrdoob** [comment]
Looks good!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Simplified it a bit 😊

**Pull request merged**
