### PR TITLE
Examples: Improve the slider in the wide gamut example

### PR DESCRIPTION
**Pull request by WestLangley**
Improved the look of the slider.

Also fixed bugs in the slider when resizing the window.

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral test link

this PR
https://raw.githack.com/westlangley/three.js/dev-wide_gamut/examples/webgl_test_wide_gamut.html

master
https://threejs.org/examples/webgl_test_wide_gamut.html

**Comment by WestLangley** [comment]
The updated screenshot is not correct...

**Comment by Mugen87** [comment]
The E2E testing for this particular example should be improved by updating https://github.com/mrdoob/three.js/blob/dev/test/e2e/clean-page.js. This script ensure to remove all HTML which overlays the renderer's canvas so the testing can focus on the renderer output.

**Comment by Mugen87** [comment]
It seems adding the `slider` and `label` class to the following line should be sufficient.

https://github.com/mrdoob/three.js/blob/2b5e50041cfbe7551b6b3f4bcfcf515a695d6b1a/test/e2e/clean-page.js#L12

**Comment by Mugen87** [comment]
webgl_test_wide_gamut

The above is the screenshot generated on my system so it's not a general issue.

Did you do a `npm i` before making the screenshot. Maybe you are using an outdated depdenencies?

**Comment by WestLangley** [comment]
I tried updating, but no luck... (I am on a mac, using homebrew.)

It appears the animation loop is rendering before the textures load.

**Comment by Mugen87** [comment]
Then let me update the screenshot after the merge so it's not blocking the PR.

**Comment by WestLangley** [comment]
OK. I reverted the screenshot update.

**Comment by Mugen87** [comment]
6b23527a059503e4e8cab4ac815eff12ab2f7b7f

**Pull request merged**
