### PR TITLE
Tga loader revert and set flip y

### PR DESCRIPTION
**Pull request by takahirox**
Refer to #8403 #8472 

Please merge this PR after merging #8519

### CODE REVIEW

**Comment by mrdoob** [comment]
How about changing `TGALoader` so it outputs a `<canvas>` instead?

**Comment by takahirox** [comment]
You mean, TGALoader outputs Texture with canvas instead of DataTexture with pixel data?
If so, I agree if we can. I was just thinking about it.
The design would be simpler.
I think the complexity of TGALoader comes from that it generates DataTexture.

**Comment by takahirox** [comment]
Texture with canvas would be better because for compatibility?

**Comment by mrdoob** [comment]
Texture with canvas sounds good :+1:

**Pull request closed without merging**
