### PR TITLE
Examples: Use PBR material in webxr_ar_lighting again.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This PR restores the PBR materials support of `XREstimatedLight` . I have some concerns though: 

The WebXR API returns an environment map which seems to be an irradiance environment map. I'm not sure but is this type of map the intended input of `PMREMGenerator`? 

Wouldn't it be more correct to transform the irradiance environment map to an instance of `LightProbe` (since we can't directly sample irradiance environment maps right now) and add it to the scene?

Besides, `XREstimatedLight` uses an instance of `LightProbe` and `DirectionalLight` for representing the estimated lighting. Does it make sense to add an instance of `XREstimatedLight` _and_ the irradiance environment map to the scene? Isn't the irradiance added twice now?

/cc @toji @elalish

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev19/examples/webxr_ar_lighting.html

**Comment by optimus007** [comment]
I can't see the blurry reflection in the sphere. Is this correct ?

**Comment by Mugen87** [comment]
> I can't see the blurry reflection in the sphere. Is this correct ?

Yes, the environment map from WebXR is currently only 16x16.

**Comment by optimus007** [comment]
Phong seems to showing some kind of blurry reflection which the standard does not. 


& There were no errors in the console
(Just some renderer.resize warnings)

Might be my phone .

**Comment by Mugen87** [comment]
> Phong seems to showing some kind of blurry reflection which the standard does not.

Like I said above I'm not sure if it is correct to process an irradiance environment map with `PMREMGenerator`.

**Comment by WestLangley** [comment]
>...an irradiance environment map. I'm not sure but is this type of map the intended input of PMREMGenerator?

No.

**Comment by Mugen87** [comment]
Good! Then I don't think the following line should be part of the example:
```js
scene.environment = xrLight.environment;
```
It's probably sufficient to just add the instance of `XREstimatedLight` to the scene.

**Comment by WestLangley** [comment]
>...an irradiance environment map. I'm not sure but is this type of map the intended input of PMREMGenerator?
>>No.

>Good! Then I don't think the following line should be part of the example:
>>scene.environment = xrLight.environment;

@Mugen87 I am not inclined to think `xrLight.environment` is an irradiance map.

I think `xrLight.environment` is a _radiance_ cube map of size 16px. (or more likely, a luminance map)

If so, that size is not compatible with PMREM.

/ping @toji
/ping @elalish

**Comment by Mugen87** [comment]
Unfortunately, the type of the map is not clear to me from the spec: https://www.w3.org/TR/2021/WD-webxr-lighting-estimation-1-20210909/

**Comment by toji** [comment]
Unfortunately the underlying APIs that we use to expose those values to the web aren't very clear about exactly what those values represent either, aside from being used for "reflections".

https://developers.google.com/ar/develop/c/lighting-estimation/introduction?hl=cs#hdr_cubemap
https://developers.google.cn/ar/reference/c/group/ar-light-estimate?hl=ur#arlightestimate_acquireenvironmentalhdrcubemap

https://developer.apple.com/documentation/arkit/camera_lighting_and_effects/adding_realistic_reflections_to_an_ar_experience
https://developer.apple.com/documentation/arkit/arenvironmentprobeanchor/2977511-environmenttexture

That said, despite the low resolution the intention of the textures is to give the impression of a plausible, if blurry, reflection of the user's environment in shiny surfaces. I would expect rendering using it to visually resemble the "Phong" screenshot that @optimus007 posted, whereas the "Standard" screenshot feels like it's not making use of it at all.

And yes, as far as I am aware they're not compatible with `PMREMGenerator`. I talked to @elalish about it at the time I was doing the initial implementation and we determined they wouldn't work as-is, but I forget if there was some sort of fundamental incompatibility there or if it was simply an implementation detail of `PMREMGenerator`.

**Comment by elalish** [comment]
I believe this PR is about how PMREM *can* finally be applied to the reflection map. I  think  our only concerns were pixel format and performance, which might both be solved now. @WestLangley As for size, agreed that it's not optimal, but `PMREMGenerator` should  work fine with any size input cubemap. This is probably a  good excuse to finally make the internal PMREM format adjustable size, but that's just an optimization. 

As for  radiance vs irradiance; I personally hate those words because I can never remember which one is which. But yes, `xrLight.environment` is estimated incoming light from the world, supposedly identical to an applied HDR map.

**Comment by elalish** [comment]
On another note;  that reflection map *really* shouldn't be 16x16; that's part of why ARCore's lighting estimation is so  bad. ARKit can return a much higher-res version, and if they ever ship  WebXR, this will likely not be  so small.

**Comment by Mugen87** [comment]
According to the guides the `xrLight.environment` is essentially a cube map generated with a cube camera. I think Unity calls this a reflection probe. In this case, we can indeed use the input for `MeshStandardMaterial.envMap`. Updated the PR accordingly.

**Comment by optimus007** [comment]
The euirectangular defaultHdri  seems to be converted into a cube map now

**Comment by Mugen87** [comment]
@optimus007 Should be fixed now.

**Comment by optimus007** [comment]
👍 

Environment from hdri 
&
Light from xrLight.lightProbe and xrLight.directionalLight 

Correct ?

**Comment by optimus007** [comment]
https://user-images.githubusercontent.com/6885294/148974621-a65dd230-b4d8-4d89-8bcb-598a8c62f800.mp4

The environment is not reflecting again.  No errors in the console

**Comment by Mugen87** [comment]
> The environment is not reflecting again. 

This is not an error but the result you get with `MeshStandardMaterial`. The environment map is definitely applied.

> The directional light should also be unnecessary.

It is part of `XREstimatedLight` and I'm not going to touch its composition in this PR.

I'm just trying to find a way how to use `XREstimatedLight` with PBR materials. If we can't agree on a solution, it's better to close this PR and just continue to use the phong material.

**Comment by optimus007** [comment]
https://user-images.githubusercontent.com/6885294/148988293-c3c26c64-0f22-44d9-9731-f6ccb111d5bd.mp4

Testing this pr in my webXR page. Looks great 👍, metallic objects don't appear black like before and the webgl warnings are gone. 🙌

The lack of blurry reflection can be solved in another update

Google's scene viewer uses the blurry reflection maybe someone who developed that can help

**Comment by WestLangley** [comment]
>As for radiance vs irradiance; I personally hate those words because I can never remember which one is which.

@elalish This is important. Do you understand that PMREM accounts for both the radiance _and_ the irradiance implied by the environment map?

See https://github.com/mrdoob/three.js/pull/22178#issuecomment-887950445 and https://github.com/mrdoob/three.js/pull/22178#issuecomment-889297668.

That means adding a radiance probe _and_ an irradiance probe is double-counting irradiance.

If you want to accommodate the modeling approach of ARCore, then you have to change how PMREM is implemented.

**Comment by mrdoob** [comment]
Regarding the fact that the reflection is blurred...
I suspect the issue is that the PMREM code is scaling down the 16x16 cubemap.

**Comment by WestLangley** [comment]
>I suspect the issue is that the PMREM code is scaling down the 16x16 cubemap.

Right. PMREM is not designed for a 16px input.

**Comment by mrdoob** [comment]
@elalish Should I merge this in the meantime?

**Comment by elalish** [comment]
Seems fine to me; it's certainly an improvement, though there's more work to do.

**Comment by mrdoob** [comment]
Thanks!

**Comment by elalish** [comment]
@Mugen87 @mrdoob I'm looking at making PMREM's internal CubeUV format have variable  size, depending on the  input texture  dimensions. I  think I've got it  worked out, but the part I'm struggling with is where  to communicate that size to  the shaders. Would you like it as a `#define` like `ENV_MAP_TYPE`, or as a uniform value like `toneMappingExposure`? Where should that value  be set?

**Comment by Mugen87** [comment]
Is it a valid use case to change the size of a single env map over time? I would expect no. I mean you might have maps of different sizes but once a size is defined it is static.

 If so, I think we should use a define.

**Comment by AdaRoseCannon** [comment]
I'm working on re-adding lighting estimation to AFrame, unfortunately it seems something odd is happening. I'm using `this.lightingEstimationTexture.needsPMREMUpdate = true;` after replacing the `__webglTexture` and that managed to get it partly working.

It seems that the way the texture is being used by the environment is peculiar. It seems to have most of the colour but none of the detail and an artifact that looks like a small thin vertical rectangle. I took a screen shot below, the left shows what the actual texture looks like, the right is how it looks on a material with 0 roughness. I took a look through the lighting estimation example and I don't think I am missing anything. 

Screenshot_20220125-104510_Samsung Internet Beta

**Comment by Mugen87** [comment]
@AdaRoseCannon #23322 should improve the reflections of `XREstimatedLight`'s env map. You might want to download the branch, update the build files and use them temporarily for testing.

**Comment by AdaRoseCannon** [comment]
Do you think the mismatched size of the env map is what's causing this issue?

**Comment by Mugen87** [comment]
At least the current `PMREMGenerator` does not properly handle 16x16 env maps. The PR is going to improve this situation.

**Pull request merged**
