### PR TITLE
Lazy UUID generation

### PR DESCRIPTION
**Pull request by takahirox**
See #12432

Maybe we need to clean up the code. Duplicated lazy `uuid` generation code across the classes.

@nkrisztian89 Would you please check if loading performance in your app will be improved with this PR?

### CODE REVIEW

**Comment by mrdoob** [comment]
Wow. I was not aware of how many places this would have to be changed. Hmm.. Yeah, lets just try to optimise the original function instead. Or even, move to a different format.

https://twitter.com/kchplr/status/921083967301996546

**Comment by takahirox** [comment]
Alright.

But I speculate it'll probably end up we need lazy generation for their use case because seems like 2-3x improvement isn't good enough. The function is based on String operation, further improvement would be difficult.

**Comment by mrdoob** [comment]
> But I speculate it'll probably end up we need lazy generation for their use case because seems like 2-3x improvement isn't good enough. The function is based on String operation, further improvement would be difficult.

Yeah... But I would prefer to not change too many things at once. Maybe replace `generateUUID` first?

**Review by zvonimirr — APPROVED** [review]

**Comment by mrdoob** [comment]
Closing this for now.

**Pull request closed without merging**
