### PR TITLE
CircleBufferGeometry: fix normals bug

### PR DESCRIPTION
**Pull request by WestLangley**
Normal was set incorrectly.

### CODE REVIEW

**Comment by mrdoob** [comment]
Are you sure? The generated circle is looking forward and not up.

**Comment by WestLangley** [comment]
The array is zero-based. `normals[ 2 ]` is the z-component.

**Comment by mrdoob** [comment]
Oh, true. I'm surprised we hadn't noticed until now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
