### PR TITLE
Nodes: rename state -> frame

### PR DESCRIPTION
**Pull request by aardgoose**
updateReference() takes a nodeFrame object, make this clear.

### CODE REVIEW

**Comment by sunag** [comment]
Hmm... I named `state` because `NodeBuilder` is also used as a parameter.

**Comment by aardgoose** [comment]
Other methods taking a nodeFrame are called frame eg PassNode..updateBefore( frame ) etc, so 'state' isn't consistent.

**Comment by sunag** [comment]
`state` sould be an `interface` like we using in C#/TypeScript, renome it for `frame` don't seems fix all the things.

**Comment by aardgoose** [comment]
Ah I missed the call in Node.

**Pull request closed without merging**
