### PR TITLE
Documented Box3.applyMatrix4 doesn't work on empty boxes.

### PR DESCRIPTION
**Pull request by tschw**

### CODE REVIEW

**Comment by tschw** [comment]
Also re-ran the tidying expressions on the boxes while still in my editor's history.

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
Shouldn't Box3.applyMatrix4 work on empty boxes?  It should just return an empty box with the extents set to the reversed [+inf, -inf] if possible.

**Comment by tschw** [comment]
@bhouston 
> Shouldn't Box3.applyMatrix4 work on empty boxes? It should just return an empty box with the extents set to the reversed [+inf, -inf] if possible.

Debatable. See https://github.com/mrdoob/three.js/issues/8620#issuecomment-209138026 .

But I won't bite if anyone decides otherwise and changes it.

**Comment by bhouston** [comment]
I do not think we should be generating NaN in Box3 for any valid use case.   Think of an empy box as a 0.  0 * x = 0.  x + 0 = x.  union( x, 0 ) = x.  I will PR a solution in a few moments.

**Pull request merged**
