### PR TITLE
Remove CanvasRenderer

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in https://github.com/mrdoob/three.js/issues/14581#issuecomment-428372629.

Please post below any canvas examples you would like ported to webgl.

### CODE REVIEW

**Comment by WestLangley** [comment]
`CanvasRenderer` was a remarkable achievement in the early days of this project. Thank you @mrdoob!

**Comment by looeee** [comment]
This is great, so many people post on the forum who have used this renderer by mistake.

**Comment by WestLangley** [comment]
@mrdoob Please let's do this before conflicts arise.

**Comment by WestLangley** [comment]
@mrdoob Is `material.overdraw` needed for any other renderer? If not, I will remove it.

**Comment by mrdoob** [comment]
I don't think so.

**Pull request merged**
