### PR TITLE
Add gammaFactor param for convertGammaToLinear & convertLinearToGamma

### PR DESCRIPTION
**Pull request by 06wj**
Add gammaFactor param for Color.convertGammaToLinear & Color.convertLinearToGamma

### CODE REVIEW

**Comment by WestLangley** [comment]
Would you mind updating the docs for all four methods?

**Comment by 06wj** [comment]
@WestLangley Thanks, I updated the doc.

**Comment by WestLangley** [comment]
@06wj Thank you.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
