### PR TITLE
blurred reflection in mirror example

### PR DESCRIPTION
**Pull request by makc**
This seems to be a popular request, e g it was asked enough times for r3f people to [backport their MeshReflectionMaterial to vanilla 3js](https://vis-prime.github.io/explore-vanilla-drei/?scene=MeshReflectionMaterial), so I thought why not patch Reflector to support it? This PR adds 3 params - blurX/Y and depthScale - and zero depthScale removes rendering overhead (makes Reflector performance same as now). Blur code is based on ShaderPass (I just copied it from some another example).

Screenshot 2023-04-15 at 04-18-22 three js webgl - mirror

[rawgithack](https://raw.githack.com/makc/three.js.fork/reflector-blur/examples/webgl_mirror.html) to try it live

### CODE REVIEW

**Comment by Mugen87** [comment]
I don't know why but the updated demo stutters on a mac Mini with M2 Pro. The unmodified mirror example runs at 60 FPS.

I would definitely not turn on blurring by default. How about adding a parameter that enables it when required so the new code path is completely optional?

**Comment by Mugen87** [comment]
It was also requested to add faded reflections to `Reflector`. But the more features we add the more things become harder to maintain. So I'm not sure about this feature request.

Besides, should `Refractor` support blurring, too?

**Comment by makc** [comment]
> How about adding a parameter that enables it when required so the new code path is completely optional?

that's what depthScale = 0 is [supposed to do](https://github.com/mrdoob/three.js/pull/25839/files#diff-e36a0647b482045a63413da9610733f12e127d4e678fabad69208b34f0946675R181). if it is still slow with that, Idk why 😔

**Comment by Mugen87** [comment]
Maybe you can also include a GLSL define that excludes the textures fetches when they are not necessary.

**Comment by makc** [comment]
so I tried a number of things, including if(...) and #ifdef in the shader, but nothing seemed to improve fps apart from limiting target resolution (since it is screen * pixel ratio in the example, I guess it just uses up gpu ram?) - pushed max 1024px blur/depth textures.

**Comment by Mugen87** [comment]
Sorry, but we can't merge the PR in this state. Every time I move the reflector in the camera view, performance goes down from 60 to 27 FPS on a M2 Pro. Feel free to reopen the PR (or open a different one) if blurring works without this kind of performance penalty.

**Pull request closed without merging**
