### PR TITLE
Examples: Added ACESFilmicTonemappingShader

### PR DESCRIPTION
**Pull request by WestLangley**
This is the approximation proposed by Stephen Hill. It is used by Babylon and PlayCanvas.

### CODE REVIEW

**Comment by looeee** [comment]
Thank you for adding this 👍 

Does this approximation give a better fit than [the one we are already using](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/tonemapping_pars_fragment.glsl.js#L46)? 

It will be interesting to see if the difference is at all noticeable. If it's not, then I would vote to just use the faster approximation everywhere.

**Comment by mrdoob** [comment]
Thanks!

**Comment by arpu** [comment]
how can i use test this?

**Comment by arpu** [comment]
@looeee  any idea how i can use the old ACESFilmicToneMapping shader or the new one ?

**Comment by looeee** [comment]
@arpu best to discuss this over on the forum.

**Pull request merged**
