### PR TITLE
make CameraHelper more customizable | choose colors | leave out sections if desired

### PR DESCRIPTION
**Pull request by Heaust-ops**
**Description**

Camera helper has too much going on,

If all that's needed is the info about the location and face direction of the camera,

the extra lines for the entire frustum of rendering is unneeded and gets in the way.

Same may be true vice-versa.

This PR makes the camera helper more customizable with extra arguments for the colors of the different parts of the helper.

Passing null instead of a color prevents that part of the helper from being rendered.

### CODE REVIEW

**Comment by Mugen87** [comment]
Is this a duplicate of #23829?

**Comment by Heaust-ops** [comment]
> Is this a duplicate of #23829?

I can't say for sure, the main intent was the ability to leave out certain sections of the helper, https://github.com/mrdoob/three.js/pull/23829 doesn't seem to do that.

**Comment by Heaust-ops** [comment]
for example if I don't wanna render the entire camera helper,
I can just do this,

```
new CameraHelper(camera, {colorFarFrustum: null, colorTarget: null});
```
and I'll only have the bits I want,
image

**Comment by Heaust-ops** [comment]
understandable, ty : )

**Comment by Mugen87** [comment]
Thanks for the PR but I think it's better if we focus on #23829, first.

**Pull request closed without merging**
