### PR TITLE
Added navigator existence check in WebGLRenderer

### PR DESCRIPTION
**Pull request by dukuo**
Useful for headless rendering, since `navigator` does not exists in a Node.JS environment. Checked main examples using webgl and everything works just fine. It's a very simple check!

### CODE REVIEW

**Review by Mugen87 — COMMENTED** [review]
Yeah, `three.js` has similar checks at other places.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
I think this code shows better the intention:

```js
var vr = null;

if ( typeof navigator !== 'undefined' ) {

    vr = ( 'xr' in navigator ) ? new WebXRManager( _this ) : new WebVRManager( _this );

}

this.vr = vr;
```

**Comment by dukuo** [comment]
true, will do.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
