### PR TITLE
adopt setFromMatrixColumn instead of manual lower-level functions.

### PR DESCRIPTION
**Pull request by bhouston**
Super minor change.  Just feel it is easier to work with high level functions like setFromMatrixColumn() rather than picking out the matrix element indices manually.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I'm considering changing `setFromMatrixColum( index, matrix )` to `setFromMatrixColum( matrix, index )` though. That was it follows `setFromArray( array, offset )`.

**Comment by bhouston** [comment]
I support that change.

**Comment by mrdoob** [comment]
Done!

**Pull request merged**
