### PR TITLE
Meta: Docs and Tests for DRACOLoader Update

### PR DESCRIPTION
**Pull request by epreston**
Related PR: #25475

**Description**

Update docs and add tests to support the updates to DRACOLoader.

Add DRACOLoader Tests
Update DRACOLoader docs.

### CODE REVIEW

**Comment by LeviPesin** [comment]
I think it was decided to remove all addons tests until all core classes are fully covered by them.

By the way, can we use import maps in tests?

**Comment by epreston** [comment]
Not sure.  There's some very unique views on tests and they don't get merged.  Such a waste.

No import maps.  You import the sources as the unit does to get clean tests or they will fail.

**Comment by LeviPesin** [comment]
Related: https://github.com/mrdoob/three.js/pull/23348 https://github.com/mrdoob/three.js/pull/23352

**Comment by LeviPesin** [comment]
> Notice in this one I am importing the way the unit does. loader imported from the source is a different object to loader imported as a three export. Change the commend and try the inheritance test to see it error out.

I think it should work if both are imported from `three`.

**Comment by epreston** [comment]
The javascript interpreter sees them as different objects.

**Comment by epreston** [comment]
Those comments on doing too much are interesting.  Instead of addressing where it is doing too much, people are removing what this thing is supposed to do.

**Comment by epreston** [comment]
I can help with that.  Can you merge in my batch of test updates and I will complete the rest for core ?

**Pull request closed without merging**
