### PR TITLE
Fix constant used in fresnel approximation

### PR DESCRIPTION
**Pull request by sirxemic**
Compare the Google results when searching for "fresnel 5.55473" and "fresnel 5.55437" :D

### CODE REVIEW

**Comment by mrdoob** [comment]
@tschw I think it was you that added this code?

**Comment by mrdoob** [comment]
Merging this...

**Comment by mrdoob** [comment]
Thanks!

**Comment by tschw** [comment]
Introduced in #7028. Thanks for the heads up.

It's obviously a typo as I got it right in the [graphs](http://fooplot.com/#W3sidHlwZSI6MCwiZXEiOiIyXigoLTUuNTU0NzMqeC02Ljk4MzE2KSp4KSIsImNvbG9yIjoiIzAwRkY0RCJ9LHsidHlwZSI6MCwiZXEiOiIoMS14KV41IiwiY29sb3IiOiIjMDBBRkZBIn0seyJ0eXBlIjowLCJlcSI6IjJeKC04LjU2NSp4KSIsImNvbG9yIjoiI0VEMDAwMCJ9LHsidHlwZSI6MTAwMCwid2luZG93IjpbIjAuMDE5MDE1MjI0MzYwODcyOTgiLCIwLjExNDkzODI5MzU0NDE2MjcxIiwiMC43Mjc5ODQ1MTg5ODY0ODk0IiwiMC43ODcwMTQxMDAwMjIzNTk3Il19XQ--) - sorry for that one. However, I doubt that it has caused any serious harm, as the error is much smaller than the deviance from Schlick's approximation which is already in the realm of the invisible. I guess we might as well go for `exp2( -8.565 * dotLH )`...

**Comment by mrdoob** [comment]
> I guess we might as well go for `exp2( -8.565 * dotLH )`...

Up to you 😊

**Pull request merged**
