### PR TITLE
PMREMGenerator: Add ability to set camera origin in fromScene

### PR DESCRIPTION
**Pull request by gkjohnson**
Related issue: --

**Description**

Add the ability to set the position that the scene is rendered from when using `PMREMGenerator.fromScene`. This is useful particularly when you have an environment with something like terrain but positioning the camera at the origin places the camera underneath the terrain when you would like to include in the map.

### CODE REVIEW

**Comment by Mugen87** [comment]
@elalish Thoughts on this? 😇

**Comment by elalish** [comment]
Seems reasonable to me. Of course you could also just move the scene, but setting the camera's position is more intuitive.

**Comment by gkjohnson** [comment]
> Of course you could also just move the scene

Like `scene.position.y -= 10`? It hadn't occurred to me to do that -- and the docs stating that the scene is rendered from the origin make it sound like that doesn't work (though I know it does). I think positioning the camera is much more intuitive, though.

**Comment by Mugen87** [comment]
> and the docs stating that the scene is rendered from the origin make it sound like that doesn't work (though I know it does).

The documentation states that "the cubeCamera is placed at the origin". To me, this does not imply that the scene can't be translated.

If you can accomplish your use requirement with the current API (meaning by translating the scene), I would not introduce an additional parameter to `PMREMGenerator.fromScene()`.

Also notice that it is the intention to completely integrate `PMREMGenerator` into the renderer. At some point, it might be possible to assign a scene to `Scene.environment` which then means the renderer internally calls `fromScene()`. Any additional parameter we introduce now will make it harder to achieve this goal.

**Comment by gkjohnson** [comment]
Sorry I've been meaning to reply to this.

> The documentation states that "the cubeCamera is placed at the origin". To me, this does not imply that the scene can't be translated.

I don't think it's fair to expect anyone to read "origin" as anything othe than the scene origin. My understanding has always been to consider the scene to be the root of what's being rendered -- I don't think the docs or anywhere else ever recommend modifying the root transform to any effect. The fact that it works here at all is really just an odd side effect of how world matrices are computed and the fact that the camera isn't parented. It really requires knowing some idiosyncrasies of both three.js and PMREMGenerator to understand and use it this way.

For what it's worth this issue cropped up when one of my colleagues asked for help because the cube map from the scene wasn't at all what they expected. They wanted to create a reflection map of the scene but the camera was placed below the terrain because that's where our data was positioned. Adjusting the root transform of the world is a _really_ unintuitive way of adjusting the cubemap center in this case. If positioning the PMREM camera to somewhere other than the origin is something we want to support (and I think it should be) I think there should be a much more clear way of setting that. I'm happy to defer until PMREMGenerator integration has matured further, though.

**Comment by WestLangley** [comment]
I agree with @gkjohnson. However, I think `PMREMGenerator.fromScene()` is the problem.

`PMREMGenerator` should take an environment map as input, not a scene.

The pattern is `scene` -> `envMap` -> `PMREM`.

How the first step is handled is use-case-specific. The first step should be handled at the app level.

`PMREMGenerator.fromScene()` is misplaced, IMO, and should be removed.

**Comment by elalish** [comment]
I tend to agree with @WestLangley (sorry, since I introduced `fromScene()`). It makes bizarre recursive loops possible. However, the ability to generate a high resolution PMREM on the fly without having to download an HDR (which tend to be quite large) I think is an important capability. I suggested to @mrdoob changing it to `fromGroup()`, which would certainly meet the needs of `<model-viewer>`. Would that be reasonable?

**Comment by WestLangley** [comment]
@elalish I understand the benefit, but the use case is app-specific.

Can model-viewer create its own method that converts scene -> data-texture -> PMREM on-the-fly?

Perhaps could also add an example that demonstrates how to do it.

**Comment by elalish** [comment]
That's what we're doing now, but it means we have to use our own PMREM Generator instead of migrating to the internal one. I also don't see how this is MV-specific; I think lots of apps that use PMREM should consider this approach for performance reasons. In many ways it's also the easiest way to create HDR environments, since powerful emissive objects can be placed without needing to figure out how to edit an HDR file.

**Comment by Mugen87** [comment]
> Perhaps we could also add an example that demonstrates how to do it.

That sounds like a good compromise!

**Comment by Mugen87** [comment]
Maybe we could a new class in the `examples` folder that does the scene-to-envMap step? And then use it in a new example of course. In this way, projects could still use a component from the repository although it wouldn't be in the core.

**Comment by WestLangley** [comment]
Cube camera specular reflections are not correct because the cube camera is not located where the scene camera is located. Materials can be made temporarily rougher as a work-around. That was the other use-case I was thinking of. Maybe it is not that common...

IMO, it make sense to decouple `scene -> envMap` from `envMap` -> `PMREM`. Since the env map is stored in memory as as a data texture, there is no loss in doing so, and added flexibility is gained.

**Comment by elalish** [comment]
Actually yes, decoupling does sound preferable. I think I did it the way I did originally to avoid another render pass, but that's probably pretty trivial. Would be nice to have an example class that makes it easy to produce an envMap from a scene.

**Pull request closed without merging**
