### PR TITLE
 Reflectivity (reflectance at F0) for MeshStandardMAterial

### PR DESCRIPTION
**Pull request by bhouston**
I've added back reflectivity for MeshStandardMaterial because we needed it for physically accurate material reproduction in Clara.io.

Varying reflectivity matters a lot for things like gems.  So I made a simple gem example for ThreeJs.  It isn't actually correct because CubeUV environment mapping doesn't yet support refraction, thus it is doing reflections on the front and back.

Here is the effect of reflectivity -- in my opinion the first gem looks a lot more realistic than the later ones, because it reflects more:

reflectivity = 1.0:

image

reflectivity = 0.5:

image

reflectivity = 0.0:

image

This implementation follows the Frostbite 3 reflectance method exactly in terms of equations used.

If you guys do not want this, I am okay if it doesn't get merged.

### CODE REVIEW

**Comment by bhouston** [comment]
Interactive example:

http://ci.threejs.org/api/pullrequests/8505/examples/webgl_materials_reflectivity.html

**Comment by WestLangley** [comment]
I like this, but I would like to see `MeshPhysicalMaterial` added to the library.

The feature proposed here is quite subtle, and I see users getting confused by reflectivity vs. glossiness/roughness, and I would opt to keep `MeshStandardMaterial` simple.

The change here is rather than hardwiring the _specular reflectance of the material_ for non-metals to 0.04, @bhouston allows it to vary from 0 (when reflectivity is 0) to 0.16 (when reflectivity is 1).

Hardwiring the specular reflectance was a simplification for `MeshStandardMaterial` -- to keep it easy-to-use. The primary parameters are `color`, `metalness`, and `roughness`.

If we add `MeshPhysicalMaterial`, it can include this feature, `reflectivity`. I have also mocked up a clear-coat model that looks quite nice, and `clearcoat` could be added too, along with @bhouston's `anisotropy` property, and any other enhancements that seem appropriate.

I would like to see this implemented in `MeshPhysicalMaterial`, however. The example is quite nice, too.

**Comment by bhouston** [comment]
No worries @WestLangley.

From page 13 of the Frostbite 3 paper:

image

Here is their chart:

image

The main reason I need reflectivity (and I've already implemented it in my branch of ThreeJS and it is live) is to get the lens of say a camera like this properly reflective:

https://clara.io/player/v2/b43f3215-c9ef-488f-a55f-1bf2a7d74f3f

image

Camera lenses have reflectance in the [0.08 to 0.1] range.

**Comment by bhouston** [comment]
@WestLangley If you want to make a stab at creating a Physical material, I think that would be great. :)

**Comment by bhouston** [comment]
It is too bad that we can not just make it a single material, with advanced and non-advanced features.  Maybe have a sub-object of MeshStandardMaterial that contains the advanced parameters -- which normally people do not touch.

e.g.:

```
standard.advanced.reflectivity = 0.5;
standard.advanced.clearCoat = 0.1;
standard.advanced.clearCoatRoughness = 0.5
standard.advanced.anisotropy = 0.5;
```

Having a lot of distinct materials with overlaping functionality makes ThreeJS bigger and harder to maintain, and a lot more loaders/savers/etc.

**Comment by bhouston** [comment]
BTW I think separating MeshPhongMaterial from MeshStandardMaterial makes sense because the parameters are completely different (BlinnPhong shininess versus GGX roughness)., but that distinction isn't there between MeshStandardMaterial and MeshPhysicalMaterial.

**Comment by WestLangley** [comment]
>Having a lot of distinct materials with overlaping functionality makes ThreeJS bigger and harder to maintain, and a lot more loaders/savers/etc.

It sure does.

>standard.advanced.reflectivity = 0.5;
>standard.advanced.clearCoat = 0.1;
>standard.advanced.clearCoatRoughness = 0.5
>standard.advanced.anisotropy = 0.5;

Yes. I think that approach may be the best of the alternatives.

**Comment by mrdoob** [comment]
How about `MeshPhysicalMaterial` extending `MeshStandardMaterial`?

**Comment by erichlof** [comment]
@bhouston Could just the roughness parameter alone control reflectivity? Intuitively I view these two factors as inversely proportional - when roughness is 1.0, reflectivity is 0.0, when roughness is 0.0, reflectivity should be 1.0 automatically?  Unless the gems you speak of don't behave that neatly and need help from the extra reflectivity parameter.  BTW I really like your new gem example! :-)

**Comment by bhouston** [comment]
> How about MeshPhysicalMaterial extending MeshStandardMaterial?

That can work.

**Comment by bhouston** [comment]
> @bhouston Could just the roughness parameter alone control reflectivity? Intuitively I view these two factors as inversely proportional - when roughness is 1.0, reflectivity is 0.0, when roughness is 0.0, reflectivity should be 1.0 automatically?

Roughness is not reflectivity, they are actually quite different things.  Roughness reflects the same amount of light at roughness 0 and roughness 1, it just isn't as focused reflections at roughness 1.  Where as reflectance at F0 actually reflects more light if reflectance is 0.16 versus at reflectance 0.

**Comment by erichlof** [comment]
Ah ok thanks for clarifying.  In that case,  I would like to see reflectivity back in the system again,  or as @WestLangley said, in a new physical material.

**Comment by bhouston** [comment]
Superceded by #8535 and #8529

**Pull request closed without merging**
