### PR TITLE
WebGPURenderer: Support for access previous frame textures using `pass()`

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/29058#issuecomment-2269427662

**Description**

Add support for accessing previous textures, without needing special configuration, just like the syntax below:

```js
const scenePass = pass( scene, camera );

const currentTexture = scenePass.getTextureNode();
const previousTexture = scenePass.getPreviousTextureNode();

postProcessing.outputNode = mix( currentTexture, previousTexture, .5 ); // simple motion blur
```

### CODE REVIEW

**Comment by sunag** [comment]
Several revisions have been made, now MRT is working on WebGLBackend as shown in the screenshots.

**Comment by cmhhelgeson** [comment]
I'm getting an error on this code ( just modifying the after image sample ):

```
const scenePass = pass( scene, camera );
const scenePassColor = scenePass.getTextureNode();
const scenePassPrevColor = scenePass.getPreviousTextureNode();

postProcessing.outputNode = scenePassPrevColor;

```


https://github.com/user-attachments/assets/8b66261f-fb2b-41f7-954c-ea4e61c645e5

**Comment by sunag** [comment]
I think it is `{ antialias: true }`, `WebGPURenderer` does not yet fully support this

**Comment by WestLangley** [comment]
@sunag It works beautifully, except on the first frame.

**Pull request merged**
