### PR TITLE
GLTFLoader: Remove old or unstable extensions.

### PR DESCRIPTION
**Pull request by donmccurdy**
Removes `KHR_materials_common` code and models, superceded by https://github.com/mrdoob/three.js/pull/13136.

Removes old `KHR_technique_webgl` models, as (1) the extension spec is just a draft, and (2) we haven't begun to implement it yet.

Also updates link to KHR_materials_pbrSpecularGlossiness.

### CODE REVIEW

**Comment by takahirox** [comment]
I'm out of the office til Saturday and can't check the detail but I think the idea is good.

One tiny thought and a bit off topic, with this change we'll have no skinning model for glTF example, correct?
Feeling like adding another new/stable skinning model because I want to show that glTF loader supports skinning in the (extension) example.

**Comment by donmccurdy** [comment]
Still have skinning shown in the `gltf_extensions.html` example, this just removes the glTF-MaterialsCommon and glTF-TechniqueWebGL versions of each model.

**Comment by takahirox** [comment]
Ah, I've misread the diff.

**Comment by mrdoob** [comment]
Merging for now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
