### PR TITLE
Ability to limit pan based on distance from origin

### PR DESCRIPTION
**Pull request by agnivade**
- Added a flag which controls the limiting of panning

### CODE REVIEW

**Comment by agnivade** [comment]
Saw this feature being requested around in several SO questions. Thought of sending a PR for this, since I had implemented this.

**Comment by mrdoob** [comment]
Is this for panning more or less relative to the distance to the target?

**Comment by WestLangley** [comment]
>Is this for panning more or less relative to the distance to the target?

It's keeping the target within a sphere centered at the origin.

It may be a bit use-case-specific.

**Comment by agnivade** [comment]
Yes, this will keep the camera at a fixed distance from the origin. Agree that its a bit use-case specific. Therefore added a flag which gives flexibility to toggle this feature.

**Comment by WestLangley** [comment]
Other users may want to constrain to within a cylinder of radius R -- which may be more appropriate for `OrbitControls`. Or restrict `target.y` to 0 when panning. There are so many use cases, I'm not sure about this one...

**Comment by agnivade** [comment]
No worries, we can close this one out, if that is the decision. Or let me know if the constraint conditions need to be different to match the most common use case

**Comment by mrdoob** [comment]
I agree with @WestLangley. Sounds a bit too specific.

**Pull request closed without merging**
