### PR TITLE
BufferGeometryUtils: Provide function for drawMode conversion.

### PR DESCRIPTION
**Pull request by Mugen87**
See https://github.com/mrdoob/three.js/issues/9869#issuecomment-545348705

This PR introduces a new helper function `BufferGeometryUtils.convertToTriangles()` which converts the draw modes `THREE.TriangleFanDrawMode` and `THREE.TriangleStripDrawMode` to `THREE.TrianglesDrawMode` by generating a new (indexed) `BufferGeometry` from the given parameters.

`THREE.TrianglesDrawMode` is the only fully supported draw mode in `three.js`. The others don't work in context of raycasting or when rendering wireframes. Groups are not yet supported by this helper (not sure this is important).

Live demo: https://jsfiddle.net/wuosq4ge/

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
The method name makes me think of triangle soup. How about one of these names?

    convertToTrianglesDrawMode()

    toTrianglesDrawMode()

Also, you are simply adding an index if it is not present, or modifying the index if it is present. So, I think it would be more natural to just modify the existing geometry, rather than returning a new one. You are "converting" it, after all.... Just a suggestion. Whatever you want is fine.

@mrdoob We never did address the issue that you can't tell what the geometry represents -- points, line, or mesh -- because `drawMode` is not a property of the geometry. Notice in this method, the user must pass the existing `drawMode` into the method in order for it to work...

**Comment by Mugen87** [comment]
> The method name makes me think of triangle soup. How about one of these names?

It was not easy to decide for a name. I think `toTrianglesDrawMode()` sounds also good.

> So, I think it would be more natural to just modify the existing geometry, rather than returning a new one.

I think it's okay to return a new geometry and leave the original geometry as it is. Choosing a different name for the method should make things maybe more clear.

**Comment by Mugen87** [comment]
> We never did address the issue that you can't tell what the geometry represents

Why is this actually important? What's wrong with having a generic geometry class that gets a specific semantic when it is assigned to a concrete 3D object?

I mean this issue was more important in context of `Geoemtry` since properties like `faces` do not make sense for points and lines. But `BufferGeometry` is different. Looking at the properties, I can't see something specific to rendering primitives.

**Pull request merged**
