### PR TITLE
Update Material.js

### PR DESCRIPTION
**Pull request by moshuying**
Imprecise judgment

### CODE REVIEW

**Comment by mrdoob** [comment]
What does this solve?

**Comment by moshuying** [comment]
> What does this solve?

```javascript
let obj = {key:'value',depth:false}
const newValue = obj["depth"]
```
If you use `newValue === undefined` in code, its `ture`,But `Object.prototype.toString.call(newValue) === '[object Undefined]'`,its `false`, So this reduces unnecessary warnings

**Comment by Mugen87** [comment]
> If you use newValue === undefined in code, its ture,

That does not seem right. Check out the following live example. The console log says `false`: https://jsfiddle.net/731euan9/1/

**Comment by moshuying** [comment]
> > If you use newValue === undefined in code, its ture,
> 
> That does not seem right. Check out the following live example. The console log says `false`: https://jsfiddle.net/731euan9/1/

all  right

**Pull request closed without merging**
