### PR TITLE
Animation cloth example: clean up

### PR DESCRIPTION
**Pull request by WestLangley**
In particular, `MeshDepthMaterial` can now be used as the custom depth material in this case. It is no longer necessary to create a custom `ShaderMaterial` for that purpose.

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: http://rawgit.com/WestLangley/three.js/dev-cloth/examples/webgl_animation_cloth.html

**Comment by Mugen87** [comment]
Compared to the current [implementation](https://threejs.org/examples/webgl_animation_cloth.html), the size of fabric pattern changed a little bit. Is this intended?

**Comment by Mugen87** [comment]
Oh, there was a uv scaling in the previous fragment shader...

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
>the size of fabric pattern changed a little bit. Is this intended?

In the previous version, the shadow vertex shader was using a different UV scaling than the texture. That was a hack to make the shadows look better.

In this PR, `offset/repeat` is used, and the texture and shadow are consistent.

I chose to use a slightly different UV scaling of 0.5 instead of 0.75. I can change it to 0.75 if you want.

**Comment by Mugen87** [comment]
It's fine like that. I really like it that we don't need a custom shader for this example anymore! :+1:

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 I agree it's nice to have a link for testing, but once the feature branch is deleted, the link no longer works, and I guess the link should be removed.

@mrdoob BTW, whatever happened to threejsworker?

**Comment by mrdoob** [comment]
> @mrdoob BTW, whatever happened to threejsworker?

I guess @gero3 was not able to keep it alive.

**Comment by Mugen87** [comment]
Maybe just crossed out the link like above?

**Comment by WestLangley** [comment]
I suggest, if you are willing, you continue to add the helpful link, but delete the comment entirely when the link is no longer valid.

An advantage to threejsworker was it would recompile the library for each PR.

**Comment by Mugen87** [comment]
Okay!

**Pull request merged**
