### PR TITLE
WebGLRenderer: Make uniforms handling of RectAreaLight more consistent.

### PR DESCRIPTION
**Pull request by Mugen87**
Removes the uniform hack in `setProgram()` for setting `ltc_1` and `ltc_2` data textures.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Needs build.

I think it would be helpful if we can remember to update the build when required.

**Comment by Mugen87** [comment]
> Edit: Maybe it is not always obvious?

Yeah, if you just clean up files in `src` (e.g.  improve formatting) you not necessarily need updated builds. 

In general, I had the impression that it's sufficient when @mrdoob updates the builds files on `dev` every few days.

**Comment by WestLangley** [comment]
>Yeah, if you just clean up files in src (e.g. improve formatting) you not necessarily need updated builds.

That is clear. Was it clear to you that a new build was required in this case?

//

This PR caused severe artifacts without a build update. Unfortunately,  I spent an hour trying to track this down. In the future, I hope I remember to update the build as a first step.  :-)

>In general, I had the impression that it's sufficient when @mrdoob updates the builds files on dev every few days.

I disagree. I do not think we should intentionally have a dev branch that fails to run properly because the project managers failed to update the build when a new build was required.

We can always help @mrdoob by mentioning that a build is required if we see he failed to do that. I have done that in the past.

**Comment by DefinitelyMaybe** [comment]
> We can always help @mrdoob by mentioning that a build is required if we see he failed to do that. I have done that in the past.

that seems more appropriate.

**Comment by mrdoob** [comment]
> We can always help @mrdoob by mentioning that a build is required if we see he failed to do that. I have done that in the past.

Yep, always useful to get these reminders 🙏

**Comment by Mugen87** [comment]
> Unfortunately, I spent an hour trying to track this down. In the future, I hope I remember to update the build as a first step. :-)

May I ask how do develop offline? I normally fetch the latest changes of the `dev` branch and then use `npm start` in order to host a local server. In this way, I have automatically new builds.

**Comment by WestLangley** [comment]
>May I ask how do [you] develop offline?

I have an Apache server running, so I do not use `npm start`. I rebuild when I personally make changes that require a rebuild.

//

If we want to update dev builds only periodically, then I think we should note somewhere that the dev branch should not be used without rebuilding first. But personally, I think that would be a bad policy.

I think it is better to do our best to keep the builds up-to-date.

Actually, I thought that was what we were doing...

**Comment by mrdoob** [comment]
Yes, I try to rebuild when needed. I think it has been working out well so far.

**Pull request merged**
