### PR TITLE
WaterMesh: Fix planar offset - WebGPU

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/29606#issuecomment-2406481113

**Description**

Now is possible better notice the normals maps too.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... Is this a bug in Chrome Android? 🤔

https://raw.githack.com/mrdoob/three.js/dev/examples/index.html?q=webgpu#webgpu_ocean

https://github.com/user-attachments/assets/2b16e1a5-0c54-449a-9025-29199428a9bc

**Comment by Makio64** [comment]
Bug on chrome iOS (webgl backend )

https://github.com/user-attachments/assets/57c776ee-d526-45fe-9bb4-de919880659c

Bug on safari iOS (webgpu enabled flag)
https://github.com/user-attachments/assets/16a7f7ad-904f-4a6b-893a-8bf2a6b9887e

**Comment by Mugen87** [comment]
@Makio64 I also see the issue of your video with Firefox on macOS.

**Comment by Mugen87** [comment]
@mrdoob I'm seeing this on a Pixel 8a and Chrome as well. But not on other devices.

@Makio64 I can reproduce this with Firefox and macOS, too.

**Comment by sunag** [comment]
Here work properly!
- Samsung Galaxy Z Flip 4
- Chrome 129.0.6668.
- Android 14

**Pull request merged**
