### PR TITLE
Fixed broken link.

### PR DESCRIPTION
**Pull request by sasha240100**
Fixed broken link to particles example.

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like the whole file changed?

**Comment by sasha240100** [comment]
@mrdoob I have no idea why so :eyes: I just changed link with github's built-in editor.

**Comment by mrdoob** [comment]
Oh! I see... https://github.com/mrdoob/three.js/pull/8008/files?w=1

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
