### PR TITLE
Added: Stenciled portal (and mirror) rendering (Now you're thinking with portals?)

### PR DESCRIPTION
**Pull request by ProPuke**
Hi guys

So this is a big pr, I've not contributed to three.js before and this probably still needs a lot of tidying before accepting (I've likely put some things in the wrong place), so please be gentle with me.

This adds support for direct portal and mirror rendering, by use of the stencil bits (so no textures or FBOs in use). I needed a solution for this for a custom project which uses aframe (which makes use of three.js), which wouldn't add any considerable render latency, and worked correctly with vr; So here it is:

An example scene is viewable here: https://31i73.com/three.js/examples/webgl_geometry_portals.html

The above scene contains 4 portals - one on the floor and ceiling, acting as mirrors, and portals on the blue and green walls, which link to one another.

### Api

This adds a new property to all `Object3D`, called `portal`, which can point to an instance of `Portal`.

A `Portal` is constructed with a single properties object, which contains 3 optional attributes:

#### Object3D

`scene` - The scene this portal leads to. If missing or null the currently rendered scene will be used  
`target` - The destination object this portal leads to. The portal is viewed in from its source object's position and negative z axis and out from the target objects position, along it's positive z axis (if not a mirror this is achieved by rotating 180 degrees around the y axis). If missing or null the current object will be used. This is mainly useful when paired with the mirror property
`mirror` - If true the target orientation will be achieved by mirroring along the z axis, instead of rotating around the y - Thus the portal will show a mirror image.

Any object that is rendered into the world can be used as a portal. When an object is a portal it foregoes any opaque render pass, and instead renders solely to the stencil buffer for use as a portal area - Thus portals do not need to be flat, and can be viewable through any 3d object in the scene (for instance you could mark a sphere as a portal for use as a crystal ball you can look into). Material shaders for the object are still used, so you could make use of  `discard` in the shader to create animated or interesting portal shapes. If the material is marked as transparent it will render first solidly as the portal area, then after the portal has been rendered it will be rendered normally using its transparency pass over the top - Thus you can use alpha blending to overlay effects or masking over the portals, or blend in lighting on top, without using additional objects.

The following extra properties are added to WebGLRenderer:

#### WebGlRenderer

`currentPortalDepth` - While rendering, how many portals deep the renderer currently is
`currentPortalStencil` - While rendering, the current stencil bits being tested against
`currentlyMirrored` - While rendering, if the camera view is currently mirrored (which means the winding order of face vertices is reversed)
`maxPortalCount` - The maximum number of portals to render (defaults to the max 15)
`maxPortalDepth` - The maximum number of portals deep to render (defaults to the max of 2)
`maxPortalTotal` - The maximum number of total portals to render, including in all recursive depths (defaults to the max of 240)

If you have more portal objects than the max is set to render you'll likely want `sortObjects` is set to true. This will ensure the closer portals are rendered first, before the further ones are culled.

### Examples:

A mirror:

```javascript
var mirror = new THREE.Mesh( new THREE.PlaneBufferGeometry( 5, 5 ), new MeshBasicMaterial() );
mirror.portal = new THREE.Portal( { mirror: true } );
scene.add( mirror );
```

A one-way portal to another position

```javascript
var source = new THREE.Mesh( new THREE.PlaneBufferGeometry( 5, 5 ), new MeshBasicMaterial() );
source.position.set( 0, 0, 20 );
scene.add( source );

var destination = new THREE.Object3D();
destination.position.set( 50, 0, 0 );
scene.add( destination );

source.portal = new THREE.Portal( { target: destination } );
```

### Implementation

With an 8bit stencil buffer active this supports rendering up to 15 portals, up to 2 portals deep (so rendering a scene inside of a portal, inside of another portal, inside of a scene). This is achieved by using the first 4 bits of the stencil buffer for the first layer of portals, and the last 4 for the next layer (with 15 non-zero values in each). Rendering could potentially be extended to an unlimited depth by rendering the portals in a breadth first manner and swapping between using the low and high bits in each layer, but 2 seemed enough for now.

When rendering from a camera the following process occurs:

1) Opaque objects are rendered front-to-back
2) Portal meshes are rendered front-to-back, writing only to the stencil and depth bits, with depth test enabled
3) For each portal mesh depth bits are first cleared within the portal region and then a camera view is rendered  (maintaining the same transform from the target position and the target camera view, as is present from the source position to the initial camera view), within the stenciled areas. The camera is rendered using an oblique near clipping plane to cull areas that sit behind the destination position's z plane.
4) Portal meshes are rendered once again, front-to-back, writing only to stencil and depth bits, clearing the stencil bits for this portal, and writing back to the depth buffer to prevent transparent geometry rendering inside the portal area
5) Transparent objects are rendered back-to-front

#### Old render callchain:

`render` > `renderObjects` > `renderObject` > `renderObjectImmediate` / `renderBufferDirect`

(renderObjects used to branch dependent on array cameras)

#### New render callchain:

`render` > `renderCamera` > `renderObjects` / `renderPortalObjects` > `renderObject` > `renderObjectInternal` > `renderObjectImmediate` / `renderBufferDirect`

(renderPortalObjects may call renderCamera, recursively)
(renderObject now branches depending on array cameras, with both routes using renderObjectInternal)

As renderCamera now calls recursively, many private global variables used during rendering have been moved to an instanced object called `renderData` which is passed to many render functions (as the first parameter)

### CODE REVIEW

**Comment by tentone** [comment]
Wow really nice work, i love the example.

Thanks, i hope this gets merged!

**Comment by mrdoob** [comment]
Looking good!

Any chance you could implement this outside of `src` though?

I think `THREE.Mirror` is a good reference:
https://github.com/mrdoob/three.js/blob/dev/examples/js/Mirror.js

**Comment by ProPuke** [comment]
Unfortunately not. This doesn't use separate render targets like `THREE.Mirror` does. It renders recursively in place.

This performs better, ensures portals are pixel perfect (while not incurring overdraw), and works correctly with webvr and array cameras (it's not a flat texture).

If the example worked like THREE.mirror did and used separate render passes, with webvr it would have to draw to render targets 32 times each frame. The best way to achieve recursive rendering like this is to unfortunately modify `src`.

A more flexible future way might be to make these changes, but have `renderCamera` as a public method, with some extra hook points in place. Things could be more modular then, and other elements could perform recursive rendering if they needed to, without hardcoding changes in WebGLRenderer.

But yeah, that's still performing changes to `src` :S

**Comment by mrdoob** [comment]
I see I see. I'll have to study all this.

What's the reason for removing `lights` from `UniformsLib`?

**Comment by mrdoob** [comment]
Also, do you mind removing the builds from the PR?

**Comment by mrdoob** [comment]
We're considering modularising `WebGLRenderer`'s `render()` by the way:

https://github.com/mrdoob/three.js/issues/11301#issuecomment-310798923

**Comment by ProPuke** [comment]
The light uniforms used to point to global variables (by reference). Light state is camera specific, so was moved into `renderData` objects to support nested rendering - Thus couldn't be pointed to by UniformsLib.

Those changes to render() look like a good direction to go in.

What portal rendering like this requires is the ability to start a second render process in between rendering opaque and transparent objects (so it needs to be able to do its own renderReset, renderBackground etc), then when that's done resume where it was before. So in the form of your example before - something like:

```javascript
renderer.renderReset();
renderer.renderBackground( scene, camera );
renderer.renderGenerateShadows( scene, camera );
renderer.renderGenerateRenderList( scene, camera );
renderer.renderDisplayCamera( scene, camera );
renderer.renderSolids( scene, camera );
renderOpenPortalAreas();

for(portal of portals){

    renderer.pushState();
    renderer.renderReset();
    usePortalStenciling(portal);
    renderer.renderBackground( scene, camera );
    renderer.renderGenerateShadows( scene, camera );
    // etc ...
    renderer.popState();

}

renderClosePortalAreas();
renderer.renderTransparents( scene, camera );
renderer.renderFinishRenderTarget();
```

You could maybe do this via push/pop functions as per the above.

In that case pushState() and popState() would look something like:

```javascript
this.pushState = function () {

    var data = {
        lightsArray: [],
        shadowsArray: [],
        spritesArray: [],
        flaresArray: [],
        // etc ...
    };

    this.dataStack.push( this.currentData );
    this.currentData = data;
}

this.popState = function () {

    this.currentData = this.dataStack.pop();

}
```

So again the globals would disappear, and instead be accessed internally as `this.currentData.lightsArray` etc

This might be a nice way of going about, cos if people don't need this feature, they don't need to worry about any extra parameters or what push/popState might do, they can just ignore those functions.

(How would I go about removing the build files, btw? I wasn't sure how to do this as they're already tracked files)

**Comment by ProPuke** [comment]
I've found a couple of bugs. I'll be patching this shortly. Soz

**Comment by tentone** [comment]
Any progress in this PR? 👍 

It would be awseome to have portals in threejs!

**Comment by ProPuke** [comment]
Okay after using it for a bit, removing `lights` from `UniformsLib` was too much of a breaking change.

I've restored it as an empty (deprecated) property, so as not to break existing code that attempts to merge it into their uniforms (there's just nothing inside it).

This is now once again merge-compatible with dev.

**Comment by blairmacintyre** [comment]
Did this go anywhere?  Looks very cool ...

**Comment by Mugen87** [comment]
I think the PR changed `WebGLRenderer` too deeply just for adding stenciled portal rendering. A PR that does not affect the core (or at least in a straightforward  way) will have more success to land in the library.

@mrdoob I suggest to close the PR. TBH, this feature is not worth such extensive change in renderer.

**Comment by Mugen87** [comment]
I think the PR changed `WebGLRenderer` too deeply just for adding stenciled portal rendering. A PR that does not affect the core (or at least in a straightforward  way) will have more success to land in the library.

@mrdoob I suggest to close the PR. TBH, this feature is not worth such extensive change in renderer.

**Comment by blairmacintyre** [comment]
@Mugen87 that's what I figured.

**Comment by mrdoob** [comment]
> I think the PR changed `WebGLRenderer` too deeply just for adding stenciled portal rendering. 

Yeah. It really changed too many things at once...

@ProPuke you probably moved on already but, would you be interested in breaking this in different PRs so it's easier to review?

**Comment by blairmacintyre** [comment]
FWIW, we took the Reflector.js and hacked it to do just the "less efficient" version that @propuke pointed out the issues with above.  It's a bit "tightly integrated" into our editor, but I'll see if we can pull it out and contribute it back, if there is interest.

**Pull request closed without merging**
