### PR TITLE
FBXLoader create buffer geometry directly

### PR DESCRIPTION
**Pull request by looeee**
The loader was using a set of custom objects as intermediaries between the FBX format and the buffer geometry. The custom objects were:

* Geometry
* Face
* Triangle
* Vertex

I presume these were left over from when the loader returned a geometry rather than a buffer geometry. 
Switched to creating a buffer geometry directly and removed the intermediate data structure.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Man... you have revamped the whole loader! Many many thanks!

**Comment by Mugen87** [comment]
Indeed, cool stuff @looeee!  🎉

**Comment by looeee** [comment]
😊 

Probably the last one for a while though, I really have to go and pay the bills 😅

**Pull request merged**
