### PR TITLE
Changed Euler Copy Clone on change test implementation.

### PR DESCRIPTION
**Pull request by levilime**
The previous implementation of the Euler Copy/Clone, FromArray and Set/Get property tests gave inconsistent behavior due to the QUnit step behavior. This test is rewritten to successfully test the behavior. It is related to this issue: https://github.com/mrdoob/three.js/issues/13606

### CODE REVIEW

**Comment by mrdoob** [comment]
Make sure you use hard tabs 😇

**Comment by levilime** [comment]
Whoops 😅, fixed using hard tabs!

**Comment by Mugen87** [comment]
I still don't understand why i don't have this fails on my machine. Neither in the browser nor with node.js.

**Comment by levilime** [comment]
@Mugen87 I wonder about this as well. There are some minor differences between our setups. I run windows 10, node.js 6.10.2. and have run the QUnit through the console with `npm test` and used the QUnit GUI in firefox. Is the QUnit version you use the one that is in the `package.json`, `^2.5.0`?

**Comment by Mugen87** [comment]
I'm using qunit 2.4.0 see like defined in `package.json`? Where have you seen `^2.5.0`?
https://github.com/mrdoob/three.js/blob/87f413430aa70638c1067a934e18d6a801aef49d/package.json#L59

**Comment by levilime** [comment]
Oops sorry, I meant `^2.4.0`. This behavior is with QUnit `^2.4.0`

**Comment by Mugen87** [comment]
Strange 🤔 . I think the feedback of other developers might be useful here.

Whoever reads this: Please execute `npm run test` and then report the number of fails here in this thread 😊. Thx.

**Comment by looeee** [comment]
qunit@2.4.1:

```bash
# pass 637
# skip 0
# todo 1101
# fail 0
```

Run `npm update` 

qunit@2.5.1:

```bash
# pass 634
# skip 0
# todo 1101
# fail 3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! three@0.91.0 test: `npm run build-test && qunit test/unit/three.source.unit.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the three@0.91.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\looee\AppData\Roaming\npm-cache\_logs\2018-03-17T01_41_54_945Z-debug.log
```

The failing tests give messages similar to 

```js
not ok 1738 # TODO Source > Textures > VideoTexture > isVideoTexture
  ---
  message: "everything's gonna be alright"
  severity: todo
  actual: false
  expected: true
  stack:     at Object.QUnit.todo (D:\Web\three.js\test\unit\three.source.unit.js:69559:12)
    at runTest (D:\Web\three.js\node_modules\qunit\qunit\qunit.js:1478:30)
    at Test.run (D:\Web\three.js\node_modules\qunit\qunit\qunit.js:1464:6)
    at D:\Web\three.js\node_modules\qunit\qunit\qunit.js:1676:12
    at Timeout.advance [as _onTimeout] (D:\Web\three.js\node_modules\qunit\qunit\qunit.js:1116:26)
    at ontimeout (timers.js:478:11)
  ...
```

**Comment by Mugen87** [comment]
When i upgrade to `qunit@2.5.1`, i also have three fails. But these fails are fixed with @levilime changes. 

@looeee I'm not sure why you have fails with `VideoTexture`. There are just placeholder in `VideoTexture.tests.js` so far.

@mrdoob Since the PR is compatible with `qunit@2.4.1`, we can merge these changes!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
