### PR TITLE
fix gltfLoader resolveURL for url startWidth "//"

### PR DESCRIPTION
**Pull request by 06wj**
url like '//g.alicdn.com/xx/xx.gltf'  is absolute url

### CODE REVIEW

**Comment by donmccurdy** [comment]
Looks good to me. thanks!

**Comment by donmccurdy** [comment]
@06wj could you include the same change for GLTF2Loader as well?

**Comment by 06wj** [comment]
@DodekaHydra fixed  GLTF2Loader.

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
