### PR TITLE
OBJLoader2: Fuse WorkerRunner and ObjectManipulator and clean-up

### LINKED ISSUE #17769: CodeSerializer Can't serialize code for OBJLoader2Parallel worker correctly when threejs is bundled with webpack
##### Description of the problem

I'm using Threejs in a project with webpack to bundle the code. When I'm trying to use the OBJLoader2Parallel class to load obj files in a web worker,  But it failed due to undefined webpack code _utils_ObjectManipulator_js__WEBPACK_IMPORTED_MODULE_0__ in the worker code.  

After some investigation, I find out that the worker code are generated on the fly using CodeSerializer based on code like WorkerRunner.js, ObjectManipulator.js and OBJLoader2Parser.js, which are all bundled into the same bundle file by webpack.

But due to ObjectManipulator.js is imported to WorkerRunner.js file, the code below:
`ObjectManipulator.applyProperties( parser, payload.params );`
in WorkerRunner.js will be converted to:
`_utils_ObjectManipulator_js__WEBPACK_IMPORTED_MODULE_0__["ObjectManipulator"].applyProperties( parser, payload.params );
`
by webpack.

Then, when the OBJLoader2Parallel is building the worker code with CodeSerializer, the code above will be copied directly and it can't resolve _utils_ObjectManipulator_js__WEBPACK_IMPORTED_MODULE_0__["ObjectManipulator"] to the ObjectManipulator object. This makes the worker fail.

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by kaisalmen**
This fixes #17769 
Overview:
- Move `ObjectManipulator` into `WorkerRunner` and export it from there ( thanks to @manyoo )
- Remove `OBJLoader2Parser` import from `WorkerRunner`. Remove unneeded functions from `DefaultWorkerPayloadHandler` and `WorkerRunner` and aligned typescript definitions

The parser in `DefaultWorkerPayloadHandler` should not be limited to `OBJ2LoaderParser`. js and ts was not aligned here.

### CODE REVIEW

**Comment by kaisalmen** [comment]
I am a little late with the change, but I hope it can be contained in tomorrows's release.

**Comment by mrdoob** [comment]
Thanks!

**Comment by qskycolor** [comment]
this issue get a new error: [https://github.com/mrdoob/three.js/issues/17769#issuecomment-570677403](url)

**Comment by Mugen87** [comment]
@qskycolor Please do not post at other PRs or issue in order to draw attention to your comment here https://github.com/mrdoob/three.js/issues/17769#issuecomment-571995904

**Comment by qskycolor** [comment]
> @qskycolor Please do not post at other PRs or issue in order to draw attention to your comment here [#17769 (comment)](https://github.com/mrdoob/three.js/issues/17769#issuecomment-571995904). One post is totally sufficient.

Sorry,I just found that comment has no answers, but I'm eager to fix it.

**Pull request merged**
