### PR TITLE
WebGPURenderer: PassNode + PostProcessing - WebGPUBackend

### PR DESCRIPTION
**Pull request by sunag**
**Description**

HDR PostProcessing and Refraction example.

[webgpu_backdrop_water](https://raw.githack.com/sunag/three.js/dev-pp/examples/webgpu_backdrop_water.html)

image

Underwater

image

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good! ✨

**Comment by mrdoob** [comment]
By the way, Chrome Canary in Android already has WebGPU enabled.

However, for some reason, weed the example loads the camera seems to be zoomed in.

Screenshot_20240111-063255

But after tapping the screen the issue goes away.

Screenshot_20240111-063307

It may be something to do with lil-gui?

**Comment by sunag** [comment]
@mrdoob I was able to reproduce the problem, clicking on the **menu (three vertical dots) -> Settings -> Accessibility** I activated `Force enable zoom`.

Maybe it's not a bug, but a special browser setting?

WhatsApp Image 2024-01-12 at 16 55 29_3a18827b

**Comment by sunag** [comment]
I didn't implement it in `WebGLBackend`, the example should work if `copyFramebufferToTexture()` uses the `RenderTarget` as a source if there is one.

/cc @RenaudRohlinger @aardgoose

**Comment by mrdoob** [comment]
> @mrdoob I was able to reproduce the problem, clicking on the **menu (three vertical dots) -> Settings -> Accessibility** I activated `Force enable zoom`.
> 
> Maybe it's not a bug, but a special browser setting?

Hmm...

Screenshot_20240123-163539

These address my settings... 🤔

**Pull request merged**
