### PR TITLE
Improve HTMLMesh (transparent and html size changes)

### PR DESCRIPTION
**Pull request by remmel**
**Description**

Small HtmlMesh improvement

- [x] Handle transparent
- [x] Fix the VR UI when the html size changes (see gif of bug) - my fix seems pretty dirty the problem should be fix at the root? Texture doesn't seem to handle when its source image size change
- [x] Demo with vanilly/litelement/react (probably won't be commited in dev)
- [x] Handle shadowRoot (with some limitation as MutationObserver ignores shadowRoot and no shadowRoot attach event (when calling HTMLMesh we cannot easily know if and when dom.shadowRoot will be created)

Peek 2022-03-08 13-56

[Demo](https://remmel.github.io/three.js/examples/webxr_vr_htmlmesh.html)

The CI fail, because I make myself the screenshot (cannot run make screenshot locally)

- There is still a bug when using react (adding bubbles : `const mouseEventInit = {bubbles: true};` fixes it, but after I get error from Google Translate chrome plugin :s) - I won't fix it
- When the html size change, the geometry should be resized, otherwise, the UI is wrongly scaled. Don't know how to fix that : Maybe just forget it? Same for the fixed part? Revert it also?

### CODE REVIEW

**Comment by remmel** [comment]
Hi! Waiting for your feedbacks. Especially about the `Fix the VR UI when the html size changes`. Thanks!

**Comment by mrdoob** [comment]
Hmm, what are your questions exactly?

**Comment by remmel** [comment]
> Hmm, what are your questions exactly?

Is there a cleaner alternative than calling `super.dispose();` when canvas changed (cf https://github.com/mrdoob/three.js/pull/23662/commits/40449310e9912997f31593b177d68ccd4fbfc4d5) - Do Texture expect the image size to change ? I have the feeling that it should be fixed somewhere in Texture instead.

**Comment by vincentfretin** [comment]
@remmel I have something working for the canvas size changed, I emit a size-changed event and recreate the mesh in an aframe component, surely we could recreate only the geometry instead of recreating the whole mesh, geometry, material and texture but I didn't succeed to do that. You were close to detect canvas size change, but you needed setting canvas.width and canvas.height out of the condition. See https://github.com/AdaRoseCannon/aframe-htmlmesh/pull/14 (aframe-htmlmesh repo contains a copy of master HTMLMesh.js)

**Comment by mrdoob** [comment]
@remmel Do you mind splitting this into multiple PRs? The resize code is blocking the other improvements.

**Comment by remmel** [comment]
Transparency has already been added [3ac055ce6111b5a63cf81c081e3c5f5940fb4e6a](https://github.com/mrdoob/three.js/commit/3ac055ce6111b5a63cf81c081e3c5f5940fb4e6a)
Others feature resize and shadow are less important and might be implemented is seperated layer.
I'm thinking about adding an exemple/webxr_vr_htmlmesh.html to show some HTMLMesh usage, (image load, transparency, etc..) what do you think?

**Pull request closed without merging**
