### PR TITLE
GLTFLoader: Fix issue where node index association is overwritten.

### PR DESCRIPTION
**Pull request by ghost**
If a mesh is referred to by several nodes, and if the mesh has a single primitive (thus Three combines the Node, Mesh, and Primitive into a Three Mesh) then mesh Id's get overwritten during the cloning process.

Fix on top of PR: #22583

### CODE REVIEW

**Comment by donmccurdy** [comment]
Just curious – would you prefer that GLTFLoader _not_ flatten Node/Mesh/Primitive into a `THREE.Mesh` in these cases? Or does that break backward-compatibility in a significant way? /cc @drcmda

**Comment by timmmeh** [comment]
> Just curious – would you prefer that GLTFLoader _not_ flatten Node/Mesh/Primitive into a `THREE.Mesh` in these cases? It would at least make parsing much more predictable. Or does that break backward-compatibility in a significant way? /cc @drcmda

@donmccurdy 
It does complicate things a bit, I have a CL where I removed it but it seemed like the flattening was an optimization as there can be many dozens of nodes that get collapsed, so I left it. My thinking was that it might have been saving a lot of identity matrix concatenations (unless that is optimized too, I'm not familiar with it). 

Currently the main complication comes from trying to keep the associations map up to date. I think a more robust way to do this would be to attach the mappings (POD data) to userData and then, as a final step, walk the scene and remove them from userData while adding them to the associations map, this way it avoids having to manage the mappings while all the cloning is taking place.

**Comment by donmccurdy** [comment]
The flattening is an optimization, yes — not sure if it's a large or a small difference in practice. In any case it is possible that any change to the output hierarchy would break things for gltfjsx users at this point. 😕

From a longer-term perspective I'm not thrilled with the complexity of maintaining these associations, e.g. needing special cases for single-primitive meshes, but that's an issue that predates this PR of course.

>  I think a more robust way to do this would be to attach the mappings (POD data) to userData and then...

Does that seem like a large change, and would you be interested in trying a PR for it? I'm OK with merging this PR instead if needed.

***

Off topic: I'm starting to wonder if having a single version of GLTFLoader fulfill all the goals it currently does might be too much... notably: (1) supporting userland extensions, (2) tracking source file associations, (3) lazy loading, (4) automatically flattening node hierarchy. These are all good goals but they're somewhat in conflict, and reducing parsing performance already.

**Comment by mrdoob** [comment]
@donmccurdy 

> From a longer-term perspective I'm not thrilled with the complexity of maintaining these associations, e.g. needing special cases for single-primitive meshes, but that's an issue that predates this PR of course.

Agreed.

Out of curiosity... What changes should the Three.js scene graph have in order to not need this associations code?

**Comment by timmmeh** [comment]
> Out of curiosity... What changes should the Three.js scenegraph have in order to not need this associations code?

First, don't collapse nodes, but not sure if there is enough metadata to properly map things back to the glTF file, I need to spend some cycles trying this out...

**Comment by donmccurdy** [comment]
Let's continue in #22750. It's a larger change but less code in the end, and easier to reason about.

**Pull request closed without merging**
