### PR TITLE
Docs: Fix language switching for examples.

### LINKED ISSUE #16669: Some docs links broken?
##### Description of the problem

Steps:

1. go to https://threejs.org/docs/#examples/loaders/TGALoader
2. click on "en" and pick "zh" (gets 404)
3. click on "zh" and pick "en" (gets 404)

I'm guessing this means the file doesn't have a translation? But then selecting english doesn't take me back to the english. 

##### Three.js version

- [ ] Dev
- [X] r105
- [ ] ...

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #16669

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev32/docs/index.html

**Comment by mrdoob** [comment]
So the problem is that https://github.com/mrdoob/three.js/tree/dev/docs/examples doesn't have `en/` . and `zh/` folders, right?

**Comment by Mugen87** [comment]
Yes, that's right.

**Comment by Mugen87** [comment]
Okay, I've introduced the same file structure (`en`/`zh`) similar to the `api` and `manual` directories. In this way, the doc pages are now ready for Chinese translation, too.

**Comment by mrdoob** [comment]
Awesome! Many thanks!

**Pull request merged**
