### PR TITLE
Add plane orientation example

### PR DESCRIPTION
**Pull request by nikolas**
This adds a new example for users to play with and visualize a plane's normal vector.

2019-02-14-140749_1100x802_scrot

### CODE REVIEW

**Comment by WestLangley** [comment]
Normal vectors must have unit length. Also, the plane constant is important. The three.js forum may be of help to you if you have questions about these concepts.

Also, this example may already be sufficient: https://threejs.org/examples/webgl_clipping_intersection.html.

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/nikolas/three.js/plane-visualization/examples/webgl_math_orientation_plane.html

**Comment by Mugen87** [comment]
> Normal vectors must have unit length.

@nikolas This example won't be merged as long as the UI allows the selection of normal vectors with no unit length. If you can come up with a solution for this, you should also ensure the example uses only modules. See the other examples on `dev` as a reference.

**Comment by WestLangley** [comment]
Sorry, I do not think this example has sufficient merit. I would suggest closing it.

**Pull request closed without merging**
