### PR TITLE
WebGL Multiple Render Targets (DrawBuffers) 

### PR DESCRIPTION
**Pull request by mattdesl**
Added support for multiple render targets in WebGLRenderer.

You can use `WebGLMultiRenderTarget` which has an `attachments` property. This is an array, default length 1 with the initial `texture` property. You can push more textures (typically clones of the initial one) to this render target.

``` js
var target = new THREE.WebGLMultiRenderTarget( window.innerWidth, window.innerHeight );
target.texture.format = THREE.RGBFormat;

// Add another attachment
target.attachments.push( target.texture.clone() );
```

Includes an example of writing color and normals into a G-Buffer, and then visualizing the G-Buffer.

This can pave the way (eventually) for deferred shading and other interesting rendering techniques.

---

WebGL2 notes:

This is exposed through a WebGL1 extension. In my WebGL2 app, I've got it working by patching the `gl.getExtension` function and returning a backwards-compatible extension for any features that have been promoted to core. 

In WebGL2, you can't use `gl_FragData` in any shaders. Instead, you need to use `out` with a location layout specifier, which means you need to write `version 300 es` shaders if you plan to use this feature in a WebGL2 app.

### CODE REVIEW

**Comment by mattdesl** [comment]
Demo:
http://ci.threejs.org/api/pullrequests/8439/examples/webgl_mrt.html

screen shot 2016-03-22 at 12 24 35 pm

**Comment by mrdoob** [comment]
Does this work with the #8417 changes?

**Comment by bhouston** [comment]
This is so awesome.  @mattdesl these are greatly appreciated improvements.

**Comment by mattdesl** [comment]
Yup, it shouldn't have any effect on that PR. Just merged with `dev` branch again and fixed conflicts.

**Comment by edankwan** [comment]
Any update on this feature? According to WebGLStats, the support rate is over 50% already :)

**Comment by mrdoob** [comment]
@mattdesl Any chance you could give another go at implementing this?

**Comment by mattdesl** [comment]
@edankwan did a nice job of cleaning up this PR, see here:
https://github.com/mrdoob/three.js/pull/9358

:tada:

**Pull request closed without merging**
