### PR TITLE
Add backspace or delete key to delete object

### PR DESCRIPTION
**Pull request by tjiahen**
I think adding a delete key to delete is a good idea to make it more user friendly.
What do you think?

### CODE REVIEW

**Comment by mrdoob** [comment]
That used to be like that but bad things happened when using the backspace when editing the name of an object. I still don't know how to control that...

**Comment by wizztjh** [comment]
I think we can prevent the event from bubbling up in each text input to prevent this from happening. I will give it a try to fix this.

**Comment by mrdoob** [comment]
Thanks!

**Comment by wizztjh** [comment]
I just found out the stop propagation is done in [lib/ui.js](https://github.com/mrdoob/three.js/blob/master/editor/js/libs/ui.js#L335)

I tried to press remove or backspace in `user data` input and it delete without going back to the last page.

**Comment by mrdoob** [comment]
Implemented back. Thanks!

**Pull request closed without merging**
