### PR TITLE
[glTF] Update BoomBox metal-rough demo.

### PR DESCRIPTION
**Pull request by donmccurdy**
Sounds like glTF's metal-rough spec will be changing channels to match the OcclusionRoughnessMetallic (RGB) ordering. takahirox has already implemented that on our end, so this demo is just swapping the channels in the old image. I haven't found an official model with the change, so this is just the result of:

```bash
convert BoomBox_metallicRoughness.png -separate -swap 0,2 -combine BoomBox_metallicRoughness_2.png
```

Also updating the demo to include an envMap, because prettier. 😬

screen shot 2017-03-29 at 10 45 17 pm

Related: #10691

/cc @takahirox

### CODE REVIEW

**Comment by donmccurdy** [comment]
Oops, this doesn't fix the binary version though. I will need to look into how to do that...

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Hmm... I wonder what is causing all the "sparkles" artifacts when the camera is rotated? This is happening even if the light's intensity is set to near zero.
```
directionalLight = new THREE.DirectionalLight( 0xffffff, 0.01 );
spot1 = new THREE.SpotLight( 0xffffff, 0.01 );
```
Well, at least on my machine...

**Comment by mrdoob** [comment]
Hmm... Can you share a screenshot?

**Comment by WestLangley** [comment]
screen shot 2017-03-30 at 1 26 08 pm

**Comment by mrdoob** [comment]
Hmm... Yeah, i can reproduce too... Must be something to do with the textures?

**Comment by donmccurdy** [comment]
@antonio-gomez the glTF 2.0 spec is not quite finalized, and the `r`->`b` change here is expected to happen in the spec soon. If so, the glTF 2.0 sample files will also be updated as I've done here. Further discussion here: https://github.com/KhronosGroup/glTF/issues/857

**Comment by antonio-gomez** [comment]
Thanks for clarifying @donmccurdy

**Comment by takahirox** [comment]
Let me understand what "sparkles" are.
Are they in the red circles?

image

**Comment by WestLangley** [comment]
Yes.

**Comment by takahirox** [comment]
I reproduced here.
Roughness related maybe?

**Comment by donmccurdy** [comment]
Opened #11106 to track this.

**Pull request merged**
