### PR TITLE
WebGLUniforms: Added caching for SingleUniform

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adresses #14004 and introduces a simple caching mechanism for single uniforms. I've tested this implementation with some examples and it greatly reduced the amount of uniform updates:

`webgl_geometry_cube`: From 7 to 1 updates per frame
`webgl_animation_cloth`: From 73 to 14 updates per frame
`webgl_loader_collada`: From 48 to 4 updates per frame
`webgl_interactive_cubes_ortho`: From 12008 to 6001 updates per frame

### CODE REVIEW

**Comment by Mugen87** [comment]
@oguzeroglu Can you please make a test with this version and see how it performs? 😉

**Comment by mrdoob** [comment]
Nice! I was thinking of implementing this 👌
I wouldn't add the uniformUpdates code for now though. That data is something the user can't do much about anyway...

**Comment by mrdoob** [comment]
We should also add:

```js
function arraysEqual( a, b ) {
    if ( a.length !== b.length ) return false;
    for ( var i = 0; i < a.length; i ++ ) {
        if ( a[ i ] !== b[ i ] ) return false;
    }
    return true;
}
```

So then many of these checks can be reduced to:

```js
if ( arraysEqual( this.cache, v ) ) return;
```

**Comment by takahirox** [comment]
> @oguzeroglu Can you please make a test with this version and see how it performs? 😉

Yes, please! I'm very curious...

**Comment by oguzeroglu** [comment]
> @oguzeroglu Can you please make a test with this version and see how it performs? 😉

Yes, I'll do it ASAP and post the results here :)

**Comment by Mugen87** [comment]
Don't expect to see a higher FPS in all use cases :wink:. But since the amount of updated uniforms is a performance metric in 3D engine design (similar to draw calls), it's definitely good to lower this number.

**Comment by Mugen87** [comment]
I wonder if there is a way to make `setValue2fv()`, `setValue3fv()` and `setValue4fv()` more compact...

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Seems like this introduced a javascript performance regression. A big part of it is the removal of `mat4array` and `mat3array` which, if I'm not mistaken, are mainly used to pass the data to gl as 32bit instead of 64bit.

Fixing...

**Comment by Mugen87** [comment]
I was not sure about the usage of these matrices. Thanks for fixing this. And I really like the refactoring 😊 .

**Comment by mrdoob** [comment]
I did some some master vs dev 5s performance captures using Chrome Dev Tools with examples with a lot of objects.

This one showed the regression the most clearly:
https://rawgit.com/mrdoob/three.js/dev/examples/webgl_lights_pointlights2.html

It is actually a bit slower than master still...

**Comment by Mugen87** [comment]
Well, this problem would not happen if the torus objects are merged or if instanced rendering is used.

**Comment by mrdoob** [comment]
Agreed 👌

**Comment by mrdoob** [comment]
On a MacBook Pro I'm seeing a considerable performance improvement!

This example goes from ~43FPS to ~60FPS 🎉
https://rawgit.com/mrdoob/three.js/dev/examples/#webgl_materials_variations_standard

**Comment by Mugen87** [comment]
😳

**Comment by oguzeroglu** [comment]
This dramatically decreased the amount of unecessary webgl uniform calls in my project as well. Nice job @Mugen87!

**Comment by mrdoob** [comment]
Hmm... I think this PR broke `NodeMaterial`...

Before: https://rawgit.com/mrdoob/three.js/e10057f07c2c4fc6b400b47646c3521896f95206/examples/webgl_loader_nodes.html

After: 
https://rawgit.com/mrdoob/three.js/a9047c54cbcc9f53c358ca53db4c4f7c67687a41/examples/webgl_loader_nodes.html

**Comment by Mugen87** [comment]
I think i found the problem. It's easier to explain with this example:

https://rawgit.com/mrdoob/three.js/dev/examples/webgl_sprites_nodes.html

The problem is that `NodeMaterial` creates a uniform of type `fv1` (in this example an array with a single float value), but the `WebGLUniforms` uses the function `setValue1f()` for the update. This function is intended for single float value and not for an array of floats. The problem is that the whole array object is assigned to the cache and subsequent compare operations with the array object are always true.

@sunag Why is uniform type `fv1` and not `f1` here?

https://github.com/mrdoob/three.js/blob/f36c9c59db9ab449e6f4285482573537a23f19c2/examples/js/nodes/inputs/FloatNode.js#L7-L9

**Comment by Mugen87** [comment]
Right now, I think the problem is related to `NodeMaterial`. If it uses `fv1`, it needs to declare the uniform like this `uniform float myFloat[0]` in the shader and use it as an array. Otherwise `WebGLUniforms.parseUniform()` won't work with the correct uniform type. 

I guess it makes more sense to change `NodeMaterial` so it uses `f1` and `i1`  and does not use arrays but primitives for the internal representation for the uniform data.

**Comment by Mugen87** [comment]
Any chances to provide a workaround for the current implementation of `NodeMaterial`? For simple float and in values, it must ensure that only primitives (not instantiate) values are used as uniform data.

**Comment by sunag** [comment]
Yes, yes. I have some solutions in mind that I will test.

**Pull request merged**
