### PR TITLE
ColladaExporter: Fix runtime error when processing ImageBitmap.

### PR DESCRIPTION
**Pull request by Mugen87**
This bug was reported in the forum (via PM).

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... Why is the code using `image.naturalWidth` and `image.naturalHeight`?

**Comment by Mugen87** [comment]
> Hmm... Why is the code using image.naturalWidth and image.naturalHeight?

@gkjohnson Can you help here? 😇

**Comment by gkjohnson** [comment]
Mm I don't believe there's a good reason to use `naturalWidth` over `width` -- I think the function could just be changed to use `width` and `height` to simplify things.

**Comment by Mugen87** [comment]
Okay, updated to PR to just use `width` and `height`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
