### PR TITLE
Editor: Allow Tube Geometry to edited by dragging points on screen

### PR DESCRIPTION
**Pull request by Temdog007**
Tube Edit Demo

If this PR goes through, my plan is add support for `Points` and `Lines` (and maybe `Paths`?) to the editor.

### CODE REVIEW

**Comment by looeee** [comment]
Hey, this is really cool 😁 Good job. 

This is purely a visual preference but the control points seem a bit large and cartoonish to me, especially when I zoom in. Ideal would be if the remain the same size at independent of zoom level, but failing that, perhaps make them a little smaller and black?

**Comment by Temdog007** [comment]
Updates

- Changed edit points to be black
- Changed edit points to be sized based on camera zoom

Tube Edit Demo 2

**Comment by looeee** [comment]
Much better! 

Live version:
https://raw.githack.com/Temdog007/three.js/feature/PointsEditor/editor/index.html

One other minor nitpick - it would be nice if the lines updated as you drag the points rather than just jumping to the new position.

**Review by looeee — APPROVED** [review]

**Comment by Temdog007** [comment]
Closing for now. I'll re-implement when #16252 is merged.

**Pull request closed without merging**
