### PR TITLE
docs: Adds `generateMipMaps` option to WebGLRenderTarget

### LINKED ISSUE #21304: docs: Add info about mipmaps in WebGLRenderTarget docs
WebGLRenderTargets sets generateMipmaps to false for the related texture, which differs from the default behaviour of the Texture object, where generateMipmaps is `true` by default:

https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderTarget.js#L35

https://github.com/mrdoob/three.js/blob/master/src/textures/Texture.js#L53

Should we add that to WebGLRenderTarget list of options or at least as a side note?

### PR DESCRIPTION
**Pull request by gsimone**
Fixes #21304

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Not sure we want to add `Set this to true if you need it.` to all booleans in the documentation 😅

**Comment by Mugen87** [comment]
Yeah, this phrase can be removed.

**Comment by Mugen87** [comment]
@mrdoob How about merging this and then I clean everything up? `Set this to true if you need it` appears in a few documents.

**Comment by gsimone** [comment]
Should I remove it from the depthBuffer and stencilBuffer or everywhere?

**Comment by Mugen87** [comment]
I'll clean things up 👍 .

**Comment by mrdoob** [comment]
> @mrdoob How about merging this and then I clean everything up? `Set this to true if you need it` appears in a few documents.

Sounds good!

**Pull request merged**
