### PR TITLE
Scalable Ambient Occlusion (SAO) post processing effect

### PR DESCRIPTION
**Pull request by bhouston**
This won't get merged because it is dependent upon the procedural.glsl PR here: https://github.com/mrdoob/three.js/pull/8603

But this is a PR that implements the core of a Scalable Ambient Occlusion shader as discussed here: https://github.com/mrdoob/three.js/issues/6446

This is the core of the shader, it is still missing the edge aware blurs in both the horizontal and vertical directions for non-noisy results.

### CODE REVIEW

**Comment by bhouston** [comment]
Example link:

http://ci.threejs.org/api/pullrequests/8605/examples/webgl_postprocessing_sao.html

Looks like this:

image

**Comment by bhouston** [comment]
I rewrote this to actually be correct and these are the new results:

Beauty+SAO:

image

SAO only:

image

Normals derived from Depth Buffer:
image

**Comment by mrdoob** [comment]
Oh, this one needs rebasing now...

**Comment by bhouston** [comment]
@WestLangley what do you think about having this SAO pass (just the ambient darkening 2D screenspace texture) as an input to a beauty pass render, I guess as a parameter to MeshStandardMaterial.ssaoMap.  It would enable ssao to darken just indirect light rather than all light as is currently happening when applying the SAO pass as a post effect.

The render path would be:

1) Render depth to depthMap via MeshDepthMaterial
2) Render SAO effect using depthMap to an ssaoMap
3) Improve quality of SAO effect via blurs (working on this now.)
4) Render beauty pass using ssaoMap as the aoMap thus reducing indirect illumination.

I think that could be very compelling solution.

I think that if we were to merge my THREE.Map PR from a few weeks ago we could actually easily add support for screenspace UVs for specific maps (such as aoMap being based on SSAO or SAO) rather than always either using a hard-coded uv or uv2 channels.  (Just an idea for you @mrdoob.)

BTW it is crazy hard to maintain my fork of ThreeJS (which is necessary because we need some unmerged PRs) now that we are collapsing change sets. :/

**Comment by mrdoob** [comment]
> BTW it is crazy hard to maintain my fork of ThreeJS (which is necessary because we need some unmerged PRs) now that we are collapsing change sets. :/

Which are those unmerged PRs? (So I can give them more priority)

**Comment by WestLangley** [comment]
> It would enable ssao to darken just indirect light rather than all light as is currently happening when applying the SAO pass as a post effect.

Hmmm. Interesting... Yes, SSAO should occlude only ambient light. Your proposal is to create an ambient occlusion map in real time and set it to be `material.aoMap`, which is the right solution.

Automating that for the user is something we could add later. But I think having an example demonstrating the manual approach would be a good idea. Unless there is a lot of ambient light relative to direct light in the example, the effect may be hard to see.

**Comment by bhouston** [comment]
> Unless there is a lot of ambient light relative to direct light in the example, the effect may be hard to see.

There is if it is an IBL-based scene, there are tons of indirect specular light.  That is my primary interest anyhow, like the setup in the envmap_hdr example.

**Comment by mrdoob** [comment]
@bhouston I think the changes in #8603 are conflicting with this PR.

**Comment by WestLangley** [comment]
>There is if it is an IBL-based scene, there are tons of indirect specular light. 

Ah, yes. We now occlude ambient specular, too. : - )

**Comment by bhouston** [comment]
@mrdoob wrote:
> Which are those unmerged PRs? (So I can give them more priority)

You do not have to merge every PR we need, I do not want to force you to accept things you do not want.  That is why it is okay for us (and there are many others) to have our forks.  But since you asked :), the main PR that we need is the THREE.Map PR that allows for per-map uv/offset and choosing which uv channel to use: https://github.com/mrdoob/three.js/pull/8278

**Comment by mrdoob** [comment]
Cool! Yep, I haven't read that one yet. I'm trying to don't overload myself.
I'll take care of textures/maps next cycle 😇

**Comment by bhouston** [comment]
Going to resubmit as it has been rewritten.

**Pull request closed without merging**
