### PR TITLE
Improve vr haptics example

### PR DESCRIPTION
**Pull request by zz85**
**Description**

- make audio more pleasant
  a) changing frequency to a pentatonic
  b) changing oscillator from square to sine type
- fix a bug so multiple boxes can simultaneously light up when
  more than 1 controllers is used

before 
image

after
image

https://raw.githack.com/zz85/three.js/improve_haptics/examples/webxr_vr_haptics.html

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, I'm getting this...?

Screen Shot 2022-01-24 at 12 24 25 PM

**Comment by zz85** [comment]
ahhh silly me, that's an off-by-one error - i had one less note in the music scale than the number of boxes.
now, there can be as many notes as there are boxes (if we increase them)

**Comment by mrdoob** [comment]
I think one note is repeated but it's definitely better than before.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Further improvement ideas: We should just just use https://tonejs.github.io/ here. It'll sound much better 🤓

**Comment by zz85** [comment]
> I think one note is repeated but it's definitely better than before.

Right, I shouldn't have include 12 (which is basically the same note as 0). 😅

> Further improvement ideas: We should just just use https://tonejs.github.io/ here. It'll sound much better 🤓

I was just looking at that too... looks tone.js can do a lot if we are ok with pulling an extra dependency

**Pull request merged**
