### PR TITLE
WebGLTextures: Fix depth textures with multisampling.

### LINKED ISSUE #23604: Multisampling effectively disables Depth Texture
**Describe the bug**

`WebGLMultisampleRenderTarget` was removed in #23455  and the functionality was added to `WebGLRenderTarget` with the new `samples` property. However, when using a `DepthTexture` attachment on a render target with multisampling enabled, the depth texture remains empty because [depth is being invalidated](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/renderers/webgl/WebGLTextures.js#L1709-L1714) for performance reasons regarding WebXR. This behaviour was the same with `WebGLMultisampleRenderTarget`, but that class had an undocumented `ignoreDepthForMultisampleCopy` property that allowed to preserve depth. I don't think this property was carried over in r138.

**To Reproduce**

1. Render a scene into a multisample render target that has a depth texture attachment.
2. Render the contents of the depth texture to screen.
3. See empty image.

***Live example***

Uncomment line `60` in `index.js`: [Sandbox](https://codesandbox.io/s/nostalgic-hodgkin-6kvw05?file=/src/index.js)

**Expected behavior**

Depth should be preserved if the multisample render target has a depth texture attachment.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox (white screen), Brave (black screen)
 - Three.js version: r138

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #23604.

**Description**

@vanruesc Looking good?

### CODE REVIEW

**Comment by vanruesc** [comment]
Yes, that fixes it :+1:

**Comment by Mugen87** [comment]
@mrdoob I guess we should cherry-pick this fix to `master`.

**Comment by mrdoob** [comment]
@Mugen87 Will do! 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Cherry-picked into `master` and published `0.138.1`.

**Pull request merged**
