### PR TITLE
Improve SimplifyModifier example and clean up

### PR DESCRIPTION
**Pull request by WestLangley**
Well... IMHO, anyway.

### CODE REVIEW

**Comment by WestLangley** [comment]
Live: https://rawgit.com/WestLangley/three.js/dev-simplifier/examples/webgl_modifier_simplifier.html

**Comment by looeee** [comment]
Looks great! 👍

**Review by looeee — APPROVED** [review]

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
> Are you seeing a black vase on a white background or two white faces in profile sitting on a black background?

I saw the two faces first 😊

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
