### PR TITLE
DRACOLoader: Update to v1.3.1, support typed attributes.

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes https://github.com/donmccurdy/three-gltf-viewer/issues/91.

/cc @ondys

### CODE REVIEW

**Comment by takahirox** [comment]
Do we manage `DRACOLoader` here? I thought master repository is https://github.com/google/draco

**Comment by donmccurdy** [comment]
I don't think we've discussed it before, but I'd prefer to consider three.js's the master copy. If it would be clearer, perhaps we could keep only a minified copy in https://github.com/google/draco, or load it with `require('three/examples/js/loaders/DRACOLoader')`.

**Comment by takahirox** [comment]
OK, I thought draco team has already discussed. If we think Three.js's as master, it'd better to have the loader follow the code style because it's less misleading. Of course, no need to do in this PR.

> perhaps we could keep only a minified copy in https://github.com/google/draco, or load it with require('three/examples/js/loaders/DRACOLoader').

Sounds better. Up to draco team.

**Comment by mrdoob** [comment]
Thanks

**Pull request merged**
