### PR TITLE
Docs: Geometries + part of Core sections translation into french

### PR DESCRIPTION
**Pull request by Mael-Kehl**
Related issue: #24510

Add french translation of : 

- Geometries
- Core
  - BufferAttribute
  - BufferGeometry

to the documentation. 

Modified list.json. 

Hope it'll help.

### CODE REVIEW

**Comment by AlexandreAllard** [comment]
Hey @Mael-Kehl,
Feel free to let us know what you plan on translating, so we don't end up translating two times the same section.

**Comment by Mael-Kehl** [comment]
Hey @AlexandreAllard, actually I  just thought that the "geometry" section was quite essential so I worked on it. I'll let you know if I plan to traduce other parts of the doc. Should I open an issue next time ?

**Comment by Mugen87** [comment]
Please use the existing issue #24510 for discussing translation topics.

**Pull request merged**
