### PR TITLE
Export all types from all type definition files

### PR DESCRIPTION
**Pull request by Methuselah96**
There were some interfaces and types (`ExtrudeGeometryOptions`, `RenderTarget`, etc.) that weren't being exported externally, which this PR fixes.

### CODE REVIEW

**Comment by mrdoob** [comment]
@bhouston are you okay with this change?

**Comment by bhouston** [comment]
This is a good idea.

**Comment by Methuselah96** [comment]
@mrdoob https://github.com/mrdoob/three.js/pull/15861 should also get merged before r102 is released.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mijofr** [comment]
You've introduced a bug on this pull request: you replaced
`export { _Math as Math } from './math/Math';`
with
`export * from './math/Math';`

and broke references to Math module.

**Comment by Methuselah96** [comment]
@mijofr My bad. Fix: https://github.com/mrdoob/three.js/pull/15873.

**Comment by mrdoob** [comment]
Published 0.102.1 to npm with this fixed.

**Pull request merged**
