### PR TITLE
Fix OBJExporter exported file format.

### PR DESCRIPTION
**Pull request by kovacsv**
OBJExporter produced invalid OBJ file in case of missing texture coordinates or vertex normals. Now I fixed it, and write dummy texture coordinates if there aren't any, and write face normals if vertex normals are not exist. In addition I created an example to test the code.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
It seems as though my comments on the PR were lost, so I will repost them...

> OBJExporter produced invalid OBJ file in case of missing texture coordinates or vertex normals

What was invalid about it?

> Now I fixed it, and write dummy texture coordinates if there aren't any

I do not think we should be doing that.

> and write face normals if vertex normals do not exist.

I do not think we should be doing that, either.

Also, if you are going to apply the object matrix to the vertices, you have apply the "normal matrix" to the normals.

**Comment by mrdoob** [comment]
>> OBJExporter produced invalid OBJ file in case of missing texture coordinates or vertex normals

> What was invalid about it?

>> Now I fixed it, and write dummy texture coordinates if there aren't any

> I do not think we should be doing that.

This solution is indeed not perfect, but compared to the amount of code that the right solution would require is very good. Eventually we should convert the `Geometry` to `BufferGeometry` and have only one code path. I would focus on that instead.

> Also, if you are going to apply the object matrix to the vertices, you have apply the "normal matrix" to the normals.

Oh! That's true.

**Comment by kovacsv** [comment]
> It seems as though my comments on the PR were lost, so I will repost them...

Sorry about that, if I made something wrong, but I can't see lost comments.

> What was invalid about it?

With a simple triangle, the old version produced this code:

```
o
v -50 -50 0
v 50 -50 0
v 50 50 0
f 1/1/1 2/2/2 3/3/3
```

It refers to uv and normal indices that are not exist. I know the correct solution would be to change the format of the face command depending on the situation, but I think it is more readable if I only write dummy values and face normals, and do not modify the rest of the code.

> Also, if you are going to apply the object matrix to the vertices, you have apply the "normal matrix" to the normals.

Yes, it is needs to be fixed, although it didn't worked in the original code (with vertex normals), either.

**Comment by WestLangley** [comment]
> I know the correct solution would be to change the format of the face command depending on the situation, but I think it is more readable if I only write dummy values and face normals, and do not modify the rest of the code.

I think that making up data is a very bad idea. Why not simply omit the `vt` lines?

If you would like to improve your testbed, I would suggest the following changes;

You have to properly dispose of geometries. Type `renderer.info` into the console to see why.

	current.geometry.dispose();
	scene.remove ( current );

Avoid `new`

**Comment by kovacsv** [comment]
I didn't want to modify the format of `f` command. As long as the exporter writes it like `f 1/1/1 2/2/2 3/3/3`, it will cause issues with some importers because of missing texture vertices (it should write `f 1//1 2//2 3//3` in this situation, and the same with normal vectors). I think this modification would cause more complicated code, but of course the result would be much better.

I think a correct obj exporter should act like this:
- Write every vertex only once (this is true now)
- If there are no vertex normals, write face normal only once (not free times)
- If there are no uvs, do not write them
- Handle face command format and indexing issues caused by the above modifications

I'm planning to do these modifications, but if you would like to use `BufferGeometry` in the future as mrdoob said, I think it is not a good idea to improve the current method.

Thanks for the example tips, I will modify it.

**Comment by WestLangley** [comment]
Since @mrdoob does not want to pursue this, I am not going to make a big deal out of it.

I know you do not want to modify the format. I was requesting that you not add fake UV data.

    vt 0 0
    vt 0 0
    vt 0 0

**Comment by kovacsv** [comment]
Ok, I will do this modification, thanks.

**Pull request merged**
