### PR TITLE
MeshNormalMaterial: support clipping planes

### PR DESCRIPTION
**Pull request by Oletus**
This fixes rendering of screen space effects depending on normals in the presence of a global clipping plane.

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks! `MeshNormalMaterial` should have supported clipping to begin with.

I understand why you added the example, but I don't think it is needed now that you have made your point. I think the example can be removed from this PR.

**Comment by Oletus** [comment]
Removed the example changes as asked. I mostly did them to just have some way of verifying that my changes were correct. Ready to merge?

**Comment by WestLangley** [comment]
@mrdoob This PR can be merged.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
