### PR TITLE
WebGLRenderer: Create WebGL2 context by default

### LINKED ISSUE #19040: WebGLRenderer: WebGL fallback from WebGL2 does not honor context attributes
Consequently, the attributes must be repeated to take effect.
```js
var canvas = document.createElement( 'canvas' );

var context = canvas.getContext( 'webgl2', { alpha: true } );

renderer = new THREE.WebGLRenderer( { canvas: canvas, context: context, alpha: true } );
```
- [ x ] Dev
- [ x ] r115

### PR DESCRIPTION
**Pull request by mrdoob**
Fixes #19040

### CODE REVIEW

**Comment by fernandojsg** [comment]
weee 👍

**Comment by mrdoob** [comment]
Hmm... I'm seeing regressions...

Before:

Screen Shot 2020-06-10 at 6 44 20 PM

After:

Screen Shot 2020-06-10 at 6 45 03 PM

**Comment by mrdoob** [comment]
@elalish Seems to be the `RoughnessMipmapper` 🤔

You can test this on model-viewer by passing WebGL2 context to the renderer:

```js
var canvas = document.createElement( 'canvas' );
var context = canvas.getContext( 'webgl2', { alpha: false } );
renderer = new THREE.WebGLRenderer( { canvas: canvas, context: context } );
```

**Comment by mrdoob** [comment]
Another regression...

Before:

Screen Shot 2020-06-10 at 9 42 10 PM

After:

Screen Shot 2020-06-10 at 9 41 32 PM

**Comment by Mugen87** [comment]
So if the user needs a WebGL 1 context, it's necessary to create it on application level and pass it into the renderer, right?

**Comment by Mugen87** [comment]
[webgl_mirror_nodes](https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_mirror_nodes.html) is broken with shader compilation errors.

**Comment by Mugen87** [comment]
Should be fixed via 795130a39d2f2d2d81572b4ab40775c45bcf499f.

**Comment by mrdoob** [comment]
> So if the user needs a WebGL 1 context, it's necessary to create it on application level and pass it into the renderer, right?

What would a use case be to not want WebGL 2?

**Comment by Mugen87** [comment]
For example a project does not have the budget to update its shader code but still needs an important bug fix in a never `three.js` version.

**Comment by Mugen87** [comment]
> Seems to be the RoughnessMipmapper 🤔

`webgl_loader_gltf` reports a WebGL warning now:

> [.WebGL-0x7fd1ef043800]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?

**Comment by DefinitelyMaybe** [comment]
> So if the user needs a WebGL 1 context, it's necessary to create it on application level and pass it into the renderer, right?

Look either way someone may have to, as you put it, create it at the application level. I don't know how put this better but basically, the situation is: if you win, someone else losses but if someone else wins, you lose.

Could someone else just confirm that I'm not the only one seeing the entirety of this?

this merged PR appears to put mugen87 into the 'but if someone else wins, you lose.' camp.

**Comment by mrdoob** [comment]
> For example a project does not have the budget to update its shader code (see #19627) but still needs an important bug fix in a newer `three.js` version.

I think that's fair.

Here are 2 possible ways:

```js
new THREE.WebGLRenderer( { forceWebGL1: true } );
```

Or make a new class that extends `WebGLRenderer`.

```js
new THREE.WebGL1Renderer();
```
And the internal code would just do `if ( scope.isWebGL1Renderer === true )`...

I think I prefer the later?

**Comment by Mugen87** [comment]
I'm fine with both. Pick the one you like the best 😇 .

In any event, it's good if we provide users an easy fallback just for the case they struggle with the migration.

**Pull request merged**
