### PR TITLE
webgl_shadowmap_pointlight: customDistanceMaterial is no longer required

### PR DESCRIPTION
**Pull request by WestLangley**
Related: #25000

What would be nice is an example where a custom distance material, or depth material,  _is_ required.

### CODE REVIEW

**Comment by mrdoob** [comment]
> What would be nice is an example where a custom distance material, or depth material, is required.

If you can you think of and describe an example that would need a custom distance material the community can help creating it.

**Comment by linxi6** [comment]
unsubscribe

**Comment by WestLangley** [comment]
I am having a hard time thinking of one... We now handle the common use cases automatically. :-)

**Comment by mrdoob** [comment]
@titansoftime any ideas?

**Comment by titansoftime** [comment]
> @titansoftime any ideas?

I did not think shadows on instanced meshes with materials with alphaTest would be so niche =[

If you can show me an alternate method to achieve this without customDepthMaterial, I would be more than happy to implement.

Here is how your examples showed how to do it previously:

Working r146: https://jsfiddle.net/titansoftime/hncbvgf8/

Not working r147: https://jsfiddle.net/titansoftime/q39foeLb/

**Comment by WestLangley** [comment]
@titansoftime What is the reason you are you not using `InstancedMesh`?

**Comment by WestLangley** [comment]
@titansoftime Hopefully we can modify r148 to accommodate your use case. But, I also expect `InstancedMesh` will work in your use case -- unless you are doing something I am unaware of. Would you be willing to try it?

**Comment by titansoftime** [comment]
I have done a test with `InstancedMesh`. It works quite well. It is nice not having to deal with `customDepthMaterial`. In addition my multi-material meshes with one part alphaTest the other not (trees), now have correct shadows and respect the alpha of the foliage. Very nice.

Ideally this would be the same behavior with meshes created manually using `instancedGeometry`. However, `InstancedMesh` does simplify my workflow, so this works for me.

**Comment by titansoftime** [comment]
Hmm, I am noticing a rather significant performance decrease though. I have not seen my app drop below 60fps since I got a 2070S some years ago. Now dips to low 50's. I need to investigate more what is causing this while using InstanceMesh vs. modified vertex shaders and having to use customDepthMaterial for shadows.

**Pull request merged**
