### PR TITLE
Fix instanced attribute update

### PR DESCRIPTION
**Pull request by taphos**
When instanced attribute of InstancedBufferGeometry is updated and has a different size, the _maxInstanceCount value is not updated. So the amount of rendered instances is wrong. 

The solution is to recalculate _maxInstanceCount on every state change

### CODE REVIEW

**Comment by Mugen87** [comment]
> When instanced attribute of InstancedBufferGeometry is updated and has a different size, the _maxInstanceCount value is not updated.

It is not intended that `_maxInstanceCount` changes after its initial definition. It's the same policy like the `count` property of `InstancedMesh`:

> The count value passed into the constructor represents the maximum number of instances of this mesh

**Comment by taphos** [comment]
> It is not intended that `_maxInstanceCount` changes after its initial definition. It's the same policy like the `count` property of `InstancedMesh`:
I see, but why not make it changeable? other geometry attribute sizes can be changed. Currently creation of new `InstancedBufferGeometry` is required every time instance count is changed

**Comment by Mugen87** [comment]
> other geometry attribute sizes can be changed.

I don't think that is true. The size of buffer attributes is fixed. Changing the size requires a `dispose()` on geometry level and the creation of new attributes.

**Comment by Mugen87** [comment]
> Currently creation of new InstancedBufferGeometry is required every time instance count is changed

Similar to normal buffer attributes the idea is to create a large enough buffer and then use draw range or `instanceCount ` in context of `InstancedBufferGeometry` to determine what data should be rendered,

**Pull request closed without merging**
