### PR TITLE
Updated glTF Loader to v1.0; more samples

### PR DESCRIPTION
**Pull request by tparisi**
Up to date with the final, ratified spec!! Please have a look and merge at your leisure. Gracias.

### CODE REVIEW

**Comment by bhouston** [comment]
There are hundreds of lines of whitespace changes, it makes it incredibly hard to figure out what was actually changed in this PR.

**Comment by bhouston** [comment]
From what I can tell tabs were converted to spaces and this is responsible for the large majority of diff changes.

**Comment by tparisi** [comment]
I can try to clean this up if people want, please advise

**Comment by bhouston** [comment]
Generally ThreeJS looks to avoid unnecessary tab->spaces chnges: https://github.com/mrdoob/three.js/pull/8119#issuecomment-183552717  https://github.com/mrdoob/three.js/pull/7602#issuecomment-157231874 https://github.com/mrdoob/three.js/pull/7114#issuecomment-138282145

**Comment by tparisi** [comment]
Any suggestions for how to entab this from the current sources? I'm not up for doing hand surgery on it

**Comment by bhouston** [comment]
The root issue is likely a text editor you are using has a setting that is auto-converting tabs to spaces.  They often have the opposite mode available as well.  Alternatively you can do a search of 4 consecutive spaces (I think that is the conversion that was done, but you should check that) and replace that with a tab character.  There are likely other options available.

**Comment by bhouston** [comment]
The best setting for a text editor when contributing to an open source project, or any project that does code reviews, is to not auto-convert tabs to spaces or vice versa.   It just creates noise.

**Comment by mrdoob** [comment]
@bhouston pro-tip: https://github.com/mrdoob/three.js/pull/8218/files?w=1 😁

**Comment by mrdoob** [comment]
Also, I think it's fine for the glTF loader to not follow my weird code style.

**Comment by tparisi** [comment]
Many thanks, sorry for the hassle, I start over with those trouble files. Stay tuned!

**Comment by tparisi** [comment]
@mrdoob :-) love your code style

**Comment by mrdoob** [comment]
@tparisi 

How come the geometry type selector is back?
http://ci.threejs.org/api/pullrequests/8218/examples/index.html#webgl_loader_gltf

Does the loader has logic for generating `THREE.Geometry`? If so, I would remove it.

**Comment by tparisi** [comment]
This is really a design choice... are you saying get rid of the type selector and always generate Buffer Geometry?

**Comment by mrdoob** [comment]
Yes, loaders no longer output `THREE.Geometry`.

**Comment by tparisi** [comment]
KK I'll fix that too

**Comment by Mugen87** [comment]
In the meanwhile `GLTFLoader`/`GLTFLoader2` changed quite substantially.

**Pull request closed without merging**
