### PR TITLE
Nodes: Follow three.js static property style

### PR DESCRIPTION
**Pull request by sunag**
**Description**

The static properties of Three.js don't use all caps by default like `POSITION` but `Position`. I think it's good to adapt `NodeMaterial`  as soon as possible for this style?

```js
// before
new NormalNode( NormalNode.LOCAL );
new PositionNode( PositionNode.VIEW_DIRECTION );

// after
new NormalNode( NormalNode.Local );
new PositionNode( PositionNode.ViewDirection );
```

This contribution is funded by [Google via Igalia](https://igalia.com).

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, it's up to you... But I think the style you were doing was more readable.

**Comment by sunag** [comment]
> Hmm, it's up to you... But I think the style you were doing was more readable.

I understand... But I think it pays off, maybe then we wouldn't have styles competing with each other?

**Comment by mrdoob** [comment]
Hmm... It's mainly because this file, right?
https://github.com/mrdoob/three.js/blob/dev/src/constants.js

**Comment by sunag** [comment]
> Hmm... It's mainly because this file, right?

Yes, yes.. Exactly this and this too:
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/nodes/core/constants.js

**Comment by mrdoob** [comment]
I think I still prefer what you had...

For example:

```js
import { Frustum, Matrix4, Vector3, Color, LinearEncoding } from 'three';
```

It's impossible to tell what is a class and what is a constant. 

This is more readable:

```js
import { Frustum, Matrix4, Vector3, Color, LINEAR_ENCODING } from 'three';
```

But I think what you have done is even better.

For example:

```js
import { Frustum, Matrix4, Vector3, Color, Encoding } from 'three';

texture.encoding = Encoding.LINEAR;
```

So I vote for keeping the current style in the Nodes system.
And maybe, at some point, we could change the constants style in core to be more like the Nodes one.

@Mugen87 What do you think?

**Comment by sunag** [comment]
> So I vote for keeping the current style in the Nodes system.
And maybe, at some point, we could change the constants style in core to be more like the Nodes one.

@mrdoob Yes, there are strong arguments. I also vote for keeping the current style and change the core constants style soon.

**Comment by mrdoob** [comment]
Closing then. We'll update the constants in core some day... 😅

**Pull request closed without merging**
