### PR TITLE
MMDLoader: Detect model extension from file content.

### PR DESCRIPTION
**Pull request by YusakuNo1**
**Description**

Before this change, the MMD model extension is detected from URL ([code](https://github.com/mrdoob/three.js/blob/f2766a0dfc47a790cd64dec6f9b7132d6fee9fa8/examples/jsm/loaders/MMDLoader.js#L134)), this approach won't work for blob url because it's like `blob://https://domain/uuid`. As the author mentioned, it'll be better to detect it by the file content.

**How to test**
For PMD file testing, please use `examples/webgl_loader_mmd.html`
For PMX file testing, please use my test branch which includes the asset from Genshin Impact: https://github.com/YusakuNo1/three.js/tree/yusakuno1/detect-mmd-ext-test-pmx

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: https://rawcdn.githack.com/YusakuNo1/three.js/yusakuno1/detect-mmd-ext/examples/index.html?q=mmd

**Comment by Mugen87** [comment]
@takahirox I've reviewed the PR as good as possible and everything looks fine to. The MMD examples work as before. Merging this now but an additional review later on would still be welcome 👍 .

**Comment by takahirox** [comment]
Thanks, I will try to review later when I have time.

**Comment by takahirox** [comment]
I did quickly review and it looks good to me. I may review more details later if I have time.

**Pull request merged**
