### PR TITLE
src: use single quotes.

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by linbingquan** [comment]
I have a question, how to make sure the source code use single quotes when we are coding?

**Comment by Mugen87** [comment]
I guess that auto-generated imports are responsible for the double-quotes. This is normally an editor/IDE setting.

**Comment by linbingquan** [comment]
> I guess that auto-generated imports are responsible for the double-quotes. This is normally an editor/IDE setting.

I also found there are 332 in `/src/**` has double quotation marks.

**Comment by mrdoob** [comment]
Thanks!

**Comment by DefinitelyMaybe** [comment]
ooo, interesting. anyone know the eslint rule for making thing's single quotes? we could add it in to package.json

**Pull request merged**
