### PR TITLE
Examples: Simplify webgl_loader_json_blender

### PR DESCRIPTION
**Pull request by Mugen87**
This PR removes the collada model so it's easier to understand the loading and processing of the `json` model file (Blender export). I've also done some clean up.

### CODE REVIEW

**Comment by jostschmithals** [comment]
Good deed! From my point of view it is very useful to focus the examples on one single aspect like you did it here (since these are for learning purposes). I always felt that for a beginner (like me) it is much harder to understand them if several things are mixed up.

@Mugen87 BTW (since you are so busy) : I would like to make a thorough revision of the webgl_animation_skinning_blending example, where I notice some bugs and some remnants of legacy code – or are you currently doing the same (we should avoid doubling the work)?

**Comment by jostschmithals** [comment]
An additional suggestion:

What about changing `.setDuration(  1 )` to `.setDuration( 1000 * s )` in line 99? 

In this way the smaller monsters would have to make more effort to keep up with the others and the crowd would look more realistic. 

One could also reduce the lower limit in line 87 to make the effect more noticeable (try 0.00015 and watch the monster babies 😉 ).

**Comment by Mugen87** [comment]
> I would like to make a thorough revision of the webgl_animation_skinning_blending example, where I notice some bugs and some remnants of legacy code – or are you currently doing the same (we should avoid doubling the work)?

Nope. Nice that you revisit this example.

**Comment by Mugen87** [comment]
> since you are so busy

Not really. 😁 It could be worse.

**Comment by Mugen87** [comment]
I think the settings are okay like that. In this way the example is straightforward.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
