### PR TITLE
Add boxselection demo

### PR DESCRIPTION
**Pull request by HypnosNova**
This feacture is very common used in BIM system.
It can help people to drag a box on the screen and then calculate a frustum in 3D space to check which objects are in frustum and these objects are selected.

### CODE REVIEW

**Comment by 06wj** [comment]
[live demo](https://rawgit.com/HypnosNova/three.js/BoxSelection/examples/webgl_interactive_boxselection.html)

**Comment by 11zouzouzou** [comment]
good function

**Comment by HypnosNova** [comment]
I found a small bug and fixed it.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 I think this PR missed a review.

**Comment by Mugen87** [comment]
Yeah, we have missed that. Apart from code style issues, I see a lot of unnecessary object creation in `SelectionBox'. Especially in `SelectionBox.select()` and `SelectionBox.createFrustum()` which are frequently called in the `mousemove` event listener of the example.

@HypnosNova You should try to avoid object instantiation via `new` and `clone()` methods.You might want to wrap `SelectionBox` into a closure and define reusable variables in the new respective scope.

**Comment by HypnosNova** [comment]
@Megun87 OK，i will update code tomorrow

**Comment by HypnosNova** [comment]
OK，i will update code tomorrow@Mugen87

**Comment by WestLangley** [comment]
Thanks, @Mugen87.

**Pull request merged**
