### PR TITLE
Refactor instancing lambert example using `onBeforeCompile`

### PR DESCRIPTION
**Pull request by pailhead**
@mrdoob 

Per our conversation i submit this PR. It shows how to use material glsl injection to reduce some of the boilerplate with alternate approaches. 

Still i'd suggest using a dictionary to store the stuff in a known format (uniforms, attributes, functions, chunks).

This will be the first usage of `onBeforeCompile` outside the example. I'm not super comfortable about that because i think there should be an alternative way to do, so i left a comment pointing to another PR.

ping @WestLangley 

Btw how can i squash all these commits that i dont even understand where are they coming from. Why is stuff before `6b34d6f` showing up?

### CODE REVIEW

**Comment by WestLangley** [comment]
Actually, I am not in favor of the approach used in this PR (using injections and string substitutions) because the shader code is obfuscated; the modified shader is not readable. In the [current listing](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_buffergeometry_instancing_lambert.html) it is.

Users learn from these examples.

**Comment by mrdoob** [comment]
Maybe this is not the best example to add `onBeforeCompile` to actually. I'm hoping that the instancing examples will no longer be relevant as soon as we manage to introduce instancing in core.

**Comment by mrdoob** [comment]
Sorry about that!

**Comment by pailhead** [comment]
Could you elaborate more? The shader code here is not even glsl, it’s just an ordered list of these include statements.

**Comment by mrdoob** [comment]
Ideally, this example should just look something like this:

```js
var geometry =  new THREE.TorusBufferGeometry( 2, 0.5, 8, 128 );
var material = new THREE.MeshLamberMaterial();
var meshes = new THREE.InstancedMesh( geometry, material );
var positions = new THREE.Curves.TorusKnot( 10 ).getSpacedPoints( 256 );
meshes.setPositions( positions );
scene.add( meshes );
```

**Comment by pailhead** [comment]
@mrdoob there are two different things outlined in the example IMHO:

1. how to use a webgl/opengl feature called "instancing" in real life.
2. how to modify existing shader templates to do more stuff. 

`onBeforeCompile` illustrates how to do both, with less code. 

If you remove this example altogether in favor of the suggested API, then this example was a waste of resources. `InstancedMesh` has been proposed a year ago, and is used a lot as an npm module, a better use of resources would be merging `InstancedMesh`. 

I would still use this for an example for `onBeforeCompile`, it doesn't matter that it's specifically illustrating instancing in this case. This feature should be so powerful that theoretically there should be hundreds of different examples by now, but there are none.

**Comment by mrdoob** [comment]
I think this example was just to show how to use built-in materials with instancing with the available code.

> If you remove this example altogether in favor of the suggested API, then this example was a waste of resources. `InstancedMesh` has been proposed a year ago, and is used a lot as an npm module, a better use of resources would be merging `InstancedMesh`.

Please, be mindful with your wording. People don't like to be told that they're wasting their time.

As per the `InstancedMesh` PRs... As far as I remember I think they still had unresolved issues?

**Comment by mrdoob** [comment]
> With `InstancedMesh` is there a reason for this example to stay?

No. But until then, it's useful.

**Comment by pailhead** [comment]
I urge you to reconsider this. For learning purposes it would make sense to keep an example like this, and introduce others.

**Comment by pailhead** [comment]
And possibly add comments in the code to explain where

```glsl 
transformed = ...
```

Suddenly comes from. That part does not seem the most readable to me.

**Comment by pailhead** [comment]
https://github.com/mrdoob/three.js/pull/14069

**Comment by WestLangley** [comment]
@pailhead We are all trying to work through this. We are considering a variety of techniques to see what the pitfalls are. Your contributions and experiments have been very illuminating. It is not always clear what approach is 'best'. Often that is a subjective decision.

All you and I can do is voice an opinion. I have learned to simply state my opinion and avoid prolonged debates. @mrdoob will make a decision and we will move on. I don't take it personally if the decision is not my preference. I think that is good advice for anyone to follow.

Be patient, we will get there! :)

**Comment by pailhead** [comment]
But how do we figure out what's best without debates :D

**Comment by WestLangley** [comment]
We have some debates, but in general, you and I don't decide what's 'best'. @mrdoob makes that judgment call.

**Comment by pailhead** [comment]
But @mrdoob doesn't have the time to even scratch the surface on these debates. When i got some of his precious times, it sounded like he was really in favor of this PR, i think your dismissal influenced his decision, a lot if not completely :)

I would really appreciate a brief discussion here with you, you seemed to have liked this way back in the day:
https://github.com/mrdoob/three.js/pull/10791


>Yes, this PR allows for the replacement of shader chunks. It would be convenient to be able to do that on a per-material-instance basis.
>It could also be useful when using InstancedBufferGeometry with built-in materials. In such a case, one may want to replace begin_vertex or default_normal, for example, with custom shader code.

**Pull request closed without merging**
