### PR TITLE
New RingBufferGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces RingBufferGeometry. I've provided a [jsfiddle](https://jsfiddle.net/6237yvu8/5/) for testing as usual.

### CODE REVIEW

**Comment by WestLangley** [comment]
Nice job, as usual!

I suggest for a future PR, the default params should produce an actual ring -- not a disk.

Perhaps defaults of ( 20, 50, 8, 1 ) would be good.

**Comment by Mugen87** [comment]
> Perhaps defaults of ( 20, 50, 8, 1 ) would be good.

Indeed, that's better.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Feel free to change the defaults btw!

**Pull request merged**
