### PR TITLE
Return UV vector from Texture.transformUv method

### PR DESCRIPTION
**Pull request by jayschwa**
This makes the method consistent with most other vector transformations, and will make it easier to include it in a chain of operations.

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks. If you are changing the API, then the docs need to be updated, too.

@looeee has been very helpful with that.

**Comment by Mugen87** [comment]
I think it's useful to merge this PR. Currently the method returns `undefined` which seems not very consistent.

BTW: The change for `docs/api/textures/Texture.html` is not 100% correct since the return type should be added at the method`s title. It should look like this:
```
<h3>[method:Vector2 transformUv]( uv )</h3>
```
But we can also correct this after merging.

**Comment by mrdoob** [comment]
Merged and fixed.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
