### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
Some style clean up. Also made the animation in `webaudio_timing` FPS independent (it looks a bit crazy on a 144 FPS monitor 😇).

### CODE REVIEW

**Comment by Mugen87** [comment]
I've recently bought a gaming laptop with a 144 FPS screen and realized that all WebGL applications run now with 144 FPS (instead of 60). This high refresh rate was obviously not considered when certain examples were developed 😁

**Comment by mrdoob** [comment]
Yeah... Mea culpa...
But also, never got to figure out a "nice" code to make animations fps independent.

**Comment by Mugen87** [comment]
One annoying issue when using `Clock.getDelta()` is the use case when the resulting delta becomes large because the app becomes inactive (e.g. tab switched or window minimized). This also happens during debugging. In this case, whole scenes can be messed up after the next update. So actually you need something like:
```js
delta = Math.min( clock.getDelta(), MAX_DELTA );
```
However, it's not easy to set a generic value for `MAX_DELTA`. Maybe `0.0167`? How would you handle this issue?

**Comment by Mugen87** [comment]
>  We can use visibilitychange to pause/resume the timer. Rather than modifying THREE.Clock I think I would do a new class, THREE.Timer including this new behaviour.

Using `visibilitychange` sounds great! I've actually used this API in an other project (but I was not sure the approach is okay like that 😅 )

Maybe [YUKA.Time](https://github.com/Mugen87/yuka/blob/master/src/core/Time.js) can help as an orientation for `THREE.Timer`. One thing that annoyed me with `THREE.Clock` is the fact that multiple calls of `Clock.getDelta()` in a single frame return different values. You get the real delta only in the first call. After that, the values are unusable (see https://jsfiddle.net/hrd07tux/).

`YUKA.Time` has an `update()` method which is called once per simulation step. You can then call `getDelta()` and `getElapsed()` as often as you want per frame and you get the expected values. I mean yeah, the additional `update()` call  is a bit inconvenient but at least the getters will work after that^^.

**Comment by mrdoob** [comment]
I feel your pain 😁

Something like `YUKA.Time` sounds good! I always wondered if we could hide that `update()` call by letting classes have their own internal `requestAnimationFrame()` but now that WebVR and WebXR have their own `requestAnimationFrame`s that idea becomes messy.

**Comment by mrdoob** [comment]
Hmm, I guess we'll have to go ahead with this...
https://twitter.com/samccone/status/1184174767798022144

**Comment by mrdoob** [comment]
> I've recently bought a gaming laptop with a 144 FPS screen and realized that all WebGL applications run now at 144 FPS (instead of 60). 

Actually, what browsers/os are you getting 144 FPS with?

**Comment by Mugen87** [comment]
Windows 10 with latest Chrome.

**Comment by mrdoob** [comment]
Do Firefox and Edge do that too?

**Comment by Mugen87** [comment]
Firefox does but not Edge. It seems 72FPS is the maximum.

**Pull request merged**
