### PR TITLE
Editor: Suport window-controls-overlay feature.

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #23153 

**Description**

Editor suport Chrome 97's new feature `window-controls-overlay feature`.

Screenshot:

image

### CODE REVIEW

**Comment by mrdoob** [comment]
Could you share a screenshot of how it looks like?

**Comment by Mugen87** [comment]
https://raw.githack.com/linbingquan/three.js/dev-editor-window-controls-overlay/editor/index.html

**Comment by Mugen87** [comment]
For clarification this only works for PWAs so the editor has to be installed. 

I've tested this with Chrome 97 on Windows 10 but the feature does not work. It works with Chrome Canary 99 though.

Prod:

image

PR:

image

Notice the additional arrow top left. When clicked, it looks like so:

image

@linbingquan Is it possible to activate the collapsed view by default?

**Comment by Mugen87** [comment]
For clarification this only works for PWAs so the editor has to be installed. 

I've tested this with Chrome 97 on Windows 10 but the feature does not work. It works with Chrome Canary 99 though.

Prod:

image

PR:

image

Notice the additional arrow top left. When clicked, it looks like so:

image

@linbingquan Is it possible to activate the collapsed view by default?

**Comment by linbingquan** [comment]
> Is it possible to activate the collapsed view by default?

Unfortunately, it can not be activate the colapsed view by default.

**Comment by linbingquan** [comment]
> Is it possible to activate the collapsed view by default?

Unfortunately, it can not be activate the collapsed view by default.

**Comment by Mugen87** [comment]
I'm not sure it's worth the effort then. Most people do not use the editor as a PWA anyway.

**Comment by mrdoob** [comment]
@linbingquan Have you tried this on MacOS?

**Comment by linbingquan** [comment]
> Have you tried this on MacOS?

Sorry, I don't have MacOS. I'm work on Windows.

**Comment by Mugen87** [comment]
I have tested it on macOS. Like with Windows I can only use it with Canary.

**Comment by mrdoob** [comment]
Let's close this until it makes more sense to adopt it.

**Comment by linbingquan** [comment]
> Is it possible to activate the collapsed view by default?

It can be activate the collapsed view by default.

This feature was supported in Chrome/Edge 105 version,
the latest version of the Chrome/Edge browser is 107.

@mrdoob @Mugen87 Whether we need to re-open this PR?

### link

https://caniuse.com/?search=window-controls-overlay
https://developer.mozilla.org/en-US/docs/Web/API/WindowControlsOverlay#browser_compatibility

**Pull request closed without merging**
