### PR TITLE
Matrix3: Use destructuring in transpose().

### PR DESCRIPTION
**Pull request by LuckyForce**
Related issue: None

**Description**

Changed the Value Change Method with a temporary variable to the Destructuring Assignment Method.
This makes no difference to the end result but is a cleaner and shorter way to swap elements by removing the tmp variable.
https://www.programiz.com/javascript/examples/swap-variables
Because of fewer characters, the code will also be loaded faster.
This is like nearly everything supported by all relevant browsers.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#browser_compatibility

### CODE REVIEW

**Comment by LeviPesin** [comment]
Why did you created 4 PRs for this? Adding commit to the branch will automatically update the commits in the PR.

**Comment by LuckyForce** [comment]
> Why did you created 4 PRs for this? Adding commit to the branch will automatically update the commits in the PR.

Oh I thought I had to make a new PR for that because I ran through formatting issues all the time.

**Comment by LeviPesin** [comment]
You can just add a commit that solves the linting issue and the tests will re-run.

**Comment by LuckyForce** [comment]
> You can just add a commit that solves the linting issue and the tests will re-run.

Okay thx for the info.

**Comment by looeee** [comment]
I ran a quick test to see if there's performance difference between these two approaches. Here's my results in the chrome console. 

```js
let a = 1;
let b = 2;

console.time("deconstruct")
for(let i=200000000; i>=0; --i)
  [a, b] = [b, a];
console.timeEnd("deconstruct")
->  deconstruct: 184.44482421875 ms

console.time("classical")
for(let i=200000000; i>=0; --i) {
  let tmp = a
  a = b
  b = tmp
}
console.timeEnd("classical")
-> classical: 123.804931640625 ms
```

This is an artificial benchmark, and I only ran it a couple of times - it would be a good idea to test with two versions of the real transpose function on multiple browsers before reaching a conclusion. But it shows that there may performance differences.

**Comment by Mugen87** [comment]
I've made a test with JSBench and the new code is more than 50% slower.

image

**Comment by WestLangley** [comment]
@Mugen87 On JSBench, I think the `for` loop is unnecessary.

Regardless, on my M1 iMac, there is no difference with Safari.

With Chrome, destructuring assignment is 33% slower.

With Firefox, destructuring assignment is 95% slower.

**Comment by mrdoob** [comment]
Sounds like we should keep the current code.

**Comment by mrdoob** [comment]
Thanks though!

**Pull request closed without merging**
