### PR TITLE
Timer: Added FixedTimer

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #17912

**Description**

Moved the `_fixedDelta` and `_useFixedDelta` functionality into its own `FixedTimer` class and removed the `enableFixedDelta()` and `disableFixedDelta()` methods.

I think this approach is cleaner... but I'm not sure how `FixedTimer` is supposed to be used.

@Mugen87 I guess it's supposed to be used for debugging? https://github.com/mrdoob/three.js/pull/17912#issuecomment-553411218

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
Very nice for physics or delta-based simulation, also see https://gafferongames.com/post/fix_your_timestep.

**Comment by mrdoob** [comment]
Hmm...

In the context of physics in the browser, isn't this better?

```js
const fps = 60;

setInterval( step, 1000 / fps );

function step() {

    world.stepSimulation( 1000 / fps, 10 );
    ...

}
```

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/physics/AmmoPhysics.js#L265
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/physics/RapierPhysics.js#L209

Otherwise, `FixedTimer` would need to have more logic inside if we want to emulate 60fps.

**Comment by Mugen87** [comment]
The idea of fixed time deltas comes from Unity: https://docs.unity3d.com/ScriptReference/Time.html. They describe their property as follows:

> The interval in seconds at which physics and other fixed frame rate updates (like MonoBehaviour's FixedUpdate) are performed.

I have found it useful by myself if I can configure a fixed time delta for testing purposes. When computing a delta based on animation loops, you never get _exact_ delta values that might be required in certain scenarios.

**Comment by Mugen87** [comment]
Does the `setInterval()` actually compute _exact_ time deltas? I'm asking since I don't know how precise `setInterval()` actually is.

**Comment by mrdoob** [comment]
Using `setInterval()` we can update a function at `60fps` even if the device runs at `120fps`.

Then we compute the deltas ourselves:
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/physics/AmmoPhysics.js#L209

I can imagine `new FixedTimer()` being useful for debugging, but I'm just not sure how it's supposed to be used for physics.

**Comment by CodyJasonBennett** [comment]
I had misunderstood how this class worked. Physics wants to subdivide the real delta time as per the reference I linked, which is not what this class does.

**Comment by Mugen87** [comment]
Indeed, we can't use it for physics but `FixedTimer` still has its value for testing purposes. Do you think this use case justifies to keep `FixedTimer`?

I think the refactoring definitely makes sense and the PR in its current state looks good to me.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
I think we can keep `FixedTimer` yeah.

I'll remove the references to `fixedDelta` in the docs.

**Pull request merged**
