### PR TITLE
quadtree sphere

### PR DESCRIPTION
**Pull request by tomasparks**
pull request for https://github.com/mrdoob/three.js/issues/6414
working protype

### CODE REVIEW

**Comment by mrdoob** [comment]
1628 files changed... 😄?

**Comment by tomasparks** [comment]
i removed all the three.js code that I was not changing

**Comment by benaadams** [comment]
@tomasparks but a remove/delete counts as a change; so if this PR was merged it would remove all of Three.js except the quadsphere

**Comment by tomasparks** [comment]
my mistake how do I pull three.js back into my fork?

**Comment by benaadams** [comment]
Probably best to create a new branch (so you keep your code in current one), 

at command line make sure you are in new branch, then pull three.js into it:

git pull -f https://github.com/mrdoob/three.js.git master

then copy your new code over into it, hopefully that should work?

**Comment by tomasparks** [comment]
fixed I hope :+1:

**Comment by mrdoob** [comment]
I think you can remove the *~ files. Those are backup files.
Do you mind creating a new PR?

**Comment by tomasparks** [comment]
ok removed backups and tried creating a new PR (pull request) it forwarded me back here :(

**Comment by benaadams** [comment]
Are you ok with using git on command line? If so try:
```
git rebase -i HEAD~21
```
This should open an editor and you should see your 20 commits and 1 from mrdoob ```Fixed sound example.``` and they should all be prefixed with ```pick```.

In the editor change all the ```pick``` to ```squash``` except mrdoob's and the one closest to it; this will merge all the commits into a single one. Save and exit the editor; it will then open it again and ask how to merge the commit messages, so edit this down to the one message you want, again save and exit.

Now you should have a nice local repository; however it will be in conflict with the one in github and if you do a sync it will mix up all the changes. So you need to do a force push to overwrite the published repository:

```
git push -f
```
This will also automatically update it here.

**Comment by tomasparks** [comment]
sorry I am total confused with what I got to change in this list

s 94092d1 Updated builds.
s 2f36e6a Editor: Script syntax error robustness.
s 498475b *Animation: Clean up.
s b61ead7 Simplified example.
s 1aabcb3 Examples clean up.
s d8eb183 Added vr_video example.
s eee2319 r71
s e7bac19 Updated vr_video example.
s f73593b Added credits to vr video example.
pick d49bb0e Fixed sound example.
pick c3d0a67 add quadsphere
pick 22cbacc add quadsphere
pick c0e6878 update
pick e6e3e4f update
pick 4f2ccc2 moved to examples
pick b95b979 updated
pick 1d94111 updated
pick 5c52da6 removing three.js code
pick 79384ea fixed
pick f24e071 Create README.md
pick 8daa641 Update README.md
pick b0b533a fixed

**Comment by benaadams** [comment]
I think you might want to start afresh as it looks like your branch has got messed up.

You'll need to create a new branch from source and go from there, unfortunately my git skills haven't reached the level to advise. I'll normally keep an unchanged branch around so I can start from there.

**Comment by tomasparks** [comment]
I delete my three.js repo and reforked it
then readded the  quadsphere patch
https://github.com/mrdoob/three.js/pull/6452

**Pull request closed without merging**
