### PR TITLE
Adds physics model parser to ColladaLoader.js

### PR DESCRIPTION
**Pull request by ferrolho**
Title pretty much explains it...

Current physics model elements being parsed:
- [x] inertia
- [x] mass

### CODE REVIEW

**Comment by Mugen87** [comment]
Interesting! What can you do with these data?

**Comment by ferrolho** [comment]
I am working on a robotics side project of mine. Robot models have physical properties associated with their physical structure (links, joints, actuator torques, etc.) which are required to compute inertial matrices if you were to consider dynamics or forces in your model. These pieces of information are stored in the `.dae` model and I wrote this so I could access them with Three.js.

**Comment by ferrolho** [comment]
Sorry, my previous comment might be a bit too much to digest. Let me try to give a more intuitive thought about what this kind of information is useful for.

When a robot is in a certain configuration/pose, you might — for whatever motives you may have — want to visualize the robot's ability to move with a certain velocity in a specific direction. This is the so-called *velocity ellipsoid* — cf. Fig. 1.

`Figure 1: Velocity ellipsoid of the ABB IRB 120-3/0.6 at the shown configuration.`
Velocity ellipsoid

The next thing you might be interested to visualize (and this is what I am working on right now) is the ability of the robot to *accelerate* in a certain direction. This is given by the so-called acceleration ellipsoid, which requires the *inertial matrix* of the robot to be computed.

I hope this was clearer... :wink:

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
OMG, the scope of Collada is really astonishing...

**Comment by ferrolho** [comment]
It certainly is! I was so impressed when I found out it contained this information.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
