### PR TITLE
NodeMaterialLoader and improvements

### PR DESCRIPTION
**Pull request by sunag**
### Loader
https://rawgit.com/sunag/three.js/90dev3/examples/?q=node#webgl_loader_nodes

### toJSON
https://rawgit.com/sunag/three.js/90dev3/examples/?q=node#webgl_materials_nodes

### Features
- `NodeMaterialLoader`: `Materials`, `PostProcessing`, `Sprite` and all `Nodes` available.
- `webgl_loader_nodes` example
- new `serialize` and `unserialize` test in `webgl_materials_nodes` 
- Code `NodeMaterialLoader` test in: (`webgl_materials_nodes`, `webgl_mirror_nodes`, `webgl_postprocessing_nodes`, `webgl_webgl_sprites_nodes_nodes`)
- Auto `Node.updateFrame` (it is not longer necessary to use `Node.requestUpdate`)
- `NodeMaterial.nodes` all nodes

### Changes
- Rename `NodeMaterial.requestAttribs` to `NodeMaterial.requires`
- Rename `NodeMaterial.requires.light` to `NodeMaterial.requires.lights`
- Rename `NodeMaterial.requestUpdateFrame` to `NodeMaterial.updaters`
- Removed `Node.requestUpdate`

### CODE REVIEW

**Comment by WestLangley** [comment]
This is sweet! I believe we discussed at one point the possibility of implementing a graphical API on top of this...

**Comment by mrdoob** [comment]
> This is sweet! I believe we discussed at one point the possibility of implementing a graphical API on top of this...

That would be sweet indeed!

**Comment by mrdoob** [comment]
Thanks!

**Comment by sunag** [comment]
my suggestion to keep the previous version on top of the new:

**Proxy**
```javascript
THREE.MeshPhongMaterial2 = function () {

	this.node = new THREE.PhongNode();

	THREE.NodeMaterial.call( this, this.node, this.node );

	this.type = "MeshPhongMaterial2";
	
};

THREE.MeshPhongMaterial2.prototype = Object.create( THREE.NodeMaterial.prototype );
THREE.MeshPhongMaterial2.prototype.constructor = THREE.MeshPhongMaterial2;

Object.defineProperties( THREE.MeshPhongMaterial2.prototype, {
	color: {
		get: function () {

			return this.node.color.value;

		},
		set: function ( val ) {

			this.node.color.value = val;

		}
	},
	shininess: {
		get: function () {

			return this.node.shininess.number;

		},
		set: function ( val ) {

			this.node.shininess.number = val;

		}
	}
// all others...
} );
```

**Usage**
```javascript
// legacy usage
var mtl = new THREE.MeshPhongMaterial2();
mtl.color.set( 0x0066FF );
mtl.shininess = 50;
// or too new usage
mtl.node.color = new THREE.PositionNode();
```

**Comment by sunag** [comment]
`MeshPhongMaterial2` as `MeshPhongMaterial`

**Comment by mrdoob** [comment]
Uh?

**Comment by sunag** [comment]
1. Replace (`MeshPhongMaterial`, `MeshStandardMaterial`... and others) to `NodeMaterial` extended material for example:

```javascript
THREE.MeshPhongMaterial = function () {

	this.node = new THREE.PhongNode();

	THREE.NodeMaterial.call( this, this.node, this.node );

	this.type = "MeshPhongMaterial";
	
};

THREE.MeshPhongMaterial.prototype = Object.create( THREE.NodeMaterial.prototype );
THREE.MeshPhongMaterial.prototype.constructor = THREE.MeshPhongMaterial;

Object.defineProperties( THREE.MeshPhongMaterial.prototype, {
	color: {
		get: function () {

			return this.node.color.value;

		},
		set: function ( val ) {

			this.node.color.value = val;

		}
	},
	shininess: {
		get: function () {

			return this.node.shininess.number;

		},
		set: function ( val ) {

			this.node.shininess.number = val;

		}
	}
// all others...
} );
```
***Usage***
```javascript
// legacy usage
var mtl = new THREE.MeshPhongMaterial();
mtl.color.set( 0x0066FF );
mtl.shininess = 50;
// or too new usage
mtl.node.color = new THREE.PositionNode();
```
2. Remove `refreshUniformsCommon`, `refreshUniformsPhong` and others in 'WebGLRenderer' . This will no longer be neccesary.

https://github.com/mrdoob/three.js/blob/3e81fbc52d8e244783c9c5760754f8870bb57a49/src/renderers/WebGLRenderer.js#L1844

3. Auto `NodeMaterial.build()` in `WebGLRenderer`

4. More `params` in `Node.generate` to `WebGL2` and `DeferredRenderer`

**Comment by sunag** [comment]
of course it will take everything nodes to ES2015

**Comment by mrdoob** [comment]
Oh, I see. You mean that if we wanted to switch the current material system to the node based, that's how we could do it.

**Comment by WestLangley** [comment]
Would such a change also have the added benefit of making the renderer material-agnostic?

**Comment by sunag** [comment]
> Oh, I see. You mean that if we wanted to switch the current material system to the node based, that's how we could do it.

Yes, too is backwards compatible. It seems the quickest solution and will simplify the `WebGLRenderer` too.

> Would such a change also have the added benefit of making the renderer material-agnostic?

That's it. and it is not hard:

https://github.com/mrdoob/three.js/blob/67a2848f5f7c9319a2b6fc37203bd775253e8da4/examples/js/nodes/inputs/TextureNode.js#L46

for example:

```javascript
switch( builder.webGLVersion ) {
		
	case 1: 
		method = "texture2D";
		break;
		
	case 2: 
		method = "texture";
		break;
		
}
```

**Comment by mrdoob** [comment]
Interesssting...

**Comment by sunag** [comment]
> Would such a change also have the added benefit of making the renderer material-agnostic?

reading again... I think you was thinking something like that?

```javascript
// get method name from a abstract renderer
// e.g: "texture2D" to webgl1 
// or "texture" to webgl2
method = builder.getMethod( "texture2d" );
```

**Comment by WestLangley** [comment]
>Would such a change also have the added benefit of making the renderer material-agnostic?

What I mean is, the renderer would no longer have to use this pattern:
```javascript
if ( material.isMeshPhongMaterial ||
	material.isMeshLambertMaterial ||
	material.isMeshBasicMaterial ||
	material.isMeshStandardMaterial ||
	material.isShaderMaterial ||
	material.skinning ) {
```
and uniforms would be updated for all materials, not just select "built-in" ones.

**Comment by sunag** [comment]
> What I mean is, the renderer would no longer have to use this pattern:

Ah. Yes, yes. and is about it I was talking about simplification in `WebGLRenderer`...

**Comment by sunag** [comment]
I will make a PR to a possible implementation still to r90.

**Comment by mrdoob** [comment]
It's likely that it'll slide r91, but the sooner we see the implications of the change the better.

**Comment by sunag** [comment]
I think the biggest changes will be in eliminating the defines `USE_...` in shader: and adapt it...

```glsl
defined( USE_MAP ) 
defined( USE_BUMPMAP )
defined( USE_NORMALMAP )
defined( USE_SPECULARMAP )
defined( USE_ALPHAMAP )
defined( USE_EMISSIVEMAP )
defined( USE_ROUGHNESSMAP )
defined( USE_METALNESSMAP )
```

**Comment by sunag** [comment]
I was thinking in create a parser to use glsl functions in nodes using `directives`

https://github.com/mrdoob/three.js/blob/846d03adc9d9835f67369c512b2ceade4613a258/src/renderers/shaders/ShaderChunk/cube_uv_reflection_fragment.glsl#L102

```glsl
#builtin_node
#define cubeUV_maxLods3 (log2(cubeUV_textureSize*0.25) - 3.0)

#builtin_node
vec4 textureCubeUV(vec3 reflectedDirection, float roughness ) {
...
```

To use `NodeLib.get( "textureCubeUV" )`

Or convert to `FunctionNode`, for example:

```javascript
var textureCubeUV = new FunctionNode(
"vec4 textureCubeUV(vec3 reflectedDirection, float roughness ) {\
	float roughnessVal = roughness* cubeUV_maxLods3;\
	float r1 = floor(roughnessVal);\
	float r2 = r1 + 1.0;\
	float t = fract(roughnessVal);\
	vec2 mipInfo = MipLevelInfo(reflectedDirection, r1, roughness);\
	float s = mipInfo.y;\
	float level0 = mipInfo.x;\
	float level1 = level0 + 1.0;\
	level1 = level1 > 5.0 ? 5.0 : level1;\
\
	// round to nearest mipmap if we are not interpolating.\
	level0 += min( floor( s + 0.5 ), 5.0 );\
\
	// Tri linear interpolation.\
	vec2 uv_10 = getCubeUV(reflectedDirection, r1, level0);\
	vec4 color10 = envMapTexelToLinear(texture2D(envMap, uv_10));\
\
	vec2 uv_20 = getCubeUV(reflectedDirection, r2, level0);\
	vec4 color20 = envMapTexelToLinear(texture2D(envMap, uv_20));\
\
	vec4 result = mix(color10, color20, t);\
\
	return vec4(result.rgb, 1.0);\
}", [ getCubeUV ] );
```
At some point these functions have to be converted to nodes to optimization

**Comment by sunag** [comment]
But I believe that using the second example `FunctionNode` it is still the best solution...

**Comment by trusktr** [comment]
This is really cool. If the current materials (f.e. `MeshPhongMaterial`, `MeshStandardMaterial`, etc) were refactored to be made from these nodes, they'd be a lot easier to customize.

**Comment by sunag** [comment]
@mrdoob  @WestLangley 

What it is like this:
`#if defined( USE_ENVMAP ) && defined( PHYSICAL ) && defined( ENVMAP_TYPE_CUBE_UV )`

And not this: ?
`#if defined( USE_ENVMAP ) && defined( PHYSICAL )`

https://github.com/mrdoob/three.js/blob/495e8cbc4a20614497644c95a1fa3d15274976cd/src/renderers/shaders/ShaderChunk/lights_template.glsl#L125

https://github.com/mrdoob/three.js/blob/8701e404874bc603b814b7ea50aaf5216cd2c9ef/src/renderers/shaders/ShaderChunk/lights_pars.glsl#L175

**Comment by WestLangley** [comment]
@sunag It will be, eventually.

Not all browsers/OS mipmap across cube map seams. (MacOS/Chrome and iOS/Safari appear to, now. Maybe others.) Consequently, the highest mipmapped textures looked terrible, so I temporarily removed the indirect irradiance term.

We definitely need to use the correct max-mipmap level, however. I assume that will have to be passed in as a uniform.

**Comment by sunag** [comment]
@WestLangley It happens same using `texture2DLodEXT` and `GL_EXT_shader_texture_lod`?

**Comment by sunag** [comment]
I see the PR `PMREM` of @bhouston. that makes sense... For me `textureLod` fixed many seams problems... but I think that to a irradiance map it is not sufficient. at any moment a `PMREM` will be merged in `threejs core`?

**Comment by WestLangley** [comment]
>at any moment a PMREM will be merged in threejs core?

It was my understanding that PMREM is a temporary solution. However, I do not want to tell you something that is not correct. /ping @bhouston

**Pull request merged**
