### PR TITLE
Sky shader cleanup

### PR DESCRIPTION
**Pull request by Oletus**
Use template literals for the sky shader GLSL and clean up some redundant computation.

### CODE REVIEW

**Comment by Oletus** [comment]
Another idea also came to mind: Should depthWrite be disabled in the sky shader? I'm not sure if there's some reason to leave it enabled. Transform logic could also maybe be simplified, but only if it's assumed that the sky always covers the viewport completely, which may not be a safe assumption to make.

**Comment by Mugen87** [comment]
> Use template literals for the sky shader GLSL 

There is already #18524 which exclusively focuses on template literals. I think it's better to avoid doing this change here and leave this up for #18524.

**Comment by Oletus** [comment]
> There is already #18524 which exclusively focuses on template literals. I think it's better to avoid doing this change here and leave this up for #18524.

Ah, okay. I'll wait until the template literal change is merged and then rebase the rest of this. Any thoughts on disabling depthWrite?

**Comment by Mugen87** [comment]
Great! And yeah, I think disabling `depthWrite`(and `depthTest`) makes totally sense. Especially since we can consider `THREE.Sky` as an alternative to `Scene.background`. You would not use both at the same time.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/18524#issuecomment-597922193

**Comment by Oletus** [comment]
Opened new PR without the template literals: https://github.com/mrdoob/three.js/pull/18879

Closing this one.

**Pull request closed without merging**
