### PR TITLE
Regression Testing: Updating 3 screenshots.

### PR DESCRIPTION
**Pull request by munrocket**

### CODE REVIEW

**Comment by munrocket** [comment]
I am updated 3 screenshot and all looks ok... but actually I am updated one screenshot with a bug in GLTF loader in dev branch.

Look here please:
expected: https://threejs.org/examples/?q=ligh#webgl_lightshafts
actual:https://rawcdn.githack.com/munrocket/three.js/e63612ca1090354a42a87a9b040fa8696b5e803d/examples/webgl_lightshafts.html

Can you notice that FrontSide changed to BackSide?

**Comment by Mugen87** [comment]
Can you please replace this line:
https://github.com/mrdoob/three.js/blob/d2811b6d3b28c10e365b40e5d6da4083119a02d5/examples/webgl_lightshafts.html#L154
with 
```js
child.material.depthWrite = true;
```
That should fix the example for now. It seems the model has problems in general and maybe need to be changed/replaced in the future.

**Comment by munrocket** [comment]
@Mugen87 it works, thanks!

**Comment by Mugen87** [comment]
Merging this for now so the Travis builds no longer fail

**Comment by Mugen87** [comment]
@munrocket Sorry, I've accidentally deleted your comment. Not sure why, but I had some issues with the github GUI on my smartphone today.

**Comment by munrocket** [comment]
np!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
