### PR TITLE
OrbitControls.d.ts : add missing properties and reorganise to match original src

### PR DESCRIPTION
**Pull request by webprofusion-chrisc**
When using TypeScript existing code fails to compile due to missing properties in OrbitControls type definition.  Add missing properties and reorganise to match order of original src file for easier diff.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
The indentation in this file seems to be inconsistent.

**Comment by webprofusion-chrisc** [comment]
@mrdoob sorry, used the github editor, feel free to edit.

**Comment by Mugen87** [comment]
@mrdoob It seems that all original TS files were committed with soft instead of hard tabs.

**Comment by webprofusion-chrisc** [comment]
Sorry, I can look at this again in about a week or so if need be. 

Off topic, but related : To be honest I don't understand the current js/jsm split of OrbitControls as one single .ts could have been used to output generated the type definitions, the docs (these type defs also need jsdoc comments), the .js module version and the .js examples version (with some transforms). I'm probably missing some discussion - perhaps the jsm is generated rather than being a fork of the original?

**Comment by Mugen87** [comment]
>  I'm probably missing some discussion - perhaps the jsm is generated rather than being a fork of the original.

Correct. Have a look at [modularize.js](https://github.com/mrdoob/three.js/blob/dev/utils/modularize.js).

**Comment by webprofusion-chrisc** [comment]
Whitespace normalised as per .editorconfig now. Was considering copying over jsdoc comments but will leave that to another PR.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
