### PR TITLE
add missing import

### PR DESCRIPTION
**Pull request by aardgoose**
Missing import

flagged by eslint

eslint also flagged several variable redeclarations.  Do you want these fixed?

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> eslint also flagged several variable redeclarations. Do you want these fixed?

Yes please 😇

**Comment by donmccurdy** [comment]
Thanks! We should look into why the modulators script is missing these, or they’ll get reverted in the future.

**Comment by aardgoose** [comment]
OK, I wasn't sure if this was automated or not.  But obviously it is.

**Pull request merged**
