### PR TITLE
lil-gui 0.11.0 → 0.16.0

### PR DESCRIPTION
**Pull request by georgealways**
No earth-shattering changes (here's the [full changelog](https://github.com/georgealways/lil-gui/blob/master/Changelog.md)). Mostly fixes and a little more dat.gui parity.

I would say these are the top 5 additions since 0.11.0:

- Number input fields can be dragged vertically.
- Number input fields show a better keyboard on iOS.
- Added `onFinishChange` to `Controller` and `GUI`.
- Added `gui.show()` and `hide()`.
- Minor CSS bug fixes, better CSS minification.

All told, the library has grown by ~0.93kb minified and ~0.11kb gzipped. 

	0.11.0 = 28.12kb, 8.17kb gzipped
	0.16.0 = 29.05kb, 8.28kb gzipped

If you want to take a close look at the changes, this is [a diff of the built source between both versions](https://www.diffchecker.com/AEopToky). (That site's not the greatest, but I don't know of a way to restrict GitHub's "compare" view to my src directory?)

I tested out a handful of examples for sanity, but not exhaustively.

Anyway, lemme know how that all looks, and happy new year!

### CODE REVIEW

**Comment by mrdoob** [comment]
Happy new year George!

**Comment by Mugen87** [comment]
It seems the broke the GUI in https://raw.githack.com/mrdoob/three.js/dev/examples/webxr_vr_layers.html.

`lil-gui` is used here in VR to control the distance of UI elements from the user. The `lil-gui` container is still visible however the label of `eyeChartDistanceFt ` is missing now. Tested on a Quest 2 with latest Oculus browser.

**Comment by georgealways** [comment]
@Mugen87 ooh, thanks for the catch! Is there an easy way for me to debug this without the Oculus browser? Also, do you mind taking a screenshot?

**Comment by Mugen87** [comment]
@georgealways Never mind! The issue was in `HTMLMesh`.

**Comment by georgealways** [comment]
@Mugen87 oh nice, glad you tracked it down

**Pull request merged**
