### PR TITLE
Deprecate BufferAttribute  and InterleavedBuffer .setArray 

### PR DESCRIPTION
**Pull request by aardgoose**
As discussed #17418 etc. 

Precursor to #17445 after which .setArray will fail if used to change the size of a buffer.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@mrdoob Is it okay to merge this PR? I'd really like to get the `.dynamic` issue out of the world 😇

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@Mugen87 Can we do the `.dynamic` change in r110?

**Comment by Mugen87** [comment]
Okay 😊 

BTW: I have not forgot your suggestion about `BufferAttribute.setAttribute()` and `BufferAttribute.deleteAttribute()`^^. If you like, we can rename the methods in `R110`, too.

**Comment by mrdoob** [comment]
I [sneakily](https://github.com/mrdoob/three.js/commit/eab99103aff8b3bb121cb1dd54ba4bcc3e7fd7ed) added a `setAttribute()` already 😇

**Pull request merged**
