### PR TITLE
fromGeometry to create indexed geometry

### PR DESCRIPTION
**Pull request by benaadams**

### CODE REVIEW

**Comment by benaadams** [comment]
@mrdoob added custom attributes as well

**Comment by benaadams** [comment]
Will try to get some dynamic updates in...

**Comment by benaadams** [comment]
* generate indexed geometry from objects
* custom attribute generation from objects
* vertex mapping from object data to buffer data for dynamic updates
* vertex remapping post drawcall chunk generation

**Comment by mrdoob** [comment]
Ok... I think I've found the solution (saner approach)...

030c33c14f579047d900ed40a1cb91e2c23c613d shows a bit the idea...

I think it will be best to ignore dynamic/skinned/morphtargets `THREE.Geometry`. We can convert those to `THREE.BufferGeometry` but starting from `r72` those will now become static. If the user wants these animated they will have to use `THREE.DynamicGeometry` instead.

`THREE.DynamicGeometry` would then be something in between `THREE.Geometry` and `THREE.BufferGeometry`. It would be a user-friendly geometry structure that maps more directly to `THREE.BufferGeometry`. Something like this:

```javascript
THREE.DynamicGeometry = function () {

	Object.defineProperty( this, 'id', { value: THREE.GeometryIdCount ++ } );

	this.uuid = THREE.Math.generateUUID();

	this.name = '';
	this.type = 'DynamicGeometry';

	this.vertices = [];
	this.colors = [];
	this.normals = [];
	this.colors = [];
	this.uvs = [];
	this.uvs2= [];
	this.faces = [];

	//

	this.morphTargets = [];
	this.morphColors = [];
	this.morphNormals = [];

	this.skinWeights = [];
	this.skinIndices = [];

	this.lineDistances = [];

	this.boundingBox = null;
	this.boundingSphere = null;

	// update flags

	this.verticesNeedUpdate = false;
	this.normalsNeedUpdate = false;
	this.colorsNeedUpdate = false;
	this.uvsNeedUpdate = false;
	this.lineDistancesNeedUpdate = false;

};
```

These `normals`, `colors`, `uvs`, ... arrays would map 1 to 1 the `vertices` array. Just as WebGL expects.

Any suggestions for a better name than `THREE.DynamicGeometry`?

/ping @WestLangley @bhouston

**Comment by benaadams** [comment]
Alas, I don't think its that simple; its a 1 to 1 map for the vertices; but isn't for other attributes; was a problem I was having in the other PR.

So if you use the flattening path for http://threejs.org/examples/webgl_materials2 see if you have a seam down the sphere? Where the positions are shared by indices on the face; but the uvs (on the faces) are not matched to the underlying position buffer. i.e. there are more uvs than there are positions.

**Comment by mrdoob** [comment]
> Alas, I don't think its that simple; its a 1 to 1 map for the vertices; but isn't for other attributes; was a problem I was having in the other PR.

I'll look at attributes next.

> So if you use the flattening path for http://threejs.org/examples/webgl_materials2 see if you have a seam down the sphere? Where the positions are shared by indices on the face; but the uvs (on the faces) are not matched to the underlying position buffer. i.e. there are more uvs than there are positions.

This is only for geometries that animate though. `webgl_materials2` can continue using `THREE.Geometry`.

**Comment by benaadams** [comment]
> This is only for geometries that animate though. webgl_materials2 can continue using THREE.Geometry.

Ah ok; should I change this PR to not do dynamic stuff, but still create the indexed buffers?

**Comment by mrdoob** [comment]
Let me take a look at custom attributes first (I don't understand them yet).

**Comment by benaadams** [comment]
> Let me take a look at custom attributes first (I don't understand them yet).

The custom ones on material.attributes are simpler as they are a 1 to 1 mapping with vertexes, so is just creating correct item sized buffer.

**Comment by mrdoob** [comment]
> > Let me take a look at custom attributes first (I don't understand them yet).

> The custom ones on material.attributes are simpler as they are a 1 to 1 mapping with vertexes, so is just creating correct item sized buffer.

Uh? I don't get this previous sentence then...

> Alas, I don't think its that simple; its a 1 to 1 map for the vertices; but isn't for other attributes; was a problem I was having in the other PR.

**Comment by benaadams** [comment]
> Uh? I don't get this previous sentence then...
> > Alas, I don't think its that simple; its a 1 to 1 map for the vertices; but isn't for other attributes; was a > > problem I was having in the other PR.

uvs and normals have this problem. So in the sphere example the two sizes of the sphere join using same position vertex; but have a x texture coordinate of 1 and 0. When the same uv is used for both sides you get a seam as the uvs go ```.95, 0, 0, .05``` rather than ```.95, 1, 0, .05```. Likewise with normals on a box; there are more normals then there are positions so you have sharp corners rather than smoothed corners.

ybtff

**Comment by benaadams** [comment]
Could move it out to a helper class; and have the conversion post model load and object create? Convert early rather than further down the rendering pipeline?

**Comment by mrdoob** [comment]
Yes, that's why the original fromGeometry duplicated vertices. It's not the most optimised but it's simple and works.

Any reason you want indexed buffers out of `THREE.Geometry`? If it's for performance reasons I would, instead, focus on converting the primitives and loaders to `BufferGeometry` (or `DynamicGeometry`).

**Comment by benaadams** [comment]
Fair enough :)

**Pull request closed without merging**
