### PR TITLE
Convert OrbitControls to ES6 format

### PR DESCRIPTION
**Pull request by cpmech**
This is the first conversion of controls to ES6 format.

### CODE REVIEW

**Comment by looeee** [comment]
There's an ongoing discussion on how best to approach using examples as modules in #9562
So far there's no consensus unfortunately.

**Comment by WestLangley** [comment]
Thanks for the contribution, but it appears you are not basing this PR off the most recent dev branch version. At the appropriate time, you will need to do that.

**Comment by cpmech** [comment]
I'm glad to use the _most recent dev branch_. I thought I was on it already...

**Comment by Mugen87** [comment]
Some more information about contribution:

https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js
https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2

**Pull request closed without merging**
