### PR TITLE
Added spherical harmonics class

### PR DESCRIPTION
**Pull request by WestLangley**
@bhouston and I worked on this in 2015, I think. I subsequently modified it.

The code is different from other versions of this file I have seen floating around the net, but in my testing, this code appears to work as expected.

I'll add this file to the build in a follow-up PR.

### CODE REVIEW

**Comment by bhouston** [comment]
Well of course I support merging this in. :)

**Comment by bhouston** [comment]
Thanks @WestLangley

**Comment by WestLangley** [comment]
Merged this for now so we can continue to press forward. :)

**Comment by mrdoob** [comment]
@WestLangley Thanks!

**Comment by mrdoob** [comment]
I'm sorry it takes me so long to understand all these things. I'm slowly getting there... this week I bumped into an issue where I needed `renderer.outputEncoding` 😅

**Comment by WestLangley** [comment]
We'll get there. :-)

**Comment by bhouston** [comment]
BTW I found this interesting SH paper that Unity 3D references: http://www.ppsloan.org/publications/StupidSH36.pdf

**Comment by WestLangley** [comment]
Yes, that is referenced in a comment at the top of the file.   :-)

**Pull request merged**
