### PR TITLE
[WIP] Suggestion: Add a way to enable ImageBitmapLoader to GLTFLoader

### PR DESCRIPTION
**Pull request by takahirox**
**Background**

`ImageBitmap` has a very good advantage to regular images, the main thread blocking time caused by uploading to texture is shorter. For example, VR app will have better presence with `ImageBitmap`.

But `ImageBitmap` has two problems in Three.js. First, compatibility. IE, Edge, and Safari don't seem to support yet.

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap

And FireFox doesn't handle `ImageBitmap` options now #15910. We tried to fix in FireFox side https://github.com/mrdoob/three.js/issues/11746#issuecomment-414845303 but I heard it may still take time to fix.

Second, `ImageBitmap` doesn't fit to some current Three.js `Texture` API. `flipY` and `premultiplyAlpha` should be specified on `ImageBitmap` creation. Changing `texture.flipY/premultiplyAlpha` later has no effect.

```javascript
texture.flipY = ! texture.flipY;
texture.premultiplyAlpha = ! texture.premultiplyAlpha;
texture.needsUpdate = true; // no effect if texture.image is ImageBitmap
```

So it's too early to switch from `ImageLoader` to `ImageBitmapLoader` as default now. But I think there are users who want to use `ImageBitmap` where it works fine. Especially they may want to use in case they don't need the `ImageBitmap` options because it works even on FireFox. Loading glTF assets may be a good use case. glTF core spec doesn't require `flipY` and `premultiplyAlpha`.

But `TextureLoader` uses `ImageLoader` inside. And there is no way to switch to `ImageBitmapLoader`.

**Suggestion**

I'd like to suggest providing users a way to switch from `ImageLoader` to `ImageBitmapLoader` in `TextureLoader` and `GLTFLoader` under their responsibility.

As I mentioned above, using `ImageBitmap` in Three.js may be problematic for some use cases. So I think it's better that users, who understand the limitation/restriction, explicitly enable `ImageBitmapLoader` rather than we automatically detect `ImageBitmap` availability and switch.

Suggested API.

```javascript
var loader = new THREE.TextureLoader();
if ( 'createImageBitmap' in window ) loader.enableImageBitmapLoader();
loader.load( ... ); // using ImageBitmapLoader instead of ImageLoader inside

var gltfLoader = new THREE.GLTFLoader().enableImageBitmapLoader();
if ( 'createImageBitmap' in window ) gltfLoader.enableImageBitmapLoader();
gltfLoader.load( ... );  // using ImageBitmapLoader instead of ImageLoader inside
```

What do you think? Sounds hacky? Any better solutions?

I haven't updated the document yet in this PR. I'll update and remove "[WIP]" from the title if this suggestion looks ok.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Note that workarounds like this are possible today:

```js
class CustomTextureLoader {

	constructor () {

		this.loader = new THREE.ImageBitmapLoader();

	}

	load ( url, onLoad, onProgress, onError ) {

		this.loader.load( url, ( imageBitmap ) => {

			onLoad( new THREE.CanvasTexture( imageBitmap ) );

		}, onProgress, onError );

	}

}

THREE.Loader.Handlers.add( /\.(png|jpg|jpeg)$/, new CustomTextureLoader() );
```

Would that be sufficient, without modifying the different loaders?

**Comment by takahirox** [comment]
Thanks, I was missing `Loader.Handlers`. I didn't really like adding the same new method across multiple loaders. `Loader.Handlers` approach should be nicer.

I don't see `Loader.Handlers` in the doc (unless I'm missing). I'll add with `GLTFLoader` + `ImageBitmapLoader` example code.

**Comment by Mugen87** [comment]
> I don't see Loader.Handlers in the doc (unless I'm missing).

No, it's actually missing. Let me add some information about `Loader.Handlers` to the `Loader` page.

**Comment by Mugen87** [comment]
> I'll add with GLTFLoader + ImageBitmapLoader example code.

Sry, I've missed that you want to make the PR^^. Anyway, the descriptions from the closed one might be a bit of a help ;)

**Comment by netpro2k** [comment]
One problem with using "handlers" for this is that all images in a glb end up being blob urls, so there would be no way to use ImageBitmapLoader for those. In general we have found a bunch of cases where we want to take further control over how things are loaded in GLTFLoader, so something that exposes that would be super useful.

**Comment by donmccurdy** [comment]
That's a good point. This is also a problem for using GLTFLoader in Node.js, where Blob URLs aren't available. If we can come up with an API that's more general than `enableImageBitmapLoader()`, ideally flexible enough for Node.js, ImageBitmap, compressed textures, etc., I'm fine with adding a method here. I'd prefer an approach that doesn't rely on the global `THREE` namespace, but instead passes something into the loader.

Naive example:

```js
const loader = new THREE.GLTFLoader();
loader.setTextureProvider( new CustomTextureProvider() );

class CustomTextureProvider {
  /**
    * @param {THREE.GLTFParser} parser
    * @param {GLTF.Texture} textureDef
    * @returns {Promise<THREE.Texture>}
    */
  load( parser, textureDef )  {

    const imageDef = parser.json.images[ textureDef.source ];
    const textureLoader = new THREE.TextureLoader();
    return new Promise( ( resolve ) => textureLoader.load( imageDef.uri, resolve ) );

  }
}
```

**Comment by takahirox** [comment]
> One problem with using "handlers" for this is that all images in a glb end up being blob urls, so there would be no way to use ImageBitmapLoader for those.

Doesn't this work?

```javascript
THREE.Loader.Handlers.add( /\.(png|jpg|jpeg)$/, new CustomTextureLoader() );
THREE.Loader.Handlers.add( /^blob:.*$/, new CustomTextureLoader() );
```

**Comment by netpro2k** [comment]
> Doesn't this work?
> 
> ```js
> THREE.Loader.Handlers.add( /\.(png|jpg|jpeg)$/, new CustomTextureLoader() );
> THREE.Loader.Handlers.add( /^blob:.*$/, new CustomTextureLoader() );
> ```

Haven't tried, but It's possible that would work in a well constrained example, but in general I don't think that's a handler you would want to register globally since there are many non-texture things that can be blob urls. In Hubs for example all parts of sketchfab models (including the gltf and bin) end up being blob urls since we read them from a zip file on the client. 

Something like Don suggested above where we actually get the texture definition would be really nice. If we expand it a bit I bet this would be useful for other types of entries like meshes, nodes, etc as well.

**Comment by Mugen87** [comment]
Quick update: `THREE.Loader.Handlers` has been removed with the last release `R109`. Instead, you can now use a new API of `LoadingManager` for loader configuration. 

- `LoadingManager.addHandler()`
- `LoadingManager.removeHandler()`
- `LoadingManager.getHandler()`

In this way, you do not register handler globally anymore but on loading manager level.

**Comment by Mugen87** [comment]
Closing. Please open a new issue if `LoadingManager.addHandler()` is not sufficient to configure the usage of `ImageBitmapLoader` in `GLTFLoader`.

Please discuss the idea of `GLTFLoader.setTextureProvider()` in a separate issue if it's still relevant (see https://github.com/mrdoob/three.js/pull/15919#issuecomment-471082093).

**Pull request closed without merging**
