### PR TITLE
Examples: Clean up SelectionBox.

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/pull/16944#issuecomment-508142612

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev31/examples/misc_boxselection.html

**Comment by WestLangley** [comment]
How about setting
```js
allSelected[ i ].material.emissive.set( 0xffffff );
```
At least it is visible.

**Comment by Mugen87** [comment]
Good idea 👍

**Comment by WestLangley** [comment]
Thanks!

**Comment by mrdoob** [comment]
Thanks thanks!

**Pull request merged**
