### PR TITLE
FontLoader: search for the start of font data instead of using a hardcoded value

### PR DESCRIPTION
**Pull request by kkananen**
Still a little dirty but better than hardcoding, as minifier scripts would break font loading

### CODE REVIEW

**Comment by kkananen** [comment]
https://github.com/mrdoob/three.js/pull/8867

**Comment by mrdoob** [comment]
Considering that "typeface.js" is kind of dead we can change it to "typeface.json". See #8262.

**Comment by mrdoob** [comment]
Ended up demoting `typeface.js` support in favour of `typeface.json`. 805d99b5517e18143e3af0069a44ab1118beda49

**Comment by kkananen** [comment]
Works for us - thanks! :)

**Comment by mrdoob** [comment]
🙌!

**Pull request closed without merging**
