### PR TITLE
Docs: Move to let/const.

### PR DESCRIPTION
**Pull request by Mugen87**
Except for Arabic and Chinese translations, this PR moves the documentation to let/const.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev51/docs/index.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
@linbingquan Applying this change to `zh` would be a great help 😇 .

**Comment by linbingquan** [comment]
> @linbingquan Applying this change to `zh` would be a great help 😇 . Are you interested?

OK, Let me do it. I found several files not just change `var` to `const`...

**Pull request merged**
