### PR TITLE
Generate lightProbe from CubeCamera

### PR DESCRIPTION
**Pull request by nipmarsh**

### CODE REVIEW

**Comment by Mugen87** [comment]
It would be actually good if you can merge all changes into a single commit. If you make a soft reset in git right before 248002c286a46522de47e2aae22d7368ef502388, you can commit all changes at once.

**Comment by bhouston** [comment]
This is really nice.  I encourage you to continue to try to get this merged.

**Comment by nipmarsh** [comment]
On my side, everything is fine. I only need @WestLangley approval

**Comment by WestLangley** [comment]
Thank's @nipmarsh 

>It would be actually good if you can merge all changes into a single commit.

@mrdoob This is good -- except I request a single squashed commit.

**Comment by Mugen87** [comment]
> @mrdoob This is good -- except I request a single squashed commit.

We can also do this when merging however this option is not enabled for the repository so far:

image

**Comment by nipmarsh** [comment]
Ok, i will do a new PR, this one was messed up by the squash commit...

**Pull request closed without merging**
