### PR TITLE
FBXLoader: Add TransparencyFactor

### PR DESCRIPTION
**Pull request by safu9**
I had warning message when loading fbx file,
`THREE.FBXLoader: TransparancyFactor map is not supported in three.js, skipping texture.`

Since TransparancyFactor seems to be another name of TransparentColor, I added it in FBXLoader.

Related: https://github.com/mrdoob/three.js/issues/11598

### CODE REVIEW

**Comment by looeee** [comment]
> Since TransparancyFactor seems to be another name of TransparentColor

`TransparencyFactor` maps to `opacity`, while `TransparentColor` maps to `alphaMap` so I don't think this is correct.

There's also an FBX property `Opacity` which is what the loader currently uses, and `TransparencyFactor` is ignored. It's possible that's not correct though.

Are you testing this change with any models? If so, can you share them?

**Comment by safu9** [comment]
Sorry for late reply.
I compared with the same model exported by Blender.

Before:
Screenshot from 2019-08-26 22-04-07
After this PR:
Screenshot from 2019-08-26 22-07-44

But I found some parts are not working correctly ... (z-buffer?)
Screenshot from 2019-08-26 22-08-40

**Comment by safu9** [comment]
Model file is here. [Tree.zip](https://github.com/mrdoob/three.js/files/3541253/Tree.zip)

**Comment by mrdoob** [comment]
@looeee what do you want to do with this one?

**Comment by looeee** [comment]
Sorry it took me so long to check this. 

It seems like the easy solution here is to manually set `material.alphaTest = 0.5`:

2020-04-14 12_44_19-three js webgl - FBX loader

Treating TransparencyFactor as an alphaMap as in this PR is _not_ correct since that makes the leaves transparent. At least in this case, it's presumably meant to be an alpha mask map, which could be handled in the loader like this:

```
case 'TransparencyFactor':
        parameters.alphaMap = scope.getTexture( textureMap, child.ID );
	parameters.alphaTest = 0.5;
	break;
```

However, when I do this, the mask is inverted:

2020-04-14 12_57_59-three js webgl - FBX loader

I'm not sure why this is happening, seem to be that 

``` js
material.alphaMap = texture;
material.alphaTest = 0.5;
```

... and 

``` js
material.map = texture;
material.alphaTest = 0.5;
```

...give inverse results, for the same `texture`.

**Comment by looeee** [comment]
I've found one more model that uses TransparencyFactor in this thread:

https://github.com/facebookincubator/FBX2glTF/issues/158

However, in that case it looks like a standard transparency map. They also note there that they've never encountered a model with this property before. Both of these files are created by a recent Blender version (2.79 and 2.80) so maybe they have started to use it. 

I've changed my mind on this - I think treating this the same way as `TransparentColor` is OK. Users will have to manually set `alphaTest` when required (as usual).

**Review by looeee — APPROVED** [review]

**Comment by looeee** [comment]
@mrdoob this can be merged now.

**Comment by mrdoob** [comment]
Thanks!

**Comment by safu9** [comment]
Thank you!

**Comment by looeee** [comment]
@safu9 thanks for your patience ^_^ 

And note that you probably still need to manually set `material.alphaTest = 0.5;` here.

**Pull request merged**
