### PR TITLE
Editor: Toggle Sidebar

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Comment by linbingquan** [comment]
@mrdoob This PR has a mistake. I don't found `windowResize()` script about `startPlayer.dispatch()`.

image

**Comment by mrdoob** [comment]
Why do you need this though?

**Comment by linbingquan** [comment]
> Why do you need this though?

First of all, there is more space to display in PC with `toggleSidebar()`.
Second, `toggleSidebar()` is very important thing in vertical scree mobile phone.
Finally, horizontal screen is OK, but it also needs more space to display.

Vertical screen's screenshot:
image

Horizontal screen's screenshot:
image

**Comment by linbingquan** [comment]
@mrdoob I fixed `startPlayer.dispatch()` layout error with `toggleSidebar()`  in https://github.com/mrdoob/three.js/pull/15213/commits/88579c6943030cfba126a24733d0cd2069add040

**Comment by linbingquan** [comment]
@mrdoob Hello, Would you like to receive this PR?

**Pull request closed without merging**
