### PR TITLE
Fix perturbNormal2Arb() bug

### PR DESCRIPTION
**Pull request by WestLangley**
As discussed in https://github.com/mrdoob/three.js/issues/7094

### CODE REVIEW

**Comment by donmccurdy** [comment]
🎉

| before | after |
|--|--|
| screen shot 2018-03-28 at 11 04 12 am | screen shot 2018-03-28 at 11 03 37 am |

**Comment by WestLangley** [comment]
@donmccurdy Unrelated: Any idea why the model has `.normalScale.x = - 1`?  It is more common to have to flip `.normalScale.y`, but flipping `y` does not appear to be required here.

**Comment by donmccurdy** [comment]
From GLTFLoader.js:1992 —

```js
// Normal map textures use OpenGL conventions:
// https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialnormaltexture
if ( material.normalScale ) {

	material.normalScale.x = - material.normalScale.x;

}
```

**Comment by bhouston** [comment]
Wohoo!  Thanks for making the PR @WestLangley and improving the solution to be more precise.

**Comment by WestLangley** [comment]
I do not think `GLTFLoader` should be doing this.
```javascript
// Normal map textures use OpenGL conventions:
// https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialnormaltexture
if ( material.normalScale ) {

	material.normalScale.x = - material.normalScale.x;

}
```

A reasonable guess is the model was created for BabylonJS. If a user wants to use the model in three.js, the user should set `normalScale.x = - 1`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> A reasonable guess is the model was created for BabylonJS. If a user wants to use the model in three.js, the user should set `normalScale.x = - 1`.

Uh oh...

**Comment by donmccurdy** [comment]
> A reasonable guess is the model was created for BabylonJS. 

I don't think that's the case, but would be more confident if I knew the answer to #11315. 😅

I'll look into this in a bit.

**Comment by donmccurdy** [comment]
On [closer look](https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/2.0/babylon.glTFLoader.ts#L1210-L1214), BabylonJS inverts normal map X when using their default left-handed system.

**Comment by mrdoob** [comment]
@donmccurdy After this PR the boombox normalmap seems to have been inverted. That `material.normalScale.x = - material.normalScale.x;` line may have been a hack to work around the problem this PR solved.

**Comment by mrdoob** [comment]
I've tested with [NormalTangentTest](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF-Binary) and [NormalTangentMirrorTest](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=NormalTangentMirrorTest&scale=1&type=glTF-Binary) and, after this PR and with this code they look correct:

```js
if ( material.normalScale ) {

	material.normalScale.y = - material.normalScale.y;

}
```

screen shot 2018-03-28 at 3 19 44 pm

screen shot 2018-03-28 at 3 20 21 pm


🤔

**Comment by mrdoob** [comment]
This PR is great by the way. The gun in `webgl_materials_standard` was also wrong:

Before:

screen shot 2018-03-28 at 3 33 54 pm

After:

screen shot 2018-03-28 at 3 34 19 pm

**Comment by WestLangley** [comment]
This is all good news, but the loader should not change the model parameters. The correct fix is to properly set `normalScale` in the model -- or alternatively, reset it in the loader callback.

**Comment by mrdoob** [comment]
Agreed. `webgl_materials_standard` does not use `GLTFLoader` though, it's a obj model.

**Comment by donmccurdy** [comment]
> This is all good news, but the loader should not change the model parameters. The correct fix is to properly set `normalScale` in the model ...

The handedness of the three.js normal map system remains unanswered in #11315. If it is not the same as the OpenGL convention (which all glTF assets must use) then inverting an axis of `normalScale` in the loader to convert seems reasonable, yes? BabylonJS does precisely that, because they're aware their convention does not match OpenGL or the glTF spec.

**Comment by mrdoob** [comment]
> A reasonable guess is the model was created for BabylonJS. If a user wants to use the model in three.js, the user should set `normalScale.x = - 1`.

Actually, this shouldn't be the problem. Otherwise this would be a bug in the GLTF spec. The model should look identical in any engine.

**Comment by bhouston** [comment]
I would suggest standardizing on Unity and UE4 style normal map interpretation.  I believe they are the same thing.

**Comment by WestLangley** [comment]
>What is three.js's normal map handedness convention?

I would say it is x-axis = right, y-axis = up.

**Comment by bhouston** [comment]
Hilarious, UE4 and Unity have different conventions - in fact the supporters of each of the two formats have equal supporters:

http://www.werwackfx.com/index.php/graphictools/graphicsarticles/graphics-articles/45-normalmapsart

I think you should then have a parameter to support both, call one OpenGL and the other DirectX, and have documentation that lists the various programs that support these two styles.  OpenGL might as well be the default.

**Comment by WestLangley** [comment]
>I think you should then have a parameter to support both

We have a parameter that supports both: `.normalScale`. It's purpose is to support normal maps authored for other engines. Of course, it also serves to reduce, or increase, the normal map's effect.

**Comment by bhouston** [comment]
My recommendation is a public parameter called normalMapStyle.  It would be separate from normalMapScale, which technically should be a scalar anyhow.

Thus you would have one style parameter and one scale parameter.  It can still be converted into a Vec3 when passed to the shader as it is right now, but my suggested parameterization is a more usable API because it matches how developers think about the problem, rather than expecting developers to jump through non-obvious mental hoops in order to figure out ThreeJS - see @donmccurdy comment.  Don is smart, but ThreeJS is confusing him here.

**Comment by mrdoob** [comment]
Another option would be to document the issue whenever we figure out exactly what is the right `normalScale` configuration to use on each case.

**Comment by WestLangley** [comment]
>normalMapScale, which technically should be a scalar anyhow.

Agreed, `normalScale` really should be a scalar.

I think the only reason it is not a scalar is to accommodate normal maps authored assuming a different tangent-space coordinate convention.
```javascript
material.normalScale.set( 0.5, - 0.5 );
```

**Comment by donmccurdy** [comment]
Quick patch in #13784 for r92.

Do we want to try the `normalScale` / `normalStyle` change for r93, or just document this?

**Comment by WestLangley** [comment]
I suggest retaining the current pattern, as it is flexible.
```javascript
material.normalScale.set( 0.5, - 0.5 );
```

**Pull request merged**
