### PR TITLE
Add a 3DS to Three.js converter

### PR DESCRIPTION
**Pull request by noahcoetsee**
We still need to find the right amount of components for BrowserFS. I'll keep on looking into it!

### CODE REVIEW

**Comment by TheCodeCrafter** [comment]
I may need some help, getting this to work with the main system, so can you? I really want to contribute to this project!

**Comment by mrdoob** [comment]
Why not just turn this into a `3DSLoader` instead?

**Comment by sasha240100** [comment]
@TheCodeCrafter +1 for @mrdoob 's `3DSLoader` suggestion

**Comment by TheCodeCrafter** [comment]
I will get right onto it! I just need to figure out how to work out files without FS... Any suggestions? The Blob function would be good, but I'm not 100% sure how to implement it?

**Comment by TheCodeCrafter** [comment]
There! I think there are some quirks in there because of the difference between .obj and .3ds... I think it is pretty functional, but I may need someone to help point me in the right direction if it's not!

Thanks for everything!

**Comment by TheCodeCrafter** [comment]
> Why not just turn this into a 3DSLoader instead?

I did that... I think :p better check my work though!

**Comment by TheCodeCrafter** [comment]
Ok! On it again!

**Comment by TheCodeCrafter** [comment]
Studying the file layout VERY CLOSELY. Will finish in a couple of days.

**Comment by Mugen87** [comment]
`TDSLoader` was added with #11099

**Pull request closed without merging**
