### PR TITLE
XRControllerModelFactory: Fix missing controllerModel usage

### PR DESCRIPTION
**Pull request by Itee**
The throwing error call directly motionController.assertUrl that will be undefined. Update to controllerModel.motionController.assertUrl.

### CODE REVIEW

**Comment by Mugen87** [comment]
It seems `componentId` is `undefined`, too.

https://github.com/mrdoob/three.js/blob/d665e52a4a48a69fcbc86a961da830b769609193/examples/jsm/webxr/XRControllerModelFactory.js#L142

**Comment by Itee** [comment]
Want componentId fix in this PR too ?

**Comment by Mugen87** [comment]
Yeah, that would be great.

**Comment by Itee** [comment]
Ok, one question more. Should i fix it in js example folder too ? Or is it considered as legacy now ?

**Comment by Mugen87** [comment]
`XRControllerModel` only exists in the `jsm` folder.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
