### PR TITLE
common.glsl: Rename transpose() to transposeMatrix3()

### PR DESCRIPTION
**Pull request by Mugen87**
This PR renames `transpose()` to `transposeMatrix3()` to avoid conflicts with the built-in transpose function in [GLSL ES 3.0](https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf).

#11906 
https://github.com/expo/expo-three/issues/2#issuecomment-325203638
https://github.com/Microsoft/HoloJS/issues/16#issuecomment-269076640

The shader implementation for `RectAreaLight` was the only place where `transpose()` is used. If the project switches to WebGL2 at some point, the code can use the built-in function.

### CODE REVIEW

**Comment by Mugen87** [comment]
@WestLangley You have refactored `RectAreaLight` some time ago. Do you think the change is okay like that?

**Review by WestLangley — COMMENTED** [review]
Fine, but I would name it differently and write it like so:
```glsl
mat3 transposeMat3( const in mat3 m ) {

	mat3 tmp;

	tmp[ 0 ] = vec3( m[ 0 ].x, m[ 1 ].x, m[ 2 ].x );
	tmp[ 1 ] = vec3( m[ 0 ].y, m[ 1 ].y, m[ 2 ].y );
	tmp[ 2 ] = vec3( m[ 0 ].z, m[ 1 ].z, m[ 2 ].z );

	return tmp;

}
```

**Comment by Mugen87** [comment]
Done! :+1:

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
