### PR TITLE
fixed 3dsMaxExporter animation delay when start frame > 0

### PR DESCRIPTION
**Pull request by dgolovin-dev**
#6829

### CODE REVIEW

**Comment by mrdoob** [comment]
How about this?

```
slidertime = 0
sliderlength = animationrange.end - animationrange.start

while (slidertime < sliderlength) do
(
	slidertime += 1
	sTime = (slidertime / FPS) as String
	
	append root_keys #(substring sTime 1 (sTime.count - 1), p, r, s)
)
```

I think it's a bit more readable...

**Comment by tormozok** [comment]
I don't know why, but your code is not working. Maybe I know bad maxscript?... I have no much time to test and force to work similar code, sorry.

**Comment by tormozok** [comment]
Oh, "slidertime" is built-in maxscript variable, it may be reason...

**Comment by tormozok** [comment]
I found another bug. When slider position is not start, then exported animation is broken. Fix - simple add ```slidertime = animationrange.start```  before export.

**Comment by mrdoob** [comment]
Merged into the `dev` branch.
Many thanks!

**Pull request closed without merging**
