### PR TITLE
WebGPURenderer: Workgroup Arrays and Barrier Support

### PR DESCRIPTION
**Pull request by cmhhelgeson**
**Description**

Add ability to create workgroup and private arrays within compute shaders, which can be used to accelerate compute operations. Ideally could be used for providing pre-written compute operations that are fast and useful out of the box ( bitonic sort, prefix sum ). This would probably be less useful to the end user, though those only targeting WebGPU devices may find some benefit out of using this functionality.

If requested, I can try to provide samples for some of this functionality, like porting the existing WebGPU Bitonic sort sample or doing something with spatial hashing and prefix sums, though this will likely require the ability to query the value of local_invocation_id and workgroup_id within TSL. 

- [x] Node implementation
- [x] Storage Buffer Sample Fix
- [x] Bespoke Workgroup Array Sample

### CODE REVIEW

**Comment by cmhhelgeson** [comment]
I'm also not really a fan of the ScopedArrayNode name. Willing to take any suggestions on a name that would make more sense ( ComputeArrayNode, ComputeLocalArrayNode, ComputeAccess, etc)

**Comment by RenaudRohlinger** [comment]
I’m not a big fan of using "Scope" in a node name either. How about `WorkgroupInfoNode`? It clearly indicates workgroup-level data and aligns with WebGPU and WGSL terminology. Or maybe DomainArrayNode?

For example:
```js

export const workgroupArray = ( type, count ) => nodeObject( new WorkgroupInfoNode( 'Workgroup', type, count ) );
export const privateArray = ( type, count ) => nodeObject( new WorkgroupInfoNode( 'Private', type, count ) );

```


By the way are you planning on trying your WebGPU SPH Simulation with TSL @cmhhelgeson? 😄

**Comment by cmhhelgeson** [comment]
> I’m not a big fan of using "Scope" in a node name either. How about `WorkgroupInfoNode`? It clearly indicates workgroup-level data and aligns with WebGPU and WGSL terminology. Or maybe DomainArrayNode?
> 
> For example:
> 
> ```js
> export const workgroupArray = ( type, count ) => nodeObject( new WorkgroupInfoNode( 'Workgroup', type, count ) );
> export const privateArray = ( type, count ) => nodeObject( new WorkgroupInfoNode( 'Private', type, count ) );
> ```
> 
> By the way are you planning on trying your WebGPU SPH Simulation with TSL @cmhhelgeson? 😄

My current plan is:

1. Get current pull requests merged in
2. Finish protoplanet port ( people seem to like ports of old samples )
3. Finish extant pull requests that can be finished (post-processing, arrayCamera, etc)
4. Do required reading on subgroups, physics, workgroup sync, maybe atomics for a week to get myself back up to speed.
5. Move onto new/more creative/more demanding uses of compute like SPH, Instanced Points FLIP, Spatial Hash Collisions with Workgroup or Subgroup Sync, etc. 

I'm just busy with work and life-stuff right now so working on the low-hanging fruit first. TLDR: Yes 😊

**Comment by sunag** [comment]
Would it be complicated to have an example using these features in this PR?

**Comment by cmhhelgeson** [comment]
> Would it be complicated to have an example using these features in this PR?

Shouldn't be too complicated, I can write one using invocationLocalIndex.

**Comment by cmhhelgeson** [comment]
Moved to draft until samples are created.

**Comment by cmhhelgeson** [comment]
@sunag The WebGPUBackend of the Storage buffer sample is now fixed with the addition of workgroupBarrier() preventing data from being accessed and written to at the same time. 

https://github.com/user-attachments/assets/1b567f93-40d6-41be-90fe-7835e4461abc

**Comment by cmhhelgeson** [comment]
Just wanted to give a brief update since this took longer than originally expected. Two things have happened:

1. Moving for a new job ( SE1! ), so haven't had the time to give PRs proper attention.
2. Sort seems to work under certain conditions but there's some weirdness with the uniforms that I haven't been able to figure out yet.

**Comment by cmhhelgeson** [comment]
Sort is now working:

https://github.com/user-attachments/assets/dc1662a5-1b68-41c9-afd4-9bbcaf312c1b

**Comment by sunag** [comment]
@cmhhelgeson Looks great! I will review and merge it soon, thanks

**Comment by RenaudRohlinger** [comment]
Right now the example mixes local (workgroup) and global swaps, but it might be worth considering completing all the local sorting first before moving on to global sorting.

This could better reflect how bitonic sort is typically optimized for parallel processing:

Phase 1: Perform all local (workgroup) swaps (flip and disperse) within each group.
Phase 2: Once the local sorting is done, proceed to global sorting across workgroups to finalize the order.

This approach could make the example easier to understand by clearly separating the local and global phases, making the sorting process more educational. Just a thought!

**Comment by cmhhelgeson** [comment]
> Right now the example mixes local (workgroup) and global swaps, but it might be worth considering completing all the local sorting first before moving on to global sorting.
> 
> This could better reflect how bitonic sort is typically optimized for parallel processing:
> 
> Phase 1: Perform all local (workgroup) swaps (flip and disperse) within each group. Phase 2: Once the local sorting is done, proceed to global sorting across workgroups to finalize the order.
> 
> This approach could make the example easier to understand by clearly separating the local and global phases, making the sorting process more educational. Just a thought!

Maybe I'm misunderstanding what you're trying to suggest, but the example already does this. It will peform only local swaps until the span of a swap necessitates that the swap be performed globally. The purpose of the computeAlgo function is to ensure that the correct swap function is executed given the span length. It's not mixing global and local swaps at random.

**Comment by cmhhelgeson** [comment]
> Oh I see, the two panels were misleading me. Then all good! I guess having just the left example could be easier to understand? Since the local already swaps to global when needed, demonstrating both features.

In each panel's info pane, you can see that Compute Local's speed changes when it switches from local to global swaps. Maybe we could color code local amd global swaps somehow

**Comment by cmhhelgeson** [comment]
@RenaudRohlinger The example has been updated to more clearly demonstrate when a local sort or when a global sort is ocurring.

**Comment by RenaudRohlinger** [comment]
Probably the best example of a sorting algorithm I've ever seen! 😄

**Comment by cmhhelgeson** [comment]
Is there anything else that needs to be done here?

**Pull request merged**
