### PR TITLE
OrbitControls: Added public methods to pan, rotate and dolly camera. …

### PR DESCRIPTION
**Pull request by carlosanunes**
…(#8906)

Proposed change.

### CODE REVIEW

**Comment by WestLangley** [comment]
Do you really think that the public methods `dollyIn/OutCamera()` should have no arguments?

Unrelated to this PR, it appears to me that the private methods `dollyIn()` and `dollyOut()` do the exact opposite of what the function names say they do. Are you seeing that, too?

Also, `pan( - 10, 0 )` moves the camera to the right?

**Comment by carlosanunes** [comment]
> Do you really think that the public methods dollyIn/OutCamera() should have no arguments?

Yes, my intent here would be to maintain consistency between performing a dolly in/out through events and calling the function.

> Unrelated to this PR, it appears to me that the private methods dollyIn() and dollyOut() do the exact opposite of what the function names say they do. Are you seeing that, too?

Yup, saw that too...

> Also, pan( - 10, 0 ) moves the camera to the right?

Also correct.

**Comment by carlosanunes** [comment]
I can check if it is trivial to rename the private methods. And make the public pan method arguments more intuitive (that is, not accept a delta).

Sounds reasonable ?

**Comment by WestLangley** [comment]
>I can check if it is trivial to rename the private methods.

Let's save that for a second PR.

>And make the public pan method arguments more intuitive (that is, not accept a delta).

I think the public pan method should accept delta args, as you have implemented it.

@mrdoob This PR looks OK to me, but I am thinking that the public methods do not need to include the word "Camera". What do you think?

**Pull request closed without merging**
