### PR TITLE
Ply exporter update

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix https://github.com/mrdoob/three.js/issues/13966

Updates to the PLY Exporter from [this repo](https://github.com/gkjohnson/ply-exporter-js).

#### Updates
- Fix issue where vertex colors were not being exported correctly
- Automatically exclude unused normal, color, uv attributes (they were generated if unavailable previously. They can still be explicitly excluded.)
- Add option to explicitly exclude triangle indices so point cloud data can be saved
- Add binary format support

### CODE REVIEW

**Review by Mugen87 — CHANGES_REQUESTED** [review]

**Comment by mrdoob** [comment]
> Would it be possible to have a single exporter and control the binary export with a flag? `GLTFExporter` works in this way.

Agreed. That'd be ideal 👌

**Comment by gkjohnson** [comment]
@Mugen87 @mrdoob I merged the two exporters in a single exporter and added an options object with `binary` and `excludeProperties` fields.

Also, I saw that the GLTFExporter didn't have `binary` specified in its `DEFAULT_OPTIONS` object, so I added that in, as well.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@gkjohnson Would you be willing to add this exporter to the docs?

**Comment by gkjohnson** [comment]
@WestLangley Sure! Is that done by adding an HTML page to this folder?

https://github.com/mrdoob/three.js/tree/dev/docs/examples/exporters

**Comment by WestLangley** [comment]
@gkjohnson Yes. Thanks!

**Pull request merged**
