### PR TITLE
Replace SceneLoader suggestion in JSONLoader

### PR DESCRIPTION
**Pull request by jostschmithals**
SceneLoader was removed (#11123)

### CODE REVIEW

**Comment by jostschmithals** [comment]
Perhaps it should better be something like
`if ( type.toLowerCase() !== 'geometry' ) {`
instead of
`if ( type.toLowerCase() === 'object' || type.toLowerCase() === 'scene' ) {`  ?

There seems to be no further restriction for `metadata.type` in ObjectLoader?

**Comment by mrdoob** [comment]
> Perhaps it should better be something like
`if ( type.toLowerCase() !== 'geometry' ) {`

Yes, that sounds good.

**Comment by mrdoob** [comment]
Actually, I think it would be better to leave it as it was. That way, if we get people getting that error, we may consider writing a converter.

**Comment by jostschmithals** [comment]
Sorry - I don't yet understand:

If sceneLoader [does not exist any longer](https://github.com/mrdoob/three.js/issues/10910#issuecomment-291919434), isn't a message saying ["Use SceneLoader"](https://github.com/mrdoob/three.js/blob/dev/src/loaders/JSONLoader.js#L62) useless?

**Comment by mrdoob** [comment]
It sure is for the user. But at the same time, if we get people asking "where is the SceneLoader?" we'll know that we should do a converter.

**Pull request closed without merging**
