### PR TITLE
Editor: Fixed shadow casting bug.

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please shortly explain what this bug fix is about?

**Comment by linbingquan** [comment]
@Mugen87 I wanna to make shadow effect, I toggle `Checkbox of  ReceiveShadow `, but `Editor` doesn't render immediately.

image

**Comment by linbingquan** [comment]
@Mugen87 I wanna to make shadow effect, when I toggle `Checkbox of  ReceiveShadow`, but `Editor` doesn't render immediately.

image

**Comment by Mugen87** [comment]
Good catch!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Hmm, I'm not able to reproduce the issue in https://threejs.org/editor/.
What are the steps to reproduce?

**Comment by linbingquan** [comment]
@mrdoob I make a `DirectionalLight` and a `Box` with `Shadow cast`,  and `Plane` without `Shadow receive`. When I toggle `Shadow receive` of `Plane`, the shadow receiveing doesn't work immediately.

Result screen shot:


and then I switch `CheckBox` tow times, the shadow receiveing works correctly.

Result screen shot:

**Comment by mrdoob** [comment]
Ah, I see. I can reproduce that and I understand why it's happening.
I think the fix is good.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
