### PR TITLE
Examples: Tidy up glTF Variants example.

### PR DESCRIPTION
**Pull request by donmccurdy**
Linting cleanup, removing some unneeded code, and ensuring that materials "reset" if a mesh is no longer affected by the selected variant.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
One minor thing: One has to remove the screenshot for `webgl_loader_gltf_variant` and add one for `webgl_loader_gltf_variants`.

**Comment by mrdoob** [comment]
I'll clean that up 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/d72eb8950e9d2be5bb491570d897be8ac0f922df

**Pull request merged**
