### PR TITLE
Examples: Use color management in lightmap example.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This PR enables color management in `webgl_materials_lightmap`. Next to the changes in the example code, it was necessary to update the JSON asset.

@donmccurdy I have noticed a small issue with `MeshPhongMaterial.specular` and its default `0x111111`. This value was supposed to be in linear-srgb previously. But after enabling color management I think this value should be updated to `0x494949` to ensure visual consistency (the decimal version of this hex is now used in the JSON, btw).

### CODE REVIEW

**Comment by Mugen87** [comment]
Since sRGB output is the default now I think material color values other than 0xffffff and 0x000000 should updated. For materials, helpers etc. 

My point is there is a visual difference with color management enabled and it should be fixed.

**Comment by Mugen87** [comment]
@mrdoob What kind of previous setup would you consider as a baseline. I think we should pick something that we can use as a reference and I vote for setups that previously configured an sRGB output color space. Meaning `renderer.outputEncoding = THREE.sRGBEncoding`. 

With color management enabled, color defaults should produce the same visual result as before. And that means the previously 0x111111 specular color value was supposed to be in linear-sRGB (assuming sRGB workflow) and should now be updated to its sRGB pendant like other color values.

**Comment by mrdoob** [comment]
It may not be a surprise to hear that numbers like `0x444444` were chosen mostly because they're easy to write and not so much for their precise color.

I personally didn't really notice when we changed color space mostly because the lines tend to be thin and hard to see the change.

So I wouldn't worry too much about updating them, the ease of write/read is more important in that case imho.

**Comment by Mugen87** [comment]
Okay, and what do you think about the specular value of `MeshPhongMaterial`? Is that something that should be updated? If not, all phong materials using the default will render slightly different with color management enabled.

**Comment by Mugen87** [comment]
Merging the PR but I won't change any other examples with an updated specular value. At this point, I think the conclusion is to not update the colors of helpers and other material properties.

**Comment by donmccurdy** [comment]
I would prefer not to update default colors of helpers, yes. I'm wondering if there is something a bit different going on with MeshPhongMaterial's default specular color, and will try to look more closely into that...

**Pull request merged**
