### PR TITLE
Examples: More usage of RoomEnvironment.

### PR DESCRIPTION
**Pull request by Mugen87**
I guess it makes sense to use `RoomEnvironment` in `webgl_materials_envmaps_hdr`, too?

### CODE REVIEW

**Comment by Mugen87** [comment]
http://raw.githack.com/Mugen87/three.js/dev47/examples/webgl_materials_envmaps_hdr.html

**Comment by sciecode** [comment]
> Is it correct that the walls of the generated room look so dark? The previous one seems different

Current form of `RoomEnvironment` sets-up the room and lights off centered from the origin, once we apply `pmremGenerator.fromScene`, I think the camera is sitting outside of the room. I'm not entirely sure, because the current room and light setup is really weird.

This PR should probably get merged, because once we fix `RoomEnvironment` it will work properly. But maybe we should focus on that first.

**Comment by WestLangley** [comment]
Please see #19238, which is reverted by this PR.

**Comment by mrdoob** [comment]
@WestLangley What do you think about turning the current code into `DebugEnvironment` instead?

**Comment by WestLangley** [comment]
@mrdoob Whatever you want is fine with me. TBH, I am most interested in being able to export and load PMREMs in OpenEXR format. Perhaps "room environment" can be used in an example in that context, instead.

**Comment by Mugen87** [comment]
@mrdoob I suggest to merge this PR so both HDR example use `RoomEnvironment` in the same way like other examples ( e.g. `webgl_loader_texture_lottie`.

**Comment by mrdoob** [comment]
Actually, I'll merge this and do the `DebugEnvironment` class.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/34519f5073c32eca2cf8b571ce03d44a5a80476a

**Pull request merged**
