### PR TITLE
Remove remaining IIFEs from core.

### PR DESCRIPTION
**Pull request by Mugen87**
This PR should remove all remaining IIFEs from the core code base.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
While reviewing this I was wondering...

Before the clean up we used to create many `Vector3`, `Matrix3`, ... But we have now introduced a lot of if conditions that could make these functions less performant...

Have we discussed if it wouldn't be better to directly create the reusable variables instead of checking if these variables have been created in each function?

**Comment by mrdoob** [comment]
For example, it seems to me that it would be better to directly create these:

https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js#L13

```js
var _vector = new Vector3();
var _quaternion = new Quaternion();
```

And remove the undefined checks in the rest of the file...

**Comment by Mugen87** [comment]
@Rich-Harris mentioned here (https://github.com/mrdoob/three.js/pull/14695#issue-207790021) that it's best when the helper variables are instantiated lazily when the methods are invoked (and not created eagerly).

**Comment by mrdoob** [comment]
I see... That makes sense 👌

**Comment by mrdoob** [comment]
Although that was one year ago... I wonder if this is something tree-shakers can handle these days.

/ping @Rich-Harris

**Comment by Mugen87** [comment]
In any event, changing the code should be no big deal. If necessary, I can do this for the all core files.

The challenging task was to ensure the code actually works without the IIFEs. When you look closer to the PRs, you see that some refactoring was necessary so everything still works with module scope variables :sweat_smile:

**Comment by mrdoob** [comment]
Yes, I noticed 🙏😊

**Comment by mrdoob** [comment]
@Mugen87 I thought about this a bit more and I think it will be better to instantiate the reusable objects and remove all the `if ( _vector === undefined )`, etc checks.

We can reintroduce them in the future once we are confident tree-shakers are not able to deal with them. But for now I think it's better to have clean and compact methods.

Do you mind amending the code?

**Comment by Mugen87** [comment]
> Do you mind amending the code?

No problem 😊

**Pull request merged**
