### PR TITLE
Fixed sprite raycast bug when sizeAttenuation is false

### LINKED ISSUE #14934: Raycast problem with SpriteMaterial.sizeAttenuation set to false
Hi Friends!
```
SpriteMaterial.sizeAttenuation = false
```
seems not working as expected with `rayCaster`.
I doubt the sprite size(dimension) estimation may be a little bit off, ray is very hard to hit them after apply `scale()`, especially scale down. 
I can upload a simplified code that regenerate this problem a bit later.

- [x] r96

##### Browser
- [x] All of them

Thanks!

### PR DESCRIPTION
**Pull request by 06wj**
Fixed #14934

[demo](https://raw.githack.com/06wj/three.js/patch0_build/examples/webgl_raycast_sprite.html)

If using an orthographic camera the results is wrong.

### CODE REVIEW

**Comment by 06wj** [comment]
If the camera is orthographic, the ```sizeAttenuation``` has no effect on render result, we should not ```worldScale.multiplyScalar( - mvPosition.z );```.

**Comment by WestLangley** [comment]
>I can't check if it is the camera is orthographic.

Right. That is what I was afraid of...

**Comment by 06wj** [comment]
Maybe we should add a note if the camera is orthographic do not set sizeAttenuation of the sprite

**Comment by WestLangley** [comment]
The user could be using a custom `ShaderMaterial` or `SpriteMaterial`.
The material may, or may not, have a `sizeAttenuation` property (`undefined`, `true`, or `false`).
The user may, or may not, be using an orthographic camera when raycasting.
There are 2 x 3 x 2 = 12 cases.

**Comment by 06wj** [comment]
#14888 Maybe this is a solution.

**Comment by WestLangley** [comment]
A raycast can emanate from any point, in any direction -- it does not have to emanate from a camera. 

Consequently, raycasting against a `Sprite` that is camera-dependent and sized in screen-space does not necessarily make sense.

**Comment by 06wj** [comment]
Sprite is a 3d object that is always facing the camera. We can do this by dynamically setting the vertices in js or using shader.Just because we chose shader for performance reasons makes raycast implementation difficult, I don't think Sprite raycast is meaningless.

**Comment by WestLangley** [comment]
>Sprite is a 3d object that is always facing the camera

Sprite is a 2D object, actually.

>This is the main reason raycast relies on cameras

Raycasting does not require a camera. It is the sprite that is camera-dependent.

>I don't think Sprite raycast is meaningless

Raycasting against a sprite using a ray that does not emanate from a camera is pretty meaningless because there is no way to determine how big the sprite should be, or how it should be oriented.

**Comment by 06wj** [comment]
Fixed in #16423, so close it.

**Pull request closed without merging**
