### PR TITLE
Add MouseEvent to DragControls drag events

### PR DESCRIPTION
**Pull request by VJigouline**
Adding mouse event to the **DragControls** _drag_, _dragstart_ and _dragend_ events will help application to take different actions according to mouse buttons pressed and key modifiers used.

**DragEvent** interface for TypeScript added.

Also found it useful for _hoveron_, _hoveroff_ events.

### CODE REVIEW

**Comment by VJigouline** [comment]
One test failed due to zlib installation failure. Don't know how to rerun it.

**Comment by Mugen87** [comment]
> will help application to take different actions according to mouse buttons pressed and key modifiers used.

Why don't you add your own event listeners on application level to get to this data?

No controls class currently puts raw event objects to in its own event data. Since I'm not yet see a convincing reason for doing this, I don't vote to make this change.

**Comment by VJigouline** [comment]
The only reason I have, but it may be not convincing, is convenience and ease to use. As example of use you can take a look at the code in https://github.com/VJigouline/SceneEditor/blob/master/src/app/materials-library-editor/materials-library-editor.component.ts
methods _onDragHoveron_ and _onDragStart_. The first line after function header make use of the event.
How it looks from the user point of view you can find in http://help.meercad.com/index.php?id=4 section **Selection and assignment of materials** and try yourself on http://scene.meercad.com

I accept, that this interface is a bit experimental, but I felt it convenient for myself.

**Comment by Mugen87** [comment]
Closing. This needs to be solved on application level.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Vladimir Jigouline <notifications@github.com>
发送时间：2020-05-05 23:33
主题：Re: [mrdoob/three.js] Add MouseEvent to DragControls drag events (#19288)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

The only reason I have, but it may be not convincing, is convenience and ease to use. As example of use you can take a look at the code in https://github.com/VJigouline/SceneEditor/blob/master/src/app/materials-library-editor/materials-library-editor.component.ts
methods onDragHoveron and onDragStart. The first line after function header make use of the event.
How it looks from the user point of view you can find in http://help.meercad.com/index.php?id=4 section Selection and assignment of materials and try yourself on http://scene.meercad.com
I accept, that this interface is a bit experimental, but I felt it convenient for myself.

**Pull request closed without merging**
