### PR TITLE
Dev: Switch to http-server

### PR DESCRIPTION
**Pull request by Mugen87**
see #14264

The projects now uses [http-server](https://www.npmjs.com/package/http-server) as the local dev server.

### CODE REVIEW

**Comment by Mugen87** [comment]
I've locally tested some examples, the documentation and the editor. Seems all to work.

**Comment by mrdoob** [comment]
+131 −1,003 👌

**Comment by mrdoob** [comment]
@donmccurdy are you okay with this?

**Comment by donmccurdy** [comment]
This means our ImageBitmap examples will not work properly in Firefox, locally, because the relevant fix (https://github.com/jfhbrook/node-ecstatic/pull/223) has not been merged to http-server, and the firefox issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1413806, is not fixed and arguably isn't a bug anyway. But that's pretty minor, I'm OK with switching over.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
