### PR TITLE
add 3MF Loader

### PR DESCRIPTION
**Pull request by technohippy**
I added a 3MF Loader. The 3MF is a quite new file format mainly for a 3D printer and its specifications can be found here: http://3mf.io/what-is-3mf/3mf-specification/

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good! What's the `extensions` property for?

Could we do it this way instead?

```javascript
var loader = new THREE.ThreeMFLoader();
loader.addExtension( extension ); // or loader.setExtensions( array );
```

**Comment by technohippy** [comment]
Thank you for the comment.

3MF specs consist of two parts, core and extension, and the `extensions` parameter is intended to receive extensions which users want to handle.

Anyway, I approved of your suggestion and added `addExtension` method. Please check: https://github.com/technohippy/three.js/commit/3b10641e4c87531725a28e0edb5173a472577839

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Many thanks!

**Comment by technohippy** [comment]
Thank you for the merging!

**Pull request merged**
