### PR TITLE
RapierPhysics: Clean up

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: https://github.com/mrdoob/three.js/pull/26034

**Description**

A new and tested version.

### CODE REVIEW

**Comment by LeviPesin** [comment]
I think timings are slightly changed because of using clock... I will update screenshot.

**Comment by mrdoob** [comment]
Expected:

physics_rapier_instancing-expected

Actual:

physics_rapier_instancing-actual

Diff:

physics_rapier_instancing-diff

I don't think that diff is because using clock 🤔

**Comment by LeviPesin** [comment]
I guess it could be an unintented E2E tests side effect -- in `performance.now()` making determinstic it returns `0` on the first frame -- so in the clock-less version the, really, first frame image is captured, while in clock-with -- the second. So it should be _more_ correct to use the clock.

**Comment by LeviPesin** [comment]
I just realized that E2E tests determinism doesn't work with `setInterval`... I think I will temporary add the example to the exceptions list and try to fix `setTimeout` and `setInterval` in the tests in another PR (by making them call `requestAnimationFrame`, potentially multiple for large intervals).

**Comment by LeviPesin** [comment]
@mrdoob I think this PR is ready to merge.

**Pull request merged**
