### PR TITLE
Examples: Regenerate RGBM textures.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #21145

**Description**

This PR regenerates RGBM textures in the repo with this code: https://jsfiddle.net/xf5oy3hd/1/

When comparing the examples, you can see less artifacts and a better brightness. This is especially noticeable in `webgl_loader_texture_rgbm`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Very nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
I suggest to recommend users who want to convert to RGBM the above fiddle. 

If more users request a RGBM converter, we can still use the code to create a new example.

**Comment by mrdoob** [comment]
I was going to turn the fiddle into a little webapp 🤓

**Comment by Mugen87** [comment]
Even better 😊 !

**Comment by WestLangley** [comment]
It still remains to set the files' color profiles correctly (somehow). It is currently set to `sRGB`, and that is not correct.

**Comment by Mugen87** [comment]
I've searched the API of `UPNG.js` for a respective setting but it seems this setting can't be influenced.

**Comment by WestLangley** [comment]
Oh well, it is not critical.

**Pull request merged**
