### PR TITLE
Use matrixWorld instead of matrix for DecalGeometry

### PR DESCRIPTION
**Pull request by pjoe**
Noticed it used matrix instead of matrixWorld when transforming to world space

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
For testing: https://rawgit.com/pjoe/three.js/decals-matrix-world/examples/webgl_decals.html

**Comment by WestLangley** [comment]
@Mugen87 How is that a test? Don't you have to test this by adding the mesh as a child of a transformed parent?

**Comment by Mugen87** [comment]
Yeah. But I just want to add a link so it's easy to see that the example does not break...

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
