### PR TITLE
Material: Add alphaToCoverage.

### LINKED ISSUE #12438: Alpha to Coverage Support
##### Feature: Support Alpha To Coverage

It would be nice to support a flag for [Alpha to Coverage](https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f). This feature has existed in WebGL contexts for a while, however, it seems hardly used in practice.

It can be used to create really crisp alpha cutouts with MSAA-enabled contexts. 

When enabled, you no longer need to specify alphaTest or perform a `discard` in the fragment shader, you simply output the frag alpha and the GL context will handle cutouts. You can read more about it [here](https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f), including some tricks to make things even smoother.

```js
// enable alpha to coverage with current ThreeJS renderer
const gl = renderer.getContext();
gl.enable(gl.SAMPLE_ALPHA_TO_COVERAGE);
```

This feature assumes MSAA is enabled and supported (i.e. may not work in external monitors).

Here is an example wireframe shader using alpha to coverage:
https://mattdesl.github.io/webgl-wireframes/app/
screenshot 64

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #12438.

**Description**

Added `Material.alphaToCoverage`. The custom shader in `webgl_materials_wireframe` was modified similar to @mattdesl wireframe code in order to demonstrate the feature.

### CODE REVIEW

**Comment by WestLangley** [comment]
I always advise to stop the spinning demos so one can actually see what is going on. When I do so, I get this:

before:

Screen Shot 2021-03-01 at 11 58 55 AM

another before:

Screen Shot 2021-03-01 at 11 58 04 AM

after:

Screen Shot 2021-03-01 at 11 58 13 AM

**Comment by WestLangley** [comment]
Maybe restoring this would help
```gjsl
gl_FragColor = gl_FrontFacing ? vec4( 0.9, 0.9, 1.0, 1.0 ) : vec4( 0.4, 0.4, 0.5, 1.0 );
```

**Comment by Mugen87** [comment]
@WestLangley I've added your improvements to the PR.

**Comment by WestLangley** [comment]
Now larger triangles have thicker lines.

before
Screen Shot 2021-03-01 at 12 43 07 PM


after

Screen Shot 2021-03-01 at 12 41 23 PM

**Comment by Mugen87** [comment]
This is part of the wireframe style and also present original demo.

https://mattdesl.github.io/webgl-wireframes/app/

**Comment by WestLangley** [comment]
>Now larger triangles have thicker lines.
>>This is part of the wireframe style and also present original demo.

It is not present in the current three.js demo, or any three.js wireframe shaders.

I'd hate to lose the current shader as an example.

**Comment by WestLangley** [comment]
Maybe there is a shader that combines the best features of both the new and the old shader... :-)

**Comment by Mugen87** [comment]
I've restored the original shader and just added the new option as a third mesh.

**Comment by Mugen87** [comment]
Pragmatism FTW!

**Comment by takahirox** [comment]
To clarify. You closed the `alphaToCoverage` PR #12445 before, and now you came up with a good example so thought it would be good time to go with this new property?

**Comment by Mugen87** [comment]
Yes. I've written [here](https://github.com/mrdoob/three.js/pull/12445#issuecomment-538460663) that an example is important to understand the effect of the new property.

However, this was not the primary reasons I've revisited this topic. While investigating #20522, I've realized that AtC can be used to fix #20522.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
@mattdesl Do you know why larger triangles produce thinker lines in https://mattdesl.github.io/webgl-wireframes/app/?

**Comment by mrdoob** [comment]
@Mugen87 Thinking about this a bit more...

What do you think about hiding this from the user and enabling it automatically like this?

```js
if ( material.transparent === true && gl.getContextAttributes().antialias === true ) {

    enable( gl.SAMPLE_ALPHA_TO_COVERAGE );

} else {

    disable( gl.SAMPLE_ALPHA_TO_COVERAGE );

}
```

**Comment by Mugen87** [comment]
The problem is that you can use AtC even without `transparent` set to `true` (an example for this is the wireframe demo). I think it's better and more safe to have a material property for this. At least for now.

**Comment by mrdoob** [comment]
I see... Was trying to avoid having to expose this in the editor and co.

**Comment by gkjohnson** [comment]
> What do you think about hiding this from the user and enabling it automatically like this?

I believe alpha to coverage has to be specifically accommodated when making a shader, texture, or material. I don't think it will "just work" in the general case. If you use it on just a basic transparent material you can see that the opacity seems to jump to bands as you animate it up and down as the alpha is mapped to MSAA blending from coverage. It's best used when trying to smooth something like an alpha clip edge.

**Comment by mrdoob** [comment]
Okay. Sounds good 👍

**Comment by Mugen87** [comment]
@gkjohnson Yes, this is also my understanding.

**Comment by mrdoob** [comment]
@WestLangley What do you think about removing the old shader now?

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_wireframe.html

**Comment by WestLangley** [comment]
>What do you think about removing the old shader now?

There should be two separate examples for now: `webgl_` and `webgl2_`.

**Comment by mrdoob** [comment]
Is Alpha to Coverage WebGL2 only?

It's true that the shader-based wireframes do not render in Safari...

Screen Shot 2021-03-03 at 6 33 02 PM

**Comment by gkjohnson** [comment]
Looking at the [MDN constants page](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Constants) it looks like `SAMPLE_ALPHA_TO_COVERAGE` is supported in WebGL 1.

The shaders in the example won't work in WebGL2 / Safari because they were set to GLSL3 but I don't think it's a requirement?

> glslVersion: THREE.GLSL3

**Comment by Mugen87** [comment]
> Is Alpha to Coverage WebGL2 only?

Like @gkjohnson said, it also works with WebGL 1. 

> The shaders in the example won't work in WebGL2 / Safari because they were set to GLSL3 but I don't think it's a requirement?

No it's not. I've just used the more modern GLSL3 syntax out of pure habit. It is no deal to go back to GLSL1.

**Pull request merged**
