### PR TITLE
CSS2DRenderer: Add missing scene parameter in renderObject call

### PR DESCRIPTION
**Pull request by juliendargelos**
See https://github.com/mrdoob/three.js/pull/18518#issuecomment-580487522

### CODE REVIEW

**Comment by elalish** [comment]
@juliendargelos I just came to the same conclusion! Thank you!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
I think we need to bump the npm package since the renderer is broken in `prod`:

https://threejs.org/examples/css2d_label

**Comment by Mugen87** [comment]
Sorry, I did not review #18508 close enough. We should have tested this change with the above example.

**Comment by juliendargelos** [comment]
I'm the one that is sorry that was heedless

**Comment by mrdoob** [comment]
@Mugen87 already did 🤓

**Comment by Mugen87** [comment]
Great!! Can we also add this fix to the `gh-pages` branch? Otherwise the example stays broken until next release (and I want to avoid complaining users).

**Comment by Mugen87** [comment]
It seems I can also do this change^^: c0dd626754910bb3d727b101ffabff78a0fdc6cb

**Pull request merged**
