### PR TITLE
Examples: Added Sobel Edge Detection

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adds an example that shows how to perform a basic edge detection with `three.js`. 

I've changed the former `EdgeShader2` to `SobelOperatorShader` and redeveloped the code according to this video https://youtu.be/uihBwtPIBxM

BTW: The respective youtube channel _Computerphile_ is one of my favorites! :blush: 

I've also renamed `EdgeShader` to `FreiChenShader` which is a more descriptive name and introduced a new grayscale shader which is necessary for the Sobel operator implementation.

### CODE REVIEW

**Comment by looeee** [comment]
Very cool! 😀

**Comment by WestLangley** [comment]
What happened to the previous edge shader example from #3075?

**Comment by WestLangley** [comment]
>I've ... introduced a new grayscale shader

We already have `LuminosityShader`.

The weights used in `LuminosityShader` are used repeatedly (at least 7 times) throughout the library: 0.299, 0.587, 0.114 . They are different than your weights: 0.2126, 0.7152, 0.0722. Your weights are based on linear assumptions, and are the correct ones to use when the input is in linear space.

We need to revisit this.

**Comment by Mugen87** [comment]
Oh, i've missed `LuminosityShader`.
> We need to revisit this.

Let's handle this in a separate PR. I'll try to find out what happened to the original examples. They are not online anymore...

**Comment by Mugen87** [comment]
Looks like the example was deleted with this commit 7207a65a7884e6ce8b59749db84c1240cc47f08e

**Comment by Mugen87** [comment]
Ok, i've deleted the redundant `GrayScaleShader` and use `LuminosityShader` now. As mentioned before, we can correct the weight values with a separate PR.

**Comment by mrdoob** [comment]
Seems to be missing some pixelRatio love 😇

screen shot 2017-08-14 at 10 10 51 pm

**Comment by Mugen87** [comment]
@mrdoob Unfortunately, i have currently no device with a pixel ratio > 1 around me. Does it look better with the latest commit?

**Comment by WestLangley** [comment]
Why are you using `gl_FragCoord`?

https://github.com/mrdoob/three.js/pull/11931#issuecomment-322057862

**Comment by Mugen87** [comment]
I think the situation is different than in the audio visualizer. In order to correctly read the values for the kernel convolution process, you need information about the actual resolution. Or in other words: Without knowing the actual resolution of the device, you're unable to calculate the correct 3x3 neighborhood of a fragment.

**Comment by Mugen87** [comment]
I think the situation is different than in the audio visualizer. In order to correctly read the values for the kernel convolution process, you need information about the actual resolution. Or in other words: Without knowing the actual resolution of the device, you're unable to calculate the correct 3x3 neighborhood of a fragment.

I'm not sure, but i don't think that works with an uv based approach.

**Comment by Mugen87** [comment]
@mrdoob I could test the example on a Google Pixel and the result looks better now.

**Comment by hccampos** [comment]
@Mugen87 you can easily test different pixel ratios with the Chrome Dev Tools mobile emulation.

**Comment by Mugen87** [comment]
@hccampos Totally missed the mobile emulation :sweat_smile:. Thanks for that advice! :+1:

**Comment by WestLangley** [comment]
>I'm not sure but i don't think the filter works with an uv based approach.

The code you removed was implementing a Sobel fliter via a uv-based approach, no? Was it not working?

**Comment by Mugen87** [comment]
@WestLangley Yes, it was working :blush:. I've just misunderstood your last comment. I've rewritten the code so we use uvs to sample the texture. The resolution is still needed to adjust the actual uv value.

I thought you suggested a solution than does not need a `resolution` uniform value. Sorry for the confusion.

**Comment by WestLangley** [comment]
No problem...

But now, what is the dimension of the Composr's render target's texture? Is it scaled by pixel ratio?

**Comment by Mugen87** [comment]
Because we are not using `gl_FragCoord` in the shader anymore, it's not necessary to regard the pixel ratio (according to [this](https://www.khronos.org/webgl/wiki/HandlingHighDPI), `gl_FragCoord` is in device pixels) . AFAIK `EffectComposer` does not respect the pixel ratio. So the example should be consistent now.

**Comment by mrdoob** [comment]
Many thanks!

**Comment by Mugen87** [comment]
@WestLangley @mrdoob Thanks for your feedback and patience! :blush:

**Comment by WestLangley** [comment]
@Mugen87 Would you mind investigating the pre-application of a blur-filter to see if it achieves more-uniform edge thickness in this case?

**Comment by Mugen87** [comment]
Okay, i'll put this on my todo list. The video also mentioned possible advantages of a blur filter before applying the sobel operator. When i remember correctly, we already have a gaussian blur implementation in our collection of shaders.

**Comment by Mugen87** [comment]
Here are two screenshots with and without gaussian blur (applied before the Sobel operator).

image
image

Our current gaussian blur implementation has one disadvantage. It's not possible to adjust the radius or amount of blur. The thing is: I'm not sure if the blur effect is too high in context of edge detection. You should actually use only a small blur with Sobel in order to get rid of noise (no true edges) in the image.

**Comment by WestLangley** [comment]
I think your use case is problematic, and not a good example. Try
```
var geometry = new THREE.TorusKnotGeometry( 8, 3, 256, 32, 2, 3 );
```
You may not need the blur at all...

**Comment by Mugen87** [comment]
This looks way more better: flushed: ! We need to change this!

**Comment by Mugen87** [comment]
And yeah, we don't need to blur the image in this case.

**Comment by WestLangley** [comment]
Hmmm... The Sobel sensitivity is due to the scene lights -- not so much the geometry.

Try varying the intensities of the point and ambient lights.

**Pull request merged**
