### PR TITLE
Core: Use `structuredClone()` when available.

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
**Description**

At the moment, you can't clone 3D objects when userData has a circular structure.

This is because internally, user data is converted to JSON as a quick way to clone it, but the JSON format can't handle circular structures.

This PR uses `structuredClone` instead of `Json.parse(Json.stringify(userData))` when available, which is faster and supports cloning circular structures.

You can see the error that this PR will fix here: https://codesandbox.io/s/suspicious-monad-wq6d3i?file=/src/index.js

```js
import { Object3D } from "three";

const dataA = {};
const dataB = { dataA };
dataA.dataB = dataB;

const obj = new Object3D();
obj.userData = dataA;

obj.clone();
```

### CODE REVIEW

**Comment by Mugen87** [comment]
`BufferGeometry`, `Texture` and `Material` also have a `userData` property that is copied like in `Object3D`. It's best to apply this change in all respective `copy()` methods.

**Comment by Mugen87** [comment]
We have lately discussed the same topic here: #23956

The idea is to keep `userData` similar to glTF's extras field. Hence, the current policy does not allow cyclic references or functions in `userData`. So I'm not sure it's to give up this policy by using `structuredClone` if there are still limitations in context of serialization/deserialization as well as exporting.

**Comment by RodrigoHamuy** [comment]
@Mugen87 happy to do so, just a few questions:

Q1: `BufferGeometry` only copies the reference, does not deep-clone using JSON. `Texture` and `Material` do use the JSON cloning. Do you want me to update all of them anyway or leave `BufferGeometry` out of it? 

Q2: For my personal use I would even be happy if they all use reference copy rather than deep copy (same as `BufferGeometry`). Would be a lot faster but I get it will be a breaking change for many developers.

Q3: Even if we don't give up on the policy, the policy checking of `JSON.stringify` is more an after effect than a feature in this case. Because nothing is stopping users from doing whatever they want with `.userData`, and they will only realise they have an unsupported structure when they run `.copy` or `.clone`. Maybe will be better to let `.copy` and `.clone` be faster and more flexible. The policy will kick in when somebody tries to serialise the data, which is where it makes sense to trigger the policy anyway.

**Comment by Mugen87** [comment]
> BufferGeometry only copies the reference, does not deep-clone using JSON. 

I think this isn't right. The class should copy `userData` like the three other ones. 

> Maybe will be better to let .copy and .clone be faster and more flexible.

I understand what you are saying. Essentially `structuredClone` wouldn't take anything away, it would introduce new features if the API is supported.

**Comment by RodrigoHamuy** [comment]
Thanks, updated @Mugen87.

**Comment by Mugen87** [comment]
What do you think about adding a new function `deepClone()` in [utils.js](https://github.com/mrdoob/three.js/blob/dev/src/utils.js) and use it in all four classes.
```js
function deepClone( object ) {

	return ( typeof structuredClone === 'function' ) ? structuredClone( object ) : JSON.parse( JSON.stringify( object ) );

}
```

**Comment by RodrigoHamuy** [comment]
@Mugen87 , sure, updated :)

**Review by Mugen87 — APPROVED** [review]

**Comment by epreston** [comment]
How does someone dispose or release the objects ?  You'd have to be null them out on disposal, seems like you'd only want this to happen when you have created them on purpose, not transparently by the library.

I thought the library did not do automatic cloning of circular references for this purpose.  The library user can set them explicitly if they want.  Is this creating a foot-gun ?

**Comment by Mugen87** [comment]
I'm afraid I don't understand your comment. The app is responsible to manage objects and it does not matter for `three.js` how they are created.

Please use the forum if you need to help to understand memory managament or how to dispose of `three.js` objects.

**Comment by epreston** [comment]
I am talking about the cloning of circular references in `userData` by three.js functions.  

It would have been clearer to write: 

When using a clone or copy method in this library or any other, I expect to have to establish and teardown circular references in order to avoid orphaned objects that just soak up memory.  There's a few issues.

- Its not a 'clone' or 'a copy' if it takes over the circular reference from the object its copying.
- if the three.js library does this quietly behind the scenes, the developer will need to remember to null out the circular references
- It's a difficult to see issue because it only shows up far into the development cycle.
- A function to clone and create special application specific references is very little code, so it is not a burden.

It is much more explicit if these are managed (established and disposed of) by the user.  Particularly because this is 'userData'.  It's nice that userData gets passed along but worth not going too far.

Our game can run using 34 MB and avoid getting throttled on phones if we manage things carefully, dispose of resources, and use object caches to avoid small object creation with garbage collection lag spikes.  When something is missed, this memory usage slowly grows.  

This is something easy to miss.  People may remember to cleanup the original object, but forget the clones.  The references would keep the two objects alive, they can't be garbage collected, memory climbs.  When this is needed and carefully managed, its best that the creation and cleanup is separated by a few lines, not libraries.

**Comment by epreston** [comment]
> I'm afraid I don't understand your comment. The app is responsible to manage objects and it does not matter for `three.js` how they are created.

Yes, the app should manage objects.

> Please use the forum if you need to help to understand memory management or how to dispose of `three.js` objects.

I'm not sure how to respond to this.  It doesn't read well.

**Comment by Mugen87** [comment]
In your first comment I had the feeling your are not familiar with the engine's disposal policy and getting things like that explained is not something that should happen at GitHub. The forum is the better place for this.

**Comment by epreston** [comment]
Sorry about that.  When I try to write quickly, it comes out poorly.  When I write carefully, it's too long.

I am concerned about this.  Please don't change the implementation of 'copy' and 'clone' with the functions meant for implementing 'replace'.  I think the intention is to be helpful but the outcome will not be.

**Comment by LeviPesin** [comment]
> The references would keep the two objects alive, they can't be garbage collected, memory climbs.

That's not true. If another reference would point to these objects, they will be kept. Otherwise, no -- JavaScript engines can deal with cyclic references in objects that aren't referenced anywhere except from these cycles.

> Last example is creating a clone or copy of a node in hierarchy, then realising this unintentionally modifies the 3rd object.

I don't see how creating a clone of an object or its user data can modify another object.

> The 3rd object is the one that is not the original or the new replacement, its the other side of the circular reference not being copied.

Can you please rephrase this sentence? I cannot understand what it means.

**Comment by LeviPesin** [comment]
And also I don't see why structure-cloning a JS object with circular references is an issue and why it may be unwanted by a developer.

**Comment by epreston** [comment]
I'm wrong.  

I thought I read `structuredClone` combined with using the parameters for transferable objects.  That is not what is happening.

`structuredClone` will duplicate the outbound references but nothing will reference it back.

**Comment by Mugen87** [comment]
Let's give this a try.

**Comment by elalish** [comment]
I'm getting a very strange error that might be related to this:
```
DOMException{stack: 'Error: Failed to execute 'structuredClone' on 'Window': function onMaterialDispose( event ) {

			const material = event.target;

			material.removeEventListener( 'dis...<omitted>...	} could not be cloned.
    at deepClone (http://localhost:9876/base/node_modules/three/build/three.module.js:1484:10)
    at Mesh.copy (http://localhost:9876/base/node_modules/three/build/three.module.js:7886:19)
    at Mesh.copy (http://localhost:9876/base/node_modules/three/build/three.module.js:11312:9)
    at Mesh.clone (http://localhost:9876/base/node_modules/three/build/three.module.js:7854:33)
    at Group.copy (http://localhost:9876/base/node_modules/three/build/three.module.js:7893:21)
    at Group.clone (http://localhost:9876/base/node_modules/three/build/three.module.js:7854:33)
```

**Comment by mrdoob** [comment]
@elalish

I reverted it in `dev-patch` and made new builds: https://github.com/mrdoob/three.js/tree/dev-patch/build

Let me know if it fixes it.

**Comment by elalish** [comment]
Indeed, that fixes it, at least on my local build. Presumably our CI will agree.

**Comment by mrdoob** [comment]
Okay, I'll publish a new version with this PR reverted.

Sorry @RodrigoHamuy 🙏

**Comment by mrdoob** [comment]
Just published `0.151.2` 👍

**Comment by LeviPesin** [comment]
Maybe we should wrap it in try-catch and revert to using JSON when it errors? /ping @mrdoob @Mugen87 @RodrigoHamuy @sunag

**Comment by LeviPesin** [comment]
So, like so:
```js
function deepClone( value ) {

	try {

		return structuredClone( value );

	} catch {

		return JSON.parse( JSON.stringify( value ) );

	}

}
```

**Comment by mrdoob** [comment]
@LeviPesin You don't think that kind of code can cause confusion for developers?

**Comment by LeviPesin** [comment]
I think it is OK... The fallback wouldn't be triggered most of time and even when it does its result wouldn't differ significantly from the structuredClone's, so it should be OK.

**Comment by mrdoob** [comment]
You don't think that a making a function that can produce different results after doing a tiny change in a data structure can be confusing for the developer?

**Comment by LeviPesin** [comment]
I don't think that this difference would be so significant...

**Comment by mrdoob** [comment]
Is it because you're not able to imagine situations where this would cause problems?
Or you're aware of the problems but you think that developers should live with them?

**Comment by LeviPesin** [comment]
I don't see any major problems that could occur from conditionally using structuredClone or JSON cloning.

**Comment by mrdoob** [comment]
Ok, that explains things.

I can imagine many situations where this can cause hard-to-track-bugs and provide a bad developer experience.
Specially in big teams with interns that do not know the ramifications of their changes.

**Comment by Mugen87** [comment]
I have to agree that using different types of serialization logic depending on the client capabilities is indeed problematic.

**Pull request merged**
