### PR TITLE
NodeMaterial fix needsUpdate

### PR DESCRIPTION
**Pull request by sunag**
it is a hack was the best so far

### CODE REVIEW

**Comment by sunag** [comment]
https://github.com/mrdoob/three.js/issues/15666

**Comment by sunag** [comment]
It seems like I have a different solution to that old problem.
https://github.com/mrdoob/three.js/pull/14442

/ping @Mugen87

**Comment by Mugen87** [comment]
Um, we still need the fix in the renderer for the other materials, right?

**Comment by sunag** [comment]
I think so. After the first compile, define `needsUpdate = true` is indifferent to customize a diferente shader using `onBeforeCompile`. `programCache.getProgramCode( material, parameters )` returns always the same value without this fix in this case.

This only works because of it:
https://github.com/mrdoob/three.js/blob/7fe9a41cb6930d8600305e8ee85830b011e461bb/src/renderers/webgl/WebGLPrograms.js#L249

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
