### PR TITLE
TS: Added types for WebXR

### PR DESCRIPTION
**Pull request by repalash**
Added types for WebXR and fixed object types in WebXR related declaration files.
Related to issue #20041 

Types are adapted from these files.
- model-viewer: https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/types/webxr.ts
- babylon.js: https://github.com/BabylonJS/Babylon.js/blob/master/src/LibDeclarations/webxr.d.ts

### CODE REVIEW

**Comment by mrdoob** [comment]
> @mrdoob I figured since it doesn't declare types for any three.js specific module, it should be put it extras. Do you think I should move it to `src/renderers/webxr`?

I think so yes.

> Also, I haven't exported these types in [Three.d.ts](https://github.com/mrdoob/three.js/blob/dev/src/Three.d.ts), should that be done? Would it be useful? 

No idea, I have no experience with Typescript...

**Comment by mrdoob** [comment]
Looking good!

Just a few linting warnings. Are these fixable?
https://github.com/mrdoob/three.js/pull/20150/files

**Comment by PalashBansal96** [comment]
Yeah, fixed.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
