### PR TITLE
Examples: Add eye rotation to `webgl_morphtargets_webcam`.

### PR DESCRIPTION
**Pull request by vis-prime**
**Description**

Using the eye rotation morph/blend scores to drive the eyeball mesh rotation

Before | After

https://github.com/vis-prime/three.js/assets/119810373/c05d8fb7-6fca-4487-845b-8221563b4b16

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Is the PR ready to merge or still working on it?

**Comment by vis-prime** [comment]
one small change left ! `MathUtils.mapLinear` is not needed , will update soon

**Review by Mugen87 — APPROVED** [review]

**Comment by amitdubey6261** [comment]
Wow!, wonderful work @vis-prime

**Pull request merged**
