### PR TITLE
fix warnings sea3d and nodematerials

### PR DESCRIPTION
**Pull request by sunag**
https://github.com/mrdoob/three.js/issues/15468

### CODE REVIEW

**Comment by sunag** [comment]
i will fixed the warns in nodematerial

**Comment by sunag** [comment]
@WestLangley Did this correct the nodematerial examples?

**Comment by WestLangley** [comment]
>@WestLangley Did this fix the nodematerial examples?

Yes.

I see however, in `examples/webgl_materials_nodes.html`, `adv / translucent` option, plus in some other cases, I get this warning:

    getsize() now requires a Vector2 as an argument

**Comment by WestLangley** [comment]
You need to fix `getsize()` in `ResolutionNode.js`.

**Comment by sunag** [comment]
@WestLangley I guess it's okay now?

**Comment by WestLangley** [comment]
@sunag Thanks!

**Comment by sunag** [comment]
:+1:

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
