### PR TITLE
Cylindrical: Support for Cylindrical Coordinates

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adds basic support for cylindrical coordinates (analogous to `Spherical`).

https://en.wikipedia.org/wiki/Cylindrical_coordinate_system

### CODE REVIEW

**Comment by Mugen87** [comment]
The notation of the components is currently: `radius`, `theta`, `y`. In some sources i've seen `rho` instead of `radius` and `height` instead of `y`. Not sure if these names fit better...

**Comment by WestLangley** [comment]
I think you should add `Vector3.setFromCylindrical( c )`.

Your notation looks fine to me.

**Comment by Mugen87** [comment]
Done!

**Comment by mrdoob** [comment]
Looks good! Thanks!

**Comment by Mugen87** [comment]
Okay, i will have a look. If somebody else finds an appropriate example or use case, just post it here.

**Comment by Mugen87** [comment]
Found one! 😉 The display of elements in `css3d_periodictable` as a sphere or helix is now done via `Spherical`/`Cylindrical`.

**Pull request merged**
