### PR TITLE
Material.d.ts: Fix onBeforeCompile parameter.

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/commit/3c934fc34d5c8a27021716d3dcd73120919b09e2#commitcomment-41033310

### CODE REVIEW

**Comment by Mugen87** [comment]
@mrdoob I guess I would be good to cherry-pick this to prod.

**Review by IhostVlad — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> @mrdoob I guess I would be good to cherry-pick this to prod 😇 .

Done!

**Comment by Mugen87** [comment]
Thanks!

**Pull request merged**
