### PR TITLE
Editor: ability to load a scene from a URL parameter

### PR DESCRIPTION
**Pull request by waldenn**
Hi,

This PR makes it possible to:
- **Load a scene from an URL parameter named "scene".**
  
  Examples:
   http://wikischool.org/three.js/editor/index.html?scene=../examples/scenes/knot.json
   http://wikischool.org/three.js/editor/index.html?scene=../examples/scenes/boxes.json
- **Put a simple hash key (based on the URL string without the http(s) part ) in the storage name, so multiple scenes can be loaded and used in the same browser without interference to the scene data.**
  
  Example: http://wikischool.org/wiki/test-multiple-scenes

I feel there is still another issue that needs to be resolved for this work nicely: The localstorage key is not hashed, so any data like the: renderer, camera position / target, etc. are shared between browser views.

Perhaps some of that localstorage data should be managed by global-defaults and locally-overwriting data. So one localstorage item for global data and then optionally one for overwriting local data. Perhaps this is too complicated though.

Thanks,

Walden

### CODE REVIEW

**Comment by WestLangley** [comment]
FYI: Using Safari 8.0.2 on OS X, your examples fail with this error:

    TypeError: FileConstructor is not a constructor (evaluating 'new File( [text], sceneURL, {type: "", lastModified: ""})')

Works with Chrome 39.

**Comment by walden-** [comment]
Ok, thanks. I am on Linux + Chrome, but will see if I can find a fix this.

I also found another issue: Everytime the scene URL is loaded it adds the scene data over the previous state. Will see how to fix this too.

**Comment by mrdoob** [comment]
I like the ideo though! Also, seeing multiple editors in one page is... uhm... unexpected, but cool!

**Comment by walden-** [comment]
Hmm, doing something wrong with Git. Will create another PR when I figure things out.

**Comment by mrdoob** [comment]
Implemented! 1842993471ec62060e81a85f709e64a663c8a913

Example: http://threejs.org/editor/#app=https://gist.githubusercontent.com/mrdoob/6e9e6913abd9ac994841/raw

**Comment by mrdoob** [comment]
Well, I guess `#scene=` would also be nice to have.

**Comment by walden-** [comment]
Thats really great. Amazing how much progress is being made with the editor lately.

Are you also going to implement some hash mechanism for the indexdb (and perhaps also the localdb), so we can edit multiple scenes / apps in the same browser? That would complement this functionality nicely I think.

Looking forwards to playing with all this and perhaps contributing more ideas.

**Comment by mrdoob** [comment]
Yep! Some sort of asset manager is definitely needed ASAP.  Multiple sessions and undo/redo is a bit more tricky...

**Pull request closed without merging**
