### PR TITLE
Added transform methods to Geometry and BufferGeometry

### PR DESCRIPTION
**Pull request by WestLangley**
Added

```
geometry.rotateX( angle )
geometry.rotateY( angle )
geometry.rotateZ( angle )
geometry.scale( x, y, z )
geometry.translate( x, y, z )
geometry.lookAt( v )
```

See discussion in #6965

### CODE REVIEW

**Comment by WestLangley** [comment]
@TatumCreative I started to add the new methods to the docs, but bailed. It is not clear to me how to properly specify the return value. Would you please have a look, and check the docs for consistency? Next time I'll do it myself. : - )  Thanks.

**Comment by mrdoob** [comment]
This makes things much nicer indeed. Thanks for updating all the examples!

**Comment by TatumCreative** [comment]
Sent a PR for the docs. I gotta say, this feature will be handy to have.

@WestLangley This is how we've been doing return values:

`[method:ReturnType methodName] ( [page:ParameterType parameterName] )`

`<h3>[method:BufferGeometry rotateX] ( [page:Float radians] )</h3>`

**Comment by WestLangley** [comment]
@TatumCreative Many thanks!

**Comment by mrdoob** [comment]
You guys are the best! 😊

**Pull request merged**
