### PR TITLE
Fix HTMLMesh image draw coordinates

### PR DESCRIPTION
**Pull request by mkeblx**
Related issue: #25655 

**Description**
A small fixup for https://github.com/mrdoob/three.js/pull/25916.

For drawing images using `drawImage`, adding a 0.5 offset is generally not necessary. The 0.5 offset is primarily used for drawing crisp lines and shapes, where sub-pixel rendering might cause blurriness, but as image itself already contains pixel data, this should not be needed.

See some comparisons here, the 1st images are without offset and are of highest quality:
https://codepen.io/mkeblx/pen/dygvqPL

@vincentfretin

### CODE REVIEW

**Comment by vincentfretin** [comment]
I tested without and I had an unwanted 1px gray line (when I used the image without border styles). I had to use -0.5 and +0.5 to get rid of those lines.

**Comment by vincentfretin** [comment]
The first image in your codepen looks higher quality indeed, but it appears to contain 1px border on the left, that doesn't seem to be in the original image. Or is it just me?

**Comment by vincentfretin** [comment]
Ok I understand a bit better the issue here.
In my case the 1px top and left border I was seeing was because of the button background. 
```html
<button style="background:white; border:1px solid blue">
  <img src="image.png">
</button>
```
When I'm doing -0.5, this fixes the image position to be at the same position as the button rect, but then I get the white border on the bottom and right. So I used +0.5 there as well to fix it but that deforms the image I guess but not really visible in VR for me.
I don't really care about the background color here, I can use background-color: inherit, but I want a border color to be really around the image.

**Comment by vincentfretin** [comment]
I tried
```
                        x = rect.left - offset.left - 0.5;
			y = rect.top - offset.top - 0.5;
			width = rect.width;
			height = rect.height;
```
For me it should be like that to match the rect rendering of the button.

and used border-width: 1px instead of 2px, now the image is centered in the button correctly, but with a 0.5px of background color showing on all 4 sides.
So what I did is set background-color the same as border-color, so I changed this from my above html snippet:
```
    background-color: blue;
    border: 1px solid blue;
```
Then the render is perfect for me in VR. For the image quality, I don't know, I don't see any difference in VR with Quest 1 where I'm testing.
I also tried removing the -0.5 offset of both image and button rect. I don't see any difference.

**Comment by vincentfretin** [comment]
I created https://github.com/mrdoob/three.js/pull/25930
If you see a real difference of quality with the -0.5 offset, we could maybe remove it and not do the -0.5 offset for button here if we detect there is an image as a child?
https://github.com/mrdoob/three.js/blob/49cee8ee8dcae800e026e87f4857a4853a3a4322/examples/jsm/interactive/HTMLMesh.js#L295-L296

but more generally do you see a difference with and without the -0.5 offset that is applied in different part of the code?

**Comment by mrdoob** [comment]
@mkeblx I've merged #25930 but happy to merge this one if you think it's right.

**Comment by mkeblx** [comment]
It may not be the easiest to see as it's a small difference but eventually it should be no offset.

However, to properly handle and play nicely with borders it'll need some adjustment.

`element.getBoundingClientRect()` computes width & height with border (and padding) included, which will result in the image being drawn at the wrong size.
```html
<img id="image" src="test.jpg"  width="100" height="100" style="border: 25px solid blue; padding: 25px">
```
```js
image.getBoundingClientRect() => { width: 200, height: 200, ... }
```

I'll update PR.

**Comment by vincentfretin** [comment]
Please note that in my example the border is on the button, not the image. Also I have `box-sizing: border-box` on all elements (I'm using tailwindcss)

**Comment by vincentfretin** [comment]
and I don't have padding on img either, but you're right if someone use a border and padding on img, the image size and position will be wrong.
Be careful box-sizing border-box doesn't include the border in the width/height, the default box-sizing content-box includes the border.

**Pull request closed without merging**
