### PR TITLE
[Blender Exporter] support BasicMaterial

### PR DESCRIPTION
**Pull request by yomotsu**
for #7627

When you check `shadeless` in Material Pane, it will be published as `BasicMaterial`

screen shot 2015-11-19 at 6 47 06 am

the JSON

```
// snip
   "materials": [{
        "DbgName": "Material",
        "visible": true,
        "wireframe": false,
        "transparent": false,
        "blending": "NormalBlending",
        "depthWrite": true,
        "colorDiffuse": [0.64,0,0],
        "shading": "basic",
        "DbgIndex": 0,
// snip
```

### CODE REVIEW

**Comment by Mugen87** [comment]
@yomotsu Thanks for this!

**Comment by Mugen87** [comment]
This line here will cause the error, because `THREE.MeshBasicMaterial` has no property `emissive `: https://github.com/mrdoob/three.js/blob/dev/src/loaders/MaterialLoader.js#L58

**Comment by mrdoob** [comment]
> To avoid a runtime error

Is it a runtime error or a warning?

**Comment by Mugen87** [comment]
```javascript
if ( json.emissive !== undefined ) material.emissive.setHex( json.emissive );
```

If `material.emissive` is `undefined` ( and that's the case for `THREE.MeshBasicMaterial`) , it's a runtime error.

**Comment by yomotsu** [comment]
@Mugen87 thanks, yeah that's right. I'll add support for that as well, but also three.js could handle that [like this line in JSONLoader.js](https://github.com/mrdoob/three.js/blob/dev/src/loaders/Loader.js#L250)

@mrdoob How do you think...?

**Comment by mrdoob** [comment]
@Mugen87 I see... The problem is somewhere else though. 

If you guy can send me a exported file I'll handle the rest.

**Comment by Mugen87** [comment]
Check out this simple model: http://yume.human-interactive.org/downloads/model.zip

The archive contains the json.file and a texture.

**Comment by mrdoob** [comment]
Sorted. Thanks guys!

**Pull request merged**
