### PR TITLE
MeshPhysicalMaterial: Initialise sheen by default and only enable sheen bsdf when is not black.

### PR DESCRIPTION
**Pull request by mrdoob**
@DanielSturk @sunag @bhouston 

What do you guys think of this change? Is there a case where a sheen of 0,0,0 makes sense?

### CODE REVIEW

**Comment by sunag** [comment]
This is nice cleanup and work in most cases except in case of `sheen` value is changed in `update` loop, the user would define a non-zero value to initialize the material with `sheen`, It can be a bit confusing if he wants to animate the `sheen color` from an arbitrary value, but considering this from a non-NodeMaterial (how did you do) I think that this is not a problem.

**Comment by sunag** [comment]
@mrdoob I think that `needsUpdate` should be deprecated, in this sense `sheen = null` seems to make more sense.

**Comment by DanielSturk** [comment]
I prefer sunag's solution, which is to use sheen=null to turn off sheen, mainly because it makes it animatable without using `needsUpdate`.

To be clear, sheen overrides the brdf, so black sheen =/= sheen off.

You can test this in `webgl_materials_physical_sheen.html` by setting sheen=black, and then turning on/off the `sheen brdf` parameter (hint, it's only a subtle difference).

In the long term, I definitely would like to remove the need for recompiling when turning on/off sheen, as well as anisotropy, but right now they aren't using compatible brdfs, so we'd have to combine them.

**Comment by mrdoob** [comment]
I think `null` is probably the way to go after all...

**Pull request closed without merging**
