### PR TITLE
Added Object3D.quaternion support to ObjectLoader.

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**

### CODE REVIEW

**Comment by mrdoob** [comment]
I would make it simpler...

```js
if ( data.rotation !== undefined ) object.rotation.fromArray( data.rotation );
if ( data.quaternion !== undefined ) object.quaternion.fromArray( data.quaternion );
```

**Comment by Benjamin-Dobell** [comment]
Done.

**Comment by Benjamin-Dobell** [comment]
Whoops, sorry *now* it's done.

**Comment by GGAlanSmithee** [comment]
Just wanted to point out that the last commit  was not only syntactical, but also logical since you changed the branching `if ... else if ...` to two consecutive `if ...` statements. If this is intentional, all is well, just wanted to let you know in case you missed it.

**Comment by Benjamin-Dobell** [comment]
@GGAlanSmithee Yeah, that's why I had it the other way originally. There's no logical situation in which you can have both `rotation` and `quaternion`.

By checking `rotation` first, then the existing behaviour has priority. Which I guess this still does as well (if you've got auto-updating matrices), but it's confusing because it allows different values to be set on the `quaternion` and the `rotation` - not that anyone should reasonably do that. But we already had a branch very similar (which this code is inside of) for specifying the matrix vs. composition.

But yeah, that was my logic. It's probably not a huge deal as you really *shouldn't* specify both.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
