### PR TITLE
Object3D: added log() method

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in #10961.

This version will count -- rather than print -- duplicated rows, limiting repeated output.

Feel free to improve it.

### CODE REVIEW

**Comment by mrdoob** [comment]
I may not be reading the code correctly but... doesn't this code log only the node and the ancestors of the passed node? I thought #10961 was about logging the node and the descendants.

**Comment by WestLangley** [comment]
It logs the children, traversing parents to compute indentation. It does not have to be efficient.

**Comment by jostschmithals** [comment]
> Feel free to improve it.

I don’t know whether it would be an improvement, but what about combining both of the versions  presented in #10961?
 
For example like this:
```
        log: function ( collapsible ) {
            
            if (collapsible) {
            
                (function printGraph( obj ) {

                    console.group( obj.name + ' <%o> ', obj );

                    obj.children.forEach( printGraph );

                    console.groupEnd();

                }(this));
                
            } else {

                this.traverse( function ( obj ) {

                    var s = '|___';

                    var obj2 = obj;

                    while ( obj2.parent !== null ) {

                        s = '\t' + s;

                        obj2 = obj2.parent;

                    }

                    console.log( s + obj.name + ' <' + obj.type + '>' );

                } );
                
            };

        }
```

- Simply calling `object.log()` would offer the mentioned advantage of limiting repeated output (by counting duplicated rows):

scenegraphwl

- Calling `object.log(true)` would provide the ability to fold and unfold the objects in deeply nested hierarchies:

scenegraph_doublecollapsing

Note: In this manner (with double folding possibility) only in Chrome!

**Comment by mrdoob** [comment]
I think I agree with @spite in #11030. Maybe it's better to leave these out of the lib...

**Comment by WestLangley** [comment]
OK. Closing.

**Pull request closed without merging**
