### PR TITLE
Partial revert of some WebVR 1.1 changes

### PR DESCRIPTION
**Pull request by toji**
They didn't produce correct eye translations in all cases (specifically
standing scenes.) This reverted version may not be 100% accurate on
future hardware (if the eyes have a rotation component, for example) but
it's correct on all current WebVR implementations. That's better than
blatantly wrong in some cases.

Use of the WebVR-provided projection matricies has been left in, since
that was working correctly.

Addresses #9708 for the time being. I'll keep looking into it.

### CODE REVIEW

**Comment by arturitu** [comment]
Thanks, I just updated the project with this provisional version and works great with 1.1.
I hope to be published soon.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Should I cherry-pick this to `master`?

**Comment by toji** [comment]
Probably be a good idea. Without it anyone with the latest Chrome build will get weird stereo convergence issues on the Vive samples when looking up or down by a significant amount.

**Comment by mrdoob** [comment]
Done!

**Pull request merged**
