### PR TITLE
Update LensFlare.html

### PR DESCRIPTION
**Pull request by that-ben**
Only added a paragraph at the bottom of the page to describe a common pitfall.  It would be very useful if this was part of the official documentation as I searched for 1 hour before realizing this.  It's not explained anywhere else.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, no other page in the documentation has the "Common Pitfalls" section. How about just adding a note in the description section at the top instead?

https://github.com/mrdoob/three.js/blob/dev/docs/api/objects/LensFlare.html#L15

Something like...

```html
<div class="desc">Creates a simulated lens flare that tracks a light.<br />
Note: WebGLRenderer must have alpha set to true for LensFlare to work.</div>
```

**Comment by that-ben** [comment]
Wouldn't it be nice to have such a "common pitfalls" section at the bottom? It would help beginners and relief a lot of redundant issues on GitHub, StackOverflow etc... no?

**Comment by mrdoob** [comment]
> But wouldn't it be nice to have such a "common pitfalls" section at the bottom? It would help beginners and relief a lot of redundant issues on GitHub, StackOverflow etc... no?

That's a difficult one. Who decides what's common or not? 😉

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
You can now say that you've contributed to an open source project! 😀

**Comment by that-ben** [comment]
mrdoob: That's a difficult one. Who decides what's common or not? :wink:

StackOverflow etc?

**Pull request merged**
