### PR TITLE
JSM: Update rollup examples config to merge and convert files

### PR DESCRIPTION
**Pull request by gkjohnson**
Related to #16917, #16688.

This PR updates the `build-examples` script to provide the ability to specify which files will be merged into a single UMD file in the `examples/js/` directory from `examples/jsm/`. At the moment only EffectComposer and Pass are merged into a single file but it can be extended to merge other files including /nodes once #16917 is merged:

```js
var mergedFiles = [{
  paths: ['nodes/**/*.js'],
  input: 'nodes/Nodes.js',
  output: 'nodes/Nodes.js',
}, {
  paths: ['curves/**/*.js'],
  input: 'curves/index.js',
  output: 'curves/index.js',
},
// ...
];
```

Every other file is converted as-is with dependencies being considered external.

You can see the output of the conversion [here](https://github.com/gkjohnson/three.js/tree/rollup-example-build/examples/js) and the diff [here](https://github.com/mrdoob/three.js/compare/dev...gkjohnson:rollup-example-build). Looking at what isn't generated it seems like `WebGL.js`, `loader/ctm/CTMWorker.js`, `offscreen/*`, `vr/*`, and `renderers/RaytracingWorker.js` are the only other files that need to be converted to modules.

I haven't had a chance to test everything yet but looking at the files it looks correct. It may be worth reverting to the pre-module versions of the example files to test that these new version work as expected.

@Mugen87 @donmccurdy

### CODE REVIEW

**Comment by Mugen87** [comment]
>  It may be worth reverting to the pre-module versions of the example files to test that these new version work as expected.

I've done this today and found no issue related to this PR. The OBJ2 examples break but only because the JSM version was temporarily different than the "normal" version in the `js` directory. The  `EXR` example was also broken but only because the JSM version was not up to date.

So it seems the script produces a usable output. The only thing that bothers me a bit is the fact that the linter complains about the wrong code styles in the generated files. I don't think this blocks the PR in any form but it would be nice if the files are formatted according to `mdcs`.

**Comment by gkjohnson** [comment]
> I've done this today and found no issues related to this PR.

Woo! Thanks.

>The only thing that bothers me a bit is the fact that the linter complains about the wrong code styles in the generated files.

Yeah unfortunately I'm not sure how much control control we have over the UMD require block that gets generated:
```js
(function (global, factory) {
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('three')) :
typeof define === 'function' && define.amd ? define(['exports', 'three'], factory) :
(global = global || self, factory(global.THREE = global.THREE || {}, global.THREE));
}(this, function (exports, THREE) { 'use strict';
// ...
})();
```

But we do have control over the indentation. I've disabled the extra indentation to make the diff easier to look at and files easier to edit but we can re-enable the added indentation so the linter doesn't spew so much by removing this line:

```js
indent: false,
```

Once modules are in place I think it would be great to get the linter running over the examples/jsm files, as well.

**Review by Mugen87 — APPROVED** [review]

**Comment by gkjohnson** [comment]
It also occurred to me that we could run `eslint --fix` on the generated UMD files to clean up the errors, as well.

**Comment by donmccurdy** [comment]
> Once modules are in place I think it would be great to get the linter running over the examples/jsm files...

Definitely. 👍

> The only thing that bothers me a bit is the fact that the linter complains about the wrong code styles in the generated files.

Just a thought, but maybe the UMD files should be minified, and omitted from the ESLint run? That would eliminate most confusion about which files to edit in PRs...

**Comment by Mugen87** [comment]
Um, I think it's more user-friendly when the UMDs are not minified. This makes debugging easier which is an important factor. Especially when we include these files in fiddles or codepens.

**Comment by donmccurdy** [comment]
Ah, yeah the debugging point is a good one.

For fiddles and codepens I think we can encourage people to use ES modules maybe, but there are lots of developers using CommonJS in build systems like Browserify still and that's fine.

**Comment by Mugen87** [comment]
I've checked the script with `NodeMaterial` and `OBJLoader2` again and it seems the output is not usable. Right now, it tries to create UMDs for all files like `ResolutionNode`. However, this file depends on many other files which are not in the `THREE` namespace anymore. E.g. the ctor of `ResolutionNode` looks like so:
```js
Vector2Node.call( this );

this.size = new Vector2();
```
The script creates this:
```
Vector2Node_js.Vector2Node.call( this );

this.size = new THREE.Vector2();
```
Maybe it's better to exclude `NodeMaterial` and `OBJLoader2` for now. Or you try to bundle everything in a single file if possible.

**Comment by gkjohnson** [comment]
I can test those two files maybe tomorrow or Friday -- for `nodes` my expectation is that they would all be bundled together into a single file:

```
{
  paths: ['nodes/**/*.js'],
  input: 'nodes/Nodes.js',
  output: 'nodes/Nodes.js',
}
```

I know that nodes were originally using imports but was OBJLoader originally a module? Or hand converted from the THREE examples? Why is it different?

**Comment by Mugen87** [comment]
> Or hand converted from the THREE examples?

This one. The old code was deleted.

**Comment by Mugen87** [comment]
Um wait. I've had a closer loo to other files now. `ColladaLoader` has a dependecy to `TGALoader`. The script produces this output in the UMD:

```js
if ( TGALoader_js.TGALoader ) {
```
which does not seem to be correct. I think it should be
```
if ( THREE.TGALoader ) {
```
Since when you include the UMD version of  `TGALoader`, the class is available in the `THREE` namespace.

**Comment by gkjohnson** [comment]
Oh interesting a change I made to this function may have broken it because it was definitely working before:

```js
function resolveGlobalObject( depPath ) {

 	if ( isLibrary( depPath ) ) {

 		return 'window';

 	} else {

 		return 'THREE';

 	}

 }
```

I'll do more testing.

**Comment by gkjohnson** [comment]
> The script produces this output in the UMD:
> ```
> if ( TGALoader_js.TGALoader ) {
> ```
>  which does not seem to be correct. It should be
> ```
> if ( THREE.TGALoader ) {
> ```

To elaborate on this a bit more this is actually correct and expected given the way that rollup converts files. The files are converted to the UMD format, which supports `require` statements (which weren't supported before) and global script tags. Take the ColladaLoader, for example, which imports THREE and TGALoader:

```js
import { TGALoader } from './TGALoader.js';
import { /* ... */ } from '../../../builds/three.module.js';
```

Rollup passes each of these imports in as a separate object so when using require it calls the ColladaLoader definition function with the following arguments (the first argument being the exported object that ColladaLoader will be added on to):

```js
// UMD
(exports, require('three'), require('..\TGALoader.js'))
```

When loading in a global script context, though, we've specified that all the exports should be loaded from the global `THREE` object so instead it calls the function like so:

```js
// global script
(global.THREE = global.THREE || {}, global.THREE, global.THREE)
```

The function that's getting called has a signature that looks like this:

```js
function (exports, THREE, TGALoader_js) {
```

The `THREE` and `TGALoader_js` variables names cannot be the same because it would break UMD loading. The `THREE` name in this case was originally `three_module_js` but is regex replaced [here](https://github.com/mrdoob/three.js/pull/16920/files#diff-b93907300a0d0e7da1ebfcb53667db7dR34) to maintain the old `THREE` naming.

I know it's a bit convoluted but I hope that explanation was clear. I haven't looked into a way to share the THREE name across all imports but if it's strongly desired maybe we can take a look later, though I'd prefer to do that in a future PR.

Regarding the nodes and OBJLoader2 files -- have you actually tried to use them and found them unusable? Or did the code just look unfamiliar or have unexpected variable names?

**Comment by Mugen87** [comment]
Okay, thanks for the explanation! I think the syntax is okay like that. I just wanted to know the reasons behind it. 

> Or did the code just look unfamiliar or have unexpected variable names?

This one. I did not had the time to refactor the examples in order to test `NodeMaterial` and `OBJ2Loader`.

**Comment by Mugen87** [comment]
@mrdoob I think we should give this PR a try and see how it goes. We can then deprecated `modularize.js` and primarily work with module version of the example code.

**Comment by Mugen87** [comment]
I suggest merging this at the beginning of `R108` dev cycle. Then we have enough time to verify it on `dev`.

**Comment by Mugen87** [comment]
@mrdoob Do we want to give this PR a try now? It's the last step to finalize the module conversion.

**Comment by gkjohnson** [comment]
Especially with all of the examples being converted to modules I think it's important that this switch be made -- I've seen a number of PRs recently that only modify the `jsm` files inadvertently because that's the easiest way to test them (my own included 😳). It would also be good to add early in the month before the r108 release to get more time in for testing.

If something needs more explaining or we'd prefer to change the output of the rollup config let me know and I'll be happy to discuss / investigate!

This is maybe related but are there any open PRs that are being considered that modify the `js` files that would need to be merged first?

**Comment by mrdoob** [comment]
Sorry for the delay.

So... I think the strategy I'm more comfortable with by leaving `examples/js` alone 😕

**Use case 1 - Improve existing file, say... GLTFLoader**
 1. Update `examples/js/loaders/GLTFLoader.js`
 2. Run `modularize.js`

**Use case 2 - Add new file, say... SuperMegaControls**
 1. Add `examples/jsm/controls/SuperMegaControls.js`

The idea is to update existing files in `examples/js` for backwards compatibility but if people want to use new controls, loaders, vr, ... then they'll have to switch to modules.

**Comment by gkjohnson** [comment]
> I think the strategy I'm more comfortable with by leaving `examples/js` alone

Hmm. Can you elaborate on what exactly makes you uncomfortable? Maybe I can find a way to convert them in a more agreeable way and simplify the config. The strategy you proposed seems like it could be a bit confusing to me, as well.

If there are some examples only available as modules then new users will have to understand which examples are available where (I feel like I still see people using the old script tags but maybe that will die out soon). Contributors will also then have to understand which example file to edit and why, which won't be immediately clear.

I think the bigger reason I would like the jsm files to be canonical is that development / maintenance process for examples is really poor at the moment. All the example pages now use the jsm files which means updating an example script involves 

- editing the module file so you can actually see the changes in the browser
- copy and pasting the changes to the /js file making sure you didn't miss anything
- running modularize.js
- make sure the script still works
- repeat for further updates / change requests

You could edit the /js files directly but then that requires manually rerunning modularize every time to actually see the changes.

**Comment by mrdoob** [comment]
> Hmm. Can you elaborate on what exactly makes you uncomfortable?

Basically, I was hoping the JS to JSM situation to be transitory. If we convert new JSM files to JS, then we're giving the signal that we support both modes and user will expect new JS files added. On top of the `.d.ts` files, maintenance will becomes pretty unfun.

> (I feel like I still see people using the old script tags but maybe that will die out soon)

That's the idea.

> Contributors will also then have to understand which example file to edit and why, which won't be immediately clear.

Yeah. We could also stop updating JS files and only update JSM files from now on. Maybe add a `console.warn()` to let people know.

**Comment by Mugen87** [comment]
Okay. In this case, we can close the PR.

> You could edit the /js files directly but then that requires manually rerunning modularize every time to actually see the changes.

We could consider to add a npm `watch` script that does this automatically as soon as you save a js file.

**Comment by gkjohnson** [comment]
@mrdoob 
> Basically, I was hoping the JS to JSM situation to be transitory. If we convert new JSM files to JS, then we're giving the signal that we support both modes and user will expect new JS files added. On top of the .d.ts files, maintenance will becomes pretty unfun.

Hmm okay it still doesn't feel quite right to remove the js modules completely especially given all the module import / resolution problems mentioned in some other threads, even if just to support the hacking / static example page with CDN-served libraries cases. Maybe I'm just feeling nostalgic, though :)

Ideally converting the jsm files to UMD would require little to no maintenance. This PR did get complicated but I think it can be simplified if some of the other levied requirements were loosened. Would it be worth proposing a different, simpler, examples rollup config?

>  We could also stop updating JS files and only update JSM files from now on. Maybe add a console.warn() to let people know.

If this is the plan, though, is there any timeline when you might expect we can consider the `jsm` modules canonical and mark the `js` files as deprecated? I can help add the warning to the files if you think it's time. Of course my preference is to do this sooner rather than later.

**Comment by mrdoob** [comment]
> Hmm okay it still doesn't feel quite right to remove the js modules completely especially given all the module import / resolution problems mentioned in some other threads, even if just to support the hacking / static example page with CDN-served libraries cases. Maybe I'm just feeling nostalgic, though :)

I know what you mean. But I'm trying to make sure we don't end up in a situation were there are too many things to consider in order to advance. We can definitely keep these files for a year or so though.

> Ideally converting the jsm files to UMD would require little to no maintenance. This PR did get complicated but I think it can be simplified if some of the other levied requirements were loosened. Would it be worth proposing a different, simpler, examples rollup config?

I think it's better to deprecate these files and encourage people to move to ES6 Modules. A single code path it's easier to maintain than two. And, considering the recent discussions, seems like ES6 Modules are already problematic enough 😣

> If this is the plan, though, is there any timeline when you might expect we can consider the `jsm` modules canonical and mark the `js` files as deprecated? I can help add the warning to the files if you think it's time. Of course my preference is to do this sooner rather than later.

Yes, I think so. I think we can consider `jsm` modules canonical already and start adding the warnings to the `js` files.

**Comment by donmccurdy** [comment]
> Yes, I think so. I think we can consider jsm modules canonical already and start adding the warnings to the js files.

What do you mean by "canonical"? I think I've been using "canonical" to refer to the file a contributor should edit, and from which other files are generated. Did you mean that, or just that the JSM files should be recommended to end-users?

**Comment by donmccurdy** [comment]
^Or do we mean that contributors should edit the JSM files, and the JS files would not be updated _at all_ moving forward? The wording, "no longer maintained or updated", in https://github.com/mrdoob/three.js/pull/17544 makes it sound like that is the plan...

I'm not sure about that... if the point of keeping them is to give users time for the transition to ES modules, providing r108 GLTFLoader in the r115 three.js distribution seems like a confusing way to do so.

**Comment by Mugen87** [comment]
> I'm not sure about that... if the point of keeping them is to give users time for the transition to ES modules, providing r108 GLTFLoader in the r115 three.js distribution seems like a confusing way to do so.

Agreed. This will only lead to confusion.

**Comment by mrdoob** [comment]
> I'm not sure about that... if the point of keeping them is to give users time for the transition to ES modules, providing r108 GLTFLoader in the r115 three.js distribution seems like a confusing way to do so.

Indeed! I thought a bit more about this and realised the same, specially when we change APIs in core and we update the examples too.

How about we continue using the existing `examples/js` files as canonical but we add a message warning the user that these version of the files will be deprecated in.. say... January 2020?

**Comment by gkjohnson** [comment]
@mrdoob heh I have a comment in the other issue (https://github.com/mrdoob/three.js/pull/17544#issuecomment-534221453) but let's continue the conversation here.

> How about we continue using the existing `examples/js` files as canonical but we add a message warning the user that these version of the files will be deprecated in.. say... January 2020?

I'd prefer to the get the modules canonical sooner but January isn't that far away, I suppose, if we're _definitely_ going to remove them then. We'll have strip the warning when generating the modules, though, or the jsm files will include it, too. My preference would be to generate the js files from jsm like which would give us a bit more leeway.

From https://github.com/mrdoob/three.js/pull/17544#issuecomment-534221453:
> What if we meet in the middle and use rollup to only generate /js versions from modules for files that already exist in the /js folder and add a warning like the above to warn users that they will be deprecated. That script should be pretty simple, will keep them working until we want to remove them with no new modules being added, and will let us edit the jsm modules directly for PRs and testing. /js examples can be generated before a release like builds are.

**Comment by donmccurdy** [comment]
> How about we continue using the existing examples/js files as canonical but we add a message warning the user that these version of the files will be deprecated in.. say... January 2020?

What specifically would happen in January 2020?

**Comment by mrdoob** [comment]
> What specifically would happen in January 2020?

Removal of `examples/js` folder...? 🙊

**Comment by donmccurdy** [comment]
Ok, if we think we'd be willing to remove `examples/js` on that timeline — or at least announce it and see what issues are raised — then I'd vote to:

1. Put a deprecation notice into the js/ files now.
2. Continue generating jsm/ from js/, stripping that notice.
3. **Do not** proceed with generating js/ from jsm/, since Jan 2020 is soon enough to make that transition unnecessary.

**Comment by gkjohnson** [comment]
A few months is definitely better than a year or so :) As long as there's a light at the end of the tunnel.

> 1. Put a deprecation notice into the js/ files now.
> 1. Continue generating jsm/ from js/, stripping that notice.

I updated #17544 to include both of these.

**Pull request closed without merging**
