### PR TITLE
NodeMaterial improvements

### PR DESCRIPTION
**Pull request by sunag**
- `reflectivity` to `environmentAlpha` in Phong/Standard `Node`

I think we can use `environment` input to `refraction` and `reflection` with `alpha` input.
- vec2 to normalmap scale https://github.com/mrdoob/three.js/pull/7830
- flip refraction options `webgl_postprocessing_nodes.html
  `

### CODE REVIEW

**Comment by WestLangley** [comment]
>reflectivity to environmentAlpha in Phong/Standard Node
>I think we can use environment input to refraction and reflection with alpha input.

There may be some confusion here.

`MeshPhongMaterial` handles environment maps differently than `MeshStandardMaterial`. 

1. `Phong` uses a "hack" of sorts, and Standard uses a PBR approach.
2. `Phong` has the property `reflectivity` which is nominally between 0 and 1.
3. `Standard` does not have a `reflectivity` property.
4. `Standard` treats the environment map as as source of light, and has the property `environmentMapIntensity`, which can be any positive number. It does not make sense to call it "alpha".

What dose  make sense to me is to have something called "alpha" that takes values in [ 0, 1 ], and something called "intensity" that takes values in [ 0, infinity ].

**Comment by sunag** [comment]
> Phong has the property reflectivity which is nominally between 0 and 1.

My idea is not to use the `reflectivity` term because `environment` input can be used to `refraction` too.

**Comment by WestLangley** [comment]
@sunag The problem is that `reflectivity` is a property of the _material_, and `intensity` is a property of the environment map.

Just so you are aware, it is my understanding that at some point, `material.envMap` will be removed and replaced by`lightProbe`, which is essentially the same thing, except a light probe is added to the scene directly, just as any other light. Materials, then, are either `reflective`, `refractive`, or maybe both.

**Comment by sunag** [comment]
> @sunag The problem is that reflectivity is a property of the material, and intensity is a property of the environment map.

`intensity` can be done with others `Nodes` by multiplying, this is not necessary in `NodeMaterial` root.

> Just so you are aware, it is my understanding that at some point, material.envMap will be removed and replaced bylightProbe, which is essentially the same thing, except a light probe is added to the scene directly, just as any other light. Materials, then, are either reflective, refractive, or maybe both.

you do not have to remove `envMap` to use `lightProbe`, you can use a `mix`, `multiply` and others math functions with 2 or more `CubeMap`  for example.

**Comment by WestLangley** [comment]
@sunag OK. So far, so good! : - )

**Comment by sunag** [comment]
I renamed `environmentAlpha` to `environmentIntensity` as an alternative.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
