### PR TITLE
Manual: added importmap support

### PR DESCRIPTION
**Pull request by ycw**
Related issue: #23363 

- added importmap in two files ([here](https://github.com/ycw/three.js/blob/80f04d89d5c412ad4f43016ad4a9ed03752ba39d/manual/index.html#L534), [there](https://github.com/ycw/three.js/blob/80f04d89d5c412ad4f43016ad4a9ed03752ba39d/manual/examples/resources/editor.js#L393))
- transform assets' path from abs to rel; asset [includes script,link,iframe,img](https://github.com/ycw/three.js/blob/80f04d89d5c412ad4f43016ad4a9ed03752ba39d/manual/index.html#L509) in manual/**/.html and manual/**/.js
- iframe is [sandboxed](https://github.com/ycw/three.js/blob/80f04d89d5c412ad4f43016ad4a9ed03752ba39d/manual/examples/resources/editor.html#L252) ( forbid export-to, and open-external, those buttons are noop, for now )

- use es-module-shim shim-mode, no errors will be prompted.

Preview: 
- [on github](https://ycw.github.io/three.js/manual/#en/load-obj)
- [on githack](https://raw.githack.com/ycw/three.js/manual-fix/manual/#en/load-obj)

### CODE REVIEW

**Comment by mrdoob** [comment]
Ops! Could you resolve the conflicts?

**Comment by ycw** [comment]
@mrdoob I'm not sure how to 455 conflicts..

**Comment by greggman** [comment]
A few comments:

* There's no reason to sandbox these iframes. The only reason to sandbox iframes is because the page is a page you log into and/or contains user content. These pages are static HTML. The site is 100% in control of what goes in them 

* It's hard to see what all the changes are here but they don't handle the OffscreenCanvas article

* I'm confused at which direction this is going. It seems like it's reverting adding the import maps to the files in manual/examples. If I try to run any of those examples on their own, they don't run.

* As for the relative paths, I'd suggest if you want relative paths do that in a single PR, separate from all any other changes.

**Comment by ycw** [comment]
@mrdoob @greggman please, don't merge this PR. will mk PRs. 1by1.

1. relpath ( current )
2. nav /doc
3. shim-mode
4. retouch export to

https://github.com/ycw/three.js/tree/manual-relpath (1)

/docs links do not work, im not sure how [this one](https://github.com/ycw/three.js/blob/5bed670952cd947c317f1f740740e7bc6374f77e/manual/index.html#L425) works. :(
[test](https://raw.githack.com/ycw/three.js/manual-relpath/manual/#en/materials) 
is it better to make all anchors to '_top' target, and use real url ?

**Comment by Mugen87** [comment]
Closing. Please split up your changes into smaller PRs.

**Pull request closed without merging**
