### PR TITLE
package.json: Bring back npm start and dev.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issues:

see #20579

### CODE REVIEW

**Comment by Mugen87** [comment]
Merging since the missing commands really block my workflow.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@greggman we replaced `http-server` with `servez` 🙏

**Comment by Mugen87** [comment]
@greggman Not a big deal but `http-server` used to support URLs like:

`
http://localhost:8080/examples/webgl_lines_fat
`

`servez` will generate a 404 in this case. It is required to use:

`
http://localhost:8080/examples/webgl_lines_fat.html
`
Is it possible to restore the old behavior?

**Comment by mrdoob** [comment]
I just noticed that these URLs work on gh-pages too 😮
https://threejs.org/examples/webgl_animation_cloth

**Comment by greggman** [comment]
I can look into it.

Is that a common behavior for web servers? I had heard of serving foo/bar/index.html as foo/bar or foo/bar/ but hadn't heard of serving foo.html as foo

**Comment by greggman** [comment]
ok,  you can try servez@1.11.0 (cli version only. I'll have to update the app version another day)

**Comment by mrdoob** [comment]
@greggman Is this something that requires config? Or could servez take care of it by default?

Screen Shot 2021-03-11 at 9 39 41 AM

**Comment by greggman** [comment]
Is there a repo I can use? I'm not sure what this is about. Grabbing some random wasm example off the net and serving it locally with servez it seems to give the correct MIME type

chrome_FeScBzj4pj

**Comment by mrdoob** [comment]
You'll be able to see this with the webgpu examples (Chrome Canary):

http://localhost:8000/examples/?q=webgpu#webgpu_materials

**Comment by greggman** [comment]
No error for me. Lemme try mac

chrome_zngLemWbfo

**Comment by greggman** [comment]
not setting it on mac either

Screen Shot 2021-03-11 at 21 03 08

`servez --version` reports 1.11.0

**Comment by mrdoob** [comment]
Oh, you know what? I'm stupid. I'm actually using `http-server`.

Please, accept my apologies 🙇‍♂️

**Pull request merged**
