### PR TITLE
Added if statements

### PR DESCRIPTION
**Pull request by ghost**
JSHint: "The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype."

### CODE REVIEW

**Comment by mrdoob** [comment]
What would be an example of unwanted properties?

**Comment by GregFrench** [comment]
The for in loop may traverse inherited properties through the prototype chain so the hasOwnProperty checks to see if the properties come directly from the object and returns a boolean if so. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

**Comment by benaadams** [comment]
```attributes``` doesn't have a prototype with an enumerable properties its a simple javascript associative array rather than a type that can be inherited. Do you have a use case?

**Comment by GregFrench** [comment]
I was thinking if someone were to extend Object.prototype the 'for in' would loop through those properties as well. Just a precaution.

**Comment by mrdoob** [comment]
> I was thinking if someone were to extend Object.prototype the 'for in' would loop through those properties as well. Just a precaution.

If they do weird things like that, they're kind of asking for trouble 😉

**Comment by GregFrench** [comment]
Lol, ok.

**Pull request closed without merging**
