### PR TITLE
fix(extend): fix extend about EventDispatcher

### PR DESCRIPTION
**Pull request by jasonChen1982**
adjust sub-class extend EventDispatcher, not copy EventDispatcher’s
prototype

#12807

### CODE REVIEW

**Comment by mrdoob** [comment]
I guess I don't see any problem with this. @Mugen87 looking for a second opinion 😅

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Looks good 😊 

You can take the inheritance of [Mesh](https://github.com/mrdoob/three.js/blob/dev/src/objects/Mesh.js#L35) as a reference.

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
If I'm right, this PR has broken `dev` branch...??
Seems like some examples don't work correctly with this change...

**Comment by Mugen87** [comment]
You're right, for some reasons examples like this [webgl_animation_cloth](file:///Users/Michael/Documents/workspace/three.js/examples/webgl_animation_cloth.html) don't work anymore. Not sure what's going wrong...

**Comment by takahirox** [comment]
Probably I've figured out.

Here sets `defineProperty` to `Texture.prototype`

https://github.com/jasonChen1982/three.js/blob/4ef93bdb3b96fc56a3ff29604748157d968f15ba/src/textures/Texture.js#L67-L75

but here overrides `Texture.prototype`.

https://github.com/jasonChen1982/three.js/blob/4ef93bdb3b96fc56a3ff29604748157d968f15ba/src/textures/Texture.js#L77

We should move `defineProperty` to the bottom in `Texture.js`?

**Comment by Mugen87** [comment]
> We should move defineProperty to the bottom in Texture.js?

Sounds good. That should solve the problem.

**Comment by takahirox** [comment]
OK, I'll open a PR.

**Pull request merged**
