### PR TITLE
PointLight/SpotLight: Change default decay to 2

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: https://github.com/mrdoob/three.js/issues/23614#issuecomment-1099523811

**Description**

If we aim to make the lighting physically correct we have to switch the default decay to `2`.
This PR is an attempt to do the change and see if there are any side effects.

/cc @bhouston @WestLangley @donmccurdy @Mugen87 @sunag

### CODE REVIEW

**Comment by donmccurdy** [comment]
Summarizing the legacy vs. physical attenuation —

- **legacy:** light attenuates from 100% to 0% linearly (`decay=1`) or by inverse square (`decay=2`) with the _ratio_ of object distance / `light.distance`, reaching 0% at `light.distance` meters. Because the range of the light is specified, and attenuation is distributed over that entire range, attenuation is not realistically based on physical distance. If either `decay=0` or `distance=0`, light does not attenuate. Distance is 0 by default, so light does not attenuate by default.
- **physical:** light attenuates from 100% to 0% linearly (`decay=1`) or by inverse square law (`decay=2`) with the _object distance_, never reaching exactly 0% unless `light.distance` is nonzero. When `light.distance` is specified, it smoothly but quickly diminishes intensity to zero at that distance<sup>1</sup>, without affecting attenuation over the rest of the light's range. If `decay=0`, light does not attenuate. 

In the legacy mode, attenuation is disabled by default and so the change to from `decay=1` to `decay=2` does not affect things much. Even with a distance, the light still has the same range, but at 50% of that range the light will now be at 25% strength rather than 50% strength.

In physical mode, attenuation is enabled by default, and the change in decay will more directly affect the perceived range of the light. This is not a dramatic difference but it is visible. 

Given that most users are probably still using the legacy mode, this seems like as good a time as any to make the change. I've created a spreadsheet, below, to illustrate the changes. I approximated the quadratic dropoff at `light.distance` in physical mode as a hard cutoff for simplicity.

light attenuation

_Source: [Punctual light attenuation in three.js](https://docs.google.com/spreadsheets/d/1O1DyZwajQQzqZOEP5qWKnoxxuIFFKDaE4QKCqRVReEg/edit?usp=sharing)_


<sup>1</sup> This is not physically correct, but is a useful tool to limit the otherwise infinite range of the light to something manageable for rendering performance in a scene with many lights. Unlike `light.distance` in the legacy mode, it has very minimal effect on the physical-correctness of attenuation _within_ the range of the light.

**Comment by donmccurdy** [comment]
One other idea. This is obviously a gross hack, but — if our ultimate goal is to _delete_ the legacy mode entirely, the path of least migration resistance would be to reduce the default `decay` to 0, instead of increasing it to 2. 😐

**Comment by donmccurdy** [comment]
Let me retract my last comment. I'd prefer to see this PR merged and `decay=2` as the default. 👍

**Comment by bhouston** [comment]
If one was making three.js now I would definitely have decay always default to 2 and enable physical lighting mode.  Over at Threekit, this is what we do.  It is only because of legacy that this isn't the default in Three.js in my opinion.

**Comment by WestLangley** [comment]
In physical lighting mode, the decay should be _hardwired_ to 2, otherwise it is not physically-correct.

How to handle artist-friendly mode (the current default), is up for debate.

**Comment by bhouston** [comment]
The original "physical lighting mode" didn't actually force people to be physical correct, rather it just changed the defaults and equations to be physically correct unless you changed things no?  I think we just want the default to be physically correct while still allowing the user to move away to more stylized choices if they really want to.  Thus I advocate changing all default behaviour to be physically correct and removing that mode.

**Comment by donmccurdy** [comment]
I like the approach @bhouston describes.

Setting `decay=2` as the default is a good change that can be made now, with or without further changes.

If/when we want to simplify further, we'll set `physicallyCorrectLights=true` as the default, and later remove the property entirely.

After that, if users want lights that decay in a non-realistic way, they can do so by increasing or decreasing `.decay`, with the understanding that `.decay=2` (default) is the physically-correct value. I hope that's a reasonable accommodation that allows some flexibility to deal with artistic goals, performance constraints, etc.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Although this PR will affect user code, the migration task is simple. Users can restore the lighting by setting `decay` back to `1`.

I vote to merge the PR for `r147`. I'll update docs, migration guide and check the examples. If a some of them are too dark after this change, we can update the light's intensity, color or decay.

**Comment by Mugen87** [comment]
After chatting with @mrdoob this will land in `r147` 🎉 .

**Comment by olyphiri** [comment]
`apt code 

> deleted
hello world

actually delete

> console
`

**Comment by olyphiri** [comment]
> console code1

> apt any change to default

> delete code
`console point a
arrY a ``

**Comment by olyphiri** [comment]
> console code1

> apt any change to default

> delete code
`console point a
arrY a ``

**Comment by olyphiri** [comment]
> `apt code
> 
> > deleted
> > hello world
> 
> actually delete
> 
> > console
> > `

**Comment by olyphiri** [comment]
> apt code 4

> apt to console code 4`array 

> image disclosed

> code apt github@olyphiri

> console to the point 

> entry data`

**Pull request merged**
