### PR TITLE
Revert to *.prototype.is* = true

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #21284 #21285

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
I think I might've confused you and this whole situation. Could someone else please provide some clarity for the related issues.

**Comment by mrdoob** [comment]
No. It's not equivalent.

**Comment by DefinitelyMaybe** [comment]
I'm at a loss on this one. The following works fine in the browser and if I'd understood that earlier I wouldn't have worried about changing as much around as I did with my movements towards classes. We could have gone slower. I apologize @mrdoob.
```javascript
class foo {
  constructor(param) {
    this.thing = param
  }
}

foo.prototype.value = 1

Object.assign(foo.prototype, {a:'...'})

class bar extends foo { }

Object.assign(bar.prototype, {a:"... ..."})

const y = new foo("aaa")
console.log(y.value);
console.log(y.a);
console.log(y.thing);

const x = new bar("dsa")
console.log(x.value);
console.log(x.a);
console.log(x.thing);
```
logs:
```
1
"..."
"aaa"
1
"... ..."
"dsa"
```

[an earlier comment](https://github.com/mrdoob/three.js/issues/19986#issuecomment-669240042)

**Comment by DefinitelyMaybe** [comment]
#21294

**Comment by linbingquan** [comment]
There has `Object.defineProperty( this, 'is`, shell we change it?

image

**Comment by Mugen87** [comment]
@linbingquan I suggest we focus on `src` now and care about `examples` when the ES6 migration in the core has been settled.

**Comment by mrdoob** [comment]
@linbingquan Actually, I think that'd be great. Please, go ahead and clean that up 🙏

**Pull request merged**
