### PR TITLE
GLTFLoader: Base color and emissive textures use sRGB.

### PR DESCRIPTION
**Pull request by donmccurdy**

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks! Also, thanks again @stevesan!

**Comment by gonnavis** [comment]
Hello @donmccurdy , excuse me, is there any relevant information explaining why sRGBEncoding is used by default here?

**Comment by donmccurdy** [comment]
This is specified by glTF. But more generally, textures providing color information (base color, emissive) should be sRGB while data textures (normal, AO, roughness, ...) should be linear.

**Comment by gonnavis** [comment]
@donmccurdy Thanks!

**Pull request merged**
