### PR TITLE
WebGPURenderer: Added double-side transmission 2/2

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/29705

**Description**

Renders all back-side first in case of materials with transmission and double-side. This would only be noticeable with many objects with this setup in the scene.

WebGPURenderer's approach, unlike WebGLRenderer, does not render opaque objects twice, and keeps the sequence of transparent materials with transmission in the same sort, which is also an improvement.

1. Render opaques
2. Render back-side transmission materials
3. Render all transparents materials, for transmission only the front-side

### CODE REVIEW

**Comment by hybridherbst** [comment]
@sunag a bit of a tangent here, but while you're in this part of the codebase: would it be possible to render transmissive objects that have transmission=1 and ior=1 with a regular transparent pass? This would improve performance on weaker devices (e.g. Quest 2/3) for the most typical case of "clear glass", which currently often needs to be emulated with opacity, since transmission always introduces a fullscreen pass at a big performance penalty.

**Comment by sunag** [comment]
I think we can have barriers with normalmaps and other settings that influence the color in transmission and other validations that will have to be tested each frame, and animation, I would recommend creating a routine to replace the material if possible?

The new architecture does not do a full-screen pass, but a copy of the current buffer to a texture, which is much faster regardless of the backend used.

**Comment by hybridherbst** [comment]
Thanks!

> a copy of the current buffer to a texture, which is much faster regardless of the backend used
I'm not sure this holds in practice on tiled GPUs – At least in my understanding, "no copy" will always be faster than "screen-space copy".

> replace the material if possible
With what? I'm not aware of a good way to emulate how transmission is supposed to look without using transmission...

**Comment by sunag** [comment]
Transmission without the framebuffer texture is not transmission anymore, I think your idea was to emulate it with opacity?

**Pull request merged**
