### PR TITLE
SSRPass: Change surfDist and infiniteThick behavior.

### PR DESCRIPTION
**Pull request by gonnavis**
Inspired by Blender Eevee SSR and [SSRrPass's infiniteThick](https://github.com/mrdoob/three.js/pull/21420#issuecomment-808795109), changed SSRPass's infiniteThick behavior.

**[Demo](https://raw.githack.com/gonnavis/three.js/c5a1418828ad9c4e687b140d0ede664e9dde46ce/examples/webgl_postprocessing_ssr.html)**

before vs after vs blender
image

---EDIT---
[**Newest Demo of this pr**](https://raw.githack.com/gonnavis/three.js/SSRPassChangeInfiniteThickBehaviorPr/examples/webgl_postprocessing_ssr.html)
image

### CODE REVIEW

**Comment by mrdoob** [comment]
That's an strange effect 🤔

**Comment by gonnavis** [comment]
Yes, the parts far away from the reflection point are very strange, such as the mouth and the tip of the tail.

Many pros ( green ) and many cons ( red ). ( yellow: not sure pro or con )
image

I'm trying to implement `distanceAttenuation` for this effect too, may can improve the visual effect.

**Comment by gkjohnson** [comment]
In my opinion "infinitely thick" shouldn't be the default in the demo because I agree it causes some odd artifacts. Instead I think the demo should just allow for increasing the apparent "thickness" of the ray marched buffer (called "surfDist" in the example page) to a higher value. And in fact setting it to a very high value should have the same effect as setting the thickness to "infinite".

Two more comments related to thickness:
- It's not clear to me what "thickTolerance" does in the demo. I expected it to do what "surfDist" seems to be doing.
- When adjusting "surfDist" it looks as though the surface is being thickened both behind _and_ in front of the depth buffer being marched against. Instead I think it should just increase the thickness behind because we know where the front surface is. You just need thickness in order to "guess" where the back surface is. This change should also prevent the model from jumping positions when toggling the ground reflector on and off when surfdist is set to a larger value.

**Comment by gonnavis** [comment]
Thanks @gkjohnson ! 

I also have some similar optimization ideas, but they are rather vague. Your suggestions make me more clear about what to do.
 
Should let `surfDist` just affect the _behind_ and merge the concept with `thickTolerance` ( which seems has problem and I've not use it for a long time) .

I'll do this first these days.

**Comment by gonnavis** [comment]
[Demo](https://raw.githack.com/gonnavis/three.js/43270be149cd0f64af0a7ee8c87f7e2ac6ebb80f/examples/webgl_postprocessing_ssr.html)

Let `surfDist` only affect _behind_, and thus it is no longer _surface_, so renamed `surfDist` to `thickness`. 
Now it's a very useful paramter to tweak to meet the needs of user's specific scene, and may can set each object seperately by the same way as https://github.com/mrdoob/three.js/pull/21487. 

Removed `thickTolerance`, because now only `thinkness` is sufficient.

Suprisingly also particaly solved these two issues!
1. https://github.com/mrdoob/three.js/pull/20156#issuecomment-766746856
2. https://github.com/mrdoob/three.js/blob/51afad97c9967e9fc4a9bbc3411067320eb835cc/examples/webgl_postprocessing_ssr.html#L308

image
image

**Comment by gonnavis** [comment]
But still some artifacts I'm trying to solve.
image

And is the breaking renaming change from `surfDist` to `thickness` acceptable?

**Comment by gonnavis** [comment]
All use `NearestFilter` instead of `LinearFilter` solved the periodic artifacts, now looking better.

image

**Comment by gonnavis** [comment]
Found that `surfDist` ( now named as `minThickness` ) can be auto-calculated, so don't need `surfDist` anymore.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I'm not 100% sure but it seems like the changes broke the e2e tests...

https://github.com/mrdoob/three.js/runs/2358873732?check_suite_focus=true

Screenshot 2021-04-16 at 10 52 06

**Comment by gonnavis** [comment]
When I execute `npm run make-screenshot webgl_postprocessing_ssr` locally, there is a high probability that will get stuck without returning, but sometimes will succeed.

After submitting it yesterday, e2e test has also been in the checking state for a long time, and was discovered that failed today.🤔

I'm trying change the code to let local always success.

**Comment by gonnavis** [comment]
Also found that there's a very high cpu usage when run `npm run make-screenshot webgl_postprocessing_ssr`.
But works well in browsers ( Win10 chrome, Android Chrome, IOS safari ).

**Comment by mrdoob** [comment]
This may be a SwiftShader issue?

@c0d1f1ed we use SwiftShader in our e2e setup and the changes in this PR made this example hang the process:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_postprocessing_ssr.html

**Comment by gonnavis** [comment]
It's really hard to debug because this is a probability issue.
In the end I found after revert [this commit](https://github.com/mrdoob/three.js/pull/21539/commits/1483183779b308bf668e71d6e744def32decda87) will ok.

And found the main reason is 
`if(viewReflectRayZ-sD>vZ) continue;` 
changed to 
`if(viewReflectRayZ>vZ) continue;`.

I tried
`if(viewReflectRayZ-.001>vZ) continue;`
but still hang, and here not need variable anymore.

So trid
```
if(viewReflectRayZ<=vZ){
    bool hit;
    #ifdef INFINITE_THICK...
    #else...
    #endif...

    if(hit){...
    }
}
```
then OK.

**Comment by gonnavis** [comment]
Seems continue commit to this merged pr has no effects.
Made a [new pr](https://github.com/mrdoob/three.js/pull/21668) and all checks ok at there.

**Comment by c0d1f1ed** [comment]
@mrdoob Thanks for alerting me about this. The Legacy SwiftShader OpenGL ES implementation unfortunately is known to have some bugs related to control flow in shaders. We're working on replacing it with the new SwiftShader Vulkan implementation, with the ANGLE project providing OpenGL ES compatibility for WebGL. This combo has no known shader bugs, so I'm hopeful it will also fix this issue.

Is there a URL for the demo of the old PR that we can try?

**Comment by mrdoob** [comment]
I think this URL should work:
http://raw.githack.com/mrdoob/three.js/4bd5270bf0221dd4fd5f9372ae216f0ca7d6009a/examples/webgl_postprocessing_ssr.html

**Comment by c0d1f1ed** [comment]
> I think this URL should work:
> https://raw.githack.com/mrdoob/three.js/4bd5270bf0221dd4fd5f9372ae216f0ca7d6009a/examples/webgl_postprocessing_ssr.html

I can confirm that with Legacy SwiftShader, the page freezes when enabling the InfiniteThick feature. There also didn't appear to be any SSR effect. With the future "SwANGLE" solution, the page doesn't freeze and there's SSR going on.

There is some other periodic artifact which appears to be either some geometry going off into infinity, or some of the reflection bleeding where it shouldn't. We'll try to look into that.

**Pull request merged**
