### PR TITLE
TSL: `shadows`

### PR DESCRIPTION
**Pull request by sunag**
**Description**

The `shadows` node allows shadows to be used as masks for effects.

```js
import { output, shadows } from 'three/tsl';

material.outputNode = output.add( shadows );
```

image

### CODE REVIEW

**Comment by Makio64** [comment]
@sunag Asking for my personal understanding :
1 : this allow us to get the shadow casted on the mesh and use it in the material for example for adding a dithering or modifying the color of the shadow on the material ( in the fragment shader level ) ?
2 : this allow us to modifying the shadow texture before its send to the material ( for example to add blur on it )

**Comment by sunag** [comment]
We have some API features aimed at different purposes.

- `material.shadowNode` -> Allows you to change the `opacity` and `color` of the `shadow`, or procedural effect in TSL. 
https://threejs.org/examples/?q=shadow%20opacity#webgpu_shadowmap_opacity

- `material.outputNode = output.add( shadows )` -> Allows you to obtain the shadow at the output level, useful for creating special effects based on the shadow, such as using the shadow as a mask to project another node in the shadow area in the target material. Note that `add()` can be replaced by another mathematical operation here.

- `light.shadow.filterNode` -> Here customizing the light shadow filter, such as using `PCFSoftShadowMap` or creating your own, is the appropriate place to soften the shadow.

**Comment by Makio64** [comment]
Thanks for clarifying!  Just to be sure : 

Shadows render pass : 
`material.shadowNode` : how the material project his shadow into the shadowmap during the rendering of lights
`light.shadow.filterNode` : filter apply during the rendering of the lights ( blur etc.. )

Scene render pass : 
`shadows` : the value of the compile shadows at the pixel level ( in the fragment shaders ).

So when you do : 
`material.outputNode = output.add( shadows )` it add the shadow value over the output which already have shadows ?
If I want to rewrite how the shadow is rendered on my mesh for example with a very low opacity for a 'GhostMaterial' how to do so ( I originaly thought it was the purpose of the shadowNode. ) ?

Maybe shadowNode is little bit confusing and a `castShadowNode` and a `receivedShadowNode`would be easier or maybe its just me ?

**Comment by sunag** [comment]
> Maybe shadowNode is little bit confusing and a castShadowNode and a receivedShadowNodewould be easier or maybe its just me ?

`castShadowNode` seems like a good name 👍

**Comment by sunag** [comment]
@Makio64 I think this will be possible now, the suggestion was great and I updated the API. 
https://github.com/mrdoob/three.js/pull/29840

**Pull request merged**
