### PR TITLE
sweeneyian mountain range

### PR DESCRIPTION
**Pull request by sweeneyian**
My first Demo attempt. 3D view with Orbit Controls of Skye, a Scottish Island, using bathymetric ascii data from https://www.bodc.ac.uk/data/hosted_data_systems/gebco_gridded_bathymetry_data/

### CODE REVIEW

**Comment by mrdoob** [comment]
Preview link:
http://raw.githack.com/sweeneyian/three.js/sweeneyian-threejs/examples/webgl_geometry_terrain_mountains.html

**Comment by sweeneyian** [comment]
Many thanks for the link 👌

**Comment by WestLangley** [comment]
You can share showcase demo links at https://discourse.threejs.org.

**Comment by mrdoob** [comment]
Yeah, I'm not sure this should be an actual example. At this point we have too many examples and they're hard to maintain. We're trying to reduce the amount and merge them whenever possible.

Definitely better to share in the forum instead. Thanks though!

**Comment by sweeneyian** [comment]
No worries. I've seen the demo pool grow. Thanks for the feedback.

I started working on the concept last week. Still needs a lot of work.
Still figuring things out. Will publish refinements to dev/forum.

But I'm using it as part of a potential job interview where they asked for
a demo. So really appreciate the link. Something with my name on it.

Love the work. Keep it up!

Regards

**Pull request closed without merging**
