### PR TITLE
Example: Add 3D LUT Color Grading Postprocessing Pass

### LINKED ISSUE #19457: Feature Request: Add support for 3DLUT color grading
I see that there's been some work done in the past in #15360 and @greggman has put together a nice article on the topic [here](https://threejsfundamentals.org/threejs/lessons/threejs-post-processing-3dlut.html). It's not entirely clear to me why the previous PR was closed but I wanted to bring this up as a nice addition to three.js. The utility has been better explained in the two links above but 3DLUTs are great for controlling the look and feel of a scene.

3DLUTs are supported in a variety of 3d engines and video editing software include [Unity](https://docs.unity3d.com/Packages/com.unity.postprocessing@2.1/manual/Color-Grading.html), [Unreal Engine](https://docs.unrealengine.com/en-US/Engine/Rendering/PostProcessEffects/UsingLUTs/index.html), and [Babylonjs](https://doc.babylonjs.com/api/classes/babylon.colorgradingtexture). There are also a couple existing file formats for them including [.cube](https://wwwimages2.adobe.com/content/dam/acom/en/products/speedgrade/cc/pdfs/cube-lut-specification-1.0.pdf) and [.3dl](http://community.foundry.com/discuss/topic/103636/format-spec-for-3dl?mode=Post&postID=895258) (though 3dl looks relatively undocumented).

These formats are available online and can also be [created in tools like Photoshop](https://helpx.adobe.com/photoshop/using/export-color-lookup-tables.html) and would enable more artistic control over the look of the final scene.

I figure that just like gamma correction there could be a postprocessing effect and WebGLRenderer support that adds the LUT application to the end of the built in shaders:

```js
const lut = new LUTLoader().load( '../path/to/lut.3dl' );
renderer.colorLUT3D = lut;
```

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #19457.

This PR adds file format loads for CUBE and 3DL 3D Color LUT files (both of which can be [exported from photoshop](https://helpx.adobe.com/photoshop/using/export-color-lookup-tables.html) and other applications) as well as LUTPass for postprocessing and an associated example. The loaders generate both 2D and 3D data textures which LUTPass can use which means it supports both WebGL1 and 2.

The LUTs used in the demo are provided free from [RocketStock.com](https://www.rocketstock.com/free-after-effects-templates/35-free-luts-for-color-grading-videos/) which I've added an attribution for at the top of the example.

Here's the example page from this PR:

https://raw.githack.com/gkjohnson/three.js/lut-pass/examples/webgl_postprocessing_3dlut.html

And here's the demo I originally made in another repo that uses a photograph and quite a few other LUTs for demonstration:

https://gkjohnson.github.io/threejs-sandbox/3d-lut/

### CODE REVIEW

**Comment by gkjohnson** [comment]
When I generate a screenshot it all looks black 🤔 not sure why that is. Have I structured something wrong in the example for taking screenshots?

webgl_postprocessing_3dlut

**Comment by mrdoob** [comment]
Beautiful! We should rename these to `InstaFilterLoader` 😁

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> When I generate a screenshot it all looks black 🤔 not sure why that is. Have I structured something wrong in the example for taking screenshots?

No idea. I've just ran `npm run make-screenshot webgl_postprocessing_3dlut` localy and it generated a good screenshot 🤔

**Pull request merged**
