### PR TITLE
Added enabled property to TransformControls.

### PR DESCRIPTION
**Pull request by arodic**
Added feature requested in #6813

### CODE REVIEW

**Comment by mrdoob** [comment]
What do you about not changing the visibility?
I wonder if there is any case where you would want to disable the controls but keep them visible?

**Comment by arodic** [comment]
I think there should definitely be a clear visual indication that the control is disabled. Hiding it was the quickest to implement but dimming the materials would be better. Having them disabled without visual indication would just look like it is broken.

**Comment by mrdoob** [comment]
Thanks!

**Comment by arodic** [comment]
@mrdoob I changed it to dimming instead hiding #14771

**Pull request merged**
