### PR TITLE
A minimal conversion example

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
Related issue: #19986

details:

* change constructor function to class. add constructor function within class.
* extend as appropriate
  * call `super()` within constructor if extended
* simplify `Object.assign( )` call

Edit:
For future reference, it was a 10/10 pass on all checks.

### CODE REVIEW

**Comment by Mugen87** [comment]
Sorry, I'm not a fan of this approach. This code looks highly inconsistent and confusing.

If I would have no foreknowledge about `three.js` and then look at this code,  I would wonder: Why would anybody develop JavaScript like this?

So please convert the whole file or nothing. But not something in between.

**Comment by Mugen87** [comment]
Besides, `AnimationMixer` is already converted in #20014.

**Comment by DefinitelyMaybe** [comment]
> This code looks highly inconsistent and confusing.

welcome to how I feel about the old state of the code and why Ive been wanting us to head away from it. 

where does someone draw the line? #21293?

**Comment by mrdoob** [comment]
I am confused. You're proposing we use [the approach that breaks tree-shaking](https://github.com/mrdoob/three.js/pull/21285#issuecomment-780091337)?

**Comment by mrdoob** [comment]
Are you testing these PRs locally and double checking they tree-shake?

**Comment by DefinitelyMaybe** [comment]
You just made and merged  #21293 which [looks like it breaks tree-shaking for webpack](https://github.com/mrdoob/three.js/pull/21285#issuecomment-780519616).

I am confused too. Let's try and make some sense.

This PR is an example of how javascript doesn't care about which concept you use regarding inheritance/structure of your object. `.prototype`s/`class`&`extends`/`Object.assign()`. whatever, doesn't care. That also means it's the possible tools of obscuring details about an instance.

#21293 is exactly that. A mix of `.prototype.` and `class`, obscuring the `is*` property.

Moving on.
Tree-shaking is an important feature because it allows users project size to be reduced significantly.

Atm [you've said](https://github.com/mrdoob/three.js/pull/21285#issuecomment-780529523) if anyone using webpack wants to tree-shake, webpack should sort out that bug/feature. [Who knows](https://webpack.js.org/guides/tree-shaking/) why webpack didn't tree-shake it. Sing out if you do.

I will make a guess on this front though, `sideEffects`. Webpack might've not been able to conclude the assignment of `prototype.is*` as side-effects free and needs a `= /*#__PURE__*/` hint to signify that everything's all good here.

**Comment by mrdoob** [comment]
> I will make a guess on this front though, `sideEffects`. Webpack might've not been able to conclude the assignment of `prototype.is*` as side-effects free and needs a `= /*#__PURE__*/` hint to signify that everything's all good here.

Could you test your hypothesis?

**Comment by DefinitelyMaybe** [comment]
sure. Anyone know an equivalent command to mrdoob's:
```sh
echo "import { Vector3 } from './src/math/Vector3.js'" | npx rollup -f es
```
but for webpack?

**Pull request closed without merging**
