### PR TITLE
Remove vertices render info

### PR DESCRIPTION
**Pull request by pailhead**
`render.info.vertices` gives the number as if all geometry was triangle soup. When rendering indexed geometry this number should be different? The easiest thing to do is to remove this number (for now).

### CODE REVIEW

**Comment by Mugen87** [comment]
See: https://discourse.threejs.org/t/renderer-info-vertices/1837

**Comment by WestLangley** [comment]
Remove it? What if the user is rendering a line?

**Comment by Mugen87** [comment]
Good point. This case needs to be considered. 

@pailhead `WebGLIndexedBufferRenderer` would also need this change.

**Comment by Mugen87** [comment]
Just to give this issue more context: The following line causes the confusion since `count` in this method is not the amount of vertices but the amount of indices.

https://github.com/mrdoob/three.js/blob/335359176b278c616dd1bb864b4d39e2c316be77/src/renderers/webgl/WebGLIndexedBufferRenderer.js#L29

**Comment by pailhead** [comment]
But it is still going to be wrong? Unless someone is rendering only lines/ points?

**Comment by Mugen87** [comment]
I like this suggestion.

**Comment by WestLangley** [comment]
>So drop vertex count for meshes

Yes.

>keep segments/points for lines?

No. Use `.segments` for lines and `.points` for points.

**Comment by pailhead** [comment]
Seems like a bigger refactor, maybe then just keep the vertices but count them properly?

**Comment by Mugen87** [comment]
It seems easier than producing a correct value for `vertices`. This would be render function of `WebGLBufferRenderer`:
```js
function render( start, count ) {

	gl.drawArrays( mode, start, count );

	infoRender.calls ++;

	switch ( mode ) {

		case gl.TRIANGLES:
			infoRender.faces += count / 3;
			break;

		case gl.LINES:
			infoRender.segments += ( count / 2 );
			break;

		case gl.LINE_STRIP:
			infoRender.segments += ( count - 1 );
			break;

		case gl.LINE_LOOP:
			infoRender.segments += count;
			break;

		case gl.POINTS:
			infoRender.points += count;
			break;
		default:

	}

}
```

**Comment by WestLangley** [comment]
Right. It is not complicated.

`renderer.info` should tally the number of _primitives_ rendered.

**Comment by pailhead** [comment]
What about the index renderer? My understanding is that each renderer can write to info during one render call. Conditions caused by having a soup, indexed mesh, lines and points in the same scene i guess.

The arguments passed into these functions don't seem to allow proper counting of vertices. Hence the question about a bigger refactor.

**proper** derived from this conversation

```
usefulthink [9:19 AM]
in the pipeline on the gpu, is vertex-shading done before primitive assembly?

pailhead [9:20 AM]
i have no idea tbh, i think i've spent a lot of time thinking yes
but may be totally wrong

usefulthink [9:20 AM]
looks like it: https://www.khronos.org/opengl/wiki/Rendering_Pipeline_Overview

pailhead [9:20 AM]
youre saying when actually rendering, ("rendering") the vertex shader may run on an assembled primitive meaning exclusively triangle soup?

usefulthink [9:21 AM]
apparently that is not the case and you were right thinking that :slightly_smiling_face:

pailhead [9:22 AM]
`he full primitive assembly step (including the processing below) will always happen after Vertex Post-Processing.`
ha!
```

**Comment by pailhead** [comment]
Reading this is melting my mind even further :(

https://www.khronos.org/opengl/wiki/Primitive

How should someone familiar with say opengl, but unfamiliar with how three.js works under the hood interpret these?


GL_TRIANGLES:
(count: 6? | triangles: 6 / 3 = 2)
```
Indices:     0 1 2 3 4 5 ...
Triangles:  {0 1 2}
                  {3 4 5}
```

GL_TRIANGLE_STRIP
(count: 6? | triangles: 6 / X = 3)
```
Indices:     0 1 2 3 4 5 ...
Triangles:  {0 1 2}
              {1 2 3}  drawing order is (2 1 3) to maintain proper winding
                {2 3 4}
                  {3 4 5}  drawing order is (4 3 5) to maintain proper winding
```

GL_TRIANGLE_FAN
(count: 6? | triangles: 6 ? WTF = 4)
```
Indices:     0 1 2 3 4 5 ...
Triangles:  {0 1 2}
            {0} {2 3}
            {0}   {3 4}
            {0}     {4 5}
```

**Comment by emeyex** [comment]
If the confusion is regarding strips and fans, it does look like cases need to be added for counting those primitives properly. Looking at the `three.js` codebase right now, AFAICT, those aren't getting counted at all in the `faces` property (only triangle lists are, i.e. `gl.TRIANGLES`). Seems like that may be a big deal for certain people profiling their scenes, as the count could be underreported.

In any case, fans (`gl.TRIANGLE_FAN`) and strips (`gl.TRIANGLE_STRIP`) should just use `faces = count - 2`. In light of that, it may still be useful for some people to know the total `element` count, as it can't necessarily just be unpacked (i.e., `faces * 3`). But I would consider renaming the field to `elements` instead of `vertices`. Anyway just my `$0.02`!

**Comment by pailhead** [comment]
>If the confusion is regarding strips and fans

I would argue no - the confusion is what does `info.vertices` represent? If you add the proper counts for fan and strip, you still are missing indexed geom?

**Comment by pailhead** [comment]
```
A vertex shader is (usually) invariant with its input. That is, within a single Drawing Command, two vertex shader invocations that get the exact same input attributes will return binary identical results. Because of this, if OpenGL can detect that a vertex shader invocation is being given the same inputs as a previous invocation, it is allowed to reuse the results of the previous invocation, instead of wasting valuable time executing something that it already knows the answer to.

OpenGL implementations generally do not do this by actually comparing the input values (that would take far too long). Instead, this optimization typically only happens when using indexed rendering functions. If a particular index is specified more than once (within the same Instanced Rendering), then this vertex is guaranteed to result in the exact same input data.

Therefore, implementations employ a cache on the results of vertex shaders. **If an index/instance pair comes up again, and the result is still in the cache**, then the vertex shader is not executed again. **Thus, there can be fewer vertex shader invocations than there are vertices specified**.
```

**Comment by emeyex** [comment]
Adding proper face counts for fans and strips is just the **Right Thing To Do™** IMO, and it definitely can and should be counted for both indexed and non-indexed geometry (looks like `WebGLBufferRenderer` and `WebGLIndexedBufferRenderer` would be the places). Triangle counts could also be tracked separately for indexed and non-indexed primitives of course, but that's probably overkill for most people's uses. Element count OTOH, while it's value is debatable, seems like an easy thing to track, so why not? My thought was that renaming to `elements` might ease the confusion, or else increase it to the point that people ignore that field :)

In any case, properly tracking triangles seems like a separate concern from determining the actual number of vertices transformed by the vertex shader, which (as your quote above suggests) is arguably not even possible given unknown GPU post-transform cache sizes, and certainly wouldn't be performant for indexed geometry.

In any case,  I'm not meaning to derail the conversation, so my apologies. It just seemed worth pointing out that triangle fans and strips do not appear to be getting counted _at all_ in the current code base. Carry on!

**Comment by pailhead** [comment]
If anyone is interested, some interesting links posted here 

https://stackoverflow.com/questions/48798175/how-are-vertices-transformed-in-webgl-in-indexed-and-non-indexed-geometries/48798572#48798572

**Comment by Mugen87** [comment]
Closing in favor for #13404

**Pull request closed without merging**
