### PR TITLE
TS: Fixes passing PositionalAudio to AudioAnalyser

### PR DESCRIPTION
**Pull request by PaulHax**
Fixies getting a Typescript compile error on this:
`
new THREE.AudioAnalyser(new THREE.PositionalAudio(audioListener), 32);
`
Error:
```
error TS2345: Argument of type 'PositionalAudio' is not assignable to parameter of type 'Audio'.
  The types returned by 'getOutput()' are incompatible between these types.
    Property 'gain' is missing in type 'PannerNode' but required in type 'GainNode'.
```
Error was introduced with pull #18022

This is a weaksauce fix I'm afraid.  Might be better to factor out a GainNode free Interface for Audio and PositionalAudio to extend.

### CODE REVIEW

**Comment by mrdoob** [comment]
> This is a weaksauce fix I'm afraid. Might be better to factor out a GainNode free Interface for Audio and PositionalAudio to extend.

How would that look like?

**Comment by Mugen87** [comment]
Isn't it possible to change the type declaration of `Audio.getOutput()` to for now?
```js
getOutput(): AudioNode;
```
Alternatively, using generics similar to `Curve` could also help here I think:

https://github.com/mrdoob/three.js/blob/b6ac023e75568aee512de1c6bfaac7b1f75807a4/src/extras/core/Curve.d.ts#L9

**Comment by PaulKElliott** [comment]
Generics eh?  How about this:
`export class Audio<NodeType extends AudioNode = GainNode> extends Object3D {`

Thanks for the guidance.

**Review by Mugen87 — APPROVED** [review]
I'm not using TS myself so I don't know if there is a more elegant solution. But IMHO, generics seems to be the right approach here.

**Comment by PaulKElliott** [comment]
For Typescript userland's information:
```
let audioOrSubtype: THREE.Audio<AudioNode>; // Variable holds any THREE.Audio flavor
audioOrSubtype = new THREE.Audio(listener); // OK
audioOrSubtype = new THREE.PositionalAudio(listener); // Also OK
```

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
