### PR TITLE
Examples: Thumbnails index page

### PR DESCRIPTION
**Pull request by greggman**
not sure if you wanted this or not.

### CODE REVIEW

**Comment by gkjohnson** [comment]
http://raw.githack.com/greggman/three.js/fruit-on-the-bottom/examples/index.html

**Comment by trusktr** [comment]
Oooh, that's ******* cool.

**Review by trusktr — APPROVED** [review]

**Comment by Mugen87** [comment]
With regard to https://github.com/mrdoob/three.js/pull/19375#issuecomment-635414699, it seems design related PRs should not be created anymore.

**Comment by looeee** [comment]
This seems to be the best solution to me. It works well on mobile and desktop, and it keeps the list and the thumbnails so everyone should be happy.

**Pull request closed without merging**
