### PR TITLE
CSS3DRenderer: Support CSS3DSprite screen-space rotation

### LINKED ISSUE #21795: CSS3DSprite rotation
I want `CSS3DSprite` to self-rotate. The rotation is invalid.
such as:
```js
const object = new CSS3DSprite( div );

object.rotation.z = Math.PI * 0.5;
```
The above code does not respond.
Strange, don't know why....

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #21795.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
What do you think about `CSS3DSprite.rotation2d` instead?

**Comment by WestLangley** [comment]
>What do you think about CSS3DSprite.rotation2d instead?

I think that is better. For consistency, perhaps `CSS3DSprite.rotation2D`?

**Comment by mrdoob** [comment]
Sounds good 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Should we move `sprite.material.rotation` to `sprite.rotation2D` too? Or is that too messy?

**Comment by Mugen87** [comment]
I vote to keep `sprite.material.rotation` for now until https://github.com/mrdoob/three.js/issues/21795#issuecomment-836781483 becomes more clear.

**Pull request merged**
