### PR TITLE
Typed polyfill of "indexOf()" for `Uint8Array`

### PR DESCRIPTION
**Pull request by benguild**
Ref:  #14482, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Polyfill

### CODE REVIEW

**Comment by mrdoob** [comment]
@looeee Yeah, less code is better 😊

**Comment by benguild** [comment]
@mrdoob @looeee "Yeah, less code is better 😊" Agreed! 👍🏻

**Comment by mrdoob** [comment]
Thanks though!

**Comment by benguild** [comment]
No problem, was just a quick fix. 😎

**Pull request closed without merging**
