### PR TITLE
Fix indentation & use let/const instead of var

### PR DESCRIPTION
**Pull request by andreipfeiffer**
- fixed mixed spaces & tabs indentation
- replace var with let/const to better differentiate between identifiers that change (variables) and constants

### CODE REVIEW

**Comment by looeee** [comment]
There's an ongoing discussion as to whether to adopt ES6 features: #6419

Also, while native support for 'const' is [good](http://caniuse.com/#search=const) (>97%), `let` support is [not so good](http://caniuse.com/#search=let) (~80%). Although the numbers on the 'let' page don't seem to add up, maybe there is somewhere to get a second opinion?

**Comment by andreipfeiffer** [comment]
I've only used let & const because I saw that you already use Object.assign().

I've also read the entire discussion you pointed out, that started in 2015.
As far as I can see, all perf benchmarks seem to point out that let is indeed a bit slower than var.

If perf is the primary goal, than maybe you should stick with ES5 for now.

**Comment by looeee** [comment]
There's a polyfill for Object.assign [here](https://github.com/mrdoob/three.js/blob/dev/src/polyfills.js#L53).

**Comment by Mugen87** [comment]
@andreipfeiffer Please avoid the usage of `let` and `const`. One design goal of the library is to run on many devices as possible. I think it's not the time yet to use ES6 features without polyfills.

**Comment by andreipfeiffer** [comment]
Sure, no problem, thanks.

**Comment by MasterJames** [comment]
New benchmarks are proof of the correcting of the run time engine 'let' is newer and solves problems with var so it's an improvement (so use it) also all on one line was slower now that's better too.
jsperf is old and broken wish I could delete them it deletes existing tests when editing and just horrible.
Anyway you can test them on your system mine should it's changed in the last few years, so I'm glad I stuck to what I think it suppose to be right for the future.

https://jsperf.com/separating-assignment-from-declaration/8
Typeof I won't use still it's faster but they'll figure it out eventually right. I stick to what I believe the let vs var is proof of that, so I compare Constructor that makes way more sense to me.
https://jsperf.com/mj-typeof-vs-constructor
It's a meaningless difference, what matters is 'var' doesn't release & collect as well as 'let' does.
Crockford says something to that effect too.
https://jsperf.com/mj-let-vs-var/1

**And the RANT of a lifetime begins enjoy:**
As to const? I build everything off of my global object, if you make it const fine you can always over right the contents of an object also meaningless as types are in JS and should be.

The only thing I do new now while avoiding null as well is create an und for undefined and then you say so explicitly not writable like so. (I also use 3 letter names like rnd for 'renderer' cam for 'camera' etc. kind of like assembly ironically, I also mostly turf the vowels you can still read it. jmp vs jump )

```
if( global.hasOwnProperty( 'und' ) === false ) {
	global.und = undefined;
	Object.defineProperty( global, 'und', {
		value: undefined,
		writable: false,
		configurable: false
	} );
}
```
Crockford explained everything well a few years back, so maybe there's an update with ES6 etc.
It's everything I understood instinctively being self taught since the first PET computer entered the school in Canada. I was in grade 4. I taught myself assembly in grade 6 because that's all you could do with them Apple ][+ etc. I'm 48 now.
He starts a few years before my time (Act I) but not many and I was just a kid through those years with many distractions (art & music) in life etc. about part/act 3 or 4 he explains you wouldn't but you can get ride of declarations altogether with his fun bit on the Y Combinator (at end of act 3).

History https://www.youtube.com/watch?v=JxAXlJEmNMg
JavaScript https://www.youtube.com/watch?v=RO1Wnu-xKoY
https://www.youtube.com/watch?v=ya4UHuXNygM
Y combinator at the end https://youtu.be/ya4UHuXNygM?t=1h9m26s
it goes on and on for like a week and beyond.
Part 5 "the end of all things" https://www.youtube.com/watch?v=47Ceot8yqeI

by building everything in an object or even from one global you can do away with all of it var let const gone. Even temps in a function can be arguments you check for und,  and set a default (you don't need to pass them and can override not so in many other languages).
I've recently destroyed the last type for the developers conscious by merging Array functions in the Object class as an Ordered Dictionary. Type's are bull for me now in every way.
I also took the ON out of JSON and pass my data as JS, (yes the sockets layer is using JSON but that's questionably... maybe BSON or just JS is better agian (must purify).
All the languages can be transpile into JS now, but I say why not just use JavaScript in the first place? Oh because your old school and think you need types in you big corporation as you were taught by others and never thought about deeply fine, but it get's turned into JS and it strips all the types out when you build it. 
Anyway I say think again.
let there be let, don't waste time with const. In a scaled system cycles are king but we don't need to worry about nano seconds.
I could go one but I'll let the reader spend 40 years figuring out how to distill and extinguish the bull as we rush into the singularity.
The JS Run-Time Engine optimizes your types so you don't have to think about them, but you need to be aware it's better not to mix them. All functions should have defaults and/or best guesses etc. to make sure they return a result.
I use und because I don't want to type undefined all the time, and banging !it is hard to see but (it && it.thing) is a nice abbreviation.
I'd prefer if the runtime better handled it.thing like (it && it.thing) so no throwing there I guess, just return und.
In the end hoisting is efficient and probably better so you should ask yourself is strict even needed and then again no var let const etc. I'm sure that was the smart point and goal of the creator BE did in a week, when he create JS. All you do is check if und or make sure you set a default and for your for-loop counter 'i' (junior labeling) could be hoisted and nested via closure to wherever because it's single threaded system. I have nodejs fork per (CPUs - 1 for system) and grab both an IPV4 and IPV6 per fork so the farm and world can communicate in cells etc. so totally trans-formative again. With mass global parallel reactive GPU node computing the nano seconds in var vs let are meaningless. Optic networks trying to achieve the dream of realtime 60 FPS rendering make things like compression to bitcoin re-thinkable and possibly a waste of cycles on both ends or it should be hidden in the server's encryption (runtime server build cached and updated with watches), etc. Realtime hot-loading means the only compiling needed is JS to GL transpile on the fly. I'll stop there but it all leads to something wonderful I've waited 30 years for and THREE js is at the center of the UI of the future.
Adding ES6 => functions just duplicates another way for my single function JS parser to have to implement so wasteful again.

**Comment by mrdoob** [comment]
@MasterJames Sorry, TL;DR again. I'm interested on what you have to say, but in the time I'm able to read one of your posts I can merge 10 PRs from other people. Please, try to make your posts shorter.

**Comment by mrdoob** [comment]
Also, just like I recently mentioned to @pailhead, I don't think it's nice to revive closed PRs in this way.

**Comment by pailhead** [comment]
😟

**Pull request closed without merging**
