### PR TITLE
WebGLCubeRenderTarget: Use CubeTexture.

### PR DESCRIPTION
**Pull request by Mugen87**
This PR makes `WebGLCubeRenderTarget` use a `CubeTexture`. 

I've realized this allows a nice refactoring in `WebGLTextures`. `setTextureCubeDynamic()` becomes obsolete.

### CODE REVIEW

**Comment by Mugen87** [comment]
It seems when applying an instance of `WebGLCubeRenderTarget` to `Scene.background`, the background is now flipped. Investigating...

**Comment by Mugen87** [comment]
It seems these checks are problematic:
```js
uniforms.flipEnvMap.value = envMap.isCubeTexture ? - 1 : 1;
```
The engine should not set `flipEnvMap` to `-1` for `CubeTexture`s  referring to a `WebGLCubeRenderTarget`.

**Comment by Mugen87** [comment]
@mrdoob @WestLangley Do you have already a preferred solution for this use case? Maybe a flag `CubeTextures.needsFlip` that controls this operation?

**Comment by Mugen87** [comment]
Well, at least it seems the flag approach works^^.

**Comment by WestLangley** [comment]
This is an excellent refactoring, IMHO. Everything seems to be working.

TBH, I am not a fan of `._needsFlipEnvMap`, but I do not have a better suggestion.

```js
CubeTexture extends Texture

	this._needsFlipEnvMap = true;

WebGLCubeRenderTarget extends WebGLRenderTarget

	this.texture = new CubeTexture()

	this.texture._needsFlipEnvMap = false;


```

**Comment by Mugen87** [comment]
@mrdoob What do you think about this PR? I would love to see `setTextureCubeDynamic()` and `isWebGLCubeRenderTargetTexture` go away 😇 .

**Comment by mrdoob** [comment]
Yes! Lets give this a try!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> TBH, I am not a fan of `._needsFlipEnvMap`, but I do not have a better suggestion.

Would `flipXZ` be better? (Considering we already have `flipY`) 🤔

**Comment by Mugen87** [comment]
I'm fine with that 👍 .

**Comment by Mugen87** [comment]
BTW: I would like to add a comment to the property that explains why it's there. I understand that it's necessary to flip the env map when just using `CubeTexture` and not cube render target. However, I'm not sure I fully understand why this detail could not be implemented elsewhere. E.g. when setup the cube render target...

**Comment by mrdoob** [comment]
I used to know, but I forgot...

**Comment by WestLangley** [comment]
>Would flipXZ be better?

I do not think so. What is in the PR is better.

**Comment by Mugen87** [comment]
Well, it seems the flipping happens since the early days^^.

https://github.com/mrdoob/three.js/commit/946cc6a26ce0223df5ea3f48cc5f5656dddecde4#diff-c0e88b98497597a015ecf238e91ac3a0R890

**Comment by WestLangley** [comment]
@WestLangey [said](https://stackoverflow.com/questions/45998274/why-are-the-faces-of-a-cubemap-labelled-px-nx-py-ny-pz-nz/45999554#45999554):

>By convention -- likely based on the RenderMan spec from the 1990's -- cube maps are specified by WebGL (and three.js) in a coordinate system in which positive-x is to the right when looking up the positive-z axis -- in other words, in a left-handed coordinate system. By continuing this convention, preexisting cube maps continued to render correctly.

>three.js uses a right-handed coordinate system. So environment maps used in three.js appear to have px and nx swapped. (This is the case for every three.js cube map example.)

**Comment by Mugen87** [comment]
I hope you don't mind if I copy this into the code base for clarification 😇 .

**Pull request merged**
