### PR TITLE
Blender exporter: optionally export Custom Properties as userData.

### PR DESCRIPTION
**Pull request by binki**
I like that in blender you can add custom key/value data per object. I thought it would be useful to be able to create different objects in blender and tag them with different attributes so that my JavaScript thing can treat them differently depending on the tags. ObjectLoader already respects userData present in JSON. This patch adds exporting the custom blender properties to the JSON.

Custom Properties shown in both Blender and the export’s JSON (after this patch)

If this feature could be added to the exporter, whether with this exact patch or via a different method, that’d be great. It seems like a natural feature to me, at least ;-).

Please let me know if this patch can be improved.

Thanks!

### CODE REVIEW

**Comment by kpgbrink** [comment]
+1

**Comment by Mugen87** [comment]
@binki One little tip: You need to target the latest dev branch and not master (see [How to contribute to three.js?](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js))

**Comment by binki** [comment]
@Mugen87 OK, see #8246.

**Comment by Mugen87** [comment]
:+1:

**Pull request closed without merging**
