### PR TITLE
UVDebug: Process BufferGeometry without conversion

### PR DESCRIPTION
**Pull request by Mugen87**
More `Geometry` removal...

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawgit.com/Mugen87/three.js/dev11/examples/#misc_uv_tests

**Comment by WestLangley** [comment]
```javascript
if ( geo.isGeometry ) geo = new THREE.BufferGeometry().fromGeometry( geo );
```

If the user passes in `Geometry`, won't this generate a plot with face and vertex indices different from the original? I expect that would be quite confusing.

**Comment by WestLangley** [comment]
Your plots appear to be overprinting triangles on the right edge with two different sets of indices.

**Comment by Mugen87** [comment]
> Your plots appear to be overprinting triangles on the right edge with two different sets of indices.

Yeah, this also happens in the current implementation (see BoxGeometry). This means that several faces have same uv coords.

> If the user passes in Geometry, won't this generate a plot with face and vertex indices different from the original? I expect that would be quite confusing.

When converting to `BufferGeometry`, geometry data become non-indexed so the result will be different. We could stop supporting `Geometry` to prevent this...

**Comment by WestLangley** [comment]
>We could stop supporting Geometry to prevent this...

I think the only useful solution is to add direct support for both `Geometry` and `BufferGeometry` to this utility.

**Comment by Mugen87** [comment]
Okay, done. `UVDebug` handles now `Geometry` and `BufferGeometry` without conversions.

**Comment by WestLangley** [comment]
Notice how in the Icosahedron case, the triangles straddle the seam. That is what the special logic was for. :)

**Comment by Mugen87** [comment]
What do you mean with "triangles straddle the seam"? On what logic do you refer? Sry, I'm a bit lost^^.

**Comment by WestLangley** [comment]
For `IcosahedronGeometry( size, 1 )`, the triangles on the right side of the uv plot straddle the uv seam, that is, they continue onto the left side of the plot. The geometry will only render with a texture correctly if `wrapS = THREE.RepeatWrapping`. That is what the "// wrap x" inline comments are all about.

**Comment by Mugen87** [comment]
Um, the visual result is exactly like before...

**Comment by Mugen87** [comment]
This is how it looks in production:

image

**Comment by WestLangley** [comment]
I was not being critical. I was just making what I thought was an interesting point. I was reminded of #3299. Sorry I did not make myself more clear.

**Comment by WestLangley** [comment]
@mrdoob This PR is good-to-go.

**Comment by Mugen87** [comment]
@WestLangley Thanks for you help in this PR! :+1: :blush:

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
