### PR TITLE
Docs: Fix edit button

### LINKED ISSUE #15136: Edit button in docs broken after r96
##### Description of the problem
#14846 stripped the localization from the `[path]` placeholder to get the links to the source files working again but the edit button in the top right needed that to point to the localized docs file.

https://github.com/mrdoob/three.js/blob/12450bedbef53649992cf55f10d7c1b9a253570f/docs/page.js#L102-L106

First noticed in https://github.com/mrdoob/three.js/pull/14750#issuecomment-414792240 as far as I can tell. A previous hotfix(hiding the button) was applied in 0c58464ab1b37451d6440025bc5d8c0095fec8da, but got removed with the release of r96.

### PR DESCRIPTION
**Pull request by Mugen87**
Finally fixed the `Edit` button for the API doc pages.

Fixed #15136

### CODE REVIEW

**Comment by Mugen87** [comment]
Manual: https://raw.githack.com/Mugen87/three.js/dev20/docs/index.html#manual/en/introduction/Creating-a-scene
API: https://raw.githack.com/Mugen87/three.js/dev20/docs/index.html#api/en/animation/AnimationAction
Examples: https://raw.githack.com/Mugen87/three.js/dev20/docs/index.html#examples/exporters/GLTFExporter

**Review by fordhurley — APPROVED** [review]
LGTM 👍 

Looks like the bug was introduced by me in #14846. Sorry about that!

**Comment by Mugen87** [comment]
Merging. This bug is annoying^^.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Cheery picked into `gh-pages`.

**Pull request merged**
