### PR TITLE
Package.json: Added "lint-fix" script

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
This change is mentioned within `three.js/.github/CONTRIBUTING.md`. Making the change into a script might be a worthy improvement to everyone's workflow.

### CODE REVIEW

**Comment by gkjohnson** [comment]
With this change PRs that introduce linting errors may not be caught because the CI runs these lint commands and instead of logging an error it could pass because it fixed the errors only in the CI build. In my opinion running a fix command should be explicit to avoid eslint inadvertently changing peoples files when they don't intend to.

**Comment by DefinitelyMaybe** [comment]
> With this change PRs that introduce linting errors may not be caught because the CI runs these lint commands and instead of logging an error it could pass because it fixed the errors only in the CI build.

my gosh. absolutely.

> In my opinion running a fix command should be explicit to avoid eslint inadvertently changing peoples files when they don't intend to.

but if one intends on contributing to three.js, one must follow the styleguide. perhaps a new script then?

**Comment by mrdoob** [comment]
What does this do?

**Comment by DefinitelyMaybe** [comment]
introduces a new script that fixes as many lint issues as eslint can sort out. instead of folks adding the ‛--fix‛ parameter within their local ‛test-lint‛ script each time.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
