### PR TITLE
Update SelectionHelper.js

### PR DESCRIPTION
**Pull request by tsaockham**
Adding updated mouse event listeners so this works on modern browsers. (old code did not work on Chrome)

Related issues:

N/A

**Description**

Adding updated mouse event listeners so this works on modern browsers. (old code did not work on Chrome)

### CODE REVIEW

**Comment by Mugen87** [comment]
> (old code did not work on Chrome)

It seems the official example works fine on my Chrome  86.0.4240.80  on macOS 10.15.7.

https://threejs.org/examples/misc_boxselection

I guess there could be a problem if you combine the helper with controls like `OrbitControls`.

BTW: Do you mind editing the version `SelectionHelper` in `example/js`, too?

**Comment by tsaockham** [comment]
I've updated the .js version.  You're correct, I do have orbit controls working as well, so likely a conflict with that.  The example works on my browser as well, but wasn't working when I ported it into my app.

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/tsaockham/three.js/patch-1/examples/misc_boxselection.html

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
