### PR TITLE
src/extras/curves: move to es6 classes

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
`Three.Legacy.js` does contain code like this:
```js
CatmullRomCurve3.call( this, points );
```
According to lgtm, this code will break now because `CatmullRomCurve3` is now a class.

**Comment by Mugen87** [comment]
Maybe just removing it? AFAICS, alias like `ClosedSplineCurve3`, `SplineCurve3` and `Spline` are quite old. Otherwise these have to be converted to classes, too.

**Comment by mrdoob** [comment]
> Maybe just removing it?

Yep! 👍

**Pull request merged**
