### PR TITLE
Double spacing after code blocks to preserve line break

### PR DESCRIPTION
**Pull request by siahlah**

### CODE REVIEW

**Comment by mrdoob** [comment]
In what browser is that? Line breaks show up properly already in Chrome here... 

screen shot 2016-01-04 at 04 29 14

**Comment by hydrospell** [comment]
Hm strange - this is on Chrome Version 47.0.2526.106 (64-bit), OSX

screen shot 2016-01-04 at 10 57 42 pm

**Comment by mrdoob** [comment]
Strange indeed! Mine is 47.0.2526.106 (64-bit) OSX too. Do you have any extensions installed?

**Comment by hydrospell** [comment]
Sorry! dug further and turns out Vimium is causing this problem. (Strange!) I’ll close this PR then. Thanks!

**Comment by mrdoob** [comment]
😶

**Pull request closed without merging**
