### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #XXXX

**Description**

Updated deps and version to `0.153.0`

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, is it really necessary to still manually update dev dependencies now that renovate is in place?

**Comment by linbingquan** [comment]
> Um, is it necessary to still manually update dev dependencies now that renovate is in place?

Should we  just update `version` for `package.json`?

**Comment by Mugen87** [comment]
Yeah, I guess that is sufficient.

**Comment by linbingquan** [comment]
Done.

**Pull request merged**
