### PR TITLE
Add tile/offset/lightmap extensions support to GLTF2Loader

### PR DESCRIPTION
**Pull request by stevenvergenz**
This PR adds GLTF2Loader support for the draft extensions [AVR_texture_offset_tile](https://github.com/KhronosGroup/glTF/pull/1015) and [AVR_lights_static](https://github.com/KhronosGroup/glTF/pull/1017). Note that Three.js does not currently allow these extensions to be used together, as texture offset and repeat settings do not affect lightmap or AO textures.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, seems like this has conflicts.

**Comment by donmccurdy** [comment]
Thanks @stevenvergenz – I think you'll need to rebase here to sync up with #11592.

I will leave a couple comments on the draft extension PRs.

**Comment by mrdoob** [comment]
Is this still needed?

**Comment by donmccurdy** [comment]
With apologies for the trouble @stevenvergenz, I'd vote that we not merge this PR, but rather work on #11682 to allow GLTF2Loader to use extensions that are written outside of itself.

**Comment by stevenvergenz** [comment]
My related work has been deprioritized for now, so I'm not in a hurry.

**Pull request closed without merging**
