### PR TITLE
Rename BufferAttribute.length to BufferAttribute.count

### PR DESCRIPTION
**Pull request by benaadams**
Lazy option, mostly to continue discussion from #6495

### CODE REVIEW

**Comment by benaadams** [comment]
@WestLangley 
> Perhaps we can come up with a better method name than length. This is incredibly confusing, IMHO... Maybe numElements or count.

**Comment by benaadams** [comment]
Use case for either ```BufferAttribute``` or ```InterleavedBufferAttribute```:
````javascript
for ( var i = 0, ul = positionBuffer.count; i < ul; i++ ) {
     positionBuffer.setXYZ( i, x, y, z );
}
````
or
````javascript
for ( var i = 0, ul = uvBuffer.count; i < ul; i++ ) {
     uvBuffer.setXY( i, u, v );
}
````

**Comment by WestLangley** [comment]
Thank you. Perhaps a better title would be

    Rename BufferAttribute.length to BufferAttriibute.count

**Comment by WestLangley** [comment]
: - )

**Comment by mrdoob** [comment]
I'm not sold about this change yet... I like `.length` because it follows the `array.length` "pattern".

**Comment by WestLangley** [comment]
> I'm not sold about this change yet... I like .length because it follows the array.length "pattern".

What is it the length of?

**Comment by mrdoob** [comment]
Of items/elements?

**Comment by WestLangley** [comment]
The value that returns is the "number" of items/elements.

**Comment by mrdoob** [comment]
[Array.prototype.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length)
It is true, however, that this follows the `this.drawcalls[ 0 ].count` naming...

**Comment by WestLangley** [comment]
> I understand that you find it confusing because of Vector*.length()?

I was prompted to [suggest](https://github.com/mrdoob/three.js/pull/6495) a change to the name when I read #6494.

**Comment by mrdoob** [comment]
> I was prompted to [suggest](https://github.com/mrdoob/three.js/pull/6495#discussion_r29544598) a change to the name when I read #6494. 

Yep! I read that exchange. What is so confusing about `.length`?

**Comment by WestLangley** [comment]
> What is so confusing about .length?

To me, it is not clear what it is the length of.

Is it the length of the typed array, or is it the number of data elements in the typed array.

It is the latter.

    length = this.array.length / this.itemSize;

Consequently, I suggested `count` or `numElements` as the method name.

**Comment by mrdoob** [comment]
Ok. Lets see how it feels 😀

**Pull request merged**
