### PR TITLE
BasicDepthPacking: white nearest

### LINKED ISSUE #13329: Depth material example inverted
##### White to black or black to white

Depth material example states 'White is nearest, black is farthest'. But example rendering shows the opposite. Need to make consistent. Decision of whether to change text, or material.
https://threejs.org/docs/#api/materials/MeshDepthMaterial

##### Three.js version

- [ x] Dev
- [ x] r90

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #13329.

### CODE REVIEW

**Comment by WestLangley** [comment]
I made what I think are the correct mods to the SAO code. It looks good, anyway!

/ping @Ludobaka 
/ping @bhouston

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
I was not able to get the God-rays example to work properly. That example is 6 years old. Perhaps someone is interested in updating it...

**Comment by WestLangley** [comment]
Merged in 24 seconds after posting. That has got to be a record! :)

**Comment by Mugen87** [comment]
What about: https://threejs.org/examples/webgl_depth_texture.html

It is still "black nearest" in this case. Do we need a change here?

**Comment by WestLangley** [comment]
@Mugen87 Might as well... I'll fix. Thanks.

**Pull request merged**
