### PR TITLE
Added ascii art and three.min.js to docs page

### PR DESCRIPTION
**Pull request by gregtatum**
Two small tweaks for the docs pages. I added a little ascii art to the console.log for some fun. Feel free to kill, but I started making it rather than programming tonight. Also I added the three.min.js to the page so that it's easy to open up the console and type in and try some code while you're reading the docs. A lot of other JS packages do this to make it easier.

screen shot 2015-02-18 at 11 24 04 pm

### CODE REVIEW

**Comment by mrdoob** [comment]
Haha! Cute! ^^

**Comment by mrdoob** [comment]
Improved it a bit ;)

screen shot 2015-02-19 at 3 52 10 pm

**Comment by mrdoob** [comment]
Ops! The T was too long... Fixed!

screen shot 2015-02-19 at 3 57 06 pm

**Comment by TatumCreative** [comment]
Cool, I dig it!

**Comment by WestLangley** [comment]
three.js is not capitalized. (It shouldn't be in the docs either, for that matter.) Can you make the "t" lower case?  : - )

**Comment by mrdoob** [comment]
Fixed ^^

screen shot 2015-02-25 at 9 55 27 pm

**Pull request merged**
