### PR TITLE
Update 3MFLoader.js to use JSZip 3 (via jszip-sync)

### PR DESCRIPTION
**Pull request by silvainSayduck**

### CODE REVIEW

**Comment by Mugen87** [comment]
Just for my understanding: What are the benefits of this change?

**Comment by silvainSayduck** [comment]
The latest version of JSZip (3.x) crashes with the current implementation in 3MFLoader. The syntax has changed for almost everything, including the constructor, and the synchronous versions of the methods do not exist anymore.

**Comment by Mugen87** [comment]
Unfortunately, this change breaks the official 3MF examples. They crash with the error:

> Uncaught TypeError: zip.sync is not a function

So it's necessary to upgrade [jszip.min.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/libs/jszip.min.js), too. And all other code that depends on this lib (at least `AMFLoader`, `KMZLoader` and the example `webgl2_materials_texture2darray`).

**Comment by silvainSayduck** [comment]
Sorry, I didn't see that other files where depending on JSZip. But yes, this PR is about updating JSZip. If it is not interesting or required, then it can be closed.

I just thought it might make sense to work with the latest version of JSZip which I am using in my project.

**Comment by Mugen87** [comment]
> I just thought it might make sense to work with the latest version of JSZip which I am using in my project.

Definitely. The upgrade was tried once (see #12849) but it seems `zip.sync()` was not available at that time. Would be nice to have a consistent solution in the repo.

**Comment by silvainSayduck** [comment]
Do you mean that this PR should update all other impacted files too? Do we have an exhaustive list of those files somewhere? Not sure when I'll have the time for this, but I might give it a try if I can.

**Comment by Mugen87** [comment]
> Do you mean that this PR should update all other impacted files too?

I think we won't get this PR merged otherwise.

>  Do we have an exhaustive list of those files somewhere?

Nope, but you search in the repo where `jszip.min.js` is included. AFAIK, it should be `3MFLoader`, `AMFLoader`, `KMZLoader` and `webgl2_materials_texture2darray`. Besides, the editor has a dependency to `jszip.min.js`.

> Not sure when I'll have the time for this, but I might give it a try if I can.

I think there is no rush. We should also try to put `getZippedFileContentSync()` in a helper method so we don't copy the code over and over again.

BTW: I did not find any references to `jszip-sync` at the JZIP repo? Where does it come from?

**Comment by silvainSayduck** [comment]
It's a fork, but seems maintained in parallel with the original JSZip. I put the link to the package in the warning message, but here it is again: https://www.npmjs.com/package/jszip-sync

**Comment by Mugen87** [comment]
Um, too bad. I thought it's part of real `JSZip` project. Are there any other libs outside there that could replace `JSZip`?

**Comment by silvainSayduck** [comment]
There probably is, but I haven't used any.

**Comment by Mugen87** [comment]
I'm actually not happy with the amount of code that is necessary to work with JSZip async code path. And we also want to keep this pattern:
```js
const loader = new THREE.3MFLoader();
const model = loader.parse( data );
```
As long as there is no more elegant way to handle decompression, I think it's better to stay at the current version of JSZip.

**Comment by silvainSayduck** [comment]
Hi,

Yes, I agree. Using the async approach would require a lot of code update and paradigm change, which is why I went with the JSZip sync fork. But if this is not good enough for THREE, then feel free to close the PR :)

**Pull request closed without merging**
