### PR TITLE
Added Beta/Gamma offsets

### PR DESCRIPTION
**Pull request by kopiro**

### CODE REVIEW

**Comment by mrdoob** [comment]
How about just doing `this.orientationOffset = [ 0, 0, 0 ]`?

**Comment by mistic100** [comment]
@kopiro do you have time to fix it ?

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/8538#issuecomment-208044931

I also think that the entire `offset` logic is too application specific and should not be a part of `DeviceOrientationControls`. In my opinion the changes made in #8538 are not consistent. Why is `alpha` exposed and not `beta` and `gamma`? The method `updateAlphaOffsetAngle` seems also not necessary because the users can call `update()` itself after changing `alphaOffsetAngle`.

**Comment by mrdoob** [comment]
@Mugen87 Agreed.

**Pull request closed without merging**
