### PR TITLE
EXAMPLES: replaced cube_dynamic with cube_dynamic2, added car controls

### PR DESCRIPTION
**Pull request by looeee**
As discussed in #13223:

* renamed webgl_materials_cube_dynamic2 to webgl_materials_cube_dynamic
* created new misc_controls_car example to showcase the [Car.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/Car.js) file

I've updated Car.js as follow:
* it now handles controls and setting up event listeners internally
* no longer handles loading and creation of meshes, so it can use a suitable model loaded by any loader
* (very roughly!) uses real world units 
* calculates all car dimensions automatically
* cars now have a brake! (use space) 

It takes a model that must have 4 wheels, which can be `Group`s, `Object3D`s or `Mesh`es and must be named `wheelFrontLeft`, `wheelFrontRight`, `wheelRearLeft` and  `wheelRearRight`.

Live version of the new example [here](https://rawgit.com/looeee/three.js/cbd862a2ead17772c36e8ab14dc5ab3fc7509fc7/examples/misc_controls_car.html).

### CODE REVIEW

**Comment by looeee** [comment]
Updated:

* improved the model a bit  (now just over 100k polys and less gaps)
* added optional steering wheel rotation 
* added "zoom in" effect when the car has first loaded 


[Updated link](https://rawgit.com/looeee/three.js/942aa81f819ec78d0a76536d49eca207e9fede47/examples/misc_controls_car.html)

**Comment by mrdoob** [comment]
I think I would use a normal `GridHelper` instead. The radial one is confusing in this example.

**Comment by looeee** [comment]
OK, [done](https://rawgit.com/looeee/three.js/312cc816df9897a6f36faba96c4d3048c3f08f5c/examples/misc_controls_car.html)!

**Comment by looeee** [comment]
Closed in favour of #14843

**Pull request closed without merging**
