### PR TITLE
Docs: Clean up

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Comment by looeee** [comment]
The examples use this style:

``` js
if ( WEBGL.isWebGLAvailable() === false ) {

	document.body.appendChild( WEBGL.getWebGLErrorMessage() );

}
```

Perhaps we should do the same in the docs?

**Comment by linbingquan** [comment]
> The examples use this style:
> 
> ```js
> if ( WEBGL.isWebGLAvailable() === false ) {
> 
> 	document.body.appendChild( WEBGL.getWebGLErrorMessage() );
> 
> }
> ```
> 
> Perhaps we should do the same in the docs?

@looeee I think it's OK now.

```js
		<code>
		if ( WEBGL.isWebGLAvailable() ) {

			// Initiate function or other initializations here
			animate();

		} else {

			var warning = WEBGL.getWebGLErrorMessage();
			document.getElementById( 'container' ).appendChild( warning );

		}
		</code>
```

**Comment by Mugen87** [comment]
I think @looeee feedback was not about the code style but to change the code section analogous to the examples.

**Comment by Mugen87** [comment]
Let's merge this. We can still align the code according to the examples with a different PR. This one improves the code style after all.

**Pull request merged**
