### PR TITLE
make Object3D properties (pos,rot,quat,scale) configurable

### PR DESCRIPTION
**Pull request by sublambda**
make Object3D properties (pos,rot,quat,scale) configurable to allow extensions by subclasses and proxies, per discussion in issue #11092

### CODE REVIEW

**Comment by WestLangley** [comment]
Can you provide an example code snippet showing how this PR allows two meshes to share the same `quaternion/rotation`?

**Comment by sublambda** [comment]
here's a self-contained example, using a proxy to share rotation/quaternion properties.
(without the PR, this code will raise a TypeError on property access)

```
<script src="js/three.js"></script>
<script>

// returns proxy for obj, whose rot/quat values come from source
//  Object3D synchronizes values of rotation and quaternion,
//  so both properties must be forwarded together
function sharedrot(obj, source) {
  var fwd = { rotation: true, quaternion: true };
  return new Proxy(obj, {
    get: function(target, key, receiver) {
      return Reflect.get(fwd[key] ? source : target, key, receiver);
    }
  });
}
function box() {
  var geometry = new THREE.BoxGeometry(100,100,100);
  var material = new THREE.MeshBasicMaterial({wireframe: true});
  return new THREE.Mesh(geometry, material);
}

function init() {
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, window.innerWidth/window.innerHeight, 1, 1000);
  camera.position.set(0, 0, 400);
  scene.add(camera);

  var b1 = box();
  var b2 = sharedrot(box(), b1);

  b1.position.x = -100;
  b2.position.x = 100;

  scene.add(b1);
  scene.add(b2);

  var renderer = new THREE.WebGLRenderer();
  renderer.setSize(window.innerWidth, window.innerHeight);
  document.body.appendChild(renderer.domElement);

  function loop() {
    requestAnimationFrame(loop);
    render();
  }
  function render() {
    b1.rotation.y = Date.now()/1000;
    b2.rotation.x = Date.now()/2000;
    renderer.render(scene, camera);
  }
  loop();
}

window.onload = init;

</script>

```

**Comment by mrdoob** [comment]
/me just learned about Proxys...
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by Mugen87** [comment]
I think this one can be merged.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
I don't know...

If we allowed this then this troublesome old pattern would work again:

```js
object.rotation = object2.rotation;
```

**Comment by jbaicoianu** [comment]
@mrdoob this change does not allow accidental overwriting of object properties via simple assignment. It does allow users who know what they're doing to swap the internal THREE.Vector3 instances for external ones - for example, so that the Vector3 object can point to the same underlying object as the physics engine.

**Comment by mrdoob** [comment]
Sounds good.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Should we introduce this in the examples? Maybe in the physics ones?

**Comment by sublambda** [comment]
thanks @mrdoob!

Physics simulation is a good use case. I could also provide an example
using this to share object state across multiple scene graphs.
(original motivation for PR)

**Comment by mrdoob** [comment]
Physics simulation use case seems easier to understand :)

**Pull request merged**
