### PR TITLE
FBXLoader: Fix incorrect joint orientation for animated FBX models exported from Maya

### PR DESCRIPTION
**Pull request by mwhirls**
**Description**

This PR fixes a bug where the rotation for joints on some FBX models from Maya were not being read correctly by `FBXLoader`.  These models have both a non-default Euler order and have the "Joint Orient" option set on their joints.  The rotation matrix for "Joint Orient" is stored in "PreRotation" in the FBX file and `FBXLoader` was erroneously using the Euler order for the regular joint rotation to read it.

Example model: [WonkyWalk.fbx.zip](https://github.com/user-attachments/files/16852505/WonkyWalk.fbx.zip)

Before the fix:

https://github.com/user-attachments/assets/3f7848bc-5dff-4850-aac4-6eabff37318c

After the fix:

https://github.com/user-attachments/assets/f9869353-40f9-4bbe-972c-cec54e6b87bd

### CODE REVIEW

**Comment by Mugen87** [comment]
@mwhirls Since you linked #14903 I have tested the PR with the related Zombie asset ( `WhiteClownSambaDancing.fbx`). Unfortunately, it is still broken. So is #14903 a different issue or do I miss something?

**Comment by mwhirls** [comment]
> @mwhirls Since you linked #14903 I have tested the PR with the related Zombie asset ( `WhiteClownSambaDancing.fbx`). Unfortunately, it is still broken. So is #14903 a different issue or do I miss something?

Ah, that must be a different issue then.  I linked it because I thought it could possibly be related, but my team was testing with different models.  I will remove the link here to avoid confusion.

**Comment by pikilipita** [comment]
Does this also fix the blender exports issue?
[https://github.com/mrdoob/three.js/issues/27907](https://github.com/mrdoob/three.js/issues/27907)

**Comment by Mugen87** [comment]
The runtime error of #27907 does not appear anymore since `r163` thanks to #27956.

**Pull request merged**
