### PR TITLE
MeshCubeMaterial - cube backgrounds with Blur, HDR Encoding, CubeUV, and ToneMapping support

### PR DESCRIPTION
**Pull request by bhouston**
Just a quick experiment to promote the cube shader to a full material.

This allows one to blur the background, and use an HDR coded material and also match its tone mapping to the rest of the scene.

As I am unsure if this is desired, I have not updated all uses of the "cube" shader to the MeshCubeMaterial.

The results look like this - you can adjust the roughness (blur) of the background or its intensity and opacity, and switch between an LDR or HDR cubemap:

image

(This is an expansion of this other PR: https://github.com/mrdoob/three.js/pull/9158 )

### CODE REVIEW

**Comment by bhouston** [comment]
Demo link: http://threejsworker.com/api/pullrequests/9163/examples/webgl_postprocessing_backgrounds.html

These types of blurred backgrounds are what Marmoset Toolbag uses.  I find them effective in showcases.

**Comment by bhouston** [comment]
@mrdoob, thus new MeshCubeMateiral would be a great upgrade for scene.backgroundBoxMesh.material.  The blurry backgrounds would work similarly in that case as with the CubeTexturePass effect. :)

**Comment by mrdoob** [comment]
This whole squash PRs approach create conflicts easily. Do you mind solving the conflicts on this PR?

**Comment by bhouston** [comment]
done. :)

**Comment by bhouston** [comment]
never mind, I didn't update this one.

This PR breaks all uses of Cube shader.  If you want it I will have to update a lot of things.  I was holding off on that until I knew you wanted this.  I'll try to make all those updates over the next few days.

**Comment by bhouston** [comment]
This is stale and replaced with with this new PR attempt: https://github.com/mrdoob/three.js/pull/16900

**Pull request closed without merging**
