### PR TITLE
Fix CSM shadow clipped by to small shadow camera frustum

### PR DESCRIPTION
**Pull request by nipmarsh**
Shadow frustrum is too small and shadow maps are clipped when getting close

Capture

Capture2

### CODE REVIEW

**Comment by gkjohnson** [comment]
Those lines are setting the shadow camera width and height to be the largest dimension of the camera frustum so it should always be able to encompass it ( `squaredBBWidth / 2 + squaredBBWidth / 2 = squaredBBWidth` ) so I don't feel this is correct.

Can you reproduce the issue with a jsfiddle?

**Comment by nipmarsh** [comment]
Maybe it's not what you mathematically expect but it fix the issue. Sorry i don't have time to do a jsfiddle. I just spotted the issue with captures, feel free to investigate futhermore.

**Comment by gkjohnson** [comment]
Unfortunately I can't investigate without a repro case. I haven't seen this in my work and can't reproduce it in [the csm example](https://threejs.org/examples/?q=csm#webgl_shadowmap_csm), either. It's possible there's an issue in how the class is being used in your application. The change you're suggesting will half the resolution of CSM shadows so it should not just be made without understanding why.

**Comment by WestLangley** [comment]
>Sorry i don't have time to do a jsfiddle.

Closing then.

**Comment by nipmarsh** [comment]
I just said i won't do a jsfiddle, but i will investigate in the example

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：nipmarsh <notifications@github.com>
发送时间：2020-05-16 03:06
主题：Re: [mrdoob/three.js] Fix CSM shadow clipped by to small shadow camera frustum (#19363)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

I just said i won't do a jsfiddle, but i will investigate in the example

**Pull request closed without merging**
