### PR TITLE
GLTFLoader: Clean up normalScale workaround

### PR DESCRIPTION
**Pull request by donmccurdy**
Consolidating the special case from https://github.com/mrdoob/three.js/issues/11438#issuecomment-507003995 into one place.

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like `webgl_loader_gltf_transmission` and `webgl_loader_gltf_variants` are failing?

**Comment by donmccurdy** [comment]
Hm, thanks! I'll take a look at that soon, it's fine for this to wait until r134 though.

**Comment by donmccurdy** [comment]
Fixed ✅

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
