### PR TITLE
Examples: Added origin-trial token

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adds an origin-trial token to all WebVR examples (except the HTC Vive ones) to address #11119. Okay like this?

### CODE REVIEW

**Comment by mrdoob** [comment]
Perfect like this 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
We may want to request another token though...

**Comment by Mugen87** [comment]
Google informs you timely when the token is going to expire. You can then renew the participation in the origin trial. I will do that as soon as i receive the notification.

**Pull request merged**
