### PR TITLE
Fix FlyControls DragToLook sometimes stuck on dragging

### PR DESCRIPTION
**Pull request by krei-se**
Related issue: None

When using FlyControls, after a couple of clicks and drags the Look Around gets stuck and keeps on rotating the camera even when the mouse button is released.

I suspected this to be the case because status gets incremented twice and never switches back to 0 again.

So i fixed it :) And it works reliable now.

### CODE REVIEW

**Comment by Mugen87** [comment]
PR: https://jsfiddle.net/9reuj2h3/show
Prod: https://jsfiddle.net/s67f9ekw/show

**Comment by Mugen87** [comment]
Unfortunately, the PR changes multi-touch behavior. If you use two fingers for dragging, the existing version supports dragging until all fingers are lifted. In the new version, dragging is stopped after a single finger is lifted. That because `status` does not count pointer anymore.

I think it would be better to find out why `status` isn't correctly decreased in some cases.  Can you please check if using `pointercancel` as an additional event for executing `_pointerup()` solves the issue? https://jsfiddle.net/aq8nhgv3/1/show

**Comment by krei-se** [comment]
I see the reason to use a counter now, thanks!

Sadly i could not reproduce the bug for now but had a browser update in the meantime. Still i would suspect pointercancel should set the state to zero to be sure, not decrement the counter? From the MDN i understand this event fires for several reasons like switching the device orientation, accidential input etc. but yeah it would prevent this bug for sure (in a separate function though, not via additional _pointerup).

Thanks for taking the time looking into this as this descent-style camera is loads of fun and counting the number of fingers allows for additions of roll, etc.!

**Comment by Mugen87** [comment]
>  Still i would suspect pointercancel should set the state to zero to be sure, not decrement the counter?

AFAIK, `pointercancel` fires per active pointer. So decrement the counter should be the more correct option.

**Comment by Mugen87** [comment]
> Still i would suspect pointercancel should set the state to zero to be sure, not decrement the counter? 

Um, I think you are right there. Previously, I have assumed `pointercancel` is fired per active pointer but it seems more of a global event. Yes, in this case, setting to `0` is more correct. I'll file a PR.

**Comment by Mugen87** [comment]
Closing in favor of #26973.

**Comment by krei-se** [comment]
Thanks for taking the time to look into this - it's a much needed boost for my development to encounter communities with constructive discussion and application of what works. Enjoy Autumn!

**Comment by krei-se** [comment]
I integrated pointercancel and even though the panning still hangs sometimes, after another short drag with the mouse pointercancel fires and makes sure it stays fixed :)

**Pull request closed without merging**
