### PR TITLE
Documentation: Added "How to dispose of objects" guide

### LINKED ISSUE #11345: Docs: Explain the caching mechanism of three.js
It would be very useful if somebody would create an additional documentation page that explains the different caching mechanism of `three.js`:

- It should be highlighted that a caching system is an important part of a 3D library in order to reduce the overhead implied by recreating or resetting something already done. The goal is to minimize the communication between `three.js` and the WebGL API, because those API calls can be expensive.
- Provide an overview what kind of entities are cached in `three.js` (e.g. Materials, Geometries, Textures...).
- Explain, what the `.dispose()` methods do and why they are important.

In the past, i've seen many questions about caching and code where `.dispose()` is not used correctly. An additional documentation page will provide a better understanding of this important topic.

The page could be integrated in the `Next Steps` section.

### PR DESCRIPTION
**Pull request by Mugen87**
Related #11345

The guide explains some things about the usage and purpose of the engine's `dispose()` methods.

### CODE REVIEW

**Comment by WestLangley** [comment]
I think it would be beneficial to discuss `renderer.info` in this context.

I'd also suggest changing the title to something like "How to dispose of objects properly".

Also, provide links to the relevant examples.

**Comment by Mugen87** [comment]
> I think it would be beneficial to discuss `renderer.info` in this context.

Good idea! I have added an additional question in the FAQ section in order to discuss this topic.

> I'd also suggest changing the title to something like "How to dispose of objects properly".

Done. However, I had to remove "properly", otherwise the title is too long and breaks in the side menu.

> Also, provide links to the relevant examples.

Okay, I have added the `memory` examples which were originally developed to demonstrate `dispose()`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by roschler** [comment]
Is there a link to the guide somewhere?  All the links on this thread lead to other GitHub commit/issue posts.

**Comment by Mugen87** [comment]
There you go: https://threejs.org/docs/index.html#manual/en/introduction/How-to-dispose-of-objects

**Comment by WilliamBagel** [comment]
Here is the updated link for anyone looking: https://threejs.org/manual/#en/how-to-dispose-of-objects
It took me a while to find this because it wouldn't appear in google search results.

**Pull request merged**
