### PR TITLE
Curve: Refactoring

### PR DESCRIPTION
**Pull request by Mugen87**
This PR does the following:

- Makes `__arcLengthDivisions` to a "public" property (see #10432)
- Corrects the inheritance of curves
- Fixes `updateArcLengths` in `CurvePath`
- Updates docs

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@Mugen87 It appears the docs example code was overlooked, though, as it is now broken.

**Comment by Mugen87** [comment]
Oops! Hope, that fixed it!

**Pull request merged**
