### PR TITLE
OrbitControls: Method to check if rendering is needed

### PR DESCRIPTION
**Pull request by samipe**
Proposal for a public method that will allow you to check if rendering is needed due to camera movement. Useful for power management if you have a static scene. Also works with damping enabled.

Couldn't get zoom detection to work with either zoomChanged or scale. Any ideas?

    const animate = function () {
        if (controls.needsUpdate()) renderer.render(scene, camera)  
        requestAnimationFrame(animate)  
    }

### CODE REVIEW

**Comment by aardgoose** [comment]
Have you considered listening for the change event that is dispatched by the update() method?

controls.addEventListener( 'change', myRenderFunction );

This is only dispatched when the scene needs rendering and handles zoom changes. You also don't need to use requestAnimationFrame() at all so even more power use friendly.

**Comment by Mugen87** [comment]
Indeed, the `change` event is intended for exact this purpoes.

**Comment by samipe** [comment]
Oh I see, didn't actually think of that! However, my use case for this was to detect changes with damping, as there is a brief need for updates even after you are not inputting any controls. This can not be handled by the change event I think?

Even so, I understand if this feature is deemed too specific, in that case close this PR

**Comment by gkjohnson** [comment]
Looks like the change event only fires when the camera changes when calling update:

https://github.com/mrdoob/three.js/blob/4a54d69b70953eddf4fbabe1b8b972e8332404cd/examples/jsm/controls/OrbitControls.js#L227-L239

**Comment by WestLangley** [comment]
For a static scene with damping, this pattern renders the scene only when necessary.
```js
controls = new OrbitControls( camera, renderer.domElement );

controls.addEventListener( 'change', render );

controls.enableDamping = true;

function render() {

	renderer.render( scene, camera );
	
	stats.update();

}

function animate() {

	requestAnimationFrame( animate );

	controls.update();

}
```
The other alternative we entertained -- but chose not to pursue -- was to have `OrbitControls` call `requestAnimationFrame()` itself.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Garrett Johnson <notifications@github.com>
发送时间：2020-05-18 01:20
主题：Re: [mrdoob/three.js] OrbitControls: Method to check if rendering is needed (#19379)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Looks like the change event only fires when the camera changes when calling update:
https://github.com/mrdoob/three.js/blob/4a54d69b70953eddf4fbabe1b8b972e8332404cd/examples/jsm/controls/OrbitControls.js#L227-L239

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Sami Kolari <notifications@github.com>
发送时间：2020-05-18 00:04
主题：Re: [mrdoob/three.js] OrbitControls: Method to check if rendering is needed (#19379)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Oh I see, didn't actually think of that! However, my use case for this was to detect changes with damping, as there is a brief need for updates even after you are not inputting any controls. This can not be handled by the change event I think?
Even so, I understand if this feature is deemed too specific, in that case close this PR

**Comment by WestLangley** [comment]
IMHO, I think what @WestLangley said in https://github.com/mrdoob/three.js/pull/19379#issuecomment-629834155 should get more attention. :-)

**Pull request closed without merging**
