### PR TITLE
TrackballControls with new rotation mode

### PR DESCRIPTION
**Pull request by daron1337**
Following indication on https://github.com/mrdoob/three.js/pull/6103 I submitted a new pull request by removing the old rotation on TrackballControls. The related example has been updated.
I also simplified the equation on getMouseOnCircle as suggested in the previous discussion.

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks!

**Comment by daron1337** [comment]
you're welcome!

**Comment by WestLangley** [comment]
@daron1337 

How do you feel about the default settings? On my iMac, and I know this is personal perference, the following settings seem more "balanced":

	controls.rotateSpeed = 2.0;
	controls.zoomSpeed = 0.4;
	controls.panSpeed = 0.3;

Since you have changed the math, do you think the defaults need to be modified? I am not pushing for it -- just a thought.

On an iPhone, the above settings seem to me to be too sensitive. Hmm... I wonder if the settings need to be device-specific?

**Comment by daron1337** [comment]
In my opinion, user while adding TrackballControls to its application has to customize speed settings depending of its purposes.

I check it on iPhone and yes, it seems a bit faster than on desktop. 
I think maybe could be related to screen dimensions. I will check it.
However, the old rotation method seems to has the same behavior ( a bit faster on small screens )

**Comment by arose** [comment]
Thanks @daron1337! I just tested the new TrackballControls version (using the example and in my own project; on ubuntu with latest Firefox and Chrome; IE11 on Win8.1 in VirtualBox) and noticed a few odd things.

- compared to the old behavior rotation is much slower (i.e. when I move the mouse all the way from left to right I now get a ~5 degree rotation compared to about 180 degree before)
- when I increase `.rotateSpeed` to 20, rotation is faster but somewhat jittery (i.e. small deviations from moving in a straight line have too much of an effect, imho)
- personally like the old behavior more (irrespective of the slower rotation)
- having a useful behavior in the corners is great -- I wonder if the the old behavior could be combined with the new behavior just in the corners

Overall I would really like to have the old behavior as an option!

**Comment by daron1337** [comment]
Dear @arose 

* Yes, we discussed it here https://github.com/mrdoob/three.js/pull/6103 . 
* `.rotateSpeed` to 20 is too much. I suggest to use a value between 0.3 and 2.5. However, I will set it to 20 and I will check the behavior.
* As I said here https://github.com/mrdoob/three.js/pull/6103 it is subjective. 
* With the old behavior you were on a sphere, now not anymore. So you can't combine the two methods.

**Comment by arose** [comment]
After some investigation I have to say that the new behavior is great! Turns out the strange behavior originates elsewhere.

Most examples use this pattern

```javascript
controls.addEventListener( 'change', render );

function animate(){
    requestAnimationFrame( animate );
    controls.update();
}

animate();
```

which means that the `controls` might not be updated in sync with mouse movement. Changing the pattern to

```javascript
controls.addEventListener( 'change', render );
document.addEventListener( 'mousemove', controls.update.bind( controls ), false );
```

seems to solve the strange behavior I observed (`touchmove` is probably also needed, but I haven't tested that). However, I don't know why this only surfaces with some examples, only on some machines and not with the old `TrackballControls` (at least as far as I know).

**Comment by WestLangley** [comment]
@arose See if [this stackoverflow post](http://stackoverflow.com/questions/28746354/trackballcontrols-change-events) clarifies things.

If you are calling `update()` in the animation loop, there should be no need for adding event listeners. At least, that was the intent...

**Comment by arose** [comment]
> If you are calling update() in the animation loop, there should be no need for adding event listeners. At least, that was the intent...

Sure. Also, the damping effect does not work with my pattern.

I don't really understand what is going on here. All I do is observe (on different machines and browsers) that with the new `TrackballControls` a full horizontal mouse swipe gives me ~5° rotation in the "controls / trackball" example and ~180° rotation in the "interactive / cubes / gpu" example". With the old `TrackballControls` I always got a ~180° rotation. While investigating this I noticed that when I get the ~180° rotation there is always one `change` event from the `controls` for each `mousemove`, while with the ~5° rotation there are orphan `mousemove` events. That is what made me add the `mousemove` event listener. I then haven't look further.

**Pull request merged**
