### PR TITLE
Added missing type property

### PR DESCRIPTION
**Pull request by Mugen87**
For consistency reasons i've added the `type` property to all helpers and some objects.

See #6810

### CODE REVIEW

**Comment by Mugen87** [comment]
Is it okay to merge this 😇 ? Or is the `type` attribute no longer relevant?

**Comment by mrdoob** [comment]
I actually don't remember what its usage is now...

**Comment by Mugen87** [comment]
After a quick search in the repo, it looks like there is no read access to this property. Maybe we can consider to remove it from all objects.

**Comment by Mugen87** [comment]
Closing. I think a change here is not required now.

**Pull request closed without merging**
