### PR TITLE
[WIP] [WEBGL2] Transform feedback

### PR DESCRIPTION
**Pull request by fernandojsg**
This approach is a mix of the (1) and (2) approaches that I exposed on https://github.com/mrdoob/three.js/issues/14416 together with some ideas from the @takahirox branch on this feature too (huge thanks for that 🤘).

I believe the current implementation is easy enough to be used together with existing code and it don't modify many things on the core. Although some pieces on the `processTransformFeedback` on the `WebGLRenderer` need some refactoring and cleaning (eg: the .compile()).

I want to improve the example too. At least adding a UI to toggle between CPU and transform feedback, and to select the number of particles to paint (Using drawrange).
I know the example is uuuuugly, but I'm sure @mrdoob will help improving the aesthetics here :)

I didn't want to include a very complex shader example, as it would affect also the CPU code and target for this example is to focus on how to use this feature.

I did a simple comparison on my mbp between CPU and GPU:
image
As the example is just simulating simple gravity with some acceleration and velocity, you could expect that having way more complex simulations could increase the difference between CPU and GPU even more.

-- 

The usage is quite simple: 
- Create a `ShaderMaterial` including your `transformFeedbackVaryings`
- Create a `THREE.WebGLTransformFeedback` with that material and the geometry you want to transform.
- Call `transformFeedback.tick()` on your loop.

```js
var material = new THREE.RawShaderMaterial( {
	uniforms: {
		deltaTime: { value: 0.0 },
		time: { value: 0.0 }
	},
	vertexShader: document.getElementById( 'transformVertex' ).textContent.trim(),
	fragmentShader: document.getElementById( 'fragmentNop' ).textContent.trim(),
	transformFeedbackVaryings: {
		outPosition: 'position',
		outVelocity: 'velocity',
		outColor: 'color'
	}
} );

transformFeedback = new THREE.WebGLTransformFeedback( material, points, renderer );
...

/// Render loop
...
transformFeedback.tick();
...
```

### CODE REVIEW

**Comment by mrdoob** [comment]
For the time being, can you move the code from `processTransformFeedback` to the example?

I think we should split this in two steps. First have a example doing transform feedback, and build a easy to use API on top of it after.

**Comment by fernandojsg** [comment]
@mrdoob the problem is that you should expose many things from the renderer publicly. For example accessing the `properties` to query the material, compiling and initializing it, modifying state...
Are you ok with exposing them somehow?

**Comment by mjmdavis** [comment]
@mrdoob Is this still in limbo?

**Comment by luc4s** [comment]
> @mrdoob Is this still in limbo?

(also interested to know)

**Comment by marquizzo** [comment]
@luc4s he added this PR to the milestones for r100 so it's not still in limbo. https://github.com/mrdoob/three.js/milestone/13

**Comment by luc4s** [comment]
@marquizzo Ok, but it also was in r99, r98, r97 and r96 milestones :/

**Comment by MacSlow** [comment]
Oh, direct support for transform-feedback is coming to Three.JS?! That would be awesome!

Doing it the 'old-school' way (aka without Three.JS) was a drag.

I would port some past examples to a Three.JS version of transform-feedback support right away, giving the new API a test-run (https://macslow.org/js/webgl2-transform-feedback-morph.html https://macslow.org/js/webgl2-transform-feedback-logo-3.html)

@fernandojsg any repo I could try in the meantime to get my hands dirty early?

**Comment by Tyl68** [comment]
Hello,
I really would need this to handle collision between starphip and planet surface in a huge project I am working on.
Hope for r113 :)

**Comment by FarazzShaikh** [comment]
Is `THREE.WebGLTransformFeedback` in ThreeJS? I cannot find it in the documentation. Was this ever added?

**Comment by Mugen87** [comment]
@FarazzShaikh There is no support for it, yet.

**Comment by mrdoob** [comment]
@FarazzShaikh out of curiosity, what do you need it for?

**Comment by FarazzShaikh** [comment]
@mrdoob I am looking to simulate hydraulic erosion on the GPU, it requires multiple iterations with the output of the previous put into next iteration.

**Comment by Tyl68** [comment]
> @FarazzShaikh out of curiosity, what do you need it for?

@mrdoob Hi, I still need this feature for my project ( `https://tylart.pagesperso-orange.fr/wu/wu-app/index.html` ) named WeirdUniverse in which you are able to fly over an entire planet.
Currently the starship can go through the ground because I can't get back to my typescript code the ground deformations made in the shader.

**Comment by FarazzShaikh** [comment]
@Tyl68 transform feedback as far as I know is only for moving data from one shader to another or from the current shader to itself in the next iteration, it does not let you move data from GPU to CPU.

I too am looking for a way to have my surface deformation get back to my javascript, as if TF will take a while to implement I'll have to calculate on the CPU but I'll need my initial deformations.

**Comment by stopyransky** [comment]
Transform Feedback is useful for getting data from buffers to the JS app, as well as moving data from shader to shader. It creates new ways of working with animation and interactivity so I also would appreciate moving its priority up. Thank you!

**Comment by MajorSquirrelTVS** [comment]
Good evening, is this feature still in the pipe ? I think TransformFeedback is pretty useful and can be game changing for three.js' WebGL features !

**Comment by ligaofeng0901** [comment]
I hope this feature can be supported soon, it is a significant way to implement particle systems on gpu, like rain, snow simulation.

**Comment by LeviPesin** [comment]
@fernandojsg Can you please try the approach @Mugen87 described in https://github.com/mrdoob/three.js/pull/14503#issuecomment-950887344?

**Comment by Junior2Ran** [comment]
> I hope this feature can be supported soon, it is a significant way to implement particle systems on gpu, like rain, snow simulation.

I agree, this comment is very objective.

**Comment by sketchpunk** [comment]
https://codesandbox.io/s/threejs-transformfeedback-compute-q66kj8

I know trying to create an abstraction that can work for many use cases will be difficult for transform feedback. I propose starting small & exposing bits of threejs needed to do things with transform feedback. I recently have a usecase that requires running a compute shader that colorizes a point cloud against a collection of OBB that changes often.

All i needed to do was modify the built library to expose the attributes in WebGLRenderer like how properties work. Exposing attributes was enough to be able to get references to the GL buffers that I need for input & output of the transform feedback. The gist of what I'm doing is having a point cloud that's split into several meshes, then loop threw each mesh using its vertices for input & its color for output. This gave huge performance gains from doing something like this with only 200k points to now 4 million. Now the only hitch is that I need to run a modified version of 3js on production to make it happen.

So my proposal is how about a few transform feedback examples that uses raw webgl api calls & just adding the lil bits in 3js to expose the references needed. With enough examples or use cases, maybe it'll be easier to work out some kind of abstraction down the line.

**Comment by MacSlow** [comment]
> So my proposal is how about a few transform feedback examples that uses raw webgl api calls & just adding the lil bits in 3js to expose the references needed. With enough examples or use cases, maybe it'll be easier to work out some kind of abstraction down the line.

I gladly offer my https://macslow.org/js/webgl2-transform-feedback-morph.html example using multiple attributes to allow a point-cloud to morph from one configuration to another. It's all plain WebGL 2. It could use a bit of clean up, but should be basic enough to inject whatever threejs-transform-feedback-patch you have.

Want me to do it adapt it to your patched threejs version? :)

**Comment by sketchpunk** [comment]
> > So my proposal is how about a few transform feedback examples that uses raw webgl api calls & just adding the lil bits in 3js to expose the references needed. With enough examples or use cases, maybe it'll be easier to work out some kind of abstraction down the line.
> 
> I gladly offer my https://macslow.org/js/webgl2-transform-feedback-morph.html example using multiple attributes to allow a point-cloud to morph from one configuration to another. It's all plain WebGL 2. It could use a bit of clean up, but should be basic enough to inject whatever threejs-transform-feedback-patch you have.
> 
> Want me to do it adapt it to your patched threejs version? :)

Looks awesome.

If you want to try to port it over, the more the merrier. Codesandbox.io allows quick & easy forking of code. So you could fork it, do whatever changes you want then post the project back here. Maybe it'll help get things rolling a lil bit.

Thanks !

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/14416#issuecomment-2160471897.

**Pull request closed without merging**
