### PR TITLE
Blender: Index buffer

### PR DESCRIPTION
**Pull request by tschw**

### CODE REVIEW

**Comment by mrdoob** [comment]
Moar thanks!

**Comment by mrdoob** [comment]
Seems like this caused some breakage... Fixed in https://github.com/mrdoob/three.js/commit/a8cc2a22ac6cfa68eca6aa812c01e4bcbbe3fcf1. Refactored in https://github.com/mrdoob/three.js/commit/767e68bcaecd586fb6346646a696d7adc03f9af2.

**Comment by tschw** [comment]
Great you're getting on top of that code and fixed it!

Looks like the same code as in a4e892b... Also has to happen in another place, I guess? Clueless now, more than a year later - and not enough time to dig into it, really. 

Technically would've been my previous PR that added indexed exports in the first place, then. I wouldn't have known, and that PR had a review, so should've been noticed by someone who had 😇

**Comment by mrdoob** [comment]
> Also has to happen in another place, I guess?

Yeah, seems like there are 2 code paths, one when exporting a single geometry and another when exporting a scene. I've unified it a bit in the refactor.

**Pull request merged**
