### PR TITLE
Loader: Introduce setWithCredentials().

### PR DESCRIPTION
**Pull request by amosbyon1224**
Related to #20350 

`STLLoader` was instantiating a `FileLoader` but never sets `withCredentials`.

I've noticed that a lot of the other loaders in `/examples` have a similar issue. I can go through them and update them so that they all call `setWithCredentials` on their `FileLoader`s if you're happy with this change and open a new PR.

### CODE REVIEW

**Comment by Mugen87** [comment]
I'm afraid this PR mixes some concepts of the engine. `crossOrigin` is only intended for images so far. It is not intended for controlling the invocation of `setWithCredentials()`.

**Comment by amosbyon1224** [comment]
I was following how `GLTFLoader` was setting its internal `FileLoader`:
https://github.com/mrdoob/three.js/blob/4c756468bda459ffd43e6f2bd84c507b72ce5ee3/examples/jsm/loaders/GLTFLoader.js#L150-L160

Right now I am able to load a .glb file if it exists in another origin but not a .stl file.

If this isn't the correct way, do you have any suggestions on how to be able to load a .stl file that exists in another origin?

**Comment by Mugen87** [comment]
Oh, I was not aware that `GLTFLoader` uses this pattern. 

I though it might be better if `setWithCredentials()` and `.withCredentials` are added to `Loader`. It's then a one liner in all loaders.

**Comment by amosbyon1224** [comment]
I've bubbled up `withCredentials` and `setWithCredentials` from `FileLoader` up to `Loader` and updated `STLLoader`.

I'm noticing that another loader had a similar pattern to the `GLTFLoader` as well:

https://github.com/mrdoob/three.js/blob/5ae634e1a4e3871415e418d025618f3f4f540747/examples/jsm/loaders/DRACOLoader.js#L94-L98

Should I go through and update `DRACOLoader` and `GTLFLoader` in this PR as well?

Should I also go through all of the example loaders that internally use `FileLoader` and add
```
loader.setWithCredentials( this.withCredentials );
```

in this PR as well?

**Comment by Mugen87** [comment]
This is exactly the change I had in mind!

> Should I also go through all of the example loaders that internally use FileLoader and add

Yes, please. Then we can update everything in one go.

**Comment by amosbyon1224** [comment]
Done!

Hopefully I didn't miss any Loaders but please let me know if there's something else you'd like me to change!

I'll open a separate PR with Doc updates

**Comment by Mugen87** [comment]
It is still necessary to update the TS declaration files. Meaning the definitions from `FileLoader` needs to be moved to `Loader`.

https://github.com/mrdoob/three.js/blob/7830fe3423d042b3735498adf2e1c49d0631442c/src/loaders/FileLoader.d.ts#L10
https://github.com/mrdoob/three.js/blob/7830fe3423d042b3735498adf2e1c49d0631442c/src/loaders/FileLoader.d.ts#L20

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Very nice! Thanks!

**Pull request merged**
