### PR TITLE
Add Dependabot configuration

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: -

**Description**

Currently Dependabot does not make updates for (dev) dependencies in the root's package.json, with this PR it should.

### CODE REVIEW

**Comment by Mugen87** [comment]
> Currently Dependabot does not make updates for (dev) dependencies in the root's package.json

I wonder why this happens 🤔 . Normally, Dependabot should verify the root's package.json by default.

**Comment by OndrejSpanel** [comment]
> Normally, Dependabot should verify the root's package.json by default.

It has to be enabled somehow - it is usually enabled for new repositories, but for older ones someone needs to do it in https://github.com/mrdoob/three.js/settings/security_analysis.

**Comment by Mugen87** [comment]
> I think it has to be enabled

Strange. In my other repos, Dependabot worked by default without further settings.

**Comment by OndrejSpanel** [comment]
Well, maybe it works. I have to admin I do not know how Security tab looks in repositories where I am not admin. Do and of you admins / owners here see Dependabots in https://github.com/mrdoob/three.js/security?

I remember I had to enable it in my repos.

**Comment by Mugen87** [comment]
> Do any of you admins / owners here see Dependabots in https://github.com/mrdoob/three.js/security?

As a collaborator I don't see the Dependabot entry in the table. In my other repos, it looks like so:

Bildschirmfoto 2023-01-27 um 10 34 30

**Comment by mrdoob** [comment]
Same.

**Comment by epreston** [comment]
Dependabot security updates and dependabot updates are different.  

Security updates run off scanning, that just happens if enabled. The automatic dependency checks and pull requests to update dependencies (as in the chore of keeping things up to date) need a config like one one suggested.  You configure what kind of PR's you want it to make and frequency.

This PR needs an update with package.json being removed from "test".

**Comment by LeviPesin** [comment]
> This PR needs an update with package.json being removed from "test".

Done.

**Comment by LeviPesin** [comment]
@mrdoob @Mugen87 @epreston I think we should merge this PR because it is better to have a Dependabot configuration in any case.

**Comment by Mugen87** [comment]
>> Do any of you admins / owners here see Dependabots in https://github.com/mrdoob/three.js/security?

> As a collaborator I don't see the Dependabot entry in the table.

Strange, now I see the Dependabot entry in the Security overview. It is already enabled and alert list is currently empty.

Bildschirm­foto 2023-02-09 um 19 18 21

**Comment by LeviPesin** [comment]
@mrdoob @Mugen87 I again suggest that we should merge this PR -- without it Dependabot currently doesn't see that some dependencies are outdated.

**Comment by LeviPesin** [comment]
@mrdoob @Mugen87 Is there anything preventing the merge of this PR? Without it Dependabot doesn't work.

**Comment by epreston** [comment]
@LeviPesin try changing it from daily to weekly checks.  that might be what's holding it back.  You might find it's rather noisy sometimes.

For me, I'm switching all my projects to monthly.  That way this only runs if "forgot" to do my chores and updates.  Like a safety net if my focus has been on other things for a while.

**Comment by LeviPesin** [comment]
@mrdoob @Mugen87 Should the checks be daily or weekly?

**Comment by mrdoob** [comment]
Lets see how things go with daily.

**Pull request merged**
