### PR TITLE
GLTFExporter: Fix JSON chunk padding issue.

### PR DESCRIPTION
**Pull request by takahirox**
This PR fixes padding logic in `stringToArrayBuffer()` of `GLTFExporter` for multi-byte strings. The current logic doesn't take account of the possibility that `.name` can be multi-byte strings.

### CODE REVIEW

**Comment by donmccurdy** [comment]
We only use this method once — could we just call `getPaddedArrayBuffer()` on the result? Conceptually converting a string to an arraybuffer does not necessarily require padding.

**Comment by takahirox** [comment]
So why does even the current `stringToArrayBuffer()` have `padded` option?

**Comment by donmccurdy** [comment]
😅 Oops. Let's remove that and just do padding when we're writing a bufferView or GLB chunk.

**Comment by takahirox** [comment]
OK, I'll update,

**Comment by fernandojsg** [comment]
Yeah you're right :D I guess it was some duplicated use somewhere on the code that didn't need padding and it was removed after all :)

**Comment by takahirox** [comment]
Probably we misunderstood each other.

`stringToArrayBuffer()` is used once for converting from JSON string to ArrayBuffer for JSON chunk. And we can't use `getPaddedArrayBuffer()` for the JSON chunk array buffer of JSON because

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#structured-json-content

> This chunk must be padded with trailing Space chars (0x20) to satisfy alignment requirements.

So padding in `stringToArrayBuffer()` is good.  Adding an padding value (0 or 0x20) option to `getPaddedArrayBuffer()` would be another option.

**Comment by donmccurdy** [comment]
Hm I see what you mean :/ ...hoping we can still solve this with a smaller change to `getPaddedArrayBuffer` though, how about this?

```js
function getPaddedArrayBuffer( arrayBuffer, paddingByte ) {

        paddingByte = paddingByte || 0;
	var paddedLength = getPaddedBufferSize( arrayBuffer.byteLength );

	if (paddedLength !== arrayBuffer.byteLength ) {

		var paddedBuffer = new ArrayBuffer( paddedLength );
		new Uint8Array( paddedBuffer )
                  .fill( paddingByte, -4 )
                  .set( new Uint8Array( arrayBuffer ) );
		return paddedBuffer;

	}

	return arrayBuffer;

}
```

**Comment by takahirox** [comment]
That's the one I mentioned

> Adding an padding value (0 or 0x20) option to getPaddedArrayBuffer() would be another option.

**Comment by takahirox** [comment]
Came to think adding that option would be better. We don't need two padding functions. I'll update.

**Comment by takahirox** [comment]
Updated.

- Added `paddingByte` option to `getPaddedArrayBuffer()`
- Removed `padded` option from `stringToArrayBuffer()`
- Cleaned up those two functions a bit


@donmccurdy 

    new Uint8Array( paddedBuffer )
        .set( [ paddingByte, paddingByte, paddingByte ], paddedLength - 3 )
        .set( new Uint8Array( arrayBuffer ) );

Just in case, `.set` doesn't return `this`.

**Review by donmccurdy — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
