### PR TITLE
Ability to set custom Gamma factors and clean up glsl code

### PR DESCRIPTION
**Pull request by bhouston**
This builds upon the [common.glsl PR here](https://github.com/mrdoob/three.js/pull/5785).  This implements the idea expressed [here](https://github.com/mrdoob/three.js/pull/5785#issuecomment-68302484) and subsequently endorsed by @WestLangley.

This add the variable `WebGLRenderer.gammaFactor` which is correctly propagated to shaders as the define `GAMMA_FACTOR`.  I have moved the conditional application of gamma correction to two helper functions within common.glsl `inputToLinear` and `linearToOutput`, instead of having it spread across a lot of shader files.

I have also changed both `THREE.Color.copyLinearToGamma()` and `THREE.Color.copyGammaToLinear()` to take the gamma exponential as an optional parameter.

I have made the code backwards compatible by defaulting the gamma correction factor to 2.0, which matches the approximation used by the square()/sqrt() methods.  (Although a better default would be 2.2, which matches the sRGB standard: https://en.wikipedia.org/wiki/SRGB -- pointed out by @WestLangley.)

Lastly, I have added a "gammaFactor" control to the webgl_shader_physical.html example, but I need to somehow force the shaders to recompile -- if someone could give me a hint on the easy way to do that, it would be greatly appreciated.

### CODE REVIEW

**Comment by mrdoob** [comment]
Ok. This is next!
Are we all good on this one?

**Comment by WestLangley** [comment]
Looking at the diffs, it is hard to tell, but it appears I was in agreement at one point, so go ahead. : - )

**Comment by mrdoob** [comment]
Done!

@WestLangley if you want to double check, these are cleaner diffs: c0478beba3c56321d1d86e116660f5f196dabe4b bc0ef0dded7c6da217911ef2f8fce9882a633bd2

**Comment by mrdoob** [comment]
Well, I'm noticing a regression...

Before:
screen shot 2015-01-24 at 11 22 56 pm

After:
screen shot 2015-01-24 at 11 23 36 pm

**Comment by WestLangley** [comment]
> @WestLangley if you want to double check, these are cleaner diffs: c0478be bc0ef0d

Diffs look OK to me.

> Well, I'm noticing a regression...

That is because `renderer.gammaInput` is no longer supported. All colors are assumed to be in linear space -- except for certain textures. (See https://github.com/mrdoob/three.js/issues/5838#issuecomment-68454839. ) The new code can be made to render the same as the old code by converting to linear space ("squaring") the material colors, specular colors, light colors, and light intensities specified in the demo.

It was not clear to me that colors should, in fact, be assumed to be in linear space. Originally, I suggested they should be in gamma space. ( See above link. ) I do not have an opinion one way or the other on this issue.

If you like, I'll modify the demo.

/ping @bhouston

**Comment by mrdoob** [comment]
> If you like, I'll modify the demo.

That could be nice. That way I can apply the changes to other examples I've noticed that changed.

**Comment by WestLangley** [comment]
@bhouston is going to have to look at this... The code changes are not yet complete.

I can duplicate r.70 rendering by changing material colors, light colors, and light intensities like so:

1. light intensities are squared.
2. light colors and material colors are mapped to linear space.

To figure out how to change the colors in the demo to prevent a regression, I did this: 

    color.convertGammaToLinear();
    console.log( '0x' + color.getHexString() );

With these changes, there is no regression.

However, it remains to remove from the demo the following line, which, according to previous discussions, should longer be needed:

    renderer.gammaInput = true;

We can't remove it yet, because it still has an effect on

1. shadow darkness
2. texture color

@bhouston I would strongly suggest we get the gamma-related changes working as desired before we embark on refactoring the shader code. This includes `gammaOutput`.

**Comment by mrdoob** [comment]
Agreed!

**Pull request merged**
