### PR TITLE
Docs: Don't fire hashchange event when typing in filter query

### PR DESCRIPTION
**Pull request by meshulam**
This PR fixes a bug in the docs site where the filter bar can lose focus as you're typing in it. It also suppresses the annoying redraw flash on each keypress.

To reproduce the bug:
*  Load a docs page that links to an anchor within the page, e.g. [PerspectiveCamera.aspect](https://threejs.org/docs/index.html#Reference/Cameras/PerspectiveCamera.aspect).
* Type into the page filter input. Every keypress annoyingly shifts focus back to the anchor link.

This is an issue in Mac Chrome but seems to not affect Safari.

### CODE REVIEW

**Comment by mrdoob** [comment]
@spite thoughts?

**Comment by spite** [comment]
Yes, something's changed lately in Chrome that triggers that behaviour. It's annoying as hell.

I like the hashchange feature, it makes sharing relevant searches pretty easy.

If i understand the PR correctly, may be I'd try, instead of removing the event, trying clearing the hash: since the user is going to be searching, the hash is not valid any more.

**Comment by meshulam** [comment]
Maybe I misunderstand, but updateFilter still gets called when typing in the search field. That means the search query still updates in the address bar with this fix.

The Chrome-specific behavior seems to be that it fires hashchange events when changing the location hash and then immediately changing it back. All this change really does is ensures the same hash gets assigned when calling replaceState, rather than appending it afterwards.

**Comment by spite** [comment]
Just checked out the code to try it. Looks good to me! 👌🏼

**Comment by mrdoob** [comment]
@meshulam do you mind implementing this in `examples/index.html` too?

**Comment by meshulam** [comment]
@mrdoob good call, updated. Now the address bar doesn't flicker when viewing an example and typing in the filter box.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
