### PR TITLE
ColladaLoader2 load external file references

### PR DESCRIPTION
**Pull request by glumb**
Just a note upfront: I'm not done with the implementation, yet. This pr is meant to be a base for discussion.

Collada files can reference parts of other files in the form of instance nodes. E.g. `<instance_geometry url="#cube"/>` or  `<instance_node url="cube.dae#red_cube"/>` 
I started implementing a mechanism to resolve node references pointing to internal or external nodes.

I split the `parse` function into `_parse` (which populates the libraries) and `_build`. `_build` constructs the scene based on the parsed data.

In the `_build` method a reference Node is parsed, if the url points to an external node, a request is made, the file parsed and the specific node is included. The concept is shown in the diagram below.

bildschirmfoto 2016-05-25 um 15 33 00

I thought that the best position to make this request was in the `_build` function. Since `_build` is no longer synchronous, induced by the async nature of an xhr, I had to add some callbacks here and there.
This does not change the api of `build` though, since this method was already async.
So the basic concept is to call `_parseAndBuild` with `text, baseUrl, fileName`. This returns an object containing methods such ad `getMainVisualScene, getNode`. This allows for getting either the complete scene, or a specific Node or Geometry.

**Thoughts/Ideas**
- How to handle the unit and up_axis on referenced files correctly. The Collada reference is not 100% clear to me on this point.
- I added some JSDOC to the new functions. I can add doc to every function if wanted.
- Make the "loading references" behavior configurable using the `options` object.
- _parse and _build can actually be in one function since they are only called in conjunction, but I like the concept of separation of concerns
- I also added the ColladaNodeId to the ThreejsNodes userData to be able to reference the nodes within the scene

### CODE REVIEW

**Comment by mrdoob** [comment]
Did you use the `master` branch as base? Seems like it has conflicts...

**Comment by glumb** [comment]
I used dev. I've seen the conflicts message, too. Not sure whats the issue there.

**Comment by mrdoob** [comment]
> Maybe cause my first commit `removed unused parameters` has already been merged into dev.

Ah, probably yeah... Better to do a different branch.

Anyway, I'm not a big fan of doing `_method`s. It's very easy to end up with something very messy if we go that route. Can you think of a way to get this to work while keeping the current methods? Couldn't we instantiate a new `ColladaLoader2` internally when a reference like that is found?

**Comment by glumb** [comment]
Thats definitely possible. Ill work on it.

**Comment by glumb** [comment]
Ok I screwed up rebasing that.

**Pull request closed without merging**
