### PR TITLE
Examples: Remove FPS workaround in webxr_vr_video.

### LINKED ISSUE #13379: VideoTexture updating at 60-90fps
As reported in https://github.com/mrdoob/three.js/pull/12763#issuecomment-364320372, we're currently updating the video texture at 60 (or 90 in VR) fps.

Ideally we'll only update the texture on the GPU in sync with the video framerate (usually 25-30). Unfortunately the web platform does not provide any API for figuring out the framerate of a video so something like `videoTexture.frameRate = 25` is needed.

It seemed easy enough so I tried to implement this (#13304) but I hit some browser bugs and I had to revert (#13305).

It'll be good to investigate this a bit more and report bugs to browsers if needed.

### LINKED ISSUE #19880: Video examples get errors
##### Description of the problem

It seems like most of the samples with video get errors at the beginning, at least when run locally (which means there's a timing issue?)

```
three.module.js:15 WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty
```

I don't know what the correct way to use video in WebGL is honestly and I'm not sure anyone actually does. It seems like every 2-3 years browsers break it again. Checking the WebGL conformance tests, [they wait for `video.currentTime` to be > 0 before calling `texImage2D`](https://github.com/KhronosGroup/WebGL/blob/16b6599302bc00728f12bcb8de2b519e2f1d5b0f/sdk/tests/js/webgl-test-utils.js#L3129) but I suspect that's just some voodoo that made the tests run and not the official way you're supposed to do it. Though maybe if it's good enough for the tests?

I don't think you'll see this on the website as it seems to be related to timing. If I use `servez` or `http-server` to serve the three.js folder and go to `http://localhost:8080/examples` and run `webgl_video_panorama_equirectangular.html` then I see the errors

ScreenFlow

Note: It's Chromium only that has the issue but checked 2 macs and a windows and they all get the errors.

##### Three.js version

- [X] Dev

##### Browser

- [ ] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Safari

##### OS

- [x] All of them
- [x] Windows
- [x] macOS
- [?] Linux
- [?] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #19880.
Fixed #13379.

Thanks to `requestVideoFrameCallback()`, the workaround from #13470 should not be necessary anymore.

This might affect the example in Firefox Reality however Chromium based browsers (like Oculus Browser) should already support it. Testing...

https://raw.githack.com/Mugen87/three.js/95d79137f9e281c54ba637359c8e132ca8c011ca/examples/webxr_vr_video.html

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev32/examples/webxr_vr_video.html

**Comment by Mugen87** [comment]
Um, it seems there is an issue with Oculus Browser (version 10.2.0.6.111....). `requestVideoFrameCallback()` is in general supported and called when you view the example in non-VR mode. But when presenting, the callback is not executed anymore. Maybe a bug?

**Comment by Mugen87** [comment]
Just for the record: Firefox Reality does not yet support `requestVideoFrameCallback()`.

**Comment by Mugen87** [comment]
> Um, it seems there is an issue with Oculus Browser (version 10.2.0.6.111....). requestVideoFrameCallback() is in general supported and called when you view the example in non-VR mode. But when presenting, the callback is not executed anymore.

Oh, it seems the same is true for Chrome on Android. I've tested with a Pixel 1 and Daydream and the behavior is the same.

**Comment by cabanier** [comment]
I logged a bug on this last week: https://bugs.chromium.org/p/chromium/issues/detail?id=1107578
Hit the star button so the bug gets more traction.

I agree that this feature would be great for WebXR because it allows you to only pick up the video frames that changed.

**Comment by Mugen87** [comment]
> Hit the star button so the bug gets more traction.

Done! 😊

**Comment by usefulthink** [comment]
Any chance to create a workaround so we can use VideoTexture in webxr-projects? Maybe add a flag `forceUpdate` or something to the `VideoTexture.update()` method that is set by the renderer when a xr-session is running?

**Comment by cabanier** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1107578 was submitted. 
Starting in Chrome 87, `requestVideoFrameCallback` should work as expected.

**Comment by Mugen87** [comment]
I'll make the PR as "Ready for Review" when Chrome 87 lands in production.

**Comment by Mugen87** [comment]
Tested the updated example today on a Quest with latest Oculus Browser (based on Chromium 87.0.4280.66) and it works fine now. Changing the PR status to `Ready for review`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
