### PR TITLE
Examples: Fix some warnings

### PR DESCRIPTION
**Pull request by Mugen87**
see #15468

Fixed warnings in `webgl_loader_ctm_materials`, `webgl_panorama_dualfisheye`, `webgl_postprocessing_masking`, `webgl_shaders_ocean2` and `webgl_materials_bumpmap_skin`.

### CODE REVIEW

**Comment by WestLangley** [comment]
Can you explain why you removed shadow support from simple skin shader?

	//	Simple skin shader
	//		- fog (use with "fog: true" material option)
	//		- shadow maps

**Comment by Mugen87** [comment]
Oh, I've missed that comment...

Well, I can't see that the shader code respects shadows in its lighting equations.

**Comment by Mugen87** [comment]
I'm not sure but it seems this commit removed shadow support from the shader:

https://github.com/mrdoob/three.js/commit/8eaf494a462762562dcc4f862debb6df26a703dc#diff-a1806af1528eb3e8af7952cfb105a597

What do you think?

**Comment by WestLangley** [comment]
If @mrdoob wants the skin shader to support shadows, we should fix it. If he doesn't care, then your removal of shadow support from the shader is fine.

**Comment by Mugen87** [comment]
> then your removal of shadow support from the shader is fine.

Well, I actually did not remove shadow support. This was done earlier, probably unintentionally.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
