### PR TITLE
Fix test error "No tests matched for filter..."

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: Fixes issue reported in https://github.com/mrdoob/three.js/issues/23324#issuecomment-1020963753

**Description**

Fix this new issue with the tests:

image

The `tests/` folder wasn't able to resolve three, it is fixed by adding a dependency pointing to itself.

After this PR, run:
- `npm i`
- `npm run test-unit-examples`

The reported error shouldn't be there anymore.

### CODE REVIEW

**Comment by Mugen87** [comment]
Is it also possible to add the `three` dependency to `test/package.json` instead?

**Comment by marcofugaro** [comment]
@Mugen87 tested it and it doesn't work.
The `examples/jsm` files resolve to the root `package.json`, and the `'three'` import can't be resolved automatically if we're not under npm.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
We might want to consider to remove the `test-unit-examples` script and the entire `test/example` directory. Considering the E2E tests, I don't think they add much value right now. Maybe better to focus unit tests on the core.

**Comment by mrdoob** [comment]
> We might want to consider to remove the `test-unit-examples` script and the entire `test/example` directory. Considering the E2E tests, I don't think these few tests add much value right now. Maybe better to focus unit tests on the core.

👍

**Comment by marcofugaro** [comment]
Cool, this PR is unnecessary then if #23352 is merged

**Comment by takahirox** [comment]
> We might want to consider to remove the test-unit-examples script and the entire test/example directory. Considering the E2E tests, I don't think these few tests add much value right now. Maybe better to focus unit tests on the core.

Hm, I have mix feelings on it.

* E2E tests don't cover all the cases, eg: exporter. And (util) functions accompanied with some calculations may be more fit to unit tests over than E2E tests, eg: BufferGeometryUtils?
* I think https://threejs.org/examples is more like show cases rather than testing. No guarantee that all example functions are used there
* Some modules in examples are essential and often as the ones in core, eg: GLTFLoader, GLTFExporter
* I can't deny that the current example test cases are not many enough. Ideally we should encourage to write more tests for robustness rather than removing the tests
* On the other hand I know our human resource is limited. It might be acceptable to lower the priority of unit tests for examples (and remove them)...

No clear opnion yet, but I feel we may keep at least some examples tests for which the modules are essential and which are hard to test with E2E (eg: GLTFExporter) and write more tests for them.

**Comment by Mugen87** [comment]
This repository has a problem: It just wants to do too many things at once. Documentation, manual, unit tests for core and examples,  E2E tests, editor...

All this stuff introduces a significant complexity that gets more and more problematic. It slows our development process down because we have to fix so many things. That became clear again in this release. It should be clear that we have to make compromises so we can easier move on with new features.

Of course it would be nice to have unit tests for the examples. However, it is strange to worry about examples/addons if the test coverage of the core is comparably low. So I suggest to fix that first.

**Pull request closed without merging**
