### PR TITLE
Instancing reset

### PR DESCRIPTION
**Pull request by benaadams**

### CODE REVIEW

**Comment by benaadams** [comment]
Gah; that was poor. Yes should be `=`

**Comment by benaadams** [comment]
The bane of premature optimization...

**Comment by mrdoob** [comment]
I think I would separate it though...

```javascript
state.setAttributeDivisor( programAttribute, data.meshPerAttribute, extension );
```

**Comment by benaadams** [comment]
Issue is ```enableAttribute``` wouldn't have the info; so would need to reset to 0 for every attribute as per #7225; or every ```enableAttribute``` would need to be always later followed by a ```setAttributeDivisor``` call including ```renderBufferImmediate```, ```LensFlarePlugin``` and ```SpritePlugin```

**Comment by benaadams** [comment]
Could maybe make a ```state.enableAttribute``` and ```state.enableAttributeWithDivisor``` (better name); that have differing param counts?

**Comment by mrdoob** [comment]
> Could maybe make a ```state.enableAttribute``` and ```state.enableAttributeWithDivisor``` (better name); that have differing param counts?

That sounds good!

**Comment by benaadams** [comment]
Something more like that? (not tested)

**Comment by emnh** [comment]
Tested. Works.

**Comment by benaadams** [comment]
:shipit:

Is it an issue this is wrong in v72? Want a PR to master?

**Comment by mrdoob** [comment]
I think it's fine... r72 already had quite a bit of post-release fixes...

**Comment by benaadams** [comment]
OK, will leave master. Will likely cause a huge number of future merge conflicts if I tried - don't want you cursing me come r73 :stuck_out_tongue_winking_eye:

**Comment by mrdoob** [comment]
I still consider all this stuff experimental and unstable API so it's kind of expected 😊

**Comment by benaadams** [comment]
As an aside: using instancing for 1x1 plane billboards will be likely slower than 4x duplication (position alone) as the gpu needs needs to process more data in the shader (position + offset); with larger models then instancing becomes more suitable as the CPU->GPU bandwidth becomes the bottleneck rather than the shader. I think the tradeoff starts happening around 100 vertices per model - though the api for updating is simpler for instancing - but that can be hidden by library.

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
