### PR TITLE
Skip non-POT texture fallback on WebGL2

### LINKED ISSUE #15554: [WebGL2] NPOT Texture should not fallback in webgl2
##### Description of the problem

These fallback logic should be skipped in webgl2:
````javascript

// webgl2 skip this
_gl.texParameteri( textureType, _gl.TEXTURE_WRAP_S, _gl.CLAMP_TO_EDGE );
_gl.texParameteri( textureType, _gl.TEXTURE_WRAP_T, _gl.CLAMP_TO_EDGE );
_gl.texParameteri( textureType, _gl.TEXTURE_MAG_FILTER, filterFallback( texture.magFilter ) );
_gl.texParameteri( textureType, _gl.TEXTURE_MIN_FILTER, filterFallback( texture.minFilter ) );

// isPowerOfTwo should be (isPowerOfTwo || webgl2)
function textureNeedsGenerateMipmaps( texture, isPowerOfTwo ) {
	return texture.generateMipmaps && isPowerOfTwo &&
			texture.minFilter !== NearestFilter && texture.minFilter !== LinearFilter;
}
````

##### Three.js version

- [x ] Dev
- [ ] r100
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by takahirox**
This PR skips non-POT texture parameter setting fallback on WebGL2.

Fixes #15554

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
And thanks for the ping too, these PR sure get lost quickly... 😔

**Comment by takahirox** [comment]
No worry! There're so many issues and PRs. I know it's very hard to catch up everything. I often miss too hehe. And sending reminder is easy and doesn't hurt anything. Also I think we should help you more.

**Comment by Tibus** [comment]
Hi. 
Could maybe add this feature in webgl2 supported features on the website as it’s a key feature of webgl2 and I tought it was not yet supported in threejs ? ;D

**Comment by Mugen87** [comment]
@Tibus I hope #16627 makes this topic more clear.

**Comment by Tibus** [comment]
Perfect ;D

**Pull request merged**
