### PR TITLE
.github folder enhancements [remake]

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
Remake of #19596

unfortunately I could not find the branch the previous work was on.
This PR is simply a copy paste of the old PR's changes.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hopefully this is the end of the `Help (please use the forum)` label 🤞

**Comment by DefinitelyMaybe** [comment]
this is my hope too

**Comment by DefinitelyMaybe** [comment]
we may need to change the order of things and the wording to further aid this but I'd like to see how it goes in the mean time

**Comment by mrdoob** [comment]
> we may need to change the order of things and the wording to further aid this but I'd like to see how it goes in the mean time

I did that already 😇

**Pull request merged**
