### PR TITLE
Support transformed pivots in FBXLoader

### PR DESCRIPTION
**Pull request by looeee**
Fix for #11895

### CODE REVIEW

**Comment by looeee** [comment]
Are there any issues with this that need to be investigated further? This is a critical bug in the FBXLoader and needs to be fixed ASAP. 

I've been running this change locally for the last month and have loaded probably a hundred or so FBX model in that time, and have not found that it caused issues with any of them. 

However if there are any particular cases that need to investigated further I will be happy to look into them.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Woops. Do you mind resolving conflicts?

**Comment by looeee** [comment]
Remaining conflicts are because of the code style being incorrect in #12276 
I ran eslint on the file before committing, which fixes nearly everything (except for comments it seems).

Rather than me tediously going through and making undoing all the automatic eslint fixes, is it possible to just merge this, ignoring conflicts? 

Or is there some way to just mark my version of the file as the correct one in git?

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
