### PR TITLE
Revert "Force context loss in renderer.dispose"

### PR DESCRIPTION
**Pull request by mrdoob**
Reverts mrdoob/three.js#17588

### CODE REVIEW

**Comment by kenrussell** [comment]
Out of curiosity @mrdoob what use cases did this break, so we can watch out for them going forward?

**Comment by mrdoob** [comment]
It was not related to WebGL itself...

The Editor has a second renderer used as player and I was disposing memory between runs. The new line in `dispose()` also removed the context so users started to report that they couldn't play twice.

https://github.com/mrdoob/three.js/commit/d540bbf7ddeec011ba5bbf09691e8cf542be3a05

**Comment by weihexin** [comment]
多加点中文, 谢谢

**Comment by weihexin** [comment]
three.js 教程 参考多加点中文

**Pull request merged**
