### PR TITLE
Depth of Field Example: Apply dof in linear space

### PR DESCRIPTION
**Pull request by WestLangley**
Apply DOF in linear space, prior to tone mapping.

### CODE REVIEW

**Comment by WestLangley** [comment]
Actually, there is no tone mapping in this example. But there could be.

**Comment by Mugen87** [comment]
This change has no effect since if tone mapping would be configured,  `PostProcessing` would already apply it after DOF.

**Comment by WestLangley** [comment]
Well, that explains why it does not look different. :-)

1. So, if `outputColorTransform` is `true`, to which node(s) is `.renderOutput()` applied by default.
2. Same question - but when `mrt` is used.

**Comment by Mugen87** [comment]
`PostProcessing` applies tone mapping and color space conversion after the last pass (at the end of the pass chain). If that is too late (like in the FXAA or LUT example), you can use `renderOutput()` to prepone this step.

**Comment by WestLangley** [comment]
What about `mrt`?

**Comment by Mugen87** [comment]
Um, I'm not sure what you mean. You use the beauty output of a MRT setup like an ordinary pass. 

If things are still unclear, it would help to share a concrete use case ideally with a fiddle that shows what you are want to do.

**Comment by WestLangley** [comment]
It might take a series of questions... :-)

In the following example, if `outputColorTransform` were set to `true`, and `renderOutput()` was removed, then `renderOutput()` would be magically applied by the renderer to which node?

```js
postProcessing = new THREE.PostProcessing( renderer );
postProcessing.outputColorTransform = false;

const scenePass = pass( scene, camera );

const outputPass = scenePass.getTextureNode();

const bloomPass = outputPass.bloom();

postProcessing.outputNode = outputPass.add( bloomPass ).renderOutput();
```

**Comment by WestLangley** [comment]
I'll try rephrasing my question:

Why is `outputColorTransform` set to `false` in this example?

https://github.com/mrdoob/three.js/blob/7bc2d4a61d383179a9bd9dc63436698e7f86e200/examples/webgpu_postprocessing_bloom_emissive.html#L85-L98

**Comment by Mugen87** [comment]
I see now that the changes in #29127 are not correct. The PR needs to be reverted.

**Comment by Mugen87** [comment]
> Why is outputColorTransform set to false in this example?

This code is not required. `webgpu_postprocessing_bloom_emissive` should be updated and the assignment to `outputColorTransform` should be removed.

**Comment by WestLangley** [comment]
>PostProcessing applies tone mapping and color space conversion after the last pass (at the end of the pass chain)

@Mugen87 How is the end of the pass chain identified?

**Comment by Mugen87** [comment]
The `PostProcessing` modules takes care about this:

https://github.com/mrdoob/three.js/blob/c6d4b83c11e573662347f017d6a057b431179b89/src/renderers/common/PostProcessing.js#L55

`renderOutput()` is applied to the final node which is assigned to `outputNode` (which is essentially the last pass in a chain of passes).

**Comment by WestLangley** [comment]
Would it be accurate to simply say `renderOutput()` is applied to `outputNode`?

**Comment by Mugen87** [comment]
If `outputColorTransform` is set to `true`, yes.

**Pull request closed without merging**
