### PR TITLE
Call onBeforeRender and onAfterRender callbacks in CSS2DRenderer

### PR DESCRIPTION
**Pull request by juliendargelos**

### CODE REVIEW

**Comment by Mugen87** [comment]
Please edit the `js` version of `CSS2DRenderer`. `jsm` files are (mostly) auto-generated.

**Comment by juliendargelos** [comment]
My bad

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by elalish** [comment]
I'm getting a TS error from this:
```node_modules/three/examples/jsm/renderers/CSS2DRenderer.d.ts:12:2 - error TS2416: Property 'onBeforeRender' in type 'CSS2DObject' is not assignable to the same property in base type 'Object3D'.
  Type '(renderer: CSS2DRenderer, scene: Scene, camera: Camera) => void' is not assignable to type '(renderer: WebGLRenderer, scene: Scene, camera: Camera, geometry: Geometry | BufferGeometry, material: Material, group: Group) => void'.
    Types of parameters 'renderer' and 'renderer' are incompatible.
      Type 'WebGLRenderer' is not assignable to type 'CSS2DRenderer'.
        Types of property 'getSize' are incompatible.
          Type '(target: Vector2) => Vector2' is not assignable to type '() => { width: number; height: number; }'.

12  onBeforeRender: (renderer: CSS2DRenderer, scene: Scene, camera: Camera) => void;
```

**Comment by elalish** [comment]
Ping @juliendargelos @Mugen87

**Comment by juliendargelos** [comment]
Yes this is not surprising, sorry. The right way to do it would be to add a generic to `Object3D` with default type `WebGLRenderer` and set it to either `CSS2DRenderer` or `CSS3DRenderer` when extending `Object3D`.

**Comment by Mugen87** [comment]
@juliendargelos Can you do a PR with this change?

**Comment by juliendargelos** [comment]
I'm on it

**Comment by elalish** [comment]
@juliendargelos Is there a way to work around this error in the meanwhile?

**Comment by juliendargelos** [comment]
I'm afraid there is not 😕

**Pull request merged**
