### PR TITLE
Remove non-ENERGY_PRESERVATION code

### PR DESCRIPTION
**Pull request by sunag**
https://github.com/mrdoob/three.js/pull/17163#issuecomment-518414655

### CODE REVIEW

**Comment by mrdoob** [comment]
Merging this for now. We can add it back if needed.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I think this PR (and/or #17163) broke the furnace test:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_furnace_test.html

Screen Shot 2019-08-07 at 5 58 25 PM

Good:
https://threejs.org/examples/webgl_furnace_test.html

**Comment by sunag** [comment]
This was a code conflict with this PR https://github.com/mrdoob/three.js/pull/17079 I will fix.

**Pull request merged**
