### PR TITLE
Editor: Allow Camera to be viewed as Orthographic

### PR DESCRIPTION
**Pull request by Temdog007**
See #16008

Editor Orthographic

### CODE REVIEW

**Comment by Temdog007** [comment]
For testing: https://raw.githack.com/Temdog007/three.js/editor/DefaultOrthographic/editor/index.html

Double click Camera in the `Outliner` to change camera view.

**Comment by Temdog007** [comment]
Closing due to lack of interest.

**Comment by suyashdixit** [comment]
Hello, For a project I like you what you have made exactly. Instead of having perspective camera I want an orthographic camera but I see no such option in Editor. Your demo works fine but when I try to move objects many times it just moves camera. Did you see that? Any solution to it?

**Comment by parth270** [comment]
Hello @suyashdixit , How are you?
Did you find a solution to it?? I am also looking for a way to use an Orthographic camera instead of perspective!

**Pull request closed without merging**
