### PR TITLE
Examples: Update model in glTF AVIF demo.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #25173

**Description**

Updated the model in `webgl_loader_gltf_avif` to avoid the usage of the damaged helmet. 

Note: I still can't generate E2E screenshots on macOS 😞 . Doing this later on a Windows machine.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/Mugen87/three.js/dev76/examples/webgl_loader_gltf_avif.html

**Comment by Mugen87** [comment]
@donmccurdy `gltf-transform` is awesome! 

>  gltf-transform optimize forest_house.glb output.glb --texture-compress avif
> info: forest_house.glb (8.56 MB) → output.glb (298.81 KB)

**Review by donmccurdy — APPROVED** [review]
I like this model a lot, thank you!

**Comment by mrdoob** [comment]
> Note: I still can't generate E2E screenshots on macOS 😞

@LeviPesin any ideas?

**Comment by LeviPesin** [comment]
I already answered why [here](https://github.com/mrdoob/three.js/pull/25504#issuecomment-1429499681).

**Comment by mrdoob** [comment]
Right...

But it used to work before without installing Rosetta.

Or we waiting for Puppeteer then?

**Comment by LeviPesin** [comment]
Maybe something changed in Chromium and/or Puppeteer builds, not sure...

**Pull request merged**
