### PR TITLE
LightProbeGenerator: convert to linear based on texture encoding

### PR DESCRIPTION
**Pull request by WestLangley**
DRAFT...

### CODE REVIEW

**Review by nipmarsh — CHANGES_REQUESTED** [review]
What is the value of gammaFactor? In your calls, it is undefined.

**Comment by WestLangley** [comment]
Ugh.... It is the same as `renderer.GammaFactor` and only applies to `GammaEncoding`. I was trying to write a general method.

We are going to get rid of `GammaEncoding` in favor of `sRGBEncoding`, so perhaps I should remove that use case from the method...

**Comment by nipmarsh** [comment]
> We are going to get rid of `GammaEncoding` in favor of `sRGBEncoding`, so perhaps I should remove that use case from the method...

Totaly agree with you!

**Comment by mrdoob** [comment]
@WestLangley Is this ready to be merged? 🤔

**Comment by WestLangley** [comment]
>@WestLangley Is this ready to be merged?

Not yet... I have been busy with other things...

**Comment by WestLangley** [comment]
Closing. I think @nipmarsh plans to incorporate the idea here into a related PR.

**Pull request closed without merging**
