### PR TITLE
preventing 0 scale objects render processing

### PR DESCRIPTION
**Pull request by Jaswant99**
In glTF generated by Adobe Animate we have some nodes which have Zero scale and should not be part of render processing returning early for such nodes. It gives us a lot of performance benefit.

### CODE REVIEW

**Comment by Mugen87** [comment]
Related #17926

**Comment by mrdoob** [comment]
@Jaswant99 but this doesn't hide the warnings, does it?

**Comment by Jaswant99** [comment]
@mrdoob no it doesn't hide the warnings. for that for now we have just suppressed 'console.warn' function in our production code.

**Comment by Jaswant99** [comment]
@mdroobb it does not give that warning with this fix. But I was not intending to do that 😇. may that piece of code is not hit after this.

**Comment by Jaswant99** [comment]
but in some other workflows if somewhere it uses "THREE.Matrix3: .getInverse()" the warning will be thrown. although its not throwing in our workflow.

**Comment by Mugen87** [comment]
> but this doesn't "fix" the THREE.Matrix3: .getInverse() warnings, does it?

I've seen other implementations where `inverse()` returns a boolean indicating whether the computation was successful or not:

https://github.com/Mugen87/MathGeoLib/blob/21f3df70da276f555f6c76a0e401706fb23e9d2d/src/Math/float4x4.h#L647-L649

The caller can then still decide to throw and error or log a warning if necessary. I like this idea however it won't be backwards compatible if implemented.

BTW: I've never liked the signature of `getInverse()`. The method should work similar to e.g. `Box3.getSize()`. So instead of:
```js
this.matrixWorldInverse.getInverse( this.matrixWorld ); 
```
it should be.
```js
this.matrixWorld.getInverse( this.matrixWorldInverse );
```
As a comparison:
```js
box.getSize( size );
```
this works too:
```js
const size = box.getSize( new Vector3() );
```

**Comment by gkjohnson** [comment]
Rendering can only be skipped if two axes are scaled to 0, right? If only one axis is scaled to zero then the geometry should still render but collapsed to a plane

**Comment by Jaswant99** [comment]
> Rendering can only be skipped if two axes are scaled to 0, right? If only one axis is scaled to zero then the geometry should still render but collapsed to a plane

Thanks @gkjohnson  for pointing it out will do the required changes. 👍

**Comment by Mugen87** [comment]
Before more code is written, the question here needs to be clarified:

https://github.com/mrdoob/three.js/issues/17926#issuecomment-554135342

**Comment by Mugen87** [comment]
Closing for now until #17926 is clarified.

**Pull request closed without merging**
