### PR TITLE
Additive, Subtractive, Multiply, Custom PremultipliedAlpha blend modes

### PR DESCRIPTION
**Pull request by bhouston**
This fills out the rest of the blend modes for premultiplied alpha using the design of @WestLangley.

This does this by renaming the existing premultipliedAlpha blend mode:

THREE.PremultipliedAlphaBlending = 6;

And instead calling it:

THREE.PremultipliedAlphaNormalBlending = 6;

And then adding these following modes:

THREE.PremultipliedAlphaAdditiveBlending = 7;
THREE.PremultipliedAlphaSubtractiveBlending = 8;
THREE.PremultipliedAlphaMultiplyBlending = 9;

This also adds the ability to use custom blending modes with premultiplied alpha - which I am sure would be useful in the future:

THREE.PremultipliedAlphaCustomBlending = 10;

I've updated the relevant examples as well.

### CODE REVIEW

**Comment by WestLangley** [comment]
@bhouston Isn't it true that only `MeshStandardMaterial` (and maybe `MeshPhongMaterial`, but I would ignore that one) need your premultiplied enhancement?

If so, why not leave all the other materials the same, using `THREE.NormalBlending` with non-premultiplied shader output.

Trying to keep things simple. : - )

Or am I missing something... ?

**Comment by bhouston** [comment]
I think you are missing something.

Premultiplied alpha is generally the way that experienced people in the graphics community recommend going when possible, while keeping open the possibility of not using premultiplied alpha for those situations were it isn't appropriate (backwards compatibility, or when you have special blending needs.)  I think that ThreeJS should also go in this direction.  There is little reason to not do the right thing here if we can properly deal with backwards compatibility issues for ThreeJS's large user base.

Here is some readings for you:

http://blog.rarepebble.com/111/premultiplied-alpha-in-opengl/

Wikipedia talks about the advantages of premultiplied Alpha:
https://en.wikipedia.org/wiki/Alpha_compositing

Premultiplied Alpha does't require divides and thus it is faster to composite:
http://www.teamten.com/lawrence/graphics/premultiplication/

Microsoft:
http://microsoft.github.io/Win2D/html/PremultipliedAlpha.htm

NVIDIA:
https://developer.nvidia.com/content/alpha-blending-pre-or-not-pre

Oculus VR:
https://twitter.com/tom_forsyth/status/578156255245545472 (need to search for premultiplied alpha on this page)

There are some downsides to premultiplied so we should keep the option to keep it around.

**Comment by WestLangley** [comment]
@bhouston I did not realize you wanted to output premultiplied values from all the predefined shaders. If you mentioned it earlier, I missed it.

**Comment by bhouston** [comment]
> @bhouston I did not realize you wanted to output premultiplied values from all the predefined shaders. If you mentioned it earlier, I missed it.

This PR is not about changing the defaults for materials - that is a separate discussion and it is something that @mrdoob recently changed.  I support that change, but it is outside of the scope of this PR.

I am just trying to add the missing default blending modes for the premultipled alpha option.

**Comment by mrdoob** [comment]
Ok, I think the safest (non blocking) thing to do by now will be to merge this. Then I'll revert to the `material.premultiplyAlpha` approach and set it to `false`. That way nothing will break and people will be able to have good transparency when enabled.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
