### PR TITLE
Math: move to es6 classes

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
Hi all.
This pull relates to #11552 #17425

I've been working on sorting the maths scripts into ES6 classes. It's close but needs some help.
My local dev website runs all of the code just fine however:

- "geometry / terrain /raycast" example has had a noticeable performance hit
- "camera / array" example fails silently...
- various WebGLProgram warnings (i.e. fakepath() ... pow(f, e) ... negative f values)

I also tried to work my way through some of the unit tests but le brain died at that point.

Going to have a look at the other folders as there may be some easier candidates for ES6 transformation.

update:
[mrdoob's comment on let/const](https://github.com/mrdoob/three.js/pull/17276#issuecomment-527687857)
[Blocking dependencies](https://github.com/mrdoob/three.js/issues/6419#issuecomment-599160231)

### CODE REVIEW

**Comment by Mugen87** [comment]
> Going to have a look at the other folders as there may be some easier candidates for ES6 transformation.

FYI: The class migration has been paused for now. So it might be better to wait until it's clear when this task moves on.

**Comment by Mugen87** [comment]
BTW: 23 units test fail with your change (which is definitely an issue).

**Comment by DefinitelyMaybe** [comment]
most definitely. I had a quick look at the tests and there were things like 'x not found on undefined'. not sure how I got there by changing the syntax. I made the PR in case someone wanted to look into before I get back to it. My thinking atm is that one of the other folders might be easier... if at first you don't succeed, right?

**Comment by DefinitelyMaybe** [comment]
> FYI: The class migration has been paused for now. 

Hey, quick question, which discussion(s) are you referencing?

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/6419#issuecomment-599152135. We cannot migrate any classes that are extended by files in `examples/js`, yet, at least. I'm not sure if that means _all_ conversions are paused, or if there are other considerations here.

**Comment by looeee** [comment]
@Mugen87 there's no reason to pause _all_ class conversions. Why don't we move ahead with classes that are not extended in the examples? The box geometries have been converted to classes for a few months now without issue.

**Comment by Mugen87** [comment]
I'm not sure it's just about the examples directory. Any class could be dervied by user level code and I don't know how @mrdoob feels about this topic in context of backwards compatibility.

Sidenote: Introducing classes does not mean introducing other ES6 features like `let`/`const`. According to https://github.com/mrdoob/three.js/pull/17276#issuecomment-527687857, the migration should only focused on classes. #18912 does honor this right now. To make things more stable, I think it's more safe to do things step by step.

**Comment by Mugen87** [comment]
Closing due to failing unit tests, merge conflicts and wrong example code (the PR modularized files in the `examples/js` directory).

**Comment by DefinitelyMaybe** [comment]
good. your turn @Mugen87

**Pull request closed without merging**
