### PR TITLE
DecalGeometry: Fixed index read access

### PR DESCRIPTION
**Pull request by Mugen87**
Bugfix for indexed `BufferGeometry` based meshes.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Nice job on this, but with all due respect, I do not think `DecalGeometry` should be part of the library -- just the examples. It was not designed to work on all geometries.

You can try, for example on a closed cylinder, or on a double-sided object, or on a thin object. I am sure there are other examples.

**Comment by mrdoob** [comment]
I think I agree.

**Comment by Mugen87** [comment]
I just thought it might be interesting to integrate decals into the editor (see http://blog.wolfire.com/2009/06/decals-editor-part-three/ for more information). Besides, there are many popular effects in games (e.g. bullet holes) that are based on this technique. From this point of view, `DecalGeometry` might be more important than other geometry types.

@WestLangley But i also understand your opinion. If you still don't think it so important, i will outsource `DecalGeometry` to a separate file like before.

**Pull request merged**
