### PR TITLE
Examples: Make files and tags to JSON files.

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/pull/20543#issuecomment-713428000

This avoids the global variables `files` and `tags` in `example/index.html` and also makes `test/e2e/check-coverage.js` less hacky.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev44/examples/index.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@Mugen87 I know it loses parallel loading, but I find the code prettier 😇 https://github.com/mrdoob/three.js/commit/80509b14fec51180f1c37ad6cc9c66f76d1f7018

**Comment by Mugen87** [comment]
Definitely 👍

**Comment by takahirox** [comment]
Yeah, this approach is much more simple and robust. Thanks for the update.

**Pull request merged**
