### PR TITLE
Abelnation RectAreaLight with ltc approximation

### PR DESCRIPTION
**Pull request by sam-g-steel**
Brought the code up to date so it can be merged without conflict.

#9234

### CODE REVIEW

**Comment by abelnation** [comment]
awesome awesome! thanks for putting in the work to get this working with the latest updates!

**Comment by mrdoob** [comment]
Would it be possible to not include the build in the PR?

There is also a ton of things that I would like to remove (mainly the whole `examples/polygon_light_example/` folder) but I'm happy to do that myself after merging.

**Comment by mrdoob** [comment]
Actually, seems like it has no conflicts, so I'll merge and do the clean up.

**Comment by mrdoob** [comment]
Thanks!

**Comment by sam-g-steel** [comment]
Awesome!!!
Glad I could help!
Can't wait for v83

**Pull request merged**
