### PR TITLE
MMDLoader: New path interface

### LINKED ISSUE #12942: Loaders: Inconsistent implementations of .setPath()
Hey dear guys,

since you urged + forced me (me, just a innocent threejs user), see https://github.com/mrdoob/three.js/issues/12903
I bravely followed you to use **GLTF**, and tried ...

It looks, as if **GLTFLoader.setPath()** doesn'nt work ...

The default "Blender Cube" should appear like this:
https://rawgit.com/wolfgangvonludwigsburg/three.js/dev/examples/_webgl_loader_gltf_cube_PR.html

Compare to current "90dev" state:
https://rawgit.com/wolfgangvonludwigsburg/three.js/dev/examples/_webgl_loader_gltf_cube_fail.html
Console.log: Failed to load resource: the server responded with a status of 404 (Not Found)

To verify the loading path, I've put in an additionally FileLoader request (which succeeds).

The fix could be, in GLTFLoader.js,
line 27, after
```
    var path = this.path !== undefined ? this.path : THREE.LoaderUtils.extractUrlBase( url );
```
insert
```
    if ( this.path !== undefined )
        url = this.path + url;
```
If you verify the fault, should I do a PR, or the author of GLTFLoader.js ?

BTW: Additionally I tried JSONLoader.setPath() which fails (member method not available) ...
- maybe all loaders should behave accordingly in the same manner ... ?

90dev, Chrome, Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixes #12942

Renames `.setTexturePath()` to `.setResourcePath()`. Because of the special character of `MMDLoader`, it think it's better to omit `setPath()`. Besides, `setResourcePath()` is only internally used. https://github.com/mrdoob/three.js/issues/12942#issuecomment-425748022 explains why.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev19/examples/webgl_loader_mmd.html

**Comment by Mugen87** [comment]
Added new path interface like discussed in #12942.

**Comment by Mugen87** [comment]
@takahirox Does these changes look good to you? :innocent:

**Comment by mrdoob** [comment]
Merging. We can change things afterwards if @takahirox has suggestions.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
