### PR TITLE
Examples: tonemapping  add backgroundIntensity gui

### PR DESCRIPTION
**Pull request by vis-prime**
**Description**

 Since [tonemapping ](https://threejs.org/examples/?q=tone#webgl_tonemapping)example already has `scene.backgroundBlurriness` , adding `scene.backgroundIntensity` slider also

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/vis-prime/three.js/tonemapping_example_gui_update/examples/webgl_tonemapping.html

**Comment by Mugen87** [comment]
Maybe we should make two folders "tone mapping" and "background". The tone mapping type and exposure are placed in the first folder, blurriness and intensity in the second one. That should make the GUI more clear.

Folders are done like so:

https://github.com/mrdoob/three.js/blob/edefdc237b2528b9668fb873a1c06cb835840303/examples/webgl_postprocessing_unreal_bloom.html#L127C16-L127C22

**Comment by vis-prime** [comment]
sure !, was thinking the same 

will add it as
`toneMapping` and `exposure` under a `tone mapping` folder
&
`blurriness` and `intensity` makes under a `background` folder

cool?

**Comment by vis-prime** [comment]
ummm... why isn't the [rawcdn.githack](https://rawcdn.githack.com/vis-prime/three.js/tonemapping_example_gui_update/examples/webgl_tonemapping.html) not showing the updated version ?

**Comment by Mugen87** [comment]
It usually takes a while until the link refers to the latest commit. In the meanwhile, you can test the changes by using the commit hash in the URL: https://rawcdn.githack.com/vis-prime/three.js/8568419d2e9858c7e4e113a1366c641804bc1f11/examples/webgl_tonemapping.html

**Pull request merged**
