### PR TITLE
Color: added support for add color values using uppercase

### PR DESCRIPTION
**Pull request by puxiao**
Related issue: null

<br>

**Description**

I think it's a bad experience.

```
const material = new Three.MeshPhongMaterial({ 
	color: 'Red'
})
```

> ⚠️warn:  THREE.Color: Unknown color Red

<br>

**So...**

```diff
-	const hex = _colorKeywords[ style ];
+	const hex = _colorKeywords[ style.toLowerCase() ];
```

### CODE REVIEW

**Comment by Mugen87** [comment]
In this case, then end of the following sentence in the documentation can be removed.

https://github.com/mrdoob/three.js/blob/342946c8392639028da439b6dc0597e58209c696/docs/api/en/math/Color.html#L313

**Comment by Mugen87** [comment]
@puxiao I've meant to just delete `(all lowercase)`, not the entire sentence^^.

**Comment by puxiao** [comment]
Oops... Do I need to recover?

**Comment by Mugen87** [comment]
Yes, that would be good. And then just remove `(all lowercase)`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
