### PR TITLE
PointerLockControls: Add `.pointerSpeed`.

### PR DESCRIPTION
**Pull request by ChrisCrossCrash**
Related issue: #23513

**Description**

This PR adds a new `mouseSpeed` property to `PointerLockControls`. Changing this property changes the mouse sensitivity for controlling the camera look direction. The PR also adds a new optional `options` parameter to the constructor for setting `mouseSpeed` when a new `PointerLockControls` instance is made.

### CODE REVIEW

**Comment by WestLangley** [comment]
>The PR also adds a new optional options parameter to the constructor 

We do not have that option in the the other controls, so I'd omit it.

> This PR adds a new mouseSpeed property

As implemented in this PR, the units of `mouseSpeed` are _radians per pixel_. Don't forget to update the docs.

//

Or, maybe better, implement it like so:

```js
_euler.y -= movementX * 0.002 * mouseSpeed;
```

In that case, `mouseSpeed` would be unit-less, and have a default value of 1.

I'd defer to @mrdoob for the choice of parameterization.

**Comment by mrdoob** [comment]
>> The PR also adds a new optional options parameter to the constructor
>
> We do not have that option in the the other controls, so I'd omit it.

Agreed.

> Or, maybe better, implement it like so:
>
> ```js
> _euler.y -= movementX * 0.002 * mouseSpeed;
> ```
>
> In that case, `mouseSpeed` would be unit-less, and have a default value of 1.

Agreed too.

**Comment by mrdoob** [comment]
I think I can make these changes directly here... 🤔

**Comment by mrdoob** [comment]
One more issue... Should it be `pointerSpeed` instead of `mouseSpeed`?

**Comment by WestLangley** [comment]
>Should it be pointerSpeed instead of mouseSpeed?

Maybe `trackingSpeed`? That is the term macOS uses for the mouse sensitivity parameter.

**Comment by ChrisCrossCrash** [comment]
These are all great ideas! I've added two more commits.

The first renames `mouseSpeed` to `pointerSpeed`. I tend to agree with @Mugen87 that it's a nice fit because it goes well with `PointerLockControls`. I can change it if you prefer.

The second commit adds documentation for the `pointerSpeed` property.

Please let me know if there's anything else you would like me to change, or feel free to make your own changes.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
