### PR TITLE
Tests: Refactor regression testing.

### PR DESCRIPTION
**Pull request by munrocket**
Refactor:
- `diff` -> `e2e`, because `diff` was a meaningless in test folder and travis config.
- created new `clean-page.js` file in order to simplify main script

This can be merged only after #18742 #18732, they are cherry-picked.

### CODE REVIEW

**Comment by mrdoob** [comment]
This PR adds new images. Is that part of the script refactoring?

**Comment by munrocket** [comment]
@mrdoob sorry I never used cherry-pick in git before.

You said that I need to split #18732 commit into several commits. So I splited:
- ignore css3d_youtube
- add thumbnail generator and thumbnails
- refactoring

The last one is mixes up and conflicting with previous two. So I just run `git cherry-pick <commit_hash>` two times and started from that point as it was already merged. But seems that I am doing it in a wrong way. Right now I know how to continue with force push, only after #18742 will be merged.

**Comment by mrdoob** [comment]
> Right now I know how to continue with force push, only after #18742 will be merged.

Yeah, seems like we still have the same problem. #18742 may take some time to be approved and it's blocking other features.

But splitting I meant doing new PRs using `dev` as base.

**Comment by munrocket** [comment]
Ok, I will start from current `dev` in both cases.

But #18742 is work well because it's doing nothing at all :D There was a problem with BeginFrame CDP HeadlesExperimental API but I am removed this change after it was not good enough.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
