### PR TITLE
Return geometry after calling applyMatrix()

### PR DESCRIPTION
**Pull request by Wilt**
Return geometry (`this`) after calling `applyMatrix():`

### CODE REVIEW

**Comment by Wilt** [comment]
Added also for `THREE.BufferGeometry`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Wilt** [comment]
You are welcome.

**Comment by Wilt** [comment]
I wanted to update the docs too, but it seems like all return values are missing from the Geometry docs. @WestLangley and @TatumCreative are discussing that over [here].(https://github.com/mrdoob/three.js/pull/8180#issuecomment-186465930)

I alread deleted my patch since you merged it so I could make new PR for only the docs, but it seems a bit overkill since the docs need a general update anyway.

**Pull request merged**
