### PR TITLE
WebGLRenderer: removed .context property

### PR DESCRIPTION
**Pull request by WestLangley**
As suggested in https://github.com/mrdoob/three.js/pull/16999#issuecomment-510280300.

Use `renderer.getContext()` instead.

### CODE REVIEW

**Comment by WestLangley** [comment]
Note: In a later PR we are going to have to check the examples for cases where gl calls are made behind the back of the renderer. Doing so can invalidate the renderer's internal state.

That makes me wonder why the renderer's context is exposed at all ( via `.getContext()` ).

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
> That makes me wonder why the renderer's context is exposed at all ( via .getContext() ).

I think it's okay to expose the raw WebGL context for advanced users who know what they are doing.

**Comment by WestLangley** [comment]
Perhaps it is sufficient -- post gl hack -- to recommend advanced users make use of, or at least be aware of:
```js
renderer.state.reset();
```

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Ugh. I modified the jsm files instead of the js files...

**Pull request merged**
