### PR TITLE
Add examples/js to bower distribution.

### PR DESCRIPTION
**Pull request by arodic**
Currently, bower distributed three.js does not include all the goodies from examples/js directory.
This change adds those files to bower distribution.

### CODE REVIEW

**Comment by arodic** [comment]
Ping @mattdesl @willywongi @sgrif @isreal-breel

Would anyone mind adding examples/js scripts to bower dist? Its approx. 1.8 MB

There are many very useful scripts in there which are not added to the build itself.
For example, examples/js/controls and examples/js/renderers

**Comment by mattdesl** [comment]
I don't have write access to the bower dist (not sure who maintains it).

I agree that example code should be added to Bower since a lot of them are an integral part of ThreeJS dev (e.g. THREE.Projector is now in examples). I don't really care for all the extra junk (tons of images and models). 

I've lately been publishing some ThreeJS things to npm. I guess we'll see how it plays out in the long run, given the difference of flat vs. nested dep tree and potential for versioning issues. 

https://www.npmjs.com/package/three-orbit-controls
https://www.npmjs.com/package/three-orbit-viewer
https://www.npmjs.com/package/three-shader-fxaa
https://www.npmjs.com/package/three-line-2d
https://www.npmjs.com/package/three-effectcomposer (via hughsk)

**Comment by arodic** [comment]
@mattdesl it is possible to include examples/js subdirectory but not the rest of the junk (images, html files etc.)

This works:
```
"examples/*",
"!examples/js",
```

**Comment by mrdoob** [comment]
> And it seems kinda crazy to not use a package manager in this day and age. :)

I agree. If I would have started all this now I would definitely be using all that fancy stuff. But right now I'm still trying to clean/design the whole thing.

**Comment by mrdoob** [comment]
Thanks Aki!

**Comment by mattdesl** [comment]
Heh, totally understand. ThreeJS is pretty great as-is, no point in tearing it down and reinventing it all.

**Comment by alisha25** [comment]
conflict

**Pull request merged**
