### PR TITLE
Benchmarks Suite Added

### PR DESCRIPTION
**Pull request by BrianCraig**
I wanted to add some Benchmarks, but the benchmarks folder only contained some snippets, so i updated the benchmarkjs to v2 and added some minimal suite, where you manage all the tests in a single page. I ported the old tests that i think that are no longer needed. And paint it all with a nice Pink palette :)

### CODE REVIEW

**Comment by mrdoob** [comment]
Does benchmark depend on lodash?

**Comment by BrianCraig** [comment]
Yes, Benchmarkjs v2 Requires lodash

**Comment by mrdoob** [comment]
I see I see!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
