### PR TITLE
BufferGeometry: set .type to base class after transform is applied

### LINKED ISSUE #22586: BufferGeometry loss translate when toJSON
```
var boxGeo = THREE.BoxGeometry(5,5,5);
boxGeo.translate(10, 20, 10);
boxGeo.toJSON()
```

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #22586

### CODE REVIEW

**Comment by WestLangley** [comment]
So far, I am not aware of any adverse consequences of doing this...

**Comment by Mugen87** [comment]
The consequence is that you don't get the type of the geometry generator anymore after deserialization which is to me way more confusing than the reported issue in #22586.

Your approach would make sense if the geometry generators would be factory methods and return `BufferGeometry` in the first place.

**Comment by Mugen87** [comment]
Besides the approach of the PR is contradictory compared to our latest changes to `BufferGeometry.clone()`. When cloing a `BoxGeometry`, you get the same type. This should also be true for serialization/deserialization.

I would rather sacrifice the serialization based on `parameters` (and accept larger JSONs) instead what is suggested here.

**Review by Mugen87 — DISMISSED** [review]

**Comment by Mugen87** [comment]
The problem with this approach is that you are going to loose type information when serializing/deserializiing and thus introduce a new bug.

To me, the resulting behavior is even more confusing. Consider the latest changes to `BufferGeometry.clone()`, I think it's better to always preserve the type of the geometry generator. 

The reported issue in #22586 is a limitation of the choice to use classes instead of factory methods for creating geometries. I think it's better to accept the design limitations and do not start to add hacks in the engine.

**Comment by WestLangley** [comment]
>The problem with this approach is that you are going to loose type information when serializing/deserializing

Once the geometry is transformed, it is no longer of the previous type.

> I think it's better to always preserve the type of the geometry generator.

Not after the geometry is modified...

... and not if you silently serialize the incorrect data.

**Comment by WestLangley** [comment]
>do not start to add hacks in the engine.

Ouch. I object to referring to this PR as a hack.

**Comment by Mugen87** [comment]
Um, it just does not feel right in context of OOP if the type of an object changes like that. 

Maybe we can just state that the result of geometry generators is considered to be immutable after the creation. If users want to further transform the geometry, it's best to create an instance of `BufferGeometry` and copy over the buffer data first.

**Comment by Mugen87** [comment]
Or we just ignore `parameters` in `BufferGeometry.copy()` and `BufferGeometry.clone()` and always work with the raw buffer data. However, this would have the drawback that resulting JSON files could be much larger than before.

**Comment by WestLangley** [comment]
>Um, it just does not feel right in context of OOP if the type of an object changes like that.

Actually, it is not _the_ type, it is just a property.

We could set a `._transformed` flag to `true` if the class has `.properties` and test the `._transformed` flag, instead, when serializing.

It is just semantics, right?

**Comment by WestLangley** [comment]
@Mugen87 I think _something_ should be done to fix this... Pick the least-offensive solution?

**Comment by makc** [comment]
@donmccurdy 
> .translate() could return a new BufferGeometry

what if you return new BG with the same buffers? this way user can choose what type of G they want to keep in their code

**Comment by WestLangley** [comment]
I recommend merging this PR, since I think it is better than doing nothing.

If there is still no interest in this PR, I am going to close it, but I still consider #22586 to be a bug.

**Comment by WestLangley** [comment]
OK, closing...

**Pull request closed without merging**
