### PR TITLE
Initial matrixWorld & ChildrenMatrixWorld seperation

### PR DESCRIPTION
**Pull request by gero3**
Continuation of #7019
This is the solution of making sure that the parent matrixworld is updated before updating the matrixworld.

What has changed:
- Methods:
  - `updateMatrix`: checks if position, rotation and scale haven't changed and recalculates only when changed Before this were always recalculated. This should only be called when matrixAutoUpdate is false and the matrix is in need of an update.
  - `_updateMatrixWorld`: This is an internal method. This calculates the matrixworld based on the previous calculated parent matrixworld and matrix. This is also the method that needs to be overridden when the matrixworld needs to be calculated differently.
  - `updateMatrixWorld`: This calculates the matrixworld by calculating the parents matrixWorld and its onw matrix. Internally it calls _updateMatrixWorld.
  - `_updateChildrenMatrixWorld`: This is an internal method. This calculates the matrixworld based on the previous calculated parent matrixworld and matrix and off all its children. Internally it calls _updateMatrixWorld.
  - `updateChildrenMatrixWorld`:This calculates the matrixworld by calculating the parents matrixWorld and its own matrix and that of its descendants. Internally it calls _updateChildrenMatrixWorld.

### CODE REVIEW

**Comment by gero3** [comment]
anyone interested in this??

**Comment by mrdoob** [comment]
Sorry for the delay. This looks good to me. Do you mind resolving the conflicts?

**Comment by gero3** [comment]
Resolved the conflicts with a new merge.

**Comment by gero3** [comment]
Does this look good to get into the r81 release??

**Comment by WestLangley** [comment]
Let's give this a go. If there are problems, we can back it out. I am really surprised users haven't complained about this issue.

**Comment by fallenoak** [comment]
Out of curiosity, why doesn't ```updateChildrenMatrixWorld``` stop traversing and updating once encountering a descendant with ```visible``` set to ```false```? I realize the current ```updateMatrixWorld``` ignores ```visible``` as well, but I'm at a loss as to why.

**Comment by WestLangley** [comment]
@fallenoak Well, one example would be the target of a spotlight -- assuming the target is part of the scene graph. The spotlight depends on the target, whether the target is visible or not.

**Comment by fallenoak** [comment]
@WestLangley Hrm, right. I suspected there was probably a reason that had eluded me. I suppose there isn't any alternative to handle that kind of need, either, without potentially causing redundant calculations...

**Comment by gero3** [comment]
Is there any interest in this??

**Comment by gero3** [comment]
Should I close this one??

**Comment by mrdoob** [comment]
Sorry, I still don't know what the right thing to do is here 😥

**Comment by gero3** [comment]
out of date

**Comment by quacrobat** [comment]
I am confused by this series of threads... is updateMatrixWorld automatic now or finally not? 
@gero3 @WestLangley @mrdoob 
Thanks

**Comment by Mugen87** [comment]
>  is updateMatrixWorld automatic now or finally not?

When accessing `matrix` or `matrixWorld`, the engine does _not_ ensure up-to-date matrices. If you change for example the `position` property of an object, both matrices do not automatically reflect the new translation.

**Comment by quacrobat** [comment]
> the engine does _not_ ensure up-to-date matrices 
except in a render loop then.
Thanks @Mugen87, pity the automatic update wasn't implemented, it sounded much fore efficient when needing to work with objects before on-demand rendering.

**Comment by Mugen87** [comment]
I agree it would be nice if `three.js` would always ensure up-to-date matrices. However, to efficiently implement such a feature, `three.js` would need a different API. For example it would be necessary to make `Object3D.matrix` private and replace it with `Object3D.getLocalMatrix()`. So it's not possible to set the local matrix anymore, only retrieve it with a getter. This would allow to cache matrices or use a dirty flag so the matrix is only computed if `position`, `rotation` or `scale` are changed. Such a workflow is somewhat the basis for a more efficient world matrix computations.

**Pull request closed without merging**
