### PR TITLE
WebGLRenderer: Removed gl_FragDepth-based logarithmic depth buffer code

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #22017

**Description**

This PR removes all `gl_FragDepth`-based logarithmic depth buffer related code.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
@jbaicoianu what do you think about this? reason in #22017

**Comment by gkjohnson** [comment]
Is this previous issue related? https://github.com/mrdoob/three.js/issues/17384

It looks like this PR is changing the behavior of log depth buffer to only apply to vertices rather than fragments which I don't believe is correct.

**Comment by Mugen87** [comment]
Sidenote: If we decide to keep the current implementation, we should document the MSAA restrictions at the doc page of `WebGLRenderer`.

**Comment by sam6321** [comment]
Would it be possible maintain both log depth buffer implementations and leave up to the user to decide which they want to use?

I use the fragment log depth buffer implementation as part of a 3D globe application, and there are quite a lot of rendering artifacts when I swap to the vertex method.

I would suggest using the vertex method by default, with an option to use the fragment method if desired (Basically the option that was described [here](https://github.com/mrdoob/three.js/issues/22017#issuecomment-868779882)).

**Comment by sam6321** [comment]
Just a note, after the alternative PR I made was declined, that I have an application that relies on threejs' current fragment log depth implementation that would break if this PR was merged and that implementation was removed.

Are there any other acceptable alternatives that can keep fragment log depth around?

**Comment by Mugen87** [comment]
I vote to keep the current logarithmic depth buffer code until a new solution (reverse depth buffer) is available.

**Comment by Mugen87** [comment]
As mentioned in https://github.com/mrdoob/three.js/pull/22041#issuecomment-867778486, we can't sacrifice per-pixel depth values since this potentially break applications. Until an alternative is found, let's keep using `GL_EXT_frag_depth` with its emulated fallback.

**Pull request closed without merging**
