### PR TITLE
Line2: Add support for Alpha To Coverage

### PR DESCRIPTION
**Pull request by gkjohnson**
Related issue: --

**Description**

Adds support for `alphaToCoverage` to Line2. It's a subtle effect but it enables anti aliasing on the rounded tips of the line segments which can be seen on the line ends and when the line is curving in the demo:

https://raw.githack.com/gkjohnson/three.js/atc-line2/examples/webgl_lines_fat.html

cc @WestLangley

### CODE REVIEW

**Comment by WestLangley** [comment]
Interesting idea: anti-aliasing of the line end-caps. It is very subtle.

I'll defer to @Mugen87 on this one.

**Comment by WestLangley** [comment]
Although with very fat (50px) straight lines I see artifacts.

Screen Shot 2021-03-11 at 9 08 23 PM

**Comment by gkjohnson** [comment]
@WestLangley 

> It is very subtle.

Heh I've noticed it forever and it's always bugged me and now it can be addressed! It's definitely more noticeable on lower DPI displays and it also helps some jaggedness around curved corners on paths where the end points meet.

> Although with very fat (50px) straight lines I see artifacts.

I'm not seeing this on the two machines I'm able to test with but I suspect it's because a derivative was being taken in a conditional the behavior of which probably varies depending on hardware. I've fixed this by defining `len2` before the conditional to ensure it's defined. Can you give it a try to see if that fixed it? Should I update the example so you can raise the line thickness to 50px?

A couple other fixes I just pushed:
- Adjust how the alpha coverage factor is computed.
- Set shader to use the derivatives extension so WebGL1 is supported.

**Comment by Mugen87** [comment]
I can see the artifacts, too. The only appear with AtC.

image

This glitch is visible with a 10px wide line.

**Comment by gkjohnson** [comment]
> I can see the artifacts, too. The only appear with AtC.

Heh uh oh 😅

@Mugen87 

What hardware are you using? I'm hoping I can reproduce it somehow otherwise this won't be a fun one to track down.

**Comment by Mugen87** [comment]
It's an iMac (10.15.7) with a AMD Radeon R9 M295X 4 GB. Chrome version: 89.0.4389.82

**Comment by gkjohnson** [comment]
I was able to reproduce the issue on a mac laptop and have fixed them (in my case). It seems that on some hardware taking a derivative inside a conditional at all can cause undefined behavior even if the variable is defined outside the condition. I should have fixed it in the last commit -- let me know!

**Comment by Mugen87** [comment]
Looks better now!

**Review by WestLangley — APPROVED** [review]
Yep, looks better.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
