### PR TITLE
Docs: Remove outdated WebGL 2 guide.

### PR DESCRIPTION
**Pull request by Mugen87**
Because WebGL 2 is now the default.

### CODE REVIEW

**Comment by marcofugaro** [comment]
This is great news! Will the `Composer` use a `WebGLMultisampleRenderTarget` by default in the future, so that the native-like antialiasing doesn't turn off when using postprocessing? [I am talking about this approach](https://discourse.threejs.org/t/advantages-disadvantages-of-using-webgl2/7717/7).

Sorry if the question is not strictly related to this PR.

**Comment by Mugen87** [comment]
TBH, this could be already done in the past so I don't see a connection to making WebGL 2 to the default.

**Comment by trusktr** [comment]
Safari doesn't have WebGL2 yet though. Doesn't now there need to be a guide on how to use WebGL1 so it works in all browsers?

Is it like the following?

```js
var canvas = document.createElement( 'canvas' );
var context = canvas.getContext( 'webgl' );
var renderer = new THREE.WebGLRenderer( { canvas: canvas, context: context } );
```

**Comment by Mugen87** [comment]
#19647 should be the solution for this case.

**Comment by Mugen87** [comment]
> Safari doesn't have WebGL2 yet though.

The renderer should fallback then to WebGL 1.

**Comment by mrdoob** [comment]
@Mugen87 `EffectComposer` passes could do this:

```js
const useWebGLMultisampleRenderTarget  = ( typeof WebGL2RenderingContext !== 'undefined' && gl instanceof WebGL2RenderingContext );
```

**Comment by Mugen87** [comment]
Yep! The only problem is that passes like `SSAOPass` create internal render targets that needs to be adjusted, too. And not every render target needs to be multi sampled. This could take some time to check all passes...

**Comment by mrdoob** [comment]
Yep! We'll keep tweaking things... 🤓

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
