### PR TITLE
EXAMPLES: panorama_equirectangular switched to orbit controls

### PR DESCRIPTION
**Pull request by looeee**
See #13275

[New version](https://rawgit.com/looeee/three.js/a67b1eff496876efaf8acaf03fd78edbdc66f025/examples/webgl_panorama_equirectangular.html) 

[Old version](https://threejs.org/examples/webgl_panorama_equirectangular.html)

### CODE REVIEW

**Comment by Mugen87** [comment]
Just one minor thing: I can still zoom and pan 😇

**Comment by WestLangley** [comment]
Uh oh. Dragging by touch is backwards... Try
```javascript
controls.rotateSpeed = - 0.1;
controls.enableDamping = true;
```
Might as well enable damping, but try without it to see if `rotateSpeed` feels right.

**Comment by looeee** [comment]
@Mugen87 oops, wrong rawgit link above! Fixed it. 

Here's an updated version with [negative autoRotate speed](https://rawgit.com/looeee/three.js/a576df794be8756c2a49428de9713bac2c1ea058/examples/webgl_panorama_equirectangular.html) and damping enabled. Seems to have fixed the issue on mobile. 

@WestLangley thanks for the tip!

**Comment by mrdoob** [comment]
This is the new version, right?

https://rawgit.com/looeee/three.js/examples_panorama_equirectangular_orbit_controls/examples/webgl_panorama_equirectangular.html

**Comment by looeee** [comment]
Yes, I kind of hit a wall with this though - panning by mouse is reversed due to rendering on the inside of a sphere. 

Setting `autorotate` speed to negative fixes this (although it rotates in other direction), but not on touch devices - that's what the link you copied does. So basically, panning direction will be opposite for touch and mouse.

Maybe that is an improvement compared to touch not working at all though?

**Comment by mrdoob** [comment]
I don't know... The old version felt like you were dragging the panorama. Felt good.

**Comment by looeee** [comment]
Yeah, this turned out to be harder to get working like the original than I expected.

I don't think it's a big deal for this not to have touch controls so if you prefer the original I'll close it.

**Comment by WestLangley** [comment]
>panning by mouse is reversed due to rendering on the inside of a sphere.

@looeee See https://github.com/mrdoob/three.js/pull/13551.

Also, the camera should be close to the origin to prevent distortion (e.g.,  `z` = 1).

Panning with mouse and touch should be similar. If not, there is a problem somewhere...

**Comment by looeee** [comment]
@WestLangley thanks for the link. I've updated the code to match the cube panorama as closely as possible and this seems to have fixed the problems. [New link](https://rawgit.com/looeee/three.js/3480a5cc2baf48dd41bee74e495cbedea8b9a653/examples/webgl_panorama_equirectangular.html)

The scene is very close to the old one, however `autoRotate` is disabled now. I think that this is better since touch controls now work and it matches the cube panorma example.

**Comment by WestLangley** [comment]
Thing is, this is now a static scene. With these changes, there is no reason for an animation loop other than to support damping.

**Comment by looeee** [comment]
> Thing is, this is now a static scene.

True, and same with the cubemap panorama example that you linked above.
If you prefer we could remove damping and the animation loop from both examples?

**Comment by WestLangley** [comment]
>If you prefer we could remove damping and the animation loop from both examples?

...or from one example?

This is sort of an ongoing issue that has never been resolved. At one point we discussed having `OrbitControls` handling its own `requestAnimationFrame` when damping or auto-rotation was enabled.

I just made the point so you'd be aware of the issue. :) Whatever you want is OK with me.

**Comment by looeee** [comment]
OK, thanks for the feedback. 
My intention with the latest update was to make the two examples as similar as possible, and I prefer the controls with damping enabled. 
Also, because of the image upload functions I think the code will be a little more complex without the animation loop. So I'd rather leave it in for now.

**Comment by looeee** [comment]
Thanks @Mugen87 😁

**Pull request closed without merging**
