### PR TITLE
Editor: Added UIFile class.

### PR DESCRIPTION
**Pull request by Johann426**
**Description**

Added `<input>` element with `type='file'`  in **`ui.js`**

I hope that this small addition can help **`Menubar.File.js`** have a more concise code, instead of creating dom elements directly.

Thanks

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Johann426/three.js/dev_ui/editor/index.html

**Comment by Mugen87** [comment]
Seems the PR does not work as expected. I can not import this basic scene anymore.

[scene.json.zip](https://github.com/mrdoob/three.js/files/7823461/scene.json.zip)

**Comment by Johann426** [comment]
Many thanks for reviewing it. Now it seems to be working well.

Tested five more scene files, we can import scene successfully.

https://raw.githack.com/Johann426/three.js/dev_ui/editor/index.html
[scenes.zip](https://github.com/mrdoob/three.js/files/7828855/scenes.zip)

**Comment by Mugen87** [comment]
It works now. However, I'm unsure about adding a `UIFile` class for this scenario.

UI classes have a visual representation which is no true for this particular use case. The input element is actually added to an invisible form. For consistency reasons, it's probably better to keep the code as it is.

**Comment by Johann426** [comment]
Thank you for your review. 
It doesn't seem to be very necessary, so I'll close PR.
Anyway, thank you for taking your time :)

**Pull request closed without merging**
