### PR TITLE
Build: Added google-closure-compiler to dev dependencies

### PR DESCRIPTION
**Pull request by Mugen87**
Instead of using a local copy of the `google-closure-compiler`, the project now uses a npm module.

https://www.npmjs.com/package/google-closure-compiler

### CODE REVIEW

**Comment by Mugen87** [comment]
Relevant issue: #8119

**Comment by Mugen87** [comment]
@mrdoob @WestLangley I have a question for the both of you 😊 . Is it okay if i merge such trivial PRs by myself or is it always necessary that somebody of you approve these changes? I mean changes like correcting typos, cleaning up formatting issues or minor refactoring like this. Can i commit such things also directly to the `dev` branch? I just want to be on the safe side and not bother anyone 😅 .

**Comment by WestLangley** [comment]
@Mugen87 The boss needs to answer that. :)  Personally, I only merge PRs in trivial cases.

**Comment by mrdoob** [comment]
I prefer to do the merging myself for now. Somehow this helps me to keep things under control 😅

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
