### PR TITLE
Add iOS workaround to BoxGeometry

### LINKED ISSUE #9195: Documentation pages with iframe unreadable on iOS
##### Description of the problem 

Several documentation pages currently have an iframe used to display the browsers in docs/scenes/ (bones-browser, geometry-browser, material-browser). These pages cannot be read on iOS because the iframe grows continuously.

One fix is to add the iOS workaround from examples/index.html to each of the affected files. I have done this for BoxGeometry as an example, but this is only a partial fix. When viewing documentation pages through docs/index.html, the rotating cube appears when the file is first loaded but does not appear when subsequently selected. This problem after the fix affects Safari desktop and mobile, as well as Firefox mobile, but not Firefox and Chrome desktop. Reloading the page does display the rotating cube again but this is hardly desirable behavior.

Is there a better way to address this issue?

##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Mobile Safari

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

### PR DESCRIPTION
**Pull request by paulmasson**
Partial fix #9195

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, there needs to be a better solution that this hack I did in the iOS8 days... Does this still happen in iOS10?

/cc @spite

**Comment by mrdoob** [comment]
Found a nicer workaround! https://github.com/mrdoob/three.js/commit/c0537d2fba206459d90e800846074bd2d464d053

**Comment by paulmasson** [comment]
Cool! Only problem is yours is hard-coded for the examples page. How about my updated version for the documentation pages? More flexible.

**Comment by mrdoob** [comment]
I like it! How about a little bit more compact?

```js
scene.style.width = getComputedStyle( scene ).width;
scene.style.height = getComputedStyle( scene ).height;
scene.setAttribute( 'scrolling', 'no' );
```

**Comment by paulmasson** [comment]
Done. Shall I begin adding this fix to the other geometries?

**Comment by mrdoob** [comment]
Would the code still work if it was in this form?

```html
<iframe id="scene" src="scenes/geometry-browser.html#BoxGeometry"></iframe>

<script>
window.onload = function() {
	var scene = document.getElementById( 'scene' );
	// iOS iframe auto-resize workaround
	if ( /(iPad|iPhone|iPod)/g.test( navigator.userAgent ) ) {
		scene.style.width = getComputedStyle( scene ).width;
		scene.style.height = getComputedStyle( scene ).height;
		scene.setAttribute( 'scrolling', 'no' );
	}
}
</script>
```
That way the patch/workaround code is independent/separate from the iframe src.

**Comment by paulmasson** [comment]
Since I was using `window.onload`, setting the `src` attribute in the iframe was very inconsistent. Setting the source in the script was also inconsistent as I described in #9195.

I was previously under the impression that `onload` does not fire for Safari iframes, but it turns out it does. I've updated the workaround again to move the source to the iframe and add an `onload` function.

Better?

**Comment by mrdoob** [comment]
Almost!

I don't think you need to wait for the onload. The style applied to the iframe doesn't depend on the iframe being loaded.

I think you should be able to have the code execute directly. Seems to work fine for the examples page.

**Comment by paulmasson** [comment]
And of course you're right. Another misconception on my part.

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
And yes, adding it to the other pages would be great!

**Pull request merged**
