### PR TITLE
Manual MSAA pass for WebGL 1.x.  Supports 1, 2, 4, 8, 16, and 32 sample patterns.

### PR DESCRIPTION
**Pull request by bhouston**
This implements the standard full screen multi-sampling anti-aliasing approach but in a manual fashion by re-rendering the scene multiple scenes with proper camera jitter offsets.  This means it is _very slow_ compared to HW-based MSAA and is not a replacement for HW-based MSAA, and it is especially slow on mobile devices.

I have implemented it also in a slow fashion (but memory efficient fashion) in that it has an accumulation buffer and a sample buffer.  It renders the scene into the sample buffer and then accumulates that sample with appropriate scaling into the accumulate buffer, and it does this for each of the 1 to 32 samples.

I am sure there are more efficient ways to do this, but this code is relatively simple and it only requires one render buffer and no large-scale code changes.

**One bug left to fix:** As I ported this to the current version of ThreeJS from a previous version I ran into a bug I can not fix, at least not yet -- the accumulate buffer is no longer accumulating, it is just getting the last render - I am using the CompositeShader for that.  Somehow it is clearing itself?  If someone could help with that (it is some flag I must be missing somewhere), it would be appreciated.

Here is example using a variant of this MSAA shader (this variant works but is build on ThreeJS r66) changing its level of refinement live on Clara.io here when you stop moving:

https://clara.io/view/af983965-be37-48ae-a400-c828934193f6

(I wonder if this manual MSAA shader could be used in conjuction with the SMAA shader recently contributed here: https://github.com/mrdoob/three.js/pull/8090 by @mpk)

(This is also a manual WebGL 1.x compatible implementation of the HW MSAA approach taking in this PR: https://github.com/mrdoob/three.js/pull/8120 by @mattdesl)

### CODE REVIEW

**Comment by bhouston** [comment]
I fixed this up and it works nicely now.

It should be displaying here but for some reason it isn't loading the brick_diffuse.jpg texture on CI.ThreeJS.Org.  This issue is also affecting the SMAA example:

http://ci.threejs.org/api/pullrequests/8129/examples/webgl_postprocessing_msaa.html
http://ci.threejs.org/api/pullrequests/8129/examples/webgl_postprocessing_smaa.html

**Comment by gero3** [comment]
Sorry about that. It should be working right now.
I'm still looking at retrieving the files more consistently.

**Comment by WestLangley** [comment]
You need to update `examples/files.js`, too.

Perhaps we can add a toggle for the effect so we can more-clearly see what it is doing. [Example toggle](http://threejs.org/examples/webgl_lights_hemisphere.html). Maybe removing the spinning would be helpful?

**Comment by bhouston** [comment]
I made a level switcher?  Isn't that the same thing?

**Comment by WestLangley** [comment]
The existing smaa example does not have an on-off switcher. It was just a suggestion, anyway. : - )

**Comment by bhouston** [comment]
There is a bug in the weight calculation though.  I will fix it tonight.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by bhouston** [comment]
I've fix the bug in the weight calculation and I've turned off mipmaps, linear interpolation and anisotropic sampling in the textures.  It is now much more obvious as to the improvements the MSAA pass can make (at the cost of extreme slowdowns):

http://ci.threejs.org/api/pullrequests/8129/examples/webgl_postprocessing_msaa.html

**Comment by bhouston** [comment]
@WestLangley are the effects of the MSAA pass now obviously enough?

http://ci.threejs.org/api/pullrequests/8129/examples/webgl_postprocessing_msaa.html

**Comment by WestLangley** [comment]
@bhouston I am getting varying results. Try setting `camera.posiiton.z = 900`. I get much-reduced texture anti-aliasing in that case. Is that the point (?) -- or are you looking at the edges of the cube? There are not a lot of triangles in the geometry to look at.

**Comment by bhouston** [comment]
@WestLangley, this is just an manual implementation of MSAA:

https://en.wikipedia.org/wiki/Multisample_anti-aliasing

By making the camera further away you make the moire patterns more intense in the texture.  These are most visible at sample level 0, where it only does one sample (which technically isn't even MSAA), but these go away as you increase the MSAA level sample, at the cost of slower renders.

From my inspection, this algorithm appears to work as it is designed.  It is a resource intensive way of getting rid of all types of anti-aliasing artifacts, which is especially useful when they can not be easily compensated for in other ways such as texture mipmapping, anisotropic sampling, etc...

Let me know if you find any bugs as I think this is otherwise ready to merge.

**Comment by WestLangley** [comment]
Go ahead and merge. I will be glad to check the implementation when I get a chance. : - )

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by mrdoob** [comment]
Is this supposed to support wireframe too? I've added a wireframe cube and doesn't seem to look too good. I've also added it to the smaa example and see,s to produce better results.

**Comment by bhouston** [comment]
I took two screenshots and zoomed in of the wireframes:

1 sample (no MSAA) with zoom 3x:

image

32 samples with zoom 3x:

image

In the 32 sample version the lines are anti-aliased - notice the grayscale pixels along the edges.

The line appear thicker though.  I think this is because of the line drawing algorithm OpenGL ensures that one pixel is always drawn along the line (e.g. [Bresenham's line drawing algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm)), where as with triangles whether a pixel is filled is based on true coverage of the center location, and they do not have to have the connectivity that the line drawing algorithm enforces.

I do believe the MSAA is producing something akin to as if Wu's line drawing algorithm was used:

https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm

Although looking at the lines, there does seem to be missing anti-aliasing on the horiziontally drawn lines on one side but not the other -- not sure how that is happening but probably a bug or an interaction with a rounding algorithm used in the Bresenham line drawing algorithm:

image

**Comment by bhouston** [comment]
Ah, found the error.  It was just a buffer precision issue.  It is best to order the MSAA samples from closest to center to furthest for best results:

image

New PR coming.

**Comment by mrdoob** [comment]
Yay!

**Pull request merged**
