### PR TITLE
MeshPhysicalMaterial: Add clearcoatMap and clearcoatRoughnessMap.

### PR DESCRIPTION
**Pull request by donmccurdy**
Core parts of https://github.com/mrdoob/three.js/pull/18682, without the GLTFLoader changes for now. Note that `.x` and `.y` channels are used for the two textures respectively.

### CODE REVIEW

**Comment by Mugen87** [comment]
It would be also good to enhance `MaterialLoader` and `Material.toJSON()` so both properties can be serialized/deserialized properly.

https://github.com/mrdoob/three.js/blob/790811db742ea9d7c54fe28f83865d7576f14134/src/loaders/MaterialLoader.js#L259-L260

https://github.com/mrdoob/three.js/blob/790811db742ea9d7c54fe28f83865d7576f14134/src/materials/Material.js#L177-L185

**Comment by donmccurdy** [comment]
Done ✅

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Reminder: Docs need an update, too. But it's okay to do this in a later PR.

**Comment by donmccurdy** [comment]
Yep! I'll get the docs later.

**Comment by donmccurdy** [comment]
It's also lacking an example, but I was just planning to do that with the glTF portion.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
