### PR TITLE
(target dev) Allow arrow keys to move orbit controls diagonally

### PR DESCRIPTION
**Pull request by mgold**
Recreate #7340 to target the dev branch.

### CODE REVIEW

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7342

**Comment by mrdoob** [comment]
Sorry, but I had to revert to an older version of `OrbitControls`. Do you mind implementing again?

**Comment by mgold** [comment]
Sorry this took awhile. Force-pushed the new commit.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/9303#issuecomment-331659928

**Pull request closed without merging**
