### PR TITLE
BufferAttribute.setArray method chaining

### PR DESCRIPTION
**Pull request by takahirox**
Let's return `this` from `BufferAttribute.setArray()` and make it chain-able as other methods of `BufferAttribute` do.

### CODE REVIEW

**Comment by WestLangley** [comment]
Fine. How about returning `this` for `InterleavedBuffer.setArray()`, too?

And, of course, update the docs. :-)

Regarding `this` as a return value, @donmccurdy  had a suggestion: see https://github.com/mrdoob/three.js/pull/13816#issuecomment-379974132.

**Comment by takahirox** [comment]
Agreed. I was just missing `InterleavedBuffer.setArray()` and documents. About `method:this` in the doc, let's consider in another PR.

**Comment by takahirox** [comment]
BTW, I wanna and am gonna enable "method chaining", not only for loaders or attributes, but also for other modules. For example I found bunch of methods in `Object3D` and `BufferGeometry` that should be chain-able but are not yet.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
