### PR TITLE
Added dark mode button next to language select

### PR DESCRIPTION
**Pull request by Aelof3**
- Added script to the bottom of index.html to update color scheme
- Added style element to head via javascript
- Sends message to iframe viewer to update color scheme on change
- Added button to inputWrapper via javascript

### CODE REVIEW

**Comment by Aelof3** [comment]
- Added style block to head via javascript
- Added iframe listener to update color scheme when changed in parent

**Comment by Mugen87** [comment]
For testing: https://rawcdn.githack.com/Aelof3/three.js/patch-1/docs/index.html

**Comment by Aelof3** [comment]
Just a heads up the documents loaded in the viewer iframe only accept updates from the threejs.org domain, so it probably will not update the color scheme for whichever document is loaded on that test link

**Comment by Mugen87** [comment]
Thanks for the PR! However, I think I prefer a simple solution and not allow users to change between light and dark mode with a button.

**Comment by mrdoob** [comment]
This seems complicated...

**Comment by Aelof3** [comment]
I think the only complicated bit is passing the message to the chosen doc iframe to update the css there as well

**Comment by mrdoob** [comment]
@Aelof3 What's the use case? You want to force dark mode but your desktop is in light mode?

**Comment by Aelof3** [comment]
The issue I was having was that the linux distro I use doesnt specify my preference to the browser, like windows does, so I just came up with a way to have a switch for it. It isnt a big deal, just thought it might be handy for people that dont have their preferences reflected automatically

**Comment by mrdoob** [comment]
> The issue I was having was that the linux distro I use doesnt specify my preference to the browser

The bug is in the distro then 🤓

I think adding a theme selector to the editor makes sense, but I don't think the docs/examples UI should get more complicated because a linux distro lacks a feature...

**Comment by mrdoob** [comment]
Closing this. Sorry.

**Pull request closed without merging**
