### PR TITLE
Animation Authoring Update

### PR DESCRIPTION
**Pull request by tschw**
See commits for details.

### CODE REVIEW

**Comment by tschw** [comment]
It might be ripe to be added to `index.html`, but I wasn't sure whether it should best have a `webgl_*`, `misc_*`, or `misc_controls_*` name...

**Comment by mrdoob** [comment]
Lets start with `misc_*`.

**Comment by tschw** [comment]
I put it above `misc_animation_keys` which seems pretty much outdated. I didn't even know that one existed, until now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
