### PR TITLE
Added ImportMaps availability script

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

Show a message when the browser doesn't support Import Maps instead of failing silently.

### CODE REVIEW

**Comment by marcofugaro** [comment]
Hello @mrdoob there is now a polyfill for importmaps, what do you think about using it to start the migration to importmaps for other examples as well? 🙂 

We are using it on [this cannon-es-debugger example](https://pmndrs.github.io/cannon-es-debugger/) to make it run on firefox and safari as well.

This is the usage:

https://github.com/pmndrs/cannon-es-debugger/blob/34c4ba8824e2a8d273c8c4cee9790e1cff2abfed/index.html#L35-L48

**Comment by mrdoob** [comment]
Oh, that shim no longer requires doing `<script type="importmap-shim">`?

**Comment by marcofugaro** [comment]
Yess, it works with native syntax now.

The tradeoff is that the error in the console is still there, because the polyfill can't disable native module loading. But the example works nonetheless.

[More info in its readme](https://github.com/guybedford/es-module-shims).

**Comment by mrdoob** [comment]
> Yess, it works with native syntax now.

Interesting development... 🤩
I'll put it in the WebGPU examples for now.

/fyi @sunag

**Pull request merged**
