### PR TITLE
added antialias property to Reflector and Refractor options

### PR DESCRIPTION
**Pull request by LR17**
**Description**

Added antialias property to Reflector and Refractor options. If true, then the internal render target instance will be a WebGLMultisampleRenderTarget

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Hmm, I think should be `true` by default.

Or would it make more sense to rename `antialias` to `multisample` and set it to `4` by default?

**Comment by Mugen87** [comment]
`multisample` sounds indeed better! 

However, if we set it to `4` by default (or if `antialias` would be `true`), it's probably safer to implement a `isWebGL2` check. Otherwise apps will break when they upgrade and use a WebGL 1 rendering context.

**Comment by LR17** [comment]
I can change 'antialias' to 'multisample' if you prefer. Regarding the default value, what about backward compatibility?

**Comment by Mugen87** [comment]
Well, `0` would be the safest value. If `4` is used, things break with a WebGL 1 rendering context. 

Since WebGL 2 is now more widely spread than a few years ago, I think we should start with `4`. If too many people complain, we still fall back to `0`.

**Comment by LR17** [comment]
Changed `antialias `to `multisample`

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
For comparison:

https://raw.githack.com/LR17/three.js/antialias/examples/webgl_mirror.html
https://threejs.org/examples/webgl_mirror

**Comment by Mugen87** [comment]
Um, does it make sense to use a multisampled render target for any sort of distortion effect? I wonder if isn't better to disable the multisampling in `Water2`:

https://github.com/mrdoob/three.js/blob/a0de39b47e9104c3dfba4c270bf9973ff9f2a33a/examples/jsm/objects/Water2.js#L71-L81

Probably any refraction effect does not need multisampling.

@LR17 Sorry for the back and forth but would you revert the changes to `Refractor`?

**Comment by LR17** [comment]
Do you mean reverting `Refractor` to its original state before the pull request?

**Comment by mrdoob** [comment]
> Um, does it make sense to use a multisampled render target for any sort of distortion effect?

I think it does? It's like transmission in `MeshStandardMaterial`, no?

**Comment by Mugen87** [comment]
Yeah, it probably depends on what kind of refraction effect is implemented (meaning how much the light is distorted).

**Comment by mrdoob** [comment]
Ah, I see what you mean... But I still think setting `multisample` to 4 is the best default for both.

**Comment by LR17** [comment]
Do you want me to apply any other changes or leave this pull request as it is?

**Comment by Mugen87** [comment]
The PR looks good as it is 👍 .

**Comment by Mugen87** [comment]
Let me resolve the merge conflicts with new PR. It's a bit hard doing this via GitHub.

**Pull request closed without merging**
