### PR TITLE
Examples: Replaces UV Grid Texture

### LINKED ISSUE #17068: Examples: Replace UV debug texture.
##### Description of the problem

[UV_Grid_Sm.jpg](https://github.com/mrdoob/three.js/blob/dev/examples/textures/UV_Grid_Sm.jpg
) is actually wrong because (0,0) is located bottom left not top left. This was already reported here #13936.

Since then I've noticed this texture lead multiple times to confusion. We should definitely replace it with a correct visualization of the UV space.

Does anyone like to contribute a royalty-free texture that we can use in the project? @looeee did make a suggestion in #13936 however it was unfortunately not accepted.

@WestLangley It would be great if you can define what you mean with "more-conventional reference map"^^.

##### Three.js version

- [x] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by sciecode**
Fixes #17068.

And as suggested in https://github.com/mrdoob/three.js/issues/17068#issuecomment-513852481, adds
[uv_grid_opengl](https://rawcdn.githack.com/sciecode/three.js/335c3b00331242503afe9756ba213352eff14ddd/examples/textures/uv_grid_opengl.jpg)
[uv_grid_directx](https://rawcdn.githack.com/sciecode/three.js/335c3b00331242503afe9756ba213352eff14ddd/examples/textures/uv_grid_directx.jpg)

### CODE REVIEW

**Comment by WestLangley** [comment]
Maybe related, but for a separate PR:

I think the parametric geometries need to be checked. I know the plane vertex normals are negative, which is odd, so there is some weirdness going on...

**Comment by Mugen87** [comment]
I'm glad this issue is finally fixed.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
> I think the parametric geometries need to be checked. I know the plane vertex normals are negative, which is odd, so there is some weirdness going on...

see https://github.com/mrdoob/three.js/pull/12404#issuecomment-336640869

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
