### PR TITLE
Add webgpu async check

### PR DESCRIPTION
**Pull request by whatisor**
Related issue: #29916

**Description**
We want to use WebGPU capability check in nodejs project.

### CODE REVIEW

**Comment by Mugen87** [comment]
With #29933 merged, what parts of the existing `WebGPU.js` cause issues with node?

**Comment by Mugen87** [comment]
What kind of issues? Can you please be more specific?

Instead of adding a separate module, maybe adding `isAvailableAsync()` would also work.

**Comment by donmccurdy** [comment]
Node.js supports top-level await (TLA) in all active versions, but some tooling does not. Node.js v22+ has greatly improved ESM support over previous versions, with one notable limitation: CommonJS modules cannot import ESM modules that use TLA, for sync/async reasons.

But I'm not sure if CommonJS is related to the reported issues in Next.js. I'd like to reproduce the issue before we commit to a particular fix for it, see https://github.com/mrdoob/three.js/issues/29916#issuecomment-2487126519. Possibly there are other options. I would have hoped a [`'use client'`](https://react.dev/reference/rsc/use-client) directive in the Next.js component would be enough, in this case.

**Comment by whatisor** [comment]
The ideal is we want to remove all "global" stuff to make it best compatibility with node development.
Right now, I have no idea to support synced version of WebGPU.isAvailable() which is used in many examples folder.

**Comment by whatisor** [comment]
> wait in the module

It will create confliction until we update repo @type/three

**Comment by whatisor** [comment]
> The ideal is we want to remove all "global" stuff to make it best compatibility with node development. Right now, I have no idea to support synced version of WebGPU.isAvailable() which is used in many examples folder.

Also, I propose to update WebGPU and all example to async check (instead of global scope) because of limitation of current browser webgpu context checking.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/29919#issuecomment-2496619319.

**Pull request closed without merging**
