### PR TITLE
Examples: Fix toggle icon CSS issue.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issues:

Replacement for #19943.

**Description**

The solution is based on: https://stackoverflow.com/questions/25166234/css-first-child-without-certain-class

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev51/examples/index.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
FYI: I've updated `gh-pages`  with this change, see d3b006e11f976a8439f09ae1370ac693d0cecb08.

**Comment by mrdoob** [comment]
Oh! Good catch! Thanks!

**Pull request merged**
