### PR TITLE
PerspectiveCamera: added setHorizontalFOV() method

### PR DESCRIPTION
**Pull request by gonnavis**
Related issue: 
https://stackoverflow.com/questions/16462848/three-js-zoom-to-fit-width-of-objects-ignoring-height
https://discourse.threejs.org/t/how-can-i-resize-my-scene-to-be-100-of-the-windows-width-when-its-browser-resized-to-a-smaller-size/14135
https://stackoverflow.com/questions/13350875/three-js-width-of-view
https://discourse.threejs.org/t/camera-zoom-to-fit-object/936

**Description**

Almost all of my mobile projects need to adapt to window width instead of window height, so I think adding this `fitWidth` option may be useful to many people.

OrthographicCamera is controlled by the application to adapt to height or width. CubeCamera should not need this option, so only added to PerspectiveCamera.

I have never used the filmGauge-related properties of PerspectiveCamera, so I don't know what effect it will have on filmGauge or other fileds, but from testing, I think the change is OK.

[**fit window width Examples**](https://raw.githack.com/gonnavis/three.js/cb43fdda984f47855e27798c52e6ef1627b70107/examples/webgl_animation_cloth.html)

### CODE REVIEW

**Comment by gonnavis** [comment]
Hello @mrdoob , I just found out that you are already making similar changes https://github.com/mrdoob/three.js/pull/19619. I have searched before, but the keyword `width` is always included, so I didn't find it.

But I think my approach is very different, so I still keep this pr without closing it immediately.

I found from your modification that I forgot to copy the newly added attributes in the copy function, which has been updated.

**Comment by WestLangley** [comment]
Sorry, but I think assigning two different definitions to `camera.fov` is unwise. In three.js, `fov` is always the vertical fov.

**Comment by WestLangley** [comment]
Instead, I would add two methods to `PerspectiveCamera` -- just as we do with `.setFocalLength()`.

```js
setHorizontalFOV: function ( horizontalFOV ) {

	this.fov = Math.atan( Math.tan( horizontalFOV * MathUtils.DEG2RAD * 0.5 ) / this.aspect ) * MathUtils.RAD2DEG * 2; // degrees

	this.updateProjectionMatrix();

},

getHorizontalFOV: function () {

	return Math.atan( Math.tan( this.fov * MathUtils.DEG2RAD * 0.5 ) * this.aspect ) * MathUtils.RAD2DEG * 2; // degrees

},
```

To maintain a constant horizontal fov, do this:
```js
function onWindowResize( event ) {

	renderer.setSize( window.innerWidth, window.innerHeight );

	// maintain a constant horizontal fov
	const hfov = camera.getHorizontalFOV();
	camera.aspect = window.innerWidth / window.innerHeight;
	camera.setHorizontalFOV( hfov );

	render(); // if there is no animation loop

}
```

**Comment by gonnavis** [comment]
@WestLangley  Thanks! Sorry for the late reply, i'm digesting.

I am also worried about whether there will be any side effects of such direct modification. Your way is safe.

Can I directly modify this pr with your code? I desperately need a method that can let PerspectiveCamera adapt to the screen width.

**Comment by WestLangley** [comment]
>Can I directly modify this pr with your code?

Yes.

**Comment by gonnavis** [comment]
Thanks! I'm updating.

**Comment by gonnavis** [comment]
I'll re-open and solve conflicts if needed.

**Pull request closed without merging**
