### PR TITLE
Moved bilinear filtering of shadow maps into the shader.

### PR DESCRIPTION
**Pull request by MiiBond**
I moved the bilinear filtering of shadow maps into the fragment shader. Previously, the filtering on the shadowmap was set to THREE.LinearFilter and this won't work properly for shadow filtering. For proper PCF, the filtering needs to be done after the depth comparison. i.e. the filtering is done on the shadow value, not the depth value.

This produces much softer shadows than the current code.  It is, however, a bit more expensive, so perhaps this is something that has already been considered and rejected?

### CODE REVIEW

**Comment by mrdoob** [comment]
Took me 3 years, but now I know that the culprit of the ugliness was `shadowDarkness` 😅

**Comment by MiiBond** [comment]
Haha :) Yeah, it's a lot harder to hide the artifacts when modulating shadow colour rather than just cancelling out the light that cast the shadow. You can still get ugliness along edges parallel to the light, of course, even with correct shadow colouring.

**Comment by WestLangley** [comment]
>You can still get ugliness along edges parallel to the light.

@MiiBond Yes, but don't you mean "artifacts on _faces_ parallel to the light direction"?

**Comment by mrdoob** [comment]
> Haha :) Yeah, it's a lot harder to hide the artifacts when modulating shadow colour rather than just cancelling out the light that cast the shadow.

I'm changing it so shadows cancel the light now. Things are looking much nicer!
Still trying to find an approach that works well in all platforms though...

**Comment by MiiBond** [comment]
Indeed, I meant _faces_ :)

What issues are you seeing across platforms? In our custom shader code, I just store the shadow values (0-1) for each shadow map in an array and then apply them when I do directional lighting. I haven't noticed any issues on other platforms, I don't think.

Are you leaving in the ability to use modulative shadows? It can be a useful feature when combined with IBL or other lighting techniques where multiple light sources are combined/approximated. Back in the day, UE3 used modulative shadows by default for their light environments.

**Comment by mrdoob** [comment]
> I just store the shadow values (0-1) for each shadow map in an array and then apply them when I do directional lighting. I haven't noticed any issues on other platforms, I don't think.

How do you access the array?

**Comment by WestLangley** [comment]
>I'm changing it so shadows cancel the light now.

I agree that is the correct way. Thing is, I expect you will get a lot of complaints if you remove the `shadow.darkness` property completely.

**Comment by mrdoob** [comment]
>> I'm changing it so shadows cancel the light now.

> I agree that is the correct way. Thing is, I expect you will get a lot of complaints if you remove the `shadow.darkness` property completely.

Yeah, will have to see how to deal with that. Bringing back shadowMask shouldn't be too hard though.

**Comment by MiiBond** [comment]
> How do you access the array?

Just with an integer index, iterated with a for loop limited by defines. The catch is that the array matches the length of the directional lights + spot lights and is pre-populated with 1.0 values. Then, the shadow code writes shadow values to the array for the number of shadow-casting lights. The lights that don't cast shadows have 1.0 as their shadow values.

**Comment by mrdoob** [comment]
Interesting! 😀

**Pull request merged**
