### PR TITLE
Blender exporter: work around #7631, export all actions

### PR DESCRIPTION
**Pull request by daniel-nth**
Undo of 7812b25 as @bhouston suggested.

### CODE REVIEW

**Comment by mrdoob** [comment]
@bhouston sounds good?

**Comment by bhouston** [comment]
Yeah, this is a fix for the bug we introduced.

The Blender ThreeJS exporter still exports too much in the case were there are multiple characters in the same scene, but that needs a more complex fix which can come later.

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by repsac** [comment]
> The Blender ThreeJS exporter still exports too much in the case were there are multiple characters in the same scene, but that needs a more complex fix which can come later.

I know I am out of the loop on this but will add my 2 cents before disappearing: I do agree that the exporter could export too much but also I would expect people to handle things like anim cycles in in unique scenes rather than trying to do it all in one scene. Some problems can be avoided by simply adhering to responsible work flows. Call me crazy but after all my years in running feature pipelines this is what I expect out of people.

However in corner cases where there would be multiple animations (and there is no other way around it) then it would be nice to have something more robust. In my defense this was something I tried to figure out but the way Blender handles action associations under the hood makes it really difficult to handle this. Either it can't be done or it can but the solution is far from clear within the API, like trying to discern objects used by instances because when you query the `users` attribute and all it returns is an integer of number of users rather than a manifest of pointers (which is why some of my logic for managing object/mesh relationships turned out to be quite ugly) to the correct nodes.

These were some of the things that took a flame thrower to my short fuse and eventually burned me out.

**Comment by antont** [comment]
With our game / realtime oriented animated models there seems to always be a dedicated blend file for each model -- I can't think of any exceptions now. So this should work fine for those, thanks.

I'll take a look at the API and perhaps ask from blender devs on irc if they have ideas for proper fixes. Will have a chance to check a bit in the evening.

**Comment by daniel-nth** [comment]
Thank you!

**Comment by bhouston** [comment]
@repsac You are completely right that this is how characters should be created.

I guess in our case an individual was creating something like a cinematic experience, where they had multiple characters interacting in a scene and wanted to export it as a pre-built scene and just play the whole thing back together - basically a cut scene.  I can understand the value of this because in ThreeJs it is just a simple playback rather than having to recoordinate all the elements, which takes some coding.

I think that this type of cinematic export is a different type of export and we should have different modes to support it, rather than screwing up the individual character export mode that is critical to an interactive game experience.

**Pull request merged**
