### PR TITLE
Examples: Removed webgl_loader_gltf_extensions

### PR DESCRIPTION
**Pull request by mrdoob**
**Description**

I think, at this point, these models make gltf look bad 🙈

### CODE REVIEW

**Comment by Mugen87** [comment]
I think it's also better to have examples for showcasing just a single extension rather than `webgl_loader_gltf_extensions`.

**Comment by donmccurdy** [comment]
Plenty of other glTF examples without these, agreed! I think this example had become too long/complex to be useful anyway.

**Comment by WestLangley** [comment]
I also do not think it is a good idea to have use cases (i.e., extensions) hidden behind GUI menu items, because CI will not test it.

**Comment by takahirox** [comment]
Yeah, `webgl_loader_gltf_extensions` design was bad for CI test.

Now, some glTF extensions (specular-glossiness, unlit, and lights?) are not in our examples. For the testing purpose, it would be good to somehow test them in `test` directory? (I don't think they are not looking so interesting that we may not need to make showcasing examples for them.)

**Comment by mrdoob** [comment]
I've heard they're trying to deprecate specular-glossiness.

**Comment by takahirox** [comment]
Yeah, glTF has specular extension now. So off topic, I'm personally thinking of specular-glossiness extension support to my https://github.com/takahirox/three-gltf-extensions repo.

**Comment by donmccurdy** [comment]
> Now, some glTF extensions (specular-glossiness, unlit, and lights?) are not in our examples

I don't think it is necessary that examples exist for every glTF extension. Creating unit tests for them would be ideal.

The GLB used for https://threejs.org/examples/?q=unreal#webgl_postprocessing_unreal_bloom could probably be switched to unlit though (`gltf-transform unlit in.glb out.glb`)

> I'm personally thinking of moving specular-glossiness extension support to my https://github.com/takahirox/three-gltf-extensions repo.

Let's start an issue about this, there may be a few options and considerations here.

**Comment by mrdoob** [comment]
> The GLB used for https://threejs.org/examples/?q=unreal#webgl_postprocessing_unreal_bloom could probably be switched to unlit though (`gltf-transform unlit in.glb out.glb`)

That sounds good to me 👍

**Pull request merged**
