### PR TITLE
Examples: Fix bug in weblg_clipping_advanced.html

### PR DESCRIPTION
**Pull request by WestLangley**
Visualization planes were not rendering.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Why were not rendering though?

**Comment by WestLangley** [comment]
The example is pretty complicated, but the short answer is the author was updating the matrix directly without disabling matrix-auto-update.

**Comment by mrdoob** [comment]
Ah I see!

**Pull request merged**
