### PR TITLE
Add VREffect preRender hooks

### PR DESCRIPTION
**Pull request by mkeblx**
Adding L/R hooks. Useful for things like #9073, but also a lot of other similar scenarios where need to call per-camera.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, this is a bit of a hack. The actual solution is to implement some sort of `ArrayCamera` which is on my TODO list.

**Comment by mkeblx** [comment]
Okay. Yes that would be nice to have that integrated into renderer, as discussed previously. Note that would still need callback(s)/events between eye rendering.

**Comment by donmccurdy** [comment]
In #10851, `object.onBeforeRender` seems to be a helpful workaround (it is called once per camera already).

**Comment by Mugen87** [comment]
`VRControls` and `VREffect` are now deprecated, see #11301 (comment)

**Pull request closed without merging**
