### PR TITLE
Update OrbitControls.js

### PR DESCRIPTION
**Pull request by mtsee**
Add a seek event, in the execution of drag, zoom, trigger this seek method, eg: do react performance optimization, animating do update() is very bad. 
use:  this.orbitControls.on('seek', () => {  do somthing });

### CODE REVIEW

**Comment by gkjohnson** [comment]
What's your goal with "seek"? Does the "change" event let you achieve what you're looking for?

```js
controls.addEventListener('change', () => {
  // controls have been moved
});
```

**Comment by mtsee** [comment]
When used on react or vue, the controller needs to render when zooming or dragging, but currently only render when animate does, which can be very expensive.

**Comment by gkjohnson** [comment]
If I'm understanding correctly and you only want to rerender the scene or your application when the controls are dragged or zoomed then you can achieve that with the `change` event I listed above:

```js
controls.addEventListener('change', () => {
  // rerender scene or application component
});
```

**Comment by mtsee** [comment]
thanks! just this `change`

**Pull request closed without merging**
