### PR TITLE
Examples: Add galaxy

### PR DESCRIPTION
**Pull request by brunosimon**
**Description**

A simple animated WebGPU galaxy based on Three.js Journey lessons.
The first of a dozen of TSL examples.

### CODE REVIEW

**Comment by Mugen87** [comment]
If you plan to add more examples like that, maybe we can all name them like `webgpu_tsl_*`. In this case: `webgpu_tsl_galaxy`.

**Comment by brunosimon** [comment]
Looks like the generated screenshot doesn't match.
I just run `npm run make-screenshot webgpu_tsl_galaxy` and then commit.
Tested from windows and MacOS.
Am I doing something wrong?

**Comment by Mugen87** [comment]
If you have the option, generate the screenshot from a Windows device (because the CI uses Windows as well). Besides, make sure you have latest build files on your local system. They are not built automatically when generating a screenshot so make sure to run `npm run build` before `npm run make-screenshot`.

**Comment by brunosimon** [comment]
All good 👍
I'll start working on the other TSL examples.

**Comment by sunag** [comment]
Bruno did some changes because WebGPU/WGSL `pow()` with negative values ​​was not working on Windows, but it works on MacOS. /cc @mrdoob

**Pull request merged**
