### PR TITLE
Clean unused and undeclared variable Bones

### PR DESCRIPTION
**Pull request by Itee**
All is in the title

### CODE REVIEW

**Comment by Mugen87** [comment]
The code style and quality of this loader is in great need of improvement. ESLint (with mdcs preset) shows 1759 errors and 13 warnings 😭 . 

Any chances you can clean up the rest of the loader 😊 ? You can use Atom + ESLint plugin to see the linter feedback right in your editor.

image

**Comment by Itee** [comment]
With pleasure !
And my IDE is already set for MrDoob style 😁

**Comment by Itee** [comment]
I have still 203 warnings about lot of others things that are wrong in this file... but for eslint this is ok right now !

A little question, could we already use let and const instead var ? Or this will cause backward compatibility issus ?

**Comment by Mugen87** [comment]
We still should focus on `var`.

**Review by Mugen87 — APPROVED** [review]

**Comment by Itee** [comment]
Ok

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
