### PR TITLE
Package.json: Added "sideEffects": false

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #16317

**Description**

I think the only way of understanding the ramifications of setting `"sideEffects": false` is by giving it a go.

### CODE REVIEW

**Comment by mrdoob** [comment]
Interestingly, after setting `sideEffects: false`, the build now lose [polyfills.js](https://github.com/mrdoob/three.js/blob/dev/src/polyfills.js).
I think [it's time to remove them](https://twitter.com/modelviewer/status/1348691038802624512) anyway.

**Comment by Mugen87** [comment]
If you want to stop support for IE11, I'd like to revive #18091 😇 .

**Comment by mrdoob** [comment]
@Mugen87 what I was going to do next is adding the required polyfills in https://threejs.org/examples/misc_legacy.html

**Comment by mrdoob** [comment]
@Mugen87 Yes, I think reviving #18091 makes sense. The clean up to CSS3DRenderer definitely. But for the common use case (WebGL) I think it'd be good if we can point people to misc_legacy.html just so they know it's possible to make it run but it's up to them to add the required polyfills.

**Comment by Mugen87** [comment]
Okay, sounds fine. I'll make a new PR for `CSS3DRenderer` only.

Also updated the migration guide to highlight the polyfills change: https://github.com/mrdoob/three.js/wiki/Migration-Guide#r125--r126

**Comment by DefinitelyMaybe** [comment]
@marcofugaro I believe with `sideEffects:false` we can remove the `/*#__PURE__*/` comments?

**Comment by marcofugaro** [comment]
that's a question for @ianpurvis, could you test with shakediff if the `/*@__PURE__*/` annotations are still needed? 🙏

**Comment by mrdoob** [comment]
@Mugen87 I think after https://github.com/mrdoob/three.js/commit/d401181625d49b86cc910ed1fec8745c07b97579 and https://github.com/mrdoob/three.js/commit/b4b24e310cbb825b8caf1eb7536513c4c33d21b9, #18091 is done?

**Comment by Mugen87** [comment]
Yes, indeed! There are some minor documentation changes left but these can be handled later.

**Pull request merged**
