### PR TITLE
Allow the use of TransformControls simultaneously with other controls

### PR DESCRIPTION
**Pull request by valette**
by invoking event.preventDefault() and event.stopPropagation() only if the control is actually involved.

### CODE REVIEW

**Comment by satori99** [comment]
This interests me

I have been adding similar code to scenes with multiple controls to enable things having shift-mouse-drag rotate lights and normal mouse-drag rotating the camera.

It would be great if all the control types played nice with each other.

**Comment by mrdoob** [comment]
@arodic looks good?

**Comment by valette** [comment]
I have also just pushed a patch for the dispose() method in this branch

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
