### PR TITLE
WebGPURenderer: Add `aoNode` to NodeMaterial

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
**Description**

This PR adds the possibility to override the `ambientOcclusion` node of a material.

*This contribution is funded by [Utsubo](https://utsubo.com)*

### CODE REVIEW

**Comment by RenaudRohlinger** [comment]
@Mugen87 CI seems to break because of `webgl_loader_gltf_dispersion`. Any idea?

**Review by sunag — APPROVED** [review]

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/28051#issuecomment-2033954996

Alternatively, can you try to regenerate the screenshot?

**Comment by RenaudRohlinger** [comment]
Unfortunately I believe that we do share the same device (Macbook Pro M1 Max). 😄

**Comment by Mugen87** [comment]
I'll try it later on a Windows notebook. Let's ignore the failure for now...

**Pull request merged**
