### PR TITLE
Ldraw example update

### PR DESCRIPTION
**Pull request by gkjohnson**
Related issue: #22188

**Description**

- Fix some lint issues in `webgl_loader_ldraw` (double quotes -> single quotes).
- Remove `outputEncoding = sRGBEncoding` because the the loaded LDraw colors are sRGB.
- Remove `envMapIntensity: 0.3` from LDraw material.
- Revert to use RoomEnvironment (and remove LDrawEnvironment) which is now bright enough with the above change.

| BEFORE | AFTER |
|---|---|
| image | image |

And for some more context here's how it would look if everything were converted to Linear color before rendering to sRGB output with ACES tone mapping:

<image src="https://user-images.githubusercontent.com/734200/127092518-ac78a7cf-6549-4a0d-af92-35614fac0bec.png" width="400px"/>

cc @WestLangley

### CODE REVIEW

**Comment by Mugen87** [comment]
Seems the E2E screenshot for the example needs an update.

**Comment by mrdoob** [comment]
I'll merge and regenerate the screenshot.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> And for some more context here's how it would look if everything were converted to Linear color before rendering to sRGB output with ACES tone mapping:
>
> <image src="https://user-images.githubusercontent.com/734200/127092518-ac78a7cf-6549-4a0d-af92-35614fac0bec.png" width="400px"/>

That looks very good!

**Pull request merged**
