### PR TITLE
Examples: Add RoomEnvironment to alpha hash example

### PR DESCRIPTION
**Pull request by donmccurdy**
Related:

- https://github.com/mrdoob/three.js/pull/26341

### CODE REVIEW

**Comment by WestLangley** [comment]
This is what I got when I set roughness to 0.2.

Screenshot 2023-06-28 at 1 52 40 PM

**Comment by Mugen87** [comment]
Do you mind setting the `useLegacyLights` flag to `false` like in all other examples?

**Comment by donmccurdy** [comment]
> Do you mind setting the useLegacyLights flag to false like in all other examples?



Done. 👍

> if you are using RoomEnvironment, I would expect to see tone mapping and exposure set.

While I agree on the importance of tone mapping in any lit scene, I'm not sure that I'm supportive of putting ACES Filmic on all of our examples as a default (or our other current tone mapping choices, for that matter). If that is the proposed direction, perhaps we can discuss in a new thread?

**Comment by donmccurdy** [comment]
It seems the CI is failing on this example. Perhaps the alpha hashing is non-deterministic across GPUs? I've added it to the exception list for now.

**Pull request merged**
