### PR TITLE
Ray: Set direction to 0, 0, -1 by default.

### PR DESCRIPTION
**Pull request by mrdoob**
Every time I user `Ray` I find myself setting the direction to `0, 0, -1`
Also, I doubt `0, 0, 0` as direction is any use so people are probably changing it anyway?

@WestLangley @Mugen87 what do you guys think?

### CODE REVIEW

**Comment by WestLangley** [comment]
It's fine with me... Just remember to update the docs. ;-)

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Oh wait, we should adjust this line in the unit test:

https://github.com/mrdoob/three.js/blob/ef17d6e80034a6e21d78e7183c04742c7e312359/test/unit/src/math/Ray.tests.js#L30

**Comment by WestLangley** [comment]
>Oh wait

Right. Direction vectors in three.js are assumed to have unit length. We should never have set the default to the zero vector.

**Comment by mrdoob** [comment]
Thanks @mrdoob! 😆

**Pull request merged**
