### PR TITLE
add IS_VERTEX and IS_FRAGMENT to shader defines

### PR DESCRIPTION
**Pull request by pailhead**
Allows for adding stuff to commons chunk for example.

https://github.com/mrdoob/three.js/pull/10750

### CODE REVIEW

**Comment by mrdoob** [comment]
If I remember correctly, you're not supposed to add anything before the `precision` line.

**Comment by pailhead** [comment]
You are right, I messed something up and added this thing twice. Still good to have per that other discussion?

**Comment by mrdoob** [comment]
Hmm, I cannot think of any specific use case for this right now, but I suspect it is indeed something handy to have.

**Comment by WestLangley** [comment]
>Hmm, I cannot think of any specific use case for this right now, but I suspect it is indeed something handy to have.

It can't be handy if a use-case cannot be identified. :)

What is the compelling use-case?

**Comment by pailhead** [comment]
Cant link to the comment in the review in the other thread. Mrdoob suggested some glsl should be in the commons chunk but it exists in both very and frag. Say you want to add 'attribute float u_should_exist_in_all_shaders' you can't use commons.

**Comment by pailhead** [comment]
Just to make this idea seem less idiotic, it is now becoming more obvious what was the use case for this.

`common.glsl` seemed like the most appropriate place to append code that should be in global scope. It is guaranteed to be in every shader, we would have access to the functions. The reason why it doesn't work is because the same chunk ends up in both vert and frag shaders.

Basically it was supposed to do what `% global_vertex %` and `% global_fragment %` should do in:

https://github.com/mrdoob/three.js/issues/11475

**Comment by pailhead** [comment]
Using the `onBeforeCompile`, i think i would really like this feature.

**Comment by mrdoob** [comment]
Could you elaborate?

**Comment by pailhead** [comment]
```
const myGLSL = 'attribute vec3 aMyAttribute;\n`

myMaterial.onBeforeCompile( shader=>{
  shader.vertexShader = myGLSL + shader.vertexShader // messes up extensions and such?
  
  shader.vertexShader = shader.vertexShader.replace( '#include <what>`, myGLSL + ... )
})
```

Actually now having written it like this it's not so much of a problem. I was thinking of something like

```
float sharedFunction( float i ) {}

#ifdef IS_VERTEX
attribute vec3 aMyAttr;
#endif
```
```
const myGlobalReplaceChunk = THREE.ShaderChunk.global + myGLSL
```

It could be like the first super mini step towards the properly named hooks etc. but maybe not worth it, sorry for wasting time.

**Pull request closed without merging**
