### PR TITLE
GLTFLoader: Implement KHR_draco_mesh_compression

### PR DESCRIPTION
**Pull request by donmccurdy**
Supports use of Draco compression on geometry in a glTF asset. [Specification](https://github.com/KhronosGroup/glTF/pull/874). [Demo](https://rawgit.com/donmccurdy/three.js/feat-gltf-draco-extension-v4/examples/webgl_loader_gltf_extensions.html).

I'm planning to include a dedicated example (`loaders / gltf / draco`) but haven't got that ready yet. This PR just includes the Draco extension as an option on several of the existing examples. Up for discussion whether we want to merge with with these, remove the examples and add them in a future PR, or wait for a nicer dedicated example.

Thanks @fanzhanggoogle for support on this PR and the rest of the Draco team. 🙂

/cc @takahirox

### CODE REVIEW

**Comment by donmccurdy** [comment]
PR for the Draco extension [has been merged](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_draco_mesh_compression).

Here's a demo with drag-and-drop support for any glTF+Draco model: https://gltf-viewer-experimental.donmccurdy.com/.

**Comment by mrdoob** [comment]
Should this be merged then?

**Comment by donmccurdy** [comment]
One more thing I want to do here is check all of the latest glTF+Draco sample models.. otherwise if there are no code comments, I think it is OK to merge.

/cc @zellski in case you've come across any issues so far.

**Comment by zellski** [comment]
@donmccurdy I did minimal testing, but what I did do worked fine!

**Comment by donmccurdy** [comment]
Ok, fixed one last thing to ensure that Draco meshes referenced multiple times are only decoded once. Sample models are all loading fine. I think this is ready. 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
Sorry for the late reply after merging. (Finally I've completed a tons of paperwork and I'm back to dev!)

1. Duplicated draco decoders

Seems like draco decoders are duplicated in `examples/js/loaders/draco/` and `examples/js/loaders/draco/gltf/`. If I'm right, we can remove the ones in `examples/js/loaders/draco/`.

2. What do you think of moving draco decoders to `examples/js/libs(/draco)`?

I'm considering if it'd be good to move draco decoders to `examples/js/libs` or `examples/js/libs/draco` because Three.js doesn't manage the draco decoders but copies from https://github.com/google/draco/tree/master/javascript. Users can easily understand that master files of decoders are in another repo if putting them under `libs`.

3. Need more explanation about Draco loader/decoder in Doc

In the doc, I feel we need some more explanation about `DRACOLoader`

- users need to add `<script src="DRACOLoader.js"></script>` in their code to use draco loader
- what files should be under the decoder path

Adding a link to https://github.com/google/draco/blob/master/javascript/example/README.md  to doc would be good.

**Comment by donmccurdy** [comment]
> 1. Duplicated draco decoders

The Draco decoders for use with the glTF extension are locked to a particular version of the Draco bitstream, until/unless a future version of the extension bumps them. The ones in `examples/js/loaders/draco/` might be compatible now, I think, but may not remain so.

> 2. What do you think of moving draco decoders to examples/js/libs(/draco)?

That sounds like a good idea, yes.

> 3. Need more explanation about Draco loader/decoder in Doc

That would be good to document, sure. I am planning to add a `loaders / gltf /draco` standalone example, but haven't got a model that quite fits the bill yet.

**Comment by donmccurdy** [comment]
And, welcome back! 😃

**Comment by takahirox** [comment]
>1. Duplicated draco decoders
The Draco decoders for use with the glTF extension are locked to a particular version of the Draco bitstream, until/unless a future version of the extension bumps them. The ones in examples/js/loaders/draco/ might be compatible now, but will not remain so.

Ah, that's the reason why `webgl_loader_draco` example uses the decoders in `examples/js/loaders/draco/` while `webgl_loader_gltf_extensions` examples uses the ones in `examples/js/loaders/draco/gltf/`.

Hm, I think we need readme in `examples/js/loaders/draco/` explaining it for now at least. Two decoders in the repo without any explanation are confusing to users/devs.

**Comment by donmccurdy** [comment]
Updated via #13351

**Pull request merged**
