### PR TITLE
Examples: Update unreal bloom example.

### PR DESCRIPTION
**Pull request by donmccurdy**
~Per https://github.com/mrdoob/three.js/issues/12903#issuecomment-405050550, do we want to replace some of the current JSON examples? If not we could also create a `gltf / animation` example.~

Updates the bloom pass example to use a holographic-style model. See [this blog post](https://blog.sketchfab.com/art-spotlight-primary-ion-drive/) for details.

| before | after |
|---|---|
| screen shot 2018-08-04 at 12 06 15 am | screen shot 2018-08-04 at 12 06 17 am |

[Source](https://sketchfab.com/models/d3f50a66fee74c6588dd9bc92f7fe7b3) (CC-Attribution), 6 MB.

~Temporary demo: https://rawgit.com/donmccurdy/three.js/examples-keyframes-glb/examples/webgl_animation_keyframes.html~

Temporary demo: https://rawgit.com/donmccurdy/three.js/examples-keyframes-glb/examples/webgl_postprocessing_unreal_bloom.html

### CODE REVIEW

**Comment by Mugen87** [comment]
I think this is a good idea.

BTW: Have you considered to Draco-compress the asset?

**Comment by mrdoob** [comment]
@looeee agreed 👌

**Comment by donmccurdy** [comment]
We could remove the extra GUI logic for adjusting the bloom filter, but this particular model doesn't look right without some post processing. If we want to use a different model instead, would [any of these](https://github.com/mrdoob/three.js/issues/12903#issuecomment-410160086) work better? I'm just filtering on Sketchfab by animated+downloadable, and looking for smaller models — a lot there are texture-heavy.

If we have an example we like, I can look into optimizing or compressing it.

**Comment by takahirox** [comment]
> I don't really understand the difference between these two examples:

Personally I prefer merging.

**Comment by mrdoob** [comment]
How about one of these?
https://sketchfab.com/models/294e79652f494130ad2ab00a13fdbafd
https://sketchfab.com/models/94b24a60dc1b48248de50bf087c0f042

**Comment by takahirox** [comment]
Tokyoooo 😆

**Comment by donmccurdy** [comment]
Little Tokyo is not so little (50 MB, mostly textures) but there are a lot of duplicate textures for some reason. I'll try cleaning that up and see how compact it can be... 😅

**Comment by takahirox** [comment]
Never mind, I just happily yelled because the asset reminded me of Japan hehe.

**Comment by mrdoob** [comment]
@donmccurdy can we replace the TorusKnot with the animation in this PR in https://threejs.org/examples/webgl_postprocessing_unreal_bloom.html?

**Comment by donmccurdy** [comment]
> can we use the current animation in this PR in https://threejs.org/examples/webgl_postprocessing_unreal_bloom.html instead of the TorusKnot?

Sounds good to me, how does this look?

**Comment by mrdoob** [comment]
Looks great!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
