### PR TITLE
Simplifying Object.lookAt() and adding high-level Object.lookAtObject3D() method #15267

### PR DESCRIPTION
**Pull request by lguminski**
Solves #15267

### CODE REVIEW

**Comment by WestLangley** [comment]
You are redefining what `Object3D.lookAt( target )` does when you declare that `target` is not in world space but in the object's parent's space. This will break existing three.js apps. Such a redefinition is almost surely not going to be acceptable.

Also, your methods do not appear to keep the object "right-side-up" in world space. Are you aware that `lookAt()` does more than just orient the object to face a particular direction?

**Comment by Mugen87** [comment]
Yes, this parametrization is unusual. Unity's `Transform.lookAt()` method also defines the target position in world space.

**Comment by lguminski** [comment]
@WestLangley @Mugen87 thank you for the comments. Let me first address your concerns about backward compatibility of this reimplementation:

- if object is connected to the scene or is parentless (like a detached camera), the change is fully backwards compatible, because `this.matrix` equals `this.matrixWorld`.
- if the object had a parent, then the change _is not_ backwards compatible. My point, however, is that such objects were never properly handled anyway, and that was explicitly stated in [documentation](https://threejs.org/docs/#api/en/core/Object3D.lookAt): "_This method does not support objects with rotated and/or translated parent(s)_."

The latest version (r98) introduced handling of rotated parents, but the disclaimer in the [documentation](https://threejs.org/docs/#api/en/core/Object3D.lookAt) remained, so I don't think anyone started using the method in that way.

The advantage of this reimplementation is that in case a camera is bound to a moving parent, like:

> movingObject.add(camera);
> controls = new THREE.OrbitControls(camera);

, then the behaviour of `OrbitControls` becomes consistent with what you would expect i.e. it respects the rotation of the parent, allowing you for a smooth navigation around the child ([demo](http://jsfiddle.net/lguminski/24ahxn5w/show)).

In addition, this PR introduces a new method (`lookAtObject3D()`) that correctly rotates object toward any other object in the scene. (The `r98` version of `lookAt()` still requires users to recalculate the target object's position to `x`, `y`, `z` coordinates in world space themselves.  The `lookAtObject3D()` method does the work for them.)

If the backwards compatibility is still a concern, you could introduce this implementation under another name (like `localLookAt()`), but then the implementations of `OrbitControls` and `TrackballControls` would need to be touched, to make use of this method instead of `lookAt()`.

I cannot tell anything about the Unity convention as I don't know that system. I also don't know if the [original problem](https://github.com/mrdoob/three.js/issues/15267) that triggered the PR, exists in that system or not.

**Comment by WestLangley** [comment]
@lguminski So, with this PR, if I want an object to look at the world origin, I can't call `object.lookAt( 0, 0, 0 )`. Instead, I must call `object.lookAt( x, y, z )`, where `( x, y, z )` are the coordinates of the world origin in the frame of reference of the object's parent. Correct? And, how will the object be oriented relative to `object.up`?

Also, can you please respond to my question above?

>Are you aware that lookAt() does more than just orient the object to face a particular direction?

**Comment by lguminski** [comment]
@WestLangley with this PR, 

    object.lookAt( 0, 0, 0 );

rotates object toward the world origin if the object's frame reference is world (i.e. `object.parent` is `null` or `object.parent` is `scene`). So for such objects nothing changes, and the PR is backward compatible.

> Also, your methods do not appear to keep the object "right-side-up" in world space. Are you aware that lookAt() does more than just orient the object to face a particular direction?

I understand that. For objects that I just mentioned (i.e. which are in the world space), "right-side-up" in world space is preserved. So again full backward compatibility.

Please correct me if I am wrong, but what I am saying is that this change is not backward compatible only for users who did not respect your disclaimer ("This method does not support objects with rotated and/or translated parent(s)."). Such users will need to modify their code from `object.lookAt( 0, 0, 0 );` to:
    
    const WORLD_CENTER = new THREE.Object3D();

    o.lookAtObject3D( WORLD_CENTER );

if they want to keep old behaviour.

Obviously it would be nice to support all old behaviours, and I can understand that. In this case, however, it is like trying to support use cases, which you explicitly said that you don't support ("_This method does not support..._"). And if I would have on one hand the decision to support unsupported use cases, and on the other the simplification of the code and fixing broken use cases (this broken `OrbitControls` issue), I would decide for the latter. But obviously I am not maintainer of this code, so it is not my decision.

**Comment by lguminski** [comment]
One more comment. The code

    const WORLD_CENTER = new THREE.Object3D();

    o.lookAtObject3D( WORLD_CENTER );

keeps "right-side-up" orientation relative to parent. Not to world. So in the sense of orientation it is not exactly the equivalent of `object.lookAt( 0, 0, 0 );` behaviour added in r98 version.

But the r98 support for objects with parents is inactive, because the documentation still says that such objects are not supported (the disclaimer "This method does not support objects with rotated and/or translated parent(s)." is still in documentation). Therefore you don't have any obligation to preserve backward compatibility with r98 for this use case.

That's why I still believe, that this PR will make three.js more robust without any side-effects. And this is probably the last moment the code can be fixed in a clean way. If your disclaimer wouldn't be in documentation, then the only way to fix the `OrbitControls` issue without affecting users, would be through the workaround with the second camera (explained in the issue).

**Comment by WestLangley** [comment]
As I said,

>So, with this PR, if I want an object to look at the world origin, I can't call object.lookAt( 0, 0, 0 ). Instead, I must call object.lookAt( x, y, z ), where ( x, y, z ) are the coordinates of the world origin in the frame of reference of the object's parent.

I believe that concept is a bit too complex for most users.

Also, in your `OrbitControls` demo, where I have added world axes for clarity, you can see that the camera is upside down relative to world space.

screen shot 2018-11-17 at 7 25 42 pm

You are treating `Object.up` -- not as a world direction --  but as a relative direction.

**Comment by lguminski** [comment]
@WestLangley thank you for giving it attention. And your patience to my strong opinions.

You are right. I am using `up` as a relative direction. And I believe it is correct. Let me explain why.

The reason is that I tend to think more like an architect than a developer. And when I model software, I always try to make it consistent with the domain it models. Because I know that inconsistencies become design flaws, and they will bite sooner or later.

In this case `three.js` aims to model physical reality. In the reality, when I take a telescope and look at, say, Jupiter, this action doesn't turn me upside down to match my orientation with the orientation of Jupiter. Instead, I keep standing firmly on the ground, and my relative orientation to my parent (the Earth) doesn't change. Why would `three.js` behave differently? That was my reasoning.

**Comment by WestLangley** [comment]
>thank you for giving it attention. And your patience to my strong opinions.

:-)

Since you are redefining `lookAt( point )` to accept a point defined in the parent's coordinate space, and since you are treating `object.up` as a relative direction, this PR is not going to be acceptable.

However, I do understand your approach, and it can be a valid methodology -- just not here.

Adding `Object3D.lookAtObject( object )` as a convenience method is possible. However, the convenience method must work in all cases, and that means it must traverse the scene graph to compute the correct world position of the target `object`. That is inefficient inside the render loop, because the renderer has already traversed the scene graph for you. `Object3D.lookAt( point )` doesn't have that problem.

**Comment by lguminski** [comment]
I can understand. Well, at least now it is a well thought through decision.

**Pull request closed without merging**
