### PR TITLE
WebGLUniforms: Remove cache on uniform arrays

### PR DESCRIPTION
**Pull request by fernandojsg**
Address the issue exposed on https://github.com/mrdoob/three.js/issues/16355
Currently I'm removing the cache on the array of matrices, textures and vectors.
Babylon.js is using a similar approach, they just cache single elements: scalar, vector2, vector3, vector4 and matrix (actually just 4x4).

The only arrays left without caching are the `setValue2iv`, `setValue3iv` and `setValue4iv` as they are shared between [single](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLUniforms.js#L470-L493) and [pure array](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLUniforms.js#L652-L673) setters.

I don't have an strong opinion about these, but we could leave the current `setValue*iv` with cache for single setters and introduce `setValue*iva` for arrays without cache. Thoughts?

### CODE REVIEW

**Comment by Mugen87** [comment]
> I don't have an strong opinion about these, but we could leave the current setValue*iv with cache for single setters and introduce setValue*iva for arrays without cache. 

Sounds good. In this way the caching separation is more clear.

**Comment by fernandojsg** [comment]
@Mugen87 done! I have also renamed the functions for consistency across singular and pure array, eg: 

| BEFORE SINGLE  | BEFORE ARRAY | AFTER SINGLE  | AFTER ARRAY |
| ------------- | ------------- | ------------- | ------------- |
| setValue1f | setValue1fv | setValueV1f | setValueV1fa |
| setValue2fv | setValueV2a | setValueV2f | setValueV2fa |
| setValue3fv | setValueV3a | setValueV3f | setValueV3fa |
| setValue4fv | setValueV4a | setValueV4f | setValueV4fa |
| ------------- | ------------- | ------------- | ------------- |
| setValue2fm | setValueM2a | setValueM2 | setValueM2a |
| setValue3fm | setValueM3a | setValueM3 | setValueM3a |
| setValue4fm | setValueM4a | setValueM4 | setValueM4a |
| ------------- | ------------- | ------------- | ------------- |
| setValueT1 | setValueT1a | setValueT1 | setValueT1a |
| setValueT3D1 | | setValueT3D1 | 
| setValueT6 | setValueT6a | setValueT6 | setValueT6a |
| setValueT2DArray1 | | setValueT2DArray1 |
| ------------- | ------------- | ------------- | ------------- |
| setValue1i | setValue1iv | setValueV1i | setValueV1ia |
| setValue2iv | setValue2iv | setValueV2i | setValueV2ia |
| setValue3iv | setValue4iv | setValueV3i | setValueV3ia |
| setValue4iv | setValue3iv | setValueV4i | setValueV4ia |

**Comment by fernandojsg** [comment]
Maybe we could even be more explicit eg: `setValueV2fa` => `setArrayValueV2f` or `setValueV2fArray`

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
> Maybe we could even be more explicit eg: `setValueV2fa` => `setArrayValueV2f` or `setValueV2fArray`

I vote for `setValueV2fArray`.

**Comment by fernandojsg** [comment]
> > Maybe we could even be more explicit eg: `setValueV2fa` => `setArrayValueV2f` or `setValueV2fArray`
> 
> I vote for `setValueV2fArray`.

done

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Um, it seems I'm getting the following error now in `webgl_postprocessing`.

> three.js:16397 Uncaught TypeError: Failed to execute 'uniform1iv' on 'WebGLRenderingContext': No function was found that matched the signature provided.

**Comment by Mugen87** [comment]
The problem is that `uniform1iv` needs an array as a parameter. But since the function is now also used for single values, the mentioned error occurs. So for the above case, using `uniform1i` solves the issue.

**Comment by Mugen87** [comment]
I've merged a quick fix so `dev` is not broken anymore.

**Comment by fernandojsg** [comment]
@Mugen87 good catch! sorry about that :)

**Comment by Mugen87** [comment]
NP^^. I've also missed it during testing. Not all examples were affected.

**Pull request merged**
