### PR TITLE
Examples: Add EdgeSplitModifier

### PR DESCRIPTION
**Pull request by Mcgode**
**About this feature**

This geometry modifier allows the user to build an indexed BufferGeometry, where are split on sharp edges. This allows you to compute normals without smoothing the edges :

Without applying the modifier:
smoothShading

After applying the modifier:
edgeSplitSmooth

Very useful if you're importing a STL file.

**How it's implemented**

The feature was implemented as an example, using the same structure as the other modifiers.
It also features an example page, which includes a new binary STL model

**Additional notes**

The feature is also available as a standalone package:
https://github.com/Mcgode/three-js-edge-split-modifier

_This contribution is funded by **Dioxygen Software** for **[Dualbox.com](https://dualbox.com)**_

### CODE REVIEW

**Comment by Mugen87** [comment]
Thanks for this but I think it's better to not add more modifiers to this repository. It is in general already large and hard to maintain. I vote to leave such specialized logic in separate repositories and `npm` packages.

**Comment by DefinitelyMaybe** [comment]
I might save this one for later. if we ever open up a 'community-made-features' repo or something similar this would be a cool addition

**Comment by mrdoob** [comment]
I actually like this!

**Comment by mrdoob** [comment]
Where's `roman_soldier.stl` from though?

**Comment by Mcgode** [comment]
`roman_soldier.stl` was a model I got from HeroForge some time ago. Thanks for asking since it's actually copyrighted and I shouldn't publish it here.

As a consequence I've removed the model from my git repo and switched to using the `cerberus.obj` model instead, giving this result :

Falt shaded:
flatShaded

Smooth shaded (no split):
image

Smooth shaded (with 20° split)
image

**Comment by maximeq** [comment]
Hello,
[I'm working with Mcgode]
We bought the Roman Soldier from Hero Forge to be used as an example on several processing algorithm in Dualbox. From my understanding as it is a uniquely generated model we paid for, we have the rights to use it. However, I guess if the demo works as well with the gun, better use the assets you already have.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@Mcgode Do you think it would be possible to build a [bevel modifier](https://www.youtube.com/watch?v=tfNWpORvYiM) out of this modifier's code?

**Comment by Mcgode** [comment]
> @Mcgode Do you think it would be possible to build a [bevel modifier](https://www.youtube.com/watch?v=tfNWpORvYiM) out of this modifier's code?

I think there's still a long way to go from my code to implement a bevel modifier.

**Pull request merged**
