### PR TITLE
Examples: Moved webgl_skinning_simple to gltf

### PR DESCRIPTION
**Pull request by Mugen87**
See #14737

The example uses now `SimpleSkinning.glb`. Besides, the scene looks a little bit nicer now.

I've not deleted the JSON model since it's used by the unit tests.

### CODE REVIEW

**Comment by takahirox** [comment]
BTW I'm wondering what this example is for... There're a lot of examples showing skinning animation. Do we really need this example?

**Comment by Mugen87** [comment]
The armature of the model is very simple. There is also corresponding blend file in the repo. I guess it was initially added to illustrate a basic workflow from Blender to `three.js`. Users can check out the blend file in order to see how things are setup.

**Comment by takahirox** [comment]
If that's the purpose of this example, I think we need to add a note or something, for example the link to `simple.blend` file on the example page. It's unclear now.

**Comment by Mugen87** [comment]
Done.

**Comment by WestLangley** [comment]
The example looks much better! It would be even better if the skeleton-helper toggle were present, IMHO.

Unfortunately, the point of the example is lost as the model file is now not human readable. I am not sure an ascii .gltf file would be much better. I am also not sure what this example adds now. Are you sure blender workflow was the point of this example?

**Comment by mrdoob** [comment]
Maybe we can convert it to .gltf (embeded) instead?

**Comment by Mugen87** [comment]
> Maybe we can convert it to .gltf (embeded) instead?

Done!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Btw, this example was very handy when I refactored the `WebGLRenderer` to use `BufferGeometry` internally years ago 😊

**Comment by takahirox** [comment]
Don't we add a skeleton-helper in this example? Agreed with @WestLangley

**Comment by Mugen87** [comment]
I've checked this but because of the simple skeleton the visualization is not really meaningful.

**Comment by takahirox** [comment]
Yeah, absolutely.

image

**Pull request merged**
