### PR TITLE
Convert to ES2015 classes, for a smaller/faster bundle

### PR DESCRIPTION
**Pull request by Rich-Harris**
Hi there! Please forgive the size of this PR; I'm opening it more to start a discussion than anything, and I chose this over opening an issue (or adding to one of the existing ones) because it felt like it would be beneficial to a) be able to show exactly what I'm talking about, and b) prove that it's actually possible.

## tl;dr

We can make Three.js smaller and faster to load — and hopefully pave the way for future improvements like treeshakeability — by switching from functions to ES2015 classes. This PR was generated with [convert-threejs-to-classes](https://github.com/Rich-Harris/convert-threejs-to-classes), which provides some more information.

## Background

There have been a couple of issues in the past suggesting migrating to ES2015 classes — e.g. https://github.com/mrdoob/three.js/issues/11552 and https://github.com/mrdoob/three.js/issues/6419 — but at the time those issues were raised it was more of an encumbrance than anything, since browsers didn't yet support the `class` keyword.

Now, though, all browsers support classes, and performance is excellent. No transpilation is needed to use them. As of this PR, `build/three.min.js` is 5% smaller than the current build, and startup time is quicker.

## Does everything work?

All the unit tests pass. Most of the examples still work, but a few need updating because **switching to classes introduces a breaking change** — you can no longer do this...

```js
function MySubclass() {
  MySuperclass.call(this); // this call is illegal!
}
```

...but must instead do this:

```js
class Mysubclass extends MySuperclass {}
```

Some of the examples may be tricky to update automatically; these could be addressed in a follow-up PR if it turns out to be prohibitively difficult.

**Edit**: As noted below, introducing `class` means dropping IE11 support. Devs who need to support IE11 can do so via e.g. [Bublé](http://buble.surge.sh/).

## Is it really worth it?

That's for the maintainers to decide. But I believe this would be the best decision for the project — classes are easier to reason about, easier to statically analyse (which raises the tantalising possibility of proper tree-shakeability!), and are the 'officially sanctioned' and modern way to write this sort of code.

The downside is the breaking change outlined above, but it's one that is very easily addressed in app codebases. May as well rip the bandaid off now!

## Follow-up work

Aside from fixing the examples mentioned above, there are some further tweaks to the codebase that could be applied manually in a second PR — [see details here](https://github.com/Rich-Harris/convert-threejs-to-classes#follow-up-work).

---

Let me know if this is something you'd be interested in doing. Thank you! 🍻

### CODE REVIEW

**Comment by Rich-Harris** [comment]
(one note, as I try to fix the CI errors before I leave the office — the `build-uglify` script doesn't work in this branch because Uglify only supports ES5. We can easily fix it by replacing it with [terser](https://www.npmjs.com/package/terser), a fork that supports modern JavaScript)

**Comment by mrdoob** [comment]
> (one note, as I try to fix the CI errors before I leave the office — the `build-uglify` script doesn't work in this branch because Uglify only supports ES5. We can easily fix it by replacing it with [terser](https://www.npmjs.com/package/terser), a fork that supports modern JavaScript)

I only use `build-closure`. Not sure who uses `build-uglify` 🤔

**Comment by Andarist** [comment]
What would be the official recommendations for people who have to support IE11 (which is far from being dead)?

**Comment by IvanSanchez** [comment]
> What would be the official recommendations for people who have to support IE11 (which is far from being dead)?

Transpile your code so it looks like a UMD package. See e.g. https://github.com/Leaflet/Leaflet/pull/6021/files - the Leaflet codebase is ES2015 modules, but the UMD bundle supports down to IE8.

[The `rollup.config.js` file here also creates a UMD bundle](https://github.com/mrdoob/three.js/blob/6201c9ac8c8a384ebc475e5bdb7c6ee0d75885f7/rollup.config.js#L34), so I don't foresee any major obstacles regarding browser support.

**Comment by Andarist** [comment]
Ok, sure - but how i.e. webpack users are supposed to consume those UMD bundles, should they chose:
```js
import Lib from 'some_lib/dist/some_lib.umd.js'
```
over 
```js
import Lib from 'some_lib'
```

Seems like a big burden on users to do that for "each" library they use (assuming that shipping es6+ code to npm becomes a trend).

**Comment by arodic** [comment]
@Rich-Harris this is amazing work. Assuming this goes through, I can help fixing some of the examples.

@Andarist

> Seems like a big burden on users to do that for "each" library they use

Perhaps this is a good thing! Lack of burden/friction is how we found ourselves in a situation that most trivial apps have hundreds of dependencies. Remember leftpad?

> assuming that shipping es6+ code to npm becomes a trend.

I wholeheartedly hope ES6+ becomes a trend as soon as possible. However, I am not convinced that npm is the best place to ship it.

**Comment by IvanSanchez** [comment]
> how i.e. webpack users are supposed to consume those UMD bundles

If a webpack user wants to consume the UMD bundle, then they must import the whole file. If a webpack user wants to consume the ES2015 exports, then Webpack shall take care of transpiling down to something that IE can understand.

Please note that this PR does **not** change the shape of the final bundles (`build/three.js` is still a UMD bundle, and `build/three.module.js` is still a ES2015 module bundle). So whatever issues you might have regarding webpack, they won't change a bit with this PR.

**Comment by Rich-Harris** [comment]
> What would be the official recommendations for people who have to support IE11 (which is far from being dead)?

I actually misread the [compat table](http://kangax.github.io/compat-table/es6/) (which has a bug — before it fully loads, the boxes in the table are offset by one column!), and thought IE11 would still be supported. My mistake.

That said, IE11 use is around 2.5%; among users of WebGL apps, I would expect the number to be much lower still. We shouldn't let a tiny minority of holdouts levy a tax on the rest of the web. For app developers that really *do* need to support IE11, it's easy enough to run the code through a transpiler; if you don't want the added bulk of a Babel transpilation then you could use [Bublé](http://buble.surge.sh/), which generates a minified bundle almost identical in size to the current one. (We could even opt to include a pre-transpiled bundle in the package, though I'd argue it's unnecessary.)

> Ok, sure - but how i.e. webpack users are supposed to consume those UMD bundles, should they chose:

The package.json has `"main": "build/three.js"` and `"module": "three.module.js"` — in other words, if you're consuming Three via webpack you're *already* consuming the bundle. This PR doesn't change anything around that.

> I wholeheartedly hope ES6+ becomes a trend as soon as possible. However, I am not convinced that npm is the best place to ship it.

I have to disagree with that 😀 It's totally reasonable to ship ES2015 code in 2018, and *not* doing so is being unkind to our users' data plans and causing unnecessarily slow app startup times (since ES5 code tends to be significantly larger than ES2015+ code). For my own libraries, I usually draw the line at whether or not the features I'm using run in all current browsers (which excludes IE11) and Node 6 (the maintenance LTS version).

Thanks for the feedback everyone!

**Comment by looeee** [comment]
@Rich-Harris what's the reason for choosing Bublé over Babel here?

**Comment by Rich-Harris** [comment]
Thanks @mrdoob — I've updated the PR to only affect `src` files. I couldn't figure out how to integrate the custom Babel plugin (more specifically, it errored out on certain files when I ran it locally), so for now it uses Bublé, which has similar output (the Babel output I'm using for comparison is the one from AST Explorer):

* current dev branch: 549321 bytes minified, 135780 zipped
* classes: 519783, 132122
* classes + Babel: 550824, 135049
* classes + Bublé: 551321 / 133706

As you can see the Bublé output is very slightly larger than hand-written functions, or the output of the custom Babel plugin, but the gzipped size is actually slightly smaller. All the examples I've checked so far continue to work.

Of course, preserving the classes results in the smallest output, but it does entail that breaking change so I understand if you'd prefer to do that at a later point. If you'd prefer to use Babel I can try and get that working later.

**Comment by looeee** [comment]
Ha, you answered my question at the exact second I asked it 😆

**Comment by Rich-Harris** [comment]
@looeee we commented at the exact same time — see my previous comment for the rationale. Basically, I couldn't get Babel to work, and Bublé's output zips better. (Also, Bublé is much faster 😀 )

**Comment by Mugen87** [comment]
It seems some files are missing e.g. `Box3` or `Vector3`. I wanted to check how the following type of methods are handled (where the actual implementation is wrapped in IIFE). This style is used in order to avoid object creation:
https://github.com/mrdoob/three.js/blob/4688a5fb211b338224d6f47b99684fcee138320e/src/math/Box3.js#L328-L342

AFAIK, you can't do the same with classes. Helper objects like `closestPoint` would need to be placed in module scope. Do we have to change this manually?

**Comment by Rich-Harris** [comment]
@Mugen87 `Box3`, `Vector3` and `Quaternion` were excluded from the initial conversion because classes don't get hoisted in the same way as functions; because those classes are eagerly instantiated inside those IIFEs, we get an error when evaluating. So I left them as functions for now.

I added an example of how we could convert methods like `intersectsSphere` over here: https://github.com/Rich-Harris/convert-threejs-to-classes#follow-up-work. Basically yes, you're right, it will need to be a manual follow-up to the automated conversion. The good news is that removing those IIFEs should get rid of the tricky cyclical dependencies, speed up startup (if only by a tiny amount), and put us on the path towards a more tree-shakeable Three.js!

**Comment by Mugen87** [comment]
How about changing the respective methods first and then use your tool for auto-conversion? In this way, the shift to classes might be maybe easier.

**Comment by Rich-Harris** [comment]
@Mugen87 good idea! done https://github.com/mrdoob/three.js/pull/14695

**Comment by mrdoob** [comment]
Some progress... #15280

**Comment by Mugen87** [comment]
Closing in favor of #17276

**Pull request closed without merging**
