### PR TITLE
Update How-to-run-things-locally.html

### PR DESCRIPTION
**Pull request by Fasani**
Adding options for live server plugins for popular code editors.

### CODE REVIEW

**Comment by linbingquan** [comment]
Can you please also update it in the Chinese version of the page.

[https://threejs.org/docs/manual/zh/introduction/How-to-run-things-locally.html](https://threejs.org/docs/manual/zh/introduction/How-to-run-things-locally.html)

**Comment by mrdoob** [comment]
Maybe better to merge and do the Chinese update in a different PR.

**Comment by mrdoob** [comment]
Thanks!

**Comment by linbingquan** [comment]
> Maybe better to merge and do the Chinese update in a different PR.

Please to see: https://github.com/mrdoob/three.js/pull/19514

**Pull request merged**
