### PR TITLE
AnimationMixer: Add .setTime() method. 

### PR DESCRIPTION
**Pull request by Bug-Reaper**
As discussed in Feature Request thread [here](https://github.com/mrdoob/three.js/issues/17485).
**1st commit:** Adds the setTime method to the AnimationMixer object and updates typescript definition.
**2nd commit:** Updates the documentation page for the AnimationMixer to include `setTime(timeInSeconds)` method documentation.
**3rd commit:** Merges the changes from dev I missed to avoid merge conflicts.
**4th commit:** Updates the `three.js, three.min.js, three.modules.js` build files.

This is literally my first PR  here ever. Let me know if there's anything I can improve going forward. 

Looking forward to making more contributions :+1:

### CODE REVIEW

**Comment by Mugen87** [comment]
Please remove all build files from your PR. Besides, ensure to use the correct code formatting (see https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2).

**Comment by mrdoob** [comment]
> This is literally my first PR here ever.

Looking good! 4th commit wasn't needed. We generate new builds ourselves.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Bug-Reaper** [comment]
@mrdoob 
> Thanks!
Yea man! Super happy to contribute back to this amazing library :) 

@Mugen87 
Thanks for that link :+1: ! Super useful!

**Pull request merged**
