### PR TITLE
Enable mat2/3/4 attribute in shader

### PR DESCRIPTION
**Pull request by takahirox**
#16140

https://stackoverflow.com/questions/38853096/webgl-how-to-bind-values-to-a-mat4-attribute

Suggested API.

```
// glsl
attribute mat4 matrix;

// js
geometry.addAttribute( 'matrix', new THREE.BufferAttribute( data, 16 ) );
```

Change
- Keeping not only attribute location but also attribute type in `WebGLProgram`.
- If attribute type is `mat2/3/4` renderer calls `enableAttribute()` and `vertexAttribPointer()` multiple times.

```javascript
var locationsNum = 1;
if ( programAttribute.type === _gl.FLOAT_MAT2 ) locationsNum = 2;
if ( programAttribute.type === _gl.FLOAT_MAT3 ) locationsNum = 3;
if ( programAttribute.type === _gl.FLOAT_MAT4 ) locationsNum = 4;

....

for ( var i = 0; i < locationsNum; i ++ ) {

	state.enableAttribute( programAttribute.location + i );

}

....

for ( var i = 0; i < locationsNum; i ++ ) {

	_gl.vertexAttribPointer(
		programAttribute.location + i,
		size / locationsNum,
		type,
		normalized,
		size * bytesPerElement,
		( size / locationsNum ) * i * bytesPerElement
	);

}
```

### CODE REVIEW

**Comment by Shimmen** [comment]
What is the status on this? Any chance of a merge in the near future? Thanks!

**Comment by yuanzhaokang** [comment]
what the status now ? thanks !

**Comment by mrdoob** [comment]
I guess this will need to be rebased?

**Comment by Mugen87** [comment]
As far as I remember, this code was originally added for a instanced mesh implementation. However, @mrdoob implemented it differently:

https://github.com/mrdoob/three.js/blob/ae1098eeff9f3018faf6cddeae358d5273c2d0cc/src/renderers/webgl/WebGLBindingStates.js#L392-L415

**Comment by takahirox** [comment]
From https://github.com/mrdoob/three.js/issues/16140#issuecomment-896386612

I'm willing to rebase to resolve the conflicts if anyone is still interested in this addition although Three.js API supports instancing now.

**Comment by mrdoob** [comment]
@takahirox Sounds good to me! I think now it's a good time for it 👍

**Comment by takahirox** [comment]
Updated.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
