### PR TITLE
Support per-map per-Material UV channels, UV offset/repeat and texel scale/offset

### PR DESCRIPTION
**Pull request by bhouston**
This introduces the idea of TextureSlots to Materials in a fully backwards compatible fashion (excluding likely a bug here or there.)  TextureSlots allow per-mat per-Material UV channels, UV offset/repeat, and texel scale/offset/invert.

This addresses the very common issue, see #5876, #7826, #7956 and #3549, besides just being broadlly useful.  I have implemented something like this in the Clara.io private ThreeJS branch, this is my attempt to polish that code and bring it back into ThreeJS proper.

What this PR does is replace the direct maps on MeshStandardMaterial with TextureSlots.  TextureSlot is a new class that can contain a texture as well as its UV Channel, an optional UV transform (offset, repeat) and an optional scalar Texel transform (scale, offset.)

This allows one to set the UV channel you want a map to follow.  It defaults to the previously ThreeJS defaults.

This also allows one to set the UV offset/repeat on a per map basis, if TextureSlot.uvTransform is set to true.  It no longer needs to be based on the textures repeat/offset.  Although I have written it so that the per map UV offset/repeat is applied along with the per-texture offset/repeat so that the previous workflows still work.

It also allows one to offset, scale and invert the resulting texel value if TextureSlot.texelTransform is set to true.  This is replaces the need for bumpScale, lightMapIntensity, displacementScale, displacementBias, and generally is very useful.

The idea of texture slots was relatively easy to support because it's uniform organization allows one to create for loops in various places in order to process them.

This PR is a rough one, and so far only applied to MeshStandardMaterial, but the design is there and if we can support getting this into dev this I can expand support of TextureSlots to the other materials.

This PR is smart about only including sampler2D, varyings, and uniforms into the resulting shaders if they are needed.  Thus it is very efficient in that sense, and if TextureSlots capabilities are not used, they do not add any additional uniforms.

/ping @QuaziKb @huttarl @Monokai @jcarpenter @titansoftime @Zob1 @benaadams @endel @karimbeyrouti @rhys-vdw (You guys requested this feature previously)

### CODE REVIEW

**Comment by bhouston** [comment]
Proof of backwards compatibility:

http://ci.threejs.org/api/pullrequests/8250/examples/webgl_materials_standard.html
http://ci.threejs.org/api/pullrequests/8250/examples/webgl_materials_displacementmap.html
http://ci.threejs.org/api/pullrequests/8250/examples/webgl_materials_envmaps_hdr.html

I'll create an example that demonstrates independent map control (uv and texel) in the next day.

**Comment by bhouston** [comment]
New example that shows shows independent control of map, normalMap, emissiveMap and uvRepeat/uvOffset and texelScale/texelOffset/texelInvert:

http://ci.threejs.org/api/pullrequests/8278/examples/webgl_materials_slots.html

image

**Comment by MiiBond** [comment]
I was just thinking about implementing something like this in Three.js yesterday and then I found this pull request. Nice work.

We don't use the Three.js materials or shader chunks so the issue of the offset/repeat being pulled from the "map" texture was never a problem for us. However, now that the Three.js shader chunks have been becoming more and more modern (many thanks to you), I've been thinking about switching over and using them rather than completely custom shaders. Hence my interest in this.

I like that the shader code for the UV transforms only get applied when they're needed. I had been thinking of doing something like this in our shaders since we always have scale, offset and panning defined for every texture and, as you can imagine, that eats up a lot of uniforms when several maps are active.

So, based on what I was thinking yesterday, here is some feedback for this pull request:

1. In my ideal world, the UV transforms would include a 3x3 matrix (or, I guess only 3x2 is needed) so as to be more flexible. Utility functions would, of course, let the user build the matrix more easily (from offset/repeat). Perhaps UV animation logic could be thrown in here too (e.g. panning, rotations, etc.). In addition, there could be other logic for generating UV's like equirectangular projections, planar projections, etc. Of course, all that could be added after your pull request is merged.

2. It would be great if maps could share uv-transforms. So, for example, I could easily apply the same transform to my albedo, normal, and roughness maps.
I'm thinking that the ```THREE.Map``` could reference a ```THREE.Texture``` and a ```THREE.UVTransform``` object that contained all the transform settings.
Ideally, underneath, each unique transform would be done only once in the shader. When a material builds, it would construct an array of unique ```THREE.UVTransform``` information and pack the relevant data into uniform arrays. Each texture map in the material is mapped to an index in this array and preprocessor macros are used to insert the uv-transform code into the shader only when needed. No, I haven't thought through the details of what this would look like but I like the idea of this logic being available even for custom shaders.

Anyway, kudos to you for going and finally working to fix this long-standing three.js issue.

**Comment by bhouston** [comment]
@MiiBond, unless there is community support for merging this, it isn't going to be merged.  I am not going to contribute to this PR if others are not supporting it.

I'd advocate getting this basic PR merged before adding additional functionality as I am not going to invest more time into this PR at this stage because the support is mearger.

**Comment by bhouston** [comment]
UVTransform should just be a THREE.Matrix3 then with some helpers.  Super easy to do, but I believe a Matrix3 takes 3 uniform slots, while the current uvTransform repeat/offset takes one.  But again, no one but you (more than a week later I submitted it), has even voiced minor interest.  So while I have adopted this PR in our production code, I am currently do not expect it to get merged.

**Comment by B6T3M6N** [comment]
Great work! It solves one of our major problems. So I'd like to see this PR to get merged. I'm fairly new to this whole Threejs and Github thing. But if there's anything to give support on that I'll do what I can.

**Comment by jcarpenter** [comment]
Outstanding. I've moved on to other projects since I originally voiced support for this feature, but I hope to be back into Three.js UI development land again in the next year, and would love to have the power this will provide. This helps fill a significant gap between Three.js's texture handling and what we get from 3D content creation apps like C4D. Full throated support from me, at least from a feature set standpoint.

_Sorry for the slow response, btw. Have been heads down on a few unrelated projects!_

**Comment by bhouston** [comment]
@mrdoob Did you notice how many voices of support this got?  Of course us at Clara.io, then @jcarpenter (Mozilla/A-Frame VR), @MiiBond (Box.com/Verold), and @MasterJames and @B6T3M6N.

**Comment by matias-capeletto** [comment]
It seems there was interest for this feature. Any chances this will get merged at the end? Thanks a lot for an awesome library to all involved.

**Comment by dirtybluejeans** [comment]
This is exactly what I've been looking for... will this ever be merged? Also, I noticed that while all the maps play well with each other, bump maps are still ignored if a normal map is present. Is there any plan to address that or that's the way it's designed to be? My usecase:

Objects can have any textures. The details of the objects are via normal maps, hence there is a normal map per object. The textures have a diffuse map and a bump map, and this is 'draped' over the object. These maps are per textures. All three need to be applied in a MeshStandardMaterial - the bump map to give realism to the texture, and the normal map to provide features.

**Comment by WestLangley** [comment]
>bump maps are still ignored if a normal map is present.

@bhouston Are you aware of any renderers that support a normal map and a bump map simultaneously?

It seems reasonable to support both a normal map and a _detail_ map -- a 2nd normal map used at higher `repeat` setting. I am not sure about mixing bump map (height map) and normal map, though.

**Comment by bhouston** [comment]
> @bhouston Are you aware of any renderers that support a normal map and a bump map simultaneously?

Unity supports detail albedo and normal maps it appears: https://docs.unity3d.com/Manual/StandardShaderMaterialParameterDetail.html

UE4 supports detail albedo and normal maps as well: https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/HowTo/DetailTexturing/

Both Unity and UE4 do not seem to by default allow for detail bump maps, but UE4's material graph is flexible enough to allow it I am sure.

**Comment by dirtybluejeans** [comment]
Thanks for looking into this guys. For my usecase, the bump map is the one that tiles (high repeat setting) - exactly the same as the diffuse map, and is used to provide realism to the 'main' texture. The normal map is created from the high-poly version of the mesh, and then applied to the low-poly version to recreate the detail that was lost - hence does not repeat (has a repeat of 1).

Maybe an easier way to explain this would be in terms of an engraving on stone. The engraving is via the normal map,  where the stone itself is via the bumpmap+diffuse map that tiles.  Essentially, I'm talking about layering of maps.

I've been able to use the combination of diffuse+bump using the standard three.js, and diffuse+normal using 'slots' in the version of three from the example in this request (had to use this because of different repeat values, which are otherwise not supported). Both versions, though, ignore bumpmap as soon as a normal map is set.

Hope that helps explain why this is needed - maybe there's a better way to do what I'm trying to do - in which case there's nobody better than you guys to suggest - but if not, hopefully others will also benefit from this change.

Thanks.

**Comment by dirtybluejeans** [comment]
Got it, so the detail-albedoMap you are talking about it a normap-map version of what I'm doing with bumpmaps. That works just fine, as long as I can have different repeat values for both. So is this layering currently possible? The current pull request at least lets me have different repeat values for diffuse and normal maps, so that's a great outcome... hopefully will be merged at some point of time.

Thanks.

**Comment by dirtybluejeans** [comment]
Any changes this is going to be merged any time soon? @bhouston, is there a more recent fork anywhere where this is merged (I'm currently stuck on the one you have used in your example, and that's based on r75dev)?

Just wanted to add that this is a really significant upgrade to the existing Three capabilities, and it would be great to see it merged.

Thanks.

**Comment by bhouston** [comment]
Hi @dirtybluejeans I have my own fork of ThreeJS here that is fairly up to date with this UV Slot stuff merged but I am hesitant to show it publicly I do not want to appear as I am running a competing open source Three.JS effort, and I do not have any time to support it.

**Comment by matias-capeletto** [comment]
Hello @bhouston, for what is worth, it will be great to have access to that version at least until this or something similar to this functionality is merged in. I think is clear you are not creating a competing lib here. Thanks again.

**Comment by dirtybluejeans** [comment]
+1 to that, for sure!

**Comment by cbravo** [comment]
any movement on this? I would love to generate pulses of light on my mesh by animating the offset of my emissive map without messing with the other maps on the object.   this seems like it would work for that correct?

**Comment by errantspark** [comment]
I'm really interested in this feature, as far as I can tell it's just waiting for approval from @mrdoob? Is that correct? If not I'm down to do whatever it takes to bring it to that stage.

**Comment by EerikKivistik** [comment]
Any news on this @dirtybluejeans, ran into a similar issue, where I need to use the same texture in multiple contexts (different offset, tiling etc) and see no reason to implement the same thing in my codebase if you already have a working solution. Also 👍 for that.

**Comment by matthew-dean** [comment]
I don't really understand why offsets can't be different for texture clones. I hope this is merged soon.

**Comment by zellski** [comment]
I will add a strong +1 urge for this enhancement.

**Comment by titansoftime** [comment]
This is me voicing support for this.

**Comment by bhouston** [comment]
@mrdoob, any thoughts about merging this?  It is not possible for Three.JS to conform to the official glTF specification unless we can do this.  I do have some time (well, not really, but I will do it) to rebase this and merge it into the latest dev.

**Comment by tobiasbu** [comment]
+1. I support this feature too. It has been 3 years and I can not find a similiar solution for Three.js other than this one. If there is any workaround I would like to know.

**Comment by bhouston** [comment]
We are using node-materials in the three.js examples folder to get around this limitation.

**Comment by Mugen87** [comment]
Closing. As mentioned by the previous post, using the flexible `NodeMaterial` is the solution for this issue.

It is planned to stabilize the API and introduce a basic documentation for `NodeMaterial` so it's easier to get started. Keep an eye on the following issue for more information about this topic: #17971

**Comment by pailhead** [comment]
@tobiasbu

Have you seen this https://github.com/mrdoob/three.js/issues/14174 it’s a workaround for the old versions.

**Pull request closed without merging**
