### PR TITLE
allow some texture assignment freedom with SoftwareRenderer

### PR DESCRIPTION
**Pull request by makc**

### CODE REVIEW

**Comment by mrdoob** [comment]
Is this to avoid the renderer breaking if the data is not ready?

**Comment by makc** [comment]
yes, and also to allow changing the `map` in materials

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
@mrdoob there is good point (or feature request) to make from this, SoftwareRenderer listens to materials 'update' events, but apparently they never come when texture is ready nor when texture is replaced.

**Pull request merged**
