### PR TITLE
Font: Remove unused divisions parameter from .generateShapes()

### PR DESCRIPTION
**Pull request by Mugen87**
The fineness of the geometry based on a given shape is controlled via `Shape.extractPoints()`. This method is used in `ShapeGeometry` or `ExtrudeGeometry`.

### CODE REVIEW

**Comment by WestLangley** [comment]
You will have to track down the use of `curveSegments`, too.

For example, in `TextBufferGeometry`:
```javascript
var shapes = font.generateShapes( text, parameters.size, parameters.curveSegments );
```

**Comment by Mugen87** [comment]
Thanks, I've actually missed that 👍

**Comment by WestLangley** [comment]
You will need to grep for `curveSegments` to find all the places where it needs to be removed.

**Comment by Mugen87** [comment]
I don't think that's correct. `curveSegments` is used within `ExtrudeGeometry` in another context.

https://github.com/mrdoob/three.js/blob/22d135e3f80e99637595458ea0488b5222b829c0/src/geometries/ExtrudeGeometry.js#L167

**Comment by WestLangley** [comment]
I see. So in `TextGeometry`, setting `parameters.curveSegments` is still OK.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
