### PR TITLE
Examples: added toggle for previews

### PR DESCRIPTION
**Pull request by ajflores1604**
Added a section to toggle preview images on the examples page for easier navigation and scrolling
https://ajflores-public.netlify.app/70202541/threejs/examples/index.html

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by marcofugaro** [comment]
Nice! I like this solution. 

Make sure to add `cursor: pointer;` to the selectable toggle buttons (`#panel #toggles *:not(.selected)`).

**Comment by mrdoob** [comment]
I refactored the code and design: https://github.com/mrdoob/three.js/commit/f60dc5b3c9ec57bbd4455c57c0b2ac689fc7e9f0

image

**Comment by mrdoob** [comment]
Even simpler implementation (thanks to Bojack on discord): https://github.com/mrdoob/three.js/commit/c30ab07b0df65ecb0c4daaff86056d50cbc6bc68

**Comment by mrdoob** [comment]
More simplifications: https://github.com/mrdoob/three.js/commit/e5a6f370b93504bfccb4952a6007c2d393e8574f https://github.com/mrdoob/three.js/commit/d9dc3d083fbbf2d2eed4f1074b48b506d0572efd

**Comment by mrdoob** [comment]
Latest iteration:

image

**Comment by Mugen87** [comment]
Looks great now! 👍

**Comment by Mugen87** [comment]
During testing on `dev`, I've encounter a small style issue.

image

When `webgl` is not the first heading (because of filtering), the top border of subsequent headings goes through the toggle icon.

**Pull request merged**
