### PR TITLE
Docs: Removed internal is* properties.

### PR DESCRIPTION
**Pull request by mrdoob**
I don't think we should document these.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Hm, do you disagree with my comment at https://github.com/mrdoob/three.js/issues/18195#issuecomment-567250096? I don't necessarily feel strongly that the properties need to be documented, but I hadn't personally considered them "internal", and I definitely prefer to use them in application code versus `.type === "Mesh"`.

Ideally `foo instanceof Mesh` would just work, but was there some issue with that? I can't remember why we don't use it internally and use `isFoo` instead.

**Comment by mrdoob** [comment]
I do not disagree. You can use them but language like "default is true" in the documentation was confusing.

**Comment by mrdoob** [comment]
If we're going to document them, we can automate it with `.is[name]`.
But I don't think I would call it a `Boolean` as it makes you think you can change it.

**Comment by donmccurdy** [comment]
Ok, thanks — I don't mind removing it from the API documentation.

**Pull request merged**
