### PR TITLE
Update json format to remove warnings

### PR DESCRIPTION
**Pull request by gero3**
In example webgl_animation_scene there are always warnings about deprecated json formats.
image
This pullrequest updates that json and has a script to automatically update such jsons.

http://ci.threejs.org/api/pullrequests/8726/examples/webgl_animation_scene.html

### CODE REVIEW

**Comment by mrdoob** [comment]
That file was exported from clara.io. Wouldn't it be better to ping @bhouston so they fix their exporter instead?

**Comment by gero3** [comment]
That may be better.

**Comment by bhouston** [comment]
We just use the blender exporter in Clara.io.  I believe there are no open source exporter that use the new animation format at the moment.  Or did someone update the exporters?  I'd recommend removing the warning for now.

/ping @tschw

**Comment by bhouston** [comment]
Also there are more than one legacy format for animation.  We are warning on the format I introduced in July 2015 to go with the new mixer system, but not the older pre-July 2015 format that existed.  I think that not warning is likely the best case, or warning in all situations.  But in all honesty, if it isn't broken, just slightly inefficient, we probably do not have to warn.

**Comment by tschw** [comment]
Yeah, sure, what Ben said. Just go ahead and remove that warning. I just added it out of routine updating `toJSON`, pretty much.

**Comment by mrdoob** [comment]
> Just go ahead and remove that warning.

Even better 😀

**Comment by gero3** [comment]
superceded by #8759

**Pull request closed without merging**
