### PR TITLE
WebGPURenderer: Fix filterable depth textures

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/28784#discussion_r1665207548

**Description**

The problem seems a bit more complicated than it seems. We needed a `Texture.renderTarget` property to bind `RenderTarget` to get `RenderTarget.samples` and thus handle it in `WebGPUBackend`.

I tried to make `Texture.isRenderTargetTexture` become a get if `.renderTarget !== null` but this seems to break the tests in `WebGLRenderer` so I kept the property.

Now `webgpu_backdrop_water` work with antialias.

### CODE REVIEW

**Comment by Spiri0** [comment]
That sounds interesting, because since I think r167 I have to use the depthTexture with f32 in the shader, which I find very nice but the sampling has suffered a bit compared to the way with texture_depth_2d and its sampler. Sometimes I see very fine seems with the scalar depth value. It's nothing that really bothers me but with texture_depth_2d and sampler the quality was perfect.
Will this have an impact on this application?

```
sceneDepthPass = depthPass( scene, camera );
sceneDepthPassColor = sceneDepthPass.getTextureNode( 'depth' );

shaderParams = {
   viewPortDepthTexture: sceneDepthPassColor,
}

//in the wgsl shader header
viewPortDepthTexture: f32,
```

**Comment by sunag** [comment]
I remember you had commented, in theory it should solve, I just haven't tested it in `wgslFn`, it will add `multisampled` in the type like `texture_depth_multisampled_2d`.

**Comment by Spiri0** [comment]
I'm curious and will add your extension locally to test it. I now need the depth texture for occlusion culling anyway. I'm confident. Everything else is going like clockwork too.

**Comment by Spiri0** [comment]
Ah, so the type will extended.
In the fragment shader it works like this again:

```
fn main_fragment(
   vUv: vec2<f32>,
   depthTexture: texture_depth_2d,
   depthSampler: sampler,
) -> vec4<f32> {

   var depth = textureSample( depthTexture, depthSampler, vUv );

   //...
```

But now I can also use texture_depth_2d in the compute shader. Just samplers don't work. Since samplers and textureSampleLevel can be used in compute shaders, I added them in 3 places in the WGSLNodeBuilder and it works.
Your PR has good timing now that I'm dealing with occlusion culling in compute shaders. I'll make a PR right away where I've added the samplers for textureSampleLevel for compute shaders, it's pretty small.

**Comment by Spiri0** [comment]
I noticed a small conflict. The line:
```
( this.isSampleCompare( texture ) === false && texture.minFilter === NearestFilter && texture.magFilter === NearestFilter ) ||
```

in this function in the WGSLNodeBuilder.js corrupt https://github.com/mrdoob/three.js/pull/30033. 
If I comment out the line, the sampler for depth textures works again. The line specifically excludes depth textures.

```	
isSampleCompare( texture ) {
	return texture.isDepthTexture === true && texture.compareFunction !== null;
}
isUnfilterable( texture ) {
	return this.getComponentTypeFromTexture( texture ) !== 'float' ||
		( ! this.isAvailable( 'float32Filterable' ) && texture.isDataTexture === true && texture.type === FloatType ) ||
		( this.isSampleCompare( texture ) === false && texture.minFilter === NearestFilter && texture.magFilter === NearestFilter ) ||
		texture.isMultisampleRenderTargetTexture === true;
		this.renderer.backend.utils.getTextureSampleData( texture ).primarySamples > 1;

}
```
@sunag is the line essential?
Even with nearest filters for depth textures, samplers are important in compute shaders

**Comment by RenaudRohlinger** [comment]
Adding `antialias: true` caused the `webgpu_backdrop_water` to run at less than 50fps on my M1 Max, compared to a smooth 120fps previously. This is the first time I've experienced such low performance. Removing antialias fixes the issue. @sunag

**Pull request merged**
