### PR TITLE
Texture: Add defaults to textures.

### PR DESCRIPTION
**Pull request by gero3**
A followup on https://github.com/mrdoob/three.js/pull/17550#commitcomment-35227048.

This adds defaults to DataTexture2DArray & DataTexture3D.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by EliasHasle** [comment]
Quoting the [WebGL 2 specification](https://www.khronos.org/registry/webgl/specs/2.0/):

> _void texImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, ArrayBufferView? srcData)_
> 
> _void texImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, ArrayBufferView srcData, GLuint srcOffset) (OpenGL ES 3.0.4 §3.8.4, man page)_
> 
> Allocates and initializes the specified mipmap level of a three-dimensional or two-dimensional array texture.
> 
> If a WebGLBuffer is bound to the PIXEL_UNPACK_BUFFER target, generates an INVALID_OPERATION error.
> 
> **If srcData is null, a buffer of sufficient size initialized to 0 is passed.**

So this should be right, for the same reasons it was right with `DataTexture`.

I am a bit scared by this line, though:
https://github.com/mrdoob/three.js/blob/2d7c0b461ef483a2cd46ca2057ba64880716b5ae/src/renderers/webgl/WebGLTextures.js#L325

I cannot (using GitHub search) find any place where `texture.image.complete` is set, for _any_ type of texture. Then I would guess it is done outside three.js, but that cannot be the case for `DataTexture`, right?

**Comment by Mugen87** [comment]
Merging this one for consistency and testing on `dev`.

**Comment by Mugen87** [comment]
Updated builds: cfdfcd76c29e7b8c2bb7a31dc7670ff3167d64c2

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
