### PR TITLE
Rollup: Removed glconstants() optimization

### PR DESCRIPTION
**Pull request by mrdoob**
Related: 25eee2d7c1c3094ebfa7daa5751c09fda817b115

**Description**

Just testing what are the file size saving when using `glconstants()`

### CODE REVIEW

**Comment by LeviPesin** [comment]
@marcofugaro I think the read size workflow doesn't react to changes in `utils`...

**Comment by mrdoob** [comment]
Ah, I think that's fine. I'll update something on `/src`.

**Comment by mrdoob** [comment]
@marcofugaro

Is it possible to update that report so it looks like this?

| Filesize `dev` | Filesize | Diff  |
|---|---|---|
| 626.8 kB (155.8 kB) | 632.4 kB (156.7 kB) | +5.51 kB |

**Comment by Mugen87** [comment]
To me, the savings in file size are negligible. I vote to remove `glconstants()`.

**Comment by mrdoob** [comment]
Sounds good yeah! 👍

**Pull request merged**
