### PR TITLE
content folder

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
Hi all,

This PR moves all example.html files into a separate `examples/content/` folder. All html links to various files have been updated as well as the two scripts which explicitly state a file path.

It was a pain to manually check each example during my workflow, was there a better way to check my work?

### CODE REVIEW

**Comment by looeee** [comment]
I think this is a great idea. It's a pain to scroll through hundreds of files every time I open the examples folder. However, I know it's been suggested before and encountered strong resistance. Not sure what the reasoning was. 

Not sure about the name `content/`, although I can't think of anything better right now. Perhaps it would reduce mental overhead to split the examples into folders by category?

**Comment by DefinitelyMaybe** [comment]
my guess for the resistance would be people's link's to various examples scattered around the internet. who knows how many. part two of a change like this would probably be a redirect of sorts.

**Comment by mrdoob** [comment]
> I think this is a great idea. It's a pain to scroll through hundreds of files every time I open the examples folder.

As far as I can see, this PR moves the pain to opening the examples/content folder...
What OS do you use? Your file manager doesn't have a file search in folder?

> my guess for the resistance would be people's link's to various examples scattered around the internet. who knows how many. 

Yep...

Honestly, I wouldn't spent time on this. I don't think this is a problem.

**Comment by DefinitelyMaybe** [comment]
ah. sounds like this is a specific user's thing then. I try not to open my OS's file system and just browse via vscode which as you can imagine, blows up anytime I open node_modules or the examples folder. The only other reason I could give for doing so would be separating concerns - everyone starts by thinking the examples page is one html page but really it's tons that are linked to later.

elaboration: say I change code that an example depends on, how do I know that example still works in the browser? I manually clicked threw all the examples in my locally served files as opposed to running an npm script (or something similar) which would tell me example x, y, z logged these errors to console.

**Comment by mrdoob** [comment]
> I try not to open my OS's file system and just browse via vscode which as you can imagine, blows up anytime I open node_modules or the examples folder. 

Sounds like an vscode issue then? 🤔

**Comment by DefinitelyMaybe** [comment]
> Sounds like an vscode issue then? 🤔

At this point in time it seems like a mostly-just-me kind of issue. I'll have a look around at other bits and pieces.

**Comment by looeee** [comment]
> At this point in time it seems like a mostly-just-me kind of issue

Well, there's at least two of us! 

Plus all the people here: #7053 

However, it would break a lot of links so I guess we're stuck with it.

**Comment by DefinitelyMaybe** [comment]
without dabbling into server side redirects, yes, we're stuck with it.

**Pull request closed without merging**
