### PR TITLE
Removed shading property for MeshNormalMaterial

### PR DESCRIPTION
**Pull request by leitzler**

### CODE REVIEW

**Comment by makc** [comment]
is this because smooth is default, or because it can't do face normals?

**Comment by leitzler** [comment]
Has been removed since March, see #6117 (where you were pretty active) :)

**Comment by makc** [comment]
checked 6117 and failed to see the relevance. if anything, that would allow MeshNormalMaterial to display flat shading, not disable that possibility

**Comment by mrdoob** [comment]
`SmoothShading` is default. We'll see about `FlatShading` later...

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
> SmoothShading is default. We'll see about FlatShading later...

Hmmm. You can't get smooth shading if you don't have smooth normals.

I am beginning to think that `SmoothShading` is a poor name.

`THREE.NormalShading` and `THREE.FlatShading` ?

**Comment by mrdoob** [comment]
`VertexShading`,  `FaceShading`? 😃

**Comment by WestLangley** [comment]
`material.flatShading = true` -- and remove `material.shading` ?

`material.shading = THREE.VertexNormalShading` / `THREE.FaceNormalShading` ?

`material.shading = THREE.NormalShading` / `THREE.FlatShading` ?

**Pull request merged**
