### PR TITLE
WebGLRenderer: Support for half-float textures.

### PR DESCRIPTION
**Pull request by tsone**
Added new type `THREE.HalfFloatType` as 1025 (the next available number). Set `WebGLRenderer` to accept this type.

### CODE REVIEW

**Comment by tsone** [comment]
BTW I didn't enable `EXT_color_buffer_half_float` as it doesn't seem to be necessary.

**Comment by benaadams** [comment]
https://www.khronos.org/webgl/public-mailing-list/archives/1501/msg00068.html

On Wed, Jan 14, 2015 at 9:42 AM, Florian BÃsch <pyalot@gmail.com> wrote:
> EXT_color_buffer_half_float and WEBGL_color_buffer_float which are in community approved status have dropped off the map (implementations have vanished). This is sort of a problem and I'd like to know if:
> Is there any intent to implement those?
> If not, should (can) it be dropped from the registry?

Any input on EXT_color_buffer_half_float and WEBGL_color_buffer_float?

**Comment by tsone** [comment]
@benaadams I didn't get the question, but I did some digging... In short, the correct way (according to my interpretation of the specs) to enable (half-)float attachments is to enable `WEBGL_color_buffer_float` and `EXT_color_buffer_half_float` and check the support from these. This should be done after `OES_texture_float` and `OES_texture_half_float` are enabled. ___So I should change the PR to enable these.__

I base my conclusion on the following parts of the specs:

[`OES_texture_float`](https://www.khronos.org/registry/webgl/extensions/OES_texture_float/):

> When this extensions is enabled: ... Implementations supporting float rendering via this extension will implicitly enable the WEBGL_color_buffer_float extension and follow its requirements. This ensures correct behavior when a texture with pixel type FLOAT is attached to an FBO. Although this feature has historically been allowed, new implementations should not implicitly support float rendering ___and applications should be modified to explicitly enable WEBGL_color_buffer_float.___

[`OES_texture_half_float`](https://www.khronos.org/registry/webgl/extensions/OES_texture_half_float/):
 
> When this extensions is enabled: ... Implementations supporting float rendering via this extension will implicitly enable the EXT_color_buffer_half_float extension and follow its requirements. This ensures correct behavior when a texture with pixel type HALF_FLOAT_OES is attached to an FBO. Although this feature has historically been allowed, new implementations should not implicitly support float rendering ___and applications should be modified to explicitly enable EXT_color_buffer_half_float.___

It's worth noting however, that _conformance test do not cover the aforementioned sections of the specs._ You can see this from the corresponding lines in [`OES_texture_float`](https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/extensions/oes-texture-float.html#L204-L235) and [`OES_texture_half_float`](https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/extensions/oes-texture-half-float.html#L292-L313). It is not verified that `WEBGL_color_buffer_float` or `EXT_color_buffer_half_float` are enabled when implementation supports the attachments implicitly.

Anyway, I find all the extension specs very vague on this part and they should be clarified.

**Comment by benaadams** [comment]
Sorry, was just quoting from the mailing list not asking question.

Mainly was highlighting that the last thing asked was if the extension should be dropped

**Comment by tsone** [comment]
Weird. When I enable `WEBGL_color_buffer_float` or `EXT_color_buffer_half_float` I get this:
```
"THREE.WebGLRenderer: OES_color_buffer_half_float extension not supported."
"THREE.WebGLRenderer: WEBGL_color_buffer_float extension not supported."
```

, but both float and half-float textures attachments work in practice. Very confusing... So should I enable `WEBGL_color_buffer_float` and `EXT_color_buffer_half_float` or not? How can I know the attachments are really supported?

**Comment by tsone** [comment]
Ok. I should've checked the extension date and related Khronos discussions. It appears `WEBGL_color_buffer_float` and `EXT_color_buffer_half_float` are both not yet fully supported in the browsers. See for example [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1102667) from last month by Mozilla. It seems these extensions are incoming.

So my PR seems to be valid _right now_ from the extensions point of view. It's possible some changes are needed when the above extensions are implemented in the browsers.

**Comment by tsone** [comment]
Added documentation. Is this good to go?

**Comment by mrdoob** [comment]
Looks good! But do you mind including an example too?

**Comment by tsone** [comment]
I tried this with the `webgl_shaders_ocean2` example  (which is not in `index.html` BTW). The simulation run much faster and the half-float inaccuracies were not that apparent. I could modify the sample so one can switch between float and half-float rendertargets.

**Comment by tsone** [comment]
Done. `webgl_shaders_ocean2` can now use half-floats in the simulation. When using half-floats, the waves are not as "sharp", so this shows quite well the accuracy-speed tradeoff of half-floats.

**Comment by tsone** [comment]
Was the introduction of `setMaterial()` distracting here? I can tidy this up, also removing unnecessary changes. Would it be better?

**Comment by mrdoob** [comment]
Great! Many thanks!

**Comment by Avnerus** [comment]
I just want to note that this fix enables this FBO example:
http://mrdoob.com/lab/javascript/webgl/particles/particles_zz85.html
To run on iOS. It used to generate framebuffer errors and not render anything, but after changing to "type:THREE.HalfFloatType" in  THREE.WebGLRenderTarget, it works perfectly!
Thanks

**Comment by mrdoob** [comment]
Oh! Interesting... ^^

**Comment by felixpalmer** [comment]
Inclusion of this is pretty huge for me too (enables piste.io on iOS). Hope it makes the next release, will be patching until then

**Comment by tsone** [comment]
Nice to hear :)

**Pull request merged**
