### PR TITLE
New CylinderBufferGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces `CylinderBufferGeometry`. 

@mrdoob You can test the new geometry with this [jsfiddle](https://jsfiddle.net/57b0mh5k/6/).

### CODE REVIEW

**Comment by mrdoob** [comment]
@WestLangley that's how it has always been...

**Comment by WestLangley** [comment]
Well, perhaps the end-caps should have a different material index, and UVs to match `CircleGeometry`? Just a thought...

**Comment by Mugen87** [comment]
I would prefer if this PR just contains a 1:1 port from `Geometry` to `BufferGeometry`. Any other changes like @WestLangley suggestions should be done in a separate PR. That's a more clear approach i think...

**Comment by WestLangley** [comment]
@Mugen87 That is fine with me.

**Comment by mrdoob** [comment]
Many thanks!

**Comment by mrdoob** [comment]
Seems like there has been a regression...
The normals aren't computed correctly when one of the radius is 0.

https://jsfiddle.net/57b0mh5k/7/
https://jsfiddle.net/gtovpvuu/ (r74)

**Comment by Mugen87** [comment]
Oops!, i think i didn't regard this special case. I've updated the three.js build in my fsfiddle example and provided a new PR.

**Pull request merged**
