### PR TITLE
Coverage testing (#1)

### PR DESCRIPTION
**Pull request by Beakerboy**
Code Coverage

**Description**

Code coverage is an important metric to watch. It looks like the unit tests cover 56% of the code. You could possibly insist that any contribution increase the coverage percentage, which could bring the number up quickly.

### CODE REVIEW

**Comment by Beakerboy** [comment]
Current stats can be seen here:
https://coveralls.io/github/Beakerboy/three.js

**Comment by Mugen87** [comment]
I'm not sure we need _yet another metric_ especially since unit testing in context of WebGL is tricky to implement. The classes that are easier to write tests for like the math classes have already a good coverage.

**Comment by mrdoob** [comment]
Agreed. The golden image test in the CI are much more useful than unit tests.

**Comment by Beakerboy** [comment]
I’m curious if you know of a way to wrap these functional tests within Qunit. I think it can only help the project to have the ability to prove that as many execution pathes are followed during testing as possible, either through unit or functional tests.

**Comment by mrdoob** [comment]
How will it help the project?

**Comment by Beakerboy** [comment]
If there are execution paths that are untested, there is no guarantee that they work correctly.

**Comment by mrdoob** [comment]
I would say that a library that has been actively used (thus tested) for 13 years by thousands of developers is a bit of a guarantee that all the paths work correctly.

**Comment by mrdoob** [comment]
> I’m speaking more philosophical than about threejs specifically…

We prefer three.js specific contributions 🙏

> I was just working on some custom geometries and using the existing threejs testing architecture to test it, and wanted to make sure all my paths were tested, so I thought I’d pass some of that work over to you.

Do you understand that by adding more dependencies to the project we'll get more vulnerability alerts which will result in extra work and stress for us maintainers?

You have good intentions but this PR would actually damage the project.

**Pull request closed without merging**
