### PR TITLE
webgl_materials_envmaps_parallax.html : modify the color value

### PR DESCRIPTION
**Pull request by 1993heqiang**
**Description**
The color value does not match the variable name.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
BTW: Do you mind regenerating the example screenshot via `npm run make-screenshot webgl_materials_envmaps_parallax`?

The E2E test works however the visual appearance of the example has still changed.

**Comment by mrdoob** [comment]
How is it possible that E2E didn't fail here?

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_envmaps_parallax.html
https://raw.githack.com/1993heqiang/three.js/local_dev/examples/webgl_materials_envmaps_parallax.html

**Comment by 1993heqiang** [comment]
> BTW: Do you mind regenerating the example screenshot via `npm run make-screenshot webgl_materials_envmaps_parallax`?
> 
> The E2E test works however the visual appearance of the example has still changed.

I have regenerated the screenshot. 👌

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
