### PR TITLE
Fix for OrbitControls not allowing keyboard input in iframe

### LINKED ISSUE #15619: OrbitControls Keyboard controls don't work when in an Iframe
##### Description of the problem

The keyboard for OrbitControls don't work in an iframe. The reason is the `mousedown` handler calles `preventDefault`. Part of that default is the iframe getting the focus

See this example: https://jsfiddle.net/3foLr7sn/ or this one  https://jsfiddle.net/qgu17w5o/   both are the default bug report examples

Drag on the sphere then press the arrow keys. Note they don't work

##### Three.js version

- [X] Dev
- [X] r100

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

### PR DESCRIPTION
**Pull request by greggman**
Fixes #15619

### CODE REVIEW

**Comment by Mugen87** [comment]
I think you somewhat implement the suggestion by @mrdoob right here: https://github.com/mrdoob/three.js/issues/9437#issuecomment-371344278

TBH, I've changed my mind since this discussion. The behavior of `OrbitControls` with such a fix is better than before.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@greggman @Mugen87 

This PR causes problems on MacOS Safari/Chrome. Not sure about other platforms...

One is now unable to toggle the Chrome Developer Tools or Safari Web Inspector with keystrokes when using `OrbitControls`. For example, `opt-cmd-i`.

**Comment by Mugen87** [comment]
@WestLangley Yep, can reproduce. @greggman does already have a solution for this 👍

**Pull request merged**
