### PR TITLE
Add userData to BufferGeometry

### PR DESCRIPTION
**Pull request by takahirox**
This PR adds `userData` property to `Geometry` and `BufferGeometry`.

See https://github.com/mrdoob/three.js/issues/11944#issuecomment-322255204 and https://github.com/mrdoob/three.js/pull/13241#discussion_r182543274

### CODE REVIEW

**Comment by takahirox** [comment]
Thanks, updated.

**Comment by mrdoob** [comment]
I guess you added it to `Geometry` too for consistency? Maybe it would be better only adding it to `BufferGeometry`?

**Comment by takahirox** [comment]
Yes, for the consistency. But it's ok to remove from `Geometry` if you don't like because I don't have strong preference.

**Comment by takahirox** [comment]
Can we merge if looking ok?

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
