### PR TITLE
Raycaster stereo

### PR DESCRIPTION
**Pull request by anhr**
@mrdoob has closed my previous Raycaster stereo [pull request](https://github.com/mrdoob/three.js/pull/16047) before I have answered to his question:
Why are you raycasting in stereo-screen space? What's your use case? 
Sorry for delay. 
I hope, I understand you. I want to use mouse in stereo-screen space for selecting an object. Old version of THREE.Raycaster is not compatible with THREE.StereoEffect. For testing of the old version  of THREE.Raycaster please open webgl_raycaster_stereo.html page,  check the "Old version" check box and choice an item in the "Spatial multiplex" of the "Stereo effects" folder. Now you can select an object on the canvas by the mouse in the "Mono" spatial multiplex but CAN NOT to do it in "Side by side" or "Top and bottom" spatial multiplex. I have divided the mouse position to two positions: mouseL and mouseR for resolving of the problem. See mousePosition function in the StereoEffect.js file for details. Please uncheck the "Old version" check box and test my new version of the THREE.Raycaster.

See more details about problem here : [Using ThreeJS StereoEffect and Raycaster](https://stackoverflow.com/questions/33655238/using-threejs-stereoeffect-and-raycaster)

For testing:
https://raw.githack.com/anhr/three.js/raycaster_stereo/examples/webgl_raycaster_stereo.html

### CODE REVIEW

**Comment by mrdoob** [comment]
>  I want to use mouse in stereo-screen space for selecting an object. 

Why do you want to do that? I need to understand that before going further on reviewing this.

**Comment by anhr** [comment]
> > I want to use mouse in stereo-screen space for selecting an object.
> 
> Why do you want to do that? I need to understand that before going further on reviewing this.

Please go to my [example](https://raw.githack.com/anhr/three.js/raycaster_stereo/examples/webgl_raycaster_stereo.html). You can see two cubes and three points there. Open the Stereo Effects branch in the upper right corner of the page and choice the "Side by side" item of the "Spatial multiplex" control. Uncheck the "Old version" check box.

I want to change color of the cube to red if user moves mouse over cube and I want see 3D coordinates of the point if user  moves mouse over point.

I could not do it in the old version. For testing of old version please check the "Old version" check box. I hope, you understand me.

**Comment by mrdoob** [comment]
Why do you want to show stereo in a website?

**Comment by anhr** [comment]
I think we do not understand one another. I use my 3D TV as monitor for my PC. Stereo mode allow me to convert 2D picture to 3D.

**Comment by mrdoob** [comment]
Sorry, I don't raycasting with a `StereoEffect` is such a common case that should be included in this repo. I think it would be better to have its own repo.

**Pull request closed without merging**
