### PR TITLE
update on selective bloom example

### PR DESCRIPTION
**Pull request by sciecode**
fixes mesh naming and header info from `box` to `sphere`.
inline with 2a174cf changes.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/sciecode/three.js/dev12/examples/webgl_postprocessing_unreal_bloom_selective.html

**Review by Mugen87 — APPROVED** [review]

**Comment by sciecode** [comment]
> https://raw.githack.com/sciecode/three.js/dev12/examples/webgl_postprocessing_unreal_bloom_selective.html

Ops, forgot to add example link. Thank you.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Please don't forget to remove temporary live links after PR is merged.

**Pull request merged**
