### PR TITLE
getProgramInfoLog can return '\0' instead of empty string

### LINKED ISSUE #9317: WebGLRenderingContext.getProgramInfoLog returns empty string of length 1
##### Description of the problem

Maybe it's a bug of Chromium, but `programLog` contains a empty string of length 1
threejs-bug
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome - Version 51.0.2704.106 (64-bit)
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

AMD FX(tm)-8120 Eight-Core Processor
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]

Regards.

### PR DESCRIPTION
**Pull request by ZaWertun**
It seems to happen only on specific versions of Chrome / Chromium, see https://bugs.chromium.org/p/chromium/issues/detail?id=111337.

Fixes #9317

### CODE REVIEW

**Comment by mrdoob** [comment]
Would `programLog.trim() !== ''` work?

**Comment by ZaWertun** [comment]
Nope...
```javascript
'\0'.trim() == '\0'
true
```

**Comment by mrdoob** [comment]
I see... I would add a comment on top explaning why we are checking for \0 though.

**Comment by ZaWertun** [comment]
Let's see.
I prepared truth table for the expression `programLog !== '' && programLog !== '\0'` (0 - false, 1 - true).

|   | `programLog := ''` | `programLog := '\0'` | other values |
| --- | :---: | :---: | :----: |
| `programLog !== ''` | 0 | 1 | 1 |
| `programLog !== '\0'` | 1 | 0 | 1 |
| `programLog !== '' && programLog !== '\0'` | 0 | 0 | 1 |

As the result only if both expressions returns  `true` we will see warning in the console.

Also we can use De Morgan's law () and rewrite expression as following: `!(programLog === '' || programLog === '\0')`.

Correct me if I'm wrong.

**Comment by ZaWertun** [comment]
> I see... I would add a comment on top explaning why we are checking for \0 though.
Yep, comment is needed.

**Comment by mrdoob** [comment]
@kenrussell on linux machines `getProgramInfoLog()` returns `'\0'` when there are no warnings, should we add this check or is this being fixed in Chrome?

**Comment by kenrussell** [comment]
@mrdoob Please provide about:gpu information (copy/paste, plaintext fine, maybe as a gist) from a machine on which this happens. I couldn't reproduce it on my Linux workstation the last time I tried.

**Comment by kenrussell** [comment]
By the way, yes, I would probably add the check, if you are considering a non-empty program info log upon successful link as always containing warnings.

**Comment by mrdoob** [comment]
> @mrdoob Please provide about:gpu information (copy/paste, plaintext fine, maybe as a gist) from a machine on which this happens. I couldn't reproduce it on my Linux workstation the last time I tried.

@ZaWertun can you provide that?

**Comment by ZaWertun** [comment]
In short - I'm using the Intel(R) HD Graphics 3000.
about:gpu - https://paste.fedoraproject.org/401589/raw/

**Comment by kenrussell** [comment]
Thanks. I've notified some colleagues at Intel about this. This is a really old GPU and a somewhat old version of Mesa, and I'm hoping that it can or will be fixed in subsequent versions of Mesa.

Again, appreciate your filtering out these sorts of somewhat-bogus program info logs.

**Comment by zhenyao** [comment]
We really should not depend on getProgramInfoLog to be empty to determine if a compile/link is successful or not - there can be warnings, etc on a successful link, or if a driver just emits "succeed", it's totally spec compliant. Instead, use getProgramParameter(LINK_STATUS).

**Comment by mrdoob** [comment]
@zhenyao yes, that's what we do already:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js#L533

The issue here is that, in some configurations, `getProgramInfoLog()` returns `'\0'` instead of `''`.

**Comment by mrdoob** [comment]
> Thanks. I've notified some colleagues at Intel about this. This is a really old GPU and a somewhat old version of Mesa, and I'm hoping that it can or will be fixed in subsequent versions of Mesa.

I'm thinking that maybe it's better to let Intel/Mesa deal with this. The only thing this solves is having a clean console.

**Comment by zhenyao** [comment]
FYI: we decided to clean it up in Chrome anyway to get rid of the "\0" logs.

**Comment by mrdoob** [comment]
✌️

**Pull request closed without merging**
