### PR TITLE
Docs: Created Docs for Japan

### PR DESCRIPTION
**Pull request by ren-ozeki**
I tried to translate docs for Japan.

Using the Korean and Arabic examples as a reference,
I translated only "Creating-a-Scene" into Japanese.

Is this the right way to do it?
If you have any other better way, please let me know !
I'd like to continue with the translation if this is the right way to go.

### CODE REVIEW

**Comment by FMS-Cat** [comment]
the translation smells like a translation a bit.
what is the purpose of the translation?

**Comment by ln3187** [comment]
Thank you for your comments!

My purpose is to make it easier for those who want to try drawing on the web(including me) to read the Three.js documentation.

Of course, I also would like to make my translation more natural.
I'll try to improve it and make it more natural in the next commit, can you take a look?

**Comment by FMS-Cat** [comment]
I'm new to docs contribution and I'm not sure of the climate about translations. I want to hear from other contributors.
But in my opinion, I feel like this specific document have a big role to almost all user of Three.js and it's pretty good to have a translation of the document.

And yes I can review your translation (I'm a Japanese main btw).

**Comment by hareha** [comment]
Hi, I'm translating korean Docs now.
There was the same question about korean.
https://github.com/mrdoob/three.js/pull/20292#issuecomment-690458593 will help.

It's need to be translated complete Manual section at least I think.

**Comment by ln3187** [comment]
Thanks for replying and I'm glad you gave me some advice.

Once the translation of the Manual section is finished, I will send a new PR.
Therefore, I think of closing this PR, is it okay?

**Pull request closed without merging**
