### PR TITLE
Fixed memory leak in OBJLoader for V8 based js engines

### PR DESCRIPTION
**Pull request by Cobertos**
See issue #9679

### CODE REVIEW

**Comment by mrdoob** [comment]
I'll merge by now, but I'll add a note.

**Comment by mrdoob** [comment]
Thanks!

**Comment by jonnenauha** [comment]
Cool find, I'll try to check at some point if this has any impact on the perf. One particular perf problem is GC pauses while parsing large OBJ files. Not entirely sure if this will make it worse or better. It could not have to collect more stuff as it's no longer leaking, hard to say though without testing :)

**Comment by Coburn37** [comment]
The .obj is 37MB, 1.02 million lines. The strings would collect between an "invocation" of a specific component in our application that uses the WebGLRenderer. Even after deleting the canvas and disposing() of the objects there would still be one copy of this string in memory which piled up after a couple view changes. It was enough that I was getting 1GB profiles after around 10 or so changes and it was crashing the app.

**Pull request merged**
