### PR TITLE
AssimpJSONLoader: Refactoring

### PR DESCRIPTION
**Pull request by Mugen87**
Refactors/simplifies the loader and the corresponding example.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by mrdoob** [comment]
Actually... what do you think about deprecating `AssimpJSONLoader` and encourage using `AssimpLoader` directly instead? 😅

**Comment by Mugen87** [comment]
Now that you say it :sweat_smile: . `AssimpLoader` was developed after `AssimpJSONLoader`, right? 

I think there are no reasons why users should use `AssimpJSONLoader` if they can directly load the assimp binary format.

**Comment by mrdoob** [comment]
Yeah!

**Comment by mrdoob** [comment]
I guess the main thing is to get `.assimp` files for `interior/` and `jeep/` here:

https://github.com/mrdoob/three.js/tree/dev/examples/models/assimp

And, if `AssimpLoader` can load it properly, then yeah...

**Comment by Mugen87** [comment]
Okay, i'll put this on my todo list :grin:

**Pull request merged**
