### PR TITLE
[wip] optimize(?) buffer binding between calls

### PR DESCRIPTION
**Pull request by pailhead**
It's possible to some times end up binding the same buffer over and over between calls. It doesn't seem very likely, and might not happen in such a number to really matter.

## r99:

https://raw.githack.com/pailhead/three.js/test-buffer-binding/examples/test.html

```
bindBuffer: 12
vertexAttribPointer: 8
```

## this branch:
https://raw.githack.com/pailhead/three.js/test-buffer-binding-build/examples/test.html

```
bindBuffer: 9
vertexAttribPointer: 5
```

The example basically renders the same sphere, but with different materials and (not sure how to categorize) instancing. The index and the positions are the same, but other draw calls may include normals and an instancing attribute.

It seems that attributes are treated on the geometry level, but it may be possible that two consecutive geometries share some of the attibutes and locations. I imagine it may not happen often if at all most of the time, but i'm wondering if there is some kind of an approach that would see a benefit from doing this diffing more granular. Any thoughts?

### CODE REVIEW

**Comment by pailhead** [comment]
image

It didn't seem to catch the instanced attribute (4 here should be bound only once):

image

And this illustrates the point, where in order to reduce these the most, it would make sense to render the instanced with normals, after the non instanced one with normals.

**Comment by mrdoob** [comment]
Have you tried a scene with, say, 1000 objects to see if this improves performance?

**Comment by pailhead** [comment]
Hmmm, i wasn't sure what a good real world test would be, but i tried to make a synthetic one, where i made a bunch of iterations and render them in the worst possible order. At first it felt like a small increase, now the same scene is actually rendering slower, i don't quite understand why :)

Less commands though:
image
image

**Comment by Mugen87** [comment]
A more promising approach is #14600 which completely eliminates redundant WebGL state changes.

**Comment by mrdoob** [comment]
@pailhead seems like this should be closed?

**Pull request closed without merging**
