### PR TITLE
VertexTangents: Only create varyings if necessary

### PR DESCRIPTION
**Pull request by Mugen87**
This PR ensures that varyings related to vertex tangents are only created if a normal map is present. Without this fix, a warning appears in the browser console like in this example:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_animation_keyframes.html

see https://github.com/mrdoob/three.js/pull/15749#issuecomment-464206817

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks! Note there are two other ways we could do this –

(A) ensure GLTFLoader doesn't set `vertexTangents=true` if there's no normal map.
(B) ensure that `WebGLProgram.js` doesn't set `USE_TANGENT` if there's no normal map.

I don't like (A) so much, but (B) seems worth considering. For example, we do something similar for `OBJECTSPACE_NORMALMAP`:

```
( parameters.normalMap && parameters.objectSpaceNormalMap ) ? '#define OBJECTSPACE_NORMALMAP' : '',
```

**Comment by mrdoob** [comment]
> (A) ensure GLTFLoader doesn't set `vertexTangents=true` if there's no normal map.

I think I prefer this option better...

**Comment by donmccurdy** [comment]
My concern with that would be that if the user is applying textures after loading the model, they need to know about the `vertexTangents` setting and they probably don't. By contrast this would work fine in that situation:

```js
( parameters.normalMap && parameters.verexTangents ) ? '#define USE_TANGENT' : '',
```

**Comment by Mugen87** [comment]
I'm basically open for bot solution but checking  `normalMap` and `vertexTangents` in `WebGLProgram` seems cleaner to me than doing this in the shader chunks. Let me make this change...

**Comment by mrdoob** [comment]
Hmm, then I think I would move the check to here instead:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLPrograms.js#L166

```js
vertexTangents: material.normalMap && material.vertexTangents,
```

I have the feeling we could be creating duplicate identical shaders otherwise.

**Comment by donmccurdy** [comment]
I think the logic works out to avoid duplicate shaders either way? But that change sounds better to me sure. 👍

**Comment by WestLangley** [comment]
I am inclined to agree with @mrdoob. Because of the program code, 'parameters.vertexTangents' should be `true` if and only if 'USE_TANGENT' is defined.

**Comment by Mugen87** [comment]
Updated the PR.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
