### PR TITLE
TTFLoader: Migrate completely to modules.

### PR DESCRIPTION
**Pull request by Mugen87**
Provides `opentype.module.min.js` so `TTFLoader` does not rely on global variables anymore.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev49/examples/webgl_loader_ttf.html

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev49/examples/webgl_loader_ttf.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by Itemshopp** [comment]
Sorry to 'open' this merged PR since 2 years but I found a problem here in `opentype.module.min.js` that I resolved locally, wanted to show it to you. 

in `opentype.module.min.js` in the first lines : 

```
(function(f)
{
        if(typeof exports==="object"&&typeof module!=="undefined")
        {
            module.exports=f();
        }
        else if(typeof define==="function"&&define.amd)
        {
            ....
        }
        else
        {
            ....
        }
 })
```

file ending with : 

```
export var opentype = window.opentype;
```

`import { opentype } from '../libs/opentype.module.min.js';` is then `undefined` in `TTFLoader`

roughly correcting it with this in `opentype.module.min.js` : 

```
if(typeof exports==="object"&&typeof module!=="undefined")
{
    module.exports=f();
    
    window.opentype=f();
}
```

**Comment by Mugen87** [comment]
> import { opentype } from '../libs/opentype.module.min.js'; is then undefined in TTFLoader

Um, I can't reproduce this in the official example: https://threejs.org/examples/webgl_loader_ttf

Do you need a special setup?

**Comment by Itemshopp** [comment]
Ow, I forgot to indicate I'm Using ViteJS to compile files, when building project, it enters the `if` , but `window.opentype` remains `undefined`

**Comment by Mugen87** [comment]
Um, it seems there is an official module version of `opentype.js`, see https://github.com/opentypejs/opentype.js/tree/master/dist

I've tested it with `TTFLoader` and it seems to work fine. The only thing I had to change was to change the import in the loader to:
```js
import opentype from '../libs/opentype.module.js';
```
Can you please check if using this approach fixes the issue on your side? If so, I'll file a PR and update the `opentype` depdency.

**Comment by Itemshopp** [comment]
@Mugen87 Worked fine when :

1 ) I created an `opentype.module.js` file in `three/examples/jsm/libs` folder with the content of `https://github.com/opentypejs/opentype.js/blob/master/dist/opentype.module.js`

2) Replaced `import { opentype } from '../libs/opentype.module.min.js` with `import opentype from '../libs/opentype.module.js`

My TTF files are readable again ! Thanks for your help and hope this PR will be released soon

**Pull request merged**
