### PR TITLE
Introduce Texture.colorSpaceConversion

### PR DESCRIPTION
**Pull request by takahirox**
Related issue: #21318

**Description**

This PR introduces `Texture.colorSpaceConversion` property to control `gl.UNPACK_COLORSPACE_CONVERSION_WEBGL` for `gl.pixelStorei()`.

`Texture.colorSpaceConversion` takes new constant `DefaultColorSpaceConversion` or `NoColorSpaceConversion` which correspond to `gl.BROWSER_DEFAULT_WEBGL` or `gl.NONE` respectively. The default is `DefaultColorSpaceConversion`.

`WebGLRenderer` calls `gl.pixelStorei(gl.UNPACK_COLORSPACE_CONVERSION_WEBGL, texture.colorSpaceConversion)` at texture uploading.

`GLTFLoader` sets `texture.colorSpaceConversion` to `NoColorSpaceConversion` because any additional color space conversion embedded in the image files must be ignored in glTF.

### CODE REVIEW

**Comment by Mugen87** [comment]
I'm a bit irritated. `UNPACK_COLORSPACE_CONVERSION_WEBGL` has a default value of `BROWSER_DEFAULT_WEBGL`. How does this setting currently affect color space conversion? I though we are controlling this process on engine level via `Texture.encoding`.

Besides, couldn't you just always set `UNPACK_COLORSPACE_CONVERSION_WEBGL` to `gl.NONE` instead of introducing a new property? Many suers hardly understand `Texture.encoding`. I'm afraid an additional property `colorSpaceConversion` makes the understanding even more complex.

**Comment by lexaknyazev** [comment]
> `UNPACK_COLORSPACE_CONVERSION_WEBGL` has a default value of `BROWSER_DEFAULT_WEBGL`. How does this setting currently affect color space conversion?

In the forth column of the new `TextureEncodingTest` sample, the PNG-embedded ICC profile skews RGB definitions in such a way that a pixel value of (0; 136; 0) is returned as (193; 0; 0). By setting `UNPACK_COLORSPACE_CONVERSION_WEBGL` to `NONE` (or by setting a similar option for `ImageBitmap`), an application requests web browser to pass original values as-is, ignoring possible color transformations.

**Comment by takahirox** [comment]
Always `gl.NONE` for `gl.UNPACK_COLORSPACE_CONVERSION_WEBGL` was another option in my mind, too, but I'm not sure if it's ok because I'm not sure how much popular embedded color space/gamma in image file is.

**Comment by Mugen87** [comment]
>  the PNG-embedded ICC profile skews RGB definitions in such a way that a pixel value of (0; 136; 0) is returned as (193; 0; 0).

Just for my understanding: Let's say you are loading a normal map as PNG via `TextureLoader` (which internally uses an ordinary HTML image element). If the texture has such a ICC profile (for whatever reasons), the rendered output would not be correct, right?

If so, it's seems better to always set `gl.UNPACK_COLORSPACE_CONVERSION_WEBGL` to `gl.NONE`. Color space conversion should be controlled by the engine and not by the browser.

**Comment by lexaknyazev** [comment]
> If the texture has such a ICC profile (for whatever reasons), the rendered output would not be correct, right?

That would depend on the reasons why such ICC profile was embedded. In a completely hypothetical situation when the normal map was authored with the profile in mind, the output would be correct. In practice, non-color textures (e.g. normals, occlusion, roughness, etc) should be never defined in color-related terms because they do not technically contain color data.

On the other hand, when a texture is directly sourced from an external image stored in non-sRGB space (e.g. a photo saved in Adobe RGB), there could be a legit case for letting the browser to perform ICC transformations to ensure that the engine gets sRGB values.

glTF requires color textures to use sRGB for portability reasons (i.e. it disallows the aforementioned example). This may be too strict for other three.js use cases.

**Comment by feruzoyen** [comment]
Yes

**Comment by Mugen87** [comment]
Okay, let's see how @mrdoobs thinks about this issue. I vote to ignore embedded ICC profiles in the engine and let the user define `Texture.encoding` instead.

**Comment by feruzoyen** [comment]
Hello

**Comment by feruzoyen** [comment]
Ok

**Comment by feruzoyen** [comment]
Tq

**Comment by takahirox** [comment]
Either one is fine to me. Personally I would prefer adding flexibility but no strong opinion.

And in the view of the performance I think probably the color transformation leads to additional CPU cost and longer texture upload(decode) time so that ideally users should pre apply the transform beforehand.

**Comment by lexaknyazev** [comment]
> users should pre apply the transform beforehand

They should, in general. Extra flexibility enables use cases when the application does not control texture sources, e.g. a user provides a URL to an external photo JPEG.

**Comment by Mugen87** [comment]
I'm just afraid that all this will overwhelm the average `three.js` user. Most users already struggle with getting a consistent color space workflow.

**Comment by mrdoob** [comment]
> Okay, let's see how @mrdoob thinks about this issue. I vote to ignore embedded ICC profiles in the engine and let the user define `Texture.encoding` instead.

I agree. Lets solve this by setting `gl.UNPACK_COLORSPACE_CONVERSION_WEBGL` to `gl.NONE` for now.
We can add flexibility if we see compelling use cases.

**Comment by Mugen87** [comment]
@takahirox Since you are already working at this topic, I suggest you make a new PR as a replacement for #21324 and #21323. The new PR should do this https://github.com/mrdoob/three.js/pull/21324#issuecomment-783314634 and this https://github.com/mrdoob/three.js/pull/21323#issuecomment-783252472.

**Comment by takahirox** [comment]
Closing in favor of #21336

**Pull request closed without merging**
