### PR TITLE
Use unified Log,Warn & Error handlers, rather than directly using console.error/warn/log

### PR DESCRIPTION
**Pull request by bhouston**
In https://Clara.io, we need to know if any errors or warnings happen within ThreeJS.  Right now most errors and warnings are piped to the console.  This isn't useful for us.  So in our version of Three.JS we have created centralized THREE.error and THREE.warning functions that are used instead of writing to console.log/error/warn that are optionally redirectable.

This allowed us to identify a number of bad behavior in our code.  We love this functionality and the default error and warning handlers output to console.error and console.warn respectively, so this doesn't change default behavior, just adds flexibility.

### CODE REVIEW

**Comment by mrdoob** [comment]
Merged!

However, I'm not totally convinced about `THREE.log`, `THREE.warn` and `THREE.error`...

Would it be weird to have a different namespace for it?

`LOG.log`, `LOG.warn`, `LOG.error`, ...?

**Comment by JackCA** [comment]
@mrdoob I definitely think name-spacing it like it is to `THREE` and limiting the global namespace to just one variable is a good move. `LOG` seems a bit too generic. Glad this was merged!

**Comment by JanWaller** [comment]
There are still several instances using the "old" console.log .warn .error mechanism. Should they be changed as well?

**Comment by mrdoob** [comment]
Yep! That'd be nice.

**Comment by mrdoob** [comment]
Hmmm... I just stumbled into this...

screen shot 2015-05-08 at 3 53 50 pm

screen shot 2015-05-08 at 3 49 02 pm

Now we can't know where the warning is coming from. This is a bit of a deal breaker :(

**Comment by bhouston** [comment]
Could you just console.trace it instead?

**Comment by bhouston** [comment]
The reason why we use THREE.warn is because we capture it on remote machines and send it back to our server -- it is key to making it robust.

**Comment by mrdoob** [comment]
Would directly instrumenting console.log() and send the ones that start with THREE work?

```javascript
var _consoleLog = console.log;
console.log = function () {
    if ( typeof arguments[ 0 ] === 'string' && arguments[ 0 ].substr( 0, 5 ) === 'THREE' ) {
        sendToServer( arguments );
    }
    _consoleLog.apply( console, arguments );
};
```

**Comment by bhouston** [comment]
I am okay with this.  It is good idea.

On Friday, May 8, 2015, Ricardo Cabello <notifications@github.com> wrote:

> Would directly instrumenting console.log() and send the ones that start
> with THREE work?
>
> var _consoleLog = console.log;console.log = function () {
>     if ( typeof arguments[ 0 ] === 'string' && arguments[ 0 ].substr( 0, 5 ) === 'THREE' ) {
>         sendToServer( arguments );
>     }
>     _consoleLog.apply( console, arguments );
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/pull/5791#issuecomment-100386679>.
>


-- 
Best regards,
Ben Houston (Cell: 613-762-4113, Skype: ben.exocortex, Twitter:
@exocortexcom)
https://Clara.io - Online 3D Modeling and Rendering

**Comment by mrdoob** [comment]
Cool! I'll revert all the console.* changes then.

**Comment by dubejf** [comment]
It's generally frowned upon to modify the global objects.

There seems to be ways to preserve the line number that do no require to modify the console: https://gist.github.com/paulirish/c307a5a585ddbcc17242

This seem to work `THREE.log = Function.prototype.bind.call(console.log, console);` while allowing customization.

**Comment by makc** [comment]
just passing by...
> Now we don't know where the warning is coming from. This is a bit of a deal breaker :(

I do [this](http://jsfiddle.net/zo6jx7bb/):
```
        var s = (new Error()).stack
        s = s.substr(s.indexOf('\n') + 1)
        console.log('blah blah blah', '\n' + s)
```
this way, not only you know where :shit: happened, but also what code is responsible, without setting the breakpoint there. looks a bit different in different browsers, but I can live with it:
screen shot 2015-06-12 at 18 42 24

**Comment by makc** [comment]
> console.trace

this looks pretty in ff, but in chrome I do not get full stack. for [example](http://jsfiddle.net/zo6jx7bb/1/):
screen shot 2015-06-12 at 18 50 13

**Comment by DelvarWorld** [comment]
> Now we don't know where the warning is coming from. This is a bit of a deal breaker :(

@mrdoob You can figure out the stack trace simply by setting a breakpoint on that line. Is it still a deal breaker?

**Comment by makc** [comment]
@DelvarWorld yes but three.min.js is single line )

**Comment by mrdoob** [comment]
> Is it still a deal breaker?

Yep. New users shouldn't have to learn to use breakpoints just to know where a warning is coming from...

**Comment by makc** [comment]
@mrdoob it's not like they know now. some warning from vector's add method not accepting two arguments still requires them to place the breakpoint to find where offending call is in their own code.

**Comment by mrdoob** [comment]
Indeed. Is complicated enough already 😉

**Comment by robhawkes** [comment]
I've been trying to find a robust method for ViziCities to wrap console methods whilst keeping the correct line numbers – it's frustratingly hard.

[I found this though](http://stackoverflow.com/a/32928812/997339), which seems to work ([demo](http://codepen.io/anon/pen/pjeZPL?editors=101)). Also, apparently [Bows](https://github.com/latentflip/bows) keeps the original / target line number so might be worth looking into how they achieve it.

**Comment by bhouston** [comment]
I still use the THREE.error and THREE.warn wrappers in Clara.io even though they were removed from ThreeJs.

I do not find the lack of line numbers problematic at all because what I do right away is to capture the full stack, via ```new Error()).stack```, so that I know exactly the full context of the error.  I find that only the line numbers of the calling function insufficient for the most part for debugging in a complex application.

**Comment by DelvarWorld** [comment]
> @DelvarWorld yes but three.min.js is single line

Click this sneaky little button 
expand

> New users shouldn't have to learn to use breakpoints just to know where a warning is coming from... 

New users are probably not going to look at the source when they get a warning. Historically they'll google for it or ask in chat or stackoverflow. Ideally the warning itself is descriptive enough that it's self explanatory. I would also wager that people who know enough debugging concepts to navigate to the line generating the warning would also have enough debugging knowledge to set a breakpoint and get a stack trace.

**Comment by GGAlanSmithee** [comment]
I agree with @DelvarWorld and was actually thinking of doing a similar PR to this, not knowing there was one pending already.

Three.js uses the console a lot, which is good, but there are times when you want to adjust or silent it without affecting debugging outside of three, which is not (easily) doable when three uses the console directly.

**Comment by makc** [comment]
> adjust or silent it without affecting debugging outside of three

```javascript
console.log = function () {
    var stack = (new Error()).stack;
    if (stack has 'THREE' in it) return;
    call original log here :)
}
```

**Comment by GGAlanSmithee** [comment]
@makc well I guess, but that's kind of a hack. Still think this should be handled by three. Also, now I am altering `console.*` directly, which is something that you in general shouldn't do.

**Comment by DelvarWorld** [comment]
Also, a possibly better solution than any of this is to emit events on most of these cases. This removes the needs for any kind of hacks all together. If events were emitted by `Three` on things like shader errors (or possibly emitted by the actual materials themselves, which could extend `EventEmitter`), then the end user could listen for these cases. We've seen several use case needs for something like this in the wild, aka a way to hook into webgl feedback.

**Comment by makc** [comment]
@DelvarWorld +1 but then users have to know they need to listen to events.

**Comment by GGAlanSmithee** [comment]
Couldn't there just be a default three.js event handler that is set up to listen and log (to `console`) respective events, and instead there can be per case opt-out using namespaced events, etc?

**Comment by bhouston** [comment]
EventListener approach sounds really nice.  The default event listener would send the results to console?  But I guess this also necessitates a level of indirection before console.log() which causes the loss of the line numbers -- the concern brought up by @mrdoob.

**Comment by arose** [comment]
What about the approach suggested by @dubejf 

```JavaScript
THREE.log = Function.prototype.bind.call( console.log, console );
```

I've been using it ever since and you get line numbers just perfectly.

**Comment by DelvarWorld** [comment]
@bhouston I think the simplest solution is to just fire an event *and* log. anyone can listen, and there's no debugging issues when logging.

**Pull request merged**
