### PR TITLE
Unit-tests for BufferGeometry

### PR DESCRIPTION
**Pull request by simonThiele**
This is the first draft of unit-tests for BufferGeometry. Because it is more stuff I created this PR earlier for review so please don't merge it atm. There is also a fix for perspective matrix test which was discussed here #7171.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by tschw** [comment]
> please don't merge it atm

@mrdoob
accident?

**Comment by mrdoob** [comment]
Oh. Missed that 😅

**Comment by tschw** [comment]
IDK how it's even possible, but #7171 appears to be another PR with different commits off the same branch...

**Comment by simonThiele** [comment]
Np with merging but you will get another one with additions :)

**Comment by tschw** [comment]
Yes. If changes are OK, another PR won't hurt. But I'm curious: How do you create these different PRs from the same branch?

**Comment by simonThiele** [comment]
If parts of the branch were merged, you can recreate a PR and git only uses diffs

**Comment by tschw** [comment]
Ah, yes, of course! Could've figured that one out m). I think I got confused from the unfinished-looking on #7171... Thanks.

**Pull request merged**
