### PR TITLE
Puppeteer E2E test: Auto-download browser

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: https://github.com/mrdoob/three.js/pull/24109

**Description**

Make Puppeteer auto-download latest Chromium browser and merge `test/package.json` with the core `package.json` (they were splitted because `puppeteer` package is very large -- now `puppeteer-core` package is used and the browser is downloaded by the script).

### CODE REVIEW

**Comment by epreston** [comment]
Unrelated question: where do I set the global timeout on the e2e tests ?

**Comment by LeviPesin** [comment]
What is the "global timeout"? You should either increase `idleTime` variable (for how long there should be no network connections) or `parseTime` variable (for how long to parse data after loading).

**Comment by marcofugaro** [comment]
It takes around 10 seconds to download chrome on github actions, not bad!

image

**Comment by mrdoob** [comment]
Ops... Some conflicts to resolve...

**Comment by LeviPesin** [comment]
It's conflicting with https://github.com/mrdoob/three.js/pull/25384, I think...

**Comment by mrdoob** [comment]
I deleted `test/package-lock.json`. Now there are only conflicts in `pupeteer.js`.

**Comment by LeviPesin** [comment]
@mrdoob I think I resolve the conflicts.

**Pull request merged**
