### PR TITLE
remove ability to set depth formula on MeshDepthMaterial.

### PR DESCRIPTION
**Pull request by bhouston**
This PR implements the conclusions derived from a discussion between @WestLangley  @mrdoob and myself here: https://github.com/mrdoob/three.js/pull/8586

We decided to remove the ability to set the depth formula in MeshDepthMAterial and thus are always relying upon gl_FragCoord.z.

This ends up removing a lot of code and is probably the right thing to do anyhow as the flexilibity offered before was unnecessary and all the code in ThreeJS has already been updated to be able to decode gl_FragCoord.z as necessary in the previous PR.

I've also renamed the depth formulas based on @WestLangley's feedback.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by WestLangley** [comment]
Many thanks @bhouston for implementing these suggestions!

The discussion you referred to was actually in #8573.

Just a few more suggestions regarding nomenclature...

    vec3 packNormalToRGB()
    vec3 unpackRGBToNormal()
    vec4 packLinearUnitToRGBA() -> packDepthToRGBA()  ( or packFloatToRGBA() )
    float unpackRGBAToLinearUnit() -> unpackRGBAToDepth()  ( or unpackRGBAToFloat() )
    float viewZToOrthoDepth()
    float OrthoDepthToViewZ()
    float viewZToPerspectiveDepth()
    float perspectiveDepthToViewZ()

Also,

```javascript
THREE.LinearDepthPacking = 3200; -> THREE.GrayscaleDepthPacking
THREE.RGBADepthPacking = 3201;
```

To me, there is nothing linear about it, but I don't know of another term that seems better. I guess it depends on the enhancements you envision.

```javascript
THREE.NoDepthPacking = 3200; ???
THREE.StandardDepthPacking = 3200; ???
```

**Comment by mrdoob** [comment]
`THREE.BasicDepthPacking`?

**Comment by WestLangley** [comment]
>THREE.BasicDepthPacking = 3200; ???

That could work. Here is the relevant code.

	#if DEPTH_PACKING == 3200

		gl_FragColor = vec4( vec3( gl_FragCoord.z ), opacity );

	#elif DEPTH_PACKING == 3201

		gl_FragColor = packLinearUnitToRGBA( gl_FragCoord.z );

	#endif

**Pull request merged**
