### PR TITLE
Examples: convert Utils files to esmodules

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: #22267

**Description**
I converted all `*Utils` files in the examples to esmodules to allow for tree-shaking. They now need to be imported like this:

```js
import * as NURBSUtils from '../curves/NURBSUtils.js';
```

The files I touched are `NURBSUtils`, `CameraUtils`, `SceneUtils`, `GeometryCompressionUtils`, `GeometryUtils`, `SkeletonUtils`.

I had to move `PackedPhongMaterial` out of `GeometryCompressionUtils` as well.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by MickeyMiao7** [comment]
> Related issue: #22267
> 
> **Description** I converted all `*Utils` files in the examples to esmodules to allow for tree-shaking. They now need to be imported like this:
> 
> ```js
> import * as NURBSUtils from '../curves/NURBSUtils.js';
> ```
> 
> The files I touched are `NURBSUtils`, `CameraUtils`, `SceneUtils`, `GeometryCompressionUtils`, `GeometryUtils`, `SkeletonUtils`.
> 
> I had to move `PackedPhongMaterial` out of `GeometryCompressionUtils` as well.

Hi @marcofugaro, would you like to share any idea why this way can help with tree shaking? I am not sure about the difference under the hood and i am curious about it.

```
import * as NURBSUtils from '../curves/NURBSUtils.js';
```

**Comment by marcofugaro** [comment]
@MickeyMiao7 basically, class methods are not tree-shakeable by bunders, while es-style exports are. There was no point in putting just functions under a class without using any of the class local state, so they've been converted to plain functions.

You can see an example of it in this short guide: https://esbuild.github.io/api/#tree-shaking

**Comment by MickeyMiao7** [comment]
> @MickeyMiao7 basically, class methods are not tree-shakeable by bunders, while es-style exports are. There was no point in putting just functions under a class without using any of the class local state, so they've been converted to plain functions.
> 
> You can see an example of it in this short guide: https://esbuild.github.io/api/#tree-shaking

@marcofugaro Thanks you so much!

**Pull request merged**
