### PR TITLE
Dynamic buffer attribute

### PR DESCRIPTION
**Pull request by benaadams**
Changes suggested for #5964 resolves #5042 and supersedes #5952, #5953
and #5964

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice one! Any plans on doing an example for this?

**Comment by benaadams** [comment]
Yes, just trying to work out how my long promised layout/interleaved buffers would fit so I can get a PR in before the library changes again ;-)

Would a dynamic or updatable flag be ok there, rather than have two types with unwieldy names?

I'm thinking something along the lines of InterleavedBuffer and InterleavedBufferAttribute; the InterleavedBufferAttribute would require a parent InterleavedBuffer which it is a view on. Constructor suggestions also welcome!

**Comment by mrdoob** [comment]
Do you mean InterleavedBufferGeometry?

**Comment by benaadams** [comment]
Yes sort of, but really it works with the new attribute stuff and regular geometry well; so you can mix interleaved and non interleaved in the new way

**Comment by benaadams** [comment]
An example might be say you had a particle system with a big buffer of stuff for all the particles; uvs might always be constant; but you want to update the particles as you add a new one. The update ranges handle updating parts, but if you are always updating the same items together rather than having multiple buffers they can be altogether in one, which also provides better locality for some gpus. Its almost like an attribute grouping that shares the same underlying array

perhaps e.g .

```javascript
geometry.addAttribute('index', new THREE.BufferAttribute(indexes, 1));
// THREE.InterleavedBuffer(array, itemSize);
// var interleavedBuffer = new THREE.InterleavedBuffer(data, 16); 
var interleavedBuffer = new THREE.DynamicInterleavedBuffer(data, 16); 
// THREE.InterleavedBufferAttribute(parentBuffer, offset, subItemSize);
var positionBuffer = new THREE.InterleavedBufferAttribute(interleavedBuffer, 0, 4);
var coeffBuffer = new THREE.InterleavedBufferAttribute(interleavedBuffer, 4, 4);
var timingBuffer = new THREE.InterleavedBufferAttribute(interleavedBuffer, 8, 4);
var easingBuffer = new THREE.InterleavedBufferAttribute(interleavedBuffer, 12, 4);
geometry.addAttribute( 'position', positionBuffer );
geometry.addAttribute( 'coeff', coeffBuffer );
geometry.addAttribute( 'timing', timingBuffer );
geometry.addAttribute( 'easing', easingBuffer );
var uvBuffer = new THREE.BufferAttribute(uvs, 2);
geometry.addAttribute('uv', uvBuffer);
```

**Pull request merged**
