### PR TITLE
Ray: Convert to es6 class

### PR DESCRIPTION
**Pull request by ianpurvis**
#11552

### CODE REVIEW

**Comment by Mugen87** [comment]
Please do not make a PR per class^^. Consider to bundle your changes into a single one.

**Comment by ianpurvis** [comment]
@Mugen87 Sorry about that- I want to make it easy to review, do you prefer like a monolithic PR with many reviewable commits?

**Comment by Mugen87** [comment]
Ideally you make a single commit/PR per directory.

**Comment by Mugen87** [comment]
If we make a PR per class the upcoming release notes will look like a nightmare^^

**Comment by ianpurvis** [comment]
Lol, my bad!!!

**Comment by Mugen87** [comment]
I wonder if there is a tool that can convert the files for us. It was not possible to do this earlier because of the IIFE. But these are gone since a while now.

**Comment by Mugen87** [comment]
For more context: #14654

**Comment by ianpurvis** [comment]
I think that could be possible, the replacement pattern is so repetitive... I'll check it out.

Btw, do you want the existing PRs closed and combined into something new? Or just move forward?

**Comment by DefinitelyMaybe** [comment]
noted.

**Comment by Mugen87** [comment]
> Btw, do you want the existing PRs closed and combined into something new? Or just move forward?

The existing PRs can be merged of course. But it would be great if you or @DefinitelyMaybe could check out the repo of @Rich-Harris. As you say since the pattern is repetitive, it would be nice to automate this process.

**Comment by DefinitelyMaybe** [comment]
if all of the IFEEs are gone then maybe. I remember that being a pain when I was trying to regex the entire library

**Comment by Mugen87** [comment]
Possibly interesting: https://github.com/lebab/lebab

**Comment by Mugen87** [comment]
Um, it turns:
```js
function CircleGeometry( radius, segments, thetaStart, thetaLength ) {

	Geometry.call( this );

	this.type = 'CircleGeometry';

	this.parameters = {
		radius: radius,
		segments: segments,
		thetaStart: thetaStart,
		thetaLength: thetaLength
	};

	this.fromBufferGeometry( new CircleBufferGeometry( radius, segments, thetaStart, thetaLength ) );
	this.mergeVertices();

}

CircleGeometry.prototype = Object.create( Geometry.prototype );
CircleGeometry.prototype.constructor = CircleGeometry;
```
into
```js
class CircleGeometry extends Geometry {
    constructor(radius, segments, thetaStart, thetaLength) {

        super();

        this.type = 'CircleGeometry';

        this.parameters = {
            radius,
            segments,
            thetaStart,
            thetaLength
        };

        this.fromBufferGeometry( new CircleBufferGeometry( radius, segments, thetaStart, thetaLength ) );
        this.mergeVertices();

    }
}
```

**Comment by Mugen87** [comment]
Another example:
```js
function LineBasicMaterial( parameters ) {

	Material.call( this );

	this.type = 'LineBasicMaterial';

	this.color = new Color( 0xffffff );

	this.linewidth = 1;
	this.linecap = 'round';
	this.linejoin = 'round';

	this.morphTargets = false;

	this.setValues( parameters );

}

LineBasicMaterial.prototype = Object.create( Material.prototype );
LineBasicMaterial.prototype.constructor = LineBasicMaterial;

LineBasicMaterial.prototype.isLineBasicMaterial = true;

LineBasicMaterial.prototype.copy = function ( source ) {

	Material.prototype.copy.call( this, source );

	this.color.copy( source.color );

	this.linewidth = source.linewidth;
	this.linecap = source.linecap;
	this.linejoin = source.linejoin;

	this.morphTargets = source.morphTargets;

	return this;

};
```
to
```js
class LineBasicMaterial extends Material {
    constructor(parameters) {

        super();

        this.type = 'LineBasicMaterial';

        this.color = new Color( 0xffffff );

        this.linewidth = 1;
        this.linecap = 'round';
        this.linejoin = 'round';

        this.morphTargets = false;

        this.setValues( parameters );

    }

    copy(source) {

        super.copy(source);

        this.color.copy( source.color );

        this.linewidth = source.linewidth;
        this.linecap = source.linecap;
        this.linejoin = source.linejoin;

        this.morphTargets = source.morphTargets;

        return this;

    }
}

LineBasicMaterial.prototype.isLineBasicMaterial = true;
```

**Comment by ianpurvis** [comment]
Looks great!

**Comment by Mugen87** [comment]
You can try it out yourself with: https://lebab.unibtc.me/editor/

**Comment by Mugen87** [comment]
It seems it can't process this style:
```js
function Bone() {

	Object3D.call( this );

	this.type = 'Bone';

}

Bone.prototype = Object.assign( Object.create( Object3D.prototype ), {

	constructor: Bone,

	isBone: true

} );
```
But maybe one could ask at the repository of `lebab` what to do in this case.

**Comment by ianpurvis** [comment]
@Mugen87 Thanks for the info. Do you guys foresee issues with classes extending a VIP like `Object3D`? (for better or worse I asked on the original issue thread https://github.com/mrdoob/three.js/issues/11552#issuecomment-667353533)

**Comment by Mugen87** [comment]
It's not possible to convert classes like `Object3D` since files in `examples/js` are derived from it. This is also true for `Geometry`, `BufferGeometry`, `Loader` and others.

`examples/js` is removed at the end of 2020. An only after that a complete migration to classes is possible.

**Comment by mrdoob** [comment]
> Please do not make a PR per class^^. Consider to bundle your changes into a single one.

Actually, a PR per class id easier to review that bundling all the changes in one. So I favour PR per class.

> If we make a PR per class the upcoming release notes will look like a nightmare^^.

Yes it will... But it will only be a nightmare once 😇

**Comment by mrdoob** [comment]
A PR per folder is also okay, depending on the complexity.... For example, `renderers` folder should definitely be per class. `geometries` folder could be per folder.

It's a case of one size don't fit all, so lets be flexible. Probably better to ask first before doing the PR?

**Comment by mrdoob** [comment]
I also wouldn't go the automation path, specially if it's a blocker because it doesn't support some of out patterns.

I know is repetitive, but we only have to do this once.

**Comment by mrdoob** [comment]
Thanks!

**Comment by DefinitelyMaybe** [comment]
> Yes it will... But it will only be a nightmare once 😇

tehe! to be fair it is likely to end other nightmares 👻

> It's a case of one size don't fit all, so lets be flexible. Probably better to ask first before doing the PR?

roger. a little co-ordination perhaps.

**Comment by mrdoob** [comment]
@Mugen87 would doing the change log like this help?

```md
* Source

* Global
 * Adopted ES6 Classes. #19976 #19977 #19978 #19979 #19980 (@DefinitelyMaybe , @linbingquan, @Mugen87)
```

**Comment by Mugen87** [comment]
Definitely. But frankly I would have done it like that anyway^^. It's the same approach we have used for the module migration last year. I just remember that it took a lot of time to process all exiting PRs.

**Comment by ianpurvis** [comment]
> A PR per folder is also okay, depending on the complexity. For example, `renderers` folder should definitely be per class. `geometries` folder could be per folder.

This sounds good to me. One of the reasons that I went the per-file route and jumped around in the tree was that I kept getting blocked by  https://github.com/mrdoob/three.js/issues/11552#issuecomment-667353533. Once we can resolve that issue, it will be a lot easier to PR a whole folder.

> roger. a little co-ordination perhaps.

@DefinitelyMaybe Your dibs system is a great idea. I'll keep pushing it forward with you in #11552 👍 

Thanks everybody- sorry to rock the boat

**Pull request merged**
