### PR TITLE
OrbitControls: Split update for correct Auto Rotate speed

### PR DESCRIPTION
**Pull request by neofuji**
Related issue: None

**Description**

Auto Rotate works on `update()` invoked in the animation loop.
The `pointermove` handlers also invoke `update()` and unexpectedly accelerate Auto Rotate. 

This PR extracts `updateInternal()` not including Auto Rotate for correct speed.

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind renaming `updateInternal` to `_update`?

**Comment by neofuji** [comment]
I renamed to `_update`.

**Review by Mugen87 — DISMISSED** [review]

**Comment by Mugen87** [comment]
@mrdoob This one is ready to merge.

**Comment by Mugen87** [comment]
> The pointermove handlers also invoke update() and unexpectedly accelerate Auto Rotate.

I have revisited this issue and I don't think this statement is `true`. The auto rotate update is only performed when the state of the controls is `NONE`. However, the handler of `pointermove` only calls `update()` when the state is _not_ `NONE`. Meaning the mentioned acceleration can't happen when the pointer is moved.

**Pull request closed without merging**
