### PR TITLE
Examples: Improve basic geometry demos

### PR DESCRIPTION
**Pull request by Mugen87**
This PR implements some feedback of @WestLangley, see https://github.com/mrdoob/three.js/pull/12393#issuecomment-336100129

### CODE REVIEW

**Comment by Mugen87** [comment]
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_geometries.html
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_geometries_parametric.html

**Comment by Mugen87** [comment]
Indeed, the examples are much nicer now! 😊

**Comment by mrdoob** [comment]
Nice nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
The new light now shows that some geometries have (I guess) normal issues.

screen shot 2017-10-14 at 08 05 19

**Comment by Mugen87** [comment]
Gah! These are`TubeGeometry` and `TorusKnotGeometry` of `ParametricGeometries`.

**Comment by Mugen87** [comment]
For debugging: https://jsfiddle.net/f2Lommf5/138/

**Comment by Mugen87** [comment]
Um, the wireframe shows that some vertex normals seems to be inverted...

**Comment by Mugen87** [comment]
After some research i'm pretty sure that the issue was introduced with this change: #11056

If i use an older `three.js` version (`R84`) the normals look better (not really optimal because of the seams, but better than now). So it looks like that the mentioned parametric geometries from `examples/js/ParametricGeometries.js` are not compatible with the analytical normal calculation of `ParametricBufferGeometry`. Unfortunately, i have no clue right now what exactly goes wrong...

Demo with `R84`: https://jsfiddle.net/f2Lommf5/141/

**Pull request merged**
