### PR TITLE
PCDLoader: Fix data parsing for Edge.

### LINKED ISSUE #16358: PCD loader does not work in Microsoft Edge
PCD loader does not work in Microsoft Edge.
Works in Chrome.
image

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #16358

`PCDLoader` is passing right now an instance of `ArrayBuffer` to `LoaderUtils.decodeText()`. If `TextDecoder` is not supported (like in Edge), the fallback is only able to handle typed arrays.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev29/examples/webgl_loader_pcd.html

**Comment by mrdoob** [comment]
Is there a performance penalty in other browsers?

**Comment by Mugen87** [comment]
I can't see any noticeable difference with Chrome Performance analysis tool. The creation of an `Uint8Array` with a given buffer should be fast since it's just a view on the underlying binary data.

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
It looks like the performance penalty here would be just in Edge/IE11, right? That seems OK, and could be avoided with a TextDecoder polyfill.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
