### PR TITLE
Remove optionalTarget - part 1

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in #12231.

Implemented just a few classes at first to see if this is going to be acceptable...

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
If there is no interest in this, I will close it...

**Comment by Mugen87** [comment]
I think we should go through this change.

**Comment by mrdoob** [comment]
Ops! Sorry, I started losing track of issues at the end of last year. That's why I started using milestones. If there are pending issues that haven't been added to a milestone, please do me a /ping on it 😅

**Comment by mrdoob** [comment]
@WestLangley Any chance you can merge `dev` into this branch and resolve the conflicts? 😇

**Comment by WestLangley** [comment]
Done! Well that was a bit tedious... Hopefully no mistakes...

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
