### PR TITLE
ImageBitmapLoader: Cache promises to deduplicate requests.

### PR DESCRIPTION
**Pull request by Archimagus**
Related issue: #XXXX

**Description**

Currently I am loading several GLTF files that reference the same texture.  Since those calls all come in before the textures have downloaded the cache is failing.
This PR adds the promise to the cache so subsequent calls can see that the fetch is in progress and it will wait for them rather than downloading again.

### CODE REVIEW

**Comment by Mugen87** [comment]
Something is wrong with the PR since the diff is the same as #27106.

**Comment by Archimagus** [comment]
> Something is wrong with the PR since the diff is the same as #27106.

Thanks,  something got out of sync.  Fixed now.

**Comment by Mugen87** [comment]
@sxxov That is a good question. The solution of this PR tries to achieve the same (monitoring pending requests) like what is already implemented in `FileLoader` with the `loading` object/dictionary.

I tend to prefer the promise based solution though. The approach in `FileLoader` comes from a time before `fetch()` was introduced (#12434). Maybe we can use the same approach from this PR in `FileLoader` as well?

**Comment by sxxov** [comment]
> @sxxov That is a good question. The solution of this PR tries to achieve the same (monitoring pending requests) like what is already implemented in `FileLoader` with the `loading` object/dictionary.
> 
> I tend to prefer the promise based solution though. The approach in `FileLoader` comes from a time before `fetch()` was introduced (#12434). Maybe we can use the same approach from this PR in `FileLoader` as well?

Why not migrate this loader to use `FileLoader` internally, then migrate `FileLoader`? Whilst this means having adjacent cached keys for caching `createImageBitmap`, it's something that might be useful when considered, given #27301.

There seems to some workarounds in `FileLoader` that is absent here too!

**Comment by Mugen87** [comment]
Now that `FileLoader` uses `fetch` it sounds right to investigate this option. 

However, it does not prevent to merge this PR and apply a refactoring in `FileLoader` to cache promises first. The merge can be done in a later point as well since it requires good testing.

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
