### PR TITLE
fix vrml test scene house.wrl

### PR DESCRIPTION
**Pull request by andreasplesch**
addresses #10502 .

rendering of house.wrl in cobweb:
image

### CODE REVIEW

**Comment by mrdoob** [comment]
@bartmcleod Looks good?

**Comment by bartmcleod** [comment]
@mrdoob Judging by the comments I would say sensible changes. Remember that you have an open PR by me that also corrects some of these issues (except moving the routes to the end).

If the example page loads it, I would say merge.

**Comment by andreasplesch** [comment]
https://rawgit.com/andreasplesch/three.js/wrl/examples/webgl_loader_vrml.html uses the fixed vrml file and displays it properly albeit not from the initially bound viewpoint (see above). The loader does not seem to take viewpoints into account to setup camera positions.

The current vrml should cause the loader to emit warnings/errors .

**Comment by bartmcleod** [comment]
The new loader in my other PR support viewpoints, this one is old. It does not. @andreasplesch if want the latest and greatest loader, check out the VrmlParser project. It is a derivate of this example and use  s THREE for rendering: https://github.com/bartmcleod/VrmlParser

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> @mrdoob Judging by the comments I would say sensible changes. Remember that you have an open PR by me that also corrects some of these issues (except moving the routes to the end).

Oh... Do you have the Issue id at hand?

**Comment by bartmcleod** [comment]
https://github.com/mrdoob/three.js/pull/10371

**Comment by mrdoob** [comment]
> #10371 It will likely conflict now with the new vrml file..

I see, yeah... That PR still needs to be amended before it can be merged.

`VRMLLoader` should behave like the other loaders. Maybe you want to do something like a `VRMLViewer` on top which adds all the interactivity features you want.

**Comment by bartmcleod** [comment]
Ok, I thought I had accomplished that, in what sense does it currently not behave like the other loaders? How can I verify that myself?

**Comment by mrdoob** [comment]
@bartmcleod 

Loaders just load and parse a file and return scene/geometry/data. VRML does have additional features that you want to handle automatically, I'm all for that but I don't think the Loader should do that (Just like `ColladaLoader` doesn't play animations or set the camera).

That's why I'm proposing something like a `VRMLViewer` which could use `VRMLLoader` internally and then add the interactions you want to support.

Makes sense?

**Comment by bartmcleod** [comment]
Yes, will look into that.

**Comment by andreasplesch** [comment]
@bartmcleod , do you want me to PR the fixed house.wrl against the dev branch in your fork ?

Chisel reports 45 errors for the current house.wrl in your dev branch, most about the ROUTEs in places where they are not allowed (and a node would be expected). The next, distinct error is the same as described above (line 1898) where the 'children' field was left out for the enclosing Transform (apparently included from a former inline ../boven/deurklink.wrl) .

**Comment by bartmcleod** [comment]
@andreasplesch Yes please!

**Comment by andreasplesch** [comment]
ok. The PR should have the minimal amount of necessary updates now (just house.wrl).

**Comment by bartmcleod** [comment]
I do not see the PR yet...

**Comment by andreasplesch** [comment]
https://github.com/bartmcleod/three.js/pull/1

**Pull request merged**
