### PR TITLE
Add support for Object position/quaternion/scale animations in ObjectLoader

### PR DESCRIPTION
**Pull request by bhouston**
One missing feature in the ObjectLoader is animations on an object hierarchy, such as a few objects that need to move in a coordinated fashion, or a camera for instance.  This PR builds upon the Mixer-based animation system (https://github.com/mrdoob/three.js/pull/6934) by adding optional tracks on each object in the scene hierarchy.

We have extended the ObjectLoader format to have a set of named tracks per object in this fashion:

```
   "object": {
        "type": "Scene",
        "children": [{
            "type": "Mesh",
            "name": "box",
            "uuid": "DFE4F84A-03CD-3DDE-9111-B1A47BF8648B",
            "matrix": [-1,0,-0,0,-0,0,1,0,0,1,0,0,0,0,0,1],
            "visible": true,
            "material": "DB260918-E28B-3309-9548-9FA55D210A2E",
            "castShadow": true,
            "receiveShadow": true,
            "geometry": "1F5FD627-B58A-39B7-8080-B97676C3A916",
            "clips": [{
                "fps": 29,
                "name": "box",
                "tracks": {
                    "position": [{
                        "value": [0,0,0],
                        "time": 0
                    },{
                        "value": [0,-2,0],
                        "time": 33.3333
                    },{
                        "value": [0,-4,0],
                        "time": 66.6667
                    },{
                        "value": [0,-6,0],
                        "time": 100
...
```

The end result is that a `ObjectLoader.parse()` call returning an object now has an optional `object.animationClip` property that will contain the all the keyframe tracks on all the nodes.

### CODE REVIEW

**Comment by mrdoob** [comment]
This is looking great Ben! I'll probably try to release `r72` before merging it, but don't let that stop you! 😊

**Comment by bhouston** [comment]
Okay we've also updated the Blender exporter to export both blend shape animations and node (TRS) animations into the clip objects in the JSON ThreeJS format.

The exporter format is backwards compatible with all existing loaders. :)

**Comment by bhouston** [comment]
The following examples all use Mixer now (and I have replaced usages of MorphAnimMesh any time I saw it.)  They also rely on automatic clip parsing by JSONLoader and ObjectLoader:

http://exocortex.github.io/three.js/examples/webgl_animation_scene.html
http://exocortex.github.io/three.js/examples/webgl_animation_skinning_morph.html
http://exocortex.github.io/three.js/examples/webgl_animation_skinning_blending.html
http://exocortex.github.io/three.js/examples/webgl_lights_hemisphere.html
http://exocortex.github.io/three.js/examples/webgl_loader_json_blender.html
http://exocortex.github.io/three.js/examples/webgl_loader_scene.html
http://exocortex.github.io/three.js/examples/webgl_morphnormals.html
http://exocortex.github.io/three.js/examples/webgl_morphtargets_horse.html
http://exocortex.github.io/three.js/examples/webgl_morphtargets_human.html
http://exocortex.github.io/three.js/examples/webgl_shading_physical.html
http://exocortex.github.io/three.js/examples/webgl_shadowmap.html
http://exocortex.github.io/three.js/examples/webgl_shadowmap_performance.html
http://exocortex.github.io/three.js/examples/webgl_skinning_simple.html
http://exocortex.github.io/three.js/examples/webgl_terrain_dynamic.html

**Comment by bhouston** [comment]
Combining this PR with the other animation PR.

**Pull request closed without merging**
