### PR TITLE
Docs: Use `<math>` for equations in webgl_multiple_elements_text.html

### PR DESCRIPTION
**Pull request by ycw**
Related issue: #26812

preview: https://raw.githack.com/ycw/three.js/wgl_mult_els_text/examples/index.html?#webgl_multiple_elements_text

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
Currently, with this PR

Screenshot 2023-10-03 at 3 14 03 PM

**Comment by WestLangley** [comment]
Hmm... Your edit to `main.css` fixed the issue for me in Chrome and Firefox, but not in Safari. MacOS Sonoma 14.0.

**Comment by WestLangley** [comment]
But what you are doing now is a hack, no?

Granted, it is not a central issue, so I am not going to press it... but the fractions are still too close together in Safari, IMHO.

**Comment by ycw** [comment]
The [spec requires UA to do this](https://w3c.github.io/mathml-core/#fractions-mfrac):

> ... To avoid visual confusion between the fraction bar and another adjacent items (e.g. minus sign or another fraction's bar), a default 1-pixel space is added around the element. The [user agent stylesheet](https://w3c.github.io/mathml-core/#dfn-user-agent-stylesheet) must contain the following rules: ...

but safari misbehaved, so a patch is needed

https://github.com/mrdoob/three.js/pull/26896/commits/8a78521e126229845264b8f629813463a27bb5e2: `mspace` is semantically correct, and supported since safari7, but this option will cause visually diff btwn safari and non-safari (space is much wider in non-safari)

Lets try another option

[sha]: adds a dot operator between `mfrac`s. The dot in safari should behave like the minus in https://github.com/mrdoob/three.js/pull/26896#issuecomment-1745573220 which has proper space added around; U+22C5 is semantically correct, but the equations now looks more 'verbose' (a dot is added between the const and derivatives)

**Comment by WestLangley** [comment]
I think adding the `dot` is a good solution.

**Review by Mugen87 — APPROVED** [review]

**Pull request merged**
