### PR TITLE
FBXLoader: support for colors specified as single floats. 

### PR DESCRIPTION
**Pull request by looeee**
Fix for https://github.com/mrdoob/three.js/issues/12067#issuecomment-344218558

Extends the `parseColor` function to support color type `Color` (rather than `ColorRGB`), where the value is a single float rather than an RGB triple. 

Also fix an error when parsing light color.

### CODE REVIEW

**Comment by looeee** [comment]
@MarcRibguth

**Comment by MarcRibguth** [comment]
@looeee thanks for the reply, I will do that.

**Comment by mrdoob** [comment]
How about...

```js
function parseColor( property ) {

    var color = new THREE.Color();

    if ( property.type === 'Color' ) {

        return color.setScalar( property.value );

    } else {

        return color.fromArray( property.value );

    }

}
```

**Comment by looeee** [comment]
@mrdoob done. 

BTW, which style do you prefer in the library?

**1**
```js
function parseColor( property ) {

    var color = new THREE.Color();

    if ( property.type === 'Color' ) {

        return color.setScalar( property.value );

    } else {

        return color.fromArray( property.value );

    }

}
```

**2**

```js
function parseColor( property ) {

    var color = new THREE.Color();

    if ( property.type === 'Color' ) {

        return color.setScalar( property.value );

   }

    return color.fromArray( property.value );

}
```

**Comment by mrdoob** [comment]
Hmm, actually, yeah... In this case 2. is prettier 😇

**Comment by looeee** [comment]
OK, updated 🙂

**Comment by mrdoob** [comment]
Another option would be:

```js
function parseColor( property ) {

    var color = new THREE.Color();

    switch ( property.type ) {
        case 'ColorRGB':
            return color.fromArray( property.value );
        case 'Color':
            return color.setScalar( property.value );
    }

}
```

But it depends of how many other types there are.

**Comment by mrdoob** [comment]
Merging for now.

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
As far as I'm aware it should just be either 'Color' (float) or 'ColorRGB' (array). 

In any case, if there are more types used (e.g. 'Number', 'Double', 'Vector3' etc ) then they will all map to either an array or float, so I would favour

```js
function parseColor( property ) {

    var color = new THREE.Color();

    if( Array.isArray( propery.value ) { 

        return color.fromArray( property.value );

    }

    return color.setScalar( property.value );

}
```

However I think the current function is sufficient.

**Pull request merged**
