### PR TITLE
[WIP] RectAreaLight in Editor & Json support

### PR DESCRIPTION
**Pull request by thmasn**
working:
-adding a rectAreaLight with visible RectAreaLightHelper
-changing color, intensity
-changing width & height

not working / to do:
-actual light / affect materials
-changing position / rotation
-loading from json
-saving height & width to json

### CODE REVIEW

**Comment by thmasn** [comment]
edit: moving the light works & it affects the scene, but the helper doesnt move with it

**Comment by thmasn** [comment]
this branch has currently 2 issues:

- [ ] the rectAreaLighHelper somehow does react different than other light helpers & therefore does not follow the light transform

- [ ] somehow after starting & stopping the game, the lights are "stuck" to the editor camera (rotate & move with it), without any error in the console

**Comment by thmasn** [comment]
bump: current state:
using pointlightHelper instead of arealighthelper because arealighthelper works differently than the editor expects
saving to & loading from json works
width & height added to object menu
[https://youtu.be/sn0g6dhsTLk](https://youtu.be/sn0g6dhsTLk)
currently having a weird bug where the arealights are 'stuck' to the camera after hitting play, then stop.

**Comment by Mugen87** [comment]
Closing in favor of #16251. In any event, thanks for the effort!

**Pull request closed without merging**
