### PR TITLE
Add submitVrFrame parameter to WebGLRenderer.render method

### PR DESCRIPTION
**Pull request by charlesfleche**
Currently when VR is enabled, `WebGLRenderer.render` calls `VRDisplay.submitFrame` as soon as a render is done. This prevent additional renders to occur, for example to display a scene independent UI overlay.

This PR adds the `submitVrFrame` parameter to `WebGLRenderer.render`: when set to `false` (`true` is default) `VRDisplay.submitFrame` won't be called.

### CODE REVIEW

**Comment by wizgrav** [comment]
Dev now supports Scene.onAfterRender((renderer, scene, camera) => void) to set a callback to run after the scene is rendered, but before the frame is submitted, so operations like post proc, overlays etc can be performed there

**Comment by charlesfleche** [comment]
The problem with the `Scene.onAfterRender` approach it that it couples a scene with a general render: it is absolutely OK to have Scene specific post-render code in `Scene.onAfterRender`. However, if this use case (drawing an UI overlay for VR), the overlay is another `Scene`, with another `Camera`: both scene do not know anything about each other, they just share a canvas. Using `Scene.onAfterRender` to trigger another render for another `Scene` before a `submitFrame` call sounds odd: having a direct control on the `submitFrame` sounds less hackish to me.

**Comment by wizgrav** [comment]
Originally I had left the autoSubmitFrame flag in but @mrdoob thought that the callback approach was more consistent with the mechanisms provided elsewhere. Mind that submitting the frame is not the only thing you'd need to work on the vr frame, you also need the stereo cameras for a lot of cases and these are not exposed by the renderer. The camera gets replaced internally when vr is on. The correct Camera/ArrayCamera is always provided as an argument of onAfterRender().

For you particular use case I don't think the two scenes(main render/ overlay) need to know anything about each other. Inside onAfterRender you can reuse the renderer with a different scene. In fact you have to, else you'd need to take care you don't end up in an infinite loop calling onAfterRender()

**Comment by charlesfleche** [comment]
Well, it means that I need to register a callback from one scene that will render another scene. In that sense those two scenes are coupled, or am I missing something here ?

I understand the argument about submitting not being the only required operation, and that it why for post-render code tied to a scene the `Scene.onAfterRender` callback makes a lof ot sense. However I don't see the point in this use case: I'm not even using the same camera for the UI overlay (to work around a RayInput bug: https://github.com/borismus/ray-input/issues/33 ), so the callback will return me a scene I won't use and a camera I won't need either (so the VR cameras will have to be recomputed anyway as part of the `WebGLRenderer.render` call). Only the renderer is of interest here, so I don't see the point of registering a callback for a sync operation that could be called as another `render` call.

I though a linear approach (clear color buffer, render scene, render UI, submit) would make sense here, similar to what is done in non-WebVR rendering. And it does make a lot of sense to have `submitFrame` called by default after a `render`, hence the proposal of putting the `submitFlag` back as a parameter.

**Comment by Mugen87** [comment]
Closing in favor of #14114.

**Pull request closed without merging**
