### PR TITLE
Add alphas channel for instanced meshes. Update example.

### PR DESCRIPTION
**Pull request by Displee**
Related issue: https://discourse.threejs.org/t/add-opacity-to-vertice-colors-and-instanced-geometry/26298

Will give you the ability to set the opacity for colors in instanced meshes.

### CODE REVIEW

**Comment by WestLangley** [comment]
Transparency does not work well with instancing because the instances are not depth-sorted.

Here is the same scene rendered from different view directions:

Screenshot 2022-12-31 at 6 12 57 PM

Screenshot 2022-12-31 at 6 12 14 PM

**Comment by Displee** [comment]
I guess we need a separate example (or none at all) in that case.

**Comment by Mugen87** [comment]
We should not add features to the library that do not properly work. I vote to not support this feature for now.

**Comment by AnweshGangula** [comment]
check this out for additional discussion in three.js forum: 
https://discourse.threejs.org/t/threejs-and-the-transparent-problem/11553/50

**Pull request closed without merging**
