### PR TITLE
GLTFLoader: Remove support for MSFT_texture_dds.

### PR DESCRIPTION
**Pull request by donmccurdy**
As mentioned in https://github.com/mrdoob/three.js/pull/13820#issuecomment-380923528 when we added this extension, we do not want to generally provide support for vendor extensions, like a `MSFT_*` extension in this case. Multi-vendor extensions (`EXT_*`) may be considered on a case-by-case basis. We made an exception here because it couldn't be implemented otherwise, and there was no alternative for compressed textures at the time. I'm not sure either of those is true anymore — GLTFLoader has a better plugin system to support customization outside of three.js, and an official `KHR_texture_basisu` extension is available now. So, I would suggest that we remove support for `MSFT_texture_dds`.

/cc @Bergmam @takahirox

### CODE REVIEW

**Comment by mrdoob** [comment]
Sounds good to me 👍

**Comment by takahirox** [comment]
I think it's good because as Don mentioned basisu texture would be main stream as compressed texture for glTF. And I started this project https://github.com/takahirox/three-gltf-plugins which provides Three.js glTF loader/exporter plugins for the extensions official Three.js doesn't support. (Anyone, PR for dds texture is welcome there.)

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
Added `GLTFLoader` `MSFT_texture_dds` plugin to my repository.

https://github.com/takahirox/three-gltf-plugins/tree/main/loaders/MSFT_texture_dds

**Pull request merged**
