### PR TITLE
BasisTextureLoader: Update Basis library.

### LINKED ISSUE #19797: BasisTextureLoader example: the texture is rendered upside down
... So the issue is: how to apply a `.basis` texture to a three.js built-in geometry.

/ping @zeux
/ping @takahirox 
/ping @donmccurdy 

- [ x ] r118

### PR DESCRIPTION
**Pull request by donmccurdy**
Updates to the newest version of the Basis library, which includes APIs we'll need to use for THREE.KTX2Loader later.

Also fixes #19797 by flipping the UVs on the example, although this is unrelated to the library update.

### CODE REVIEW

**Comment by WestLangley** [comment]
I think it would be best to use a texture that has an obvious right-side-up.

... And texture a simple plane geometry, as in https://threejs.org/examples/webgl_loader_texture_exr.html.

**Comment by donmccurdy** [comment]
Sounds good, updated:

Screen Shot 2021-01-15 at 9 00 46 PM

**Comment by WestLangley** [comment]
There is no need for a spinning plane; it obfuscates bugs.

That is why the flipY problem was not noticed in the first place.

Also, what is the aspect ratio of the new basis texture? You are texturing a square plane.

**Comment by donmccurdy** [comment]
What you would prefer that this example contain?

**Comment by WestLangley** [comment]
>What you would prefer that this example contain?

IMHO, a static image with the correct aspect ratio.

**Comment by donmccurdy** [comment]
I've fixed the aspect ratio — it was off by 2% so I'm surprised you were seeing a difference? I think it is necessary to at least include OrbitControls here. If the image is static, I can't tell whether mipmaps are loaded correctly.

**Comment by mrdoob** [comment]
Indeed. Another benefit of having a rotating object is that we can see if we are missing frames at texture upload.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
>I've fixed the aspect ratio — it was off by 2% so I'm surprised you were seeing a difference?

Oh, I thought the aspect of the basis file was the same as the aspect of `758px-Canestra_di_frutta_(Caravaggio).jpg`.

//

But still, calling the constructor without args raises unnecessary questions for me.
```js
const geometry = flipY( new THREE.PlaneBufferGeometry() );
```
I was expecting you were going to query the texture's aspect (somehow), and set the plane aspect to match.

**Comment by donmccurdy** [comment]
I cropped it to 512x512 for this example to include compressed mipmaps. 👍

**Pull request merged**
