### PR TITLE
WebGLRenderer: Fix update of materialProperties.envMap.

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/pull/20048#issuecomment-674466890

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like this broke `webgl_loader_gltf` 🤔

**Comment by Mugen87** [comment]
Updated. I was not correct to remove the line in `initMaterial()`. Otherwise the first render will have the "wrong" envmap uniform value since `materialProperties.uniformsList` is generated in `initMaterial()`.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Unfortunately, it seems to go one frame behind.

You can test this by using a screen recorder and changing the envMap types in `webgl_materials_envmaps` and then stepping frame by frame on the recorded video.

https://www.youtube.com/watch?v=Tlgw1oRlJRk

**Comment by Mugen87** [comment]
Yeah, the timing when the envmap is set is not yet right.

**Pull request merged**
