### PR TITLE
Prenvent page scroll when zoom with mousewheel

### PR DESCRIPTION
**Pull request by gregui**
for this:
http://stackoverflow.com/questions/25293927/threejs-rendering-scene-in-div-prevent-scrolling-of-browser-window-do-zoom-i

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind targeting the `dev` branch instead?

**Comment by gregui** [comment]
Ops sorry. I changed the code online and forgot to create branch. Would you rather I do commit in dev? or you prefer to do it?

**Comment by mrdoob** [comment]
Yes please, do a new commit in dev.

**Comment by gregui** [comment]
Humm the problem is already fixed in Dev. Sorry and thanks

**Pull request closed without merging**
