### PR TITLE
Mesh custom attribute fix

### PR DESCRIPTION
**Pull request by benaadams**

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmmm... Is this fixable in `WebGLRenderer` & co instead? You know... backward support?

**Comment by benaadams** [comment]
Makes sense... maybe do it in both? Compat and example of using buffers directly.

A weird thing (been there since rev50s) is to use custom attributes with buffer geo you need to set the material attribute to something (and anything https://github.com/mrdoob/three.js/pull/6418/files#diff-b84a096e733389637e4ee9b6fdd3ff1aR108). Just something to be aware of...

**Comment by mrdoob** [comment]
Yeah, I want to find where in the code is that...

**Comment by benaadams** [comment]
> Yeah, I want to find where in the code is that...

Was looking at it when I was doing the program refactoring; its in the post shader compile. 

Basically in the legacy Geometry world the materials have the custom attributes on them; the program also has attributes on them post compile; then the two are matched post compile to determine the actual attributes to bind. The material is used in the shader compile but the geometry doesn't come into play, so the attributes need to be 'marked' on the material to be available to bind.

Alternative would be to ignore the attributes on the material altogether at render time and just use the ones in the geometry and program; assuming the transfer to the buffergeometry is done and the updates are handled? I think its less complicated than it was before.

**Comment by mrdoob** [comment]
> Alternative would be to ignore the attributes on the material altogether at render time and just use the ones in the geometry and program; assuming the transfer to the buffergeometry is done and the updates are handled? I think its less complicated than it was before.

Yep. That's the idea. I wonder if there was a lot of people using attributes with `THREE.Geometry`...

**Comment by benaadams** [comment]
> I wonder if there was a lot of people using attributes with THREE.Geometry

If they are they are closer to using BufferGeometry than they realise as they are mostly the same format; so it shouldn't be too big a shock :innocent:

**Comment by WestLangley** [comment]
> I wonder if there was a lot of people using attributes with THREE.Geometry...

They are used frequently with `PointCloud`. They are also used in `webgl_materials_wireframe.html`.

**Comment by benaadams** [comment]
> They are used frequently with PointCloud. 

It wouldn't work without instancing support, but could drop the PointCloud render path and use the Mesh render path? Would make WebGLRenderer simpler.
http://prealpha.ageofascent.com/examples/webgl_instanced_particles_billboards.html

Would also mean you can use any shape not just squares; so using a square to draw circles is about 1/4 discards in the pixel shader so a lot of overdraw; whereas in the example I'm using circles so there are very few discards.

**Comment by mrdoob** [comment]
This requires instancing support though...
Have you tried with many many particles? Something like [this](http://mrdoob.com/lab/javascript/webgl/particles/magicdust.html)?

**Comment by mrdoob** [comment]
A benefit of not using GL_POINTS​ would be that we would no longer have point size limitations.

**Comment by benaadams** [comment]
I think you've covered this one off?

**Pull request closed without merging**
