### PR TITLE
Docs: Restrict to Y axis to scroll

### PR DESCRIPTION
**Pull request by linbingquan**
|Before | After  |
| -- | -- |
| image|image |

### CODE REVIEW

**Comment by Mugen87** [comment]
What kind of device are you using in order to see the horizontal scroll bar?

**Comment by linbingquan** [comment]
> What kind of device are you using in order to see the horizontal scroll bar? I do not see it with a Pixel (1) and Chrome.

##### Three.js version

- [x] Dev
- [ ] r104

##### Browser

- [x] Chrome 74
- [x] Firefox 66

##### OS

- [x] Windows 10

Screenshot in `Chrome 74` (left) and `Firefox 66` (right)

image

**Comment by Mugen87** [comment]
Okay, I can also see them on my desktop. They are just less obvious on macOS^^.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@yuinchien FYI

**Pull request merged**
