### PR TITLE
Remove parent scale limitation from Object3D.lookAt

### PR DESCRIPTION
**Pull request by ghost**
**Description**

Remove parent scale limitation from `Object3D.lookAt`. By normalizing the premultiplied parent quaternion extracted from the rotation matrix, we ensure that it's independent of scale.

### CODE REVIEW

**Comment by Aidenhjj** [comment]
I followed this guide for building https://github.com/mrdoob/three.js/wiki/Build-instructions, but looks like i'm missing a step as some doc strings are missing in the build.three.js file (eg. 
https://github.com/mrdoob/three.js/pull/22180/commits/a6a2144d1d04e214917dd6a68de90a3bcc176b32#diff-af408426d6a7b072569230b0ee45fa87b6e69f3e97ebdc527d6995924aa1a1ceR5910)

**Comment by WestLangley** [comment]
Thank you for you PR.

We do not include builds in PRs, so you can remove them.

A fiddle demonstrating that the method works would be helpful, however.

**Comment by makc** [comment]
@WestLangley it does not work in any meaningful way https://jsfiddle.net/tkvhasbg/

**Comment by Aidenhjj** [comment]
Sorry for the noise, I thought this was a valid fix from my limited testing.

**Pull request closed without merging**
