### PR TITLE
[WIP] Example for extending materials

### PR DESCRIPTION
**Pull request by pailhead**
I've copied over the instancing lambert example and tried to make it work on various materials. The focus of this example **is not instancing by itself** (its a very simplified example) but for extending materials. 

I was unable to make it work with `MeshToonMaterial` though:

http://dusanbosnjak.com/test/webGL/three-materials-extended/

### CODE REVIEW

**Comment by WestLangley** [comment]
Sweet. Well-done, and informative.

**Comment by pailhead** [comment]
Thank you, ill clean it up a bit. Leave the giant comment? The most important thing i wanted to outline are the "discrete steps" meaning, vertex transformation is a different thing from normal transformations.

**Comment by mrdoob** [comment]
What does this example show that the one introduced in #14012 doesn't? 🤔

**Comment by pailhead** [comment]
How to write arbitrary extensions for arbitrary materials? @WestLangley you're welcome to share what you liked about this ❓

**Comment by WestLangley** [comment]
>@WestLangley you're welcome to share what you liked about this

I considered this to be an informative experiment that is beneficial to the other contributors who are trying to understand the issues involved in extending materials. These kinds of experiments are helpful when making design decisions. They are particularly helpful in identifying design limitations.

I have not considered this WIP as something to be added as an example. We should only include in the examples coding patterns we recommend users to follow. I think we are still trying to figure that out.

**Comment by WestLangley** [comment]
Sorry, @pailhead, I have tried and tried, but I have a very difficult time comprehending your posts. Consequently, I have nothing else to add because I do not understand what you are trying to say.

So sorry...

**Comment by pailhead** [comment]
Lol no worries. In short, do not look at this when developing threejs. Possibly combine with materials modified example (don’t compare to lambert instancing).

**Pull request closed without merging**
