### PR TITLE
Build using npm start, added missing deps

### PR DESCRIPTION
**Pull request by DVLP**
"npm start" as a shortcut to build, added missing deps

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
Wouldn't `npm build` make more sense for building?

**Comment by DVLP** [comment]
Yeah. That was my afterthought too. Will update tomorrow.

**Comment by DVLP** [comment]
"npm start" changed to "npm build" to build Three

**Comment by mrdoob** [comment]
Thanks!

**Comment by DVLP** [comment]
Hooray! My first contribution to Three.js merged :)
Check out the game we're working on: http://bad.city . Up to 4 people can sit inside the brand new helicopter which standing in the centre of the map.

**Comment by MasterJames** [comment]
On android mobile chrome I can't click to put a name so it won't start. Just shows a gray tapping circle or something.

**Comment by DVLP** [comment]
It will not work on mobile for now. It's way too heavy and works good only on desktops/laptops in Chrome.

**Pull request merged**
