### PR TITLE
SVGLoader: Support rounded rect

### PR DESCRIPTION
**Pull request by ndebeiss**
code style approved on http://zz85.github.io/mrdoobapproves/  :relieved:

Can be tested here :
https://rawgit.com/ndebeiss/three.js/dev/examples/svg_load_and_render.html
(orbit control is enabled on the visualization at right)

See #13478

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
In the above text link, if I zoom in, some triangles of the tessellated rounded rect disappear. This occurs on multiple devices and browsers. Perhaps a limitation of SVGRenderer?

**Comment by Mugen87** [comment]
image

becomes to 

image

if you zoom in.

**Comment by mrdoob** [comment]
> Perhaps a limitation of SVGRenderer?

I think so. That test link (not included in this repo) is misleading. He should really use `WebGLRenderer` instead.

**Pull request merged**
