### PR TITLE
WebGPURenderer: Introduce WebGPUUtils.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: https://github.com/mrdoob/three.js/pull/24373#issuecomment-1191119775

**Description**

Moving some methods of `WebGPURenderer` to a new internal module to keep the public interface clean.

### CODE REVIEW

**Comment by sunag** [comment]
@Mugen87 Wouldn't it be better to move the functions of `WebGPUConfig` to `WebGPURenderPipelines`? 
The first impression I have when reading `WebGPUConfig` is something related to the user setting.

**Comment by sunag** [comment]
> Maybe we can rename WebGPUConfig to something different?

Maybe `WebGPUPipelineUtils`?

**Comment by Mugen87** [comment]
Would `WebGPUUtils` be good, too? I'd favor a more generic name so we can easier use the module for other use cases.

**Comment by sunag** [comment]
> Would WebGPUUtils be good, too? I'd favor a more generic name so we can easier use the module for other use cases.

`WebGPUUtils` sounds good for me!!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
