### PR TITLE
NodeMaterial - Fix DoubleSided and BackSided NormalMap flipped

### LINKED ISSUE #17383: Node Material normals flipped
##### Description of the problem

On the newest version of three.js, the normals as seen on the  [node material example](https://threejs.org/examples/?q=node#webgl_materials_nodes) are flipped.

This is what it looked like [before the latest release](https://rawgit.com/mrdoob/three.js/r107/examples/?q=nodes#webgl_materials_nodes):

node-normal-before

[After the release](https://threejs.org/examples/?q=node#webgl_materials_nodes):
node-normal-after

##### Three.js version

- [x] Dev
- [x] r108

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Android
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] iOS

### PR DESCRIPTION
**Pull request by sunag**
https://raw.githack.com/sunag/three.js/dev-node-sides/examples/webgl_materials_nodes.html

Fixes #17383

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, when opening your live link, the normal map still looks flipped. However, if I switched to `BackSided` and then back to `FrontSided`, it looks good. Is this the intended behavior?

**Comment by sunag** [comment]
@Mugen87 I forgot to define the default side, the default side is DoubleSided and not FrontSided.

**Comment by sunag** [comment]
My issue is that apparently in non NodeMaterial too DoubleSided and FrontSided have different results rendering the front face only?

**Comment by sunag** [comment]
I think that it should be ` < 0.0`?
https://github.com/mrdoob/three.js/blob/84f9c5145548f67ffebf6e82478df97118c7bfd3/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl.js#L44

**Comment by sunag** [comment]
Seems that @bhouston explained better the cause better here:
http://hacksoflife.blogspot.com/2009/11/per-pixel-tangent-space-normal-mapping.html?showComment=1522254677437#c5087545147696715943

**Comment by sunag** [comment]
@arobertson0 @Mugen87 Seems correct now?

**Comment by WestLangley** [comment]
@sunag 

To test, remove the lid and bottom like so:
```js
teapot = new TeapotBufferGeometry( 15, 18, false, false );
```
so you can see what is happening.

`FrontSide` should be extruded; `BackSide` should be indented.

`DoubleSide` should be extruded on the front and indented on the back.

/ping @donmccurdy

**Comment by sunag** [comment]
Hmm @WestLangley seems that BackSide issue in NodeMaterial is related with this:
https://github.com/mrdoob/three.js/blob/2d7c0b461ef483a2cd46ca2057ba64880716b5ae/src/renderers/WebGLRenderer.js#L2264

**Comment by sunag** [comment]
Maybe should be we move this to the shader?

**Comment by sunag** [comment]
Anyway, this seems to fix DoubleSided fliped normal in front-face in core shader?

**Comment by WestLangley** [comment]
Double-sided materials with a normal map are broken in the core shader. Breakage occurred in r.108 -- possibly in #17158.

The breakage is easily-seen in `webgl_decals.html`. Make the following change in the example, and the decals will become inverted:

```js
var material = decalMaterial.clone();
material.side = THREE.DoubleSide; // add this
```

/ping @JordyvanDortmont
/ping @donmccurdy (to confirm desired behavior)

**Comment by WestLangley** [comment]
@sunag Whether the triangle is front-facing is a separate issue from whether the geometry and or UVs are mirrored. All we need is a test to replace `gl_FrontFacing`.

**Comment by WestLangley** [comment]
@sunag Oops. I did not realize you proposed a change to the core shader in this PR. I also proposed #17586.

**Comment by Mugen87** [comment]
> I also proposed #17586.

I think it's better to have a single PR and use a uniform solution in `normalmap_pars_fragment.glsl.js` and `NormalMapNode.js `. I've tested both solutions and both work.

@mrdoob Which one do you prefer? I suggest to update this PR with your desired solution and close #17586.

**Comment by sunag** [comment]
I liked the PR of @WestLangley, I suggest merge the PR of @WestLangley first and after I fix any conflicts.

**Comment by WestLangley** [comment]
@sunag Done!

**Comment by sunag** [comment]
The approach used currently to BackSided is incompatible with NodeMaterial and a bit more hard to implement. I think in leave this fix to another PR.
https://github.com/mrdoob/three.js/blob/2d7c0b461ef483a2cd46ca2057ba64880716b5ae/src/renderers/WebGLRenderer.js#L2264

**Comment by JordyvanDortmont** [comment]
I'm sorry for breaking the normals for double-sided materials!

I tested both PRs on a GTX 1070 and I see differences between the two PRs suggested. One is related to the `DoubleSide` issue, and another is related to `BackSide`.

While I was writing this, this PR has changed, so I'll describe the current behaviour of this PR.

The normals are flipped for `DoubleSide` when `use node material` is unchecked, so the teapot is indented on the front instead of extruded. Is this the case for you as well?

The normals flip when `webgl_materials_node` is set to `BackSide` and check/uncheck `use node material`. I think @sunag mentions this here: https://github.com/mrdoob/three.js/pull/17584#issuecomment-535725310 and here: https://github.com/mrdoob/three.js/pull/17584#issuecomment-536035471

When the `DoubleSide` issue is resolved, I'll test the PR on an Adreno GPU.

**Comment by sunag** [comment]
I was thinking of fix BackSided using shader, but with node seems easier... I will commit this fix.

**Comment by sunag** [comment]
> The normals are flipped for DoubleSide when use node material is unchecked, so the teapot is indented on the front instead of extruded. Is this the case for you as well?

My live example is only for nodematerial, the core was fixed in Wesley PR https://github.com/mrdoob/three.js/pull/17586.

**Comment by sunag** [comment]
I think it is ready to merge?

**Comment by arobertson0** [comment]
> I think it is ready to merge?

Looks great. As you said, this matches https://github.com/mrdoob/three.js/pull/17586. Thanks for the fix.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
