### PR TITLE
SSRPass: Support hierarchy and different intensity.

### PR DESCRIPTION
**Pull request by gonnavis**
[Demo](https://raw.githack.com/gonnavis/three.js/SSRPassSupportDifferentMetalnessPr/examples/webgl_postprocessing_ssr.html)

Supporting different metalness is a feature I have always wanted to add, and it is also a must-have feature.
But I have not been sure which method is the best, `one material for each metalness`, `layer` or something else?
It wasn't until I saw the codes in [Pass.js](https://github.com/mrdoob/three.js/blob/3c7d51552114e792bbdf2b77f1466416c0902f17/examples/jsm/postprocessing/Pass.js#L78) that I realized **can render `object3D` directly, not necessarily `scene`**. I think this should be the best way.
So now just use one `metalnessMaterial`, change it's `metalness` and render one `object3D` in a loop.
https://github.com/gonnavis/three.js/blob/c40ddf2d1114cdbf38e7da2386173267d5e5c659/examples/jsm/postprocessing/SSRPass.js#L603

But I'm still not sure, should I use the `metalness` property of object directly, or add a custom property to `selects`?
Is the logic of `selects` should applied consistently, rather than as an option?
Use `scene.tranverse` or `scene.children.forEach`?
I'm still looking for the most suitable solution, and want to avoid breaking changes as much as possible.

### CODE REVIEW

**Comment by mrdoob** [comment]
> But I'm still not sure, should I use the `metalness` property of object directly

That sounds good to me.

**Comment by gonnavis** [comment]
Bound Material's `metalness` to SSRPass's `opacity`, but the result seems not very well.

Blender use Material's `specular` to control SSR's `opacity`, but `MeshStandardMaterial` has not `specular`.
Seems still needs a independent `ssrPass.opacity` parameter. 🤔

[Demo](https://raw.githack.com/gonnavis/three.js/SSRPassSupportDifferentMetalnessPr/examples/webgl_postprocessing_ssr.html)
image

Blender
image
image

**Comment by mrdoob** [comment]
I think `envMapIntensity` is our `specular`?

/cc @WestLangley

**Comment by gonnavis** [comment]
> I think `envMapIntensity` is our `specular`?

Bound SSRPass's opacity to Material's envMapIntensity.

[Demo](https://raw.githack.com/gonnavis/three.js/26d92d919b6c87e51947425cffecd3ff65f63088/examples/webgl_postprocessing_ssr.html)
Looking better and feel more reasonable.

**Comment by WestLangley** [comment]
>I think envMapIntensity is our specular?

No, I believe Blender's Principled BSDF `specular` property equates to the `reflectivity` property of `MeshPhysicalMaterial`.

**Comment by gonnavis** [comment]
> I believe Blender's Principled BSDF `specular` property equates to the `reflectivity` property of `MeshPhysicalMaterial`.

Bound SSRPass's opacity to MeshPhysicalMaterial's reflectivity.
Awesome! Because realized the independent ssr opacity tweaking and no need add any custom parameter, at least for this demo scene.

[Demo](https://raw.githack.com/gonnavis/three.js/3aed165076523b3a2c15275040970f9fa7ff6648/examples/webgl_postprocessing_ssr.html)
But require MeshPhysicalMaterial.

How about, for per object ssr opacity,
use `reflectivity` if is MeshPhysicalMaterial,
use `envMapIntensity` if is MeshStandardMaterial,
use `specular` / `shininess` if corresponding materials have,
use `1` for others?

Still leave overrall ssrPass.opacity as is.

**Comment by mrdoob** [comment]
@WestLangley 

>> I think envMapIntensity is our specular?
>
> No, I believe Blender's Principled BSDF `specular` property equates to the `reflectivity` property of `MeshPhysicalMaterial`.

Ah!

Hmm... Should we "graduate" `reflectivity` to `MeshStandardMaterial`?
And... How about renaming it to `specular` to match Blender?

@donmccurdy Would this make sense in the context of GLTF?

**Comment by WestLangley** [comment]
>Should we "graduate" reflectivity to MeshStandardMaterial?

I do not think so. It may not be what you think it is. It is a very subtle effect.

**Comment by gonnavis** [comment]
Found Blender use the combination of at least `metalness` and `specular` to control the ssr's intensity.

image
image
image
image

**Comment by gonnavis** [comment]
Any chance to deriive the correct parameters from [this equation](https://twitter.com/KostasAAA/status/1379918353553371139)?
image

**Comment by gonnavis** [comment]
Found that in Blender, 
`metallic` and `envMap` blending more like `mix`,
`specular` and `envMap` blending more like `additive`.
image
image
image

**Comment by gonnavis** [comment]
Also tried to solve the [hierarchy problem](https://github.com/mrdoob/three.js/pull/20156#issuecomment-821116332) .

I want to use `renderer.render( object3D, camera )` to render objects and change the single `metallnessMaterial` one by one,
but found it'll render all descendants too, not what I want.

So tried to add a third parameter `includeChildren`:
https://github.com/mrdoob/three.js/blob/ce44c7d326d58e102059e9cb4f99164b56e04b73/src/renderers/WebGLRenderer.js#L977
Is this acceptable? All any other better solution?

**Comment by WestLangley** [comment]
@gonnavis

In `MeshPhysicalMaterial`, `refectivity` models the _specular reflectance_ of non-metals. It has no effect when `metalness` is 1.

In `MeshStandardMaterial`,  the specular reflectance of non-metals is hardwired to 0.04.

See #8529 and https://github.com/mrdoob/three.js/pull/8505#issuecomment-204530304.

**Comment by gonnavis** [comment]
@WestLangley Thanks a lot for your learning resource! I'll investigate.

**Comment by gonnavis** [comment]
three.js version of learnopengl.com's pbr demo:
https://raw.githack.com/gonnavis/three.js/pbr/examples/pbr_learnopengl.com.html

Translated [the code](https://github.com/JoeyDeVries/LearnOpenGL/blob/85ee9d136f49cf4469bf24f9c64a6e0c9245a685/src/6.pbr/1.1.lighting/1.1.pbr.fs) of [this tut](https://learnopengl.com/PBR/Theory) to three.js version, for better investigating and comparing.
And made the `reflectivity` tweakable based on [this code](https://github.com/mrdoob/three.js/blob/5a6df635c32071bec92df393f85c0d72ba34b560/src/renderers/shaders/ShaderChunk/lights_physical_fragment.glsl#L4).

**Comment by mrdoob** [comment]
@WestLangley 

>> Should we "graduate" reflectivity to MeshStandardMaterial?
>
> I do not think so. It may not be what you think it is. It is a very subtle effect.

Doesn't seem so subtle to me?
https://raw.githack.com/gonnavis/three.js/pbr/examples/pbr_learnopengl.com.html

**Comment by Mugen87** [comment]
Let's find a solution for this for the new `SSRNode` implementation (see #29597). We already have the metalness material values via MRT in the SSR shader so all what's left is finding a way to use it for the blending/weighting process.

BTW: If it turns out metalness is not the best property for defining what objects receive SSR reflections we can easily switch to something else. With `WebGPURenderer` it's just a question how we configure the MRT setup.

**Pull request closed without merging**
