### PR TITLE
WebXR: Covert to es6 class.

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
@linbingquan checking in on this PR.

couple of conflicts to resolve.

I light of [mrdoobs comments here](https://github.com/mrdoob/three.js/pull/21235#issuecomment-777472708), are there any any additional changes you'd make?

**Comment by Mugen87** [comment]
Do you mind resolving the merge conflicts?

**Comment by DefinitelyMaybe** [comment]
👍

**Comment by Mugen87** [comment]
Closing in favor of #21646 and #21648.

@linbingquan I'll still add you to the release notes for these changes 👍 .

**Pull request closed without merging**
