### PR TITLE
GLTFExporter: Missing required padding on integer vertex attributes

### LINKED ISSUE #25309: GLTFExporter: Missing required padding on integer vertex attributes
### Description

The glTF 2.0 standard states that:

> For performance and compatibility reasons, each element of a vertex attribute MUST be aligned to 4-byte boundaries inside a bufferView (i.e., accessor.byteOffset and bufferView.byteStride MUST be multiples of 4).

However, three.js - under some circumstances - creates glTF files containing a `byteStride` that is not a multiple of 4.

This happens because of the [following line](https://github.com/mrdoob/three.js/blob/03349e98aa1f57a97433c0a3f17697594fdc0997/examples/jsm/exporters/GLTFExporter.js#L930):

```
bufferViewDef.byteStride = attribute.itemSize * componentSize;
```

For example, you might decide to use single-byte integers for UV coordinates. So each item might be an unsigned byte (and thus have an `itemSize` of 1) and the `componentSize` be 2, leading to an invalid `byteStride` of 1*2 = 2.

### Reproduction steps

1. Generate an invalid glTF using the example code/jsfiddle below
2. Upload it to the [glTF validator](https://github.khronos.org/glTF-Validator/) to see how it is broken

### Code

```js
const geom = new THREE.BufferGeometry()
geom.setAttribute(
  'position',
  new THREE.BufferAttribute(new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]), 3)
)
geom.setAttribute('uv', new THREE.BufferAttribute(new Uint8Array([0, 0, 1, 0, 0, 1]), 2))

const mesh = new THREE.Mesh(geom)

const exporter = new GLTFExporter()
exporter.parse(
  mesh,
  data => {
    const file = new File([JSON.stringify(data)], "mesh.gltf")
    const a = document.createElement('a')
    a.href = URL.createObjectURL(file)
    a.download = file.name
    document.body.appendChild(a)
    a.click()
  },
  err => {
  },
  { binary: false }
)
```

### Live example

* [jsfiddle-latest-release - example gltf creation](https://jsfiddle.net/4nkagz1p/)

### Screenshots

_No response_

### Version

r148

### Device

Desktop

### Browser

Firefox

### OS

MacOS

### PR DESCRIPTION
**Pull request by grzesiekmq**
Fixed #25309

**Description**

Problem was with missing padding on integer vertex attributes.
Problem solved by padding with additional two 0's to 6 bytes filled `Uint8Array` , to make it 8 bytes, so
result is `Uint8Array([0, 0, 1, 0, 0, 1, 0, 0])`  
like on screenshot below:
image

But **note** issue with required stride **is not still solved**

### CODE REVIEW

**Comment by grzesiekmq** [comment]
oh I see I pushed also commit with discarded changes so this commit shouldn't be
I wanted only to add commit with 'added missing padding to integer vertex attributes'
not this 'merge dev... '

**Comment by jabri62018** [comment]
https://www.facebook.com/100069268520164/posts/662222566096688/?mibextid=rS40aB7S9Ucbxw6v


👁️🦁🇵🇸🟤🇾🇪🚓

ياخبرة.....

الذي يعرف ينزل هذا الفيديو ورابطة هو::::


https://www.facebook.com/100025489485753/posts/pfbid0SNe14C7pKXXFybtmrpzmYTe8od7wD9LSq9b2GuFsHTipmavfnwBKWnA765nkQA3Ql/?app=fbl



انا مشغول ومقيد بالصلاحيات....

Who can download that vedio?
👁️🦁🇵🇸


https://www.facebook.com/100025489485753/posts/1424599398399696/?mibextid=rS40aB7S9Ucbxw6v

🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸🇵🇸
#Al-Aqsa_Flood
#Here_Yemen
#Here_Palestine
O people, listen and be aware:::

You, not me, not Sanaa, not Aden, not Yemen. We say:::: not Gaza, Al-Aqsa,
Jerusalem, Palestine, and...
We are surrounded, so no:
- Electricity and gas (we have no light)
- Water (And We made from water every living thing)
- Wheat (food)
- Treatment (diseases)
- Salaries (non-income)
- Internet (no connection)
- Petroleum and its derivatives (immobile)
- The entire infrastructure was destroyed. (We have no roof)
9 years ago for the war of aggression against Yemen... and before that 6
years of transitional phase and the Arab Spring and before that 6 years of
the Saada wars, and now you know what today’s events are? ▄ Hunger - thirst
- diseases - siege - killing - kidnapping - displacement - division -
displacement - colonization...

I forgot to mention what we have?
- We have independence and freedom, and there is no guardianship over the
Republic of Yemen, and Bayt Al-Maqdis (Al-Aqsa - Haziz - Bayt Al-Jabri) is
an endowment for all Muslims.

✍ #Abdulla_AlJabri
- Sanaa... 4/23/1445 AH
Tuesday... 11/7/2023 AD
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸
🇾🇪🚓🦁🇵🇸👁️
#طوفان_الاقصى
#هنا_اليمن
#هنا_فلسطين
ايها الناس اسمعوا وعوا :::

انت بل انا بل صنعاء بل عدن بل اليمن نقول:::: بل غزة والاقصى والقدس وفلسطين
و ...
نحن محاصرون فلا:
- كهرباء وغاز (لا نور لنا)
- ماء (وجعلنا من الماء كل شيئا حيا)
- قمح (طعام)
- علاج (امراض)
- مرتبات (عديمي دخل)
- انترنت (عديمي تواصل)
- بترول ومشتقاتة (عديمي الحركة)
- البنية التحتية بالكامل دمرت.(لا سقف لنا)
منذ 9 سنوات لحرب العدوان لليمن...وقبلها 6 سنوات مرحلة انتقالية والربيع
العربي وقبلها 6 سنوات لحروب صعدة والان تعرفون ماهي احداث اليوم?▄ جوع- عطش-
امراض- حصار-قتل-خطف-تشربد-تقسيم- تهجير-استعمار...

نسيت ان اذكر ماذا نملك?
- نملك الاستقلال والحرية ولا توجد وصاية على الجمهورية اليمنية وبيت
المقدس(الاقصى-حزيز-بيت الجبري) وقف ذرية لجميع المسلمين.

✍ #عبدالله_الجبري
- صنعاء... 24/4/1445 هجري
الاربعاء... 8/11/2023م
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸

**Comment by mrdoob** [comment]
@donmccurdy Is this required?

**Comment by donmccurdy** [comment]
I agree that something like this is probably needed. However, I'm not sure if the padding should be limited to cases where `target === WEBGL_CONSTANTS.ARRAY_BUFFER`, and I believe padding may *also* be needed when `componentSize` is 2. And as @grzesiekmq mentions, there is a remaining issue with stride.

Right now I don't have time to investigate or test this further, but if someone else would like to do so, please do! 

This is a case where I do wish we still had unit tests covering GLTFExporter, it would save a lot of time manually checking edge cases.

**Comment by takahirox** [comment]
Hi, thanks for making a PR!

I don't think I have looked into the issue and the change in deep yet but let me share my some impressions for now.

```
if(componentSize === 1){
  const paddedArray = new Uint8Array(getPaddedArrayBuffer(attribute.array.buffer));
  attribute.array = paddedArray;
}
```

It's a bit weird to me that Exporter has a side effect to Three.js object. Ideally no side effect in Three.js objects, but adjusting the byte offset and stride in exported glTF would be better.

Also, wondering whether it's a good place to insert the code. The code is inserted at almost the end of `processBufferView()` and after that part that attribute doesn't seem to be accessed.

As @donmccurdy 's comment,

> I'm not sure if the padding should be limited to cases where target === WEBGL_CONSTANTS.ARRAY_BUFFER, and I believe padding may also be needed when componentSize is 2.

I agree with it.

> This is a case where I do wish we still had unit tests covering GLTFExporter, it would save a lot of time manually checking edge cases.

I feel the same. glTF loader and exporters are under addons but because of the standard 3D format they are one of the most popular modules in Three.js and have been wanting automatic/unit tests for them. If lack of resources for maintaining the tests for glTF stuffs in the official Three.js repo, I've been thinking of that we volunteers make an external Three.js glTF stuffs test repository, that has glTF loader/exporter unit/e2e tests, imports Three.js glTF loader/exporter, and run the tests.

**Comment by takahirox** [comment]
If I understand the issue correctly, glTF loader already [attempts to keep byte offset on four-byte boundary](https://github.com/mrdoob/three.js/blob/76bff1eb9584c47d521755b87e49246079a8ae24/examples/jsm/exporters/GLTFExporter.js#L985) but [doesn't take care of byte stride](https://github.com/mrdoob/three.js/blob/76bff1eb9584c47d521755b87e49246079a8ae24/examples/jsm/exporters/GLTFExporter.js#L1065) (as described in #25309).

Perhaps the lines we need to edit are [here](https://github.com/mrdoob/three.js/blob/76bff1eb9584c47d521755b87e49246079a8ae24/examples/jsm/exporters/GLTFExporter.js#L985-L1050). I think we need to

* Calculate byte stride first
* Take the byte stride into account [when calculating the padded byte length](https://github.com/mrdoob/three.js/blob/76bff1eb9584c47d521755b87e49246079a8ae24/examples/jsm/exporters/GLTFExporter.js#L985)
* Add padding [at the end of each item until the boundary](https://github.com/mrdoob/three.js/blob/76bff1eb9584c47d521755b87e49246079a8ae24/examples/jsm/exporters/GLTFExporter.js#L1049)

**Comment by takahirox** [comment]
@grzesiekmq Let me know if you are too busy now. I can take over. Even if I do I ask @Mugen87 to add your name to the release log because I want to respect your original work.

**Comment by mrdoob** [comment]
@takahirox Feel free to take over and update this PR! 👍

**Comment by takahirox** [comment]
OK. I would like to wait for @grzesiekmq 's response for a few days for now because I really don't want to steal his contribution. And then I would try to update this PR if no response.

**Comment by grzesiekmq** [comment]
> @grzesiekmq Let me know if you are too busy now. I can take over because this issue really needs to be fixed. Even if I do I ask @Mugen87 to add your name to the release log because I want to respect your original work.

Yes, please take it over, I don't have idea how to continue this

**Comment by takahirox** [comment]
OK, I will take it over. I'm working on the issue...

**Comment by donmccurdy** [comment]
@takahirox ah you're right, thank you!

**Comment by takahirox** [comment]
I have reflected [this idea](https://github.com/mrdoob/three.js/pull/27064#issuecomment-1945397522) to this PR, and confirmed that the error is disappeared in [this example](https://github.com/mrdoob/three.js/issues/25309#issue-1550136904).

I didn't test many enough yet, but if you folks start to review, it's very helpful to me.

**Comment by takahirox** [comment]
I think ready for review @donmccurdy @Mugen87

**Review by Mugen87 — APPROVED** [review]

**Review by donmccurdy — APPROVED** [review]
Thank you!

**Pull request merged**
