### PR TITLE
Introduce TriangleStrip and TriangleFan via mode in Mesh

### PR DESCRIPTION
**Pull request by Axiverse**
Reintroduce the ability for meshes to render triangle strips (and triangle fans for completeness) as tracked in issue https://github.com/mrdoob/three.js/issues/4738. This follows the same convention as LinePieces and LineStrip in THREE.Lines. Tested and works fine from a rendering point of view. There may be support functions that don't support alternate triangle configurations.

### CODE REVIEW

**Comment by Axiverse** [comment]
7124fcc is unrelated to this, not sure how to separate out commits into different pull requests. It's code clean up for a build error I'm getting. I'm using build.js, doesn't seem to show up using build.py.

**Comment by dubejf** [comment]
I cannot comment on the technical merits of your patch, but the unused variable in 7124fcc was fixed earlier today in the `dev` branch!

You seem to have made a mistake with your build command. You have overwritten `src/Three.js` (a source file) with what should be `build/three.js` (build output). 1) wrong path 2) you should not include build output in your PR.

**Comment by Axiverse** [comment]
Reverted, sorry.

**Comment by mrdoob** [comment]
Do you mind doing a new PR targeting the `dev` branch instead?

**Comment by WestLangley** [comment]
You need to fork and target the `dev` branch instead. Please see the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

> This follows the same convention as LinePieces and LineStrip in THREE.Lines.

They no longer exist. See `THREE.LineSegments` in the dev branch.

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#6849

**Comment by mrdoob** [comment]
Do you mind targeting the `dev` branch instead?

**Pull request closed without merging**
