### PR TITLE
WebGPU: Custom Lighting Model

### PR DESCRIPTION
**Pull request by sunag**
**Description**

An example of  how to create custom lighting model with `NodeMaterial` and `PointsMaterial`.

**Related**

https://github.com/mrdoob/three.js/issues/17618

image

### CODE REVIEW

**Comment by sunag** [comment]
A `points` distanced based light model example: (this example)

`lightColor` already returns the color with the intensity calculated.

```glsl
void ( vec3 lightColor ) {

	ReflectedLightDirectDiffuse += lightColor;

}
```

A `mesh bling phong` light model example:
```glsl
void RE_Direct_BlinnPhong( vec3 lightDirection, vec3 lightColor ) {

	float dotNL = saturate( dot( NormalView, lightDirection ) );
	vec3 irradiance = dotNL * lightColor;

#ifndef PHYSICALLY_CORRECT_LIGHTS

		irradiance *= PI; // punctual light

#endif

	ReflectedLightDirectDiffuse += irradiance * BRDF_Diffuse_Lambert( MaterialDiffuseColor.rgb );

	ReflectedLightDirectSpecular += irradiance * BRDF_Specular_BlinnPhong( lightDirection, MaterialSpecularColor, MaterialSpecularShininess );

}
```

**Comment by Mugen87** [comment]
Looks interesting!

I like the idea introduced in #21322 to represent components of a lighting model as instances of `FunctionNode` that can be changed/modified by the user. In this way, users are implementing nodes instead of implementing the raw vertex/fragment shader or overriding shader chunks via `onBeforeCompile()`. 

This goes definitely into the right direction 👍 .

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
BTW: It seems the spheres representing the point lights in `webgpu_lights_custom` and `webgpu_lights_selective` are black now. Is it because both examples still use `MeshBasicMaterial` instead of `MeshBasicNodeMaterial`?

**Comment by sunag** [comment]
> BTW: It seems the spheres representing the point lights in webgpu_lights_custom and webgpu_lights_selective are black now. Is it because both examples still use MeshBasicMaterial instead of MeshBasicNodeMaterial?

Ohh… I will fix it.

**Pull request merged**
