### PR TITLE
use diffuseColor and outgoingLight instead of repeatedly redefining what gl_FragColor is

### PR DESCRIPTION
**Pull request by bhouston**
Right now lightMap is modulating the gl_FragColor after the lighting calculation modifies gl_FragColor to include specular and diffuse lighting contributions.  This is not correct.

lightMap should be considered un-directional incoming light that should get modulated by the surface color (diffuseColor) and then it should be added to the result.

This is what this PR does by introducing the new `diffuseColor` variable into all the shaders that is properly modulated by the `map` and the vertex colors, as well as an `outgoingLight` that accumulates the outgoing light contributions from the various shading calculations.

This fixes a lot of issues where gl_FragColor was repeatedly modified by multiple shader blocks, but its definition of what it was supposed to represent was constantly changing.

This new formulation clarifies both how diffuseColor is built up and also what is going into the resulting gl_FragColor via outgoingLight.

Motivated by this discussion here: https://github.com/mrdoob/three.js/pull/5741#issuecomment-67876234

### CODE REVIEW

**Comment by WestLangley** [comment]
> I would document the exact meaning of those variables

Agreed. I would like hold off on this one until previous commits are merged and the conflicts are resolved. I need to have a closer look at this PR.

**Comment by mrdoob** [comment]
Ok. Dependency PRs has been merged I think?

**Comment by WestLangley** [comment]
There must be conflicts. I see remnants of `ambient` here and there. I will check it after @bhouston has done some testing.

This should be a refactoring only, and should produce the same output as before. Modeling changes can be made in later PRs.

**Comment by mrdoob** [comment]
@bhouston any idea of when you will be able to address @WestLangley points?

**Comment by bhouston** [comment]
I'd like to get to it this week.  Sorry for the delay.

**Comment by bhouston** [comment]
@mrdoob @WestLangley Sorry for the delay, was a bit sick.  I've merged in dev into this branch and fixed a few minor issues with ShaderSkin.js (it is tricky as it isn't clear what it trying to do sometimes, but I made it behave as it used to -- thus no regressions.)

**Comment by mrdoob** [comment]
@WestLangley looks good to you?

**Comment by WestLangley** [comment]
> @WestLangley looks good?

I want to take a careful look... I'll be able to get to this in a few days.

**Comment by mrdoob** [comment]
Oks!

**Comment by WestLangley** [comment]
I had hoped this PR would focus on code refactoring only, but there appears to be modeling changes too, several of which I feel are incorrect.

I am suggesting the following corrections as a first pass. Once these changes are implemented, I'll have another look.

1. In THREE.ShaderChunk[ "lightmap_fragment" ], replace `outgoingLight += diffuseColor.xyz * texture2D( lightMap, vUv2 ).xyz;` with  `outgoingLight *= texture2D( lightMap, vUv2 ).xyz;`. Lightmaps are multiplicative in three.js. In addition, reconsider your changes to the lighting in the examples you modified. That may no longer be needed.

2. In THREE.ShaderChunk[ "linear_to_gamma_fragment" ], add a new line to the end of the file.

3. Everywhere, replace `outgoingLight.xyz` with `outgoingLight`.

4. In THREE.ShaderChunk[ "lights_phong_fragment" ], `totalDiffuseLight`, as you have defined it, is the total _incoming_ light for the diffuse term. `totalSpecularLight`, as you have defined it, is the total _outgoing_ (reflected) specular light. The fact that these terms have similar names is confusing, IMO. Can you suggest better terminology?

5. In THREE.ShaderChunk[ "lights_phong_fragment" ], for the non-metal case, you have `outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + ambientLightColor * diffuse ) + totalSpecularLight + emissive;`. It should be `outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + ambientLightColor ) + totalSpecularLight + emissive;`.

6. This same error as in 5. appears in the NormalDisplacementShader and in ShaderTerrain.

7. In THREE.ShaderChunk[ "lights_phong_fragment" ], for the metal case, the model never was correct. For now, I'd make it match the non-metal case, and we will fix it before the next PR.

8. You wrote "Light map on an otherwise unlit surface doesn't make sense." To the contrary, lightmaps on `MeshBasicMaterial` make perfect sense. I think it is fine as is.

9. The Lambert model is totally messed up. I will fix it in another PR before the next release.

I will have a look at the skin shaders after the above changes are implemented.

**Comment by bhouston** [comment]
@WestLangley Thanks so much for having a look.  I agree with most changes but a few stand out:

> In THREE.ShaderChunk[ "lightmap_fragment" ], replace outgoingLight += diffuseColor.xyz * texture2D( lightMap, vUv2 ).xyz; with outgoingLight *= texture2D( lightMap, vUv2 ).xyz;. Lightmaps are multiplicative in three.js. In addition, reconsider your changes to the lighting in the examples you modified. That may no longer be needed.

I disagree that Light map should modulate outgoingLight, it should be just another light source added to the outgoingLight -- although it can make sense to modulate lightMap by the diffuseColor of the surface/map.  This is a key bug in ThreeJS that I am trying to fix.  This is actually discussed as the primary motivator for this PR here: https://github.com/mrdoob/three.js/pull/5805#issue-52680580.

I would really prefer not to change this because it breaks lightMaps -- you can never use them as they are used in other game engines if we are modulating outgoingLight by the lightMaps.  If we do this, we are unique in our use of lightMaps and I think it is problematic.

> In THREE.ShaderChunk[ "lights_phong_fragment" ], totalDiffuseLight, as you have defined it, is the total incoming light for the diffuse term. totalSpecularLight, as you have defined it, is the total outgoing (reflected) specular light. The fact that these terms have similar names is confusing, IMO. Can you suggest better terminology?

With regards to "totalDiffuseLight", it isn't exactly incoming light because it is weighty by the surface normal relative to the light (N dot L), thus it is probably better considered the reflected diffuse light unmodulated by the surface color (because that happens afterwards.)  It is an intermediate value.

> In THREE.ShaderChunk[ "lights_phong_fragment" ], for the non-metal case, you have outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + ambientLightColor * diffuse ) + totalSpecularLight + emissive;. It should be outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + ambientLightColor ) + totalSpecularLight + emissive;.

I do prefer the second version your propose, but the reason that I now have the first version is because of this comment of yours here (as I originally did have the second version):

https://github.com/mrdoob/three.js/pull/5809#issuecomment-68063733

In response to your previous comment that I link to above, I made this comment to put back the "* diffuse" modulation of ambientLightColor.

https://github.com/bhouston/three.js/commit/263109a251d1af067e83a157ad668929427e2b92

I am okay with either version, but I wanted to make you aware of why this is in the code now.

> You wrote "Light map on an otherwise unlit surface doesn't make sense." To the contrary, lightmaps on MeshBasicMaterial make perfect sense. I think it is fine as is.

Can you clarify where I wrote this?  I don't understand my own context, sorry.

**Comment by WestLangley** [comment]
@bhouston Thanks. I appreciate your efforts to refactor the code base and to improve the models.

Regarding the lightmap issue, in [this comment](https://github.com/mrdoob/three.js/pull/2372#issuecomment-8202145) @alteredq states:

> Also lightmaps should be multiplicative, not additive. Big use case for lightmaps are pre-baked shadows and ambient occlusion, so you need to be able to darken things.

The way you allow a light map to lighten a scene is to use `Modulate2X`, as discussed in [here](https://github.com/mrdoob/three.js/pull/5741#issuecomment-66477956).

I am in favor of multiplicative light maps. I am also in favor of supporting `Modulate2X`. Whatever we do, the rendering pipeline must be consistent with the assumptions made when the lightmaps are baked.

But we should move this discussion to a new thread. If you want to change how lightmaps are handled, it should be in a sparate PR, please. This PR is a code refactoring.

> With regards to "totalDiffuseLight", it isn't exactly incoming light because it is weighty by the surface normal relative to the light (N dot L), thus it is probably better considered the reflected diffuse light unmodulated by the surface color (because that happens afterwards.) It is an intermediate value.

I would argue the the cosine term is required to properly account for the intensity of the incoming radiance, so `totalDiffuseLight` is the incoming light.

In any event, in this PR, you moved `material.diffuse` into the `diffuseColor` term. Therefore, you do not need to apply it again when accounting for the ambient light effect.


> Can you clarify where I wrote this? I don't understand my own context, sorry.

It is in your PR in `ShaderLib.js`.

**Comment by bhouston** [comment]
Hi @WestLangley.

I am in favor of modulating the diffuseColor/diffuseMap by lightMaps.  But it is incorrect for lightMaps to modulate other lighting effects in the scene.  It is supposed to be considered another source of light that is additive with all the others -- thus you can combine a lightMap with a real-time lighting source correctly.

You can still bake in ambient occlusion and shadows into light maps.  Ambient occlusion would just be done as an absense of light in corners, so values in the light map closer to 0.  And shadows are also done as the absence of light.  This happens automatically in a global illumination baking solution. :)

LightMaps by their name are additive lightMaps.  If you want a shadow map or something that makes texture darker, then you need to call it something else -- because it isn't technically a light map.

> If you want to change how lightmaps are handled, it should be in a sparate PR, please.

I mentioned this issue in the first two sentences of this PR's writeup -- it was supposed to be the point of this PR. :/

I discussed this before this PR with @mrdoob here: https://github.com/mrdoob/three.js/pull/5741#issuecomment-67875815  And then I created this PR specifically to fix this issue with lightMaps.

Why are we even discussing this PR if I can not use it to fix the issue that motivated it?

**Comment by WestLangley** [comment]
@bhouston I can see you are upset. I am sorry. Please understand that I am on your side, and I am confident we will get to a solution we both find acceptable.

Lightmaps can be handled as either additive or multiplicative. In three.js, as implemented by @alteredq, they are multiplicative, and can only darken. As I proposed elsewhere, we can add suppport for `Modulate2X

**Comment by mrdoob** [comment]
> How about if we also implement your additive lightmaps? There would be a flag that specifies how the lightmap is to be interpreted?

Yeah, I think something like this would be great. Just like we already do with envMap:
https://github.com/mrdoob/three.js/blob/master/src/materials/MeshBasicMaterial.js#L55

So, am I right on understanding that this PR is changing the lightMaps from multiplicative to additive and we need to address it first? Or can I merge already and we can tweak things later?

Thanks for your patience guys!

**Comment by WestLangley** [comment]
This is not ready to be merged yet. Also, I still have not reviewed the skin shaders.

I am hopeful that @bhouston will agree that it makes sense to support a variety of light map types:

    Mesh*Material.lightmapType

    THREE.MupltiplyOperation
    THREE.AddOperation
    THREE.Modulate2XOperation

Or, if you do not think it is wise to reuse constants for multiple purposes (this would be my preference), then:

    Mesh*Material.lightmapType

    THREE.LightmapMupltiply
    THREE.LightmapAdd
    THREE.LightmapModulate2X

**Comment by mrdoob** [comment]
> I am hopeful that @bhouston will agree that it makes sense to support a variety of light map types:

I agree, but we can do that in another PR?

**Comment by WestLangley** [comment]
> I agree, but we can do that in another PR?

Yes.

> I am in favor of modulating the diffuseColor/diffuseMap by lightMaps. 

We agree on that, and you are correct in that the product of lightmap and diffuseColor/Map should be additive to `outgoingLight`. I see now that that was your intention from the start.

@bhouston My apologies, we were cross-talking, and it was most likely my fault.

If you can make the agreed-upon changes, that would be great.

**Comment by mrdoob** [comment]
@bhouston let me know if you have time next week to sort this out, otherwise I'll try to dive in into all this myself.

**Comment by bhouston** [comment]
@mrdoob @WestLangley I've done some research into game materials and talked to a bunch of people very knowledgable in the area.

The main issue here is trying to fit two things into one. Light maps, which are purely additive, and ambient occlusion maps, which modulate incoming light.  They are separate things and need to be treated as such.

So @WestLangley is right that if it is an ambient occlusion map, it modulates incoming light.  And I am right that light maps are purely additive.  The confusion was that we were combining both, and they are two different things -- and technically they should be supported at the same time.

The Frostbite engine paper is incredibly interesting because they go further and treat diffuse ambient occlusion separately than specular ambient occlusion -- I don't advocate going that far yet, but it is interesting.  Page 74-75, section 4.10.1 in this note on Frostbite engine:
http://www.frostbite.com/wp-content/uploads/2014/11/course_notes_moving_frostbite_to_pbr.pdf

I'll remove the light map change in this PR and do it as a separate PR.

**Comment by WestLangley** [comment]
@bhouston Let's just make sure we agree. The exacts words are important in this case. : - )

> So @WestLangley is right that if it is an ambient occlusion map, it modulates incoming light.

AO maps are _ambient occlusion_ maps and only modulate incoming _ambient_ light, a.k.a., "indirect diffuse light". They do not modulate all incoming light -- light from direct sources, for example.

(Ambient specular, which we do not currently model, is a separate issue.)

>  I am right that light maps are purely additive.

Yes, a light map is additive to total incoming light. It also modulates the diffuse reflectance of the material (`diffuseColor/Map`), just like other lights.

But _how_ it modulates the diffuse reflectance of the material depends on the light map type. It could be purely multiplicative (like other lights), or it can use the `Modulate2X` formula, which is also multiplicative, but with a slightly different formula.

**Comment by bhouston** [comment]
@WestLangley Yes, our current use of lightMaps as what others call ambientOcclusion is wrong in that we are modulating all light sources when usually, according to the Frostbite paper, they only generally modulate indirect light.  So when we properly implement lightMaps (as additive, with a scale factor to allow for things Modulate2X*) and ambientOcclusion (as modulating indirect lighting), we need to do these separately and properly.

* My understanding is that "modulate2X" is just the standard modulation with a 2x scale factor.  We might as well put in an arbitrary scale factor as Unity 5 does.

**Comment by mrdoob** [comment]
Merged! Thanks for your patience guys.

**Comment by mrdoob** [comment]
Btw, this broke `webgldeferred_arealights` and `webgldeferred_pointlights`. Any ideas?

**Comment by bhouston** [comment]
I'll have a look in a couple hours.

**Comment by bhouston** [comment]
Fixed in this PR: https://github.com/mrdoob/three.js/pull/6209

**Comment by mrdoob** [comment]
`webgl_lines_dashed` seems to be affected too. It's all black now.

**Comment by WestLangley** [comment]
> webgl_lines_dashed seems to be affected too. It's all black now.

This patch to the 'dashed' shader seems to make sense.

				THREE.ShaderChunk[ "logdepthbuf_fragment" ],
				THREE.ShaderChunk[ "color_fragment" ],

			"	outgoingLight = diffuseColor.rgb;", // simple shader

				THREE.ShaderChunk[ "fog_fragment" ],

**Comment by mrdoob** [comment]
Thanks!

**Comment by titansoftime** [comment]
I am getting this error in dev:

THREE.WebGLShader: Shader couldn't compile.
Three71dev2.full.js:34 THREE.WebGLShader: gl.getShaderInfoLog() ERROR: 0:190: 'outgoingLight' : undeclared identifier 
ERROR: 0:190: 'mix' : no matching overloaded function found

**Comment by WestLangley** [comment]
@titansoftime A simple example to reproduce the problem would be helpful. Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by titansoftime** [comment]
I know, I know. I'm at work right now. I will later, just wanted to give a heads up.

**Comment by mrdoob** [comment]
@bhouston can you take a look at `webgldeferred_pointlights` in `dev`? Seems to be broken at the moment...

**Comment by C4RL05** [comment]
Lightmaps on MeshBasicMaterial appear to be broken, it looks like diffuseColor is multiplied twice in the shader:

outgoingLight = diffuseColor.rgb;
outgoingLight *= diffuseColor.xyz * texture2D( lightMap, vUv2 ).xyz;

This seems to come from removing the `#if defined( PHONG )` from `src/renderers/shaders/ShaderChunk/lightmap_fragment.glsl` [here](https://github.com/mrdoob/three.js/commit/cc7634efa2ac6783ee58a5aa5893bd9ba71814bc#diff-87d040b59403733cfa50701f86903a67)

/cc @mrdoob @bhouston

**Comment by WestLangley** [comment]
@C4RL05  Yes, there were errors, but a lot has happened since. See https://github.com/mrdoob/three.js/pull/6364 and https://github.com/mrdoob/three.js/pull/6588.

**Comment by C4RL05** [comment]
@WestLangley I see, there's quite a few changes. Thanks for the heads up, much appreciated.

**Pull request merged**
