### PR TITLE
New example: break objects by throwing balls

### PR DESCRIPTION
**Pull request by yomboprime**
In this example you can throw balls to existing objects which breaks into pieces, which can also be broken.

The example uses `Ammo.js` to handle the physics, and the great `THREE.ConvexGeometry` to construct the pieces from a set of points.

It occurred suddenly to me that dividing a convex object by a plane always gives two resulting convex pieces, and as long as the pieces vertex count is keep low, it can be done in real time.

So i implemented the `cutByPlane` function and then a `subdivideByImpact` one which does a radial and then random recursive subdivision using the previous `cutByPlane`

The subdivision algorithm is located in `THREE.ConvexObjectBreaker` class and it is independent of the physics library. It can be used to subdivide any convex `Geometry`, not just `ConvexGeometry`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by yomboprime** [comment]
Great!

**Comment by satori99** [comment]
This is awesome. Nice work!

**Pull request merged**
