### PR TITLE
Docs: replace RegExp search with fuzzy search

### PR DESCRIPTION
**Pull request by peppsac**
Fuzzy search is used in several software and is a handy way to search for files
by name.

The implementation used can order result by score but this commit didn't use it to
preserve the original ordering of items.

The implementation comes from https://github.com/forrestthewoods/lib_fts/blob/master/code/fts_fuzzy_match.js

Note: the same feature could be used for the example pages as well.

---
This change is [Reviewable](https://reviewable.io/reviews/mrdoob/three.js/13505)

### CODE REVIEW

**Comment by peppsac** [comment]
Example search results when typing `wre`:
    - **W**i**ref**rameGeometry
    - Ra**w**Shade**r**Mat**e**rial
    - **We**bGL**R**enderer
    - **We**bGL**R**enderTarget
    - **We**bGL**R**enderTargetCube

**Comment by looeee** [comment]
[Live version](https://rawgit.com/peppsac/three.js/ff0fbac2af5d9195b6629a3a010f177e817b2ac4/docs/index.html)

Personally I don't think is very useful. I'd rather if I search `mes` that I get things related to meshes. Instead I also get: 

DrawModes
Materials
CompressedTextureLoader
etc...

**Comment by peppsac** [comment]
Thanks for the live version link!

> Personally I don't think is very useful. I'd rather if I search mes that I get things related to meshes. Instead I also get: [...]

If the "display best ranked search result first" was enabled, the first results would be more relevant (see [this example](https://s3-us-west-2.amazonaws.com/forrestthewoods.staticweb/lib_fts/tests/fuzzy_match/fts_fuzzy_match_test.html)).

**Comment by looeee** [comment]
There is another PR that improves docs search functionality here btw #13027

**Comment by Mugen87** [comment]
I don't have the impression that the current search of docs/examples is not precise enough. Adding an additional dependency `fts_fuzzy_match.js` seems a little bit overengineered to me.

**Comment by peppsac** [comment]
> I don't have the impression that the current search of docs/examples is not precise enough

It's not really a matter of precision. Fuzzy search is IMHO more convenient (I use SublimeText so of course I'm biased, but other softwares use it too: Atom, Chrome Dev tools, etc).

Regarding the additional dependency: it's 250 lines of self-contained js (and could be reduced to 150 by removing the unused `fts_fuzzy_match_async` function) so I don't see what harm it could cause?

**Comment by looeee** [comment]
> if the "display best ranked search result first" was enabled, the first results would be more relevant

But then the order of the menu would be messed up.

**Comment by mrdoob** [comment]
I agree with @looeee and @Mugen87. I prefer the current behaviour too.
Thanks though!

**Pull request closed without merging**
