### PR TITLE
Mesh: Fix raycast() for BufferGeometry with multiple materials

### PR DESCRIPTION
**Pull request by Mugen87**
After some user feedback i have revived #11860.

It fixes raycasting with `BufferGeometry` and multiple materials. It also adds support for `drawRange` and `groups`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by JohnRCook** [comment]
I tested the fix today. The raycaster with multi materials works now. The only problem is that faceIndex in the Intersection-Object is always '0'. I use the face.a as a workaround now.

**Comment by Mugen87** [comment]
@JohnRCook Can you please test if #14392 solves your problem?

**Comment by JohnRCook** [comment]
@Mugen87 I tested #14392 and it does solve the problem. Thanks!

**Pull request merged**
