### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
More `Geometry` removal.

BTW: I've noticed that the [uv debug texture](https://github.com/mrdoob/three.js/blob/dev/examples/textures/UV_Grid_Sm.jpg) is actually wrong. (0,0) should be bottom left, not top left. And (1,1) should be top right, not bottom right.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawgit.com/Mugen87/three.js/dev11/examples/webgl_raycast_texture.html
https://rawgit.com/Mugen87/three.js/dev11/examples/webgl_shaders_tonemapping.html

**Comment by Mugen87** [comment]
How about this one? It's the same like doing `gl_FragColor = vec4( vUv.x, vUv.y, 0.0, 1.0 );` in the fragment shader.

uv_grid_sm

**Comment by looeee** [comment]
I made one a while back, feel free to use it if you like it.

uv_test_512

**Comment by Mugen87** [comment]
@looeee That's great! Let's replace the current one with yours :+1:

**Comment by Mugen87** [comment]
@mrdoob @WestLangley What do you think about the new uv debug texture? Is it okay like this?

**Comment by WestLangley** [comment]
Sorry, with all due respect, I think it is confusing. I would stick to a more-conventional reference map.

**Comment by Mugen87** [comment]
Unfortunately, I was not able to find one that we can safely use in this project. I'm afraid we have to create a new one...

**Comment by Mugen87** [comment]
@mrdoob I will remove the changes to the uv map, so this PR can be merged. We can change the uv map at a later point.

**Comment by Mugen87** [comment]
Done!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
