### PR TITLE
bsdfs.glsl: Correct comment in G_GGX_Smith

### PR DESCRIPTION
**Pull request by Mugen87**
The common geometry or shadowing/masking function of a microfacet specular BRDF looks like this: `G(l,v,h)`. `three.js` uses the GGX model based on Smith's method to determine how many microfacets are unshadowed and unmasked so they actually transfer light.

The formal notation is:

`G(l,v,h) = G_GGX(l) * G_ GGX(v)` where `G_GGX` is:

image

This formula is basically implemented in `G_GGX_Smith()` although the term in the numerator is not regarded, for good reasons.

While studying the implementation i've noticed that a comment in `G_GGX_Smith()` is not correct. ~I think numerator and denominator need to be switched. Only then `4(n⋅l)(n⋅v)` is canceled in the further process of the calculation, right?~

Sry for asking this question but I just want to clarify some formal aspects of the shading implementation of `three.js`. 😇

[Reference](https://graphicrants.blogspot.de/2013/08/specular-brdf-reference.html)

### CODE REVIEW

**Comment by Mugen87** [comment]
Any yes, `G_GGX_SmithCorrelated()`  is actually used but this question bothers me a bit.

**Comment by WestLangley** [comment]
The comment specifies the quantity the function is computing.

**Comment by Mugen87** [comment]
I've read the code with this in mind:
image

The implementation in `G_GGX_Smith()` is of course correct. I'm just confused about the comment. I would expected the mentioned one or just `geometry term = G(l)⋅G(v)`. This is actually better because it maps nicer to the formal definition. Please correct me if i overlook something.

**Comment by Mugen87** [comment]
I think the implementation would be more clear when we explain why we are doing this in `G_GGX_Smith`:
```
return 1.0 / ( gl * gv );
```
and not
```
return ( 4 * dotNL * dotNV ) / ( gl * gv );
```

**Comment by bhouston** [comment]
The comment is wrong, but not in the way you have fixed it.

Just to be clear, the equation and the glsl code is from the end of this page where there is the "Optimize" heading -- I think you stopped reading the referenced blog post too soon:

http://graphicrants.blogspot.ca/2013/08/specular-brdf-reference.html

The equation isn't just "geometry term", you are correct there.  The equation is right though, but it is the Geometry term with the BRDF denominator as per the text of the blog post.

**Comment by bhouston** [comment]
Just to be clear, it was my fault that I wrote the wrong comment.  Sorry about that.

**Comment by WestLangley** [comment]
I would edit the comment like so:
```glsl
// geometry term (normalized) = G(l)⋅G(v) / 4(n⋅l)(n⋅v)
```

**Comment by Mugen87** [comment]
>  I think you stopped reading the referenced blog post too soon.

Yep! 😅 

> The equation isn't just "geometry term", you are correct there. The equation is right though, but it is the Geometry term with the BRDF denominator as per the text of the blog post.

This was exactly the answer i was looking for 😊! Many thanks for your explanation.

@WestLangley Okay. I'll also add the hash of this PR. New readers should then find all necessary information.

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
