### PR TITLE
SVGLoader: Fix parsing of flags in compressed definitions.

### LINKED ISSUE #20608: SVGLoader - Incorrect/mangled path rendering
**Describe the bug**

Hello, it appears that with SVG's which have been exported from Adobe XD, SVGLoader fails to convert the paths reliably.

This might be the same issue as #18560

Alternatively, is there a tool/script which can convert/re-export the SVG paths into a format Three can parse?

***Live example***
Here is how the SVG renders as a browser element
* [jsfiddle](https://jsfiddle.net/16udgkwq/1/)

**Screenshots**

Here is how the SVG appears when imported into the ThreeJS editor (https://threejs.org/editor/)

image

**Platform:**

 - Device: [Desktop,]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r120.1]

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #20608.

**Description**

`SVGLoader` assumes sequences of floats like `7.51,7.51,0,0,1,1.311,3.879` are separated by specific values (signs, points, comma or whitespaces). The problem is that a mangled version like `7.51 7.51 0 011.311 3.879` is impossible to parse without knowing the semantics of the respective command. 

For example `011.311` is actually `0,1,1.311`. However, without knowing that the first and second numbers in that string are SVG flags, you will end up with `0,11.311` (because you can't detect whether the `1` is part of the subsequent number or not).

With this PR `parseFloats()` is enhanced with two parameters that allow the caller to specify optional semantics about the given definition. An additional array defines the indices of flags (meaning where flags occur in a definition) and the total length of a single definition. This should fix the tooth SVG (which is now a test asset of `webgl_loader_svg`) and the SVG from https://discourse.threejs.org/t/svgloader-parse-errors/24537.

@karimbeyrouti Do you mind testing this PR?

### CODE REVIEW

**Comment by Mugen87** [comment]
@karimbeyrouti Do you mind testing this PR?

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev1/examples/webgl_loader_svg.html

**Comment by yomboprime** [comment]
I've noticed that the parse time now is much bigger (the recent ```createShapes``` PR did had much lower impact) and that the last example, "Zero Radius" doesn't show up.

**Comment by yomboprime** [comment]
Definitely I would implement this in a separated function and only call it where it is needed to parse mangled floats, for performance reasons.

**Comment by Mugen87** [comment]
Should be fixed now. I've missed to update the parser's state.

**Review by yomboprime — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by karimbeyrouti** [comment]
Pointed our code at the dev branch, and found some more path issues, mentioned here:

https://github.com/mrdoob/three.js/issues/20608#issuecomment-807769167

Should I raise a new issue ?

**Comment by Mugen87** [comment]
I'm already looking at them.

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/issues/20608#issuecomment-808050078

**Pull request merged**
