### PR TITLE
chmod 755 to 644 of 'examples/webvr_vive.html'

### PR DESCRIPTION
**Pull request by pjhjohn**
Found this while exploring file trees. I didn't took a serious look at other files, but seems pretty sure this file should be in mode 644

How about these following files:
```
-rwxr-xr-x ./examples/models/3mf/cube_gears.3mf
-rwxr-xr-x ./examples/models/collada/pump/pump.dae
-rwxr-xr-x ./examples/models/collada/pump/pump_body.jpg
-rwxr-xr-x ./examples/models/collada/pump/pump_gears.jpg
-rwxr-xr-x ./examples/models/collada/pump/pump_metalreflect.jpg
-rwxr-xr-x ./examples/models/platform/platform.jpg

-rwxr-xr-x ./test/unit/unittests_editor.html

-rwxr-xr-x ./utils/converters/fbx/LICENSE
-rwxr-xr-x ./utils/converters/fbx/README.md
-rwxr-xr-x ./utils/exporters/max/annotate/README.md
-rwxr-xr-x ./utils/exporters/maya/README.md

-rwxr-xr-x ./utils/exporters/max/annotate/annotate.py
-rwxr-xr-x ./utils/converters/fbx/convert_to_threejs.py
-rwxr-xr-x ./utils/converters/msgpack/json2msgpack.py
```

Also executable candidates are follows:
```
-rwxr-xr-x ./editor/examples/arkanoid.app.json
-rwxr-xr-x ./editor/examples/camera.app.json
-rwxr-xr-x ./editor/examples/particles.app.json
-rwxr-xr-x ./editor/examples/pong.app.json
-rwxr-xr-x ./examples/fonts/droid/droid_sans_bold.typeface.json
-rwxr-xr-x ./examples/fonts/droid/droid_sans_mono_regular.typeface.json
-rwxr-xr-x ./examples/fonts/droid/droid_sans_regular.typeface.json
-rwxr-xr-x ./examples/fonts/droid/droid_serif_bold.typeface.json
-rwxr-xr-x ./examples/fonts/droid/droid_serif_regular.typeface.json
-rwxr-xr-x ./examples/fonts/gentilis_bold.typeface.json
-rwxr-xr-x ./examples/fonts/gentilis_regular.typeface.json
-rwxr-xr-x ./examples/fonts/helvetiker_bold.typeface.json
-rwxr-xr-x ./examples/fonts/helvetiker_regular.typeface.json
-rwxr-xr-x ./examples/fonts/optimer_bold.typeface.json
-rwxr-xr-x ./examples/fonts/optimer_regular.typeface.json
-rwxr-xr-x ./editor/js/Command.js
-rwxr-xr-x ./editor/js/Sidebar.History.js
-rwxr-xr-x ./editor/js/commands/AddObjectCommand.js
-rwxr-xr-x ./editor/js/commands/AddScriptCommand.js
-rwxr-xr-x ./editor/js/commands/MoveObjectCommand.js
-rwxr-xr-x ./editor/js/commands/MultiCmdsCommand.js
-rwxr-xr-x ./editor/js/commands/RemoveObjectCommand.js
-rwxr-xr-x ./editor/js/commands/RemoveScriptCommand.js
-rwxr-xr-x ./editor/js/commands/SetColorCommand.js
-rwxr-xr-x ./editor/js/commands/SetGeometryCommand.js
-rwxr-xr-x ./editor/js/commands/SetGeometryValueCommand.js
-rwxr-xr-x ./editor/js/commands/SetMaterialColorCommand.js
-rwxr-xr-x ./editor/js/commands/SetMaterialCommand.js
-rwxr-xr-x ./editor/js/commands/SetMaterialMapCommand.js
-rwxr-xr-x ./editor/js/commands/SetMaterialValueCommand.js
-rwxr-xr-x ./editor/js/commands/SetPositionCommand.js
-rwxr-xr-x ./editor/js/commands/SetRotationCommand.js
-rwxr-xr-x ./editor/js/commands/SetScaleCommand.js
-rwxr-xr-x ./editor/js/commands/SetSceneCommand.js
-rwxr-xr-x ./editor/js/commands/SetScriptValueCommand.js
-rwxr-xr-x ./editor/js/commands/SetUuidCommand.js
-rwxr-xr-x ./editor/js/commands/SetValueCommand.js
-rwxr-xr-x ./examples/js/controls/VRControls.js
-rwxr-xr-x ./examples/js/libs/dat.gui.min.js
-rwxr-xr-x ./examples/js/loaders/ctm/CTMLoader.js
-rwxr-xr-x ./examples/js/loaders/ctm/ctm.js
-rwxr-xr-x ./examples/js/loaders/deprecated/gltf/glTF-parser.js
-rwxr-xr-x ./examples/js/vr/WebVR.js
-rwxr-xr-x ./test/unit/editor/CommonUtilities.js
-rwxr-xr-x ./test/unit/editor/TestAddObjectCommandAndRemoveObjectCommand.js
-rwxr-xr-x ./test/unit/editor/TestAddScriptCommand.js
-rwxr-xr-x ./test/unit/editor/TestMoveObjectCommand.js
-rwxr-xr-x ./test/unit/editor/TestNestedDoUndoRedo.js
-rwxr-xr-x ./test/unit/editor/TestRemoveScriptCommand.js
-rwxr-xr-x ./test/unit/editor/TestSerialization.js
-rwxr-xr-x ./test/unit/editor/TestSetColorCommand.js
-rwxr-xr-x ./test/unit/editor/TestSetPositionCommand.js
-rwxr-xr-x ./test/unit/editor/TestSetRotationCommand.js
-rwxr-xr-x ./test/unit/editor/TestSetScaleCommand.js
-rwxr-xr-x ./test/unit/editor/TestSetScriptValueCommand.js
-rwxr-xr-x ./test/unit/editor/TestSetUuidCommand.js
-rwxr-xr-x ./test/unit/editor/TestSetValueCommand.js
-rwxr-xr-x ./utils/exporters/maya/scripts/ThreeJsExportScript.mel
```

Seems following files are right to be as executable:
```
-rwxr-xr-x ./examples/models/vrml/house.wrl
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/exporter.py
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/setup_test_env.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_buffer_geometry.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_animation.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_bump_spec_maps.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_diffuse_map.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_influences.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_lambert_material.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_light_map.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_mix_colors.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_morph_targets.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_normal_map.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_normals.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_phong_material.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_vertex_colors.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_geometry_wireframe.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_area_light.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_buffer_geometry.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_buffer_geometry_noembed.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_children.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_directional_light.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_hemi_light.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_instancing.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_maps.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_no_embed.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_orthographic.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_perspective.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_point_light.bash
-rwxr-xr-x ./utils/exporters/blender/tests/scripts/test_scene_spot_light.bash
-rwxr-xr-x ./utils/servers/nodejs_server.sh
```

### CODE REVIEW

**Comment by mrdoob** [comment]
These changes look good to me! 👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by pjhjohn** [comment]
Thanks for the quick response and merge!!
@mrdoob It could be my lack of English experience, but could you tell me which of the followings is the meaning of your first comment? 
- "This is fine for current modification"
- "It will be good if you also modify file modes in `How about these following files`"
- "It will be good if you also cover file modes in `Also executable candidates are follows`"

**Comment by mrdoob** [comment]
> - "It will be good if you also modify file modes in `How about these following files`"

👍

> - "It will be good if you also cover file modes in `Also executable candidates are follows`"

👍

**Pull request merged**
