### PR TITLE
FBXLoader support rotated pivots

### PR DESCRIPTION
**Pull request by looeee**
#11963 added support for pivots that have been translated. 

This adds supports for rotated pivots as well

### CODE REVIEW

**Comment by mrdoob** [comment]
Moar conflicts 😇

**Comment by looeee** [comment]
Fixed!

**Comment by mrdoob** [comment]
Thanks!

**Comment by nNightKil** [comment]
I want to ask if it's a problem that when I use geometry.translate(x, y, z) to transform the geometry, the pre rotation of the geometry leads to split the geometry. just like the following picture. It happen in FBXLoader and I can't get the original rotation matrix so that I can't fix it outside the loader.
qgne v ji5p5x 1b 7dp

The result for OBJLoader:
rm7hjaiqq n zk e0wxny3

**Pull request merged**
