### PR TITLE
SW: Add secure headers and clean up

### LINKED ISSUE #24212: Editor: Video renderer no longer available in Chrome
**Describe the bug**

The editor's video renderer [relies on a global `SharedArrayBuffer` constructor.](https://github.com/mrdoob/three.js/commit/71ffae30b3c75407d87696f726392215885dd8f9) Previously, this was [compatible with Chrome and not Firefox](https://github.com/mrdoob/three.js/issues/21603#issuecomment-814956064).

However [API changes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes#api_changes) have made this condition fail in Chrome too without certain headers present. AFAIK, the video renderer is not visible in any modern browser.

**To Reproduce**

In Chrome (currently v102.0.5005.61), run `'SharedArrayBuffer' in window`. It will evaluate to `false`, and the video renderer UI will not appear on https://threejs.org/editor

**Expected behavior**

The video renderer will be visible and functional in the editor on Chrome at least. I have to read more deeply about the new security restrictions, but hopefully this is an easy fix.

**Platform:**

 - Device: 2018 MacBook Pro
 - OS: MacOS 11.6
 - Browser: Chrome 102.0.5005.61
 - Three.js version: r141

### PR DESCRIPTION
**Pull request by LeviPesin**
Fixes https://github.com/mrdoob/three.js/issues/24212

**Description**

Add the required secure headers to the editor's service worker and clean up it.

@mattrossman Please confirm this works.

### CODE REVIEW

**Comment by LeviPesin** [comment]
Should be fixed now.

**Comment by LeviPesin** [comment]
It seems that unpkg does not provide CORP header, so we cannot use `COEP: require-corp` and should use the new `COEP: credentialless`.

**Comment by mattrossman** [comment]
In my case https://github.com/mattrossman/three.js/commit/bc818a752ae2e3ad13adceaa142608c7c9f56de0 I had to copy the two libs (ffmpeg.wasm and es-module-shims) from unpkg locally. [Working demo](https://rawcdn.githack.com/mattrossman/three.js/bc818a752ae2e3ad13adceaa142608c7c9f56de0/editor/index.html).

**Comment by LeviPesin** [comment]
I think @mrdoob should decide should we keep these libs locally, investigate ways to enable the SW to work with cross-origin requests, or just use a non-SharedArrayBuffer version.

**Comment by mrdoob** [comment]
Is the non-SharedArrayBuffer version 10x slower or something? 🤔

**Comment by LeviPesin** [comment]
I think it is exactly number-of-coresX slower, because SharedArrayBuffer allows multithreading. I think we can actually keep the libs like we do with the other libs?

**Comment by mrdoob** [comment]
Alright, lets host the libraries then 👍

**Comment by LeviPesin** [comment]
Done.

**Comment by LeviPesin** [comment]
Is there something preventing merging this PR?

**Comment by LeviPesin** [comment]
@mrdoob Can this PR be merged, please?

**Comment by LeviPesin** [comment]
@mrdoob @Mugen87 Something preventing the merge?

**Comment by mrdoob** [comment]
Sorry for the delay!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
