### PR TITLE
Update to FileLoader.js as per Richtr 

### PR DESCRIPTION
**Pull request by kkruups**
As per @richtr simplified code in switch-case for ArrayBuffer and added comments you requested.

### CODE REVIEW

**Comment by mrdoob** [comment]
The `PDBLoader` comments look good, but do you mind doing a different Pull Request for those?

**Comment by kkruups** [comment]
@mrdoob ,

Understood will do.

BR/KK

**Comment by Mugen87** [comment]
TBH, I'm not a fan of comprehensive documentation within the code because it has a negative impact on the readability.

@kkruups Instead, could you enhance the documentation page of PDBLoader with further information?

see https://threejs.org/docs/index.html#examples/loaders/PDBLoader

**Comment by richtr** [comment]
@kkruups I would suggest that you cherry-pick commit `d1631845d290aaa97a8326c49f87a53e1c28ece5` on to the original PR here: https://github.com/mrdoob/three.js/pull/12050.

So from your command-line terminal:

```
git checkout patch-1
git cherry-pick d1631845d290aaa97a8326c49f87a53e1c28ece5
git push origin patch-1
```

Then we should be able to merge https://github.com/mrdoob/three.js/pull/12050 and it will include all the changes requested.

**Comment by mrdoob** [comment]
Hmm, I'll try to cherry pick that commit directly.

**Comment by mrdoob** [comment]
Done! https://github.com/mrdoob/three.js/commit/22b9214e95737e195dc77d922146d81728d7442e

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by kkruups** [comment]
Thanks guys, understood on PDBLoader comments will do as soon as I get a chance.

BR/KK

**Pull request closed without merging**
