### PR TITLE
remove Three.legacy.js

### PR DESCRIPTION
**Pull request by gero3**
This seperates Three.legacy.js. This makes it easier to use include or remove parts from this file. 
This adds a single folder src/_legacy which contains all legacy code.

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, I've actually liked the idea to have everything in one file...

**Comment by gero3** [comment]
It makes the dependencies clearer and allows us to easily add or remove new parts to legacy. It also still is [the lagacy file](https://github.com/gero3/three.js/blob/legacyCleanup/src/_legacy/Legacy.js) that adds all dependencies to the [three.js main file](https://github.com/gero3/three.js/blob/legacyCleanup/src/Three.js#L162). It also makes tree shaking  possible in the legacy file. Before when you added the legacy file, nearly the complete library would be added.

**Comment by Mugen87** [comment]
I see. The amount of new files is just a bit overwhelming...

**Comment by gero3** [comment]
I understand. 
But this also shows that there is no reviews done on this file. Because there are 35 types and 45 types get extra properties or methods in the legacy file.

**Comment by gero3** [comment]
@Mugen87 Would it be better if I separate every file in a different commit and create a new PR ??

Or is there no interest at all to change this??

**Comment by Mugen87** [comment]
> Would it be better if I separate every file in a different commit and create a new PR ??

I think that's not necessary. Let's wait what @mrdoob thinks about this change.

**Comment by Mugen87** [comment]
Closing for now. We can reopen if @mrdoob prefers this approach over the current single-file approach.

**Comment by mrdoob** [comment]
> This makes it easier to use include or remove parts from this file.

Hmm, splitting the file seems like more things for the user to think about?

The original idea was that the user should not have to include the file at all when their app had been successfully ported to the last version.

But now we have a file that keeps growing but I don't know when to get rid of... 😕

**Pull request closed without merging**
