### PR TITLE
Subsurface lighting example

### PR DESCRIPTION
**Pull request by wizgrav**
playing with light is fun

### CODE REVIEW

**Comment by donmccurdy** [comment]
Demo: https://rawcdn.githack.com/wizgrav/three.js/dev/examples/webgl_subsurface_lighting.html

**Comment by WestLangley** [comment]
We already have this: https://threejs.org/examples/webgl_materials_translucency.html

I am reluctant to support examples that inject non PBR-based code into the PBR materials.

**Comment by wizgrav** [comment]
@WestLangley the surface scattering itself was just to highlight the concept. You can think about it as a king of procedural light cookie. There's no similar example and it basically highlights cases where traditional shadow mapping completely breaks. It's not something that should go in core obviously, just food for thought

**Comment by Mugen87** [comment]
> I am reluctant to support examples that inject non PBR-based code into the PBR materials.

Agreed. Even if the PR is not merged, I'd like to promote the [forum](https://discourse.threejs.org/) as an excellent place for sharing such interesting work. Topics in the `Resource` category often demonstrate similar features/enhancements for `three.js`.

**Pull request closed without merging**
