### PR TITLE
DragControls: Add support for dragging a group object.

### PR DESCRIPTION
**Pull request by Mugen87**
This PR adds a small enhancement to `DragControls`. It allows users to drag a group instead of the individual 3D objects. I've seen this feature request multiple times in the past and I thought it's a good addition to the controls (e.g. https://discourse.threejs.org/t/dragcontrol-for-a-group-object/12645). 

The idea is to expose the array of draggable objects and introduce a new boolean property that enables the new behavior. I've enhanced `webgl_loader_3mf_materials` to shows this new feature. It's now possible to drag the entire truck and not its individual parts.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev42/examples/webgl_loader_3mf_materials.html

**Comment by mrdoob** [comment]
I think the example is confusing.

What about adding something like "shift+click" to add to the selection in [this example](https://threejs.org/examples/misc_controls_drag.html)?

**Comment by Mugen87** [comment]
> What about adding something like "shift+click" to add to the selection in this example?

You're right, that makes the handling more clear. Let me update the PR...

**Comment by Mugen87** [comment]
Okay, I've enhanced `misc_controls_drag` and refactored my initial code a bit:

https://raw.githack.com/Mugen87/three.js/dev42/examples/misc_controls_drag.html

**Comment by mrdoob** [comment]
I think it's just missing Shift+Click to deselect too. So Shift+Click toggles.

**Comment by Mugen87** [comment]
Done. Also clarified the description at the header.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
