### PR TITLE
WebGLRenderer: Improve integer attribute support.

### LINKED ISSUE #21595: Expand support for GLSL integer attributes
Expanding on the `vertexAttribIPointer` support added in https://github.com/mrdoob/three.js/pull/19019, I would like to propose a new property:

`BufferAttribute.targetType = FloatType` (default)

This property would support values of the existing constants `FloatType` (default) and `IntType`.

This would expand support for integer attributes (beyond the current `int32` and `uint32`) without changing any existing behavior.

The property would ultimately get passed through to `WebGLBindingStates.vertexAttribPointer()` where the code impact is minimal:

```diff
-function vertexAttribPointer( index, size, type, normalized, stride, offset ) {
+function vertexAttribPointer( index, size, type, normalized, stride, offset, targetType ) {

-    if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 ) ) {
+    if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 || targetType == IntType ) ) {

        gl.vertexAttribIPointer( index, size, type, stride, offset );

    } else {

        gl.vertexAttribPointer( index, size, type, normalized, stride, offset );

    }

}
```

Alternatively, this could be a boolean attribute such as `BufferAttribute.toIntegers = true`, as it looks like WebGL only supports `vertexAttribPointer` (float) and `vertexAttribIPointer` (int) – not `vertexAttribLPointer` (double).

Apologies if I'm missing anything obvious. Thank you!

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #21595

**Description**

The current implementation of integer attributes only supports `Int32BufferAttribute` and `Uint32BufferAttribute`  which maps to `gl.INT` and `gl.UNSIGNED_INT`. However, `gl.BYTE`, `gl.UNSIGNED_BYTE`, `gl.SHORT` and `gl.UNSIGNED_SHORT` are also valid data types. 

The respective buffer attribute classes are `Int8BufferAttribute`, `Uint8BufferAttribute`, `Int16BufferAttribute` and `Uint16BufferAttribute`. Since these classes are also use for float attributes, it's not possible to use the class or data type to detect whether the user wants  float or integer data. A new flag `integer` is added to make this possible. The default `false` means the data are interpreted as floats. If set to `true`, the renderer assumes an integer attribute and then uses `gl.vertexAttribIPointer()`.

### CODE REVIEW

**Comment by takahirox** [comment]
1. Shouldn't `InterleavedBuffer` have `.integer`, too?
2. Shouldn't `.integer` be serialized?

**Comment by gkjohnson** [comment]
The `copy` and `clone` functions should be aware of it, as well, and it should be available on `InstancedBufferAttribute`.

I think I would expect this to be on `BufferAttribute` at least for the reasons that @takahirox mentioned but also using the `<TYPE>BufferAttribute` classes is unnecessary in a lot of cases if you already have the data in a typed array and they're undocumented. I've personally only ever used the `BufferAttribute` class.

I really like this addition, though -- I'll definitely be taking advantage of it.

**Comment by Mugen87** [comment]
The problem is that `integer` could be set by users although it does not make sense for certain data types. E.g. when using `Float32BufferAttribute` setting `integer` to `true` would result in a WebGL error since `gl.FLOAT` is not supported by `vertexAttribIPointer()`. This is also true the other way around for `gl.INT`, or `gl.UNSIGNED_INT`. This was the reason for putting the property in specific buffer attribute classes.

But yes, I understand that not everybody uses the `<TYPE>BufferAttribute` classes and other features like copy/serialization would be easier to implement if the property belongs to `BufferAttribute`. 

If @mrdoob is fine with that proposal I move the new property to `BufferAttribute` and honor it `copy()`, `toJSON()` and `BufferGeometryLoader`. And of course add documentation.

I should have mark the PR as a draft PR since I excluded documentation and other things until the API is clear^^.

**Comment by mrdoob** [comment]
@Mugen87

> Since these classes are also use for float attributes, it's not possible to use the class or data type to detect whether the user wants float or integer data.

Hmm... Should these classes be used for float attributes?

**Comment by gkjohnson** [comment]
> Hmm... Should these classes be used for float attributes?

There is value I think to using 8 or 16 byte integer buffers for float values in terms of memory savings, quantized attributes, or custom shader attributes. At the least it saves memory on the CPU and presumably saves memory on the GPU, as well. The [webgl_loader_gltf_compressed](http://localhost:8080/examples/?q=compres#webgl_loader_gltf_compressed) example uses non-normalized UInt16 buffers to halve the amount of data used for the position attribute in the loaded GLTF file, for example.

I personally vote for adding something like `.integer` to `BufferAttribute` (and the other necessary classes) defaulting it to `false` and logging a warning if it is set to `true` when used with a Float32 array. I think it's an understandable, explicit, easy to set addition while retaining a users flexibility over the representation of vertex buffer data.

**Comment by mrdoob** [comment]
> There is value I think to using 8 or 16 byte integer buffers for float values in terms of memory savings, quantized attributes, or custom shader attributes.

How about creating `Float8BufferAttribute` and `Float16BufferAttribute` for these cases?

**Comment by Mugen87** [comment]
I think it's best if we the `<TYPE>BufferAttribute` can be used according to the `type` property of [vertexAttribPointer](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/vertexAttribPointer) and [vertexAttribIPointer](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/vertexAttribIPointer). Simply because integer attributes are advanced features and WebGL developers are usually familiar with what data type is allowed for each WebGL command.

Hence, I suggested to indicated with a new property whether data should be interpreted as integers or not. At first, I wanted to add this property only to the ambiguous types like `Uint8BufferAttribute`. But it seems other want to have the property on `BufferAttribute` level. However, this might have the implication that the property is set in invalid situations e.g. for `Float32BufferAttribute`.

**Comment by WestLangley** [comment]
How about creating the class `IntegerBufferAttribute`, interpreted as integers in the shader. No `normalized` property.

Then, extend that class with `Int8IntegerBufferAttribute`, `UInt8IntegerBufferAttribute`, etc...

**Comment by gkjohnson** [comment]
> How about creating Float8BufferAttribute and Float16BufferAttribute for these cases?

In practice I've never used any of the typed BufferAttribute classes -- I've just never seen the purpose because I typically already have my data in an appropriately typed buffer and in the rare cases I don't it seems more intuitive to just wrap it in a typed array than use those classes. Also because I tend to already have data in an already typed array I often deal with these types of arrays abstractly which means if I _did_ want to use the typed buffer attribute classes it would involve checking the array type before creating the correct BufferAttribute which is needlessly complicated. That's a peek into how I use these things, anyway.

> How about creating the class IntegerBufferAttribute, interpreted as integers in the shader. No normalized property.

Something like an `IntegerBufferAttribute` would be nice and is still explicit but I think enabling support for the other buffer types gets verbose. You'd need an Integer version of InstancedBufferAttributes and InterleavedBufferAttributes and then I'd question why there aren't `UInt8IntegerInstancedBufferAttribute` and other fully typed variants of those, as well.

Overall it just strikes me as more complicated with little benefit compared to a flag on the BufferAttribute classes but perhaps other people find it more clear. Generally I would just like to able to continue handling my typed arrays abstractly without having to type-match a Uint8Array to a Uint8BufferAttribute to get things to work because it feels redundant and I expect I'm not the only one who works / learned that way.

**Comment by donmccurdy** [comment]
> In practice I've never used any of the typed BufferAttribute classes -- I've just never seen the purpose because I typically already have my data in an appropriately typed buffer ...

+1 for this, I really only ever use BufferAttribute and find the subclasses for different data-types a bit redundant. The complexity compounds as we get into interleaved and instanced attributes, I'd rather not sub-class for component types further.

I guess I'm missing something here and in https://github.com/mrdoob/three.js/issues/21595 though, why is it we cannot intepret the data this way?

| array type | normalized | gl type |
|---|----|----|
| u8 | false | int |
| u8 | true | float |
| i8 | false | int |
| i8 | true | float |

A Uint8Array with normalized=false seems clearly integer-like to me, do we need another property here?

**Comment by gkjohnson** [comment]
> I guess I'm missing something here and in https://github.com/mrdoob/three.js/issues/21595 though, why is it we cannot intepret the data this way?
>
> array type | normalized | glsl type
> -- | -- | --
> u8 | false | uint

What happens when gltfpack generates a GLTF with a non-normalized uint8 array for the position attribute? In the shader the position attribute is always (and should be) a floating point vector value.

**Comment by donmccurdy** [comment]
Ahh ok, thanks. It doesn't seem _impossible_ that we could change that, particularly with how the node-based system handles types. But I can see that the shaders become more complex in the current system. At the minimum we'd need to add a conditional cast in the snippet below, and there are likely other places.

https://github.com/mrdoob/three.js/blob/d9346066c46789548f6a4e5896fecbf7c05fb63a/src/renderers/shaders/ShaderChunk/begin_vertex.glsl.js#L1-L3

**Comment by gkjohnson** [comment]
> Casting from int to float before use does not seem impossible or inherently worse than the alternative,

It's definitely not impossible but I think it is inherently worse. There may be performance implications for the cast, however small. Writing shader code will be less convenient, more confusing, and a breaking change. And most importantly maintenance for our internal shaders will be more complicated if we have to add a new flag for every vertex attribute that needs to be a float.

I'm very strongly in favor the `BufferAttribute.integer` field and opposed to the implicit approach for every integer buffer. Overall I also appreciate that it exposes core webgl flexibility and capabilities in a convenient way.

**Comment by donmccurdy** [comment]
If we need the new property that's OK with me. It's this API that I'm concerned about, and that was leading me to look for ways around it:

- new BufferAttribute( Int16Array( ... ) )
- Int16BufferAttribute
- `.integer = true`

I worry it will not be obvious how the third differs from the first two.

**Comment by gkjohnson** [comment]
I can see that - `.integer` could be replaced with something that declares the feature differently and maybe more clearly:

```js
attribute.shaderFormat = THREE.IntType;
attribute.integerUpload = true;
```

But for me the attribute that's most confusing is `new Int16BufferAttribute( [ ... ] )` - the naming might have made it sound like it just took a int16 array previously when all attributes were floats but you're right that it now could sound more like an attribute that declares and uploads to the gpu as an integer attribute.

As I mentioned in https://github.com/mrdoob/three.js/pull/21606#issuecomment-815249612 I've never quite grokked the reasoning for the separate `<Type>BufferAttribute` class definitions. They only seem redundant to me. This is probably not the place to discuss it at length but if it were my decision I would deprecate those classes since I think they're unsustainable in the general case. And here the naming conventions might lead ambiguity.

**Comment by Mugen87** [comment]
> The copy and clone functions should be aware of it, as well

This is now supported.

**Comment by mrdoob** [comment]
> * `attr.gpuFormat = THREE.IntFormat`
> * `attr.uploadAsInteger = true`

I like these two.

Maybe I like the first one better, but what would the format options be?

**Comment by gkjohnson** [comment]
> Maybe I like the first one better, but what would the format options be?

Right now, as far as I can tell, the options would be `THREE.IntType` and `THREE.FloatType` - which probably means the member name should actually be `gpuType` so it lines up with the existing nomenclature:

```js
attrib.gpuType = IntType;

// or

attrib.gpuType = FloatType;
```

I think using an enum here lines up with the other class fields so I think I'm in favor of this, as well. But as mentioned above - even in WebGPU I think the above values would be the only two viable options for the foreseeable future (see [the WGSL vertex input docs](https://www.w3.org/TR/WGSL/#user-defined-inputs-outputs)).

**Comment by mrdoob** [comment]
> This looks good to me. If @mrdoob approves `gpuType`, I'll update the PR by renaming `integer` to `gpuType` with default `FloatType`.

Sounds good to me yep! 👍

**Comment by Mugen87** [comment]
Updated!

**Pull request merged**
