### PR TITLE
Examples: Fix typo in HTML

### PR DESCRIPTION
**Pull request by linbingquan**

### CODE REVIEW

**Comment by Mugen87** [comment]
There are three other example files with the same markup problem: `software_sandbox.html`, `webgl_loader_nodes.html` and `webgl_performance_nodes.html`. It would be good if you fix these too.

**Comment by linbingquan** [comment]
Thanks, here you are. 😄

**Comment by Mugen87** [comment]
Cool, you also thought at the docs! 😉

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
