### PR TITLE
Docs: Added MeshToonMaterial to material browser.

### PR DESCRIPTION
**Pull request by Mugen87**
Related: #15105

Added `MeshToonMaterial` with a 3x1 and 5x1 gradient map to the material browser.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev28/docs/index.html#api/en/materials/MeshToonMaterial

**Comment by WestLangley** [comment]
related: #15105

**Comment by gkjohnson** [comment]
Nice! I'm not seeing that the `alphaMap` option has any affect, though?

**Comment by Mugen87** [comment]
Or you set a value for `alphaTest` :blush:

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
