### PR TITLE
Editor: Video encoding using mp4-h264

### PR DESCRIPTION
**Pull request by kchapelier**
**Description**

Following an earlier [discussion](https://twitter.com/kchplr/status/1358746308949983233) on Twitter, this PR essentially replaces ffmpeg-wasm with mp4-h264. The UI was extended with a select box to let the user choose the level of quality s/he wants. The [parameters](https://github.com/mattdesl/mp4-h264/tree/851b9064e038049908a48cf16141ed2fd737cbdd#:~:text=Creates%20a%20new%20encoder%20interface) associated to those levels of quality are stored in the qualityPresets constant.

This PR also makes so any previously created object url is revoked when a new download is initiated, to prevent any risk of memory leak.

The dependencies were added to ./js/libs/ as importing them from unpkg was sometimes leading to a good second of load time on my end.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/kchapelier/three.js/editor-mp4-h264-experiment/examples/index.html

**Comment by mrdoob** [comment]
Thanks a lot for this! 🙏

I just tested the `Shaders` example and the output quality suffers a bit (mostly the green areas).

ffmpeg.wasm (100MB):
Screen Shot 2021-02-09 at 12 02 58 PM

mp4-h264 very-high (146MB):
Screen Shot 2021-02-09 at 12 02 43 PM

**Comment by kchapelier** [comment]
@Mugen87 Thanks, I did not know it possible to pull a whole web app using rawgithack. That's certainly useful.

@mrdoob I see, I did not expect the veryhigh preset to output something of a worse quality than ffmpeg. I thought the current quality of the ffmpeg-wasm export in the editor was more in the line of something between the medium and the high presets. But to my defense, if the artifacts are mostly in the greens, I can pull my deuteranomaly card... More seriously, while this would explain why ffmpeg-wasm is slower, I still find it surprising and wonder if the issue may be elsewhere.

In this implementation I use drawImage() the WebGL render to a 2d context then use getPixelData() to get the pixel data as an array of RGBA data for mp4-h264 while in the current ffmpeg-wasm implementation the image data is pulled using canvas.toDataUrl() which generate a png image. Maybe this roundabout process somehow produces an image of lower quality ? I would naively expect it to produce an image of the same quality at the very least, but if it turns out this is the issue, properly getting the RGBA data with gl.readPixels() would fix the issue.

Just as a head-up, I probably won't have the time to look into it before this weekend.

**Comment by Mugen87** [comment]
Related: #21173

> properly getting the RGBA data with gl.readPixels() would fix the issue.

I've made similar findings when implementing the RGBM export. It was best to extract the data from a render target via `readRenderTargetPixels()` (which internally uses `gl.readPixels()`) instead of extracting data from a canvas.

**Comment by kchapelier** [comment]
Due to possible patent-related issues the development of the mp4-h264 package was dropped ( see https://twitter.com/mattdesl/status/1360155203543179264 and https://twitter.com/mattdesl/status/1360003074400649216 ), the issue specifically lies in the (unavoidable) distribution of the compiled h264 encoder which may require licensing.

I think it's best to close the PR.

**Comment by mrdoob** [comment]
Oh man. Patents...
Thanks for making the PR though! 🙏

**Pull request closed without merging**
