### PR TITLE
Removed BinaryLoader

### PR DESCRIPTION
**Pull request by looeee**
Companion PR to #14843 - once that is merged, there will be nowhere left that uses the `BinaryLoader`. 
This PR simply removes `BinarlyLoader.js` and all the remaining binary files. 

I'll add a note to the migration guide after this is merged.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
It appears you are not "deprecating" `BinaryLoader`, you are removing it. When deprecated, user's code will still work, albeit with a warning.

**Comment by looeee** [comment]
Deprecation as a CS term means to recommend against the use of something, usually in favour of a newer/better alternative. 

It will still be possible for users to find the loader by downloading old releases, so either term is reasonable here - that is, we are both deprecating (recommending against the use of) the loader and removing it from future releases.

**Comment by mrdoob** [comment]
We should definitely remove this loader.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
>Deprecation is a CS term means to recommend against the use of something

... because it may not be supported in a _future_ release. But it still works.

What you have done is remove it.

**Pull request merged**
