### PR TITLE
Fix unpack bug

### PR DESCRIPTION
**Pull request by WestLangley**
Packing and unpacking should be inverse operations.

/ping @bhouston

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
I think we need to remove this negative from the SAO shader where I compensated for the inverted reconstructed normal:

https://github.com/mrdoob/three.js/blob/1bab8d04baa69453e61e500287d283a70e102f7c/examples/js/shaders/SAOShader.js#L105

**Comment by WestLangley** [comment]
@bhouston That change is part of this PR.

**Comment by bhouston** [comment]
Sweet!  somehow I missed that.  Sorry about that.

**Comment by WestLangley** [comment]
@bhouston No problem. I appreciate your review!

**Pull request merged**
