### PR TITLE
Examples: remove useCapture param from addEventListener calls

### LINKED ISSUE #21100: Examples: remove addEventListener third parameter
**Is your feature request related to a problem? Please describe.**

In examples, you may find event listeners like this:

```js
window.addEventListener( 'resize', onWindowResize, false );
```

The third parameter, the `useCapture` parameter, is already false by default.
**This confuses newcomers**, also combined with the fact that event capturing is a not so easy concept to grasp.

This pattern comes from around 2012, when you needed to define the third parameter explicitly.

image

Nowadays browsers, already default the parameter to `false`, so it can safely be omitted.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Describe the solution you'd like**

Instead set:

```js
window.addEventListener( 'resize', onWindowResize );
```

I can contribute with some PRs if we decide to go forward with this change.

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: Fixed #21100

**Description**

Remove the third parameter from remaining `addEventListener` calls.

### CODE REVIEW

**Comment by marcofugaro** [comment]
@Mugen87 there are some more event listeners in the `examples/jsm` folder. Should I edit that folder or should I edit the `examples/js` and then run modularize?

**Comment by Mugen87** [comment]
> r should I edit the examples/js and then run modularize?

Please use this approach.

**Comment by mrdoob** [comment]
Thanks!

**Comment by marcofugaro** [comment]
@Mugen87 done in #21125. We should probably replace the modularize script with an unmodularize one, now that there are more scripts in the `jsm` folder than the `js` one.

**Comment by Mugen87** [comment]
see #20527

**Pull request merged**
