### PR TITLE
Vector3: added .setFromMatrix3Column()

### PR DESCRIPTION
**Pull request by WestLangley**
This implementation prevents renaming methods, but I don't feel that strongly about it...

### CODE REVIEW

**Comment by Mugen87** [comment]
I don't think this change is consistent to the rest of the codebase. There is already `applyMatrix3()` and `applyMatrix4()`. Against this backdrop, it's more correct to introduce `setFromMatrix3Column()` and `setFromMatrix4Column()`. Or you have to introduce just `applyMatrix()` and made it work with both types of matrices.

**Comment by looeee** [comment]
> Or you have to introduce just applyMatrix() and make it work with both types of matrices.

That sounds like a good plan to me.

**Comment by WestLangley** [comment]
To avoid renaming methods for now, I reimplemented the PR and just added a new method.

**Comment by WestLangley** [comment]
...and notice that the method nomenclature follows the pattrern: `vector.setFrom( matrix )` -- not `matrix.setVector( vector )`.

**Comment by Mugen87** [comment]
I'm of a fan of this PR right now since it is just half-done. I can't approve it as long as you don't rename `setFromMatrixColumn()` to `setFromMatrixColumn4()`.

**Comment by WestLangley** [comment]
We currently have `setFromMatrixPosition()` and `setFromMatrixScale()` and `setFromMatrixColumn()`.

This PR adds `setFromMatrix3Column()`.

I'll change method names if @mrdoob prefers it. Otherwise, I think what I have done in this PR is fine. It is a subjective decision that should be up to @mrdoob.

**Comment by Mugen87** [comment]
> I'll change method names if @mrdoob prefers it. Otherwise, I think what I have done in this PR is fine. It is a subjective decision that should be up to @mrdoob.

👍

**Comment by mrdoob** [comment]
Yeah, for clarity we probably should do `setFromMatrix(3|4)Position()`, `setFromMatrix(3|4)Scale()` and `setFromMatrix4Column()`.

Merging this for now.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Wait!

@mrdoob Transforms in three.js are always `Matrix4`. I can rename methods if you want, but there never will be `.setFromMatrix3Position()` or `.setFromMatrix3Scale()`.

I can simple rename the existing methods to `.setFromMatrix4Position()`,  `.setFromMatrix4Scale()`, `.setFromMatrix4Column()` if you prefer.

I think it is equally-reasonable to leave it as it is. Your decision.

**Comment by mrdoob** [comment]
> I can simply rename the existing methods to `.setFromMatrix4Position()`,  `.setFromMatrix4Scale()`, `.setFromMatrix4Column()` if you prefer.

That sounds good 👌

**Comment by WestLangley** [comment]
OK. I'll do that.

**Pull request merged**
