### PR TITLE
unprefix Fullscreen API usage in VREffect - for Firefox Nightly + Edge (fixes #8568)

### LINKED ISSUE #8568: Use unprefixed Fullscreen API in `VREffect`
##### Description of the problem 

The vendor prefixes were dropped in Firefox Nightly for the Fullscreen API. And deprecation warnings are now thrown when using `mozRequestFullScreen` instead of `requestFullScreen`.

##### Three.js version

- [x] Dev
- [x] r75
- [x] ...

##### Browser

- [x] Firefox Nightly
- [x] Microsoft Edge (v13)

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by cvan**
also properly handles exiting VR mode w/ the deprecated WebVR API

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, but this fullscreen code will be deprecated soon, right? Isn't Firefox going to adopt `vrdisplaypresentchange`?

**Comment by cvan** [comment]
> Hmm, but this fullscreen code will be deprecated soon, right? Isn't Firefox going to adopt `vrdisplaypresentchange`?

Yes, there are patches under review. FWIW, the Samsung Gear VR uses this API too. The [exiting bit](https://github.com/mrdoob/three.js/pull/8570/files#diff-9241b49ed6cabf364c42e019568a978eR248) is useful, but, yes, that could be certainly done separately from this PR.

**Comment by mrdoob** [comment]
> The [exiting bit](https://github.com/mrdoob/three.js/pull/8570/files#diff-9241b49ed6cabf364c42e019568a978eR248) is useful, but, yes, that could be certainly done separately from this PR.

Agreed!

**Comment by cvan** [comment]
> Hmm, but this fullscreen code will be deprecated soon, right? Isn't Firefox going to adopt `vrdisplaypresentchange`?

Yes, soon (within the coming months). In the meantime, I figured it was worth properly abstracting and handling the old API for Firefox, the Samsung Gear VR browser, and the pre-v1.0 Chromium builds for Mac OS X.

It'll likely be fine to close this PR, fail fast, and carry on, but I wanted to get your input here. When would you be comfortable with deprecating support in three.js for the old WebVR API? FWIW, there are still folks who use the Chromium builds for the Mac OS X 0.5 runtime (and Firefox for WebVR, on both Windows and Mac OS X). The pre-v0.1 Chromium builds absolutely deprecated, but lots of folks don't have the privilege (or curse?) of having a Windows machine.

It also probably goes without saying that, although there are [experimental Chromium builds](https://webvr.info/get-chrome/), the [WebVR Spec](https://github.com/mozvr/webvr-spec) is still in flux.

Let me know your thoughts. Thanks!

**Comment by mrdoob** [comment]
> FWIW, there are still folks who use the Chromium builds for the Mac OS X 0.5 runtime (and Firefox for WebVR, on both Windows and Mac OS X). The pre-v0.1 Chromium builds absolutely deprecated, but lots of folks don't have the privilege (or curse?) of having a Windows machine.

Yep, I'm one of those guys. I use Firefox Nightly 😊

I just want to be careful to not over complicate these files just for the sake of removing temporal browser warnings in the console.

**Comment by cvan** [comment]
> I just want to be careful to not over complicate these files just for the sake of removing temporal browser warnings in the console.

yep, that's totally fair. and I think the only otherwise [interesting change](https://github.com/mrdoob/three.js/pull/8570/files#diff-9241b49ed6cabf364c42e019568a978eR248) I personally don't think is actually worth patching. I'll close. thanks :+1:

**Pull request closed without merging**
