### PR TITLE
Add generic Renderer to Object3D and use it when extending for css renderers

### PR DESCRIPTION
**Pull request by juliendargelos**
See https://github.com/mrdoob/three.js/pull/18508#issuecomment-580466763

### CODE REVIEW

**Comment by elalish** [comment]
@juliendargelos Thank you! Think we can add a quick run of `tsc` to the CI tests to catch this kind of thing in the future?

**Comment by juliendargelos** [comment]
Yes it would be safer

```bash
tsc src/**/*.d.ts examples/jsm/**/*.d.ts
```

**Comment by elalish** [comment]
```Types of property 'onBeforeRender' are incompatible.
    Type '(renderer: CSS2DRenderer, scene: Scene, camera: Camera) => void' is not assignable to type '(renderer: WebGLRenderer, scene: Scene, camera: Camera, geometry: Geometry | BufferGeometry, material: Material, group: Group) => void'.
      Types of parameters 'renderer' and 'renderer' are incompatible.
        Type 'WebGLRenderer' is not assignable to type 'CSS2DRenderer'.
          Types of property 'getSize' are incompatible.
            Type '(target: Vector2) => Vector2' is not assignable to type '() => { width: number; height: number; }'.

241         this[$scene].pivot.add(hotspot);
```

**Comment by elalish** [comment]
@juliendargelos I'm still getting this error after pulling you change; I think the issue is `Vector2` vs `{width, height}`

**Comment by elalish** [comment]
But on the plus side, I can now work around it in my code by casting my `CSS2DObject` to `any`, which I couldn't before, so that's a good step at least!

**Comment by elalish** [comment]
@mrdoob @juliendargelos This may be more serious; I'm now getting a runtime error that leaves CSS2DRenderer unusable: `Uncaught TypeError: Cannot read property 'matrixWorld' of undefined`

**Comment by juliendargelos** [comment]
Does 19ae971 fix the original problem ?

**Comment by mrdoob** [comment]
Thanks!

**Comment by juliendargelos** [comment]
> Does [19ae971](https://github.com/mrdoob/three.js/commit/19ae9719a126bd5291600b9db64a62020700c824) fix the original problem for your code ?

I think this will not work either, and cause type errors when setting `onBefore|AfterRender` callbacks on other ordinary `object3D`.

The simpler and non-breaking solution may just be to set the `renderer` parameter as `unknown` in `CSS2DObject` and `CSS3DObject`:

```typescript
declare class CSS2DObject extends Object3D {
  //...
  onBeforeRender: (renderer: unknown, scene: Scene, camera: Camera) => void;
  onAfterRender: (renderer: unknown, scene: Scene, camera: Camera) => void;
}
```

```typescript
let css2DObject = new CSS2DObject()

css2DObject.onbeforeRender = (renderer: unknown) => {
  let { width, height } = (renderer as CSS2DRenderer).getSize()
}
```

This is not elegant at all, but since rendering callbacks were not implemented on `CSS2|3DObject` until now, this shouldn't cause problem with existing typescript code.

**Pull request merged**
