### PR TITLE
Geometries: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
- Import statements at the top
- Consolidate redundant metadata (authors)
- Formatting

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, the reason the imports are at the top on most of the code base was because the tool that automatically converted it to es6 modules. I feel like there metadata authors should go first but I don't know if that's how people usually do it...?

**Comment by Mugen87** [comment]
Good question. I've just done it like this so the code is consistent with most of the other files in `src`. But changing the PR is no big deal. If you like, i switch the positions of imports and metadata.

**Comment by mrdoob** [comment]
Yeah, let's try with the metadata on top for now.

**Comment by Mugen87** [comment]
Okay, done :blush:

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
