### PR TITLE
SkinnedMesh.bind calculates the skeleton inverses

### PR DESCRIPTION
**Pull request by gregtatum**
It seems like most SkinnedMesh uses are with the loaders, but I'm using them programmatically. It seems like the interface for adding a Skeleton with .bind is awkward and confusing. The matrixWorlds of the mesh and children are automatically updated on .bind, but not the Skeleton's inverses. Typically it seems from the uses that the bones are added as children to the `SkinnedMesh`. To me it makes sense to recalculate the Skeleton inverses when doing the initial `SkinnedMesh.bind` since those matrices are being updated as well.

The current procedure looks like this:

```
skinnedMesh.add( rootBone );
skinnedMesh.bind( skeleton );
skeleton.calculateInverses();
```

Which is error prone for the end user, because there's no obvious reason why you would need to perform calculateInverses as it's not obvious that the bones have all had their matrices secretly updated with a `.updateMatrixWorld( true )`

With this tweak it turns into:

```
skinnedMesh.add( rootBone );
skinnedMesh.bind( skeleton );
```

Which is much cleaner and less error prone. If you pass the bindMatrix manually, then it skips all of this matrix updating for performant code.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sounds good to me!
Do you mind updating the loaders too?

**Comment by TatumCreative** [comment]
Yeah, I'll do that and update the docs with the change too.

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
> The current procedure looks like this

what I did was just placing bones into geometry.bones and then just new THREE.SkinnedMesh (geometry, ...) unless you have specific need to add bones one by one?

**Comment by TatumCreative** [comment]
Well, the problem if I recall is that it uses these weird non-three.js bone objects. The existing logic looks like it was targeting an importer and not actual usage with the three.js objects. 

For example:
```
gbone = this.geometry.bones[ b ];

p = gbone.pos;
q = gbone.rotq;
s = gbone.scl;

bone = new THREE.Bone( this );
bones.push( bone );

bone.name = gbone.name;
bone.position.set( p[ 0 ], p[ 1 ], p[ 2 ] );
bone.quaternion.set( q[ 0 ], q[ 1 ], q[ 2 ], q[ 3 ] );
```

Plus there is this note in there, which I also agree with:

```
// TODO: remove bone creation as there is no reason (other than
// convenience) for THREE.SkinnedMesh to do this.
```

That process is pretty limiting and in my opinion confusing if you want to create a skeleton system dynamically.

I am planning on finishing up this PR, but I've been busy with some other projects.

**Comment by makc** [comment]
true, but 1) arrays of numbers in buffer geometry are no longer 3js objects either, and 2) you can always get 3js bone by skin.getObjectByName (boneName) when you want to move it, so not a real problem.

**Comment by TatumCreative** [comment]
This should handle everything. The only loader that looked to use .bind() was the gltfloader. It was really hard to read because the formatting was way off. I ran it through mrdoob approves to clean it up, and manually went and did a bit more cleanup. Ultimately the only non-style change I did was change the line using .bind do pass in the matrixWorld so it wouldn't recalculate the inverses.

    threeMesh.bind( new THREE.Skeleton( bones, boneInverses, false ), threeMesh.matrixWorld );

Barring any issues, this should be ready to be merged in.

**Comment by mrdoob** [comment]
Hmm... Sorry, but it will be better to leave the gltfloader formatting intact as it's being developed outside this repo. This way we'll be able to spot regressions easily whenever they submit an updated version.

Do you mind reverting the reformatting and only updating the needed code?

**Comment by TatumCreative** [comment]
Okie dokie, it's reverted.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
