### PR TITLE
Prevent tonemapping of scene background texture

### LINKED ISSUE #13066: scene.background affected by tonemapping
images displayed on the background of the canvas using scene.background are affected by environment maps, in my case, they get darken.

I thought the purpose of the scene background was to display an image on the back of the canvas, but without the need of using an  html tag.

In cases like the one below, I would expect the scene background not to be affected in any way by the scene lightning.

screen shot 2018-01-08 at 14 59 59

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #13066.

As discussed in #14827.

### CODE REVIEW

**Comment by WestLangley** [comment]
An alternate solution is to use a custom `ShaderMaterial` for the background plane mesh instead of `MeshBasicMaterial`, but I think this approach is OK.

**Comment by mrdoob** [comment]
> FWIW I've put together a ShaderMaterial version which has the background rendered after the opaque objects in the scene.

That looks good! Would you like to do a PR with it?

**Comment by WestLangley** [comment]
The shader approach by @aardgoose is OK with me, as long as the rendering order is correct.

**Comment by WestLangley** [comment]
Closing in favor of #14856.

**Pull request closed without merging**
