### PR TITLE
fix: Command should be used as a constructor

### PR DESCRIPTION
**Pull request by nicrizzo**
Command is used as a function in History.js: this way six globals are created

### CODE REVIEW

**Comment by GoldenGodXX** [comment]
Holla

**Comment by mrdoob** [comment]
Seems like a more clear code would be to do `Command.editor = editor;` instead?

**Comment by nicrizzo** [comment]
The Command function itself does a
Command.editor = editorRef;
(Command.js, line 22).
If you prefer to assign Command.editor in History.js, it should be possible
to remove the lines 20-24 from Command.js

I thought Command was intended to be a constructor (see prototype usage),
so I added the "new" keyword; I don't like too much the static member
Command.editor, because it prevents more than one editor per page, it's
used by every Command "subclass" with Command.call(this) and it
automagically assigns this.editor without passing it as an argument; then
it forces you to call new History(this) before instancing a Command
subclass, otherwise the commands won't work.
What do you think about rewriting the *Command classes with a extra
"editor" argument?
 Thank you very much

**Comment by mrdoob** [comment]
> What do you think about rewriting the *Command classes with a extra "editor" argument?

I think that would be cleaner indeed. Would you like to do a PR with that change?

**Comment by nicrizzo** [comment]
Sure!

**Comment by nicrizzo** [comment]
I added the new editor argument to the *Command constructors and removed the static member from Command.
It works, but I noticed that the unit tests cannot be executed right now.
Would you mind if I convert the Editor to es6 modules in this PR?

**Comment by mrdoob** [comment]
And stop supporting browser that don't support es6 modules yet...? 🤔
Wouldn't it be better to update the unit tests instead?

**Comment by nicrizzo** [comment]
Sorry, I meant using rollup: now the test suite uses it and the tests are
empty because the Editor classes do not export anything.
Thank you!

**Pull request closed without merging**
