### PR TITLE
TS: Add missing types: is***

### PR DESCRIPTION
**Pull request by yomotsu**
`isXXX` is missing in d.ts.
This PR is to fill them.

Screen Shot 2019-12-29 at 2 51 03 AM

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, can we mark all `is*` properties as read-only? 

Related #18217 .

**Comment by yomotsu** [comment]
Maybe with `true` rather than `boolean`?
```
readonly isBox3 = true;
```

**Comment by yomotsu** [comment]
Thanks for the suggestion.
Regarding it, Which one is preferable?

- `readonly isBox3: boolean`
- `isBox3: true`

Seems some are already `isXXX: true` like
https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.d.ts#L30

But we can respect the actual value in .js file (which is `true`) to set `boolean` as `readonly`?

**Comment by donmccurdy** [comment]
I'd suggest both: `readonly isBox3: true` 👍

**Comment by yomotsu** [comment]
Done it 👍

**Review by Mugen87 — APPROVED** [review]

**Review by donmccurdy — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
