### PR TITLE
Improved webgl_materials_car example

### PR DESCRIPTION
**Pull request by mrdoob**
Before

screen shot 2018-09-04 at 22 52 58

After

screen shot 2018-09-04 at 22 53 12

https://rawgit.com/mrdoob/three.js/dev/examples/webgl_materials_cars.html

### CODE REVIEW

**Comment by mrdoob** [comment]
I believe it can look much better still but it's a start 😊

**Comment by mrdoob** [comment]
Fixed light direction.

screen shot 2018-09-04 at 23 30 46

**Comment by looeee** [comment]
Looks good! 👍

**Comment by looeee** [comment]
A quick question about shadows: is there a reason to prefer 512x512 over 1024x1024? Just performance, or are there more limitations? Because the shadows look kinda jagged now.

Also the car's shadow is cut off when stretching behind it, the shadow camera `far` plane needs to be increased a bit.

**Comment by mrdoob** [comment]
> A quick question about shadows: is there a reason to prefer 512x512 over 1024x1024? Just performance, or are there more limitations? 

Mainly performance yeah...

> Also the car's shadow is cut off when stretching behind it, the shadow camera far plane needs to be increased a bit.

Oh! Feel free to tweak!

**Pull request merged**
