### PR TITLE
GLTFExporter: Merge occlusion, roughness and metalness textures

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #14940 #16325

**Description**

The code in this PR only checks if texture has already been merged (which solves the actual issue in #14940).
Should we add additional parameters as suggested in https://github.com/mrdoob/three.js/issues/14940#issuecomment-423417677?

/cc @fernandojsg @donmccurdy @elalish

### CODE REVIEW

**Comment by mrdoob** [comment]
This will need some tweaks probably but it'll easier to understand when people start using it. Merging.

**Comment by Mugen87** [comment]
Yes, that makes sense!

**Comment by donmccurdy** [comment]
Opened https://github.com/mrdoob/three.js/pull/23385.

**Comment by mrdoob** [comment]
#23463 fixed this.

**Comment by repalash** [comment]
Thanks for your reply. 
@mrdoob In the case where the same aoMap is applied to multiple objects, will it be serialized separately for each object or is this handled somewhere?

**Comment by mrdoob** [comment]
> @mrdoob In the case where the same aoMap is applied to multiple objects, will it be serialized separately for each object or is this handled somewhere?

Oh, I was not aware that could happen. Does that also happen with metalnessMap and/or roughnessMap?

**Comment by repalash** [comment]
> Does that also happen with metalnessMap and/or roughnessMap?

Generally not. aoMaps use uv2, so it's possible to pack occlusion for multiple objects or even the complete scene in a single texture.

**Comment by mrdoob** [comment]
@repalash Fixed #23616

**Pull request merged**
