### PR TITLE
Proposal for new UUID algo

### PR DESCRIPTION
**Pull request by munrocket**
##### Motivation:

* decrease memory consumption #13069
* solve problem with deterministic UUID #19528 #19513 #17949

##### Solution:

This benchmark have two new UUID algos: 
* With own format: int32 date + int32 circular iterator
* With RFC compliant: int64 date + int32 circular iterator + int32 pseudo random (pushed in PR)

Here you can check memory consumption and performance ([github](https://munrocket.github.io/three.js/examples/misc_uv_tests), [codepen](https://codepen.io/munrocket/pen/QWyLKMB)).

First version more efficient in memory and faster in performance but not pass UUID unit test, second is RFC 4122 compliant UUID and not solve a problem with not efficient strings in javascript.

Note that the first version used int32 unix dates in milliseconds, and this is enough to store 50 days, so collisions can appear only after 50 days. Max value of int32 circular iterator is 2147483647 which is pretty big number and can't have a cycle while Data.now() give same results. Also first version can be optimized even more, because int32 + int32 can be packed into one float64 number without strings. If the first version is fit to Three.js this will give memory consumption with strings equal to zero.

### CODE REVIEW

**Comment by munrocket** [comment]
@sunag do you analyze UUID in node shaders somehow? Can you please review this PR also?
Looks like #webgl_sprites_nodes is broken.

**Comment by Mugen87** [comment]
I just want to make clear that a broken CI should never be the reason for changing logic in a project. If there are issues with E2E testing, it's probably better to overthink the entire approach how the CI is currently implemented. Especially since there are other conceptual issue like the fact that the screenshot are part of the version control (which is not something you would normally want).

**Comment by munrocket** [comment]
@Mugen87 apologize.

**Comment by mrdoob** [comment]
> I just want to make clear that a broken CI should never be the reason for changing logic in a project. 

I agree with that.

>  Especially since there are other conceptual issues like the fact that the screenshots are part of the version control (which is not something you would normally want).

I don't think it's too much of a problem actually. @munrocket did a great job at keeping them small (12MB in total) 👌

**Comment by mrdoob** [comment]
Having said that... Yes, the screenshots shouldn't be part of this PR.

**Comment by munrocket** [comment]
Ok and what the reason in 128 bit UUID in RFC format? Maybe to decrease it to 96 bit?
We are not database after all. Also we can't solve #13069 problem without TextDecoder API.

**Comment by munrocket** [comment]
It's much harder to create a special Three.js build for CI, but idea with determinism there will be the same.

**Comment by Mugen87** [comment]
I'm totally fine if a CI-script injects an alternative, deterministic version of `MathUtils.generateUUID()` so it's easier to make the E2E tests work. However, I don't think that having a deterministic algorithm is a reason for changing the default implementation of `MathUtils.generateUUID()`.

**Comment by mrdoob** [comment]
I ended up diving into this puppeteer stuff and managed to get [my suggestion](https://github.com/mrdoob/three.js/pull/19411#issuecomment-636390137) working: #19549

**Comment by mrdoob** [comment]
Regarding this PR... `MathUtils.generateUUID()` should not use deterministic random.
If a user tried to merge 2 different json files there will be conflicts because of duplicated UUIDs.

**Comment by munrocket** [comment]
Ok, if you don't like it I will close it, but this approach was not deterministic, because based on time and PRNG with pure random seed.

**Pull request closed without merging**
