### PR TITLE
Docs fix object clone method documentation

### PR DESCRIPTION
**Pull request by aardgoose**

### CODE REVIEW

**Comment by WestLangley** [comment]
Many thanks for this.

I wonder if instead of using the term _descendants_, the term _children_ would be better -- just for consistency.

_descendants_ is only used in a couple of other doc files, and those instances could be changed, too.

**Comment by GGAlanSmithee** [comment]
Isn't children and descendants two different things though? In my mind children is only the direct children (one level deep) while descendants are n levels deep - children, grandchildren etc. Not a native english speaker though, so might be mistaken.

**Comment by WestLangley** [comment]
@GGAlanSmithee Good point.

**Comment by aardgoose** [comment]
That was my reasoning,  _Descendants_ is more accurate and Object3D already uses that term.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
