### PR TITLE
Update EffectComposer.js to Reset Passes

### PR DESCRIPTION
**Pull request by abogartz**
Update reset method to also reset the passes. Otherwise, the passes array will grow over time and consume GPU time and memory.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Review by Mugen87 — CHANGES_REQUESTED** [review]
Oh, i missed something. Some examples use `.reset()` in `onWindowResize()` like https://threejs.org/examples/webgl_shader_lava.html.

This PR will break all these examples when resizing the window. I guess we should switch to `.setSize()` instead?

**Comment by Mugen87** [comment]
Let's wait that @mrdoob and @WestLangley think about this. IMO, `.setSize()` is the better choice.

**Comment by WestLangley** [comment]
Right. `passes` should not be reset by this method. Maybe the methods should be renamed to make their functionality more obvious.

`setSize()`has problems, because it should use the drawing buffer size, in theory -- but each pass will need to be reset based on either the renderer size or drawing buffer size, depending on what the author intended.

**Comment by abogartz** [comment]
@WestLangley how about adding a `dispose()` method that clears the passes and resets the buffers?

```
function dispose() {
 this.reset();
 this.passes = [];
 // anything else that cleans everything up
}
```

**Comment by WestLangley** [comment]
Why don't you just set `composer.passes = []` in your app?

**Comment by abogartz** [comment]
I'm doing that, but it seems like a hidden problem that I didn't realize that passes were filling up and causing a memory leak. I would choose to wrap code like this in a `dispose` method to centralize this kind of cleanup.

**Comment by WestLangley** [comment]
`reset()` was not intended to do what you think it is.

**Comment by abogartz** [comment]
Maybe I do misunderstand, but we recently found a nasty memory leak when running the composer over and over. This was solved by calling reset on the composer and clearing out the passes array (it was not enough to simply null out the composer object). From what I can tell, this was due to the reset method clearing out the render targets and the read and write buffers. Additionally, we needed to clear the passes array.

**Comment by Mugen87** [comment]
Closing. Like mentioned in https://github.com/mrdoob/three.js/pull/13100#issuecomment-357338555 we need different changes, if any.

**Pull request closed without merging**
