### PR TITLE
VRMLLoader: New implementation

### LINKED ISSUE #8282: Loading textures on vrmlloader
Not really sure whether a bug or not?

I'm loading a vrml with vrmlloader that also has textures in the same ~~file~~ folder, but vrmlloader shows me just a blackscreen? No textures loaded. Any Idea? I'm new in this so excuse me for this question if the way of thinking is wrong...

http://stackoverflow.com/questions/35768609/loading-textures-on-vrml-loader-with-three-js

### PR DESCRIPTION
**Pull request by Mugen87**
The previous `VRMLLoader` has produced many issues in the past because of it's line-by-line parsing approach. Although `VRML` is a very old 3D standard, it has still some significance in various areas like the scientific community. Because of this, I've decided to implement a new `VRMLLoader` from scratch.

The new loader use as lexer + parser built with [chevrotain](https://github.com/SAP/chevrotain) to convert the VRML into a JSON representation. In the next step, the loader builds a `three.js` scene similar to the previous one. So the loader is backwards-compatible but it's necessary to [include the chevrotain lib](https://github.com/mrdoob/three.js/pull/16726/files#diff-6e2badced81358581e1d90bb1e24b7cd) in your code. However, this dependency of `VRMLLoader` will not be noticeable anymore with the JSM version in the future.

Using a lexer/parser approach makes the loader more robust and allows to retain the actual semantic of the VRML tree. Because of this, `VRMLLoader` can now handle more files than before.

The PR also added support for points, lines, textures, texture transforms and computes normals now according to the VRML standard. I've also created a new directory with some VRML test files that I've used to verify the correctness. But you can also see the difference with the official example.

If you closely compare the geometries of the house, you will see a noticeable improvement and a more consistent result compared to other viewers (e.g. Sketchfab).

This PR closes: #8282, #14814, #15725, #15281

### CODE REVIEW

**Comment by mrdoob** [comment]
Awesome!

**Comment by mrdoob** [comment]
Thanks!

**Comment by coderextreme** [comment]
Hi, Is there any hope that the JSON representation could be converted to the up and coming X3D JSON encoding standard? https://www.web3d.org/wiki/index.php/X3D_JSON_Encoding and https://github.com/coderextreme/X3DJSONLD I'm not saying my implementation of JSON -> DOM is the best possible solution (found in .../X3DJSONLD/src/main/node/X3DJSONLD.js),  but it has found a place in X3DOM and X_ITE.  If we had the same JSON representation, there might be more interoperability.  If you want to influence the X3D JSON standard, join the Web3D Consortium or public mailing lists.  For example, we need help with upgrading the JavaScript SAI (Scene Access Interface) API standard.

**Comment by mrdoob** [comment]
I don't think we're going to invest much time on VRML/X3D support ourselves, but we're always welcome to contributions.

**Pull request merged**
