### PR TITLE
Remove arguments to allow optimalisations

### PR DESCRIPTION
**Pull request by gero3**
This cleans up the color construstor to allow optimalisations. 

image

### CODE REVIEW

**Comment by mrdoob** [comment]
I think I'd just make the change:

```javascript
THREE.Color = function ( r, g, b ) {

	if ( g === undefined && b === undefined ) {

		// r is THREE.Color, hex or string
		return this.set( r );

	}

	return this.setRGB( r, g, b );

};
```

**Comment by gero3** [comment]
I changed the constructor based on your argument

**Comment by mrdoob** [comment]
Ops. Tabs got converted to spaces.

**Comment by WestLangley** [comment]
Please update the docs, too, since the signature has changed. Thank you.

**Comment by gero3** [comment]
The docs are also updated.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Thank you, @gero3!

**Pull request merged**
