### PR TITLE
Docs: Consolidate examples section.

### PR DESCRIPTION
**Pull request by Mugen87**
Related #16619.

Ensures a consistent style of the examples section for all doc pages.

### CODE REVIEW

**Comment by Mugen87** [comment]
@munrocket Any ideas why the Travis build fails here? I have not changed any source files...

**Comment by cecilemuller** [comment]
Looks like only one test failed, during installation of dependencies: I'd bet re-running this test suite would fix this.

**Comment by munrocket** [comment]
Yep, just ping travis again please. Sometimes travis fails without any reason.

**Comment by Mugen87** [comment]
> Yep, just ping travis again please

How can I do this?

**Comment by munrocket** [comment]
With force push. Actually I thought that I am turned off this stage for a while.

**Comment by mrdoob** [comment]
> Sometimes travis fails without any reason.

Make your code more robust by adding a layer that fails for no reason. 😁

**Comment by mrdoob** [comment]
@munrocket is it possible to do e2e tests only when files in `src/` or `examples/` change?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@munrocket is it possible to do e2e tests only when files in `src/` or `examples/` change?

**Comment by munrocket** [comment]
Probably we could somehow analyze commit? Never thought about that.
But CircleCI is more robust. Also exist Github CI, I am not try yet. Should I?

**Comment by mrdoob** [comment]
> But CircleCI is more robust. Also exist Github CI, I am not try yet. Should I?

Up to you! Just sharing thoughts.

**Comment by munrocket** [comment]
Github CI should be fairly easy, if it support webgl.

**Pull request merged**
