### PR TITLE
Add regenerator-runtime as a polyfill for async/await

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: https://github.com/mrdoob/three.js/pull/20754#issuecomment-733068567

**Description**
[regenerator-runtime](https://github.com/facebook/regenerator) is also needed to polyfill async/await for IE11. It's a dependency which babel doesn't include by default. More details about this procedure [in this guide](https://babeljs.io/docs/en/babel-plugin-transform-runtime).

I added the library as a poyfill and used the `@rollup/plugin-node-resolve` plugin to import it directly from node_modules.

✅ I tested the new build with the PR #20754 and it fixes the issue with `misc_legacy`.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by DefinitelyMaybe** [comment]
nice! async/await here we come

**Comment by mrdoob** [comment]
Thanks!

**Comment by arikwex** [comment]
Hello all,
I think that this change has introduce a CSP issue to the tune of:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script
```
Looking at [the build since r125](https://raw.githubusercontent.com/mrdoob/three.js/r125/build/three.js), we can see the following:
```
try {
    regeneratorRuntime = runtime;
} catch (accidentalStrictMode) {
    // This module should not be running in strict mode, so the above
    // assignment should always work unless something is misconfigured. Just
    // in case runtime.js accidentally runs in strict mode, we can escape
    // strict mode using a global Function call. This could conceivably fail
    // if a Content Security Policy forbids using Function, but in that case
    // the proper solution is to fix the accidental strict mode problem. If
    // you've misconfigured your bundler to force strict mode and applied a
    // CSP to forbid Function, and you're not willing to fix either of those
    // problems, please detail your unique predicament in a GitHub issue.
    Function("r", "regeneratorRuntime = r")(runtime);
}
```
The problematic line seems to live here (commented it out to verify): https://github.com/mrdoob/three.js/commit/e677e9572de8d61e05bf32b02e9fb684fd2bafea#diff-ae80df62f9f5c7165b96cece03e3ad2dc1e16b90770c9d59683eabc1b529d9eeR280
From the comment in the build about fixing the CSP, it seems like there's no out-of-threejs solution since the `'use strict'` is baked in to the build (unless I'm missing something).

fwiw the [three.module.js build](https://raw.githubusercontent.com/mrdoob/three.js/r125/build/three.module.js) doesn't have this issue.

Does anyone have recommendations of how to move forward with a fix here? Migrating to use the three.module.js is viable (but high effort), and ultimately doesn't solve the core issue with the other build.

**Comment by arikwex** [comment]
If I use `strict: false` for the three.js and three.min.js builds, that does solve my issue. I'm not familiar enough with the implications of making such a change... but these things seems to be competing (use strict vs. regenerator-runtime + CSP).

**Comment by marcofugaro** [comment]
@arikwex it's an issue with babel and your current setup, what tools are you using?

Adding `var regeneratorRuntime;` also before the three.js bundle should fix it.

**Comment by arikwex** [comment]
Thanks for that @marcofugaro. We're using brunch js. Your suggestion to add `var regeneratorRuntime;` does fix this.

**Pull request merged**
