### PR TITLE
`fromBufferGeometry` takes into account indexes

### PR DESCRIPTION
**Pull request by xswordsx**
When you call `computeOffsets` to a BufferGeometry and the geometry gets split `fromBufferGeometry` took into account only the first offset group.

**Comparison shot**
Comparison shot

### CODE REVIEW

**Comment by WestLangley** [comment]
Related issue: #5605

**Comment by xswordsx** [comment]
Although I have touched on that issue, the bigger one here is the fact that `fromBufferGeometry` does not take into account the re-arranging that `computeOffsets` does, mainly the `.offsets / .drawcalls` property.

**Comment by mrdoob** [comment]
I don't think this code is correct... You should be looping across `.drawcalls` first...?
Also, out of curiousity, why are you converting a `BufferGeometry` to `Geometry`?

**Comment by xswordsx** [comment]
I believe I am looping through `.drawcalls` just a bit more effectively than with a `for` loop.
You can have a look at [this snippet](https://gist.github.com/xswordsx/66474df2e2a8a908666b) - it reproduces the problem very well *(it also solves the problem with more than 2 UV layers)*.
As far as the problem that was being tackled with `BufferGeomtry -> Geometry` - I have a geometry in the form of buffers. The geometry also has several UV layers (more than 2), which have their own indexes *(which do not match the ones the geometry uses)*

**Comment by mrdoob** [comment]
> I believe I am looping through `.drawcalls` just a bit more effectively than with a `for` loop.

Maybe it's more effective but I'm having a hard time to understand the logic...

Do you mind sharing the .json file that uses drawcalls?

**Comment by xswordsx** [comment]
The basic idea is that the `requiredOffset` variable is used to index the `offsets / drawcalls` array, starting at the first element.
```javascript
var offset = geometry.drawcalls[ requiredOffset ];
```
When an index of a face we want to add is outside of our current `offset / drawcall`
```javascript
if ( i >= offset.start + offset.count ) {
```
 we move to the next `offset / drawcall`.
```javascript
    requiredOffset ++ ;
    offset = geometry.drawcalls[ requiredOffset ];
```
```
}
```
Thus, we are iterating through the offsets / drawcalls.

In the case that `computeOffsets` has not been called or has produced a single element, we draw as we used to - ignoring the `offset / drawcall` variable.

As for the JSON - I cannot share the model, as I don't have the legal rights to, but the problem can easily be [reproduced](https://gist.githubusercontent.com/xswordsx/66474df2e2a8a908666b/raw/0ce557403667dfeb8795374dbfd1bb5bb88730eb/index.html) with `PlaneBufferGeometry`.

**Comment by mrdoob** [comment]
In open source projects tends to be better to write self explanatory code.
I'll try to see if I can do the same in a way that the code doesn't need to be explained.

Thanks for the reproduction code!

**Comment by mrdoob** [comment]
Implemented. Thanks!

**Pull request closed without merging**
