### PR TITLE
Examples: add webgl rendering regression test.

### PR DESCRIPTION
**Pull request by jchen10**
The initial test framework and first 3 examples added as testcase.

### CODE REVIEW

**Comment by jchen10** [comment]
A test runner for webgl rendering test.

These tests aim to catch webgl rendering regression early. Ideally we need to
run the tests every time before we submit a new PR for review. The tests
compare the rendering result of the new PR again an existing reference
rendering result. Usually we must make sure there is no unexpected mismatch
of rendering result before calling for a review. The reference rendering
result may be either stored in remote repo already, or generated locally.
Typically we generate local reference before making any new change. That will
be the baseline for the later changes. The rendering result is a set of
images taken as snapshots from webgl renderer canvas via the toDataURL API.
There are 2 comparers to decide whether images match. The 'Simple' comparer
strictly compare pixel by pixel. This is mostly used to compare against the
local reference result, as same case on a specific GPU and browser must
produce same images. The other one is the 'Fuzzy' comparer stolen from dEQP.
This one can be used to compare rendering result accross various GPUs and
browsers. But it's less sensitive to catch all potential regressions. The key
point for a testcase is always producing same images. That is to say we must
take snapshot on a fully loaded and fixed scene -- all resource loaded, same
animation time, same camera position, and same canvas size. With helper.js,
we can add a new testcase easily.

How to run:
     1. Run 'php -S localhost:8080'
     2. Visit 'localhost:8080/examples/tests/' in browser
     3. Click the 'Baseline' button to generate reference images locally
     4. Make your changes to THREE.js, and re-build it
     5. Click the 'Compare' button to compare with the baseline
     6. Review the diff images if any

**Comment by jchen10** [comment]
A screen shot of reviewing diff images.
image

@mrdoob Please have a look! If you like the idea, I would further polish it and add more test cases. I have been working on Chromium/ANGLE community. Chromium/ANGLE trybots run millions of tests for each of your changes. This makes you safe and brave to refactor the existing code. I wish THREE can have such good tests as well. As I am a HTML/CSS/Javascript newbie, please be nice in reviewing. Thanks much!

**Comment by looeee** [comment]
I love this! If it works smoothly this would be a great addition. 

Perhaps it could even be automated like we currently do with [lgtm](https://lgtm.com/)?

**Comment by takahirox** [comment]
Nice work.

Can we remove test code from examples, and directly inserting/replacing when running the test instead?

I think one of the purposes of examples is showing how to edit code/use Three.js to users.
Regression test code would be a bit confusing for that purpose.

**Comment by looeee** [comment]
> Run 'php -S localhost:8080'

I notice that you are doing some basic image uploading using php. It would be best to switch this to node.js since I don't think PHP is used anywhere else in the repo - or failing that, at least python.

> Can we remove test code from examples

Taking a quick look through the examples included here, this should be fairly easy in some cases, but will probably be too difficult in others. 
But I agree that having the test code in the examples will not be acceptable since the examples are designed to show people how to use the library. 

Perhaps what we will have to do is take just a few examples - the ones where the test code can be easily injected - and run the tests against these. For instance, any example that will always look the same at a given resolution and given mouse position will be a good candidate, while examples with time based animation or randomness might be harder. 

@jchen10 do you think it would be possible to refactor this so that all you have to do is include `<script src="test/helper.js"></script>` (perhaps _after_ the main example script), without modifying any other code?  Or just run the tests with one line, maybe something like: `runTests( camera, renderer, scene )`?

**Comment by mrdoob** [comment]
I agree when @takahirox. Would be ideal if examples didn't require changes.

**Comment by jchen10** [comment]
Thank you all for the suggestions. I have managed to keep examples unchanged by injecting test script for each example. This can only work with these simple examples for now, just as @looeee mentioned. Please take a look.
@looeee I will figure out the PHP node.js issue later. Thanks!

**Comment by looeee** [comment]
Great, looking forward to seeing the changes. 

One other thing - you're modifying the loading manager to make `loadingManager.isLoading` accessible. This isn't ideal - would it be possible to use the `loadingManager.onLoad` method instead?

**Comment by jchen10** [comment]
When the test script is injected, loadingManager's onStart event could be fired already. So it's hard to decide whether to wait OnLoad then.

**Comment by jchen10** [comment]
@looeee I have switched PHP uploading to Node.js. It was my time to write Node.js app. Don't be scared if there is something stupid. Thanks!

**Comment by looeee** [comment]
@jchen10 great, thanks :) I haven't done much node.js server side stuff myself either, so I'm not really in a position to judge. 

I'd say if it works then it's good enough for now, we can always come back and improve it later if needed. 

Testing this now - a couple of observations:

* The code should probably go in some folder like `test/regression/`, rather than `examples/test`
* The `rendering-test` in package.json should probably use `npm run start` instead of `npm run build`

Also, when I test this, the initial "baseline" images generate fine, but if I make some changes then the "compare" images all 404:

screenshot-localhost-8080-2018-01-04-16-07-04-219

```js
webgl_materials_variations_phong_0.png:1 GET http://localhost:8080/examples/test/images/cmp/webgl_materials_variations_phong_0.png 404 (Not Found)
Image (async)
(anonymous) @ cmp_result.html:40
webgl_materials_variations_phong_1.png:1 GET http://localhost:8080/examples/test/images/cmp/webgl_materials_variations_phong_1.png 404 (Not Found)
Image (async)
(anonymous) @ cmp_result.html:40
webgl_materials_variations_phong_2.png:1 GET http://localhost:8080/examples/test/images/cmp/webgl_materials_variations_phong_2.png 404 (Not Found)
```

**Comment by jchen10** [comment]
@looeee I have tried to verify your problem with EDGE, Firefox, Chrome on Window, Ubuntu, and MacOS, but unable to reproduce it. I improved the PR by adding a server side file write error log. Hopefully it will catch something. Besides, a new simple API `AnimationMixer.resetAllAction` has to be added in this update, as the mixer may have been kicked already before executing test code. So I need to restore it. For the test folder, it is moved to `test/regression`. Running `npm run start` will launch a httpserver, which conflicts with the Node.js server, so it is not used.

**Comment by looeee** [comment]
@jchen10 I've tested again, and the compare images are working correctly
now. I had used `npm run start` last time, perhaps that was the issue.

**Comment by jchen10** [comment]
@looeee Good to know it works for you, thanks!
I have tested it further and made a few small fixes since last update. Now it can work correctly and stably on many browsers and  platforms. Please let me know if any other concern!

**Comment by jchen10** [comment]
Having walked through all existing webgl examples, I roughly  picked and added 40 cases, which are plain to be integrated into the test framework, and can mostly cover three.js rendering code. It takes less than 1 minute to run all these case on my dev machines with Chrome. Seemingly it can be a handy tool for practical use now. @mrdoob @looeee Could you have a look? Thanks!

**Comment by looeee** [comment]
@jchen10 I'm unlikely to have time to check this properly this week. I'm glad to see you are still working on it though, I think this has the potential to be a useful addition to the library, and I will look into it properly as soon as I have time. 

I notice that you are still making changes to `src/animation/AnimationMixer.js` and `src/loaders/LoadingManager.js`. It would be best if you refactored to avoid this.

**Comment by jchen10** [comment]
@looeee Thank you very much for the attention! I worked out a way to avoid these changes as you mentioned. Hopefully you will find time to review this soon.

**Comment by looeee** [comment]
Thinking about this a bit more, the way it's currently set up is good to demonstrate that this is feasible - however it's perhaps not the best way to actually use this. We can't expect people to run regression tests every time they make a change that _might_ effect one of these examples. 

It would be better to set this up so that it takes snapshots every so often (for example, at each new release, every time a PR is submitted, or perhaps daily/weekly), and then set up an alert system that notifies when regression occurs. This way we would be notified if examples break, and it would be simpler to track down when it occurred. 

Currently there are far too many examples to check manually and when they do break sometimes it is not noticed for a while. This could be a good way of catching those errors early. 

First thoughts on how the automation could work:

* Each example has base images captured
* at the next snapshot, the base images are compared to the new images
* if regression has occurred, the example is flagged 
* we check the example manually and if it's OK, new base images are captured to replace the old ones

**Comment by fernandojsg** [comment]
@jchen10 nice job, we really need something like this! Looking through the comments.
I've been working on a similar approach so I'll try to push something so we could keep the discussion about how to handle it, some of the ideas I had in mind and on the same line as the comments by @looeee:
- The test should be available both locally or on a CI server
- Using CI test could run on each submitted PR so we could detect regressions before merging them.
- We should be able to specify the frames we want to compare, instead of just the first N frames, let's say 10, 540, 2130, and the number of frames to run in total.
- There're few things that should be polyfilled, in my case I was polyfilling Math.random, Date.now() and so on, so you can ensure that every run on the tests results on the exact same result.
- I don't think we need to replicate all the init and update code as in the example, but instead inject only the specific needed setup for the test itself.
- It could be nice to include also benchmark values so you could detect regression also in performance not just in rendering.
- I was doing a device capabilities detection on the client side (command line, not the browser) so we could send info to the regression server remotely so we could detect regression on different devices other than just the regression server itself.
- You should be able to record user input and use it to run the test

**Comment by jchen10** [comment]
@fernandojsg, sorry for response slow. I really appreicate you also think we need such tests.  I need not to preach how important test is. Looking at these great projects like AOSP, Chromium, we will know what a critical role test plays for running an open source project successfully. Your ideas are all very good. We need a power test infrastructure. Beside feature tests, we need performance tests as well. More importantly, we need more test cases. But we can't achieve this overnight, there is a fair amount efforts required. Probably we should make a plan for this goal, break down and prioritize tasks. This PR  intended to come up with a barely workable test framework without too much efforts spent. So I tried best to re-use the existing examples as test cases to save time. Ideally we'd bette write new test cases from scratch. After all, examples are for a different purpose as previously mentioned by the reviewers, and we shouldn't twist them with tests. Probably we can iteratively improve this later. To some extent, writing tests is not as cool as adding new fancy features. It's not an eye-catching thing you can advertise. As such, the community should be more supportive on this, as it's really really important!

**Comment by mrdoob** [comment]
Sorry for the late response @jchen10.

Have you considered implementing this using puppeteer?
https://github.com/GoogleChrome/puppeteer

**Comment by jchen10** [comment]
@mrdoob puppeteer looks great. Before using it to implement, may I know more about your ideas on this? For example, are you expecting a fully automotive tool that can be integrated with a CI system? If so, what need to be done for this PR to adapt the CI server? Thanks much for your attention!

**Comment by Mugen87** [comment]
> Before using it to implement, may I know more about your ideas on this? For example, are you expecting a fully automotive tool that can be integrated with a CI system? If so, what need to be done for this PR to adapt the CI server?

There is a new issue (#16941) were these questions can be discussed.

I'm closing this PR for now since a different approach is needed. In any event, many thanks for your work on this topic!

**Pull request closed without merging**
