### PR TITLE
MeshPhysicalMaterial: Added .ior property

### PR DESCRIPTION
**Pull request by WestLangley**
This is appears to be compatible with where the glTF spec is heading, and it allows `MeshPhysicalMaterial` to retain its [0, 1] `reflectivity` property.

/ping @donmccurdy 

~~todo: update docs, ts~~

### CODE REVIEW

**Comment by WestLangley** [comment]
The CI failures have nothing to do with this PR.

**Comment by donmccurdy** [comment]
Thanks, I like this addition! 

Is our `.reflectivity` similar to `.specular` in KHR_materials_specular? If so, could/should the interaction be multiplying derived F0, rather than one property overwriting the other? See [KHR_materials_ior#interaction-with-other-extensions](https://github.com/KhronosGroup/glTF/blob/5883dc7495754a82ef33fb635e1fc7259d472123/extensions/2.0/Khronos/KHR_materials_ior/README.md#interaction-with-other-extensions) and [KHR_materials_specular#interaction-with-other-extensions)](https://github.com/KhronosGroup/glTF/blob/1cd78c6db4fbcd5a67e3b8389399770d99a002f0/extensions/2.0/Khronos/KHR_materials_specular/README.md#interaction-with-other-extensions).

**Comment by WestLangley** [comment]
@donmccurdy Using glTF terminology, and ignoring the optional texture,
```glsl
dielectricSpecularF0 = 0.04 * specularFactor * specularColorFactor;
dielectricSpecularF90 = 1.0 * specularFactor;
```

In three.js, `.reflectivity`, which is normalized to [0, 1], can be varied to effectively change the 0.04 constant to a value in [0, 0.16]. Setting `.ior` is an alternate way of doing the same thing.

`specularFactor`, in [0, 1], is for artistic control, and is used to dampen the specular contribution -- or remove it completely.

Is there anything here that does not seem right to you?

**Comment by donmccurdy** [comment]
Ok, thanks! I'd like to support both KHR_materials_ior and KHR_materials_specular in MeshPhysicalMaterial. But I actually don't have much of a preference whether we adopt their naming. The term IOR is also used in Blender and Houdini's principled shaders, and in Autodesk's Standard Surface, so I think it's likely to be more familiar to artists. Whether it's familiar to most three.js users is another question.

Given that GLTFLoader could easily read the `KHR_materials_ior` value and set `.reflectivity` without this, do you think it is worthwhile to support both? Should our long-term goal be to remove `.reflectivity`?

**Comment by WestLangley** [comment]
My intention was to support `KHR_materials_ior` via this PR. It allows both the loader and the user to set the IOR. It also allows the user to retrieve the IOR via the getter.

`MeshPhysicalMaterial` was designed to have [0, 1] properties. Consequently, _dielectric specular reflectance_ was remapped and named `reflectivity`.

Personally, I think is is beneficial to retain both. Certainly for now.

//

My plan is to add support for `KHR_materials_specular` soon.

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
Ok, sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
