### PR TITLE
BufferAttribute: add convenience methods

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in #18006.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
Sweet. Thanks.

**Comment by mrdoob** [comment]
I thought we were also going to remove `Matrix3.applyToBufferAttribute()` and `Matrix4.applyToBufferAttribute()`? Or is that coming in another PR?

**Comment by WestLangley** [comment]
>Or is that coming in another PR?

Correct. I just haven't gotten to that yet. :-)

**Comment by mrdoob** [comment]
Sounds good! Thanks! 😊

**Comment by WestLangley** [comment]
This PR requires a new build.

**Comment by Mugen87** [comment]
5226b374b9ff527bbe6885116a91ec2e1ad653bc

**Pull request merged**
