### PR TITLE
Remove redundant loop from dispatchEvent

### PR DESCRIPTION
**Pull request by agostbiro**
The 'dispatchEvent' method of 'THREE.EventDispatcher' ran two loops
to execute callbacks. The first copied references to callback
functions from the listener array to another array, and then the
second loop would call the callbacks from this second array. This
is completely unnecessary, therefore the second loop was removed
and the callbacks are now accessed from the listener array when
executed.

A random sample of 12 examples seem functional after the patch.

### CODE REVIEW

**Comment by mrdoob** [comment]
The reason this is like this is because one could do:

```javascript
object.addEventListener( 'event', function () {
    object.removeEventListener( 'event' );
} );
```

In that situation the array we're going through just got shortened and we would be skiping the next item.

**Comment by luizfilipe** [comment]
Maybe the fastest approach to duplicate an array would be use `arr.slice(0)` method as we can see [here](http://jsperf.com/new-array-vs-splice-vs-slice/19)

I've only tested on chrome

**Comment by gero3** [comment]
@luizfilipe You can't do that because that is a problem for the garbage collector.

**Comment by abiro** [comment]
My bad, thanks for pointing that out. In this situation, one can count down to avoid issues from mutating the array in the loop:

```
var testArray = [0, 1, 2, 3, 4, 5];

for (var i = testArray.length - 1; 0 <= i; i -= 1)
{
  console.log(testArray[i], i);

  testArray.splice(i, 1);
}
```

I added a commit to the pull request with a for loop that counts down.

(I thought this was dead code from a time when a different data structure was used for event listeners, thats' why I didn't ask first.)

**Comment by abiro** [comment]
Well, if order matters, there is a way without copying the array, but it certainly got too hacky at this point to make it worth, so I'm not advocating this. :)

```
var
  i = 0,
  testArray = [0, 1, 2, 3, 4, 5],

  currentEl;

while (i < testArray.length)
{
  currentEl = testArray[i];

  console.log(currentEl, i);

  testArray.splice(i, 1);

  if (currentEl === testArray[i])
    i += 1;
}
```

Just out of curiosity, @gero3, could you point me to some resources on garbage collection issues with array.slice?

**Comment by luizfilipe** [comment]
I'm little confusing about the @gero3 consideration, but I've looking for a explanation about and I've found [this resource](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) (look for the 3.2 item) that explains something about leaking arguments object in a function, I don't know that is relative to the same purpose with an array like.

**Pull request closed without merging**
