### PR TITLE
Update OrbitControls.html

### PR DESCRIPTION
**Pull request by freez10**
Fixed controls.mouseButtons def example

### CODE REVIEW

**Comment by Mugen87** [comment]
Unfortunately, the change is not correct. See #19330.

**Comment by Mugen87** [comment]
This change does not look correct, see:

https://github.com/mrdoob/three.js/blob/87e441a859d83d18eed751f6a719385b2bba0fd5/examples/jsm/controls/OrbitControls.js#L91

**Comment by mrdoob** [comment]
I guess the confusion comes from here?

https://github.com/mrdoob/three.js/blob/87e441a859d83d18eed751f6a719385b2bba0fd5/src/constants.js#L2

I don't remember adding these constants to `MOUSE`... 🤔

**Comment by mrdoob** [comment]
Here's the PR that added these: https://github.com/mrdoob/three.js/pull/16961

**Pull request closed without merging**
