### PR TITLE
x file loader update

### LINKED ISSUE #12599: directX.x loader bug
i tried loading my model in the new x-loader but it's returning cannot read property name of null

[https://jsfiddle.net/48xkyp1m/](url)

here's the log file:-

three.min.js:173 THREE.WebGLRenderer 88
three.min.js:145 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
get @ three.min.js:145
XLoader.js:1457 Uncaught TypeError: Cannot read property 'name' of null
    at THREE.XLoader.XAnimationObj.make (XLoader.js:1457)
    at THREE.XLoader.animationFinalize_step (XLoader.js:1362)
    at THREE.XLoader.animationFinalize_step (XLoader.js:1373)
    at THREE.XLoader.animationFinalize (XLoader.js:1331)
    at XLoader.js:206

Here's the diectx.x model:
[https://cdn.rawgit.com/marshall-hunts/game-assets/master/monster.x](url)

### PR DESCRIPTION
**Pull request by adrs2002**
fix #12599 unload xfiles.

. Apply structural loading. It corresponds to many X files.
.Separate file of model and animation can be load and bind animation.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@adrs2002 

Can you please explain the reason for the so-called `zFlag` option in the loader? What is the issue it solves?

It appears to set a negative x-scale on the mesh, flip the normals, and set the mesh's material to backside. And it is set to `true`.

/ping @takahirox @Mugen87 also, please

**Comment by adrs2002** [comment]
sorce : https://msdn.microsoft.com/en-us/library/windows/desktop/bb324490(v=vs.85).aspx

named `zFlag`,  solve coordinate key is `z-axis`  As I intended. and As a result of trial and error, by the time we solved the problem, the name ceased to be meaningful.

You are right. this name is wrong. How shall we change it?   
I think that switching to `_changeCoordinate` is still better.

**Comment by WestLangley** [comment]
You did this to mirror your animated model, and you got it working by trial and error?

Is that why `material.side = THREE.BackSide`?

**Comment by Mugen87** [comment]
Wouldn't it be better to rotate the entire scene like in `ColladaLoader`?
https://github.com/mrdoob/three.js/blob/84c0b9fb1726329c001cbfcf93589478026d2d03/examples/js/loaders/ColladaLoader.js#L3433-L3437

**Comment by adrs2002** [comment]
watch this.

mq1
mq2

The settings that can be correctly read are different for each output software. I created this `zflag` to follow the difference.

**Comment by adrs2002** [comment]
I have created ``zflag to transform this difference which seems to be a difference in the coordinate system. It may not be the right way. Is there a good way to do it?

**Pull request merged**
