### PR TITLE
THREE.PointCloud offsets fix

### PR DESCRIPTION
**Pull request by kirilledelman**
Hi Ricardo,
I fixed particle drawing with offsets always starting at 0 index. Looks like it was copy'n'paste typo.

### CODE REVIEW

**Comment by WestLangley** [comment]
Nice find!

It looks like line `THREE.Line` has the same problem (line 2802). Should be:

    var startIndex = offsets[ i ].index;

     _gl.drawArrays( mode, startIndex, offsets[ i ].count );

**Comment by kirilledelman** [comment]
You want to submit that one, or should I?

**Comment by WestLangley** [comment]
@mrdoob can verify it and add it, I think. It appears to be part of a recent commit by him...

Thanks for the "cut-and-past" comment. It encouraged me to search for other instances. : - )

**Comment by mrdoob** [comment]
Uh oh! Nice catch O:)

> You want to submit that one, or should I?

Please, submit the fix for `THREE.Line` if you can too :)

Thanks!

**Pull request merged**
