### PR TITLE
PCDLoader:‌‌ Support parsing other scalar fields.

### PR DESCRIPTION
**Pull request by duzeng**
**Description**

‌‌‌The code for parsing other scalar fields has been added in PCDLoader, such as C2C_absolute_distances and Approx._distances data generated after calculating point cloud distances in CloudCompare.

### CODE REVIEW

**Comment by Mugen87** [comment]
I have the feeling the suggested changes are too use case specific for the loader. 

Are there other tools that export such data next to CloudCompare?

**Comment by duzeng** [comment]
> I have the feeling the suggested changes are too use case specific for `PCDLoader`.
> 
> Are there other tools that export such data next to CloudCompare?

In various formats of point cloud data, it not only includes fields such as x, y, z, rgb, normal_x but may also have additional fields added based on processing needs to represent other states of the points. I believe this requirement is not limited to just CloudCompare.

**Comment by Mugen87** [comment]
Do you mind sharing a sample PCD file for closer investigation?

**Comment by duzeng** [comment]
Of course, it is possible.
[sample-ascii.zip](https://github.com/mrdoob/three.js/files/14589993/sample-ascii.zip)

**Comment by Mugen87** [comment]
Thanks for filing the PR but it seems these changes are too use-case specific. If we receive more related feature requests, we can reconsider the PR. In the meanwhile, it's best to use a custom version of the loader if you require more a fields than in the default set.

**Pull request closed without merging**
