### PR TITLE
BufferGeometryUtils: Add .mergeBufferAttributes().

### PR DESCRIPTION
**Pull request by donmccurdy**
I wanted to suggest this as a partial alternative to #8162 and #9529, as a utility to help with merging geometries. Merging arbitrary BufferGeometries in their entirety has many edge cases, but merging BufferAttributes is simpler. This has been helpful to me while working on merging glTF primitives into a single multi-group geometry (see #11944) rather than separate meshes.

### CODE REVIEW

**Comment by donmccurdy** [comment]
For example, the [BrainStem skinned mesh](https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BrainStem/glTF/BrainStem.gltf) can be reduced from 59 meshes to just 1, referencing multiple materials... I'll open a PR with the GLTFLoader changes later, but wanted to see whether parts of this should be put into a shared utility.

**Comment by mrdoob** [comment]
How do you use it? Do you parse the scene graph and look for objects with the same material type and merge their attributes?

**Comment by donmccurdy** [comment]
Here is how I am using it in GLTFLoader: [work in progress](https://github.com/mrdoob/three.js/commit/ff0b4d89d3bbebea1f4be8169933e8553fadda2b). The main difference versus current `a.merge(b)` is that if you have many geometries to combine, the content of each attribute is only copied once. glTF has a concept of [primitives within meshes](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes), which can be used to separate draw calls e.g. for multi-material meshes.

Parsing the whole scene graph for mergeable things sounds hard, and was not something I was looking at. I also haven't tried to deal with geometries that have mismatched attributes; other than just bailing out early. I could imagine a similar helper in BufferGeometryUtils to merge an array of geometries or whole meshes, maybe being clever about only calling `.addGroup` when needed for a new material... this still requires that the user knows what they're doing — we probably don't want to deal with populating empty UVs if only one of N geometries have them — but in suitable cases could be more helpful and efficient than the `a.merge(b)` approach.

**Comment by donmccurdy** [comment]
Closing in favor of #13241.

**Pull request closed without merging**
