### PR TITLE
Default material shader modifier

### PR DESCRIPTION
**Pull request by fernandojsg**
Many times I've tried to use some of the default materials like MeshPhongMaterial but at the same time I wanted to add some kind of custom transformation, like a simple mesh deformation. To do that I needed to create a completely new shader and copy the shader from MeshPhong, add my custom deformation code and create a new ShaderMaterial.
It's really a pain so I thought It could be useful to add the possibility to include custom code inside the default materials making this changes much easier.

I've added a new material param called `shaderModifier` that is a object with the following parameters:
- `preMainVertex`: This code will be added before the `main()` in the shader code. Typically used to add uniforms declarations or custom functions.
- `preVertex`: It's added just after the `transformed = position;` so you could add your custom code to play with the `transformed` vertex.
- `postVertex`: It's added at the end of the vertex shader.
- `preMainFragment`: Like `preMainVertex`it's added before the `main()` in the fragment shader code.
- `preFragment`: The same as `preVertex` but for fragment shader.
- `postFragment`: The same as `postVertex`but for fragment shader.
- `uniforms`:  Custom uniforms added.

Having this new code we could add a custom vertex shader modifier (distortion) based on a new uniform variable called `time`:

``` javascript
material = new THREE.MeshPhongMaterial( { 
    color: 0xAAAAAA,
    specular: 0xffffff,
    shininess: 10,
    map: DiffuseMap,
    normalMap: NormalMap,
    shaderModifier: {
        preVertex: [
            'float angle = (150.*sin(time-position.y))*0.02;',
            'transformed = vec3(transformed.x * cos(angle) - transformed.z * sin(angle), transformed.y, transformed.x * sin(angle) + transformed.z*cos(angle));',
            'vNormal = vec3( vNormal.x * cos( angle ) - vNormal.z * sin( angle ), vNormal.y, vNormal.x * sin( angle ) + vNormal.z * cos( angle ) );'
         ].join("\n"),
        uniforms: { 
            "time": { type: "f", value: 1.0 }
        },
        preMainVertex: "uniform float time;",
    }
} );
```

Typically uses will require `preVertex` to do actual vertex transformation code on `transformed` point, `preMainVertex` to define the uniform, `uniforms` to access them and `postFragment`to modify the  `gl_FragColor`. 

In the previous example we defined `time` uniform. If we want to access it on the render loop we could just simple use the following line:
`material.shaderModifier.uniforms[ "time" ].value = time;`

I've included also a simple example showing this functionality:
http://fernandojsg.com/lab/js/twist

Twister effect

### CODE REVIEW

**Comment by danielribeiro** [comment]
Wow! This looks great. I wonder if anybody here knows the answer to this question: https://github.com/mrdoob/three.js/pull/7581/files#diff-e24610216374beea052f744c4643869bR86

**Comment by GGAlanSmithee** [comment]
Yeah, it really does look good!

**Comment by fernandojsg** [comment]
@danielribeiro umm I thought I deleted that parameter, as I just copied from another example. I guess it really depends on how the normal maps is stored, but for the one on the example is not necessary.

**Comment by nn4e** [comment]
A few months ago  was dismissed  PR from my with the same functionality (but more dirty implementation)
https://github.com/mrdoob/three.js/pull/6885

Im afraid the same awaits this one

**Comment by mrdoob** [comment]
@nn4e maybe the dirtiness had something to do, the prettier the solution the more chances it has to be merged 😊

**Comment by fernandojsg** [comment]
I just deleted the builds, sorry for that :)

**Comment by bhouston** [comment]
This could be done in an elegant way via @sunag's node based material system?  Basically this would be a customization of the normal parameter.

**Comment by mrdoob** [comment]
API wise... How about something like this instead?

```javascript
var material = new THREE.MeshPhongMaterial( color: 0xAAAAAA,
    specular: 0xffffff,
    shininess: 10,
    map: DiffuseMap,
    normalMap: NormalMap
);
var enhanced = new THREE.EnhancedMaterial( material, {
        uniforms: { 
            "time": { type: "f", value: 1.0 }
        },
        preVertex: [
            'float angle = (150.*sin(time-position.y))*0.02;',
            'transformed = vec3(transformed.x * cos(angle) - transformed.z * sin(angle), transformed.y, transformed.x * sin(angle) + transformed.z*cos(angle));',
            'vNormal = vec3( vNormal.x * cos( angle ) - vNormal.z * sin( angle ), vNormal.y, vNormal.x * sin( angle ) + vNormal.z * cos( angle ) );'
         ].join("\n"),
        preMainVertex: "uniform float time;",
    }
);
```

Actually, something like this would be better I think:

```javascript
var material = new THREE.MeshPhongMaterial().toShaderMaterial();
material.fragmentShader.replace( '%PRE_MAIN_VERTEX%, 'uniform float time;' );
```

**Comment by fernandojsg** [comment]
@mrdoob I like the second approach to convert the default material to a shader material but keeping something similar to the shadermodifier attributes. I belive it would be easier for the newbies than replacing string in their own. And we could keep track of those properties.
For example thinking on the editor, I believe having the properties object you could enable them or modify their values easier.

**Comment by fernandojsg** [comment]
This is an old PR but today I started to play again with this problem and tried @sunag's NodeMaterial. It's a very nice way to inject code using those shortcuts to the standard materials defined in three.js but I see some problems for use it in this kind of simple situations:
* It's code is _big_ and **not part of the core**
* The code of the shaders from the core must be replicated and maintained, so everytime you change the core you must change the library.
* It doesn't seems to allow include of _raw_ expressions, something like a `rawTextNode` where you could write the code in a similar way I described before. Otherwise for simple code like the one in the example we should create several nodes and tweaking them won't be as easy as playing directly with the shader's code.

So I'm not sure what you think but maybe we could have this two approach together? Include something like this proposal in the base core: adding the shorcuts directly on the core and with a simple api where you could inject directly code on those shorcuts. Simple enough to prevent excesive changes on the core, so the users should know what they're doing and which attributes they're modifying.

What do you think?

**Comment by tschw** [comment]
> This is an old PR but today I started to play again with this problem and tried @sunag's NodeMaterial. It's a very nice way to inject code using those shortcuts to the standard materials defined in three.js but I see some problems for use it in this kind of simple situations:
> [...]
> It's code is big and not part of the core 

That.

It's possible to write something like this in-core with a minimum of code.  However, in order for that to happen we'd have to clean up some more (see #8552).

**Comment by fernandojsg** [comment]
Following the discussion on https://github.com/mrdoob/three.js/issues/11475

**Comment by pailhead** [comment]
>It's code is big and not part of the core

sigh

**Pull request closed without merging**
