### PR TITLE
ObjectLoader add support for normal/bump scale + io_three enhancement

### PR DESCRIPTION
**Pull request by mese79**
Hi
I've added support for normal map and bump map scale factor.
Plus minor fix for texturePath initialization.

### CODE REVIEW

**Comment by mrdoob** [comment]
@repsac does the blender part look good to you?

**Comment by repsac** [comment]
Does not follow conventions rest of the constant values have. Should use snake case values instead of camel cased values. 
`+TEXTURE_FOLDER = "texture_folder"`

Scene export should probably be off by default. This the source of the single biggest screw up from users who keep exporting scenes when they intended only to select the exported mesh. This was `True` for r70 but in `dev` was set to `False` because I grew tired of repeating myself.
`+    SCENE: True,`

In `exporter/scene.py` the `texture_folder` value is passed through to `exporter/geometry.py`. As an empty string that value should be fine but it would probably be safe to pad this a bit so we aren't passing `None`, which would traceback during `os.path.join`.
```
# was
texture_folder = self.options.get(constants.TEXTURE_FOLDER)

# safer
texture_folder = self.options.get(constants.TEXTURE_FOLDER, '')
```

**Comment by repsac** [comment]
edit: Should use camel case values instead of snake case values. 

@mese79 lots of good logic improvements overall

**Comment by repsac** [comment]
@mese79 the nitpicking on the camel-case vs snake-case does have some work flow issues that I should explain. From just Blender a user wouldn't notice this or care. But from a perspective of someone like myself it does. Using a custom export wrapper of mine; the `--` arguments are built dynamically from the values in the constants. Example:
```
$ blend2three --src scenes/infile.blend --dst exports/outfile.json --faceMaterials \
--uvs --maps --copyTextures
```

Using this new option would result in something like this
```
$ blend2three --src scenes/infile.blend --dst exports/outfile.json --faceMaterials \
--uvs --maps --copyTextures --texture_folder exports/textures
```

Changing to camel case gives my wrapper syntax consistency 
```
$ blend2three --src scenes/infile.blend --dst exports/outfile.json --faceMaterials \
--uvs --maps --copyTextures --textureFolder exports/textures
```

So there is, at least for myself, a work flow context in which this inconsistency would actually show itself.
Examples of using the constants as arguments can be found in test/scripts
https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/tests/scripts/test_geometry_light_map.bash

**Comment by mese79** [comment]
@repsac You are right about camle case. I haven't considered the command-line options. but generally in python i prefer snake case but usually it's just a matter of developer taste.
@mrdoob Sorry for two different commit in one request. i'm still github noob :D .

**Comment by repsac** [comment]
> generally in python i prefer snake case but usually it's just a matter of developer taste.

Oh yes I do as well for variable and function names (so I understand the initial confusion) but in the case of the values held in the variables/constants it is an exception. Especially considering that some of the those values defined in the constants are passed to `three` in the JSON file and `three` uses camel case. So it is a bit more than just the command-line context. I should have mentioned that as well in my previous comment. Hope everything is clear now.

Thanks for your contributions. They are pretty solid.

**Comment by mrdoob** [comment]
> @mrdoob Sorry for two different commit in one request. i'm still github noob :D .

No worries! Multiple commits in one PR is fine!

**Comment by mrdoob** [comment]
@repsac Looks good now?

**Comment by repsac** [comment]
@mrdoob yup

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
