### PR TITLE
Enable ssl in dev script

### PR DESCRIPTION
**Pull request by DevPika**
**Description**

A quality-of-life addition which makes it easier to start a secure context for WebXR development.

**Usage**
```sh
npm run dev-https
```

### CODE REVIEW

**Comment by Mugen87** [comment]
@mrdoob I'm not in favor of adding even more `npm` scripts. Would it be an option to use SSL by default?

**Comment by DevPika** [comment]
True, there are quite a few scripts already... While I have not encountered them myself, are there any issues with using SSL by default though? Maybe situations where the encryption could get in the way while testing locally? Or maybe because of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) security warnings?

**Comment by mrdoob** [comment]
Yeah, I think we can just add ` --ssl` to the `dev` script instead.

**Comment by mrdoob** [comment]
@DevPika

> True, there are quite a few scripts already... While I have not encountered them myself, are there any issues with using SSL by default though? Maybe situations where the encryption could get in the way while testing locally? Or maybe because of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) security warnings?

There's is only one way to know 😉

**Comment by DevPika** [comment]
> @DevPika
> 
> > True, there are quite a few scripts already... While I have not encountered them myself, are there any issues with using SSL by default though? Maybe situations where the encryption could get in the way while testing locally? Or maybe because of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) security warnings?
> 
> There's is only one way to know 😉

YOLO 😉

**Pull request merged**
