### PR TITLE
Fat lines example: add support for dashed lines

### PR DESCRIPTION
**Pull request by WestLangley**
There are some artifacts if the lines are sharply curved and thick, and the model in this PR is a particularly-challenging one.

But this is a step in the right direction. Consider it a WIP.   :)

### CODE REVIEW

**Comment by WestLangley** [comment]
Ephemeral test link: https://rawgit.com/westlangley/three.js/dev-dashed/examples/webgl_lines_fat.html

**Comment by mkarnicki** [comment]
@WestLangley I just wanted to let you know you're awesome and your contributions are very much appreciated.

**Comment by mrdoob** [comment]
Awesome!

**Comment by mrdoob** [comment]
Let me know when you want me to merge it.

**Comment by WestLangley** [comment]
We can merge it now. There's no need to throw the baby out with the bathwater. :-)

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
