### PR TITLE
SEA3D minified version

### PR DESCRIPTION
**Pull request by RemusMar**
Many people are interested in this file.
This one is 100% compatible with the current THREE r85 dev.
I will try to keep it up to date.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... What about deleting the other and only updating this one?

**Comment by RemusMar** [comment]
> Hmm... What about deleting the other and only updating this one? 

I'm not aware of any other SEA3D minified version.

**Comment by RemusMar** [comment]
1 file and 108KB to download
vs
5 files and 177 KB to download.

**Comment by mrdoob** [comment]
I just wanted to avoid having to keep two versions.

**Comment by RemusMar** [comment]
> I just wanted to avoid having to maintain two versions.

This is the only minified version in https://github.com/mrdoob/three.js 
Also it's 100% backwards compatible.

**Comment by donmccurdy** [comment]
IMO it would be best not to have any manually minified files in `examples/*`; SEA3D isn't uniquely different from other loaders, so it would be strange for some examples to be available minified and others not, and bad if a new r8X release comes out but the SEA3D minified files are not updated.

Maybe it would be helpful to have minified versions of _everything_ in `examples/*` created somehow, but that would need to be automated and perhaps managed in a separate repo.

**Comment by RemusMar** [comment]
> IMO it would be best not to have any manually minified files in examples/*; 

Honestly, SEA3D is something much more than "examples".
On the other hand,  you always need to MANUALLY update the files before generating the minified version.
So in this case "automated" or "manually" is the same thing.

**Comment by donmccurdy** [comment]
But many things in the "examples" folder are more than examples. :)

By "manual", I mean that when mrdoob generates a new release of three.js, this minified file will not be updated, unlike the minified files in `build/*`. This PR also does not include instructions for other people to update the file. Realistically, that means this minified file is going to become out of date eventually, and people will download it expecting it to have been updated when it hasn't.

IMO the best option here would be to create a repo that pulls these SEA3D files from NPM and builds minified bundle for others to use. Someone has already done [something like this for ColladaLoader](https://github.com/AndrewRayCode/three-collada-loader), although they've manually copied the file and that isn't be necessary. In A-Frame we are using [this code](https://github.com/aframevr/aframe/blob/6306459b2d193d7951e52ffb10bdfb3c10cdbea8/src/lib/three.js#L22-L26) to grab the examples files we need and add them to our minified build.

**Comment by RemusMar** [comment]
> This PR also does not include instructions for other people to update the file.

No needed because 99% of the users don't update files.
They're just looking for the latest versions.
But the main problem with the JS libraries hosted on github.com (and not only):
A relies on B, B relies on C.
The C owner has a great idea, updates C and he brokes the backwards compatibility.
Now the A and B users are stuck with the old C version until the A and B owners update their libraries.
So as general rule: "if you have a serious project it's not a good idea to rely on 3rd party libraries"

> IMO the best option here would be to create a repo that pulls these SEA3D files from NPM and builds a minified bundle for others to use

Presuming someone will update those files one day ...

**Comment by mrdoob** [comment]
> Many people are interested in this file.

Is that in SEA3D forum?

**Comment by donmccurdy** [comment]
> Not needed because 99% of the users don't update files.

Sorry but I think it is needed: the sea3d directory has been edited [many times in the last few months](https://github.com/mrdoob/three.js/commits/dev/examples/js/loaders/sea3d), meaning this file must be updated often to stay up to date. If we expect that to happen, someone other than you needs to be able to quickly and easily update the file.

I am skeptical that a minified file, sitting in a subfolder with no instructions for updating it, is going to be kept up to date.

> Many people are interested in this file.

Many people are also interested in OBJLoader, ColladaLoader, and others. I would be happy with making minified builds of `examples/js/loaders/*` available somehow, but this doesn't seem like the right way to do that. 

@mrdoob if you're open to having a rollup build for the entire loaders directory, I'm glad to look into that, or to open an issue for discussion.

**Comment by mrdoob** [comment]
> but this doesn't seem like the right way to do that.

Agreed.

**Comment by RemusMar** [comment]
>>  Many people are interested in this file.
> Is that in SEA3D forum?

No.
This is a very popular WebGL benchmark:
http://necromanthus.com/Test/html5/testA_disco.html 
And I get a bunch of emails from the THREE.js users.

But if you agree with "this doesn't seem like the right way to do that" let's close this subject.

**Pull request closed without merging**
