### PR TITLE
Handle material indices that are "out of bounds"

### PR DESCRIPTION
**Pull request by ikerr**
Handle material indices that are "out of bounds": either less than 0 or greater than or equal to the number of materials assigned to the object.

### CODE REVIEW

**Comment by mrdoob** [comment]
The description of the PR is confusing looking at what the actual code changes are... 😶

**Comment by mrdoob** [comment]
Do you mind explaining it a bit more?

**Comment by ikerr** [comment]
Hi @mrdoob, the problem that I'm facing is that sometimes our data contains invalid material indices. That is, the `materialIndex` in a `group` is less than 0 or greater than or equal to the number of materials assigned to the object (via `MeshFaceMaterial`).

Ideally I would fix our data, but this is not a trivial problem. I regularly encounter "real-world" FBX models with these "invalid" material indices. Since the material indices are stored in the mesh and the materials are stored on the object, it can be difficult to correct this, especially when the mesh is shared by multiple objects.

This commit simply checks that `groupMaterial` is not null/undefined before trying to use it. Without this, if `group.materialIndex` is invalid, `groupMaterial` is undefined and you get errors when checking that `groupMaterial.visible === true`.

Does that make sense?

**Comment by arose** [comment]
What about adding a warning that there is an invalid `materialIndex` instead of silently ignoring it? Maybe not in the renderer but in the loader?

**Comment by bhouston** [comment]
Yeah, this should be a load time thing.  Having the render handle bad data will increase its complexity a fair bit.

**Comment by WestLangley** [comment]
> Yeah, this should be a load time thing.

Yes -- or checked at mesh-creation time. (Although we do not typically check for user errors.)

In any event, this works:

	mesh = new THREE.Mesh( geometry, undefined );

Perhaps this should too.

	mesh = new THREE.Mesh( geometry, new THREE.MultiMaterial( [ material, undefined ] ) );

**Comment by ikerr** [comment]
Thanks for the feedback. @bhouston I hear what you're saying about error checking adding complexity to the renderer - I'd like to avoid this as well.

At the same time, I think @WestLangley has a point. Right now, we create a default material for a `THREE.Mesh` when one isn't supplied. Should there be a mechanism for doing the same thing with a `group`? That is, should there be a way to *not* specify a material index for a particular `group` and have the renderer use a default material instead?

**Comment by bhouston** [comment]
What we do in Clara.io is we have a single default material (a medium gray) that we use in cases where a material isn't specified by the user.  It is very efficient and easy to do and only requires a single material allocation.  I am okay with what you guys decide to add in ThreeJS.  I prefer to keep things as simple as possible though, although I would suggest staying away from creating material dynamically when users are not creating them themselves or whatever reason.  Another option to do when materials are not supplied is to put an error on the console and do not draw the offending item -- for an SDK,-type library this seems like a more appropriate solution (I like hard errors in an SDK when it is misused), although it isn't the appropriate behavior for a GUI-type editor.  But again, I do not have strong preferences in this area, so whatever you guys decide I am fine.

**Comment by WestLangley** [comment]
> Another option to do when materials are not supplied is to put an error on the console and do not draw the offending item

That solution is fine, too. I do not have a strong opinion one way or the other.

**Comment by mrdoob** [comment]
I see I see. I can't see how `groupMaterial` could be `null`, so how about this instead?

```javascript
if ( groupMaterial !== undefined && groupMaterial.visible === true ) {
```

**Comment by Mugen87** [comment]
The suggestion of @mrdoob was implemented some time ago, see https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L1407

**Pull request closed without merging**
