### PR TITLE
Sky Shader Example Clean Up

### PR DESCRIPTION
**Pull request by WestLangley**
mrdoobapproves formatting, switched to `OrbitControls`, removed animation loop.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

What do you think about adding `requestAnimationFrame` inside the controls directly so the user doesn't have to worry about calling `.update()`?

**Comment by WestLangley** [comment]
It would be nice if we could improve the API. Users almost always get this wrong -- especially since `TrackballControls` is different. Here is a summary.

If there is no animation loop, then only this line is required.

```javascript
controls.addEventListener( 'change', render ); // add this only if there is no animation loop
```

If there is an animation loop, and controls damping or auto-rotation is desired, then this line is required.

```javascript
controls.update(); // required if controls.enableDamping = true, or if controls.autoRotate = true
```

Otherwise, neither pattern is required.

**Comment by mrdoob** [comment]
Yeah... That's too much to know I think... If we added rAF to all the controls there would only be two cases:

1. There is an animation loop. The user doesn't need to do anything.
2. There is animation loop. The user will need to add `controls.addEventListener( 'change', render );`

**Comment by WestLangley** [comment]
And `update()` would no longer need to be exposed.

**Comment by mrdoob** [comment]
Yep!

**Pull request merged**
