### PR TITLE
Add support for passing Vector3 in Matrix4.makeTranslation(v) see #12101

### PR DESCRIPTION
**Pull request by cnspaha**
see #12101

### CODE REVIEW

**Comment by WestLangley** [comment]
Well, there are all these methods, if we want to go down this path. We would also need to update the docs.
```javascript
Matrix4.makeTranslation()
Geometry.translate()
BufferGeometry.translate()
Box2.translate()
Box3.translate()
Plane.translate()
Sphere.translate()
Matrix3.translate()
```
And, then
```javascript
Matrix4.makeScale()
Matrix3.scale()
Geometry.scale()
BufferGeometry.scale()
Matrix4.setPosition()
```

@cnspaha Why are you calling `Matrix4.makeTranslation()`? Can you show your use case?

**Comment by Mugen87** [comment]
I vote against this. Such a change would downgrade the readability of many methods.

**Comment by mrdoob** [comment]
Indeed. Doesn't end up very pretty...

**Comment by mrdoob** [comment]
```js
if ( x.isVector3 ) z = x.z, y = x.y, x = x.x;
```
🤔

**Comment by cnspaha** [comment]
@WestLangley 
Why? Because I want to create a translation matrix? ;)

It is simple, when I for example have a movement described via a vector3 and I want to make a translation matrix out of it, because I am working mainly with matrices I use Matrix4.makeTranslation() to create it and then apply this matrix to my current object matrix. I don't like it to work much with obj.position and obj.rotation.

@mrdoob 
> if ( x.isVector3 ) z = x.z, y = x.y, x = x.x;
yeah that may be better 👍  but since you and @Mugen87 are against it (and I get your point) I think it is rejected either way.

**Comment by WestLangley** [comment]
@cnspaha Are you instantiating a new `Matrix4` and using this method?

**Comment by cnspaha** [comment]
@WestLangley 
yeah sure
```javascript
var mat = new THREE.Matrix4().makeTranslation(...)

**Comment by WestLangley** [comment]
Don't do that. Create one matrix and reuse it.

**Pull request closed without merging**
