### PR TITLE
KTX2Loader: Add support for ASTC 6x6 format

### LINKED ISSUE #26569: KTX2Loader: Support for ASTC and ETC1 formats
### Description

ASTC & ETC1 textures generated with [ARM-software/astc-encoder](https://github.com/ARM-software/astc-encoder) and [etc2comp](https://github.com/google/etc2comp) are being rendered inconsistently with threejs versions.

I have a PNG image of resolution 1024x1024. I compressed it into ASTC with below command. (`astcenc-sse2` is built from [ARM-software/astc-encoder](https://github.com/ARM-software/astc-encoder) source)

```bash
❯ astcenc-sse2 -cs texture-1k.png texture-astc-1k.ktx 6x6 -thorough
❯ file texture-astc-1k.ktx
texture-astc-1k.ktx: Khronos KTX texture (little-endian), 1024 x 1024, COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR
```

And I compressed the same PNG into ETC1 texture with below command. (`EtcTool` is built from [google/etc2comp](https://github.com/google/etc2comp) source)

```bash
❯ EtcTool texture-1k.png -format ETC1  -output ./texture-etc1-1k.ktx
❯ file texture-etc1-1k.ktx
texture-etc1-1k.ktx: Khronos KTX texture (little-endian), 1024 x 1024, ETC1_RGB8_OES
```

Since these are in KTX container format, I used [KTXLoader.js](https://unpkg.com/three@0.153.0/examples/jsm/loaders/KTXLoader.js) of `three@0.153.0` to load them. They appeared black (I was testing on mobile).

But when I change the threejs version to older versions, they did appear with colors. Exact specifics below.

- ETC1 texture appeared correctly when `three <= 0.135.0` 
- ASTC texture appeared when `three <= 0.136.0` (although it's darker).

PS:
- It might appear that, I'm mixing up `KTXLoader.js` of `three@.153.0` with different versions. But older threejs seems to render textures without errors, but the newer threejs is not rendering them.
- PNG Image and texture files are in codesandbox repos which are linked below.

### Reproduction steps

Steps to create textures are in description. Concise demo is in Codesandbox repo which is linked below. 

### Code

This is how I'm loading textures.

```js
const ktxLoader = new KTXLoader();
const getKTXTexture = async () => {
  return new Promise((res, rej) => {
    ktxLoader.load("../texture-astc-1k.ktx", (texture) => {
      // Setting to sRGB is making texture super dark
      texture.encoding = LinearEncoding;
      console.log(texture, texture.mipmaps[0].data.length);
      res(texture);
    });
  });
};

getKTXTexture().then((texture) => {
  const material = new MeshBasicMaterial({ map: texture });
})
```

### Live example

1. [ASTC Codesandbox](https://codesandbox.io/s/astc-texture-demo-with-vite-dmw9g3)
2. [ETC1 Codesandbox](https://codesandbox.io/s/etc1-texture-demo-with-vite-ptwmw9)

### Screenshots

_No response_

### Version

0.153.0

### Device

Mobile

### Browser

Chrome

### OS

Android

### PR DESCRIPTION
**Pull request by donmccurdy**
Related:

- Fixes https://github.com/mrdoob/three.js/issues/26569

To create samples with [KTX-Software](https://github.com/KhronosGroup/KTX-Software) v4.2:

```bash
# no supercompression
toktx --t2 --encode astc output.ktx2 input.png

# zstd supercompression
toktx --t2 --encode astc --zcmp 18 output.ktx2 input.png
```

ASTC is a GPU texture format, and works only on GPUs that support it — primarily mobile devices. ASTC is _not_ a transcoded format like Basis Universal's UASTC, which would work on any device.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Aside – it would be helpful to have more test cases for KTX2 support, we are supporting a fair number of cases at this point:

- UASTC + THREE.CompressedTexture
- ETC1S + THREE.CompressedTexture
- DataTexture
- DataArrayTexture
- ASTC + THREE.CompressedTexture
- LDR cubemap + THREE.CompressedCubeTexture
- (future) HDR cubemap + THREE.CompressedCubeTexture

Do we have a preference about making one example with dropdown selection, vs. a number of examples?

**Comment by CITIZENDOT** [comment]
ASTC supports various block sizes: `4x4`, `5x4`, `5x5`, `6x5`, `6x6`, `8x5`, `8x6`, `10x5`, `10x6`, `8x8`, `10x8`, `10x10`, `12x10`, `12x12`. I think it's good idea to cover all the block sizes.

**Comment by Mugen87** [comment]
> Do we have a preference about making one example with dropdown selection, vs. a number of KTX2 examples, vs. mixing KTX2 into existing examples where appropriate?

Since there are already many examples, I would prefer a single KTX2 demo with a dropdown selection. That said, I think it's also fine to update one or two of the existing (glTF) examples so they are using `KTX2Loader`.

**Comment by donmccurdy** [comment]
@CITIZENDOT Exactly — glad to support them, just not sure how to test it.

@Mugen87 I've added a dropdown with a number of small KTX2 2D texture samples for now. We're implementing KTX2 features that glTF files do not allow — ASTC, cubemaps, array textures, 3D textures, ... — so updating glTF examples won't help us here.

I have more samples to test (https://github.com/donmccurdy/KTX2-Samples), but have included only 2D textures in this PR.

**Pull request merged**
