### PR TITLE
WebGLProgram: camera-specific shader define.

### PR DESCRIPTION
**Pull request by sciecode**
As per suggested on https://github.com/mrdoob/three.js/issues/17662#issuecomment-541164744

This PR introduces `#define ORTHO` on programShaders. In my opinion this is long overdue.

As noted by @EliasHasle, this would facilitate a lot the handling of orthographic projection specific behavior inside `ShaderChunks`. It would also solve the issue of `varying vIsPerspective` hardware dependant calculation, dismiss the problems involved in colliding varyings and avoid several conditional branching currently happening inside the shaders to deal with orthographic cameras.

I'm also waiting for this change to push a fix for https://github.com/mrdoob/three.js/issues/17379 and https://github.com/mrdoob/three.js/issues/17662

**sidenote**: went for `ORTHO` instead of `ORTHOGRAPHIC` for shorter notation, but open to suggestions.

### CODE REVIEW

**Comment by EliasHasle** [comment]
Without complete overview, I think this is a step in the right direction. The implementation looks clean and complete too.

The obivious downside is that it will cause more compiles (and more _programs_) for cases where both perspective and orthographic cameras are to be used on the same objects.

Regarding my (arguably minor) point in the same comment of opening for more exotic cameras, it would be an advantage to also define `MATRIX_CAMERA` (or something like that) for both orthographic and perspective, and let the default `project_vertex` `#ifdef`-depend on that.

**Comment by sciecode** [comment]
> The obivious downside is that it will cause more compiles (and more programs) for cases where both perspective and orthographic cameras are to be used on the same objects.

Yes, this has the side effect of doubling the number of programs for materials being used by two different cameras. 

However, considering all the benefits exposed for single camera ( overwhelming majority of use-cases), I feel the pros far out-weight the cons in this case.

**Comment by Mugen87** [comment]
> However, considering all the benefits exposed for single camera ( overwhelming majority of use-cases), I feel the pros far out-weight the cons in this case.

I'm not sure about that. Having more programs will lead to more WebGL state changes which can noticeable downgrade rendering performance (depending on the scenario). 

Why is the current shader-based solution `isPerspectiveMatrix()` not sufficient?

**Comment by sciecode** [comment]
@Mugen87 I know you edited the answer, but I feel like the question "why `isPerspectiveMatrix` isn't sufficient" is relevant and I'd like to address it.

The current problem with that approach is that the `projectionMatrix` isn't available on the fragmentShader, thus requiring us to set a varying on the vertex to pass this information onwards. This `varying vIsPerspective` is how Log Depth chunks are currently dealing orthographic vs perspective handling.

I'd say this is probably the best option if there's a low number of conditional branching happening, but this won't be the case after I start handling problems discussed on https://github.com/mrdoob/three.js/issues/17662. Let me illustrate the problem:

On the PR in question, I proposed a fix that involved directly changing `vViewPosition`, however this is not the correct way of handling it, as it causes problems with clipping planes and flat shading. 

Thus I'd need to change `geometry.viewDir` declaration conditionally, which is on itself always executed. `viewDir`is calculated on the fragment for most material models, but not on lambert model. Which already introduces the problem of when and where it should be the declared and defined, additionally we when using a `envMap` or `logdepth` this varying will be used on the every material model. 

In short, `isPerspectiveMatrix` with `vIsPerspective` are sufficient to handle the problem if done correctly, which will likely require the introduction of few new shaderchunks <ortho_pars>, <ortho_vertex>, <ortho_fragment> and so on.

>I'm not sure about that. Having more programs can potentially lead to more WebGL state changes which can downgrade rendering performance (depending on the scenario).

The current model makes the code way harder to maintain and it affects performance of every material even when not using orthogonal projection. There's, also, the fact that we're checking and branching if the camera is orthographic on every frame and every fragment when we could simply be calculating it once at compile time. Which is making every use-case slower, instead of making it possibly slower on a very specific use-case.

**Comment by sciecode** [comment]
I prefer @gkjohnson proposal over this PR actually.

**Comment by sciecode** [comment]
This would solve the problems regarding varying and make it a lot easier to mantain, but it would still require the multiple conditional branching. It’s an improvement over our current approach nonetheless

**Comment by gkjohnson** [comment]
The modern impacts of branching in shaders are also not so clear to me. I know it used to be a big deal but if you have any documents on the current thinking on this topic that would be great. I've heard that 

1. branching is always bad and incurs a performance hit
2. it's only really bad if multiple fragments in a batch take different branches
3. that it's really not a big deal on modern hardware

I'm sure it really depends on the graphics hardware in question but my strategy is typically to assume the worst case and use `mix` in order to avoid a condition:

```hlsl
float3 viewDir = mix( perspViewDir, orthoViewDir, isOrthographic );
```

where `isOrthographic` is `1.0` or `0.0`.  But I don't know if this is _actually_ better because both "branches" here still have to be calculated in order to call `mix`. I'd definitely be interested in whatever the de-facto best practices on this are if they exist.

An aside but if `isOrthographic` is passed as a uniform I think that would remove the rounding precision issue that caused a logarithmic depth rendering regression we ran into due to varying field interpolation (see https://github.com/mrdoob/three.js/issues/17623#issuecomment-537125504).

**Comment by sciecode** [comment]
> 1. branching is always bad and incurs a performance hit
>2. it's only really bad if multiple fragments in a batch take different branches
>3. that it's really not a big deal on modern hardware

I'm also not completely clear on the impacts of conditional branching and I have read similar things. I know it is highly dependant on specific hardware, therefore I've always used the same `mix` approach as you presented.

But, I also remember reading that the built-in ternary operator is supposed to be better for modern hardware when compared with `mix`. I think if we were to use the `isOrthographic` uniform, we could probably stick the ternary operator.

```glsl
vec3 viewDir = ( isOrthographic == 0.0 ) ? pespViewDir : orthoViewDir;
```

My only worry is that, by using multiple of these conditionals, we have negative impact on the performance for older hardware.

**Comment by EliasHasle** [comment]
> I'm also not completely clear on the impacts of conditional branching

Here is a relevant question on StackExchange which has attracted some seemingly high-quality answers (that I personally feel I learned from reading): https://gamedev.stackexchange.com/questions/158173/does-cause-branching-in-glsl

**Pull request closed without merging**
