### PR TITLE
Bugfix: Model shadow error when OES_texture_float extension is unavailable

### PR DESCRIPTION
**Pull request by cenkai88**
Related issue: #23921

**Description**
Problem:
The value of maxBone of different skinnedMesh objects is not consistent, in the rendering process of each frame, the check of needsProgramChange does not include maxBone. As a result, during generation of skinnedMesh's shadowMap, the program is created for the first time and reused for all other skinnedMeshes. If some skinnedMesh has larger number of bones than the first program, data in boneMatrices will not be correctly passed to skin's shader(src/renderer/shaders/ShaderChunk/skinning_pars_vertex.glsl.js).

Solution:
Save the` maxBones` parameter to `materialProperties` and compare them when checking `needsProgramChange` in rendering of next skinnedMesh.

### CODE REVIEW

**Comment by Mugen87** [comment]
My view on this topic is still the same like in #20704. I do not vote merge this PR since it introduces additional checks that most platforms don't need (even if they actually use skinning). I would rather vote to expect floating point texture support for `SkinnedMesh`.

**Comment by cenkai88** [comment]
Thanks @Mugen87, I understand your concern, removing supports for platforms without OES_float_texture is an alternative solution but at least some warning or doc about this is necessary. Personally I spent almost one entire day to locate this.

Although considering the large population using three.js, 7% of users is not a small number. I still think adding few checks to help developers solve this is worthwhile.

**Comment by Mugen87** [comment]
> , removing supports for platforms without OES_float_texture is an alternative solution but at least some warning or doc about this is necessary.

Definitely. The documentation page of `SkinnedMesh` would define its requirements (WebGL 2 or support for OES_float_texture) and the renderer would report a warning if instances of `SkinnedMesh` are in the scene but no hardware support is detected.

**Comment by Mugen87** [comment]
Closing, see #23928.

**Pull request closed without merging**
