### PR TITLE
Logarithmic Depth Buffer: improve test for detecting perspective matrix in fragment shader

### LINKED ISSUE #17623: Logarithmic Depth Artifacts
#### Description of the problem

Logarithmic depth appears to be broken in `three@0.109.0`. Possibly related: #17442.

On my system, I see lots of depth artifacts in setups that use `logarithmicDepthBuffer`. I don't know if this problem is hardware-related; would be cool if someone could verify!

#### Screenshots

[logarithmicdepthbuffer example](https://threejs.org/examples/?q=log#webgl_camera_logarithmicdepthbuffer)

logdepthbuf

I get the same artifacts in one of my [projects](https://vanruesc.github.io/postprocessing/public/demo/#bokeh) where I use logarithmic depth for testing purposes:

| r108 (worked fine) | r109 (broken) |
|------|------|
| logdepthbuf1 | logdepthbuf2 |

#### Three.js version

- [x] Dev
- [x] r109
- [ ] r108

#### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Edge

#### OS

- [ ] All of them
- [x] Windows 10 Pro, 64-bit
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

#### Hardware Requirements (graphics card, VR Device, ...)

GPU: NVIDIA GTX 1060 6GB

#### Drivers

Graphics Driver: 436.30 (Standard Type)

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #17623

### CODE REVIEW

**Comment by WestLangley** [comment]
Please see continued discussion in https://github.com/mrdoob/three.js/issues/17623#issuecomment-537120501.

**Comment by mrdoob** [comment]
I'll wait until you guys decide 👌

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
OK to merge. Thanks.

**Comment by Mugen87** [comment]
Update builds: 4c684a90cbaa820b40e9bf093cc94b8d6d75100f

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
