### PR TITLE
adding color and normal vector support to VTKLoader.js 

### PR DESCRIPTION
**Pull request by pletzer**
Hi,
The following PR will:
- Read normal vector data if present in the file. Adding this information will render shapes with sharp edges more accurately
- Read color data (R, G, B in the 0 to 1 range) for each node or cell if present in the file
  Both the normals and colors are standard VTK fields described in http://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf. 

NORMALS dataName dataType
n0x n0y n0z
n1x n1y n1z
...
n(n-1)x n(n-1)y n(n-1)z

COLOR_SCALARS dataName nValues
c00 c01 ... c0(nValues-1)
c10 c11 ... c1(nValues-1)
...
c(n-1)0 c(n-1)1 ... c(n-1)(nValues-1)

A file example that contains colors is:
# vtk DataFile Version 3.0

vtk output
ASCII
DATASET POLYDATA
POINTS 3 float
0 0 0 
1 0 0
1 1 0
0 1 0 
POLYGONS 2 8
3 0 1 2 
3 0 2 3
CELL_DATA 2
COLOR_SCALARS Colors 3
1 0 0
0 1 0

### CODE REVIEW

**Comment by mrdoob** [comment]
I think you used the `master` branch as a base.
Do you mind using the `dev` branch as a base and re-implement?

**Comment by pletzer** [comment]
Hi,

I deleted the fork and startyed from the dev branch (I think). The only
file affected by the PR is VTKLoader.js.

Thanks.

--Alex

On Sat, Nov 14, 2015 at 12:10 PM, Mr.doob <notifications@github.com> wrote:

> I think you used the master branch as a base.
> Do you mind using the dev branch as a base and re-implement?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/pull/7597#issuecomment-156734571>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by mrdoob** [comment]
It still shows as it has conflicts 😕

**Comment by mrdoob** [comment]
If you take a look here:
https://github.com/mrdoob/three.js/pull/7597

It still shows as it has conflicts.

Maybe try doing a new PR?

**Comment by pletzer** [comment]
Hi,

Please use pull request # https://github.com/mrdoob/three.js/pull/7602
instead. #7597 was based on a fork from master and can be deleted. Thanks.

--Alex

On Mon, Nov 16, 2015 at 5:49 PM, Mr.doob <notifications@github.com> wrote:

> If you take a look here:
> #7597 <https://github.com/mrdoob/three.js/pull/7597>
>
> It still shows as it has conflicts.
>
> Maybe try doing a new PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/pull/7597#issuecomment-157222963>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by pletzer** [comment]
This PR is superceded by #7602 so closing.

**Pull request closed without merging**
