### PR TITLE
Using Vertex Array Objects to set multiple attributes/buffer at once

### PR DESCRIPTION
**Pull request by tstanev**
This is an example of how certain renderBufferDirect calls can make use of VAO to cut down on the number of GL calls. A VAO is attached to the geometry and used when available, instead of calling setupVertexAttributes on every pass through renderBufferDirect. The limitations of VAO in general mean that this can't be used with materials that have default attributes. The limitation of the particular implementation is that it doesn't work with geometry that uses multiple offsets -- though this could be easily added if the change is considered useful enough to go into the mainline.

### CODE REVIEW

**Comment by WestLangley** [comment]
For reference, [this post](http://blog.tojicode.com/2012/10/oesvertexarrayobject-extension.html) provides a nice summary of what Vertex Array Objects are all about.

**Comment by greggman** [comment]
Just curious but could you use an [emulation library like this](https://github.com/KhronosGroup/WebGL/blob/master/sdk/demos/google/resources/OESVertexArrayObject.js) ?

Or at least take the idea from the library. I think you could design an optimal emulation layer so three would could just assume VAOs exist and the library below could handle either passing through to the real thing or emulating. 

That library linked above is probably not the most efficient implementation, it sets all attributes. I think you could write one that only sets used attributes for each emulated VAO. That seems like it could be fast enough.

[Webglstats.com](http://webglstats.com) says VAOs are available on 88% of machines. They're emulated in Chrome even on machines they aren't native on. The point being that with an emulation layer in three, three says simple. It just assumes they exist. The emulation layer only really kicks in if they don't exist so even if it's slightly slower it's so few machines who cares? Most machines will win since they support it.

Just an idea.

**Comment by tstanev** [comment]
VAOs have certain limitations, for example they cannot be used when an attribute has a default/constant value. In such cases the non-VAO code path still has to be used.

**Comment by greggman** [comment]
That doesn't change my point. You can still use an emulation layer.

**Comment by tstanev** [comment]
You could use an emulation layer, but you would still have to keep both code paths in WebGLRenderer for the reason mentioned. So all you get from the emulation layer is performance overhead and bigger code size. Anyway, this PR is meant as example of how to retrofit VAO into the renderer with minimal effort for use cases that warrant it. There is no urgency to get the PR merged into mainline, my goal was to share work we’ve done for our own renderer that can be of general interest.

**Pull request closed without merging**
