### PR TITLE
Support for renderRect from WebVR spec

### PR DESCRIPTION
**Pull request by borismus**
See [WebVR spec](http://mozvr.github.io/webvr-spec/webvr.html#dom-vreyeparameters-renderrect)

I'm now relying on this for vertex-based distortion.

### CODE REVIEW

**Comment by mrdoob** [comment]
How about this instead?

```javascript
if ( rectL === undefined ) rectL = { x: 0, y: 0, width: size.width / 2, size.height };
if ( rectR === undefined ) rectR = { x: size.width / 2, y: 0, width: size.width / 2, size.height };
```

**Comment by borismus** [comment]
LGTM! Want me to update the PR?

**Comment by mrdoob** [comment]
Yes please 😊

**Comment by mrdoob** [comment]
While you're at it, can you rename `rect*` to `renderRect*`?

**Comment by MasterJames** [comment]
rectR.x  =  rectL.w would save one division computation.

**Comment by mrdoob** [comment]
> rectR.x  =  rectL.w would save one division computation. 

Micro optimisations are evil...

**Comment by MasterJames** [comment]
Roger on that.

**Comment by borismus** [comment]
Here's an update.

**Comment by mrdoob** [comment]
Sweet! Thanks!

**Pull request merged**
