### PR TITLE
MeshToonMaterial: Stop deriving from MeshPhongMaterial.

### PR DESCRIPTION
**Pull request by Mugen87**
Related: #16257

This PR ensures `MeshToonMaterial` is not derived from `MeshPhongMaterial` anymore. This makes it easier to implement toon specific lighting without affecting the phong shader chunks.

Everything should be as before except for environment maps which are not supported anymore (they are quite unusual for a toon shader).

I know it's remarkable how differently toon materials can be implement. However, I would prefer to discuss lighting related topics in a different issue. This PR is focused on decoupling the toon material from `MeshPhongMaterial` and implement an approach similar to `MeshMatcapMaterial`.

### CODE REVIEW

**Comment by WestLangley** [comment]
This is awesome. Thanks!

> I would prefer to discuss lighting related topics in a different issue. This PR is focused on decoupling the toon material from MeshPhongMaterial and implement an approach similar to MeshMatcapMaterial.

I think that is a wise decision.

**Comment by Mugen87** [comment]
Merging this before things break again.

**Comment by Mugen87** [comment]
Updated builds: faa7fe7b88b01ac56f09456f1f01fb11383e1f8c

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
