### PR TITLE
Add Quaternion.pow(exp) method

### LINKED ISSUE #22959: Add .pow(exponent) and .multiplyByExponentiatedQuaternion(quat2, exponent) methods to the Quaternion class
**Is your feature request related to a problem? Please describe.**

Hello!
I want to be able to handle rotations in my engine in similar way to the positions - I can write `position.addScaledVector(velocity, timePassed)` if I want to program moving with some velocity frame-by-frame and I want to be able to do similar thing for quaternions (or at least thing similar to `position.add(velocity.clone().scale(timePassed))`), i.e. `rotation.multiplyByExponentiatedQuaternion(rotationalVelocity, timePassed)` (or `rotation.multiply(rotationalVelocity.clone().pow(timePassed))`).

**Describe the solution you'd like**

I suggest that methods `.pow(exponent)` and `.multiplyByExponentiatedQuaternion(quat2, exponent)` would be added to the Quaternion class.

**Describe alternatives you've considered**

These methods could be added just by monkey-patching the prototype of the Quaternion class (and it is how I do it currently).

**Additional context**

The methods could be implemented similar to glMatrix's `pow(out, a, b)` function: https://github.com/toji/gl-matrix/blob/master/src/quat.js#L280.

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: Fixed https://github.com/mrdoob/three.js/issues/22959

**Description**

This pull request adds Quaternion.pow(exp) method.

### CODE REVIEW

**Comment by Mugen87** [comment]
Do you mind adding a unit test in https://github.com/mrdoob/three.js/blob/dev/test/unit/src/math/Quaternion.tests.js to verify the methods implementation? Would be good to have two test for the default case and for the case when `ratio` is `Infinity`.

The new method also needs to be documented here: https://threejs.org/docs/index.html#api/en/math/Quaternion

**Comment by LeviPesin** [comment]
@Mugen87 Done! :-)

**Review by Mugen87 — DISMISSED** [review]

**Comment by WestLangley** [comment]
@Mugen87 Have you been able to find this method implemented in other engines?

I think it would be beneficial to verify this implementation.

**Comment by LeviPesin** [comment]
@WestLangley There is [an implementation in glMatrix](https://github.com/toji/gl-matrix/blob/master/src/quat.js#L280).

**Comment by WestLangley** [comment]
@LeviPesin _Rendering_ engine?

Is there a reference for your implementation?

**Comment by Mugen87** [comment]
`glMatrix` is designed to be used with realtime 3D graphics so I think it's a good reference.

**Comment by WestLangley** [comment]
This is not the glMatrix implementation.

Where does this implementation come from?

**Comment by WestLangley** [comment]
@Mugen87 To be honest, I would feel a lot better if I could see this method used in another engine. Otherwise, I feel like we may be missing something...

**Comment by LeviPesin** [comment]
@WestLangley I wrote this implementation basing on `Vector.setAxisAngleFromQuaternion` and `Quaternion.setFromAxisAngle`.

**Comment by Mugen87** [comment]
> @Mugen87 To be honest, I would feel a lot better if I could see this method used in another engine. Otherwise, I feel like we may be missing something...

Okay, agreed. I try to find a reference.

@LeviPesin If possible, we implement math routines always based on references. So doing it like in `glMatrix` and linking to its source would be the best solution for now. The `ln()`, `scale()` and `exp()` functions could be inlined in `Quaternion.pow()`.

**Comment by Mugen87** [comment]
> Okay, agreed. I try to find a reference.

I've checked the quaternion doc pages of Babylon.js, OGRE, PlayCanvas, Godot, Unity, Unreal and MathGeoLib. No one lists a `pow()` method. `glMatrix` was the only lib that provides a `pow()` method so far.

**Comment by LeviPesin** [comment]
My implementation is actually very similar to the implementation in glMatrix. `r` in `ln` is `oldS` in my code, `t` is `arccos(w) / sin(w)`, `r` in `exp` is `oldS * arccos(w) / sin(w) * exp` - just `arccos(w) * exp`, `et` is 1 (my implementation assumes that the quaternion is normalized), and `s` is `sin(arccos(w) * exp) / (arccos(w) * exp)` - so `t * exp * s` is `sin(arccos(w) * exp) / sin(w)`, i.e. equal to `ratio` in my code.

**Comment by WestLangley** [comment]
> So doing it like in glMatrix and linking to its source would be the best solution for now.

I said https://github.com/mrdoob/three.js/issues/22959#issuecomment-986831653 because I was aware of https://math.stackexchange.com/a/940427, and using `Quaternion.exp()` and `Quaternion.ln()` would not be efficient.

>I've checked the quaternion doc pages of Babylon.js, OGRE, PlayCanvas, Godot, Unity, Unreal and MathGeoLib. No one lists a pow() method.

So there must be a reason it is not listed. I want to understand what we are missing...

**Comment by LeviPesin** [comment]
@Mugen87 What information is required?

**Comment by Mugen87** [comment]
It would be good to understand why no other common 3D/game engines do not provide such a method. In the past, it was avoided to add too use case specific features to the core.

**Comment by WestLangley** [comment]
@LeviPesin Since there has been no demand for this method, I'd suggest you add it to your own project for now.

Maybe in the future, there will be a compelling reason to add `.pow()`, `.exp()`, and `.ln()`.

For the record, three.js rotates _objects_, so methods such as `object.rotateOnAxis( axis, rate * time )` are used.

**Comment by Mugen87** [comment]
Closing for now. 

@LeviPesin As mentioned before we can reconsider adding this method when more users requesting it. Nevertheless, thanks for sharing the implementation of `pow()` in this thread.

**Pull request closed without merging**
