### PR TITLE
SEA3D 1.8.1

### PR DESCRIPTION
**Pull request by sunag**
- Open3DGC - High geometry compression algorithm
- Load `background` and `environment`
- Apply automatically `environment` in PB'Materials using `loader.config.useEnvironment`
- Global `attributes` and `scripts`
- Fix `loader.container`
- Fix `loader.clone` matrix
- Sync or Async loader textures
- Add `Reflectivity` and `Clear Coat` using `THREE.MeshPhysicalMaterial`
- Many fixes and improvements by @lo-th - http://community.poonya.com/250

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm...

```js
		if ( THREE.Float32BufferAttribute ) {

			// three dev

			geo.addAttribute( 'skinIndex', new THREE.Float32BufferAttribute( sea.joint, sea.jointPerVertex ) );
			geo.addAttribute( 'skinWeight', new THREE.Float32BufferAttribute( sea.weight, sea.jointPerVertex ) );

		} else {

			geo.addAttribute( 'skinIndex', new THREE.Float32Attribute( sea.joint, sea.jointPerVertex ) );
			geo.addAttribute( 'skinWeight', new THREE.Float32Attribute( sea.weight, sea.jointPerVertex ) );

		}
```

Wouldn't it be easier to "polyfill" `THREE.Float32BufferAttribute` at the beginning of the loader?

```js
if ( THREE.Float32BufferAttribute === undefined ) {

	THREE.Float32BufferAttribute = function ( array, itemSize ) {

		THREE.BufferAttribute.call( this, new Float32Array( array ), itemSize );

	}

	THREE.Float32BufferAttribute.prototype = Object.create( THREE.BufferAttribute.prototype );
	THREE.Float32BufferAttribute.prototype.constructor = THREE.Float32BufferAttribute;

}
```

**Comment by lo-th** [comment]
yes you right is fixed in sea repro

**Comment by mrdoob** [comment]
Merging this for now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
