### PR TITLE
VRMLLoader: Adding VRML Parser

### PR DESCRIPTION
**Pull request by bartmcleod**
I hope this version of the loader can be accepted. I adheres to the interface for a loader and does not modify the root scene.

@mrdoob Can it be tested or is that still a problem.? If so, what can I do to make it testable like the other loaders?

Advantages of this loader:
- The node tree will be fully parsed and you can inspect it. So you will be able to recognize your VRML objects in the three. Each Three object will have the original VRML node in its userdata property, which allows you to debug what you get or add extra functionality based on the userdata from your original VRML.
- Is is fast and simple

If you also want animation and viewpoint support, you will need to use the VrmlParser project, but this provides a good example.

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: https://rawgit.com/bartmcleod/three.js/vrml-loader-vrmlparser/examples/webgl_loader_vrml.html

**Comment by Mugen87** [comment]
It's up to @mrdoob to decide whether or not we rely on an external project for `VRML` parsing. I mean with this change, the logic inside `VRMLLoader` is reduced to a minimum and the actual logic is inside an additional library (more or less a black box).  If this is merged, upcoming issues in context of `VRML` might be delegated to https://github.com/bartmcleod/VrmlParser

**Comment by bartmcleod** [comment]
@Mugen87 The colors differ because VrmlParser has lighting support and the lighting has been removed from the global scene setup. The light you see now is the light as I built it in 1997 in the house model. One things that will be added in the future is support for ambient light. The diverged code of the current parser had a hacky approach to ambient lighting that should have been discouraged, but was helpful in one particular use case. The VrmlParser implementation does not provide that particluar hack.

**Comment by makc** [comment]
> and the actual logic is inside an additional library

the parser is in examples, right? I seem to remember few other examples do use external libs as well.

**Comment by bartmcleod** [comment]
@makc I have seen that too, just don't remember where and if they still do. There is a libs dir, probably for that reason.

**Comment by Mugen87** [comment]
I'm open for a library based approach. Looks like there are only two open issues in context of `VRML`. Both issues should be revisited if this is merged: #13002 and #8282. If necessary, they should be closed and tackled in https://github.com/bartmcleod/VrmlParser

**Comment by bartmcleod** [comment]
https://github.com/mrdoob/three.js/issues/8282 should be solved when using VrmlParser. If not, I am happy to address the issue.

**Comment by andreasplesch** [comment]
If there is interest in more testing, here are a few vrml scenes in VRML97 (and other) encoding:

http://www.web3d.org/x3d/content/examples/Vrml2Sourcebook/
http://www.web3d.org/x3d/content/examples/ConformanceNist/

**Comment by bartmcleod** [comment]
And that was that. No conclusion. No reason. Silence.

**Comment by Mugen87** [comment]
Sry, we stick to `VRMLLoader` as it is. Users can still use your lib if they need a more sophisticated solution in context of VRML.

**Pull request closed without merging**
