### PR TITLE
New TorusBufferGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces `TorusBufferGeometry`. You can test the new geometry with this [jsfiddle](https://jsfiddle.net/ob00wcwt/1/).

Besides, i fixed my editor so the indentation should be better than in the previous PR :wink:

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice! You're on a roll! 😀

**Comment by mrdoob** [comment]
Many thanks!

**Comment by WestLangley** [comment]
Would you be willing to update the docs, too, when you create a new class?

**Comment by WestLangley** [comment]
Thanks for this!

It is great that you are using _indexed_ BufferGeometry. But you are duplicating positions on the seams unnecessarily. So if you were to call `geometry.computeVertexNormals()` you would show two different normals on the seams. And of course, there are two seams for a torus -- unless it is a segment of a torus.

For example, a complete torus with 3 radial segments and 3 tubular segments only requires 3 x 3 = 9 vertices. Yours has ( 3 + 1 ) x ( 3 + 1 ) = 16.

Since you went to the trouble to use indexed geometry, I think it would be nice to fix this issue, too. : - )

**Comment by Mugen87** [comment]
> Would you be willing to update the docs, too, when you create a new class?

Yes, i will create a doc file for `BoxBufferGeometry` and `TorusBufferGeometry`.

> So, what you have done here is fine. : - )

Nice to hear that :wink:

**Pull request merged**
