### PR TITLE
WebGLRenderer: Fix issue 19430. and enable rendering without vertex data.

### PR DESCRIPTION
**Pull request by sjpt**
Allow use of procedural geometry (a) with no index or position attributes, and/or (b) no instance attributes.

### CODE REVIEW

**Comment by sjpt** [comment]
Note: some discussion on background at https://github.com/mrdoob/three.js/issues/19430
This also resolves the original issue raised there.

**Comment by sjpt** [comment]
For a more realistic example of procedural geometry see https://jsfiddle.net/sjpt/hgfsvLzn/latest

**Comment by xinaesthete** [comment]
hacky replacement of gui with dat.gui version for second sample above https://jsfiddle.net/kse6vd3g/

**Comment by sjpt** [comment]
Changed title to reflect that this resolves the change introduced in 117 that broke code that previously worked, as well as allowing new usage.

**Comment by duhaime** [comment]
2**64 thanks @sjpt! I just hit this exact problem attempting to upgrade from 110 to 111 and had a heck of a time figuring out what was going on. 

It turns out I was not passing an attribute named "position" to my BufferGeometry. I _was_ passing positional information, but under a different buffer name. 

In version 110, this was allowed, and I could just set my vertex position in the vertex shader without issue. In version 111, nothing is rendered unless I rename my buffer with position data "position"!

**Comment by filonik** [comment]
I just submitted an issue (#24165) that rightfully got closed as a duplicate. This looks like a great fix. Any chance of it ending up being adopted? What is still lacking? It is a bit discouraging that the last activity seems 2 years ago.

**Comment by dBat23** [comment]
Maybe who ever was working on it felt like they needed a masters degree to
be qualified to fix it better?

**Comment by Mugen87** [comment]
Closing in favor of #24179.

**Pull request closed without merging**
