### PR TITLE
Mesh/Line/Points: Fix copy().

### LINKED ISSUE #16224: Mesh.copy() does not copy the geometry or material
For example:
```js
var geometry = new THREE.BoxBufferGeometry( 1, 1, 1 );

var material = new THREE.MeshNormalMaterial();

var mesh = new THREE.Mesh( geometry, material );


var m = new THREE.Mesh().copy( mesh );

console.log( m.geometry ); // BufferGeometry with no attributes

console.log( m.material ); // MeshBasicMaterial
```
Likewise for `Line`, `LineSegments`, and `Point`. 

`Sprite`, does not copy the material.

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #16224.

This PR implements the approach I have outlined here: https://github.com/mrdoob/three.js/issues/16224#issuecomment-485878508

The idea is to remove all `clone()` methods in mesh, points and line classes and always use the version of `Object3D`. The `copy()` methods are now responsible for copying all properties.

### CODE REVIEW

**Comment by Mugen87** [comment]
The difference in the new implementation is the invocation of `updateMorphTargets()`. Previously, the method was called with the geometry of the source mesh. Now, it is called with the default geometry and thus producing no result. However, `morphTargetInfluences` and `morphTargetDictionary` are copied in `copy()` so you really get now the same object status.

In any event, there might be use cases where code could break. E.g.

```
var mesh1 = new THREE.Mesh();
mesh.geometry = geometry; // assign geometry with morph attributes
var mesh2 = mesh.clone();
```
Previously, `mesh2` would have valid `morphTargetInfluences` and `morphTargetDictionary` properties. Now, these  properties are missing since `copy()` replicates the status of `mesh1`(which has no `morphTargetInfluences` and `morphTargetDictionary`).

**Comment by WestLangley** [comment]
This is getting better. Thank you for working on it.

Even so, I have long-advocated removing `clone()` for a host of reasons -- except for the math classes, maybe. ***


---
***  But I do not like it there either because it violates our so-called policy of requiring users to allocate memory at the application level. Plus, inexperienced users are known to call `clone()` unnecessarily in tight loops.

**Comment by Mugen87** [comment]
How about discussing a potential removal of `Object3D.clone()` in a new issue? AFAIC, the knowledge about this topic is spread over multiple issues and PRs. Maybe it's easier to draw attention to the downsides by having a single issue.

**Review by WestLangley — APPROVED** [review]
I think this PR an improvement, so let's merge it.

You can wait until r.118 if you want to be safe.

**Comment by Mugen87** [comment]
> You can wait until r.118 if you want to be safe.

I would prefer that so we have more time for testing 😇 . Although I _think_ this change should be safe.

**Comment by Mugen87** [comment]
@mrdoob Since we are at the beginning of a new dev cycle, can we merge not this PR? 😇

**Comment by WestLangley** [comment]
I think this is worth a try. But we will see...

**Comment by mrdoob** [comment]
Yeah, I think we're good. Only `GLTFLoader` had a minor issue but I updated npm only with the fixed `GLTFLoader`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
