### PR TITLE
Add ColladaExporter

### PR DESCRIPTION
**Pull request by gkjohnson**
A Collada Exporter I've been working on [here](https://github.com/gkjohnson/collada-exporter-js)!

I've tested it with the collada models provided in the `examples/models/collada` folder, as well as the model used in [this](https://github.com/mrdoob/three.js/pull/13792) PR and the results look the same. The only exception is the stormtrooper model's orientation and scale, but that's because the exporter does not include bone or animation information. Speaking of which --

### Limitations

- Can only export model geometry, materials, and textures. Animations, skinning, joints, kinematics and other features are not included.
- Only `phong` (default), `lambert`, and `constant` material tags are supported.
- Only diffuse, specular, and emission maps are supported for export.
- Diffuse maps cannot be exported with a tint color (per the spec).
- MeshLab has problems importing attributes with shared index offsets ([this meshlab bug is discussed here](https://sourceforge.net/p/meshlab/bugs/424/)), so it looks like triangle soup there.

### Options

**version**: Which version of Collada to export (`1.4.1` or `1.5.0`). Defaults to `1.4.1`.
**author**: Name to put in the `author` field.
**textureDirectory**: The directory to save textures to

### Result

Returns an object that looks like this:
```js
// exporter.parse(obj)
{
	// Collada file content
	data: "",

	// List of referenced texures
	textures: [{

		// File directory (relative to collada file), name, and extension of the texture data
		directory: "",
		name: "",
		ext: "",

		// The texture data and original texture object
		data: [],
		original: <THREE.Texture>
	}, ...]
}
```

### Question

I noticed that the `GLTFExporter` uses an asynchronous API (with an `onCompleted ` function). Does it make sense for all the exporters to support the same function signature for consistency? That would make it easier to switch between the exporters. I like that the loaders are (for the most part) all consistent in that way. Also I'm not sure if there's any existing format I should use for the output of the exporter, as well?

If this all looks good I can make a documentation page for it.

Thanks!

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking great!

**Comment by mrdoob** [comment]
> Does it make sense for all the exporters to support the same function signature for consistency? That would make it easier to switch between the exporters.

Yeah, would be nice to keep that consistency.

**Comment by gkjohnson** [comment]
> Yeah, would be nice to keep that consistency.

Great! Any thoughts on result data? Does it makes more sense to have a `files` field with an array of external dependencies rather than strictly `textures`? I know it doesn't right now, but the OBJExporter could eventually output material as well as texture files, for example.

**Comment by Mugen87** [comment]
Have you considered to build the XML document via [XML DOM](https://www.w3schools.com/xml/dom_intro.asp) and use methods like `createElement()`,  `setAttribute()` etc.? From my point of view, this approach seems a little bit more robust than performing string operations.

**Comment by gkjohnson** [comment]
@Mugen87 I feel like those APIs are less read-able but I can see the argument for using them. Is the concern that using strings could result in producing invalid xml (which I understand)?

**Comment by Mugen87** [comment]
I've made the suggestion since we use `DOMParser` in `ColladaLoader`. TBH, working with a XML API in context of Collada seems to be most obvious and natural approach to me.

**Comment by gkjohnson** [comment]
I understand the position -- I guess I just feel like the strings are more readable and I'm not sure I see a big benefit to using the DOM APIs. I wouldn't be against using them, necessarily, but I'll probably track it for consideration in a future update.

**Comment by Mugen87** [comment]
> I wouldn't be against using them, necessarily, but I'll probably track it for consideration in a future update.

Okay, I'm fine with this 👍

**Comment by gkjohnson** [comment]
@mrdoob Okay I've updated the `parse` function to take an `onDone` callback like the GLTFExporter!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
