### PR TITLE
Support Object3D.lookAt( x, y, z )

### PR DESCRIPTION
**Pull request by WestLangley**
... as discussed in #12101.

### CODE REVIEW

**Comment by mrdoob** [comment]
Actually, I'm reconsidering this...

I think this is more clear:

```js
object.lookAt( x, y, z );
object.lookAtVector( v );
object.lookAtObject( o );
```

`object.lookAt()` will now have to throw a warning because now it expects `x, y, z` instead of `v`.

**Comment by mrdoob** [comment]
Before @pailhead gets upset... Yes, that's what he suggested in https://github.com/mrdoob/three.js/issues/12101#issuecomment-327019375 😉

**Comment by WestLangley** [comment]
>Actually, I'm reconsidering this...

I hope you decide not to. I think it is better if `lookAt()` just works.

`LookAtObject()` is not well-defined. The geometry can be offset from the origin.

**Comment by pailhead** [comment]
:D

**Comment by mrdoob** [comment]
> `LookAtObject()` is not well-defined. The geometry can be offset from the origin.

Good point.

**Comment by pailhead** [comment]
I think the alternative would be in tune more with JavaScript, than a graphics library. A super experienced JavaScript person might expect lookAtVector, without knowing much about linear algebra or graphics. A 3D artist that's trying some coding would expect the overloaded function. I'm totally 50:50 on this. It would be so nice if we had some sort of analytics with how people use threejs :)

**Pull request merged**
