### PR TITLE
Docs: Mentioned Import Maps in Installation guide.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: https://github.com/mrdoob/three.js/issues/23427#issuecomment-1051382403

**Description**

Updates the `Installation` guide to honor the introduction of Import Maps in `three.js`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev61/docs/index.html#manual/en/introduction/Installation

**Comment by LeviPesin** [comment]
Maybe the section "Import maps" in the "Compatibility" should be removed now?

**Comment by marcofugaro** [comment]
Thank you, I am in favor of removing all occurrences of skypack 👍

**Comment by Mugen87** [comment]
Both feedbacks should be implemented 👍 .

**Comment by LeviPesin** [comment]
The second paragraph of "Import maps" also should be removed, I think :-)

**Pull request merged**
