### PR TITLE
WebGLTextures: Simplify `updateMultisampleRenderTarget()`.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

The idea of the PR is to put the invalidation calls of `gl.invalidateFramebuffer()` in `updateMultisampleRenderTarget()` at one place.

It also makes sure to reuse array instances for the invalidation to avoid unnecessary object allocation.

### CODE REVIEW

**Comment by Mugen87** [comment]
@cabanier Does this new approach look good to you?

**Comment by cabanier** [comment]
> @cabanier Does this new approach look good to you?

Yes, it looks reasonable. This code is only exercised when "multisample render to texture" is not available so it should be tested on non-quest devices.

**Comment by Mugen87** [comment]
For testing, I've set `supportsInvalidateFramebuffer` to `true` and interestingly the glitches mentioned in other issues are now gone with this PR. I suspect this is related because the invalidation happens now once for draw and read buffer. Previously depth was invalidated first and then depth+color for the read buffer again. Maybe this order was responsible for the visual issues in the past.

I'll merge to finalize the performance related improvements for `r164`. For `r165`, I'll try to remove `supportsInvalidateFramebuffer` so `gl.invalidateFramebuffer()` is always used. At least I want to do some test on different devices.

**Comment by cabanier** [comment]
I remember having a similar issue on Safari before but now it seems to be on Chrome. Would it make sense to file a bug?

**Comment by Mugen87** [comment]
Yes, that would be good!

**Pull request merged**
