### PR TITLE
fix for PMREM warning: "INVALID_OPERATION: bindTexture: textures can not be used with multiple targets"

### PR DESCRIPTION
**Pull request by bhouston**
This is a fix for warnings that currently show in Chrome when running the envmap_hdr example.  It warns that a texture can not be bound to two targets at once:

image

What is happening is that ThreeJS (for probably a good reason that I do not fully understand) is binding a default emptyTexture when one tries to bind a null texture (which means unbind.)   If I prevent this default behavior of binding the emptyTexture in the CubeTexture case, the bug/warning goes away.  I have seen no side effects of this change in my testing.

### CODE REVIEW

**Comment by mrdoob** [comment]
@mattdesl as far as I remember you added this because WebGL2 complained. Does the patch still work in WebGL2?

**Comment by mattdesl** [comment]
Yeah I added that due to Chrome issues with null texture reference (was getting with webgl1 too). However I think it may be best to revert what I've done and just bug Tojiro or whoever if we see it appear in Chrome. It may already have been fixed?

I believe the spec should allow for null there, so emptyTexture should not be needed when the browser is spec compliant.

**Comment by mattdesl** [comment]
See here:
https://github.com/mrdoob/three.js/pull/8578

**Comment by kenrussell** [comment]
Apologies for not reviewing this in time.

Yes, if Chrome is failing if a null texture is passed to bindTexture, that's a bad bug. The WebGL conformance tests should cover this area and prevent regressions, but if there is a bug please point it out.

**Comment by mrdoob** [comment]
So the problem was that we were using a TEXTURE_2D as a TEXTURE_CUBE_MAP. ae81860411fb397e5905b8282eb497351a61121b

**Pull request closed without merging**
