### PR TITLE
Add documentation over textures not getting disposed together with material

### LINKED ISSUE #6834: View Frustum culling of children does not work
It seems to us that the frustum culling does not work for children of an object in the scene. Here is a simplified problem description:
- We have 1 parent object3d which is set to visible=false and frustumCulled=true
- We add to this parent 100 textured child-object with 512x512 textures each
- We switch visible to true in the parent object
- the renderer crashes because it tries to load all children objects into memory (i guess?) even if they are not in the field of view (is there a way to avoid this?)
- If we only show x children at once and hide children again it still crashes because the memory is not freed again when a child is not visible anymore (is that correct? how do we free this memory again?)

Our testing devices are mobile devices (the fastest it crashes on an samsung s3 but the same problems seem to occur on desktop machines after the memory limits are reached)

JSFiddle to reproduce the problem: http://jsfiddle.net/vao125wx/13

### PR DESCRIPTION
**Pull request by gero3**
fixes #6834

Add documentation over textures not getting disposed together with material

### CODE REVIEW

**Comment by benaadams** [comment]
As an aside I do the following on my static image textures to dump their memory post gpu transfer:
````javascript
function ReleaseTexture( texture ) {
    texture.image = null;
    if ( texture.mipmaps ) {
        texture.mipmaps = null;
    }
    texture.onUpdate = undefined;
}
...
var texture = THREE.ImageUtils.loadTexture( pathTextures + texturePath, undefined, resolve, reject );
texture.onUpdate = ReleaseTexture;
````
Stuffed on a context loss, but otherwise reduces memory pressure significantly

**Comment by titansoftime** [comment]
@benaadams Interesting. Would this work if one cached textures/materials and applied them to dynamically created objects?

**Comment by benaadams** [comment]
> Would this work if one cached textures/materials and applied them to dynamically created objects?

Yes the textures are there and loaded to gpu at this point so you can apply them to what ever you want; it just drops the dom img objects and any client side js data for them.

**Comment by mrdoob** [comment]
Thanks!

**Comment by titansoftime** [comment]
Ah, awesome thanks =]

**Pull request merged**
