### PR TITLE
Geometry/BufferGeometry: Changed semantics of .center()

### PR DESCRIPTION
**Pull request by Mugen87**
As propose in #13522

### CODE REVIEW

**Comment by WestLangley** [comment]
@mrdoob Reminder: This is a breaking change and needs to be highlighted in the migration docs.

**Comment by WestLangley** [comment]
@Mugen87 Thanks for making a separate PR.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
> This is a breaking change and needs to be highlighted in the migration docs.

Done, https://github.com/mrdoob/three.js/wiki/Migration-Guide

**Pull request merged**
