### PR TITLE
CI: Next try fixing E2E.

### LINKED ISSUE #28296: E2E tests broken.
### Description

Since about two weeks the E2E testing as a part of the CI is broken. Jobs fails with the following error:

> Run actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
With the provided path, there will be 153 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

AFAIK, we have not recently changed the CI settings apart from the updates renovate performs.

I have temporarily removed the E2E jobs from the CI via https://github.com/mrdoob/three.js/commit/7604fee89cedf7ba358c1c452bccf12345027034. 

### Reproduction steps

-

### Code

-

### Live example

-

### Screenshots

_No response_

### Version

r164

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28296.

**Description**

Next attempt to fix #28296. Testing for issues in the runner environment.

This PR uses Windows instead of macOS as the OS.

### CODE REVIEW

**Comment by Mugen87** [comment]
npm run make-screenshot games_fps physics_ammo_break physics_ammo_volume webaudio_timing webgl2_rendertarget_texture2darray webgl_animation_multiple webgl_animation_skinning_additive_blending webgl_animation_skinning_ik webgl_buffergeometry_drawrange webgl_buffergeometry_lines webgl_camera_cinematic webgl_effects_peppersghost webgl_marchingcubes webgl_materials_texture_anisotropy webgl_materials_texture_filters webgl_materials_texture_manualmipmap webgl_math_obb webgl_mesh_batch webgl_points_waves webgl_postprocessing webgl_postprocessing_advanced webgl_postprocessing_afterimage webgl_postprocessing_fxaa webgl_postprocessing_glitch webgl_postprocessing_rgb_halftone webgl_postprocessing_smaa webgl_postprocessing_ssaa webgl_postprocessing_taa webgl_geometry_cube webgl_gpgpu_birds webgl_gpgpu_birds_gltf webgl_gpgpu_protoplanet webgl_gpgpu_water webgl_instancing_morph webgl_instancing_performance webgl_interactive_cubes webgl_interactive_cubes_gpu webgl_interactive_cubes_ortho webgl_interactive_points webgl_interactive_raycasting_points webgl_layers webgl_lines_colors webgl_loader_bvh webgl_loader_fbx webgl_shadow_contact webgl_shadowmap_performance webgl_test_memory

**Comment by Mugen87** [comment]
Finally, it works! 🎉

**Comment by RenaudRohlinger** [comment]
Nice one! 👏

**Comment by mrdoob** [comment]
Nice nice! 👏

**Comment by sunag** [comment]
Yeah, awesome

**Pull request merged**
