### PR TITLE
fixed:shadows are not being casted right on obj

### PR DESCRIPTION
**Pull request by TyrealGray**
fix about shadows are not being casted right on obj sometime,some .obj file just can't see anything.

### CODE REVIEW

**Comment by mrdoob** [comment]
I don't think this fixes the shadows. I think this forces the obj to have normals, which shadows have nothing to do with...

**Comment by TyrealGray** [comment]
qq 20151027234610
I don't know if my description is accurate,basically that is how some .obj files looks like,it does not happened all the time,but some file does that.

**Comment by mrdoob** [comment]
I think for your case you only need `buffergeometry.computeVertexNormals()`.

**Comment by TyrealGray** [comment]
that's cool,thx :+1:

**Comment by mrdoob** [comment]
Implemented in #7524.

**Pull request closed without merging**
