### PR TITLE
favicon

### PR DESCRIPTION
**Pull request by sunag**
image
image
Prevent `favicon.ico` warning.

### CODE REVIEW

**Comment by mrdoob** [comment]
Should we put it in the root so `editor` and `gh-pages` can use it too? Or maybe a `files` folder in root if we have more images?

**Comment by sunag** [comment]
We can put `favicon.ico` in root? browsers automatically search the icon in root folder.

**Comment by Mugen87** [comment]
If `favicon.ico` is in the root directory, it is not necessary to include it via:
```
<link rel="shortcut icon" type="image/x-icon" href="/path/to/favicon.ico">
```
This is only necessary if the files is not placed in the root directory or if it has a different name.

**Comment by sunag** [comment]
@mrdoob Do you find it better on the root or a folder? thinking that this could evolve to add others metatags like `og:image` for example... I think favicon would be in the root while others metatags in a specific folder?

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
