### PR TITLE
Remove warning when using sRGBEncoding

### PR DESCRIPTION
**Pull request by Temdog007**
Fixes [issue](https://github.com/mrdoob/three.js/pull/16148#issuecomment-480611998) discovered in #16148

### CODE REVIEW

**Comment by WestLangley** [comment]
What is causing

    r * 0.9478672986 + 0.0521327014

to be negative in your application?

**Comment by Temdog007** [comment]
If you have a material with a texture and you set its encoding to `THREE.sRGBEncoding`, the before mentioned warning appears when it is first rendered. I don't think it is an application specific thing since it happens in #16148 and the only thing that changes is that the encoding of the texture is changed.

I also created a [jsfiddle](https://jsfiddle.net/pd0se687/) just to be sure. The warning occurs there too.

**Comment by WestLangley** [comment]
Your fiddle generates no warnings on my machine...

**Comment by Temdog007** [comment]
Oh, then I guess this is a machine specific issue. I'll close this PR then.

**Comment by looeee** [comment]
I do get the warning, but it's intermittent - maybe about once every ten times I load the scene. 
I get this warning in many scenes actually, and have for some time. However, since it's only occasional and doesn't seem to cause any problems I've ignored it until now.  

Chrome, last few version, windows, GTX 970m.

**Comment by WestLangley** [comment]
Hacking the shader code to make the waring disappear is not the proper solution -- especially when the cause is not yet understood. I hope that was made clear.

**Comment by mrdoob** [comment]
@Temdog007 can you share the image you're getting that warning with?

**Comment by Temdog007** [comment]
I get the warning whenever I set the `texture.encoding` to `THREE.sRGBEncoding`. The image doesn't matter. If the [jfiddle](https://jsfiddle.net/pd0se687/) doesn't give the warning, I believe the warning won't happen on your machine.

I used Chrome and Firefox on windows, GTX 1080 and I got warnings on both. I also see the warning consistently every time I load the scene.

**Comment by mrdoob** [comment]
I see. Yeah, I'm unable to reproduce too...

**Pull request closed without merging**
