### PR TITLE
Fix export of TypeScript Math namespace

### PR DESCRIPTION
**Pull request by Methuselah96**
Context: https://github.com/mrdoob/three.js/pull/15823#issuecomment-468764424

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Does this need a new npm publish?

**Comment by Methuselah96** [comment]
@mrdoob Yeah, sorry, it probably should be published so that the Math namespace is usable in Typescript.

**Comment by mrdoob** [comment]
No worries. Thanks!

**Comment by mrdoob** [comment]
Re-published.

**Pull request merged**
