### PR TITLE
StereoEffect: Handle clear differently.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

I was testing what type of effects already work with `WebGPURenderer`(it's `AsciiEffect` and `PeppersGhostEffect`, btw). `StereoEffect` does not work because of the way the clear happens in `render()`. 

When defining a scissor area, WebGL honors it during the clear. That does not work with WebGPU where the clear value is loaded for the entire framebuffer.

`StereoEffect` clears now the entire framebuffer once before rendering the left and right view.

### CODE REVIEW

**Comment by Mugen87** [comment]
@WestLangley `StereoCamera` manipulates the projection matrices for the left and right eye to achieve an off-axis stereoscopic effect. It seems these changes do not work with WebGPU, probably because it has different NDC conventions. We have different code paths for WebGL and WebGPU in `Matrix4.makePerspective()` and we probably need something similar in `StereoCamera`. Do you know what part of the matrix computation in `StereoCamera.update()` must be changed to make it compatible to WebGPU?

**Comment by WestLangley** [comment]
@Mugen87 If I am not mistaken,  `StereoCamera` does not know the correct `coordinateSystem`.

**Comment by Mugen87** [comment]
We can inject the coordinate system from outside, e.g. `StereoEffect`. This class has a reference to the renderer and can assign the value when creating a stereo camera.

**Comment by Mugen87** [comment]
The following line can be added to the constructor of `StereoCamera`.
```js
this.coordinateSystem = WebGLCoordinateSystem;
```

**Pull request merged**
