### PR TITLE
Removal of THREE.MeshFaceMaterial in examples, docs and core

### PR DESCRIPTION
**Pull request by Mugen87**
This PR does the following in all examples, docs and the core library (except `THREE.Legacy.js`):

`THREE.MeshFaceMaterial` -> `THREE.MultiMaterial`

### CODE REVIEW

**Comment by mrdoob** [comment]
Maaaany thanks!

**Comment by GFargo** [comment]
Think there might still be some old bits hanging around in the `utils/build` settings, when trying to compile the `canvas` config Node threw the following error :bug: 

```
Error: ENOENT: no such file or directory, open '../../src/materials/MeshFaceMaterial.js'
```

Apologies if this is the incorrect place to post this, still a bit new to the Three.js project

**Comment by Mugen87** [comment]
@GFargo I didn't find any remaining references to `THREE.MeshFaceMaterial` in the `utils/build` directory. If I understand you correctly, then you had the mentioned problems with a custom build, right?

**Comment by GFargo** [comment]
I could be wrong, but [here](https://github.com/mrdoob/three.js/blob/master/utils/build/includes/canvas.json) in `utils/build/includes/canvas.json` *MeshFaceMaterial* is referenced on line 48.

**Comment by mrdoob** [comment]
@GFargo that has been changed in the `dev` branch already.

**Comment by GFargo** [comment]
:+1: my mistake, thanks for the awesomeness! :beers:

**Pull request merged**
