### PR TITLE
WebGLRenderer: Refactored render loop and fix transmission in VR

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #21911

**Description**

Live link: https://raw.githack.com/mrdoob/three.js/dev/examples/#webxr_vr_sandbox

Screen Shot 2021-08-25 at 4 48 12 PM

In order to get transmission working in VR I had to refactor the render loop following what @davehill00 did in #22123.

Before this PR the logic was:

1. Render Camera 1 Opaque List
2. Render Camera 2 Opaque List
3. Render Camera 1 Transparent List
4. Render Camera 2 Transparent List

After this PR the logic is:

1. Render Camera 1 Opaque List
2. Render Camera 1 Transparent List
3. Render Camera 2 Opaque List
4. Render Camera 2 Transparent List

/cc @takahirox @davehill00

### CODE REVIEW

**Comment by davehill00** [comment]
Were you able to make any optimizations to per-object render state setup costs, or does this just roll back the performance gain from my previous change?

**Comment by mrdoob** [comment]
It's an evolution of what you did.

Before your PR the logic was:

1. Render Opaque Object 1 Camera 1
2. Render Opaque Object 1 Camera 2
3. ...
3. Render Transparent Object 1 Camera 1
4. Render Transparent Object 1 Camera 2
5. ...

**Comment by mrdoob** [comment]
I'll push the builds temporarily so we can test this easily.

**Comment by mrdoob** [comment]
Live link: https://raw.githack.com/mrdoob/three.js/transmission-vr/examples/#webxr_vr_sandbox

**Comment by mrdoob** [comment]
@davehill00 Any chance you can try this a bit? I do not have my Quest this week.

**Comment by davehill00** [comment]
Yep, should be able to take a look sometime this week.

**Comment by phoenixbf** [comment]
link tested on my quest 2: transmission looks fine now in VR. For performance should compare more in depth

**Comment by mrdoob** [comment]
Hmm... I think I'll merge this for r132 and revert and release a point release if something goes wrong.

**Comment by davehill00** [comment]
Finally got around to testing this on Quest 2 (got sidelined by the bundler issue). Draw call perf looks comparable to the what we landed in r131. 👍

**Comment by mrdoob** [comment]
Sweet! Thanks!

**Pull request merged**
