### PR TITLE
Added Convex Geometry

### PR DESCRIPTION
**Pull request by qiao**
The ConvexGeometry receives a list of vertices and generates the convex hull.  Fixes #1112

An example is included in the commits :)

### CODE REVIEW

**Comment by kintel** [comment]
Revisiting this: Did the quickhull discussion ever make it into its own issue?
The reason I ask is that I recently did a very simple test of both THREE.ConvexGeometry and the QuickHull implementation from @marklundin, and I found both to be surprisingly fragile.

I whipped up a quick & dirty demo here to show that ConvexGeometry of two spheres fails, and QuickHull of two spheres give a pretty garbled result, while the corresponding using two cubes work fine:
http://codepen.io/kintel/pen/GpxOyE

Happy to continue/reopen discussion somewhere else..

**Comment by WestLangley** [comment]
@kintel Try calling `sphereGeometry.mergeVertices()`.

> Happy to continue/reopen discussion somewhere else..

If you see more issues, that would be best.

**Comment by kintel** [comment]
@WestLangley Thx. Looks like ConvexGeometry is ok after removing duplicate vertices. Not sure if that's considered an bug or a documentation improvement potential.
The QuickHull one still fails pretty badly, but that's a separate issue.

**Comment by marklundin** [comment]
@kintel the quickhull implementation is not very robust as you can tell. There are a few other scenarios that produce bas results. I'll get round to addressing these at some point

**Comment by kintel** [comment]
@marklundin got it. I  posted my example in your github project as well, for reference. I was just under the impression that this was solid enough for inclusion into three.js, but I guess it needs some work. If you get around to getting a test framework up and running, I might be able to help you get stuff tested as I find corner cases.

**Comment by marklundin** [comment]
I think the plan was to integrate it at some point, but we never got round to it; probably a good thing.

I think it would still make sense having a quick hull implementation in three.js as in many cases it's a faster routine. That being said, I'd need to make sure it's more robust. Scenarios I imagine it would fail are co-planar sets and sets with co-incident points.

**Comment by kintel** [comment]
Agreed. IMO, the path to success is writing testable code. This sort of testing could probably beneficial to other parts of three.js, but that's yet another larger project..

**Comment by kintel** [comment]
@WestLangley Found additional issues - see #8416

**Comment by ipbebnev** [comment]
How to add texture to one edge of convex geometry mesh? Can somebody write code example? 
For base we can get that: http://jsfiddle.net/cwoodall22/bk3qx8ys/

**Pull request merged**
