### PR TITLE
BGL.parse fix

### LINKED ISSUE #6166: Either BufferGeometryLoader.parse or BufferGeometry.toJSON is broken :S
[here](https://github.com/mrdoob/three.js/blob/dev/src/loaders/BufferGeometryLoader.js#L39) it expects "attributes" in json, but it can't find any, because [here](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L875) attributes are nested under "data".

nice quest to fix json files before three can load them and all, but what about making it just work :wink:

### PR DESCRIPTION
**Pull request by makc**
This seems to fix #6166. At least, local version of editor can now import BufferGeometry json that it exports.

The references of BGL.parse are:
/editor/js/Loader.js (no change needed)
/examples/webgl_geometry_colors_lookuptable.html (no change needed here, but /examples/models/json/pressure.json needs to be changed)
/src/loaders/ObjectLoader.js (changed in this commit)
/utils/exporters/blender/tests/scripts/js/review.js (not sure if the change is needed, seems it should not need the change)

### CODE REVIEW

**Comment by makc** [comment]
ok, I have fixed the model, too.
test

**Comment by mrdoob** [comment]
Ah. I see what the problem is now...

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
Meanwhile I have uploaded this [util](http://makc.github.io/three.js/buffergeometry/) to work around issue #6166 in r70 (outputs json that can be loaded back into editor) and #6206 also. That eiffel tower I sent you before goes from 5.5 to 1.2 megabytes.

test

**Pull request merged**
