### PR TITLE
Examples > VFX Flames > Uses Sprite

### PR DESCRIPTION
**Pull request by brunosimon**
**Description**

Uses Sprite in the VFX flames example to demonstrate a more relevant way to use the effect.
Following @WestLangley advice: https://github.com/mrdoob/three.js/pull/28969#issuecomment-2251281457

### CODE REVIEW

**Comment by WestLangley** [comment]
This is a great example!

But as I suggested, I'd instantiate a sprite, instead of a mesh.

```js
const flame1 = new THREE.Sprite( flame1Material );
flame1.center.set( 0.5, 0 );
flame1.position.x = - 0.5;
scene.add( flame1 );

const flame2 = new THREE.Sprite( flame2Material );
flame2.center.set( 0.5, 0 );
flame2.position.x = 0.5;
scene.add( flame2 );
```

**Comment by sunag** [comment]
It would be interesting to have a `billboarding()` node. Fire, grass, branches should follow the camera only on the horizontal axis, like the rain example.

**Comment by brunosimon** [comment]
> It would be interesting to have a `billboarding()` node. Fire, grass, branches should follow the camera only on the horizontal axis, like the rain example.

A `billboarding()` node sounds useful. Maybe with some levels of control on it, like what's the `up` axis (sounds silly but I did a Three.js project where `z` was up).

I took the `billboarding()` function from the compute particle rain example and stripped it without understanding what I'm doing:

```js
const billboarding = tslFn( () => {

	const modelViewMatrix = cameraViewMatrix.mul( modelWorldMatrix );
	modelViewMatrix[ 0 ][ 0 ] = 1;
	modelViewMatrix[ 0 ][ 1 ] = 0;
	modelViewMatrix[ 0 ][ 2 ] = 0;

	modelViewMatrix[ 2 ][ 0 ] = 0;
	modelViewMatrix[ 2 ][ 1 ] = 0;
	modelViewMatrix[ 2 ][ 2 ] = 0;

	return cameraProjectionMatrix.mul( modelViewMatrix ).mul( positionGeometry );

} );
```

Is that okay?

**Comment by sunag** [comment]
I did it in [this PR](https://github.com/mrdoob/three.js/pull/29011) to make it easier

**Pull request closed without merging**
