### PR TITLE
Docs: Refactor URL generation in geometry browser.

### PR DESCRIPTION
**Pull request by gero3**
**Description**
This fixes the following lgtm error =>
[LGTM Error](https://lgtm.com/projects/g/gero3/threejsWithLGTMconfig/snapshot/6dc9ec21909256e6dddb307e7e90409666d674f4/files/docs/scenes/geometry-browser.html?sort=name&dir=ASC&mode=heatmap#x921af1e588a3c59b:1)

### CODE REVIEW

**Comment by Mugen87** [comment]
> No new or fixed alerts

I wonder why lgtm does not recognize this change as a fix for an alert 🤔 .

**Comment by gero3** [comment]
This is becuase the file gets classified as docs. A classification removes the alerts from the total that gets shown.
image

The alert still gets shown when you show excluded files.
=> [LGTM](https://lgtm.com/projects/g/mrdoob/three.js/latest/files/docs/scenes/?sort=name&dir=ASC&mode=heatmap&showExcluded=true)


#23062 removes the classification from the docs folder.

**Comment by Mugen87** [comment]
Thanks for the clarification. I've just updated the code a bit so it looks similar to what's happen in `chooseFromHash()`.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
