### PR TITLE
New BoxBufferGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces `BoxBufferGeometry`, the BufferGeometry port of `BoxGeometry`. I've changed three examples so they directly use `BoxBufferGeometry`.

### CODE REVIEW

**Comment by WestLangley** [comment]
Nice work!

Unfortunately, `materialIndex` has been lost from `BoxGeometry` with this PR, so this pattern will not  work:

```javascript
mesh = new THREE.Mesh( new THREE.BoxGeometry(), new THREE.MultiMaterial( materials ) );
```

**Comment by Mugen87** [comment]
@WestLangley Any ideas, how we can add `materialIndex` to `BoxBufferGeometry`? I mean, is it conceptual possible to add a `materialIndex` with the current structure of `BufferGeometry`? To be honest, i've found no obvious solution for this...

**Comment by WestLangley** [comment]
This is a lot of [history](https://github.com/mrdoob/three.js/search?o=desc&q=buffergeometry+materialindex&s=created&type=Issues&utf8=✓) on that issue. I do not recall what the current status is.

**Comment by Mugen87** [comment]
Thanks for the link :+1: . I'll try to get an overview...

**Comment by Mugen87** [comment]
I can manage to add a group for each side of the box, so you can apply a `MultiMaterial` on `BoxBufferGeometry`. The problem is that the amount of materials in `MultiMaterial` must exactly match the amount of indices in the geometry, otherwise you get runtime errors in `projectObject`.

```javascript
for ( var i = 0, l = groups.length; i < l; i ++ ) {

    var group = groups[ i ];
    var groupMaterial = materials[ group.materialIndex ];

    if ( groupMaterial.visible === true ) { // ERROR: Cannot read property 'visible' of undefined

        pushRenderItem( object, geometry, groupMaterial, _vector3.z, group );

    }

}
```
Because a box has six sides, `BoxBufferGeometry` should have six groups and therefore six material indices (0-5). But how can the renderer handle this geometry when the users applies a `MultiMaterial` with e.g. two materials? Or would this be an invalid setup?

**Comment by WestLangley** [comment]
`Geometry.fromBufferGeometry()` does not set `materialIndex` properly. Consequently the `BoxGeometry` constructor in this PR will not work correctly.

I think this can be easily fixed by passing `materialIndex` as an arg to `addFace( a, b, c )` in `Geometry.fromBufferGeometry()`.

/ping @mrdoob 

>But how can the renderer handle this geometry when the users applies a MultiMaterial with e.g. two materials? Or would this be an invalid setup?

If I recall correctly, that used to work: the materials would repeat. Perhaps not with the current design, though.

**Comment by Mugen87** [comment]
I've provided a [jsfiddle](https://jsfiddle.net/taetpr7y/) with the new code. Removing one of the `MeshBasicMaterial` from the materials array will cause the mentioned runtime error.

**Comment by Mugen87** [comment]
Jus

**Comment by WestLangley** [comment]
This looks good to me. Thanks!

**Comment by mrdoob** [comment]
>> But how can the renderer handle this geometry when the users applies a MultiMaterial with e.g. two materials? Or would this be an invalid setup?

> If I recall correctly, that used to work: the materials would repeat. Perhaps not with the current design, though.

Did they? I think it was always the expectation that the MultiMaterial will have the same amount of materials. But if the user misses one we should be able to handle that.

**Comment by mrdoob** [comment]
Many thanks!

**Pull request merged**
