### PR TITLE
ES6 Classes: Add support for class fields

### PR DESCRIPTION
**Pull request by marcofugaro**
As explained in https://github.com/mrdoob/three.js/issues/19986#issuecomment-675559937, let's switch to [@rollup/plugin-babel](https://github.com/rollup/plugins/tree/master/packages/babel) to support the class fields.

I also updated `babelCleanup()` which unwraps the classes, everything should be more or less like before.

I included the build files to do a check, but I can remove them from this PR if you guys don't want them.

### CODE REVIEW

**Comment by marcofugaro** [comment]
Ugh, unit tests are failing because they're not recognizing the class fields, let me investigate

**Comment by donmccurdy** [comment]
Note that the build outputs have a header, `// threejs.org/license` before this change but not afterward — we probably want to keep that.

**Comment by mrdoob** [comment]
@donmccurdy believe it or not, I've been dealing with that by hand forever 😅

**Comment by mrdoob** [comment]
Sadly I can't see the diff on github, but I find it suspicious that `three.js` has 33,770 additions, 48,132 deletions 🤔

**Comment by munrocket** [comment]
Glad to see that you actively using E2E tests in this migration.
You could add `banner: '/*  threejs.org license  */'` in rollup config for header in build file.

**Comment by marcofugaro** [comment]
@mrdoob time to automate it 😝

Thanks for the suggestion @munrocket, I've added it as a JSDoc comment so google closure compiler doesn't remove it. BTW I could move the google closure compiler step in the rollup.config.js via [rollup-plugin-closure-compiler](https://github.com/ampproject/rollup-plugin-closure-compiler) so that we have only one build command.

> Sadly I can't see the diff on github, but I find it suspicious that build/three.js has 33,770 additions, 48,132 deletions 🤔

It was showing that diff because it was removing all the whitespace. I've added the option to preserve the whitespace as much as possible now.

**Comment by marcofugaro** [comment]
To fix the CI issue, I had to update the node version of the CI to 12, the latest LTS release. 

This is because [class fields are supported from node 12](https://node.green/#ESNEXT-candidate--stage-3-).

**Comment by mrdoob** [comment]
Looking at `build/three.js`, seems like the indents start with a tab, and then it's spaces 🤔

**Comment by donmccurdy** [comment]
That's a major part of why people would choose Bublé over Babel, I think? Bublé just "does less" by design. But Bublé seems to be in maintenance mode, so perhaps it's best to try to find a Babel configuration that provides something similar.

@marcofugaro perhaps check out how the [Microbundle's "modern" mode is implemented](https://github.com/developit/microbundle#-modern-mode-)? The `bugfixes: true` option on preset-env might might simplify things.

**Comment by marcofugaro** [comment]
@mrdoob Yeah that was the `retainLines` option doing its best. As @donmccurdy pointed out, Babel's purpose is not really human readability after compilation. Rather it optimizes code as much as possible for machines. For example it does a lot of optimization for smaller minified files. People use sourcemaps nowadays for human readability.

Said so, I've added an `eslint --fix` step after the compilation, which should get rid of any formatting issues.

Take a look now, I think the result is much more acceptable.

-------------------

> @marcofugaro perhaps check out how the Microbundle's "modern" mode is implemented? The bugfixes: true option on preset-env might might simplify things.

I've sniffed the source of that library, and [the most of the "modern" mode is being done here](https://github.com/developit/microbundle/blob/225e35072ca2ab5d7c748c72e2cd849b2eb6bf40/src/lib/babel-custom.js#L128-L130), it basically uses [@babel/preset-modules](https://github.com/babel/preset-modules) under the hood, which is the same of the `bugfixes: true` option.

@donmccurdy I've enabled the `bugfixes: true` option as you suggested, but right now it has no effect, since we are still supporting IE11.

**Comment by marcofugaro** [comment]
After the new changes in the rollup.config.js, this PR is outdated.

Opened a new one #20395

**Pull request closed without merging**
