### PR TITLE
GLTFExporter: Added forceIndices for non-indexed geometry

### PR DESCRIPTION
**Pull request by fernandojsg**
As discussed on https://github.com/mrdoob/three.js/issues/13397
image

### CODE REVIEW

**Comment by mrdoob** [comment]
Very nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@zellski does facebook support non-indexed geometries these days?

**Comment by zellski** [comment]
... *weeps*
no. not yet.

**Comment by zellski** [comment]
Ugh, I am seriously tempted to create fake indices when needed on the server, just to unblock this...

**Comment by mrdoob** [comment]
Now that Facebook has cancelled their GLTF on the timeline efforts, I guess we can remove this code?

**Comment by donmccurdy** [comment]
Agreed, we don't need a `forceIndices` option on GLTFExporter.

**Comment by mrdoob** [comment]
Done! Should we also remove `forcePowerOfTwoTextures`?

**Comment by donmccurdy** [comment]
No preference on that one, either way is fine with me. :)

**Comment by mrdoob** [comment]
Okay, the code is minimal anyway, but I'll remove it from the editor export.

**Pull request merged**
