### PR TITLE
WebGLRenderer: Removed renderTarget from scene.onAfterRender()

### PR DESCRIPTION
**Pull request by mrdoob**
Removed `renderTarget` from `scene.onAfterRender()` to match `object.onAfterRender()`.

Also cleaned up `webgl_tiled_forward`.

### CODE REVIEW

**Comment by mrdoob** [comment]
FYI @wizgrav

**Comment by wizgrav** [comment]
@mrdoob yeah better more consistent. Sorry for being so slow on doing the cleanup myself, I got very tied up with work. At some point soon I'd like to update the example for webvr, should it be with a webgl_ or webvr_ prefix?

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
> At some point soon I'd like to update the example for webvr, should it be with a webgl_ or webvr_ prefix?

Maybe better to have two different examples?

**Comment by wizgrav** [comment]
Sure, though the tiled lighting needs only minor additions to support both cases. I'll do these on a different scene for the webvr example

**Pull request merged**
