### PR TITLE
Fix circular references and improve closure performance

### PR DESCRIPTION
**Pull request by Itee**
Edit: Next to #10563 and #10564 !

This PR fix all object that aren't protected yet against closure circular reference bug #10547 (without affecting library parsing performances). And improve performance for all closure that are now protected !

Take into account this bug type:

```javascript
(function () {

  // Create constructor a top level like
  // Foo constructor
  function Foo () {
    this.name = "Foo"
  }

  // Bar constructor
  function Bar () {
    this.name = "Bar"
  }

  // Baz constructor
  function Baz () {
    this.name = "Baz"
  }

  function Qux () {
    this.name = "Qux"
  }

  var closure = (function(){

    // Instancing BEFORE declaring prototype
    var foo = new Foo();
    var bar = new Bar();
    var baz = new Baz();
    var qux = new Qux();

    return function() {

      try {
        foo.sayIt();
      } catch(err) {
          console.error(err);
      }

      try {
        bar.sayIt(); // BOOM !
      } catch(err) {
        console.error(err);
      }

      try {
        baz.sayIt();
      } catch(err) {
        console.error(err);
      }

      try {
        qux.sayIt(); // BOOM !
      } catch(err) {
        console.error(err);
      }

    }

  })()


  Foo.prototype.sayIt = function fooSayIt() {
    console.log("I'm " + this.name);
  }

  Bar.prototype = {
    sayIt: function barSayIt() {
      console.log("I'm " + this.name);
    }
  }

  Object.assign(Baz.prototype, {
    sayIt: function bazSayIt() {
      console.log("I'm " + this.name);
    }
  });

  Qux.prototype = Object.assign( {
    sayIt: function quxSayIt() {
      console.log("I'm " + this.name);
    }
  } );

  // Instancing AFTER declaring prototype
  var foo = new Foo();
  foo.sayIt();

  var bar = new Bar();
  bar.sayIt();

  var baz = new Baz();
  baz.sayIt();

  var qux = new Qux();
  qux.sayIt();

  closure();

})()
```

and this benchmark about declaration/instantiation performances:

```javascript
var Benchmark = function ( title, test ) {

	var titleDom = document.createElement( 'div' );
	titleDom.style.fontWeight = 'bold';
	titleDom.textContent = title;
	document.body.appendChild( titleDom );

	var msDom = document.createElement( 'div' );
	document.body.appendChild( msDom );

	this.run = function () {

		var start = performance.now();

		test();

		msDom.textContent = performance.now() - start;

	}

};

// FOR INSTANCING
function _Foo() {}

_Foo.prototype.sayIt = function() {
	return "I'm _Foo"
}


function _Bar () {}

_Bar.prototype = {

	constructor: _Bar,

	sayIt: function () {
		return "I'm _Bar"
	}

}

function _Baz () {}

Object.assign( _Baz.prototype, {
	sayIt: function () {
		return "I'm Baz"
	}
});
////////////

var benchmarks = [

	new Benchmark( 'Declaring Foo.prototype INLINE', function () {

		function Foo() {}

		Foo.prototype.sayIt = function() {
			return "I'm Foo"
		}

	} ),

	new Benchmark( 'Declaring Bar.prototype LITERAL', function () {

		function Bar () {}

		Bar.prototype = {

			constructor: Bar,

			sayIt: function () {
				return "I'm Bar"
			}

		}

	} ),

	new Benchmark( 'Declaring Baz.prototype ASSIGN LITERAL', function () {

		function Baz () {}

		Object.assign( Baz.prototype, {
			sayIt: function () {
				return "I'm Baz"
			}
		} );

	} ),

	new Benchmark( 'Instancing Foo.prototype INLINE', function () {

		for ( var i = 0; i < 1000000; i ++ ) {

			var foo = new _Foo()

		}

	} ),

	new Benchmark( 'Instancing Bar.prototype LITERAL', function () {

		for ( var i = 0; i < 1000000; i ++ ) {

			var foo = new _Bar()

		}

	} ),

	new Benchmark( 'Instancing Baz.prototype ASSIGN LITERAL', function () {

		for ( var i = 0; i < 1000000; i ++ ) {

			var foo = new _Baz()

		}

	} )

];

function update () {

	for ( var i = 0, l = benchmarks.length; i < l; i ++ ) {

		benchmarks[ i ].run();

	}

	setTimeout( update, 3000 );

}

update();
```

All the advantages, without the inconveniences !

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hmm, Bad news...

screen shot 2017-01-23 at 12 13 31

**Comment by mrdoob** [comment]
Maybe better to separate this in different PRs (one per folder in src) so it's easier to see what's going on.

**Comment by TristanVALCKE** [comment]
Ok... the qunit test was passed... but i will see what happen about WebGLRenderer...

Else, i take note about one PR per folder !

**Pull request merged**
