### PR TITLE
FBXLoader: support for alternate Euler orders and post rotation

### LINKED ISSUE #14520: FBXLoader: wrong transform on DAZ3D models
##### Description of the problem

Dear Ladies and Gentlemen,

We struggle with three js, DAZ3D and Mixamo, to release a new web browser game, it looks like the current blocker is in mixamo exporter or three js fbx importer (more likely).

As all mixamo's objects works with three js FBX loader we've decided to firstly export a FBX model to Mixamo from Daz Studio and then from Mixamo to Three JS to make process clear and to preserve formats compatibility.

However. In Mixamo, our FBX model works perfectly, but when we export it to Three JS from Mixamo, it looks very bad, however animation is recognized and some kind of animation is ongoing, but head, legs etc. are not in the proper place.

If you like "The Thing" from John Carpenter, then you will know what I mean ;)

Please see attachments for details 👍 
https://drive.google.com/open?id=1fBJX4v7T_lQ54f8wlGPTqr-3EZjs8Q9z

Attachment contains 2 models (one imported to mixamo, one exported from mixamo) and videos showing how well model behave in mixamo and how bad it looks in three js.. :(

Thank you !

##### Three.js version

Latest greatest!

##### Browser

- [x] All of them
- exclude internet explorer as it's not compatible with the fbx loader..

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

none..

Best Regards,
Karol

Software Architect
www.artificialworldsltd.com

### PR DESCRIPTION
**Pull request by looeee**
Fixes #14520 

Added support for alternate rotation orders based on [this reference](http://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref_class_fbx_euler_html). 

FBX appears to use extrinsic euler ordering, converted that to intrinsic ordering using @WestLangley's suggestions [here](https://github.com/mrdoob/three.js/issues/10485#issuecomment-269796099). 

Also created a `generateTransform` function which uses [this](https://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_10CDD63C_79C1_4F2D_BB28_AD2BE65A02ED_htm) reference to convert the FBX transform to three.js transform. It's now used to generate the transforms for geometry, models and animations, which were previously repeating code.

We're still ignoring the rotation pivot, scaling pivot, and scaling offset. Currently I have not come across any files that use these.

### CODE REVIEW

**Comment by looeee** [comment]
Also added support for Rotation offset. Although this sounds like a pivot transform, it appears to work well when applied at the Object3D level. 

For reference, we are currently applying the following transforms at the  geometry level, as they relate to a transformed pivot (in 3DS Max at least), and transforming the geometry works as a kind of fake pivot transform.  
* Geometric transform translation
* Geometric transform rotation
* Geometric transform scaling

**Comment by mrdoob** [comment]
Great!

**Comment by mrdoob** [comment]
Thanks!

**Comment by sarahannnicholson** [comment]
I'm very new to Three.JS and FBXLoader. 

Could I get an example on how to set the Euler orientation? 
I couldn't figure it out from the links above...

**Comment by looeee** [comment]
@sarahannnicholson the Euler order is defined in the FBX file and set automatically by the loader. 

Previously we are ignoring all but the default XYZ order. 

If you need any more help with this please use the [forum](http://discourse.threejs.org).

**Comment by looeee** [comment]
I forgot to mention in this PR - it's possible that some work still needs to be done to make non XYZ Euler order work with animations, however I don't have any models to test this with. If anybody encounters problems with this please open a new issue.

**Comment by WahlbergRu** [comment]
This https://github.com/ckddbs/three-fbx-loader version and you version have difference? 
Can you load you version of fbx loader because I have bug 

1) after first add - http://joxi.ru/Vm6WOWCD351j2Z
2) after second add - http://joxi.ru/5mdZOZHkqOPaA1
3) after 3nd add - http://joxi.ru/Q2KMRMf4Oo3grj
4) after 4nd add - http://joxi.ru/52adadc4laBDm0 http://joxi.ru/823QaQtJzbMXrO

**Comment by looeee** [comment]
> This https://github.com/ckddbs/three-fbx-loader version and you version have difference?

That version hasn't been updated in 5 months, so yes, there'll be some differences. Just stick with using the version from this repo.

**Comment by WahlbergRu** [comment]
How I can install you version? Because I write with typescript and load module with npm.

**Comment by looeee** [comment]
@WahlbergRu this is not the place to ask for help. Ask on the forum instead:
https://discourse.threejs.org

Search first though because I'm sure this has been asked many times already.

**Pull request merged**
