### PR TITLE
NodeMaterial: Playground ( WebGPU version )

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/22868

**Description**

https://raw.githack.com/sunag/three.js/dev-scene-apply/examples/?q=playground#webgl_materials_nodes_playground

image

- add `material.dispose()` support to `WebGPU` ( https://github.com/mrdoob/three.js/commit/c00e1a3fa8e3fe2740a84c645d4d1492b83ef29c )  /ping: @Mugen87 
- add `outputEncoding` ( `sRGBEncoding` ) support to `WebGPU`
- add `bvec3` support to `WebGPU`
- `ColorSpaceNode`: Add support to `LinearTosRGB`
- Update `origin-trial` token (threejs.org)
- Create `PhysicalMaterialFunctions` for some `PBR` functions ( https://github.com/mrdoob/three.js/commit/a8cb423f369a61eee4f1e05f1dda2e682760c40d )
- `ShaderNode`: add `normalGeometry`
- add `lessThanEqual` function for `WebGPU`
- Minor fixes

This contribution is funded by [Google via Igalia](https://igalia.com).

### CODE REVIEW

**Comment by Mugen87** [comment]
> add material.dispose() support to WebGPU ( c00e1a3 )

The support for `Material.dispose()` was already implemented. Do you mind explaining in more detail your changes in that context?

**Comment by sunag** [comment]
> The support for Material.dispose() was already implemented. Do you mind explaining in more detail your changes in that context?

The old approach of `Material.dispose()` don't work done It was focused only on material pipeline but `WebGPU` work with the logic of `RenderItem`  for all include `NodeBuilder` and `Bindings`. This approach fix manly this issue, disposing all pipeline depedencies.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
It seems this PR broke the box with the compressed texture in `webgpu_sandbox`. It now looks like so:

image

**Comment by sunag** [comment]
> It seems this PR broke the box with the compressed texture in webgpu_sandbox. It now looks like so:

Yeah, I will fix it.

**Pull request merged**
