### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
Switched to a different skybox and cleaned up the code.

I've also removed `skyboxsun25degtest.png` since it is not used in the examples any more. The format of the skybox was unfavorable in general. `CubeTextureLoader` wants this for example: `nx.jpg`, `ny.jpg`, `nz.jpg`, `px.jpg`, `py.jpg`, `pz.jpg`.

### CODE REVIEW

**Comment by Mugen87** [comment]
http://rawgit.com/mugen87/three.js/dev4/examples/webgl_shaders_ocean.html

**Comment by mrdoob** [comment]
Hmm, the skybox worked well with the example though.
How about breaking up the image in different files instead?

**Comment by Mugen87** [comment]
Okay 👍

**Comment by Mugen87** [comment]
Done!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
