### PR TITLE
Examples: Update skinning + morph example.

### PR DESCRIPTION
**Pull request by donmccurdy**
Per https://github.com/mrdoob/three.js/issues/14737.

Removes `knight.js`. There are fewer GUI options here than in the original, although I think this communicates the main functionality clearly. And, there are too many animations to provide that many options for each. I would also be fine with reorganizing or renaming examples like 

- `animation / skinning / blending`
- `animation / skinning / morph`

Arguably this could be a "blending" example. 🤔

Here is the modified `.blend` file, for posterity: 
[RobotExpressive.blend.zip](https://github.com/mrdoob/three.js/files/2513000/RobotExpressive.blend.zip)

### CODE REVIEW

**Comment by donmccurdy** [comment]
Demos:

- https://raw.githack.com/donmccurdy/three.js/feat-skinning-robot-demo/examples/webgl_animation_skinning_morph.html
- https://raw.githack.com/donmccurdy/three.js/feat-skinning-robot-demo/examples/webgldeferred_animation.html

**Comment by donmccurdy** [comment]
Hm I'm not sure we should use the word "blending" in that sense. I'd assumed the intended meaning for this example was to show blending between multiple animation clips (regardless of what type of deformation the clips used). And morph targets are sometimes also called "blend shapes". 😅

**Comment by Mugen87** [comment]
Yes, unfortunately the terminology is not consistent. My previous comment refers to "Real-Time Rendering (Tomas Akenine-Möller, Eric Haines, Naty Hoffman)" where both animation techniques are discussed and named in that way.

**Comment by looeee** [comment]
I'd avoid using blending at all and go for the most commonly names for these techniques:

`animation / skinning / morph`

IMO we should think about how easily these examples can be found from a search engine and what words people are likely to use when searching. This example will be most useful for people searching for something like 'how to combine skinning and morph target animation in three.js'.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
