### PR TITLE
Fix GLTFExporter processAnimation() .bones path case

### PR DESCRIPTION
**Pull request by takahirox**
This PR fixes `GLTFExporter` `processAnimation()` `*.bones` path case.
If the path is `*.bones[boneName].*` we should find a track node(bone) from `.skeleton.bones`.

I exposed `findBone()` function of `PropertyBinding` and use if from `GLTFExporter`.

/cc @fernandojsg @donmccurdy

### CODE REVIEW

**Comment by donmccurdy** [comment]
The behavior here looks the same as before, so I see no problem with your change, but a couple questions:

1. Why does PropertyBinding need to handle bones with a special `objectName.bones[boneName].rotation` syntax? Why not just `boneName.rotation` for example? Is that because the bone could be outside of the root node's tree?
2. Why do we only check if `root.skeleton` exists? Couldn't `root.children[2]` be a SkinnedMesh, and we'd still want to check its bones too? Seems like the call to `findBone` could be inside the `searchNodeSubtree()` recursion?

^These aren't blocking. I haven't looked at this bit of code before and I'm confused, so I'm just asking anyway. 😅 

Just one actual suggestion though — couldn't we keep `findBone` as a private or inlined method and call `findNode` a second time? Would be nice to avoid adding an extra bit of API.

```js
if ( trackBinding.objectName === 'bones' ) {

  trackNode = THREE.PropertyBinding.findNode( trackNode, trackBinding.objectIndex );

}
```

**Comment by takahirox** [comment]
> Why does PropertyBinding need to handle bones with a special objectName.bones[boneName].rotation syntax? Why not just boneName.rotation for example? Is that because the bone could be outside of the root node's tree?

I'm not sure the original indentation, but I suppose "bone could be outside of the root node's tree" would be one of the reasons.

> Why do we only check if root.skeleton exists? Couldn't root.children[2] be a SkinnedMesh, and we'd still want to check its bones too? Seems like the call to findBone could be inside the searchNodeSubtree() recursion?

> Just one actual suggestion though — couldn't we keep findBone as a private or inlined method and call findNode a second time? Would be nice to avoid adding an extra bit of API.

About this PR, I just wanna follow the current `PropertyBinding` rule, that is find node and then find bone  from the skeleton of the node. (findNode() goes down and searches its children so I couldn't use.)

And in general, (perhaps) bone's name is unique in a skeleton but two or more objects in a scene graph can have the same name. Besides that (also perhaps in general) one skinning animation clip expects to be applied to a skeleton, not to be applied to across two or more skeletons.

**Comment by donmccurdy** [comment]
Ok, agreed let's not go down the graph with bone search then, at least not in this PR.

For the second part, I still think you could call `findNode` a second time instead of creating `findBone`, because (1) we already know `trackNode` is a skinned mesh, (2) we already know the bone exists, and (3) `findNode()` will exit early in that case.

**Comment by takahirox** [comment]
> (2) we already know the bone exists,

How can we know the target bone (= the bone name is `trackBinding.objectInde`) exists beforehand?

**Comment by donmccurdy** [comment]
Assuming the AnimationClip is valid, that would have to be true wouldn't it? If we want to ensure that we fail gracefully even if the clip were bad, I suppose the safer alternative would be:

```js
if ( trackBinding.objectName === 'bones' ) {

  trackNode THREE.PropertyBinding.findNode( trackNode, trackBinding.objectIndex );

  // If the result isn't a bone under trackNode but we got a descendant with the same name,
  // unset trackNode so the clip is skipped with a warning.
  if ( !trackNode.isBone ) trackNode = undefined;

}
```

If that seems safer. But if the user passes animation clips into the exporter with no valid targets,

**Review by donmccurdy — APPROVED** [review]

**Comment by takahirox** [comment]
Ah, I didn't assume it's valid. I assumed there's a possibility that the skeleton of the target node doesn't have the target bone name. With this assumption and if another SkinnedMesh node under the target node has a bone the name of which occasionally has the target's bone name your code could get wrong bone.

BTW, becoming to think letting `Skeleton` have `findBone()` method, rather than `PropertyBinding` have , would be more straightforward API.

**Comment by donmccurdy** [comment]
Ok, either way is fine with me then. findBone on skeleton or skinnedmesh might be nicer.

**Comment by takahirox** [comment]
I'll make another PR for adding `findBone()` to `Skeleton` (or `SkinnedMesh`) because I wanna hear @mrdoob and other folks comments about it as well.

I close this PR til that `findBone()` PR is merged (or decided not to be merged) so far.

**Comment by mrdoob** [comment]
Adding that method to `Skeleton` instead sounds good to me 👌

**Comment by takahirox** [comment]
Reopned and updated.
This PR became very simple!

One thing I'm concerning, should we display warning if `trackNode` isn't `SkinnedMesh` though `objecetName` is `bones`?

**Comment by takahirox** [comment]
This'd be better?

    if ( trackBinding.objectName === 'bones' ) {

        if ( trackNode.isSkinnedMesh === true ) {
 
            trackNode = trackNode.skeleton.getBoneByName( trackBinding.objectIndex );

        } else {

            trackNode = undefined;

        }

    }

**Comment by takahirox** [comment]
Updated.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
