### PR TITLE
TSL: SetNode

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/26493#discussion_r1313456485

**Description**

Added `node.set*()` syntax to TSL:

Cases of use:

```js
let vec = vec4( ...values );

// single-set
vec = vec.setW( 1 ); // equivalent to: vec4( vec.x, vec.y, vec.z, 1 );

// multi-set
vec = vec.setXY( 1 ); // equivalent to: vec4( 1, 1, vec.z, vec.w );

// multi-set2
vec = vec.setXY( vec2( 1, 2 ) ); // equivalent to: vec4( vec2( 1, 1 ), vec.z, vec.w );
```

### CODE REVIEW

**Comment by LeviPesin** [comment]
I still don't really see why we can't just implement `SplitNode.assign()`?
I can file a PR alternative to this if it would be OK.

**Comment by mrdoob** [comment]
> I still don't really see why we can't just implement `SplitNode.assign()`?

Every time we try to explain something to you, you fight our arguments instead of trying to understand 😅

**Comment by LeviPesin** [comment]
It's about the same from my POV 😅 I understand that this is rather an API preference, and I understand that, for example, BufferGeometry classes have `.set()` methods -- but my arguments are that 1) for example, Vector classes have property accessors, 2) such a syntax would be more powerful, 3) it betters reflects the shader code.

**Comment by aardgoose** [comment]
Only GLSL implements multi value assignments like 

vec3 a;
a.xy = vec2( 1, 1 );

It isn't permitted in WGSL (yet).

https://github.com/gpuweb/gpuweb/issues/737

**Comment by sunag** [comment]
@LeviPesin this seems to be the best solution for inline assigns, since it follows the expected flow and is within the Three.js API, let's keep an eye on your approach, it would be an alternative but not a replacement since your approach is not inline.

**Comment by LeviPesin** [comment]
Well, my PR has two approaches, one of which is also inline... But I'm fine with keeping them as alternative approaches, if we find one especially complex or useless we could still remove it at any time.

**Pull request merged**
