### PR TITLE
Rollup: Replace addons three.module.js dependency.

### LINKED ISSUE #20387: Custom build produces files too large
Simply trying to add `OrbitControls` to `three.min.js` by following the instructions in the Wiki. Working from a fresh clone of the master branch of r120 on a Windows 10 machine with current Node and npm. Added the line

`export { OrbitControls } from '../examples/jsm/controls/OrbitControls.js';`

to `src/Three.js` and ran `npm install` followed by `npm run build-closure`. The resulting file is twice as big as expected, and further runs of the build keep increasing file sizes. Either something critical is missing from the Wiki instructions or there is an error somewhere.

### PR DESCRIPTION
**Pull request by mrdoob**
This allows producing custom builds that include addons.

For example, adding `OrbitControls`:
1. Add `export { OrbitControls } from '../examples/jsm/controls/OrbitControls.js';` in `./src/Three.js`.
2. Run `npm run build`

Fixes #20387

### CODE REVIEW

**Comment by Mugen87** [comment]
Unrelated to this PR but related to the rollup build^^: I've noticed lately the following warning when performing the build:

> (!) Broken sourcemap
[ROLLUP] https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
[ROLLUP] Plugins that transform code (such as 'at position 5') should generate accompanying sourcemaps

Unfortunately, I'm not sure _when_ this warning appeared for the first time...

**Comment by DefinitelyMaybe** [comment]
I'd love to get into writing up some documentation around folks creating custom builds and/or tweeking three.js for specific applications

**Comment by mrdoob** [comment]
@Mugen87 Weird, I'm not getting that 🤔

**Comment by Mugen87** [comment]
When removing `build/three.js` and `build/three.min.js` and updating `package.json`, I've noticed `addons()` and wondered if we still need it. AFAICS, the helper was originally implemented in 2020 when we have not used import maps yet, see https://github.com/mrdoob/three.js/issues/20387#issuecomment-696545851.

Now with import maps in place and a pure ESM code base, can we simplify `rollup.config.js` and remove the `addons()` helper?

**Pull request merged**
