### PR TITLE
Editor: fixes scripts container layout error.

### PR DESCRIPTION
**Pull request by linbingquan**
I created a script for `Mesh`, and then delete it, but `script = []`, I add condition for `scriptsContainer`.

image

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice catch!

**Comment by mrdoob** [comment]
I think you can just do this though?

```js
if ( scripts !== undefined && scripts.length > 0 ) {
```

**Comment by linbingquan** [comment]
> I think you can just do this though?
> 
> ```js
> if ( scripts !== undefined && scripts.length > 0 ) {
> ```

@mrdoob  https://github.com/mrdoob/three.js/pull/15201/commits/932b6236eba351b9ad42408b9763d62d911fa6bb

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
