### PR TITLE
Add area light to GLTFLoader with KHR_lights_pbr extension

### PR DESCRIPTION
**Pull request by tehbelinda**
I'm trying to get a scene with area lights into Three.js, so this uses the experimental RectAreaLights and an extension to the still unfinalised KHR_lights_pbr extension, (which was recently updated from KHR_lights into two common and pbr versions - https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/14592d92838dde10f3a38662ea3a83283e3e1bce)

Since this is meant to be physically based, I've set decay to 2 as per the docs `In physically correct mode, decay = 2 leads to physically realistic light falloff. The default is 1.` (Unfortunately the docs also say that decay is not yet implemented for RectAreaLights - if anyone can give any beginner friendly suggestions on how to help with that, let me know)

I wasn't sure what other parameters were still relevant in the pbr version, so they're mostly copied over from the existing KHR_lights extension implementation.

Example on codepen with a scene exported from Blender: https://codepen.io/anon/pen/PENaVJ
Related Blender GLTF exporter issue: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/136

### CODE REVIEW

**Comment by tehbelinda** [comment]
Discussion on actual GLTF spec is still ongoing in so this may not be very stable yet... https://github.com/KhronosGroup/glTF/issues/945

**Comment by donmccurdy** [comment]
You are very thorough! 😄 Per previous comment, I'd be glad to include this if there's consensus on the [glTF lights discussion](https://github.com/KhronosGroup/glTF/issues/945), but until then I think we'll need to wait before merging.

If you need a quick fix for some project, I'd suggest using Blender's custom properties, which will be preserved in glTF and passed into each three.js object's `.userData` property.

**Comment by tehbelinda** [comment]
Haha yes I really wanted to find out if it would work at all, which led to this 3 github repository cross linking fun...

Thanks for the suggestion! I'll try that in the meantime

**Comment by donmccurdy** [comment]
Going to close this for now — finishing up the `KHR_lights_*` extension is on the glTF short list but even so it's going to take some time. Thanks for the suggestion of area lights!

**Pull request closed without merging**
