### PR TITLE
SpotLightHelper: correctly orient helper to face light target

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes this issue mentioned in https://github.com/mrdoob/three.js/issues/14773#issuecomment-441696262.

This change is similar to #15200 and is required as a result of #14517.

### CODE REVIEW

**Review by rowild — APPROVED** [review]
Tested and works.

**Comment by rowild** [comment]
Wow, that was quick! Thank you very much, @WestLangley !
Tested it and it works perfectly fine! Hope I didn't do anything wrong?

**Comment by WestLangley** [comment]
>Hope I didn't do anything wrong?

You were very helpful.  :-)

**Comment by WestLangley** [comment]
The helper should point to the target's world position.

This PR requires that you rebuild the library.

**Comment by rowild** [comment]
I added the changes directly to the SpotLightHelper script on my local setup (with webpack 4).

I am only "2 days old" when it comes to Three, so I have yet no idea what the "world position" is. All i can say is, that it looks different between v95 and v98. While in 95 the cone of the SpotLighthelper points directly to the center of the box, in v98 it points to the bottom (and even lower) of the box...

The orientation, though, is corrected now. That's great!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I guess we should close #14738?

**Comment by WestLangley** [comment]
@mrdoob I guess. The code is now different, so who knows...

**Pull request merged**
