### PR TITLE
WebGLRenderTarget: convert to es6

### PR DESCRIPTION
**Pull request by alexfriesen**
Related issue: #19986

**Description**

I converted WebGLRenderTarget, WebGLMultisampleRenderTarget and WebGLCubeRenderTarget to es6 classes.

### CODE REVIEW

**Comment by Mugen87** [comment]
It seems these classes are already covered by an existing (still open) PR #20101.

**Comment by mrdoob** [comment]
Seems like #20101 has unresolved conflicts though. Merging this one.

**Comment by mrdoob** [comment]
Thanks!

**Comment by johnnyweegie** [comment]
just could I have a hint how to catch up regarding THREE.WebGLCubeRenderTarget

**Comment by alexfriesen** [comment]
> just could I have a hint how to catch up regarding THREE.WebGLCubeRenderTarget

Everything should be working as usual. 
Docs are here: https://threejs.org/docs/index.html#api/en/cameras/CubeCamera
There is also an example how to use it.

**Pull request merged**
