### PR TITLE
Add BSP algorithm for SVGRenderer

### PR DESCRIPTION
**Pull request by the-owl**
SVGRenderer has some issues with z-sorting: painter sort which is currently used sometimes gives wrong results and it can't deal with intersecting objects. As a solution, I've implemented an algorithm that builds a BSP tree and splits objects into smaller pieces. Here is an [example](https://jsfiddle.net/kpoopxc3/6/) (set `useBSP = false` to see the difference).
It only supports triangles and lines, but it can probably be improved in future.

### CODE REVIEW

**Comment by mrdoob** [comment]
Very nice! The good thing is that this also works for `CanvasRenderer`! I guess it doesn't handle UVs though?

**Comment by the-owl** [comment]
I didn't expect this to work with `CanvasRenderer`, so I didn't add UVs handling because `SVGRenderer` doesn't support textures. It also could be improved in future.

**Comment by mrdoob** [comment]
I see... Do you think you could add UVs to this PR?

**Comment by the-owl** [comment]
I've added UV handling and an option for `CanvasRenderer`

**Comment by ToJans** [comment]
This might be a long shot, but if I understood correctly transparent object rendering might also benefit from this?

**Comment by Mugen87** [comment]
Not sure this PR is still necessary. Just because `SVGRenderer` seems a bit deprecated. In the meanwhile we can render `SVG` files with WebGL thanks to `SVGLoader` (see #13616).

Besides, when reading the code I've noticed a lot of objects are created when the BSP tree is computed per frame. This approach might lead to noticeable GC pressure. Without knowing the performance implications, it seems to be hard to merge such a change...

**Comment by Mugen87** [comment]
Closing for now.

**Pull request closed without merging**
