### PR TITLE
Add introspectable Stride and TypeArrays to math primitives

### PR DESCRIPTION
**Pull request by bhouston**
This PR adds two variables to a number of the math primitives, TypedArray, which indicates what type is required to flatten the primitive into an typed ArrayBuffer, and TypedStride, which is the number of elements required by the math primitive.  Typed that have these two parameters are also expected to have the functions "toArray" and "fromArray" to allow for easy packing into flat arrays.

This allows for a lot of neat automation based on introspection.

For example:

```
THREE.Vector3.TypedArray = Float32Array;
THREE.Vector3.TypedStride = 3;
```

I also added a THREE.Arrays class within the /math library for utility functions related to these introspectionable types.

The first function on THREE.Arrays is: "THREE.Arrays.copyPrimitivesToTypedArray".  I used it already to replace a bunch of type specific copy functions on BufferAttribute.

I am seeing no performance difference.

### CODE REVIEW

**Comment by bhouston** [comment]
This PR makes ThreeJS /src smaller by 28 lines, while making the library smarter.

I have other classes already written that make use of this form of introspection on math primitives.  But I figured I'd try this simple PR first.

**Comment by SuberFu** [comment]
A bit on performance, since those two values are essentially constant, won't it be better, performance-wise, to assign them to the prototype?
THREE.Vector3.prototype.TypedArray = Float32Array;
THREE.Vector3.prototype.TypedStride = 3;
Granted, I'm not 100% sure on the black art of javascript optimization, but the use of prototype may help with avoiding the javascript engine from assigning those two values each time it needs to create a new THREE.Vector3 object.

**Comment by tschw** [comment]
@SuberFu 
> The use of prototype may help with avoiding the javascript engine from assigning those two values each time it needs to create a new THREE.Vector3 object.

On the class / constructor function, they're just as static as on the prototype (or maybe even more static), so shouldn't be much of a performance difference.


```javascript
THREE.Vector3.prototype.TypedArray = Float32Array;
THREE.Vector3.prototype.TypedStride = 3;
```

However, I still like the idea because it think it's more practical to go `myValue.TypedStride` instead of `myValue.constructor.TypedStride`. It also yields shorter code.

**Comment by mrdoob** [comment]
Hmm, not a big fan of this... Makes the code a bit convoluted...

**Comment by tschw** [comment]
@mrdoob 
> Hmm, not a big fan of this... Makes the code a bit convoluted...

About the suggestion to use prototype instead of the constructor or of this PR in general?

**Comment by mrdoob** [comment]
No, no. The whole PR.

**Comment by bhouston** [comment]
I'm fine with that.

**Comment by tschw** [comment]
@mrdoob 
Not sure about the other changes in this PR, but I'm talking about the constants: It's extraordinarily useful and I'd love this to be provided *somewhere*. In fact, a similar submission had been on my list as well.

We currently work around the lack of it in Animation.

And it's broadly useful in all places that require automation or caching, because it allows you to calculate buffer sizes. The `prototype` approach plus shorter names would make it fairly minimal, e.g.

```javascript
Array: Float32Array,
Size: 3,
```

for `THREE.Vector3`...

Is there any way to make something like this more likeable to you?

**Comment by bhouston** [comment]
> We currently work around the lack of it in Animation.

This PR was submitted this in preparation of adopting the technique to reduce the complexity with the animation framework.

**Comment by bhouston** [comment]
@tschw I have another bit of code I haven't submitted that contains a "BlockArray" class that allows for fast growable arrays that are also efficient, similar in design to the memory manager classes:

https://github.com/mrdoob/three.js/compare/dev...bhouston:block_array

I've used variants of this BlockArray class for optimizing situations where I do not know the size of the final array over near 14 years, it is awesome and efficient.

**Comment by mrdoob** [comment]
I think the problem was modifying `BufferAttribute`. I made these functions that way for performance reasons. In the past, similar refactoring resulted in performance hits.

I'm not sure `Animation` requires `Face3` to have `fromArray()` and `toArray()` so the PR didn't seem to have a clear purpose from my point of view.

I don't question the intentions, but the PRs need to make sense in my mind (and be as simple as possible) in order to get my support.

**Comment by tschw** [comment]
@bhouston 
> I've used variants of this BlockArray class for optimizing situations where I do not know the size of the final array over near 14 years, it is awesome and efficient.

I see. Interesting approach.

Linear memory rocks. I guess you may know [Stroustroup's talk on "Why you should avoid Linked Lists"](https://www.youtube.com/watch?v=YQs6IC-vgmo), but I'm posting it anyway. Anyone who cares about fast code should be aware of the issue it discusses...

"Re-over-allocate & copy on grow, then shrink to fit" might not be too bad of a strategy either, just like `std::vector`. It's piece of cake to implement on top of JS typed arrays, and using proportional increments of the capacity, the cost for allocation and copying applies at logarithmic complexity and becomes negligible.

@mrdoob 
Thanks for summarizing the motivating factors for acceptance: **F**ast, **F**eature-driven, and **F**ocused then...

**Comment by bhouston** [comment]
> "Re-over-allocate & copy on grow, then shrink to fit" might not be too bad of a strategy either, just like std::vector. It's piece of cake to implement on top of JS typed arrays, and using proportional increments of the capacity, the cost for allocation and copying applies at logarithmic complexity and becomes negligible.

This pattern gets rid of the need to copy until the very end, a copy which would be needed if you want to shrink to size anyhow.  Thus while theoretically it may be similar in speed, this is more efficient in practice, there are no need to touch previous values at all during building except at the final copy.  BlockArray is O( e ), where is std::vector is O( e log e ) if you just want to grow and then shrink to the final size of e right?

I first wrote this to get around memory limitations in 32 bit memory models were std::vector approach was failing outright for us, we needed many +100MB arrays but the standard std::vector approach was fragmenting the hell out of the memory space and leading to premature oom falures -- specifically for this project in the 2003 timeframe: https://www.cs.ubc.ca/nest/imager/tr/2006/Batty_HRLE/  This pattern got around it very effectively.  You could change the block sizes so they are all identical in bytes even if the types are different to even better reduce fragmentation issues.  BlockArray only requires one contiguous +100MB array, were as std::vector requires two contiguous +100MB arrays during the shrink to size, one that could be significantly larger than the final required size.  BlockArray isn't as flexible as std::vector though, it is special case for building.

I think that now with 64 bit memory spaces memory fragmentation may be less of a concern - although Chrome still dies after you get past somewhere around ~1.5GB memory usage in 64 bit mode for some reason.  I do not know the cost of copies, I just now the above pattern is robust and fast.

My past experience was that Microsoft's std::vector is generally too costly for high performance applications, at least it used to always be a huge bottleneck, never completely sure why that was, probably just bad implementation.  There is this though that I've never used because it was just open sourced this year: https://github.com/electronicarts/EASTL

**Comment by tschw** [comment]
@bhouston 
> This pattern gets rid of the need to copy until the very end, a copy which would be needed if you want to shrink to size anyhow. Thus while theoretically it may be similar in speed, this is more efficient in practice, there are no need to touch previous values at all during building except at the final copy.

This may actually be the least of all concerns at exponentially increasing intervals.

> Seems O-notation is the same per doc here, even if there are more copies: http://www.drdobbs.com/c-made-easier-how-vectors-grow/184401375

Yep.

> I first wrote this to get around memory limitations in 32 bit memory models were std::vector approach was failing outright for us, we needed many +100MB arrays but the standard std::vector approach was fragmenting the hell out of the memory space and leading to premature oom falures -- specifically for this project in the 2003 timeframe: https://www.cs.ubc.ca/nest/imager/tr/2006/Batty_HRLE/ This pattern got around it very effectively. You could change the block sizes so they are all identical in bytes even if the types are different to even better reduce fragmentation issues. BlockArray only requires one contiguous +100MB array, were as std::vector requires two contiguous +100MB arrays during the shrink to size, one that could be significantly larger than the final required size. BlockArray isn't as flexible as std::vector though, it is special case for building.

`BlockArray` is actually more of a  `std::deque` (unfortunately that one doesn't let you bump the block size). [`push_back`](http://en.cppreference.com/w/cpp/container/deque/push_back) still goes under "amortized constant complexity".

When growing buffers, running out of address space certainly is an issue, so is fragmentation with more random access patterns, or on top of a low quality system allocator that fragments more than need be. Also, memory management is a lot easier to customize dealing with fixed-sized blocks, of course.

> I think that now with 64 bit memory spaces memory fragmentation may be less of a concern - although **Chrome still dies after you get past somewhere around ~1.5GB memory usage in 64 bit mode for some reason.** I do not know the cost of copies, I just now the above pattern is robust and fast.

**OK, this is a very convincing argument not to grow buffers that can become large, but go block-wise instead, even in JS, and even if it's a little less trivial.**

> My past experience was that Microsoft's std::vector is generally too costly for high performance applications, at least it used to always be a huge bottleneck, never completely sure why that was, probably just bad implementation. 

I guess that Dinkumware's `std::vector` (shipped with Visual C++) might be rather innocent, given the memory management in the MSVC runtime has a bit of a record - the Windows way to speed is to do the memory management yourself.

> https://www.cs.ubc.ca/nest/imager/tr/2006/Batty_HRLE/

Recognize the paper and have it somewhere on my disk - didn't know it was yours :).

> There is this though that I've never used because it was just open sourced this year: https://github.com/electronicarts/EASTL

Thanks for sharing!

**Pull request closed without merging**
