### PR TITLE
MTLLoader: Add default value for crossOrigin

### LINKED ISSUE #16438: Inconsistent Default CORS Behavior for MTLLoader?
**Problem:**
In [Line 168](https://github.com/mrdoob/three.js/blob/1bb18eb508323b80fe1c5b64265e7d6594167fff/examples/js/loaders/MTLLoader.js#L168) of `MTLLoader.js`:

	materialCreator.setCrossOrigin( this.crossOrigin );

`this.crossOrigin` is `undefined` by default for `THREE.MTLLoader`, so the default value given by `THREE.MTLLoader.MaterialCreator` at [line 210](https://github.com/mrdoob/three.js/blob/93e72ba7b24958ddb0652bd33171edd14ed2d693/examples/js/loaders/MTLLoader.js#L210):

	crossOrigin: 'anonymous',

is overwritten and ignored.

**Suggestion to Fix:**
Either `THREE.MTLLoader` should set a default value for `crossOrigin` as well or the `setCrossOrigin` method ([line 212](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/MTLLoader.js#L212)) of `THREE.MTLLoader.MaterialCreator` should return early for a null input.

### PR DESCRIPTION
**Pull request by spenceryue**
Fixes #16438 .

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/spenceryue/three.js/fix-missing-default/examples/webgl_loader_obj_mtl.html

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Why have you closed the PR?

**Comment by spenceryue** [comment]
Oops, my bad. I deleted the branch in my fork thinking it had gone through.

**Comment by Mugen87** [comment]
Never mind. Just create a new PR.

**Comment by Mugen87** [comment]
Then lest reopen it.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
