### PR TITLE
TextureLoader: Update created texture with default image if exist

### PR DESCRIPTION
**Pull request by Itee**
Currently the TextureLoader is unable to properly set the DEFAULT_IMAGE of Texture.

Some explanation before:

Currently the Texture object set the Texture.DEFAULT_IMAGE as Texture.image member in case where no image was given in arguments.

```javascript

function Texture( image, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy, encoding ) {

	Object.defineProperty( this, 'id', { value: textureId ++ } );

	this.uuid = _Math.generateUUID();

	this.name = '';

	this.image = image !== undefined ? image : Texture.DEFAULT_IMAGE;

        //...

}

Texture.DEFAULT_IMAGE = undefined;

```

This will result as an object with black texture un case like below:

```javascript
THREE.Texture.DEFAULT_IMAGE = new Three.ImageLoader().load('default_image.png')

var textureWithDefaultImageNotShown= new Three.Texture()
object.material.map = textureWithDefaultImageNotShown
```

This is not due to the lazy loading of the default_image, this is the same for base64 image too.
To show the imaged texture we need to call
```javascript
textureWithDefaultImageNotShown.needsUpdate = true
```
And this is the expected behavior because we don't want to see the default image of texture during the real image is loading. (Agree ? Maybe an option for that ???)

But, and this is the purpose of this PR. In case we are loading a texture using the TextureLoader like this:

```javascript
const textureLoader = new Three.TextureLoader()
//...
object.material.map = textureLoader.load( `/resources/images/myUnexistingImageTexture.jpg` )
```

**If the loader is unable to load the requested image, it will shown a black texture object instead of the default image. The default image goal is exactly for this type of use case.**

This PR allow to defaulting to the default texture image when the TextureLoader is unable to retrieve the requested image.

I hope this help,
Itee

### CODE REVIEW

**Comment by mrdoob** [comment]
I'm not sure I understand what the issue is. Can you create a jsfiddle?

**Comment by Mugen87** [comment]
I understand it like that: 

- Set a default image via `Texture.DEFAULT_IMAGE`
- Perform a failing texture loading process
- The default image is not rendered

This happens because `Texture.needsUpdate` is never set to `true`. You can easily verify this by setting the flag with a simple timeout.

https://jsfiddle.net/f2Lommf5/13409/

@Itee Are you aware that the `onError()` callback is not fired if a 404 occurs? The demo illustrates this. Since a 404 is the most common reason for a loading failure, I'm not sure the PR is okay like that.

**Comment by Itee** [comment]
Here the [fiddle](https://jsfiddle.net/jutLgv4h/36/)

You need to play with line 53 to apply the same result than this PR

**Comment by Mugen87** [comment]
Interesting. Yeah, right now the usage of `Texture.DEFAULT_IMAGE` is somewhat restricted because of the dependency to `needsUpdate`.

**Comment by Itee** [comment]
@Mugen87 This is exactly the idea and currently onError() is called when get a 404 !

**Comment by Itee** [comment]
Updated [fiddle ](https://jsfiddle.net/jutLgv4h/59/) with an alternative method that do not warn on needsUpdate

**Comment by Itee** [comment]
Your onError is pluged in onProgress methods that why you do not receive error envent ;)

**Comment by Mugen87** [comment]
@Itee Thanks for mentioning this 😊 . I've missed on `undefined`.

**Comment by Itee** [comment]
So what about this fallback default feature ?

**Comment by WestLangley** [comment]
I implemented an automatic _fallback_ default texture image -- a 1x1 white pixel -- yesterday, and it works well, preventing black renderings if the desired texture does not load.

Thing is, for normal maps, for example, one would want the default to be medium blue, instead. So I am not sure this fallback approach makes sense.

However, I think if the user specifies `Texture.DEFAULT_IMAGE`, it makes sense for the loader to use it if the desired texture does not load. That way the error handling is the user's responsibility.

**Comment by Itee** [comment]
@WestLangley 

> I implemented an automatic fallback default texture image -- a 1x1 white pixel -- yesterday, and it works well, preventing black renderings if the desired texture does not load.

Where could i see this implementation ? I'm interesting by any texture fallback at the current time.

> However, I think if the user specifies Texture.DEFAULT_IMAGE, it makes sense for the loader to use it if the desired texture does not load. That way the error handling is the user's responsibility.

This is why this PR and allow a certain way of automation for the user that specify and expect a default image for broken textures.

**Comment by Mugen87** [comment]
> So what about this fallback default feature ?

I'm unsure about the implementation. I do not mean this negatively but the proposed solution feels like a hack. I was recently faced with a similar situation (see #13725). The conclusion was that there is no simple/obvious solution in order to solve the conceptual problem which is in some sense caused by a design limitation. Like I've mentioned before the relationship between `Texture.DEFAULT_IMAGE` and `Texture.needsUpdate` makes it hard to provide a solution which feels well. 

Maybe the easiest way in order to ensure consistency is to remove `Texture.DEFAULT_IMAGE`. As far as I can see, the code does not use this function once.

**Comment by Itee** [comment]
The DEFAULT_IMAGE  itself is hacky. And undocumented in Texture page. The alternative that i proposed in the fiddle could do the trick and allow the user to choose the defaulting image for different objects.

```javascript
var myDefaultImage = new Three.ImageLoader().load('myDefaultImage.png')

var material = new THREE.MeshPhongMaterial({
      map: textureLoader.load('unexistingImage.png', undefined, undefined, (error)=>{
        console.error('Error: unable to load texture... Using default image instead !')
        material.map = myDefaultImage
        material.map.needsUpdate = true
      })
    });
```


This could be the correct (and actual) work around, that doesn't throw any warning. In such case maybe we should remove `Texture.DEFAULT_IMAGE`, yes. Want you a PR to remove it ?

**Comment by Mugen87** [comment]
> Want you a PR to remove it ?

Let's wait what @mrdoob thinks about this issue...

**Pull request closed without merging**
