### PR TITLE
add support for Lightimport in VRML

### PR DESCRIPTION
**Pull request by polygontwist**
for import PointLight and SpotLight. An AmbientLight is emitted when in the name "AmbientLight" occurs.
exampel:

```
vrml-Code:
DEF Licht_AmbientLight Transform {
  translation 0 4.274257 0
  children [ 
    DEF LIGHT_Licht_AmbientLight PointLight {
      location 0 0 0
      radius 100000000
      color 0.34902 0.34902 1
      intensity 0.23
      on TRUE
    }
  ]
}

DEF Licht_1spot Transform {
  translation -56.342838 57.6591 -58.975361
  rotation -0.244504 0.769274 0.590284 -0.987861
  children [ 
    DEF LIGHT_Licht_1spot SpotLight {
      location 0 0 0
      direction 1 0 0
      cutOffAngle 0.587197
      radius 100000000
      color 0.47451 0.823529 1
      intensity 1
      on TRUE
    }
  ]
}

DEF Licht Transform {
  translation -49.414658 88.717239 51.611542
  children [ 
    DEF LIGHT_Licht PointLight {
      location 0 0 0
      radius 100000000
      color 1 0.807843 0.560784
      intensity 1
      on TRUE
    }
  ]
}
```

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind targeting the `dev` branch instead?

**Comment by polygontwist** [comment]
No, you can do that. I do not know github so well.

**Comment by mrdoob** [comment]
Unfortunately you'll need to do a new PR, but this time targeting the `dev` branch instead.

**Comment by polygontwist** [comment]
Ok, I'll try it

**Comment by mrdoob** [comment]
#10177

**Pull request closed without merging**
