### PR TITLE
SVGLoader: Fix hole identifier.

### LINKED ISSUE #24780: SVGLoader: Exception in `isHoleTo` when loading an SVG file
**Describe the bug**

When using `SVGLoader` to load a particular SVG file ([file attached](https://user-images.githubusercontent.com/1017304/195216421-5677c5d5-85fd-44a5-9721-3abc176fec05.svg)), an exception is thrown in the internal `isHoleTo` function, at [this line](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/SVGLoader.js#L2019):

`TypeError: Cannot read properties of undefined (reading 'isCW')`

Full stack trace:
```
SVGLoader.js:2019 Uncaught TypeError: Cannot read properties of undefined (reading 'isCW')
    at isHoleTo (SVGLoader.js:2019:57)
    at SVGLoader.js:2110:41
    at Array.map (<anonymous>)
    at SVGLoader.createShapes (SVGLoader.js:2110:31)
    at main.js?t=1665531910670:16:26
```

**To Reproduce**

See code and JS Fiddles below.

The SVG file is [available here](https://user-images.githubusercontent.com/1017304/195216421-5677c5d5-85fd-44a5-9721-3abc176fec05.svg). It's also embedded in the example below.

(the specific path that's creating the exception was extracted from a larger SVG -- this is why the .svg file in itself doesn't look that "great"..) :-)

***Code***

```js
import { SVGLoader } from "three/addons/loaders/SVGLoader.js";

const loader = new SVGLoader();

let loadedSvg = loader.parse(`
  <svg xmlns="http://www.w3.org/2000/svg">
    <g transform="matrix(5.0000,0.0000,0.0000,5.0000,100,100)">
        <path d="M 5.6 -9.9 L 5.4 -11.9 M 2 -7.3 L 1.7 -6.7 M 2 -7.3 L 2 -7.3 M 2 -7.2 L 2 -7.3 M 2 -7.2 L 2 -7.2 M 2 -7.5 L 2 -7.5 L 1.9 -9.9 L 2.2 -8 L 2.9 -9.6 M 2.4 -8.4 L 2.3 -7.7 L 2.0 -7.2 M 4.4 -6.3 L 4.4 -7.7 L 3.6 -5.4 L 2.7 -2.6 L 3.2 -3.4 L 3.8 -4.7" style="" transform=""/>
    </g>
  </svg>
`);

const path = loadedSvg.paths[0];

// the following line will raise an exception
const shapes = SVGLoader.createShapes(path);

```

***Live example***

Both fiddles below (latest & dev) show the issue:
* [jsfiddle-latest-release](https://jsfiddle.net/gregsadetsky/su710ykn/20/)
* [jsfiddle-dev](https://jsfiddle.net/gregsadetsky/pc2os8ut/1/)

**Expected behavior**

The SVG file should be loaded without any errors.

**Platform:**

 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - Three.js version: dev, 0.145.0

### PR DESCRIPTION
**Pull request by Ttommeke**
Fixed https://github.com/mrdoob/three.js/issues/24780.

**Description**

SVG path filter on holes with 2 or less points messed up the hole identifier.

### CODE REVIEW

**Comment by Ttommeke** [comment]
Fix for: #24780

**Comment by Mugen87** [comment]
It seems your branch is still way behind `dev` which produces merge conflicts. Probably best if you rebase.

**Comment by Mugen87** [comment]
https://raw.githack.com/Ttommeke/three.js/isHoleFix/examples/webgl_loader_svg.html

**Comment by Mugen87** [comment]
It seems the original issue of the OP is fixed now 👍 .

However, when loading `singlePointTest3.svg`, the output looks different compared to opening the SVG directly in the browser. Is this a known issue?

**Pull request merged**
