### PR TITLE
Manual: updated monaco-editor@0.34.1

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #XXXX

**Description**

Removed `manual/3rdparty/monaco-editor` dir.

Updated `monaco-editor` lastest version with `https://unpkg.com/monaco-editor@0.34.1/min/vs` link.

I tested in my local computer, it can work, if has any problem, please tell me.

### CODE REVIEW

**Comment by epreston** [comment]
So `manual` does not work offline, is broken, and still links the following in some files.

```
<script src="/manual/3rdparty/monaco-editor/min/vs/loader.js"></script>
```

**Comment by epreston** [comment]
Two options:

- fix all references to use the package manager 
- update this one by downloading the most recent update and replacing the files

**Comment by epreston** [comment]
To get better tests, open the chrome dev tools, in the network tab click "disable cache".  Then click on each link to see any 404 errors.  Also, before you test, do a quick search for references in the code.  You using vscode ?

**Comment by linbingquan** [comment]
> So `manual` does not work offline, is broken, and still links the following in some files.
> 
> ```
> <script src="/manual/3rdparty/monaco-editor/min/vs/loader.js"></script>
> ```

Thank you for your reply.

Is that right?

```diff
--- a/manual/examples/resources/editor.html
+++ b/manual/examples/resources/editor.html
@@ -277,7 +277,7 @@ button:focus {
   </div>
 </div>
 </body>
-<script src="/manual/3rdparty/monaco-editor/min/vs/loader.js"></script>
+<script src="https://unpkg.com/monaco-editor@0.34.1/min/vs/loader.js"></script>
 <script src="editor-settings.js"></script>
 <script src="editor.js"></script>
```

**Comment by linbingquan** [comment]
> To get better tests, open the chrome dev tools, in the network tab click "disable cache". Then click on each link to see any 404 errors. You can view the console for javascript errors at the same time by pressing `esc` key. Also, before you test, do a quick search for references in the code. You using vscode ?

Thank you for your suggestion, I tested code it can be work in browser(with cache), I think it is no problem, my mistake...

**Comment by epreston** [comment]
Happy to help.

Are you sure everyone is ok with the `manual` being something that only works when connected to the internet ?

**Comment by mrdoob** [comment]
This one seems a bit more complicated...
I think we can give it a try and see if anyone complains.

**Pull request merged**
