### PR TITLE
Docs: Update Matrix4.compose()

### LINKED ISSUE #19334: Matrix4.compose wrong order?
##### Description of the problem
The documentation for **Matrix4.compose** states:

> "Sets this matrix to the transformation composed of position, quaternion and scale. Internally this calls makeRotationFromQuaternion( quaternion ) followed by scale( scale ), then finally setPosition( position )."

My understanding was always that you should scale before doing the rotation otherwise you can end up with unusual scaling (skewing).

So it should be (IMHO): scale, rotation, translation

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by cjbailey**
Remove outdated ref to how Matrix4.compose works in documentation

Fixed #19334.

### CODE REVIEW

**Comment by WestLangley** [comment]
Can you update the `/zh` file too?

**Comment by cjbailey** [comment]
> Can you update the `/zh` file too?

Done... I think

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：CJ Bailey <notifications@github.com>
发送时间：2020-05-11 04:36
主题：Re: [mrdoob/three.js] Docs: Update Matrix4.compose() (#19335)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Can you update the /zh file too?
Done... I think

**Pull request merged**
