### PR TITLE
Support BufferGeometry in ConvexObjectBreaker.

### LINKED ISSUE #14609: webgl_physics_convex_break.html: Support BufferGeometry
Support for Geometry is not required.

/ping - @yomboprime

### PR DESCRIPTION
**Pull request by yomboprime**
Added new `ConvexBufferObjectBreaker` Which supports only `BufferGeometry`'s, and new companion demo.

I left the old demo which supports only `Geometry`. Changed the colors of the new one to distinguish them.

Also, the old `cutByPlane()` algorithm was messy, this one is refactored and better.

Fixes #14609

### CODE REVIEW

**Comment by WestLangley** [comment]
This is so sweet!

I'm not sure the old demo is needed anymore.

**Comment by yomboprime** [comment]
Should I remove it?

**Comment by WestLangley** [comment]
Geometry, eventually, will no longer be renderable, so I would say remove the old example -- but use the old filename for the new example.

**Comment by yomboprime** [comment]
Ok. Is the old `ConvexObjectBreaker` class still useful?

**Comment by yomboprime** [comment]
By the way, see this funny video I recorded while debugging the feature:
https://www.youtube.com/watch?v=V7TgWKU08fM

**Comment by WestLangley** [comment]
I do not understand why you have both `webgl_physics_convex_break.html` and `webgl_physics_convex_buffer_break.html`.

But I will let @mrdoob decide what he wants to keep.

**Comment by yomboprime** [comment]
Oh!, I already deleted the old one. Anyways the new one is more efficient.

**Comment by WestLangley** [comment]
Like I said, I think you only need one demo (the new one), and the name of the demo should be "webgl_physics_convex_break.html". But @mrdoob will decide.

**Comment by mrdoob** [comment]
Yes, I don't think we need two examples.
I would just update `webgl_physics_convex_break` so it uses `BufferGeometry` internaly.

**Comment by yomboprime** [comment]
Sorry, I had those changes pending to be pushed. I think it is alright now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
