### PR TITLE
Access to example link from Examples page

### PR DESCRIPTION
**Pull request by spite**
Added actual link to the list items.
Added a link next to the View Source button to open the example.

### CODE REVIEW

**Comment by mrdoob** [comment]
I can't see the new addition... http://ci.threejs.org/viewpullrequest.html#8392

Something I was thinking was to try to turn all the list items into `<a>`s with the `target` set to the iframe. That way we should be able to middle click them to open in a new tab.

The problem is that we lose the anchor on the url, but I wonder if having an `onClick` that takes care of that would work...?

**Comment by spite** [comment]
For some reason, there's only half of the change in there: the list item has now the real link, but the buttons are missing.

**Comment by spite** [comment]
Can I change a PR, or do I have to create a new one?

**Comment by mrdoob** [comment]
Ah. It's there now.

**Comment by mrdoob** [comment]
However, what do you think about the other approach? Does it make sense?

**Comment by spite** [comment]
Yes, makes sense. I'm not sure about what the click event handler may block in the process. I can give it a go next.

**Comment by spite** [comment]
It's up, seems to work.

**Comment by mrdoob** [comment]
Grachas!

**Pull request merged**
