### PR TITLE
Contribution guide: more formatting and addition of 'draft PR' note

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
There were a small amount of spaces left in front of some of the blocks and it was annoying me. Apparently 6 spaces does the trick.

Reading through some markdown cheat sheets/guides was part of the motivation behind adding in the extra lines but it does also add clarity to the raw .md file.

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
Follow up question:
is
```If you modify files in `examples/js` directory, then don't perform any changes in the `examples/jsm`, JavaScript modules are auto-generated via running `node utils/modularize.js`.```
still an appropriate note at the bottom re the deprecation of examples/js

**Comment by munrocket** [comment]
##### Feedback

* Cloning step can be improved as we have done in [readme.md](https://github.com/mrdoob/three.js/blob/dev/README.md#cloning-this-repository)

* Installation step for tests is missing, to run any command you need to install test dependencies at first with `npm i --prefix test`.

* `npm run test` was removed because CI working in any fork now and it was faster than local tests. You can easily add this command back if you want, but right now you should run `npm run test-lint`, `npm run test-unit`, `npm run test-e2e`, `npm run test-e2e-cov` manually.

##### Offtopic

we should remove JSON articles from wiki as outdated

---

---

**Comment by Mugen87** [comment]
> Follow up question:
is
If you modify files in `examples/js` directory, then don't perform any changes in the `examples/jsm`, JavaScript modules are auto-generated via running `node utils/modularize.js`.
still an appropriate note at the bottom re the deprecation of examples/js

Yes. These files need to be updated until end of 2020.

**Review by Mugen87 — APPROVED** [review]

**Comment by DefinitelyMaybe** [comment]
on it

**Comment by DefinitelyMaybe** [comment]
Remake. My old fork has gone walk abouts.
#20578

**Pull request closed without merging**
