### PR TITLE
Add function to access last camera pose retrivied from the WebXR API

### PR DESCRIPTION
**Pull request by dmarcos**
The WebXRManager updates the `matrixWorld` of the camera but not local matrix, rotation, position or scale. The pose gives easy access to local rotation and position of the headset as measured by sensors.

### CODE REVIEW

**Comment by dmarcos** [comment]
Let me know if you there's anything pending. Happy to accommodate any changes.

**Comment by tlaukkan** [comment]
+1

**Comment by arpu** [comment]
@mrdoob  possible merge in r102 ? and all the other webXR stuff

**Comment by mrdoob** [comment]
The idea is that `WebVRManager` and `WebXRManager` should expose the same API so the user doesn't need to worry what API is being used underneath. We should find a way to provide the same functionality with both.

**Comment by Mugen87** [comment]
@mrdoob Needs this PR a reconsideration?

**Comment by dmarcos** [comment]
I rebased just in case

**Comment by mrdoob** [comment]
> @mrdoob Needs this PR a reconsideration?

I don't know. After https://github.com/mrdoob/three.js/pull/15290 we are now passing `frame` in the `requestAnimationFrame` callback.

@dmarcos how do you use `frame` and how would you use `pose`?

**Comment by dmarcos** [comment]
For the `frame` we have our own logic to handle controllers and [need access to the frame to query their pose](https://github.com/immersive-web/webxr-samples/blob/master/controller-state.html#L358)

For the `pose` we need access to the headset local pose (not just the world one). It's used in many contexts like avatars, HUDs, reticle based cursors, collision detection logic...

**Comment by mrdoob** [comment]
Hmm, can't you get the pose by doing `frame.getPose()`?

**Comment by dmarcos** [comment]
@mrdoob Now that we have access to the frame we could call [frame.getViewerPose( referenceSpace )](https://github.com/mrdoob/three.js/blob/62b0767f3cfa55caf833067cac9e3842ab5e714c/src/renderers/webxr/WebXRManager.js#L309) but we would have to make sure is called with the same `referenceSpaceType` value. Maybe error prone. Having a single pose as source of truth feels cleaner and also one less API call, the value is often needed every frame.

**Comment by mrdoob** [comment]
Some updates here. I added a getReferenceSpace() method last week:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webxr/WebXRManager.js#L129-L133

Example of usage:

https://github.com/mrdoob/three.js/blob/dev/examples/webxr_ar_hittest.html#L115-L117

**Comment by dmarcos** [comment]
@mrdoob thanks for being on top of this. That will indeed make possible to retrieve the pose. My only worry is that is exposes more details and harder to use. Wanting to know the camera pose is a common. What are your worries about a `getPose` method?

**Comment by mrdoob** [comment]
>What are your concerns about a `getPose` method?

It exposes internal state of `WebXRManager`.

For maintentance reasons, I prefer exposing the WebXR API directly until new API methods feel right. Right now it feels like a hack to me.

**Comment by mrdoob** [comment]
Closing this for now.

**Comment by dmarcos** [comment]
If the concern is exposing an internal variable we could do:

`renderer.xr.getPose(object3D);`

The user doesn’t have to be aware of the WebXR internals and state remains encapsulated

**Comment by NNskelly** [comment]
I've been able to get viewer pose information successfully after splicing together some of the code samples and suggestions from this thread, but if a decision has been reached as to the desired functionality/implementation, could there be a bit more official documentation?  
I was able to trace the `renderer` references back to https://threejs.org/docs/#api/en/renderers/WebGLRenderer , but it only states that `.xr` is an Object with "WebXR related interface" and that `setAnimationLoop` "can be used instead of `requestAnimationFrame`".  Except for code examples and breakpoint debugging, I would have no idea that `xr` had reference space and session getters, or that `frame` had a pose getter.  I still don't know precisely what kind of objects `xr`, `session`, and `frame` even are, which makes it difficult to look up what e.g. the difference between `xr.getReferenceSpace` and `session.requestReferenceSpace` is beyond inferring that one is probably system/infrastructural-level and the other, by virtue of taking parameters, could likely be used to retrieve spaces for other entities than simply the viewer.  This kind of confusion in turn makes it difficult to expand into new use cases for which there aren't yet direct samples/demos.
If these things were omitted from the THREE docs proper because they are actually part of an underlying or external API, I'd posit that linking that API's docs would be appropriate (e.g. `setAnimationLoop` links out to Mozilla's API docs for `requestAnimationFrame`).

That said, great work on the actual implementation- it's exciting to see AR becoming core browser functionality, and at easily twice the framerate of comparable demos in e.g. 8th Wall!

**Pull request closed without merging**
