### PR TITLE
Docs: Added TextBufferGeometry

### PR DESCRIPTION
**Pull request by Mugen87**
see #11715

### CODE REVIEW

**Comment by Mugen87** [comment]
Okay, i've checked the docs and all `BufferGeometries` have now a respective documentation page.

**Comment by mrdoob** [comment]
Thanks!

**Comment by notflip** [comment]
Does the TextBufferGeometry still exist? Can't find any information in the docs?

**Comment by Mugen87** [comment]
Use this link: https://threejs.org/docs/index.html#examples/en/geometries/TextGeometry

**Comment by notflip** [comment]
> Use this link: https://threejs.org/docs/index.html#examples/en/geometries/TextGeometry
> 
> The link has changed because `TextGeometry` has been moved to the examples folder. Besides, all geometry generators are now based on `BufferGeometry`. So there is no need to use `TextBufferGeometry` aynmore.

Thanks! That's good to know

**Pull request merged**
