### PR TITLE
Examples: Remove PRNG.js

### PR DESCRIPTION
**Pull request by Mugen87**
This file is not referenced in the entire repo.

### CODE REVIEW

**Comment by Mugen87** [comment]
If @mrdoob wants to keep the `PRNG`, I suggest to move it into the `THREE` namespace and the file to the `math` directory.

**Comment by mrdoob** [comment]
We can always add it back if we need it.

**Comment by mrdoob** [comment]
Thanks!

**Comment by EliasHasle** [comment]
I used it. ;-)

But I am fine with it being removed, as the need is easily covered by alternatives found elsewhere, or by a custom implementation. It is not as if PRNG.js was some ingenious new PRNG algorithm. It was very simple and standard.

**Pull request merged**
