### PR TITLE
MRT clean up

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #16390

**Description**

Some internal code clean up.

@takahirox looks good?

### CODE REVIEW

**Comment by gkjohnson** [comment]
If you're going to rename the example from `_mrt` to `_multiple_rendertargets` you might want to add `mrt` as a tag for the example. "MRT" is how I refer to and search around for references on the feature, at least.

**Comment by mrdoob** [comment]
@gkjohnson done!

**Comment by takahirox** [comment]
> @takahirox looks good?

I couldn't look into the detail yet but the clean up basically looks good!
And thanks for fixing some bugs that I had forgotten to rename `isWebGLMultiRenderTarget` to `isWebGLMultipleRenderTargets`.

**Comment by mrdoob** [comment]
It's mostly renames and readability.
Considering that all the tests passed I'll merge, we can tweak things if you find something.

**Pull request merged**
