### PR TITLE
Add scaled vector

### LINKED ISSUE #6781: enchncmnt: add vector premultiplied by scalar
I find myself calculating sums like number1 * vector1 + number2 * vector2 + .... quite often (mostly for averaging or interpolating). Far more often than I had to use addScalar method (which was never). But in order to do so I need to create temporary vector, set this vector for every addend, multiplyScalar it and then finally add it. Or, I could just inline everything and not use Vector3 methods.

Would it not be nice to have something like
```
	addScaledVector: function ( v, s ) {

		this.x += v.x * s;
		this.y += v.y * s;
		this.z += v.z * s;

		return this;

	},
```
instead?

Vector3 already has lerp, which is fine for two vectors, but it can be 3 vectors (think vertex normals) or more.

Same applies to Vector2 (uv and stuff).

### PR DESCRIPTION
**Pull request by gero3**
fixes #6781

This adds AddScaledVector to every vector type.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Many thanks.

    vA.addScaledVector( tempA.subVectors( targets[ face.a ], a ), influence );

@gero3 Can we mrdoobify the codebase (and examples) with a script, instead? @zz85 did this for us awhile back.

**Comment by gero3** [comment]
I actually added #6845 for that. It does the source folder and examples/js folder now.

**Comment by WestLangley** [comment]
> I can do it myself though if you want.

That would be sweet. Thanks. Sorry for hijacking the thread.

I have noticed that sometimes it reformats code we don't want reformatted. Like this:

    foo[ i     ] = 1;
    foo[ i + 1 ] = 2;
    foo[ i + 2 ] = 3;

But, so be it.

**Pull request merged**
