### PR TITLE
fix tiled forward example

### PR DESCRIPTION
**Pull request by wizgrav**
Fix broken example

### CODE REVIEW

**Comment by wizgrav** [comment]
/pingback @WestLangley thanks for bringing this to my attention, sorry for the delay in response

**Comment by Mugen87** [comment]
https://rawgit.com/wizgrav/three.js/dev/examples/webgl_tiled_forward.html

**Comment by WestLangley** [comment]
@mrdoob This is ready to merge.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
