### PR TITLE
WebGLRenderer: Patch for devices that have the old struct assignment compiler bug.

### PR DESCRIPTION
**Pull request by amzn-chris-subagio**
cf https://developer.qualcomm.com/forum/qdn-forums/maximize-hardware/mobile-gaming-graphics-adreno/28503 For what looks like the same problem.

I encountered it on hardware that reported in gl_info as "Intel(R) HD Graphics for Atom(TM) x5/x7"

It looks like at one point one or more GLSL compilers suffered from the same problem: assignment of structs didn't necessarily correctly copy all members. The symptom that led me here was that lighting didn't appear to work at all on a target that has this bug, ambient light would be applied, but all other lights would have no effect. 

The fix I'm proposing here just assigns members individually. Granted it looks icky and it feels bad, but it should result in the equivalent shader code and help support these older devices. Thanks!

### CODE REVIEW

**Comment by mrdoob** [comment]
I have a Nexus 5 and a Nexus 6. Do you have a test I can try?

**Comment by amzn-chris-subagio** [comment]
On the device I'm seeing the problem on any scene with lighting fails, so for instance: https://threejs.org/examples/?q=shadow#webgl_shadowmap only displays ambient, all direct lighting is absent.

**Comment by mrdoob** [comment]
Seems like this may be able to be fixed at the browser level. I'll report here when I know more.

**Comment by Mugen87** [comment]
Considering #24390 I think this PR can be closed. Devices from the last couple of years should not be affected by the mentioned bug anymore.

**Pull request closed without merging**
