### PR TITLE
FBXLoader: Fix clip offset time.

### PR DESCRIPTION
**Pull request by mykola-nikoliuk**
Every new clip start time should always start from zero, but not from current frame time.

### CODE REVIEW

**Comment by mrdoob** [comment]
Instead of a forEach I would use a simple for loop.
Apart from that, looks good @looeee?

**Comment by nick-nikoliuk** [comment]
updated according your suggestion

**Comment by looeee** [comment]
@nick-nikoliuk do you have any example models that were not working correctly prior to this fix?

**Comment by nick-nikoliuk** [comment]
https://youtu.be/NrnW1f6DO7M
[scene.zip](https://github.com/mrdoob/three.js/files/1870923/scene.zip)

**Comment by looeee** [comment]
Other models that I've tested don't have this issue - that is, yours is the first I've come across that has non-zero clip start times. 

However, the fix doesn't break anything since clips with zero start times don't get affected. So this is OK to merge.

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
This broke some other models. I think we need to revert. 

@nick-nikoliuk yours is the only model I've come across that needs this fix - other models have the start time of their clips correctly specified, and it may not be zero. 

What program did you export from?

**Comment by looeee** [comment]
Here's a model with incorrect animation after this PR:

[space.zip](https://github.com/mrdoob/three.js/files/1910003/space.zip)

**Comment by nick-nikoliuk** [comment]
Our company using 3ds Max. 
One FBX file should not contain only one animation. For example charter animations (idle, walk, run, jump, etc.). When FBX contain more than 1 animation, logically they can’t start at 0. 
@looeee

**Comment by looeee** [comment]
@nick-nikoliuk we need to support all applications that export FBX files. A fix that works for you but breaks things for other people is not acceptable. 

If you want to make another PR that fixes your problem but doesn't break that model then please go ahead.

**Comment by mrdoob** [comment]
We could consider adding a `setParseOptions` to the loader to enable this kind of things. Something like `MTLLoader`'s `setMaterialOptions`... 

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MTLLoader.js#L99-L104
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MTLLoader.js#L181-L189

**Comment by looeee** [comment]
@nick-nikoliuk  as a workaround you can manually reset times of the problematic clips like this:

```js
object.animations[ 1 ].tracks.forEach( function( track ) {
	track.shift( -track.times[ 0 ] );
})

object.animations[ 1 ].resetDuration()
```

**Pull request merged**
