### PR TITLE
DRACOExporter: Fixed number of faces parameter.

### LINKED ISSUE #19216: Files exported using DRACOExporter are 3 times the original size
##### Three.js version

- [x] Dev
- [x] r115

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

I have imported 'bunny.drc' [94KB] using DRACOLoader and exported using DRACOExporter. 
The new file loads without loosing any geometry but to my surprise, it is 281KB  (almost three times the original file size).

Then, I have tested with other DRC files as well. All exported files are exactly three times the size of original file. 

As a developer, I have debugged and thought issue can be in DRACOExporter.js in below lines.

	
```
                var faces = geometry.getIndex();

		if ( faces !== null ) {

			builder.AddFacesToMesh( mesh, faces.count, faces.array );

		} 
```

   Here, geometry.getIndex() returns 'index' object. 

From official [Google DRACO Project](https://github.com/google/draco#javascript-encoder-api),

```
const numFaces = mesh.indices.length / 3;
const numPoints = mesh.vertices.length;
meshBuilder.AddFacesToMesh(dracoMesh, numFaces, mesh.indices);
```

I have fixed it by below snippet 
       `  builder.AddFacesToMesh( mesh, faces.count, faces.array );`
                    to
         `builder.AddFacesToMesh( mesh, faces.count/3, faces.array );`

Let me know are there any other things I am missing by this?

### PR DESCRIPTION
**Pull request by TejaSwaroopArukoti**
Fixed #19216 

Made changes to the `AddFacesToMesh` function in  `DRACOExporter.js` and `DRACOExporter.jsm` files to reflect face count value according to [Official DRACO site.](https://github.com/google/draco)

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
I can see this fixing indexed geometries indeed!

But I've also tried exporting non-indexed geometries before and after and makes me wonder if `builder.AddFacesToMesh( mesh, vertices.count, faces );` was correct already.

**Comment by mrdoob** [comment]
I've reverted the non-indexed geometries change. https://github.com/mrdoob/three.js/commit/b537ebda9c59fafc4579c500fb5686132c451dfe

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Teja Swaroop Arukoti <notifications@github.com>
发送时间：2020-04-26 01:50
主题：[mrdoob/three.js] #19216 Fixed the bug related to number of faces param. (#19220)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Fixed #19216
Made changes to the AddFacesToMesh function in DRACOExporter.js and DRACOExporter.jsm files to reflect face count value according to Official DRACO site.



You can view, comment on, or merge this pull request online at:
  https://github.com/mrdoob/three.js/pull/19220
Commit Summary
Fixed the bug related to number of faces param. 
File Changes
M examples/js/exporters/DRACOExporter.js (10) 
M examples/jsm/exporters/DRACOExporter.js (10) 
Patch Links:
https://github.com/mrdoob/three.js/pull/19220.patch 
https://github.com/mrdoob/three.js/pull/19220.diff

**Pull request merged**
