### PR TITLE
Rename WebGLProgram "code" to "cacheKey"

### PR DESCRIPTION
**Pull request by Oletus**
This name is clearer since "code" can be easily confused to mean shader code in this context.

Settling on a good name here is important because we want to expose the ability to customize the hash through the API. ( #17567 )

### CODE REVIEW

**Comment by Oletus** [comment]
@Mugen87 please review, I think it would be important to clarify the naming before we put this in the API ( #17567 ).

**Comment by Mugen87** [comment]
> This name is clearer since "code" can be easily confused to mean shader code in this context.

I know what you mean but the term "hash" would better fit with the following implementation #16674. The PR computes a CRC32 value which is something that can be considered as an actual hash value.

I think I vote for `programCacheKey` what you have already suggested in  #17567.

**Comment by Oletus** [comment]
Cool, I'm happy with "cacheKey". Pushed an amended commit changing the name to cacheKey instead.

**Review by Mugen87 — APPROVED** [review]

**Comment by Oletus** [comment]
@mrdoob Please merge!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
