### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
Minor clean up...

### CODE REVIEW

**Comment by WestLangley** [comment]
Restore your clear color, and try setting the plane geometry to be of size ( 0.5, 0.5 ) as an experiment.

Using an orthographic camera is fine, if you want, but you should then modify the shader accordingly, as you are now mixing incompatible methodologies.

**Comment by Mugen87** [comment]
I'm a little bit uncertain now :sweat_smile: . Is it okay like this now (especially the usage of a plain `Camera`)?

A geometry of size ( 0.5, 0.5 ) did not work. It was just a little quad in the screen center that did not show the entire audio visualization.

**Comment by WestLangley** [comment]
>A geometry of size ( 0.5, 0.5 ) did not work. It was just a little quad in the screen center that did not show the entire audio visualization.

Exactly. The three.js way is to use the uv's of the geometry. The _ShaderToy_ way is to use `gl_FragCoord.xy / resolution.xy;` You're mixing methodologies.

My suggestion is to do it the three.js way.

**Comment by Mugen87** [comment]
Indeed, that was a nice suggestions! You're great! :blush:

**Comment by WestLangley** [comment]
Well, we might as well keep going...   :)

There is no need to create two buffers;
```
uniforms = {
	tAudioData: { value: new THREE.DataTexture( analyser.data, size, 1, THREE.LuminanceFormat ) },
};
```
```
function render() {

	analyser.getFrequencyData();

	uniforms.tAudioData.value.needsUpdate = true;

	renderer.render( scene, camera );

}
```

**Comment by Mugen87** [comment]
Cool! Was not aware of `THREE.LuminanceFormat`.

**Comment by Mugen87** [comment]
So a single value `L` in the buffer looks like this after a texture sample in the fragment shader, right?
```
(L,L,L,1) 
```

**Comment by WestLangley** [comment]
Try confirming that with an experiment.

**Comment by Mugen87** [comment]
Yep, all `rgb` values are identical and the `alpha` value is 1.

**Comment by mrdoob** [comment]
Very nice!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
