### PR TITLE
fix nan on first frame

### PR DESCRIPTION
**Pull request by greggman**

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]
Using `THREE.Clock` would also solve the issue. However, having one example that utilizes the parameter of `requestAnimationFrame`'s callback seems okay.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hmm, actually... This is kind of hacky, not really a pattern we would like to encoutage.

I'll change it using `performance.now()` in the render loop.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/56382ed5ced21ff8107d4b54eacce4678339cb4f

**Pull request merged**
