### PR TITLE
Editor: Move commands to ES6.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #21229

**Description**

Converted all command classes to ES6 code.

Also fixed an issue with `SetMaterialColorCommand` which produces a runtime error when persistent history was enabled.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev2/editor/index.html

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
@mrdoob Consider a file like [Config.js](https://github.com/mrdoob/three.js/blob/dev/editor/js/Config.js) from the editor.

Do you also want to convert such files to classes? Currently they define their public API by the ctor's return object. Similar files also exist in `src/renderers`. When I've started developing `WebGPURenderer`, I've used the class approach. However, I had the impression you were not 100% happy with it because it requires that certain properties and/or methods are available via `this`. For comparison:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/renderers/webgpu/WebGPUObjects.js
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLObjects.js 

What style should we choose for the editor, `WebGLRenderer` and potentially other source files?

**Comment by mrdoob** [comment]
The approach of returning an object had interesting properties but it was yet another workarounds for the fact that JS didn't have proper classes. Nowadays I think it's probably better to unify to standard class usage.

I would avoid making properties public whenever possible though. We know how users end up abusing those.

**Comment by Mugen87** [comment]
> I would avoid making properties public whenever possible though.

Let's say there is no way around to add an internal property to `this` so it is accessible by all methods. Do you think we should use the `_` prefix to mark this methods as private?

**Comment by mrdoob** [comment]
For the time being... yes.

**Comment by DefinitelyMaybe** [comment]
ok, I will add a note of this to the dev contribution guide

**Pull request merged**
