### PR TITLE
Docs and examples switching retains filter

### PR DESCRIPTION
**Pull request by octopoulos**
For example, if you search for "fog" in the examples, then click on "docs" link, the filter is emptied and it shows "Create a scene" page.
Same thing if you search in docs and click on the examples link.

With this PR, the search is retained, which personally helps me a lot.
Typical scenario is:
- Let's see if there are examples of ... parametric, so I type "param", cool I see an example.
- Now let's see if there's any doc about it, so I click on the docs link, then: "arghh, I have to type it again!!"
:)

Screenshots:
1) write "skin"
image

2) click on docs and this appears:
image

3) click again on examples and this appears:
image

### CODE REVIEW

**Comment by octopoulos** [comment]
I was using a sort of a non standard way to store the original href, with `sectionLink.href2 = ...` instead of using a dataset or `setAttribute`, which personally I don't mind doing at all, but after looking at the existing code, I realized the coding style was different, so I made some changes, and removed that href2 "hack", and instead I'm storing the original href value in a variable, that's it!

The functionality has not changed.

**Comment by mrdoob** [comment]
> so I made some changes, and removed that href2 "hack"

Nice, I was going to mention that 🤓

**Comment by mrdoob** [comment]
For testing:
https://raw.githack.com/octopoulos/three.js/docex/examples/

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
We'll have to remove all that duplicated code from `examples/index.html` and `docs/index.html` some day...

**Pull request merged**
