### PR TITLE
Allow Morph Attributes to be serialized/deserialized in Buffer Geometry

### PR DESCRIPTION
**Pull request by Temdog007**

### CODE REVIEW

**Comment by Mugen87** [comment]
Your dedication is great but maybe it's a good idea to wait with new PRs until your others are reviewed and merged 😇. You already created twelve PRs but none of your changes are in code base, yet.

**Comment by Temdog007** [comment]
Ok. :smirk:

**Comment by takahirox** [comment]
Duplicated? #11596

**Comment by Mugen87** [comment]
Good catch! I remember I've already tested your code...long time ago^^.

**Pull request closed without merging**
