### PR TITLE
2 useful changes and 1 fix

### PR DESCRIPTION
**Pull request by RemusMar**
MTLLoader: support for Specular and Normal maps
Result: http://necromanthus.com/Test/html5/claire.html 

UTF8Loader: progress callback
Result: http://necromanthus.com/Test/html5/ 

ColladaLoader: fixed the missing animation in case of skinned mesh with multiple materials
Result: http://necromanthus.com/Test/html5/girl2.html

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks for the contributions.

You need to fork and target the dev branch, however, and create separate branches per patch or feature. In this case, three of them, since the issues are not related.

Please see the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

There also seems to be significant changes to the formatting.

Please see the Wiki article [Mr.doob's-Code-Style™](https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style™) and the utility http://zz85.github.io/mrdoobapproves/.

Thanks.

**Comment by RemusMar** [comment]
> You need to fork and target the dev branch, however, and create separate branches per patch or feature. 

That's the ColladaLoader case.

> There also seems to be significant changes to the formatting.
>  http://zz85.github.io/mrdoobapproves/ 

All the spaces between lines and all the worthless comments have been removed.
- they double the script lines number
- they add worthelss bytes to be downloaded

I know, we're not talking about minified versions here, but for something in a browser to reduce the  server bandwidth is a very important goal.

cheers

**Comment by RemusMar** [comment]
BTW

The UTF8Loader should be included in the main package.
It's the best option for static high-poly meshes.
Two HUGE advantages compared to any other format:
- 1:7 ... 1:8 compression
- buffer geometry (faster rendering)

cheers

**Comment by mrdoob** [comment]
As @WestLangley suggested, is best to keep do multiple Pull Request (one per feature) than combine different changes in one. The `ColladaLoder` change is interesting (even if `MeshFaceMaterials` are going away) but I don't agree with the `MTLLoader` change (specially because you just removed @angelxuanchang credit from the file), so I can't merge this.

Also, as @WestLangley also suggested, you should work on the from the `dev` branch instead.

> The UTF8Loader should be included in the main package.

I'm trying to keep the (minified+gzipped) three.min.js under 100kb. If we want to include UTF8Loader we'll have to remove other stuff.

**Comment by RemusMar** [comment]
MTLLoader:

add

				case 'map_ks':
					params[ 'specularMap' ] = this.loadTexture( this.baseUrl + value );
					params[ 'specularMap' ].wrapS = this.wrap;
					params[ 'specularMap' ].wrapT = this.wrap;
					break;
				case 'map_norm':
					params[ 'normalMap' ] = this.loadTexture( this.baseUrl + value );
					params[ 'normalMap' ].wrapS = this.wrap;
					params[ 'normalMap' ].wrapT = this.wrap;
					break;

after

				case 'map_kd':
					params[ 'map' ] = this.loadTexture( this.baseUrl + value );
					params[ 'map' ].wrapS = this.wrap;
					params[ 'map' ].wrapT = this.wrap;
					break;

That's all and nothing more.


> I'm trying to keep the (minified+gzipped) three.min.js under 100kb

Come on Ricardo ...
three.min.js v71 is 410KB
UTF8Loader minified is less than 10KB
But if you don't agree that this is the best loader so far, the choice is yours.

**Comment by RemusMar** [comment]
> The ColladaLoder change is interesting

It's not interesting.
It's a bug fix !!!

**Comment by mrdoob** [comment]
> > The ColladaLoder change is interesting

> It's not interesting.
> It's a bug fix !!!

Agreed! But I can't merge this because there is more stuff that comes with it.

Can you do a new PR only with the ColladaLoader bug fix?

**Comment by mrdoob** [comment]
Actually, I've a better fix for the `ColladaLoader` issue. It entails adding getters/setters to `MeshFaceMaterial` so it automatically applies it to all the materials. However, at the moment `MeshFaceMaterial` has been removed from the `dev` branch (Still working on it!) so your fix only works with version in the `master` branch.

**Comment by RemusMar** [comment]
Ricardo, for me it's a nightmare to folllow the script with so many spaces and comments.
In dev72 please replace

					if ( geom.morphTargets.length > 0 ) {

						material.morphTargets = true;
						material.skinning = false;

					} else {

						material.morphTargets = false;
						material.skinning = true;

					}

with

					if ( geom.morphTargets.length > 0 ) {
						if ( num_materials > 1 ) {
							for ( j = 0; j < num_materials; j ++ ) {
								material.materials[j].morphTargets = true;
							}
						} else {
							material.morphTargets = true;
						}
						material.skinning = false;
					} else {
						material.morphTargets = false;
						if ( num_materials > 1 ) {
							for ( j = 0; j < num_materials; j ++ ) {
								material.materials[j].skinning = true;
							}
						} else {
							material.skinning = true;
						}
					}

That's all.
cheers

**Comment by RemusMar** [comment]
> Actually, I've a better fix for the ColladaLoader issue. It entails adding getters/setters to MeshFaceMaterial so it automatically applies it to all the materials.
> However, at the moment MeshFaceMaterial has been removed from the dev branch (Still working on it!) 

Do not forget to fix the JSONLoader bug in case of 2 (or more) materials per mesh!
That's a part of the main package and is more difficult for me to trace the issue.

From by point of view, JSON and UTF8 are the best THREE loaders by far.
JSON for skinned meshes (bones)
UTF8 for static meshes.

cheers

**Pull request closed without merging**
