### PR TITLE
Added USDZExporter

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #14219

**Description**

First version of the USDZ exporter:

* Generates a USDA file and zero-compresses it into a USDZ.
* Exports all meshes in the scene and materials but no textures yet.
* It's pretty hacky.

I've also added it to the editor so it's easier to try different models.

Screen Shot 2021-01-16 at 4 45 53 PM

Screen Shot 2021-01-16 at 4 27 38 PM

### CODE REVIEW

**Comment by mrdoob** [comment]
@101arrowzI had to add the full `fflate.module.js` into the repo because I needed methods that were not available in the custom builds.

**Comment by 101arrowz** [comment]
Alright, let me know if you want a custom build and I'll make another one.

**Comment by mrdoob** [comment]
I think it'll be best to remove the custom builds and just have the build that has everything.

**Comment by 101arrowz** [comment]
Sounds good. For people using in production, you might want to make a script for creating a minified build by running through `terser` (or a bundler if you use the same minification script with all libraries). At the cost of creating slightly larger builds than hand minification, it's automatic.

**Comment by kolodi** [comment]
I've tried different models but after exporting in USDZ they all look too dark in Quick View. Setting adding metallic map (all black or white) does not solve the problem. Do you experience the same "too dark" problem?

**Comment by mrdoob** [comment]
@kolodi Can you share the files you're having issues with?

**Comment by kolodi** [comment]
> 
> 
> @kolodi Can you share the files you're having issues with?

https://s3.eu-south-1.amazonaws.com/k3.varplus.it/res/ab/LTS2019/web/dev/tests/models/Anna_T_M_1uv_material.glb

**Comment by mrdoob** [comment]
@qeeqez any chance you can investigate the issue?

**Comment by qeeqez** [comment]
@mrdoob I'll have a look on it. I have an opposite problem - my materials are too bright in Quick Look 😅

**Comment by kolodi** [comment]
> 
> 
> @mrdoob I'll have a look on it. I have an opposite problem - my materials are too bright in Quick Look 😅

Did you have a chance to look at them?

**Comment by mrdoob** [comment]
Having a look at it today.

**Comment by mrdoob** [comment]
Unrelated...

Seems like USD doesn't support `doubleSided` at material level.
It only supports it at geometry level, which means that we would need to duplicate geometries?

**Comment by mrdoob** [comment]
@kolodi 

> simple cubes: https://tinyurl.com/yzmvvcsu or https://tinyurl.com/ydvxg9u9

These export correctly. We're matching Apple's own usdzconvert:

Screen Shot 2021-05-21 at 11 22 38 AM

Screen Shot 2021-05-21 at 11 25 54 AM

**Comment by qeeqez** [comment]
@kolodi sorry for long answer, pretty busy this week.

I've checked yours models. Looks like this "grayish" is not a problem of the model but of the lighting in AR QuickLook which we couldn't change.

For my issue (too light color): it seems to be that I've used SRGB colors instead of Linear ones for the models. And also lighting changes my colors a little bit. I'm further investigating this issue.

**Comment by kolodi** [comment]
> I've checked yours models. Looks like this "grayish" is not a problem of the model but of the lighting in AR QuickLook which 
> we couldn't change.

I have checked everything we can do in QuickLook and, yes, we can't control anything like lighting, there is a reflection (environment) map created dynamically (which is pretty cool) but overall it makes models darker.

> For my issue (too light color): it seems to be that I've used SRGB colors instead of Linear ones for the models. And also lighting > changes my colors a little bit. I'm further investigating this issue.

Very interesting. I was playing around :sourceColorSpace:
`token inputs:sourceColorSpace = "auto" or "sRGB"`
but see no changes.
Also I don't see how colorspace of a texture can be transferred to the exported texture. Is this information maintained when we draw image to the temporary canvas, here:
https://github.com/mrdoob/three.js/blob/d379666e9ba063ec59e91458445b3c2a79653ca0/examples/jsm/exporters/USDZExporter.js#L110-L118

**Comment by mrdoob** [comment]
@kolodi 

> https://tinyurl.com/yh6y649y

The issue with this file is the fact that we don't export `aoMap` properly yet.

**Comment by kolodi** [comment]
> 
> These export correctly. We're matching Apple's own usdzconvert:
> 
I was also using usdzexport tool to compare results. materials and texture definitions are structured differently (I'm currently working to change the structure for USDZExporter as well) but the visual result is the same. When opening in xCode converted usdz looks fine, but in QuickLook lighting makes them too dark. I was trying on 2 devices. On older iPad they are a bit brighter, but on latest and greatest iPhone with lidar models look very dark for some reason.

**Pull request merged**
