### PR TITLE
Corrected limit condition for x-coordinates.

### PR DESCRIPTION
**Pull request by MagnuzBinder**
x-coordinate for the starting and ending points must be equal to 0 for a closed geometry, hence edited "greater than" => "greater than or equal to". x-coordinates less than zero don't give an error, but an unexpected and sometimes even artistic result, hence edited "must" => "should".

### CODE REVIEW

**Comment by WestLangley** [comment]
I believe values of `x` equal to zero result in degenerate triangles. I am not sure if that is problematic, but if it is, and you want to allow zero values, the code should be fixed to prevent degenerate triangles.

Also, in this doc, I would replace `The lathe rotates around the Y axis.` with `The axis of rotation is the y-axis.` -- or something similar.

Many thanks for your ongoing improvements to the docs.

**Comment by MagnuzBinder** [comment]
I have tested several geometries containing degenerate triangles (no area because two points are equal or all three points are in a straight line), usually around "poles", and all of these have been rendered properly, so it seems WebGL handles degenerate triangles gracefully. Raycasting on these geometries also gives the expected results. I haven't been through much of the Threejs code, but in the places I have seen, degenerate triangles shouldn't cause a problem neither, besides the overhead of handling "unnecessary "triangles.

**Comment by MagnuzBinder** [comment]
The possible problem with degenerate "polar" triangles already exists in the Cone and Sphere geometries, and can be generated in several other geometries, e.g. Cylinder (with at least one radius set to 0), Ring (with inner radius set to 0), and Parametric (with certain functions). You can also get degenerate triangles in the basic (buffer) geometry, dynamically in skinned mesh, and both false positive and false negative ones owing to rounding errors, if you use e.g. triangle area to detect them. While the "polar" ones in Cone, Cylinder, Lathe, Ring and Sphere should be "rather" simple to fix, the other cases will be harder, and may also need splitting or merging of adjacent triangles (in cases where no points are equal but lie on the same line). If WebGL handles it gracefully, even if it means a bit of overhead, I wouldn't recommend going there.

**Comment by WestLangley** [comment]
While you are investigating this... :)

`computeFaceNormals()` and `computeVertexNormals()` may produce zero-length normals with degenerate triangles. I believe we handle that gracefully now, but it is worth checking. There are multiple cases: buffer-geometry, non-buffer-geometry, shared and non-shared vertices, triangle soup, ...

My guess is we are OK, in which case, the only change I would recommend is the change I proposed in my first comment.

**Comment by MagnuzBinder** [comment]
I checked the possible problem with zero-length normals.

Face normals of degenerate triangles (with zero area) should never display in reality, but in mathematics you can actually construct a situation where a zero area triangle has a 1/3 probability (depending on triangle order) to show up as a horizontal or vertical black line (infinitely thin area located exactly on a rendered pixel row or column), a single black pixel (infinitely small intersection area between the zero area line and a rendered pixel row or column, located exactly on a rendered pixel) or several spaced black pixels (if the zero area line has inclination 3/4 or 4/3), between two non-zero area triangles.  In a "real" scene rendering, the probability for this is extremely small though.

Vertex normals is not a problem, since they are constructed from a normalized sum of adjacent face normals, so any zero-length normal added to this sum is effectively discarded, as it should be. If all adjacent triangles are degenerate, the vertex should never display in reality, but as above you can construct a situation where it would show up as a single black pixel (infinitely small area located exactly on a rendered pixel).

I made the text adjustments suggested, in both (buffer and non-buffer) files.

**Comment by WestLangley** [comment]
>Face normals of degenerate triangles (with zero area) should never display in reality

This is not a rendering issue; it's a numerical one -- if it is an issue at all. Any numerical issues would be related to division by zero, I expect.

>Vertex normals are not a problem, since they are constructed from a normalized sum of adjacent face normals

There are not necessarily any adjacent faces to a given face. There will be none, for example, if there are no shared vertices.

@Mugen87 Can you think of any part of the codebase where degenerate triangles is problematic?

**Comment by Mugen87** [comment]
The GPU can easily detect degenerated triangles and discards them. So there should not be any rendering artifacts. However, for consistency reasons it's better when the geometry generators avoid the creation of degenerated triangle if possible. From an analytical point of view, triangles with zero area do not make sense.

According to Anyuru in _Professional WebGL Programming_, one use case for degenerated triangles is the combination of different triangle strips when using `gl.TRIANGLE_STRIP`. However, this seems not important for us.

I think the PR can be closed. https://github.com/mrdoob/three.js/pull/12886#issuecomment-352080193 can be addressed in a different PR.

**Pull request closed without merging**
