### PR TITLE
QuickHull: Added intersectRay().

### PR DESCRIPTION
**Pull request by Mugen87**
Now it's possible to raycast against convex hulls 🎉 

Code and nomenclature is based on _Fast Ray-Convex Polyhedron Intersection_ by Eric Haines, GRAPHICS GEMS II.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
FYI @erich666 😊

**Comment by erich666** [comment]
Ha, fun, nice!

**Comment by Mugen87** [comment]
@errorx666 Your article _Fast Ray-Convex Polyhedron Intersection_ is really great! Thank you for this work 😊

**Pull request merged**
