### PR TITLE
Remove SphericalReflectionMapping

### PR DESCRIPTION
**Pull request by WestLangley**
As discussed [here](https://github.com/mrdoob/three.js/pull/5622#issuecomment-62961394), sphere maps are camera view-dependent and are not appropriate as we are using them. Furthermore, SEMs assume the object is centered directly in front of the camera, which is generally not the case in three.js.

Users can use `MeshMatcapMaterial` instead. I have seen users use `SphericalReflectionMapping`, but they are passing in a matcap texture, thinking it is the same thing. A spherical reflection map is not the same as a matcap.

//

@mrdoob I am not sure about the change I made to `Sidebar.Material.js`...
	
@takahirox I was also not sure what to do with `MMDLoader.js`. `MeshToonMaterial` no longer extends `MeshPhongMaterial`  (#18003), and no longer supports environment maps, so I was not sure what changes would be appropriate to `MMDLoader.js`. That loader is not modified in this PR. Can you please have a look? We can safely save it for later.

To do: update migration docs when appropriate.

### CODE REVIEW

**Comment by mrdoob** [comment]
> @mrdoob I am not sure about the change I made to `Sidebar.Material.js`...

I think this works.

But when removing `EquirectangularReflectionMapping` we may want to do a `THREE.EquirectangularTexture` that tells the renderer that needs to be internally converted to a `CubeTexture` at upload time.

What do you think?

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
I'll give it a try and see how it goes...

**Comment by takahirox** [comment]
@WestLangley Sorry I didn't notice for a while. I reviewed MMD specification and found that material in MMD can apply environment mapping while it is cartoon based material. So the current `MeshToonMaterial` doesn't satisfy MMD material specification. I think I need to implement MMD specific material `MMDToonMaterial` in `MMDLoader` by extending `MeshToonMaterial` (or `MeshPhongMaterial`) or using `ShaderMaterial`. If node based material system lands, it would be a good use case.

**Pull request merged**
