### PR TITLE
Add missing `dispose()` methods

### LINKED ISSUE #21572: Inconsistent existence of `dispose()` across API
# Describe the bug

Documentation states ([here](https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects)):
> In general, it's recommended to check the API or documentation of a class and watch for `dispose()`. If present, you should use it when cleaning things up.

However, the existence of `dispose()` across API is inconsistent. E.g. `SpotLightHelper` has `dispose()` but `CameraHelper` does not. Based on the above statement from the documentation, one might assume a `CameraHelper` does not need to be disposed, but such a conclusion would leak one material and one geometry that the `CameraHelper` creates _internally_ (probably unknown by the user). To know this, you must look at the source code of `CameraHelper` to see how it works, which is _doable_ but not _optimal_.

I propose that any object which creates materials/geometries/textures *internally* should have a `dispose()` method to dispose of those internally-created-resources (like `SpotLightHelper` already does ... but others do not).

If this is of interest to the maintainers, I can volunteer to send in a PR. If not, I will not send in a PR. :) Let me know. I have an SPA site so I've found many of these missing-`dispose()` objects and have runtime patches to fix them already in my app.

### PR DESCRIPTION
**Pull request by acu192**
Fixed #21572

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like the docs changes use spaces for indentation instead of tabs.

**Comment by acu192** [comment]
@mrdoob Fixed now.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by JaidenDeChon** [comment]
After updating recently, I found `dispose()` is also missing from `Scene`. Was this intentional? If it was intentional, is there a replacement or does the move to webgl2 mean we don't need this anymore? 

Please let me know if I'm asking in the wrong place and I'll move this question. Thank you

**Comment by acu192** [comment]
| After updating ...

Was there *ever* a `dispose()` in the `Scene`? If so, I never noticed it.

I don't think `Scene` needs one; the `Scene` *itself* does not create disposable objects. Rather, *you* create disposable objects and add them to the Scene. The purpose of `dispose()` is to dispose of resources that are created *internally* by the object.

For a larger discussion, you should probably file a new issue for it since this PR is already merged.

**Comment by Mugen87** [comment]
> Was there ever a dispose() in the Scene? 

Yes. And it was removed in #19972 when internal data-structures of the engine where converted to weak maps.

**Pull request merged**
