### PR TITLE
[WIP] Examples: Clean up href for light/dark background.

### PR DESCRIPTION
**Pull request by linbingquan**
@mrdoob What do you think about use `light` and `dark` theme for `body`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Seems like over-engineering to me honestly.

**Comment by makc** [comment]
@linbingquan FYI https://webkit.org/blog/8840/dark-mode-support-in-webkit/

**Comment by makc** [comment]
@mrdoob you probably saw it on discord but in case you didnt:
Screen Shot 2020-05-28 at 23 50 58

**Comment by mrdoob** [comment]
Haha! I didn't yet. Nice catch 😁

**Comment by mrdoob** [comment]
@makc fixed https://github.com/mrdoob/three.js/commit/b2eaf43e202d92ef3ea5f122cdbf44a0e501f67a

**Comment by mrdoob** [comment]
@linbingquan Closing this one. Sorry, I think this over-complicates things a bit.

**Pull request closed without merging**
