### PR TITLE
Docs: Added preview for MeshPhysicalMaterial

### PR DESCRIPTION
**Pull request by Mugen87**
I've noticed that the material preview for `MeshPhysicalMaterial` was missing.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawgit.com/Mugen87/three.js/dev8/docs/index.html#api/materials/MeshPhysicalMaterial

**Comment by WestLangley** [comment]
`MeshPhysicalMaterial` and `MeshStandardMaterial` were designed to be used with an environment map so there is something to reflect. They were not designed to support refraction.

**Comment by Mugen87** [comment]
I've just added a similar setup that is already in place for `MeshStandardMaterial`. I don't have the intention to rework both previews. Let's do this in a different PR.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
