### PR TITLE
Uninterleave sphere geo

### PR DESCRIPTION
**Pull request by benaadams**
Strangely simple to change :)

### CODE REVIEW

**Comment by mrdoob** [comment]
Yay! Thanks!

**Comment by WestLangley** [comment]
When do you want to use interleaved buffers, and when do you not want to use them?

**Comment by benaadams** [comment]
> When do you want to use interleaved buffers, and when do you not want to use them?

In a general sense, use them for all static stuff; use them for dynamic stuff you do partial updates for in groups. So you might have an interleaved buffer that's just color and size that you use in a object pool style buffer where you always update them together and in partial chunks. 

Break out things you don't update together else you have unnecessary updates and unnecessary multiplys to get the positions.

[Apple OpenGLES Best Practices - Use Interleaved Vertex Data](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW10)

In a practical sense, on desktop, it would be at the edges of performance rather than general use that they may make a difference (hardware dependent); also there a few specific use cases; which caused me to first start using them in the first place: http://codeflow.org/entries/2012/aug/05/webgl-rendering-of-solid-trails/

**Comment by benaadams** [comment]
@WestLangley also for the primitives you probably wouldn't get much gain as they end up mostly being fairly small geometries, so code clarity is probably more important.

Something to convert BufferedAttributes to InterleavedAttributes for large models post load however would probably be more useful.

**Comment by WestLangley** [comment]
@benaadams Many thanks!

**Pull request merged**
