### PR TITLE
SceneLoader: Removal

### PR DESCRIPTION
**Pull request by Mugen87**
I'm currently cleaning up some remaining references to obsolete animation entities (like `collada/AnimationHandler`). When working on `webgl_loader_scene`, i wonder if this example is still needed because it uses (and promotes) the deprecated `SceneLoader`.

### CODE REVIEW

**Comment by mrdoob** [comment]
I think it's time to remove it yeah...

**Comment by Mugen87** [comment]
Okay, done.

**Comment by mrdoob** [comment]
I guess we can also remove this one https://github.com/mrdoob/three.js/blob/dev/examples/scenes/test_scene.js

**Comment by Mugen87** [comment]
👍

**Comment by mrdoob** [comment]
And https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/deprecated/SceneLoader.js while we are at it 😇

**Comment by Mugen87** [comment]
😉 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
