### PR TITLE
Examples: Add webgl_loader_gltf_lights.

### LINKED ISSUE #18629: We need glTF model including lights extension
##### Description of the problem

We have removed glTF Monster model in #18579. It was the only glTF model which has lights extension in our examples. I think we need a new model (or another existing model) which has lights extension for the test and showing we support lights extension.

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #18629.

**Description**

Adds an example that makes use of the `KHR_lights_punctual` extension.

### CODE REVIEW

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
Maybe we should make this GLB use AVIF, to resolve [#25173](https://github.com/mrdoob/three.js/pull/25173#issuecomment-1411723538)? Reduces the model from 4.5 MB to 0.5 MB —

[Archive.zip](https://github.com/mrdoob/three.js/files/10733713/Archive.zip)

**Comment by Mugen87** [comment]
I would prefer to use a separate example for this. Unless it might not be clear for the user why the lights example does not work in Edge and Safari.

**Comment by donmccurdy** [comment]
Ok – maybe let's use the WebP version in the archive above instead, then? It'll work in all modern browsers and is still much smaller than 4.5 MB.

**Comment by Mugen87** [comment]
I've checked the WebP version but I see many compression artifacts over the metal stand.

Dev:

image

WebP:

image

Maybe compression is a bit too aggressive in this case.

**Comment by donmccurdy** [comment]
Here's a version with the normal maps losslessly compressed, 4.5 MB → 2.2 MB. I think 4.5 MB is larger than necessary for this example.

[LightsPunctualLamp.glb.zip](https://github.com/mrdoob/three.js/files/10734909/LightsPunctualLamp.glb.zip)

**Comment by mrdoob** [comment]
Could you try using [moonless_golf_1k.hdr](https://github.com/mrdoob/three.js/blob/dev/examples/textures/equirectangular/moonless_golf_1k.hdr) as `scene.background` and `scene.environment`?
I think it'll look nice and still show the feature.

**Comment by Mugen87** [comment]
Updated the example with the env map! Unfortunately, I can generate the new screenshot right now on my mac Mini (still getting the runtime error mentioned in https://github.com/mrdoob/three.js/pull/25504#issuecomment-1429488503). I'll do it later on my Windows machine.

**Pull request merged**
