### PR TITLE
TransformControls: Redesigned translation/scale modes and increased line thickness

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #22048

**Description**

We've had a few reports of people being confused with how the translation handles get inverted depending of the camera location so I decided to try a different design.

While I was at it I also made the lines thicker.

Live links:
https://raw.githack.com/mrdoob/three.js/dev/editor/
https://raw.githack.com/mrdoob/three.js/dev/examples/misc_controls_transform.html

Before:

https://user-images.githubusercontent.com/97088/123818802-33a37380-d8f1-11eb-846d-80895bdf2075.mov

After:

https://user-images.githubusercontent.com/97088/123818919-47e77080-d8f1-11eb-86eb-cf3461c190b6.mov

/cc @arodic

### CODE REVIEW

**Comment by arodic** [comment]
The purpose of the axis flipping was primarily to mitigate handle occlusion at various angles. For example, you can't pick x axis when its pointing away from the camera because it is occluded by other parts of the gizmo.

Flipping the axis at certain threshold was a neat solution but it had one problem - in flipped state it misrepresented the coordinate system directions. That is why I also flipped the arrow head to indicate the real direction of the axis. My understanding is that head flipping part confused some users not the axis flipping part.

Anyway, this new design looks nice but it has one problem. At some angles, the invisible picker geometry of the negative axis perfectly occludes another visible positive axis like in this image below. So if you hover the blue axis on the right you would expect z axis to get highlighted, but x gets highlighted instead.

Screen Shot 2021-06-29 at 10 59 31 PM

**Comment by arodic** [comment]
Another issue is object sorting and transparency.

Gizmo objects are rendered as transparent without depth write/test. I think this was to make the geometry always be visible no matter what is in the depth buffer.

I notice in this version sometimes geometry from the back gets rendered on top. Perhaps there is a way to fix this.

**Comment by mrdoob** [comment]
@arodic Yeah, I noticed these issues too. It will definitely benefit of some iteration...

**Comment by nipmarsh** [comment]
The current version is really problematic because of these issues... In practice, the gizmo is unusable

**Comment by mrdoob** [comment]
@nipmarsh I use it every day. Seems usable to me?

**Comment by nipmarsh** [comment]
@mrdoob The problems are linked to @arodic comments. I have 50 users using the previous version daily and when I updated it to the last one, all my users screamed at me... Depending on the camera view the previous version can adapt whereas the new one cannot... to grab translation plane, you have to move your camera which in practice made the gizmo not very efficient

**Pull request merged**
