### PR TITLE
Material: Move .lights property to ShaderMaterial.

### LINKED ISSUE #13896: Crash setting .lights to false for MeshStandardMaterials
##### Description of the problem

When I set .lights to false on a MeshStandardMaterial the renderer crashes setting up the uniforms for the material.

Here is an example taken from the MeshStandardMaterial demo in the three documentation.

https://jsfiddle.net/cleveard/xyu5tav2/

I am not sure what is happening, but the shader is being created with the lighting chunks, but the uniform values aren't being initialized because material.lights is false.

##### Three.js version

- [ ] Dev
- [x] r91
- [x] r90

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #13896 and #10491

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good! I think we can cache the value [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1618):

```js
materialProperties.needsLights = materialNeedsLights( material );
```

And then use `materialProperties.needsLights` directly.

**Comment by Mugen87** [comment]
Done!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hmm, we should probably move the `lights` property from `Material` to `ShaderMaterial` next cycle?

**Comment by Mugen87** [comment]
Definitely. I think we should do this right now^^. Let me file a PR.

**Pull request merged**
