### PR TITLE
Reverse direction of glTF lights to comply with spec changes

### PR DESCRIPTION
**Pull request by MiiBond**
As discussed here:
https://github.com/KhronosGroup/glTF/pull/1223

We've decided that the default direction for an untransformed light node should be toward -Z rather than +Z.

@donmccurdy @mrdoob

### CODE REVIEW

**Comment by WestLangley** [comment]
three.js does not support transformed lights; it uses targets instead.

If and when three.js is modified to support transforms on lights, an untransformed light will face its local positive-z axis, just like other scene nodes.

**Comment by MiiBond** [comment]
Yes, I know.
The comment was referring to the glTF scene nodes, not the three.js ones. The loader sets the target for the light appropriately for three.js.

**Comment by donmccurdy** [comment]
The demo (https://rawgit.com/MiiBond/three.js/bde0cbdc9de0746398d2cc594608ee4d45f7c990/examples/webgl_loader_gltf_extensions.html) is not working for me with the lit model, looks like there is a git case issue with the `examples/models/gltf/[m|M]onster` folder?

**Comment by WestLangley** [comment]
It's up to you of course, but the spec change does not sound like a good idea to me.

**Comment by donmccurdy** [comment]
For technical/historical/API reasons? Or because r95 has already shipped with an experimental KHR_lights_punctual implementation?

**Comment by WestLangley** [comment]
(1) For the same reason three.js does: all scene nodes face the same direction when untransformed. (the camera is an exception, but it does not have to be part of the scene graph.) (2) I did not see a compelling reason for the change when reading your thread.

**Comment by donmccurdy** [comment]
Will comment in the other thread, but I'm having trouble coming up with a preference on this.

**Comment by mrdoob** [comment]
Moving it to r97. We'll see how we feel about it next month.

**Comment by donmccurdy** [comment]
Per most recent comment on the other thread (https://github.com/KhronosGroup/glTF/pull/1223#issuecomment-416820274), we're likely to go ahead with this change. Having the default direction of lights match the default direction of cameras — so that individual engines have to implement at most one variation of node transform — was the most compelling argument on +Z vs -Z so far.

However, waiting until r97 is fine with me.

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
The extension is highly likely to stick with –Z, matching default camera direction in glTF. Should be OK to merge this.

**Comment by donmccurdy** [comment]
Yes, that's all clear. The glTF spec on directional lights will read:

> Directional lights are light sources that act as though they are infinitely far away and emit light in the direction of the local -z axis. This light type inherits the orientation of the node that it belongs to but ignores position and scale. Because it is at an infinite distance, the light is not attenuated. Its intensity is defined in lumens per metre squared, or lux (lm/m<sup>2</sup>).

Because scale affects the direction from the light to its `.target` child, non-uniform scale will cause threejs to get results that are not consistent here (https://github.com/mrdoob/three.js/issues/14618) but I think that's a relatively minor issue that we can always deal with later.

**Comment by WestLangley** [comment]
@donmccurdy OK, thanks. I think we are all on the same page, then.

@mrdoob Given that the glTF developers seem determined to make this change, I think three.js would be wise to adopt the glTF convention regarding lights. Currently, this only affects `RectAreaLight`, because for now, it is the only three.js light whose orientation is defined by its quaternion.

I will file a PR to modify the convention for `RectAreaLight` if you agree to the change. The change should largely be transparent to the users as long as they use `lookAt()` to orient the light, instead of setting the quaternion directly.

**Comment by donmccurdy** [comment]
Note there will be no area lights in glTF for now - only punctual (point/spot/directional).

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
