### PR TITLE
Addons: Remove `HBAOPass`.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

I have explained in https://github.com/mrdoob/three.js/issues/27295#issuecomment-1839074202 and https://github.com/mrdoob/three.js/pull/27296#issuecomment-1837623787 why we should not have merged `HBAOPass` in the first place. I think it's better to revert  and redirect users to https://github.com/N8python/n8ao if they want N8AO. 

I should also mentioned that the addition of `HBAOPass` produced confusion in the community and (unfortunately yet another) somewhat toxic discussion at the forum (https://discourse.threejs.org/t/new-ambient-occlusion-example-hbao-vs-n8ao/58847).

### CODE REVIEW

**Comment by Rabbid76** [comment]
@CodyJasonBennett I'm not sure if a ❤️ is very empathetic here.

**Comment by CodyJasonBennett** [comment]
I'm not sure what you're saying, but this is what I wrote on the forum:

> Thank you for this. I was hesitant to even mirror this in public forks like `three-stdlib` since I was worried about community response and licensing. I noticed that significant code was copied/pasted verbatim, although there were physical enhancements. Maybe we can direct the author to the sources they referenced who have collaborated before so not all is lost.

**Comment by mrdoob** [comment]
Maybe another way to sort this out would by modifying the current code so it actually uses the HBAO algorithm.

@Rabbid76 did you get to implement to algorithm when you worked on it? Was it too slow?

**Comment by Rabbid76** [comment]
@Mugen87 I was not satisfied with my HBAO implementation, but I developed a GTAO algorithm based on it, GTAO builds on HABO and develops it further. In this sense, GTAO is a dedicated HBAO algorithm. My algorithm is based on https://github.com/Patapom/GodComplex/blob/master/Tests/TestHBIL/2018%20Mayaux%20-%20Horizon-Based%20Indirect%20Lighting%20(HBIL).pdf. The code could be adapted very easily.

**Comment by Mugen87** [comment]
How about renaming `HBAOPass` to `AOPass` and implement GTAO?

In the next step, I would suggest to remove `SSAOPass` and `SAOPass` so we only have `AOPass` with hopefully the best solution of all three.

**Comment by Rabbid76** [comment]
I could do that this evening (MET)

**Comment by Mugen87** [comment]
Awesome! I vote for this approach!

**Comment by mrdoob** [comment]
> How about renaming `HBAOPass` to `AOPass` and implement GTAO?
> 
> In the next step, I would suggest to remove `SSAOPass` and `SAOPass` so we only have `AOPass` with hopefully the best solution of all three.

I think it would be better to name it `GTAOPass` for now.

Once that's done, we can compare all the approaches and discuss which ones are redundant.

**Comment by Mugen87** [comment]
I'm fine with that! 

GTAO is awesome. For everyone who is interested in the technique, the respective paper is https://www.activision.com/cdn/research/Practical_Real_Time_Strategies_for_Accurate_Indirect_Occlusion_NEW%20VERSION_COLOR.pdf

**Comment by Rabbid76** [comment]
@Mugen87 Yes, that's it and I'll add it as a reference in the comments

**Pull request closed without merging**
