### PR TITLE
USDZExporter: Use scale input to tint the texture

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #26010

**Description**

Replaced canvas2d tint with `UsdUVTexture`'s `inputs:scale`.

### CODE REVIEW

**Comment by mrdoob** [comment]
@hybridherbst seems like the using `inputs:scale` only works in the USDZ viewer?

Screenshot 2023-05-08 at 18 44 22

Screenshot 2023-05-08 at 18 44 43

**Comment by mrdoob** [comment]
I should probably revert this...

**Comment by hybridherbst** [comment]
Not entirely sure what I'm looking at here. That looks like a bug in that viewer maybe.
It works fine in QuickLook, Omniverse, usdview, ...

**Comment by mrdoob** [comment]
MacOS Preview

Screenshot 2023-05-08 at 19 38 54

**Comment by mrdoob** [comment]
Okay, I'll leave it for now then.

**Pull request merged**
