### PR TITLE
Clock fix

### PR DESCRIPTION
**Pull request by Itee**
This PR fix the Clock that is un-stopable by default !

It keep complete backward compatibility, and keep the unstopable mode too.

Before merge this PR, please take time to think about the "unstopable" capability of the current Clock that in my sens should not be exist...

It allow in a certain way to do not start the clock but allow to get elapsed time and delta, and disabling the stop method... This is a weird/bad capability i think. 

So if you are agree to remove this capability please tell me before merge !!!

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... Do you mind elaborating a bit? I'm not sure what cases this solves.

**Comment by TristanVALCKE** [comment]
Ok.

For the moment (without this PR) you can do by default:

```javascript

	var clock = new THREE.Clock();
	clock.start();

	self.performance.next(123);
	assert.ok( clock.getElapsedTime() === 0.123 , "okay");

	self.performance.next(100);
	assert.ok( clock.getElapsedTime() === 0.223 , "okay");

	clock.stop();

	self.performance.next(1000);

        // This assert is FALSE ! You can't stop the Clock
	assert.ok( clock.getElapsedTime() === 0.223 , "don't update time if the clock was stopped");

```

Why ? Because in `getDelat` that is call by `getElapsedTime` you have:

```javascript

getDelta: function () {

	var diff = 0;

	if ( this.autoStart && ! this.running ) {

		this.start();

	}

	if ( this.running ) {

		var newTime = ( performance || Date ).now();

		diff = ( newTime - this.oldTime ) / 1000;
		this.oldTime = newTime;

		this.elapsedTime += diff;

	}

	return diff;

}

```

and `autostart` is true by default (that is bad) and you can't set it to false by default due to backward compat...

The goal of this PR is to allow to stop the clock without breaking backward compatibility by default !


In regards to unstopable mode, i keep the "feature" in case it was wanted but i'm really not sure it was !

**Comment by TristanVALCKE** [comment]
@mrdoob So... what about this PR ? Keep i the unstoppable "features" ? Or do you want any other change before apply this fix ?

**Comment by mrdoob** [comment]
Hmm, I'm not sure this is the right fix.

**Comment by Mugen87** [comment]
The dependency of `.getElapsedTime()` to `.getDelta()` needs to be solved in a different way. Maybe we could introduce a new `Time` class some day with a different API than `Clock`.

**Comment by mrdoob** [comment]
@Mugen87 Agreed!

**Pull request closed without merging**
