### PR TITLE
WebGL2 Transformfeedback examples

### PR DESCRIPTION
**Pull request by sketchpunk**
**Description**
Exposing Attributes in WebGLRenderer to gain access to reference to GL buffers. Doing so is enough to use webgl to execute transform feedback / compute shaders on 3js geometry attributes.

Example 1 : webgl2_transformfeedback_instancedmesh
How to use a compute shader to manipulate the instanceMatrix of an instancedMesh. Example shows how to modify a Mat4 as vec4 chunks. It will translate, rotate and scale a cube while being animated on a trefoil curve.

Example 2 : webgl2_transformfeedback_pointcloudobb.html
Use a compute shader to modify 4 point meshes by testing each point against an array of OBBs. A point will have its color changed by mixing the colors of OBBs that it intersects. This example also builds a data texture using webgl api as a way to have random access to the OBB array data.

### CODE REVIEW

**Comment by mrdoob** [comment]
This looks great to me!

**Comment by mrdoob** [comment]
@Mugen87 @sunag

1. What do you guys think about the `this.attributes` addition? Should it be `this.getAttributes()` instead?
2. How would this be done in the `WebGPURenderer`?

**Comment by Mugen87** [comment]
> Exposing Attributes in WebGLRenderer to gain access to reference to GL buffers.

Instead of exposing `attributes, you could just use the existing [GLBufferAttribute](https://threejs.org/docs/index.html#api/en/core/GLBufferAttribute) class?

**Comment by sketchpunk** [comment]
> > Exposing Attributes in WebGLRenderer to gain access to reference to GL buffers.
> 
> Instead of exposing `attributes`, you could just use the existing [GLBufferAttribute](https://threejs.org/docs/index.html#api/en/core/GLBufferAttribute) class?

Didn't know about GLBufferAttributes. Looking at the doc, looks like I have to create the gl buffers myself using the GL context then pass it to the object. This complicates things as I'm modifying threejs existing primitives & instance meshes with compute shaders. All the attribute buffers are created by threejs, using GLBufferAttribute means I'll have to create custom version of those things. In the event the context is lost, all those geometries will need to be recreated from scratch again if I had to manage the buffers whereas it is now, I'm using modified version of 3js in production, it handles that bit itself, I just need to recreate the compute shader & data texture.

I understand not exposing the internals of the renderer, but its already being done with 'properties' in the same function I'd like to expose attributes in. I currently use properties to get the GL reference to framebuffers to do custom things like using webgl's blitFrameBuffer API. If framebuffers are exposed, why not regular buffers.

**Comment by Mugen87** [comment]
> If framebuffers are exposed, why not regular buffers.

That is a fair point but `properties` was exposed at a time where we wasn't aware about the related consequences. Or in other words, doing things wrong in the past does not justify doing things wrong now.

I was hoping having a dedicated API at some point like outlined here: https://github.com/mrdoob/three.js/pull/14503#issuecomment-950887344

In the meanwhile, I would prefer to use the options we already have.

**Comment by sketchpunk** [comment]
> In the meanwhile, I would prefer to use the options we already have.

Thats the thing, the options available don't really help. In the examples I provided, GLBufferAttribute wouldn't be a solution, instead it would complicate matters by needing to create custom version of primitives & InstancedMesh. I've done things like that in the past, a few 3js versions out things break that I'd have to fix up my custom versions of threejs objects.

To me, this is the path of least resistance to utilize compute shaders on existing threejs features.

**Comment by sunag** [comment]
I think when we see the renderer losing control of the backend calls, it is because something could be improved. I would not like to see the WebGPU API exposed in the WebGPU Examples... On the other hand, the example is well done and can temporarily help until a Three.js API is oriented towards this. I don't know how much impact this would have, @Mugen87 would know how to respond better.

About `WebGPURenderer`, I think `Transformfeedback` would have an oriented to be used in `WebGLBackend.compute()`, because `WebGPURenderer.compute()` is aimed at this kind of solution.

**Comment by sketchpunk** [comment]
Curious, whats the final decision on this? Accepted or not?

If it does, I'll like to attempt two more examples. One doing Dual Quaternion Skinning & maybe animation with compute shader while threejs renders a character as a static mesh without using the built in skinning features.

The other example using a procedurally generated spring mesh, how to properly compress & expand it. Doing regular scaling stretches the mesh which doesn't look right. 

Maybe these 4 test cases can be useful for further developing an abstraction layer down the line to properly run transformfeedback in threejs.

**Comment by CodyJasonBennett** [comment]
I'm not at liberty to share details, but I've used transform feedback in my prior work which is somewhat publicized in https://twitter.com/onirenaud/status/1592183793548677125. I'd be happy to help champion or clear remaining blockers, but I don't recall this feature being particularly involved.

> About `WebGPURenderer`, I think `Transformfeedback` should be oriented to be used in `WebGLBackend.compute()`, because `WebGPURenderer.compute()` is aimed at this kind of solution.

I think so too since they provide similar benefits with GPU-side work and how precious texture memory is, although we don't get fancy storage memory or real compute access with shared memory in WebGL. I've even modeled compute in my toy library after it since I could offer an identical API and examples https://github.com/CodyJasonBennett/four#compute. I'm working on a few GPU-driven examples which I wanted to port to WebGL 2 to prove the similarity, but I think this and uniform buffers (I'm not sure if we cleared every issue?) could use some work to at least serve as a stepping stone to WebGPU.

**Comment by sketchpunk** [comment]
> Edit: I see that almost no work needs to be done if we're to rely on internal `attributes`? I'm not super happy about requiring WebGL code anywhere in user-land though.

Yes, it's a quick & dirty solution but it's better than nothing at all. I know there are issues doing this, like Vao bindings aren't being cleaned up correctly by the 3js renderer, so I have to clear it before I do any sort of compute or meshes will be harmed in the process. In my opinion, this is for someone who needs compute now & has some know-how of webgl itself. In our case, we really need compute as it was the only solution to a problem, so now we run a modified version of the library in production just so we can get access to attributes, this itself isn't ideal but we don't have much of a choice.

Since its a tiny change & it mirrors "properties" which I also use in production to access framebuffer references to use with webgl's blitFramebuffer functionality since 3js doesn't have support for it.  If there is no support for transformfeedback then the only thing people need is access to buffer references to be able to read & write into them which exposing attributes will do.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/14416#issuecomment-2160471897.

**Pull request closed without merging**
