### PR TITLE
MeshSurfaceSampler: Incremental, weighted surface sampling

### PR DESCRIPTION
**Pull request by donmccurdy**
**Summary:**
- Removes GeometryUtils random point selection.
- Adds MeshSurfaceSampler for incremental, weighted surface sampling.
- Adds 'webgl / instancing / scatter' example with InstancedMesh.
- Adds 'Flower.glb' sample for the example.

**Details:**

This PR removes a large portion of GeometryUtils, which focused on sampling points from the surface of Geometry and BufferGeometry instances. The previous implementation sampled a fixed number of points up front, in roughly `O(n*m*log(m))` time, for 'n' samples and 'm' surface faces. MeshSurfaceSampler — the new implementation — despite avoiding object creation while sampling, has pretty much the same performance for a fixed number of samples. However, it adds several features that I think are useful improvements:

1. _Incremental sampling._ Build once (`O(m)`) then sample any number of times (`O(log(m)`).
2. _Provides normals._ Useful for orienting a sample relative to the surface.
3. _Weighted sampling._ Sampling can be weighted based on an arbitrary attribute. For example, a user could paint vertex colors or UVs on the surface, and use those to influence the distribution of hair or particles.

MeshSurfaceSampler supports BufferGeometry, but not Geometry.

This PR includes another InstancedMesh demo, which randomly scatters animated instances on the surface of a mesh, relocating them randomly when they expire. The example also makes better use of InstancedBufferGeometry than #18033 by setting per-instance colors via InstancedBufferAttribute. Happy to do a bit more fine-tuning on the demo...

Demo: https://raw.githack.com/donmccurdy/three.js/feat-randomsurfacesampler/examples/?q=instanc#webgl_instancing_scatter

### CODE REVIEW

**Comment by Mugen87** [comment]
While you're at it: It think it's okay to remove `GeometryUtils.merge()` and `GeometryUtils.center()`. Both functions are deprecated for a while now...

**Comment by donmccurdy** [comment]
> While you're at it: It think it's okay to remove GeometryUtils.merge() and GeometryUtils.center(). 

✅ Done

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
This looks great!

Is there a reason we need `js/math/MeshSurfaceSampler.js` though?
I think it's better to only have `jsm` version of new files added.

**Comment by mrdoob** [comment]
Also, noob question...
What does weighted distribution show in this example?

**Comment by donmccurdy** [comment]
>  I think it's better to only have jsm version of new files added.

Sounds good, done.

> What does weighted distribution show in this example?

In this example it should be concentrating the flowers in areas with higher `uv.x` values. That's contrived as a simple test here, but a more interesting example would be something like [The Basics of Grass • Section 4](https://generallyplayful.com/vfx-animation/blender-30-30-day-09/), where you paint vertex colors or vertex weights in Blender and use those to influence foliage placement or particle emissions. More details in https://github.com/mrdoob/three.js/pull/18074 (documentation).

**Comment by mrdoob** [comment]
I see I see. Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
