### PR TITLE
Editor: Updated Sidebar.Project.js

### PR DESCRIPTION
**Pull request by linbingquan**
Fixed bug for toggled `physicallyCorrectLights` button, renderer changed without `toneMappingExposure` value.

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, changing the tonemapping exposure does not require to rebuild the renderer.

Can you please explain in more detail how the bug occurs.

**Comment by linbingquan** [comment]
> Um, changing the tonemapping exposure does not require to rebuild the renderer.
> 
> Can you please explain in more detail how the bug occurs.

I am not good at English, I speek Chinglish, I hope I can explain clear.

1. Set `Exposure` 0.1 value
2. Toggle `Physically corrent lights` checkbox.
3. The renderer is not `Exposure` 0.1 value result. 

image

**Comment by Mugen87** [comment]
Okay, that helps! I understand now the issue. In this case, we also have to do the same for `toneMappingWhitePoint`. Can you please update the PR?

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
