### PR TITLE
Parse and set smooth shading value in OBJs

### PR DESCRIPTION
**Pull request by dhritzkiv**

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you think it would be possible to make it so one could pass a `MTLLoader` to `OBJLoader` so we can remove this `OBJMTLLoader` duplication?

**Comment by mrdoob** [comment]
Also, at the moment `OBJMTLLoader` generates `Geometry` which is not very efficient...

**Comment by dhritzkiv** [comment]
I could look into it cleaning up + deduping code. I always meant to (as my project relies on OBJ+MTL parsing heavily), but it was always daunting, and a case of if-it-ain't broke-don't-fix-it. 

Any specific direction I take? Or should I simply have the `OBJLoader` load and parse an optional MTL file?

**Comment by dhritzkiv** [comment]
And switching to the `OBJ*Loader` to use `BufferGeometry` was going to be my next task, as r72 changed the behaviour of my dependent code (`ShaderMaterial` no longer works with `Geometry`)

**Comment by mrdoob** [comment]
I think I would so something like this:

```javascript
var loader = new THREE.MTLLoader();
loader.load( 'name.mtl', function ( material ) {

    var loader = new THREE.OBJLoader();
    loader.setMaterial( material );
    loader.load( 'name.obj', function ( object ) {

        scene.add( object );

    } );

} );

**Comment by dhritzkiv** [comment]
Makes sense to me.

**Comment by mrdoob** [comment]
Or, considering that there are more than one material...

```javascript
var loader = new THREE.MTLLoader();
loader.load( 'name.mtl', function ( materials ) {

    var loader = new THREE.OBJLoader();
    loader.setMaterials( materials );
    loader.load( 'name.obj', function ( object ) {

        scene.add( object );

    } );

} );
```

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7195

**Pull request closed without merging**
