### PR TITLE
CurveExtras: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
Added default value to `VivianiCurve`'s parameter and unify names.

### CODE REVIEW

**Comment by WestLangley** [comment]
Are these default parameter values arbitrary? Why not make the default 1?

And do that for all geometries.

**Comment by Mugen87** [comment]
> Are these default parameter values arbitrary?

No. For example an instance of `VivianiCurve` with `scale` = `1` looks terrible.

image

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
>For example an instance of VivianiCurve with scale = 1 looks terrible.

That is not a rendering of a `VivianiCurve `. That is a rendering of a `TubeBufferGeometry` with a `radius` that is not compatible with a Viviani `scale` of 1.

**Comment by Mugen87** [comment]
Oh, i did not view it from this point. What do you suggest now? I think it's basically useful when the curves in `CurveExtras` produces comparable results with the same `TubeBufferGeometry` setup.

**Comment by WestLangley** [comment]
> I think it's basically useful when the curves in CurveExtras produces comparable results with the same TubeBufferGeometry setup.

The curves in `CurveExtras` can be used for purposes other than as the path for a tube. And besides, we are only talking about default values. In the examples, pass in the value you prefer.

Also, I do not think a scale of zero makes sense, so you can just use this pattern:
```javascript
this.scale = scale || 1;
```

**Comment by Mugen87** [comment]
I see. Yeah, sounds reasonable. So changing things would mean:
- standardize default values (like #12418)
- check and adjust example code, if necessary

**Pull request merged**
