### PR TITLE
Daydream: Controller and Example

### PR DESCRIPTION
**Pull request by Mugen87**
see #10586

Just a first implementation, so we have a little working basis 😉 

I've tried to keep the code similar to `ViveController`. Same for the example.

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks!

**Comment by judax** [comment]
I think there is a bug in the code: 

if ( axes[ 0 ] !== gamepad.axes[ 0 ] || axes[ 1 ] !== gamepad.axes[ 1 ] ) {

should be

if ( axes[ 0 ] !== gamepad.axes[ 0 ] && axes[ 1 ] !== gamepad.axes[ 1 ] ) {

Sorry, I will send a PR next time :).

**Comment by Mugen87** [comment]
@judax Good catch! :wink:

**Pull request merged**
