### PR TITLE
Log image.src in Power of Two image texture resize warning.

### PR DESCRIPTION
**Pull request by ngokevin**
#14729

### CODE REVIEW

**Comment by takahirox** [comment]
If I'm right, `HTMLCanvasElement` and `ImageBitmap` don't have `.src` property?

**Comment by ngokevin** [comment]
Updated with a little `|| ''`

**Comment by looeee** [comment]
Can the image src be a base 64 string? This could cause console crashes when logging lots of large images if so.

**Comment by Mugen87** [comment]
I'm not sure if the library really needs to log properties of the image object. Since there is a console message, it should be easy for users to set a breakpoint and then inspect the image object in detail with the debugger.

**Comment by mrdoob** [comment]
@ngokevin maybe this code could sit in a-frame instead?

**Pull request closed without merging**
