### PR TITLE
Material: Add `TwoPassDoubleSide`.

### LINKED ISSUE #24711: Option to disable two-pass rendering of transparent objects
**Is your feature request related to a problem? Please describe.**

There's a [hardcoded path](https://github.com/mrdoob/three.js/blob/d081c5a3501d272d19375fab1b01fedf9df29b22/src/renderers/WebGLRenderer.js#L1334) for rendering transparent objects with doublesided materials. However it's not particularly suitable for our use-case since our models are optimized for a single blended pass with backface fulling disabled. That leads to artifacts.

**Describe the solution you'd like**

An option for materials to override this behaviour.

**Describe alternatives you've considered**

Right now we're forced to patch by hand and commit into our repo a copy of threejs build.

### LINKED ISSUE #25149: gl_FrontFacing fails when a DoubleSide object is marked as transparent
**Describe the bug**

I have a fragment shader that uses the OpenGL boolean variable [`gl_FrontFacing`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_FrontFacing.xhtml) to change the color of the fragment for backside faces.

This works fine as long as the material is not `transparent`. This seems to be related to how `WebGLRenderer` handles double-sided transparent objects as two different render calls :

- https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L827
- https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1313

**To Reproduce**

1. Create a material with `transparent` as `true` and `side` as `DoubleSide`.
2. Use the following fragment shader: 
```glsl
void main() {
    if (gl_FrontFacing) {
        gl_FragColor = vec4(1, 0, 0, 1);
    } else {
        gl_FragColor = vec4(0, 0, 1, 1);
    }
}

```
4. The backside of the object should be blue, but it its red instead. Set `transparent` to `false`, and the backside becomes blue.

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-dev](https://jsfiddle.net/jmef760t/15/)

**Expected behavior**

The backside should stay blue even when `transparent` is `true`.

**Screenshots**

See the jsfiddle.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: Tested on MacOS X, Windows 10, and Ubuntu 22.04
 - Browser: Chrome, Firefox
 - Three.js version: all ?

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed https://github.com/mrdoob/three.js/issues/24711.
Fixed https://github.com/mrdoob/three.js/issues/25149.

**Description**

Alternative implementation to #25156 as suggested in https://github.com/mrdoob/three.js/issues/24711#issuecomment-1360917554. Instead of introducing a new `Object3D` property, a new `Material.side` constant controls the rendering of double-sided transparent objects instead.

### CODE REVIEW

**Comment by elalish** [comment]
This sounds good, but is it a regression by default now? I think `GLTFImporter` sets `Material.side = DoubleSide` for double-sided materials. Should we update it to set `Material.side = TwoPassDoubleSide` when `BLEND` mode is used?

**Comment by donmccurdy** [comment]
I don't think I'd consider it a regression, one way or the other. But we can do whichever we think is likely to be the best choice for most users, and I think I'm fine with either option.

**Comment by LeviPesin** [comment]
Two-pass rendering feels like something that should be opt-in (as after this PR) rather than opt-out.

**Comment by Mugen87** [comment]
According to the user feedback in the last month I think that, too.

**Comment by elalish** [comment]
My impression from the user feedback (though I can't find the older threads now) was that the main reason to avoid two-pass rendering was for performance in some non-PBR use cases. For PBR, we get pretty ugly artifacts without the two-pass, hence why it was added. Since GLTF is for PBR, this is why I'd recommend changing this default in the Loader. Especially because this will be a pretty tricky change for a user to make after the fact, and also a difficult artifact to debug in the first place in order to find this solution.

**Comment by donmccurdy** [comment]
I don't think I agree that two-pass rendering is more necessary for PBR materials than any other materials, or that the performance cost is any less relevant with PBR. Or that "GLTF is for PBR" for that matter. We can't advise people to use FBX just because they want unlit materials, glTF is also a great choice for that.

Both the visual issue we originally solved here, and the performance regression introduced by our fix, are difficult for users to debug themselves. It is probably most important that we be consistent in whatever we decide is the right default.

**Comment by WestLangley** [comment]
I, too, think two-pass rendering for transparent double-sided materials should be the default. @mrdoob also thought so, which is why he added the feature.

IMO, this has nothing to do with glTF or PBR.

I also think users who are rendering single-plane, transparent, double-sided objects and are having a performance issue should have the ability to opt-out.

This means reverting this PR in favor of a different API.

//

Also, IMO, this PR does not "fix" #25149 as claimed in the original post above. The issue with `gl_FrontFacing` remains. But that is a separate issue.

**Comment by donmccurdy** [comment]
> This means reverting this PR in favor of a different API.

I don't think I followed the link between the earlier sentences and this conclusion, why do you feel that `TwoPassDoubleSide` is the wrong API? I do prefer it to having a new property on THREE.Object3D.

**Comment by elalish** [comment]
Maybe something like `SinglePassDoubleSide` so that `DoubleSide` can have the same default behavior as before?

**Comment by WestLangley** [comment]
@donmccurdy I thought we would have to revert to an different API, but maybe the suggestion by @elalish is OK...

**Comment by donmccurdy** [comment]
Thanks @elalish and @WestLangley! 

If we think that two-pass rendering is the right default for most users then giving single-pass rendering another name makes sense to me. I don't know whether @mrdoob still prefers that, as the performance drawbacks were less obvious at the time of the original change. 

Aside — There's some advantage to leading with a common prefix when we can. Like `DoubleSide` and `DoubleSideSinglePass`. Both names will appear side-by-side in autocomplete and other developer tooling, making the choice explicit and harder to overlook.

**Comment by WestLangley** [comment]
Well, `DoubleSideSinglePass` is better IMO, 

...but this is such an edge case, I compare it to `frustumCulled = false`, and would personally prefer an opt-out at the object level instead of `material.side = DoubleSideSinglePass`.

**Comment by WestLangley** [comment]
`material.transparent` takes two values.

`material.side` now takes four values.

But all 8 possible combinations do not make sense.

That means there is something wrong with the API.

**Comment by WestLangley** [comment]
Setting `material.side` to `TwoPassDoubleSide` renders single-sided when `material.transparent` is `false`.

If that combination makes no sense, then the API is not the right API.

If that combination does make sense, then this PR is buggy.

**Comment by Mugen87** [comment]
`TwoPassDoubleSide` is only intended for _double-sided, transparent_ objects.

THB, I see no reason for changing anything since I question your premise that every possible combination of properties has to make sense. Let's just take `OrbitControls` as an example. Certain properties only makes sense when using perspective cameras. Others are intended for orthographic. That does not mean `OrbitControls` has a bad API.

**Comment by donmccurdy** [comment]
> TwoPassDoubleSide is only intended for double-sided, transparent objects.

Is this necessarily true? I can imagine using TwoPassDoubleSide for additive blending without `.transparent = true`. Not sure if it solves a problem or not, but it doesn't seem unreasonable to allow and so I'm not sure the API needs to make that impossible.

**Comment by WestLangley** [comment]
>TwoPassDoubleSide is only intended for double-sided, transparent objects.

With all due respect, to me, that means the API is a poor one.

I would vote to revert to the previous implementation where two-pass was the default, and add a per-object out-out akin to `.frustumCulled`. Opting out is an edge case.

**Comment by mrdoob** [comment]
Something like this?

```js
if ( material.transparent === true && material.side === DoubleSide && object.renderDoubleSideSinglePass === false ) {

	material.side = BackSide;
	material.needsUpdate = true;
	_this.renderBufferDirect( camera, scene, geometry, material, object, group );
	material.side = FrontSide;
	material.needsUpdate = true;
	_this.renderBufferDirect( camera, scene, geometry, material, object, group );

	material.side = DoubleSide;

} else {

	_this.renderBufferDirect( camera, scene, geometry, material, object, group );

}
```

**Comment by gkjohnson** [comment]
Fwiw if a material is opaque and set to "TwoPassDoubleSide" I'd expect it to render the opaque object double sided. Rendering the object single sided is clearly misleading.

**Comment by mrdoob** [comment]
@gkjohnson Oh! Didn't think of that. Right...

**Comment by jtbandes** [comment]
This change should be called out in https://github.com/mrdoob/three.js/wiki/Migration-Guide for r148, since the default behavior for certain objects has changed.

**Comment by gkjohnson** [comment]
Added:

> - `Material.side = DoubleSide` no longer renders a transparent object in separate front and back passes. Use `TwoPassDoubleSide` for two-pass transparent rendering.

**Comment by d3x0r** [comment]
For a few versions now I can't get the back of a solid object to render... 
I have a sphere, with 2 halves.  The back half is a solid, double sided, non transparent texture.  The front is a front-sided transparent texture, so I could see the inside of the ball.  This used to work (I don't recall the exact version)
But now, I can't get the back side of the sphere to ever show - if I do 'DoubleSided' or 'FrontSide' it shows, but BackSide or DoubleSide looking at the back side doesn't show.  I'm just using .MeshPhongMaterial and some geometry.  I'm sort of lazy to simplify this.
I thought maybe this new option would work - but then what, i have to make the back texture also double sided transparent?

**Comment by d3x0r** [comment]
This is a VERY old version that was barely even working; but is enough to show that it shows the inside-back side of half spheres...  This uses three.js 111
https://d3x0r.github.io/three.js-double-side-test/old/index.html

this is the current version (150dev)
https://d3x0r.github.io/three.js-double-side-test/new/index.html

This is the repo... 
https://github.com/d3x0r/three.js-double-side-test
phong init (new)
https://github.com/d3x0r/three.js-double-side-test/blob/main/new/ballView.mjs#L860

phong init (old)
https://github.com/d3x0r/three.js-double-side-test/blob/main/old/view.js#L395


I am doing lots of 'work' to build the sphere mesh geometries... but the winding order is correct for the front, so I'd think the back would also be right.
(Though I may have a double-flip and have scaling factors that are (-1,-1,1)  too)

I do apologize for not minimizing it to just a plane or something...

**Comment by mrdoob** [comment]
@d3x0r Can you please create a minimal jsfiddle that shows the issue? We can't help you otherwise.

**Comment by d3x0r** [comment]
This should have a 4 pixel image included... without the .map it doesn't not show the backs... But not it's not showing the texture either.

https://jsfiddle.net/ptrceavx/  (105)   if ( set 	, transparent : true ) (like line 173 ) then nothing shows....

https://jsfiddle.net/26dybawe/  (149)  

I don't know why the texture isn't showing though- it's all black in the simplified version.
This is why I tried to avoid the fiddle, becaue the answer will be 'no I can't' and then it'll still be 'well sure, we can see on your github.io links that it's not working, but JS fiddle works so it's just you'.   It's not.

**Comment by mrdoob** [comment]
Is that as simple as you're able to make the example?
Is everything in the code you shared necessary to show the issue you're having?

**Comment by mrdoob** [comment]
Here's a simple jsfiddle you can build on top of: https://jsfiddle.net/em4j9hvu/

**Comment by d3x0r** [comment]
https://jsfiddle.net/86fmkban/2/ added texture - added to window (small red dot upper left, so you can see it IS a valid PNG image) ... it's 2 pixels opaque red and 2 pixels mostly opaque red (slightly transparent)
adding transparent:true or alphaTest:true to the MeshBasicMaterial makes the cube disappear; the cube is black - the default clear color was black - changed it to a dark grey so I can see the black cube.  Adding map: to the cube makes it black.

**Comment by mrdoob** [comment]
Here's your jsfiddle fixed: https://jsfiddle.net/6espjogh/

Please, continue working on the jsfiddle until it shows the issue you're trying to describe.

**Comment by d3x0r** [comment]
https://jsfiddle.net/7ac2wfh8/3/  seems to work fine still.   Includes BufferGeometry, OrthoCamera, phong material, complex geometry -- I see no difference between This and mine other than count of objects; but I still have no backsides.  Matched the canvas to be transparent too.  swapped the image to the high res one I'm using(worked fine so went back to the small one).  
Includes all of the objects; and is copy of the same int code that fails... Thanks for the test - but I actually see 0 difference between this and my code; and  the fiddle appears to work fine.    (Yes, one object now gets blocked by another, but that's because of the order of the objects in the scene, and that's working right; there's never a time when double side doesn't show back side also.  I even updated to use the exact same version of tthree.js the module is using, and it's still failing for me; but it shouldn't be (according to the fiddle with the same code)

**Comment by mrdoob** [comment]
Sorry, I can't read blobs of text like that.

I've asked ChatGPT to summarise it:

> The author is comparing their code to a working example on jsfiddle (https://jsfiddle.net/7ac2wfh8/3/), but their code is failing despite having no apparent differences. The author has tried various changes, such as making the canvas transparent and swapping the image, but the issue persists. The code in the jsfiddle is a copy of the author's code and should be working, but the author is still encountering problems.

**Comment by mrdoob** [comment]
Credits to thespite on twitter for the ChatGPT idea:
https://twitter.com/thespite/status/1624206812416299008

**Comment by d3x0r** [comment]
> Credits to thespite on twitter for the ChatGPT idea: https://twitter.com/thespite/status/1624206812416299008

Nice.  That IS what I said.

https://jsfiddle.net/ox1bqyse/
Added
```
 cube.scale.set( -1.1, -1.1, 1.1 );
```

Anything > 1 for scale causes the back to not show.

**Comment by mrdoob** [comment]
You need to add `side: THREE.DoubleSide` to the material.

**Comment by mrdoob** [comment]
> Nice. That IS what I said.

Maybe you can use ChatGPT to summarise your text before posting here next time.

**Comment by sketchpunk** [comment]
I'm having an issue related to this and getting gl_FrontFacing to work right. I setup a simple jsfiddle example : 
https://jsfiddle.net/sketchpunk/bnmy0Lv3/19/

WIth transparent:true, both faces get colored red.  If I turn transparent:false then uncomment the discard condition in the fragment shader, then both faces get different colors. Not sure if its a depth issue since I'm using a sphere and trying to hide half of it.

For context, I'm trying to recreate minionsart's fake liquid shader from unity.

**Comment by WestLangley** [comment]
@sketchpunk For a workaround, see https://github.com/mrdoob/three.js/issues/25149#issuecomment-1353614434. It will work for `ShaderMaterial`; not `RawShaderMaterial`.

You can also set `material.forceSinglePass = true`, but depending on your use case, that may cause artifacts we aim to prevent.

If you need more help, please post at the [forum](https://discourse.threejs.org).

**Comment by d3x0r** [comment]
> I'm having an issue related to this and getting gl_FrontFacing to work right. I setup a simple jsfiddle example : https://jsfiddle.net/sketchpunk/bnmy0Lv3/19/
> 
> WIth transparent:true, both faces get colored red. If I turn transparent:false then uncomment the discard condition in the fragment shader, then both faces get different colors. Not sure if its a depth issue since I'm using a sphere and trying to hide half of it.
> 
> For context, I'm trying to recreate minionsart's fake liquid shader from unity.

If you move the ball to y=-0.5 instead of y=0.5 it works (?)

**Comment by mrdoob** [comment]
It has been resolved already:
https://twitter.com/SketchpunkLabs/status/1638750725453885440

**Pull request merged**
