### PR TITLE
FileLoader: Add response modifier.

### LINKED ISSUE #10706: AudioLoader and LoadingManager onLoad Race
##### Description of the problem 

`AudioLoader` calls `scope.manager.itemEnd` (through the file loader) after loading the buffer, but its own `onLoad` after decoding it. Since decoding the buffer is asynchronous (or at least, has a callback) you can get into a race condition if the audio loader is the last loader in the loading manager's queue, where the manager thinks all of it's items are finished but the individual loaders haven't finished parsing. We noticed this in our preloading situation and had to implement our own loading queue that used the per-item `onLoad` to tick off complete items.

Unfortunately, looking at FileLoader/AudioLoader source, I'm not sure how to fix this or if it's even a concern; maybe the easiest solution to just clarify in the docs that `LoadingManager#onLoad` only indicates the network request is finished, and doesn't indicate that the data has been parsed.

##### Three.js version

- [x] r84

##### Browser

- [x] All of them

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #10706.

This is a new attempt of #13725 but now with a more generic interface. The idea is to introduce the possibility to add a response modifier to `FileLoader`. This callback function can be used to post-process raw response data before handing them over to the `onLoad()` callback. 

This new interface is used by `AudioLoader` to implement the audio decode. In this way, it's actually possible to cache the decoded audio data! Before this change, the raw buffer data were cached which lead to #13710. The workaround so far was to just clone the buffer data before a decode which is more or less a hack.

The timing of when `LoadingManager` triggers its `onLoad()` callback is now correct, too.

### CODE REVIEW

**Review by ViniciusFXavier — APPROVED** [review]
👍

**Comment by mrdoob** [comment]
@Mugen87 Sorry for not checking this before. How do you feel about this solution?

**Comment by Mugen87** [comment]
Well, it was the best solution I could come up with in order to solve #10706. At least it was better than #13725^^.

I would merge it instead of keeping #10706 unsolved. This issue can be quite confusing for users.

**Comment by GN-c** [comment]
is this solution pushed to release?

**Comment by DRL9** [comment]
How about add a error callback to `responseModifier`? 
```ts
responseModifier: (
		response: string | ArrayBuffer,
		callback: ( response: any ) => void,
                onError: ( err:Error ) => void
	) => void;
```
This method can propagate errors that occur during decoding. [#21754](https://github.com/mrdoob/three.js/issues/21754)

**Comment by Mugen87** [comment]
Sounds good. However, the general approach of having an additional callback for solving #10706 seems questionable. Although I still think it's better than no solution 😅 . 

Besides, #21754 normally only happens if you try to load an unsupported audio format. This can be avoided on app level by only requesting a format which the browser knows.

**Pull request closed without merging**
