### PR TITLE
Examples-Loaders: move to es6 class syntax

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
related: #19061

This PR should not be pulled unless the related PR is merged first.

Various Loaders were not included in the init commit because of the following:
-global namespace pollution if anon functions unwrapped
-possible name collisions or issues (`KhronosTextureContainer`, `MaterialCreator`...)

The `webgl_loader_texture_rgbm` example did not use a loader.

### CODE REVIEW

**Comment by munrocket** [comment]
Tests is ok here.

**Comment by mrdoob** [comment]
`examples/js` are supposed to work with "old" browsers.
`examples/jsm` could move to classes, but I don't know what's the right way of doing it yet.

**Comment by DefinitelyMaybe** [comment]
Well, there might be a bit of a mess to sort out here then. As far as I've understood (and used) thus far, the modularize.js script is used to generate the files in `examples/jsm/`, so there isn't a 'lets move `examples/jsm` to classes' without disjointing those two folders.

Meanwhile there's [this comment](https://github.com/mrdoob/three.js/pull/17276#issuecomment-534553025) from last year about how support for old browsers could be handled.

From a project managers perspective, I'd assume there's the contention between new development and there potential unintended consequences of said new development but until someone can throw around some solid numbers or tests or research or something, it's all hearsay. If angry/disappointment/upset emails/messages are the only sample of which decisions are made, you will never get anywhere. Someone will always be upset over something.

**Comment by mrdoob** [comment]
> If angry/disappointment/upset emails/messages are the only sample of which decisions are made, you will never get anywhere.

We have crossed similar bridges in the past. We'll figure it out.

**Comment by donmccurdy** [comment]
> examples/js are supposed to work with "old" browsers.

@mrdoob I take it you'd prefer not to break that compatibility with old browsers between now and the deletion of this folder?

**Comment by mrdoob** [comment]
> @mrdoob I take it you'd prefer not to break that compatibility with old browsers between now and the deletion of this folder?

Yeah, I think it's better if things suddenly not work at all than kind of work.

**Pull request closed without merging**
