### PR TITLE
SVGLoader: Apply default values when using getAttribute().

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: see  https://github.com/mrdoob/three.js/commit/330b18605ae145604f4168cf70802621f11ea2a1#commitcomment-48264586

**Description**

That fixes the broken `Defs` and `Defs2` tests.

### CODE REVIEW

**Comment by Mugen87** [comment]
Used the initial values from https://www.w3.org/TR/SVG2/shapes.html.

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev1/examples/webgl_loader_svg.html

**Comment by mrdoob** [comment]
Good catch!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
