### PR TITLE
New StereoCamera class (altered from StereoEffect) and example

### PR DESCRIPTION
**Pull request by owntheweb-archive**
StereoCamera is based on StereoEffect, only it returns the left/right
cameras instead of rendering an effect. This makes it possible to apply
effects with EffectComposer and others, rendering the scene separately.

### CODE REVIEW

**Comment by owntheweb** [comment]
This is my first pull request attempt with three.js. I'm happy to make any tweaks and resubmit if needed. Have an awesome day.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/blob/dev/src/cameras/StereoCamera.js

😇

**Comment by owntheweb** [comment]
Oh! I'm a touch behind the curve lol! :blush: 

Well, good to know I'm in sync with what's at top of mind. Thanks for what you do.

**Comment by owntheweb** [comment]
Closing request, already covered

**Pull request closed without merging**
