### PR TITLE
Updated docs for DataTexture.

### LINKED ISSUE #7062: Let DataTexture default to Nearest filtering
Using `DataTexture` with `FloatType` and default filters silently requires yet another extension for the linear filtering.

For that reason, and also as a general matter of clarity, the default should be Nearest filtering. If linear filtering is actually desired, it better be explicit.

Almost a bug, subtle and inconvenient: I once got bitten by it and reading #7060 found that it actually deserves a fix. Don't you want to agree?

The documentation should be updated accordingly and while we're at it could also fix the currently broken markup.

### PR DESCRIPTION
**Pull request by tschw**
Complements #7063 to close #7062.

### CODE REVIEW

**Comment by mrdoob** [comment]
Many thanks!

**Comment by mrdoob** [comment]
Wait. I think we lost a lot of changes here. Did you use the last version of the file before making the changes?

**Comment by tschw** [comment]
I used a little trick to remove a lot of redundant information that is documented for `Texture` in a much more readable way (in fact, I always thought the markup was broken, but it turned there was no markup):

> Further parameters correspond to the properties inherited from Texture [... explaining different defaults].

**Comment by mrdoob** [comment]
Ah! I see I see 😅

**Pull request merged**
