### PR TITLE
OrthographicSSRPass (screen space reflection)

### PR DESCRIPTION
**Pull request by gonnavis**
[Demo](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_postprocessing_orthographicSSR.html)   [Demo2](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_postprocessing_orthographicSSR_2.html)
Inspired by [Blender EEVEE SSR](https://docs.blender.org/manual/en/latest/render/eevee/render_settings/screen_space_reflections.html), and [this tut](https://lettier.github.io/3d-game-shaders-for-beginners/screen-space-reflection.html) ( mostly by the two screen grid images [imgA](https://i.imgur.com/MpBR225.png) [imgB](https://i.imgur.com/Um4dzgL.png), I only read a little text and hardly read the code, then start writing my own code. )
Now just support OrthographicCamera. I'm trying to support PerspectiveCamera.

----------------EDIT 2----------------
**Now support PerspectiveCamera. New PR: https://github.com/mrdoob/three.js/pull/20156**

----------------EDIT----------------
Demo ScreenShot
clipboard

### CODE REVIEW

**Comment by mrdoob** [comment]
Thaks for working on this!

Is this how's supposed to look like?

Screen Shot 2020-08-13 at 4 22 03 PM

Also, it runs at ~5fps on my machine (MacBook Pro, Intel).

**Comment by gonnavis** [comment]
Hello Mr.doob

Yes, it is. I've already added the screenshot to the pr.
I know it's not look very well now, may need more advaced blur and anti-alias, and SSR has own limitations.
But I'm already satisfied with this reflection feeling.
My main goal now is to support PerspectiveCamera, after this, I will do in-depth study with the looking improvement.

I can run at 30fps at my win7 laptop with GTX 980M about 40% usage and 1920*1080 chrome maxized window.
The performance cost by the shader is mainly based on pixels count. May Mac retina monitor has too many pixels? 
I'll consider these factors.

**Comment by mrdoob** [comment]
Okay, let us know when the PR is ready for a second review.

Here's some reading material on the subject:
https://twitter.com/edankwan/status/1293934302191931395

**Comment by gonnavis** [comment]
OK, Thanks, I'll learning!

**Comment by gonnavis** [comment]
I found out that antialas was turned on and dpr was set before.
If turn them off, can reach about 12fps on Mac when the window is maximized.
If stepStride is set to 2, it can run to about 28fps.
[Demo.](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_postprocessing_orthographicSSR.html)
[Mac configuration](https://aws1.discourse-cdn.com/standard17/uploads/threejs/optimized/2X/e/e9c1d56a7fe00ffc6a4aa6ab84ae4faa2f979734_2_690x390.jpeg)

**Comment by Mugen87** [comment]
On my iMac I get only about 10 FPS which is definitely to low. Apart from the performance aspect, the visual appearance of the pass still looks buggy.

**Comment by gonnavis** [comment]
Yes, I just want to mention that the performance of this pass is not that bad on mac. I'll keep improving.

**Comment by gonnavis** [comment]
@mrdoob Hello Mr.doob

After use depthTexture instead of depthRenderTarget, the quality has been greatly improved.

I think it might be worth a second review now.

[Demo](http://gonnavis.com/lib/three.js_github_gonnavis/examples/webgl_postprocessing_orthographicSSR.html)

clipboard

**Comment by mrdoob** [comment]
Nice! It is looking much better indeed!

**Comment by mrdoob** [comment]
Would it be hard to make this work with `PerspectiveCamera` too?

**Comment by gonnavis** [comment]
Thanks!

Yes, I find it difficult to judge the ray position of the current pixel with PerspectiveCamera.
Because of the perspective effect, cannot simply use these code
```
vec3 ray=(length(xy-d0)/totalLen)*(reflectDir*maxDistance);
```
I'm still trying in this branch
https://github.com/gonnavis/three.js/blob/SSRPassPerspective/examples/webgl_postprocessing_ssr.html
https://github.com/gonnavis/three.js/blob/SSRPassPerspective/examples/jsm/postprocessing/SSRPass.js
https://github.com/gonnavis/three.js/blob/SSRPassPerspective/examples/jsm/shaders/SSRShader.js

**Comment by mrdoob** [comment]
This one can be closed then?

**Comment by gonnavis** [comment]
Yes, I'll merge these codes to SSRPass.

**Pull request closed without merging**
