### PR TITLE
add function Mesh.objectSpaceRayIntersectsFace

### PR DESCRIPTION
**Pull request by BenediktS**
add function Mesh.objectSpaceRayIntersectsFace( faceIndex, objectSpaceRay, near, far, intersects)

### CODE REVIEW

**Comment by BenediktS** [comment]
I wasn't sure with the naming  "objectSpaceRayIntersectsFace", "objectRayIntersectsFace",  "rayIntersectsFace". 
But i wanted that everyone knows that the function needs a ray that is already in object space.

**Comment by mrdoob** [comment]
Hmm... This duplicates `raycast`?

**Comment by BenediktS** [comment]
I wanted to kill the duplication with the next pull request. 
I didn't want to put it in one pull request so it would be easier to see the two steps. 

But i could put the second commit in the same pull request, if you wonna see it in one pull request.

**Comment by mrdoob** [comment]
> But i could put the second commit in the same pull request, if you wonna see it in one pull request.

Yes please! 😊

**Comment by BenediktS** [comment]
done

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7152

**Comment by BenediktS** [comment]
threejsworker is a very cool tool. I found a major typo with that. (Don't know how it get through the testing)

@mrdoob: really? first you wanted me to rewrite the "split raycaster" code. Then u asked me to pull in  the the second PR (witch i did 5 minutes later). And then you discard the hole PR without any comment?

Without the hope getting them in the mainline, i will put the splitted raycaster function in the BVH.js. So they will override the code and will get out off date soon.  But i don't see how you will ever optimize the raycaster with WebWorkers, BVH, Octree, etc. without the split.    But i will see... :) 

I wish you happy coding.

**Comment by mrdoob** [comment]
Sorry about that. I was probably under stress 😐

Someone refractored the radicated code and it collided with this. I think the current code is split the same way, only the methods aren't public.

**Pull request closed without merging**
