### PR TITLE
CSS2DRenderer: Round values used for translation.

### LINKED ISSUE #21415: CSS2DObject - potential rendering issue in Safari MacOS
**Describe the bug**

Our team has used Three.JS to create a Virtual Tour content type that allows content authors to create interactions which enables the user to navigate around a scene, click on interactions and change to different scenes.

We've recently updated our this content type to work with labels which are 2d objects. However after testing in Safari we started to notice that lines would be drawn all over the scene from our labels. These lines go away when you hover over a label again however they keep on coming back and look quite distracting for a user.

**Potential fix**

I found that by using whole numbers, rather than decimal numbers, for the pixel position of the buttons (which the labels that cause the issue are a child of). This would be done by adding `Math.round` [twice on this line](https://github.com/mrdoob/three.js/blob/a543c8170cdaa32b635be97bec59fe2db76cdc78/examples/js/renderers/CSS2DRenderer.js#L96). I've made the change on [our fork ](https://github.com/h5p/h5p-three-js/blob/release/three.min.js#L1398)of the Three.JS library and it has has issue has been gone since.

I was wondering if anyone had noticed any issue like this and if this fix is valid? Or if it's instead caused by another change we made somewhere. 

***Code***

https://github.com/h5p/h5p-three-image/tree/release
https://github.com/h5p/h5p-three-js
https://github.com/h5p/h5p-three-sixty/tree/release

***Demo***

https://staging.h5p.org/node/622030

**Screenshot and video**

https://www.screencast.com/t/1J7ZjSWc

Screenshot 2021-03-05 at 14 06 20

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Safari]
 - Three.js version: [Not sure, but was updated Feb 2019]

### PR DESCRIPTION
**Pull request by simondate**
Related issue: Fixed #21415

**Description**

Uses Math.round to set only whole numbers for values being used by CSS2DRenderer

### CODE REVIEW

**Comment by Mugen87** [comment]
Do you mind running `node utils/modularize.js` from the project's root directory to generate the ES6 module of `CSS3DRenderer`.

**Comment by simondate** [comment]
It returned this

```
AnimationClipCreator
CCDIKSolver
MMDAnimationHelper
MMDPhysics
CinematicCamera
DragControls
DeviceOrientationControls
FirstPersonControls
FlyControls
OrbitControls
MapControls
PointerLockControls
TrackballControls
TransformControls
TransformControlsGizmo
TransformControlsPlane
Curves
NURBSCurve
NURBSSurface
NURBSUtils
AnaglyphEffect
AsciiEffect
OutlineEffect
ParallaxBarrierEffect
PeppersGhostEffect
StereoEffect
ColladaExporter
DRACOExporter
GLTFExporter
MMDExporter
OBJExporter
PLYExporter
STLExporter
BoxLineGeometry
ConvexGeometry
DecalGeometry
DecalVertex
LightningStrike
ParametricGeometries
TeapotGeometry
SelectionBox
SelectionHelper
LightProbeGenerator
RectAreaLightUniformsLib
Line2
LineGeometry
LineMaterial
LineSegments2
LineSegmentsGeometry
Wireframe
WireframeGeometry2
ThreeMFLoader
AMFLoader
AssimpLoader
BasisTextureLoader
BVHLoader
ColladaLoader
DDSLoader
DRACOLoader
EXRLoader
FBXLoader
GCodeLoader
GLTFLoader
HDRCubeTextureLoader
KMZLoader
LDrawLoader
KTXLoader
MD2Loader
MMDLoader
MTLLoader
NRRDLoader
OBJLoader
PCDLoader
PDBLoader
PLYLoader
PRWMLoader
PVRLoader
RGBELoader
STLLoader
SVGLoader
TDSLoader
TGALoader
TTFLoader
VRMLLoader
VRMLoader
VTKLoader
XLoader
ColorConverter
ConvexHull
ImprovedNoise
Lut
ColorMapKeywords
SimplexNoise
ConvexObjectBreaker
GPUComputationRenderer
Gyroscope
MD2Character
MD2CharacterComplex
MorphAnimMesh
MorphBlendMesh
RollerCoasterGeometry
RollerCoasterLiftersGeometry
RollerCoasterShadowGeometry
SkyGeometry
TreesGeometry
Volume
VolumeSlice
EdgeSplitModifier
SimplifyModifier
TessellateModifier
Lensflare
LensflareElement
LightningStorm
MarchingCubes
edgeTable
triTable
Reflector
Refractor
ReflectorRTT
ShadowMesh
Sky
Water
Water
AdaptiveToneMappingPass
AfterimagePass
BloomPass
BokehPass
ClearPass
CubeTexturePass
DotScreenPass
EffectComposer
Pass
FilmPass
GlitchPass
HalftonePass
MaskPass
ClearMaskPass
OutlinePass
RenderPass
SAOPass
SavePass
ShaderPass
SMAAPass
SSAARenderPass
SSAOPass
TAARenderPass
TexturePass
UnrealBloomPass
CSS2DObject
CSS2DRenderer
CSS3DObject
CSS3DSprite
CSS3DRenderer
RenderableObject
RenderableFace
RenderableVertex
RenderableLine
RenderableSprite
Projector
SVGObject
SVGRenderer
ACESFilmicToneMappingShader
AfterimageShader
BasicShader
BleachBypassShader
BlendShader
BokehShader
BokehShader
BokehDepthShader
BrightnessContrastShader
ColorCorrectionShader
ColorifyShader
ConvolutionShader
CopyShader
DepthLimitedBlurShader
BlurShaderUtils
DigitalGlitch
DOFMipMapShader
DotScreenShader
FilmShader
FocusShader
FreiChenShader
FresnelShader
FXAAShader
GammaCorrectionShader
GodRaysDepthMaskShader
GodRaysGenerateShader
GodRaysCombineShader
GodRaysFakeSunShader
HalftoneShader
HorizontalBlurShader
HorizontalTiltShiftShader
HueSaturationShader
KaleidoShader
LuminosityHighPassShader
LuminosityShader
MirrorShader
NormalMapShader
ParallaxShader
PixelShader
RGBShiftShader
SAOShader
SepiaShader
SMAAEdgesShader
SMAAWeightsShader
SMAABlendShader
SobelOperatorShader
SSAOShader
SSAODepthShader
SSAOBlurShader
TechnicolorShader
ToneMapShader
ToonShader1
ToonShader2
ToonShaderHatching
ToonShaderDotted
SubsurfaceScatteringShader
TriangleBlurShader
UnpackDepthRGBAShader
VerticalBlurShader
VerticalTiltShiftShader
VignetteShader
VolumeRenderShader1
WaterRefractionShader
BufferGeometryUtils
GeometryUtils
SceneUtils
ShadowMapViewer
SkeletonUtils
UVsDebug
WEBGL
```

**Review by Mugen87 — APPROVED** [review]
Even if this PR fixes your problem, it would be good if you could report it to WebKit: https://bugs.webkit.org/

If WebKit would fix the issue, this change would not be required and could be reverted.

**Comment by mrdoob** [comment]
@elalish I think you're one of the few users of `CSS2DRenderer`. Do you know if this change will be noticeable?

**Comment by mrdoob** [comment]
Considering this only affects Safari I think it'd be better to do this:

```js
if ( /apple/i.test( navigator.vendor ) ) {

	// https://github.com/mrdoob/three.js/issues/21415
	element.style.transform = 'translate(-50%,-50%) translate(' + Math.round( vector.x * _widthHalf + _widthHalf ) + 'px,' + Math.round( - vector.y * _heightHalf + _heightHalf ) + 'px)';

} else {

	element.style.transform = 'translate(-50%,-50%) translate(' + ( vector.x * _widthHalf + _widthHalf ) + 'px,' + ( - vector.y * _heightHalf + _heightHalf ) + 'px)';

}
```

**Comment by Mugen87** [comment]
@simondate Do you mind updating the PR with @mrdoob's suggestion?

**Comment by Mugen87** [comment]
Now it depends whether we want to risk this change or not, see https://github.com/mrdoob/three.js/issues/21415#issuecomment-794568950.

**Comment by mrdoob** [comment]
I don't see much risk... Labels movement won't be as smooth in Safari but that's it I think.

**Pull request merged**
