### PR TITLE
Buffer attribute size is fixed at creation.  Remove unneeded recalculations

### PR DESCRIPTION
**Pull request by aardgoose**
Also removes need for "hack" in buffer discard PR

### CODE REVIEW

**Comment by mrdoob** [comment]
Interesting. I guess we can simplify it even further by just calling it `this.count` and remove the getter?

**Comment by aardgoose** [comment]
I don't see why not.  I'll do that,  I wondered if the read only nature of the getter had value, but looking at the git history, ,This evolved from being effectively an alias for array.length to array.length / itemSize, at which point the redundancy of the calculation wasn't noticed.

**Comment by aardgoose** [comment]
Done,

**Comment by mattdesl** [comment]
I think this is a premature optimization that will cause more problems in the long-run (i.e. with non-fixed buffers).

**Comment by aardgoose** [comment]
The trade off is between this calculation for every attribute for every frame, against taking care when changing a buffer's length which 1. can't be done at the moment* 2. probably won't happen with any significant frequency. *which seems like a desirable change to make though.

I commented on your discussion of gl.BufferData etc.  If a change in buffer length is detected in the BufferAttribute copy(x) functions with a resize operation carried out by a simple resize( n ) method, which could be applied simply, the count property could be accurately maintained in the resize operation, so I think all the paths that change a buffer length could easily and reliably handled. 

so all the methods become:

.copy{type)( vectors ) {

if ( this.array.length !== vectors.length * this.itemSize ) this.resize ( vectors.length );
...
}

with:

.resize ( length ) {

this.count = length;

var newArray = new this.array.constructor(  length * this.itemSize );
this.array = newArray;

}

**Comment by mattdesl** [comment]
Do you have any real benchmarks or are you just assuming this is a good optimization? I think uploading a buffer is probably much more of a bottleneck than a simple math getter if you are calling this many times per frame.

**Comment by aardgoose** [comment]
Actually optimization was a side effect, it removed the need for an ugly hack required in my PR to allow BufferAttribues to discard their data after it is sent to the GPU.
( This has allowed me to reduce JS memory requirements in my use case (150MB in one test case).

**Comment by mrdoob** [comment]
> Do you have any real benchmarks or are you just assuming this is a good optimization? I think uploading a buffer is probably much more of a bottleneck than a simple math getter if you are calling this many times per frame.

Yeah, this is not an optimisation, is some cleanup that would allow disposing the typedarrays once uploaded to the GPU.

I guess you're updating the typedarray of the BufferAttribute? Maybe we can add a `.setArray()` for your use case? Maybe that will also allow us to do the `gl.bufferData()` call?

**Comment by aardgoose** [comment]
incidently should the InterleavedBuffer .length property deprecated, or is it still used?

**Comment by mrdoob** [comment]
> incidently should the InterleavedBuffer .length property deprecated, or is it still used?

I think it can go. I'll remove it.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
FYI I've added a array check because `clone()` (which calls to itself with undefined parameters) broke.

https://github.com/mrdoob/three.js/commit/fd4c58dcbe4f06e8ec4c5771f4742220d83103e3

**Pull request merged**
