### PR TITLE
GroundedSkybox: Fix UVs being flipped

### PR DESCRIPTION
**Pull request by hybridherbst**
Related issue: #27422, cc @elalish 

**Description**

The current implementation had flipped UVs compared to using the same texture as environment.background and environment.image, which also resulted in flipped lighting.

I brought the GUI back and added a toggle to switch back and forth now :)
ezgif com-video-to-gif-converter

*This contribution is funded by [Needle](https://needle.tools)*

### CODE REVIEW

**Comment by hybridherbst** [comment]
Hm, may actually need to use the same logic as scene.background to decide if to flip:
`boxMesh.material.uniforms.flipEnvMap.value = ( background.isCubeTexture && background.isRenderTargetTexture === false ) ? - 1 : 1;`

**Comment by Mugen87** [comment]
The flip indeed depends on the texture type since texture of cube render targets have px/nx flipped.

**Comment by hybridherbst** [comment]
I see – then I think flipping here as currently in the PR is always correct for the supported case (an equirectangular texture is passed in), don't think passing in a cubemap would be expected to work for now.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/needle-tools/three.js/fix/grounded-skybox-uv-flip/examples/webgl_materials_envmaps_groundprojected.html

**Comment by elalish** [comment]
Ah, good catch! I totally missed that reversal in my model-viewer examples. I don't rely on cube map inputs, so this is fine, but it seems like adding that flip is still a good idea. Might as well make cube maps work too if it's easy.

**Pull request merged**
