### PR TITLE
Optimize GPUParticleSystem.geometryUpdate

### PR DESCRIPTION
**Pull request by 06wj**
```positionStartAttribute.updateRange.count = positionStartAttribute.count;``` 
The range count should be ```positionStartAttribute.count * positionStartAttribute.itemSize ```

And set count to -1 will call ```gl.bufferSubData( bufferType, 0, array );``` directly.
if set count to array length , it will call array.subarray.

### CODE REVIEW

**Comment by 06wj** [comment]
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLAttributes.js#L92

Should updateRange.count be reset to -1?

**Comment by Mugen87** [comment]
I'd like to debug this one, just to be sure. It will maybe need so time, because i'd like to finish some other work first. I'll put this on my todo list 😊

**Comment by Mugen87** [comment]
> The range count should be positionStartAttribute.count * positionStartAttribute.itemSize

That's correct! And because the code in the `else` branch updates the entire buffer, we can use `-1`. Can you please add a comment in `GPUParticleSystem` that explains why this value is used? You can also link to this PR. Then it's easier for users to understand what's happening.

**Comment by Mugen87** [comment]
> Should updateRange.count be reset to -1?

I think we could change this, too. `-1` is the actual default value in the `BufferAttribute` constructor.

**Comment by 06wj** [comment]
@Mugen87 ok, added.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
