### PR TITLE
Triangle: Add `getAreaSquared()`.

### PR DESCRIPTION
**Pull request by nzjony**
**Description**

Adding a method to compute the squared area of a Triangle. I'm implementing the algorithm: "Adaptive Sampling of Parametric Curves" from Graphics Gems V and one way to do it is to compute the area of a triangle and compare to some threshold. Of course, the squared area can be compared as well. Hence this PR.

Note, because the area of a triangle is the length of the cross product divided by two, the squared area is therefore the lengthSq divided by 4.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
Thanks for the PR, but AFAIK,  unlike length-squared, this method is not provided in other engines.

We do not add methods to the library to accommodate a single user's app. Typically, @Mugen87  defers to see if there is more demand, and I agree with that policy.

If `Triangle.getArea()` leads to a measurable performance problem in your app due to the square-root, then you can add your method to your app.

**Comment by Mugen87** [comment]
Since this method is so compact is thought it's okay to add it. The mentioned use case of from Graphics Gems seems also makes sense.

**Comment by WestLangley** [comment]
@Mugen87 That is very use-case specific. It is best to continue to have a consistent policy in how we handle the addition of new methods. I thought you had the correct, even-handed approach in that regard.

**Comment by Mugen87** [comment]
I thought we have stated that it's okay to add new math routines given that they are compact. 

Granted, I didn't assume `getAreaSquared()` is so use-case. If you are convinced that is the case, I'm okay with leaving this method out for now.

**Comment by Mugen87** [comment]
@nzjony Still, thanks for the contribution. We can reconsider the PR if more devs request for this method.

**Comment by WestLangley** [comment]
@nzjony Yes, thank you for your contribution. Sometimes these decisions are judgement calls, but we are doing our best to adhere to a consistent policy.

**Comment by nzjony** [comment]
@WestLangley @Mugen87 , no worries! Thanks anyway for the consideration and the great work you guys do!

**Pull request closed without merging**
