### PR TITLE
Add support for glTF binary extension (.glb)

### LINKED ISSUE #9255: Support for the gltf .glb file loading via the new GLTFLoader
##### Description of the problem

We are converting our collada models to gltf .glb files but there does not seem to be a support for them in the current r78 version.
Currently the GLTFLoader only supports embedded uris. Can this feature be added?
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #9255.

[Binary extension specification](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF).

Changes:

- Add GLTFBinaryExtension helper, to support `.glb` parsing.
- Add GLTFMaterialsCommonExtension, moving KHR_materials_common-related code there.
- Add `.glb` versions of Monster, Duck, Cesium Man, and Cesium Milk Truck models.

I'd appreciate feedback on structuring extension-related code. Should it be more (or less?) detached from the GLTFParser? I was considering rewriting the _withDependencies method to allow extensions to provide/inject dependencies, which would enable users to provide custom extensions. But I don't know of actual use cases yet, and it would be more complicated.

### CODE REVIEW

**Comment by Jeremy-Gaillard** [comment]
Hi,

Thank you for your work on this issue.

There's a couple of extensions that have already been specified [here](https://github.com/KhronosGroup/glTF/tree/master/extensions/Vendor) if you didn't already see.

I have a few comments on the current implementation:
- In some cases, the url may not have the `.glb` extension. Is there an alternative way we could tell the loader that the url points to a binary file?
- The parse method can't be used since it requires the extensions to be passed as an argument and the extensions are not accessible from outside the class. I recommend moving the extension handling and JSON parsing (line 37 to 50) from `.load` to `.parse` and removing the `extensions` argument.

**Comment by donmccurdy** [comment]
Thanks @Jeremy-Gaillard, I've updated the PR with both suggested changes.

One side effect: because we can't tell in advance if the file is binary without the `.glb` extension, we need to always make the request with `responseType= "arraybuffer"`. I don't know why that is, but the plaintext responses come back with fewer bytes than arraybuffer responses, breaking the binary parser. Perhaps whitespace is being stripped somehow.

**Comment by donmccurdy** [comment]
Rebased.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
