### PR TITLE
DataTextureLoader: Refactor parsing.

### PR DESCRIPTION
**Pull request by Mugen87**
Same as #17403

### CODE REVIEW

**Comment by Mugen87** [comment]
Updated builds: f3205d7cc2b1478c8e80fd06490d552b2d44eb6f

**Comment by Mugen87** [comment]
Finally, all loaders except of `OBJLoader2` are now directly or indirectly derived from `Loader`. The general loader architecture is now more clear and consistent 🎉 

@kaisalmen I've tried to change `OBJLoader2` according to the rest of the codebase. However, `OBJLoader2` is derived from `OBJLoader2Parser`. Maybe you can find a way to derive `OBJLoader2` from `Loader` instead and use an instance of the parser class as a member variable. I'm aware that `OBJLoader2` has a very special design but it still would be preferable to adhere some `three.js` standards.

**Comment by mrdoob** [comment]
> Finally, all loaders except of `OBJLoader2` are now directly or indirectly derived from `Loader`. The general loader architecture is now more clear and consistent 🎉 

Sweet! Many thanks!

**Comment by kaisalmen** [comment]
@Mugen87 I just recently introduced the derivation of `OBJLoader2Parser`, so a way back should be easy. It used to be like that in the V3-beta. I think the introduction of `Loader` is a good idea and `OBJLoader2` will be aligned before 109 is due.

**Comment by Mugen87** [comment]
@kaisalmen Sounds great!

**Comment by kaisalmen** [comment]
Ported already. Needs some polishing + other issues should to be resolved along:
https://raw.githack.com/kaisalmen/three.js/OBJLoader2_V301/examples/webgl_loader_obj2.html
https://raw.githack.com/kaisalmen/three.js/OBJLoader2_V301/examples/webgl_loader_obj2_options.html

**Pull request merged**
