### PR TITLE
Clean up RawShader example

### PR DESCRIPTION
**Pull request by WestLangley**
Use `THREE.BufferAttribute` instead of `THREE.Float32Attribute`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Yeah... I'm not super happy about the `.setXYZ()` stuff either...

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Grepping for `THREE.Float32Attribute` finds several other cases. Do you intend to deprecate it?

**Comment by mrdoob** [comment]
Oh! I do like `Float32Attribute`. `.set***()` not so much...

**Comment by computersarecool** [comment]
Thanks for looking at this stuff guys! I am just going over the examples now and the mix of `THREE.BufferAttribute` and `BufferAttribrute` in the examples was a bit confusing.

**Pull request merged**
