### PR TITLE
removed legacy utils/builds readme

### PR DESCRIPTION
**Pull request by sciecode**
removing legacy `npm run build-uglify` from utils/build readme.

perhaps would be best to simply remove `readme.md` or refer to Wiki's [Build Instructions](https://github.com/mrdoob/three.js/wiki/Build-instructions).

### CODE REVIEW

**Comment by Mugen87** [comment]
> perhaps would be best to simply remove readme.md or refer to Wiki's Build Instructions.

I vote to remove the file.

**Comment by mrdoob** [comment]
Me too!

**Comment by sciecode** [comment]
good to go.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
