### PR TITLE
TS: Improve EventDispatcher declaration

### PR DESCRIPTION
**Pull request by woo-cie**
Hi.
I propose these changes to resolve some problems in EventDispatcher declaration file.

1. Collect type of event.target
Now, event.target is defined as any or undefined in listener args.
But, in js implementation, event.target must be EventDispatcher itself.
So, it has to be defined as this.

2. Enable to restrict method's args by type
Current declaration allows code below.
``` ts
class MyEventDispatcher extends EventDispatcher {
  someFunction(){
    this.dispatch({event: "onSomeEvent", attachment: 10});
  }
}

// somewhere
myEventDispatcher.addEventListener("onSomeEvent", e => console.log(e.attachmant))
// expected 10 but actually undefined because of typo
```
So I enable to restrict args like this.
``` ts
type Event = {type: "onSomeEvent", attachment: number} | {type: "onSomeEvent2", attachment2: string};
class MyEventDispatcher extends EventDispatcher<Event> {
  someFunction(){
    this.dispatch({event: "onSomeEvent", attachment: 10});
  }
}

// somewhere
myEventDispatcher.addEventListener("onSomeEvent", e => console.log(e.attachment))
// Auto-completion also works well.

// myEventDispatcher.addEventListener("onSomeEvent2", e => console.log(e.attachment))
// Error: Property 'attachment' does not exist on ...
```

### CODE REVIEW

**Comment by woo-cie** [comment]
Sorry, I found mistake in PR description.
Wrong > class MyEventDispatcher extends EventDispatcher
Right > class MyEventDispatcher extends EventDispatcher<Event>

It has been corrected in description.

**Comment by mrdoob** [comment]
@dmnsgn does this look good?

**Comment by dmnsgn** [comment]
Looks good on using a custom type `Listener` instead of a generic `Event` interface that comes from TS DOM lib.

Should the EventDispatcher still extends `Event` with `EventDispatcher<E extends Event = Event>` if EventDispatcher is not used for DOM event but for Three.js own events though? Need a TS expert to jump in this conversation.

**Comment by woo-cie** [comment]
Did you mean to say that EventDispatcher should extends ```{type: string}``` instead of ```Event``` as
```EventDispatcher<E extends {type: string} = Event>```?
If so, I agree with you.

**Comment by Mugen87** [comment]
TS type declaration files have been removed. The code will be located on `DefinitelyTyped` in the future, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50930

**Pull request closed without merging**
