### PR TITLE
Remove unnecessary "#include <specularmap_fragment>" from meshphysical_frag.glsl

### PR DESCRIPTION
**Pull request by takahirox**
This PR removes unnecessary `#include <specularmap_fragment>` from `meshphysical_frag.glsl` which is shader for `MeshStandardMaterial` and `MeshPhysicalMaterial`.

If I'm right, `meshphysical_frag.glsl` doesn't need to include `specularmap_fragment`.

`specularmap_fragment.glsl` is a shader chunk for `specularStrength`.
`specularStrength` is used only in `envmap_fragment.glsl` and `lights_phong_[pars_]fragment.glsl` but
`meshphysical_frag.glsl` doesn't include them.

### CODE REVIEW

**Comment by mrdoob** [comment]
@WestLangley looks good?

**Comment by WestLangley** [comment]
Yes, that can be removed.

`<specularmap_pars_fragment>` can also be removed, I expect.

Please confirm. Thanks.

**Comment by takahirox** [comment]
Yup, seems like we also can remove it.
Confirmed and updated.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
