### PR TITLE
Added #include_once shader directive and circular inclusion detection

### PR DESCRIPTION
**Pull request by patrickguenther**
I've spent the last day or so trying to figure out how to create my own shader by reusing as much as possible from three.js's included ShaderChunk library. What I found particularly annoying about it, was figuring out how these chunks depend on each other, since they never include their own dependencies, like the common chunk.

With these changes, each chunk should be able to declare `#include_once <...>` to declare their dependencies without having to worry about including chunks more than once. And while I was at it I also added circular inclusion detection for regular includes.

I didn't know how to write unit tests for `parseIncludes()` without exporting it or writing actual shaders that do compile. Examples seem to still work as expected.

I didn't actually rewrite glsl files for now, but I hope this can be used to write more comprehensive shader libraries in the future.

### CODE REVIEW

**Comment by patrickguenther** [comment]
I don't know about that LensFlare.tests.js conflict. I had to change the case of a letter somewhere or the tests wouldn't have run on my machine.

**Comment by Mugen87** [comment]
@patrickfuller You can revert these changes. It's already fixed in `dev`.

**Comment by WestLangley** [comment]
Related: #9035.

**Comment by bhouston** [comment]
@WestLangley this is not a bad idea.  It is actually simplier, although not as smart, than our previous defineonce ideas.

**Comment by WestLangley** [comment]
@bhouston If I am not mistaken, this PR does not prevent the redeclaration of variables, as described in https://github.com/mrdoob/three.js/issues/9035#issue-157419114, it only prevents the re-inclusion of chunks -- well, as the chunks are currently written.

**Comment by Mugen87** [comment]
In the meanwhile it's fair to state that instead of enhancing the shader chunk system in `WebGLRenderer` (like adding new validation checks), it's better to focus on `NodeMaterial`, `TSL` and `WebGPURenderer`.

**Pull request closed without merging**
