### PR TITLE
InterleavedBufferAttribute: Added toJSON() and clone().

### LINKED ISSUE #15395: InterleavedBufferAttribute has no clone method
##### Description of the problem

Hi! I get this error because `InterleavedBufferAttribute` has no `.clone()` method. This happens when I'm trying to clone geometry that uses `InterleavedBufferAttribute`.
image

##### Three.js version

- [x] Dev
- [ ] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### LINKED ISSUE #19407: Editor：Uncaught TypeError: normal.clone is not a function
##### Description of the problem

 I import a gltf file into three.js Editor, and when I export it ,I got this error

```
Uncaught TypeError: normal.clone is not a function
at createNormalizedNormalAttribute (GLTFExporter.js:297)
at processMesh (GLTFExporter.js:1240)
at processNode (GLTFExporter.js:1812)
at processNode (GLTFExporter.js:1860)
at processNode (GLTFExporter.js:1860)
at processScene (GLTFExporter.js:1921)
at processInput (GLTFExporter.js:1974)
at GLTFExporter.parse (GLTFExporter.js:2004)
at UIRow. (Menubar.File.js:272)
createNormalizedNormalAttribute @ GLTFExporter.js:297
processMesh @ GLTFExporter.js:1240
processNode @ GLTFExporter.js:1812
processNode @ GLTFExporter.js:1860
processNode @ GLTFExporter.js:1860
processScene @ GLTFExporter.js:1921
processInput @ GLTFExporter.js:1974
parse @ GLTFExporter.js:2004
(anonymous) @ Menubar.File.js:272 

```

And here is the file
[https://github.com/zypy333/test1/blob/HEAD/2cen.gltf](https://github.com/zypy333/test1/blob/HEAD/2cen.gltf)

##### Three.js version

- [x] Dev
- [x] r116

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] Windows

##### Hardware Requirements (graphics card, VR Device, ...)
no

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #19407.
Closes #17328. 
Closes #15395.

I've stumbled across this issue multiple times and I think it's better to serialize interleaved buffer attributes as normal buffer attributes for now instead of producing a runtime error. 

Stuff like the persistent history function in the editor does not break anymore when interleaved data are imported.

`InterleavedBufferAttribute.name` is only introduced so `BufferGeometry.toJSON()` can perform a check on this property.

### CODE REVIEW

**Comment by Mugen87** [comment]
Maybe it's better to find a solution that maintains interleaved data.

**Comment by Mugen87** [comment]
`InterleavedBufferAttribute` now supports `toJSON()` and `clone()` by deinterleaving data. The PR also changed `GLTFExporter` so it is able to process interleaved buffer attributes (up to a certain item size).

**Comment by Mugen87** [comment]
If the PR is merged, I'm going to create a new issue that tracks the enhancement of `BufferGeometry.clone()` that retains interleaved buffer attributes.

**Comment by arpu** [comment]
what is the different to this implementation https://github.com/mrdoob/three.js/pull/19233 ?

**Comment by Mugen87** [comment]
It seems the PR implements this on `BufferGeometry` level. However, I wanted to focus on #19233 after this PR since cloning and serializing of individual attributes (not the entire geometry) also has to work.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Alchemist0823** [comment]
Thanks

**Comment by xx0618** [comment]
> `InterleavedBufferAttribute`现在支持`toJSON()`并`clone()`通过解交织数据。PR也进行了更改，`GLTFExporter`因此它能够处理交错的缓冲区属性（最大为某个项目大小）。
GLTFExporter reported an error, how can I solve it?
微信截图_20200926163841

**Comment by Mugen87** [comment]
@xx0618 Do you mind describing in more detail how this error occurs?

**Comment by xx0618** [comment]
> @xx0618 Do you mind describing in more detail how this error occurs?

I compressed the 3D model using GLTFPACK. Unzip the file and display the 3D model. Now I want to save the content of the page, and an error occurs. Before using Draco to compress, GLB files can be exported normally. It's not working now. Do not you know why.
jiazai
baocun
cuowu

**Comment by Mugen87** [comment]
Where does `setMeshoptDecoder` come from?

**Comment by xx0618** [comment]
setMeshoptDecoder is used for decompression and is obtained by importing files. It can decompress GLTFPACK compressed files.

**Comment by Mugen87** [comment]
This is not an official method of `GLTFLoader`. So without seeing the implementation, there is no chance to investigate this issue.

**Comment by arpu** [comment]
@xx0618  you use the old way to load the geos with meshopt new version use the GLTFLoader plugin system see https://github.com/zeux/meshoptimizer/blob/master/demo/index.html

**Comment by xx0618** [comment]
How to solve this problem? Draco takes too long to decompress after compression, and GLTFPACK solves this problem. And GLTFPACK cannot be exported.

**Comment by xx0618** [comment]
> @xx0618 you use the old way to load the geos with meshopt new version use the GLTFLoader plugin system see https://github.com/zeux/meshoptimizer/blob/master/demo/index.html

Let me try

**Comment by xx0618** [comment]
> @xx0618 you use the old way to load the geos with meshopt new version use the GLTFLoader plugin system see https://github.com/zeux/meshoptimizer/blob/master/demo/index.html

The first picture is to load the GLTFLoader in jsm/, and the second picture is to load the js/ in, and both report errors.
jsm
js

**Comment by xx0618** [comment]
> @xx0618 you use the old way to load the geos with meshopt new version use the GLTFLoader plugin system see https://github.com/zeux/meshoptimizer/blob/master/demo/index.html

I loaded meshopt_decoder.js and the system prompts that it is not a function.
微信截图_20201005091239

**Comment by Mugen87** [comment]
@xx0618 Please use the [forum](https://discourse.threejs.org/) if you need help.

**Pull request merged**
