### PR TITLE
Allow setting direction of DirectionalLight by angles

### PR DESCRIPTION
**Pull request by EliasHasle**
I appreciate the Three.js philosophy of keeping things clean, simple and modular. Yet, I often find myself in situations where I have to create and manipulate a Spherical to modify the direction of DirectionalLights in a sensible way. Unit3D, by comparison (and I like Three.js much better for sure), has angles as the default way of configuring the direction. So I thought I could add it to DirectionalLight as an option. The implementation conserves the radius.

### CODE REVIEW

**Comment by EliasHasle** [comment]
I have not tested it, though. Don't know how to build from source yet. So I have just tried my best at making it correct. Even if it is not correct, it serves as a starting point for discussion.

**Comment by looeee** [comment]
This looks like it should work, however I would rather add a second directional light type without a target, then we can match the functionality from other apps such as 3DS Max (targeted and untargeted directional lights supported), Unity (untargeted only), Blender (untargeted only as Sun Lamp), Maya (untargeted only) etc. 

The current light is a `TargetDirectionalLight`, we should add a second `RotationalDirectionalLight`.

**Comment by Mugen87** [comment]
Related: #13373

**Comment by EliasHasle** [comment]
Oh, I have been ignoring the target issue. I sincerely thought that DirectionalLight direction was specified only by the position, always pointing toward the origin.

**Comment by WestLangley** [comment]
```javascript
light.position.setFromSpherical( spherical ).add( light.target.position );
```

**Comment by EliasHasle** [comment]
@WestLangley I think so, yes, if target is in same space and the "radius" is computed as distance to target instead of distance to origin.

**Comment by WestLangley** [comment]
I think my suggestion is all that you need and this PR can be closed.

**Comment by Mugen87** [comment]
> I think my suggestion is all that you need and this PR can be closed.

👍

**Pull request closed without merging**
