### PR TITLE
Fix OutlineEffect

### PR DESCRIPTION
**Pull request by takahirox**
Fix `OutlineEffect` broken by #15571

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
How about just doing `var renderTarget = null;` here?

https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/OutlineEffect.js#L407

**Comment by mrdoob** [comment]
And `var forceClear = false;` while you're at it 😇

**Comment by takahirox** [comment]
That should be clearer. Updated, thanks.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
