### PR TITLE
audio.js - set isPlaying to false on stop()

### PR DESCRIPTION
**Pull request by smatthews1999**
The boolean 'isPlaying' gets set to true in 'play()', but never gets set to false in 'stop()'

Added line to set 'isPlaying' to false in 'stop()'.

### CODE REVIEW

**Comment by smatthews1999** [comment]
I hope I did this right :-/  The pull request is definitely harder than the code fix.

**Comment by mrdoob** [comment]
Almost! You just need to target the `dev` branch instead 😊

**Comment by smatthews1999** [comment]
Sorry!  Shall I try to push it up again?

**Comment by mrdoob** [comment]
Yes please

**Comment by mrdoob** [comment]
#9072

**Comment by smatthews1999** [comment]
Thank you ... for your patience!

**Pull request closed without merging**
