### PR TITLE
Grounded Skybox

### LINKED ISSUE #27422: Alternate GroundProjectedSkybox
### Description

I recently tried to use `GroundProjectedSkybox` in `<model-viewer>` and utterly failed. I'm not sure I can list all the problems I found, but here are a few:

1) There is a radius parameter, but the object also seems to need to be scaled (possibly to this same radius, possibly independent?).
2) If the parameters have units, then I'm dubious of the math - the example uses a height of 15 (presumably meters, since it's loading a glTF car) and I personally doubt anyone put their camera that high, unless it was a drone.
3) When I tried to apply it to other scenes, I could find no combination of parameters that gave a sensical result, and no system of parenting that allowed a model to appear fixed on the ground. I'm not actually sure it's possible, because I noticed that even in the example, the ground appears to slip under the wheels as the camera zooms, and it doesn't enable pan at all:

https://github.com/mrdoob/three.js/assets/97088/22266465-0d5c-4474-851d-7f489ff9f440

Note the sand ripple under the front tire.

I could find no clear way to fix it, so I just wrote my own. It's dramatically simpler (no custom shaders), and pretty much the only drawback is that it's slower to dynamically update the parameters, though I see no problem with this in practice since the three.js example is pretty much the only place I would imagine actually doing that on a per-frame basis. 

Mine also has the advantage of making a smooth curve from the flat ground to the sky sphere:
image

It's not much code, but curious if anyone would like to see it upstreamed, and if so, in what form? @mrdoob @WestLangley @bhouston

### Reproduction steps

1. Attempt to pan around a model with a GroundProjectedSkybox.

### Code

See my alternative [here](https://github.com/google/model-viewer/pull/4604/files#diff-988c3121907b851859f7a1cd472cf33174f0b2b88b8cd9ffae1754521df36646)

### Live example

Current: https://threejs.org/examples/?q=ground#webgl_materials_envmaps_groundprojected
Mine: https://modelviewer.dev/examples/lightingandenv/#groundedSkybox and https://modelviewer.dev/examples/augmentedreality/#ar

### Screenshots

_No response_

### Version

r159

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by elalish**
Fixes #27422 

**Description**

As requested; I've simplified it a bit too, as well as removed the GUI from the example since the parameters are not really meant to be tweaked realtime.

### CODE REVIEW

**Comment by Mugen87** [comment]
For comparison:

https://rawcdn.githack.com/elalish/three.js/groundedSkybox/examples/webgl_materials_envmaps_groundprojected.html
https://threejs.org/examples/webgl_materials_envmaps_groundprojected.html

**Comment by Mugen87** [comment]
The E2E screenshot needs an update via `npm run make-screenshot webgl_materials_envmaps_groundprojected".

**Comment by marcofugaro** [comment]
Maybe it makes sense to convert the HDR to .jpg like in #27183 for this particular example?

**Comment by elalish** [comment]
> Maybe it makes sense to convert the HDR to .jpg like in #27183 for this particular example?

Probably, but let's leave that to another PR. Ideally once UltraHDR support comes to core - 🙏 @mrdoob!

**Comment by elalish** [comment]
Hmm, `make-screenshot` gave me a black image. It used to work fine on this macbook, but it also used to open Chrome - it seems to be headless now? I wonder if that's related...

Meantime, can someone else generate the screenshot?

**Comment by mrdoob** [comment]
Seems like it worked on my machine... https://github.com/mrdoob/three.js/commit/fc885c512b61a87575ae5bb4ec39b5caca4ccdcf 🤔

**Comment by hybridherbst** [comment]
@elalish is there a reason for not setting `depthWrite = false` on the material? Can I make a PR?

**Comment by timothyallan** [comment]
> Fixes #27422
> 
> **Description**
> 
> As requested; I've simplified it a bit too, as well as removed the GUI from the example since the parameters are not really meant to be tweaked realtime.

I run a builder type site where people used to be able to tweak the parameters in real time to get their content to display the way they wanted. Is the best way now to just delete/recreate via `new GroundedSkybox()` when updating params?

**Comment by Mugen87** [comment]
Remove the skybox from the scene and then call `dispose()` on its geometry and material to make sure to clean things up. You can then setup a new instance.

**Comment by timothyallan** [comment]
Yep, the types showed there was no .dispose(), but after checking out the code and seeing how the new code is actually structured, that's exactly what I'm doing now. Thanks.

**Comment by mrdoob** [comment]
@timothyallan do you have a link to that site?

**Comment by timothyallan** [comment]
> @timothyallan do you have a link to that site?

It's part of a new suite of 3d tooling being added to an existing SaaS platform. We've been beta testing it all for the past few months, and it's not available to the general public yet. It's good this update happened now actually!

**Pull request merged**
