### PR TITLE
Add method to set camera pose target on WebXRManager

### PR DESCRIPTION
**Pull request by dmarcos**
Analog to the existing method in `WebVRManager` A-Frame applies the headset pose to a parent Object3D different than the camera (the entity's Group where all Object3Ds including the camera hang from)

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by dmarcos** [comment]
Let me know if you there's anything pending. Happy to accommodate any changes.

**Comment by tlaukkan** [comment]
+1

**Comment by dmarcos** [comment]
@Mugen87 Is there anything else you want me to do here?

**Comment by Mugen87** [comment]
No, but I think @mrdoob should review and merge all VR/XR related changes.

**Comment by dmarcos** [comment]
Cool, thanks for the update. We will wait for @mrdoob

**Comment by dmarcos** [comment]
@mrdoob Any changes you want me to do here? Happy to adjust

**Comment by mrdoob** [comment]
The `poseTarget` made the code inside `WebVRManager` confusing and harder to maintain...

What if we pass the computed camera in the `onAnimationFrameCallback()`? Can aframe use that to update the Object3D entity and reset the camera transformation before rendering?

**Comment by dmarcos** [comment]
@mrdoob Sorry I missed this. Thanks for taking a look. I think the solution you propose will work for us. Do you want me to take a stab at it and I can make sure it works?

**Comment by mrdoob** [comment]
Yes please!

**Comment by dmarcos** [comment]
> `onAnimationFrameCallback`

> The `poseTarget` made the code inside `WebVRManager` confusing and harder to maintain...
> 
> What if we pass the computed camera in the `onAnimationFrameCallback()`? Can aframe use that to update the Object3D entity and reset the camera transformation before rendering?

Problem with the approach is that there's no opportunity to read back and reset the camera in `onAnimationFrameCallback` before rendereing. The pose is applied later within the `render` call when [`getCamera` is invoked](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1131). Am I misunderstanding anything?

**Comment by mrdoob** [comment]
Can we see how you tried to implement it?

**Comment by dmarcos** [comment]
> 
> 
> Can we see how you tried to implement it?

Sorry no code yet. Trying to see a way to incorporate your suggestion first. One question, When would do you expect A-Frame to copy and reset the camera before rendering? It would have to happen after the [getCamera](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1131) call (that updates the camera with the headset pose) and before rendering. We could move the camera pose update at an earlier point out of `getCamera` but we want to request the pose as late as possible to get the most recent pose before render.

**Comment by klausw** [comment]
@dmarcos wrote:
> We could move the camera pose update at an earlier point out of `getCamera` but we want to request the pose as late as possible to get the most recent pose before render.

Just a drive-by comment since I got pointed at this discussion - there may be a misunderstanding here? Once you're inside a WebXR session rAF callback, the poses you get won't change for the duration of that frame. So there's no point in trying to defer fetching the viewer pose, you won't get a fresher pose.

Or are you getting poses outside the animation loop (which isn't possible in WebXR) or saving them across frames?

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/18012#issuecomment-558896060

**Pull request closed without merging**
