### PR TITLE
Examples: Added OimoPhysics instancing example

### PR DESCRIPTION
**Pull request by VBT-YTokan**
Added OimoPhysics example using mesh instancing. Actually tried to copy structure of ammo.js example.

https://www.npmjs.com/package/oimophysics

image

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good!

Could you try resolving the package-lock conflict?

Also, could you move `examples/oimophysics/OimoPhysics.js` to `examples/jsm/libs/OimoPhysics.js`?

**Comment by OleksiiMaksymovVBT** [comment]
@mrdoob sure, will resolve it now

**Comment by OleksiiMaksymovVBT** [comment]
@saharan 👀

**Comment by mrdoob** [comment]
Actually... What do you think about making a wrapper similar to [AmmoPhysics.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/physics/AmmoPhysics.js)?
You can see how it works in [this example](https://github.com/mrdoob/three.js/blob/dev/examples/physics_ammo_instancing.html).

**Comment by OleksiiMaksymovVBT** [comment]
@mrdoob we have this wrapper+physics threejs debuggers in g.frame (threejs based TS framework).

**Comment by OleksiiMaksymovVBT** [comment]
Perhaps as you know there is oimo.js, but it doesn't have any kind of normal documentation / debuggers / etc

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/VeryBigThings/three.js/examples/physics_oimo_instancing/examples/physics_oimo_instancing.html

**Comment by mrdoob** [comment]
> @mrdoob we have this wrapper+physics threejs debuggers in g.frame (threejs based TS framework).

Ah, I see. I'll try doing the wrapper myself then...

**Comment by mrdoob** [comment]
Thanks!

**Comment by OleksiiMaksymovVBT** [comment]
@mrdoob no problem, leave it on us. We work a lot with oimo and threejs, so we will add more this and next week :)

**Comment by mrdoob** [comment]
Okay!

What I was going to do was something just like the [AmmoPhysics.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/physics/AmmoPhysics.js) file so developers can swap physics engines by just changing one line.

**Comment by OleksiiMaksymovVBT** [comment]
@mrdoob sounds legit, let's continue this conversation in issue #21686.

**Comment by mrdoob** [comment]
Actually, I was half-way done... https://github.com/mrdoob/three.js/commit/e35862887b9ccdbf08d97e36dffd45f98a538c8b 😅

**Comment by mrdoob** [comment]
Now `physics_ammo_instancing` and `physics_oimo_instancing` are basically identical.

**Comment by OleksiiMaksymovVBT** [comment]
Lol. We are working rn on OimoUtils, some functions to create primitives, joints easier.
Also we will push OimoDebugger (to see primitives and joints in three)

**Comment by Mugen87** [comment]
@OleksiiMaksymovVBT @VBT-YTokan It seems adding `OimoPhysics.js` to the repository introduced a lot of new `lgtm.com` alerts. It would be great if you could fix these issues in your repo and then update the library.

https://lgtm.com/projects/g/mrdoob/three.js/snapshot/7f2c330a801fc90fa4cdf452ccfe699741d6bae4/files/examples/jsm/libs/OimoPhysics.js?sort=name&dir=ASC&mode=heatmap

**Comment by mrdoob** [comment]
Wow...

https://lgtm.com/projects/g/mrdoob/three.js/history/

Screen Shot 2021-04-21 at 9 48 52 AM

**Comment by mrdoob** [comment]
Unfortunately I'm going to have to revert this.
I'm not happy how this affects the perceived code quality of the project.

**Comment by saharan** [comment]
I think Haxe's dead code elimination feature can resolve this. I'll report you when the clean up is done!

**Comment by OleksiiMaksymovVBT** [comment]
@saharan yeap, you can ping me directly

**Comment by saharan** [comment]
@OleksiiMaksymovVBT I've just modified the compiler option and cleaned up the exported js file! Would you also check your examples work well with this? https://github.com/saharan/OimoPhysics/commit/2da651ca30ab8bd1e031caec1e32df938554b0e4

**Comment by OleksiiMaksymovVBT** [comment]
@saharan I will check it tomorrow and also I will check file with lgtm

**Comment by OleksiiMaksymovVBT** [comment]
Waiting for PR review and merge :) 
https://github.com/saharan/OimoPhysics/pull/36

**Pull request merged**
