### PR TITLE
OBJLoader2(Parallel) 3.1.0

### LINKED ISSUE #15227: Use Object.assign in OBJLoader2
https://github.com/mrdoob/three.js/blob/36f9f34752a985359e2556c68a52234436cefdfa/examples/js/loaders/OBJLoader2.js#L513-L521

Should this be replaced with just?

     Object.assign(materials, materialCreator.materials);

According to MDN Object.assign doesn't exist in IE. Is it still a goal of THREE.js to support IE? If so maybe a similar function should be added to three (I'd vote for not supporting IE personally)

### LINKED ISSUE #17364: OBJLoader2.d.ts: Argument of type 'void' is not assignable to parameter of type 'Object3D'
##### Description of the problem

The return type of objloader2.parse in the OBJLoader2.js code is **Group** and in OBJLoader2.d.ts is **void**

##### Three.js version

- [ ] Dev
- [x] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by kaisalmen**
Changes:
- [x] `OBJLoader2` is now based on `Loader` (#17406)
- [x] Updated typescript definitions (fixed #17364) Note: `OBJLoader2Parallel#parse` is implemented differently
- [x] Unified `load` and `parse` behaviour of `OBJLoader2` and `OBJLoader2Parallel`: Separate `onParseComplete` is gone. `onLoad` serves the same purpose in both sync an parallel use cases
- [x] Update docs: Clean and update `OBJloader2` and introduce `OBJLoader2Parallel` 
- [x] Fix logging verbosity (`MaterialHandler`, etc) 
- [x] Fixed #15227 along

I have a question to the maintainers: Should loaders log per default on info level or should users need to enable it (debug is false per default already). Do you have a guideline or advice? Thanks.

### CODE REVIEW

**Comment by Mugen87** [comment]
> Should loaders log per default on info level or should users need to enable it (debug is false per default already). Do you have a guideline or advice?

There is no log level concept in `three.js` but ideally the library only logs warnings and errors by default. Lower levels like info and debug only if requested.

**Comment by kaisalmen** [comment]
> There is no log level concept in three.js but ideally the library only logs warnings and errors by default. Lower levels like info and debug only if requested.

Thanks, ok, then I will change both to be "silent" per default.

**Comment by kaisalmen** [comment]
Ok, all changes are done. I will check again later if js, ts and docs are aligned and will then remove the WIP status.

**Comment by kaisalmen** [comment]
Ok, fixed minor issue in `OBJLoader2` doc and bumped version to 3.1.0. I only updated the English docs, btw.

**Comment by Mugen87** [comment]
>  I only updated the English docs, btw.

Can you please copy both pages to the `zh` directory. The mismatch might be confusing for the Chinese translators.

**Comment by kaisalmen** [comment]
Fixed to other issue now as well and just copied the docs to zh directory.

**Comment by mrdoob** [comment]
Thanks!

**Comment by kaisalmen** [comment]
@mrdoob or @Mugen87 you mentioned the minor IE11 fix in the r109 changelog, but not this one. 😉 

👏 for having the changelog immediately ready, though.

**Comment by Mugen87** [comment]
Done!

**Pull request merged**
