### PR TITLE
Material: Added callback to identify customized programs

### LINKED ISSUE #19377: Using Material.onBeforeCompile on multiple materials causes cache conflicts
##### Description of the problem

Creating multiple materials using `onBeforeCompile` breaks when the source code of `onBeforeCompile` is exactly the same.

It looks like the compiled programs are cached based on the `onBeforeCompile` source code (looking at `material.program.cacheKey`).

Here is an example:

* [jsfiddle](https://jsfiddle.net/5b6zndjh/7/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/401w8dbu/) (dev branch)

The `makeMaterial` function is supposed to create two different materials (based on parameters), but the two objects render in the same color.

As a workaround, redefining `material.defines` works. In the above example, adding the following line to `makeMaterial` fixes the issue and makes the two object render differently:

    material.defines = {'FOO': ''+r};

I realize that it might not be so easy to disambiguate the two materials, but maybe this could be documented as part of `Material.onBeforeCompile`?

##### Three.js version

- [x] Dev
- [x] r116

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Oletus**
In case onBeforeCompile has conditional statements in it, the parameter values affecting the shader code can be returned from customProgramCode so the shader program is correctly fetched from cache or recompiled as needed.

Fixed #19377.

### CODE REVIEW

**Comment by Oletus** [comment]
We've found this API to be very useful for more complex customizations of materials, though we're not quite sure of the naming - maybe "programHash" would be more understandable than "programCode"?

Also suggestions on how to make an example for this would be welcome. Maybe we could change the existing webgl_materials_modified example so that it switches between two different materials using the same onBeforeCompile function but with different parameters?

**Comment by pailhead** [comment]
Related:

https://github.com/mrdoob/three.js/issues/13192

Unfortunately (IMO), it hasn't been accepted as a bug, but rather as design.

**Comment by pailhead** [comment]
@Oletus 

Related PRs for modified webgl material examples:

Chunk replacements. You can provide a chunk replacement to be consumed by the material *when the time comes*. Ie. you're not bound to modify the materials when `render()` encounters them, you just fire and forget. As soon as you say `myMaterial.chunks.myChunk = myChunk` you're done, you don't care _when_ compilation happens.

https://github.com/mrdoob/three.js/pull/14206

`onBeforeCompile` example PR:

https://github.com/mrdoob/three.js/pull/14166

And another `onBeforeCompile` example:

https://github.com/mrdoob/three.js/pull/14174

**Comment by Oletus** [comment]
@Mugen87 @mrdoob Can I get feedback on this change? Do you have some other direction in mind for customizing shader programs?

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
I've struggled a bit with the name of `customProgramCode ()` however I can't think of a better one. (maybe `onCustomProgramCode()` but only if @mrdoob wants to retain the `on*` syntax for such hooks).

**Comment by Oletus** [comment]
I think "customProgramHash" or "customShaderHash" might be more understandable, even if an actual hash algorithm isn't necessarily involved. Or maybe "customProgramCacheKey"?

If we do change it I'd like to go and change the core to also use "programHash" or "programCacheKey" instead of "programCode" for consistency. "programCode" can be a bit confusing since it sounds like it might refer to the shader source code rather than a key used for caching the compiled program.

**Comment by Mugen87** [comment]
> "programCode" can be a bit confusing since it sounds like it might refer to the shader source code rather than a key used for caching the compiled program.

True. Related #16674

**Comment by Oletus** [comment]
Updated the naming since #17748 was merged, and added documentation and an example. @Mugen87 @mrdoob could this be merged?

**Comment by Mugen87** [comment]
I suggest to undo the changes to `webgl_materials_modified` in order to keep it as simple as possible. Your code example in the documentation seems sufficient to me.

**Comment by pailhead** [comment]
Is there any chance that https://github.com/mrdoob/three.js/pull/14231 could be revisited? 

IIRC the biggest pro of `onBeforeCompile` was that it was only 3 lines of code. But if we are fixing #13192 (or adding the feature) `onBeforeCompile` is slowly growing. 

I was never convinced that these kind of operations need to be called asynchronously in the `onBeforeCompile`.

It seems like `onBeforeCompile` will break cloning even further if it introduces more callbacks that aren't cloned?

**Comment by Oletus** [comment]
Force-pushed to remove the commit that contained the example changes. @mrdoob this should be ready to merge! :)

**Review by Mugen87 — APPROVED** [review]

**Comment by Oletus** [comment]
Rebased this patch on top of the latest dev. @mrdoob do you think that this patch is ok? @Mugen87 approved the earlier version quite a while ago but not sure if you noticed it.

**Comment by mrdoob** [comment]
> In case onBeforeCompile has conditional statements in it, the parameter values affecting the shader code can be returned from customProgramCode so the shader program is correctly fetched from cache or recompiled as needed.

Do you mind elaborating a bit? I'm having a hard time to understand what the problem is.
The example being added to the documentation also doesn't seem easy to understand 🤔

**Comment by pailhead** [comment]
@mrdoob 

I believe it's describing this issue:
https://github.com/mrdoob/three.js/issues/13192

There's a jsfiddle there. In short, given N materials with the same `onBeforeCompile` but with conditional logic in there, like a `switch (condition) {}` you won't get N different materials to render, but one, and arbitrary at that.

**Comment by Oletus** [comment]
@mrdoob @pailhead described the issue fairly well. Without this change three.js is only able to cache one material shader per unique onBeforeCompile callback. With this change several material shaders can be cached in case they have the same onBeforeCompile callback but that callback is run with different parameters (from a closure for example) for each material.

Earlier this PR included an example but I was asked to remove that. Should I reintroduce the example code to make this easier to understand?

**Comment by DusanBosnjakKodiak** [comment]
>described the issue fairly well. 

It's not an issue unfortunately, but a feature, by design. So to be more specific, the issue is can we change the behavior of `onBeforeCompile` to work as people might expect it, or at least be deterministic.

**Comment by mrdoob** [comment]
Thanks!

**Comment by pboyer** [comment]
Woohoo!

**Comment by titansoftime** [comment]
THANK YOU! I spent 7 hours straight trying to debug my code and eventually realized it was related to three.js material cache. So happy to find this.

**Pull request merged**
