### PR TITLE
OBJLoader: MultiMaterial and geometry group support

### LINKED ISSUE #8681: OBJLoader does not handle more than one material per object/group
##### Description of the problem 

It is possible for one object/group to have multiple materials, e.g. to have 12 faces of material A and next 12 faces of material B. Current implementation does not handle it properly. 

I changed OBJLoader.js, now it creates not one mesh per object, but one mesh per tuple (object name, group name, material name, material smoothness), named 'o:foo,g:bar,usemtl:baz,s:[01]'. This way there is still one material per mesh, but more than one mesh per object/group, albeit with somewhat convoluted names.

I don't know how to make an attachment in this issue tracker (I'm new to github), so I share that externally and provide links:

http://gnu.univ.gda.pl/~grzes/three.js/OBJLoader.js
http://gnu.univ.gda.pl/~grzes/three.js/OBJLoader.js.diff

##### Three.js version

- [x] Dev
- [ ] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### PR DESCRIPTION
**Pull request by jonnenauha**
- Tracks material declaration occuring mid face declaration
- If object has multiple materials a MultiMaterial and geometry groups are created.
- This approach is better than splitting into separate objects (this would have been the easy path)
  - We are creating as many objects the file defines. Author/dev can expect the same amount to come out than what was declared (correctness).
  - The full geometry would be duplicated into N objects, afaik this uploads the geometry multiple times to the GPU (perf, i had test asset that had >400 submeshes with 1-6 geometry groups each).

Fixes #8681 #8640 (provided assets tested with mtl:s)

Updates #8203 (fixes OPs 2. point, no test assets provided unfortunately). In this issue we also discussed that this approach should be taken when fixing these bugs.

objloader

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by jonnenauha** [comment]
@mrdoob #8681 #8640 can be closed. #8203 is partly fixed, there are other things in the ticket. Maybe a new more focused issue on the mtl preparsing/autoloading should be created and that one closed?

I guess doing the "Fixes #xxx" in the commit msg does not work if my account does not have rights to close tickets :) I was hoping that would work to save you the trouble.

**Comment by mrdoob** [comment]
> @mrdoob #8681 #8640 can be closed. 

Done! 😊

**Comment by thanhcongvt1992** [comment]
Dear mrdoob and jonnenauha,

I have just imported my office OBJ and MTL file with Three.js but when I zoom and move to see around like .GIF file below, the wall of the house is shook. What's happen? and How I can fix it?

whatshappen

I'm looking forward to receiving your reply.

Thank you all.

**Comment by jonnenauha** [comment]
Looks like z-fighting (https://en.wikipedia.org/wiki/Z-fighting)? How "big" is the model in scale, do you use logdepth?

Try to make the obj loader returned `object.scale` smaller if that helps.

**Comment by thanhcongvt1992** [comment]
I'vs got it!!

You're right man. My office is too small. Then I used logarithmic depth you told me and the result is successful. Thank you so much. Thank for your help again!

stackoverflow

**Comment by thanhcongvt1992** [comment]
Halo mrdoob and jonnenauha, how's it going?
I've just had a mistake with some models which have textures are TGA file extension.
I changed the .TGA file texture to .JPG and configured the .MTL file, but the result is like this pic below:
whathappen
I cannot find how to fix it. Where is the reason?
This is the original file:
 https://drive.google.com/open?id=0B1adndnM3iNwUzAtNUpnVFptdlE
This is the fixed file:
https://drive.google.com/open?id=0B1adndnM3iNwejlSOEVMZFFHRG8

Thank you all again

**Comment by thanhcongvt1992** [comment]
Bonus information for our problem:
When I open the fixed files (.TGA to .JPG) in Blender, I worked exactly.
whathappen1

That is the reason I think we have something wrong in OBJLoader.js or MTLLoader.js

**Comment by jonnenauha** [comment]
@thanhcongvt1992 I'll try to check it out before I sent the PR out. With a quick look of the .obj I might have fixed this already dealing with this https://github.com/mrdoob/three.js/issues/8792 

TGA is probably not a problem, granted that three.js supports loading them (I think it does?)

**Comment by jonnenauha** [comment]
@thanhcongvt1992 I figured this out. You diffuse color is black. Which apparently will make the whole model black even if textured. So not a problem with the loader. I was thinking if there should be a warning if Kd is zero :P I think its a authoring issue, you might want a mesh to be black, so not a great idea to add warning.

`Kd 0.000000 0.000000 0.000000` increase these on both, `1 1 1` looks ok.

image

**Comment by thanhcongvt1992** [comment]
@jonnenauha Yeah man! I followed your last instruction, added some lines with **_usemtl_** after g/o line in OBJ file but it is still failed. And now, the MTL file is the key. After this problem, I have to read the meaning of symbols in MTL file carefully! ^.^

fixed

Thank you so much again

But why blender can read it with Kd 0.000000 0.000000 0.000000 ?

**Comment by jonnenauha** [comment]
I have no idea, there are always differences in colors and lighting between different renderers. Someone more experienced with three.js might be able to explain what actually happens in the lighting model when phong diffuse is zero. Should think it would still pick up the texture a bit and not go full black :)

**Comment by mrdoob** [comment]
Diffuse color (`color`) and diffuse texture (`map`) are multiplied. So that's why...

**Pull request merged**
