### PR TITLE
Fix: wrong face cull for shadows of freshly inserted mirrored objects.

### PR DESCRIPTION
**Pull request by OndrejSpanel**
PR for #15821

As the function `renderBufferDirect` uses a `object.normalMatrix` value to determine the face cull direction, it needs to be set in `WebGLShadowMap.renderObject` as well, not only in the `WebGLRenderer.renderObject`.

Note: `normalMatrix` is computed as `this.setFromMatrix4( matrix4 ).getInverse( this ).transpose()`. I hope the performance impact caused by this is acceptable. If not, I suggest adding parameter `mirrored` to the `renderBufferDirect` function and to compute matrix determinant directly without inverting the matrix (matrix inversion does not change determinant sign).

### CODE REVIEW

**Comment by WestLangley** [comment]
Hmm... Would you be willing to investigate the history of this, working backwards from #14379?

Perhaps this can be refactored, and the determinant can be computed only once as `object.matrixWorld.determinant()`, which is independent of the shadow camera.

**Comment by OndrejSpanel** [comment]
The determinant is already computed for each object for both normal and shadow rendering before this fix. All this fix adds it matrix inversion computation for the shadow object rendering (the same computation already is present in normal object rendering). Unless there is some experiment which shows this fix introduces a measurable performance impact, I suggest leaving possible optimizations for separate issues / PRs.

**Comment by WestLangley** [comment]
Does your edge case go away if we did this, instead?
```js
var frontFaceCW = ( object.isMesh && object.matrixWorld.determinant() < 0 );
```

**Comment by OndrejSpanel** [comment]
Yes, that fixes it fine, as `matrixWorld` is already computed both for shadows and normal objects.

**Comment by WestLangley** [comment]
>I think we can safely assume camera matrix is a non-mirroring one.

Actually, not, apparently. (#14372)

This is why I asked you to study the history of #14379. If you look at #12787, the original PR used `matrixWorld`.

---

Personally, I do not think reflections in `camera.matrixWorld` should be supported. For one thing, we would have to fix `OrbitControls` to support it, and it is not even clear to me what the behavior should be in that case.

**Comment by OndrejSpanel** [comment]
Sigh. A proper fix could then be to multiply signs of `camera.matrixWorld` and `object.matrixWorld` determinants. The `camera.matrixWorld` one can be computed once for the whole scene.

**Comment by OndrejSpanel** [comment]
> multiply signs of `camera.matrixWorld` and `object.matrixWorld` determinants (3x3 determinants should do).

Pushed a commit implementing this.

> The `camera.matrixWorld` one can be computed once for the whole scene.

While this is possible to add,  current implementation computing two 3x3 determinants should be faster then previous which computed one 4x4, therefore I am not convinced adding the logic to handle the global value computation is worth the effort.

**Comment by mrdoob** [comment]
@WestLangley Does this look good to you?

**Comment by Mugen87** [comment]
`Matrix4.determinant3x3()` should be documented here: https://threejs.org/docs/#api/en/math/Matrix4

**Comment by WestLangley** [comment]
>@WestLangley Does this look good to you?

I am not in favor of this latest change to the PR. This is overkill, IMO.

I would implement what I suggested above:

```js
var frontFaceCW = ( object.isMesh && object.matrixWorld.determinant() < 0 );
```
which is the approach originally used in #12787.

The approach in #12787 was modified in a later PR to accommodate a user who wanted to negatively-scale the camera matrix. But the modification did not test shadows or the effects on other features like the controls. The library does not fully-support a negative scale on the camera.

I would restore the approach used in #12787. Shadows will then work correctly.

I would also not worry about `determinant3x3()`. The need for that optimization has not been demonstrated.

Instead, _if_ there is a performance issue, we can optimize the code in `determinant()`.

**Comment by OndrejSpanel** [comment]
Ok, I have no preference on this. Back to the previous commit.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@OndrejSpanel Thank you for working on this.

**Pull request merged**
