### PR TITLE
Examples: Added touch support to webgl_panorama_equirectangular

### LINKED ISSUE #13275: Examples: panorama_equirectangular does not support touch controls
##### Description of the problem

Mobile touch is not working for the following example:

https://threejs.org/examples/webgl_panorama_equirectangular.html

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

### PR DESCRIPTION
**Pull request by Mugen87**
Fixes #13275

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawgit.com/Mugen87/three.js/dev2/examples/webgl_panorama_equirectangular.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
There is a problem with this on iPhone, at least. The entire webpage drags on touch.

Also, do you think it would be better to remove the autorotation ( and therefore, the animation loop)? Personally, I do not think using autorotation and touch together makes for a pleasant API.

**Comment by mrdoob** [comment]
We should definitely fix this on iPhone, but I think the autorotation should stay. It hints the user that it's a panorama. Maybe we should disable the autorotation after the user interacts?

**Comment by WestLangley** [comment]
>Maybe we should disable the autorotation after the user interacts?

If you don't want to remove the autorotation, that makes sense -- and cancel the animation frame at the same time.

**Comment by Mugen87** [comment]
I think the problem is that Safari does not support the CSS `touch-action` property. I've tested with my Pixel with Chrome and Firefox

https://caniuse.com/#feat=css-touch-action

Unfortunately, I have no iPhone so it's hard to fix this on my side. Using `event.preventDefault()` would do the trick but this can be problematic in context of passive event listeners.

see https://www.chromestatus.com/features/5093566007214080

**Comment by Mugen87** [comment]
Interesting: https://bugs.webkit.org/show_bug.cgi?id=133112

**Comment by Mugen87** [comment]
If you like to introduce `OrbitControls` in the example, please do. But keep in mind that it only works since `OrbitControls` sets its event listener to the canvas element. If you remove the second parameter `renderer.domElement` from the ctor in `webgl_panorama_cube` (so `document` is used), you get the following warnings in Chrome/Android:

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

In general, the way we use `event.preventDefault()` within the control classes might not be future-proof. This is something we need to investigate. Using `touch-action` seems more promising. Too bad, that Safari does not support the property yet.

**Comment by WestLangley** [comment]
@Mugen87 I'm OK with leaving it as-is for now. Thank you for the explanation.

**Pull request merged**
