### PR TITLE
WebGLPrograms: Enable uvs only in vertex shader.

### PR DESCRIPTION
**Pull request by Mugen87**
Related #17626

### CODE REVIEW

**Comment by jbaicoianu** [comment]
This seems like it fixes the warning by declaring the variable as local to the vertex shader in the case where the fragment shader doesn't use it, but I think in that case it's initializing the vector to the default (0,0).  Correct me if I'm missing something, but it seems we'll also need to modify the vertex shader to assign the values if they're not defined:

https://github.com/mrdoob/three.js/blob/970f47a2addd1b965d2c43d63ca47170649eba73/src/renderers/shaders/ShaderChunk/uv_vertex.glsl.js#L2-L6

**Comment by Mugen87** [comment]
I'm afraid I don't understand what you mean^^. The idea of the PR is to avoid the usage of a varying. Essentially `vUv` is just declared differently. 

> Correct me if I'm missing something, but it seems we'll also need to modify the vertex shader to assign the values if they're not defined:

How would this modification look like?

**Comment by Mugen87** [comment]
Merging. We can finally verify the change on `dev`.

**Pull request merged**
