### PR TITLE
ShaderMaterial: Added loop unroll control

### PR DESCRIPTION
**Pull request by Mugen87**
Solves #12312

### CODE REVIEW

**Comment by mrdoob** [comment]
I wonder if this is something that we could "hide" in `material.defines` for the time being without having to touch the API that much...

**Comment by Mugen87** [comment]
Do you mean something like this?

**Comment by blaze33** [comment]
Hi ! Could it be considered to reopen the PR ? I had the same issue with a ShaderMaterial where I was trying to add three.js shader chunks to compute shadows and it took me hours to debug it with only `0:102(109): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later` as an error message. Thanks :)

**Comment by blaze33** [comment]
Actually I got it working with : 
```javascript
material.isShaderMaterial = false
material.isMeshStandardMaterial = true
material.isMeshPhysicalMaterial = true
```
Then I could include `lights_template.glsl` in my shader material and have the loops unrolled :)

**Comment by Mugen87** [comment]
Implemented via #13140

**Pull request closed without merging**
