### PR TITLE
Editor: updated es-module-shims@1.6.3

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #XXXX

**Description**

As the title.

### CODE REVIEW

**Comment by epreston** [comment]
Removing the library and replacing it with "content delivery network" import breaks working offline.

**Comment by mrdoob** [comment]
That's a good point.

**Comment by epreston** [comment]
See `'./js/libs/es-module-shims.js',` in `sw.js`

**Comment by linbingquan** [comment]
I think maybe download the `es-module-shims@1.6.3` and commit it.

**Comment by epreston** [comment]
Exactly.  Thats what editor needs.

**Pull request merged**
