### PR TITLE
common.glsl: Introduce linearToRelativeLuminance()

### PR DESCRIPTION
**Pull request by Mugen87**
see #11986

### CODE REVIEW

**Comment by Mugen87** [comment]
@WestLangley I've just changed `LuminosityShader`. Do you think we need further comments like proposed in https://github.com/mrdoob/three.js/pull/11986#issuecomment-323535084 ?

**Comment by WestLangley** [comment]
For now, I would just call the function `relativeLuminance()` and not differentiate between linear or sRGB inputs. This is a subtlety that most users will neither understand, nor care about.

If @bhouston feels strongly about keeping the name `linearToRelativeLuminance`, then you should modify your examples to only use the function when you know the input space is linear.

**Comment by Mugen87** [comment]
Okay, done!

**Comment by WestLangley** [comment]
Let's make sure @bhouston finds this acceptable.

**Comment by bhouston** [comment]
> Let's make sure @bhouston finds this acceptable.

It is for linear RGB color spaces, it isn't a general function.  There is a different function for dealing sRGB or gamma corrected spaces, basically you need to decode sRGB or gamma RGB to linear and then apply this.

So I much prefer the original name because it will remind people to be in linear space before using this conversion.

**Comment by Mugen87** [comment]
Only two examples make use of `LuminosityShader` right now. `webgl_postprocessing_sobel` and `webgl_shaders_tonemapping`. In both cases `LuminosityShader` works on a linear input. So `linearToRelativeLuminance()` should be consistent with regard to the examples.

**Comment by Mugen87** [comment]
I think it should be okay now!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
