### PR TITLE
Collada GLSL support and Uniform animation for it.

### PR DESCRIPTION
**Pull request by Thral25**
Added GLSL support for Collada with animation for uniforms. Some changes to the interpolation depending on what is the dataType of the uniform. Haven't tested with sample files after merging to current dev. Will test and update if there are changes.

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you have a sample file?

**Comment by Thral25** [comment]
I will send you some demo files on monday. I'm away from the PC for the
weekend.

**Comment by Thral25** [comment]
https://1drv.ms/u/s!ApZejoMIFMeriPhQkob8N0KzGWOjcQ?e=R3GjG7
Here is a test file but after the merge to latest dev The pointLights of
ShaderMaterial
no longer have shadowMapSize and the other uniforms for shadow. Is this a
bug or expected behaviour?

**Comment by Mugen87** [comment]
I have the feeling this change goes too far. The engine should not change its internals in order to enhance the support for Collada. It would be basically possible to do the same for other standards like VRML which would also be inappropriate.

Notice that Collada can be considered as deprecated. For new projects, glTF is a much better alternative and actually the recommended 3D format of `three.js`. The engine tries to implement this standard as good as possible.

**Comment by Thral25** [comment]
No problem. I added the complex uniforms animation to the engine, because it seamed reasonable to be able to animate more complex types in general, not only for Collada. This will cover glsl more fully. I haven't looked in to gITF ,i will look in to it later on.

**Comment by Mugen87** [comment]
BTW: Even without this change it's already possible to animate material properties like `opacity` which is represented as a uniform in GLSL. Check out how this is done in [misc_animation_keys](https://threejs.org/examples/misc_animation_keys).

**Comment by WestLangley** [comment]
@Mugen87 said

>Notice that Collada can be considered as deprecated.

Then make an announcement that the loader is not to be enhanced. Don't do that after the contributor has done all the work.

These kinds of arbitrary decisions are very frustrating.

@mrdoob What other loaders are to be considered as deprecated?

**Comment by WestLangley** [comment]
@Thral25 FYI -- If you get approval, it is the `/js` file that should be modified in this case, followed by `node utils/modularize.js` -- not the `/jsm` file. Otherwise, your contribution will be overwritten.

**Comment by donmccurdy** [comment]
I tend to agree with @WestLangley that ColladaLoader is not deprecated, it's just not the workflow we recommend that people use. But three.js supports 30+ formats, and if we were going to really deprecate any of those, Collada would definitely not be the first to choose.

Whether we should make these changes to ColladaLoader and to the core library is a different question of course, and I don't know the answer. Like @Mugen87, I'm a little nervous about the changes. I wonder if this could be implemented on NodeMaterial, without core API changes?

**Comment by Mugen87** [comment]
I just wanna say that `three.js` as a project should not promote the usage of Collada, OBJ and FBX. There are still too many users who are using these standards although glTF is the much better alternative.

I understand that it's useful to have loaders for these formats but on the other hand their existence can lead users into unfavorable workflows. 

> Don't do that after the contributor has done all the work.

Sorry, but the OP could also raise an issue first and ask if this contribution might be useful, especially if he puts a lot of work into it.

**Comment by Mugen87** [comment]
BTW: How would you label a standard that should not be used anymore because there is a more modern alternative? I think using the word "deprecated" seems appropriate. However, since English is not my native language I'm open for suggestion 😇 .

**Comment by donmccurdy** [comment]
The word "deprecated" has pretty formal meaning in software: it typically means something will no longer receive updates, and may eventually be removed. Usually deprecated code is clearly and formally marked as deprecated — it shouldn't be a matter of opinion whether something is deprecated. On the other hand, whether something is "recommended" or "best practice" would more often be a matter of opinion.

While both COLLADA and glTF are standards created by the Khronos Group, and even though glTF is newer and more modern, the COLLADA format is going to be around for a long time, it is [published in ISO](https://www.iso.org/standard/59902.html). The important difference (for three.js users, at least) is that COLLADA is meant for exchanging exhaustive data between authoring tools whereas glTF is meant for delivery of a final, optimized model to a runtime. For this reason (and some others) a correctly created glTF model should virtually always work better with three.js.

> I wanna say that three.js as a project should not promote the usage of Collada, OBJ and FBX. There are still too many users who are using these standards although glTF is the much better alternative.

I agree we want to encourage using glTF. Many users have the mentality that if they have a COLLADA or FBX model already, the correct workflow is to load it directly in three.js, when they would probably be better off converting it to glTF with official tools that can access the COLLADA and FBX SDKs.

But I think steering users toward better workflows is a different question than accepting bug fixes or feature additions to these loaders. If we were going to really try to deprecate any formats (formally) surely there are others in the [loaders folder](https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders) that are far less recommended than COLLADA?

**Comment by Mugen87** [comment]
> If we were going to really try to deprecate any formats (formally) surely there are others in the loaders folder that are far less recommended than COLLADA?

That's true.

In any event, thanks for this clarification! TBH, I did not expect that my statement about Collada would cause this reaction 😅 .

**Comment by Thral25** [comment]
Neither did i :) . I all ready had to develop a COLLADA export from U3D, so the extension of the loader seamed the reasonable decision. It may be older but its still used by 3dsmax, and other CAD software. As to the engine changes i don't see another way to describe complex uniform animations  (Arrays of vec3 for example) ,so i made the extension to the engine so that it supports in no matter the file format you have.
@WestLangley The build scripts output that the old way would be deprecated and only /jsm will be used i may have miss understood this not sure. I read the wiki and was wondering about that too.

**Comment by Mugen87** [comment]
Closing. The fact that the internal animation system would require a specific enhancement in order to support all possible Collada animation features makes this PR not appropriate. It's in general best if users try to avoid Collada in web based applications and use glTF instead.

**Comment by WestLangley** [comment]
>Don't do that after the contributor has done all the work.
>>Sorry but the OP could also raise an issue first and ask if this contribution might be useful. Especially if he is going to put a lot of work into it.

@Mugen87 TBH, that is a good point. :-)

**Comment by Thral25** [comment]
> Closing. The fact that the internal animation system would require a specific enhancement in order to support all possible Collada animation features makes this PR not appropriate. It's in general best if users try to avoid Collada in web based applications and use glTF instead.

Hi some information .Gltf 1.0 is the only one that supports GLSL shaders, and I don't think the uniforms are animatable in that standard (I might be wrong),but never the less it is an outdated standard also .The ne GLTF 2.0 supports PBR materials only for now I dont think it will be extended from Khronos maybe someone else will write an extension.  So there is no point to implement another outdated format to replace an existing one. Maybe mark the standards the you think should not be extended so that no one wastes their time again.

**Pull request closed without merging**
