### PR TITLE
oob glitch in games_fps

### PR DESCRIPTION
**Pull request by ghost**
**Description**

Hello, in the "games_fps" example, it is possible for the player to jump over the wall and fall endlessly: https://www.youtube.com/watch?v=ZpNtAz3NFOc

I thought it would be good to add a collidable floor that blends into the scene's background. This way the player won't fall forever and instead can explore the underside of the gltf model.

Please let me know if I can modify my work in any way.

### CODE REVIEW

**Comment by looeee** [comment]
Live example:

https://raw.githack.com/mrdoob/three.js/50abe8c34bea88bcfc3f95c5241edb1386a77a27/examples/games_fps.html

**Comment by Mugen87** [comment]
I'm afraid this is not a real fix since it's still possible to fall of the edge if you walk long enough on the new ground.

Probably better to just lower the jump height so it's not possible for the player to leave the level.

**Comment by marcofugaro** [comment]
I mean, why are we caring if a player falls endlessly? This is not a game, it's just a demo.

**Comment by Uueuuuuu** [comment]
@Mugen87 Thanks for writing! I agree, there are a few options that I can work on, if anyone had a preference:

1) Lower jump height.
2) Edit the gltf so that the bounding wall is a bit higher.
3) Teleport the player if their capsule/camera position is below y -25 (to be safe)/
4) Increase dimensions of the invisible floor I added.

@marcofugaro Thanks for writing :) While it is possible to simply reload the demo, I don't see any downsides to adding some features that would allow the player to teleport back or continue exploring the world after accidentally falling out, which was how I discovered this actually.

Looking forward to your responses and to modifying this PR based on the feedback.

**Comment by Uueuuuuu** [comment]
Erm, actually what I think might be best is to put an invisible but collidable barrier that blocks the player from ever jumping out in the first place.

I will edit this PR and re-ping. This probably is the least intrusive fix to the demo?

**Comment by Uueuuuuu** [comment]
Hi everyone,

I've updated the demo to have invisible walls that block the player from jumping out.

Can see the collision in action here:

https://www.youtube.com/watch?v=Ci9ZqpeEgPs

Thanks for making this a nice experience!

**Comment by Mugen87** [comment]
@Uueuuuuu Thanks for your efforts here! But for now 3f1dce330f9a872ad164e10e481ab1bb6aeffa30 should fix the issue without adding additional complexity.

**Comment by Uueuuuuu** [comment]
@Mugen87 Nice fix, and thank you for your kind words! I am going to dive deeply into the mechanics of Capsule and Octree to be able to contribute more. :)

**Comment by mrdoob** [comment]
> 3. Teleport the player if their capsule/camera position is below y -25 (to be safe)/

I think this is the simplest and more fun solution (so we can still jump outside the level 😁)

**Comment by Uueuuuuu** [comment]
@mrdoob Thanks for writing! I've implemented this functionality in this PR https://github.com/mrdoob/three.js/pull/22877

Happy to continue the discussion there.

**Pull request closed without merging**
