### PR TITLE
Editor: Move to ES6 modules (2nd attempt).

### PR DESCRIPTION
**Pull request by Mugen87**
This PR moves the editor to ES6 modules. I've found now a way in order to not rely on `build/three.js` anymore which was a blocker for the previous PR (see #16968).

@mrdoob Please review how `app.js` was changed. The problem is that the file is used in the editor (as part of the player) and in published projects. Hence it's not possible to import `three.modules.js` within the file since the path depends on the use case. `THREE` is now injected via `new APP.Player( THREE );`. It's also necessary to define `THREE` into the global namespace so the editor scripts are able to run.

We might want to merge the PR at the beginning of the next dev cycle since this needs some careful testing^^.

### CODE REVIEW

**Comment by Mugen87** [comment]
http://raw.githack.com/Mugen87/three.js/dev29/editor/index.html

**Comment by mrdoob** [comment]
Thanks for diving into this! 🙏

**Comment by mrdoob** [comment]
Hmm... Similarly to when we changed the examples to use modules I think it'll make things easier to use the `THREE` namespace for now:

```js
import * as THREE from '../../build/three.module.js';
```

Instead of:

```js
import {
	AnimationMixer,
	CameraHelper,
	Color,
	DirectionalLightHelper,
	HemisphereLightHelper,
	Mesh,
	MeshBasicMaterial,
	ObjectLoader,
	PerspectiveCamera,
	PointLightHelper,
	Scene,
	SkeletonHelper,
	SphereBufferGeometry,
	SpotLightHelper,
	Vector3
} from '../../build/three.module.js';
```

**Comment by Mugen87** [comment]
> Similarly to when we changed the examples to use modules I think it'll make things easier to use the THREE namespace for now:

Okay, done 👍

**Comment by mrdoob** [comment]
Lets do this! 😁
I'll test it over the weekend and fix whatever I find.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
