### PR TITLE
Lensflare: refactor

### PR DESCRIPTION
**Pull request by mrdoob**

### CODE REVIEW

**Comment by Mugen87** [comment]
Wow! Great refactoring :flushed:

Just one minor thing. I get now the warning `Output of vertex shader 'vUV' not read by fragment shader` because `fragmentShader1` does not utilize `vUV`. The combined fragment shader approach avoided this message.

**Comment by Mugen87** [comment]
BTW: Should we also rename the file to `Lensflare.js`?

**Comment by RemusMar** [comment]
The refactored version is buggy.
http://necromanthus.com/Test/html5/testA_r90.html 
1) in certain positions, the intensity is reduced in case of flare over window (semi-transparent object) 
2) in certain positions (front - right) you can see the plane model used for the first flare element.

**Comment by Mugen87** [comment]
@RemusMar Well, your demo is actually a good test case 😅

**Comment by Mugen87** [comment]
I guess the blending problem is related to https://github.com/mrdoob/three.js/commit/fe29d2def0ad9ce58467e9d9943d73139a330685#commitcomment-26836922

**Comment by mrdoob** [comment]
> Wow! Great refactoring 😳

Thanks! 😊

> Just one minor thing. I see now the warning `Output of vertex shader 'vUV' not read by fragment shader` because `fragmentShader1` does not utilize `vUV`. The combined fragment shader approach avoided this message.

I'll fix that.

**Comment by mrdoob** [comment]
@RemusMar Many thanks for testing all this!

**Comment by mrdoob** [comment]
Okay, the vUV warning is gone. 500262ab0af2d5e4ffdc1952d616bc237e2ecde6

**Comment by Mugen87** [comment]
I guess we can avoid the problem when we set `renderOrder` of `Lensflare` to `Infinity` again. So it's actually the same fix as before.

@RemusMar Can you please test if the visual errors disappear when we put the lensflare at the of the render list?

**Comment by RemusMar** [comment]
> RemusMar Can you please test if the problems disappear when we put the lensflare at the of the render list?

```javascript
this.renderOrder = Infinity;
```
seems to be enough to get rid of both issues.
http://necromanthus.com/Test/html5/testA_r90.html 
:thumbsup:

**Comment by Mugen87** [comment]
Thx for testing! Added the fix to `Lensflare` 528cbcf249b0182d23990be6a12d56754e787312

**Pull request merged**
