### PR TITLE
Puppeteer E2E test: Use `new` headless mode

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue:
```
  Puppeteer old Headless deprecation warning: 
    In the near feature `headless: true` will default to the new Headless mode 
    for Chrome instead of the old Headless implementation. For more 
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()` 
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```

**Description**

Let's see how this works...

### CODE REVIEW

**Comment by LeviPesin** [comment]
Seems like it also changes some font rendering... Maybe it could fix some examples in the exception list.

**Comment by LeviPesin** [comment]
I think this is ready to merge now.

**Comment by mrdoob** [comment]
Are you sure?

Screenshot 2023-05-04 10 34 52

**Comment by LeviPesin** [comment]
I'm afraid this is the only way to fix the text rendering inconsistences without adding like 20 more examples to the exception list -- in addition to those before this PR changing to the new headless mode adds like 5 more.

**Comment by mrdoob** [comment]
Uhh... Is there any other side effect you have not disclosed in this PR?

**Comment by mrdoob** [comment]
I can see many other broken screenshots...

Why do we need to support the new headless mode if it's breaking things and not fixing anything?

**Comment by LeviPesin** [comment]
This PR has two things: 1) enable new headless mode and 2) disable HTML text rendering (by simply `* { color: #00000000 !important; }`). 2 is so not because the new headless mode introduces the issue, but rather makes it more severe.

I can revert the text-related changes and just add more examples to the exceptions then.

**Comment by mrdoob** [comment]
Do all the OSes have the text rendering issue?

**Comment by LeviPesin** [comment]
This commit didn't revert the previous ones 🤦‍♂️

**Comment by LeviPesin** [comment]
> Do all the OSes have the text rendering issue?

The issue is the difference of text rendering between all three OSes.

**Comment by LeviPesin** [comment]
> This commit didn't revert the previous ones 🤦‍♂️

https://github.com/mrdoob/three.js/pull/25982

**Comment by mrdoob** [comment]
> The issue is the difference of text rendering between all three OSes.

Then... How about we just test in one OS as we used to?

I have yet to see any benefit in testing on all OSes...

**Pull request closed without merging**
