### PR TITLE
Expand `lint-fix` script

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: https://github.com/mrdoob/three.js/pull/25251

**Description**

Expand lint test to lint everything (core, addons, examples, docs, etc) except manual.

### CODE REVIEW

**Comment by LeviPesin** [comment]
@mrdoob @Mugen87 What's your opinion about this PR? I think it's great to also have linter reporting incorrect linting at least in addons (I think PRs break linting there quite frequently...).

**Comment by Mugen87** [comment]
I'm not 100% sure about expanding the linter like that. Originally, we wanted to enforce the code style in the core but be less strict in the examples section so it's easier for devs to contribute. Not everybody works with a IDE/editor that automatically lints the code according to the project settings. To avoid delays in PRs, we've often merged them as they are and cleaned things up at a later point.

**Comment by LeviPesin** [comment]
Maybe then we can expand `lint-fix` but keep `lint` as it is?

**Comment by Mugen87** [comment]
That sounds good to me.

**Pull request merged**
