### PR TITLE
Remove THREE.UniformsUtils from OutlineEffect

### PR DESCRIPTION
**Pull request by takahirox**
This PR removes legacy code `UniformsUtils.merge()` and `UniformsUtils.clone()` from `OutlineEffect`.

I think I need to apply the same change into `WebGLDeferredRenderer`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Just so you know, `UniformsUtils.merge()` and `UniformsUtils.clone()` are back. In case it makes `OutlineEffect` code simpler...

**Comment by takahirox** [comment]
I see. But I'd like to keep `OutlineEffect` code because
simpleness won't be improved so much even with the `merge/clone` methods.
And I like updating uniforms on `onBeforeRender` approach 
because we can reduce memory consumption by sharing uniforms.

**Comment by WestLangley** [comment]
>And I like updating uniforms on onBeforeRender approach because we can reduce memory consumption by sharing uniforms.

I do not think most users understand the subtlety and limitations of using the `object.assign()` approach -- that uniforms are shared when they are not expected to be.

Users copy these coding patterns. I'd recommend using a consistent pattern throughout the library. If you don't want to do that, then I would suggest commenting the code in great detail and explaining what you are doing and why.

**Comment by takahirox** [comment]
That makes sense.

So... give me a time what's the best way is.

**Pull request merged**
