### PR TITLE
Shaders: add equirectUv() method

### PR DESCRIPTION
**Pull request by WestLangley**

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Nice refactoring!

**Comment by mrdoob** [comment]
Very nice indeed!

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
build required.

**Comment by mrdoob** [comment]
Done!

**Comment by kila001ma** [comment]
what is  this ' equirectUv() '' method do?

**Comment by Mugen87** [comment]
Based on the given direction vector, it computes uv coordinates that can be used to sample an equirectangular texture.

**Pull request merged**
