### PR TITLE
JSM: Exporters: Create ES modules.

### PR DESCRIPTION
**Pull request by donmccurdy**
A couple issues had to be cleaned up by hand:

- converting `Math` -> `_Math`
- removing imports generated from comments containing unused `THREE.Foo` references.

### CODE REVIEW

**Comment by gkjohnson** [comment]
Should the `modularize.js` script be updated to generate these so they can be kept up to date? Or do you expect these will be the canonical versions?

**Comment by donmccurdy** [comment]
I left them out of the script because there were some manual changes that would have to be repeated, and I’m not sure how to include them in the script.

GLTFExporter has several active PRs, and OBJExporter has one somewhat stale PR. I think all except GLTFExporter could consider the ES modules canonical now.

**Comment by gkjohnson** [comment]
Would it be workable to add the `THREE.Foo` references found in comments to the `ignore` list for those particular scripts?

And for Math could maybe we could do something like the following for the `method` and `constant` replace blocks:

```js
return `new ${ p1 === 'Math' ? '_Math' : p1 }(`;
```

And update the imports generation line to

```js
var keys = Object.keys( dependencies )
    .sort().map( value => '\n\t' + value )
    .map(key => key === 'Math' ? 'Math as _Math' : key)
    .toString();
```

I think `Math` should be the only special case like this and would make it easier to regenerate those files without remembering to do the manual changes.

**Comment by donmccurdy** [comment]
Done, although it's a little messy... Definitely seeing some value in getting these off of the modularize script and considering them canonical sooner than later. 😓

**Comment by gkjohnson** [comment]
@donmccurdy I've made a PR [here](https://github.com/mrdoob/three.js/pull/15599) to help with that. Feedback appreciated!

**Comment by donmccurdy** [comment]
Great, thanks! Let's review and merge https://github.com/mrdoob/three.js/pull/15599 and then I'll polish up this PR after that. :)

**Comment by Mugen87** [comment]
@donmccurdy  #15582 us now merged. Would it make sense to update this PR/rerun the script before merging this one?

**Comment by donmccurdy** [comment]
I'm glad to update this, although note that some of my changes to the modularize script in this PR (e.g. support `_Math`) are also provided by https://github.com/mrdoob/three.js/pull/15832, which is probably more robust, if a bit more complex. If we want to merge that PR it may as well happen first. 

Or if we would like to keep on with the existing script, I'll update this PR.

**Comment by Mugen87** [comment]
Well, I just want to ensure that people can use `modularize.js`^^. More and more users complain about the broken feature and it would be good to provide a solution for this. 

Maybe fix `modularize.js` for now and later switch to something different?

**Comment by donmccurdy** [comment]
That's fine with me. 👍 Unless @mrdoob has another preference I'll rebase this PR and re-run the script.

**Comment by mrdoob** [comment]
Sorry for the delay. Lets sort this out this cycle 🙌

@donmccurdy do you mind resolving the conflicts in this pr?

**Comment by donmccurdy** [comment]
Ok, the PR is up to date. I've tested the four that have examples. The other three (MMDExporter, TypedGeometryExporter, PLYExporter) don't have examples or tests, but static analysis for unused or undefined variables is passing and the imports are all there.

I'll point out that the long `ignoreList` on GLTFExporter's entry is there because the regex can't distinguish references in comments, and using an AST (#15832) would fix that more robustly. I think I'll need to look at that PR more closely to make up my mind about it. Meanwhile feel free to merge this, or to wait to consider the PR, either way is fine.

**Comment by garyo** [comment]
Original exporter code. I found a case where it could emit a null set of primitive indices which causes an importer I'm using to crash, and I'm adding an option to allow the user of the exporter to strip geom attributes (again because an importer I'm using fails if the glTF file contains a `PRIMITIVEID` attr).
I know how to use modularize.js now though :-) so I'll regenerate as part of my PR.

**Comment by mrdoob** [comment]
Thanks!

**Comment by donmccurdy** [comment]
@garyo Ok thanks! Maybe better to just open the PR against the original file for now, there could be some rebase churn for a while trying to include the generated JSM.

**Comment by mrdoob** [comment]
The original file meaning the non-JSM file 😅

**Comment by garyo** [comment]
I did both before I saw this -- feel free to adjust as needed or let me know & I'll omit the JSM. (The JSM is what I'm using.)

**Pull request merged**
