### PR TITLE
webglmrts by default

### PR DESCRIPTION
**Pull request by mbredif**
Related issue: #21930

This PR shows that, with very hardly no API changes, a refactoring may lift many current (multiple)rendertarget limitations.

**Description**
Because of the current design, orthogonal features are currently incompatible :
- MRT is only available for 2D textures (targeting a cube, 2Darray and 3D texture is limited to a single texture)
- RenderTarget.depthTexture must be DepthTextures, and are thus limited to 2D textures (rather than cube or 2Darray)
- Many places do not provide a systematic treatment of the 4 texture cases (2D, cube, 3D, 2Darray) : eg generateMipmaps only work on 2D and cube textures.

**Proposal**
- Deprecate WebGLMultipleRenderTargets, and have WebGLRenderTargetDepth handle MRTs by default. For backward compability, install a getter/setter from texture to textures[0]
- DepthTexture is no longer needed, it may be kept to instantiate with sensible defaults a 2D depth texture. However any Texture with format set to DepthFormat or DepthStencilFormat may be used as a depth texture (except 3D textures, as this is forbidden by the spec).
- Refactor code to enable mixing render target depth texture and color textures with different types. Currently all attached non-2D textures write to the same layer/cubeface and mipmap level specified in setRenderTarget.

**Limitations**
the code paths with cube texture and/or cube rendertarget has not been extensively tested. I am not sure whether it makes sense to mix cube texture targets with, 2D, 3D layer and 2D array layer. Maybe it does, considering it as if it were a 2D array with 6 layers.

### CODE REVIEW

**Comment by mbredif** [comment]
Rendering depth and/or color(s) to a CubeTexture in WebGLCubeRenderTarget.depthTexture should now work (see the webgl_materials_cubemap_dynamic example).
I am looking for feedback in terms of use cases (does it work for your use cases ?) and design/coding (would it be possible to merge such a refactoring ?).

**Comment by LeviPesin** [comment]
@mbredif Can you please update the PR and remove build files from it?

**Comment by Mugen87** [comment]
In the meanwhile, https://github.com/mrdoob/three.js/pull/26427 has been merged which means `WebGLMultipleRenderTargets` is gone and MRT is integrated int the `RenderTarget` class with a new `count` option. 

Missing features like MRT support for 3D textures can be investigated/implemented separately in step-by-step fashion. 

I'm afraid too many changes were packed into this PR which made it too complex to review. Sorry for not providing this feedback earlier.

**Comment by mbredif** [comment]
I understand. I am glad #26427 was merged. I'll try to rebase this PR and cut it down in more manageable PRs.

**Pull request closed without merging**
