### PR TITLE
Examples: Introduce basic OBB implementation.

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduce an oriented bounding box implementation.

The class provides intersection tests with OBBs, AABBs, bounding spheres and planes. I've demonstrated the intended usage in a new example `webgl_math_obb`.

OBB's are a great compromise between tightness and performance. If the PR is accepted, I'm going to add raycasting support first and after that a routine for computing best-fit OBBs (based on Gottschalk's approach). I already have the code for this in Yuka however it requires some work and testing in order to port it to `three.js`.

### CODE REVIEW

**Comment by WestLangley** [comment]
Please note that just as
```js
Matrix4.getPosition( vec )
```
was removed in favor of
```js
Vector3.setFromMatrixPosition( matrix )
```
we are trying to avoid using the pattern
```js
this.Foo( that );
```
to modify `that`. The method  should modify `this`.

So I would not implement
```js
Matrix3.extractBasis( xAxis, yAxis, zAxis )
```
and, instead, created a private `extractBasis()` method within `OBB` for internal use to `OBB` only.

Alternatively, we already have
```js
Vector3.setFromMatrixColumn( matrix4, index )
```
which can be modified to support `Matrix3`.

**Comment by Mugen87** [comment]
> we are trying to avoid using the pattern

Can you please share the issue where this was discussed?

**Comment by WestLangley** [comment]
>Matrix4.extractBasis()

Ugh. I forgot about that one. So in that regard, `Matrix3.extractBasis()` is reasonable. :-)

**Comment by Mugen87** [comment]
@WestLangley  Do you still know where the pattern `this.Foo( that );` was discussed?

**Comment by WestLangley** [comment]
There is a long discussion in https://github.com/mrdoob/three.js/issues/2860 from 2012.

I continued that pattern in #18006.

**Comment by mrdoob** [comment]
This looks good! No need to add `examples/js` files for new files though.

**Comment by sciecode** [comment]
> This looks good! No need to add `examples/js` files for new files though.

Oh boy, I like the sound of that :heavy_check_mark:

**Comment by Mugen87** [comment]
> No need to add examples/js files for new files though.

Okay, I removed it and the respective entry in `utils/modularize.js`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
