### PR TITLE
Lathe with Vector2

### PR DESCRIPTION
**Pull request by rfm1201**
LatheGeometry modified to use Vector2 and allowing axe choice by the caller.
The axe is designed by a letter because I didn't know where I should put a constance definition.
The loop that create the geometry is not optimized for speed => the axis test is in the inner loop.

Should not break any existing code. Tested with all the examples that create a LatheGeometry.

Doc and examples not updated.

it's the next step of https://github.com/mrdoob/three.js/pull/7971#issuecomment-172276179

### CODE REVIEW

**Comment by mrdoob** [comment]
Oh, I was working on that. I think I would not have the `axe` parameter for now.

`LatheGeometry` change should just be this:

```diff
diff --git a/src/extras/geometries/LatheGeometry.js b/src/extras/geometries/LatheGeometry.js
index f702c4a..6f271bc 100644
--- a/src/extras/geometries/LatheGeometry.js
+++ b/src/extras/geometries/LatheGeometry.js
@@ -35,18 +35,18 @@ THREE.LatheGeometry = function ( points, segments, phiStart, phiLength ) {
 
 		var phi = phiStart + i * inverseSegments * phiLength;
 
-		var c = Math.cos( phi ),
-			s = Math.sin( phi );
+		var sin = Math.sin( phi );
+		var cos = Math.cos( phi );
 
 		for ( var j = 0, jl = points.length; j < jl; j ++ ) {
 
-			var pt = points[ j ];
+			var point = points[ j ];
 
 			var vertex = new THREE.Vector3();
 
-			vertex.x = c * pt.x - s * pt.y;
-			vertex.y = s * pt.x + c * pt.y;
-			vertex.z = pt.z;
+			vertex.x = point.x * cos;
+			vertex.y = point.y;
+			vertex.z = point.x * sin;
 
 			this.vertices.push( vertex );
 ```

**Comment by rfm1201** [comment]
I agree, but if someone is using LatheGeometry, his scene gonna change.
The axe parameter is not really usefull for new user, but it allow the building of exactly the same scene.

**Comment by mrdoob** [comment]
I know, I know. But we can suggest to use `geometry.rotateX( - Math.PI / 2 )`.

**Comment by mrdoob** [comment]
I'll merge and simplify.

**Comment by mrdoob** [comment]
Thanks!

**Comment by rfm1201** [comment]
Do you want me to update the documentation and examples that are know broken ?
I found
- docs/api/extras/geometries/LatheGeometry.html
- editor\js\libs\tern-threejs\threejs.js
- examples\misc_uv_tests.html
- examples\webgl_geometries.html
- examples\webgl_geometry_normals.html
- examples\webgl_modifier_subdivision.html

**Comment by mrdoob** [comment]
@rfm1201 that would be great!

**Pull request merged**
