### PR TITLE
Fast Box3 applyMatrix4

### PR DESCRIPTION
**Pull request by mikialex**
I modified three in other project, changed the view frustum culling from sphere intersection test to aabb intersection test, so I need a more efficient way to do aabb transform. The following link is maybe a better implementation .

http://dev.theomader.com/transform-bounding-boxes/

### CODE REVIEW

**Comment by WestLangley** [comment]
The method appears to produce the same output , although the code is not as clear.

Do you mind quantifying the performance improvement?

**Comment by mikialex** [comment]
Compare to the old, performance at least doubled.

1 million box transform, 20 samples
New box transform average: 31.380000000353903
Old box transform average: 83.95999999193009
Chrome 65 Macbookpro13-2015

pref code:
https://gist.github.com/mikialex/0ef8358dcfa1edf25b7466eb0f212c32

**Comment by looeee** [comment]
@mikialex could you set up a jsperf.com test? 
Different browsers and operating systems can give very different results.

**Comment by mikialex** [comment]
I tried jsperf.com, but I still cant figure out how to write a test on it, the user experience is awful..

I am confident about the performance, because the improvement is all based on algorithm, not related to platform.  The origin method is quite naive, set 6 points, each point applyMatrix4, and get box from points, which roughly has 78 addition, 90 multiplication, 6 division, 12 Math.min/max and some compare cost and function call cost. The new method only 18 multiplication, 18 addition, 18 Math.min/max, no any other cost.  

We should sacrifice some readability to gain max efficiency in basic math lib. In some cases performance is crucial.

**Comment by mrdoob** [comment]
Merging for now. Seems like we do not really rely in this method anyway...

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
This PR was reverted due to #14655.

**Pull request merged**
