### PR TITLE
AnimationAction: Fix LoopRepeat

### PR DESCRIPTION
**Pull request by Mugen87**
This PR should solve #13011

@gero3's test fiddle executes now only three times as you would expect.

### CODE REVIEW

**Comment by donmccurdy** [comment]
There is a note in the AnimationAction docs that can be removed now:

>  Note: The first run is not taken into account. For example: if repetition is set to 2, the total number of executed rounds will be 3.

**Comment by Mugen87** [comment]
Done! 👍

**Comment by Mugen87** [comment]
Reminder: Add this change to the migration guide 😊

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
