### PR TITLE
NodeEditor: Node-based for native objects

### PR DESCRIPTION
**Pull request by sunag**
### Introduction

After many attempts to create an API to define a `NodeMaterial` from editor to some specific `Mesh` I created a system so that any Three.js object could be used as `Node/*Editor` and  that `NodeEditor` could recognize and handle conflicts through the API.

This way we can bring all the native elements of Three.js: `Geometry`, `Camera`, `Animations`, etc

https://raw.githack.com/sunag/three.js/dev-scene-apply/examples/?q=playground#webgl_materials_nodes_playground

image

### Errors viewer

image

### Cable color by Node type

image

### ContextMenu opens on Top or Right

If it detects that it has reached the edge of the screen.

image

### Node creator input / Search

Use this tool to create a new `Node` or to bring a `Mesh` from `Three.js` `Scene` to `NodeEditor`

image

This contribution is funded by [Google via Igalia](https://igalia.com).

### CODE REVIEW

**Comment by sunag** [comment]
It is a step to we can be a `JSNodeBuilder` to create CPU codes in JS using `NodeEditor` too.

**Comment by looeee** [comment]
I'm having trouble adding any nodes - when I type a node then click on the node name nothing happens.

**Comment by sunag** [comment]
Hmm.. I will fix this, you can press enter too

**Comment by looeee** [comment]
Great, seems to be working again now. This is a lot of fun to play with :) 

Is there a reason why Color doesn't accept inputs? I wanted to try hooking: timer -> sin -> color.r, for example.

**Comment by sunag** [comment]
@looeee Still I need to add `JoinNode` and `SplitNode` for `NodeEditor`. I should add this next week

**Comment by mrdoob** [comment]
I guess we should rename this from `webgl_materials_nodes_playground` to `webgl_nodes_playground` at this point? 😅

**Comment by sunag** [comment]
@looeee I add `SplitNode` and `JoinNode` to `Editor`.

image

**Comment by mrdoob** [comment]
Thanks!

**Comment by jo-chemla** [comment]
Quick note: I often stumble on this issue and then spend some time trying to find the url of threejs node-material editor. It is called playground and is available here, hope it is useful to anyone including my future self!

https://threejs.org/playground/

**Comment by mrdoob** [comment]
The link is back 👋 https://github.com/mrdoob/three.js/commit/d3646a4678109befe8a9b22e55a82eeb788363f9

**Comment by jo-chemla** [comment]
Thanks, did not know it was there in the first place!

**Pull request merged**
