### PR TITLE
3DMLoader: Updates

### PR DESCRIPTION
**Pull request by fraguada**
- Added support for translation of lights
- Changed how dots are translated (CSS2DObject -> `THREE.Sprite` with `CanvasTexture`)
image
Beauties! Life is too short for rounded rectangles (for now).
- Added some material comparison so as not to end up with a material per object.

### CODE REVIEW

**Comment by Mugen87** [comment]
It seems you have to update the respective E2E screenshot. Try this:

```
npm run make-screenshot webgl_loader_3dm
```

**Comment by fraguada** [comment]
@Mugen87 it would be the same screenshot already here: https://github.com/mrdoob/three.js/blob/dev/examples/screenshots/webgl_loader_3dm.jpg

**Comment by Mugen87** [comment]
I wonder why the E2E test is complaining then 🤔 ...

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
