### PR TITLE
Async callback for cached resources.

### LINKED ISSUE #6572: THREE.ImageLoader fails when the same url is being used twice.
Just got 2 projects broken after moving from r69 to r71.

the code being used in a method that receives the material as param.

```javascript
var imageLoader = new THREE.ImageLoader();
var bitmap = imageLoader.load( url, imageLoaded );
 
function imageLoaded(){
		var texture = material.map;
		texture.image = bitmap;
		texture.needsUpdate = true;
}
```

r69 and r71 will load and update the texture with newly loaded image.
If the same url is used again, r69 works as expected, r71 crashes.
The caching mechanism seems to be the bad guy.

commenting this bit fixes my 2 projects….

```javascript
THREE.ImageLoader.prototype = {

	constructor: THREE.ImageLoader,

	load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

		/*var cached = THREE.Cache.get( url );

		if ( cached !== undefined ) {

			onLoad( cached );
			return;

		}*/
```

### LINKED ISSUE #6779: THREE.ImageUtils.loadTexture often returns undefined the second time it is run on the same URL
The following code *usually* gives me

```
i1: object
i2: undefined
```

```javascript
i1 = THREE.ImageUtils.loadTexture('http://placehold.it/100/100', undefined, function () {
    console.log("i1: " + typeof i1);
    i2 = THREE.ImageUtils.loadTexture('http://placehold.it/100/100', undefined, function () {
        console.log("i2: " + typeof i2);
    });
});
```

I'm testing on Chrome 43 on OS X.

### PR DESCRIPTION
**Pull request by dubejf**
For consistency, the `load` call should always be asynchronous, even when the resource is readily available in cache.

Affects `ImageLoader`, `XHRLoader` and `ImageUtils`.

Add unit tests (unittests_three.html only).
Update QUnit to latest version (1.10 -> 1.18).

Fixes #6779. Does NOT fix #6572.

### CODE REVIEW

**Comment by mrdoob** [comment]
> For consistency, the `load` call should always be asynchronous, even when the resource is readily available in cache.

Hmmm, what happens otherwise?

**Comment by dubejf** [comment]
> Hmmm, what happens otherwise?

Described in #6779. Basically the loader behaves differently whether images are in cache or not.

Previously: If the image is not cached, the "load" callback is called asynchronously. If the image is in cache, the callback is called immediately.

Now: The "load" callback is always called asynchronously. When the image is in cache, we schedule the callback to be executed at the next turn of the event loop.

**Comment by mrdoob** [comment]
I was trying to understand the specific use case where things break. I guess this would be a case?

```javascript
new THREE.ImageLoader().load( 'file', function ( image ) {

my_image = image;

} );

var my_image;
```

If you run that one the callback will assign `my_image` correctly because it will be executed after it's defined. But the second time it will break.

**Comment by mrdoob** [comment]
Thanks!

**Comment by dubejf** [comment]
Actually, your code is fine. `var` *declaration* are hoisted at the beginning of their scope. Declaring `my_image` at the after the function call is exactly the same as declaring it before.

However, assignments are not moved. This
```
{
	// ... stuff ...
	var my_var = 'test';
}
```
is equivalent to this:
```
{
	var my_var
	// ... stuff ...
	my_var = 'test';
}
```

**Comment by dubejf** [comment]
The problem is with code like this:
```
var texture = THREE.ImageUtils.loadTexture( url, undefined, function () {

	/// use texture

});
```

Notice that the code is not capturing the texture from the callback arguments! This code will succeed the first time, but when the image is in cache, `texture` will be `undefined`.

Texture and image loaders "return" their value twice: once when the function returns, once has parameter in the callback.

When the image is not in cache, the `loadTexture` function returns first, and the callback will run later. 

When the image is in cache, the callback is executed first, before `loadTexture` returns. `texture` in the example above is unassigned.

**Comment by WestLangley** [comment]
@dubejf Very well-stated.

And to clarify, as a result of this PR, the following code:

    var texture = THREE.ImageUtils.loadTexture( url, undefined, function () {

        /// use texture

    });

is no longer a problem. Correct?

**Comment by dubejf** [comment]
@WestLangley  Correct. And backed by this unit test: https://github.com/mrdoob/three.js/blob/dev/test/unit/extras/ImageUtils.test.js#L69

**Comment by WestLangley** [comment]
Many thanks. You are definitely on a roll here. Please don't stop. : - )

**Comment by tremby** [comment]
Wonderful; thanks, guys.

**Comment by dubejf** [comment]
@WestLangley There's still a few low hanging fruits I'll try to address!

**Comment by mrdoob** [comment]
> When the image is in cache, the callback is executed first, before loadTexture returns. texture in the example above is unassigned.

Oh! Now I got it... Thanks for explaining!

**Pull request merged**
