### PR TITLE
Clean up WebGLRenderer

### PR DESCRIPTION
**Pull request by takahirox**
I added some spaces and removed unnecessary brackets to/from `WebGLRenderer` to let it more strictly follow the coding style.

### CODE REVIEW

**Comment by takahirox** [comment]
I just realized that @Rich-Harris seems like modifying is* things so I'll close this PR so far.

#9310

**Comment by mrdoob** [comment]
This was good actually. Do you mind submitting it again?

**Comment by takahirox** [comment]
NP.

(something && something.is*) seems like being added in various files by #9310.
You'll see with this command

    $ find src/ -type f -name "*.js" | xargs egrep "\([^ )]"

**Comment by mrdoob** [comment]
Thanks!

**Comment by Rich-Harris** [comment]
> (something && something.is*) seems like being added in various files by #9310.

yep, this was to guard against falsy values, which would have caused an exception to be raised:

```js
var thing = null;

// old style – just equals `false`
if ( thing instanceof THREE.Whatever ) {
  // ...
}

// new style – would raise an exception without the guard
if ( thing.isWhatever ) {
  // ...
}
```

It looks like in the majority of cases the left hand side of the `&&` can be safely removed – another one of those unfortunate cases where an automated script has to err on the side of caution. Was planning to eventually submit a new PR taking care of them but it looks like you might be a step ahead of me @takahirox 😀

**Pull request merged**
