### PR TITLE
DRAFT: enable MSAA with WebGLMultisampledRenderTarget without EffectComposer

### PR DESCRIPTION
**Pull request by aardgoose**
Enables the WebGLMultisampledRenderTarget to target the default framebuffer for the blitFramebuffer operations, removing the need for EffectComposer and the extra copy pass. 

example modified to test.

### CODE REVIEW

**Comment by Mugen87** [comment]
> example modified to test.

The example should demonstrate MSAA in context of postprocessing which is the most relveant use case for `WebGLMultisampledRenderTarget`.

If it's a draft PR, then please use the respective github feature:

https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by aardgoose** [comment]
I wasn't aware of the draft feature - rather well hidden.

The point was to allow MSAA without the overhead/complications of the postprocessing framework.

**Comment by mrdoob** [comment]
Oh, why was this closed?

**Comment by arpu** [comment]
@aaaabaker i am interessierend in this too could you rebase this PR and reopen? or should i open a new one?

**Comment by arpu** [comment]
@Mugen87  i tested this patch against r127dev and get 
``` GL_INVALID_OPERATION: Blit feedback loop: the read and draw framebuffers are the same. ``
would be cool if you could look at this if you have time.

**Comment by Mugen87** [comment]
This change does not work 1:1 when applied since framebuffer management has changed. 

I'm also not sure if the `directToCanvas` property is a good solution...

**Comment by arpu** [comment]
for me the most imported part is setting the Hardware MSAA, because Chrome set it to 4x as default still if gl.MAX_SAMPLES is higher ( 8x,16x) 

https://bugs.chromium.org/p/chromium/issues/detail?id=1063437

**Comment by arpu** [comment]
@Mugen87  maybe i oversee something?  is there any other simpler way to set this?

**Comment by Mugen87** [comment]
@arpu Can you please try the latest if @aardgoose's example code works after #21570.

On my machine, it seems to work without further changes to the renderer.

**Pull request closed without merging**
