### PR TITLE
Allow for rendering into mipmap levels of a WebGLRenderTargetCube

### PR DESCRIPTION
**Pull request by bhouston**
This is backwards compatible with existing code because the mipmap level defaults to 0.  Very simple change.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by bhouston** [comment]
@pyalot I noticed you had a new WebGL extension here: https://www.khronos.org/registry/webgl/extensions/OES_fbo_render_mipmap/  Does this mean that currently it isn't possible to render to a mipmap level (if one is not using the extension, and according to your WebGLStats.com no one supports this extension) even if you specify it as I did in this PR for ThreeJS?

**Comment by pyalot** [comment]
> Does this mean that currently it isn't possible to render to a mipmap level

In WebGL 1.0 (and OpenGL ES 2.0) it is only permissible to render to miplevel 0 of a texture. You can set a different miplevel (the parameter exists), however this will likely either have no effect or generate a GL error (or even throw an exception because it's undefined behavior).

In WebGL 2.0 (and OpenGL ES 3.0), rendering to miplevels of textures is core functionality.

The OES_fbo_render_mipmap extension allows you to render to other miplevels than 0 on WebGL 1.0 (and OpenGL ES 2.0) contexts.

I specified that extension because it eases upgrading to WebGL 2.0.

**Comment by kenrussell** [comment]
Sorry for the delay moving that extension forward. We could push it through, but I think at this point it would be more profitable to just focus on WebGL 2.0. It's getting close, and the remaining bugs are being fixed one by one.

**Pull request merged**
