### PR TITLE
Major update of Unit tests

### PR DESCRIPTION
**Pull request by Itee**
Hello,

you're welcome in the new refactored section of unit tests of the famous threejs library !

What's is new ? So many things... But to be more precise:

- All tests are now ES6 modules
- You can run the unit tests using CLI using `npm test` or `npm run test`
- But you can also run it under your browser, when opening `UnitTests.html` under `test/unit/UnitTests.html`
- You can build with a watcher using `npm run build-test`
- Currently there are 1789 tests with 9273 assertions
- All test skeleton are ready to be implemented for all file under /src

What remains to be done:

- Create skeleton's test for /examples ( uh uh uh... )
- Implements missing tests ( marked with a todo flag in html view )

Be happy, and have fun !
Itee

### CODE REVIEW

**Comment by Itee** [comment]
Ok i merge and i'm back... damned !

**Comment by Itee** [comment]
Merged !

**Comment by mrdoob** [comment]
Seems like this PR is removing `LegacyGLTFLoader.js`? 🤔
Any chance you can do a bit of double-checking and clean up?

**Comment by Itee** [comment]
I will give a look... again

**Comment by Itee** [comment]
I close due to lot of breaks that come from nowhere... Maybe a breaking merge... 
A new cleaner PR will come soon.

**Pull request closed without merging**
