### PR TITLE
Editor: use screenfull.js lib and update i18n

### PR DESCRIPTION
**Pull request by 1993heqiang**
**Description**

Why use screenfull.js？
Simple wrapper for cross-browser usage of the JavaScript Fullscreen API, which lets you bring the page or any element into fullscreen. Smoothens out the browser implementation differences, so you don't have to.  😆 😆 😆 
Github：[https://github.com/sindresorhus/screenfull.js](https://github.com/sindresorhus/screenfull.js
)

### CODE REVIEW

**Comment by Mugen87** [comment]
The editor already has a fullscreen feature which has worked for me in the past without issues in Chrome and Firefox.

Do you mind explaining why the existing feature is not sufficient for you?

**Comment by mrdoob** [comment]
Yeah, fullscreen should work on modern browser.

Maybe better to remove that change and leave it for another PR so it doesn't block the rest of the changes here?

**Comment by 1993heqiang** [comment]
> The editor already has a fullscreen feature which has worked for me in the past without issues in Chrome and Firefox.
> 
> Do you mind explaining why the existing feature is not sufficient for you?

First , there are some differences in the fullscreen api of each browser. In order to adapt to more browsers, it is necessary to use screenfull.js.
Second, after full screen, "Fullscreen" should change the state to "Exit Fullscreen", and this state change is easier to use screenfull.js.

In addition, this code has a little problem. When entering the full screen, the first if statement is executed for a week, and the second if statement will still be executed. This logic is incorrect. I think it's better to leave this kind of troublesome logic to screenfull.js.
image

**Comment by 1993heqiang** [comment]
> Yeah, fullscreen should work on modern browser.
> 
> Maybe better to remove that change and leave it for another PR so it doesn't block the rest of the changes here?


I have already mentioned another PR #21454, if you don't think it is necessary to use screenfull.js, I will close this.

**Comment by Mugen87** [comment]
Closing in favor of #21454.

**Comment by mrdoob** [comment]
> I have already submitted another PR #21454, if you don't think it is necessary to use screenfull.js, I will close this.

Seems like [the only browse that doesn't support the latest version of the Fullscreen API is Safari](https://caniuse.com/fullscreen). Lets hope they implement it soon 🤞

**Pull request closed without merging**
