### PR TITLE
Src: output_fragment -> opaque_fragment

### PR DESCRIPTION
**Pull request by WestLangley**
"Output pass" is now the term we use for a device-specific, tone-mapping/color-space transform.

Consequently, I think `output_fragment` is misnamed; `opaque_fragment` seems reasonable to me.

I have included a migration helper, so this shader chunk name change is backwards-compatible.

### CODE REVIEW

**Comment by WestLangley** [comment]
This PR requires updated build files.

**Comment by Mugen87** [comment]
Updated builds: c9ace8c01ba678bd6d7b0312bf296f11faab18a4

**Comment by drcmda** [comment]
Could this please be reverted?

 This is a major breaking change released in a feature minor over a name change that will break threes eco system. Please think about the churn changes like that will cause, not to mention that libraries that do move up have to pin threejs to latest. It will also kill libraries that are unmaintained. 
 
I can understand that breaking changes are sometimes necessary but this change probably isn’t and should be slipped in once three goes through heavy changes.
 
@mrdoob

**Comment by drcmda** [comment]
Quick Github search reveals ~500 projects/libraries that will fail come 154. One of them is https://github.com/pmndrs/drei used by ~40k Github projects and ~150k npm installs/week. If we move to opaque_fragment it requires a new pin in peerDep. Not saying this to complain, i honestly want Threejs to have a sustainable and heathly eco system.

**Comment by Mugen87** [comment]
> Quick Github search reveals ~500 projects/libraries that will fail come 154.

For clarity: They do not _fail_ only a warning will be logged. Read the discussion in https://github.com/mrdoob/three.js/pull/26206#issuecomment-1580185725.

**Comment by drcmda** [comment]
> > Quick Github search reveals ~500 projects/libraries that will fail come 154.
> 
> For clarity: They do not _fail_ only a warning will be logged. Read the discussion in [#26206 (comment)](https://github.com/mrdoob/three.js/pull/26206#issuecomment-1580185725).

custom shaders, but extending via replace will (imo) break.

**Comment by Mugen87** [comment]
In what use cases do you use `replace()`?

**Comment by drcmda** [comment]
there are countless of shaders out there extending existing materials via replace. https://github.com/search?q=replace%28%27%23include+%3Coutput&type=code

**Comment by Mugen87** [comment]
I've mentioned my concerns in #26206 about renaming shader chunks. 

However, it is no option to "freeze" the name of chunks since things have to change/improve/refactor things. It is also no option right now to change the release management (please do not start a discussion about this here).

Given the fallback in #26206 I would say it's appropriate to make this change. We can't guarantee that things do not ever break again and the migration task for fixing this one is easy.

**Comment by drcmda** [comment]
> the migration task for fixing this one is easy.

it is only easy when you think of migration in terms of local code. it is not easy if you ship a library that people rely on, like drei which is used by thousands, which is now, as i feared, breaking. https://github.com/pmndrs/drei/commit/1169c02fcfd1151fa08effb4ca7215f91b140f53

this change clamps it to latest three, while users reported drei failing before the change. all we are asking for is that threejs considers this, too.

**Pull request merged**
