### PR TITLE
npm run build-watch - automatically rebuild three.js when changes made

### PR DESCRIPTION
**Pull request by bhouston**
This adds a new npm run script - "build-watch".  To run it go to the root three.js directory and type in:

```
npm run build-watch
```

What this script does is that it continues to watch the /src/ directory and if it notices any changes its run "npm run build" to build a new version of build/three.js.  This means if you use this, you just need to make changes to your js or glsl, save and refresh your three.js example page -- no need to manually run build.bat all the time.

Personally, I love this work flow.

NOTE: requires "npm install" for chokidar.

### CODE REVIEW

**Comment by zz85** [comment]
Love this 👍 

I have 2 suggestions - I would prefer `dev` over `build-watch`... so I'll just have to type `npm run dev` when going into development mode.

Also, it would be nice if there's a console log message when the build is done... right now the output seems to indicate the build is still running when it has completed..

```
> three@0.77.1 build /Users/joshua/dev/gits/three.js
> cd ./utils/build && node build.js --include common --include extras

 * Building ../../build/three.js
unlink:src/renderers/test.js
change:src/extras/core/CurvePath.js
change:src/extras/core/Path.js
change:src/extras/curves/EllipseCurve.js

> three@0.77.1 build /Users/joshua/dev/gits/three.js
> cd ./utils/build && node build.js --include common --include extras

 * Building ../../build/three.js
```

and the 2 and a half suggestion, I always like to see how long the build took to run, and that can be done by adding a `time` before `npm run build`

**Comment by bhouston** [comment]
I've updated this PR so that the command is "npm run dev" and that the console output of a build shows a little progress status and total time elapsed once completed:

```
> node build.js --include common --include extras

Building ../../build/three.js:
  Collecting source files.
  Writing output.
  --- Build time: 0.1s
```

I am not saying this is perfect but I think it achieves what @zz85 likes.  I like it too.

**Comment by bhouston** [comment]
BTW @zz85, I can not use "time" as that isn't available on Windows - only on OSX and Linux unfortunately.

**Comment by mrdoob** [comment]
Thanks!

**Comment by zz85** [comment]
Cool~ maybe linting and code styling during `npm run dev` could be one future enhancement :)

**Pull request merged**
