### PR TITLE
CSS2DObject and CSS3DObject: Remove broken generics and make renderer parameter unknown

### PR DESCRIPTION
**Pull request by juliendargelos**
See https://github.com/mrdoob/three.js/pull/18518#issuecomment-580511393

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Does this deserve pushing the npm package to `0.113.2`?

**Comment by juliendargelos** [comment]
This was quite a nonsense and will cause type errors on existing typescript code that uses render callbacks:

https://github.com/mrdoob/three.js/blob/19ae9719a126bd5291600b9db64a62020700c824/src/core/Object3D.d.ts#L156-L157

So I think the fix should be pushed

**Comment by mrdoob** [comment]
Done!

**Comment by Mugen87** [comment]
Um, that's why I'm not a fan of static typing^^.

**Pull request merged**
