### PR TITLE
Lights: Add selective lighting via layers

### PR DESCRIPTION
**Pull request by FarazzShaikh**
Related issue: #5180 

**Description**

Adds support for selective lighting via Layers - Lights and object mask are passed in an uniforms, then, a light is only calculated if it passes the mask test.

**Potential issue**

This impl uses logical AND `&` which is only supported in GLSL ES version 3. Do we want to support version 1 and 2 as well? In which case I will be looking for a way to polyfill AND. 

**TODO**

- [ ] Fix support for multiple lights
- [ ] Add support for all other light types (Currently only supports point light)
- [ ] Polyfill logical AND

https://github.com/mrdoob/three.js/assets/55190601/ece20768-066b-4405-a899-80722dcf68dc

### CODE REVIEW

**Comment by Mugen87** [comment]
Similar to transform feedback (see https://github.com/mrdoob/three.js/issues/14416#issuecomment-2160471897), I'm not in favor of adding support to selective lighting in `WebGLRenderer` since we already have this working for `WebGPURenderer`.

https://threejs.org/examples/webgpu_lights_selective

The renderer has a WebGPU and WebGL backend and the demo works for both of them.

We are currently in the process of a slow migration from `WebGPURenderer` to `WebGLRenderer` and that means we do only add selected features to `WebGLRenderer` anymore. Meaning features with a manageable scope. Your PR will add quite a lot of complexity until all light types and other TODOs are implemented. IMO, it's out of scope. It's probably best if you start using `WebGPURenderer` if you want selective lighting in your app.

**Comment by FarazzShaikh** [comment]
Gotcha, feel free to close if truly out of scope. However, this PR even when complete will not really be too complicated, its a few uniforms and a few lines of shader code. 

In my opnion, even if core developement on `WebGLRenderer` is halted, Three should still allow for community driven updates to it since I believe the use of `WebGLRenderer` will stick around for a good while even after the migration to the new renderer is complete.

**Comment by Mugen87** [comment]
Yeah, I can understand that. Depending on how Ricardo and others from the core team think about this issue, we maybe decide differently.

But I also see devs discovering `WebGPURenderer`, the new material system and especially TSL and they are excited about the new possibilities. So I'm not surprised if these people do not miss `WebGLRenderer` at all and can't wait to migrate.

**Comment by Mugen87** [comment]
Closing. Since we want to put the focus on `WebGPURenderer`, selective lighting won't be supported with `WebGPURenderer`.

**Pull request closed without merging**
