### PR TITLE
THREE.Mesh.raycast - check uvs array length before accessing

### PR DESCRIPTION
**Pull request by Immugio**
The existing code assumes that if there are uvs there has to be one for each face. In my case I have a custom Geometry that has textures on some faces and solid colors on other faces. I don't specify uvs for faces with solid colors since they are not required. 

I've added a check to verify that the uv for the particular face is present before accessing it. 

Thanks.

### CODE REVIEW

**Comment by WestLangley** [comment]
>The existing code assumes that if there are uvs there has to be one for each face.

Is that not an implicit assumption throughout the library? If so, if we are going to relax that assumption in raycasting, we should do so everywhere.

@Immugio Can you provide a simple live example showing your use case? Are you using `MultiMaterial`? Any console errors?

**Comment by Immugio** [comment]
@WestLangley you are correct, after checking the console more closely I can see that there is actually a bunch of warnings related to this - I get lot of warnings caused by output from ColladaLoader and my console is completely spammed. I withdraw my request. Thanks.

**Comment by Immugio** [comment]
I would like to reopen this discussion. I keep running into the problem that the uvs are set for only some faces as the others use colors and don't necessary need uvs. It is possible to ensure that uvs are correct for models I manage. However I'm having this problem with collada files exported from SketchUp. This simple check would make the library more robust.

**Comment by mrdoob** [comment]
Ok!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
