### PR TITLE
Doc and examples

### PR DESCRIPTION
**Pull request by rfm1201**
Didn't change the link to the source code at the end of docs/api/extras/geometries/LatheGeometry.html because I don't know if you change those kind of thing during the dev.

By the way, when you cleaned LatheGeometry.js (after https://github.com/mrdoob/three.js/pull/7989), you removed the console.warn when the function is called with an array of Vector3.
The array conversion was maybe to much, but the I think that the console.warn is needed to help people already using LatheGeometry.

### CODE REVIEW

**Comment by mrdoob** [comment]
> The array conversion was maybe to much, but the I think that the console.warn is needed to help people already using LatheGeometry.

Yeah. I think I'll will wait for someone to complain. It may be that no one is using it yet.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
> I think I'll will wait for someone to complain.

Yikes!  Complaining.   : - )

**Comment by mrdoob** [comment]
😅

**Pull request merged**
