### PR TITLE
use strict (in)equalities

### PR DESCRIPTION
**Pull request by CodingFabian**
I started to look into a few performance numbers of three.js when working through my profilings I saw a few places where non strict equalities are used. I checked with your codebase and you generally seem to prefer the strict ones. I went through all the ones in this pr, and they all work with strict as will.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice. Thanks!

**Comment by WestLangley** [comment]
Do you really want these to be the patterns we are to follow?

    var hasFaceVertexNormals = faces[ 0 ] && faces[ 0 ].vertexNormals.length === 3;

    if ( plane.distanceToPoint( this.origin ) === 0 ) {

    if ( subPaths.length === 1 ) {

**Comment by mrdoob** [comment]
Hmm... Yes? Do you see anything wrong with it?

**Comment by WestLangley** [comment]
I am trying to find something wrong with it. No luck so far. : - )

**Comment by mrdoob** [comment]
Haha!

**Pull request merged**
