### PR TITLE
Shaders: Improve Packing

### LINKED ISSUE #28692: packDepthToRG seems broken
### Description

`packing.glsl.js` includes several packDepth / unpackDepth functions.

`packDepthToRGBA` packs a float in [0,1] range to a vec4 in the same range, `unpackRGBAToDepth` does the reverse 

`packDepthToRG` `unpackRGToDepth` do the same in low resolution (vec2)

I see two problems here:

1. (minor) By some strange design decision, packDepthToRGBA uses the fourth (A) component for the most significant part, red for the least significant part. This does not matter if one is only interested in converting to-from a vec4, but seems inconvenient for visual inspection - and it's also cumbersome if the alpha component gets lost in the pipeline. It would seem more natural to me to pack in reverse order.

2.  (major) `packDepthToRG` `unpackRGToDepth`  are wrong, because they ignore the above, they take the RG components of `packDepthToRGBA` (the least significant), setting the most significant part to zero. 

I attach an example with a fixed version (for the second issue, I suspect that the first one could have more impact to change)

### Reproduction steps

1. Check that the composed transformation  `float f2 = unpackRGToDepth( packDepthToRG( f ))` does not return (not even approximately) the original value

You can see in the attached live example that the composing works for the original high-res packDepthToRGBA - unpackRGBAToDepth and for my fixed versions packDepthToRG2 unpackRGToDepth2 

### Code

```glsl
// normalized coordinates, (0,0) is the bottom left
in vec2 uv;
// resulting fragment color, you may name it whatever you like
out vec4 fragColor;

// --- from https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/packing.glsl.js ------

const float PackUpscale = 256. / 255.; // fraction -> 0..1 (including 1)
const float UnpackDownscale = 255. / 256.; // 0..1 -> fraction (excluding 1)

const vec3 PackFactors = vec3( 256. * 256. * 256., 256. * 256., 256. );
const vec4 UnpackFactors = UnpackDownscale / vec4( PackFactors, 1. );

const float ShiftRight8 = 1. / 256.;

vec4 packDepthToRGBA( const in float v ) {
	vec4 r = vec4( fract( v * PackFactors ), v );
	r.yzw -= r.xyz * ShiftRight8; // tidy overflow
	return r * PackUpscale;
}

float unpackRGBAToDepth( const in vec4 v ) {
	return dot( v, UnpackFactors );
}

vec2 packDepthToRG( in highp float v ) {
	return packDepthToRGBA( v ).yx;
}

float unpackRGToDepth( const in highp vec2 v ) {
	return unpackRGBAToDepth( vec4( v.xy, 0.0, 0.0 ) );
}

// ---------- my own "fixed" versions

vec2 packDepthToRG2( in highp float v ) {
	return packDepthToRGBA( v ).zw;
}

float unpackRGToDepth2( const in highp vec2 v ) {
	return unpackRGBAToDepth( vec4(0.0, 0.0,v) );
}

// should produce a uniform gradient - comment/uncomment fragColor = lines to try
void main() {
	vec2 st = uv;
    float r = unpackRGBAToDepth(packDepthToRGBA(st.x));
    float g = st.y;
    bool plain = fract(st.x * 5.0 + st.y) > 0.5; // bands
    // fragColor = plain ? vec4(r,g,0.0,1.0) : vec4( unpackRGBAToDepth(packDepthToRGBA(r)), g, 0.0, 1.0); // this works
    fragColor = plain ? vec4(r,g,0.0,1.0) : vec4( unpackRGToDepth(packDepthToRG(r)), g, 0.0, 1.0); // this does not work
    // fragColor = plain ? vec4(r,g,0.0,1.0) : vec4( unpackRGToDepth2(packDepthToRG2(r)), g, 0.0, 1.0); // FIXED 
}
```

### Live example

* [glsl.app](https://glsl.app/#~gnfdrvwhkk7hp47op55spxfx)

### Screenshots

_No response_

### Version

r165

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by WestLangley**
Fixed #28692.

This PR implements the improvements to packing suggested by @leonbloy in #28692.

### CODE REVIEW

**Comment by WestLangley** [comment]
Temporary live example:
https://raw.githack.com/westlangley/three.js/dev-pack_depth/examples/webgl_materials_channels.html

**Review by Mugen87 — APPROVED** [review]
LGTM! Do you mind reverting the changes to `three.module.js` for merging?

**Comment by lmicola** [comment]
Any reason why this wasnt included in 167 milestone? It took me by suprise that my implementation of depth picking stoped working properly.

**Comment by Mugen87** [comment]
Not sure what you mean since the changes are part of the engine since `r167`.

**Comment by mrdoob** [comment]
@lmicola Do you mean in the change log?

**Comment by Mugen87** [comment]
It should be there:

image

**Comment by WestLangley** [comment]
Perhaps he is referring to r167 in the [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#166--r167).

**Comment by WestLangley** [comment]
The `RGBADepthPacking` API has not changed, only the implementation. I am inclined to think it is not appropriate to include it in the r167 migration guide.

/ping @Mugen87

**Pull request merged**
