### PR TITLE
Simple cone geometry

### PR DESCRIPTION
**Pull request by abelnation**
Addresses #8720, at least in a trivial way.  

Creates a new primitive, `ConeGeometry` and `ConeBufferGeometry`, that are just wrappers around the corresponding `Cyilinder` geometries.  

Note that, the "point" in a cylinder that has one radius as `0` is rendered just like any other side face of the cylinder, i.e. with two triangles.  In the `r=0` case, one of those triangles is reduced to zero-area, so this solution unnecessarily renders 1 extra invisible triangle per radial segment.  I spent some time trying to optimize the CylinderBufferGeometry logic to detect and remove those extra vertices and indices, but found that it dirtied the otherwise nice logic of the cynlinder generation code.  

@mrdoob @WestLangley

### CODE REVIEW

**Comment by WestLangley** [comment]
This PR appears to be well-done and complete.

As a separate issue, not to detract from this PR, I think the `Cylinder/Cone(Buffer)Geometry` UVs for the end-caps are not right. I think the UV mapping should look like that of `Circle(Buffer)Geometry`.

...Just in case you are interested in pursuing that. ;)

**Comment by abelnation** [comment]
@WestLangley do you have a reference image / example that I might work from?

**Comment by abelnation** [comment]
intuitively, it seems that the torso mapping should map the entire texture image to the entire face of the torso.  i'm less clear on what the mapping should look like for a cap...

**Comment by WestLangley** [comment]
>@WestLangley do you have a reference image / example that I might work from?

Just have a look at `CircleBufferGeometry` and see if you agree. There is no right answer here.

/ping @Mugen87 for another opinion.

**Comment by WestLangley** [comment]
Oh. I meant to mention not to include the build files in the PR.

See [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

**Comment by Mugen87** [comment]
> As a separate issue, not to detract from this PR, I think the Cylinder/Cone(Buffer)Geometry UVs for the end-caps are not right. I think the UV mapping should look like that of Circle(Buffer)Geometry.

Here is the corresponding issue for this requirement #8270. I agree that an alignment to `Circle(Buffer)Geometry` is definitely an improvement.

**Comment by Mugen87** [comment]
BTW, PR looks good :wink:

**Comment by abelnation** [comment]
@mrdoob @Mugen87 what is the process for merging PR's?  does the author merge when it get's the thumbs up? or does some primary other contributor take care of merging the pr's?

**Comment by WestLangley** [comment]
@abelnation The merging is done by @mrdoob if he approves. Some others have authority, but usually it is he.

**Comment by abelnation** [comment]
Ok.  I addressed uv mapping fix separately in #8830.

**Comment by mrdoob** [comment]
Nice PR indeed!

**Comment by mrdoob** [comment]
Many thanks!

**Pull request merged**
