### PR TITLE
NodeMaterial in core 1/2 - isolate light system from the parameterized materials

### PR DESCRIPTION
**Pull request by sunag**
Is need isolate light system from the parameterized materials to implement material-agnostic is too the first step to replace the current material system to node based.

`lights_template` is now seprated in three parts:

to the legacy version:

1. `lights_fragment` - light system begin
2. `lights_maps_fragment` - parameterized materials (phong, standard *extended)
3. `lights_apply_fragment` - light system ends

to the node based version, e.g:

1. `lights_fragment` - light system begin
2. `NodeLight` or any node for `environment` 
3. `lights_apply_fragment` - light system ends

I add too `lights_template` to `Three.Legacy`:

```javascript
ShaderChunk.lights_template = ShaderChunk.lights_fragment + ShaderChunk.lights_maps_fragment + ShaderChunk.lights_apply_fragment;
```

/ping @WestLangley

### CODE REVIEW

**Comment by WestLangley** [comment]
@bhouston The ultimate goal here is to make the renderer material-agnostic. The approach is to make the materials node-based. @sunag is having a go at this. This PR is a first step.

I do not see a problem with this PR, since it can be easily reverted if there is a problem, and new files can always be renamed. Your thoughts?

**Comment by sunag** [comment]
Thoughts?

**Comment by bhouston** [comment]
I am of the opinion that the node material should always use either phong or physical/standard as a base.  The nodes should just be used for dynamically filling in the colors into the slots already provided by phong/physical/standard.

Thus what I would do is to separate out the fulfilling of the material structure to either be fixed function or use the node-based material.  Thus I wouldn't change the phong or the physical light templates, but rather the stuff just before them.

I think you do not want to change BRDFs (e.g. phong/physical), rather just the parameters to them.

**Comment by sunag** [comment]
> I think you do not want to change BRDFs (e.g. phong/physical), rather just the parameters to them.

The idea is the same. The problem is that `WebGLRenderer` uses material properties for example `mtl.envMap` to add `varys` and `uniforms` and this is incompatible.

All `USE_`... definitions must be done automatically with nodes. This is already integrated part in `NodeMaterial`
https://github.com/mrdoob/three.js/blob/949690710f25127869a60a3762b638feb0c60c0c/src/renderers/webgl/WebGLProgram.js#L337

It is accordingly non `light_template` (light shader system) should mix some slot input of a parameterized material, for example `USE_ENV`. but a empty area to add whatever you wish, e.g: `env map`, `light probe` and others custom environments nodes... The current `NodeMaterial ` already works this way.

After the node-based be the current material system we can remove `lights_maps_fragment` and `lights_physical_pars_fragment` but keep the `lights_fragment` and `lights_apply_fragment` and all BRDFs code.

It is necessary to convert all others materials to node-based in core: `MeshDistanceMaterial`, `MeshDepthMaterial`, `MeshNormalMaterial`...

All `refreshUniforms` and use of slots of parameterized to add `varys` must be removed to avoid holes.
https://github.com/mrdoob/three.js/blob/1b1806eb83cb783bbe62b6b1db9aab92b1db1056/src/renderers/WebGLRenderer.js#L1792

https://github.com/mrdoob/three.js/blob/1b1806eb83cb783bbe62b6b1db9aab92b1db1056/src/renderers/WebGLRenderer.js#L1679

Of all changes this PR is less impacting.

**Comment by sunag** [comment]
This is not definitive but I think it will be like this:

Files | Change
------------ | -------------
alphamap_fragment.glsl | Remove - build in NodeMaterial
alphamap_pars_fragment.glsl | Remove - build in NodeMaterial
alphatest_fragment.glsl | Remove - build in NodeMaterial
aomap_fragment.glsl | Removed - Code added in CustomShaderNode
begin_vertex.glsl | Keep
beginnormal_vertex.glsl | Keep
bsdfs.glsl | Keep
bumpmap_pars_fragment.glsl | Convert to node
clipping_planes_fragment.glsl | Keep
clipping_planes_pars_fragment.glsl | Keep
clipping_planes_pars_vertex.glsl | Keep
clipping_planes_vertex.glsl | Keep
color_fragment.glsl | Remove - build in NodeMaterial
color_pars_fragment.glsl | Remove - build in NodeMaterial
color_vertex.glsl | Remove - build in NodeMaterial
common.glsl | Keep
cube_uv_reflection_fragment.glsl | Keep with changes in renderer or convert to node
defaultnormal_vertex.glsl | Keep
displacementmap_pars_vertex.glsl | Remove - build in NodeMaterial
displacementmap_vertex.glsl | Remove - build in NodeMaterial
displacementmap_pars_vertex.glsl | Remove - build in NodeMaterial
displacementmap_vertex.glsl |  Remove - build in NodeMaterial
dithering_fragment.glsl |  Keep
dithering_pars_fragment.glsl |  Keep
emissivemap_fragment.glsl |  Remove - build in NodeMaterial
emissivemap_pars_fragment.glsl |  Remove - build in NodeMaterial
encodings_fragment.glsl |  Keep
encodings_pars_fragment.glsl | Keep
envmap_fragment.glsl |  Remove - build in NodeMaterial
envmap_pars_vertex.glsl |  Remove - build in NodeMaterial
envmap_vertex.glsl |  Remove - build in NodeMaterial
fog_fragment.glsl |  Keep
fog_pars_fragment.glsl |  Keep
fog_pars_vertex.glsl |  Keep
fog_vertex.glsl |  Keep
fog_fragment.glsl |  Keep
gradientmap_pars_fragment.glsl |  Remove - build in NodeMaterial
lightmap_fragment.glsl |  Remove - build in NodeMaterial
lightmap_pars_fragment.glsl |  Remove - build in NodeMaterial
lights_pars.glsl |  Keep with changes
lights_phong_fragment.glsl |  Keep
lights_phong_pars_fragment.glsl |  Keep
lights_physical_pars_fragment.glsl |  Keep
lights_physical_fragment.glsl |  Keep
lights_physical_pars_fragment.glsl | Keep
lights_template.glsl | Keep with changes, this PR
logdepthbuf_fragment.glsl | Keep
logdepthbuf_pars_fragment.glsl | Keep
logdepthbuf_pars_vertex.glsl | Keep
logdepthbuf_vertex.glsl | Keep
map_fragment.glsl | Remove - build in NodeMaterial
map_particle_fragment.glsl | Remove - build in NodeMaterial
map_particle_pars_fragment.glsl | Remove - build in NodeMaterial
metalnessmap_fragment.glsl | Remove - build in NodeMaterial
metalnessmap_pars_fragment.glsl | Remove - build in NodeMaterial
morphnormal_vertex.glsl | Keep
morphtarget_pars_vertex.glsl | Keep
morphtarget_vertex.glsl | Keep
normal_fragment.glsl | Remove - build in NodeMaterial
normalmap_pars_fragment.glsl | Convert to node
packing.glsl | Keep
premultiplied_alpha_fragment.glsl | Keep
project_vertex.glsl | Keep
roughnessmap_fragment.glsl | Remove - build in NodeMaterial
roughnessmap_pars_fragment.glsl | Remove - build in NodeMaterial
shadowmap_pars_fragment.glsl | Keep
shadowmap_pars_vertex.glsl | Keep
shadowmap_vertex.glsl | Keep
shadowmask_pars_fragment.glsl | Keep
skinbase_vertex.glsl | Keep
skinning_pars_vertex.glsl | Keep
skinning_vertex.glsl | Keep
skinnormal_vertex.glsl | Keep
specularmap_fragment.glsl | Remove - build in NodeMaterial
specularmap_pars_fragment.glsl | Remove - build in NodeMaterial
specularmap_fragment.glsl | Remove - build in NodeMaterial
tonemapping_fragment.glsl | Keep
tonemapping_pars_fragment.glsl | Keep 	 	
uv2_pars_fragment.glsl | Remove - build in NodeMaterial
uv2_pars_vertex.glsl | Remove - build in NodeMaterial
uv2_vertex.glsl | Remove - build in NodeMaterial
uv_pars_fragment.glsl | Remove - build in NodeMaterial
uv_pars_vertex.glsl| Remove - build in NodeMaterial
worldpos_vertex.glsl | Keep with changes

**Comment by WestLangley** [comment]
@sunag Major changes like this will not be merged until @mrdoob is ready to do so, and that can take some time. So, another approach you can consider is to just add an example that shows how to create `MeshStandardNodeMaterial` and `MeshStandardNodeMaterialExtended`, a modified version of the same material. This will not require any changes to the core library, but can serve as a first step... Just a thought...

**Comment by sunag** [comment]
@WestLangley Yeah! but anyway this change will be necessary otherwise I will have to rewrite a lot of code.

**Comment by sunag** [comment]
@WestLangley @bhouston @mrdoob I did not any change in behavior only in `webgl_materials_nodes` example but I fix this in other PR.

**Comment by sunag** [comment]
or even here if you wish?

**Comment by sunag** [comment]
> So, another approach you can consider is to just add an example that shows how to create MeshStandardNodeMaterial and MeshStandardNodeMaterialExtended, a modified version of the same material. This will not require any changes to the core library, but can serve as a first step... 

The reason I write a lot of code is related with this:

https://github.com/mrdoob/three.js/blob/35a26f178c523514673d992da1aece23c1cfca6e/src/renderers/webgl/WebGLPrograms.js#L141

This PR fix the "duplicated" use of `USE_ENVMAP` in `lights_template` and `lights_pars` for nodes and could reuse the native code with node-material proxy, e.g: `MeshStandardNodeMaterial` using the sames `properties names` of the current materials.

Example:

https://github.com/mrdoob/three.js/blob/eb15d8160d22720d1ee9f3a500b2fc80b373f6c7/examples/webgl_materials_nodes.html#L371

```javascript
mtl = new THREE.StandardNodeMaterial();
// ...
// in line bellow, this crash the shader because add USE_ENVMAP automatically if of prop envMap is used:
mtl.envMap = getTexture( "decalDiffuse" );
```

**Comment by sunag** [comment]
What do you think? I can make a new PR or do you have some other idea?

**Comment by WestLangley** [comment]
Sorry, I do not have any further suggestions at this time...

**Comment by bhouston** [comment]
I do support node materials being in core and replacing our current system as long as the root nodes are true BRDFs.  So if this is on the way to that goal, I support it.  @sunag has been a three.js contributor for a while and produces great code so I would trust him here.  I know how hard it is to get major changes accepted into Three.JS even when they are good ones, one has to fight for them.

**Comment by sunag** [comment]
@WestLangley @bhouston Thank you very much for the answers and support. 
I created a new PR https://github.com/mrdoob/three.js/pull/13277 more simplified and fix conflicts of this PR.

In parallel I am already converting NodeMaterial to ES6:
https://github.com/sunag/three.js/tree/90dev-nodes/src/nodes

**Pull request closed without merging**
