### PR TITLE
Nodes: TSL Support `return`, `continue` and `break`

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
There is currently no ways to interrupt a loop in TSL.

This PR adds `cond.continue()` and `cond.break()` and `cond.return()` methods.

Example usage:
```js
loop( 10, ( { i } ) => {

	i.greaterThan( 5 ).continue();

	position.addAssign( velocity );

} );
```

I wanted to also add standalones `Continue()`, `Break()` and `Return()` but it currently doesn't seem to work, not sure how to do this /cc @sunag 
```js
loop( 10, ( { i } ) => {

	If (i.greaterThan( 5 ), () => {
	
		Continue()
		position.addAssign( velocity );

	} )

} );
```

_This contribution is funded by [Utsubo](https://utsubo.com/)_

### CODE REVIEW

**Comment by sunag** [comment]
`DiscardNode` was created when we didn't yet have TLS functions with global stack control. I think now we can just use standalone functions, like your second example :) 

```js
loop( 10, ( { i } ) => {

	If (i.greaterThan( 5 ), () => {
	
		Continue();

	} )

} );
```

Try this for `LoopContinueNode`:

```js
import Expression from '../code/ExpressionNode.js';
import { addNodeClass } from '../core/Node.js';
import { nodeObject } from '../shadernode/ShaderNode.js';

class LoopContinueNode extends Expression {

	constructor() {

		super( 'continue' );

	}

}

export default LoopContinueNode;

export const Continue = () => nodeObject( new LoopContinueNode() ).append();

addNodeClass( 'LoopContinueNode', LoopContinueNode );
```

**Comment by sunag** [comment]
For `return` I think it would be better `return` a value in `if` or `else` instead of use a specific node. i.e:

```js
tslFn( () => {
...
	If ( i.greaterThan( 5 ), () => {
	
		return i;

	} )
...
} );
```

**Comment by RenaudRohlinger** [comment]
@sunag for `return` I am referring to the `return;` statement in `GLSL` (basically like `discard;`). Also can you return a value in shaders in WebGL or WebGPU?

**Comment by sunag** [comment]
> @sunag for return I am referring to the return; statement in GLSL (basically like discard;). Also can you return a value in shaders in WebGL or WebGPU?

Yes, this would be an example of a statement for more common cases. Returning a `value` or `null` as `void` in some conditional could node system generate a `return` statement too.

It is important that `ReturnNode` is able to know what the current function is so that the value conversion can be carried out if necessary. I can be doing this if you wish

**Comment by LeviPesin** [comment]
> Try this for continue and break:

I think we can even simplify this to something like `const Continue = () => expression( 'continue' ).append()`, without even needing to create separate nodes for that.

**Pull request closed without merging**
