### PR TITLE
WebGPURenderer: Render Bundle + Shared Bind Group (WIP)

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/28347, https://github.com/mrdoob/three.js/pull/28705

**Description**

Shared Bind Groups bring great results in rendering optimization, together with the Render Bundle it is beautiful to see, it was so simple when setting `object3d.static=true` to get this result.

[Live example](https://raw.githack.com/sunag/three.js/dev-renderbundle/examples/webgpu_performance_renderbundle.html)

| no bundle | bundle | bundle + shared bind group |
| ------------- | ------------- | ------------- |
| 13.74ms | 10.81ms | 3.82ms |
| image | image | image |

### CODE REVIEW

**Comment by RenaudRohlinger** [comment]
Incredible. This PR marks a significant leap forward as the WebGPURenderer will now offers way better performance and a more modern API, surpassing the WebGLRenderer and aligning with the latest 3D API.

The UBO and static part will also benefit the WebGLBackend.

An interesting example could also be a split-screen camera view (3D Editor Tools UI / Mario Kart style) rendering the same scene multiple times from different camera angles.

**Comment by RenaudRohlinger** [comment]
Currently, one thing we need to figure out soon is how to update a specific object within the bundle.

Using something like `group.children[i].needsUpdate = true`  seems the most straightforward approach. This means we might need to keep a reference somewhere of all the meshes in the bundle within the Renderer so we can handle per-mesh updates and visibility state.


Additionally, we can later introduce frustum culling via indirect draw calls.

For example:
```js
_renderBundle( bundle, sceneRef, lightsNode ) {

if ( renderBundleNeedsUpdate ) {
  ...
} else {
  
  const renderContext = this._currentRenderContext;
  const renderContextData = this.backend.get( renderContext );
  
  for ( let i = 0, l = renderContextData.renderObjects.length; i < l; i ++ ) {
  
  const renderObject = renderContextData.renderObjects[ i ];
  
  if ( renderObject.object.needsUpdate === true) {
	// TODO 1: ... update object here if needed
  }
  if ( renderObject.object.visible !== prevVisible ) {
	// TODO 2: ... handle .visible flag here and maybe layers?
  }
  if ( renderObject.object.frustumCulled === true ) {
	// TODO 3: handle frustum culling via indirectDraw call in WebGPU and CPU in WebGL
  }
  
  this._nodes.updateForRender( renderObject, renderGroup );
  this._bindings.updateForRender( renderObject, renderGroup );
  
  this.backend.draw( renderObject, this.info );
  
  }
  
}

/cc @sunag

**Comment by nkallen** [comment]
Great progress -

Can I suggest: I prefer to avoid interfaces like this:

```
group.children[i].needsUpdate = true
```

Which are going to guarantee O(n) iterations

Write "batch" interfaces

```
group.setChildNeedsUpdate(i) 
group.needsUpdate(i)
group.needsUpdate(child[i])
```

(or whatever)

Batch operations allow for O(1) updates and more generally allow batching work performance optimizations. Of course there are many factors to balance in designing an API.

**Comment by sunag** [comment]
I think that when we have sub-children it is better to define the property on the object instead of on the group, since the renderer deals with RenderObject, it seems easier to implement it as well.

I am inclined to add object class terms to handle this, like `StaticGroup()` or `BundleGroup()` instead of `group.static` for example. `group.static` seems to limit the evolution of the API a bit in the sense that we will have different optimization techniques for dynamic and static objects in this context. I think `mesh.static` could be better inside a `BundleGroup` for example. /cc @mrdoob

**Comment by mrdoob** [comment]
`BundleGroup` sounds good to me 👍

**Comment by mrdoob** [comment]
@nkallen

> Write "batch" interfaces
> 
> ```
> group.setChildNeedsUpdate(i) 
> group.needsUpdate(i)
> group.needsUpdate(child[i])
> ```
> 
> (or whatever)

These are interesting...

How about:

```js
group.updateChildAt(i)
```

**Comment by sunag** [comment]
@RenaudRohlinger @aardgoose I think all related implementations have been done in separate PR. Thanks for the help 🙏

**Pull request closed without merging**
