### PR TITLE
Consider placing object_space_normal_map property on Texture instead of Material

### PR DESCRIPTION
**Pull request by pailhead**
I think this makes slightly more sense on `Texture` instead of `Material`. Needs to be tested, i'd also propose landing something like this with an example. 

Related:
https://github.com/mrdoob/three.js/pull/14239

objectspacenormalmap

In case of utmost urgency, this functionality can be achieved today by doing:

```javascript

myMesh.material.onBeforeCompile = shader => {

  shader.u_my_matrix = {value: myMesh.normalMatrix}
 
  shader.fragmentShader = `
  uniform mat3 u_my_matrix;
  ${ 
    shader.fragmentShader.replace('#include <normal_fragment_maps>', `
#ifdef USE_NORMALMAP
    normal = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0; // overrides both flatShading and attribute normals

		#ifdef FLIP_SIDED

			normal = - normal;

		#endif

		#ifdef DOUBLE_SIDED

			normal = normal * ( float( gl_FrontFacing ) * 2.0 - 1.0 );

		#endif

		normal = normalize( normalMatrix * normal );
#endif
    `) 
  }

}
```

### CODE REVIEW

**Comment by looeee** [comment]
>In case of utmost urgency, this functionality can be achieved today by doing

It could also be achieved today if @WestLangley's PR #14239 was merged.

**Comment by looeee** [comment]
Can you provide some more justification as to why you think this makes more sense on the Texture rather than the Material?

**Comment by pailhead** [comment]
>It could also be achieved today if @WestLangley's PR #14239 was merged.

Apologies, i meant to write:

>In case of utmost urgency, this functionality can be achieved today, without merging, by using `shader patching`.

>Can you provide some more justification as to why you think this makes more sense on the Texture rather than the Material?

- base `Material` class doesn't have to know about an arbitrary property of a sub class. There are 16 materials now, but imagine if there were 116, `Material.js` would just keep growing.
- `normal - map - space` the construct itself refers to a map, which in three.js is commonly associated with `Texture` (every `${something}Map` is a `Texture` object). This alone could justify having the "space" attribute on the `Texture`
- `space` in particular, refers to a property of the `Texture` - it's data. Whatever pixels are in the texture could belong to an albedo map and not be related to normal maps, but if the are, they can be in  one of the two spaces.

**Comment by Mugen87** [comment]
I'm not voting for this approach since properties like `normalScale`, `bumpScale`, `displacementScale` or `displacementBias` are also material properties. @WestLangley's PR is way more consistent in that regard. I also think that changing this strategy at the current maturity level of the library is not meaningful.

**Comment by pailhead** [comment]
>normalScale, bumpScale, displacementScale or displacementBias

None of these actually refer to the image data found in the maps though?  Those are all actually some values, this here is just a constant. 

Please consider comparing this property to something like `wrapS` or `magFilter`.

**Comment by looeee** [comment]
> There are 16 materials now but imagine if there were 116, Material.js would just keep growing

This is not going to happen so it's irrelevant. It's in the nature of class extension that sometimes things will be easier if the super class has properties that only _some_ subclasses use.  This is to be minimised, of course, but it's often the case that it can't be entirely avoided without making the code more complex.

> normal - map - space the construct itself refers to a map

> space in particular, refers to a property of the Texture - it's data

These are just nomenclature issues / semantics, not reasons why the property would be better on Texture. As @Mugen87  points out, doing it this way goes against all the other texture properties on materials. That means that it's inconsistent, which is by far the worst way of doing things in a codebase. 

> Those are all actually some values, this here is just a constant. 

A constant is just a value from a discrete, restricted set that's been given a special name to make it memorable. 

> some poor soul maintaining the docs

Over the last year or two, that's largely been me. Every so often I suggest that other people help, but for some reason they only want to get involved with "important" stuff like nit-picking and blocking other people's PRs 🙄

**Comment by pailhead** [comment]
>"important" stuff like nit-picking and blocking other people's PRs

I didn't mean it like that, i just was referring to the same sentence used twice. Imagine there was a typo, you'd have to fix it in two places. 

>These are just nomenclature issues / semantics, not reasons why the property would be better on Texture. As @Mugen87 points out, doing it this way goes against all the other texture properties on materials. That means that it's inconsistent, which is by far the worst way of doing things in a codebase.

I disagree with this. Changing this property triggers the whole shader to be recompiled into a different shader. Changing the value of `normalScale:Vector2` works with any provided texture without recompiling the shader.  

https://threejs.org/docs/#api/textures/Texture

List of possible properties it's in alignment with and not going against, up for debate:
```
mapping
wrapS
wrapT
magFilter
minFilter
anisotropy
format
type
//material ever uses only one of these:
offset
repeat
rotation
center
encoding
```

offset,repeat,rotation and center actually don't belong on the `Texture` since three's `Material` will only ever use one of them based on a priority list. If that somehow made it's way onto `Texture` i'd urge you to consider loosening the restrictions around this a little bit.

**Comment by pailhead** [comment]
```javascipt

var o = new Texture({ space: 'o' })
var t = new Texture()

var myMaterial = new Material()

myMaterial.normalMap = t  

myMaterial.normalMap = o //doesn't work
myMaterial.normalMapType = 'object' //redundant call, makes it work
```

**Comment by pailhead** [comment]
@looeee 

>Can you provide some more justification as to why you think this makes more sense on the Texture rather than the Material?

Did any of what i provided make sense?

**Comment by pailhead** [comment]
I'd advise not leaving this kind of stuff for another PR. 

Given that there are properties both on material and texture that apply to textures, i'd say that opens door to putting new ones in either of those places not just one.

If we do this now, there is no need to deprecate anything. **It could even work in both places, where the one on `Material` would be an override if you so desire.** 

The drawback i see from refactoring later is that this entire interface needs to be deprecated. It would have to be one giant PR tackling all of these props at once, with additional deprecation warnings `this thing is now on Texture`.

**Comment by mrdoob** [comment]
Opted for merging #14239 instead.

**Comment by mrdoob** [comment]
Thanks though!

**Pull request closed without merging**
