### PR TITLE
Add renderer parameter to GLTFExporter

### LINKED ISSUE #11692: Advanced audio with wad
Hello everyone. 
I'd like to use Wad for audio inside three.js (https://github.com/rserota/wad) instead of the default audio interface. 
Is this possible? How? 
I'm asking because I'd avoid to even just try without knowing and I'm a total noob with javascript in general. 
So thanks in advance for any help, greatly appreciated. 

Cheers.

### LINKED ISSUE #11962: 'Export GLTF' menu of Three.js editor does not work
##### Description of the problem 

I tried the 'Export GLTF' menu of Three.js Editor.

https://cdn.rawgit.com/mrdoob/three.js/dev/editor/index.html

[File] - [Export GLTF]

image

However, the following error occurs.

```js
GLTFExporter.js:29 
Uncaught TypeError: Cannot read property 'context' of undefined
    at THREE.GLTFExporter.parse (GLTFExporter.js:29)
    at UI.Row.<anonymous> (Menubar.File.js:188)
```

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 Intel(R) HD Graphics 520

### PR DESCRIPTION
**Pull request by fernandojsg**
Fixes #11962

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... This `renderer` dependency feels weird.

Considering that gl constants do not change, I think it would be better to create a map like in `GLTFLoader`.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L771-L791

Same thing for `WebGLUtils`...

**Comment by fernandojsg** [comment]
I have it like that in the beginning but I changed it to reuse the `WebGLUtils` class. For me it also looks strange that we need to keep the list of constants everywhere we use it instead of having a `WebGLUtils` or so we we could do the match. 
Maybe having the list of constants with it number directly instead of accessing the webgl context? Similar to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/WebGLConstants.js

Also please note that if the following iterations of the exporter we'll need the `renderer` to access the textures directly, transform them and read the pixels back to store within the file.

**Comment by mrdoob** [comment]
> Maybe having the list of constants with it number directly instead of accessing the webgl context? 

Sounds good to me.

> Also please note that if the following iterations of the exporter we'll need the `renderer` to access the textures directly, transform them and read the pixels back to store within the file.

Lets try to keep the exporters renderer agnostic until is just not possible.

**Comment by fernandojsg** [comment]
Ok, I'll close it and create another PR with the proposed changes

**Pull request closed without merging**
