### PR TITLE
SimplifyModifier: Move to BufferGeometry.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

`SimplifyModifier` no longer relies on `Geometry`. The modifier now has a dependency to `BufferGeometryUtils`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev2/examples/webgl_modifier_simplifier.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
I had a look at `SubdivisionModifier` today and it's tricky to honor texture coordinates when using `BufferGeometry`.

The problem is the algorithm assumes vertices are merged. And this is possible with `Geometry` even if texture coordinates a different for two or more identical vertices. However, this does not work when performing the merge with `BufferGeometry` since _all_ vertex data (normals, colors, uvs) have to match.

Since you can only use `BufferGeometryUtils.merge()` for an efficient merge when dropping all other vertex information, a conversion to `BufferGeometry` only works if we remove features from the modifier.

**Comment by mrdoob** [comment]
Thanks for taking a look 🙏

Since `SubdivisionModifier` never got to work properly for `Geometry` either, what do you think about just removing it?

**Comment by Mugen87** [comment]
Even better! 😊

**Comment by mrdoob** [comment]
Lets do that then! 🙌

**Comment by Mugen87** [comment]
I'll make a PR.

**Pull request merged**
