### PR TITLE
VTKLoader: fix POLYDATA comparison failing with unicode character

### PR DESCRIPTION
**Pull request by DavidPeicho**
* Fixes parsing failing on files saved with CRLF

The comparison:
```javascript
if ( dataset !== 'POLYDATA' ) throw new Error( 'Unsupported DATASET type: ' + dataset );
```
was failing when `line` had a unicode character. So, if your file is saved with CRLF, this comparison will fail, even though the `dataset` variable has the value `POLYDATA`.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by DavidPeicho** [comment]
@Mugen87 Do we need to change the non-ES6 module too? I just saw there is a duplicated VTKLoader

**Comment by Mugen87** [comment]
Perfect! Otherwise @mrdoob or myself run the modularization script (`node utils/modularize.js`) from time to time on `dev`.

**Comment by DavidPeicho** [comment]
Okay great! Didn't know about this script :)

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
