### PR TITLE
Fix .shadowCameraVisible warning

### PR DESCRIPTION
**Pull request by liammagee**
A simple fix for the .shadowCameraVisible warning.

### CODE REVIEW

**Comment by mrdoob** [comment]
Oh wait, I guess it should be `new THREE.CameraHelper( light.shadow.camera )` instead?

**Comment by WestLangley** [comment]
Yes.
```javascript
light.shadowCameraHelper = new THREE.CameraHelper( light.shadow.camera );
scene.add( light.shadowCameraHelper );
```

**Comment by mrdoob** [comment]
Fixed. Thanks guys!

**Comment by unphased** [comment]
this doesnt seem to work? I cant make the shadow camera frustum appear.

**Pull request closed without merging**
