### PR TITLE
Ignore case on name match

### PR DESCRIPTION
**Pull request by leitzler**
Ignore case on name match

### CODE REVIEW

**Comment by leitzler** [comment]
Proposal fix for #7639. Note that I haven't tested if this will help the OP.

**Comment by mrdoob** [comment]
@Fabrice3D does this solve the issue?

**Comment by Fabrice3D** [comment]
yes, all fine when engine doesn't speak klingon :)

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by Fabrice3D** [comment]
ou elcome!

**Comment by mrdoob** [comment]
ehe

**Comment by Fabrice3D** [comment]
looks like it works now :)
Just needed to invert some z en uvs to fit away orientation to your baby.
this shows a quick in app lightmaps rendering + the export to r73 using buffgeoms with the new parser.
All objects have secondary uvs, the stuff i missed for so long !

whohoo :)

Side question, hows your design/logo going? Would be nice to have one…

Cheers,
Fabrice

**Pull request merged**
