### PR TITLE
Iterable vectors

### PR DESCRIPTION
**Pull request by ghost**
**Description**

All vectors (`Vector2`, `Vector3` and `Vector4`) are now iterable.

```js
const vec = new THREE.Vector3(5,5.7,8);

Math.min(...vec.toArray());//before

Math.min(...vec);//after
```

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]
It seems the browser support for this syntax is well enough to give it a try. Builds do work and our eslint setup has no problems with this code, too.

**Comment by Mugen87** [comment]
Out of curiosity: How does Babel process such generators? Is it possible to produce ES5 builds with this syntax?

**Comment by Mugen87** [comment]
That is an important question since there are `three.js` users which require ES5. And since we use generators the first time in the core, we should clarify this question.

**Comment by B3epBo0p** [comment]
@Mugen87 Hey, thanks for the review. I just checked and it uses apply.

before babel:
```js
const ar = [1, "owo", {"a":"letter"}];

console.log(...ar);
```
after babel:
```js
"use strict";

var _console;

var ar = [1, "owo", { "a": "letter" }];

(_console = console).log.apply(_console, ar);
```

**Comment by B3epBo0p** [comment]
Hey, that is an important question, thanks for the inquiry. A plugin is required for it to work with ES5, it's called [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime). I tested a class with a custom iterator and destructuring it worked as expected.

**Comment by donmccurdy** [comment]
It appears that `regenerator-runtime` and `@babel/runtime` are meant to be used as _production_ `dependencies` of a library like three.js; they are not `devDependencies` like most of the Babel toolchain. Currently three.js has no production dependencies, so I think it may be better to wait for features like this until after IE11 end-of-life.

**Comment by looeee** [comment]
>  it may be better to wait for features like this until after IE11 end-of-life.

Would adding this code break things for ES5 users even if they don't use it?

**Comment by Mugen87** [comment]
I would expect that IE11 is not able to parse JS code with generators. It would be a syntax error.

**Comment by mrdoob** [comment]
I think at this point we no longer support IE11 but I do worry about bundlers. Do bundlers support this well?

**Comment by donmccurdy** [comment]
[Browserify](https://browserify.org/) works fine with them, so I'd expect newer bundlers like Webpack, Parcel, and Rollup to be OK as well. They are an ES6 feature, so not actually all that new.

**Comment by mrdoob** [comment]
Alright, lets see what happens 🤞

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
