### PR TITLE
Updated Shadow docs

### PR DESCRIPTION
**Pull request by looeee**
Added descriptions and example code for DirectionalLightShadow, LightShadow, SpotLightShadow

### CODE REVIEW

**Comment by looeee** [comment]
One thing I'm unclear on is what exactly the LightShadow.radius does - something to do with the bias?

@mrdoob I think you added that?

**Comment by looeee** [comment]
Digging a bit, deeper, it looks like the radius is for use with PCSShadows, which I don't think have been implemented yet. Is that correct?

**Comment by mrdoob** [comment]
It's a hacky way of producing blurry-ish shadows...

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl#L77-L80

**Comment by looeee** [comment]
@mrdoob how does that look?

**Comment by mrdoob** [comment]
Looks good! 👌

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
