### PR TITLE
OBJ/MTL Loaders and Example: add support for chaining

### PR DESCRIPTION
**Pull request by WestLangley**

### CODE REVIEW

**Comment by WestLangley** [comment]
I was not able to figure out how to update the return values for these methods in the docs. Clearly, I am missing something...

**Comment by WestLangley** [comment]
Can we agree on a consistent pattern to follow in the docs -- or do you not feel it matters?

I am partial to the one I used in this PR, which I have seen used elsewhere in the examples.

```javascript
new THREE.MTLLoader()
	.setPath( 'models/obj/male02/' )
	.load( 'male02_dds.mtl', function ( materials ) {

		materials.preload();

		new THREE.OBJLoader()
			.setMaterials( materials )
			.setPath( 'models/obj/male02/' )
			.load( 'male02.obj', function ( object ) {

				object.position.y = - 95;
				scene.add( object );

			}, onProgress, onError );

	} );
```

**Comment by donmccurdy** [comment]
> I was not able to figure out how to update the return values for these methods in the docs. Clearly, I am missing something...

For example:

```html
<h3>[method:MTLLoader setTexturePath]( [param:String path] )</h3>
```

Maybe `method:this` would be clearer, and we add `this` to the blacklist in `page.js` so it doesn't get a hyperlink, but I don't see that syntax anywhere in the docs currently.

**Comment by WestLangley** [comment]
>Maybe `method:this` would be clearer

Yes. I think it would be.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Should we ensure that all loaders support the chaining pattern above -- and modify the examples to use it?

**Comment by mrdoob** [comment]
Yeah. That sounds good to me. Consistency 👌

**Pull request merged**
