### PR TITLE
Editor: Make editor parameter of Command class mandatory.

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/pull/13982#issuecomment-391478027

It's now necessary to pass a reference to the editor instance to each command. In this way, the current hack in [History.js](https://github.com/mrdoob/three.js/blob/bffb09dbeb1f97e86c3164ff6dbde6974efc48ac/editor/js/History.js#L19) is not necessary anymore.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by nicrizzo** [comment]
SetColorCommand, line 16:
I think should be Command.call( this, editor ) instead of Command.call( editor, this )
(this part needs tests).
Best regards,
    Nicola

**Comment by Mugen87** [comment]
@nicrizzo Thanks, fixed!

**Pull request merged**
