### PR TITLE
Addons: Add `TRAAPassNode`.

### LINKED ISSUE #14050: Temporal Reprojection Anti-Aliasing (TRAA)
This is the method used by DICE's latest work as well as UE4.

There are two methods of doing this.

The first and simpler approach is to just use the delta camera transform to figure out the velocity vectors from the world positions.

The more advanced method is to render a velocity field for each object that also incorporates the camera transform, this allows capturing the object velocity of moving objects and the sub-object velocities of deforming objects (such as morphs and skins.)  I would slowly build up to the more complex version of this.

The main implementation that people use is this one: https://github.com/playdeadgames/temporal

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #14050.
Related issue: #29295.

**Description**

This PR rewrites `TAARenderPass` as `TRAAPassNode` for `WebGPURenderer`.

It is now a full TRAA approach meaning it uses reprojection based on a velocity pass. `TRAAPassNode` also implements color clamping based on neighborhood sampling as well as flicker reduction based on luminance weighing. The implementation could be further enhanced e.g. by variance clipping, subpixel sampling or post sharpening but for now it's a good start.
 
There are some open issues:

- ~~WebGL is not supported yet since the pass needs the ability to copy between render targets. A few days ago @gkjohnson coincidentally filed the respective issue: #29612.~~
- Like any other TRAA implementation, `TRAAPassNode` uses jitter to produce a frame with a slight offset which is used for accumulation. However, the jitter should _only_ affect the beauty pass. Right now, the pass injects a non-modified projection matrix into `VelocityNode` to get accurate results. However, depth and any other additional MRT output should not receive jitter as well.

To solve 2, one solution would be an unjittered pre-pass for velocity, depth, normals etc.. The beauty is then produced with a separate pass that incorporates the jitter. That means however only beauty will receive the AA, depth and normals not. I'm not sure how other engines handle this aspect but I think it would be one way to go.

### CODE REVIEW

**Comment by sunag** [comment]
> MRT support is not complete. TRAAPassNode uses MRT to produce the beauty and velocity pass but it does not honor any existing MRT settings from the app. So it's not possible e.g. to render normal or metalness data yet.

Hmm.. could you give me an example?

**Comment by Mugen87** [comment]
If you want to use TRAA for anti-aliasing and afterwards AO, you would do this on app level:
``js
const scenePass = traaPass( scene, camera );
scenePass.setMRT( mrt( {
    output: output,
    normal: transformedNormalView
} ) );

const scenePassNormal = scenePass.getTextureNode( 'normal' );
const scenePassDepth = scenePass.getTextureNode( 'depth' );

aoPass = ao( scenePassDepth, scenePassNormal, camera );
```
You get a runtime error when trying to use the normal pass since it isn't produced by `TRAAPassNode`. It overwrites the MRT setting via `renderer.setMRT()`. 

Using `scenePassDepth` works but it has a jitter right now.

**Comment by Mugen87** [comment]
I have refactored the MRT handling a bit so `TRAAPassNode` is now more similar to `SSAAPassNode`. Meaning it has no internal MRT setting anymore but uses the one from the app. 

However, because of the intermediate sample render target that gets a jitter applied, the result isn't correct. We can't use the same approach like in `SSAAPassNode` where we resolve all targets via blending. I guess we need two passes like mentioned above:

- Use an overwrite material to render the original MRT setup without jitter (prepass).
- Render beauty and depth with jitter (this depth is only need in the next step).
- Resolve and copy the result into `output`.

I've implemented this via https://github.com/mrdoob/three.js/pull/29636/commits/172c2eeabc446facc53fb3f7f6dd134ba18e7009 but unfortunately, I get a `Uncaught RangeError: Maximum call stack size exceeded` runtime error in `updateBefore()`.

**Comment by Mugen87** [comment]
Reverting the prepass approach for now. I have the feeling we need a different approach like configuring what MRT outputs should be affected jitter and which not. In this way, we would not need any updates to `VelocityNode`.

**Comment by Mugen87** [comment]
I'll go ahead and merge since adding full MRT support might take a while until we figure out a solution. In the meanwhile, `TRAAPassNode` works in WebGPU and WebGL so it can already be included in certain FX setups.

**Pull request merged**
