### PR TITLE
Small postprocessing cleanups

### PR DESCRIPTION
**Pull request by Oletus**
This improves handling of render target sizes in the current EffectComposer.

### CODE REVIEW

**Comment by Mugen87** [comment]
I think it's a good idea if `EffectComposer` managed its size as a property and does not immediately bypass it to render targets or passes. In this context, it would be great if you find a way so the composer handles the pixel ratio more consistently than before, see #14340

`WebGLRenderer.getDrawingBufferSize()` regards the pixel ratio so initial render targets are sized correctly according to the renderer settings. But since `EffectComposer` has no concept of `pixelRatio`, `EffectComposer.setSize()` behaves a bit unexpected. If an app sets the size like in the following listing, the sizes of the renderer and the effect composer do not match anymore if the pixel ratio is greater than 1.
```js
renderer.setSize( width, height );
composer.setSize( width, height );
```
Normally you would expect both methods do the same but that is currently not the case. You can see the problem with one of the basic post processing examples:

https://threejs.org/examples/webgl_postprocessing

**Comment by Oletus** [comment]
Agreed that it would be nice to unify WebGLRenderer and EffectComposer behavior when it comes to setSize, but since this changes the behaviour of an existing API I'd rather do that as a part of moving to a new incompatible version of EffectComposer, see #15671

**Comment by Mugen87** [comment]
> but since this changes the behaviour of an existing API I'd rather do that as a part of moving to a new incompatible version of EffectComposer

I would classify the issue with the pixel ratio as a bug that should be fixed in the existing API.

**Comment by Oletus** [comment]
A lot of this is outdated - will do a new pull request with just the parts that are needed.

**Pull request closed without merging**
