### PR TITLE
ConvexGeometry: use flat vertex normals

### PR DESCRIPTION
**Pull request by WestLangley**
As discussed in #9220.

### CODE REVIEW

**Comment by WestLangley** [comment]
http://threejsworker.com/api/pullrequests/9221/examples/webgl_geometry_convex.html

What improvement does this example need?

**Comment by mrdoob** [comment]
> What improvement does this example need?

Hmmm, maybe it would be nice to see the points (using `THREE.Points`) superimposed to the resulting geometry.

**Comment by WestLangley** [comment]
OK. A single mesh would be sufficient?

**Comment by mrdoob** [comment]
Yep! 😊

**Comment by mrdoob** [comment]
Merging this one by now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
