### PR TITLE
Protoplanet fix

### PR DESCRIPTION
**Pull request by aardgoose**
Reduce the default number of particles for IE and Edge.
A work around for #11196.

@looeee Does this work for you?

### CODE REVIEW

**Comment by looeee** [comment]
I'll check tomorrow when I have a Windows machine.

**Comment by looeee** [comment]
Well, it's very slow to initialise (the browser window freezes for 5-10 seconds before showing anything), and it looks pretty bad compared to the higher particle example.

...but it no longer crashes either IE 11 or Edge so I guess that's a win! 😁 

On the other hand, once it has loaded you can still select higher amounts of debris which just causes the screen to go blank for a few seconds before resetting to a lower amount. Would it be possible to display a warning, or disable amounts >64 for these browsers?

**Comment by aardgoose** [comment]
Yes, I think a warning or disabling would be good (I had considered that.  If the failure is timeout based what is the maximum particle count possible may depend on performance of the user's CPU, so maybe hard limits aren't correct for all users. A warning might be better in that case.

It clearly shows deficiencies in the MS shader compiler/converter. Is it worth filing a bug against Edge?

Incidentally removing one of the texture2D() accesses from the nested loops allowed the code to compile with higher particle counts (although obviously breaking the code), Which indicates it is not just the loop count, but also dependant on the complexity of the code within the loop.

**Comment by looeee** [comment]
Probably this should be raised as a bug with Edge / I.E. though - in which case leaving the example as is while they investigate might be a good idea.

**Comment by aardgoose** [comment]
I've logged this with MS Issue #11827163.  I couldn't see anything similar on their public bug report tool,

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
