### PR TITLE
Adding advanced WebXR hands examples

### PR DESCRIPTION
**Pull request by felixtrz**
Adding 3 advanced WebXR hands examples:

Button Press Example - Using collision detection to trigger events when user press down button
Point-and-Click Example - Using a droplet-shaped target ray to point and click on buttons in the scene
Point-and-Drag Example - Using a droplet-shaped target ray to drag and drop objects in the scene

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good!

**Comment by mrdoob** [comment]
Instead of adding a custom ECS, what do you think about using [ECSY](https://github.com/ecsyjs/ecsy) instead?

**Comment by fe1ixz** [comment]
> Instead of adding a custom ECS, what do you think about using [ECSY](https://github.com/ecsyjs/ecsy) instead?

Great point! Let me update the examples to using ECSY.

**Comment by fe1ixz** [comment]
Updated the new hands examples with ECSY implementation @mrdoob

**Comment by fe1ixz** [comment]
changes merged in #21712

**Pull request closed without merging**
