### PR TITLE
Allows export of non-skinning Vertex Groups as BufferGeometry custom …

### PR DESCRIPTION
**Pull request by tschw**
…attributes.

### CODE REVIEW

**Comment by repsac** [comment]
At a glance it looks like a clean implementation but give me a bit to go over it.

**Comment by tschw** [comment]
It's alarming when something doesn't read easily... Pulled up, simplified and tested again :smile:

**Comment by repsac** [comment]
Reads easy enough. I am currently very limited on time so even it takes some effort to even set aside time for code review.

**Comment by tschw** [comment]
No pressure from my side - your response time on the other two PRs was like of a build tool! Just informing you that the code has changed (you may have pulled a local copy for testing). It should read quite a bit cleaner and is down to ~2/3 of its initial size, as for my excuse messing with the changeset on your desk.

**Comment by repsac** [comment]
This looks fine. Test scripts produced working scenes. Only hiccup I found wasn't with your commit (I'll address that).

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
