### PR TITLE
Fixed TextureCubeNode

### PR DESCRIPTION
**Pull request by DanielSturk**
TextureCubeNode references a non-existing function for decoding (`NodeBuilder.getTexelDecodingFunctionFromTexture`), making it unusable at the moment

### CODE REVIEW

**Comment by DanielSturk** [comment]
@sunag

**Comment by bhouston** [comment]
Thanks @DanielSturk !  This really helped us.

**Comment by sunag** [comment]
Thanks @DanielSturk nice example!

About the function, for some reason I forget to deploy this code `NodeBuilder.getTexelDecodingFunctionFromTexture` apparently, this fix too `render.gammaInput`.
```javascript
	getTexelDecodingFunctionFromTexture: function( code, texture ) {

		var gammaOverrideLinear = this.getTextureEncodingFromMap( texture, this.requires.gamma && ( this.renderer ? this.renderer.gammaInput : false ) )

		return this.getTexelDecodingFunction( code, gammaOverrideLinear );

	},

	getTexelDecodingFunction: function( value, encoding ) {

		var components = this.getEncodingComponents( encoding );

		return components[ 0 ] + 'ToLinear' + components[ 1 ].replace( 'value', value );

	},

	getTexelEncodingFunction: function( value, encoding ) {

		var components = this.getEncodingComponents( encoding );

		return 'LinearTo' + components[ 0 ] + components[ 1 ].replace( 'value', value );

	},

````

**Comment by sunag** [comment]
@DanielSturk it is possible I edit this PR together, maybe your me adding as a collaborator?

**Comment by bhouston** [comment]
@sunag just pull from @DanielSturk 's git repository modify this branch and make a new PR.

**Pull request merged**
