### PR TITLE
AnimationMixer: Move validate/optimization call, allow opt-out.

### PR DESCRIPTION
**Pull request by donmccurdy**
Allows developers to opt out of clip validation/optimization:

```js
clip.isValidated = true;
clip.isOptimized = true;
const action = mixer.clipAction( clip );
action.play();
```

Fixes https://github.com/mrdoob/three.js/issues/14336.

### CODE REVIEW

**Review by haroldiedema — APPROVED** [review]
Nice solution! 👍

**Comment by looeee** [comment]
Nice and simple solution, great! 😄

**Comment by takahirox** [comment]
Just two cents:

If I'm right, `KeyframeTrack` can be shared among two or more `AnimationClip`. In that case, redundant `.optimize/validata` for shared `KeyframeTrack` will still be executed. Ideally these flags should be in `KeyframeTrack` but yeah perhaps shared `KeyframeTrack` may be kinda rare.

**Review by Mugen87 — APPROVED** [review]

**Comment by takahirox** [comment]
Just two cents again:

IMO ideally `isValidated/isOptimized` flags should be in `KeyframeTrack`, not `AnimationClip`, for better modularity because what are validated/optimized are tracks, not clip itself. But yeah I know we don't wanna let users write

    for ( var i = 0; i < clip.tracks.length; i ++ ) {

        clip.tracks[ i ].isValidated  = true;
        clip.tracks[ i ].isOptimized  = true;

    }

for opt-out. `clip.isValidated/isOptimized = true` is much simpler API for users. So I'm worried about who should have the flags...

**Comment by donmccurdy** [comment]
I'm OK with putting flags either on the clip or on the track. Using the track does give more control, at the cost of a slightly more awkward API. I don't know of any loaders that reuse tracks across clips, so the practical difference seems small.. 

We could make it an argument like `clipAction( clip, root, needsValidateAndOptimize )` but I can't decide if that feels any better.

**Comment by haroldiedema** [comment]
> We could make it an argument like clipAction( clip, root, needsValidateAndOptimize ) but I can't decide if that feels any better.

This feels like the right approach, since the ClipActions is what users will be using for their animations anyway. This way there is only one interaction with the API necessary, instead of having to set the flags separately.

Let internal code then set the appropriate flags on the `KeyframeTrack` so the user doesn't have to bother with it.

**Comment by mrdoob** [comment]
Nice solution indeed! 👍👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
Sorry, I'm late.

I prefer moving the flags into tracks and having `clipAction( clip, root, needsValidateAndOptimize )` API.

**Comment by donmccurdy** [comment]
Reopened: https://github.com/mrdoob/three.js/pull/14385

**Pull request merged**
