### PR TITLE
WebGLProgram: detach shaders for deletion

### LINKED ISSUE #18401: WebGLProgram: shader memory not released throughout lifecycle.
Although `WebGLProgram` calls `deleteShader` for both vertex and fragment shader, the shaders aren't actually released until the actual program is deleted.

https://github.com/mrdoob/three.js/blob/2c52b411ee0ceb090533cb8f713c1b8afb73e550/src/renderers/webgl/WebGLProgram.js#L841-L842

This happens because `deleteShader` only marks the shaders as ready to delete, but they are only released after being detached from the program. In order to actually delete them from memory, we need to manually invoke `gl.detachShader( program, shader )`. This is preferable because, after linking the program, the shaders are no longer used/needed.

This behavior can be verified by calling `gl.getShaderParameter( shader, gl.DELETE_STATUS )` after the `deleteShader` call.

- On the current workflow, the result is `true`. Which means the shader still exists and is flagged for deletion.
- If we also detach the shader, we get a `INVALID_OPERATION` warning, as the shader we are trying to get the parameter from no longer exists.

Funnily enough, no other framework does this as well. I'm not sure if there's any underlying reason for this, or if it's just the case that everyone copied the code and never worried to check.

### PR DESCRIPTION
**Pull request by sciecode**
Fixes #18401

### CODE REVIEW

**Comment by Mugen87** [comment]
@kenrussell I remember there was some discussion in the past about the correct usage of `deleteShader()` and `detachShader()` (e.g. https://www.khronos.org/webgl/public-mailing-list/public_webgl/1412/msg00007.php). 

`three.js` already calls `deleteShader()` after linking the program. Do you think it's safe to call `detachShader()` before the actual delete is performed?

**Comment by sciecode** [comment]
My understanding is that both `deleteShader` and `detachShader` are unique and completely separated functionalities, and both are required conditions for the shader to be released from the GPU. 
So, the order shouldn't matter.

That is, of course, according to the WebGL specification. Whether or not browsers abide by that is a different story. During the tests I performed, that seemed to be the case for both Firefox and Chrome.

The reason why I chose to detach before deleting is purely semantic based. It makes sense to separate something before destroying it, not so much the other way around.

**Comment by sciecode** [comment]
@Mugen87 refer to [WebGL conformance test](https://github.com/KhronosGroup/WebGL/blob/cff43329aa6592c5e2de9fa6bb631d56acf22113/sdk/tests/conformance/programs/program-handling.html#L95-L99).

Firefox and Safari passes the test item, Chrome doesn't. But that's only because the test item is tightly related with the previous item, which is the one actually failing. 

In order to get a clear view of browser support, I've created the following [conformance test](https://jsfiddle.net/2ao91fgy/). No browser appears to have problems dealing with the program even after the shaders are detached and deleted, however Firefox doesn't seem to actually follow the specification. The shaders don't seem to get deleted even after delete/detach. This, however, is not a problem for us. Given that the current behavior is exactly the same.

**Comment by kenrussell** [comment]
@Mugen87 @sciecode sorry for the delay reviewing.

It is safe to detach and delete the shaders after linking the program. Chrome currently has a bug in conformance test https://www.khronos.org/registry/webgl/sdk/tests/conformance/programs/program-handling.html where it doesn't correctly preserve the old program during relinking. A fix was attempted for this but it was more complicated than expected. We'll get back to it soon, but there are higher priority issues right now. This conformance test failure is unrelated to detaching and deletion of shaders after a successful program link.

This pull request should be fine on all browsers and platforms and shouldn't destabilize Three.js - but of course it's best to do broad testing to confirm this.

**Comment by Mugen87** [comment]
Thanks for the review! In this case, I suggest to merge this PR at the beginning of the next `dev` cycle.

**Comment by kenrussell** [comment]
That's a good plan - would allow more time for broad testing.

**Comment by rotoglup** [comment]
> My understanding is that both `deleteShader` and `detachShader` are unique and completely separated functionalities, and both are required conditions for the shader to be released.

FWIW I've been working in memory leak sensitive scenarios for a long time, and I've never used `detachShader`. The GL ES 2 specification says : 
> When a program object is deleted, all shaderobjects attached to it are detached

Explicit calls can't hurt, but are not mandatory.

**Comment by sciecode** [comment]
Never said the issue was related with a memory leak or that detaching was mandatory. Refer to the first paragraph of the original issue.

We just have no need to keep the shaders in memory after linking the program. This can have significant memory impact depending on the number of active shaders.

**Comment by sciecode** [comment]
Should we merge PR and proceed with tests now?

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Seems like this is crashing iOS10. https://github.com/mrdoob/three.js/commit/9e072aa7f7ca5ec114df7b861af5b4111c0f1b9c#r38862505

**Comment by sciecode** [comment]
I was just taking a look at this because of #19267, it's ok to reverse.

**Comment by paulmasson** [comment]
FYI this PR does not crash iOS 13

**Comment by sciecode** [comment]
> FYI this PR does not crash iOS 13

Yeah, I noticed. I tested the PR on a iOS 13, that's probably why I didn't catch it.

Thanks for letting us know @paulmasson  👍

**Comment by mrdoob** [comment]
So it crashes iOS 9 and iOS 10 only?

**Pull request merged**
