### PR TITLE
add build closure to make use off the closure compiler.

### PR DESCRIPTION
**Pull request by gero3**
Adds a new build command to make use of google closure to minify the code after it is combined. 

To make use of it, just call `npm run build-closure` and it executes first the rollup command, then the google closure command. 

This solves #9524 partially. It would be better if google closure understood the es6 modules better.

### CODE REVIEW

**Comment by mrdoob** [comment]
Oh, but I merged your other PR that removed the closure stuff, so now it points to a missing .jar

**Comment by gero3** [comment]
I just added the closure compiler again to make the google closure compiler work again

**Comment by mrdoob** [comment]
Nice! How's the output? Smaller/Bigger than uglify?

**Comment by mrdoob** [comment]
I'll merge and check 😁

**Comment by mrdoob** [comment]
The resulting gzipped file it's just 600bytes smaller. However, somehow feels safer to keep using that.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hmm, there has been an interesting new development!
https://github.com/google/closure-compiler-js

**Comment by zz85** [comment]
@mrdoob - seems like it's GWT compiled version of the java closure compiler. https://developers.googleblog.com/2016/08/closure-compiler-in-javascript.html

**Pull request merged**
