### PR TITLE
OrbitControls: Add 3D cursor and limit to orbit camera target.

### PR DESCRIPTION
**Pull request by schwyzl**
Allows the user to limit the orbit controls target distance from a 3D cursor. 

My use case is having models load far from the origin. I want to move the camera to the object, then limit it's distance from that object. This change allows me to limit the scale of the scene (and camera frustum) to achieve the highest quality rendering.

*This contribution is funded by [Axial3D](https://axial3d.com)*

### CODE REVIEW

**Comment by Mugen87** [comment]
So this feature effectively limits panning operations, right? 

Do you mind modifying the following templated by using your custom version of `OrbitControls` so the new feature can be tested? 

https://jsfiddle.net/g3atw6k5/

**Comment by schwyzl** [comment]
@Mugen87 here is the updated fiddle: https://jsfiddle.net/oz0a69dn/22/

What you should see:

- You should see an additional red sphere positioned at 20 units along the x axis. 
- The camera should be focussed on this sphere. 
- You shouldn't be able to move the target away from this sphere.

**Comment by Mugen87** [comment]
Users wanted to limit panning operations with `OrbitControls` multiple times in the past so I like the idea of having this as a feature in the class. Especially since it's already possible to limit orbiting and zooming/dollying.

The live example helped to understand the new code! I have just fixed the code style in `OrbitControls` and also move the clamping a few lines further up. Does it look good to you?

**Comment by schwyzl** [comment]
Yep, looks good, thanks

**Pull request merged**
