### PR TITLE
LDrawLoader: Fix filename formatting to support Windows PC

### PR DESCRIPTION
**Pull request by lk-lkaz**
Fixed filename formatting to support Windows PC file paths separated by "\\".

issue:
I made a packed mpd file on Windows PC using "three.js/utils/packLDrawModel.js".
However, the mpd file cannot be loaded because of these formatting issues.

### CODE REVIEW

**Review by yomboprime — COMMENTED** [review]
Seems correct to me. Only thing left is to update the 'jsm' too.
But, the packing utility already converts ```\``` to ```/``` with the same regular expression ```( /\\/g, '/' )```, so I don't understand fully why this is needed.

**Comment by lk-lkaz** [comment]
Thank you for reviewing. ;)
When I investigated, it was caused by "path.join()" of the packing utility. ( line 175 )
So, is it better to fix "packLDrawModel.js" instead?

Test code:
var prefix = "parts/";
var fileName = "aaa.ldr";
var objectPath = path.join( prefix, fileName );
console.log( objectPath );
--> "parts\\aaa.ldr"

( Environment: Windows 10, Japanese )

**Comment by mrdoob** [comment]
> So, is it better to fix "packLDrawModel.js" instead?

I think so 👍

**Comment by lk-lkaz** [comment]
OK ;)
I'll try to fix "packLDrawModel.js" instead.

**Pull request closed without merging**
