### PR TITLE
Fix material for managing vertex colors

### PR DESCRIPTION
**Pull request by ghost**
When we tried to load a collada model with only the vertex colors (no material), it didn't take into account the vertex colors. The mesh had the default color from MeshLambertMaterial : 0xdddddd. We have fix this issue by adding the option vertexColors.

### CODE REVIEW

**Comment by mrdoob** [comment]
That doesn't seem like the right fix...

**Comment by csblo** [comment]
Can you detail your answer ? I've probably missing something.

**Comment by csblo** [comment]
Can you detail your answer ? I've probably missing something.

**Comment by mrdoob** [comment]
This is forcing vertexColors to all the objects. Even if they don't have vertex colors.

**Pull request closed without merging**
