### PR TITLE
Added dispose method to Scene.

### PR DESCRIPTION
**Pull request by cliffhall**
This method removes all objects and disposes geometry, materials, and textures from the scene.

### CODE REVIEW

**Comment by WestLangley** [comment]
Actually, I thought we were looking for a `dispose()` method that can be applied to any `Object3D`, such as a loaded model and its children.
```
myObject.dispose();
```

Also, meshes can have many textures, not just maps -- they all would need to be disposed of. Meshes can also have an array of materials.

**Comment by cliffhall** [comment]
Ok, yeah that makes more sense, since Scene subclasses Object3D. I'm closing this PR and will move the method over to Object3D and also add the more exhaustive texture and material removal. Thanks for the guidance.

**Comment by cliffhall** [comment]
> Also, meshes can have many textures, not just maps -- they all would need to be disposed of. 
What properties are those textures stored in? 

> Meshes can also have an array of materials.
So Mesh.material can be an array or just one material?

**Comment by WestLangley** [comment]
We also already have `Object3D.remove( object )`, so you may want to consider decoupling removal and disposal. I am not sure of the best solution in that regard.

Also, to save you some trouble, we have not yet adopted the ES6 code style.

**Comment by cliffhall** [comment]
Thanks again, WestLangley. I'd already dropped my fat arrows after more review of the code and build process. And decoupling the remove from the dispose is easy enough, I can just make a removeAll method.

Here's what I'm looking at right now:

```
	removeAll: function() {
		this.traverse( function(object) {
			if (object && object.isObject3D) this.remove(object);
		});
	}
```
and

```
	dispose: function() {

		this.traverse( function( object ) {

			if ( object && object.isObject3D  ) {

				if ( object.geometry ) object.geometry.dispose();
				if ( object.material ) {
					if ( Array.isArray( object.material ) ) {
						object.material.forEach( function(material) { disposeObjectAndMaps(material); } );
					} else {
						disposeObjectAndMaps(object);
					}
				}
			}

			function disposeObjectAndMaps(object)
			{
				if ( object.map && object.map.isTexture ) object.map.dispose();
				if ( object.alphaMap && object.alphaMap.isTexture ) object.alphaMap.dispose();
				if ( object.lightMap && object.lightMap.isTexture ) object.lightMap.dispose();
				if ( object.bumpMap && object.bumpMap.isTexture ) object.bumpMap.dispose();
				if ( object.normalMap && object.normalMap.isTexture ) object.normalMap.dispose();
				if ( object.displacementMap && object.displacementMap.isTexture ) object.displacementMap.dispose();
				if ( object.roughnessMap && object.roughnessMap.isTexture ) object.roughnessMap.dispose();
				if ( object.metalnessMap && object.metalnessMap.isTexture ) object.metalnessMap.dispose();
				if ( object.emissiveMap && object.emissiveMap.isTexture ) object.emissiveMap.dispose();
				if ( object.specularMap && object.specularMap.isTexture ) object.specularMap.dispose();
				if ( object.envMap && object.envMap.isTexture ) object.envMap.dispose();
				if ( object.gradientMap && object.gradientMap.isTexture ) object.gradientMap.dispose();
				if ( object.dispose ) object.dispose();
			}

		});

```

Anything else you'd suggest?

**Comment by WestLangley** [comment]
You can look on stackoverflow for how others have solved this problem.

To test, 
1. load a model
2. render it
3. type renderer.info into the console
4. remove model from scene
5. dispose of it
6. type renderer.info into the console

Follow the three.js style guidelines when submitting your new PR.

**Pull request closed without merging**
