### PR TITLE
Fix RectAreaLightUniformsLib

### PR DESCRIPTION
**Pull request by zhoushijie163**

### CODE REVIEW

**Comment by mrdoob** [comment]
I guess that is a nicer implementation indeed 😁

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Actually, seems like it got broken...

screen shot 2017-02-27 at 09 59 48

http://rawgit.com/mrdoob/three.js/dev/examples/webgl_lights_rectarealight.html

**Comment by mrdoob** [comment]
Reverting for now...

**Comment by zhoushijie163** [comment]
https://github.com/mrdoob/three.js/pull/10907/commits/32cc99666cee5245b0ac0019cfd181979d0a8b98

**Pull request merged**
