### PR TITLE
New controls IndoorControls latest

### PR DESCRIPTION
**Pull request by wobushijiujiu**
related: #18908 #18877
Hello, everyone. I finally decided to use existing models instead of uploading new models to write the indoor controls example. 
I used this example [https://threejs.org/examples/?q=loader#webgl_loader_vrml](url) and replace the OrbitControls in it with the indoorControls for 'examples/misc_controls_indoor.html'.

### CODE REVIEW

**Comment by munrocket** [comment]
Thanks for simplifying your example, here [live version](https://rawcdn.githack.com/wobushijiujiu/three.js/b0d8077a7f3559e31d21a137d51661ae2eccc4f0/examples/misc_controls_indoor.html).
1. Sometimes when you quickly click on the buttons, they point in another place. Bug.
2. Probably better name misc_controls_checkpoints, this can be used in another situation?

**Comment by munrocket** [comment]
Thanks for simplifying your example, here [live version](https://rawcdn.githack.com/wobushijiujiu/three.js/b0d8077a7f3559e31d21a137d51661ae2eccc4f0/examples/misc_controls_indoor.html).
1. Sometimes when you quickly click on the buttons, they point in another place. Bug.
2. Probably can find better name, this can be used in another situation?

**Comment by munrocket** [comment]
About the code:

This not a `controls`, sorry, this is just an example that can be placed in showcase :|

**Comment by wobushijiujiu** [comment]
> 1. Sometimes when you quickly click on the buttons, they point in another place. Bug.
> 2. Probably can find better name, this can be used in another situation?

About operation mode, only in rooms you can move the position by clicking on the ground ( or stairs ).
About bugs, I cannot set the ground correctly for current model, so sometimes click on the roof or a horizontal place like handles will move camera as well.

**Comment by munrocket** [comment]
>in rooms you can move the position by clicking on the ground

I didn’t notice that it was possible to press on the floor. This can confuse somebody too, because initial position is outside and `ground control` not work there.

Steps to reproduce a bug:
* load page
* press `house1` button.
* when you almost flew into place, click `outside` button and try to return back.

**Comment by wobushijiujiu** [comment]
> Steps to reproduce a bug:

Thank you！ I will try to fix this bugs.

**Comment by munrocket** [comment]
Ok, seems bug fixed 👍.

I also suggest to:
* add a plane geometry to turn on outdoor navigation.
* rename example to 'floor control' /  'ground control'
* remove Chinese comments in source code
* add screenshot and description, in order to fix CI as suggested in report. `npm run make-screenshot <example_name>` works like charm now.



And just to be clear:
* I am not responsible for merging
* I am not reviewed your code fully

Sometimes PRs merging takes a long time ¯\_(ツ)_/¯
But your PR was already mentioned in discord by @mrdoob

**Comment by wobushijiujiu** [comment]
> 
> I also suggest to:
> 
I agree with your suggestion. And have ready for a long revision. ヾ(≧▽≦*)o
Just for the naming, at first I thought it would only be used indoors, but it's not fit well to calling  ground control because it can also run without ground, and I think it need more advice.

**Comment by munrocket** [comment]
I am not checked your code but result is cool! --> [GitHack](https://rawcdn.githack.com/wobushijiujiu/three.js/08a7ee2d8e40c928189ddc6ffc50188dcaf3294e/examples/misc_controls_indoor.html)

About CI... Do you taken a screenshot on a latest version of example? If not run this:
```shell
git reset HEAD^
git checkout .
npm run make-screenshot misc_controls_indoor
git add .
git commit -m "Examples: new misc_controls_indoor screenshot"
```
Because your repo is updated and we use CPU rendering, it's platform independent (as we think).

**Comment by Mugen87** [comment]
According to https://github.com/mrdoob/three.js/pull/21014#issue-550543213, it's better when `IndoorControls` is placed and maintained in a separate repository.

**Comment by LostAndDamned** [comment]
Hello, where can i find the repository of IndoorControls ?
Thanks in advance

**Comment by wobushijiujiu** [comment]
> Hello, where can i find the repository of IndoorControls ?
> Thanks in advance

Sorry, I've used it for a private project, you can email me if you need it. 
[wobushi.jiujiu@qq.com](url)

**Comment by wenxiaofang2022** [comment]
GitHub name: wenxiaofang2022
I send the email, but rejected.

**Pull request closed without merging**
