### PR TITLE
Examples: Modularized PMREM and added webgl2_loader_gltf

### PR DESCRIPTION
**Pull request by oparisy**
Following discussions with @donmccurdy, this PR provides a fully functional  version of the glTF loader example using modules from `examples/jsm`.

For this purpose I needed to include the `examples/js/PMREM` utils to the `modularize.js` script provided by #9562. This PR also provides `.d.ts` type definitions for those utilities.

Following @mrdoob advice, I named this example `webgl2_loader_gltf.html` since `webgl2` samples already use ES6 syntax. I chose to use a coding style closer to the `examples/jsm` files though (only import needed modules from `three.module.js`, no `THREE` prefix).

I also took special care to minimize differences with the original `webgl_loader_gltf.html`, so that they can be diffed for reference purpose.

I'd especially appreciate a code review on this coding style, and the provided type definitions.

### CODE REVIEW

**Comment by donmccurdy** [comment]
This should be using WebGL2Renderer rather than WebGLRenderer – I tried making that change but:

1. WebGL2Renderer is not currently exported by the ES module version (easy to fix)
2. WebGL2Renderer is not compatible with PMREMGenerator (??? to fix)

**Comment by mrdoob** [comment]
I'm hesitant about `WebGL2Renderer`. At this point, seems like it'll be easier to just make `WebGLRenderer` use WebGL 2.0 when available. If we're going to create a new renderer from scratch, maybe better to focus on `WebGPURenderer` instead.

**Comment by donmccurdy** [comment]
Ah ok. In the meantime, should we hide this example from the sidebar until it uses webgl2, or list it elsewhere?

**Comment by mrdoob** [comment]
Yeah, we should do some clean up next cycle.

**Comment by oparisy** [comment]
May I suggest an `ES6` or `JSM` prefix instead of `webgl2` then?

**Pull request merged**
