### PR TITLE
Resize the subsurface scatting thickness map.

### PR DESCRIPTION
**Pull request by daoshengmu**
I find the thickness map from `models/fbx/bunny_thickness.png` is too large (9 MB) and unnecessary. In the `webgl_materials_translucency.html` demo, it only uses its red channel. We should decrease the size to be 512 x 512 and convert it to be a `.jpg` because we don't need `alpha` (27 KB).

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
BTW, how are you generating the thickness map?

**Comment by daoshengmu** [comment]
The local thickness map is generated from DCC tools (3ds max). It chooses the same method that generates the Ambient Occulsion map.

**Comment by shaochun** [comment]
The thickness map is generated using Substance Painter. Used to create it using Arnold's AO with reversed normal option checked in Maya 2017, but the generated map doesn't look quite right.

SP gives a better result since it offers more params, and generates the map based on reversed normals.
Invert it should give the desired result.

**Comment by WestLangley** [comment]
It appears to me there is still something wrong with the map. It certainly is not a measure of "thickness" or "thinness".

screen shot 2018-04-28 at 12 21 29 pm

The bunny should show white (thinness) in the ears, but not on the body. Perhaps the map needs to be generated using different parameters...

**Comment by shaochun** [comment]
interesting. I'll take a look on this next week.

**Comment by daoshengmu** [comment]
screen shot 2018-05-01 at 3 10 29 pm
@WestLangley, @shaochun has helped update the thickness map to me. We can see the body is more darker and the thin part like ears, feet are white. This should be more correct.

**Comment by WestLangley** [comment]
Either is this not a good model for this technique, or the technique is limited, or both.

@mrdoob In any event, this PR can be merged. The depth map is no longer inverted, and is reduced in size.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
