### PR TITLE
Examples: Add possibility to set encoding for Reflector/Refractor.

### LINKED ISSUE #18699: Performance problem with reflector and new outputEncoding option
##### Description of the problem

If I add the line `renderer.outputEncoding = THREE.sRGBEncoding;` in the `webgl_mirror.html` example I get a massive performance problem. I posted this problem in the threejs discussion board here: https://discourse.threejs.org/t/performance-problem-with-outputencoding-and-reflection-in-linux/12901 The gist of it is that it seems that the shaders are recompiled every frame since the internal RenderTarget from Reflector does not use the correct output encoding. Mugens suggestion to add `encoding: sRGBEncoding` to the target parameters worked. 

I tested this only under Linux Ubuntu 19.10.

I guess the question is now, how to fix? Should the user be able to pass in the encoding? Should reflector detect it automatically? I guess automatically would be nice, but it would also be nice to specify the other parameters of renderTarget so I guess extending the constructor options object would also not be the worst idea...

If the extending parameter solution is chosen by the dev team I could provide a PullRequest for that - if desired. 

##### Three.js version

- [X ] Dev
- [ X] r113

##### Browser

- [] All of them
- [X ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [X ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #18699.

### CODE REVIEW

**Comment by WestLangley** [comment]
For the record, https://github.com/mrdoob/three.js/issues/18699#issuecomment-590089847.

**Comment by mrdoob** [comment]
> Fixed #18699.

Do you mind elaborating on how this fixes #18699?

**Comment by Mugen87** [comment]
If the user sets `WebGLRenderer.outputEncoding` to `THREE.sRGBEncoding`, it's now possible to do the same for `Reflector`/`Refractor`. Before this PR, it was necessary to copy the sources and apply this modification on app level.

It's like when rendering to a render target. In this case, it's also necessary to define the correct encoding.

**Comment by WestLangley** [comment]
As I [said](https://github.com/mrdoob/three.js/issues/18699#issuecomment-590089847), that is a work-around. Rendering should be in linear space for a proper workflow.

How does that "fix" the performance problem -- other than as a work-around in this particular use case?

**Comment by Mugen87** [comment]
> Rendering should be in linear space for a proper workflow.

I don't think this assumption is correct for 100% of all use cases.

> How does that "fix" the performance problem

It's because of this block:

https://github.com/mrdoob/three.js/blob/e9eda9bced1af8f014d0da83f4751bc02f220277/src/renderers/WebGLRenderer.js#L1694-L1698

The encoding is embedded in the shader programs such that a recompilation is necessary if the encoding changes. This can lead to a ping-pong effect which totally ruins the performance.

**Comment by WestLangley** [comment]
I understand all that, but there is a design problem.

It seems to me that telling the user to change the color space so as to prevent the renderer from recompiling every frame is not fixing the performance problem. It is sweeping the problem under the rug.

@mrdoob Rendering the scene to a render target in linear space (for a mirror, for example), and then rendering the scene to the default render target in sRGB space, will cause the materials to recompile every frame.

It is because of the code injection... A material has one shader -- not one shader for each color space.

**Pull request merged**
