### PR TITLE
added rotateOnWorldAxis method

### PR DESCRIPTION
**Pull request by sphaero**
As a convenience method. 

Simply use as the rotateOnAxis method

### CODE REVIEW

**Comment by WestLangley** [comment]
Actually, this was proposed several years ago, and for simplicity, a world rotation method was not deemed necessary -- only a local one -- which we added.

It remains to be seen if that is still the preference.

In any event, the proposed implementation here should now be implemented differently, but we can cross that bridge if we get to it.

**Comment by WestLangley** [comment]
@sphaero Did you test this on the latest version of three.js?

Also, I do not expect this will work if the object has a parent that is rotated.

**Comment by sphaero** [comment]
For a camera orientation it is often very helpful. It prevents following orientation of objects on every axis. Like done in the PointerLock example.

Perhaps it is better to specify what axis to rotate on. If null (undefined) it will be the worldaxis. Anyway, I haven't tested it on the dev branch. I just did it and it doesn't work. Looking into it

**Comment by WestLangley** [comment]
>I haven't tested it on the dev branch. I just did it and it doesn't work.

Closing for now. Repost if you desire.

**Pull request closed without merging**
