### PR TITLE
Matcap Example: added color option to gui

### PR DESCRIPTION
**Pull request by WestLangley**
Also added readme.txt with credits.

### CODE REVIEW

**Comment by WestLangley** [comment]
Live link
https://rawgit.com/westlangley/three.js/dev-matcap/examples/webgl_materials_matcap.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Great idea. I'll work on exr matcap support. In the mean time, we can keep what we have.

**Comment by WestLangley** [comment]
@mrdoob Unfortunately, few of those matcaps load because `EXRLoader`has some limitations.

1. the loader does not support ZIP_COMPRESSION
2. the loader does not support pixel type 32-bit FLOAT
3. the loader throws an error on `stringvector` (that is an easy fix, it appears)

/ping @richardmonette Any chance you would be interested in making those improvements?

**Pull request merged**
