### PR TITLE
Added Box3/Sphere intersection tests

### PR DESCRIPTION
**Pull request by Mugen87**
Ladies and Gentlemen! :wink:

I use the Sphere/AABB intersection test quite often in my 3D applications. Therefore, i have added to both prototypes (`THREE.Sphere` and `THREE.Box3`) new methods for this use case. 

Besides, i've renamed the method `intersectsSphere`to `isIntersectionSphere`, so the interfaces are more consistent.

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice! I wonder if we should, instead, rename all the `isIntersection*` to `intersects*` instead though.

**Comment by Mugen87** [comment]
I personally like to indicate with "is..." in the method name, that a boolean is the return value. But that's a matter of taste. The last math lib i've worked with name their intersection method just with `intersects*`.

[MathGeoLib, AABB.h](https://github.com/juj/MathGeoLib/blob/master/src/Geometry/AABB.h#L414)

**Comment by mrdoob** [comment]
@bhouston any particular reason why you named those methods `isIntersection*`?

**Comment by bhouston** [comment]
@mrdoob I have no preference here. :)  Either way is fine.

**Comment by mrdoob** [comment]
Will change 😊

**Comment by GGAlanSmithee** [comment]
Som random thoughts:

I think it makes the most sense to name methods that returns a conditional in a way so that they "flow" nicely in an if statement:

`if (sphere.isIntersectionSphere(sphere))` does not
`if (sphere.intersectsSphere(sphere))` does

I think this is the best that can be done in an untyped language such as JavaScript. In a statically typed language I think it makes sense to let the whole signature of a method be a part of its description, In other words, let the argument name describe what is being checked: `sphere.intersects(sphere)`

/end random rambling :)

**Pull request merged**
