### PR TITLE
SpriteNodeMaterial and example

### PR DESCRIPTION
**Pull request by sunag**
Finally news :blush:
https://github.com/mrdoob/three.js/issues/5876

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
How about replacing all these `THREE.ShaderChunk[ "project_vertex" ]` with `#include <project_vertex>`?

**Comment by sunag** [comment]
Only the `project_vertex` or all others `shaderchucks` too?

**Comment by mrdoob** [comment]
All of them 😇

**Pull request merged**
