### PR TITLE
Camera: Properly update world matrix prior to use

### PR DESCRIPTION
**Pull request by WestLangley**

### CODE REVIEW

**Comment by WestLangley** [comment]
@Mugen87 I _think_ this completes the remaining use cases. :-)

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@WestLangley What do you think about introducing default parameters to `updateWorldMatrix()`? I mean:
```js
updateWorldMatrix: function ( updateParents = true, updateChildren = false ) {
```
This seems to be a proper default for a world matrix update routine.

**Comment by WestLangley** [comment]
@Mugen87 

The method has _implied_ default values of `false` and `false`. I did that intentionally when I implemented the method.

If you would like default values specified _explicitly_, I would suggest:

```js
updateWorldMatrix: function ( updateParents = false, updateChildren = false ) {
```

I think @donmccurdy would be particularly happy with that decision.  :-)

This makes it clear that it is the _user's_ responsibility to traverse the tree based on the user's use case.

**Comment by DefinitelyMaybe** [comment]
> This makes it clear that it is the user's responsibility to traverse the tree based on the user's use case.

that sounds like the way to go IMO

**Comment by WestLangley** [comment]
Again, let's ensure the method returns the correct answer as a first step. We can improve it later.

**Review by donmccurdy — APPROVED** [review]

**Comment by WestLangley** [comment]
This PR is a follow-up to #19969.

**Comment by Mugen87** [comment]
@mrdoob Since #19969 was merged, this PR should go in, too. Unlike #20221, this PR only improves the _already existing_ world matrix computation.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
