### PR TITLE
Examples: Improve data type selection for env maps.

### LINKED ISSUE #22226: Transmission examples not working on Galaxy M30
**Describe the bug**

On Chrome on my android phone both transmission examples https://threejs.org/examples/?q=transmission seems to be loading a black page. With USB debugging I took the screen shot below of the error displayed.

**Screenshots**

transmission example

**Platform:**

 - Device: [ Mobile]
 - Samsung Galaxy M30 (does not support ARcore but webgl stuff runs fine )
 - OS: [ Android]
 - Browser: [Chrome]
 - Three.js version: [r131]

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #22226.

**Description**

see https://github.com/mrdoob/three.js/issues/22226#issuecomment-890312612.

### CODE REVIEW

**Comment by WestLangley** [comment]
```js
const dataType = renderer.extensions.has( 'OES_texture_float_linear' ) ? THREE.FloatType : THREE.HalfFloatType;
const loader = new RGBELoader().setDataType( dataType );
```
What is the support for half-float-linear as compared to float-linear?

**Comment by WestLangley** [comment]
Just set the default in the two loaders to `HalfFloatType` instead -- rather than all this.

**Comment by Mugen87** [comment]
> What is the support for half-float-linear as compared to float-linear?

I don't know. There was once a website that tracked such statistics (webglstats.com) but unfortunately it's down since quite a while.

> Just set the default in the two loaders to HalfFloatType instead -- rather than all this.

Even when changing the default, the examples will still be broken on certain devices. There is no way around to check for the extension in the example code. Or we always use `THREE.HalfFloatType` although that would mean we sacrifice potential hardware capabilities.

**Comment by WestLangley** [comment]
>Or we always use THREE.HalfFloatType

I would do that.

I don't think we sacrifice anything for the environment maps were are using or are typically used. The dynamic range is not great enough to require floats AFAIK. There is certainly no visual difference as far as I can tell.

>Even when changing the default, the examples will still be broken on certain devices.

I think what you are doing in the PR is not going to solve that.

I understand you would like to show the user how to user Float vs HalfFloat vs Unsigned, but I think best the solution here is to just set the default to Half.

**Comment by Mugen87** [comment]
I'm not feeling strong about both solutions so if @mrdoob agrees I change the default texture type in `RGBELoader` and `HDRCubeTextureLoader` and then remove the `setDataType()` call in the examples. Otherwise the current implementation can be merged.

**Comment by WestLangley** [comment]
If you don't want to lose all the work you put into rewriting these examples, I'd be happy if you just removed the `setDataType()` and changed the default in the loaders to `HalfType`.  :-) 

ref:  #22190

I am pretty sure that will be sufficient.

**Comment by Mugen87** [comment]
Okay, let's give this a try.

**Pull request closed without merging**
