### PR TITLE
Array length fixed

### PR DESCRIPTION
**Pull request by rfm1201**
The indexCount was rigth but the vertexCount was wrong. The squares on each plane (face) have common vertices

### CODE REVIEW

**Comment by Mugen87** [comment]
Nice improvement. I actually didn't see this in my initial commit.

**Comment by WestLangley** [comment]
Please check `CylinderGeometry`, and the others. Just in case...

**Comment by rfm1201** [comment]
I will check

**Comment by mrdoob** [comment]
Thanks!

**Comment by rfm1201** [comment]
The only thing that I can optimize is CylinderGeometry when the radius of one end is 0.
Place is reserved for the vertices and indexes of each end but the end with 0 radius will have no vertex and no index.
See https://github.com/mrdoob/three.js/pull/8713

**Pull request merged**
