### PR TITLE
Docs: Use a dark color theme for code snippets in dark mode

### PR DESCRIPTION
**Pull request by gkjohnson**
Updates the colors for the docs code snippets when using a dark color scheme. Here's a before and after:

image

[Current Docs Link](https://threejs.org/docs/#api/en/objects/SkinnedMesh), [PR Docs Link](https://raw.githack.com/gkjohnson/three.js/dark-code-docs/docs/index.html#api/en/objects/SkinnedMesh)

### CODE REVIEW

**Comment by Mugen87** [comment]
Looks awesome! 👍

**Review by Mugen87 — APPROVED** [review]
Tested offline since the styles were not applied correctly via githack.

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
The dark theme looks good for JS code but I've noticed today that HTML markup is a bit hard to read. Primarily the dark blue HTML tags:

image

Maybe a lighter color would be better?

**Comment by gkjohnson** [comment]
@Mugen87 Thanks for the catch! I'm out of the country for another week or so but I can look into picking more readable colors for html when I get back.

**Pull request merged**
