### PR TITLE
nodematerial r6

### PR DESCRIPTION
**Pull request by sunag**
New examples
- `triangle-blur`, `expression`, `reserved-keywords`, `custom-attribute`, `bump`, `blur`, `spherical-reflection`
  https://rawgit.com/sunag/three.js/master_r80/examples/webgl_materials_nodes.html
- `blur`
  https://rawgit.com/sunag/three.js/master_r80/examples/webgl_postprocessing_nodes.html
- `blur` option with `gui`
  https://rawgit.com/sunag/three.js/master_r80/examples/webgl_mirror_nodes.html

New features
- support to inline `expression` using `FunctionNode`
- support to `gammaInput`, `gammaOutput`, `tonemapping`, `premultiplied_alpha`, `indirectSpecular`
- support to `sample2D` input using `TextureNode`, `ScreenNode`, `MirrorNode`
- support to `sampleCube` input using `CubeTextureNode`
- support to `BufferAttribute` geometry using `AttributeNode`
- support to reserved keywords in `NodeFunction` global and local using `this.useKeywords` to active or not
- automatic `int <-> float` and `int <-> vectors` convertions
- interoperability `FunctionNode` keywords with `Nodes`
- new `ConstNode` usage mode: auto include

Changes
- renamed `BuilderNode` to `NodeBuilder`
- renamed `Node.updateAnimation` to `Node.updateFrame`
- renamed `Node.requestAttrib` to `Node.requestAttribs`
- renamed `Node.allow` to `Node.allows`

Fixes
- auto transparent
- fog
- spherical reflection
- `int` input in `FunctionCallNode`
- not create temp vars with `InputNode`
- others minors fixes

@mrdoob if possible not merge yet I have some improvements to make... :blush:

### CODE REVIEW

**Comment by mrdoob** [comment]
For easy checking...
https://rawgit.com/sunag/three.js/master_r80/examples/webgl_materials_nodes.html

**Comment by sunag** [comment]
@mrdoob Done! :sweat_smile: I update the description.

**Comment by mrdoob** [comment]
Looking really good! 😁

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
