### PR TITLE
WebGLRenderer: Don't automatically rebind in WebXR.

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Related issue: https://github.com/mrdoob/three.js/pull/26160#issuecomment-1751012842

**Description**

Manually binds to the layer render target at the end of the chain to work around misc. performance issues.

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
https://rawcdn.githack.com/CodyJasonBennett/three.js/test/manual-xr-resolve/examples/webxr_vr_postprocessing.html

**Comment by CodyJasonBennett** [comment]
https://rawcdn.githack.com/CodyJasonBennett/three.js/a7bd357c92e707262febe33e12d49b324e6c2cb8/examples/webxr_vr_postprocessing.html

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/26160#issuecomment-1751147396.

**Comment by Mugen87** [comment]
@CodyJasonBennett Thank you for pushing this topic forward! The revert is unfortunate but at least we know the bottlenecks now.

**Comment by otse** [comment]
Cody Jason Bennett, your post processing vr tests can render one frame before showing an hour glass.

**Pull request closed without merging**
