### PR TITLE
ObjLoader2Parser materials are not applied in worker

### LINKED ISSUE #17615: Materials not correctly applied by ObjLoader2Parallel (jsm)
##### Description of the problem

The OBJLoader2Parallel does not correctly apply given materials, added by calling addMaterials(materials) before loading, when using web workers (executeParallel = true) and falls back to default materials instead.

In WorkerRunner.js, **payload.materials** are applied to the corresponding instance of OBJLoader2Parser using ObjectManipulator.

https://github.com/mrdoob/three.js/blob/a84f4c469dd1b9414b45ff47da8433febc60bfdb/examples/jsm/loaders/obj2/worker/parallel/WorkerRunner.js#L52-L54

However, in order for the ObjectManipulator to call the appropriate method, which is setMaterials(payload.materials), the second argument (L53) should be an object with **materials** as key and **payload.materials** as value.

https://github.com/mrdoob/three.js/blob/a84f4c469dd1b9414b45ff47da8433febc60bfdb/examples/jsm/loaders/obj2/utils/ObjectManipulator.js#L14-L37

I would suggest to move **materials** (L193) to the **params** object above in OBJLoader2Parallel.js and remove L53 from WorkerRunner.js:

https://github.com/mrdoob/three.js/blob/a84f4c469dd1b9414b45ff47da8433febc60bfdb/examples/jsm/loaders/OBJLoader2Parallel.js#L185-L193

##### Three.js version

- [x] Dev
- [x] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by kaisalmen**
Fixes #17615 Material assignment is no properly done when Parser is run in worker.
Additionally, allow material override from OBJLoader2.addMaterials to MaterialHandler.addMaterials

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by kaisalmen** [comment]
One can observe you are currently synced to CEST! 😉

**Comment by mrdoob** [comment]
In Stockholm, extremely jet-lagged though 😅

**Comment by kaisalmen** [comment]
Saw your tweet yesterday. Have a good time and try visit a light bar against the jet lag. 😄

**Pull request merged**
