### PR TITLE
Make energyPreservation an optional parameter in ts

### PR DESCRIPTION
**Pull request by Oletus**

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by WestLangley** [comment]
Energy preservation should not be an option. Where is it anyway?

That is like having a "normals correct" option. Do you want your normals correct or incorrect? :/

**Comment by mrdoob** [comment]
> That is like having a "normals correct" option. Do you want your normals correct or incorrect? :/

Actually, this year I learned that sometimes people want their own (incorrect) normals...

But yes, sounds like we may want to get rid of the `energyPreservation` property?

**Comment by WestLangley** [comment]
`energyPreservation` is not a property of `MeshStandardMaterial`.

**Comment by mrdoob** [comment]
Fixed https://github.com/mrdoob/three.js/commit/2dfbb5dd546f64e9870c72a16813d15ac635cf7f

**Pull request merged**
