### PR TITLE
Added PCFSoftShadowMapFast for better looking shadows on low powered devices

### PR DESCRIPTION
**Pull request by IvoJager**
Proposed fix for #15577.

The solution has been working very well on mobile and Oculus Go in terms of performance gains and maintaining reasonable visual quality.

User testing on these devices indicated they did not notice difference between fast solution and "proper" PCFSoftShadowMap until it was pointed out.

### CODE REVIEW

**Comment by mrdoob** [comment]
I wouldn't mind just updating the current `SHADOWMAP_TYPE_PCF_SOFT`.

In #15577 you have a screenshot comparing `SHADOWMAP_TYPE_PCF` and `SHADOWMAP_TYPE_PCF_SOFT`. Do you have a screenshot comparing `SHADOWMAP_TYPE_PCF_SOFT` and `SHADOWMAP_TYPE_PCF_SOFT_FAST`?

**Comment by IvoJager** [comment]
Agree quality downgrade is too noticeable. However, upgrading the current SHADOWMAP_TYPE_PCF might be an option.

**Comment by Mugen87** [comment]
Please also update the docs. The new type should be noted at the [WebGLRenderer](https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer) page and [here](https://threejs.org/docs/index.html#api/en/constants/Renderer).

**Comment by IvoJager** [comment]
@Mugen87 Thank you for the pointers. I updated the docs update with the changes as proposed. Do let me know if you need anything else!

**Review by Mugen87 — APPROVED** [review]

**Comment by arpu** [comment]
@mrdoob  what is needed to get this merged?

**Comment by mrdoob** [comment]
Upgrading the current SHADOWMAP_TYPE_PCF sounds good to me 👌

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
