### PR TITLE
WebGPUPipelines: Improve reuse pipeline and ComputeNode dispose

### PR DESCRIPTION
**Pull request by sunag**
**Description**

Same thing that https://github.com/mrdoob/three.js/pull/26305 with pipelines.

### CODE REVIEW

**Comment by LeviPesin** [comment]
Why do we need `ComputeNode.needsUpdate`?

**Comment by danrossi** [comment]
Is it required to change/update pipelines during a loop ? It seems adding these during a loop chews cpu. Thanks for looking into it.

**Comment by sunag** [comment]
> Why do we need ComputeNode.needsUpdate?

To update the compute program if some node is changed, we should also add `dispose()`.

**Comment by sunag** [comment]
Thanks, @danrossi, I think it will work now. We will just do some additional testing.

**Pull request merged**
