### PR TITLE
Update FileLoader.js

### PR DESCRIPTION
**Pull request by kkruups**
Unless, I am missing something Safari Data URI handler code for ArrayBuffer and  Blob Cases not populating [response] with [data].
Added code which corrects issue (populates response accordingly).

### CODE REVIEW

**Comment by kkruups** [comment]
Submitted fix, assumes Blob or Uint8Array desired.  

In the else clause, If we just want to return the ArrayBuffer, then in submitted fix need to change **response = view** to  **_response = view.buffer_** in order to change Uint8Array back to an ArrayBuffer.

**Comment by richtr** [comment]
I see the bug but I _think_ we should return an `ArrayBuffer` object. i.e. change `response = view.buffer` since the requested `responseType` is "arraybuffer".

**Comment by richtr** [comment]
It also seems like we could change this:

```
response = new ArrayBuffer( data.length );

var view = new Uint8Array( response );
```

to this:

```
var view = new Uint8Array( data.length );
```

**Comment by richtr** [comment]
Since you're making changes we _could_ also clarify this comment in the code:

    // Wait for next browser tick

to:

   // Wait for next browser tick like standard XMLHttpRequest load event dispatching does

**Pull request closed without merging**
