### PR TITLE
Nodes: Add anaglyph and parallax barrier pass nodes.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: #29173

**Description**

Adds pass nodes for anaglyph and parallax barrier effects. Instead of creating an example per node class, the effects are selectable in `webgpu_display_stereo`.

### CODE REVIEW

**Comment by Mugen87** [comment]
I'm not sure why `webgpu_backdrop_water` fails with this PR. AFAICS, the PR does not touch related logic...

**Comment by cmhhelgeson** [comment]
Would it make sense to collapse these classes into a shared StereoPassNode or class? It seems like there's lots of shared functionality between anaglyph and parallax?

**Comment by Mugen87** [comment]
There is already `StereoPassNode` but it works differently than `AnaglyphPassNode` and `ParallaxBarrierPassNode`. So it would be required to name a shared module differently. 

This kind of optimization is something that I would consider in a subsequent PR though.

**Comment by Mugen87** [comment]
I've updated the screenshot for `webgpu_backdrop_water` and it seems there is some sort of timing issue. In the new screenshot, the spheres are at different positions. Not sure why this happens. If this is somehow related to the latest performance improvements, I wonder why the CI did not fail earlier...

**Comment by sunag** [comment]
> I've updated the screenshot for webgpu_backdrop_water and it seems there is some sort of timing issue. In the new screenshot, the spheres are at different positions. Not sure why this happens. If this is somehow related to the latest performance improvements, I wonder why the CI did not fail earlier...

Thanks @Mugen87, I also didn't understand exactly what happened, but it's good to see it working again.

**Comment by mrdoob** [comment]
Hmm... How come we're adding so many thing to `src`? Shouldn't these nodes be addons?

**Comment by Mugen87** [comment]
I think it was some sort of "unspoken agreement" to add node classes in the core. We should establish a policy like in https://github.com/mrdoob/three.js/pull/29187#issuecomment-2314174423 to address this issue.

**Pull request merged**
