### PR TITLE
SVGRenderer: produce string with HTML code instead of SVG elements creation 

### PR DESCRIPTION
**Pull request by linev**
Improved version of #11379 

Use creator instance to clearly separate SVG elements production from plain text dump.

Plus improves cleanup, using following code:

     _svg.innerHTML = '';

### CODE REVIEW

**Comment by linev** [comment]
Are there chances that this code will be merged?
Should I change it?

**Comment by mrdoob** [comment]
Sorry for the delay... I feel like this change over-complicates the code 😕

**Comment by linev** [comment]
> I feel like this change over-complicates the code

Yes, It is a little bit more complicated - but complication remains inside SVGRenderer.
And it is the only way to overcome performance problem with SVG.

Another possible way for us to solve this problem - try to catch calls to `document` object and emulate creation of SVG elements. But this method would be very unstable and after each change in SVGRenderer one need to synchronize changes in our external code.

**Comment by mrdoob** [comment]
> And it is the only way to overcome performance problem with SVG.

I'm curious about your use case.

**Comment by linev** [comment]
like such geometries

https://github.com/linev/jsroot-test/blob/master/TGeo/atlas.svg
https://github.com/linev/jsroot-test/blob/master/TH3/glbox2.svg

If one uses normal way (with DOM elements), it takes factor 10 longer to produce such images - 
5 seconds instead of 0.5 sec.

**Comment by linev** [comment]
And the same, but interactive:

https://root.cern/js/latest/examples.htm#tgeo_atlas
https://root.cern/js/latest/examples.htm#th3_glbox2

**Comment by mrdoob** [comment]
Did you guys switch to WebGL?

**Comment by linev** [comment]
Of course we are using WebGL.
But for different tests and for creation of output files SVG is very useful for us.

Now I found a workaround to emulate `document` functionality and generate text SVG output directly  with existing SVGRednderer:

https://github.com/root-project/jsroot/blob/dev/libs/three.svg_renderer_footer.js#L15-L52

**Comment by mrdoob** [comment]
Oh nice!

**Pull request closed without merging**
