### PR TITLE
THREE.Box3.size() should return a zero-length vector when box is empty

### PR DESCRIPTION
**Pull request by valette**

### CODE REVIEW

**Comment by bhouston** [comment]
That seems acceptable.

**Comment by mrdoob** [comment]
There is a reason why default values are Infinity and -Infinity. Changing them to 0 will break things...

**Comment by valette** [comment]
Well, the issue comes from this example: http://jsfiddle.net/rgebecfx/
```
var box1 = new THREE.Box3();
box1.min.set( 0, 0, -2 );
box1.max.set( 1, 1, -1 );

var box2 = new THREE.Box3();
box2.min.set( 0, 0, 1 );
box2.max.set( 1, 1, 2 );

box2.intersect( box1 );
console.log( box2.size() ); // {x: 1, y: 1, z: -2}
```

There are no Infinitiy numbers in these results, just the z-component being negative.
In the end, you cannot really use box.size() without calling isEmpty() to take care of these issues.

But this also adds extra-computation since isEmpty() is not free...

**Comment by bhouston** [comment]
I think you are on to something @valette.  There is an issue here.

But my feeling is that box.size() should return negative numbers when is empty.  There is a difference between an empty box and a box with 0 size, and we should keep that distinction.

I think that maybe the issue is that intersect should return a true empty Box3(+inf, -inf ) when there is no intersection, that is probably the right place to fix the issue?

BTW love your publications, I've also done some embedded tetrahedral meshing stuff a couple years back: https://cs.uwaterloo.ca/~c2batty/papers/Batty10.pdf

BTW 2 Given that it is your area, I think that there is a need for a practical mesh compression in ThreeJS, both a compressor and a decompressor, and it would be a godsend to ThreeJS.  This is the largest single slowdown with ThreeJS in production, it is downloading the damn meshes.  CTM isn't really a solution, it is just simple lzma compression.  I've tried gzip, lzma and brotli compression schemes, but they all have downsides.  Interesting discussion here, especially the input from @JarekDuda: https://github.com/google/brotli/issues/165  Basically I think that one needs to have varying bitsizes of data for different types of elements in a mesh, and one has to try reordering the data to get the best compression ratio.  It can probably result in 2x+ savings compared to current approaches and that means 2x faster page loads -- which would mean the world to users.

**Comment by bhouston** [comment]
> I think that maybe the issue is that intersect should return a true empty Box3(+inf, -inf ) when there is no intersection, that is probably the right place to fix the issue?

The reason why I think this is the fix is that if we leave its current behavior, the semi-empty box may result in an intersection with another box, but realy it shouldn't.  The current intersection logic is only valid for 2 box intersects, but on 3+ box intersections it may produce incorrect results.

**Comment by mrdoob** [comment]
#8643

**Pull request closed without merging**
