### PR TITLE
changed VREffect to only update world matrices once and address a problem when the camera's parent is dynamic

### PR DESCRIPTION
**Pull request by jzitelli**
When VREffect is applied to a camera that is added to a moving object (e.g. a vehicle that the viewer is riding in), I observe unwanted relative motion between the moving object and the viewpoint.  The modified vr_cubes example illustrates this effect.  This all applies to the case where there is one scene, not distinct left and right eye scenes.

Breakdown of the problem as I understand it:

(base line 136) Since the camera has a parent, camera.updateMatrixWorld is not performed.  

(base lines 141, 142) The decomposition performed here is then based on a potentially stale camera.matrixWorld.

(base line 150) Calling renderer.render here would update the entire scene graph (unless scene.autoUpdate was false), which would update camera.matrixWorld, but cameraL.matrixWorld is only updated (WebGLRenderer.js line 1092) for the rendered frame based on the previous stale decomposition.

(base line 155) Similar deal in this call to renderer.render for cameraR.  It also seems like the whole scene graph would be updated again, which is unnecessary as far as I can tell.

The changes I made to VREffect,js are along the lines of those made in another fork (where WebGLRenderer itself is patched): https://github.com/capnmidnight/three.js/commit/3cc06752fcf05688e94d6b5efd916ff000e3be97

(head line 144) The scene graph is updated once up front, which updates camera.matrixWorld.

(head lines 162, 168) cameraL.matrixWorld and cameraR.matrixWorld are formed directly by matrix multiplication with translation matrices that are initialized once when the VR parameters are determined (head lines 54, 55).

(head lines 122, 123) cameraL and cameraR matrixAutoUpdate are set to false, so when renderer.render is called for each (head lines 163, 169), the internal call to camera.updateMatrixWorld (WebGLRenderer.js line 1092) won't overwrite the matrices that were just formed in head lines 162, 168.

The shuffling around of the projection matrices is not relevant, only further optimization as far as I can see... sorry for mucking up the pull request with that, I'm happy to clean things up if any of these changes are of interest!

To test things you can run the modified vr_cubes example, swapping between the previous and proposed versions of VREffect.js.

### CODE REVIEW

**Comment by mrdoob** [comment]
> Sorry for mucking up the pull request with that, I'm happy to clean things up if any of these changes are of interest!

Yes please, better to have a clean PR.

**Comment by jzitelli** [comment]
done, please see #7196!

**Comment by Deminetix** [comment]
@jzitelli why did this PR and your remake #7196 never get merged? 

I just copied the VREffect.js changes into my project and it completely eliminated all jittering of things such as crosshairs added to the camera.

**Comment by Deminetix** [comment]
@mrdoob in fact i'd prefer #7196 as it doesn't change the constructor params and require the camera. I also tested that and its perfect :)

**Comment by jzitelli** [comment]
Hi, sorry I never really pressed this as it was my first ever GitHub PR, I hadn't used three.js much, didn't necessarily know what I was doing, etc... if it helps I can reopen, my latest version (based on @mrdoob's r74 dev branch) is here: https://github.com/jzitelli/three.js/blob/dev/examples/js/effects/VREffect.js

...it can maybe be cleaned up a bit, I recently made some changes to support webvr-boilerplate / CardboardEffect porting efforts

**Pull request closed without merging**
