### PR TITLE
Modularized OrbitControls

### PR DESCRIPTION
**Pull request by mikemeerschaert**
Modularized OrbitControls so it can be used like so:

```javascript
import { PerspectiveCamera, OrbitControls } from 'three'
const camera = new PerspectiveCamera(75, width / height, 0.1, 1000)
const controls = new OrbitControls(camera)
```

### CODE REVIEW

**Comment by Mugen87** [comment]
I think we should not start adding controls to the core. Otherwise users will request to also include `TransformControls`, `TrackballControls` etc...

**Comment by mikemeerschaert** [comment]
Why not?

I just started using this library yesterday, went through the Getting started guide and ended up on the [https://threejs.org/docs/#manual/en/introduction/Import-via-modules](Import via modules) page which tells me why I shouldn't be script tags. 

I set up my webpack dev server and started hacking away, and one of the first things I want to do is be able to move my cube around with the mouse. I fund the [https://threejs.org/docs/#examples/controls/OrbitControls](OrbitControls)  page and try and import it, but my typescript compiler throws an error telling me "three has no module OrbitControls". i googled around and found some custom implementations, some people said use the three-orbitcontrols-ts module, and others said do this:

```javascript
import * as THREE from 'three';
import 'three/examples/js/controls/OrbitControls';
```

That imports the whole three library and makes a huge bundle, which isn't very efficient, and isn't great for production. I'd much rather do the intuitive thing and just import the controls and use them, why wouldn't they be included in the core?

**Comment by looeee** [comment]
> Why not?

If anything, we should be trying to move things out of the core, not add more. 

In any case, this issue will become moot once #9562 is (finally!) resolved. 
It's a very long issue but if you want understand while files in the /examples folder are not yet modules then have a read through that to see some of the problems that have been encountered, and possible solutions.

**Comment by mikemeerschaert** [comment]
I removed all references to the global THREE variable in this port, everything that was being referenced from THREE was already available in the /src folder so I just imported everything I needed. Technically there shouldn't be anything wrong with this PR, it won't affect the existing examples folder or the global THREE variable. Other than that, what issue is there with adding this? 

I didn't read all the comments (looks like 2 years of [bikeshedding](http://bikeshed.com/) with no decisions on how to actually move forward) but what I did gather from those comments is a ton of people would like to use orbital controls it this way.

You have both mentioned the core, and why things shouldn't be added to it, but what's the alternative? as far as I know something can only be a core if other things are peripheral to it, but there is only one three repo that I'm aware of. Why even have a documentation page on OrbitControls if it doesn't belong in the library?

**Comment by looeee** [comment]
> looks like 2 years of bikeshedding

Unfortunately yes, to some degree. A lot of people have strong and often conflicting opinions on how to proceed with this and that makes it hard to reach any consensus. 

However there is also #14803, which hopefully marks a path forward.

**Comment by WestLangley** [comment]
The controls were moved to the examples 6 years ago. See https://github.com/mrdoob/three.js/commit/04b652ae26e228796f67838c0ec4d555e8b16528 for why.

Whether to promote `OrbitControls` to the library is up to @mrdoob.

**Comment by WestLangley** [comment]
@mikemeerschaert For future reference, please see [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js) -- especially the last two bullet points. Avoid tab-to-space conversion.

**Comment by mikemeerschaert** [comment]
Ok @WestLangley thanks. I think the scope of this pr should just be getting this one module into the library to make the module imports consistent with the documentation. And thanks for the note, I'll fix the formatting when I get home from work. I use prettier and I'll adjust the settings to conform to the style guide.

**Comment by mikemeerschaert** [comment]
@donmccurdy  If you import it using
```javascript
import { OrbitControls } from 'three/examples/js/controls/OrbitControls';
```
can you still import it without importing the whole library? I'm just trying to keep my bundle as small as possible by only using what I need. I guess I don't know enough about this whole project to know how the global THREE gets used, but it seems to me with that implementation you'd need to import all the modules twice if you used them elsewhere.

for example, if you had something like 
```javascript
import { PerspectiveCamera, Spherical } from 'three';
import { OrbitControls } from 'three/examples/js/controls/OrbitControls';
```

Your bundle would now have Spherical imported from the math/Spherical.js module, and the definition of THREE.Spherical() imported for the global object.

Also, you now have a syntax that requires knowledge of the whole libraries file structure in order to use those components. It's not bad for an interim step, but in the end it's hard to get started with a library where you have to jump through a lot of hoops and use inconsistent import schemes to get at various components. Also, once it's set up like that people are going to start depending on it which will make it very difficult to change.

**Comment by donmccurdy** [comment]
> Can you still import it without importing the entire library?

See https://github.com/mrdoob/three.js/pull/14803#issuecomment-417099084. That is definitely a requirement I think, so if the PR  isn’t working that way already we’ll need to resolve that before merging the PR.

> ... you now have a syntax that requires knowledge of the whole libraries file structure ...

Keep in mind that we cannot put everything from `examples/js` into the core library, so `import { RarelyUsedLoader } from ‘three’;` isn’t an option. With that constraint, do you have suggestions for how to make it better? We could, for example, include the “how to import this file” at the top of the documentation for every file that isn’t part of the core library.

**Comment by mikemeerschaert** [comment]
It's obviously up to @mrdoob, but if I were to offer a suggestion I'd say have a readme that tells people that if they want a module from the examples library they should put in a feature request for it, and if it gets enough +1's it should be ported over to the core library and have the the THREE references refactored to use existing exported modules. If the dependant THREE properties haven't been ported yet, they should get moved over as well.

I don't know what the issue is with having a lot of stuff in the core library as long as it's well documented (I've found the documentation on this library to be pretty outstang considering it's complexity!). And as long as you aren't doing `import * as THREE from 'three'` your bundle size won't be affected by the additional modules.

**Comment by WestLangley** [comment]
@mikemeerschaert As I pointed out, `OrbitControls` is not part of the core because users want to modify `OrbitControls`.

**Comment by donmccurdy** [comment]
The goal right now is to ensure things that aren't in the core library (for whatever reason) are still as easy as possible to include in your project.

Not everyone has tree-shaking available, or uses ES modules yet, or even necessarily uses a build system. I'm not sure what the bar should be for a file to be added to the core library, but I think it does need to be more than just popularity. Files that other example modules depend on are better candidates. Having additional threejs NPM modules someday (think `import { OrbitControls } from '@three/controls'`) would be interesting in the future, but we need to get things ported to ES modules before considering that.

**Comment by mikemeerschaert** [comment]
@WestLangley can't people just copy out the logic out of the source and roll their own implementation if they want to change the way it works?

@donmccurdy I get your point, and I've seen other libraries do that successfully, but it does add a layer of complexity to the developer. For example, there are some animations and geometries in the examples folder, would those be in new npm modules? How do you know when to get an animation from the core library and when to reference the external module? How do you even decide which goes where? It seems like the easiest thing is just to port them all to the core library on request.

I do think you raise some valid points about users not using ES modules yet, or thier build systems not supporting tree-shaking. That being said, lots of new developers are coming to JS with create-react-app in hand and other boilerplates that set this all up for them, and I believe the trend will continue to move toward good support for ES modules.

**Comment by donmccurdy** [comment]
> It seems like the easiest thing is just to port them all to the core library on request.

Unfortunately that's not an acceptable general solution... I think you're describing a discovery and documentation problem, for which adding files to the core library is only one of many technical solutions. There will always be a need for plugins to exist, as in many other libraries, and we need to get to the point where those external plugins are clearly documented and easily-importable no matter what.

**Comment by Mugen87** [comment]
> There are many reasons we should consider additions from time to time.

`GLTFLoader` is one candidate from my point of view.

**Comment by arodic** [comment]
I think this issue should be closed for three reasons:

1. We have consensus that examples should be modularized and that already includes OrbitControls. Therefore this issue is redundant with infamous bikeshedding discussion.

2. Once examples are modularized, it does not matter what is in core/build and what is in examples since modules will make it easy to make custom builds with modules from examples included.

3. In the future, it will not matter what is bundled in the core/build since that practice is slowly but surely becoming unnecessary.

**Comment by sanonz** [comment]
### suggests:
install
```shell
npm install @threejs/core @three/orbit-control
```

use
```js
import THREE from '@threejs/core';
import OrbitControls from '@threejs/orbit-control';

const controls = new OrbitControls(camera);
```

and org [@threejs](https://www.npmjs.com/org/threejs) available.

@mrdoob @donmccurdy see see

**Comment by mikemeerschaert** [comment]
Sorry for making another big bikeshedding argument on this simple pr, you guys seem to have a direction you want to go with the library and you've put a lot of work into it, and I've only been using it for a couple of days.

That being said, @sanonz, if you do that, you import the entire library and the whole thing ends up in your bundle. Furthermore, it gets duplicated if you import other things from core elsewhere in your code. See  https://github.com/mrdoob/three.js/pull/15070#issuecomment-430738375. Much better to refactor OrbitControls to remove references from THREE and instead import the dependencies from the 'three' library. I think weather you split three up into smaller modules or keep it all in core, you'd still want to refactor the modules in examples to remove the dependency on the global THREE object.

**Comment by donmccurdy** [comment]
@sanonz I agree that would be very convenient, but I'd vote to just keep focused on ES modules for now, which have to be solved first anyway... there are pros/cons to NPM packages, that can be discussed after ES modules are solved...

> Sorry for making another big bikeshedding argument ...

No problem @mikemeerschaert, it's a totally fair suggestion. :)

> ... you import the entire library and the whole thing ends up in your bundle. Furthermore, it gets duplicated if you import other things from core elsewhere in your code ... you'd still want to refactor the modules in examples to remove the dependency on the global THREE object.

Agreed, we have to solve that in any case. I think it's a prerequisite to using ES modules at all here.

**Comment by donmccurdy** [comment]
> (3) In the future, it will not matter what is bundled in the core/build since the practice of bundling is slowly but surely becoming unnecessary.

@arodic I think there are a few exceptions to this rule, but I agree with your other points.

I'm closing this issue, but we'll keep working on these issues — making sure the whole library isn't imported, especially — in #14803 and future PRs.

**Comment by mrdoob** [comment]
@sanonz

> and org @threejs available.

I just created the org 😊

**Comment by gkjohnson** [comment]
@mrdoob Interesting -- is there a plan for the @threejs org? Will examples be moved into many separate repos? Or will there be a separate examples repo?

**Comment by looeee** [comment]
> I just created the org

@mrdoob could we add a note here pointing people to the main repo, to avoid confusion?

https://github.com/threejs/three.js/blob/master/README.md

**Comment by donmccurdy** [comment]
@gkjohnson @looeee I think he means the npm organization (https://www.npmjs.com/org/threejs) not the GitHub organization. It could be used for publishing scoped packages, like:

```js
import { OrbitControls } from '@threejs/???';
```

**Comment by IRelLoveWeb** [comment]
maybe you can see https://gist.github.com/cecilemuller/0be98dcbb0c7efff64762919ca486a59.

**Pull request closed without merging**
