### PR TITLE
Examples: Update FBXLoader examples to .outputEncoding = sRGBEncoding

### PR DESCRIPTION
**Pull request by donmccurdy**
Related issue: 

- https://github.com/mrdoob/three.js/issues/23283

Added `THREE.ColorManagement.legacyMode = false` only where helpful to preserve the original look. In other cases I think the changes to the image are correct.

### CODE REVIEW

**Comment by epreston** [comment]
I've been wondering about that. Will both Color and ColorManagement continue to export SRGBToLinear ?  Is it more future proof to import from ColorManagement ?

**Comment by Mugen87** [comment]
Don't we need some changes in `FBXLoader` first before doing this, see https://github.com/mrdoob/three.js/issues/23283#issuecomment-1026393084?

**Comment by donmccurdy** [comment]
> Will both Color and ColorManagement continue to export SRGBToLinear ? Is it more future proof to import from ColorManagement ?

Although ColorManagement.js exports SRGBToLinear and LinearToSRGB, we don't export those functions from the three.js top-level module. Userland code will have to access them through other methods, like the THREE.Color API. It's also an option to do this...

```javascript
THREE.ColorManagement.convert( color, 'srgb', 'srgb-linear' );
```

... but the THREE.Color API is more stable at this point; there is no reason to switch. I would probably consider `convert(...)` to be an internal API at least for now.

***

> Don't we need some changes in FBXLoader first before doing this, see https://github.com/mrdoob/three.js/issues/23283#issuecomment-1026393084?

I'd missed that, thanks! Currently FBXLoader color manages textures, but nothing else. So we're in a limbo where it's only half correct. I don't think that updating the examples to use `.outputEncoding = sRGBEncoding` makes things any worse, but we should definitely finish the changes to FBXLoader as well.

**Comment by donmccurdy** [comment]
Let's go ahead and do the changes described by https://github.com/mrdoob/three.js/issues/23283#issuecomment-1026393084 too. I noticed that Blender has a choice when exporting FBX of whether the vertex colors are linear or sRGB. The default is sRGB, and I don't know that we can detect which was chosen, so I've assumed they're sRGB here.

@looeee as FYI, meant to preserve the look and appearance of FBX models under outputEncoding=sRGBEncoding.

**Comment by Mugen87** [comment]
Since the color maps already set `.encoding = sRGBEncoding;`, this PR is complete now. Merging.

**Pull request merged**
