### PR TITLE
Examples: Update fflate version

### PR DESCRIPTION
**Pull request by gkjohnson**
Related to #21654

**Description**

See comment [here](https://github.com/mrdoob/three.js/pull/21654#issuecomment-821721653).

This PR updates the fflate file in js/libs and jsm/libs to use the latest [esm](https://unpkg.com/browse/fflate@0.6.9/esm/browser.js) and [umd](https://unpkg.com/browse/fflate@0.6.9/umd/index.js) files from the published package. The new esm variant does not use `require` so it shouldn't cause issues with skypack. I'm not sure where the previous minified fflate module came from but this one is not minified. Perhaps we should change the file name?

You can see that the new module version of fflate functions correctly in the fbx example:

https://raw.githack.com/gkjohnson/three.js/fflate-update/examples/webgl_loader_fbx.html

For some reason I'm not able to get the FBX example to work at all when switching it over to use the classic `examples/js/` scripts even before updating fflate. I get an "unknown format" error -- am I missing a step here?

cc @Mugen87 @donmccurdy

### CODE REVIEW

**Comment by Mugen87** [comment]
@gkjohnson The issue in `FBXLoader` should be fixed via #21671.

@marcofugaro It seems `npm run build-examples` formats strings in a way that might break code. In `FBXLoader`, the following line:
```js
const CORRECT = 'Kaydara FBX Binary  \0'; 
```
was transformed to:
```js
const CORRECT = 'Kaydara FBX Binary	\0'; 
```
Notice that the two spaces after "Binary" were replaced with a tab. This breaks the detection of binary FBX files.

I've patched this by using character characters which is more robust anyway. However, it's probably better to ensure `npm run build-examples` does not perform such changes to strings.

**Comment by Mugen87** [comment]
> I'm not sure where the previous minified fflate module came from but this one is not minified.

The original developer of `fflate` provided these builds for us.

**Comment by gkjohnson** [comment]
- Renamed `fflate.module.min.js` to `fflate.module.js`
- Used find and replace to adjust fflate imports in jsm files
- Tested FBX Loader example with classic script tag and module variants

Thanks @Mugen87! That fixed it

**Comment by Mugen87** [comment]
This line needs an update, too.

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/examples/webgl2_materials_texture2darray.html#L59

**Comment by Mugen87** [comment]
And here:

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/utils/build/rollup.examples.config.js#L119

**Comment by gkjohnson** [comment]
ooh sneaky. I'd just checked in the /jsm folder. Last commit fixes those two lines.

**Comment by Mugen87** [comment]
Unfortunately, the PR is still incomplete. Next to `webgl2_rendertarget_texture2darray`, please update:

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/examples/webgl2_materials_texture2darray.html#L59

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/editor/js/Loader.js#L10

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/editor/js/Menubar.File.js#L3

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/editor/sw.js#L16

Next time, do a search in the entire repository ;)

**Comment by marcofugaro** [comment]
> @marcofugaro It seems npm run build-examples formats strings in a way that potentially breaks code.


@Mugen87 oh yeah, it's because of this line:

https://github.com/mrdoob/three.js/blob/58cd9308d14801889659741da054b91de2f4d905/utils/build/rollup.examples.config.js#L17


I saw your fix in #21671, thank you!

I'll see if we can make eslint change spaces to tabs with this rule: https://eslint.org/docs/rules/indent

**Comment by gkjohnson** [comment]
@Mugen87 sorry, thanks for the catch. Just updated and I no longer see any references to `fflate.module.min.js` in the entire repository.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
