### PR TITLE
OBJLoader support for loading lines and obj file fix for blender's broken two-vertex-face lines

### PR DESCRIPTION
**Pull request by chr15m**

### CODE REVIEW

**Comment by matkoniecz** [comment]
@mrdoob It is quite discouraging to see very old pull requests without neither merge nor comments.

Closing with "refused because..." is much better than something like that.

**Comment by mrdoob** [comment]
Sorry about that. I think this couldn't be merged because the loader switched to `BufferGeometry` during the same dev cycle.

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#3115

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#3115

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#3115

**Pull request closed without merging**
