### PR TITLE
Core: rename .applyMatrix() to .applyMatrix4()

### PR DESCRIPTION
**Pull request by WestLangley**
Following from the discussion in #18343, methods that take a matrix arg will now clearly identify the type of matrix.

I'll update the migration docs...

### CODE REVIEW

**Comment by Mugen87** [comment]
There seems to be much more example code that uses `applyMatrix()` but which is not migrated in this PR. Just one example:

https://github.com/mrdoob/three.js/blob/cf28da969d278e38932de9b4dfc2357978d694b1/examples/webgl_instancing_performance.html#L185

A full text search 27 examples files using `applyMatrix()`.

**Comment by WestLangley** [comment]
I am not going to update the examples in this PR. We need to ensure that all examples still function with the Legacy patch.

I updated `.ts`, `docs/en`, `docs/zh`, `unit`,  `Legacy`, and `DeprecatedList`. I will update `Migration` and `Examples` if this is merged.

**Comment by WestLangley** [comment]
rebuild required... working on updating the examples...

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> rebuild required... 

Done!

**Pull request merged**
