### PR TITLE
Faster projectOnVector function

### PR DESCRIPTION
**Pull request by loldrup**
This implementation of projectOnVector is faster and shorter than the current version, and it requires no intermediate Vector3 allocation

### CODE REVIEW

**Comment by mrdoob** [comment]
Looks good @WestLangley?

**Comment by WestLangley** [comment]
OK.

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by loldrup** [comment]
Thanks Mr. Doob :D
Den 08/06/2016 23.42 skrev "Mr.doob" <notifications@github.com>:

**Pull request merged**
