### PR TITLE
Lint manual

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: https://github.com/mrdoob/three.js/pull/25251

**Description**

Fix manual so that it adheres to three.js code lint standards.

### CODE REVIEW

**Comment by Mugen87** [comment]
I guess the CodeQL warnings are existing ones which just pop up because you are modifying the respective lines of code, right.

**Comment by LeviPesin** [comment]
Yes, I think so.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Do you know why I can't test your branch via githack? It works with other PRs without issues. 

So this link should work: https://raw.githack.com/LeviPesin/three.js/lint-manual/manual/index.html

**Comment by LeviPesin** [comment]
> So this link should work: https://raw.githack.com/LeviPesin/three.js/lint-manual/manual/index.html

I think I made an error while cloning the repository some time ago, so it is actually named LeviPesin/three.js-1, not LeviPesin/three.js...

**Pull request merged**
