### PR TITLE
WebGPURenderer: Add (u)int16 Support

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
**Description**

This PR adds the support to int16 and uint16 to the WebGL Backend and also handle automatically the conversion to int32 and uint32 typed arrays in WebGPU since 16 format is not available by default.

*This contribution is funded by [Utsubo](https://utsubo.com)*

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
https://github.com/gpuweb/gpuweb/issues/229
https://github.com/gpuweb/gpuweb/issues/273

**Comment by RenaudRohlinger** [comment]
Thanks for this @CodyJasonBennett! So if I understand correctly I should also include `int8` and `uint8`?

**Comment by CodyJasonBennett** [comment]
Linked only for posterity, but I suppose those types would require the same treatment.

**Comment by kainino0x** [comment]
Thanks mrdoob for forwarding this issue, I've filed https://github.com/gpuweb/gpuweb/issues/4549

**Pull request merged**
