### PR TITLE
Object3D: make applyMatrix() more robust

### PR DESCRIPTION
**Pull request by WestLangley**
Ensure `.matrix` is updated before using it in a calculation.

### CODE REVIEW

**Comment by Mugen87** [comment]
It makes the method more robust but it will also lead to redundant computations in certain cases. What is your motivation behind this PR? 

Looking at related code it seems there is no policy about whether matrices should be updated or not. Methods like `getWorldPosition()` ensure the world matrix is up-to-date whereas e.g. `localToWorld()` do not.

**Comment by WestLangley** [comment]
>What is your motivation behind this PR?

I want the method to produce the correct answer.

>It makes the method more robust but it will also lead to redundant computations in certain cases.

As three.js is designed to be used, it is not a hot method.

>Looking at related code it seems there is no policy about whether matrices should be updated or not.

The policy has been that it is a judgement call.

**Comment by Mugen87** [comment]
> I want the method to produce the correct answer.

It's okay from my point of view if method make certain assumptions for performance reasons. It's no good approach to always blindly update all inputs which are necessary to produce a certain result.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
