### PR TITLE
fix to LWOLoader.js : add suport LWO2 format

### PR DESCRIPTION
**Pull request by adrs2002**
LWOLoader supports only `LWO3` format.
This fix is correspondence to `LWO2` format , Used in NASA's Open Model.

[ NASA's Open model - LWO ](https://nasa3d.arc.nasa.gov/search/lwo/model) , and [ github-NASA ](https://github.com/nasa/NASA-3D-Resources)
[ preview sample ](http://adrs2002.com/sandbox/lwoLoader/webgl_loader_lwo.html)

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
This is not correct, it's introduced errors when parsing LWO3 files. 

[webgl_loader_lwo.html](https://raw.githack.com/adrs2002/three.js/325c9f45f04508f52ad31d807db2f405e71f1e41/examples/webgl_loader_lwo.html)

@mrdoob can you revert this?

**Comment by looeee** [comment]
@adrs2002 thanks for the contribution, but please make sure to check at least with the `webgl_loader_lwo` example in future.

**Comment by mrdoob** [comment]
@adrs2002 could you fix the regression with a new PR?

**Comment by mrdoob** [comment]
Before:
https://threejs.org/examples/webgl_loader_lwo.html

After:
https://raw.githack.com/adrs2002/three.js/325c9f45f04508f52ad31d807db2f405e71f1e41/examples/webgl_loader_lwo.html

**Comment by adrs2002** [comment]
@looeee  @mrdoob 
Oh.Sorry! I make new PR ASAP!

**Pull request merged**
