### PR TITLE
Add Code Of Conduct

### PR DESCRIPTION
**Pull request by ivannieto**

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm... Have you seen any incident in the community that could have been avoided by having this file?

**Comment by mrdoob** [comment]
screen shot 2016-12-25 at 09 46 41

Wow. I've never seen that kind of language in this community before...

**Comment by ivannieto** [comment]
It's hard to be called spammer without reasons. Never intented to be rude, and always tried to help by adding a simple file. 

Now put yourself in my situation. I'm adding in the same day some PR's and I don't know who and whith which powers he starts to drop shit on me... It was easy, said that, bye to the project. I don't want to take part in a community prejudging no one.

**Comment by ivannieto** [comment]
And please @mrdoob, tell me where do you find I'm being rude in my explanations. It will make me improve my english skills.

**Comment by Hectate** [comment]
Just my two cents - and separate from concerns regarding someone going around "spamming" pull requests for a CoC readme on selected repositories - I find this pull request useless. All the interaction on this project in this space happens through GitHub, which already has it's own [Community Guide](https://help.github.com/articles/github-community-guidelines/) and [Terms of Service](https://help.github.com/articles/github-terms-of-service/) that guides these interactions. Anyone acting in a fashion that is outside of those terms/guidelines clearly stands out as an unpleasant interaction and is, presumably, swiftly handled with appropriate moderator activity.

Furthermore, by adding a CoC readme into the repository, we would be introducing content unrelated to the purpose of the repository itself. README and LICENSE are logically necessary; one describes information related to the the use of the library and the other information about one's legal rights in using it. An additional file instructing how one should interact with other people has no place in a code repository itself, in my opinion.

I agree with the general sentiment of the Code of Conduct as presented, but is it really necessary to include a file that essentially asks everyone to treat other people as humans? A document will not stop someone from being unpleasant to others. Yes, I read the "101 + FAQ" that the Covenant website provided a link to, and I am still unconvinced.

@ivannieto Do you actually intend to contribute to this community? If you really care about "_...fostering an open and welcoming environment..._" and "_...making participation in our project and our community a harassment-free experience for everyone..._" for this repository, the appropriate move would be to examine the contents for instances where that is lacking, and issuing pull requests to correct _those_ files.

If you are rather interested in merely pushing a CoC across the tens of repositories where you've submitted and not actually being a member of those communities, you _will_ get labelled as a spammer. As a first introduction, it's a poor one.

Should you celebrate it as it appears, Merry Christmas. Otherwise, I wish you a pleasant December 25th.

**Comment by mrdoob** [comment]
Very well put @Hectate.

**Comment by ivannieto** [comment]
Well... It was never intended to be that way.

Can't think why adding this file is game-changing at all. I'm now gonna being marked because of these comments, in my try to add something that I've found interesting for a project. 1 or 100 times. And this is made because of 24pullrequests.com, maybe I've missed something in the way to reach the goal...

Please pardon me if you found this behaviour offensive or context empty, but I  guess it's your point, as I've said some communties adopted it gracefully and with a smile. 

Some criticism is ok, but there are limits.

I never ever won't mark someone as spammer because of adding a proposal to add a new file like this one. Better say something like your comment @Hectate rather than posting images like @mrdoob did, and dropping shit on someone at first glance. This makes me look like a monster when I'm trying to start in here. That's what I'm saying. 

 Said that, enjoy your holidays. And thanks for your time.

**Comment by mrdoob** [comment]
On top of that...

@ivannieto, we know your intentions are good, but the execution is definitely not the best.

You have added a file to many repositories that define how contributors should behave, but I've found instances were [you ignored the contributing rules of those projects](https://github.com/graphhopper/graphhopper/pull/924#issuecomment-269100595). Which is also ironic, considering you're adding a file asking people to follow rules carefully.

Also, you've used language like "without knowing a little shit", "he starts to drop shit on me"... which is unprofessional and unrespectful. Which is also ironic, considering you're adding a file asking people to be respectful.

**Comment by ivannieto** [comment]
I understand that point about the language. But understand as well, that I'm feeling really umconfortable with this situation.

And yes, I've missed some guidelines along the way. It's my fault of course and something to learn about. But a rejection could be really better for me. It's a file, but it's not an ad to buy Viagra. Let's understand what spam means. I really don't need all of this buzz...

Thanks for your points.

**Comment by mrdoob** [comment]
> But understand as well, that I'm feeling really umconfortable with this situation.

Yeah, I understand things didn't work as you expected. Life is complicated 😉

**Pull request closed without merging**
