### PR TITLE
ColladaLoader: instance node names now match their associated library nodes name

### LINKED ISSUE #13365: ColladaLoader instance nodes imported with names like 'instance_0'
##### Description of the problem

After the replacement of `ColladaLoader` with `ColladaLoader2` (now named just `ColladaLoader`), it looks like the imported information has changed a little bit.

heres a (condensed) snippet of my dae.
```
<library_nodes>
  <node id="ID3" name="Element_entry-door-handle">
    <node id="ID47" name="instance_3">
      </matrix>
      <instance_node url="#ID48" />
    </node>
  </node>
  <node id="ID48" name="Anchor">
    </instance_geometry>
  </node>
</library_nodes>
```

the behavior that i used to see was that the imported dae object would look like this:
```
scene.children[0] = [
  {
    name: 'Element_entry-door-handle',
    children: [
      {
        name: 'Anchor'
      }
    ]
  }
]
```

now it is looking like this:
```
scene.children[0] = [
  {
    name: 'instance_0',
    children: [
      {
        name: 'instance_3'
      }
    ]
  }
]
```

is this the expected output? on one hand i see at as incorrect because of how `ColladaLoader` used to work, but on the other hand i see it as correct because it matches how the dae is represented.

i am able to achieve what i need by doing a search through `library.nodes` and marrying the 'instance' up with its original definition and getting _that_ name.

would you accept a PR if i ensure that instance nodes are coming through with their definitions name rather than `'instance_0'`, `'instance_1'` etc?

i'll work on putting together a jsfiddle and updating this issue once complete.

##### Three.js version

- [ ] Dev
- [ ] r90
- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by shelbyspeegle**
Fixes #13365

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by thedayofcondor** [comment]
Hi,
just updated my project from r87 to r100 and the updated ColladaLoader does not seem to load my model correctly anymore . My model is generated with SketchUp 2018.

In my opinion the original behavious was correct, allowing an instance to have a separate name from the library node (this is the intended behaviour, having a separate "name" property in the node). 

As a suggestion, what about allowing a node to have a "name" and an "instanceName" (or a "name" and a "libraryName")?

**Comment by mrdoob** [comment]
@thedayofcondor It'll be better to create a new issue for this. Please, provide a example file if possible.

**Comment by thedayofcondor** [comment]
@mrdoob i created [#15658](https://github.com/mrdoob/three.js/issues/15658)

**Pull request merged**
