### PR TITLE
Fix Matrix3, Matix4 applyToBuffer

### PR DESCRIPTION
**Pull request by milcktoast**
`BufferAttribute.setXYZ` was missing `index` argument.

### CODE REVIEW

**Comment by jpweeks** [comment]
Maybe a test should be added for this as well?

**Comment by jpweeks** [comment]
Ok, I fixed `Matrix3` as well. I can also work on adding some tests if that is desired.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
> I can also work on adding some tests if that is desired.

Yes, please. :)

**Pull request merged**
