### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
This PR cleans up `misc_controls_deviceorientation.html`  and explains the following line of code in all relevant examples.

```javascript
geometry.scale( - 1, 1, 1 );
```
I was frequently asked why this operation is performed so i've added a comment in the code.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Sorry, I am not in favor of this at all...

three.js does not support `scale( - 1, 1, 1 )`; Such a pattern leaves the normals and winding order in an inconsistent state.

Consequently, I would not add further credence to that pattern by adding a comment justifying it.

The only reason it works in these examples, is because the material is `MeshBasicMaterial` and that material does not respond to lights.

>I was frequently asked why this operation is performed so i've added a comment in the code.

The proper answer is to say "don't do it".

The way to handle this is to use this pattern:
```
var geometry = new THREE.SphereBufferGeometry( 500, 60, 40 );

var texture = new THREE.TextureLoader().load( 'textures/2294472375_24a3b8ef46_o.jpg' );
texture.wrapS = THREE.RepeatWrapping;
texture.offset.set( 0, 0 ); // optional
texture.repeat.set( - 1, 1 );

var material = new THREE.MeshBasicMaterial( {
	map: texture,
	side: THREE.BackSide
} );
```
I'm not sure how to handle video textures in this case, though. That example appears to be distorted anyway, so something is not right...

**Comment by mrdoob** [comment]
👍

**Comment by Mugen87** [comment]
@WestLangley Yes, i know the drawbacks of this approach. I'm actually familiar with your posts at stackoverflow :wink: e.g. https://stackoverflow.com/a/16840273

Although it's not a consistent solution, people quickly get the desired result if they want to develop something like 3D image gallery: https://www.youtube.com/watch?v=jT2mR9WzJ7Y&feature=youtu.be&t=1160

But yeah, the code snippet of @WestLangley is a better solution. We should revise the example and clean things up.

**Comment by Mugen87** [comment]
BTW: @WestLangley  What's the problem with video textures and your approach?

**Comment by WestLangley** [comment]
Right. Users copy these example. That is why the quality of the examples is so important.

Regarding the video example. As-implemented, it is distorted.

screen shot 2017-08-05 at 9 05 17 am

When trying `repeat.set( - 1, 1 )`, the video rendered as a blur for me.

**Comment by WestLangley** [comment]
Video distortion fixed in #11994

**Comment by Mugen87** [comment]
Cool! 👍

**Pull request merged**
