### PR TITLE
VRMLoader prototype

### PR DESCRIPTION
**Pull request by takahirox**
VRM has been released by Dwango today.

https://dwango.github.io/vrm/
https://dwango.github.io/vrm/vrm_spec/

VRM is VR 3D avatar file format. The specification is based on glTF 2.0 binary format. VRM extension is defined in top-level `json.extensions.VRM`.

I think the VRM extension feature is inspired by MMD. So I speculate `VRMLoader` can build with `GLTFLoader`, MMD stuffs, and some new stuffs.

Let me add `VRMLoader` prototype for developers who are interested in contributing to `VRMLoader`.

Example: https://rawgit.com/takahirox/three.js/VRMLoader/examples/webgl_loader_vrm.html

### CODE REVIEW

**Comment by mrdoob** [comment]
Nice! I wish the avatar was a little bit more dress up though... 😇

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
>  I wish the avatar was a little bit more dress up though

Agreed, not a big fan of this model. Are there any other options?

**Comment by takahirox** [comment]
I replace once I find a better model. Seems like this's the only VRM model whose license is ok now.

**Comment by mrdoob** [comment]
Seems like the loader is currently broken in `dev`. @takahirox do you mind taking a look?

**Comment by cx20** [comment]
@takahirox BTW, Recently, the [official VRM model](https://3d.nicovideo.jp/works/td32797) seems to have improved a bit.

**Comment by Mugen87** [comment]
I have found: https://github.com/pixiv/three-vrm.

Regarding this project, does `THREE.VRMLoader` still makes sense? Or isn't it better to refer potential VRM users to the above project?

**Comment by takahirox** [comment]
`THREE.VRMLoader` status is waiting for the VRM specification update. The  VRM specification doesn't expose some detail specification yet (eg. its toon material and secondary animation).

`three-vrm` team seemed to analyze Unity VRM implementation (VRM core members made(?) and it supports unexposed VRM features) and achieve to support VRM.

So currently `three-vrm` goes very forward and `THREE.VRMLoader` may be useless. Personally I want to keep working on `THREE.VRMLoader` if the specification is updated (`three-vrm` looks already nice but having competitors isn't bad), but not sure when the detail specification is exposed.

Then I have two options in my mind

1. Keep `THREE.VRMLoader` so far and has a link to `three-vrm` project in VRM example page
2. Remove `THREE.VRMLoader` and have a link to `three-vrm` project maybe somewhere in the document?. And consider to add `THREE.VRMLoader` again later when the specification is updated (and if having our loader makes sense).

**Comment by mrdoob** [comment]
I think I vote for option 2. Users may get confused otherwise?

**Comment by FMS-Cat** [comment]
What takahiro-san said is pretty accurate.
I think It's way too huge and rough to include our three-vrm into the examples folder of three.js.

We are so sorry about the lack of documentation in VRM spec :bow:
We are trying to describe detailed specs for VRM 1.0 right now.

**Pull request merged**
