### PR TITLE
Overwritten THREE.Geometry.clone for THREE.TubeGeometry to fix #7301

### LINKED ISSUE #7301: TubeGeometry.clone() fails
TubeGeometry.clone() calls TubeGeometry.constructor() with default parameters (path is undefined)
constructor calls FrenetFrames which fails at path.getTangetAt()

var tube = new THREE.TubeGeometry(path, 2, 1, 3, false);
var tubeClone = tube.clone();

### PR DESCRIPTION
**Pull request by AVGP**
I'm not sure if I'm exactly following code style guidelines for Three.js. Please tell me if I need to make adjustements so we get this landed :)

### CODE REVIEW

**Comment by mrdoob** [comment]
I don't think you need the `copy( this )`

**Comment by AVGP** [comment]
@mrdoob True that, good catch. Edited.

**Comment by mrdoob** [comment]
Thanks!

**Comment by threejsworker** [comment]
The examples of this pullrequest are now built and visible in threejsworker. To view them, go to the following link: 

 http://threejsworker.com/viewpullrequest.html#7303

**Pull request merged**
