### PR TITLE
Utils: Converters use now modules.

### PR DESCRIPTION
**Pull request by Mugen87**
A lot of examples are already using modules. However, other parts of the repository like the converters (`fbx2three.js` and `obj2three.js`) require UMDs. They are node scripts where using ES6 modules is still experimental. Nevertheless, the ultimate goal is to avoid any duplicates in the code base.

After some research, I've realized that using [esm](https://www.npmjs.com/package/esm) works pretty well for this use case. It's possible to use the same coding patterns like in the examples. It's only necessary to install `esm` before executing the scripts and add `-r esm` to the node command.

Feedback and other ideas are welcome since I've not used this approach in production before.

### CODE REVIEW

**Comment by donmccurdy** [comment]
> However, other parts of the repository like the converters (fbx2three.js and obj2three.js) require UMDs. 

To be specific, we don't use UMD modules anywhere yet – the `examples/js` files are not modules, they're just scripts that write to global variables. Real UMD modules can be consumed as CommonJS modules, or can write to browser globals.

I'm hoping that the end goal is still to generate true UMD modules (to `examples/js`) from source ES modules (in `examples/jsm`). Once we get there, it would probably be better for these nodejs scripts to use the UMD versions via CommonJS. Once nodejs gets ES module support we could switch it over of course.

In the meantime I have no problem with merging this PR.

**Comment by Mugen87** [comment]
> To be specific, we don't use UMD modules anywhere yet – the examples/js files are not modules, they're just scripts that write to global variables.

Sorry for not being precise here. I've accidentally used the term `UMD` in the wrong context.

 > I'm hoping that the end goal is still to generate true UMD modules (to examples/js) from source ES modules (in examples/jsm).

But do we need actually need `examples/js` under source control? If the code base has no dependencies to `examples/js` anymore, why not removing it and let the user generate UMDs if necessary.

**Comment by donmccurdy** [comment]
> But do we actually need examples/js under source control? If the code base has no dependencies to examples/js anymore, why not removing it and let the user generate UMDs if necessary.

Maybe not, but if we were planning to delete `examples/js` then I'm not sure why we're going to so much trouble to keep both directories in sync during the transition... Why not delete `examples/js/GLTFLoader.js` today? I'd assumed we wanted backward-compatibility. Or just for a few versions? There may still be enough people using CommonJS (e.g. with build tools like Browserify and Budo) to justify keeping the CommonJS modules – the core library is available as CommonJS, for instance.

**Comment by Mugen87** [comment]
> Why not delete examples/js/GLTFLoader.js today?

Stuff like the editor still depend on these files. That's because I have not suggested a removal so far.

How would a conversion of ES6 to UMD look like? Can we use an existing tool for this?

**Comment by donmccurdy** [comment]
> How would a conversion of an ES6 module to UMD look like? Can we use an existing tool for this?

Yes, going ES->UMD is more straightforward and we can use Rollup directly.

**Comment by Mugen87** [comment]
When performing the conversion, I expect rollup will bundle all dependencies of an ES6 module into the final UMD, right? Let's say you do this for `GLTFLoader`. Does it also include `three.js` into the `UMD` then?

**Comment by donmccurdy** [comment]
Nope! We'll need a Rollup transform to change the paths from `examples/jsm` to `examples/js`, but the imports become requires. https://github.com/mrdoob/three.js/pull/15526 by @gkjohnson implements this.

There could certainly be some edge cases, e.g. I'm not sure `nodes/` and maybe some groups of files that collectively represent a single module should be transformed 1:1... it might be better to bundle a single file with all of the dependencies in those cases.

**Comment by Mugen87** [comment]
I totally missed that PR! In this case, I'm closing this one. We should not wait too long to finish the transition though.

**Comment by Mugen87** [comment]
@donmccurdy Thanks for the information! 😊

**Pull request closed without merging**
