### PR TITLE
Add parameter 'digits' to vector*.round() + update tests and docs

### PR DESCRIPTION
**Pull request by felixmariotto**
following #17873

I tried to follow the [contribution instructions](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js), but it's my first time contributing to three.js, so pardon me for any obvious mistake...

@Mugen87 you mentioned in the issue that you prefer to remove the tests and implement the methods instead, but I didn't get what you meant... So I've only updated the tests, but I'm happy to change it you explain me what you want in a bit more detail.

### CODE REVIEW

**Comment by looeee** [comment]
> it's my first time contributing to three.js, so pardon me for any obvious mistake...

You need to remove the following files from your PR:

* package-lock.json
* build/three.js 
* build/three.min.js
* build/three.module.js

**Comment by Mugen87** [comment]
> you mentioned in the issue that you prefer to remove the tests and implement the methods instead, but I didn't get what you meant

I suggested to remove `QUnit.test( "rounding", ( assert ) => { ))` and added `QUnit.test( "round()", ( assert ) => {` for each class (`Vector2`, `Vector3` and `Vector4`).

But don't worry about it. This can be refactored at a later point.

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/issues/17873#issuecomment-552506083

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@felixmariotto Many thanks for your work on this! It would have been great if this PR has been merged. But unfortunately, there is not enough support for this change.

**Pull request closed without merging**
