### PR TITLE
SVGRenderer: produce string with HTML code instead of SVG elements creation

### PR DESCRIPTION
**Pull request by linev**
Starting from certain level of complexity (~100K faces) creation of SVG elements dominates rendering time, especially with node.js and jsdom. In batch mode I only require SVG file, therefore usage of text mode will speed up significantly my performance.

Plus there is very large performance penalty of current SVGRenderer.clear() function. 
Just check with current code here:

https://jsfiddle.net/x8c3ubt7/

In my browser first rendering takes ~2.5 sec, while clear takes ~25 sec.
Usage of `element.innerHTML = ""` speeds up significantly.

Here same example, but with code provided in this PR:

https://jsfiddle.net/x8c3ubt7/1/

Clear time is only 0.3 seconds and SVG file is smaller (due to reduced precision)

And when using text mode, one can skip creation of HTML elements at all.
Or can use producing string to set innerHTML property directly:

https://jsfiddle.net/x8c3ubt7/2/

Produced string can be used to create SVG elements directly:

    var renderer = new THREE.SVGRenderer( { astext:true } );
    renderer.setSize( window.innerWidth, window.innerHeight );
    renderer.render( scene, camera );
    var elem = document.createElement('div');
    elem.innerHTML = renderer.outerHTML;

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, I'm not sure about this PR actually. I can see how it makes sense in a node environment, but I think it complicates the code a bit...

**Comment by linev** [comment]
Alternative solution - define two sets of functions.
One for normal SVG creation, other for text output.

> I can see how it makes sense in a node environment

Not only. We have environment, where SVG graphics combined with WebGL. Like this one: 

https://root.cern/js/latest/examples.htm#tcanvas_2d+3d

We have to produce vector graphics output (SVG/PDF/PS) for such picture.
But for such tasks I do not need **real** SVG rendering - I just create SVG string for three.js drawing and insert it into the existing SVG code. 

And yes, second application - batch (headless) production of such images with node.js (or may be phantom.js)

**Comment by linev** [comment]
In principle, one could fully separate SVG and text production.

https://github.com/linev/three.js/tree/text2svg

In this branch I add one more commit, where special producer object is introduced.
It fully decouples normal SVG from text production.
Probably such kind of implementation is better

**Comment by linev** [comment]
Should I submit alternative PR with improved branch?
https://github.com/linev/three.js/tree/text2svg

**Pull request closed without merging**
