### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
This PR improves the consistency between `THREE.Refractor` and `THREE.Mirror`.

- Change type of `color` parameter in `THREE.Refractor`
- Fix empty `undefined` options parameter in `THREE.Refractor`
- Align some internal names of variables in `THREE.Mirror` to `THREE.Refractor`
- Transfer default shader code of `THREE.Mirror` into `THREE.DefaultMirrorShader` and allow a custom mirror shader via parameter (see `THREE.Refractor`)
- Apply the world matrix of the mirror to the texture matrix in `onBeforeRender` once and not in the vertex shader for each vertex.

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing:
http://rawgit.com/mugen87/three.js/refraction/examples/webgl_refraction.html
http://rawgit.com/mugen87/three.js/refraction/examples/webgl_mirror.html

**Comment by Mugen87** [comment]
Now the default shaders for `THREE.Refractor` and `THREE.Mirror` are actually identical.

**Comment by mrdoob** [comment]
> - Transfer default shader code of `THREE.Mirror` into `THREE.DefaultMirrorShader` and allow a custom mirror shader via parameter (see `THREE.Refractor`)

Maybe we can follow `THREE.Sky` approach:

https://github.com/mrdoob/three.js/blob/dev/examples/js/objects/Sky.js#L34

**Comment by mrdoob** [comment]
> - Apply the world matrix of the mirror to the texture matrix in `onBeforeRender` once and not in the vertex shader for each vertex.

Niice!

**Comment by Mugen87** [comment]
> Maybe we can follow THREE.Sky approach:

Agreed!

**Comment by Mugen87** [comment]
Done! :blush:

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
