### PR TITLE
Tightened flattening of uniform array data.

### PR DESCRIPTION
**Pull request by tschw**

### CODE REVIEW

**Comment by tschw** [comment]
Fixes the problem reported in https://github.com/mrdoob/three.js/pull/8606#issuecomment-211119304 

To verify [fiddle](http://jsfiddle.net/kuquj1qp/) with the `<script>` tag to `https://raw.githubusercontent.com/tschw/three.js/UniformType/build/three.js`.

BTW: Is there any advantage from using that `rawgit` URL? Worked once, then didn't want to load my updates...

**Comment by mrdoob** [comment]
> BTW: Is there any advantage from using that rawgit URL? Worked once, then didn't want to load my updates.

Yeah. I don't know what's the best/easy way to pass a new build to jsfiddle to verify its fixed.

I think it's better not to worry about doing the new builds. I can test locally.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Fix confirmed. Thanks!

**Pull request merged**
