### PR TITLE
FBXLoader: Rotate animation fix

### PR DESCRIPTION
**Pull request by mykola-nikoliuk**
Quaternion replaced by Euler

### CODE REVIEW

**Comment by nick-nikoliuk** [comment]
The fix broke some animation. Working on it.

**Comment by looeee** [comment]
I'm not sure that this is the best approach. What do you think of testing for when there are rotation values greater than 2PI and subdividing the values? For examples, your model would go from 

``` 
times = [ 0, 3.333]
values = [0, 0, 0, 0, 0, -17.278]
```

to 

```
times = [0, 1.665, 3.33 ]
values = [0, 0,  -4.7124, 0, 0, -10.995, 0, 0, -17.278 ]
```

Then we can process these new times / values the way we are currently doing, with no need to modify the property bindings file.

**Comment by nick-nikoliuk** [comment]
Yeah, I know that we can use subkeys for that. But designers using 3ds or Maya and they can use "Resample all" or not. When "Resample all" checked, all transformations will be set for each key. It's redundant info increase traffic. Another way, it's to say every new designer make interpolated rotation keys manually. That not a good idea too. I know that my solution isn't great, but together we can found solution.

**Comment by looeee** [comment]
> But designers using 3ds or Maya and they can use "Resample all" or not. 

The goal is that the loader should work for all applications, no matter what settings the user exported with. 

If they export with 'resample all' and create redundant keys, or not, that is their choice and the loader should ideally just handle it gracefully.

**Comment by looeee** [comment]
I've created an alternative to this PR implementing my suggestion above to interpolate large rotation values: #13838

**Comment by nick-nikoliuk** [comment]
Looks very easy and simple. Thanks. @looeee

**Pull request closed without merging**
