### PR TITLE
Updated Draco decoder javascript to the latest version.

### PR DESCRIPTION
**Pull request by ondys**
Moved all Draco related stuff into a separate sub-folder that seems to
be a more common practice when it comes to multi file loaders. We can
keep it as it was if preferred.

We are also going to includ WebAssembly decoder in a separate PR.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@ondys any update on the webasm based decoder?

**Comment by ondys** [comment]
@mrdoob Thanks for the reminder, I'll look into it later this week

**Pull request merged**
