### PR TITLE
Remove deprecated code.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

Some deprecated code can be removed with `r161`.

### CODE REVIEW

**Comment by Mugen87** [comment]
@agviegas The example `webgl_loader_ifc` breaks with this change since https://github.com/IFCjs/web-ifc-three still relies on the deprecated `mergeBufferGeometries()`. 

> Uncaught SyntaxError: The requested module 'three/examples/jsm/utils/BufferGeometryUtils' does not provide an export named 'mergeBufferGeometries' (at IFCLoader.js:4:10)

Do you mind migrating to `mergeGeometries()` and publish a new version of https://github.com/IFCjs/web-ifc-three?

**Comment by agviegas** [comment]
Hey @Mugen87 sure! I can do that tomorrow.
By the way, web-ifc-three is now deprecated. We are now scaling as a company (not just me anymore) and are working on [this new repository](https://github.com/IFCjs/components/), which is much more modular, much faster and will progress a lot this year. I think we have 3 options here (all of them are fine by me)

- Stick with web-ifc-three, I update it and it works again.
- Change to components.
- Remove it from the examples.

Sorry for the inconvenience of these changes. This started as a personal project and now is becoming something much bigger. This wouldn't be possible without your huge work, so I hope that this success will also allow us to give something back to you guys.

PD: We have moved the docs [here](https://docs.thatopen.com/intro), in case you want to update the [three.js page reference to our docs](https://threejs.org/).

**Comment by Mugen87** [comment]
As a quick fix, updating and using `web-ifc-three` is probably best. At a later point and depending on how you (or someone else from the `IFCjs/components/` space) have time, it would be better to switch to components for a more future-proof solution.

**Comment by agviegas** [comment]
Got it @Mugen87! I'll do it tomorrow 🙏

**Comment by agviegas** [comment]
I have just published a new version `0.0.126`. I haven't updated the Worker, which is optional and would require a lot of work. Using the normal loader without worker should be fine. Let me know how it goes!

**Comment by mrdoob** [comment]
The demo requires login? 🤔

Screenshot_20240103-171704

**Comment by agviegas** [comment]
@mrdoob all examples and docs should be open in github pages, like the previous libraries. For instance, [here's](https://ifcjs.github.io/components/src/fragments/FragmentIfcLoader/index.html) the demo for IFC loading.

**Comment by mrdoob** [comment]
I clicked this link:

Screenshot_20240103-231730

**Comment by agviegas** [comment]
My bad, I just updated the link in the README!

**Pull request merged**
