### PR TITLE
WebGLRenderTarget: Support for custom depth and stencil buffers

### PR DESCRIPTION
**Pull request by pailhead**
### Problem

Multiple `WebGLRenderTarget`  can't share the same depth / stencil render buffer because `WebGLRenderer` creates them in a private cache. This is possible to do with webgl, [but not with three.js. ](https://github.com/mrdoob/three.js/issues/15440)

### Proposal

Have the `WebGLRenderer` attempt to use an existing buffer if one is provided. And allow the targets to be used so:

```
targetA.ownDepthBuffer = buffer
targetB.ownDepthBuffer = buffer
```

### Use case

This [depth peel example](https://raw.githack.com/pailhead/three.js/depth-peel-stencil/examples/webgl_materials_depthpeel.html),  goes from not being interactive to working on phones when stencil masking is used ([video](https://www.youtube.com/watch?v=nMfQeotbN8s)).

### Argument for

There are a few things in three.js that already work like this i think. `defines`, `customDepthMaterial` are the two that pop to mind - you could set them, and they would make `WebGLRenderer` do certain things, but were not present in documentation for a long time. This does not change the behavior of the renderer in any way, and allows WebGL to be fully utilized. 

### Optional

Document it:

> Sets the render buffer on the target. If one is not provided, three creates one internally for this target. You can share render buffers between targets:
```
const gl = renderer.getContext()

const buffer = gl.createRenderBuffer()

targetA.ownDepthBuffer = buffer
targetB.ownDepthBuffer = buffer
```

### Future (if accepted)

Make an API:

```
const buffer = new THREE.RenderBuffer(config)

targetA.depthBuffer = buffer
targetB.depthBuffer = buffer
```

### CODE REVIEW

**Comment by pailhead** [comment]
bump

**Comment by MEBoo** [comment]
Hi! 
So are we getting the Deep Peel Demo officially supported?
After that... is complicated to include the new transparency management?
Could be integrated in threejs as an option?

**Comment by pailhead** [comment]
This PR specifically addresses the render buffers of render targets being locked. IMHO three.js is being too opinionated here and would benefit from releasing this lock. Depth peeling is just one of the examples that could leverage this, there are probably more.

**Comment by Ben-Mack** [comment]
Transparency sorting has always been a headache. Would love to see this PR merged to support the depth peel example.

@mrdoob Is there any obstacle preventing this PR being merged?

**Comment by pailhead** [comment]
I have to admit that this is interesting. Why is three.js so opinionated when it comes to this? WebGL allows for this out of the box.

**Comment by anderscognite** [comment]
I would love to see this too!

**Comment by RandomShaper** [comment]
What about this: https://github.com/mrdoob/three.js/commit/e77697f4aaefc5d31ad855d791df69029b0b0513?

I haven't tried it yet, but seems to allow for that.

**Comment by pailhead** [comment]
@RandomShaper 

This looks like it could work. I'll test it.

**Comment by MEBoo** [comment]
@pailhead any news about? we everybody need OIT :)

**Comment by pailhead** [comment]
None unfortunately :( 

And I don’t think this might change any time soon. In the meantime I found more examples of three being opinionated. May be best so look into this class mentioned above, I don’t have time atm.

**Comment by gkjohnson** [comment]
I'll move my question here since the other discussion was closed:

@pailhead Can you explain a bit more about why using DepthTexture wouldn't work? At least on the surface it seems to be what you're interested in, granted it requires an extension to work.

**Comment by DusanBosnjakKodiak** [comment]
@gkjohnson 

In all honesty i didn't give it a shot :) It does look like it could get the job done, but it also seemed like it was using a different path. The way it was achieved requires no extensions (i think). It may be worth a shot.

**Comment by gkjohnson** [comment]
> The way it was achieved requires no extensions (i think). It may be worth a shot.
> ...
> Yeah, now that i've jogged my memory, i got intimidated with the mentions of texture like properties (for example related to mip mapping) that made me decide that this is not suitable.

The depth texture extenion is [supported in every browser](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_depth_texture) so there's no real reason not to use it. And mip map generation isn't required -- it's a really just a depth buffer that can be sampled as a texture in shaders. Other than that it doesn't seem like there's a whole lot that's different so I think it's a good fit for this.

I might interested in depth peeling coming up here, which is why I'm asking. I might give it a go with DepthTexture.

I agree it might be nice to be able to create a shareable depth (and color!) buffer between render targets, though. I think an API like this might fit into three.js' model a bit more:

```js
const renderTarget = new WebGLRenderTarget( 256, 256 );

renderTarget.colorTarget = new ColorBuffer( 256, 256 );
renderTarget.depthTarget = new DepthBuffer( 256, 256 );

// OR

renderTarget.depthTarget = new DepthTexture( 256, 256 );
```

**Comment by Mugen87** [comment]
> The depth texture extenion is supported in every browser so there's no real reason not to use it.

That does not mean each device supports it. The support of WebGL 1 extensions is something you have to check for each user. Except for WebGL 2 rendering contexts.

**Comment by gkjohnson** [comment]
> That does not mean each device supports it. The support of WebGL 1 extensions is something you have to check for each user. Especially on (older) mobile device the support can be still problematic.

Oh okay got it -- might be another reason to support setting a custom non-texture the DepthBuffer, then

**Comment by DusanBosnjakKodiak** [comment]
I have to admit that i'm not entirely clear on the difference. From the description i seem to recall that it should do the same thing. @Mugen87 if this is not supported on some devices (i know some extenions have greated coverage) would it mean the render buffer would work on all?

**Comment by Mugen87** [comment]
Renderbuffers always work. Let's recall that a render target represents a custom framebuffer object. Framebuffers have attachments which represents in some sense the actual buffers that hold rendering data. These data can be save in renderbuffers or textures. The difference between both entities is that you can't sample a renderbuffer like a texture. If you want to implement depth peeling and need to sample depth values in the shader, you need to bind a texture to the framebuffer's depth attachment.

Unfortunately, you can only save depth information directly in a texture with the mentioned extension. If that is missing, you need RGBA depth packing (the primary purpose of `MeshDepthMaterial`) and a separate render pass.

**Comment by gkjohnson** [comment]
@Mugen87 

> Unfortunately, you can only save depth information directly in a texture with the mentioned extension. If that is missing, you need RGBA depth packing (the primary purpose of `MeshDepthMaterial`) and definitely a separate render pass.

I don't think the suggestion is that depth peeling requires sampling a depth buffer but rather that it benefits from reusing an existing depthbuffer when rendering to a different color attachment:

```js
const depthTarget = new DepthTexture( ... );
const renderTarget1 = new WebGLRenderTarget( ... );
const renderTarget2 = new WebGLRenderTarget( ... );

renderTarget1.depthTexture = depthTarget;
renderTarget2.depthTexture = depthTarget;
```

Now `renderTarget2` can reuse the depthbuffer data written when renderTarget1 was rendered to. Beyond depth peeling another use case is using a previously rendered to depthbuffer when rendering something like a normal pass to avoid unneeded fragment calculations (like a depth prepass). The addition of `DepthTexture` inadvertently exposed this ability.

Adding something like a `DepthBuffer()` API might be pretty simply added by modifying the [setupDepthTexture function here](https://github.com/mrdoob/three.js/blob/7c1424c5819ab622a346dd630ee4e6431388021e/src/renderers/webgl/WebGLTextures.js#L928-L970).

**Comment by pailhead** [comment]
I think my example is still using depth packing (there are some issues on ios, which I recall seeing mentioned in another issue). The performance benefit came from being able to write and use the same stencil buffer. I’m still not sure if this is possible with the mentioned class.

**Comment by pailhead** [comment]
@mrdoob @mugen87

Hi guys. This PR has been stuck for a bit with no feedback and no milestone but it’s till open?

What can we expect to happen with this if anything?

**Comment by valenn** [comment]
bump

Is this something that is planned to be merged eventually? Use case I came across is rendering opaque objects to one render target, and then rendering transparents to different render target. It would be nice to reuse depth buffer from opaque pass without copying anything, especially on lower end devices

**Comment by Ben-Mack** [comment]
@mrdoob @Mugen87 Please take a look and merge/give feedback on this PR. As I can see, it's just a simple, non-breaking change that allows greater flexibility and performance enhancements.
Merging this should be no problem.

**Comment by pailhead** [comment]
I think i fixed the conflict. It's been a while and i don't work with three.js professionally at the moment, but i'd be down to implement the depth peeling stuff as a module if this were to land.

**Comment by pailhead** [comment]
I just tried to fix the lint. 

Thought: 

Is this blocked only on account of the name? I am not at all proposing that this thing is called `ownDepthBuffer`, but i am proposing that this thing, whatever it's name, allows for what the description asks for. If there is a better name for this, i'm more than willing to rename it.

**Comment by mrdoob** [comment]
`ownDepthBuffer` doesn't exist in `WebGLRenderTarget`. This PR is missing adding that to `WebGLRenderTarget`.

Plus an example of usage (so people know how to use, and we don't break it).

Docs would be the cherry on top.

**Comment by pailhead** [comment]
Yeey, thanks for the feedback!

I'm going to proceed with the proposed changes, but would like to note a concern:

`Material` doesn't seem to have the `defines` member actually defined: 
https://github.com/mrdoob/three.js/blob/master/src/materials/Material.js

It looks like i wrote the docs for that one :rofl: , but i'm not sure if it's correct, it's not that the key holds a value of `undefined`, it just doesn't exist altogether. I believe the same goes for `customDepthMaterial` if it's used at all anymore. 

I've outlined these in the first post, i'm concerned that the proposal may be inconsistent with the rest of the library . 

My reasoning is that the examples from the first post used to be "secret" and i was hoping to do the same with this.
For all intents and purposes, it would be as if this feature didn't even exist, and hopefully people who were following this PR and https://github.com/mrdoob/three.js/issues/15440 could test it, provide feedback before making it official. 

However, if it lands and something explodes, feel free to ping me :wink:

**Comment by pailhead** [comment]
w00t hopefully all proposed changes have been addressed. I used google translate for the chinese docs.

**Comment by pailhead** [comment]
Hmm, i'm not actually sure how to make this green, this `DeepScan` thing doesn't look like it's at all related to these two loc changes.

**Comment by Ben-Mack** [comment]
@mrdoob This PR seems good to merge now, could you take a look

**Comment by pailhead** [comment]
With the docs in Chinese now, there is potential for many more conflicts. But i don't mind resolving the conflicts over and over, but does anyone know what this `deep scan` thing is complaining about?

**Comment by mrdoob** [comment]
It's not clear to me what the issue is with the `DepthTexture` approach.
Is the problem that it required a WebGL 1 extension? Is that still relevant now that we're moving to WebGL 2?

**Comment by pailhead** [comment]
That’s a good question! This was made though before the webgl 2 move I imagine. It may be totally fixed by webgl 3 :)

**Comment by mrdoob** [comment]
@Ben-Mack Does the `DepthTexture` approach solve your use case?

**Comment by Ben-Mack** [comment]
My main use case is to implement Depth Peeling by @pailhead , he's said this PR is blocking him from releasing a DepthPeel module.
Transparency sorting has always been a headache problem with many issues raised overtime. This PR will make DepthPeel performance reasonable, thus provide a great solution to fix transparency sorting, many will benefit from this I believe.

**Comment by mrdoob** [comment]
I guess we just need someone to try and see if it's possible to do depth peeling using `DepthTexture`.

**Comment by pailhead** [comment]
Oooh, I think this defeats the purpose of the PR then. There was also an issue linked to this with a similar discussion. Depth peeling is not the only thing that this could be used for I imagine. 

It’s a simple issue - if I can hand code some webgl call list, there is no theoretical possibility that I can generate it with threejs. It may be possible to generate a different list that would do the same thing. But if we need someone to investigate that, why just not allow the former?

**Comment by pailhead** [comment]
> I guess we just need someone to try and see if it's possible to do depth peeling using DepthTexture then.

@gkjohnson you mentioned this above, have you ever tried it?

**Comment by gkjohnson** [comment]
> > I guess we just need someone to try and see if it's possible to do depth peeling using DepthTexture then.
>
> @gkjohnson you mentioned this above, have you ever tried it?

I had tried this but unfortunately it doesn't just work. Depth peeling (and other effects) are easier when you can swap out / save / share a depth target but once a render target has been rendered once with a particular depth texture it cannot be changed. See #19447. I think adjusting the WebGLRenderer to be able to detect and change which depth attachment is being used with a target render texture would effectively solve this problem and be aligned with existing three.js APIs.

I think my current hesitation with the currently suggested approach is that it requires the user to create a native GL render buffer instance which isn't required anywhere else in three. And for some context [this demo](https://gkjohnson.github.io/threejs-sandbox/translucent-material/index.html) that implements translucent materials using depth peeling is how I found the issue.

**Comment by pailhead** [comment]
>I think my current hesitation with the currently suggested approach is that it requires the user to create a native GL render buffer instance which isn't required anywhere else in three. 

This has been the case with the stencil buffer for years though. Granted it wasn't plugged directly into a property to be handled by the renderer, but it sort of was when it was plugged into `onBeforeRender` .

There simply was no other way to use the stencil buffer **(a webgl feature)** unless the `gl` context was obtained. Per OP this is advocating for the same treatment. To see if it even works, have this **experimental** feature (it could be documented as such - experimental), which allows to use a webgl feature (just like stencil ops in the past) with three. Unfortunately i think this is much more complicated to setup then just enabling some stencil state before a draw call, using any existing hooks.

**Comment by pailhead** [comment]
Also, come to think of it, what would the API here even do? Looks to me like it could be a constant like `THREE.RenderBuffer` or `THREE.RenderBufferReference` , the default would be `THREE.CreateBufferForTarget` or something along those lines. Point is, it's just a null, or some ref, if two targets have `null` everything happens as it did, it's a noop. If two targets have like `1`, then the renderer would create one buffer, and reuse the cache on the other. Does not look like it would add a lot of code, just some thought needs to be put into how this would look.

`depthBuffer: null | number` seems kinda awkward, it should either be a number or an object that can be compared with `===`

**Comment by gkjohnson** [comment]
> Granted it wasn't plugged directly into a property to be handled by the renderer, but it sort of was when it was plugged into `onBeforeRender`.

I think this is fairly big difference. There was never anything in the API that encouraged running raw gl functions. Stencils were simply never supported and it happened to be the case that you could adjust the stencil flags by hacking the gl context directly.

> Also, come to think of it, what would the API here even do?

In https://github.com/mrdoob/three.js/pull/15490#issuecomment-604668713 I lay out how I think this should look and other use cases. Now that WebGL2 seems to be the norm I'd think it would be okay to require using `DepthTexture` to make reusable depth buffers:

```js
const depthTarget1 = new DepthTexture( ... );
const depthTarget2 = new DepthTexture( ... );
const renderTarget1 = new WebGLRenderTarget( ... );
const renderTarget2 = new WebGLRenderTarget( ... );

renderTarget1.depthTexture = depthTarget;
renderTarget2.depthTexture = depthTarget;

// ...

// this does nothing right now
renderTarget2.depthTexture = depthTarget2;
```

You should be able to change the depth buffer attached to a render target so it can be depth tested against while color is rendered to a different target and then be able to change that depth texture again later. This doesn't work at the moment. As a user the fact that you can't swap out the depth texture after rendering to a target once feels like a bug (though I understand it may not be by the original implementation intent) and imo that should be addressed.

I think the current proposal in this PR is a bit of a half baked implementation to get a hack in to support this feature. I want this, too, for a few reasons including Depth Peeling but imo it should be done correctly and in alignment with the existing three.js APIs.

**Comment by pailhead** [comment]
>  Stencils were simply never supported and it happened to be the case that you could adjust the stencil flags by hacking the gl context directly.

To me this seems like hacking, but much less hacking. You aren’t explicitly setting gl state, you’re just passing in a gl resource. 

I guess it can be said that these are valid concerns but it would have been nice if this was voiced earlier. Especially before asking for docs in Chinese :)

**Comment by gkjohnson** [comment]
> I guess it can be said that these are valid concerns but it would have been nice if this was voiced earlier. Especially before asking for docs in Chinese :)

My previous comments on a different API were an effort to suggest that the proposed solution didn't seem adequate. Sorry for not being more clear. Regarding the docs request - I do agree that there has been a tendency to request more work (docs, examples) which gives the impression that everything else looks good before discussing or committing to whether or not the core feature contribution is mergeable. I agree it's frustrating and hopefully that can be considered in the future.

To that end I want to be clear that these are just my opinions on the topic and I can't speak for the project. I think it would be good if @mrdoob or @Mugen87 could comment on whether what I've suggested is a reasonable solution for this feature if something else is required so someone can work on it if they feel inclined. Depth peeling would be a big step toward better transparency and support for multilayer, depth-aware material transmission.

**Comment by pailhead** [comment]
I can take a look at what’s involved to not use gl

**Comment by gkjohnson** [comment]
Looks like Babylonjs just added support for depth peeling:

https://doc.babylonjs.com/divingDeeper/materials/advanced/transparent_rendering#order-independent-transparency

**Comment by pailhead** [comment]
Also looks like someone has figured out a way to do this. I didn't know `properties` are available, looks like the renderer can be triggered from outside to create the buffer, it doesn't have to be part of the render call. 

https://discourse.threejs.org/t/apply-depth-buffer-from-render-target-to-the-next-render/37276/2

Might still be worth to document this, and maybe look into a cleaner API ie. something that doesn't use the double underscore (eg. `__webglDepthRenderbuffer`)

**Comment by ingun37** [comment]
Hello, Is there an depth peeling example that uses `DepthTexture` approach?

**Comment by gkjohnson** [comment]
Closing in favor of #28584

**Pull request closed without merging**
