### PR TITLE
PerspectiveCamera: Add Kooima's Generalized Projection Formulation

### PR DESCRIPTION
**Pull request by zalo**
Related issue: #5381

**Description**

This PR adds an implementation for [Kooima's Generalized Projection Matrix Formulation](https://web.archive.org/web/20191110002841/http://csc.lsu.edu/~kooima/articles/genperspective/index.html), better known as "the way CAVE and Portal rendering work".

In a nutshell, it sets the camera's quaternion and `projectionMatrix` frustum to exactly frame an arbitrary rectangle.   This is a key operation in rendering portals, CAVEs, and certain kinds of projection based effects.

I find myself porting and reporting this function wherever I go because it's so darn useful.   I'm not certain that this is the right place in the codebase for it, but I'd really love for three.js to have a working implementation for people to use.  Happy to move it to a more appropriate location and/or to add unit tests.

Here's a live demo of the new Portal Example:
https://raw.githack.com/zalo/three.js/feat-generalized-projection/examples/?q=portal#webgl_portal

Portal

Here's a .gif that shows my test implementation:
Kooima

[And here's a fun video I made a while ago in Unity that uses the same formulation.](https://www.youtube.com/watch?v=90kHhOUzeQc&t=1s)

### CODE REVIEW

**Comment by gonnavis** [comment]
Seems used something like [Oblique Near-Plane Clipping](http://www.terathon.com/code/oblique.html), will it distort depthBuffer?

ref: https://github.com/mrdoob/three.js/pull/21574

**Comment by mrdoob** [comment]
Very nice!

Would you be up for also adding an example that shows how to use it to the PR?
Maybe a portal example?

**Comment by WestLangley** [comment]
>it sets the camera's quaternion and projectionMatrix frustum to exactly frame an arbitrary rectangle

Completely arbitrary? Your demo appears to only consider rectangles whose bottom edge is parallel to the x-z plane.

**Comment by zalo** [comment]
> Completely arbitrary [rectangle]? Your demo appears to only consider rectangles whose bottom edge is parallel to the x-z plane.

Sorry; it does work on arbitrary (camera-facing) rectangles, but I made a poor choice of specifying corner manipulations in the gif-demo, so the more interesting movements would have broken rectangliness.

I’m putting together a portal example now that will show off the feature more effectively...

**Comment by zalo** [comment]
Just added the portal example:
https://raw.githack.com/zalo/three.js/feat-generalized-projection/examples/?q=portal#webgl_portal

Hopefully the mirror example fellow doesn't mind me being derivative xD

**Comment by mrdoob** [comment]
Ops! Could you remove the build from the PR?

**Comment by zalo** [comment]
Yep!  (Sorry about that)

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Considering that bundlers can't yet treeshake methods...
I've moved it to a new `CameraUtils` class in the examples folder: https://github.com/mrdoob/three.js/commit/e87bfebbadff63e5208cbb9dffb6418a05f6fc01

**Pull request merged**
