### PR TITLE
CircleBufferGeometry

### PR DESCRIPTION
**Pull request by benaadams**

### CODE REVIEW

**Comment by benaadams** [comment]
Don't merge, think somethings wrong with it

**Comment by benaadams** [comment]
Fixed

**Comment by mrdoob** [comment]
I guess it can be a good test for Interleaved Buffer Geometry. But wouldn't it be better to have all the *BufferGeometry using the same approach?

**Comment by benaadams** [comment]
> I guess it can be a good test for Interleaved Buffer Geometry.

Its just a regular Buffer Geometry, with some Interleaved Attributes

> wouldn't it be better to have all the *BufferGeometry using the same approach?

Change PlaneBufferGeometry? SphereBufferGeometry is uses an InterleavedBuffer; don't think there are any others yet ;-)

The *BufferGeometry are a good candidate for interleaving their standard attributes are position, normal, uv making a nice 8 float chunk; and then you can just add extra regular buffers for extra attributes or any dynamic data like:

````javascript
var geometry = new THREE.SphereBufferGeometry( 10, 16, 16 );
geometry.addAttribute( 'color', new THREE.BufferAttribute( new Float32Array( colors ), 3 ) );
````

As per [Apple OpenGLES Best Practices - Use Interleaved Vertex Data](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW10)

Or with #6472 if you wanted to create a geometry based point cloud of 32000 instanced circle billboards:

````javascript
var particleCount = 32000;
var particleGeo = new THREE.InstancedBufferGeometry()
        .copy( new THREE.CircleBufferGeometry( 1, 16 ) );

var translateScaleArray = new Float32Array( 4 * particleCount );
var translateScaleBuffer =  new THREE.InstancedBufferAttribute( translateScaleArray, 4, 1, true );
particleGeo.addAttribute( "translateScale", translateScaleBuffer );

var particleMesh = new THREE.Mesh( particleGeo, instancedParticleMaterial );

// operate on translateScaleArray 
// then set translateScaleBuffer.needsUpdate = true
````

I'm not sure about changing PlaneBufferGeometry as planes seem to be what most people like to mess with the coordinates most and its been out in the wild. Though I guess you are actually suggesting changing to non interleaved geometries? :-)

**Comment by mrdoob** [comment]
>  Though I guess you are actually suggesting changing to non interleaved geometries? :-)

Yeah... I think it would be better if all the *BufferGeometry used the simpler approach. That way we can still do `THREE.Geometry().fromBufferGeometry()` if needed (and keep that method simple). We could then also do `new THREE.InterleavedBufferGeometry().fromBufferGeometry( new THREE.CircleBufferGeometry( 1, 16 ) )` for your use case.

How does that sound?

**Comment by benaadams** [comment]
> I think it would be better if all the *BufferGeometry used the simpler approach.

Makes sense

> That way we can still do ```THREE.Geometry().fromBufferGeometry()``` if needed (and keep that method simple).

Don't understand? I don't think anything has or needs to change here? I did put a change in for ```BufferGeometry.copy``` #6472 though? But I can't think of a simpler way of doing it that doesn't make it even messier.

> THREE.InterleavedBufferGeometry.fromBufferGeometry

Makes sense, but it would have to make assumptions about the ```BufferGeometry``` so break if their weren't the 3 attributes ```postion```,```normal```,```uv```?

**Comment by benaadams** [comment]
> have to make assumptions about the BufferGeometry

If you are good with this, might be a nice option as it would allow conversion of any geometries

**Comment by mrdoob** [comment]
> Makes sense, but it would have to make assumptions about the ```BufferGeometry``` so break if their weren't the 3 attributes ```postion```,```normal```,```uv```?

How about having an extra parameter to define what attributes should get interleaved?

```javascript
var geometry = new THREE.InterleavedBufferGeometry();
geometry.fromBufferGeometry( bufferGeometry, [ 'position', 'normal', 'uv' ] );`
```

**Comment by benaadams** [comment]
> How about having an extra parameter to define what attributes should get interleaved?

Now you say it...  :smiley_cat:

**Comment by benaadams** [comment]
Uninterleaved

**Comment by benaadams** [comment]
Added example for the instancing conversion I mentioned earlier

**Comment by mrdoob** [comment]
Beautiful! 😃

**Comment by mrdoob** [comment]
Do you mind uninterleaving `SphereBufferGeometry` when you get a moment?

**Pull request merged**
