### PR TITLE
fixing parsing of "d"/"tr" in MTLLoader

### PR DESCRIPTION
**Pull request by blairmacintyre**
The parsing of these two values in the .mtl file was incorrectly looking at the value (a string) when it needed to parse it into a float first.

### CODE REVIEW

**Comment by WestLangley** [comment]
Can you please remove the builds from the PR?

**Comment by mrdoob** [comment]
Yes please

**Comment by blairmacintyre** [comment]
Sorry about that.  fixed.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
