### PR TITLE
Fixed "Texture is not power of two" warning

### PR DESCRIPTION
**Pull request by ghost**
Decal diffuse texture was generating a warning. Created a new decal diffuse along with a new normal map.

### CODE REVIEW

**Comment by WestLangley** [comment]
This is nice!

Given this change, I think `decalMaterial.normalScale` can be increased to `( 0.5, 0.5 )`.

**Comment by redsolarmoon** [comment]
Great suggestion! Much better looking. :) I've added commit.

**Comment by mrdoob** [comment]
Not sure about this... The light now appears obviously wrong (because the decal is rotated).

screenshot from 2015-03-08 17 28 21

You'll notice that some splats have the top area shining and other do not.

**Comment by redsolarmoon** [comment]
Hmm... I see what you mean there. Is this due to how the normal map is setup or how the light is reacting to the normal? Should the light be automatically lighting the normal map correctly?

**Comment by redsolarmoon** [comment]
I removed the uniform shading on the diffuse to perhaps help a bit with perception of the normal lighting.

The other matter is the lighting of the normal maps themselves. The normals are being lit from the light that appears to be anchored to the camera. So, the light is always adjusting. If you rotate the camera, you will see how the light is adjusting along the normals. Do you notice this as well?

I did invert the normal map, which appears correctly now. I think removing the diffuse shading helped notice this better.

**Comment by WestLangley** [comment]
> The normals are being lit from the light that appears to be anchored to the camera.

It is a hemisphere light. It is not anchored to the camera.

> I did invert the normal map, which appears correctly now. I think removing the diffuse shading helped notice this better.

Yes. Those changes were requried.

I think this setting looks best.

    	decalMaterial.normalScale = new THREE.Vector2( 1, 1 );

This now looks good to me with these changes. /ping @mrdoob.

If you don't mind, what tools are you using to create the maps? What are your settings?

**Comment by redsolarmoon** [comment]
I'm using the Photoshop Nvidia NormalMapFilter plugin. Settings are:
4 sample
Invert Y
Scale 8
Average RGB
Alpha Field Height

**Comment by WestLangley** [comment]
Were you not inverting Y previously?

**Comment by redsolarmoon** [comment]
It was not Y-inverted previously.

**Pull request closed without merging**
