### PR TITLE
Unit tests - New PR

### PR DESCRIPTION
**Pull request by Itee**
Next to #12453 but without breaking changes !

### CODE REVIEW

**Comment by Itee** [comment]
Voila !

**Comment by looeee** [comment]
Are all of these tests stubs? I just looked at a few of them and they all seem to be something like

```js
QUnit.test( "Instancing", ( assert ) => {

    assert.ok( false, "everything's gonna be alright" );

} );
```

Apologies if I'm just looking at the wrong ones, it's a lot of files 😛

**Comment by Itee** [comment]
No no you're right, i write all missing skeletons. Currently we can said that all test files are present but not yet implemented for a lot of them.

**Comment by Itee** [comment]
And you can notice too, that all test are marked as todo. 
I'm not alone to write unit tests so i just make a global template for all users that want participate ! 
As soon as this PR will be merge, i will start implementing them with few other devs 😄

**Comment by mrdoob** [comment]
Thanks!

**Comment by Itee** [comment]
🙏

**Comment by duhaime** [comment]
@ltee I clone Three.js, cd into the directory, `npm install && qunit` and get lots of import errors:

```
not ok 319 test/unit/src/utils.tests.js > Failed to load the test file with error:
/Users/yaledhlab/Desktop/three.js/test/unit/src/utils.tests.js:7
import { arrayMin, arrayMax } from '../../../src/utils';
^^^^^^

SyntaxError: Unexpected token import
```

I then `npm test` and get:

```
Yales-MBP:three.js yaledhlab$ npm run test

> three@0.88.0 test /Users/yaledhlab/Desktop/three.js
> qunit test/unit/three.source.unit.js

No files were found matching: test/unit/three.source.unit.js
Error: Process exited before tests finished running
/Users/yaledhlab/Desktop/three.js/node_modules/qunitjs/bin/run.js:26
			const currentTest = QUnit.config.current;
			                         ^

TypeError: Cannot read property 'config' of undefined
    at process.<anonymous> (/Users/yaledhlab/Desktop/three.js/node_modules/qunitjs/bin/run.js:26:29)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process.exit (internal/process.js:158:15)
    at error (/Users/yaledhlab/Desktop/three.js/node_modules/qunitjs/bin/utils.js:37:10)
    at Object.getFilesFromArgs (/Users/yaledhlab/Desktop/three.js/node_modules/qunitjs/bin/utils.js:29:3)
    at run (/Users/yaledhlab/Desktop/three.js/node_modules/qunitjs/bin/run.js:36:22)
    at Object.<anonymous> (/Users/yaledhlab/Desktop/three.js/node_modules/qunitjs/bin/qunit:48:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

Do you know what I'm missing?

Also, did you mean to remove [this file](https://github.com/Itee/three.js/blob/d75c0585f1a7882a100e936e5be0adca4882a66d/test/unit/unittests_editor_toRemoveAfterEditorES6Refactoring.html)?

**Comment by moraxy** [comment]
The

> SyntaxError: Unexpected token import

error might be due to an outdated version. Node implemented the `import` statement only quite recently afaik(v8 possibly?)

**Comment by duhaime** [comment]
@moraxy strange, I just updated right now to 9.2.0:

```
Yales-MBP:three.js yaledhlab$ node --version
v9.2.0
```

Still the same result. Does `npm test` run the tests fine on your machine?

**Comment by moraxy** [comment]
@duhaime ah I see, `npm test` is supposed to be used after running `npm build-test` first to build the missing `test/unit/three.source.unit.js`.  
I seem to remember that being done automatically, but apparently that changed.

**Comment by duhaime** [comment]
@moraxy perfect! Thanks very much!

**Comment by Itee** [comment]
Sorry to being late ! 

Yes you need to build units test before run them, i don't really know if i have the "right" to build it in PR. Like the threejs builds.

@moraxy previously the unit test were build when cloning ??? If it was the case there is a regression...

**Comment by moraxy** [comment]
@Itee no no, I just thought running unit tests did always test if `build-test` was necessary first, but I checked and I was wrong

**Pull request merged**
