### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Did you mean to target the dev branch?

**Comment by kkirsche** [comment]
Nope. Sending it to all bower package masters

**Comment by WestLangley** [comment]
Then, this change will revert next release.

**Comment by kkirsche** [comment]
@WestLangley check your dev branch bud... come on now...

**Pull request merged**
