### PR TITLE
MeshNormalMaterial improvements

### PR DESCRIPTION
**Pull request by WestLangley**
Continuation of #10330

Fixed some bugs. Added support for normal/bump/displacement maps, flat shading, morphs, skinning.

Removed support for clipping ( at least for now ) as the chunk `if-defs` are becoming more and more difficult to get right. I am not sure clipping is a big deal for this material, anyway, as it is primarily a diagnostic tool.

/ping @bhouston

### CODE REVIEW

**Comment by WestLangley** [comment]
Hmm. I miss threejsworker. Here is a screenshot.

screen shot 2016-12-12 at 5 08 34 pm

**Comment by bhouston** [comment]
Very nice. :)  I think this is great.  And all the new features are optional too so that is great.  This will allow for effects like SAO and SSAO to produce better results on models who represent their normals using normal or bump maps.  I can not wait to try it out.  Thank you @WestLangley

**Comment by WestLangley** [comment]
@bhouston This PR was the last straw. I am going to take a stab at implementing https://github.com/mrdoob/three.js/issues/9035. : - )

**Comment by mrdoob** [comment]
Thanks thanks!

**Comment by mrdoob** [comment]
> I am going to take a stab at implementing #9035. : - )

Yay!

**Pull request merged**
