### PR TITLE
Editor: Added submenu navigation

### PR DESCRIPTION
**Pull request by ycw**
Related: #28284

This PR added submenu navigation

- Added box-shadow to menu and submenu for more popover-ish
- Localized the submenu titles 
- Can close #28284

https://github.com/mrdoob/three.js/assets/1063018/6f6a5cb5-1d37-4864-9a24-379244245562

Preview: https://raw.githack.com/ycw/three.js/editor-submenu/editor/index.html

### CODE REVIEW

**Comment by mrdoob** [comment]
Looking good!

**Comment by mrdoob** [comment]
Actually, sorry... Instead of "Geometry" ot should be "Mesh" 🙏

**Comment by ycw** [comment]
done :D

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Few more tweaks: https://github.com/mrdoob/three.js/commit/9f81b724089ceb058522b0b2f92b1668225ce496 https://github.com/mrdoob/three.js/commit/cc9a249ba13b031e92fb12d318dd9c20edb2a48d https://github.com/mrdoob/three.js/commit/c857c1eb6c7bea0d8667d6c742d50550d94cae84 https://github.com/mrdoob/three.js/commit/cf29a58617a0d5e2f068ed9918dc542e8c0ab702 https://github.com/mrdoob/three.js/commit/346814524d163119af2473a399c9b7f864c9f604 https://github.com/mrdoob/three.js/commit/65c4c2704ad9382f4788d771595ec6446cad28f9 https://github.com/mrdoob/three.js/commit/c5ae3486bf678693988bb0e7bc2c4e02f18eb671 https://github.com/mrdoob/three.js/commit/b2e138925361814fa9ec8e3fffbf4cfaab74c1ab

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/assets/97088/d5fb1484-d781-4ec3-8885-aa15e71815b7

**Comment by ycw** [comment]
Good :D

**Comment by ycw** [comment]
what about

```
File 
  New
  Example >     <<<<<< put examples here
  Import
  Export >
```
?

**Comment by mrdoob** [comment]
Good idea!

I think I would then add a couple of `UIHorizontalRule`s.

```
File 
  New
  ---
  Examples >
  ---
  Import
  Export >
```

**Comment by mrdoob** [comment]
While looking at this I wanted to try how it would look like if we listed all the formats that we can import:

Screenshot 2024-05-08 at 8 29 12 PM

Seems way too intimidating...

**Comment by mrdoob** [comment]
Just found out about `<input>`'s `accept` property: https://github.com/mrdoob/three.js/commit/a1317753d899a5a4349cdfc6066002eca1dff588

That way the user can tell what files can be imported.

Before:

Screenshot 2024-05-08 at 8 45 47 PM

After:

Screenshot 2024-05-08 at 8 45 26 PM

**Comment by ycw** [comment]
> Just found out about < input > 's accept property: https://github.com/mrdoob/three.js/commit/a1317753d899a5a4349cdfc6066002eca1dff588

Good, and remember that `accept` list must be in sync with Loader.js https://github.com/mrdoob/three.js/pull/28295#discussion_r1590734928

**Pull request merged**
