### PR TITLE
PR resolves issue #14104

### PR DESCRIPTION
**Pull request by DOSputin**
Resolves issue: #14104 

**Description**
re-implementation of  @mbalex99 alpha method

### CODE REVIEW

**Comment by mrdoob** [comment]
Oh, seems like the whole file has been reformatted: https://github.com/mrdoob/three.js/pull/23356/files

That makes it pretty much impossible to see what it is that changed in order to review it... 😕

**Comment by DOSputin** [comment]
> Oh, seems like the whole file has been reformatted: https://github.com/mrdoob/three.js/pull/23356/files
> 
> That makes it pretty much impossible to see what it is that changed in order to review it... 😕

ʕ ͡° ʖ̯ ͡°ʔ   

I disabled formatter in Sublime to avoid this dang it!   the TS version must have been clobbered by the guys editor.. 

Let me address that, and I'll push up a less clobbered version.  
Sorry.

**Comment by VanderSP** [comment]
Hey, I admire all efforts from threejs team, awesome library getting better and better! I was just needing the alpha back, in a very misterious synch they got fixed by this moments lol

Sorry my noobness, but those import paths should not be ../ instead three/  ? (i mean about the pr) im monkey patching it r8 now to node... luck that i already bumped .5 lol :D

**Comment by DOSputin** [comment]
>../ instead three/ ? (i mean about the pr) im monkey patching it r8 now to node... 
in my haste trying to hack on this during a lunch break at the day job, i inadvertently pushed the wrong local branch.  
won't have time until this evening (PST) or later this weekend to fix my f*ck-up.  

Again.  v v sorry for the mess.. ʕ ͡° ʖ̯ ͡°ʔ

**Comment by VanderSP** [comment]
Ah, so i was trying to patch the same thing, just diff formatting lol

**Comment by DOSputin** [comment]
@mrdoob Okay bab28e0 hopefully is less of a clusterfuck.   
https://github.com/mrdoob/three.js/pull/23356/files?diff=unified&w=1

**Comment by VanderSP** [comment]
Strange, when i paste this new code on my node and re run npm run dev... i dunno it still black background! the only time i´ve got success was using by myself the original 99 guy code...any clue?

**Comment by DOSputin** [comment]
> Strange, when i paste this new code on my node and re run npm run dev... i dunno it still black background! the only time i´ve got success was using by myself the original 99 guy code...any clue?

this is really not the place for resolving your implementation questions.  
my suggestion that you go back to #14104 and read up / ask questions there.

**Comment by LeviPesin** [comment]
I think if you run `npm run lint` then it will fix your linting changes (possibly...). Also, please remove the build file (i.e. that one that is located in `js` folder instead of `jsm`).

**Comment by Mugen87** [comment]
The PR can be reopened when the formatting issues are fixed, see https://github.com/mrdoob/three.js/pull/23356#issuecomment-1023567022.

**Pull request closed without merging**
