### PR TITLE
WebGLRenderer: reimplement onBeforeRender()

### PR DESCRIPTION
**Pull request by WestLangley**
`onBeforeRender()` is not called for objects that are not renderable, such as a light helper that has only renderable children.

With this change, the light helpers can be implemented using `onBeforeRender()`, instead of requiring the user to call `update()`. See https://github.com/mrdoob/three.js/pull/11515#issuecomment-311222622.

`onAfterRender()` can be implemented in a similar fashion -- or removed.

### CODE REVIEW

**Comment by WestLangley** [comment]
Related: #11306

**Comment by mrdoob** [comment]
I don't think this is a good idea. Right now the `onBeforeRender()` is only called before the object is about to get rendered. With your suggestion the method would be called even if the object is culled.

In the case of [Mirror](https://github.com/mrdoob/three.js/blob/dev/examples/js/Mirror.js#L183-L206), we would be doing extra renders even if it's not visible.

This whole `omBeforeRender()` thing is bit delicate...

**Comment by WestLangley** [comment]
There are tradeoffs. Doing what I propose is equivalent to calling update() in the animation loop just prior to calling render().

`onBeforeRender` is a property of each `Object3D` -- not of just renderable objects.

Think of a Collada model, for example.
```
colladaModel.onBeforeRender = function() { this.lookAt( camera.position ) };
```

The current implementation does not support this pattern. This PR does.

**Comment by mrdoob** [comment]
I see... Maybe what you're really proposing is a adding a new `onUpdate()` though?

**Comment by fernandojsg** [comment]
+1 for a `onUpdate/onTick`, but I agree that it should be different in concept and use from `onBeforeRender`

**Comment by WestLangley** [comment]
>Maybe what you're really proposing is a adding a new onUpdate() though?

I am simply proposing that `onBeforeRender()` be called for every `Object3D`.

> it should be different in concept and use from onBeforeRender

Why do you say that? What is the use case for which the two methods are conceptually different?

**Comment by fernandojsg** [comment]
Like you said, `onUpdate/onTick` is being called on all the objects before the render loop will start. `onBeforeRender` just on the objects that are going to be rendered and just right before doing it.

**Comment by WestLangley** [comment]
@fernandojsg I want to understand what you are saying... What is a use case for which two methods are required?

**Comment by mrdoob** [comment]
Basically, right now `onBeforeRender()` is being called before the object is being rendered. If the object is not visible then the method is not called.

What you're proposing is a method to ping all the objects in the scene graph so they know they're going to be considered for a render. I think that concept fits more with `update`.

I think having both, `onBeforeRender()` and `onUpdate()` makes sense.

**Comment by fernandojsg** [comment]
That's it, I think both are useful. The new `onUpdate` could be used the same way we do on `entity.update` on aframe or the `update` method on unity so you just add your per frame logic to the object and forget about calling that function yourself in your loop.

**Comment by WestLangley** [comment]
OK. What is your preferred nomenclature?
```
.onUpdate()     // defined on all Object3D
.onPreRender()  // defined on renderable objects only, called just prior to rendering
.onPostRender() // defined on renderable objects only, called just after rendering
```

**Comment by mrdoob** [comment]
You prefer `onPreRender()` and `onPostRender()` instead of `onBeforeRender()` and `onAfterRender()`?

I think I would just add `onUpdate()` to `Object3D` for now.

**Comment by WestLangley** [comment]
>I think I would just add onUpdate() to Object3D for now.

OK. WIll do.

Closing this.

**Pull request closed without merging**
