### PR TITLE
EXRExporter: implements support for DataTexture export

### PR DESCRIPTION
**Pull request by sciecode**
Implements changes discussed in #26681.

Since it's been a couple of weeks without any follow-ups on the changes, I've decided to go ahead and implement the proposed API changes to support exporting `DataTexture`. Also includes better error handling for non-supported `WebGLRenderTarget` variations.

There's just an API question I'd like to confirm with @Mugen87, before updating docs page with the new arguments and setting PR as "ready to merge"

In this PR, I've followed the interface used by `KTX2Exporter`. Specifically, using the first argument to infer the internal workflow for the exporter. However, unlike `KTX2Exporter`, there's also an optional third argument `options` which defines output information for file.

For the existing interface, it follows: 

```js
exporter.parse( renderer, renderTarget, options );
```

But, in order to provide the options for this PR's new interface with `DataTexture`, we are forced to introduce an `undefined` (ignored) second parameter:

```js
exporter.parse( dataTexture, undefined, options );
```

Should we treat the second argument as `options` for when DataTexture is used, or do you believe that would confuse users?

### CODE REVIEW

**Comment by Mugen87** [comment]
> Should we treat the second argument as options for when DataTexture is used, or do you believe that would confuse users?

The arguments are already variable in their types so I don't think it's too confusing. The exporter basically provides `parse()` as two overloaded methods.

**Comment by sciecode** [comment]
Ready to review / merge.

**Comment by Mugen87** [comment]
Looking good!

Would you be willing to add `misc_exporter_exr` as an example? It would be good to have a demo so we can easier test the exporter.

**Comment by sciecode** [comment]
> Would you be willing to add `misc_exporter_exr` as an example? It would be good to have a demo so we can easier test the exporter.

Sure! Will try to work on something, should have some ideas by the weekend.

**Comment by Mugen87** [comment]
The example can be as simple as https://threejs.org/examples/webgl_loader_texture_hdr. Probably with texture selection and some export options.

**Comment by donmccurdy** [comment]
I'd also be fine with changing KTX2Exporter to an API like...

```js
exporter.parse( renderTarget, { renderer } );
```

... if that works better for EXRExporter too.

**Comment by sciecode** [comment]
I think it's better if we keep the required inputs outside of object arguments, much like most core APIs.
Also, we avoid breaking changes that way. I find the current API for both `KTX` and `EXR` pretty reasonable and consistent.

```js
ktxExporter.parse( renderer, renderTarget );
exrExporter.parse( renderer, renderTarget, options );

ktxExporter.parse( dataTexture );
exrExporter.parse( dataTexture, options );
```

With the only difference being that `EXRExporter` allows for an extra options for output config.

**Comment by donmccurdy** [comment]
I'm fine with it either way! If there started to be *more* required arguments for certain cases, like `parse( x, y, z, w, options )` then I would certainly roll them into the options object if they're only conditionally required. Also for async exporters you avoid this stuff:

```js
parse( x, y, ..., onLoad, onError, options );
```

Maybe best to just match what KTX2Exporter does for now yes, and we can make changes if the pattern isn't working well for other exporters.

**Comment by sciecode** [comment]
> Maybe best to just match what KTX2Exporter does for now yes, and we can make changes if the pattern isn't working well for other exporters.

Agreed, sounds good to me.

**Comment by sciecode** [comment]
Added [misc_exporter_exr](https://rawcdn.githack.com/sciecode/three.js/86c70de7133b7eafdea5764c3bfc544b66d22c07/examples/misc_exporter_exr.html?min=1) - example of exporting PMREM & DataTexture.

**Pull request merged**
