### PR TITLE
ColladaLoader: Check if mesh exists before working with it

### PR DESCRIPTION
**Pull request by cnspaha**
There is the possibility that there isn't a 'mesh' attribute in the 'geometry' one so we should check if we found a mesh before trying to access its properties. 
See Image below with the .dae file on the right and the error when there is no 'mesh' in 'geometry' on the left. 
The used file is attached. (Standing_table.zip)
image

@Mugen87 
Since you are the author of the loader, any opinion? ;)

[Standing_table.zip](https://github.com/mrdoob/three.js/files/1454495/Standing_table.zip)

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, i've never seen the tag `convex_mesh` 😮 . 

Maybe we can rewrite the function like this. The comment will point to this thread from more information.

```javascript
function parseGeometry( xml ) {

	var data = {
		name: xml.getAttribute( 'name' ),
		sources: {},
		vertices: {},
		primitives: []
	};

	var mesh = getElementsByTagName( xml, 'mesh' )[ 0 ];

	// geometry may contain tags like "convex_mesh" which are not supported, see #12606

	if ( mesh !== undefined ) {

		for ( var i = 0; i < mesh.childNodes.length; i ++ ) {

			var child = mesh.childNodes[ i ];

			if ( child.nodeType !== 1 ) continue;

			var id = child.getAttribute( 'id' );

			switch ( child.nodeName ) {

				case 'source':
					data.sources[ id ] = parseSource( child );
					break;

				case 'vertices':
					// data.sources[ id ] = data.sources[ parseId( getElementsByTagName( child, 'input' )[ 0 ].getAttribute( 'source' ) ) ];
					data.vertices = parseGeometryVertices( child );
					break;

				case 'polygons':
					console.warn( 'THREE.ColladaLoader: Unsupported primitive type: ', child.nodeName );
					break;

				case 'lines':
				case 'linestrips':
				case 'polylist':
				case 'triangles':
					data.primitives.push( parseGeometryPrimitive( child ) );
					break;

				default:
					console.log( child );

			}

		}

		library.geometries[ xml.getAttribute( 'id' ) ] = data;

	}

}
```

**Comment by cnspaha** [comment]
> Um, i've never seen the tag convex_mesh 😮 .

@Mugen87  Take a look at https://www.khronos.org/files/collada_spec_1_5.pdf
page 82, there the geometry element is described.
According to this specification (collada spec 1.5)  there could be also a 'spline' or 'brep' child element. So there are four possible child elements for geometry. 'mesh', 'convex_mesh', 'spline', 'brep'
image
But mine and also your code (which area the same in logic terms) should handle that fine.

Is there are reason you prefer a '!== undefined' check over a check if the element isn't available and return then?
But I like the idea with the comment ;) But we would also have to add 'spline' and 'brep' to it :)

**Comment by Mugen87** [comment]
It's just a personal preference. If you are not happy with it, we can keep your suggestion. But please with this code style:
```javascript
if ( mesh === undefined ) return;
```
What do you think?

**Comment by cnspaha** [comment]
Yeah sounds good to me, will edit it.

**Comment by cnspaha** [comment]
@mrdoob 
do you mind checking/approve this single line change and merge it? ;)

**Comment by Mugen87** [comment]
Can you also add mentioned comment? Something like:
_the following tags inside geometry are not supported yet (see #12606): convex_mesh, spline, brep_

**Comment by cnspaha** [comment]
> Can you also add mentioned comment? Something like:
the following tags inside geometry are not supported yet (see #12606): convex_mesh, spline, brep

ah yeah sorry, forgot about that ;) will add it

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
