### PR TITLE
TS: Export TextGeometryParameters

### PR DESCRIPTION
**Pull request by Methuselah96**
**Description**

https://github.com/mrdoob/three.js/pull/20437 is helpful in adding missing exports, but it removed exporting some helpful interfaces like `TextGeometryParamters`. It's a much better experience to be able to do:
```
import { Geometry, Material, MeshBasicMaterial, TextGeometryParameters } from 'three';
```
rather than:
```
import { Geometry, Material, MeshBasicMaterial } from 'three';
import { TextGeometryParameters } from 'three/src/geometries/TextGeometry';
```

### CODE REVIEW

**Review by Mugen87 — CHANGES_REQUESTED** [review]
This PR seems to introduce multiple linter warnings.

**Comment by Methuselah96** [comment]
@Mugen87 Thanks for noticing. Any reason not to make the ESLint config have those rules be errors instead of warnings so that the CI will fail?

**Comment by DefinitelyMaybe** [comment]
> ... to make the ESLint config ...

@mrdoob has a preference for less configs last time I checked.

From your knowledge, can you turn the package.json eslint rules from warnings to errors?

**Review by Mugen87 — APPROVED** [review]

**Comment by Methuselah96** [comment]
@DefinitelyMaybe Yeah, just change the 1's to 2's. Should I make a PR?

**Comment by DefinitelyMaybe** [comment]
Give it a go. My brains trying to think about un-intended consequences (like what I came up against when I added the `"lint-fix"` rule within the `package.json` file). coming up blank atm.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
