### PR TITLE
Indexed Buffer from Geometry

### PR DESCRIPTION
**Pull request by benaadams**
(Do not merge, has UV bug) Added method fromGeometryIndexed

### CODE REVIEW

**Comment by benaadams** [comment]
Not sure what's wrong, has UV bug, but decided to share anyway :P

Example of issue:
```javascript
var isoGeometry = ( new THREE.BufferGeometry() )
    .fromGeometryIndexed( new THREE.IcosahedronGeometry( 10, 3 ) );
```
When applying map to the generated buffergeometry; it has a UV seam that looks weird.

**Comment by benaadams** [comment]
Also works the instanced buffers #6242 so you can go:
```javascript
var isoGeometry = ( new THREE.InstancedBufferGeometry() )
    .fromGeometryIndexed( new THREE.IcosahedronGeometry( 10, 3 ) );
isoGeometry.addAttribute( 'orientation', new THREE.InstancedBufferAttribute(....
```
Still has uv bug though :(

**Comment by benaadams** [comment]
uv seam issue can be seen in: http://prealpha.ageofascent.com/examples/webgl_materials2-fg.html working on it

**Comment by WestLangley** [comment]
With regular geometry, vertices can be shared. When you convert to indexed geometry, you can only share vertices when _all_ attributes are identical for that vertex. Otherwise, the vertex must be duplicated.

Vertices on UV seams must be duplicated -- at a minimum. The remaining vertices must be duplicated if the shared faces have different vertex normals, colors, etc. for that vertex.

**Comment by benaadams** [comment]
Ah, is regular geometry not indexed geometry? Makes things more complicated...

**Comment by benaadams** [comment]
Understand a bit more; are indexed, but need code from setMeshBuffers which does a bit more fancy stuff before converting to buffers

**Comment by benaadams** [comment]
@mrdoob looks like you are already doing this?

**Comment by benaadams** [comment]
@mrdoob happy to code the .fromGeometry to do indexed and convert full regular geometries, now I understand how they work a bit better; but it looks like you are already going that direction with the latests commits?

**Comment by mrdoob** [comment]
Yeah... I guess we'll have to force `IndexedGeometry`. Otherwise it will be hard to match dynamic geometries. I need to give it a try and see what it is that we lose. I remember `IndexedGeometry` didn't allow FlatShading, but now that it's being done in `MeshPhongMaterial` directly it is less of a problem. Maybe multiple uvs per vertex? We'll have to see.

**Comment by mrdoob** [comment]
I'll have a look at this PR.

**Comment by benaadams** [comment]
Am just finishing an alt PR for this... :D 

Staying away from skinning and morph targets though as don't really understand them

**Comment by benaadams** [comment]
Is PR #6377 potentially renumbers the indexes so might be problematic for dynamic geometries but should work for other cases

**Comment by benaadams** [comment]
#6377 working for dynamic geometries and for draw call chunking gemoetries

**Pull request closed without merging**
