### PR TITLE
More efficient ray-box intersection functions

### PR DESCRIPTION
**Pull request by Labrium**
Related issue: #26937

**Description**

This PR implements the new ray-box intersection function outlined in the related issue.

### CODE REVIEW

**Comment by Mugen87** [comment]
Um, it seems some unit tests for `Ray.intersectBox()` fail with this PR.

**Comment by Labrium** [comment]
It looks like the tests failed because in JavaScript `Math.min(1, 0/0)` is `NaN` instead of `1`...

**Comment by WestLangley** [comment]
This PR appears to generate false positives.

Can you please provide evidence that both methods produces the same output as the existing code -- or evidence of a bug if there is one?

Also, can you quantify the performance difference?

**Comment by Labrium** [comment]
Sorry, I'm still working on it. Like I said before, this is my first real contribution so I'm not exactly sure how to interpret the unit testing logs or even what professional benchmarks are supposed to look like...

**Comment by WestLangley** [comment]
OK. Don't worry about the performance test. Just see if you can ensure the results are correct. Thanks for your contribution!

**Comment by Mugen87** [comment]
Converting this PR into "draft" status in the meanwhile.

**Comment by sciecode** [comment]
The original implementation presented in the paper was designed for shader, some of the assumptions used cannot be easily reproduced or matched in Javascript. As you might've noticed yourself with the problems relating to `NaN` comparisons and `min/max` functions. 

There's also one extra thing to keep in mind, the original implementation was inconsistent when it comes to handling corners, coplanar ray & ray originating from one of the faces. On some instances it treats the bounding box as inclusive, in order cases it doesn't. 

Our current implementation treats all edges/faces inclusively. In order to keep backwards compatibility, it would be preferred to keep it that way.

I've sketched an implementation that tries to accomodate for all of these pre-requisites, and have ran against our current test suite and a few extra edge cases. I haven't, however, ran a more extensive performance test, that would be recommended. But I have no reason to believe it would be slower than the current approach.

```js
intersectBox( box, target ) {

    const invDist = _vector.set( 1, 1, 1 ).divide( this.direction );

    const t0 = _edge1.set( 
        ( box.min.x - this.origin.x ) * invDist.x || Infinity * Math.sign( invDist.x ),
        ( box.min.y - this.origin.y ) * invDist.y || Infinity * Math.sign( invDist.y ),
        ( box.min.z - this.origin.z ) * invDist.z || Infinity * Math.sign( invDist.z ),
    );
    const t1 = _edge2.set(
        ( box.max.x - this.origin.x ) * invDist.x || Infinity * Math.sign( invDist.x ),
        ( box.max.y - this.origin.y ) * invDist.y || Infinity * Math.sign( invDist.y ),
        ( box.max.z - this.origin.z ) * invDist.z || Infinity * Math.sign( invDist.z ),
    );

    const tmin = _vector.copy( t1 ).min( t0 );
    const tmax = t1.max( t0 );

    const pmin = Math.max( tmin.x, Math.max( tmin.y, tmin.z ) );
    const pmax = Math.min( tmax.x, Math.min( tmax.y, tmax.z ) );

    const intersects = pmin <= pmax && ( pmax >= 0 || pmin >= 0 ) && ( isFinite( pmin ) || pmin != pmax );

    if ( ! intersects ) return null;

    return this.at( ( ( pmin * pmax > 0 ) ? pmin : pmax ) || 0, target );

}
```

**Comment by Mugen87** [comment]
@sciecode Thanks for the additional insights. If there isn't an advantage regarding the instruction count, I would prefer to keep the implementation as it is. 

Of course a performance comparison could also be beneficial but I've made the experience that you easily get different numbers depending on the platform, browser and device you are testing. So a meaningful is quite sophisticated and I'm not sure it's worth regarding the potential benefits (simply because the current implementation isn't that bad).

**Comment by sciecode** [comment]
I've ran some tests in order to quantify the performance differences on multiple devices. The naive implementation above is significantly slower than our current approach, on the order for 15%-30% slower, even after micro-optimizing the operations and inlining most `Vector3` ops, it is still about 5%-15% slower.

Turns out having to deal with `NaN` & handle edge cases negates most of the benefits of this implementation on JS. Just for the sake of completeness, I've also ran a version that ignores `NaN`, and in that case it does ran 10%-15% faster, but it generates incorrect results.

It is possible generate a more efficient solution for the cases where intersections are non-inclusive, but I don't see this being preferable for us. All in all, I believe we're better off keeping our current approach.

**Pull request closed without merging**
