### PR TITLE
Docs: Explain the 2D contour

### PR DESCRIPTION
**Pull request by qifei**
state the format of a contour as a argument

### CODE REVIEW

**Comment by Mugen87** [comment]
Please remove the link since there is no guarantee that it will not break in the future. `An array of THREE.Vector2()` should be sufficient.

**Comment by Mugen87** [comment]
Please remove the link since there is no guarantee that it will not break in the future. `An array of THREE.Vector2()` should be sufficient.

**Comment by qifei** [comment]
removed

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
@qifei I think @Mugen87 suggested removing ", according to the definition of this method".

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
