### PR TITLE
Fixes #12201 When using a texture non POT, use the previous POT size

### LINKED ISSUE #12201: texture max size
It could be good idea to limit texture size by some user setting, not just round up to next power of two or use max value reported by system. Otherwise we get this:
screen shot 2017-09-15 at 0 36 28

ios also says the max size is 4096, for example, but using it triggers visible bugs, so you dont want 4K textures there.

### PR DESCRIPTION
**Pull request by fernandojsg**
Re https://github.com/mrdoob/three.js/issues/12201

### CODE REVIEW

**Comment by fernandojsg** [comment]
I just realized that maybe we should use another naming or at least modify the comment in doc, as if using `previousPOT(4096)` you'll get 4096 not 2048?
/cc @mrdoob @makc

**Comment by mrdoob** [comment]
How about `ensurePOT()`?

**Comment by mrdoob** [comment]
Could just be a internal function in `WebGLTextures` no need to put it on `Math` I think.

**Comment by mrdoob** [comment]
Hold on. `Math` already has a `nearestPowerOfTwo()` function.

**Comment by mrdoob** [comment]
I think this has been like this for a while now. @makc is using `r79`.

**Comment by mrdoob** [comment]
Oh, I just noticed the `Math.floor` instead of `Math.round`.

**Comment by mrdoob** [comment]
I'm tempted to just change the code inside `nearestPowerOfTwo`.

**Comment by mrdoob** [comment]
What do you think @WestLangley?

**Comment by WestLangley** [comment]
I would opt for clarity. For example:
```javascript
smallestPOTGreaterThanOrEqualTo( value )

largestPowerOfTwoLessThanOrEqualTo( value )
```
and make sure the methods are doing what we think they are.

**Comment by fernandojsg** [comment]
So with the @WestLangley proposal, it should look like this
```
nextPowerOfTwo -> smallestPowerOfTwoGreaterThanOrEqualTo( value )
previousPowerOfTwo -> largestPowerOfTwoLessThanOrEqualTo( value )
nearestPowerOfTwo -> nearestPowerOfTwoTo( value )
```
@mrdoob what do you think?

**Comment by WestLangley** [comment]
That's fine. But in that case, the docs should state exactly what the methods do.

**Comment by mrdoob** [comment]
> That's fine. But in that case, the docs should state exactly what the methods do.

Yep. Just updated it. https://github.com/mrdoob/three.js/commit/31e8e610b6ad86aca97c24c71fd4ebc6b5bfa259

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by fernandojsg** [comment]
cool!

**Pull request closed without merging**
