### PR TITLE
Added 'annotate' utility to slice JSON-from-3DS-Max animated model into multiple animations

### PR DESCRIPTION
**Pull request by and3rson**
Recently I saw that `ThreeJSAnimationExporter.ms` cannot export multiple animations.

So I decided to write a small app that refactors THREE.js JSON model splitting `Action` animation into other different animations.

Basically, what it does is:
- Takes out single `animation` from JSON file (named `Action`);
- Creates few different animations based on animation names & frame ranges provided;
- Dumps them under `animations` key.

Example usage:

```
$ annotate.py -i model.js -o model.new.js idle=1..10 walk=11..20
```

README.md is included in the pull request.

Glad if it is useful!

### CODE REVIEW

**Comment by mrdoob** [comment]
Shouldn't it sit in https://github.com/mrdoob/three.js/tree/master/utils/exporters/max instead?

**Comment by and3rson** [comment]
@mrdoob I can move it. I just added it to `converters/` dir because it's not an exported, but converter from 1 animation to multiple. And it works for any `JSON` models, not just exported from 3DS Max

**Comment by mrdoob** [comment]
`converters/` folder is for scripts that convert OBJ to JSON or similar. Your script is designed to handle a limitation of the 3DS Max exporter.

**Comment by and3rson** [comment]
@mrdoob Moved under `utils/exporters/max/`

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
