### PR TITLE
fix for thick line dashed example

### PR DESCRIPTION
**Pull request by pailhead**
Added a little epsilon to get rid of the fuzziness. 

https://github.com/mrdoob/three.js/issues/14197

### CODE REVIEW

**Comment by looeee** [comment]
https://rawgit.com/pailhead/three.js/a4ad6f5458e7a454d728fc60920764fd4c2136ba/examples/webgl_lines_fat.html

**Comment by pailhead** [comment]
I don't know what's the right thing to do here, maybe the value could be smaller, maybe the cap mask could be scaled somehow, i know you can flip bits with floats i just dont know how to do it :(

**Comment by WestLangley** [comment]
What problem is this solving and how is this change solving it?

**Comment by pailhead** [comment]
Someone posted that screenshot in the linked issue, this fixes it by moving the clipping of the endcaps slightly towards the end caps. If the value is small enough this shouldn't show up, if it's larger there could be some artifacts. But it solves the fuzziness from the imprecise value.

**Comment by pailhead** [comment]
Did it fix it for you @looeee , the link works for me?

**Comment by pailhead** [comment]
Maybe this could benefit from a different approach, this is a bandaid, I think there needs to be a distinct value in the body.

**Comment by Usnul** [comment]
I still see some breakage, but it's rather minimal.

**Comment by Mugen87** [comment]
I don't think using the values `0.49999` and `0.50001` is robust since such tolerance values significantly depend on the scale of the geometry. I assume they are chosen more or less arbitrary right now. They maybe solve this particular example but not others.

**Comment by Mugen87** [comment]
@pailhead How did you determine the values `0.49999` and `0.50001`?

**Comment by pailhead** [comment]
I didn’t, I imagined the numbers are just stretched over those middle polygons, and tried to shift the clipping. I need to study this a bit more.

**Comment by pailhead** [comment]
I thought i could get rid of the epsilon if make an uv split for the body, But it didn't quite work, i think it has a problem with checking for that 0.5 value without even the interpolation. 

In this last diff i added another attribute value, 0 or 1 if it's end cap or not.

**Comment by pailhead** [comment]
>I don't think using the values 0.49999 and 0.50001 is robust since such tolerance values significantly depend on the scale of the geometry. I assume they are chosen more or less arbitrary right now. They maybe solve this particular example but not others.

It doesn't actually depend on the scale of the geometry, but you're right they are chosen arbitrary. I think overall that these equality checks for floats don't work with shaders but i don't quite understand why. Whenever you want to check for a float, it's good to make it fuzzy.

**Comment by pailhead** [comment]
Slightly different results, from #14279, maybe we could look into not clipping all the caps for dashed.

**Comment by mrdoob** [comment]
Merged #14275 instead.

**Comment by mrdoob** [comment]
Thanks though!

**Comment by pailhead** [comment]
@mrdoob you think the extra checks are worth it?

**Comment by pailhead** [comment]
btw why did we need another PR for this? Wouldn't it be easier to review one? @mrdoob @WestLangley

**Comment by mrdoob** [comment]
> btw why did we need another PR for this? Wouldn't it be easier to review one? @mrdoob @WestLangley.

Could we just move on instead of discussing this?

There are a lot of pending PRs that are being delayed because I'm trying to catch up with the extensive discussions that have been happening over the previous days 😟

**Comment by mrdoob** [comment]
If you think your PR was better than the one that was merged I'd be happy to discuss that. Otherwise, I would prefer to keep moving.

**Comment by pailhead** [comment]
>If you think your PR was better 

@mrdoob 
I think it's not obvious, it would be beneficial to discuss it. I'm not sure if either is better. The other one has three times as many checks going on (9 vs 3). I don't actually know how this impacts things. 

I think it might be better just on account of this, but it also yielded slightly different visual results. I rely a lot on thick lines, in my day to day life, i'd like to follow the development of this.

**Comment by WestLangley** [comment]
@pailhead Thank you for pointing out that the following change in your code removed the artifacts for you:
```javascript
if ( vUv.y < 0.49999 || vUv.y > 0.50001 ) discard;
```
It was then clear to me that an attribute that was assumed to be a constant 0.5 across the face of the primitive was not guaranteed to be so in practice -- at least not on certain hardware.

My solution in #14279 was to change the model so the assumption of the constant attribute was no longer required. This was an easy and trivial change. I filed a PR because that was my preferred solution.

---

On a related matter, this "fat line" feature was difficult to get right, and the implementation is not easy to understand. Consequently, I wrote the code with clarity in mind. The only reason to further modify the code for performance reasons is if there is a demonstrated performance issue.

**Comment by pailhead** [comment]
Fair enough, this does make sense. Doing `bool isSomething;` might make sense too though, from a readability standpoint. Thanks for clarifying.

**Pull request closed without merging**
