### PR TITLE
OBJLoader example: load all assets before adding object to the scene

### PR DESCRIPTION
**Pull request by WestLangley**
It was not clear to me we had an example of this use case. If not, here is one.

Maybe this PR can be further improved...

### CODE REVIEW

**Comment by Mugen87** [comment]
See:

https://github.com/mrdoob/three.js/blob/4a4123206826429d154d1df9e9ef74560ae13dcd/examples/webgl_loader_collada.html#L69-L82

Anyway, I think it's okay to show the usage of `LoadingManager` multiple times.

**Comment by WestLangley** [comment]
The Collada  example is using the loading manager to load just a single model, but the loader itself uses the manager internally.

I added a log to `ColladaLoader`:
```javascript
var texture = loader.load( image, function () { console.log( 'loaded ', image ) } );
```
and to the Collada example:
```javascript
scene.add( elf );
console.log( `added model to scene` );
```
The model is, in fact, added to the scene after the textures load.

That's not just luck, right? :-)

**Comment by mrdoob** [comment]
> Anyway, I think it's okay to show the usage of `LoadingManager` multiple times.

👍

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
/ping @Mugen87 

>The model is, in fact, added to the scene after the textures load.

Does the loader ensure that, or is that luck?

**Comment by Mugen87** [comment]
In case of `ColladaLoader`, `FBXLoader` or `OBJLoader` it's like this: If you are using the `onLoad()` callback of the loaders `load()` method, you are not waiting for all related assets like textures. You have to use `LoadingManager`'s `onLoad()` for this. 

You maybe don't see this effect when textures are cached by the browser. If you load the following example for the first time, you should clearly see that the model pops up before the diffuse map is added.

https://threejs.org/examples/webgl_loader_collada_skinning.html

Other loaders like `ObjectLoader` or `GLTFLoader` are implemented differently and always wait for all assets.

**Comment by WestLangley** [comment]
>Other loaders like ObjectLoader or GLTFLoader are implemented differently and always wait for all assets.

That's got to be confusing to users. Should not all loader behave similarly?

/ping @donmccurdy I expect you have opinions on this... :-)

**Comment by donmccurdy** [comment]
I agree that there's probably no reason for loaders to be inconsistent on something like that, but I don't have a strong preference one way or another. Waiting for textures does seem slightly more intuitive to me — users shouldn't need a LoadingManager to know when a single model is really fully loaded. Especially with VR, where the texture upload will drop frames and needs to happen before you begin presenting.

**Comment by WestLangley** [comment]
> users shouldn't need a LoadingManager to know when a single model is really fully loaded

Exactly.

>ObjectLoader or GLTFLoader are implemented differently and always wait for all assets.

If that is true, then I think the remaining loaders should do the same.

**Comment by looeee** [comment]
> If that is true, then I think the remaining loaders should do the same. 

Agreed.

**Comment by takahirox** [comment]
I agree with consistent behavior across loaders, it should be preferable. But I don't have a strong preference 
whether we should wait for all assets or not.

I think waiting for all assets may be more intuitive, too, but I'm also wondering response time. I guess one of the aims of the `TextureLoader.load()` design, synchronously returning `texture` and asynchronously setting `.needsUpdate` when download completion, is for short response time as web content. Texture image size is big in general. If apps waits for all asset downloading, response time would longer.

Some of the users may still want model faster, before loading all assets, for their short response time web contents. Should we provide a way to do that even if we let all loaders' `.load()` wait for all assets?

**Comment by donmccurdy** [comment]
> Incrementally displaying is very webby... Some of the users may still want model faster, even before loading all assets...

Rendering an untextured model is a very specific way of doing incremental display. Especially since image upload tends to drop frames badly (more browsers need ImageBitmap support! 😅) I'm not sure we'd want to roll out a second load callback just for pre-texture-load across all loaders. Just making `.load()` work in a consistent way will be a big task on its own.

We could do something more explicit and flexible like a streaming option:

```js
new FooLoader()
  .setStreaming( true )
  .load( 'model.foo', ( o ) => { ... } );
```

This gives the flexibility to do incremental display in other ways, like loading lower LODs first. But I imagine only a few loaders would actually support that. glTF has some features intended to help with streaming, but even there we don't have an established best practice or examples yet. I think SEA3D does have streaming, too?

**Comment by takahirox** [comment]
> Especially since image upload tends to drop frames badly

Three.js is general purpose 3D CG library for web, not only for WebVR. I think some users/apps don't care the frame rate drop so much and instead want model faster even without textures. Short response time is sometimes very important for web contents.

Indeed I was one of them. I made an app(non-VR) which just renders models with large and many textures. I wanted to start rendering the models as soon as possible even without textures not to lose visitors interest.

About `.setStreaming()`, is your idea that Loaders fire `onLoad` callback when all assets are ready if `.streaming = false (default)` but if `.streaming = true` Loaders fire before all assets are ready (maybe the behavior depends on Loader)?

**Comment by looeee** [comment]
On further consideration I'm inclined to side with @takahirox on this. We should not take away the ability for users to decide to display models before textures are loaded if they want, especially since we currently (if awkwardly) allow both behaviours via loader's `onLoad` vs `loadingManager.onLoad`.

**Pull request merged**
