### PR TITLE
Adds a "new" tag to examples released in the last major

### LINKED ISSUE #20199: Examples: Adding a "new" tag to examples released in the last major
Hi 👋
The three examples page is a fun place to just spend an afternoon exploring, and it's fun to see what's new. 

What would you think about adding a small tag on the new examples?

Something linke this:
image

It would be easy to handle the special case of `#new` in the searchbar to show all new examples. 

### Maintaining it
This is of course something that would have to be changed between releases, it could be stored as an object in `files.js`:

```js
const newExamples = ['webgl2_volume_cloud', 'webgl2_volume_instancing', 'webxr_vr_haptics'];
```

They would have to be changed every major release ( or two? ).

Looking for thoughts and comments, If it feels like something interesting I'll work on the PR 👍

### PR DESCRIPTION
**Pull request by gsimone**
Closes #20199 

#### Preview
https://rawcdn.githack.com/gsimone/three.js/bf510f806536d623d45d283d6680cd68ac95ecb0/examples/index.html?q=volume

Search by new: https://rawcdn.githack.com/gsimone/three.js/bf510f806536d623d45d283d6680cd68ac95ecb0/examples/index.html?q=new

#### Todo
- [x] Base style
- [x] Search

### CODE REVIEW

**Comment by gsimone** [comment]
Search was added in the simplest possible way I could think of, by just adding `new` to the string used to match against the search query when the examined file is in the newFiles array:

```js
var isNew = newExamples.includes( file );
var res = ( file + ( isNew ? "new" : "" ) ).match( exp );
```

**Comment by gsimone** [comment]
👋 I'd like to get this ready for 122, anything I can do this month to finish it up?

**Comment by mrdoob** [comment]
@gsimone Sorry, this would have been a bit too much maintenance for me 😕

**Comment by gsimone** [comment]
No worries 🤗

**Pull request closed without merging**
