### PR TITLE
Dev: convert_obj_three_for_python3.py

### PR DESCRIPTION
**Pull request by leroyron-zz**
Convert Wavefront OBJ / MTL files into Three.js (JSON model version, to be used with ascii / binary loader)

1st Errors-----------------:
The problem is that in Python 2 the print function is different in Python 3.
Python 2:
print ''

Python 3: print is a function and no keyword so it needs brackets:
print('')

2nd Errors-----------------:
struct.error: argument for 's' must be a bytes object
a.
signature = struct.pack('<12s', 'Three.js 003') Changed To signature = struct.pack(b'<12s', b'Three.js 003')

b.
out.write("".join(buffer)) Changed To > out.write(b"".join(buffer))

Explanation:

The error
packed = struct.pack(1, 'ab', 2.7)

With Python 3, 'ab' isn't a bytes object, what was called a str on Python 2, it's unicode. You need to use:
packed = struct.pack(1, b'ab', 2.7)

which tells Python that 'ab' is a byte literal. See PEP 3112 for more info.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
How come you're not loading the .obj file with `OBJLoader` though? I'm considering deprecating these converters.

**Comment by leroyron** [comment]
OBJLoader has limited options, I prefer the binary compressed option and
the JS file so I could identify material index for shading.

- Leroy

**Comment by mrdoob** [comment]
I see I see.

**Pull request merged**
