### PR TITLE
Remove ImmediateRenderObject.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: https://github.com/mrdoob/three.js/pull/22624#discussion_r721513959

**Description**

The primary intention behind this change is to simplify the renderer. Looking back, it also seems that ImmediateRenderObject was too hard to use and thus only poorly adapted by the user base. Overall, it seems better to guide user to the normal BufferGeometry workflows.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks! 🥲

**Comment by cdhuangyong** [comment]
I have a usage, such as rendering a vector tile, the material has stencilWrite: true turned on, and I need to update the position in onBeforeRender, and I don't want to create too many buffers, ImmediateRenderObject can help me, but it is deleted now, do I have any other solutions?

**Comment by mrdoob** [comment]
@cdhuangyong Could you elaborate a bit more?

**Comment by cdhuangyong** [comment]
In my special case, I need to render a stencil buffer to clip my vector tile mesh, so my steps are like this：
step1:
`
 const group = new THREE.Group();
      const clipBuffer = (this.buffers = {
        hasPositions: true,
        positionArray: this.positions,
        count: 18 / 3,
      });
      const clipMaterial = new THREE.ShaderMaterial({
        vertexShader: '...',
        fragmentShader: '...',
        transparent: true,
        stencilWrite: true,
        stencilRef: 0,
        stencilWriteMask: 0xff,
        stencilFunc: AlwaysStencilFunc,
        stencilFuncMask: 0,
        stencilFail: KeepStencilOp,
        stencilZFail: KeepStencilOp,
        stencilZPass: ReplaceStencilOp,
      });

      const layoutMaterial = new THREE.ShaderMaterial({
        vertexShader: '...',
        fragmentShader: '...',
        transparent: true,
        stencilWrite: true,
        stencilRef: 0,
        stencilWriteMask: 0x00,
        stencilFunc: EqualStencilFunc,
        stencilFuncMask: 0xff,
        stencilFail: KeepStencilOp,
        stencilZFail: KeepStencilOp,
        stencilZPass: ReplaceStencilOp,
      });

      /**
       * Suppose I have 10 tiles
       */
      const tiles = new Array(10).fill(0).map((v, index) => {
        return {
          id: index,
          extent: [-180, -90, 180, 90], //The tile extent is different
        };
      });

      for (let i = 0; i < tiles.length; i++) {
        /**
         *create a clipping mesh
         */
        const clipMesh = new THREE.ImmediateRenderObject();
        clipMesh.material = clipMaterial;
        clipMesh.renderOrder = tiles[i].id;
        clipMesh.onBeforeRender = () => {
          clipMesh.material.stencilRef = tiles[i].id;
          clipMesh.position.set();
          clipBuffer.count = 18 / 3;
          const arr = clipBuffer.positionArray;
          (arr[0] = extent[0]), (arr[1] = extent[1]), (arr[2] = 0);
          (arr[3] = extent[0]), (arr[4] = extent[3]), (arr[5] = 0);
          (arr[6] = extent[2]), (arr[7] = extent[3]), (arr[8] = 0);
          (arr[9] = extent[2]), (arr[10] = extent[3]), (arr[11] = 0);
          (arr[12] = extent[2]), (arr[13] = extent[1]), (arr[14] = 0);
          (arr[15] = extent[0]), (arr[16] = extent[1]), (arr[17] = 0);
        };
        mesh.render = (renderCallback) => {
          renderCallback(clipBuffer);
        };

        /**
         *Create clipped mesh
         */
        const layoutMesh = new Mesh();
        layoutMesh.renderOrder = tiles[i].id + 0.1;
        layoutMesh.geometry = new BufferGeometry(); //Omit vertex data
        layoutMesh.material = layoutMaterial;
        layoutMesh.onBeforeRender = () => {
          layoutMesh.material.stencilRef = tiles[i].id;
        };
        group.add(clipMesh);
        group.add(layoutMesh);
      }
`

**Comment by cdhuangyong** [comment]
Because there is a lot of code, I just briefly describe the logic of the code. Sorry, I haven't been able to provide a working demo yet. If I don't consider performance issues, I can use other ways to render.

**Pull request merged**
