### PR TITLE
Fixes for clone method for some of the helpers

### LINKED ISSUE #7824: Cannot clone BoxHelper
In version r71 I could clone BoxHelper meshes. When I upgrade to r72 or r73, anytime I try to clone a BoxHelper or any object containing a BoxHelper I get the following exception:

Uncaught TypeError: object.updateMatrixWorld is not a function
You can replicate this by making the following change to the example code in "webgl_helpers.html"

Change line 73 from:

```
scene.add( new THREE.BoxHelper( mesh ) );
```

To:

```
var helper = new THREE.BoxHelper( mesh );
var helper1 = helper.clone();
scene.add( helper1 );
```

Is there a workaround?

### PR DESCRIPTION
**Pull request by dhritzkiv**
Was unable to add clone methods for these helpers:
- ArrowHelper
- EdgesHelper
- SkeletonHelper

as they require more custom solutions.

---

Closes #7824

### CODE REVIEW

**Comment by DanielAChandler** [comment]
The BoxHelper clone method does not take into account a change in line/material color.

It is odd that BoxHelper does not take a color like other helpers. Might be a good enhancement to add color to the constructor.

You may use something like this:

    THREE.BoxHelper.prototype.clone = function () {
        var helper = new this.constructor(this);
        helper.material.color = this.material.color;
        return helper;
    }

**Comment by dhritzkiv** [comment]
If color is to be cloned, then it should also be part of the constructor:

```js
THREE.BoxHelper = function ( object, hex ) {

    //…

}

//…

THREE.BoxHelper.prototype.clone = function ( ) {

    return new this.constructor( this, this.material.color );

}
```

I'll let the owners of this project decide any API changes, however small the changes and however ancillary the functionality may be.

**Comment by EliasHasle** [comment]
I have run into this same problem with the BoxHelper, when trying to add a BoxHelper as child to a box-shaped cell, and then clone the cell. So I would certainly appreciate further progress in this PR. Keep up the good work! :-)

IMO, adding an optional color parameter to the BoxHelper is a no-brainer, but then again I am not the owner of this project.

I could use the BoundingBoxHelper, but that one adds diagonals on the faces, for some reason.

**Comment by brianpeiris** [comment]
Would be nice if this was reopened and merged. Let me know if I can help. I'm mainly interested in being able to clone BoxHelpers at least, if that's less controversial.

**Comment by DanielAChandler** [comment]
I put the below in my own code.
It gave me the color control and cloning I needed
------------------------------------------------------------------------------------------------------------

// Override of ThreeJS BoxHelper to fix clone and color issue
var EYC_THREE = { REVISION: '73' };

EYC_THREE.BoxHelper = function (object, hex) {
    var color = (hex !== undefined) ? hex : 0xffff00;

    var indices = new Uint16Array([0, 1, 1, 2, 2, 3, 3, 0, 4, 5, 5, 6, 6, 7, 7, 4, 0, 4, 1, 5, 2, 6, 3, 7]);
    var positions = new Float32Array(8 * 3);

    var geometry = new THREE.BufferGeometry();
    geometry.setIndex(new THREE.BufferAttribute(indices, 1));
    geometry.addAttribute('position', new THREE.BufferAttribute(positions, 3));

    THREE.LineSegments.call(this, geometry, new THREE.LineBasicMaterial({ color: color }));

    if (object !== undefined) {

        this.update(object);

    }

};

MY_THREE.BoxHelper.prototype = Object.create(THREE.LineSegments.prototype);
MY_THREE.BoxHelper.prototype.constructor = MY_THREE.BoxHelper;

MY_THREE.BoxHelper.prototype.update = (function () {

    var box = new THREE.Box3();

    return function (object) {

        box.setFromObject(object);

        if (box.isEmpty()) return;

        var min = box.min;
        var max = box.max;

        /*
          5____4
        1/___0/|
        | 6__|_7
        2/___3/

        0: max.x, max.y, max.z
        1: min.x, max.y, max.z
        2: min.x, min.y, max.z
        3: max.x, min.y, max.z
        4: max.x, max.y, min.z
        5: min.x, max.y, min.z
        6: min.x, min.y, min.z
        7: max.x, min.y, min.z
        */

        var position = this.geometry.attributes.position;
        var array = position.array;

        array[0] = max.x; array[1] = max.y; array[2] = max.z;
        array[3] = min.x; array[4] = max.y; array[5] = max.z;
        array[6] = min.x; array[7] = min.y; array[8] = max.z;
        array[9] = max.x; array[10] = min.y; array[11] = max.z;
        array[12] = max.x; array[13] = max.y; array[14] = min.z;
        array[15] = min.x; array[16] = max.y; array[17] = min.z;
        array[18] = min.x; array[19] = min.y; array[20] = min.z;
        array[21] = max.x; array[22] = min.y; array[23] = min.z;

        position.needsUpdate = true;

        this.geometry.computeBoundingSphere();

        return this;

    }

})();

MY_THREE.BoxHelper.prototype.clone = function () {
    return new this.constructor(this, this.material.color);
};

**Pull request closed without merging**
