### PR TITLE
Examples: Use import maps polyfill

### PR DESCRIPTION
**Pull request by mrdoob**
Related issue: #23148

### CODE REVIEW

**Comment by mrdoob** [comment]
@sunag should I revert #22936?

**Comment by sunag** [comment]
Hmm... In case of revert we would have to put this polyfill to `NodeMaterial`/WebGL examples too.

**Comment by mrdoob** [comment]
@sunag Could you take care of that?

**Comment by sunag** [comment]
Should we have something like `three-nodes`?

```js
{
	"imports": {
		"three": "../build/three.module.js",
		"three-nodes": "../jsm/renderers/nodes/Nodes.js"
	}
}
```

**Comment by mrdoob** [comment]
Hmm, right now `three` is also a npm package...
If we did this, people would expect `three-nodes` to be a npm package too. Is that something we want to do?

**Comment by sunag** [comment]
> If we did this, people would expect three-nodes to be a npm package too. Is that something we want to do?

@mrdoob I think in something like this: 
https://github.com/mrdoob/three.js/pull/23368#issuecomment-1024645696

**Comment by mrdoob** [comment]
Yesterday I registered the package just in case 😀
https://www.npmjs.com/package/three-nodes

**Comment by mrdoob** [comment]
@marcofugaro Is there a way of publishing multiple packages from the same package.json/repo?

**Comment by marcofugaro** [comment]
> @marcofugaro Is there a way of publishing multiple packages from the same package.json/repo?

Not with plain npm, but there are some tools/scripts.

@mrdoob what do you think about this aliasing instead? This way we don't have to publish a new package.

```js
import { ArrayInputNode } from 'three/nodes'
```

**Comment by unphased** [comment]
Hi, the import maps polyfill/shim is preventing Safari from being able to run app code if dev tools are open, so there would be no way to use dev tools to work on safari-specific issues with three.is apps. Are we aware of the issue? I'll also follow up at https://github.com/guybedford/es-module-shims.

**Comment by marcofugaro** [comment]
@unphased no issues for me in safari devtools, are you sure this isn't caused by some other part of your application?

image

**Comment by unphased** [comment]
If you reload while the dev tools open, does the 3d scene load at all for you?

**Comment by marcofugaro** [comment]
Yup, all normal.

**Comment by unphased** [comment]
> Yup, all normal.
Thanks for confirming. So, you still get the error `TypeError: Module specifier, 'application' does not start with "/", "./", or "../".`, but with dev tools open and reloading on the examples page the scene loads for you. This is not what I experience on my M1 Max, but I will check on my intel Macs.

**Comment by unphased** [comment]
Ok so I wasn't accounting for the slower execution speed when devtools are open. the Threejs examples do work as you say, sorry about that.

**Pull request merged**
