### PR TITLE
remove deprecated UniformsUtils.[merge|copy] from examples.

### PR DESCRIPTION
**Pull request by aardgoose**
Replaced UniformsUtils and replaced with Object.assign() 

+ fix declaration in global scope missing in dynamic terrain example.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by takahirox** [comment]
Can you revert `MMDLoader`?
This PR has broken `webgl_loader_mmd*` examples.

And #9912 solves the `UniformsUtils.*` issues in `MMDLoader`.

**Comment by mrdoob** [comment]
@takahirox done!

**Comment by takahirox** [comment]
Thanks!

**Comment by aardgoose** [comment]
@takahirox appologies for breaking your code,  i'll check more carefully next time.

**Comment by takahirox** [comment]
NP!

**Comment by mrdoob** [comment]
Seems like this PR broke `webgl_mirror` and many of the `webgl_postprocessing_` examples. Do you mind taking a look @aardgoose?

**Comment by aardgoose** [comment]
certainly, I must have missed the damage.

**Pull request merged**
