### PR TITLE
Reflector/Refractor: Expose virtual camera as a property.

### PR DESCRIPTION
**Pull request by LR17**
**Description**

It may be useful to control some properties of the camera used by Reflector, for example to set its layers. This pull request expose the camera used by Reflector as a property of the object.

### CODE REVIEW

**Comment by Mugen87** [comment]
Do you mind making the same change for `Refractor`? It would be good to keep both classes in sync.

**Comment by mrdoob** [comment]
> It may be useful to control some properties of the camera used by Reflector, for example to set its layers.

Do you mean copying the main camera layers? Or custom layers?

**Comment by LR17** [comment]
My specific use case is this: I have some sets of meshes and for each set I assign it a layer so that all the meshes of a set have the same layer. Then I want the main camera of my application to be able to see a set of layers different from the ones seen by the Reflector camera. My client code would then look like this:
```
const reflector = new Reflector(geometry, options); 
reflector.camera.layers.enable(3); 
reflector.camera.layers.enable(7);
```

**Comment by Mugen87** [comment]
Um, if the virtual camera should work with different layers than the main camera, it's indeed required to expose it. 

Too bad, I was hoping we could hide the camera inside the classes. In some sense, the virtual camera is a technical detail that should not be relevant to users.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
