### PR TITLE
MMDLoader

### PR DESCRIPTION
**Pull request by takahirox**
I made MMDLoader for example.
MMD(MikuMikuDance) is a 3D CG animation tool which is popular in Japan.
MMDLoader loads MMD Model/Dance data and lets models dance.

Demo: http://takahirox.github.io/three.js/examples/#webgl_loader_mmd

### CODE REVIEW

**Comment by mrdoob** [comment]
Looks great! Out of curiosity, what's the CharsetEncoder for?

**Comment by takahirox** [comment]
That's for converting character code from Shift_JIS to UTF-16.

Japanese characters in PMD(Model data) and VMD(Dance motion data) file are
encoded as Shift_JIS, so it's necessary to encode to UTF-16 to be handled in JavaScript.

And Japanese characters in PMX(Extended model data) file are encoded as
UTF-16 (or UTF-8,  I'm also gonna support UTF-8 soon).
Motion data key in VMD specifies corresponding bone with bone name,
so I needed to unify character where bone name in PMX is Japanese.

**Comment by mrdoob** [comment]
I see I see. Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
