### PR TITLE
VRMLLoader: Fix parsing of CoordIndex when not ending with -1

### PR DESCRIPTION
**Pull request by palortoff**
According to [[1]](http://www.graphics.stanford.edu/courses/cs248-98-fall/Assignments/Assignment3/VRML2_Specification/spec/part1/nodesRef.html#IndexedFaceSet):

 'The last face may (but does not have to be) followed by a -1.'

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please share a VRML file that demonstrates the current the issue? Besides, a fix would be needed at other places, too.

https://github.com/mrdoob/three.js/blob/4cecb4869ada527b97c327ee0fd5baadea561f6c/examples/js/loaders/VRMLLoader.js#L1894
https://github.com/mrdoob/three.js/blob/4cecb4869ada527b97c327ee0fd5baadea561f6c/examples/js/loaders/VRMLLoader.js#L1942
https://github.com/mrdoob/three.js/blob/4cecb4869ada527b97c327ee0fd5baadea561f6c/examples/js/loaders/VRMLLoader.js#L1972

Also please respect the code style. The line should look like so:
```js
if ( index[ i + 3 ] === - 1 || i + 3 >= l ) {
```

**Comment by palortoff** [comment]
Wow, that was a quick response! 

Fixed the code style and the other places. 
I will provide the sample file shortly, probably on monday.

Should the examples/jsm/loaders/VRMLLoader.js be changed manually or is there some tool to make the conversion?

**Comment by Mugen87** [comment]
You can run `node utils/modularize.js` to generate the module version.

**Comment by Mugen87** [comment]
I've tested with an adjusted `WRL`  file and the fix is correct.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
