### PR TITLE
Shapes refactor

### PR DESCRIPTION
**Pull request by zz85**
Changes to `Path`
- got rid of `.actions` (yay)
- `getPoints()` moved to `CurvePath`
- `toShapes()` moved to new class `ShapePath`

Includes @rfm1201's commit in #8952 and related to #8897, and fixes the weird arc API in https://twitter.com/mrdoob/status/669400362835681280 / http://bl.ocks.org/mbostock/8bee9cf362d56d9cb19f/507166861adc3d52038ba43c934e6073937eb13c

TODO / some things for consideration before merging
- [ ] update docs and migration
- [ ] does API make more sense now?
- [ ] move point deduplication to ShapeUtils as suggested by rfm1201
- [ ] code format

### CODE REVIEW

**Comment by rfm1201** [comment]
@zz85 you used the `THREE.EllipseCurve` and `THREE.CurvePath` found in https://github.com/mrdoob/three.js/pull/8952 that should be updated to reflect @WestLangley remarks.

For `THREE.CurvePath`, would you please use
```
var segmentLength = curve.getLength();
var u = segmentLength === 0 ? 0 : 1 - diff / segmentLength;
```
instead of
```
var segmentLength = curve.getLength();
var u = 0;
if ( segmentLength !== 0 ) {

	u = 1 - diff / curve.getLength();

}
```

For `THREE.EllipseCurve`, would you please use a version where deltaAngle is not a member and with your better
```
var tx = x - this.aX;
var ty = y - this.aY;

// Rotate the point about the center of the ellipse.
x = tx * cos - ty * sin + this.aX;
y = tx * sin + ty * cos + this.aY;
```
than
```
var tx = x, ty = y;

// Rotate the point about the center of the ellipse.
x = ( tx - this.aX ) * cos - ( ty - this.aY ) * sin + this.aX;
y = ( tx - this.aX ) * sin + ( ty - this.aY ) * cos + this.aY;
```
Something like the `THREE.EllipseCurve that can be found in https://github.com/mrdoob/three.js/compare/dev...rfm1201:Path_using_curves

**Comment by zz85** [comment]
Thanks @rfm1201! I'll try to fix up the commits again. Apart from that, are there any other comments on nature of the PR?

**Comment by rfm1201** [comment]
I didn't have time to test yesterday, I just did a code comparison.
I just tried with my local test pages and there are problems. I'm going to investigate and will tell you what I found this afternoon (Paris local time)

**Comment by rfm1201** [comment]
I found 3 bugs in your PR, and there is one change in the result of `CurvePath.getPoints` when a `moveTo` is called before an arc or ellipse.

The 3 bugs:
First there is a problem in `CurvePath.getPoints` when the path should be closed with `autoClose` at `true`. The first point is added at the end of the path with
```
if ( this.autoClose ) {

	points.push( points[ 0 ] );

}
```
to be immediately removed when the next line is executed
```
points = this.removeDuplicatesInAPath( points );
```
Better change the order of these two blocks of code.

Second, `CurvePath.getSpacedPoints` should loop `for ( var i = 0; i <= divisions; i ++ ) {
`and not `for ( var i = 0; i < divisions; i ++ ) {`

Third, `Path.splineThru` doesn't set `this.currentPoint`. You should add something like
```
var lastPoint = pts[ pts.length - 1 ];
this.currentPoint.set( lastPoint.x, lastPoint.y );
```
at the end of the function.

When you build a path with a `moveTo` and put an ellipse (or an arc) just after it, the points returned by the `CurvePath.getPoints` of your PR will only be the points of the ellipse.
If the `moveTo` is done to the first point of the ellipse, it is also what the current prod/dev `Path.getPoints` returns.
But, if the first point of the ellipse is not the point of the `moveTo`, the current prod/dev `Path.getPoints` returns that point as the first one. It is currently a problem because `Path.getSpacedPoints` won't consider that first point (see my [Fiddle](https://jsfiddle.net/wdsmy9k3/3/) to add a point before an ellipse)
With your PR there is no problem between `getPoints` and `getSpacedPoints`, both draw the same path. But I think that the `moveTo` should have an effect on the final path. That's why I added an automatic `lineTo` when "needed" in my `Path.absellipse` that was in [https://github.com/mrdoob/three.js/compare/dev...rfm1201:Path_using_curves](https://github.com/mrdoob/three.js/compare/dev...rfm1201:Path_using_curves).
It is just my opinion, I can be wrong, but the documentation should be clear because with an ellipse (or an arc) the final point of the previous curve can be totally different from the first point of the ellipse.

I have not found any other change in the output of your PR.

I have one question, why do you fill the `points` array inside `CurvePath.getPoints` with points that will be removed in `CurvePath.removeDuplicatesInAPath`.
`Curve.getPoints` can be changed to return an array where 2 successive points are guaranteed to be different. I know it's a change in the way it is currently computed, but I can't imagine a use where it's useful to have those same points. The points are usefull to draw the path, when to successive points are the same, there is nothing to draw.
With that modification, `CurvePath.getPoints` will just have to check that the last point of the previous curve is not the first point of the current one. In fact it should, but it is better to check before removing any point.

**Comment by zz85** [comment]
>  First there is a problem in CurvePath.getPoints when the path should be closed with autoClose at true. Fixed. Also,

> I have one question, why do you fill the points array inside CurvePath.getPoints with points that will be removed in CurvePath.removeDuplicatesInAPath

I think I've wrote it a more generic, functional approach than an imperative one although I think there's no harm in either. 

> Second, CurvePath.getSpacedPoints should loop for ( var i = 0; i <= divisions; i ++ ) { and not for ( var i = 0; i < divisions; i ++ ) {
Fixed too thanks.

> Third, Path.splineThru doesn't set this.currentPoint. 
Updated too.

> That's why I added an automatic lineTo when "needed" in my Path.absellipse that was in dev...rfm1201:Path_using_curves.
It is just my opinion, I can be wrong, but the documentation should be clear because with an ellipse (or an arc) the final point of the previous curve can be totally different from the first point of the ellipse.

I looked at the implementation in Canvas (moveTo followed by an ellipse) and it seems like it does draw an automatic line to join the ends. Because of this I'm adding this automatic lineTo also, although I'm not sure if this behaviour should be extended to others (eg. splineThru now uses the last currentPoint as the first interpolation point rather than drawing a lineTo the first point in the spline)

**Comment by mrdoob** [comment]
@rfm1201 looks good?

**Comment by rfm1201** [comment]
@mrdoob , I will look tomorrow morning, I have no computer to test today.

**Comment by rfm1201** [comment]
It works with all the examples I used to test (`canvas_geometry_shapes.html`, `webgl_geometry_shapes.html`, `webgl_geometry_extrude_shapes.html`, `webgl_geometry_extrude_shapes2.html` and `webgl_geometry_text.html`) and with the tests I wrote so far, but I have 3 comments questions for @zz85:
- You changes the code of `THREE.CurvePath.getPoints` and removed the `THREE.CurvePath.removeDuplicatesInAPath` from his preceding version of the PR. Maybe is it because I asked him why he fills the `points` array in `getPoints` and, potentially, emptied it in `removeDuplicatesInAPath`.
Anyway, the result is not exactly the same because `THREE.Curve.GetPoints` can put the same point many times in the array it returns. For example, if someone add an ellipse with the same starting an ending angle in a path, all the (13 by default) points returned will be the same. OK you may think it is a strange way to define a path, but from a defensive programmatic point of view, it would be necessary to modify `THREE.Curve.GetPoints` to avoid that.
- The documentation should say that a path (or sub-path) must begin with a call to moveTo. When you read the documentation, for absarc or absellipse you can think that they can be used alone. It is possible with the current three.js version (I did it in the [Fiddle](https://jsfiddle.net/wdsmy9k3/3/) I made for #8897), it is not possible with that PR because of the way the lineTo is added before the ellipse.
It’s not a bug, but if a path could be defined with just an absarc or an absellipse (@mrdoob or you to choose), a test must be added in `THREE.Path.absellipse` to add the `lineTo` only if `currentPoint` have been defined by a call to one of the drawing functions (but in fact only` moveTo` need to be modified, because the other functions require a `moveTo`). I have not found a way to do it without adding a boolean or an equivalent to `THREE.Path`.
- I never used sub-path and have not build an example to test it, so my last remarks just come from the reading of the code, is it normal that `THREE.ShapePath` does not have an `absellipse` function?

**Comment by zz85** [comment]
@rfm1201 

1. You've got a point, I think removing duplicated points would be better (sorry flip flopping my decisions here)
2. I think we should allow no lines if there is no moveTo before 
3. `THREE.ShapePath` is primarily used for text fonts I believe, which mostly uses `moveTo`, `lineTo`, `bezierCurveTo`. I think we could start with a minimal set of APIs for this 2D Path, or move `ShapePath` back into `Shape` class again.

**Comment by zz85** [comment]
@rfm1201 pushed 2 commits to address point 1 and 2

**Comment by rfm1201** [comment]
@zz85, I will look at your PR tomorrow

**Comment by rfm1201** [comment]
For me it looks good.

My only concern is about the fact that the last point of a path may be removed by `THREE.CurvePath.getPoints` if it is the same as the first point. This can be written another way, "the only correct way to close a path is to put `autoClose` at true"
For me this is non intuitive, and when the last point of a path is removed because of that rule, I look for a bug in my code. Before reading the code, I couldn't imagine it was just a rule in three.js.
This rule is currently in three.js but not in three.js documentation and as your PR doesn't include the documentation, it won't be in the documentation after.

Instead of the end of `THREE.CurvePath.getPoints` beeing
```
if ( points[ points.length - 1 ].equals( points[ 0 ] ) ) {

	points.pop();

}

if ( this.autoClose ) {

	points.push( points[ 0 ] );

}
```
I would prefer something like
```
if ( this.autoClose && points.length > 1 && !points[ points.length - 1 ].equals( points[ 0 ] ) ) {

	points.push( points[ 0 ] );

}
```
But this is not a bug, I just have a different interpretation of the way a path should work.

**Comment by rfm1201** [comment]
I forget to say that, if you would go for what I propose, you will need to change ShapeUtils because it will have a problem with the first and last point being the same.
The simplest thing is to do what you do because it is already the way three.js goes.

**Comment by mrdoob** [comment]
Lets start landing this and experimenting... 😁

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by zz85** [comment]
> But this is not a bug, I just have a different interpretation of the way a path should work.

@rfm1201 This is a fair interpretation. We should address this is a separate PR.

Thanks mrdoob.

**Comment by mrdoob** [comment]
Seems like this example has changed a little bit...

screen shot 2016-06-17 at 10 40 38

screen shot 2016-06-17 at 10 40 47

Is that expected?

**Comment by rfm1201** [comment]
I have not the code with me now, but from what I see on your capture, I think the change is in GetPoints that  returns less point than before for some kind of curves, because there is no more internal multiplication of the parameter. GetSpacedPoints has not been changed from that point of view.

**Comment by zz85** [comment]
@mrdoob oh yes. looks like the number of divisions used previously were doubled for arc segments. I always felt there was something which looked different but I soon ignored that... always good to have 2nd pair of eyes :)

**Comment by zz85** [comment]
@mrdoob fixed in #9168

**Comment by killroy42** [comment]
I would like to add my "getSpacedPointsWithCorners" method as my first three.js PR and would appreciate some guidance. It seems you guys are familiar with that part of the code. It would work along with "getPoints" and "getSpacedPoints", but it would force points on the edges between the curves, while distributing hte remaining divisions proportionally according to the lengths of the segments. I could add it as a new method in the same spot, or as a boolean flag on the "getSpacedPoints" function, perhaps "snapToEdges" or similar. Thanks for the guidance!

**Comment by killroy42** [comment]
Small update, absellipse no longer renders in my test case in 79dev. I'm investigating.

**Comment by zz85** [comment]
@killroy42 yeah that part is strange. See my comments https://github.com/mrdoob/three.js/pull/8952#discussion-diff-65017213

**Comment by zz85** [comment]
@killroy42 it seems like the new code has a correct behaviour. With the same start and end angle, no arc may be renderered

**Comment by killroy42** [comment]
But it false for the case when the two angles are 2Pi apart, which means we no longer can render a full circle.

**Pull request merged**
