### PR TITLE
Examples > Add VFX flames

### PR DESCRIPTION
**Pull request by brunosimon**
**Description**

Add WebGPU/TSL VFX flames example, along with two textures in the `examples/textures/noises/` folder.
VFX inspired by [@cmzw_](https://x.com/cmzw_/status/1799648702338158747)
I added the screenshot to the exceptions since I can't generate one that works with the tests.

localhost_8083_examples_webgpu_tsl_vfx_flames html

### CODE REVIEW

**Comment by sunag** [comment]
There is an artifact being generated because of `pow()` on Windows https://github.com/mrdoob/three.js/pull/28955#issuecomment-2248737201, I will merge it up and submit a fix soon.

image

**Comment by WestLangley** [comment]
How about it we emulate a sprite and add this in the render loop:
```js
flame1.lookAt( camera.position );
flame2.lookAt( camera.position );
```

**Comment by brunosimon** [comment]
> How about it we emulate a sprite and add this in the render loop:
> 
> ```js
> flame1.lookAt( camera.position );
> flame2.lookAt( camera.position );
> ```

It's a good idea, but I actually kept it like this on purpose so that the user notice that it's a simple plane.

**Comment by WestLangley** [comment]
I hear you, but it is not going to be used that way. I think the example should show how to use it properly.

I wonder if it could be implemented as a sprite with a pivot point at the bottom-center.

**Pull request merged**
