### PR TITLE
Examples: Geometry -> BufferGeometry

### PR DESCRIPTION
**Pull request by WestLangley**

### CODE REVIEW

**Review by looeee — APPROVED** [review]

**Comment by looeee** [comment]
Awesome! 

The only example with a non-trivial change is `webgl_custom_attributes_lines`. Here's a [live version](https://rawgit.com/WestLangley/three.js/fb7db268d295f8dcff49bd9287e4ef9196cdff45/examples/webgl_custom_attributes_lines.html).

Nit picking, but I guess some of these are incorrectly named - `webgl_geometry_shapes` should now be `webgl_buffergeometry_shapes`. I'm OK with leaving them as is though.

**Comment by Mugen87** [comment]
I suggest to rename examples in different PRs.

BTW: The output of `CanvasRenderer` in `misc_lights_test` looks different now.

PR: https://rawgit.com/WestLangley/three.js/dev-to_buffer_geo/examples/#misc_lights_test
Prod: https://threejs.org/examples/#misc_lights_test

**Comment by WestLangley** [comment]
Thanks @looeee. That example was so dark I couldn't see some of the letters. Perhaps it can be further improved...

Also, I do temporary live links like so

    https://rawgit.com/WestLangley/three.js/dev-to_buffer_geo/examples/webgl_custom_attributes_lines.html

which update automatically when new commits are added. Then I delete the live link when it is no longer needed. That is different than the way you do it...

**Comment by WestLangley** [comment]
@Mugen87 Any idea why the LGTM failed?

**Comment by WestLangley** [comment]
>BTW: The output of CanvasRenderer in misc_lights_test looks different now.

Hmmm... What is the difference you are referring to?

**Comment by Mugen87** [comment]
BTW: This variable can be removed:

https://github.com/WestLangley/three.js/blob/fb7db268d295f8dcff49bd9287e4ef9196cdff45/examples/webgl_geometry_text_shapes.html#L54

**Comment by Mugen87** [comment]
Notice the different shapes of the faces. The PR skewed the faces of the geometries.

PR:
image
Prod:
image

**Comment by WestLangley** [comment]
Maybe `CanvasRenderer` is having a problem rendering `BufferGeometry`...

**Comment by Mugen87** [comment]
I'm not sure about this. That was one reason why I have not migrated any `canvas` examples to `BufferGeometry` yet 😇

**Comment by WestLangley** [comment]
>That was one reason why I have not migrated any canvas examples to BufferGeometry

Somebody must have, because I checked before I started this task.

I did hold back on some changes because `CanvasRenderer` may not handle multi-materials correctly.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
