### PR TITLE
NodeMaterials: Introduce a new BasicNodeMaterial class

### PR DESCRIPTION
**Pull request by martinRenou**
cc. @sunag this is more or less what I had in mind.

I suspect you might not like the `SimpleNode` name, for a better naming convention I would have liked it to be named `RawNode` (already taken). `RawNode` would be for `RawNodeMaterial` what `StandardNode` is for `StandardNodeMaterial`, if that makes sense.

### CODE REVIEW

**Comment by sunag** [comment]
Nice... Maybe `BasicNode` and `BasicNodeMaterial` seems more closer of three.js names.

**Comment by sunag** [comment]
is necessary format the code using mrdoob code style

**Comment by martinRenou** [comment]
> Nice... Maybe BasicNode and BasicNodeMaterial seems more closer of three.js names

Funny enough, that's how I named those two classes in my local project ahah. I just thought `RawNodeMaterial` made more sense. But if you think `BasicNodeMaterial` is better then I'll rename it :)

**Comment by sunag** [comment]
> Funny enough, that's how I named those two classes in my local project ahah.

this is good sign :)

**Comment by martinRenou** [comment]
> is necessary format the code using mrdoob code style

Very convenient website ahah. Will do.

**Comment by sunag** [comment]
I think that would be good an example in `webgl_materials_nodes`?

**Comment by martinRenou** [comment]
Indeed, will add one

**Comment by martinRenou** [comment]
@sunag Should I add a `mask` property as well? I would find it very convenient myself, but I don't know if that fits in the most basic material. I guess it does, as it's directly bound to the `discard` keyword, which is built-in GLSL, so it sounds basic to me.

**Comment by sunag** [comment]
> @sunag Should I add a mask property as well?

Yes, yes. It should be great.

**Comment by martinRenou** [comment]
I still want to add an example, and that should be good to go :rocket: hopefully

**Comment by sunag** [comment]
Do you think about add the example in this PR or other?

**Comment by martinRenou** [comment]
I will add it to this PR today :)

**Comment by martinRenou** [comment]
@sunag I added a simple example:

pot

**Review by sunag — APPROVED** [review]
Great work. Thanks!

**Comment by mrdoob** [comment]
Thanks!

**Comment by martinRenou** [comment]
Thank you for merging :) You rock!

**Pull request merged**
