### PR TITLE
OrbitControls: support 2-finger zoom/pan

### PR DESCRIPTION
**Pull request by WestLangley**
Three-finger panning has been removed with this PR, and replaced with the more-familiar 2-finger zoom/pan.

### CODE REVIEW

**Comment by WestLangley** [comment]
Please try it and let me know if touch is jittery.

/ping @wuweiweiwu, @ranbuch, @huj2, @moroine, @XanderLuciano

Apologies to @MauricioVives and @smcllns for the delay.

**Comment by WestLangley** [comment]
Test link: https://rawgit.com/westlangley/three.js/dev-orbit/examples/misc_controls_orbit.html

**Comment by wuweiweiwu** [comment]
LGTM 👍!

**Comment by moroine** [comment]
Looks good also on my side :+1: 

I'll see later to add a PR to be able to customize the touch behavior like we have with the option `mouseButtons` to have the ability to customize the behavior like:
 - 1 finger: pan
 - 2 fingers: rotate + zoom

**Comment by MauricioVives** [comment]
Great, thanks for getting this in!

**Comment by WestLangley** [comment]
@XanderLuciano Settings on one device are likely to yield different behavior than the identical settings on a different device.

I would prefer to keep the defaults at 1, and instead focus on code that help achieve more consistent behavior across devices -- to the extent that is even possible.

`OrbitControls` is an example, remember. Users are free to modify it according to their intended use case.

**Comment by mrdoob** [comment]
> @XanderLuciano Settings on one device are likely to yield different behavior than the identical settings on a different device.

I was thinking about this a bit the other day. I think we may want to divide the speed by `window.devicePixelRatio` or something along the lines.

**Comment by mrdoob** [comment]
Thanks!

**Comment by huj2** [comment]
@WestLangley First of all, thank you very much for your work!

I just implemented the new version from r92 in my project and found a problem.
I can not select objcets with raycaster on touch devices anymore. If I try, nothing is happening.

**Comment by WestLangley** [comment]
@huj2 hmm... likely competing event handlers.

I expect [this line](https://github.com/mrdoob/three.js/pull/13706/files#diff-ffef32863dd826c87a45cfb28c4ddd83R809) should be removed.

**Comment by huj2** [comment]
@WestLangley That's the line. Removed it and now it works again.

**Comment by moroine** [comment]
A little bit late, but as mentioned in https://github.com/mrdoob/three.js/pull/13706#issuecomment-376718496 new PR for adding a new touch behavior.

If you can test/review this could be awesome

**Comment by XanderLuciano** [comment]
@Pl4n3 Did you try removing the `event.preventDefault()` line?

**Comment by Pl4n3** [comment]
@XanderLuciano Now using an older version (from 81) without event.preventDefault(), also liked the old touch behavior better for my projects. I guess the threejs-examples-files are generally more subject to change then the threejs-core and shouldnt be directly referenced in a project.

**Pull request merged**
