### PR TITLE
Added Oculus Go controller.

### PR DESCRIPTION
**Pull request by kosso**
Added Oculus Go controller MTL and OBJ files. 
Updated and added example.

### CODE REVIEW

**Comment by mrdoob** [comment]
Live link:
https://rawgit.com/kosso/three.js/oculus-go-controller/examples/webvr_oculus-go.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Sorry, ended up removing all these controllers and unified into a single example. #14355

**Comment by kosso** [comment]
That's a shame. Having recently bought an Oculus Go, I expected to see a recognisable example in threejs. 

Is it not possible to get an identifier from the Gamepad API  device `id` ? 

I had looked around for a controller object in this repo, before making one. 
https://github.com/stewdio/THREE.VRController

**Comment by mrdoob** [comment]
> That's a shame. Having recently bought an Oculus Go, I expected to see a recognisable example in threejs.

`webvr_daydream` and `webvr_gearvr` are also gone. I'm about to rename the `webvr_vive_*` ones too. WebVR should just work everywhere and the device shouldn't matter ✌️

> Is it not possible to get an identifier from the Gamepad API device `id`?

The Gamepad API approach no longer will work with the WebXR API.

**Pull request merged**
