### PR TITLE
WebVR: Update origin trial token

### PR DESCRIPTION
**Pull request by Mugen87**
New Tokens 🎉 !

Important note: The tokens only work with Chrome M62+.

### CODE REVIEW

**Comment by mrdoob** [comment]
> Important note: The tokens only work with Chrome M62+.

Good to know!

**Comment by mrdoob** [comment]
Hmm, how come not all the webvr examples use the tokens? 🤔

**Comment by Mugen87** [comment]
see #11122

At that time we decided to exclude all Vive related stuff. But i think it should be no problem to add the token to all WebVR examples.

**Comment by mrdoob** [comment]
Yeah, I think we should add it to all the examples. Otherwise, on Chrome/Android, some examples show `ENTER VR` and others show `WEBVR NOT SUPPORTED`.

**Comment by Mugen87** [comment]
Okay 👍

**Pull request merged**
