### PR TITLE
WebXR backward compatibility for Magic Leap Helio (Chrome m73)

### PR DESCRIPTION
**Pull request by mvilledieu**
Magic Leap will be adding WebXR support to the Helio browser in the next few days, the problem is the version of Helio that is going to be released is based on the older Chrome m73 implementation of the WebXR API. Currently, Three doesn't support that library and users can't experience WebXR on the Three examples and start building using Three.js.

I realize the WebXR is constantly evolving but think that it could be a good temporary solution rather than having to share a custom build of three with developers. 

Let me know what you think?

### CODE REVIEW

**Comment by mrdoob** [comment]
Do you mind removing the builds from the PR?

**Comment by mrdoob** [comment]
Also, would a polyfill work for this? I think the version of the WebXR in m76 should be pretty stable 🤞

**Comment by mvilledieu** [comment]
@mrdoob done! Yes, I actually haven't thought about doing that. What about the three examples not being available on the Magic Leap device? Would you also include that Polyfill in three so that everyone can experience the demos? If you feel like this is the way to go (Polyfill) feel free to close that PR and I'll start working on that Polyfill.

**Comment by mrdoob** [comment]
Yep! Happy to include a polyfill in these demos until Helio catches up 👌

**Comment by mvilledieu** [comment]
I quickly put together a Polyfill for Helio WebXR [Here](https://github.com/mvilledieu/three.js/blob/helio-webxr-polyfill/examples/js/vr/HelioWebXRPolyfill.js)

If we publish it to npm on Monday could you include it using external? 
```<script src="https://unpkg.com/HelioWebXRPolyfill@latest/"></script>```

Or would you rather include it directly to the library as I did here?
https://github.com/mvilledieu/three.js/blob/helio-webxr-polyfill/examples/js/vr/HelioWebXRPolyfill.js

**Comment by mrdoob** [comment]
> Or would you rather include it directly to the library as I did here?
https://github.com/mvilledieu/three.js/blob/helio-webxr-polyfill/examples/js/vr/HelioWebXRPolyfill.js

That sounds good! Do you mind doing a PR adding it and updating the examples? I'll then cherry-pick it to the `gh-pages` 👌

**Comment by mvilledieu** [comment]
Closing, created a Polyfill see: https://github.com/mrdoob/three.js/pull/16649/files

**Pull request closed without merging**
