### PR TITLE
distanceToManhattan() -> manhattanDistanceTo()

### PR DESCRIPTION
**Pull request by WestLangley**
So glad to rename that one... what was I thinking?...  :)

### CODE REVIEW

**Comment by WestLangley** [comment]
So... what about `lengthManhattan()`?  I would be inclined to change it to `manhattanLength()`.

**Comment by mrdoob** [comment]
> So... what about `lengthManhattan()`?  I would be inclined to change it to `manhattanLength()`.

Sounds good to me! Do you want to do it in this PR or on a different PR?

**Comment by WestLangley** [comment]
Another one, is OK.

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
what about matrixWorld -> worldMatrix 😂

**Comment by mrdoob** [comment]
I think that has too much usage... 😛

**Comment by WestLangley** [comment]
>what about matrixWorld -> worldMatrix

I totally agree. Also,

    updateMatrixWorld() -> updateWorldMatrix()

**Pull request merged**
