### PR TITLE
Explicitly specify morphTargetsRelative=false

### PR DESCRIPTION
**Pull request by zeux**
This makes sure that we can grep for morphTargetsRelative and find
all places that need adjustments if we do change morph target behavior.

### CODE REVIEW

**Comment by Mugen87** [comment]
Isn't `ColladaLoader` also affected? I thought it support both types of morph targets?

**Comment by zeux** [comment]
It appears that ColladaLoader doesn’t implement morph target support at all. (COLLADA format supports both relative and absolute but the loader just has a TODO note for morph targets)

**Comment by Mugen87** [comment]
Ah, good to know! I forgot we only implement skeletal animation so far.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
