### PR TITLE
Fix scene.onBeforeRender and  .onAfterRender

### PR DESCRIPTION
**Pull request by wizgrav**
scene.onBeforeRender needs to be before currentRenderState is initialized in order to allow rendering inside it

scene.onAfterRender must be called after multiview or multisampled rendertargets do their blitFramebuffer  for post proc to have valid data in the renderTarget. 

multiview should also blit the depth if the final render target has a depth texture. 

when using a WebGL2 Context glInternal Format for depthStencil must be sized, ie DEPTH24_STENCIL8 instead of DEPTH_STENCIL

ping @fernandojsg @diekus @AdaRoseCannon

### CODE REVIEW

**Comment by wizgrav** [comment]
demo https://samsunginter.net/three-effects/examples/basic/

**Comment by wizgrav** [comment]
hmm there appears to be a mismatch on formats when trying to blit the framebuffer, investigating

**Comment by mrdoob** [comment]
We only support the last version of the WebXR API: https://github.com/mrdoob/three.js/pull/17685

**Comment by wizgrav** [comment]
@mrdoob that was sloppy of me, reverted. The format mismatch was similar to #16769, ie WebGL2 needs sized internal formats (DEPTH24_STENCIL8) so was easy to fix.

Tested on non VR mode but with renderer.vr.enabled === true and gl2 context to force use of the multiview path and it seems to work ok now. I'll do some tests on an actual HMD when I get home but it seems this PR does the trick.

To force the use of multiview you'll need to append an "#multiview" anchor on the demo url https://samsunginter.net/three-effects/examples/basic/#multiview

**Comment by wizgrav** [comment]
Tested extensively and it works. Some demos for all cases:

1) https://samsunginter.net/three-effects/examples/basic is built against three 0.109.0 and works without multiview normally, https://samsunginter.net/three-effects/examples/basic#multiview will try to enable the multiview extension but will fail with "texImage2D: invalid internalformat" for the depth texture.

2) https://samsunginter.net/three-effects/examples/canary/ is built against this PR and will enable try to enable multiview by default. It works normally

**Comment by fernandojsg** [comment]
ping @takahirox as he has been working on the VR + postprocessing recently https://github.com/mrdoob/three.js/pull/15840 and he was also working on the multiview support.
I'm still not sure if the postprocessing will happens always at the end of the frame, once the framebuffer is already pushed with both eyes, or if it could be interesting to be able to add a previous step where we could do postprocessing accessing also the view's parameters for view dependant effects or so.

**Comment by wizgrav** [comment]
@fernandojsg the view information is on the ArrayCamera so its easy as is to calculate eg sun position in godrays. Then you can either do two passes one for each half of the frame and send different uniforms. My approach is to upload uniform arrays for both eyes and the frames half width as a single float. Then I do one full frame pass and have the shader choose like gl_FragCoord < halfWidth ? left : right This way I have a single setup for normal and vr modes.

The design as is is adequate and has evolved very nice imho. It just needs this little tweak so post processing can work consistently across use cases

@mrdoob moved onAfterRender after even the multisampled renderTarget is resolved. It should always be the last operation on the frame in render(), only before vr submition.

**Comment by wizgrav** [comment]
Not related to scene.onAfterRender() but the renderTarget mipmap generation should take place after multiview and multisample actually blit into renderTarget,texture otherwise the mipmaps will be redundant or empty.

@fernandojsg how do you plan on supporting antialiasing with multiview?

**Comment by fernandojsg** [comment]
@wizgrav not news yet from the WebGL WG on the status of the multisampled multiview extension (https://github.com/KhronosGroup/WebGL/issues/2912) but I expect it to be used in a similar way as the current one just with a multisampled blit at the end, similar to how oculus is implementing right now their custom OCULUS_multiview extension, that support multisampling fb

**Comment by wizgrav** [comment]
@fernandojsg yeah I thought so but this will cause an issue with post processing. If a dev wants to render with antialiasing he would set a multisampled renderTarget which I suspect will lead to multiview not blitting in the right framebuffer. Maybe these two functionalities(multiview multisampled renderTargets) should be unified

**Comment by Mugen87** [comment]
Let's focus on #18626 for now. Especially since `WebGLMutliview` has been removed via  #18750.

**Comment by wizgrav** [comment]
@Mugen87 good call, imo multiview will be redundant soon. When this extension lands https://www.khronos.org/registry/webgl/extensions/EXT_clip_cull_distance/ it can be utilized along with instancing to achieve the same draw call reduction, minus the extra blit that multiview requires. It will also simplify the webglrenderer code which had overlap issues with the multisampled render target functionality

**Pull request closed without merging**
