### PR TITLE
Examples: Remove SubdivisionModifier.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: see https://github.com/mrdoob/three.js/pull/21067#issuecomment-758883027

**Description**

This PR removes `SubdivisionModifier`.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by arpu** [comment]
anyone knows a replacement for this? best for Buffer Geometry

**Comment by donmccurdy** [comment]
Offline subdivision with tools like gltfpack, Blender, or RapidCompact would be my recommendation. The implementation of SubdivisionModifier was never really robust even for Geometry, see https://github.com/mrdoob/three.js/pull/21067#issuecomment-758847777.

**Comment by arpu** [comment]
my use case is generate a Terrain mesh from  height map  image generated mesh  optimize with @mapbox/martini (https://github.com/mapbox/martini)
and after this optimization i use 
```
		const modifier = new THREE.SubdivisionModifier( 1 );
		let smoothGeometry = modifier.modify( martiniGeo );
		martiniGeo = new THREE.BufferGeometry().fromGeometry( smoothGeometry );
```

all is done on client side user browser

**Comment by arpu** [comment]
maybe this https://github.com/heremaps/harp.gl/blob/master/%40here/harp-geometry/lib/SubdivisionModifier.ts ?

**Comment by donmccurdy** [comment]
`@mapbox/martini` provides control over the resolution of the mesh it generates — can you not generate a smoother mesh to with a higher setting?  You might also want to look at https://www.npmjs.com/package/taubin-smooth, where `cells` are indices, which should work on data from martini.

I don't believe the three.js maintainers are able to provide a subdivision library right now. If someone would like to move SubdivisionModifier into a new repository, fix the known issues with it, and add support for BufferGeometry, that would probably be a useful project in its own right. The hard part is properly supporting UVs and other vertex attributes.

**Comment by arpu** [comment]
thx a lot @donmccurdy  for the clarification! will test the alternatives

**Comment by donmccurdy** [comment]
> If someone would like to move SubdivisionModifier into a new repository, fix the known issues with it, and add support for BufferGeometry, that would probably be a useful project in its own right.

On second thought — finishing the work described by https://github.com/PixarAnimationStudios/OpenSubdiv/issues/247 and getting OpenSubdiv compiled to WASM would be even better. That's a robust subdivision implementation, and would be valuable to have available in the web ecosystem.

**Comment by changkun** [comment]
How could you just removed it and break the compatibility without providing a single alternative solution?

**Comment by changkun** [comment]
Hi, sorry for commenting again. How could my previous comment become disruptive content? We are in a university and teaching students for using your excellent work, thus we appreciate your work a lot. but removing it without providing an alternative solution actually breaks the educational content, and very unfortunately there are no provided solutions from what I saw in this thread. Of course, the OpenSubdiv is an alternative solution but the setup cost for students goes much higher. The only solution would install v124, but it is actually discouraged from the community, am I right?

**Comment by arpu** [comment]
not sure from where his comes from https://github.com/mtnguru/ab/blob/1cd76561c4780a69e4db6e3287abec384499897d/js/threejs/modifiers/BufferSubdivisionModifier.js

**Comment by arpu** [comment]
@donmccurdy  would this be a good alternative?

**Comment by changkun** [comment]
@arpu Looks great, thanks a lot!  is it possible to merge it back or at least document the breaking change?

**Comment by donmccurdy** [comment]
three.js is an open source library and relies on contributors to maintain. SubdivisionModifier was effectively unmaintained, broken, and depended heavily on long-deprecated parts of three.js. With no contributors supporting something, that thing is likely to be eventually removed to allow the project to grow. The removal of SubdivisionModifier was documented under the [r125 release notes](https://github.com/mrdoob/three.js/releases/tag/r125).

If someone would like to test `BufferSubdivisionModifier` and maintain it, please feel free to open a PR. If there are no contributors willing to support a feature, it is unlikely to be supported.

**Comment by Mugen87** [comment]
> The removal of SubdivisionModifier was documented under the r125 release notes.

And in the migration guide 😇 .

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r124--r125

BTW: I think we should also discuss if new modifiers should added to the repo. To me, I see them in third-party repositories.

**Comment by mrdoob** [comment]
@stevinz Hmm, do you think we could/should bring back `SubdivisionModifier` and use your implementation instead?

**Comment by stevinz** [comment]
@mrdoob I think the `SubdivisionModifier` was a really nice addition to three.js. Since the switch to `BufferGeometry` and the removal of the modifier I've come across a number of discussions around the web searching for a replacement.

Personally, I feel pretty good about my implementation. It does a nice job with all the built-in geometries and was specifically tested using geometries with 'position', 'normal', 'uv', and 'color' attributes. It does attempt to handle other attributes contained within the geometry, but it has not been tested much against geometries with other attributes.

A few negatives I should mention, though:
- Speed was not an overall concern within the implementation.
- The algorithm prefers geometries with shared edges / vertices. This is true for all built-in geometries, but may not be with custom loaded geometries.
- Internally the algorithm converts Indexed geometries to Non-Indexed before the algorithm proceeds. The new geometry returned is always Non-Indexed (although a new Indexed geometry could easily be generated using [BufferGeometryUtils.mergeVertices](https://threejs.org/docs/?q=buffer#examples/en/utils/BufferGeometryUtils.mergeVertices)).
- There is no consideration for morphTargets / morphAttributes.

I know [there was discussion](https://github.com/mrdoob/three.js/pull/21014#issue-550543213) about reducing the amount of code to be maintained within three.js. However, if there is interest, I can submit a PR to bring back the `SubdivisionModifier` and am willing to help maintain it as best I can. Or if it's preferred to keep the code base smaller, I can submit a PR for an `External` example as I've noticed has been done [a few times recently](https://threejs.org/examples/?q=external), and can maintain the modifier on my repo.

**Comment by WestLangley** [comment]
>Or if it's preferred to keep the code base smaller, I can submit a PR for an External example as I've noticed has been done [a few times recently](https://threejs.org/examples/?q=external), and can maintain the modifier on my repo.

I vote for that, as it reduces the burden on the three.js maintainers.

**Pull request merged**
