### PR TITLE
Editor: Enhanced default script template

### PR DESCRIPTION
**Pull request by jmschrack**
Related issue: 

**Description**

For newcomers using the Three.JS Editor, the default template does not inform them of the available events and variables they can use. This PR just adds a comment block that lists out the events and variables.

Preview:

```
/*
========================================
Lifecycle Events:
init - Runs once after app.json is loaded.
start - Runs when APP.Play() is called.
update - Runs every frame before update.
stop - Runs when APP.Stop() is called.

Anything outside of an event will be run immediately when the script is loaded.

Local Variables:
player
renderer
scene
camera

Input Events:
keydown
keyup
pointerdown
pointerup
pointermove
========================================
*/
function update( event ) {}
```

### CODE REVIEW

**Comment by Mugen87** [comment]
I guess the usage becomes even more clear if the comment highlights that users have to implement functions and name them like the lifecycles and input events in order to make use of them. 

Instead of adding such a large inline comment, I wonder if it isn't better to explain the script usage in a GitHub wiki page which is then listed in the `Help` menu point.

**Comment by jmschrack** [comment]
That works for me.  Is there a process to submit requests to the wiki? Or should it be included as an HTML page in the docs folder?

**Comment by Mugen87** [comment]
If @mrdoob approves, we can create a new wiki page (e.g editor manual) which you can directly edit without having specific permissions.

**Comment by Mugen87** [comment]
Anyway, I have added a manual page with some basic information about scripting.

https://github.com/mrdoob/three.js/wiki/Editor-Manual

I'll make a PR in order to link from the editor to it.

**Pull request closed without merging**
