### PR TITLE
sea3d fixes, optimization, native script features

### PR DESCRIPTION
**Pull request by sunag**
- Improvement in performance. Use memcpy to read vector.
- Fixes lightMap/aoMap, additive or multiply.
- Fixes Keyframe Animation
  - Camera - http://community.poonya.com/165
  - Dummy - http://community.poonya.com/164
- Native Script Features. (article about this soon)
  - Domain
  - Domain Manager
  - Native Events
  - Script Manager

### CODE REVIEW

**Comment by mrdoob** [comment]
Are you intentionally targeting the `master` branch instead of the `dev` branch?

**Comment by sunag** [comment]
> Are you intentionally targeting the master branch instead of the dev branch?

Hi. Yes, would be the main fixes of sea3d to r72.

**Comment by sunag** [comment]
I will make it to the dev with improvements in animation system :pizza:

**Comment by mrdoob** [comment]
Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
