### PR TITLE
add reflectivity example.

### PR DESCRIPTION
**Pull request by bhouston**
Pulling across the reflectivity example updated to use @WestLangley's new MeshPhysicalMaterial from my previous PR: https://github.com/mrdoob/three.js/pull/8505

### CODE REVIEW

**Comment by bhouston** [comment]
@WestLangley, there seems to be an intensity difference between this example with MeshPhysicalMaterial:

http://ci.threejs.org/api/pullrequests/8535/examples/webgl_materials_reflectivity.html

image

And the previous PR:

image

http://ci.threejs.org/api/pullrequests/8505/examples/webgl_materials_reflectivity.html

The only change I made to the example was to change MeshStandardMaterial -> MeshPhysicalMaterial.  Thus this intensity change was unexpected.

**Comment by WestLangley** [comment]
Hmmm... I agree that does not make sense... I am not able to reproduce that symptom locally.

**Comment by bhouston** [comment]
You mean if you run both examples, they look the same?  Both bright or both dark?

**Comment by WestLangley** [comment]
The threejsworker links are not the same for me, either.

However, local testing using different models shows the rendered output of Standard and Physical identical.

**Comment by gero3** [comment]
@WestLangley I'm examined this now.
But even when I rebuild the threejsworker database, it still shows 2 different images.
It also shows different images when I pull and build both PRs on cloud9.

**Comment by bhouston** [comment]
Let's assume there was a bug in my previous PR and move on. :/

**Comment by WestLangley** [comment]
>Let's assume there was a bug in my previous PR and move on. :/

OK

**Comment by WestLangley** [comment]
@gero3 Sorry. I missed your post... Thank you for checking.

threejsworker is very helpful! : - )

**Comment by bhouston** [comment]
Ah, figured it out.  I had another separate PR that fixed the HDR maps to be true HDR, it was submitted parallel to the first reflectivity PR but was merged prior to the MeshPhysicalMaterial.  Thus everything is correct.

**Comment by mrdoob** [comment]
Thanks guys!

**Pull request merged**
