### PR TITLE
Manual translation for the Animation system section

### PR DESCRIPTION
**Pull request by luhaopeng**
Dump poor Google translation. I translated this section word by word manually.

Additionally, I fixed(maybe) the problem with those hyperlinks. Check how awful they are at https://threejs.org/docs/index.html#manual/zh/introduction/Animation-system

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/LuHaoPeng/three.js/patch-2/docs/index.html#manual/zh/introduction/Animation-system

**Comment by Mugen87** [comment]
Indeed, your version looks much better 👍

**Comment by LuHaoPeng** [comment]
By checking the testing page, I found out that formatted links like "[page:title remark]" and "[link:link remark]" wouldn't take Chinese for their parameters. And line breaks would automatically insert a space at the break.

Adjustments were made according to the above. It should be better now.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
