### PR TITLE
Examples: set .depthWrite to false for transparent materials

### PR DESCRIPTION
**Pull request by WestLangley**
Use the coding pattern we are currently recommending for this use case.

### CODE REVIEW

**Comment by mrdoob** [comment]
> set to 1 when transparency is non-zero

What does that mean? 🤔

**Comment by WestLangley** [comment]
@mrdoob See https://github.com/mrdoob/three.js/pull/18695#issuecomment-589478174.

**Comment by mrdoob** [comment]
Ah! I understand now.

How about `// set to 1 when material.transparency is non-zero`?
Or `// use material.transparency for glass materials`?

**Comment by WestLangley** [comment]
@mrdoob I implemented both suggestions! :-)

**Comment by mrdoob** [comment]
Pretty clear now!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
