### PR TITLE
EXRLoader: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
Removes all linter issues from `EXRLoader`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev32/examples/webgl_loader_texture_exr.html
https://raw.githack.com/Mugen87/three.js/dev32/examples/webgl_materials_envmaps_exr.html

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
FYI @richardmonette

**Comment by richardmonette** [comment]
Thanks!

**Pull request merged**
