### PR TITLE
Revert closure optimisations

### LINKED ISSUE #11226: Modules (or circular dependencies) broken in 85?
##### Description of the problem 

Using anything in THREE, even if it's just a Vector

```js
import { Vector3 } from 'three/src/Three';
console.log(Vector3)
```

causes:

    vendor.js:53016 Uncaught TypeError:
        __WEBPACK_IMPORTED_MODULE_0__Vector3__.a is not a constructor

for instance somewhere in Quaternion, which relies on Vector3.

```js
    setFromUnitVectors: function () {

        // http://lolengine.net/blog/2014/02/24/quaternion-from-two-vectors-final

        // assumes direction vectors vFrom and vTo are normalized
>>>>>>> var v1 = new __WEBPACK_IMPORTED_MODULE_0__Vector3__["a" /* Vector3 */]();
```

It looks like for some reason it can't resolve circular dependencies any longer, the internal require returns an empty object. It breaks r85 for module users. The only change i made was updating from 84 to 85.

##### Three.js version

- [x] r85

##### Browser

- [x] Chrome

##### OS

- [x] macOS

##### Build tool

- [x] Webpack 2.4.1

### PR DESCRIPTION
**Pull request by zorro-fr24**
Rollback for some seemingly safe optimisations that are causing circular dependency issues with third party module bundlers/transpilers such as webpack/babel 

Fixes #11226

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by drcmda** [comment]
@zorro-fr24  Awesome, thanks alot!

@mrdoob Can we get a quick npm revision for this?

**Comment by Mugen87** [comment]
@drcmda There will be a new npm revision with the next release. In the meanwhile, do you mind using the `dev` branch? Alternatively you have stay at `r84` until `86` is released.

**Comment by drcmda** [comment]
@Mugen87 Understood. Waiting out of 86 then. : )

**Comment by mrdoob** [comment]
Seems like this is no longer needed with webpack 2.5.1... https://github.com/mrdoob/three.js/issues/11226#issuecomment-299846009

**Pull request merged**
