### PR TITLE
GLTFLoader example: clean up

### PR DESCRIPTION
**Pull request by WestLangley**
1. Removed the animation loop since the scene is static.
2. Added exposure control.

IMO, the scene was over-bright. Just my opinion, of course.

Rather that reducing the environment intensity, which reduces the reflections, but leaves the background unchanged, I reduced the tonemapping exposure. I also added a gui.

/ping @donmccurdy

### CODE REVIEW

**Comment by WestLangley** [comment]
current:
https://threejs.org/examples/webgl_loader_gltf.html

ephemeral test link:
https://raw.githack.com/westlangley/three.js/dev_gltf_example/examples/webgl_loader_gltf.html

**Comment by Mugen87** [comment]
I think this example should just focus on `GLTFLoader`. A configurable tonemapping is necessary here.

**Comment by donmccurdy** [comment]
I'm going to be very unhelpful, and say that I aesthetically prefer the brightness of the model _before_, and the brightness of the environment _after_. I'm fine with whatever you want to do. 😅

**Comment by WestLangley** [comment]
@Mugen87 I can remove the GUI exposure control since you are opposed to it.

**Comment by Mugen87** [comment]
That would be good. Otherwise one  could argue to add it to all examples that use `MeshStandardMaterial` e.g. `webgl_materials_standard`.

**Comment by WestLangley** [comment]
>Otherwise one could argue to add it to all examples that use MeshStandardMaterial

@Mugen87 This has nothing to do with `MeshStandardMaterial`; it has to do with the use of HDR textures and lighting.

Scenes that use HDR must have tonemapping and exposure control to accommodate LDR monitors.

>But apart from that, I still think the new example looks too dark.

It is a subjective decision. That is why we have exposure control.

**Comment by WestLangley** [comment]
@donmccurdy It is important to me that the brightness of the reflections look compatible with the brightness of the rendered background. And yes, we all have different views on what looks correct.

I have long felt that `.envMapIntensity` should not be a property of the material -- it should be a property of the specular light probe, or environment map. Granted, as implemented, it adds a degree of flexibility to the artist -- but I don't like it.

We could restore some flexibility by adding `scene.backgroundIntensity` if @mrdoob refactors the background code.

**Comment by Mugen87** [comment]
> This has nothing to do with MeshStandardMaterial; it has to do with the use of HDR textures and lighting.

Well, that was what I wanted to refer to. Thanks for the indoctrination.

**Comment by Mugen87** [comment]
> I have long felt that .envMapIntensity should not be a property of the material -- it should be a property of the specular light probe, or environment map. Granted, as implemented, it adds a degree of flexibility to the artist -- but I don't like it.

How about making a new issue for this?

**Comment by mrdoob** [comment]
I agree with everyone!

1. I agree that the scene is over-bright (but I would set `toneMappingExposure` to `0.8` instead).
2. I agree that the GUI is not needed.
3. I agree that `.envMapIntensity` should not be a property of the material.

**Comment by WestLangley** [comment]
Done!  Exposure reduced. GUI removed. Animation loop removed.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
