### PR TITLE
function explanation

### PR DESCRIPTION
**Pull request by cg-cnu**
Very small clean up 
* Removed the indentation in the example code.
* Improved the wording on the function explanations.

🙂

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Guys,

1. I would specify when an argument is _optional_, not when it is required.
```javascript
[page:Function onLoad] — (optional) A function to be called ...
```
2. This change needs to be applied to _all_ the loader's docs, consistently. @cg-cnu Would you be willing to make that change, too?

Less important, but I'll mention it anyway:

>"The function receives the error."

I think it should be "the function is passed the error". I'll leave that up to @mrdoob and @Mugen87.

**Comment by mrdoob** [comment]
Sounds good to me.
@cg-cnu would you like to do another PR addressing @WestLangley's points?

**Comment by cg-cnu** [comment]
@WestLangley Thanks for the input. I will make the changes across all the loaders. 😄 

> the function is passed the error

I know its a very debateable discussion. In case of doubt, my approach is to refer to the existing projects and see how they are approaching it. So, before writing this I refereed to [ajax documentation](http://api.jquery.com/jQuery.ajax/). (check the error method wording) 

@mrdoob Am on it. I can do a pull over the weekend. 🙂

**Pull request merged**
