### PR TITLE
Minimap demo

### PR DESCRIPTION
**Pull request by LeonYuanYao**
Added examples/jsm/misc/Minimap.js & examples/webgl_camera_minimap.html for demo purpose.

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please remove the changes to `three.module.js` and `WebGLRenderer.js`?

**Comment by Mugen87** [comment]
For testing: http://raw.githack.com/LeonYuanYao/three.js/minimap-demo/examples/webgl_camera_minimap.html

**Comment by WestLangley** [comment]
Nice demo. However, I think it is more appropriate as a forum showcase than as a three.js example.

The three.js examples demonstrate -- and serve as test cases of -- three.js features.

This is a three.js application.

**Comment by LeonYuanYao** [comment]
> Can you please remove the changes to `three.module.js` and `WebGLRenderer.js`?
> 
> Normally you would create `js/misc/Minimap.js` instead and generate the module version via `node utils/modularize.js`. However, I remember that @mrdoob is okay when new files are only added as modules, see [#16920 (comment)](https://github.com/mrdoob/three.js/pull/16920#issuecomment-531446949).

Hi, Mugen87
I have restored the changes in the WebGLRenderer.js and re-build the three.js and three.module.js. It seems some '__proto__: null,' codes were added into the built files. Is that acceptable?

**Comment by LeonYuanYao** [comment]
> Can you please remove the changes to `three.module.js` and `WebGLRenderer.js`?
> 
> Normally you would create `js/misc/Minimap.js` instead and generate the module version via `node utils/modularize.js`. However, I remember that @mrdoob is okay when new files are only added as modules, see [#16920 (comment)](https://github.com/mrdoob/three.js/pull/16920#issuecomment-531446949).

Hi, Mugen87
I have restored the changes in the WebGLRenderer.js and re-build the three.js and three.module.js. It seems some '__proto__: null,' codes were added into the built files. Is that acceptable?

**Comment by LeonYuanYao** [comment]
> Nice demo. However, I think it is more appropriate as a forum showcase than as a three.js example.
> 
> The three.js examples demonstrate -- and serve as test cases of -- three.js features.
> 
> This is a three.js application.

Hi, WestLangley 
Thank you for the advice! Yes, maybe I should consider submitting this as a showcase. But I don't know how to do that yet. Can you please provide some instructions or maybe accept this as a showcase? Just want to give a demo and module codes for people who need 'minimap' functionality. =)

**Comment by Mugen87** [comment]
> I have restored the changes in the WebGLRenderer.js and re-build the three.js and three.module.js. It seems some 'proto: null,' codes were added into the built files. Is that acceptable?

Not really. You should actually never commit build files.

> Can you please provide some instructions or maybe accept this as a showcase?

Showcases are shared at the official [forum](https://discourse.threejs.org/). You can login with your github account and then create a new topic in the category `Showcase`.

**Comment by LeonYuanYao** [comment]
It's a clean commit now with Minimap.js, the moduled version and the demo html files only!

**Comment by Mugen87** [comment]
I agree with @WestLangley. In the meanwhile, it's recommended to use the forum for such work since we try to avoid application specific code in the library as much as possible.

**Pull request closed without merging**
