### PR TITLE
Added example for peppers ghost effect

### PR DESCRIPTION
**Pull request by tpowellmeto**
This is an example renderer effect to use in conjunction with a reflective prism to illustrate the 'peppers ghost effect' (3D hologram effect)

See these links for more info:
https://en.wikipedia.org/wiki/Pepper%27s_ghost
http://www.instructables.com/id/Reflective-Prism/

### CODE REVIEW

**Comment by mrdoob** [comment]
Looks good!

**Comment by mrdoob** [comment]
Thanks!

**Comment by arose** [comment]
Nice, any reason why the example is not linked in `index.html`?

**Comment by tpowellmeto** [comment]
sorry, I totally forgot to do that! - whats the best way make another change?

**Pull request merged**
