### PR TITLE
Issue #10883: STLLoader's binary check trips up

### PR DESCRIPTION
**Pull request by dnewman-polar3d**
This commit addresses Issue #10883 in which the isBinary() check of an STL data stream can incorrectly identify a syntactically invalid but still useful ASCII STL as being binary.  Namely, the ASCII STL will be identified as binary if the ASCII STL data presents a non-US-ASCII 'name' field parameter with the 'solid' or 'endsolid' keywords.  E.g.,

    solid 穿山甲
    facet normal 0.7071067717164974 -0.00016366188967739515 0.707106771716591
      outer loop
        vertex 135.89921424250542 449.7206946618269 58.1296582226351
    ...
        endloop
    endfacet
    endsolid 穿山甲

Note that as ASCII STLs must be in US-ASCII, they may contain no characters with the high bit set.  As such, the example above is syntactically invalid.  However, more and more such ASCII STLs are appearing.  Moreover, the isBinary() check itself is tripping up as it tries to accommodate a potentially incorrect binary STL for which the computed data length disagrees with the observed data length.  So, it's something of a juggling act as the code attempts to accommodate different, broken inputs.

This commit attempts to address this issue while making minimal disruption to the present code.  After the data length is computed but found to not agree, this change next looks for the US-ASCII phrase 'solid' at/near the start of the data.  If it is found, then the STL is declared to NOT be binary.  Then, the existing check of the data for any non US-ASCII characters is performed. That is, a new check has been inserted between the length check and the 8bit character check.  A more robust change might be to look for 'solid' in the first five bytes of the data and, if found, declare it ASCII from the get go.

### CODE REVIEW

**Comment by mrdoob** [comment]
How about...

```js
// US-ASCII ordinal values for 's', 'o', 'l', 'i', 'd'
var solid = [ 115, 111, 108, 105, 100 ];

for ( var i = 0; i < 5; i ++ ) {
    if ( solid[ i ] !== reader.getUint8( i, false ) ) return false;
}

return true;
```

**Comment by dnewman-polar3d** [comment]
That's my preference actually.  Question is, first check or second check?  The STL format spec wasn't written with a lot of care....   A binary STL starts with a fixed length, 80 byte header of "ASCII" characters (US-ASCII, I presume).  And it has "no data signficance".   No explicit statement that it SHOULD or MUST not begin with "solid" however.

So, you may want to make the binary length check.  Then the check for "solid" in the first 5 bytes.  Then the check for non-US-ASCII chars.

I.e., what I pushed but only checking the first 5 bytes, not the first 50.

**Comment by dnewman-polar3d** [comment]
I can withdraw the old pull request and do a new one if you'd like

**Comment by dnewman-polar3d** [comment]
Oh, boolean return values are flipped in your code snippet above, should be

    // US-ASCII ordinal values for 's', 'o', 'l', 'i', 'd'
    var solid = [ 115, 111, 108, 105, 100 ];
    
    for ( var i = 0; i < 5; i ++ ) {
        // If solid[ i ] doesn't match i-th byte, then it's not a valid ASCII STL; hence, isBinary() === true
        if ( solid[ i ] !== reader.getUint8( i, false ) ) return true;
    }

    // The first 5 bytes read "solid".   Appears to be a valid ASCII STL
    return false;

**Comment by mrdoob** [comment]
You should be able to push a new commit to your branch and it'll update this PR.

**Comment by mrdoob** [comment]
Oh yes, sorry. I didn't know the check was to say if it's Binary or Text 😅

**Comment by dnewman-polar3d** [comment]
Pushed

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
