### PR TITLE
Mild glsl improvements

### PR DESCRIPTION
**Pull request by benaadams**
Remove unneeded function calls, rearrage for fused multiply–add as noticed in #6335

### CODE REVIEW

**Comment by bhouston** [comment]
I'd like to keep square and saturate as utility function calls.  Saturate is supported in CG and HLSL and UE4's custom shader language and is quite useful.  Square is nice as well.  They both have the effect of cleaning up code.

 It doesn't hurt to leave them there I believe.  Can we just not remove these functions?

You also didn't remove all usages of square().

**Comment by benaadams** [comment]
@bhouston will make the changes, not fussed about whiteCompliment?

**Comment by benaadams** [comment]
Although it currently means the functions are compiled into every standard vertex and fragment shader; although unlikely to have much impact and can use RawShaderMaterial if doing something unusual where instruction count becomes and issue.

**Comment by bhouston** [comment]
I grabbed whitecompliment from vray's shaders.  It is useful in subtractive
calculations but it is less useful than others.  Such as transparency
tinting.  I am also okay with removing square after some thought.  But
saturate is really useful and cleans up the code.

**Comment by benaadams** [comment]
Changed the missed ````square()```` call in ````fog_fragment.glsl```` also removed ````average()```` which I didn't originally remove as it is a slightly more complex function. However it isn't actually used anywhere. The two places that do an average in examples use their own glsl:

https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/DotScreenShader.js#L60
````glsl
float average = ( color.r + color.g + color.b ) / 3.0;
````

https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/HueSaturationShader.js#L58
````glsl
float average = (gl_FragColor.r + gl_FragColor.g + gl_FragColor.b) / 3.0;
````

````square()```` I can see has its usefulness but again OceanShaders.js example which uses it as otherwise it would need to introduce an extra variable:
````glsl
float Gamma = exp(-square(sqrt(k / kp) - 1.0) / 2.0 * square(sigma));
````
Which as the following shows becomes less immediately graspable as an understandable formula and worse therefore as a learning resource:
````glsl
float n = sqrt(k / kp) - 1.0;
float Gamma = exp( - 0.5 * n * n * sigma * sigma);
````
However, it defines its own square function for this purpose:
https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/OceanShaders.js#L109
````glsl
float square (float x) {
   return x * x;
}
````
So within three.js they are (with this PR) all unused; even in the examples which make use of the functions, as they define their own. I'm not denying the usefulness of the functions and the example in OceanShaders.js really improves clarity. However, they are all fairly trivial functions to write when needed and if you do need them you are already writing custom glsl and not using three.js' inbuilt shaders as is. So my concern is mostly around their inclusion in common.glsl as their use internally isn't that common, however being in common.glsl means they are included in every vertex and fragment shader. This means every three.js shader starts with 24 functions, of which this PR removes 16 of them. 

If you write your own shader with ````THREE.ShaderMaterial```` or ````THREE.RawShaderMaterial```` as I understand it ````common.glsl```` isn't included and these functions aren't available for use anyway, so they aren't really serving any purpose?

**Comment by bhouston** [comment]
Just to be clear if the functions are not used they do not take up any
instructions at all.

**Comment by benaadams** [comment]
atm they would be dead code as not used anywhere and are unreachable by custom shaders without manually including the common shader chunk.

To recreate this I have created a helper.glsl file that if you include the helper shader chunk will include these functions - would that be an acceptable compromise?

**Comment by bhouston** [comment]
@benaadams Is there a performance issue you measured that motivated this change?  I believe that encouraging a library of reusable functions in the GLSL shaders is really useful.  Most mature engines do that -- to huge extents as well.

**Comment by bhouston** [comment]
This PR here of mine will dramatically speed up ThreeJS in a lot of situations because it improves recycling of programs.  https://github.com/mrdoob/three.js/pull/5789  I've seen things jump from 4 fps to 50 fps from this simple change.  Spending effort on getting the idea behind PR #5789 accepted in some form into ThreeJS is a lot more valuable than this PR that worries about a few milliseconds.

**Comment by benaadams** [comment]
Added PR #6342 for your other issue.

The point is these functions are dead code and do nothing. They are not used in the three.js shaders and you can't use them in custom shaders without including ````THREE.ShaderChunk[ "common" ]```` in your glsl string build; in which case its easy enough to change this to ````THREE.ShaderChunk[ "helper" ]````.

Their inclusion means there are 16 functions for the compiler to decide to discard in both the fragment and vertex shader; if you have 20 shaders in use that is 640 functions for the shader compiler to decide to discard and 100 shaders would be  3200 functions to discard. As you noticed in PR #5789 the shader compiler isn't very fast and it gets even slower on mobile platforms, tablets and WinRT devices.

A secondary motivation is I spend a lot of time in shader debuggers tweaking shaders (would recommend the Firefox shader debugger) or checking programs in WebGL Inspector to see if they are what I expect. Without these changes it's 113 lines to get to your code if you use a ````THREE.ShaderMaterial```` with the start of *every* glsl shader; fragment and vertex, looking like this:
````glsl
precision highp float;
precision highp int;


#define MAX_DIR_LIGHTS 0
#define MAX_POINT_LIGHTS 0
#define MAX_SPOT_LIGHTS 0
#define MAX_HEMI_LIGHTS 0
#define MAX_SHADOWS 0



#define GAMMA_FACTOR 2
#define USE_FOG











#define USE_COLOR










uniform mat4 viewMatrix;
uniform vec3 cameraPosition;
#define PI 3.14159
#define PI2 6.28318
#define RECIPROCAL_PI2 0.15915494
#define LOG2 1.442695
#define EPSILON 1e-6

float square( in float a ) { return a*a; }
vec2  square( in vec2 a )  { return vec2( a.x*a.x, a.y*a.y ); }
vec3  square( in vec3 a )  { return vec3( a.x*a.x, a.y*a.y, a.z*a.z ); }
vec4  square( in vec4 a )  { return vec4( a.x*a.x, a.y*a.y, a.z*a.z, a.w*a.w ); }
float saturate( in float a ) { return clamp( a, 0.0, 1.0 ); }
vec2  saturate( in vec2 a )  { return clamp( a, 0.0, 1.0 ); }
vec3  saturate( in vec3 a )  { return clamp( a, 0.0, 1.0 ); }
vec4  saturate( in vec4 a )  { return clamp( a, 0.0, 1.0 ); }
float average( in float a ) { return a; }
float average( in vec2 a )  { return ( a.x + a.y) * 0.5; }
float average( in vec3 a )  { return ( a.x + a.y + a.z) / 3.0; }
float average( in vec4 a )  { return ( a.x + a.y + a.z + a.w) * 0.25; }
float whiteCompliment( in float a ) { return saturate( 1.0 - a ); }
vec2  whiteCompliment( in vec2 a )  { return saturate( vec2(1.0) - a ); }
vec3  whiteCompliment( in vec3 a )  { return saturate( vec3(1.0) - a ); }
vec4  whiteCompliment( in vec4 a )  { return saturate( vec4(1.0) - a ); }
vec3 transformDirection( in vec3 normal, in mat4 matrix ) {
	return normalize( ( matrix * vec4( normal, 0.0 ) ).xyz );
}
...
````
These changes reduce that to 70 lines; still quite high, with the start looking like this which is much better:
````glsl
precision highp float;
precision highp int;
#define MAX_DIR_LIGHTS 0
#define MAX_POINT_LIGHTS 0
#define MAX_SPOT_LIGHTS 0
#define MAX_HEMI_LIGHTS 0
#define MAX_SHADOWS 0
#define GAMMA_FACTOR 2
#define USE_FOG
#define USE_COLOR
uniform mat4 viewMatrix;
uniform vec3 cameraPosition;
#define PI 3.14159
#define PI2 6.28318
#define RECIPROCAL_PI2 0.15915494
#define LOG2 1.442695
#define EPSILON 1e-6

vec3 transformDirection( in vec3 normal, in mat4 matrix ) {
	return normalize( ( matrix * vec4( normal, 0.0 ) ).xyz );
}
...
````

**Comment by bhouston** [comment]
> Added PR #6342 for your other issue.

Thanks!  That is a massive speed up. :)

Feel free to remove the code as you feel strongly about it, but I think that the common.glsl and the shader headers will get larger as we move forward -- it is the best way to organize the code.

**Comment by mrdoob** [comment]
@benaadams should I merge #6335 first?

**Comment by benaadams** [comment]
@mrdoob yes probably, I'll clear up any conflicts that occur

**Comment by WestLangley** [comment]
@benaadams @bhouston In #6335, I had some difficulty figuring out where to place the method `calcCosineTerm()`. It has to be defined after `wrapRGB`. I feel there should be more chunks -- or something... I'll leave the design decisions to the experts. : - )

**Comment by benaadams** [comment]
Closing this as its picked up in PR #6347

**Pull request closed without merging**
