### PR TITLE
package.json: updated deps

### PR DESCRIPTION
**Pull request by linbingquan**
**Description**

Updated package.json for deps.

### CODE REVIEW

**Comment by Mugen87** [comment]
You can't just update the `package.json` file without updating `package-lock.json`, too. Both are actually coupled.

**Comment by mrdoob** [comment]
Probably better to update dependencies after the release.

**Comment by linbingquan** [comment]
> You can't just update the `package.json` file without updating `package-lock.json`, too. Both are actually coupled.

OK, Here you are.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
