### PR TITLE
Replaced Google Closure compiler with Terser

### PR DESCRIPTION
**Pull request by mrdoob**
Giving [Terser](https://terser.org/) a try, we can revert if we bump into problems.

This simplifies the build setup so it's all done inside rollup now.
The script also automatically adds the `// threejs.org/license` header so we won't have to worry about it anymore.

### CODE REVIEW

**Comment by mrdoob** [comment]
Updated the PR so gl constants don't get replaced in non-minified builds.

Fixes #16066

**Comment by Mugen87** [comment]
> Creating three.module.min.js is also straightforward.

Please consider https://github.com/mrdoob/three.js/issues/15176#issuecomment-605696623. I'm afraid the existence of `three.module.min.js` will cause a lot of issues...

**Comment by Mugen87** [comment]
> Updated the PR so gl constants don't get replaced in non-minified builds.

Most users who use a build system will now miss the constant replacement in `three.module.js`.

**Comment by mrdoob** [comment]
> All users who use a build system will now miss the constant replacement (since they use `three.module.js`).

Yes, I'm aware of that. We can change `package.json` so it points to `three.module.min.js` instead.

**Comment by mrdoob** [comment]
> Please consider https://github.com/mrdoob/three.js/issues/15176#issuecomment-605696623. I'm afraid the existence of `three.module.min.js` will cause a lot of issues...

Damn. I didn't think of that.
Yes, we can't do this until import maps are available, or we come up with an alternative.

**Comment by mrdoob** [comment]
> All users who use a build system will now miss the constant replacement (since they use `three.module.js`).

I'll do some measurements to see what filesize savings these provide.

**Comment by Mugen87** [comment]
> I'll do some measurements to see what filesize savings these provide.

Question: Didn't you add the constant replacement primarily for performance reasons? I thought it would be faster to just embed the value instead of looking it up over the `gl` reference...

**Comment by mrdoob** [comment]
> Question: Didn't you add the constant replacement primarily for performance reasons?

I think the original intent was filesize savings, but performance improvements was a side effect that I forgot. I guess I'll revert that too haha 😅

Although I know that sometimes when debugging your project you find yourself having to look up these constants. But I haven't heard anyone mentioning that recently.

**Comment by mrdoob** [comment]
Hmm, what a strange thing.

Screen Shot 2020-09-15 at 7 43 53 PM

**Comment by mrdoob** [comment]
Well, that fixed it. I don't even want to know why that happened.

**Comment by mrdoob** [comment]
@Mugen87 looks good to you?

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
BTW: I've switched to Terser since a while now because of the easier rollup integration and made good experiences 👍 .

**Pull request merged**
