### PR TITLE
ObjectLoader: Fix TS definition of .load()

### PR DESCRIPTION
**Pull request by jeffreylanters**
The Object3D typings we're missing the material.

### CODE REVIEW

**Comment by Mugen87** [comment]
This seems to be a mistake. `Object3D` does not have a `material` property.

**Comment by jeffreylanters** [comment]
> This seems to be a misunderstanding. `Object3D` does not have a `material` property.

But it does work, when I log an `Object3D` object, I'll see and can set the material.

**Comment by jeffreylanters** [comment]
Screenshot 2019-03-13 at 11 18 31

**Comment by Mugen87** [comment]
It looks like you are working with an instance of `Mesh`.

**Comment by jeffreylanters** [comment]
The variable comes straight out of the object loader, it's untouched. There might my another mistyping?

image

**Comment by jeffreylanters** [comment]
When I log the Object3D
Screenshot 2019-03-13 at 11 30 52

The material does exist
Screenshot 2019-03-13 at 11 31 09

**Comment by Mugen87** [comment]
`Mesh` is derived from `Object3D`. I think if you study the source code of `Object3D` and `Mesh`, things should become more clear:

https://github.com/mrdoob/three.js/blob/09e1fde724b89e2de4d5e774de27f137ab13d97c/src/core/Object3D.js#L21-L101
https://github.com/mrdoob/three.js/blob/09e1fde724b89e2de4d5e774de27f137ab13d97c/src/objects/Mesh.js#L20-L33

**Comment by jeffreylanters** [comment]
Okay, I see what you mean. But still, the ObjectLoader packed in the module, returns an object with the Typescript Type `Object3D`, and it does contain `material`, but it's not typed.

**Comment by Mugen87** [comment]
> returns an object with the Typescript Type Object3D, and it does contain material, but it's not typed.

Then there is a problem in `ObjectLoader.d.ts`. The `onLoad()` callback of `ObjectLoader.load()` can return many different types of objects e.g. `Scene`, `Mesh`, `LineSegments` etc. It would not make sense to put all the properties of these classes to `Object3D.d.ts`, right? Instead, the following line needs to be changed:

https://github.com/mrdoob/three.js/blob/09e1fde724b89e2de4d5e774de27f137ab13d97c/src/loaders/ObjectLoader.d.ts#L16

**Comment by jeffreylanters** [comment]
I see what is going on. Thanks for clearing it up! It could be a `generic key of type`, function to keep it more strict.

**Comment by Mugen87** [comment]
Like so?

https://github.com/mrdoob/three.js/blob/09e1fde724b89e2de4d5e774de27f137ab13d97c/src/loaders/ObjectLoader.d.ts#L22

**Comment by mrdoob** [comment]
> It would not make sense to put all the properties of these classes to `Object3D.d.ts`, right?

Wouldn't this work?

```
onLoad?: (object: Scene | Mesh | Line | LineSegments | Points) => void,
```

**Comment by Mugen87** [comment]
As an alternative, I think it would also work to define a generic type derived from `Object3D`.
```
onLoad?: <T extends Object3D>(object: T) => void,
```
Not sure which approach is better  🤔

**Comment by mrdoob** [comment]
> Not sure which approach is better 🤔

@jeffreylanters you choose 🙂

**Comment by jeffreylanters** [comment]
> As an alternative, I think it would also work to define a generic type derived from `Object3D`.
> 
> ```
> onLoad?: <T extends Object3D>(object: T) => void,
> ```
> Not sure which approach is better 🤔

Like I said before, I think a generic approach would be the best way to go. I think this looks is perfect. Thanks for thinking with me!

**Comment by jeffreylanters** [comment]
I've updated the PR.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
