### PR TITLE
Docs: Update 'Creating A Scene' code

### PR DESCRIPTION
**Pull request by ayushmanchhabra**
Related issue: #XXXX

**Description**

- Update `cube.rotate.x` and `cube.rotate.y` to `cube.rotateX()` and `cube.rotateY()` respectively
- Make function declarations consistent
- Made the above changes for all languages

### CODE REVIEW

**Comment by Mugen87** [comment]
> Update cube.rotate.x and cube.rotate.y to cube.rotateX() and cube.rotateY() respectively

I'm not sure we should do that. Modulating the properties `position`, `rotation` and `scale` should be the first choice when transforming objects.

> Make function declarations consistent

For simplicity I vote to use ordinary function declarations. So just:
```js
function animate() {

    requestAnimationFrame( animate );
    renderer.render( scene, camera );

}
```

**Comment by ayushmxn** [comment]
> I'm not sure we should do that. Modulating the properties `position`, `rotation` and `scale` should be the first choice when transforming objects.

My code editor's IntelliSense showed me there was no `rotate` property on `cube` so I went with `rotateX` and `rotateY` which worked. After looking into the source realized `rotate` had changed to `rotation`!

> For simplicity I vote to use ordinary function declarations. So just:

Sure!

**Comment by ayushmxn** [comment]
> My code editor's IntelliSense showed me there was no `rotate` property on `cube` so I went with `rotateX` and `rotateY` which worked. After looking into the source realized `rotate` had changed to `rotation`!

Just realized I must have misread `rotation` as `rotate`!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
