### PR TITLE
Use unit norm when finding plane distanceToPoint

### PR DESCRIPTION
**Pull request by casawa**
In case the normal supplied is not of unit length.

### CODE REVIEW

**Comment by WestLangley** [comment]
Thanks for checking the code. The more the better!

All normal vectors in three.js are assumed to be of unit length. This is not something we check.

We can add a comment in the `Plane` docs.

**Comment by casawa** [comment]
Ah -- is it worth it to maybe call normalize upon initialization? That way, say I want the norm to be in the direction of <0.5, 1, 0>, then as a client I don't necessarily need to always calculate the normalized version and constant on my end.

**Comment by WestLangley** [comment]
>is it worth it to maybe call normalize upon initialization?

If we did that, the plane constant would be immediately changed after setting it, which may lead to more confusion.

We assume normals and direction vectors have unit length. It is best to be consistent throughout the library, so users know what to expect.

**Comment by casawa** [comment]
Makes sense; will try to add a small comment to the Plane docs.

**Comment by WestLangley** [comment]
>Makes sense; will try to add a small comment to the Plane docs.

Yes,  please do.

**Pull request closed without merging**
