### PR TITLE
Render HTML document in Texture (for VR UIs)

### PR DESCRIPTION
**Pull request by 0X-JonMichaelGalindo**
Edit Jul. 27, 2021:
Latest Firefox update broke SVG rendering for most of my tests. Not sure what they're doing over there at Mozilla, but this works only in Chrome now. (Well, some simple layouts still work in Firefox.)

---

Create a new texture from an HTML document URL (instead of from an image or data). Update that texture by interacting the with its [HTML DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model).

Three.js browser apps create user interfaces using HTML/CSS positioned over the WebGL canvas. That is not possible in VR.
This class renders an HTML document to a texture, which can then be drawn onto a VR surface.

- [source](https://github.com/0X-JonMichaelGalindo/three.js/blob/dev/examples/jsm/textures/HTMLTexture.js)
- [doc](https://raw.githack.com/0X-JonMichaelGalindo/three.js/dev/docs/index.html#examples/en/textures/HTMLTexture)
- [example](https://raw.githack.com/0X-JonMichaelGalindo/three.js/dev/examples/#webxr_vr_html_ui)

Usage:
```js
const myURL = 'example/mystuff/my-ui.html';

const width = 256;
const height = 256;

const htmlTexture = new HTMLTexture( myURL, width , height );


function render() {

    /* Update styles, text, etc. */

    const someElement = htmlTexture.document.getElementById( 'my-element' );

    someElement.classList.add( "highlighted" );

    /* Redraw the texture. */

    htmlTexture.redrawAsync();


    renderer.render( scene, camera );

}
```

---

Alternatives, (writing text to a canvas, positioning text meshes), fall far short of HTML / CSS features:

Developer familiarity, frameworks, extensions, templates, tutorials, real-time previewing, prototyping and inspection tools, with ongoing maintenance by browser teams. 
Plus, these are non-trivial systems: content re-flowing, flexible alignment and sizing, modular elements, reusable styles, font rendering, kerning, and switching.

---

Do VR developers want this? Yes. The consensus is that this is simply not possible. Three.JS VR frameworks exist to fill the role, but lack nearly all of what makes HTML / CSS powerful.

---

webxr_vr_html_ui

---

This idea can go much further. My personal project's version has pointer events from UV-mapped mesh intersections / projections. Turns any VR surface (doesn't have to be square / flat) into a touch screen for any interface a website can display. (With UI development in the browser before VR deploy! Couldn't live without it.) Keeping it simple here. Can extend someday.

(Edit 28 June, now supports everything* except scroll and iframes.)

*Probably.

### CODE REVIEW

**Comment by mrdoob** [comment]
> My personal project's version has pointer events from UV-mapped mesh intersections / projections.

Any change you can share that piece of code too? When I looked at this approach I couldn't figure it out.

**Comment by mrdoob** [comment]
> - [example](https://raw.githack.com/0X-JonMichaelGalindo/three.js/dev/examples/#webgl_html_texture)

Hmm, I'm getting this... 🤔

Screen Shot 2021-06-17 at 1 05 49 PM

**Comment by 0X-JonMichaelGalindo** [comment]
For the error: pull request on hold until I figure it out.
Works in Firefox, but now I'm getting the same thing when I try in Chrome. There's no cross-origin content here to taint the canvas, so absenting browser bug, I'll be able to fix it. I'll look into.

For the other piece of code: It's scattered across 7,000 lines of a VR app and barely works.

But the idea is straight forward: 
1. Add the texture's HTML DOM to the browser's live DOM inside a hidden element so we can compute screen coordinates (offsetX,Y,Width,Height)
2. For any mesh with UVs, get the UVs at an intersect (cast a ray to a triangle (or intersect an XYZ with a triangle), get the UV at the intersection).
3. That UV * texture{width,height} is now a screen XY coordinate
4. Use document.elementFromPoint to get the intersected element in our hidden DOM holder
5. Depending on controller buttons / elementFromPoint history, fire events (enter, leave, interact, etc.)
6. In event handlers for those events, update the DOM styles, then redraw the texture.

I don't try to imitate the standard pointer events because I didn't want to mess with the 'isTrusted' flag. I just use 'vr-pointerover' ,'vr-pointerdown', etc. But if you could handle the isTrusted flag right, you might be able to use quite a few libraries designed for the browser. Definitely a long-term project to turn this idea into general-use code.

To be clear: This does not mean you could just fetch a url and draw it to VR. It only means that many HTML/CSS libraries could potentially be brought into VR using this approach and some mediating JS. As far as I know, this is limited to HTML/CSS for VR. I have no approach for making it JS/HTML/CSS for VR.

**Comment by 0X-JonMichaelGalindo** [comment]
> This does not mean you could just fetch a url and draw it to VR

Hmmm. Actually, once a page has finished loading in an iframe, you can traverse its DOM to collect all the CSS text. 2 lines? Its HTML 1 line. Shadow roots? What about nested iframes? Place-holders for elements we can't render (video, webgl)? Can we poll those per draw forward their textures to VR? There's nothing performant about the idea, but it's interesting to think about.

Anyway, for now, I'll stick with getting this working.

**Comment by 0X-JonMichaelGalindo** [comment]
OK. Fixed the Chrome bug. Ready to pull again.

I think Chrome's tainted canvas check was failing because the blob's URL was revoked before upload to GPU. Without a record of where that blob in the canvas history came from, the canvas would have to default to tainted. Firefox must be implementing the check differently or be keeping some records on revoked URLs.

**Comment by mrdoob** [comment]
> I don't try to imitate the standard pointer events because I didn't want to mess with the 'isTrusted' flag. I just use 'vr-pointerover' ,'vr-pointerdown', etc. But if you could handle the isTrusted flag right, you might be able to use quite a few libraries designed for the browser. Definitely a long-term project to turn this idea into general-use code.

This is the how I implemented it myself:

https://github.com/mrdoob/three.js/blob/2f6358dd55956e4f3595f304b2b2c925551228d3/examples/jsm/interactive/HTMLMesh.js#L268-L307

**Comment by 0X-JonMichaelGalindo** [comment]
(To be honest, I didn't notice you had implemented a version of this. I'm still unfamiliar with a lot of three.js.)

Rectangles are how I planned hit-testing originally, but elementFromPoint is the only way.
CSS has clip geometry, opacity, layering, and pointer-event ignoring that I couldn't deal with in my code. (Realized after the first time I clicked a hover menu and triggered a button on the page under it.)

When I fire an event, I limit it to 1 target, so I can handle bubbling / cancelling normally inside handlers.

I think it is possible to use normal mouse events though, just like you do here. 
Hard to remember, but I think when I first tried implementing these VR menus, I tried using normal pointer events, but the :hover effect never worked. It was because of '.isTrusted=false', so I just changed course immediately and went with custom events instead. Definitely worth revisiting.

**Comment by 0X-JonMichaelGalindo** [comment]
Added support for screen coordinates (offsetWidth, offsetHeight, getClientRect(), etc.).

Successfully implemented elementFromPoint without dirtying the screen / normal page input. 
Wont break queries, but DOM traversals will be affected. No user-friendly way around that. 
I'm 90% sure it never reflows the page. Maybe 91% sure.

```javascript
htmlTexture.document.getElementById( 'mybutton' ).onclick = () => console.log( 'hi there!' );

htmlTexture.elementFromPoint( 100,100 ).dispatchEvent( new MouseEvent( 'click' ) );

//>hi there!
```

**Comment by 0X-JonMichaelGalindo** [comment]
Added two methods, addPointer( vec2, down ) and updatePointer( vec2, down ) to simulate a mouse.

Supports click event per https://www.w3.org/TR/uievents/#event-type-click
Supports mouse events per https://w3c.github.io/uievents/#dom-mouseevent-mouseevent
Supports pointer events per https://w3c.github.io/pointerevents/#pointerevent-interface
Supports multitouch via pointer events.

Not going to support hover, must simulate behavior with onmouseover / onmouseout
Not going to support focus, must simulate behavior with onclick
Not going to support pointercapture. Simulate behavior by directly firing events on target.
Not going to support pointercancel, since no hardware requirements exist.

No plans to support 'dblclick', can support if desired.

```html
<button onclick="console.log('hi there!'); this.style.color='red';">Click Me</button>
```

```javascript
let myPointer = new THREE.Vector2( 10 , 10 );

htmlTexture.addPointer( myPointer, true ); //mouse down
htmlTexture.updatePointer( myPointer, false ); //mouse up

//>hi there!
```

**Comment by 0X-JonMichaelGalindo** [comment]
MrDoob, this is done. Plug in pretty much any code for a working website in VR.

I should not implement something like an "htmlMesh".
This texture can be applied to any mesh, including instancedMesh, skinnedMesh, LOD, etc. Extending base Mesh would be a mistake. 

Devs will want a convenient way to turn raycaster / controller into pointer XY.

I can math write code to intersect a mesh and extract UV coordinates, but where should that code live? Advice needed.

**Comment by mrdoob** [comment]
> I can write math / code to intersect a mesh and extract UV coordinates, but where should that code live? Advice needed.

[Mesh.raycast](https://threejs.org/docs/#api/en/objects/Mesh.raycast) already does that.

**Comment by 0X-JonMichaelGalindo** [comment]
Wow, and way more. Should have read instead of assuming.
I  might keep fiddling with this.
If I can get video and canvas working, I'll rename it html5texture or webtexture or something.
It's beyond my expectations already though.

**Comment by 0X-JonMichaelGalindo** [comment]
Got video and webgl working, isolated JS. Can now run Three.js inside a Three.js texture. :-)
(Plus, reduced overall code size and improved performance.)
I've already gone way too far with this. But, I have one more impossible idea to try...

**Comment by 0X-JonMichaelGalindo** [comment]
Created a real example: a VR UI with some menus and animations (instead of just a spinning cube).

Getting it to run on GitHack was very hackish, because the entire domain is considered insecure (to prevent users from cross-origin-loading other users' content). It works well on localhost and secure domains.

**Comment by 0X-JonMichaelGalindo** [comment]
This is frustratingly broken in subtle use cases. Even in Chrome, there are SVG rendering inconsistencies between tab-SVG vs. inline-SVG vs. canvas-image-source-SVG. The exact same, in-spec, standard CSS will render differently in all three contexts, but only in very rare, impossible-to-debug cases.

I can make it work, but I can't make it robust enough for general use.

**Comment by jbaicoianu** [comment]
Hey all, jumping in late now, I've been hacking away at the HTML-in-VR problem for a few years now, I can't claim I've 100% solved it, but I thought I'd share what I had in case it helps anyone else solve the problem more generally.

I'll give a brief rundown of how it works, it's definitely some duplication of what you've already discussed, but there might be some tricks which could be useful here as well.

### Rendering

https://github.com/jbaicoianu/elation/blob/master/components/elements/scripts/elements.js#L485-L633

Fundamentally this is the SVG foreignObject technique + simulated events mapped via UV coordinates.  In my framework, I implement a base class which extends HTMLElement and adds a `.toCanvas()` function.  It also sets up some MutationObservers to watch for HTML changes, and also watches the page's active stylesheets so it can refresh if any new CSS is loaded.

It works around the tainted canvas problem by fetching all remote resources and turning them into data URIs.  It keeps a cache for each element, so that those resources don't need to be re-fetched every time the element changes.

### Mouse events
While none of the DOM element rendering stuff three.js specific, the mouse events are, so I handle them in a different project.  This part is a lot more experimental, I implemented it for a specific `XRMenuPopup` element, and haven't yet cleaned up some of the ugly hacks I used to make it work, so please excuse the mess!

https://github.com/jbaicoianu/janusweb/blob/f85366633fc4a3c2a942ca4a0a3de38790beae86/media/assets/webui/apps/xrmenu/xrmenu.js#L120-L263

This works by creating the real DOM element and appending it to the page, then hiding it off-screen with CSS.  We then create a shadow DOM attached to this element (important for later!) and append our content to that.  We also inject all of the style sheets our parent document has into the shadow DOM, so we can have consistent styling with the rest of our page.

We then call our `element.toCanvas()` function to get the `<canvas>` object, which we then use as a texture mapped to a plane, which we also set up with a pickable collision mesh (a thin cube, in this case).  We add some event listeners to this 3d object - mousemove, mouseover, mouseout, mousedown, mouseup, click, and wheel.  The engine is already handling all the work of proxying those events from the main renderer's canvas to the individual 3d objects in the scene, so we can use them like we would normal DOM events, but associated with objects in the 3d scene.

Once that's all set up, in our event handler we can now map the UVs to pixels relative to our parent DOM element.  Once we have the pixel coordinates, we use the `shadowdom.elementFromPoint()` function to figure out which sub-element our mouse is over, and then we dispatch a synthetic event on that element. 

```javascript
      let mousexy = [ev.data.uv.x * this.canvas.width, (1 - ev.data.uv.y) * this.canvas.height];
      let EventClass = (ev.type == 'wheel' ? WheelEvent : MouseEvent);
      let fakeev = new EventClass(ev.type, {
        bubbles: true,
        cancelable: true,
        screenX: mousexy[0],
        screenY: mousexy[1],
        clientX: mousexy[0],
        clientY: mousexy[1],
        view: window,
      });

      let target = this.shadowdom.elementFromPoint(mousexy[0], mousexy[1]) || this.element;
      target.dispatchEvent(fakeev);
```

There's also some stuff we have to do with z-index for these elements, if we have multiple virtual DOM elements in the same page the elementFromPoint() function gets confused, so we set their z-index to -1000 by default, and set a positive z-index only on the currently-moused-over 3d object's associated virtual DOM element.

All in all it's a crazy ugly hack, but it works pretty well.  Here are soem shots of it working in 2d - I've used it on the Quest too, and it works well!

image

image

There are a lot of caveats - native browser controls like dropdowns don't work, canvases within your DOM element need special handling, CSS images need special handling, etc...but all in all, this allows us to deliver the same UI controls to VR users as we have in our 2d client.

I'm happy to provide more specific details on any of this, I know it's pretty insanely convoluted, and this implementation is heavily tied to my engine which makes it hard to extract.  Hopefully the tricks I figured out in the process will be useful to someone who's looking to make it more general, though.

**Pull request closed without merging**
