### PR TITLE
You can now define optional parameters for `DataArrayTexture`.

### PR DESCRIPTION
**Pull request by Byloth**
In particular, I was struggling using `DataArrayTexture` with:
- `RedFormat` for `PixelFormat`.
- `FloatType` for `TextureDataType`.

This PR solve this problem.

### CODE REVIEW

**Comment by gkjohnson** [comment]
We should probably do the same thing with `Data3DTexture`. The docs will need to be updated, as well.

This looks like a good change to me but cc @Mugen87 - I'm not sure if there's a reason this hadn't been added, yet.

**Comment by mrdoob** [comment]
I'm not really a fan of optional parameters in constructors.

1. It becomes long and messy when people keep adding things to it.
2. We can't really reorder the parameters so we end up with backwards compatibility code in constructors.

I prefer having only the minimal number of parameters and then modify the object after.

**Comment by mrdoob** [comment]
> In particular, I was struggling using `DataArrayTexture` with:
> 
> * `RedFormat` for `PixelFormat`.
> * `FloatType` for `TextureDataType`.
> 
> This PR solve this problem.

I don't understand how adding default parameters to the constructor solves that issue...

**Comment by Byloth** [comment]
Hi, everyone! 🙃
Thanks for your interest in this PR.

> @gkjohnson  
> We should probably do the same thing with Data3DTexture. The docs will need to be updated, as well.

Uh, right! I missed that!

---

> @mrdoob  
> I don't understand how adding default parameters to the constructor solves that issue...

I would say, just like it works for `DataTexture`:

```ts
new DataTexture(data, width, height, RedFormat, FloatType);
```

---

> @mrdoob  
> I'm not really a fan of optional parameters in constructors.

> @gkjohnson  
> I'm not sure if there's a reason this hadn't been added, yet. I know there had been a move away from large lists of constructor arguments before.

Honestly, I didn't know that...
Actually, it makes sense!

I was simply inspired by the way `DataTexture` works.  
IMHO, `DataTexture` & `DataArrayTexture` (and -sure- also `Data3DTexture`) are closely related and should work as similarly as possible...

So -if you choose to use shorter constructors- it should be be that way for each of these classes.  
But I also understand backwards compatibility issues... 😅

---

Just to point it out...
The alternative implementation for this, without long constructors, would be:

```ts
const dataTexture = new DataArrayTexture(indexes, tX, tY, layers);
dataTexture.format = RedFormat;
dataTexture.type = FloatType;
```

Right? 🙃

**Comment by Mugen87** [comment]
> Right? 🙃

Yes.

In the meanwhile, I'm also convinced that long parameters lists in constructors and methods are not good because of the reasons @mrdoob mentioned in https://github.com/mrdoob/three.js/pull/29856#issuecomment-2469857612. 

> I prefer having only the minimal number of parameters and then modify the instance after creation.

Me too. What we can considering is the usage of an `options` object that holds the optional parameters. Such an object solves the ordering issue, supports default parameters and can be compact on application level (since you only define the parameters which are actually different from the default values).

The PR can be closed in any event though.

**Pull request closed without merging**
