### PR TITLE
Feature/Orientation helper

### PR DESCRIPTION
**Pull request by SntsDev**
**New Orientation Helper (cube with side faces) like most 3D editing programs**

We've all seen that little cube with a ring that is floating in some corner of most of the 3D editing tools. That whenever we rotate the camera will also rotate to tell us which faces we're seeing in the current perspective.

Captura de pantalla 2021-01-28 a las 18 17 42

This feature generates one for your THREE.js project and can be personalized:

- Size & look & feel.
- Faces names & font & colors
- Also works as a navigation helper (click on it to move the camera accordingly)
- ... 

The gizmo can be substituted by any other Mesh using the api:

Captura de pantalla 2021-01-28 a las 18 17 59

I've created an example and the documentation for it too.
It's been developed in `examples/js`, provided  a `d.ts` and modularized.

This contribution is funded by [Tedivo LLC](https://tedivo.com).

### CODE REVIEW

**Comment by gkjohnson** [comment]
For testing:

https://raw.githack.com/SntsDev/three.js/feature/OrientationHelper/examples/misc_controls_orbit_orientation.html

**Comment by NicolasRannou** [comment]
Nice, I did try the navigation helper (double click on a face of the cube I guess), but somehow that doesn't seem to work consistently unless the face is already almost well oriented -

Feb-05-2021 11-57-51

**Comment by SntsDev** [comment]
Thanks @NicolasRannou, I had a bug in the mouse coordinates screen conversion.

**Comment by Mugen87** [comment]
Instead of adding this to `three.js`, it's better to put this in a custom repository and share it as a resource in the [forum](https://discourse.threejs.org/).

We have lately stated to reduce the extend of the repository this year, not further increase it, see https://github.com/mrdoob/three.js/pull/21014#issue-550543213.

So it's actually more likely that things will be removed instead of added.

**Comment by Mugen87** [comment]
Closing. Please share this code as a resource in the forum.

**Comment by Peque** [comment]
@SntsDev Thanks a lot for sharing! And thanks to [Tevido](https://tedivo.com/) too for funding your work.  :blush:

**Pull request closed without merging**
