### PR TITLE
Change HemisphereLight orientation to respect quaternion instead of facing origin

### PR DESCRIPTION
**Pull request by DanielSturk**
Currently, HemisphereLights face the origin, but it would be more intuitive/logical for them to simply be oriented using their quaternion. This is also how practically any other software works (orient lights by rotating them, not moving them).

I'm guessing the reason why they face the origin is because the DirectionalLight and SpotLight face their targets, which is a similar concept, but HemisphereLights don't support targets and environment lighting should not be calculated as such.

In practice, the HemisphereLight.quaternion has had no reason to be changed up until now, so I assume most projects leave theirs' unchanged, allowing for the groundColor and [sky]color to still be oriented correctly after this change.

### CODE REVIEW

**Comment by WestLangley** [comment]
>Currently, HemisphereLights face the origin

Hemisphere lights do not "face the origin". The position property is used to set the axis of each hemisphere. Granted, it would have been better to use the `.up` property for that, instead.

**Comment by Mugen87** [comment]
In any event, the overall idea of the change does make sense to me. It should be irrelevant where you position an instance of `HemisphereLight`. Its direction should be derived from its orientation and thus `quaternion`. 

@DanielSturk Do you mind resolving the merge conflicts? Please do not include build files into the PR.

**Comment by Mugen87** [comment]
Related #14683

**Comment by DanielSturk** [comment]
@Mugen87 conflicts resolved, build files removed

**Comment by WestLangley** [comment]
Sorry, I do not think the proposal here is the correct API. I appreciate the PR, however, because it gives us the chance to revisit this. :-)

First, an aside...

An _ambient light probe_ is not a _source_ of light -- it is a _probe_ of ambient light; it _measures_ the amount of ambient light -- or indirect light -- at a particular location.

A probe aligns with the coordinate axes, maintaining a fixed frame of reference.

A probe is not rotated. It has a position, however.

// 

A three.js `AmbientLight` is is a special case of a `LightProbe` that has a constant value in every direction. It is not rotated. It has a position. (Currently three.js ignores the position, and assumes the level of ambient light is the same at every location.)

We call it a "light", but that is really not what it is. It is not like a "light bulb".

A `HemisphereLight` is also a special case of a `LightProbe`. It has a simple, two-color model for the level of ambient light. It has a position, and it is not rotated.

Since you want to be able to "tilt" the hemisphere light, then was can use the "up" direction for that purpose, or we can add a new property.

Only directional lights should be controlled by their quaternion -- that is, lights for which `lookAt()` makes sense.

I am hopeful that at some point "targets" will be removed from three.js directional lights in favor of quaternion control.

//

Currently, we use the hemisphere light's `position` property for a purpose for which it was not intended. 

Let's not make the same mistake with the `quaternion` property.

/ping @bhouston

**Pull request closed without merging**
