### PR TITLE
#9995: Improved lucy model (PLY) and respective examples

### PR DESCRIPTION
**Pull request by Mugen87**
see #9995

### CODE REVIEW

**Comment by Mugen87** [comment]
@mrdoob Um, i wonder if it's maybe better to change the used model type of the examples `webgl_materials_cubemap_refraction` and `webgl_octree_raycasting` to `PLY`. Then it's not necessary to restore the deleted model file...

**Comment by mrdoob** [comment]
Yes, I was hoping to change it so they use `PLY` instead. But the current `Lucy100k.ply` doesn't match the position/scale of the old `Lucy100k_slim.js` and seems like my computer isn't powerful enough to create a new `Lucy100k.ply`. So I'm stuck. Help?! 😢

**Comment by Mugen87** [comment]
Well, i can try it on my computer. But how should i perform the conversion? With Blender? And where can i find the original source model file?

**Comment by mrdoob** [comment]
Original file: http://graphics.stanford.edu/data/3Dscanrep/lucy.tar.gz
Software to convvert: https://sourceforge.net/projects/meshlab/files/meshlab/MeshLab%20v1.3.3/

Tutorial: https://www.youtube.com/watch?v=PWM6EGVVNQU (Set 100000 as faces target)

It may need to be rotated and center aligned.

**Comment by Mugen87** [comment]
If i perform the `Quadric Edge Collapse Decimation` with 100.000 faces, i get the following output. 

[Lucy100k.ply.zip](https://github.com/mrdoob/three.js/files/609869/Lucy100k.ply.zip)

At first appearance the model looks exactly like the existing `Lucy100k.ply` in `examples/models/ply/binary`. Do i miss anything?

**Comment by mrdoob** [comment]
Yes, that is correct. But if you try to use that file in the relevant examples, you'll need to fiddle with scale and rotation. I'm not sure if `Lucy100k_slim.js` had wrong rotations or if `Lucy100k.ply` needs to be rotated.

**Comment by Mugen87** [comment]
I think i've made it. Like you said, the rotation and alignment of  `Lucy100k.ply`  was somewhat wired. I've fixed this with Meshlab. All examples should work again. 

In `webgl_octree_raycasting` i've deleted the lucy model and increased the amount of boxes instead. `Octree` is based on `Geometry` and can't handle a `BufferGeometry` yet...

**Comment by mrdoob** [comment]
Many thanks!

**Pull request merged**
