### PR TITLE
Editor: Updated `signals.min.js`

### PR DESCRIPTION
**Pull request by linbingquan**
Related issue: #---

**Description**

1. Updated `signals.min.js` lib v1.0.0 version.
2. Improved signals for `Editor.js`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/linbingquan/three.js/dev-signals/editor/index.html

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Tested some workflows and it seems everything works as expected.

**Comment by mrdoob** [comment]
Their [documentation](https://github.com/millermedeiros/js-signals/wiki/Examples) still has this:

```js
var Signal = signals.Signal;
```

**Comment by linbingquan** [comment]
> Their [documentation](https://github.com/millermedeiros/js-signals/wiki/Examples) still has this...
> 
> ```js
> var Signal = signals.Signal;
> ```

Should I not modify `editor.js`.

**Comment by Mugen87** [comment]
Yes, please undo the change to `Editor.js` so the usage of signal corresponds to the documentation.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
