### PR TITLE
Deprecate legacy BufferGeometry nomenclature for built-in geometries

### PR DESCRIPTION
**Pull request by WestLangley**
As proposed in https://github.com/mrdoob/three.js/pull/24349#issuecomment-1185312799.

Does this look like the right approach? If so, I'll add the remaining geometries.

### CODE REVIEW

**Comment by LeviPesin** [comment]
I think the right approach would be to do this in `BoxGeometry.js` instead of `Three.Legacy.js`.

**Comment by Mugen87** [comment]
We only put deprecated methods or properties into non-deprecated classes. Legacy classes should go into `Three.Legacy.js`.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
TBH, I want that @mrdoob merges this PR. I'm not sure about his preferences regarding the geometry generator aliases.

**Comment by WestLangley** [comment]
.

**Comment by WestLangley** [comment]
>TBH, I want that @mrdoob merges this PR... 

@mrdoob What do you think? 😇

**Comment by mrdoob** [comment]
What if we just removed these aliases? 🤔

**Comment by WestLangley** [comment]
>What if we just removed these aliases?

@Mugen87 What do you prefer?

**Comment by Mugen87** [comment]
I've thought the policy was to first deprecated things and then make the removal after 10 releases. I personally would prefer to keep doing this especially in this case since I've frequently see the usage of `BoxBufferGeometry` or `PlaneBufferGeometry` in user code.

**Comment by mrdoob** [comment]
@Mugen87 Sounds good!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
