### PR TITLE
WebGPURenderer: Introduce `NodeMaterialObserver` and updates

### PR DESCRIPTION
**Pull request by sunag**
Related issue: https://github.com/mrdoob/three.js/pull/29077#issuecomment-2275630249, https://github.com/mrdoob/three.js/pull/29299

`NodeMaterialObserver` is responsible for checking if there are any changes in the materials, and if so, moving forward with the process of updating the nodes and bindings at the GPU level.

`NodeMaterialObserver` is an intermediate component between node updates that can be extended or manipulated using `NodeMaterial.setupObserver()`. 

## List

- [x] Added `NodeMaterialObserver`
- [x] Move lights to `renderGroup`
- [x] Move camera to `renderGroup`
- [x] Move fog to `renderGroup`
- [x] Remove Proxies in `updateBeforeNodes`  and `updateAfterNodes`
- [x] TSL Added `Lights.js` 
- [x] RenderObjects: Reuse `chainArray`
- [x] Move `tone mapping exposure` to `renderGroup`

### `webgpu_performance_renderbundle`

| bundle = r168 | bundle += viewMatrices GPU | bundle += node observer |
| ------------- | ------------- | ------------- | 
| 5.67ms | 3.27ms | 0.96ms |
| image | image | image |

| default = r168 | default += viewMatrices GPU | default += node observer |
| ------------- | ------------- | ------------- | 
| 12.10ms | 8.85ms | 6.59ms |
| image | image | image |

### `webgpu_performance`
| Screenshot | Description |
| ------------- | ------------- |
| image | WebGPU ~1026fps - `mesh.static = true` + non-string initial cacheKey in RenderObject - maybe we can some hash algorithm like crc32/64 for comparison in the rendering cycle - not available in this PR |
| image | WebGPU ~870fps - `mesh.static = true` |
| image | WebGPU ~717fps |
| image | * WebGL ~640fps - reference |
| image | WebGPU previous `r168` ~299fps |

### CODE REVIEW

**Comment by cmhhelgeson** [comment]
I'm still trying to familiarize myself with the deeper workings of the API rather than just adding onto it, but is the monitor meant to simply just analyze whether the node material's properties match the data returned by getXData calls, then setting the needsRefresh flag as needed based on the result of that query?

**Comment by sunag** [comment]
@cmhhelgeson Yes, your analysis is correct :)

**Comment by cmhhelgeson** [comment]
If setupMonitor let's us manipulate the monitor's properties, would it make sense to have one of setupMonitor's arguments be a list of properties that are either included or excluded in the needsRefresh call, essentially making those properties static even if the program itself is not? Or would that not really provide any meaningful performance benefits given the small list of properties?

**Comment by sunag** [comment]
The large list will be ignored in the frame cycle, leaving only the properties present in the material, so we wouldn't need to add many functions here.

I think interesting add refreshUniform as a property of the NodeMaterialMonitor, that way users could edit it.

The idea of ​​setupMonitor() is to encourage users to extend the NodeMaterialMonitor class and do their own specific optimization.

**Comment by sunag** [comment]
This is the first time we have improved performance for many normals objects without refraction, as we already had better performance in refraction, now without using special native WebGPU features.

| Screenshot | Description |
| ------------- | ------------- |
| image | WebGPU ~1026ms - `mesh.static = true` + non-string initial cacheKey in RenderObject - maybe we can some hash algorithm like crc32/64 for comparison in the rendering cycle - not available in this PR |
| image | WebGPU ~870ms - `mesh.static = true` |
| image | WebGPU ~717ms |
| image | * WebGL ~640ms - reference point |
| image | WebGPU previous `r168` ~299ms |

**Comment by mrdoob** [comment]
`Monitor` sounds strange to me... `NodeMaterialManager` or `NodeMaterialObserver` may be more fitting?

**Comment by sunag** [comment]
What do you think of `NodeMaterialWatcher`? I'm not sure if it's better than `NodeMaterialObserver`. 

In my head material optimizer would enter the compilation process, shaders, etc. The main objective of the class would be to check data changes and release the update of nodes and bindings.

**Comment by sunag** [comment]
Some others options could be `NodeMaterialUpdater`, `NodeMaterialListener`...

**Comment by cmhhelgeson** [comment]
I think NodeMaterialObserver is good. Updater suggests a class that's performing more robust modifications on the materials.

**Comment by RenaudRohlinger** [comment]
Awesome!!

By the way, @sunag this PR seems to break the WebGL version of `webgpu_performance_renderbundle`.

**Pull request merged**
