### PR TITLE
Webgl BufferGeometry Instance Billboard Example GPU Boost

### PR DESCRIPTION
**Pull request by BrianCraig**
Hi! I ported some parts of the code from Javascript to the shaders, and made it a simpler example.

I personally got a better FPS from 11~ to 45~ in my PC (1600*900 screen, radeon R3 integrated, amd Athlon 5350)

### CODE REVIEW

**Comment by WestLangley** [comment]
Any idea why the colors appear lighter?

**Comment by BrianCraig** [comment]
Hi, i didn't see the colors appearing lighter, i saw red instead of blue/violet.

I fixed the problem, it were on the GLSL HSL to RGB shader. The problem was that HSL(-0.1,1.0,0.5) rendered as HSL(.0,1.0,0.5) and not like HSL(0.9,1.0,0.5)

thats why i added a modulus to the H

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@BrianCraig Thank you for your contribution.

For future reference, and to save you some trouble, you need to fork and target the `dev` branch instead.

Please see the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

**Comment by BrianCraig** [comment]
Thanks @WestLangley , sorry i didn't read that info.

**Pull request merged**
