### PR TITLE
Added docs for WireframeGeometry and EdgesGeometry

### PR DESCRIPTION
**Pull request by looeee**
@mrdoob I guess as these get added to the dev branch it will start to cause conflicts with 
docs/list.js as I'm adding a line or two to it each time I create new docs so that they show up in the menu.

Probably it will be OK to just merge the file, what do you think?

### CODE REVIEW

**Comment by mrdoob** [comment]
> @mrdoob I guess as these get added to the dev branch it will start to cause conflicts with
docs/list.js as I'm adding a line or two to it each time I create new docs so that they show up in the menu.

> Probably it will be OK to just merge the file, what do you think?

The reason I do squash is because the resulting commit is very helpful when writing the change logs every month 😕

**Comment by mrdoob** [comment]
Thanks!

**Comment by looeee** [comment]
Ah OK, well I'm not sure if it's something you're doing or some git magic, but it seems to be working fine so far.

If there ends up being issues I can just fix them manually I guess...

**Comment by mrdoob** [comment]
Yeah, unless you modified the same code in different PRs, things shouldn't have conflicts.

**Comment by looeee** [comment]
Great, good to know!

**Pull request merged**
