### PR TITLE
WebGPURenderer: StorageTexture

### LINKED ISSUE #26749: Computer shaders cannot load textures that they have previously created themselves
### Description

If I write a compute shader that store textures, I can load and use those textures in another compute Shader.
But when I try to pass a texture to a compute shader that I previously created with the same shader, then I get these warnings and it doesn't work:

```
Tint WGSL reader failure: :64:43 error: type mismatch for argument 3 in call to 'computeWGSL', expected 'texture_2d<f32>', got 'texture_storage_2d<rgba8unorm, write>'

  computeWGSL( nodeUniform0, nodeUniform1, nodeUniform0, instanceIndex, 512.0, 0.01, 250.0, f32( true ) );

                                           ^^^^^^^^^^^^
- While validating [ShaderModuleDescriptor "compute"]

- While calling [Device].CreateShaderModule([ShaderModuleDescriptor "compute"]).

[127.0.0.1/:1](http://127.0.0.1/:1) 1 error(s) generated while compiling the shader:

:64:43 error: type mismatch for argument 3 in call to 'computeWGSL', expected 'texture_2d<f32>', got 'texture_storage_2d<rgba8unorm, write>'

  computeWGSL( nodeUniform0, nodeUniform1, nodeUniform0, instanceIndex, 512.0, 0.01, 250.0, f32( true ) );

                                           ^^^^^^^^^^^^
166[Invalid ShaderModule "compute"] is invalid.

- While validating compute stage ([Invalid ShaderModule "compute"], entryPoint: main).

- While calling [Device].CreateComputePipeline([ComputePipelineDescriptor]).

166[Invalid ComputePipeline] is invalid.

- While encoding [ComputePassEncoder].SetPipeline([Invalid ComputePipeline]).

166[Invalid CommandBuffer] is invalid.

- While calling [Queue].Submit([[Invalid CommandBuffer]])

[127.0.0.1/:1](http://127.0.0.1/:1) Tint WGSL reader failure: :64:43 error: type mismatch for argument 3 in call to 'computeWGSL', expected 'texture_2d<f32>', got 'texture_storage_2d<rgba8unorm, write>'

  computeWGSL( nodeUniform0, nodeUniform1, nodeUniform1, instanceIndex, 512.0, 0.01, 250.0, f32( false ) );

                                           ^^^^^^^^^^^^
- While validating [ShaderModuleDescriptor "compute"]

- While calling [Device].CreateShaderModule([ShaderModuleDescriptor "compute"]).

[127.0.0.1/:1](http://127.0.0.1/:1) 1 error(s) generated while compiling the shader:

:64:43 error: type mismatch for argument 3 in call to 'computeWGSL', expected 'texture_2d<f32>', got 'texture_storage_2d<rgba8unorm, write>'

  computeWGSL( nodeUniform0, nodeUniform1, nodeUniform1, instanceIndex, 512.0, 0.01, 250.0, f32( false ) );

                                           ^^^^^^^^^^^^

[127.0.0.1/:1](http://127.0.0.1/:1) WebGPU: too many warnings, no more warnings will be reported to the console for this GPUDevice.
```

### Reproduction steps

1.) Create a compute shader that stores a texture and reads a texture.

2.) In the first run, use an initial texture for the texture input of the compute shader.

3.) In the next run, pass the texture created by the compute shader itself to the texture input of the compute shader.

Unfortunately, in the CodePen example that I created, I only get a white image so far.

Since I can use a texture created by another computer shader, I suspect that it might have something to do with the bindings and locations.

The compute shaders are really great for IFFT (inverse fast Fourier transformations). IFFT requires computer shaders that can load their own previously created textures. Considering that the textureStorage function is brand new in 3js, it runs very satisfactorily.

### Code

```
import * as THREE from "three";
import {texture, textureStore, instanceIndex, MeshBasicNodeMaterial, attribute, uniform, vec2, vec3, vec4, wgslFn } from 'three/nodes';
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import Stats from "three/addons/libs/stats.module.js";
import WebGPURenderer from 'three/addons/renderers/webgpu/WebGPURenderer.js';
import {EffectComposer} from "three/addons/postprocessing/EffectComposer.js";
import {RenderPass} from "three/addons/postprocessing/RenderPass.js";
import {ShaderPass} from "three/addons/postprocessing/ShaderPass.js";


const initialSpectrumWGSL = wgslFn(`

    fn computeWGSL( 
        storageTex: texture_storage_2d<rgba8unorm, write>, 
        index: u32,
        resolution: f32,
        L: f32,
        wind: vec2<f32>
    ) -> void {

        let posX = index % u32(resolution);
        let posY = index / u32(resolution);
        let indexUV = vec2u( posX, posY );
        let uv = vec2f( f32( posX ) / resolution, f32( posY ) / resolution );
                    

        let K: vec2<f32> = (2 * PI * (uv - vec2<f32>(0.5))) / L;
        let k: f32 = length(K);
        let l_wind: f32 = length(wind);
        let Omega: f32 = 0.84;
        let kp: f32 = g * square(Omega/l_wind);
        let c: f32 = omega(k)/k;

        let cp: f32 = omega(kp)/kp;
        let Lpm: f32 = exp(-1.25 * square(kp/k));
        let gamma: f32 = 1.7;
        let sigma: f32 = 0.08 * (1 + 4*pow(Omega, -3));
        let Gamma: f32 = exp(-square(sqrt(k/kp) - 1)/2 * square(sigma));
        let Jp: f32 = pow(gamma, Gamma);
        let Fp: f32 = Lpm * Jp * exp(-Omega/sqrt(10) * (sqrt(k/kp) - 1));
        let alphap: f32 = 0.006*sqrt(Omega);
        let Bl: f32 = 0.5*alphap*cp/c*Fp;
        let z0: f32 = 0.000037 * square(l_wind)/g*pow(l_wind/cp, 0.9);
        let uStar: f32 = 0.41*l_wind/log(10.0/z0);
        let alpham: f32 = alphaM(uStar);
        let Fm: f32 = exp(-0.25*square(k/KM-1.0));
        let Bh: f32 = 0.5*alpham*CM/c*Fm*Lpm;
        let a0: f32 = log(2.0)/4.0;
        let am: f32 = 0.13*uStar/CM;
        let Delta: f32 = tanH(a0+4.0*pow(c/cp, 2.5)+am*pow(CM/c, 2.5));
        let cosPhi: f32 = dot(normalize(wind), normalize(K));
        let S: f32 = (1.0/(2.0*PI))*pow(k,-4.0)*(Bl+Bh)*(1.0+Delta*(2.0*cosPhi*cosPhi-1.0));
        let dk: f32 = 2.0*PI/L;
        let h: f32 = spectrum( S, K, dk );

        textureStore( storageTex, indexUV, vec4f( h, 0, 0, 0 ) );
    }

    const PI: f32 = 3.141592653;
    const g: f32 = 9.81;
    const KM: f32 = 370;
    const CM: f32 = 0.23;
    

    fn square( x: f32 ) -> f32 {
        return x * x;
    }
            
    fn omega( k: f32 ) -> f32 {
        return sqrt(g * k * (1 + square(k / KM)));
    }

    fn tanH( x: f32 ) -> f32 {
        return (1 - exp(-2 * x)) / (1 + exp(-2 * x));
    }

    fn alphaM( uStar: f32 ) -> f32 {
        if(uStar < CM){
            return 0.01 * (1.0+log(uStar/CM));
        }
        else{
            return 0.01 * (1.0+3.0*log(uStar/CM));
        }
    }

    fn spectrum( S: f32, K: vec2<f32>, dk: f32 ) -> f32 {
        if(K.x == 0 && K.y == 0){
            return 0;
        }
        else{
            return sqrt(S/2.0)*dk;
        }
    } 
                
`);


const phaseWGSL = wgslFn(`

    fn computeWGSL( 
        storageTexPing: texture_storage_2d<rgba8unorm, write>,
        storageTexPong: texture_storage_2d<rgba8unorm, write>,
        phase: texture_2d<f32>,
        index: u32, 
        resolution: f32,
        time: f32,
        L: f32,
        pingPhase: f32
    ) -> void {

        let posX = index % u32(resolution);
        let posY = index / u32(resolution);
        let indexUV = vec2u( posX, posY );
        let uv = vec2f( f32( posX ) / resolution, f32( posY ) / resolution );

        
		    let K: vec2<f32> = (2 * PI * (uv - vec2<f32>(0.5))) / L;
        let ph = textureLoad(phase, indexUV, 0).r;
        let dph = omega(length(K)) * time;
        let new_ph = (ph + dph) % (2.0 * PI);
 
        
        if(u32(pingPhase) == 1){
            textureStore(storageTexPong, indexUV, vec4f(new_ph, 0, 0, 0));
        }
        if(u32(pingPhase) == 0){
            textureStore(storageTexPing, indexUV, vec4f(new_ph, 0, 0, 0));
        }

    }


    const PI: f32 = 3.141592653;
    const g: f32 = 9.81;
    const KM: f32 = 370.0;
    

    fn omega(k: f32) -> f32 {
		   return sqrt(g*k*(1.0+k*k/KM*KM));
	  }
         
`);




let scene = new THREE.Scene();
scene.background = new THREE.Color(0x00001f);
let renderer = new WebGPURenderer();
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth,window.innerHeight);
document.body.appendChild(renderer.domElement);
let camera = new THREE.PerspectiveCamera(50.0, window.innerWidth/window.innerHeight, 0.5, 10000);

let composer = new EffectComposer(renderer);
composer.setSize(window.innerWidth,window.innerHeight);
const renderPass = new RenderPass(scene, camera);
composer.addPass(renderPass);

camera.position.set(3, 3, 3);

let controls = new OrbitControls(camera, renderer.domElement);


window.addEventListener("resize", onWindowResize, false);



var changed = true;
var initial = true;
var pingPhase = true;
			
var initialSpectrumMaterial = new MeshBasicNodeMaterial();	
var pingMaterial = new MeshBasicNodeMaterial();
var pongMaterial = new MeshBasicNodeMaterial();



init();
render();

var initialSpectrumParams, initialSpectrumTexture, initialSpectrumCall;
var phaseParams, pingTexture, pongTexture, phaseCall, computePhase;
    

function init() {
  
              			
  initialSpectrumParams = {
    resolution: 512,
    workgroup_size: [8, 8, 1],
    L: 100,
    wind: vec2(10, 10)
  }
	initialSpectrumTexture = new THREE.Texture();
	initialSpectrumTexture.image = {width: initialSpectrumParams.resolution, height: initialSpectrumParams.resolution};
  initialSpectrumTexture.magFilter = initialSpectrumTexture.minFilter = THREE.NearestFilter;

  initialSpectrumCall = initialSpectrumWGSL({ 
    storageTex: textureStore(initialSpectrumTexture), 
    index: instanceIndex,
    resolution: initialSpectrumParams.resolution,
    L: initialSpectrumParams.L,
    wind: initialSpectrumParams.wind,
  });



  phaseParams = {
    resolution: 512,
    workgroup_size: [8, 8, 1],
    time: 0,
    L: 250,
  }
  pingTexture = new THREE.Texture();
  pongTexture = new THREE.Texture();    
  pingTexture.image = {width: phaseParams.resolution, height: phaseParams.resolution};
  pongTexture.image = {width: phaseParams.resolution, height: phaseParams.resolution};
  pingTexture.magFilter = pingTexture.minFilter = THREE.NearestFilter;
  pongTexture.magFilter = pongTexture.minFilter = THREE.NearestFilter;

  phaseCall = phaseWGSL({ 
    storageTexPing: textureStore(pingTexture), 
    storageTexPong: textureStore(pongTexture), 
    index: instanceIndex,
    resolution: phaseParams.resolution,
    phase: null,
    time: phaseParams.time,
    L: phaseParams.L,
    pingPhase: pingPhase
  });
  computePhase = phaseCall.compute(phaseParams.resolution * phaseParams.resolution); 
  
  
  const geometry = new THREE.PlaneGeometry( 1, 1 );
  const plane = new THREE.Mesh( geometry, initialSpectrumMaterial );
  scene.add( plane );
  
  

}


function update() {
  
  if(changed) {
    var computeInitialSpectrum = initialSpectrumCall.compute(initialSpectrumParams.resolution * initialSpectrumParams.resolution);
    renderer.compute(computeInitialSpectrum, initialSpectrumParams.workgroup_size);
    changed = false;
  }  
  
  
  if(initial) {
    computePhase.computeNode.parameters.phase = texture(InitPhaseDataTexture());
		initial = false;
	}
  else{
    //computePhase.computeNode.parameters.phase = pingPhase ? texture(pingTexture) : texture(pongTexture); //here i get strange warnings and it doesn't work

    computePhase.computeNode.parameters.phase = texture(initialSpectrumTexture); //this works (just for test)
  }
  computePhase.computeNode.parameters.time.value = 0.01;
  computePhase.computeNode.parameters.pingPhase.value = pingPhase;
  computePhase = phaseCall.compute(phaseParams.resolution * phaseParams.resolution);
  renderer.compute(computePhase, phaseParams.workgroup_size);
  pingPhase = !pingPhase;
   
  
  
  initialSpectrumMaterial.colorNode = texture(InitPhaseDataTexture());
  
  
}

function render() {
  requestAnimationFrame(render);
  
  update();
  
  renderer.render(scene, camera);
  //composer.render();
}


function onWindowResize() {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
}



function InitPhaseDataTexture(){
  var Res = 512;
	let phaseArray = new Float32Array(Res * Res * 4);
	for (let y = 0; y < Res; y++) {
		for (let x = 0; x < Res; x++) {
			phaseArray[y*Res*4 + x*4] = Math.random() * 2.0 * Math.PI;
			phaseArray[y*Res*4 + x*4+1] = 0.0;
			phaseArray[y*Res*4 + x*4+2] = 0.0;
			phaseArray[y*Res*4 + x*4+3] = 0.0;
		}
	}
	const pingPhaseTexture = new THREE.DataTexture(phaseArray, Res, Res, THREE.RGBAFormat, THREE.FloatType);
			
	pingPhaseTexture.minFilter = THREE.NearestFilter;
	pingPhaseTexture.magFilter = THREE.NearestFilter;
	pingPhaseTexture.wrapS = THREE.ClampToEdgeWrapping;
	pingPhaseTexture.wrapT = THREE.ClampToEdgeWrapping;
	pingPhaseTexture.needsUpdate = true;
			
	return pingPhaseTexture;
}

```

### Live example

https://codepen.io/Spiri0/pen/abPwOoG

### Screenshots

_No response_

### Version

156

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Closes https://github.com/mrdoob/three.js/issues/26749

**Description**

```js
const storageTexture = new StorageTexture( width, height );
```

- [x] [Add `StorageTexture`](https://github.com/mrdoob/three.js/commit/178f7b7f321ee5aa6dd6b8eac846e6d60410bef0)
- [x] [Add `webgpu_compute_texture_pingpong` example](https://github.com/mrdoob/three.js/commit/922025bd93d9907100999994588c0b3af0ab9fe3)

### CODE REVIEW

**Comment by Spiri0** [comment]
Ok, then I'll be patient and wait for r157.

**Comment by sunag** [comment]
@Spiri0 Can this example already help with your project?

**Comment by Spiri0** [comment]
Yes very, this is my topic:

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://tore.tuhh.de/bitstream/11420/1439/1/GPGPU_FFT_Ocean_Simulation.pdf&ved=2ahUKEwj07qP5vbWBAxUx1AIHHdE9AO4QFnoECBgQAQ&usg=AOvVaw0_z-QXC4vcYeIYLsP5WBfM

With r156 I also created the butterfly texture (pages 26 and 40) and the init spectras. This works very well with the node system and wgslFn. For the butterfly texture I only had to write my own bit-reverse fn but these are minor obstacles. The textures look exactly like in the paper. The only thing I was missing was the textureStore functionality before r156. I could have done the pingpong mechanic thing more complicatedly with two separate shaders, but with the pingpong possibility it's cleaner. I have this IFFT ocean since may in WebGL2, but with lots of render targets. But now I want to do all of this with computer shaders. Phil Crowther inspired me to do this because he has been looking for a gpu IFFT ocean for a longer time. Once I've finished it, he can add it as a module in three.js.
Thanks to your comment with the textureNode and the uniforms, I now understand the node system quite well and I like it.

**Comment by mrdoob** [comment]
Is this how `webgpu_compute_texture_pingpong` is supposed to look like?

https://github.com/mrdoob/three.js/assets/97088/a580fe99-1381-4600-aa40-3ef2c1b4cc40

**Comment by Spiri0** [comment]
This looks good. It looks similar to what I have already implemented in WebGL2 with renderTargets. You probably used the noise pattern that I saw in the r157 example, but that's a user matter. The mechanism certainly looks correct. To us it just looks like noise. However, for the Fourier mechanism, these are numerous different wavelengths that evolve over time. The thing with the StorageTexture was a great idea. I wonder if you or sunag are aware that you have essentially made the DataTexture, which generates the textures on the CPU side, superfluous with the StorageTexture. In any case, I only see advantages in the StorageTexture. 
Being able to generate textures on gpu side with the compute shaders is an enormous milestone.

**Comment by mrdoob** [comment]
Improved the example to make it more visually appealing in https://github.com/mrdoob/three.js/commit/d6c8dd0b50a2994c05f94687ed0dfa44ae61ee4c

Screenshot 2023-09-28 at 23 49 19

**Comment by Spiri0** [comment]
The example turned out very well. Not because it happens to be what I need, but because it conveys the node system very well in conjunction with slightly more extensive but not too large WGSL shaders. It also teaches pretty much everything one need to use compute shaders with their full potential for texture generation. In my opinion, the 3 compute examples and the materials example are sufficient to learn nearly everything about the node system. I'm now really looking forward to the weekend to port my IFFT generator with r157 into my WebGPU variant.

**Comment by Spiri0** [comment]
Is writing here still correct to the topic? I don't want to create new issues unnecessarily. The pingpong mechanism works fine. I like the solution with the two compute initializations so that only the respective compute needs to be rendered. I have an idea for an extension of StorageTexture. I'm currently initializing this via an initialization compute. 

```
import {wgslFn} from "../../../src/three-defs.js";

export const InitStorageTextureWGSL = wgslFn(`
   fn mainWGSL(
      writeTex: texture_storage_2d<rgba16float, write>,
      readTex: texture_2d<f32>,
      index: u32,
      size: f32
   ) -> void {
      var posX f32(index) % size;
      var posY f32(index) / size;
      var idx = vec2i(i32(posX), i32(posY));

      var tex textureLoad(readTex, idx, 0);
      textureStore(writeTex, idx, tex);
   }
`);
```

```
import {InitStorageTextureWGSL} from "../resources/shader/IFFT/initStorageTexture.js";

this.computeInitStorageTexture = InitStorageTextureWGSL({
   writeTex: textureStore(this.pingTexture),
   readTex: texture(this.hkt_Texture),
   index: instanceIndex,
   size: params.size
})
```

This is no effort but a method like ".setTexture(customTexture)" to initialize a storageTexture would be handy. A "setTexture()" method would be very practical for initializations in other classes to which textures are passed. But that's nothing urgent.

I have another topic that is really causing me problems and that would probably be something for a new issue. If I pass the iteration steps to a uniform in a for loop, they don't arrive correctly in the shader. I created a post about this in the forum:

https://discourse.threejs.org/t/has-anyone-noticed-any-unusual-behavior-in-the-uniform-node/56657

 and made a CodePen example.

https://codepen.io/Spiri0/pen/QWzZVdZ?editors=0010

I really like the node system. I think you've created something great with it. I don't claim to fully understand it, but the behavior I'm seeing in my uniform is strange. The analog mechanism in webgl2 works as I expect.

**Comment by sunag** [comment]
I don't think we have implement the entire uniform mechanism for WebGPU compute, so it could be a uniform bug in specific to `WebGPURenderer.compute()`, I'll be checking that.

**Comment by Spiri0** [comment]
Seems like I can look forward to r158 then. There don't seem to be many people who are concerned with webgpu and the node system yet. But it's pretty elegant and saves code. It makes things easier. I tell myself that if interest in webgpu increases quickly, all of these points will already anticipate a lot.
I hope my codePen example is helpful and I'm curious to read what your analysis reveals. Mine surprised me and reassured me at the same time.
I can imagine my IFFT system as a module for three.js. This would then be easy to use for all possible frequency images so that users do not have to deal with the demanding IFFT mechanics themselves. I do this because I want a real ocean because for land I use real maps. But I could also easily create much more natural-looking artificial landscapes with my IFFT system than is possible with the usual noise functions.

**Comment by sunag** [comment]
I think the concerned is because the system of nodes and `TSL` is something very new for many, it is not documented and `WebGPURenderer` and `TSL` is a WIP, comparisons usually between `WebGLRenderer` and `WebGPURenderer` are about the strengths of `WebGLRenderer` that have been polished over many years, we are closing several issues per month and I believe it is a matter of time before everything is resolved and we have the best of both worlds, and certainly projects like yours speed up development, makes us think about different needs and solutions and it does all the deep testing work which there was no time to do it.

**Comment by Spiri0** [comment]
I think that might have been the last obstacle in my implementation. The pingpong routine in which I need the uniform for the current iteration step is the last step in the IFFT calculation. The progress in r156 and r157 was already clearly noticeable for me. I think this covers most of the cases that users will ever have to deal with when generating textures with compute shaders. 

Not that I'm conjuring up the devil with my confidence, who will then confront me again with the next bug. But if that's the case, so be it.

**Comment by Spiri0** [comment]
In the forum I see that other people are also interested in the node system and that makes me happy. Since there is still some time until r158, I thought I would take a look at what could possibly cause problems. Instead of THREE.HalfFloatType I tested THREE.FloatType and rgba32float in the shader. rgba16float is enough for me but I just wanted to see if rgba32float also works. That doesn't work and warnings appear in the console that remind me of #26576. But that's more of a luxury problem because with rgba16float I can do a lot of things and everything that I can currently imagine. 
I'm really looking forward to r158.

**Pull request merged**
