### PR TITLE
Examples: Clean up

### PR DESCRIPTION
**Pull request by Mugen87**
see #15387

One point cloud is still based on `Geometry`. I've aligned the others now in a line.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev11/examples/webgl_interactive_raycasting_points.html

**Comment by Mugen87** [comment]
`misc_exporter_gltf` is another one...

**Comment by Mugen87** [comment]
Okay, I think all examples should work now even if `WebGLRenderer` stops rendering `Geometry`.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
