### PR TITLE
Add isClassName pattern property in lot of places

### LINKED ISSUE #14898: FeatureRequest: Is it possible to add isClassName everywhere ?
This is a feature request.

Currently many class in threejs have included an isClassName property to performance reason, mainly in Renderer.

Is it possible to consider this as a global pattern for all threejs class and allow fast type checking ?

### PR DESCRIPTION
**Pull request by Itee**
Add isClassName pattern where it could be required

Fix #14898

### CODE REVIEW

**Review by haroldiedema — APPROVED** [review]
This could work  :)

**Comment by Itee** [comment]
I saw lot of place where this pattern could be used. In majority under example folder. I just waiting merge.

**Comment by mrdoob** [comment]
Can you check how much bigger `three.min.js` gets after this PR? Also curious how the file size increased of gzipped `three.min.js`.

**Comment by Itee** [comment]
Yes i will

**Comment by Itee** [comment]
Before:

three => 1142 Ko (1 169 175 bytes)
three.min => 544 Ko (556 376 bytes)
three.module => 1 103 Ko (1 129 322 bytes)

After:

three => 1166 Ko (1 193 248 bytes) [+24 (+24 073)]
three.min => 544 Ko (556 346 bytes) [0 (-30)]
three.module => 1 127 Ko (1 153 676 bytes) [+24 (+24 354)]

**Pull request closed without merging**
