### PR TITLE
ShapeUtils: Use earcut for polygon triangulation

### PR DESCRIPTION
**Pull request by Mugen87**
Instead of using an own polygon triangulation implementation, the PR introduces the usage of the external library [earcut](https://github.com/mapbox/earcut).  This approach was suggested in #11957.

I had to slightly modify the build configuration so `rollup` is able to resolve and regard the new external dependency.

### CODE REVIEW

**Comment by Mugen87** [comment]
Also removed `webgl_geometry_text_earcut`  since earcut is now default.

**Comment by Mugen87** [comment]
@mrdoob If you are not happy with the `npm` solution, i suggest to create `THREE.Earcut` and port the code of the library. The little drawback of this approach is it will be harder to upgrade the code if the original creators fix a bug in their project. But still we would have a more robust polygon triangulation algorithm in `three.js`. And with nice code style :blush:.

**Comment by agnivade** [comment]
We had to plugin the earcut algorithm manually from outside to achieve this. It would be great if this is the default triangulation algorithm !

**Comment by Mugen87** [comment]
@mrdoob If you are okay with `THREE.Earcut`, i'll will make a new PR with a port of the library. Or with the `npm` solution. Depending on what you prefer.

**Comment by WestLangley** [comment]
This is [worth improving](https://stackoverflow.com/questions/47228915/three-js-extrude-with-holes-issue).

**Pull request closed without merging**
