### PR TITLE
Added n-gon support to OBJLoader2

### PR DESCRIPTION
**Pull request by kaisalmen**
It is working. Performance is not impacted.

### CODE REVIEW

**Comment by kaisalmen** [comment]
@jbaicoianu @jonnenauha @WestLangley n-gon support is now available in (WW)OBJLoader2 as well.
Performance is not impacted on large models.

**Comment by kaisalmen** [comment]
The last update removed the need for extra buffers. There is only one buffer that is always rewritten (and size is only increased by very large n-gon definitions) and a pointer always marks the end. Slashes detection on space is performed even if not in f and l lines, but it has a fast-fail and this removes the need to pass parameters down to deeper functions and then the need for later calculations.
Firefox 55.0.1 loads the 150MB PTV1 model in approx. 3200ms and Chrome Canary 62 takes approx. 4100ms on Windows 10 Core i7-6700.
When the proposed performance measurement tool becomes available, parsing adjustments could be evaluated more easily. All in all these adjustment do not slow the parsing down (also not for samller models).

**Comment by kaisalmen** [comment]
Ok, I thought again about the detection approach and now came up with a less simpler approach that only depends on slash count in relation to buffer length for faces and lines. Save 50 lines of code and needs less calculations + is easier to understand! 😄  Now, I am happy!

**Comment by mrdoob** [comment]
Sweet!

**Pull request merged**
