### PR TITLE
Add MathUtils.pingpong()

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: -

**Description**

One function I find useful is the [pingPong](https://docs.unity3d.com/ScriptReference/Mathf.PingPong.html) function. It alternates between two values, you can use it to alternate between two colors for example.
It also can be combined with the in-out eases from [Robert Penner's Easing Functions](http://robertpenner.com/easing/) to create a differently shaped alternating function.

Here is how the function looks like:
https://www.desmos.com/calculator/vcsjnyz7x4

[image](https://www.desmos.com/calculator/vcsjnyz7x4)

### CODE REVIEW

**Comment by gkjohnson** [comment]
It looks like the current implementation doesn't work with negative numbers:

```js
MathUtils.pingPong( - 1.5 ); // - 1.5
MathUtils.pingPong( - 2.5 ); // - 0.5
```

**Comment by marcofugaro** [comment]
@gkjohnson missed that, thanks for testing. It is fixed by using the `euclideanModulo` instead of the javascript modulo.

I added the correct negative case to the unit test.

**Review by Mugen87 — APPROVED** [review]
The same function also exists in Unity, see

https://docs.unity3d.com/ScriptReference/Mathf.PingPong.html

Reference implementation:

https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Runtime/Export/Math/Mathf.cs#L361-L366

**Comment by marcofugaro** [comment]
Thanks, I was aware, I put the unity link in the description.

From the unity implementation, I renamed `t` to `x` to better match the rest fo the `MathUtils` functions.

**Comment by Mugen87** [comment]
> Thanks, I was aware, I put the unity link in the description.

Sorry, did not realize that^^. I know the method from Unity and I think it's a useful addition to `MathUtils`.

**Comment by mrdoob** [comment]
Maybe `pingpong` instead of `pingPong` in this case? We have `smoothstep` and `smootherstep` ...

**Comment by marcofugaro** [comment]
Sure, it makes sense. Done!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
