### PR TITLE
3MFLoader: Added basic material support.

### PR DESCRIPTION
**Pull request by Mugen87**
The loader is now able to parse material definitions. Added a new example with a more complex `3MF` asset that demonstrates this feature and component parsing.

image

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev29/examples/webgl_loader_3mf_materials.html

**Comment by Mugen87** [comment]
BTW: This is the actual thumbnail of the asset:

image

So the colors of the model are not too bright^^.

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
