### PR TITLE
add lgtm config

### PR DESCRIPTION
**Pull request by gero3**
**Description**

This adds an LGTM config to reduce the number of errors that come from external libraries.

### CODE REVIEW

**Comment by Mugen87** [comment]
According to the [documentation](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file), the file needs to be saved in the root directory of the repository.

I'm not sure we want to further pollute the root directory with config files. On the other side, the current configuration of lgtm.com is problematic since it always scans the entire repo (meaning third-party code) and not just the actual sources.

**Comment by gero3** [comment]
I finally got around to testing this. This is the test => [lgtm.com](https://lgtm.com/projects/g/gero3/threejsWithLGTMconfig/)

**Comment by mrdoob** [comment]
Hmm, lets give this a try... 👍

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
