### PR TITLE
Reinstate SkinnedMesh and Bone types into ObjectLoader

### PR DESCRIPTION
**Pull request by satori99**
As per #9436 , this PR re-instates `SkinnedMesh` and `Bone` types to the `ObjectLoader`.

This won't affect existing code, but will allow for `SkinnedMesh` types that use `BufferGeometry` to be loaded properly using the `ObjectLoader`.

It will also allow for skeletons to simply be defined using `Bone` types in the JSON object graph, rather than only using a bones array attached to `Geometry`.

I think this is another step toward deprecating the `Geometry` type for good.

### CODE REVIEW

**Comment by satori99** [comment]
I have been playing around a bit more with the ObjectLoader, and ended up seeing what it would take to implement a pure BufferGeometry Object Format 4 JSON model with new AnimationClip data all in the same file.

This required implementing loading and animating morphAttribute on BufferGeometry instances.

I have converted the existing knight.js model (which used old- Geometry and old- animation format, even though it is Object Format 4 JSON) into a pure BufferGeometry form ([knight.json](https://raw.githubusercontent.com/satori99/three.js/load-skinnedmesh/examples/models/skinned/knight.json)). 

This file is around 500Kb smaller than the original.

I also modified the existing webgl_animation_skinning_morph.html example to use this new model.

You can see it in action [here](https://rawgit.com/satori99/three.js/load-skinnedmesh/examples/webgl_animation_skinning_morph.html).

Even if this is not a suitable PR, I will leave this here for when this gets implemented for real.

**Comment by mrdoob** [comment]
Have you seen #8978? I'm currently reviewing it.

**Comment by satori99** [comment]
I missed that! looks interesting...
I have been thinking of similar things recently.

My example here implements BufferGeometry morphAttributes loading and animating which would go very nicely with proper Skeleton serialization and loading,

**Comment by satori99** [comment]
Closing, but I'll leave the branch up, so I remember what needs to be done to add morphs to skinned BufferGeometry when the Skeleton serialization is merged.

**Pull request closed without merging**
