### PR TITLE
Light: Convert to ES6 class

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
Related issue: #19986

**Description**

Just the `src/lights/light.js` file changed to es6 class syntax

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
ugh. will start with the edge scripts and come back to this.

**Comment by Mugen87** [comment]
It makes more sense to convert `Light` when all other files are converted. Otherwise things will break.

**Comment by mrdoob** [comment]
LightProbe: https://github.com/mrdoob/three.js/commit/e2ddbc9010aa0e709be4c6cb263aed3deca5f043
AmbientLightProbe: https://github.com/mrdoob/three.js/commit/0ed7a89580acf926b789f08b63293085cfc8bb58

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
DirectionalLightShadow: https://github.com/mrdoob/three.js/commit/bb5cfdefa57826765bc6fff33853f8e37520cf31
PointLightShadow: https://github.com/mrdoob/three.js/commit/b9dd2b636c09ca7e600c28dddb587b4eab340bf6
SpotLightShadow: https://github.com/mrdoob/three.js/commit/31545b9d564ae5b30b6766f6b0ba4b28f5e5779d
LightShadow: https://github.com/mrdoob/three.js/commit/4eb500d5f536a02a50229e814f87236482cd5d1f

**Comment by DefinitelyMaybe** [comment]
> It makes more sense to convert `Light` when all other lights are converted. Otherwise things will break.

Don't mind me. that was simply the conclusion I came to upon posting the PR ... *sigh*

**Pull request merged**
