### PR TITLE
Nodes: Add `SSAAPassNode`.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This ports `SSAARenderPass` to `WebGPURenderer`. 

`SSAAPassNode` does not yet support MRT since I'm not sure how to proceed. 

I guess it's expected to supersample not just beauty but all other attachments as well. However, I'm not sure how to do the accumulation for additional outputs and the depth. The accumulation itself is just a simple copy with an additively blended material (see code in `setup()`). But I did not figure out so far how to apply it to a MRT configuration.

We need this bit at a later point for TRAA as well so it would be beneficial to already find a solution for `SSAAPassNode`.

### CODE REVIEW

**Comment by sunag** [comment]
> SSAAPassNode does not yet support MRT since I'm not sure how to proceed.

I added some commits that should bring support. AutoMRT will not work on `.fragmentNode`, in these cases the user will have to use `.fragmentNode = mrt( .. )` manually. I cloned `RenderTarget` this should help when user gets new textures using `pass.getTexture()`.

> We need this bit at a later point for TRAA

Yes, rendering the same scene multiple times in a single frame seems really expensive...

**Comment by Mugen87** [comment]
I've tried to replace `pass` with `ssaaPass` in `webgpu_postprocessing_ao` but only the beauty output is correct. Normal and depth appears to be empty. The code looks like so:
```js
const scenePass = ssaaPass( scene, camera );
scenePass.setMRT( mrt( {
	output: output,
	normal: transformedNormalView
} ) );

scenePassColor = scenePass.getTextureNode( 'output' );
const scenePassNormal = scenePass.getTextureNode( 'normal' );
const scenePassDepth = scenePass.getTextureNode( 'depth' );

postProcessing.outputNode = scenePassColor; // scenePassNormal and scenePassDepth does not work yet
```
I think we can expect this usage from SSAA/TRAA at a later point. Meaning if users want this type of anti-aliasing, they replace `pass()` with an alternative.

**Comment by Mugen87** [comment]
Side note: I always find it great when engines or games offer SSAA as an option. In games, you normally can't use this type of anti-aliasing during the release. But after some years of hardware progression it's nice if you can enable SSAA when you revisit a game. In this way you have superior anit-aliasing but without the temporal artifacts known from TRAA.

**Comment by sunag** [comment]
Thanks for the tests with normals, replacing the MRT was necessary, otherwise it would get the normal information from QuadMesh, apparently it is working.

image

**Comment by sunag** [comment]
I added `depth`, it is possible to gain performance by allocating it outside the jitterOffsets loop, or using the depth of the sampleRenderTarget, it could be a possibility

image

**Comment by Mugen87** [comment]
Regarding the depth: Is it already possible with the node material to write to `frag_depth ` and `gl_FragDepth`? I guess we could that use to produce a supersampled depth value.

**Comment by sunag** [comment]
We would have to implement it for MRT as well but I assume it won't work without an update, another possibility would be to store the depth in a third MRT texture.

**Comment by sunag** [comment]
> Edit: It seems it won't work since the blend does not honor the depth buffer...

Maybe we can leave this for later, I think the priority is related to the beauty output and allow other MRT outputs, we already have great progress here.

**Comment by Mugen87** [comment]
Agreed!

**Pull request merged**
