### PR TITLE
Addons: Improve JSDocs

### PR DESCRIPTION
**Pull request by s-rigaud**
**Description**

Add missing parameter types to decrease eslint warnings. From `33` to `4`.

### CODE REVIEW

**Comment by donmccurdy** [comment]
I'm fine with the changes, but, are we doing anything with JSDoc in these folders? Would we prefer to limit ESLint to the folders where JSDoc is run?

**Comment by Mugen87** [comment]
Yes, I think we should only concern about JSDoc in the nodes folder for now.

**Comment by s-rigaud** [comment]
As `eqeqeq` eslint rule has been deactivated from the whole project because it was causing too many warnings in the `addons` folder while running the lint command, I think it might be great to keep the `valid-jsdoc` rule. The only issue with this rule is that currently some documentation in addons are treated as invalid JSdoc and so 30 warnings have been added in the linting command output. With this PR I just tried to remove all these warnings polluting the output, no addition to previous doc is wanted simply reducing the current doc treated by default as JSdoc due to the syntax 🤔

**Comment by Mugen87** [comment]
Okay, let's merge but let's also focus on `src/nodes` for now.

**Pull request merged**
