### PR TITLE
Honor matrixAutoUpdate flag in serialization

### LINKED ISSUE #13828: Support Skew in Editor
This is a feature request.

1. When importing skewed objects in the Editor, their matrix gets orthogonalized and the skew disappears. It would be nice to be at least able to visualize skewed objects in the editor.
2. There also are no tools to manually skew objects in the editor. It would be nice to be able to manually edit the skew in the editor

Looking forward to this, thank you !

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #13828

### CODE REVIEW

**Comment by WestLangley** [comment]
Maybe there are other places where this needs to be addressed... Not sure...

**Comment by mrdoob** [comment]
Thanks!

**Comment by crubier** [comment]
Thanks !

**Comment by WestLangley** [comment]
@Mugen87 Do you have a feeling for what additional changes need to be made to honor `matrixAutoUpdate` on export/import?

**Comment by Mugen87** [comment]
Since you've already changed `ObjectLoader` and `Object3D`, there should be no more work to do.

**Comment by WestLangley** [comment]
@Mugen87 Good. Thanks.

**Pull request merged**
