### PR TITLE
PBS (physically based shader) 

### PR DESCRIPTION
**Pull request by wolfmanfx**
PBS (physically based shader) whiche has the same visual output as in Ogre3d
Somethings are not finished due the shader was created with r69 and today I made a upgrade to the latest three.js.

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, are you aware that in `dev` we have a physically based material already?

https://rawgit.com/mrdoob/three.js/dev/examples/index.html#webgl_materials_variations_standard
https://rawgit.com/mrdoob/three.js/dev/examples/index.html#webgl_materials_variations_standard2

**Comment by wolfmanfx** [comment]
Hi,

This shader were created to have the same visual output as the PBS shader we use in Ogre.
Furthermore we support 2 detail maps (which can be blended via blendfunctions) also we support anisotrophic rendering.

here is an example https://coderabbit.at/arnest/#/projectViewer2?id=9ba5cfce-eb71-430e-adde-ebff344238ba 

TBH the shader were written over a year ago :) so I did not saw the PBS impl.

**Comment by mrdoob** [comment]
Oh oh! I see I see...

How about moving it to examples folder by now? Just to not confuse people with two different PB materials.

I wonder if it could be possible to refactor into something like this:

```
examples/webgl_materials_variations_ogre3d.html
examples/js/materials/Ogre3DMaterial.js // outputs ShaderMaterial, self includes shaders
```

**Comment by wolfmanfx** [comment]
Could be done but moving the material? That would mean I have to move out all code from webGL renderer (which does the uniform update).
Also I added the extension for seamless cubemaps (does the current PBS impl allow cubemaps at all because without that ext it do not make much sense)

**Comment by mrdoob** [comment]
> Could be done but moving the material? That would mean I have to move out all code from webGL renderer (which does the uniform update).

Yes, ideally the renderer shouldn't have to know anything about the material.

> Also I added the extension for seamless cubemaps (does the current PBS impl allow cubemaps at all because without that ext it do not make much sense)

I noticed! I think we were trying to not rely on that extension. I have to take a closer look.

**Comment by mrdoob** [comment]
>> Also I added the extension for seamless cubemaps (does the current PBS impl allow cubemaps at all because without that ext it do not make much sense)

> I noticed! I think we were trying to not rely on that extension. I have to take a closer look.

Now I remember. We load it when needed:
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js#L436

**Comment by bhouston** [comment]
> Also I added the extension for seamless cubemaps (does the current PBS impl allow cubemaps at all because without that ext it do not make much sense)

As far as I know, there is no extension that guarantees seamless cubemaps in WebGL 1.x.  There is a bug in ANGLE (which implements WebGL in Chrome and FireFox on Windows) that makes cubemaps erroneously seamless.  For more details see this discussion here:

https://code.google.com/p/chromium/issues/detail?id=479753

**Comment by wolfmanfx** [comment]
Did you had a chance to review the shader?

**Comment by mrdoob** [comment]
Yes but, unfortunately, my previous comment still stands. We should find a way to move this out of `/src`...

**Comment by Mugen87** [comment]
Closing, since this PR must not affect `src` code.

**Pull request closed without merging**
