### PR TITLE
Camera: Refactor camera view offset function

### PR DESCRIPTION
**Pull request by webglzhang**
**Description**

I was confused when I first use viewoffst function. I just want to change the left ,right, bottom  and top of the projection parmas for change the position of the near plane.

On the whole, this function feels a little customized. I’m trying to make this function more flexible.

In my opinion, viewOffset should make effect of projection matrix directly and simply.  

This is my basic design. Viewoffset only includes left, right, top and bottom in projection. I think this parameter design is closer to the essence of projection near plane and is universal.

The final projection parameters of the camera are offset directly based on viewoffset. How to reasonably set the viewoffset should be decided by the user.

And	I make a darft pull request to show my design, which only support perspective camera at present.

### CODE REVIEW

**Comment by webglzhang** [comment]
I haven't done any other demo adaptation yet, so the puppeter failed. If this idea works, I will do adaptation work.

**Comment by webglzhang** [comment]
All the adaptation work for new view offset has been done.

**Comment by mrdoob** [comment]
@greggman What do you think?

**Comment by greggman** [comment]
I don't really have an opinion on the design itself. I do have a opinions that I find it sad that this will break any page that uses `setViewOffset`

Note that the function is not just used for windows. Example: https://stackoverflow.com/a/27586987/128511

The code itself I have comments on

```
const newObj = Object.assign({}, stuff, otherStuff);
```

could be written

```
const newObj = {...stuff, ...otherStuff};
```

That second form is idiomatic JavaScript in 2022 and you'll find in the example of the docs for React, Redux, Svelte, etc... as well as the three.js manual

Also this code

```
const skew = this.filmOffset;
if ( skew !== 0 ) left += near * skew / this.getFilmWidth();
```

What is the point of checking for `!== 0`? Why not just

```
const skew = this.filmOffset;
left += near * skew / this.getFilmWidth();
```

or even just

```
left += near * this.filmOffset / this.getFilmWidth();
```

**Comment by greggman** [comment]
I don't really have an opinion on the design itself. I do have a opinions that I find it sad that this will break any page that uses `setViewOffset`

Note that the function is not just used for windows. Example: https://stackoverflow.com/a/27586987/128511

The code itself I have comments on

```
const newObj = Object.assign({}, stuff, otherStuff);
```

could be written

```
const newObj = {...stuff, ...otherStuff};
```

That second form is idiomatic JavaScript in 2022 and you'll find in the example of the docs for React, Redux, Svelte, etc... as well as the three.js manual

Also this code

```
const skew = this.filmOffset;
if ( skew !== 0 ) left += near * skew / this.getFilmWidth();
```

What is the point of checking for `!== 0`? Why not just

```
const skew = this.filmOffset;
left += near * skew / this.getFilmWidth();
```

or even just

```
left += near * this.filmOffset / this.getFilmWidth();
```

**Comment by webglzhang** [comment]
@greggman Thank you for your advice.  I will try to solve the destructive code implementation and code writing.

For the problem of code destructive implementation, I will solve it as follows:

1. The camera provides the function of setProjectionOffset, which can directly modify the right, left, top and bottom parameters of the projection.

2. Retain the setViewoffset function of the camera, and change the projection parameters internally through the setProjectionOffset function.

**Comment by webglzhang** [comment]
I'm sorry. I haven't figured out how to provide a way to directly modify the projection parameters without  breaking any page that uses setViewOffset. I will close this PR first, and then open when I find a good way to implement it.

**Pull request closed without merging**
