### PR TITLE
Fix #11683 using pixelRatio on viewport and scissors

### PR DESCRIPTION
**Pull request by fernandojsg**
Just fixed the issue (https://github.com/mrdoob/three.js/pull/11683) that was broken the array_camera example (It just missed the pixelRatio).
I've also added the example with arraycamera and normal camera provided by @takahirox

### CODE REVIEW

**Comment by mrdoob** [comment]
I think this will break even more things. This code is delicate, sorry 😕

**Comment by mrdoob** [comment]
I'll merge and try to fix on my end.

**Comment by mrdoob** [comment]
Thanks!

**Comment by fernandojsg** [comment]
Ops sorry I didn't pay attention to side effects as I thought it was just a simple mistake 👼

**Comment by mrdoob** [comment]
Should be ok now. Albeit `webvr_sandbox` is still broken. Will work on it tomorrow.

**Comment by mrdoob** [comment]
Never mind. `webvr_sandbox` is still broken. Will work on it tomorrow.

**Comment by takahirox** [comment]
Hm, perhaps `Mirror.js` has been broken in VR mode?

**Comment by mrdoob** [comment]
Yeah, these changes broke `Mirror.js` in VR but I think it's `Mirror.js` code fault. Working on it.

**Comment by fernandojsg** [comment]
That's why we need automated testing! :angel:

**Pull request merged**
