### PR TITLE
WebGPURenderer: Add support for VSM.

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: -

**Description**

This PR adds support for Variance Shadow Maps (VSM) to `WebGPURenderer`.

This is WIP though since the current code only supports one shadow casting light. I'm not sure why the shadows of an additional shadow casting light are currently ignored. The new example illustrates this issue. You only see the shadow of the spot light but no the directional light.

Some help/support in this context would be welcome 😇 .

Side note: VSM works by preprocessing the actual shadow map with two blur passes. The render target of the second blur pass is then used as the new shadow map in the shader. The shadow information are not stored as floats in a depth texture but in special two-component `distribution` vectors. A smart calculation based on these data leads to the final occlusion value.

### CODE REVIEW

**Comment by sunag** [comment]
The problem was in NodeFrame which was not restoring the scene from the previous render in the call tree, I still have to see the best solution, but I already feel relieved since it was kind of difficult to find the problem :)

image

**Comment by sunag** [comment]
I have to improve `filterNode` to support VSM,  I think that after we merge this PR.

**Comment by sunag** [comment]
It looks like we have another issue in `WebGPUBackend`.

**Comment by Mugen87** [comment]
The behavior seems odd. You can see the directional light but not its shadows. The spot light is completely missing in the scene (light + shadow).

**Comment by Mugen87** [comment]
I stall the PR for the moment since I could not figure out the root cause so far. Hopefully the issue will pop up in a different, more isolated context.

**Comment by sunag** [comment]
This PR https://github.com/mrdoob/three.js/pull/29326 should fix it, sorry the delay, I had to deconstruct the code step by step to find the source of the problem.

**Comment by Mugen87** [comment]
Awesome, it really works!

**Pull request merged**
