### PR TITLE
Textured lighting as a spotLight.map property

### PR DESCRIPTION
**Pull request by mbredif**
This PR is a second attempt at #13057, by adding a ~~`colorMap`~~ `map` property to the `SpotLight` class :

image

http://localhost:8000/examples/webgl_shadowmap_viewer.html

This PR generalizes the single-channel [cookie](https://docs.unity3d.com/Manual/Cookies.html) concept  to a 4-channel texture : the `directLight.color` of the spot light is `mix`ed with the rgb value of the `colorMap` lookup with a ratio corresponding to its alpha value : ``` mix( directLight.color, spotColor.rgb, spotColor.a ) ```. The cookie effect is reproduced using pixel values `(0,0,0,1-cookie_value)`.

Comments :
- ~~with this PR, each spotLight takes an extra texture slot (similar to https://github.com/mrdoob/three.js/pull/13057#issuecomment-359135200). Is it an issue ? any idea ?~~ (the second commit 8d683b8 addresses this issue.)
- it is not currently possible to control the geometry of the spotlight to match a known PerspectiveCamera (the `spotShadowMatrix` is used for texture lookup). This will be tackled in a follow-up PR if this one gets merged.

### CODE REVIEW

**Comment by looeee** [comment]
[Live example](https://rawgit.com/mbredif/three.js/41f1a55998ee717b5957621cdd42d2fe961c0faa/examples/webgl_shadowmap_viewer.html)

**Review by haroldiedema — CHANGES_REQUESTED** [review]
Build files should not be part of the PR.

**Comment by mbredif** [comment]
good to know !
Rebased on three.js/dev without the `build` files.

**Comment by mbredif** [comment]
(Rebased on dev after shadowmap/fog was fixed by #14617)

The second commit ( 8d683b8 ) adds : 
- [documentation](https://rawgit.com/mbredif/three.js/2b1d5e6f27d34f98b5dc250b06905cb77e2c103d/docs/#api/lights/SpotLight), including an extended doc [example](https://rawgit.com/mbredif/three.js/2b1d5e6f27d34f98b5dc250b06905cb77e2c103d/examples/webgl_lights_spotlight.html) (including a video texture) with switchable textures/video. When no texture is selected, no extra texture slot is used.
- [examples/webgl_shadowmap_viewer](https://rawgit.com/mbredif/three.js/2b1d5e6f27d34f98b5dc250b06905cb77e2c103d/examples/webgl_shadowmap_viewer.html) is still working, but takes one less texture slot (as one of the two spotlights has no `map`)
- `SpotLight.colorMap` is renamed to [`SpotLight.map`](https://rawgit.com/mbredif/three.js/2b1d5e6f27d34f98b5dc250b06905cb77e2c103d/docs/#api/lights/SpotLight.map) for simplicity, but I can change it back if requested.

This PR is now ready for review.

**Comment by mbredif** [comment]
@mrdoob @WestLangley , any feedback on this long awaited feature ?

**Comment by WestLangley** [comment]
I definitely support this feature.

I am sure working, live links would be helpful to @mrdoob.

**Comment by mbredif** [comment]
> I am sure working, live links would be helpful to @mrdoob.

sure !
* [SpotLight doc](https://rawgit.com/mbredif/three.js/demo_spotColorMap/docs/api/lights/SpotLight.html) that introduces the new `map` property.
* [webgl_lights_spotlight example](https://rawgit.com/mbredif/three.js/demo_spotColorMap/examples/webgl_lights_spotlight.html) : you can select different project textures using the `map` dropdown list (defaults to 'none')
* [webgl_shadowmap_viewer example](https://rawgit.com/mbredif/three.js/demo_spotColorMap/examples/webgl_shadowmap_viewer.html) : the spotlight projects the (much too faded!) uv-debuging texture.

**Comment by danielgranat** [comment]
@mbredif  I think this can be a great addition to the Threejs. At my company, we are trying to use this branch, and being a noob with shaders, how would you handle rotation of the texture (maybe use [Texture.rotation](https://threejs.org/docs/#api/en/textures/Texture.rotation)?
Is it possible to change the alpha so the image isn't transparent?

**Comment by mbredif** [comment]
`Texture.matrix` and its defining parameters (such as `Texture.rotation`) is not yet supported in this PR.
I see 2 solutions : 
- either you rotate the camera in 3D around its optical axis to fake the texture rotation, or 
- you add support for the `Texture.matrix` by setting up a `mat3` uniform and applying it in the shader in this loop : https://github.com/mrdoob/three.js/blob/b6b8ce29fa64941975e3a0fc900fbe888aae2fb4/src/renderers/shaders/ShaderChunk/lights_fragment_begin.glsl#L53, the application should be similar to : https://github.com/mrdoob/three.js/blob/2ad018c7c7ad103c9da9d7f22b3154537384ab26/src/renderers/shaders/ShaderChunk/uv_vertex.glsl.js#L4, ) 

Please file a PR against mine if you go for the second option ! :)

**Comment by danielgranat** [comment]
Thank you! I will try the second option.

**Comment by WestLangley** [comment]
This was an excellent contribution by @mbredif, IMO.

I am disappointed it has not received the attention it deserves.

**Comment by marcofugaro** [comment]
So sad this was never implemented, would have been awesome

**Comment by mbredif** [comment]
Let me correct : textured spotlights ARE implemented in this PR. However it has not been merged yet...
I do not know what s blocking it though.

**Comment by Mugen87** [comment]
Sorry, this PR has lacked of attention in the last month. I would also like to see this PR merged!

However, I would only put effort in resolving the merge conflicts if @mrdoob is fine with this. Maybe he wants to head in another direction in context of textured lighting. 

BTW: I think one spotlight example is sufficient to demonstrate this new feature. Hence, I would undo the changes to `webgl_shadowmap_viewer`. There is also one issue in `webgl_lights_spotlight example`. If I change the video texture and then switch to a different one, the video is still playing in the background.

**Comment by dlawrence2060** [comment]
Any idea if this will get merged soon?

**Comment by mbredif** [comment]
Not my call unfortunately... I can update the PR if I get a green light that this is very likely to be merged by a maintainer @mrdoob @WestLangley @Mugen87

**Comment by WestLangley** [comment]
@mbredif At this point, you should get buy-in from @mrdoob before investing your time.

@mrdoob Will you please render a decision?

**Comment by carstenschwede** [comment]
@mbredif Not sure if having a milestone assigned can be considered "likely to be merged", but I would love to see this PR updated to current dev. Really nice work!

**Comment by mbredif** [comment]
@mrdoob I did not see you attached a milestone. Is it a green light that says that a rebase is likely to be merged ?

**Comment by mrdoob** [comment]
Sorry for the... 2 years late review... 🙁

I think the `(This PR is the geometric counterpart of #14621)` comment in #14658 made me think that the PRs were entangled and I never knew which one to start reading first 🙃

Looks good to me! Any chance you can resolve the conflicts?

**Comment by trbll** [comment]
Did this not get added in r120 as planned? Looks great and am really looking forward to having this support built in. Thanks!

**Comment by carstenschwede** [comment]
Friendly pinging @mbredif cause I am not sure he receives notifications.

**Comment by mrdoob** [comment]
@trbll The PR has conflicts...

**Comment by trbll** [comment]
> @trbll The PR has conflicts...

@mrdoob Yeah, I see that now. Thank you and sorry about that. Just got going too fast in anticipation after I saw r120 had dropped. Appreciate all that you do!

**Comment by mbredif** [comment]
Sorry for the delay, I started rebasing this very old PR but it had a lot of conflicts due to the reformating of the glsl code. I was too busy to polish it but I am quite there.

**Comment by mbredif** [comment]
I got it working again : https://github.com/mrdoob/three.js/compare/dev...mbredif:spotLightMap2
Should I file a new PR ?

**Comment by mrdoob** [comment]
Whatever is easier for you 👍

**Comment by mbredif** [comment]
rebased version of this PR is available at #20290

**Pull request closed without merging**
