### PR TITLE
FBXLoader: use THREE.Math.degToRad

### PR DESCRIPTION
**Pull request by looeee**
...instead of the degreeToRadian function defined in the loader.

Also fixed some formatting that got messed up along the way somewhere.

### CODE REVIEW

**Comment by mrdoob** [comment]
Opss. Conflicts...

**Comment by looeee** [comment]
Great! 😆

**Comment by looeee** [comment]
OK, this one is good. I'll let you merge it before fixing the rest so that I can sync the formatting.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
