### PR TITLE
LUT: Fix color definition and sampling.

### LINKED ISSUE #23549: Lookup Table's Lut.getColor() should use Math.floor instead of Math.round
**Describe the bug**

In Lut.getColor(), once the input value is converted into an alpha between 0 and 1, alpha is multiplied by the number of colors to assign it an index, and then rounded to the **nearest integer** using `Math.round`.

I think this might be wrong, as alpha should be rounded to the **nearest integer below**, using `Math.floor`.

Otherwise, values that fall under a color **i** but are closer to its border with the color **i+1** will eventually be assigned the color **i+1**.

Here is the referred line in the source code:

https://github.com/mrdoob/three.js/blob/cd4f4e7fac6faeaf79bc53fcc64ccc3e88aaa872/examples/jsm/math/Lut.js#L108

**To Reproduce**

See code snippet below.

***Code***

```js
import { Lut, ColorMapKeywords } from 'three/examples/jsm/math/Lut';

const colormap = ColorMapKeywords.rainbow;
const lut = Lut( colormap, 6 );
    
lut.setMax( 100.0 );
lut.setMin( 0.0 );
    
// This value gets a correct color
// alpha = 0.7
// alpha * nrColors = 4.2
// getColor picks this.lut[4]
const a = 70;
const colorA = lut.getColor( a );

// This value gets a wrong color
// alpha = 0.6
// alpha * nrColors = 3.6
// getColor picks this.lut[4] instead of this.lut[3]
const b = 60;
const colorB = lut.getColor( b );
```

**Screenshots**

Maybe this schematic helps to illustrate my point:

imagen

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: r137

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #23549.

**Description**

Fixes `getColor()` and `setColorMap()`. Improves `updateCanvas()`.

@dcriado @scurest Does this look better to you?

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev63/examples/webgl_geometry_colors_lookuptable.html

**Comment by scurest** [comment]
No, sorry. Maybe I wasn't clear, but rounding is the right thing to do. Here's an example:

Let's add a keyword `'blacktowhite': [[ 0.0, 0x000000 ], [ 1.0, 0xFFFFFF ]]`. This is easy to understand since sampling at alpha ideally produces r=g=b=alpha.

With this PR's Lut:

```js
>>> const l = new Lut("blacktowhite", 4);

// this returns lut[1] (0.25), it should return lut[2] (0.5)
// since 0.48 is closer to 0.5 than 0.25
>>> l.getColor(0.48)
Object { r: 0.25, g: 0.25, b: 0.25 }

// behavior for alpha near 1
>>> l.getColor(0.999)
Object { r: 0.75, g: 0.75, b: 0.75 }  // bad
>>> l.getColor(1)
Object { r: 1, g: 1, b: 1 }  // good!
```

With dev's Lut:

```js
// this is correct
>>> l.getColor(0.48)
Object { r: 0.5, g: 0.5, b: 0.5 }

// the only "problem" is for alpha near 1 the color at
// the very end of the ramp doesn't get returned
// (essentially the lut[n] bucket is missing/unused)
>>> l.getColor(0.999)
Object { r: 0.75, g: 0.75, b: 0.75 }
>>> l.getColor(1)
Object { r: 0.75, g: 0.75, b: 0.75 }

// contrast with alpha near 0, where the color at
// the beginning DOES get returned
>>> l.getColor(0.001)
Object { r: 0, g: 0, b: 0 }
```

**Comment by scurest** [comment]
Cool, getColor looks right to me.

For setColorMap:

The loop doesn't always make n+1 elements in lut. For n=11 for example, i ends up being > 1 at the end of the loop, so there is no lut[11] and getColor(1) returns undefined.

IMO it would be easier to do something like this

```js
let j = 0;

for (i = 0; i !== n+1; i++) {  // use integer loop counter
    const alpha = i * step;

    // advance j until alpha is in the right range
    ...

    const color = lerp(...)

    // every iteration unconditionally pushes one element
    this.lut.push(color)
}
```

**Comment by scurest** [comment]
Well now that I think about it, of those two ways, only the first one makes sense for updateCanvas since pixels are equal-sized.

I don't really understand the canvas code. It uses this.n for the height? Is the purpose to visualize the contents of this.lut? But then why does it do its own lerping loop instead of reading this.lut?

**Comment by Mugen87** [comment]
Slightly your code listing but the result should be okay now.

**Comment by scurest** [comment]
Okay. As far as I can tell, it's right now.

**Comment by mrdoob** [comment]
Thanks!

**Comment by dcriado** [comment]
Sorry guys, I could not have a look at this until now. It really looks good now!

**Pull request merged**
