### PR TITLE
Unify setting postprocessing pass size

### PR DESCRIPTION
**Pull request by Oletus**
The size is now set the same way in EffectComposer.addPass() and EffectComposer.setSize().

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
Be careful, everybody!

This PR should have been applied to the JS file. `modularize.js` now reverts this PR.

**Comment by Oletus** [comment]
Sorry, I should have checked my assumptions about how to contribute changes to the modularized code. I now realize that files in both js/ and jsm/ should be changed in patches like this.

There's a new PR that fixes the file in js/ : https://github.com/mrdoob/three.js/pull/17043

**Comment by Mugen87** [comment]
We really need to get #16920 in place^^

**Pull request merged**
