### PR TITLE
PCSS

### PR DESCRIPTION
**Pull request by spidersharma03**
PCSS with support for spot and directional lights.

### CODE REVIEW

**Comment by bhouston** [comment]
Interactive example here:

http://ci.threejs.org/api/pullrequests/9620/examples/webgl_shadowmap_pcss.html

**Comment by mrdoob** [comment]
Hmm, there seems to be conflicts in this PR.

**Comment by reality3d** [comment]
@spidersharma03 Nice. Check the typo of the sample's title (Precent Closer Soft-Shadows)

**Comment by mrdoob** [comment]
Sorry for breaking this again. Do you mind pulling from `dev`?

**Comment by titansoftime** [comment]
The live example does not load for me. Does this shadow system maintain the lighting from normal maps? The current one does not and is driving me crazy trying to workaround.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/8933#issuecomment-322637807

**Pull request closed without merging**
