### PR TITLE
Line2 Example: Remove copy function overrides

### PR DESCRIPTION
**Pull request by gkjohnson**
I'm planning to finish out some of the example Line2 implementation and eventually add a proper raycast function to the object, as well.

This PR starts by removing some unnecessary no op copy function overrides so that the copy implementation behaves like other `Mesh` sub classes. I couldn't see any reason why the line object implementations should need a special handling for copy but please correct me if I'm wrong!

~It also adds support for some missing fields to the `LineMaterial` copy function.~

@WestLangley

### CODE REVIEW

**Comment by WestLangley** [comment]
Yay!

>I couldn't see any reason why the line object implementations should need a special handling for copy but please correct me if I'm wrong!

TBH, I don't remember...

>It also adds support for some missing fields to the LineMaterial copy function.

I am not sure why the defined properties should be included in the copy() method.

/ping @Mugen87  ?

**Comment by gkjohnson** [comment]
> I am not sure why the defined properties should be included in the copy() method.

Oh you're right it looks like that copy function can be removed entirely, as well. The default ShaderMaterial copy function will handle the uniform copying [here](https://github.com/mrdoob/three.js/blob/dev/src/materials/ShaderMaterial.js#L97). I'll remove it.

**Comment by gkjohnson** [comment]
Maybe an aside but at this point `Wireframe.js` and `WireframeGeometry2.js` seem entirely redundant to `LineSegments2.js` and `LineSegmentsGeometry.js`. How do you feel about removing them entirely? `Line2.js` doesn't seem to offer anything worthwhile at this point, either.

**Comment by WestLangley** [comment]
>`Line2.js` doesn't seem to offer anything worthwhile

So only fat line _segments_ would be supported -- not fat lines?

//

>`WireframeGeometry2.js` ... seems entirely redundant

`WireframeGeometry2` parallels `THREE.WireframeGeometry`.

```js
var geo = new THREE.IcosahedronBufferGeometry( 20, 1 );

var geometry = new WireframeGeometry2( geo );
```

You think it should be removed?

//

>Wireframe.js ... seems entirely redundant

```js
wireframe = new Wireframe( geometry, material );

wireframe.computeLineDistances();
```

Maybe `Wireframe` is not needed. It was proposed as perhaps a helpful API.

**Comment by gkjohnson** [comment]
Sorry you're right -- I see now that the constructor implementations are slightly different between the classes and not necessarily redundant (different default geometries). I initially thought they were identical.

The "computeLineDistances" _does_ look identical, though. Would it be preferable for `Wireframe` to inherit from `LineSegments2` instead of `Mesh`? As it is if a raycast function is added it will have to be duplicated between both class definitions, too. It was just something I noticed when looking over the files. In any case I think that can happen in another PR! I think this one is complete as it is.

> `WireframeGeometry2` parallels `THREE.WireframeGeometry`.

> It was proposed as perhaps a helpful API.

I think these are fine reasons to keep the classes. I thought that maybe they were just vestigial class definitions from when they had more unique functionality defined for each of them :)

**Comment by WestLangley** [comment]
@gkjohnson I trust you have fully tested these changes, so this PR is fine with me!

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
