### PR TITLE
ColladaLoader2: Update Examples

### PR DESCRIPTION
**Pull request by Mugen87**
`ColladaLoader2` is ready to be used in two examples. Besides, i've deleted the old Collada file in `webgl_loader_collada.html` (monster) and use now a visual more appealing model with multiple materials (good test case).

### CODE REVIEW

**Comment by mrdoob** [comment]
Yay! 🎉

**Comment by mrdoob** [comment]
Many thanks!

**Comment by WestLangley** [comment]
The ambient light is set way to high. You are rim-lighting the scene from the back. Do something like this:
```
var ambientLight = new THREE.AmbientLight( 0xffffff, 0.2 );
scene.add( ambientLight );

var directionalLight = new THREE.DirectionalLight( 0xffffff, 0.8 );
directionalLight.position.set( 1, 1, 0 );
scene.add( directionalLight );
```
Also, there are 12 identical materials in the model for some reason, and they all have the specular reflectance of the material too high. Consider reducing the values to between ( .05, .05, .05 ) and ( 0.1, 0.1, 0.1 ).

**Comment by Mugen87** [comment]
I've change the lights in the example, see #11660. And reducing the specular reflectance was also a good idea! 

But the `material` property of the mesh should actually have an array with only four materials.

**Comment by WestLangley** [comment]
Yes, 4 materials.

**Pull request merged**
