### PR TITLE
OrthographicTrackballControls -- Fixes zoom lock-up issue

### PR DESCRIPTION
**Pull request by mrz5018**
The zoom would lock up whenever the 'factor' became negative.  There was no way to reset the zoom start value, and so zooming would never work again (until the control is reset or reinitialized).

### CODE REVIEW

**Comment by mrdoob** [comment]
Is this code more robust?

https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TrackballControls.js#L216-L222

**Comment by mrz5018** [comment]
@mrdoob that definitely makes sense to me.  Looks cleaner.  I'll model this one after that.

**Comment by mrz5018** [comment]
@mrdoob is there anyway that this could sneak its way into r93?  I'm using the [three-full](https://github.com/Itee/three-full) project, and so it would be cool if this could get in earlier so it can trickle down a little more quickly.  Thanks!

**Comment by Mugen87** [comment]
`OrthographicTrackballControls` has been removed (see #17500). `TrackballControls` now supports  orthographic cameras. The issue should be fixed.

**Pull request closed without merging**
