### PR TITLE
Add frustum property to SelectionBox

### PR DESCRIPTION
**Pull request by seonglae**
**Description**

Unable to access frustum from SelectionBox is hard to utlize SelectionBox

Current SelectionBox only check center when select Object (probably for performance)

But I think there is need to use `frustum.intersectsObject()` or `frustum.containsPoint()` directly

So I added frustum to SelectionBox

### CODE REVIEW

**Comment by Mugen87** [comment]
> Unable to access frustum from SelectionBox is hard to utlize SelectionBox

Do you mind explaining in more detail? The property was not made public in the first place because it should not be relevant.

**Comment by sungle3737** [comment]
Currently, this [example](https://threejs.org/examples/?q=selec#misc_boxselection), selectbox only select object when intersect object's center because of `selectbox.select()`

But there is situation to use `frustum.intersectsObject` to select large object like this [another example](https://threejs.org/examples/?q=selec#misc_boxselection).

For fast solution, expose of frustum is increase usage of SelectionBox

**Comment by Mugen87** [comment]
I'm not sure I understand since you have linked to the same example twice.

**Comment by sungle3737** [comment]
Oh I edited second link

**Comment by Mugen87** [comment]
Although I think the selection of the second example feels weird, I have no objections no make the frustum property public if it helps your use case. But a better solution would be #20530.

**Comment by sungle3737** [comment]
OK, I agree that make frustum public is illegal. I'll try to add options to select function for more universal usage

**Pull request closed without merging**
