### PR TITLE
Fix Matrix3 Matrix4 getInverse throwOnDegenerate

### PR DESCRIPTION
**Pull request by milcktoast**
Having an assertion with literal Boolean `false` is causing this code branch to get stripped by the compiler.

### CODE REVIEW

**Comment by WestLangley** [comment]
Just to make sure, I was trying to figure out what the original intent was... Not sure, though: https://github.com/mrdoob/three.js/commit/f52aa6303dbe7dcfb0d52e513e195b9befd1d7f3

**Comment by bhouston** [comment]
This relies on the falsity of "undefined" but I am okay with it.

**Comment by mrdoob** [comment]
How about `throwOnDegenerate === true`?

**Comment by bhouston** [comment]
> How about throwOnDegenerate === true?

That sounds like a good idea.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
