### PR TITLE
Fix for #7260: PointLight shadows work properly only if shadow is applied to first light added to the scene.

### PR DESCRIPTION
**Pull request by mkkellogg**
Also refactored code in shadowmap_fragment.glsl

### CODE REVIEW

**Comment by mrdoob** [comment]
I think you can simplify the Gsd constants line this:

```glsl
const vec3 Gsd = vec3( -1, 0, 1);
```

And then do...

```glsl
bd3D + Gsd.zzz * os // instead of Gsd0
bd3D + Gsd.zxz * os // instead of Gsd1
bd3D + Gsd.xxz * os // instead of Gsd2
...
```

**Comment by mrdoob** [comment]
You can probably not even create the constant and keep `shadowmap_pars_fragment.glsl` tidier 😊

**Comment by mkkellogg** [comment]
> You can probably not even create the constant and keep shadowmap_pars_fragment.glsl tidier

I was actually thinking about doing that exact thing at one point :) I'll update the PR.

**Comment by mrdoob** [comment]
Hmm... with the code I posted you only need to define one single `vec3`, then you use `xyz`, `xxx`, ... combinations depending on the values you want.

**Comment by mrdoob** [comment]
I think this would be the equivalent:

```glsl
vec3 gsd = vec3( -1, 0, 1 );

adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zzz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zxz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xxz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xzz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zzx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zxx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xxx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xzx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zzy * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zxy * os, texelSizeY ) ), shadowBias[ i ], shadow );

adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xxy * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xzy * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zyz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xyz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.zyx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.xyx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.yzz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.yxz * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.yxx * os, texelSizeY ) ), shadowBias[ i ], shadow );
adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + gsd.yzx * os, texelSizeY ) ), shadowBias[ i ], shadow );
```

**Comment by mkkellogg** [comment]
> Hmm... with the code I posted you only need to define one single vec3, then you use xyz, xxx, ... combinations depending on the values you want.

Ah, sorry, I thought you wanted to get rid of ```gsd``` altogether and put the literals directly into the code. I double checked your code and it works fine. I will update the PR.

**Comment by tschw** [comment]
Better yet:
```glsl
const vec3 Gsd = vec3( -1, 0, 1 );
```
:-)

**Comment by WestLangley** [comment]
Even better yet:
```glsl
const vec3 Gsd = vec3( - 1, 0, 1 );
```
: - )

**Comment by mrdoob** [comment]
😅

**Comment by mkkellogg** [comment]
> Even better yet:

>> const vec3 Gsd = vec3( - 1, 0, 1 );

Done :)

**Comment by tschw** [comment]
@WestLangley 
Because the GLSL ES 1 syntax (as found in the [spec](https://www.khronos.org/registry/gles/specs/2.0/GLSL_ES_Specification_1.0.17.pdf)) does not know signed numerals - only unary operators? Oh my... :-) Isn't that a bit über bureaucratic?

**Comment by mrdoob** [comment]
Pheww! That took a while... Thanks for the patience guys!

**Comment by mrdoob** [comment]
Just one question that seems like I missed. How come did you guys moved from cubetexture to single texture? Aren't we losing possible resolution because of that?

**Comment by WestLangley** [comment]
@tschw Whoa!.... We have not yet specified a coding style for GLSL, so I proposed a pattern consistent with mrdoobapproves that also incorporates your suggestion of capitalizing constants.

**Comment by tschw** [comment]
> Just one question that seems like I missed. How come did you guys moved from cubetexture to single texture? 

Problem with using cube samplers is:
```glsl
uniform samplerCube pointShadowMaps[ N_SHADOWING_LIGHTS ];
uniform sampler2D shadowMaps[ N_SHADOWING_LIGHTS ]; 

// [ ... code that conditionally subscripts one of these arrays with a loop
//   index, where the condition depends on what another uniform says ... ]
```

In this case, although only half of the sampler array elements are actually used, they are *statically referenced*, IOW the uniforms are *active* because it's impossible to knock them out at link time and thus count against the `MAX_TEXTURE_IMAGE_UNITS` limit.

> Aren't we losing possible resolution because of that?

According to [webglstats](http://webglstats.com/), not really. Cube texture critical limits are pretty much one fourth of the non-cube texture limits. The 2D texture has a 2:1 aspect, using six of 4x2 = eight square tiles, utilizing 75% of the allocated memory, so we're losing 25% of it. That seemed to be the lesser evil compared to the other options, such as allocating twice the number of samplers, bumping fragment shader uniform count, or extra rendering passes.
Note that the 2D textures  have proper square texels so there's no extra distortion over that from the cube projection itself. The latter is of course also present with a cube sampler. Similarly, we don't filter correctly over the seams, and neither do WebGL cube samplers.

**Comment by tschw** [comment]
@WestLangley 

Never used mrdoobapproves, but I read [Mr.doob's Code Style™](https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2).

It states that
> All unary operators are written together with the following operands:

although shows an example that does otherwise, underneath. 

Also, in languages other than GLSL, negative numerals *do* exist. So `-1` may in fact be a single token and not an unsigned numeral prefixed with an unary operator.

**Comment by mrdoob** [comment]
@tschw thanks for the explanation!

Again, nicely done guys! 😊

**Pull request merged**
