### PR TITLE
[Very WIP] Rework how WebGL NodeMaterials are built

### PR DESCRIPTION
**Pull request by LeviPesin**
Related issue: https://github.com/mrdoob/three.js/pull/23797

**Description**

This PR reworks how WebGL NodeMaterials are built.

@sunag Why function WebGLNodeBuilder._updateUniforms() is needed? Can it be removed?

### CODE REVIEW

**Comment by sunag** [comment]
> @sunag Why function WebGLNodeBuilder._updateUniforms() is needed? Can it be removed?

I would have to test it again in this context, it was used to update default uniforms values. 

I think that this approach (build the shader from "zero") is not appropriate for `WebGLRenderer` at this moment, this will kill all native resources of it this way. That could certainly be done in a moment, but I think it's too early for that.

**Comment by LeviPesin** [comment]
> I think that this approach (build the shader from "zero") is not appropriate for WebGLRenderer at this moment, this will kill all native resources. That could certainly be done in a moment, but I think it's too early for that.

Then I suggest that I will try now to make this PR support lighting and fog, and when the NodeMaterial.build() would be at a stage comparable to the three.js' native, I will un-draft this PR.

**Comment by LeviPesin** [comment]
@sunag Can we actually do something like this PR tried for the WebGLBackend? So that we can remove reliance on ShaderLib from it and at some time in the future when Renderer and Nodes system are added to the core remove ShaderLib entirely.

**Comment by LeviPesin** [comment]
Closing because there exists the `renderers/webgl/nodes/GLSLNodeBuilder.js` now (of which existence I forgot when writing the previous comment 😅).

**Pull request closed without merging**
