### PR TITLE
cubemap background Increase blur level

### PR DESCRIPTION
**Pull request by gameatp**

### CODE REVIEW

**Comment by WestLangley** [comment]
Related #18241.

**Comment by Mugen87** [comment]
Closing for now until it's clear in #18241 what API is preferred.

**Comment by WestLangley** [comment]
Reopening. This will not be considered as an option if it is closed.

@gameatp Thank you for your suggestion!

**Comment by Mugen87** [comment]
But the implementation in #18241 is almost identical?

**Comment by WestLangley** [comment]
@Mugen87 As you wish...

**Pull request closed without merging**
