### PR TITLE
add toString to Vector3 prototype

### PR DESCRIPTION
**Pull request by zhihuidev**
I found this can be useful when we need to set a Vector3 as an Object key. Especially when we want to eliminate vertices which share same positions in bufferGeometry.

### CODE REVIEW

**Comment by mrdoob** [comment]
> I found this can be useful when we need to set a Vector3 as an Object key. Especially when we want to eliminate vertices which share same positions in bufferGeometry.

Can you share code examples so we understand the use cases better?

**Comment by huiwzh** [comment]
```
let attribute = geometry.attributes.position
if ( attribute !== undefined ) {
    let v = new THREE.Vector3()
    let vertices = []
    let obj = {}
    for ( i = 0, l = attribute.count; i < l; i ++ ) {
	v.fromBufferAttribute( attribute, i )

	// remove vertices with the same position
        // only store unique position vertices
	if (!obj[v]) {
            vertices.push(v.clone())
            obj[v] = true
         }
   }
```

my use case is need to extract a collection with unique position vertices from bufferGeometry, so if we could set the position vector3 as a key of object then we don't have to manually cast the vector3 to string before setting the `obj[v]`. Currently when we do `obj[v]`, it will store the key as `[object Object]`.

**Comment by mrdoob** [comment]
Would `v.toArray().toString()` work?

**Comment by huiwzh** [comment]
`v.toArray().toString()` and `v.toArray()` both work when set them as object key - I just concern a little with performance and the usage convenient. 

Since  `v.toArray()` need to construct a new `Array` object each time, and I think If we override the `Object.prototype.toString()` method in `Vector3`, it will be more intuitive.

**Comment by mrdoob** [comment]
I see...

We do not support template literals in `src/` yet thought, so the could would need to be:

```js
return '{x: ' + this.x + ', y: ' + this.y + ', z: ' + this.z + '}';
```

Also, if we add this, we should probably add it to all the objects in `src/math`.

**Comment by WestLangley** [comment]
> I just concern a little with performance

How many times per second are you calling this method?

**Comment by huiwzh** [comment]
> I see...
> 
> We do not support template literals in `src/` yet thought, so the could would need to be:
> 
> ```js
> return '{x: ' + this.x + ', y: ' + this.y + ', z: ' + this.z + '}';
> ```
> 
> Also, if we add this, we should probably add it to all the files in `src/math`.

That's a good idea - if we decide to do these changes, I would like to keep working on the other files in the `src/math`.

**Comment by WestLangley** [comment]
This seems like an app-specific method to me. I also expect formatting would be required.

>return '{x: ' + this.x + ', y: ' + this.y + ', z: ' + this.z + '}';

"{x: 14.999999999999998, y: 20, z: 29.999999999999996}"

What is the point of defining the method if it is going to be overridden anyway?

**Comment by mrdoob** [comment]
> This seems like an app-specific method to me. 

I kind of feels the same to me, but I was curious to explore the options.

> What is the point of defining the method if it is going to be overridden anyway?

What do you mean?

**Comment by WestLangley** [comment]
I think users will want to redefine the method with custom formatting -- or write their own function. So what is the point in adding the method at all?

**Comment by mrdoob** [comment]
I see I see.

**Comment by mrdoob** [comment]
@huiwzh Actually, how about `JSON.stringify( v )`?

**Comment by huiwzh** [comment]
> @huiwzh Actually, how about `JSON.stringify( v )`?

`JSON.stringify( v )` will deliver similar result with `return '{x: ' + this.x + ', y: ' + this.y + ', z: ' + this.z + '}'`. It just depends on whether we are going to put this kind of `stringify` method into the `Vector3.prototype.toString` or not. I think we may benefit from having a native overridden `toString` method for some possible usage.

**Comment by mrdoob** [comment]
>  I think we may benefit from having a native overridden toString method for some possible usage.

We can't just add code "just in case". Code has bugs and needs to be maintained. We need good reasons to add code. But sounds like `JSON.stringify()` solves your use case?

**Comment by mrdoob** [comment]
Closing until we find a compeling reason to add this.

**Pull request closed without merging**
