### PR TITLE
WebGLProgram: Refactor GLSL conversion.

### PR DESCRIPTION
**Pull request by Mugen87**
see https://github.com/mrdoob/three.js/pull/20005#issuecomment-674378445

### CODE REVIEW

**Comment by Mugen87** [comment]
Let me check the result of the E2E tests...

**Comment by Mugen87** [comment]
Okay, this looks good now!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Updated the migration guide to explain the `ShaderMaterial.glslVersion` property:

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r119--r120

**Pull request merged**
