### PR TITLE
Set path to web-ifc.wasm in editor's IFCLoader

### PR DESCRIPTION
**Pull request by xawill**
Related issue: #21988

**Description**

See related issue.

@agviegas and I are pretty confident that this fixes the issue, but we don't know how to test it.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Actually, the path was not quite right: https://github.com/mrdoob/three.js/commit/2272eaecf181ab2486392a4cb8e7f77b8cab72ad

**Comment by mrdoob** [comment]
I've cherry-picked the change into the `gh-pages` branch and https://threejs.org/editor/ loads `ifc` files again 👍

**Comment by xawill** [comment]
Ah, ok, sorry about that. Thanks a lot for checking and releasing that fast! This will definitely help me with debugging.

**Pull request merged**
