### PR TITLE
MaterialX: Add basic support for `time` and `frame`

### LINKED ISSUE #28985: MaterialXLoader: "time" and "frame" MaterialX nodes not loaded
### Description

Seems [the time and frame application nodes](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/Specification/MaterialX.Specification.md#application-nodes) from MaterialX are already supported as nodes, but not processed by MaterialXLoader.

Related to https://github.com/mrdoob/three.js/pull/24680

### Reproduction steps

1. Load this file with MaterialXLoader: https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/resources/Materials/TestSuite/stdlib/application/time_frame.mtlx
2. It contains two materials, one for "time" and one for "frame"
3. Note that "time" node and "frame" node are not supported

image

### Code

I tried to fix it with

```js
	// << Application >>
	new MXElement( 'time', timerLocal, [ 'timeScale' ] ),
	// new MXElement( 'frame', ... ),
```

in `MaterialXLoader.js`, but then I get a shader error, so that doesn't seem to be the right approach. cc @sunag

### Live example

-

### Screenshots

_No response_

### Version

r167

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Closes https://github.com/mrdoob/three.js/issues/28985

### CODE REVIEW

**Comment by sunag** [comment]
The `fps` parameter in `time` is ignored for now.

**Comment by hybridherbst** [comment]
Thanks!
That’s fine — the fps parameter was removed in MaterialX 1.39 anyways.

**Comment by hybridherbst** [comment]
Hi @sunag, do you happen to have a testcase online where this works?

I'm still getting errors, presumably because "in" is a reserved word:

image

Any ideas?

**Comment by sunag** [comment]
> I'm still getting errors with the file I had attached to the original issue, presumably because "in" is a reserved word:

This looks like an old issue, are you using `WebGLRenderer`?

**Pull request merged**
